### ISSUE TITLE
Is there anyway to get some bayesian graph manipulation tools like moralizing and triangulating?

### ISSUE THREAD

**Issue by mb3152** [networkx/networkx#1012]
I have been wrapping old matlab code, but networkx stuff would be great!

**Comment by hagberg** [comment]
Closed due to inactivity.

**Comment by chebee7i** [comment]
Good move. Also, at this point there is a mature package dedicated to this: https://github.com/pgmpy/pgmpy

If interest in this picks up again, I suspect conversions between the two libraries would be a good option instead of an all-out implementation.
