### ISSUE TITLE
wishlist: girth of a graph

### ISSUE THREAD

**Issue by argriffing** [networkx/networkx#1030]
The [girth](http://en.wikipedia.org/wiki/Girth_%28graph_theory%29) of a graph is the length of a shortest cycle contained in the graph.  I was looking for this when I was trying to implement a densest k-subgraph algorithm restricted to a certain class of sparse graphs.

**Comment by hector1618** [comment]
If we decided to implement the algorithm by @nadesai ( O(VE) algorithm) then what is the ideal place(file) to write the function?

**Comment by arpitdm** [comment]
Hello,
Is this issue still open? If so, I would like to work on it. I've forked the repo and gotten NetworkX setup on my system. What's the first thing I should do?
-Arpit.

**Comment by hagberg** [comment]
Closed due to inactivity.
