### ISSUE TITLE
Cycle space algorithms

### ISSUE THREAD

**Issue by kakila** [networkx/networkx#1046]
Hi,

Some time I wrote some functions that are useful to derive Kirchhof laws from given graphs. I followed the algorithm in Modern Graph theory by Bollobás.

I would like to receive comment on how to improve them to match the level and quality of current algorithms in networkx.

The file can be found here
https://github.com/kakila/cycle_space

**Comment by dschult** [comment]
This moved from #1067 to #1538 to #2069 which is scheduled for NetworkX 2.1 So I'm changing this to NetworkX 2.1 as well. (Also, there are some other cycle based issues on the 2.0 list.)

**Comment by dschult** [comment]
See #2069
