### ISSUE TITLE
wishlist: make chordal graph

### ISSUE THREAD

**Issue by mb3152** [networkx/networkx#1054]
A function to add edges to make a graph chordal would be great.

**Comment by jfinkels** [comment]
The Matlab code to which @mb3152 refers is at https://github.com/bayesnet/bnt/blob/master/graph/triangulate.m.

[Here][1] is a paper that provides an algorithm for computing a minimal triangulation of a graph.

[1]: http://dx.doi.org/10.1016/j.tcs.2009.10.004

**Comment by MridulS** [comment]
@jfinkels Are you working on this?

**Comment by chebee7i** [comment]
There might be some code for this already. I know I wrote some moralization code at some point...probably as a gist.

**Comment by mb3152** [comment]
Did you profile it? Making large graphs chordal can be rather computationally intensive. Also, many algorithms just try to get close to a chordal graph, or "overfill" the graph, as there is no single best solution. Perhaps an implementation for which the user can set how "perfect" or complete the triangulation is, is the best first step. This could be qualified by how many times nx.is_chordal is ran and how many edges are added in relation to how many edges/nodes the graph has.

Maxwell Bertolero

**Comment by jfinkels** [comment]
@MridulS Not immediately. Seems like it would be easy to get *an* implementation, hard to get a *fast* implementation. Feel free to do it.

**Comment by mb3152** [comment]
A version is available on C as well...

https://github.com/bayesnet/bnt/blob/d905c537b8003ab1453a5617a1ad0d83b4de886b/graph/triangulate.c

**Comment by mb3152** [comment]
Here is a reasonable python / networkx version as well...

https://github.com/opencog/opencog/blob/3ce377ceb74b28d7dbf40f48af6716eaebb298d5/opencog/python/learning/incremental_learner/IncrementaLearner_Mcs.py

**Comment by mb3152** [comment]
and this has a nice heuristic for ordering the nodes... 

https://github.com/JohnReid/infpy/blob/c92069325418ac46ede92f13499f0b312c42fd74/python/infpy/variational/message_passing/svmp.py

**Comment by julien-klaus** [comment]
I have written an algorithm to calculate the chordal enhancement of a graph. May you can have a review. I used the MCS-M algorithm which is one of the fastest algorithms.
