### ISSUE TITLE
Add method to contract edges

### ISSUE THREAD

**Issue by rburing** [networkx/networkx#1057]
It would be nice to be able to do [edge contraction](http://en.wikipedia.org/wiki/Edge_contraction) out of the box. The following gist I found implements this: https://gist.github.com/aanastasiou/7639465

**Comment by johnyf** [comment]
Relevant: I happened to implement [edge contraction](https://github.com/johnyf/promela/blob/34f7d3fb5a1d609e260f26eedb187ea45df4acb4/promela/ast.py#L111) for `MultiDiGraph` during manipulation of program graphs in a parser.

**Comment by hagberg** [comment]
Are we done here?

**Comment by jfinkels** [comment]
I believe so; fixed by pull request #1439.
