### ISSUE TITLE
matrix graphs

### ISSUE THREAD

**Issue by Midnighter** [networkx/networkx#1076]
Dear all,

As a side note, when I talk about a graph here I mean `Graph`, `DiGraph`, `MultiGraph` and `MultiDiGraph`.

I want to start a discussion here about the use for dense and sparse matrix based graph classes. The reasoning for that is recent work by @FedericoV on directed clustering and my own need for a sparse matrix representation. So far the linear algebra based functions each convert a graph instance into a desired matrix. Chances are high, though, that if I want to work with one of those functions, I will use others as well and it'd be more convenient/consistent to have one matrix based graph to pass to each of them.

We've talked about designing different specialized graph classes in #980 and I would like design dense and sparse matrix based graph families. Using `numpy` and `scipy` seems obvious here since we can leverage, for example, the [csgraph](http://docs.scipy.org/doc/scipy/reference/sparse.csgraph.html) and we can also have a look at [APGL](http://pythonhosted.org/apgl/index.html) (although I think not all of its code is correct). My goal would be to have classes that _feel_ almost like the normal classes and matrix based functions that follow the same naming convention and, hopefully, parameters, as the in the standard `networkx` package.

My main question is whether these classes should live inside `networkx`, be an off-shoot like the scikits-... or an entirely separate package.

Cheers

**Comment by rashoodkhan** [comment]
@Midnighter - I like your idea of providing an alternative implementation of Graph in a turbo package as mentioned above. This will ensure that networkx provides performance in terms of time/space complexities. As there is a parallel project on moving to new API and once the API design is finalized, the new classes and methods can be implemented using the new API.

Correct me if wrong, all the algorithm implementations rely on the existing API for the graph, so to make the existing algorithms compatible with the newly developed implementation two things could be done:
1. Provide helper functions to convert back to compatible data format (i.e dicts)
2. Update the existing algorithms to use suitable back end graph classes (possibly by checking the type of graph initiated).

**Comment by Midnighter** [comment]
> Correct me if wrong, all the algorithm implementations rely on the existing API for the graph, so to make the existing algorithms compatible with the newly developed implementation two things could be done:
1. Provide helper functions to convert back to compatible data format (i.e dicts)
2. Update the existing algorithms to use suitable back end graph classes (possibly by checking the type of graph initiated).

1. My idea was to provide `dict` like interfaces (cf. [emulating container types](https://docs.python.org/2/reference/datamodel.html#emulating-container-types)) where feasible. @hagberg has some prototype code that can serve as a starting point.
2. We've had quite a few discussions and certainly will have more discussions in the future (with the 2.0 API changes) about what the graph interface actually is. It is true that current code makes heavy use of the dict-of-dict structure and @dschult once asserted that this is actually part of the current graph interface. The new API and thoughts about other backends may yield a definitive set of methods that algorithms have to use. Much of the codebase would have to be adapted but then other graph classes can be drop-in replacements.

Overall, the appeal of a matrix class to me is not as an alternative storage solution (the dict-of-dict is actually quite good and very convenient) but to make use of algebraic solutions to graph problems. So at this point I am more concerned with implementing those algorithms where algebraic solutions exist efficiently rather than making the matrix classes work with every networkx function. However, if the 2.0 API makes this feasible, it should definitely be pursued.

**Comment by rashoodkhan** [comment]
> Overall, the appeal of a matrix class to me is not as an alternative storage solution (the dict-of-dict is
> actually quite good and very convenient) but to make use of algebraic solutions to graph problems. So > at this point I am more concerned with implementing those algorithms where algebraic solutions exist > efficiently rather than making the matrix classes work with every networkx function. However, if the 2.0 > API makes this feasible, it should definitely be pursued.

It now makes sense from the project description. I had doubts that once the new implementation is done, then the existing graph implementation will become obsolete which is cleared now. Do you have any specific algorithms to be implemented with the new implementation? 

Also, I want to read up more on Linear Algebra for Graphs - what would you suggest to look at? One resource I found was on the GraphBLAS homepage which is the book Graph Algorithms in the language of Linear Algebra.

**Comment by chebee7i** [comment]
If you haven't already, you also will need to familiarize yourself with the various sparse representations. See `scipy.sparse` and `scipy.sparse.csgraph`

**Comment by Midnighter** [comment]
@rashoodkhan I haven't yet compiled a list of algorithms and resources but it's a logical and necessary next step.

**Comment by rashoodkhan** [comment]
@Midnighter Making a Wiki page on Github will be nice which collects all the algorithms and resources links!

@chebee7i - I have studied about sparse representation in my algorithms course, but will need to brush up on the concepts. I will have a look at ```scipy.sparse``` and ```scipy.sparse.csgraph```

**Comment by rashoodkhan** [comment]
I went through the [code](https://github.com/hagberg/networkx/commit/b6e18655f51104c06251558890e88a9dee189d4d) by @hagberg and as mentioned it can be a good starting point for the project. I have started to work on the GSoC proposal for this project, it would be nice if we can compile the list of algorithms. Once the list is ready, depending on the complexity of each algorithm, I can make up the project timeline @Midnighter.

**Comment by zjpjack** [comment]
I have a question that why we need separate classes for sparse graph and dense graph. If we use matrix for sparse graph and dense graph, we have the same space complexity for both class, and linear algebra graph algorithms for both graphs have the same time complexity (but actually maybe dense graph can have higher performance because it can take advantage of bandwidth or cache). For example, we also can use csgraph BFS for dense graph even though it is for sparse graph, right?

**Comment by MridulS** [comment]
@zjpjack Dense matrices store every entry in the matrix. Sparse matrices only store the nonzero entries. Sparse matrices don't have a lot of extra features, and some algorithms may not work for them. You use them when you need to work with matrices that would be too big for the computer to handle them, but they are mostly zero, so they compress easily.

**Comment by zjpjack** [comment]
@MridulS Thanks for your answering. Of course we can store sparse graph in compressed. If we only store nonzero entries of sparse matrix, like CSR (Compressed Sparse Row) format, is it still called matrix? Because we only need three arrays for storage(val, row_pointer and column index). Besides, based on this, how can we do a linear algebra graph algorithm with CSR format? Or we just implement graph algorithm based on CSR format for sparse matrix, not a linear algebra graph for sparse graph?

**Comment by hagberg** [comment]
Closed due to inactivity.
