### ISSUE TITLE
Better shortest paths for Multigraphs...

### ISSUE THREAD

**Issue by chebee7i** [networkx/networkx#1120]
Most (all?) of the shortest path algorithms do not give sufficient information for multigraphs.  In those situations, knowing the source and target is not enough---one must also know the key of the edge.  These algorithms touch _everything_ though. So I'm not sure it's wise to change them. Perhaps though, we can offer more general implementations and then have the existing implementations use them to create the outputs?

Also, its often that case that one is interested in the edges of the shortest path. In situations like these, it might even be simpler to get output of the form:  [(u,v,key,weight),...].  Without the weight, you'd have to query the graph again.

Obviously, we can't cater to every possible output format, but I think the issue with multigraphs is serious enough that we should do something. For the various outputs, perhaps we can provide some helper functions for typical cases.

Thoughts on this?

**Comment by dschult** [comment]
This Issue discusses shortest paths for Multigraphs. The question is whether the shortest_path routines should return something like [(u, v, key, weight), ...] for each edge in the path. 

My impression is that shortest_path for most multigraph problems would use the edge with minimum weight between two nodes. Can we write a wrapper for the output that moves along the found shortest path and adds keys and weights after-the-fact? For that matter, wouldn't it be possible to shrink the multigraph to a graph by only keeping minimal edges between each pair of connected nodes?  Maybe I don't understand the use-case for multigraphs and shortest path.

**Comment by chebee7i** [comment]
A pre-processing step that keeps only minimal edges could work: parse the existing graph, construct a new graph with the same edge keys, and then run shortest path on that reduced graph. An after-the-fact solution could work too.

Aesthetically though, both of those solutions seem a bit awkward. The shortest path algorithms are well-defined on multigraphs and the lack of a key seems more like an oversight.

Suppose after the wrapper was created, I then find that I'm interested in *all* shortest paths on a multigraph. With the pre- and post-processing solutions, we now have to write additional code that will make sure to visit all edges between A and B that have the same weight (or we have to extend the wrapper to cover this new use case). This begs the question: in what other ways might we have to extend the wrapper for other algorithms that *should* be returning a complete specification of the edge in the first place.

At the time, I was running into multiple issues in the codebase where algorithms were, at the conceptual level, operating on or returning edges---and I wanted a better API to support writing edge-based algorithms that was the same across the base classes.  One way to do that would be that every edge has a unique key and you iterate over and return edge keys. The situation now is that we use the (tail, head) to represent the edge and then sometimes we have to include the key.  Only we don't this uniformly, such as with the shortest path algorithms.

[The arborescence code has a lot of ugliness, for example `MultiDiGraph_EdgeKey`, that I had to create just to do Edmonds algorithm.  Similarly, the `edge_dfs` function was another attempt to expand the codebase in a way that was more friendly to multigraphs and edge-based algorithms. I'm not a fan of its varying output format and would have preferred to a unique ID for the edges. My feeling was that these sorts of changes were flirting with redesigning how the base classes worked and that, understandably, put enough headwind on it that it stalled.]

**Comment by chebee7i** [comment]
All that said, I'd say that multigraph traversals like what I was working on are a bit of niche use case, and there doesn't seem to be a lot of user requests for this. So perhaps the best course would be to close this issue for now until someone really needs it.

**Comment by brooksandrew** [comment]
+1 for this.  This would simplify the Rural and Chinese Postman solver I'm working on.  From the user perspective, it seems natural that`shortest_path` would return the corresponding key on MultiGraph since presumably this information is considered in the computation.

**Comment by fsquillace** [comment]
+1
