### ISSUE TITLE
a kind of "patched" subgraph

### ISSUE THREAD

**Issue by argriffing** [networkx/networkx#1151]
I am interested in an operation that returns an induced subgraph of an undirected unweighted graph and "patches over" the removed vertices by adding some edges between some remaining vertices.  In particular, if vertices s and t are not removed, and if there is a path between vertices s and t in the original graph that contains only s and t and removed vertices, then the "patched" subgraph will contain the edge (s, t).

Maybe this operation has a name in graph theory, but I don't know what it is.  It has some applications to electrical network analysis and probably elsewhere in graph theory, so if this is in scope for networkx and is not already available under a name that I could not find, then I could contribute an implementation.

**Comment by jfinkels** [comment]
(I skimmed this discussion.) I added functions for computing graph minors (node and edge contraction functions), as well as a more general function for computing quotient graphs, in `networkx.algorithms.minors`. Does that help?
