### ISSUE TITLE
Structure-only copy/to_directed/to_undirected

### ISSUE THREAD

**Issue by ysitu** [networkx/networkx#1152]
(From #1126)

`copy`/`to_directed`/`to_undirected` should allow copying only the graph structure instead of deepcopying everything because the user can attach data of unknown size or copyability to the graph. Deepcopying such data may not be appropriate.

**Comment by dschult** [comment]
Revisit in light of #1876

**Comment by dschult** [comment]
I'm going to close this and refer to #1164 for this feature.
