### ISSUE TITLE
Benchmarks via vbench?

### ISSUE THREAD

**Issue by chebee7i** [networkx/networkx#1154]
Is there any interest in benchmarking performance, perhaps through something like `vbench`: 

1. http://wesmckinney.com/blog/?p=373.  
2. https://github.com/pydata/vbench

It might be nice, but I definitely can't commit to this right now.  When we make changes to the base classes or to algorithms that touch a lot other code (e.g. copy or subgraph or shortest_path), I can see how this might be helpful.

**Comment by hagberg** [comment]
Addressed in #1313
