### ISSUE TITLE
shortest paths for DAGs

### ISSUE THREAD

**Issue by chebee7i** [networkx/networkx#1161]
As was pointed out in https://github.com/networkx/networkx/pull/1118#issuecomment-41171119, the algorithm for shortest paths on DAGs is straightforward, but DAGs seem common/important enough to warrant official support. The main difference would be in the single-source or single-target portions of the code to achieve the O(V + E) running time. They could be implemented in `networkx/algorithms/shortest_path/dag.py` but exposed at `networkx.dag.shortest_path`, etc.  This would also complement other DAG algorithms like `longest_path` (#847).

What are general thoughts on this?

Aside: I still wish there was a better interface for the shortest_path code, see https://github.com/networkx/networkx/pull/762#issuecomment-8405360.  That situation makes me hesitant to (essentially) duplicate the code in `networkx/algorithms/shortest_path/generic.py`.

**Comment by edouardklein** [comment]
Just chiming in to say that I was hurt by this as well. The documentation does not explicitly state that shortest_path does not work on DAGs, the function does not check that the passed graph is a DAG, and so sometimes it works, sometimes it does not.

**Comment by dschult** [comment]
shortest_path should work on DAGs. This issue only talks about making it more efficient for DAGs.

**Comment by hagberg** [comment]
I suggest we close (until we have a dags class or something where we can easily check for dags).  Consider putting https://github.com/networkx/networkx/pull/1118#issuecomment-41171119 into topological sort.
