### ISSUE TITLE
Graph partitioning with METIS

### ISSUE THREAD

**Issue by ysitu** [networkx/networkx#1167]
I wonder if there is interest in integrating [METIS](http://glaros.dtc.umn.edu/gkhome/metis/metis/overview) and the how if so.

**Comment by OrkoHunter** [comment]
Hi,
This idea seems great to me! I would like to work on it.

**Comment by OrkoHunter** [comment]
In the project, Metis seems to be very recommended. I would like to know whether we are planning to add Boost Graph and Lemon both or just one of them? Please tell. That will confine my area of interest.

**Comment by ysitu** [comment]
@OrkoHunter AFAIK, your proposal is to work on an add-on system instead of merely integrating METIS. Then the important part is the add-on system itself. This can be nontrivial. Requiring inclusion of at least two add-ons aims to show three things: 1) that your add-on system works; 2) that your system is general-purpose, not tailored to just one use case; 3) how others can create add-ons using your system.

**Comment by OrkoHunter** [comment]
@ysitu @hagberg @chebee7i @jtorrents 
For a while, I've been working on my proposal. Now I think it's ready for a review. :) 
Please have a look and give suggestions.

https://github.com/networkx/networkx/wiki/GSoC-2015-Application-Himanshu-Mishra-:-Add-On-System-for-Networkx

I still have to work on the prototype.

**Comment by ysitu** [comment]
I am preparing an initial review.

**Comment by OrkoHunter** [comment]
@ysitu Thanks!

**Comment by MridulS** [comment]
I think this can be closed now.
