### ISSUE TITLE
MixedGraph and MixedMultiGraph

### ISSUE THREAD

**Issue by chebee7i** [networkx/networkx#1168]
I don't have time now, but over the summer I might look into implementing some basic mixed-type graph classes.  Right now, we have graph classes that require all edges to be of the same type---all undirected, or all directed.  This is, by far, the most common use case.

We've also had a few requests to be able to create mixed graph types.  The normal response we give is to create two graphs and analyze them separately, but this is quite awkward in a number of important cases. Specifically, I have in mind Bayesian networks.  If implemented, these would be `MixedGraph` instances whose total set of edges (directed and undirected) have no loops. There are a number of algorithms in this area that require one to traverse the graph while ignoring the direction of the edge, or in other cases, while allowing an undirected edge to be traversed in either directed manner. Generally, the undirected edges mean that the direction is unspecified, but you can't just toss in two directed edges b/c this would affect path algorithms---between any two nodes we are required there there be, at most, only one edge (hence MixedGraph and not MixedMultiGraph).

Now maybe this will end up being too specific for NetworkX, but I'm curious to see if we can come up with something nice.  Even if it ultimately just has:  `self.pred, self.succ` for directed edges and `self.adj` for undirected edges, that's probably better than two graphs---but you can already see why this will be difficult to work with since almost every algorithm we have in NetworkX treats succ and adj as the "same" (just with different interpretations).  I'm reminded of how [sparse.csgraph](http://docs.scipy.org/doc/scipy/reference/sparse.csgraph.html#directed-vs-undirected) is quite flexible here, allowing algorithms to work with a directed graph in an undirected fashion, if requested.  More of this in NetworkX would probably be helpful for mixed graphs.

**Comment by MridulS** [comment]
I have added this to https://github.com/networkx/networkx/wiki/NetworkX-2.0-API-~-DRAFT . I think this is a good time to discuss this further.

**Comment by chebee7i** [comment]
Just a quick note, making `self.adj` look into both `self.succ` and `self.pred` would be a technique for traversing directed edges in an undirected manner. This is a technique that works for pure directed graphs, and strictly speaking, it is not sufficient if you want a graph with both directed and undirected edges. 

The idea is that `self.adj` would contain a disjoint set of edges from those contained in `self.succ` and `self.pred`. For example, `G.degree(A)` would tell us the degree of A by looking only at undirected edges, while `G.out_degree(A)` would give the out degree from A while looking only at directed edges.  This isn't the only way to implement `G.out_degree`. We might also want to provide a parameter that will treat any undirected edge with A as an outgoing edge. This would modify it's outdegree.

**Comment by MridulS** [comment]
@chebee7i like you initially suggested we should keep `self.adj` and `self.succ` different. And yes this will create a lot chaos for algorithms (as they wont work for mixedgraph). So this is many naive attempt at this.
```python
def add_undirected_edges():
# Follow the graph class add_edge()
def add_directed_edges():
# Follow the digraph class add_edge() with self.succ different from sel.adj
def degree():
# give the degree by looking at self.adj
def out_degree()/in_degree():
# give the degree by looking at self.pred and self.succ
```

**Comment by MridulS** [comment]
Okay I aslo have a-not-so-great idea. I was going through [Voltage Graphs](https://en.wikipedia.org/wiki/Voltage_graph) and found the concept of "darts". They are basically a cartesian product between the sets of arcs and (+1, -1) [note](http://courses.csail.mit.edu/6.889/fall11/lectures/L02.pdf). Should we discuss this kind of implementation where we add new a characteristic for edges/arcs.

**Comment by MridulS** [comment]
This is some skeleton code for mixedgraph class
``` python
import networkx as nx
from networkx.classes.graph import Graph
from networkx.classes.digraph import DiGraph

class MixedGraph(Graph):
	node_dict_factory = dict
	adjlist_dict_factory = dict
	edge_attr_dict_factory = dict
	def __init__(self):

		self.node_dict_factory = ndf = self.node_dict_factory
		self.adjlist_dict_factory = self.adjlist_dict_factory
		self.edge_attr_dict_factory = self.edge_attr_dict_factory
		self.graph = {}
		self.node = ndf()
		self.adj = ndf()
		self.pred = ndf()
		self.succ = ndf()
		self.edge=self.adj

	def add_node(self, n):
		if n not in self.node:
			self.adj[n] = self.adjlist_dict_factory()
			self.node[n] = attr_dict

	def add_undirected_edge(self, u, v, attr_dict=None, **attr):
		if attr_dict is None:
			attr_dict=attr
		if u not in self.adj:
			self.adj[u] = self.adjlist_dict_factory()
			self.node[u] = {}
		if v not in self.adj:
			self.adj[v] = self.adjlist_dict_factory()
			self.node[v] = {}
		datadict = self.adj[u].get(v, self.edge_attr_dict_factory())
		datadict.update(attr_dict)
		self.adj[u][v] = datadict
		self.adj[v][u] = datadict

	def add_directed_edge(self, u, v, attr_dict=None, **attr):
		if attr_dict is None:
			attr_dict=attr
		if u not in self.succ:
			self.succ[u]= self.adjlist_dict_factory()
			self.pred[u]= self.adjlist_dict_factory()
			self.node[u] = {}
		if v not in self.succ:
			self.succ[v]= self.adjlist_dict_factory()
			self.pred[v]= self.adjlist_dict_factory()
			self.node[v] = {}
		datadict=self.succ[u].get(v,self.edge_attr_dict_factory())
		datadict.update(attr_dict)
		self.succ[u][v]=datadict
		self.pred[v][u]=datadict


```

With the output being something like this
``` python
In [1]: import networkx as nx

In [2]: G = nx.MixedGraph()

In [3]: G.add_undirected_edge(1, 2)

In [4]: G.add_directed_edge(1, 2)

In [5]: G.add_directed_edge(3, 4)

In [6]: G.add_undirected_edge(2, 3)

In [7]: G.adj
Out[7]: {1: {2: {}}, 2: {1: {}, 3: {}}, 3: {2: {}}}

In [8]: G.pred
Out[8]: {1: {}, 2: {1: {}}, 3: {}, 4: {3: {}}}

In [9]: G.succ
Out[9]: {1: {2: {}}, 2: {}, 3: {4: {}}, 4: {}}
```

@dschult Is there any general interest in networkx community regarding an unified class for all types of graphs?

**Comment by MridulS** [comment]
As @chebee7i suggested we can calculate degree, in_degree, out_degree using combinations of `G.adj`, `G.succ`, `G.pred`

**Comment by dschult** [comment]
@MridulS  asked about interest from the community for a unified class for all types of graphs. I can give some history on that question. But I don't speak for the whole community. From my perspective, an ideal world would have provided definitions that worked nicely for all types of graphs, and then we would have a single graph class. But my experience suggests that it just isn't effective to try to combine all the different ideas about graph structure people have invented into a single class. The swiss-army-knife graph class leads to more confusion than problem solution. On the other hand having 20 or 30 different graph classes to handle each type of graph doesn't work well either (mostly from a maintenance perspective). The optimum is in the middle somewhere and we try to stumble toward it through incremental improvements. The MixedGraph structure discussed in this issue might be reasonable. It would be nice to have an algorithm or application in mind to guide its development.

**Comment by MridulS** [comment]
As @chebee7i pointed out MixedGraph are helpful for Bayesian networks.

http://www.jmlr.org/papers/volume10/silva09a/silva09a.pdf

**Comment by hagberg** [comment]
I didn't read the whole paper.  But in that context doesn't it make sense
to just use two directed edges for a "bi-directed edge"?

**Comment by MridulS** [comment]
@hagberg I think "bi-directed edges" do make sense but the properties won't be well defined. For example, `G.degree()` will return `in_degree + out_degree` and a node(undirected) which was originally supposed to have degree 1 will have degree 2. This may create chaos in implementation of algorithms.

**Comment by adam2392** [comment]
Was this ever addressed/implemented? If not, what are the challenges? It looks like based on the discussion the `MixedGraph` abstraction seemed plausible?

I had a similar question that I raised before seeing this issue: https://github.com/networkx/networkx/discussions/5408
