### ISSUE TITLE
Feature Request: Graph from Pandas DataFrame

### ISSUE THREAD

**Issue by ericmjl** [networkx/networkx#1174]
I hope I'm posting in the right place! 

Pandas DataFrames contain one very crucial difference to numpy matrices - the index labels and column labels. Could there be a way to parse DFs into a graph, automatically creating the nodes from the index & column labels, and edges with weights based on the matrix values?

**Comment by Michael-E-Rose** [comment]
If I'm not mistaken, we can close this issue, as it was fixed in #1321.
