### ISSUE TITLE
List ordering in kosaraju_strongly_connected_components

### ISSUE THREAD

**Issue by artas360** [networkx/networkx#1216]
Hi all,
After switching form networkx1.8.1 to 1.9 I noticed that the order of the list returned by `kosaraju_strongly_connected_components` seems to be reversed.

```
import networkx as nx
G=nx.DiGraph()
G.add_edges_from([(1,2),(2,1),(1,0),(2,0)])
[_ for _ in nx.kosaraju_strongly_connected_components(G)]
```

In 1.8.1 returns: `[[1, 2], [0]]`
In master (cloned last week) returns: `[[0], [1, 2]]` -> Contradicts the doc

Did I miss something?

Thanks for all your work.

Regards.

**Comment by JonathanShor** [comment]
`strongly_connected_components_recursive` has this same documentation issue: `A list of nodes for each component of G. The list is ordered from largest connected component to smallest.` when it seems that here the order is, again, in fact not guaranteed.
