### ISSUE TITLE
wishlist: markov equilibrium distribution

### ISSUE THREAD

**Issue by argriffing** [networkx/networkx#1225]
NetworkX includes sophisticated analyses of directed weighted graphs, evaluating or ranking nodes according to HITS or PageRank, implemented in the `link_analysis` sub-package http://networkx.github.io/documentation/development/reference/algorithms.link_analysis.html.  What about the less complicated task of evaluating nodes according to their equilibrium distribution when edge weights represent discrete-time transition probabilities, or continuous-time instantaneous transition rates?  I imagine this could be implemented in NetworkX with pure Python using a power iteration method, or using clever numpy or scipy tricks if these are installed.  Or is this already implemented in networkx and I'm just not finding it?

**Comment by chebee7i** [comment]
I'm guessing we'd accept a PR for this.

**Comment by hagberg** [comment]
Closed due to inactivity.
