### ISSUE TITLE
xrange vs python 3

### ISSUE THREAD

**Issue by argriffing** [networkx/networkx#1227]
Searching the networkx code for `xrange` I see it's used in some "Shapefile" related code and tests.  Should this be updated for python 3 compatibility, and is it not tested in the TravisCI testing?

**Comment by dschult** [comment]
The f.geometry() returned None in python3 because the shpfile had not been created correctly. Unrolling the map() and xrange() calls allows the shpfile to be correctly written and then f.geometry() works.  PR #1317 holds the changes.
