### ISSUE TITLE
drawing breaks on unicode label

### ISSUE THREAD

**Issue by jogo** [networkx/networkx#1230]
https://github.com/networkx/networkx/blob/master/networkx/drawing/nx_pylab.py#L849

breaks for unicode.

    for n, label in labels.items():
        (x, y) = pos[n]
        if not cb.is_string_like(label):
            label = str(label)  # this will cause "1" and 1 to be labeled the same

where label="Édouard"

**Comment by hagberg** [comment]
I'm going to defer action on this since there is an easy work-around and #1325
