### ISSUE TITLE
Communicability, subgraph centrality, clarification and refactor

### ISSUE THREAD

**Issue by Michael-E-Rose** [networkx/networkx#1239]
The documentation on `communicability_centrality()` says that it calculates communicability centrality which is also know as subgraph centrality according the documentation. But communicability centrality is not the same as subgraph centrality. These two are related but distinct concepts:

Subgraph centrality builds subgraphs using closed walks. Communicability centrality uses open walks between any two nodes. 

Given the formula and description of the command, it seems that NetworkX actually uses subgraph centrality which however renders the NetworkX command 'communicability' wrong.

**Comment by Michael-E-Rose** [comment]
It also affects all the other centrality measures listed in [`communicability_alg.py`](https://github.com/networkx/networkx/blob/master/networkx/algorithms/centrality/communicability_alg.py), namely the communicability centrality for each pair of nodes and the two alternative definitions. It would be straightforward to rename all the measures. In this case we'd be left off with an algorithm named `subgraph()` (formerly `communicability()`) and `subgraph_exp()` (formerly `communicability_exp()`).

But an algorithm called `subgraph()` doesn't sound very intuitive. So maybe `subgraph_pairwise()` and `subgraph_pairwise_exp()` is better?

**Comment by hagberg** [comment]
Thanks for picking this back up.  We do need to rename things here - obviously it is confusing to me and probably others too.  Here are some questions for you 
1) Can subgraph centrality and communicability centrality be combined together in one algorithm with a switch (open v closed walk)?

2) How about renaming things to open_walk_  and closed_walk instead of the current names?

I haven't looked (recently anyway) at the papers you listed so maybe I am misunderstanding things here.

**Comment by Michael-E-Rose** [comment]
Yes, it is a bit confusing. Me for example, I am not sure whether the python code entered actually uses open or closed walks. In the first case, both the code and the docs are wrong. In the second case, only the docs are wrong (as the claim subgraph cent. and communicability cent. to be the same). Can you say what the code actually computes?

Regarding your questions:
 1. Theoretically yes, but that would be confusing. subgraph cent. and communicability cent. are indeed related, but only because they are betweenness-like centralities. They are as related to each other as they are related to the ordinary betweenness centrality or load centrality. All of these centralities just differ in how they define a connection between a pair of nodes.
 2. Well, literature has already established names for them. Giving the centralities different names would mean to explain a lot in the docs.

Whats more confusing is that Estrada came up with a communicability_betweenness centrality. In [his work on that](http://arxiv.org/ftp/arxiv/papers/0905/0905.4102.pdf), he (p. 3/20) writes: "The idea of using a weighted sum over walks of all possible lengths has been used successfully to define communicability between pairs of nodes [26]. Here we are extending the idea by looking at weighted all-walks passing through a third node. In the next section we show how to characterise and compute communicability betweenness via the exponential of an adjacency matrix." [26] refers to [R176] above. I think I will ask Ernesto.

**Comment by Michael-E-Rose** [comment]
So here is the first clarification: The estrada index (starting in lin 437) is the sum of the subgraph centralities. That's also what [en.wikipedia](http://en.wikipedia.org/wiki/Estrada_index) writes.

I am waiting for clarification on the rest.

PS: Maybe we should change the title of the issue, as it's about the entire [`communicability_alg.py`](https://github.com/networkx/networkx/blob/master/networkx/algorithms/centrality/communicability_alg.py) and not only one function of that.

**Comment by Michael-E-Rose** [comment]
So here is what Ernesto wrote me:
- communicability is *not* a centrality. I was very wrong about this. It's better to understand communicability as a property of nodes. Therefore, we should not combine communicability and subgraph centrality; rather, we should think about putting communicability in another category on https://networkx.github.io/documentation/latest/reference/algorithms.html
- subraph centrality is indeed a centrality and as such not to be confused with communicability.
- communicability betweenness is also a centrality and more specifically a betweenness centrality. The name indicates a similar understanding of information flow, but it doesn't mean that communicability betweenness and communicability are the same.

I'm sorry that I missunderstood the things in the first place. But the clarification made even clearer that [`communicability_alg.py`](https://github.com/networkx/networkx/blob/master/networkx/algorithms/centrality/communicability_alg.py) needs a severe reconfiguration.

**Comment by hagberg** [comment]
Well, it's all clear now :confused:.
I think we need a pull request with a proposal to endorse.

**Comment by Michael-E-Rose** [comment]
Sure, I can change the file. But let me ask you one last thing: Are the algorithms in [`communicability_alg.py`](https://github.com/networkx/networkx/blob/master/networkx/algorithms/centrality/communicability_alg.py) (e.g. line 78, 149, etc.) actually calculation subgraph centrality or communicability?

**Comment by hagberg** [comment]
I was hoping you would figure that out for me.  I might not get to reading all of those papers and unwinding it myself for a while.

**Comment by Michael-E-Rose** [comment]
I figured it out using the example graph in his papers. What's now called communicability centrality is in fact subgraph centrality. I can correct and pull that during this week.

Now the question is: Where should I put `communicability()`and `communicability_exp()`? It's not a centrality, hence it doesn't belong there. Should it a be a group of it's own in [`Algorithms`](https://networkx.github.io/documentation/latest/reference/algorithms.html)?

**Comment by Michael-E-Rose** [comment]
Pull request created. Please have a look for code review.

**Comment by Michael-E-Rose** [comment]
I'm writing regarding the documentary for betweenness centralities, which I proposed in #1397 and recently been closed.

This issue (1239) is about the naming of some functions, while 1397 is about the docs. My original plan was to continue 1397 once my proposed changes from this issue (1239) are live. Now both issues are "merged" - but is this good, when they are only vaguely related?

**Comment by hagberg** [comment]
II probably just didn't quite understand here.  I'm working on cleaning up many old issues.  I'd like to get these resolved and thanks a lot for your help.

**Comment by Michael-E-Rose** [comment]
In https://github.com/Michael-E-Rose/networkx/commit/8291bf100147988c53f33bf391d6158405d5008c, I suggest a change affecting `networkx/algorithms/centrality/communicability_alg.py`. It renames the algorithms consistently and in line with scientific terms. No change in the code. So, from my side the issue is resolved.

**Comment by hagberg** [comment]
OK - those changes are good. Could you make a pull request?

**Comment by Michael-E-Rose** [comment]
Pull request created. Sorry, I sometimes forget about this.

**Comment by Michael-E-Rose** [comment]
So, after having had troubles with my outdated fork I created a new pull request (#1950), which seems ok to merge. Please have a look.

**Comment by Michael-E-Rose** [comment]
Done with #1958.
