### ISSUE TITLE
there should be stable_topological_sort()

### ISSUE THREAD

**Issue by normanyahq** [networkx/networkx#1244]
Currently the topological_sort is unstable, I think there should be a stable one -- when doing recursion, sort the nodes first.

I made a small change on topological_sort() and it worked.

    1c1
    < def stable_topological_sort(G,nbunch=None):
    ---
    > def topological_sort(G,nbunch=None):
    50c50
    <         nbunch = sorted(G.nodes())
    ---
    >         nbunch = G.nodes_iter()
    63c63
    <             for n in sorted(G[w]):
    ---
    >             for n in G[w]:
    74a75
    > _

However, I noticed that nodes can be any hashable objects, so when sorted() is not available, it should raise error or do something else.

**Comment by hagberg** [comment]
This should be resolved now that we added #1314.
```python
import networkx as nx
from collections import OrderedDict
class OrderedDiGraph(nx.DiGraph):
    node_dict_factory = OrderedDict
    adjlist_dict_factory = OrderedDict
edges = [(7,8),(7,11),(5,11),(3,8),(3,10),(11,2),(11,9),(8,9)]
O = OrderedDiGraph(edges)
print(nx.topological_sort(O))
```
