### ISSUE TITLE
`from_numpy_matrix` incorrect for multigraphs

### ISSUE THREAD

**Issue by thoppe** [networkx/networkx#1249]
Using `from_numpy_matrix` on a multigraph will not add the additional edges. A minimal working example:

    import numpy as np
    import networkx as nx

    A1 = [[0,2],[1,0]]
    g1 = nx.from_numpy_matrix(np.matrix(A1),nx.MultiDiGraph())

    print "from_numpy_matrix edges: ", list(g1.edges())

    g2 = nx.MultiDiGraph()
    g2.add_edge(0,1)
    g2.add_edge(0,1)
    g2.add_edge(1,0)

    print "manual edges:            ", list(g2.edges())

It is expected that these two should be the same. The output using version 1.9 is:

    from_numpy_matrix edges:  [(0, 1), (1, 0)]
    manual edges:             [(0, 1), (0, 1), (1, 0)]

**Comment by jfinkels** [comment]
This should now be fixed by pull request #1339, with the only caveat that (following a discussion by the maintainers) you will have to explicitly state if you want to interpret the array entries as parallel edges in a multigraph as opposed to a single weighted edge:

    >>> import numpy as np
    >>> import networkx as nx
    >>>
    >>> A = np.matrix([[0, 2], [1, 0]])
    >>> G = nx.from_numpy_matrix(A, create_using=nx.MultiGraph())
    >>> H = nx.from_numpy_matrix(A, parallel_edges=True,
    ...                          create_using=nx.MultiDiGraph())
    >>> 
    >>> print(G.edges())
    [(0, 1)]    
    >>> print(H.edges())
    [(0, 1), (0, 1), (1, 0)]
