### ISSUE TITLE
nx.Graph does not handle square matrix and the proper error code is not displayed

### ISSUE THREAD

**Issue by JBPressac** [networkx/networkx#1293]
Hello,
I tried to create a bipartite graph from an adjacency matrix stored in a numpy matrix with nx.Graph and it seems that because the matrix is not square, the following error message is displayed : [NetworkXError: Input is not a correct numpy matrix or array](https://github.com/networkx/networkx/blob/a946b38d91dd562b5b719aecb442d3965a9e5581/networkx/convert.py#L139), which should be, I guess,  [Adjacency matrix is not square.](https://github.com/networkx/networkx/blob/a946b38d91dd562b5b719aecb442d3965a9e5581/networkx/convert_matrix.py#L268).

nx.Graph executes [from_numpy_matrix](https://github.com/networkx/networkx/blob/a946b38d91dd562b5b719aecb442d3965a9e5581/networkx/convert_matrix.py#L204), which raise an exception in case of non-square matrix : [Adjacency matrix is not square.](https://github.com/networkx/networkx/blob/a946b38d91dd562b5b719aecb442d3965a9e5581/networkx/convert_matrix.py#L268), but I guess that this exeption is not redirected to nx.Graph. 

1. Would it be possible to implement the creation of graph from non-square matrix ?
2. Otherwise add this restriction in the documentation of nx.Graph and from_numpy_matrix and enable nx.Graph to catch the from_numpy_matrix exceptions ?

Thanks,

**Comment by jtorrents** [comment]
This was fixed in #1333
