### ISSUE TITLE
Renaming weighted_projected_graph into coaffiliation_graph?

### ISSUE THREAD

**Issue by JBPressac** [networkx/networkx#1298]
Hello,
I recently discovered affiliation networks throught the publication of Borgatti and Halgin, “Analyzing Affiliation Networks”. from which hoplefully derive some NetworkX functions (and I thank you for that). But I found difficult to understand that the weighted_projected_graph function was in fact linked to the co-affiliation matrix suggested in the publication. Would it be simpler to rename weighted_projected_graph as coaffiliation_graph?
Thanks,

**Comment by hagberg** [comment]
Google says "co-affilation graph" has 1 hit and "coaffilation graph" has 0 hits.
So I'm not seeing how that terminology would help general understanding.

We could add some documentation to explain that the projection algorithms are making one-mode graphs from two-mode (bipartite, affiliation) graphs.  Do you think that would help?

**Comment by JBPressac** [comment]
Well, the refence of the [weighted_projected_graph function](https://networkx.github.io/documentation/latest/reference/generated/networkx.algorithms.bipartite.projection.weighted_projected_graph.html#weighted-projected-graph) comes form a paper from Borgatti [Analysing Affiliation Networks](http://www.steveborgatti.com/research/publications/bhaffiliations.pdf?attredirects=0&d=1) which uses the term co-affiliation... which is more known by the sociologists than "weighted projected" which vaguely tells what you could expect a weighted graph from the function but does not designates clearly the nature of the weight (i.e. the number of shared neighbors).

**Comment by jtorrents** [comment]
@JBPressac, I'm a sociologist myself, but I think that the naming "projection" or "projected graph" and variants have ended up being the most common way to refer to one mode projections of bipartite graphs, even in the field of sociology. Co-affiliation naming comes from the tradition of analyzing the duality of persons and groups, which is one of the earliest (and coolest) uses of bipartite networks, but they are more general and can be used to model a wide range of things. Thus I think that we should keep the more general (and more common) names.
