### ISSUE TITLE
wishlist: random k-out graph

### ISSUE THREAD

**Issue by argriffing** [networkx/networkx#1316]
These random graphs are sampled as follows: for each node, sample k edges directed away from that node.  There are several variants.  For each node, the outgoing edges may be sampled with or without replacement.  Loops may be allowed or not allowed.  The direction of the edges may be kept or removed, and the edge multiplicities may be kept or removed.

The motivation is some foo.bar withgoogle challenge where they are asking for exact moments of functions of these graphs, and their variant involves k=1, loops not allowed, edge directions removed, and edge duplicates removed.  Sampling these graphs won't help solve the challenge, but I thought that because I'm too dumb to solve it at least I could suggest the random graph family for networkx.

As a reference, the recent arxiv [paper](http://arxiv.org/pdf/1311.5961.pdf) mentions these random graphs with the added twist of preferential (non-uniform) attachment.

**Comment by jfinkels** [comment]
This was added in pull request #1768.

**Comment by argriffing** [comment]
I opened that issue a year ago so I don't remember the details of the context, but does the PR allow uniform attachment?  Maybe this could be hacked in by special-casing `alpha=inf`, if that is correct? When I said that the preprint implements an 'added twist' I was not actually requesting that twist...

**Comment by argriffing** [comment]
Also, it still prints as the empty graph.
```python
>>> G = networkx.random_k_out_graph(10, 3, 1)
>>> print G
empty_graph(10)
```

**Comment by jfinkels** [comment]
The way I implemented it does not allow uniform attachment (and it fails if you try to provide `alpha=float('inf')`). I will work on a version that allows uniform attachment.
