### ISSUE TITLE
Not found in reference PDF of closeness_centrality

### ISSUE THREAD

**Issue by soh-i** [networkx/networkx#1318]
I'm reading the document described about `networkx.closeness_centrality()` at https://networkx.github.io/documentation/latest/reference/generated/networkx.algorithms.centrality.closeness_centrality.html, but link of reference paper (http://www.soc.ucsb.edu/faculty/friedkin/Syllabi/Soc146/Freeman78.PDF) is now dead.

I found another pdf link, that is http://leonidzhukov.ru/hse/2013/socialnetworks/papers/freeman79-centrality.pdf.

**Comment by chebee7i** [comment]
Fixed in #1319.
