### ISSUE TITLE
Timing Tests Failing

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#1323]
From #1322 
@hagberg said: Those tests are not related to your code but instead in the timing tests. @dschult can you look at this? Do we need to run these tests regularly or are they primarily for evaluation performance when suggesting changes?

I am looking at them now....  I've tried the tests on a variety of machines and my numbers all come out to be with a ratio of 1.3 or lower. The travis code is occasionally giving results like 2.05 which is above the 2.0 cutoff.  I think maybe @chebee7i mentioned changing the cutoff to 3.0 to avoid this problem. But I don't understand what is making the travis ratios so much bigger on occasion.

To answer your question: the idea of running the timing tests on travis is to catch changes that slow down basic features when we don't expect them to slow it down. Perhaps @chebee7i change to cutoff=3 will work for now but when it has to be changed again to 4 and then to 5 we'll know something is going on.  It might not even be something in our code--but something about how python does lookups. But it shows the speed relative to our old (1.9.1) base classes.

I'm fine with taking them out of travis if that's preferred. But these are the reason it is in travis.

**Comment by hagberg** [comment]
I see what the goal is.  I don't have any strong preference of changing cutoff vs removing from travis testing.

**Comment by dschult** [comment]
I just had travis return values greater than 3 -- usually the biggest is
about 1.2.
Somehow I think the fluctuations with timeit.Timer() are just too great to
make this a useful test.
I'll put a PR together to remove it from Travis.
