### ISSUE TITLE
Remove matplotlib drawing to separate package

### ISSUE THREAD

**Issue by hagberg** [networkx/networkx#1325]
Maybe it violates the _batteries included_ philosophy - but how about removing the nx_pylab.py code to a separate package?  Maybe it will get more attention that way or people would be inspired to write a better version?  I'd suggest keeping it at github networkx/networkx-matplotlib so then it could be _batteries included but contained in separate packaging_.  Comments?

**Comment by ysitu** [comment]
Back in #1167 there was discussion about optional components and an add-on system. nx_pylab.py may well be a customer of such a system.

**Comment by hagberg** [comment]
Yes, it could be part of some optional or add-on system.  

The purpose of removing it from the networkx code base is more for developers and maintainers than end users or packagers.  My thought is that graph drawing is quite different than the algorithms and data structures components of networkx in that it involves visual elements, external graphics packages, potentially platform specific or domain specific tools.   Maybe keeping the drawing separate from the algorithms and data structures will make both easier to develop and maintain?  

I'm proposing moving the code to a separate repository (something like networkx/networkx-matplotlib).

**Comment by pabloem** [comment]
Hello everyone,
so in this case, would there be some sort of a 'Drawer' class that has some methods, and thus people interested in definining 'Drawers' for NetworkX would just need to make a class with these methods? An overview of a drawer class would look like this:
```
class Drawer:
    def draw(G,...):  # Draws the graph
        [....]
```
And then, in networkX, we'd just want to be able to set different drawers, and care not about their dependencies:
```
def set_drawer_class(self,drawer):
    self.drawer = drawer
[...]
def draw(...):
    try:
        self.drawer.draw(...)
    except NameError:
        error("No drawer has been defined") # error out if we have no drawer
[...]
```
So we'd implement a Drawer class with the matplotlib functionality that we already have... and also fixing the arrow drawing logic.
Is this assessment of the necessary work correct?

**Comment by OrkoHunter** [comment]
I liked the idea of @hagberg to move `nx_pylab.py` into `networkx` package itself, not in the proposed `networkx.addons` because the later should contain the add-ons which are more related to algorithms and data structures so that contribution could be made easier.

**Comment by OrkoHunter** [comment]
Concerning #1167 and this, how is this idea to create something like `import_module` for this purpose. So to avoid confusion between the path of such modules, we can just do this

>>>from nx.external import import_module

>>>plt = import_module(matplotlib)

>>metis = import_module(networkx-metis)

In this way, we won't need to remember the location of the module which we want to import. There are also other ways in which we can make use of `import_module`

1. A minimum version for the module can be given as the keyword argument
    min_module_version.  This should be comparable against the module version.
   Then, we could give a warning "Module version is too old."

2. import_module returns None if the Module is not installed. So it could raise the 
    ImportError accordingly.

3. We can also specify a minimum Python version by using the
    min_python_version keyword argument.  This should be comparable against
    sys.version_info. This could give a warning "Python version is too old."
    
@hagberg @ysitu @jtorrents @chebee7i @dschult

**Comment by OrkoHunter** [comment]
I'm sorry for so much amendments. It looks ugly here, I know.

**Comment by jtorrents** [comment]
@OrkoHunter, Aric is proposing to *remove* `nx_pylab` from NetworkX and put it in a separate repository at github, upload it as a separate package at pypi, ... And @ysitu is suggesting to use the (yet to be defined and implemented) new add-ons system for integrating this new (yet to be created) `networkx-matplotlib` project into NetworkX. Thus, this is a big change that will require planing and coordination with other (more or less concurrent) development efforts, not a good candidate for a quick PR. I suggest you close #1408. This could be a cool GSOC project, which as @pabloem points out, it could also try to address some shortcomings of the current `nx_pylab`, such as arrows in directed graphs, ....

**Comment by OrkoHunter** [comment]
Thanks for the clarification @jtorrents. This is really a big change. Looking forward to the decisions.

**Comment by jarrodmillman** [comment]
See https://github.com/networkx/grave

**Comment by hagberg** [comment]
This didn't get enough traction so I'm closing.
