### ISSUE TITLE
Add clustering coefficient measures for directed graphs

### ISSUE THREAD

**Issue by hagberg** [networkx/networkx#1331]
See previous PR #1051.
I suggest a pure python implementation (previous used numpy/scipy).

**Comment by OrkoHunter** [comment]
While going through the already existing algorithms of clustering coefficients, I came through statements like "`triangles()` is not defined for directed graphs" and "Clustering algorithms are not defined for directed graphs."

I want to know how are clustering coefficients defined for Directed Graphs. 
I'm willing to solve this issue.

**Comment by ayushidalmia** [comment]
https://en.wikipedia.org/wiki/Clustering_coefficient#Local_clustering_coefficient

Based on the definition above, can we convert the directed graph into an undirected graph, compute the clustering coefficient for every node and divide it by 2? Is it a right way to compute the clustering coefficient for nodes in a directed graph?

**Comment by dschult** [comment]
The wikipedia link does not imply you can convert to an undirected graph to compute the clustering coefficient. When converting to undirected, there is no way to tell whether the resulting undirected edge came from a single directed edge or two directed edges. A single directed edge leads to a different coefficient (based on the defn in wikipedia) than two directed edges in opposite directions. The convert-to-undirected method would provide the same answer as a directed graph where all edges were in both directions. I think the potential difference is a factor of 2.
