### ISSUE TITLE
"robust" topological sort (does best it can when there are cycles)

### ISSUE THREAD

**Issue by jason-s** [networkx/networkx#1342]
The existing version of networkx raises an exception [if topological_sort is called on a directed graph with cycles](https://networkx.github.io/documentation/latest/reference/generated/networkx.algorithms.dag.topological_sort.html).

I am not very familiar with graph theory so don't really know how to comment on this, but I am looking for an algorithm that does "the best it can", maybe leaving the nodes in a cycle in some order and doing a topological sort on the rest. [This article](http://www.logarithmic.net/pfh/blog/01208083168) allegedly uses an algorithm from Tarjan (which gives me some confidence that it has merit), with a fairly simple Python implementation posted.

Is there a way you could add a keyword `robust=False` to the `topological_sort()` method, and if `robust` is `True`, use this type of algorithm?

**Comment by ysitu** [comment]
I am not inclined towards calling that "robust". Topologically sorting a cyclic graph is ill-posed to begin with. The article you pointed to suggests sorting the strongly connected components (that is why it refers to Tarjan's algorithm) and order the nodes within each SCC arbitrarily. `nx.condensation` is what you need to do that.

**Comment by jason-s** [comment]
ok, thanks. Well, it sounds like what I can do with the existing version of networkx is use `G2 = nx.condensation(G1)` followed by `sortednodes = nx.topological_sort(G2)`, and then create a list of node names from the original graph G1 by walking through the results.

If this merits a new feature as a convenience to make this easier and do it automatically, then great -- if not, I'm fine with closing this issue.

**Comment by zhiyzuo** [comment]
Agree with @ysitu . Topological sort is for dags (thank god I just learnt this algorithm from unlocked algorithm LOL)

**Comment by jason-s** [comment]
for what it's worth, my use case is to create a dependency structure matrix e.g as in http://www.ndepend.com/docs/dependency-structure-matrix-dsm

**Comment by jason-s** [comment]
looks like this will do what I want:

```
def soft_toposort(g):
    g2 = nx.condensation(g)
    sorted_comps = nx.topological_sort(g2)
    return [m for c in sorted_comps for m in g2.node[c]['members']]
```
