### ISSUE TITLE
Number of graphs on n unlabelled nodes

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#1343]
Is it possible to calculate the number of graphs on n unlabelled nodes?
Something like: 
```python
>>> import networkx as nx
>>> nx.number_of_graphs(3)
>>> 4
>>> nx.number_of_graphs(4)
>>> 11
```

And it would be nice if it can return a list of graphs with the possible graphs.
http://reference.wolfram.com/language/Combinatorica/ref/ListGraphs.html
https://oeis.org/A000088

**Comment by Midnighter** [comment]
It's for small graphs only but there is the [graph atlas](http://networkx.github.io/documentation/networkx-1.9.1/reference/generated/networkx.generators.atlas.graph_atlas_g.html#networkx.generators.atlas.graph_atlas_g). It needs to be imported separately:

```python
from networkx.generators.atlas import graph_atlas_g
```

**Comment by MridulS** [comment]
Was going through the source code. I think we can implement it in a better way and for graphs with number of nodes greater than 7.
Like for a graph with 4 nodes.
```python 
import networkx as nx
import itertools as tools

m = [(i,j) for i in range(1,5) for j in range(i + 1, 5)]
q=[]
for i in range(0,6):
    q.append(list(tools.combinations(m,i+1)))

g=[]
for i in range(0,63):
    g.append(nx.Graph())

for i in range(0,63):
    g[i].add_nodes_from([1,2,3,4])

for i in range(0,6):
    g[i].add_edges_from(q[0][i])

for i in range(0,15):
    g[i+6].add_edges_from(q[1][i])

for i in range(0,20):
    g[i+21].add_edges_from(q[2][i])

for i in range(0,15):
    g[i+41].add_edges_from(q[3][i])

for i in range(0,6):
    g[i+56].add_edges_from(q[4][i])

for i in range(0,1):
    g[i+62].add_edges_from(q[5][i])

for i in range(0,63):
    for j in range(i+1,63):
        if nx.is_isomorphic(g[i],g[j]):
            g[j].clear()

lis = filter(None,g)

print len(lis)

for i in range(0,10):
    print lis[i].edges()
```
``` lis ``` gives out non isomorphic graphs while ``` g ``` will give all the graphs
I think this can be improved and used for graphs with nodes > 7.

**Comment by chebee7i** [comment]
What would the counts be useful for? It seems like it is a one-off lookup to OEIS:

```python
def n_graphs(n):
    counts = '	1, 1, 2, 4, 11, 34, 156, 1044, 12346, 274668, 12005168, 1018997864, 165091172592, 50502031367952, 29054155657235488, 31426485969804308768, 64001015704527557894928, 245935864153532932683719776, 1787577725145611700547878190848, 24637809253125004524383007491432768'
    counts = list(map(int, counts.split(',')))
    if n >= len(counts):
        raise ValueError("The count is too damn high.") # This is a joke
    else:
        return counts[n]
```

There are many variants of counting (self-loops, directed, etc). Now, I can definitely see the value in having the graphs themselves, but this is a tough computational problem when n is large.

**Comment by MridulS** [comment]
Yeah, it is a tough computational problem when n is large.
But at least we can change graph atlas code from ~12000 lines to ~200 lines.

**Comment by hagberg** [comment]
Counting graphs with 5 nodes:

```python
In [1]: from networkx.generators.atlas import graph_atlas_g

In [2]: len([g for g in graph_atlas_g() if len(g)==5])
Out[2]: 34
```

I don't see a benefit from adding non-isomorphic graphs here.

**Comment by MridulS** [comment]
@hagberg 
How about implementing a module like http://reference.wolfram.com/language/Combinatorica/ref/ListGraphs.html 
in networkx.

**Comment by hagberg** [comment]
It's called http://reference.wolfram.com/language/ref/GraphData.html now.
And implementing that is some amount of work.
Take a look at http://graphclasses.org.  I think SAGE includes some of that data.

**Comment by hagberg** [comment]
If there is a specific proposal let's open a new issue.
