### ISSUE TITLE
Add dijkstra version with node weights

### ISSUE THREAD

**Issue by joelmiller** [networkx/networkx#1345]
(minor request)

Sometimes people want to find the cheapest path where the cost is calculated based on node weights or a sum of edge and node weights.

In this case it is easy to translate into dijkstra's algorithm with just edge weights by assigning a weight to each edge equal to the sum of the weights of the nodes on either end (or just their average).  However, this requires doing modifications to all the edges a priori, and we may not want to modify the graph.

It should be straightforward to adapt the existing Dijkstra's algorithm to do this at each step as it runs.

**Comment by MridulS** [comment]
@joelmiller 
``` python
G.add_weighted_edges_from([(1, 2, 2), (1, 3, 2), (2, 4, 2), (3, 4,3)])
G.node[2]['node_weight'] = 5
def func(u, v, d):
    return G.node[u].get('node_weight', 1)/2 + G.node[v].get('node_weight', 1)/2 + d.get('weight', 1)
print(nx.dijkstra_path(G, 1, 4, weight=func))
[1, 3, 4]
```
Let me know if you need any help! :)
