### ISSUE TITLE
Node names need their special characters escaped for DOT generation (and possibly in other formats)

### ISSUE THREAD

**Issue by michalsta** [networkx/networkx#1348]
Consider the following code:

=========generate.py==============
```
G = NX.Graph()
G.add_node('A\A')
NX.write_dot(G, 'graph.dot')
```
================================

Running this file results in:

===========graph.dot==========
```
strict graph  {
        "A\A";
}
```
=============================

which, when processed with "dot -Tpdf graph.dot > graph.pdf" generates a graph with single node named "AA" instead of "A\A".

The expected output would be:

=============expected.dot=======
```
strict graph  {
        "A\\A";
}
```
==============================

**Comment by hagberg** [comment]
This is the expected behavior with graphviz  - see the escString documentation at http://www.graphviz.org/doc/info/attrs.html

So you will need to write "A\\A" for a label in order to render what you want when drawing with graphviz.

**Comment by michalsta** [comment]
All right, I made a typo in my post (or rather, didn't notice that markup "ate" a one very cruicial backslash), it should be clearer now. 

My point is, that networkx, when given a graph with "A\A" node will generate a dot file which will render the node in graphviz as "AA" due to the backslash being treated by graphviz (again, as expected, this is not a bug in graphviz) as an escape for the next character. IMHO, while generating dot files, networkx should search the name strings for any special characters which need to be escaped (for graphiviz to interpret them correctly), and escape them. In fact, right now, the following code will generate a dot file which isn't even syntactically correct:

```
G = NX.Graph()
G.add_node('A"A')
NX.write_dot(G, 'graph.dot')
```

the output is:

```
strict graph G {
A"A;
}
```

Graphviz chokes on that:

```
$ dot -Tpdf g.gv          
Warning: g.gv: syntax error in line 2 near ''
```
(no output produced)

**Comment by chebee7i** [comment]
I've had similar thoughts and was never able to decide what should be done. The present approach requires that the user provide node names with graphiz encodings in mind. Your proposal definitely makes it more user-friendly. The question, I guess, is whether we want `write_dot` to do something vanilla or put a cherry on top too.

**Comment by hagberg** [comment]
I'm ambivalent about trying to adjust this behavior.  I can see that it is annoying to have a \ swallowed by Graphviz because it wasn't escaped by another \, or quotes disappearing.  But I suspect that fixing some of these issues might be tricky (or break something else).  If you want to propose a fix in to_agraph() and to_pydot() that addresses the Graphviz escString transformations - go for it.

**Comment by mad4alcohol** [comment]
I have tested the following code with my version of networkx
```python
G = NX.Graph()
G.add_node('A\A')
NX.write_dot(G, 'graph.dot', escape_backslashes=True)
```
The output is following:
```
strict graph  {
        "A\\A";
}
```

And about
```python
G = NX.Graph()
G.add_node('A"A')
NX.write_dot(G, 'graph.dot')
```
It outputs the following under pygraphviz 1.3rc2
```
strict digraph  {
	"A\"A";
}
```
