### ISSUE TITLE
Graphviz subgraphs?

### ISSUE THREAD

**Issue by dorneanu** [networkx/networkx#1352]
Hi,

I've recently found this post on generating Graphviz subgraphs using networkx. However in the newest version, there is no `name` attribute in `subgraph(...)`. 

Are there any other ways to generate (graphviz) subgraphs? Thx in advance.

Cheers,

Victor

**Comment by chebee7i** [comment]
Which post?

**Comment by dorneanu** [comment]
Oh, sorry! I mean this one: https://groups.google.com/forum/#!topic/networkx-discuss/HffAfH0_AYQ

**Comment by Midnighter** [comment]
Which versions are you using? I'm on graphviz version 2.38.0 and pygraphviz 1.3rc2. I can easily implement the example from that post:

```python
In [1]: import pygraphviz as pgv

In [2]: g = pgv.AGraph()

In [3]: g.add_edge(1, 2)

In [4]: g.add_edge(2, 3)

In [5]: h = g.subgraph([2, 3], name="funny")

In [6]: print(g.string())
strict graph {
        subgraph funny {
                2 -- 3;
        }
        1 -- 2;
}
```

Does this work for you or can you explain your problem in more detail?

**Comment by hagberg** [comment]
This is a http://github.com/pygraphviz/pygraphviz/issues
