### ISSUE TITLE
Many graphs in one file

### ISSUE THREAD

**Issue by mohsenuss91** [networkx/networkx#1353]
Hello! I want to know if it is possible to use Networkx library to read/write many graphs from/in one file?
I find only examples with one graph!

**Comment by Midnighter** [comment]
(Almost) Verbatim copy from my mailing list post. In general open questions like this are better discussed there.

> That depends a lot on the file format you would like to store them as. You can easily pickle a list of many graphs, for example. Although it's a little bit of a cheat you could also generate a zip or tar archive that contains multiple other files.

> So what's your preferred format?

**Comment by hagberg** [comment]
Better topic for the mailing list.

**Comment by mohsenuss91** [comment]
@hagberg done.
