### ISSUE TITLE
from decorator import decorator 	ImportError: No module named decorator

### ISSUE THREAD

**Issue by JordyCR** [networkx/networkx#1366]
Dear all

I am having some troubles with networkx package.

I recently started to work with networkx, if I use IDLE (python), Terminal or iPython, all works fine but, you know, its easier to work using an IDE like Eclipse or IntellijIDEA, then I downloaded LiClipse and Python plugin for intelliIDEA

This is my problem:

	Traceback (most recent call last):
	  File "/Users/JordyCuan/Workspaces/myProject/src/Prueba.py", line 15, in <module>
	    import networkx as nx
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/networkx/__init__.py", line 56, in <module>
	    import networkx.utils
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/networkx/utils/__init__.py", line 2, in <module>
	    from networkx.utils.decorators import *
	  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/networkx/utils/decorators.py", line 7, in <module>
	    from decorator import decorator
	ImportError: No module named decorator

<br>
**I am using MacOSX Mavericks (10.9)**

I tried:

* Uninstalling and reinstalling: setuptools, decorator and networkx using 'pip'
* Installing all files and copying here: 
	* /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages
	* /System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python
	* /Library/Python/2.7/site-packages

	
Any Ideas?

Thanks all!

**Comment by mad4alcohol** [comment]
I am no expert of Mac OS X but probably you are missing some environment variables. Or maybe you have multiple Python installations on your system, so you need to specify the one with NetworkX installed for IntellijIDEA or other IDEs.

And I don't know how you installed networkx and decorator. I'd suggest that you install only networkx by `pip` and let `pip` resolve the dependencies of networkx on its own.

P.S. JetBrains has developed a Python-IDE named PyCharm, maybe you should check it out and see if that solves your problem.

**Comment by MridulS** [comment]
You could use https://virtualenv.pypa.io/en/latest/ to deal with multiple
python installations. I used to face similar issues, virtualenv worked for
me.

**Comment by chebee7i** [comment]
I'd second @mad4alcohol thought. I suspect the Eclipse IDE is using your system Python (`/System/Library/Frameworks/Python.framework/Versions/2.7`). Could it be that when you use IDLE (python), Terminal or iPython, that you are using a different Python?  One easy check would be to do the following from a Python terminal session:

```
import networkx
print networkx
```

If the location of the displayed file is different from `/System/Library/Frameworks/Python.framework/Versions/2.7` then you'll need to configure the Eclipse plugin appropriately. If it is the same, then we'll have to dig deeper.

**Comment by rashoodkhan** [comment]
I use PyCharm for all python development, and by default it takes the python installed by the system.

I use virtual environment by using the virtualenv. Install virtualenv by ```$ pip install virtualenv``` and the workflow which I follow for each project is given below - 
* If I want to work a new project, I make sure not to install any packages on the default python installation, hence I create a virtual environment for each project. You can create a new virtual environment by ```$ virtualenv projectname-env```
* Activate the virtual environment by running ```$ source path-to-virtualenvironment/bin/activate``` - You should be able to see the environment name on the bash prompt
* Install all dependencies required by the project using pip
* Run ```$ pip freeze``` to verify all the required dependencies are installed
* Install the required application using source (i.e. ```$ python setup.py install``` or ```$ pip install projectname```)

Now comes the PyCharm Setup
* Open the project in PyCharm
* Click ```Cmd ,``` to open the preferences menu
* Navigate to Project tab -> Project Interpreter
* Click on the settings icon on the right next to and click Add Local - Now navigate to your path of installation of virtual environment/bin/ and select python2.x depending on your installation

![screen shot 2015-02-26 at 4 09 20 am](https://cloud.githubusercontent.com/assets/2310087/6382362/f6e69184-bd6d-11e4-9737-39d04a2c7b95.png)


Now your PyCharm is loaded with given virtual environment.

If you want to run the code from terminal, you will need to activate the virtual environment and then run your code. If a terminal session closes, the virtual environment session closes too. At any point of time you can deactivate the virtual environment by executing ```$ deactivate``` on the terminal.

I think by following the above steps will solve your problem. In case you are stuck, please reply to this thread.

**Comment by JordyCR** [comment]
Thanks all for answering
I really appreciate your comments

I do not why but using PyCharm all works fine.

I thought could be my SO and every IDE I would try to use would crash (I learned persistence is the key, haha)
@rashoodkhan thanks for that useful instructions

Once again thank you all for commenting
