### ISSUE TITLE
Contributing biologically motivated models

### ISSUE THREAD

**Issue by dansondergaard** [networkx/networkx#1368]
Hi!

I have implemented graph generators for two models commonly used for analysis of protein interaction networks: the partial duplication model and the duplication-divergence model. Since these graph generators may be of use to others in the field of proteomics/bioinformatics I wondered if the networkx developers were interested in such generators.

In case you are, I was wondering where they should be placed? It may make sense to put them in a separate module for biological graph generators. If not, I think that they should be placed as random graph generators.

**Comment by Midnighter** [comment]
Personally, I'm very interested in this as I work in bioinformatics myself. I'd be happy to review the code, tests and documentation. I can't make the call on whether and where this should go into networkx, however.

**Comment by dschult** [comment]
I believe these generators will be of use to others. I think the best place to put them is in a separate module within the generators folder called duplication.py or similar. While they are mostly used for biological systems now they may find uses elsewhere later so I'd prefer a name that describes the generator method instead of the application for which it works well.
Thanks!

**Comment by chebee7i** [comment]
How does this relate to #1210?

**Comment by dansondergaard** [comment]
@Midnighter, that would be great!

@dschult, I agree :)

@chebee7i, the PR only includes a generator for the duplication-divergence model, not the partial duplication model. I cannot immediately see if my code is equivalent to the code in #1210 though. My code was written for teaching purposes, so it is written with clarity, not speed, in mind.

I made my implementation available as a Gist: https://gist.github.com/dansondergaard/59a43c156c890f0f0be8

I have not added any tests yet, but sit tight :)

**Comment by dschult** [comment]
Fixed in #1939 with both methods, removal of a similar function in random_graphs.py and tests added...
