### ISSUE TITLE
Documentation issue

### ISSUE THREAD

**Issue by OrkoHunter** [networkx/networkx#1369]
In the Credits page,
http://networkx.github.io/documentation/networkx-1.9.1/reference/credits.html

In the second line, saying "Thanks to Guido van Rossum for the idea of using Python for implementing a graph data structure" followed by a link to python.org which does not exist.

http://www.python.org/doc/essays/graphs.html

Shouldn't we remove the link as it points to an empty page?

**Comment by dschult** [comment]
Thanks for pointing this out.
I found the correct link and updated the credits.
https://www.python.org/doc/essays/graphs

**Comment by OrkoHunter** [comment]
Glad to help. :)
