### ISSUE TITLE
Convert MultiGraph to Graph

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#1371]
``` python
In [2]: G = nx.MultiGraph()

In [3]: G.add_edge(1,2,weight=1)

In [4]: G.add_edge(1,2,weight=2)

In [5]: G.add_edge(3,2,weight=1)

In [6]: H= nx.Graph(G)

In [9]: H.edges(data=True)
Out[9]: [(1, 2, {'weight': 2}), (2, 3, {'weight': 1})]
```
nx.Graph(G) should add the weights of all the multiedges instead of just assigning the weight of the latest edge.

I guess the most obvious solution would be to add the edges and it is possible that user wants to convert a multigraph to graph. 
@hagberg gave a way to do this in http://stackoverflow.com/questions/15590812/networkx-convert-multigraph-into-simple-graph-with-weighted-edges.

**Comment by hagberg** [comment]
That might be the most obvious way if the data are numbers representing weights.  But when the data are categorical (e.g. colors) it could be a lot more complicated.  

If it is confusing that the edge data has an arbitrary selection I'd prefer just not allowing this.

**Comment by MridulS** [comment]
What about allowing it for numbers and raising an error for strings? I
think converting a multigraph to graph should be allowed if possible.

**Comment by hagberg** [comment]
But then you'd have to decide what to do with the numbers.  You want to sum them but I want to take the harmonic mean or find the greatest common divisor.  It's cleaner just to let a user decide how to combine attributes.

**Comment by MridulS** [comment]
Yeah, I guess then we should leave it to the user. But should we raise an
error or just leave it the way it is.

**Comment by khs26** [comment]
What about adding an optional function to be applied to the edges with reduce or something similar? The default be enforced with something like `lambda x, y: y`.

**Comment by hagberg** [comment]
Adding an optional function would work.  The question would be whether it is simpler for a user to learn how to write such a function to pass into this method or instead to just loop over the edges directly and insert the desired data into a new graph.  I think doing like the example @MridulS pointed to above is simplest.

**Comment by ysitu** [comment]
If you allow supplying one function, you probably want to allow a dict of functions indexed by graph keys---you may want to do different things for different keys, e.g., sum weights vs set-union colors. Or perhaps the one function should handle all keys instead of just one.

**Comment by hagberg** [comment]
Right, it gets complicated pretty fast.  So I am advocating that the user explicitly write code that takes a MultiGraph, manipulates the edges, and returns a Graph.  It may be simpler to do that than to learn how to write a dict of functions.

Aric

**Comment by chebee7i** [comment]
We seem to come across situations like this frequently, where the solution is not a one-liner but also not that complicated either. Maybe we should promote example recipes (organized into sections etc) as part of the documentation. I think tossing them in the examples folder is also a possibilty, but users might be less likely to find and/or understand them without some contextual discussion.

**Comment by hagberg** [comment]
Yes, examples.  I proposed creating notebooks and examples as part of the docs for GSoC.
This is exactly the kind of thing that would be appropriate.

**Comment by Midnighter** [comment]
There's already a large collection of examples that could easily be converted to notebooks. Definitely an easy project for GSoC.

**Comment by MridulS** [comment]
How about we create a new function ```convert_to_graph(G, option=None)``` where ```G``` is a MultiGraph and ```option``` could be various things we can do with the weights of the edges (add, min, max, harmonic mean, etc.)?

**Comment by hagberg** [comment]
@Midnighter  it is not easy to do it well.  It requires quite a lot of technical skill, creativity, and writing ability.

**Comment by hagberg** [comment]
I still don't think it is a good idea to try to create a complicated functional interface to something that might be very simple - (e.g. add weights).  It's probably mostly a philosophical approach. But practically imagine that I wrote 20 functions like convert_to_graph (such as get_neighbors_with_data() etc).  Now the problem for a user is to search the catalog of those functions to find one that does what they want and learn to use it.  I am arguing that it is better to show a user how to write a few lines of Python code instead.

**Comment by MridulS** [comment]
Well then it should be properly documented then :)

PS: #480

**Comment by hagberg** [comment]
I have never argued against documentation and have personally written quite a lot.  So go for it.

**Comment by MridulS** [comment]
:+1:
