### ISSUE TITLE
Issues not labelled with difficulty

### ISSUE THREAD

**Issue by OrkoHunter** [networkx/networkx#1372]
Hi,

I have read the tutorials written in the documentation. And now, I want to solve some bugs. But here in the issue tracker I can't find any of them labelled as 'easy' or 'beginner-friendly'. IMHO It would really help people like me to start contributing to networkx.

**Comment by OrkoHunter** [comment]
Thanks @Midnighter for replying on the google group. It was nice to hear! :)

**Comment by ysitu** [comment]
You raised a good point. My impression of the existing issues and bugs is that there are not many 'easy' ones. A truly easy one that I can immediately think of is to edit `api_2.0.rst` and make sure that it covers everything major new features added since maybe last November. For the upcoming GSoC, we need to define a few truly beginner-friendly projects.

**Comment by hagberg** [comment]
If we make some labels I'm willing to attach some to issues.  Also I will try to find some more beginner-friendly projects.  I suggested a few GSoC projects at #1341 that might suitable for newcomers.

**Comment by OrkoHunter** [comment]
@ysitu I edited `api_2.0.rst` as you said. :)
Checkout this PR #1374

**Comment by SanketDG** [comment]
Any other easy issues to be fixed? Its really hard to start contributing without any difficulty tags in issues.

**Comment by ntdef** [comment]
+1 to this thread. I've enjoyed using NetworkX a lot, and I would really like to contribute, and don't know where to start.

**Comment by OrkoHunter** [comment]
Are we good to create a new label say "easy to fix" or "beginner friendly"? We surely have some bunch of issues fit for the tag.

**Comment by dschult** [comment]
I've created a label named "Easy-fix or Beginner" and labeled a few issues as such. 
It may take some effort to maintain the labels, especially adding labels to new issues.
Let's try it and see how it works.
