### ISSUE TITLE
Add an interface to http://www.graphclasses.org/smallgraphs.html

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#1373]
This could help us in problems like #1343. We could remove graph atlas and instead use http://www.graphclasses.org/smallgraphs.html for all the small graphs calculations.

**Comment by ixoth** [comment]
There exists an interface in Sage. Perhaps it could be ported without much effort.

http://www.sagemath.org/doc/reference/graphs/sage/graphs/isgci.html

**Comment by hagberg** [comment]
No it can't be ported. The code in Sage has an incompatible license (GPL).
