### ISSUE TITLE
Construction `complete_bipartite_graph` does not set the 'bipartite' node attribute.

### ISSUE THREAD

**Issue by MassimoLauria** [networkx/networkx#1375]
The complete bipartite graph generator does not set the 'bipartite' attribute. This is particularly problematic since the `complete_bipartite_graph` is the fallback method for `bipartite_random_graph(n,m,p)` when `p>=1` and for `bipartite_gnmk_random_graph(n,m,k)` when `k>=n*m`. Therefore the latter graph generators may not set the 'bipartite' attribute, despite what is documented. The obvious fix is to make `complete_bipartite_graph` set the node attribute, too.

**Comment by jtorrents** [comment]
Thanks for the report. I think that #1379 fixes it.

**Comment by MassimoLauria** [comment]
Thank you for the patch. Unfortunately the fix in #1379 sets the `bipartite` attribute in the opposite way as it should be. See my comment there.
