### ISSUE TITLE
networkx.compose() inconsistently treats edge attributes

### ISSUE THREAD

**Issue by mcannamela** [networkx/networkx#1377]
The documentation for the compose(G,H) function states:
"Attributes from H take precedent over attributes from G."
However, this is only true for node and graph attributes; edge attributes will come from G, not H:

```python
import networkx
attrkey = 'x'
def build_node_attr(name, i):
    return "%snode%d"%(name, i)

def build_edge_attr(name, i,j):
    return "%sedge%d->%d"%(name, i,j)

def build_graph(name):
    g = networkx.DiGraph()
    g.add_edge(0,1)
    for n in g:
        g.node[n][attrkey] = build_node_attr(name, n)
    for e in g.edges():
        g.edge[e[0]][e[1]][attrkey] = build_edge_attr(name, e[0], e[1])
    return g

g_name = 'g'
h_name = 'h'
g = build_graph(g_name)
h = build_graph(h_name)
assert set(g.nodes())==set(h.nodes())
assert set(g.edges())==set(h.edges())
for n in g:
    assert g.node[n]!=h.node[n]

for e in g.edges():
    assert g.edge[e[0]][e[1]]!=h.edge[e[0]][e[1]]

f = networkx.compose(g,h)

assert set(f.nodes())==set(h.nodes())
assert set(f.edges())==set(h.edges())

#node properties ok
for n in g:
    assert f.node[n]==h.node[n]

#edge properties reversed!
for e in g.edges():
    assert f.edge[e[0]][e[1]]==h.edge[e[0]][e[1]]
```

It looks like the order of these two code blocks in the body of compose() should be reversed for consistent behavior:

```python
if H.is_multigraph():
    R.add_edges_from(H.edges_iter(keys=True, data=True))
else:
    R.add_edges_from(H.edges_iter(data=True))
if G.is_multigraph():
    R.add_edges_from(G.edges_iter(keys=True, data=True))
else:
    R.add_edges_from(G.edges_iter(data=True))
```

**Comment by alexnikleo** [comment]
@mcannamela, From documentation: The node sets of G and H need not be disjoint. 

So, your example is not correct and order of this blocks doesn't matter. But it will be good to raise NetworkXError, if disjoint is not empty.

**Comment by alexnikleo** [comment]
My mistake, sets in your example is not disjoint.

**Comment by alexnikleo** [comment]
@mcannamela, You're right. I've pushed fix.

**Comment by alexnikleo** [comment]
Offtop: "The node sets of G and H need not be disjoint." There are examples of usage this function with not disjoint sets. So, I think it's better to delete this line from docs.

**Comment by dschult** [comment]
Can you change the doc_string in your PR to make it:
"The node sets of G and H do not need to be disjoint."
