### ISSUE TITLE
None is accepted as node identifier, but then degree() method breaks / changes behaviour

### ISSUE THREAD

**Issue by abeld** [networkx/networkx#1381]
As per the included shell example, None is accepted as a node identifier, but then calling degree() without an argument will return a number instead of a dictionary. This breaks code that assumes that degree() will return a dict in this case.

The bug is due to the the check at the beginning of degree(): "if nbunch in self:      # return a single node" see: https://github.com/networkx/networkx/blob/master/networkx/classes/graph.py#L1351
since in this case 'if None in g' will return True, since there is such a node in g.

I am not sure what is the right fix -- even an explicit "if nbunch is None" won't be a full solution, since in that case "for n in g.nodes(): g.degree(n)" would break.
Possibly None has to be prohibited to be used as a node? But that might also break various codes that use networkx.

```
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import networkx
>>> g = networkx.Graph()
>>> g.add_node(None)
>>> g.degree()
0
>>> gg = networkx.Graph()
>>> gg.degree()
{}
>>> networkx.__version__
'1.9.1'
>>> 
```

**Comment by dschult** [comment]
It is stated in the documentation that None should not be used as a node.
But currently there is no check when you add a node that it is not None.
That was a choice we made, but should it be revisited?
Do you have a use case for None as a node?
Dan

**Comment by abeld** [comment]
No, I don't have a usecase (I was just speculating that someone might be using it like that), and if the documentation advises against using None as a node then maybe enforcing that recommendation is the best thing to do. (Or are there other considerations against it? I assume the performance impact won't be considered important enough.)

**Comment by Umang-Goel** [comment]
@abeld @dschult  I would like to work on this issue.
I think keeping a simple check while adding a node to the graph that the node is None or not would do.
I'm also thinking of contributing to the org as part of gsoc'15 so it would just help me getting started.

**Comment by hagberg** [comment]
I'm not in favor of adding checks unless things really are confusing.  
In this case it really doesn't make sense to use None as a node and we advocate against that.
