### ISSUE TITLE
Move bipartite generators to the bipartite package

### ISSUE THREAD

**Issue by jtorrents** [networkx/networkx#1383]
Following the discussion on #1379 , moving the bipartite generators to the bipartite package wil allow for shorter function names (eg `bipartite_havel_hakimi_graph` to `bipartite.havel_hakimi_graph`). We can also remove most of the generators from the main namespace (maybe all but `complete_bipartite_graph`) and ask the user to explicitly import the bipartite package to use them:

```
from networkx.algorithms import bipartite as bp
G = bp.configuration_model(aseq, bseq)
```

**Comment by SanketDG** [comment]
I would be happy to take this up. I am a beginner, so it would be really helpful if someone could lay down the steps involved.

I am guessing I should first create a `generators.py` in `algorithms/bipartite` and then move the functions from `generators/bipartite.py`? I have no idea what to do next.

Thanks.

**Comment by alexnikleo** [comment]
@SanketDG, Next you should find all entries of moved generators. It can be done using grep or your IDE. Change every entry by new naming, don't forget tests.

Then think about removing generators from the main namespace. I don't see any advantages, but may be I'm wrong. 

Good luck!

**Comment by jtorrents** [comment]
@SanketDG I think this is a good issue for a beginner; you'll have to familiarize yourself with the package structure, the tests and the documentation of NetworkX. I'll try to lay out the steps:

1. Move `networkx/generators/bipartite.py` to `networkx/algorithms/bipartite/generators.py`. Also move their tests to the bipartite test directory: `networkx/generators/tests/test_bipartite.py` to `networkx/algorithms/bipartite/tests/test_generators.py`.

2. Change generator functions names removing the `bipartite_` prefix (I think that `complete_bipartite_graph` should have the same name). And adapt all code to the new generator function names; you'll have to change for sure the bipartite generator tests, but maybe also in other places. You can grep the sources or just run the test suite locally and see where it fails. For instance, `networkx/generators/classic.py` imports `complete_bipartite_graph`, you will have to adapt the import to the new location.

3. Modify the documentation of each bipartite generator function to explain that now the user will have to explicitly import the bipartite package to use the biartite generators. Adapt the examples in the docstrings.

4. Move the documentation of bipatite generators from `doc/source/reference/generators.rst` to `doc/source/reference/algorithms.bipartite.rst`

5. Edit `networkx/algorithms/bipartite/__init__.py` to load all generator functions when the bipartite package is imported.

6. Edit  `networkx/algorithms/__init__.py` to import at least `complete_bipartite_graph` from the bipatite package to the main namespace. Try to figure out if we need to import something else.

Regarding removing generators from the main namespace, we are trying to clean a bit the main namespace because it's overpopulated now.  It's a way to improve the organization of the code base.

**Comment by jtorrents** [comment]
Oh, I forgot to add:

7. Edit `doc/source/reference/api_2.0.rst` to explain the changes in bipartite generators for the new release.

**Comment by SanketDG** [comment]
Thank you @jtorrents for the detailed instructions.

I have been able to do all of them except for 5. Should I just add a note about importing `nx.algorithms.bipartite`. Also, I couldn't understand what you meant about adapting the examples in the docstrings.

Since I have done most of the work, will it be okay if I submit a pull request? So that you can check the code?

I will edit the `doc/source/reference/api_2.0.rst` after everything else is okay and ready to be merged.

**Comment by jtorrents** [comment]
@SanketDG yes, please submit a PR with what you did so far and we'll figure out the remaining details.

**Comment by SanketDG** [comment]
Done. `nosetests` show `Ran 2566 tests in 40.545s OK (SKIP=10)`

Please review the diffs.
