### ISSUE TITLE
overlap_weighted_projected_graph incorect values for Jaccard coefficients

### ISSUE THREAD

**Issue by JBPressac** [networkx/networkx#1387]
Hello,
The following code:
```
DSW = nx.davis_southern_women_graph()
DSW_jaccard = bipartite.overlap_weighted_projected_graph(DSW,DSW_women_list,jaccard=True)
```
returns a matrix with a diagonal filled with zeros while it should be filled with ones. In fact, the Jaccard value for pairs with the same person should be 1 rather than 0 (the same person is 100% similar to herself, not 0%).

**Comment by jtorrents** [comment]
Hi @JBPressac, the function `bipartite.overlap_weighted_projected_graph` returns a unipartite (or one-mode) graph from an input bipartite graph. Bipartite projection consists in creating a graph where each pair of nodes of one node set is linked with an edge if they share one or more common neighbors in the original bipartite graph. The jaccard coefficient here is a way to assign weights to the projected edges (number of nodes in the intersection of their neighborhood in the original bipartite graph divided by the number of nodes in the union). Thus, the diagonal of the adjacency matrix of the projected graph (which refers to self-loops) should not be in play.
