### ISSUE TITLE
Can't import networkx package in PyCharm.

### ISSUE THREAD

**Issue by SanketDG** [networkx/networkx#1388]
I have been trying to get started with networkx in pyCharm v4.0.4. But whenever i try to import the `networkx` package, I get this error message:

![](http://i.imgur.com/hclsvU2.png)

Help would be appreciated. Thanks.

**Comment by MridulS** [comment]
@SanketDG http://stackoverflow.com/questions/27841396/cannot-import-release-from-networkx. Try reinstalling it.

**Comment by SanketDG** [comment]
@MridulS I am using a clone of this repository. I want to work on the latest dev version.

Strange is, it works on the command line. Maybe I am missing a setting or something?

**Comment by SanketDG** [comment]
Never mind, I never did `python setup.py install` so it couldn't import.

**Comment by MridulS** [comment]
I am not that familiar with PyCharm so can't really comment on it.
