### ISSUE TITLE
Nodes tested for identity with `==` rather than `is`

### ISSUE THREAD

**Issue by khs26** [networkx/networkx#1392]
I found a bug in ```_bidirectional_pred_succ(G, source, target)```. I had overridden `__cmp__` for the object making up each node (they were meant to represent atoms and the graph represents atomic connectivity). This meant that two nodes could test positive for equality without being identical.

I realise that this is perhaps not a sensible thing on my part, but a quick substitution for ```is``` does the trick.

    def _bidirectional_pred_succ(G, source, target):
        """Bidirectional shortest path helper.
           Returns (pred,succ,w) where
           pred is a dictionary of predecessors from w to the source, and
           succ is a dictionary of successors from w to the target.
        """
        # does BFS from both source and target and meets in the middle
        ***if target == source:***
            return ({target:None},{source:None},source)
    
        ...
    
        raise nx.NetworkXNoPath("No path between %s and %s." % (source, target))

I will file a PR shortly, but I thought this issue could also arise elsewhere in the code and perhaps needs further investigation.

**Comment by ysitu** [comment]
No, please fix your code or keep the change to NetworkX to your own copy. A change to `target is source` will not be accepted. It breaks sane cases such as both `source` and `target` are strings.

**Comment by khs26** [comment]
Yeah, sorry, I closed this because I realised that it also affects list membership, which uses ```==``` too. I didn't mean to have it included in my old PR (related to something else). Still getting used to how Github PRs work.
