### ISSUE TITLE
`create_using` should be a class, not an instance of a class

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#1393]
The `create_using` idiom appears in several places throughout the code. As a keyword argument to, for example, the `from_numpy_matrix` function, it specifies the type of graph that will be returned. The function expects this keyword argument to be an _instance_ of a graph, and it proceeds to clear the graph and add nodes and edges to it.

Why should `create_using` be an instance of a graph class if it is just going to be cleared? Instead, `create_using` should be a graph _class_ which should then be instantiated by the function when creating the graph that it will eventually return. Not only does this make more sense with respect to way the keyword argument is being used, this way, the responsibility of instantiating the graph that will be eventually be returned moves from the caller to the callee: this helps to prevent the caller from fiddling with the object when it is being created.

**Comment by chebee7i** [comment]
I've desired this on occasion as well. Maybe we can meet partway and query if `create_using` is a callable, and if so, call it to create the instance to be populated?

**Comment by jfinkels** [comment]
Do you want to meet partway for backwards compatibility? With a major version increment coming up, this is a good opportunity to make non-backwards compatible changes. Is there a place in the code or tests where using an instance instead of a class is really required?

**Comment by MridulS** [comment]
I did a quick search with grep. I didn't find any place where instance is really required.

**Comment by ysitu** [comment]
If we are to do this, let's do it right, not with a mix of what we like and we don't like.

**Comment by chebee7i** [comment]
But suppose I have a graph already with some nodes and edges that was provided to me, and then I want to use some graph generator to add more nodes (I dont't want it cleared). It seems like callables and instances are equally valid use cases. If we don't support an instance, then the user would have to write a silly lambda function to return the instance. Both approaches seem fine to me, but checking if `create_using` is callable seems pretty simple for us to do. In fact, there might even be a few places where we already do such a check, not sure though.

**Comment by jfinkels** [comment]
That situation could be solved by taking the original graph, generating the new graph, and using one of the union or compose operators.

**Comment by chebee7i** [comment]
I might be thinking of the `weight` parameter wrt to existing code checking if it is callable.

**Comment by chebee7i** [comment]
@jfinkels those operators assume you want disjoint combinations, which may not be what is desired. I try to think of the generators as functions that add edges to the graph with a particular property, etc. In that sense, they should always be able to work with existing graphs---the final graph may not have the properties of the graph generator, but that is a decision the user made. Now whether existing graphs are supported directly or through a lambda function or similar, I could see it either way.

**Comment by hagberg** [comment]
I'll just come out from under the bridge again and say - I think we should consider abandoning the create_using= keywords completely.  There is an older discussion somewhere I'll try to dig up.
My biggest complaint are such allowed uses as passing a digraph into a generator that wants to create a graph or vice versa, etc, and any other Latin I can think of.  

I don't have a simple alternative to suggest for graphs that aren't connected.  (Connected graphs we can generate edges and use graph.add_edges_from().)

**Comment by chebee7i** [comment]
That could work too...then it would be up to the user to merge the returned graph with their existing graph. It isn't as efficient though. If I have a subclass and I want the generator to populate my subclass, it seems a shame to have to add all the edges twice.  

Regarding DiGraphs in generators that desire to create Graph-like objects, I see the concern, but I'm usually of the view that we should allow users to utilize the code we have written in as many ways as possible. It could be that the code used in, say, `nx.generators.gn_graph` could be useful in some unexpected context with undirected graphs or multi-digraphs. Without `create_using`, we either require the user to rewrite the code we have already written, or they will have to populate a DiGraph and then, on a second pass, add those edges to their desired graph.

**Comment by hagberg** [comment]
I was thinking that the graph generators would generate edges (now they are edge generators?).    That is, return a generator that you can pass to G.add_edges_from() so it would be efficient and simpler code.  That doesn't work for isolated nodes though.  Of course you could return both an edge generator and a node generator...

**Comment by jfinkels** [comment]
In response to viewing generators as "edge set generators", I think `nx.compose()` computes the union of the node sets and of the edge sets of two graphs, so if the node sets are the same, this will just add the edges from the generated graph to the original graph, right? This has the benefit of readability: it is more explicit to someone reading the code that you are adding the edges from the generated graph to the source graph. Plus it maintains the possibility of using a generator function to generate a graph.

**Comment by chebee7i** [comment]
Oh I see, so these wouldn't construct graphs at all...just a generator over edge tuples. How would that work in practice? Would the generator have to build a graph internally and then yield from `G_internal.edges()`? There's no way we can assume that the generator can generate all the edges on the fly without some intermediate graph-like storage. E.g. future edges might depend on graph properties induced by previously added (random) edges. So it seems like, in many cases, we would still have to add the edges twice in the "edge generator" paradigm---once internally and then once again externally. And even then, I think we'd have to adopt the most general solution and return both a node and edge generator.

**Comment by hagberg** [comment]
Yes, I haven't really thought this through.  But something like this

```python
def generate_path(n):
    nodes = iter(range(n))
    edges = ((v,v+1) for v in range(n-1))
    return nodes,edges

def path_graph(n):
    G = nx.Graph(generate_path(n)) # <- would need to modify constructor
    G.name="path_graph(%d)"%n
    return G
```

It could be that some algorithms require some memory of  previous edges but I couldn't think of them.

**Comment by ysitu** [comment]
@chebee7i 

> But suppose I have a graph already with some nodes and edges that was provided to me, and then I want to use some graph generator to add more nodes (I dont't want it cleared). It seems like callables and instances are equally valid use cases. If we don't support an instance, then the user would have to write a silly lambda function to return the instance. Both approaches seem fine to me, but checking if create_using is callable seems pretty simple for us to do. In fact, there might even be a few places where we already do such a check, not sure though.

```python
G = get_an_existing_graph()
G = from_numpy_matrix(A, create_using=G)
```

is just cryptic compared to

```python
G = get_an_existing_graph()
H = from_numpy_matrix(A, create_using=some_graph_class)
G.add_edges_from(H.edges(...))
```

**Comment by hagberg** [comment]
You'd also need a 
`G.add_nodes_from(H.nodes())`
there.

Should we consider G.add_graph() that takes a graph or a tuple of (nodes,edges)?

**Comment by ysitu** [comment]
@hagberg Maybe `G.merge_graph(H)` or `G.update_graph(H)` a la `dict.update`?

**Comment by chebee7i** [comment]
@ysitu No argument there. :) I'm liking the direction this is going.

**Comment by jfinkels** [comment]
`update_graph` is good, but again, it is essentially the `compose` function.

**Comment by hagberg** [comment]
I'd like to pursue this .  It might make it simpler and clearer.  Anyone have more thoughts?

The current strawman in something like @ysitu suggests for G.update(H) or G.update_graph(H) perhaps with the ability to take a graph or a (nodes,edges) tuple.

**Comment by dschult** [comment]
Let's postpone create_using changes.

I have some ideas on better generators, better create_using and a more universal packaging of graph (a GraphBox?). For example, perhaps a GraphBox is just a tuple ```(nodes, edges)``` or for more universal treatment a tuple ```(graphattr, nodes, edges, succ, pred)``` with None in any of those position. 

I know Aric has thought about improvements to the graph structure/conversion system along these lines and mentions some of that above.

But I don't think we are ready to put even the ```create_using``` ideas into practice for v2.0.

I'm going to move this issue to v2.1 and open a v-future issue for a GraphBox transportation system.  If people think we should do something for v2.0 on this please post something here.

**Comment by hagberg** [comment]
Deferred, needs design decisions.

**Comment by dschult** [comment]
This discussion should be continued in #3036.  With #3004 and #3028 we have the building blocks for many of the ideas here.
