### ISSUE TITLE
Check of create_using type in __prep_create_using 

### ISSUE THREAD

**Issue by alexnikleo** [networkx/networkx#1395]
In this code part we make a conclusion of type based on having clear() method.
```python
    try:
        create_using.clear()
    except:
        raise TypeError("Input graph is not a networkx graph type")
```
It can lead to some bugs in future. 
It would be better to check up type with some other ways. For example, by ```inspect``` module.

What do you think about it?

**Comment by hagberg** [comment]
I usually advocate to remove the create_using() idiom here - #1393 etc.
But I don't have consensus on a replacement plan yet.

**Comment by hagberg** [comment]
continue at #1393
