### ISSUE TITLE
Order betweenness centralities together

### ISSUE THREAD

**Issue by Michael-E-Rose** [networkx/networkx#1397]
Betweenness centralities (as listed on https://networkx.github.io/documentation/latest/reference/algorithms.centrality.html#betweenness) all measure how many paths go through a certain node. There are different definitions of paths. The original betweenness centrality takes the shortest path.

Alternative path definitions are [`communicability_betweenness_centrality()`](https://networkx.github.io/documentation/latest/reference/generated/networkx.algorithms.centrality.communicability_betweenness_centrality.html#networkx.algorithms.centrality.communicability_betweenness_centrality) (all paths between two nodes) and [`load_centrality()`](https://networkx.github.io/documentation/latest/reference/generated/networkx.algorithms.centrality.load_centrality.html#networkx.algorithms.centrality.load_centrality) (all paths between two nodes, but kind of weighted).

Therefore I propose to sort these centralities together. [`doc/source/reference/algorithms.centrality.rst`](https://github.com/networkx/networkx/blob/master/doc/source/reference/algorithms.centrality.rst) is the respective file. Maybe the "See also" sections of each of these centralities should be updated as well.

**Comment by hagberg** [comment]
Let's straighten out the names and algorithms in #1239 first.
I prefer not to have the modules be too big but we can adjust the documentation so it is clearer.

**Comment by hagberg** [comment]
Continue at #1239

**Comment by Michael-E-Rose** [comment]
Thanks for reopening :) For further reference: I'm going to work on this issue (i.e. update the docs) once #1239 is live.

**Comment by hagberg** [comment]
What do we need to do on #1239?

**Comment by hagberg** [comment]
Now that #1239 and #1958 are done is there anything left to do here?

**Comment by Michael-E-Rose** [comment]
I'd say so and I'm working on a proposal right now!

**Comment by Michael-E-Rose** [comment]
PR is live. Not a big deal, but a minor improvement at least, I hope.
