### ISSUE TITLE
Graphml default attribute values are not applied

### ISSUE THREAD

**Issue by AgostinoSturaro** [networkx/networkx#1398]
It seems default attribute values for custom graphml attributes are not applied, when loading a graph.

Here is a test case

```
import networkx as nx

G = nx.read_graphml("colored.graphml")

for node in G.nodes():
    print(G.node[node]['color'])
```

Here's the input graphml file, a simplified version of this [official example](http://graphml.graphdrawing.org/primer/graphml-primer.html#AttributesExample).

```
<?xml version="1.0" encoding="UTF-8"?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns"  
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns 
        http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
  <key id="d0" for="node" attr.name="color" attr.type="string">
    <default>yellow</default>
  </key>
  <graph id="G" edgedefault="undirected">
    <node id="n0">
      <data key="d0">green</data>
    </node>
    <node id="n1"/>
  </graph>
</graphml>
```

Here is an error showing that the default "yellow" value was not applied.

```
green
Traceback (most recent call last):
  File "C:/Users/sturaroa/Documents/PycharmProjects/node_labeling_test.py", line 16, in <module>
    print(G.node[node]['color'])
KeyError: 'color'
```

**Comment by hagberg** [comment]
I wonder if that is an error.  Should the default attributes be applied to every node or edge?
I would say no.

 The default value is captured in the G.graph atribute

```python
In [1]: import networkx as nx

In [2]: G = nx.read_graphml('colored.graphml')

In [3]: G.graph
Out[3]: {'edge_default': {}, 'node_default': {'color': u'yellow'}}
```

You could apply the default to your nodes like this

```python
In [4]: default_color=G.graph['node_default']['color']

In [5]: for node,data in G.nodes(data=True):
   ...:     if 'color' not in data:
   ...:         data['color']=default_color
   ...:         

In [6]: G.node
Out[6]: {'n0': {'color': u'green'}, 'n1': {'color': u'yellow'}}
```

**Comment by AgostinoSturaro** [comment]
I would prefer if the default value was automatically applied when no other value is specified.

Here is [a better link](http://graphml.graphdrawing.org/primer/graphml-primer.html#AttributesExample) describing this behavior.

If it's not applied as a default value, then it's not a default value anymore, IMHO.

Thank you for the quick solution.

**Comment by hagberg** [comment]
I don't know what drawing tool made the diagram on that page but it clearly applies default values.
The matplotlib drawing package in networkx doesn't do that (among many shortcomings).  

But if we apply the default values when reading the GraphML file then writing the file will create a different output than the original.  That probably isn't the desired behavior.

**Comment by AgostinoSturaro** [comment]
Drawing aside, when I load a graph reading a graphml file, I expect to find the all attribute values defined. Having to manually check for the missing default values kinda defeats the purpose of having a default value to start with.

Right now I'm using the default value to avoid specifying the value each and every time. If 80% of edges have "weight=1.0", then I set the default value to "1.0" and specify it only for edges with a different weight.

When I read a graphml, if it defines a default value of "1.0" for the edge weight, I expect the edge weight to default to 1.0, unless there's a different weight explicitly stated. What I do not expect is to end up with most edges with "weight=undefined".

**Comment by chebee7i** [comment]
I see the "intuition" gap, and also from an efficiency perspective. We could make the documentation clearer and provide the code @hagberg suggested as an exapmle, or maybe we could consider an `apply_defaults` argument, which defaults to `False`.

**Comment by hagberg** [comment]
The problem is that the NetworkX/Matplotlib drawing solution isn't comprehensive. 
I don't think we should fix that by messing around with the GraphML reader and writer.

An example is fine though.

**Comment by AgostinoSturaro** [comment]
@hagberg thanks for the example.

I would appreciate having a function to apply the default values when loading a graph, so I can use it straight away, knowing all nodes (and edges) attributes have been initialized.

Thanks.

**Comment by hagberg** [comment]
You can set the default attributes to output as GraphML.  Need a PR with some examples here instead of code fixes.

**Comment by AgostinoSturaro** [comment]
@hagberg you mentioned that if `read_graphml` applied the defaults when loading the graph, then `write_graphml` would write a different files. The solution I propose is to have the `write_graphml` aware of the defaults, as in, "only write a value if it differs from the default".

Moreover, having `write_graphml` recognize the default values and only write values different from the defaults would save quite a bit of space and probably speed it up as well (writing to disk is slower than performing equality checks in memory).

To maintain backward compatibility, a parameter `apply_defaults=False`, as @chebee7i mentioned could indeed be useful.

If the defaults are actually applied to nodes (and not just memorized as graph properties), then matplotlib won't have any problems drawing the graph. I mean, if the default color for a node is yellow, then do:

    G.graph['node_default'] = {'color': 'yellow'}  # already done
    for node_id in G.nodes()  # apply defaults (to do)
        G.node[node_id]['color']

Thanks.

**Comment by kiryph** [comment]
To apply all node and edge default attributes one can use following snippet:

```python
# Expand Default Attributes
for node, data in G.nodes(data=True):
    for k, v in G.graph['node_default'].items():
        if k not in data:
            data[k] = v

for u, v, data in G.edges(data=True):
    for k, v in G.graph['edge_default'].items():
        if k not in data:
            data[k] = v
```
