### ISSUE TITLE
ford_fulkerson not deprecated from 1.9.1 documentation

### ISSUE THREAD

**Issue by mjbommar** [networkx/networkx#1401]
Hello,
 Even though 66d67489f221b7142165a55f474fdb4a46e4ce7a removed the Ford-Fulkerson method from ``algorithm.flow``, the documentation (as of 1.9.1) still contains references to the method.

**Comment by mjbommar** [comment]
To clarify, a student with Anaconda who installed ``1.9.1`` from source is unable to perform the import from ``algorithm.flow`` as the ``doc/source/reference/api_1.9.rst`` indicates is still possible.

**Comment by mjbommar** [comment]
I'm seeing that this is still in 1.9.1 source, so will close.  Not sure how the student could have gotten ``__version__=='1.9.1'`` but not been able to get the doc import to work.

**Comment by jtorrents** [comment]
Indeed `ford_fulkerson` is still in 1.9.1. In any case, note that this same algorithm is now implemented at the function [edmonds_karp](https://networkx.github.io/documentation/latest/reference/generated/networkx.algorithms.flow.edmonds_karp.html). It's part of the new NetworkX flow API and the output will be a bit different, but the new API is much more powerful (eg you can use different flow algorithms by passign a function as an argument to `nx.maximum_flow` and friends). And for some problems (especially repeated computatcions over different pairs of nodes on the same graph), the new implementation is much, much faster.
