### ISSUE TITLE
int' object has no attribute 'copy' - MultiDiGraph

### ISSUE THREAD

**Issue by beyssac** [networkx/networkx#1403]
Hi,

I was trying to write a .Net (Pajek) file with generate_pajek() and I got an error when passed MultiDiGraph as parameter:

'int' object has no attribute 'copy'

It does not happen when I pass DiGraphs

PS: Both cases the graphs had edges having attributes 

Thanks,
Pedro Henrique

**Comment by dschult** [comment]
Can you provide a (hopefully small) example that reproduces the error?

**Comment by beyssac** [comment]
Of course:
![image](https://cloud.githubusercontent.com/assets/2438843/6719105/3718f646-cd97-11e4-9e05-e951b253c7c4.png)

Sorry about the image instead of text.

**Comment by hagberg** [comment]
With a multgraph you can't set `graph.edge[source][target][attr]` directly.  There is an additional 'key' level so it is `graph.edge[source][target][key][attr]`.

But we don't recommend setting data attributes this way.  A better way is to use 

```python
graph.add_edge(source,target,attr_dict=jsonGraph['edge']['source][target])
```

(I am assuming your jsonGraph graph is a dictionary).

**Comment by beyssac** [comment]
I think that I understood.
Is it because of parallel edges, isn't it? I had forgotten that.
But It works....in spite of the fact that is wrong.

So:
The function generate_pajek is trying to get a copy() of a empty int, isn't it?

Thank you, Hagberg

**Comment by hagberg** [comment]
It doesn't produce an error. But it corrupts the internal data structure which then produces the error you get in generate_pajek().

**Comment by beyssac** [comment]
That's true!
Thank you very much!
