### ISSUE TITLE
add functions that return the largest (bi)connected component

### ISSUE THREAD

**Issue by jtorrents** [networkx/networkx#1404]
Since `[bi]connected_components` and friends do not yield components sorted by their order, we could add functions to get the largest connected component. It's a quite common operation to build a graph somehow and only use the giant connected component for some analysis. Now it requires:

```python
G = build_graph_somehow()
Gc = max(list(nx.connected_component_subgraphs(G)), key=len)
# It could be something like
Gc = nx.largest_connected_component(G)
``` 

A dedicate function, with another for `biconnected_components`, will enhance readability and reduce the verbosity of the code for a common operation. 

However, it might be confusing that a function named `largest_connected_component` returns a graph, given that `connected_components` yields sets of nodes, if you want graphs, you have to use `connected_component_subgraphs`. I'd rather not have `largest_connected_component` and `largest_connected_component_sugraph`, but I think that the inconsistency with the rest of the components API would be worse than having a couple more functions. Thoughts?

Also, I think that this is not a complicated addition (once we decide if we add them and how), so it would be a good oportunity to contribute to NetworkX for the first time.

**Comment by hagberg** [comment]
I'm for adding "largest_connected_component".

As for the naming I prefer nx.connected_components() return subgraphs not nodes.
(That isn't backward compatible but it is more consistent with graph terminology, right?).



To get nodes you could simply say, e.g. nx.largest_connected_component(G).nodes()

**Comment by chebee7i** [comment]
Agreed that it would be nice to just return the graphs, but there are performance concerns. Building a graph is much slower than just returning the nodes in the graph, and sometimes you really only need the nodes.

As for breaking backwards compatibility, I think we should resist the urge to turn 2.0 into a massive (more massive than necessary) backwards compatibility breakage mess.  We need to make it as easy as possible for users to migrate or we will have the Python 2.x/3.x all over again. 

While I could be persuaded, I think this change should not happen in 2.0, which is already breaking enough compatibility. We could announce a deprecation warning in 2.0 that says in 2.1 (or 2.2) the behavior of `nx.connected_components` is set to change and instruct the users how they can adjust their code now to prempt the change.

**Comment by SanketDG** [comment]
Can I take this up? I could use some help about where to add the `largest_connected_component` function.

**Comment by jtorrents** [comment]
@SanketDG , sounds good. But first we have to figure out what exactly we want to do.

@hagberg, my preference is also for `connected_components` and friends to return graphs, but @chebee7i raises good points. I'm more concerned with speed than backwards compatibiity. I think that most of the code that expects nodes from `connected_components` would work unmodifyed if we yield graphs instead (this is based on uses of `connected_components` in my code, not sure how generalizable this observation is). But yielding nodes is a lot faster:

```python
In [19]: G = nx.fast_gnp_random_graph(10000, 0.001)

In [20]: nx.is_connected(G)
Out[20]: False

In [21]: %timeit list(nx.connected_components(G))
100 loops, best of 3: 16.7 ms per loop

In [22]: timeit list(nx.connected_component_subgraphs(G))
1 loops, best of 3: 256 ms per loop

In [23]: %timeit list(nx.biconnected_components(G))
10 loops, best of 3: 73.1 ms per loop

In [24]: %timeit list(nx.biconnected_component_subgraphs(G))
1 loops, best of 3: 313 ms per loop
```

Thus I think we should keep functions that return nodes, but maybe we could change names: `connected_components` -> yields graphs, `connected_components_nodes` -> yields nodes, `connected_component_subgraphs` -> alias to `connected_components` to ease the transition. With this I think that we'll not break a lot user code, but it's true that users will have to keep in mind the changes on `connected_components` and firends.

So maybe waiting for the next release + 1 is a good idea, but if we decide to wait and do not change the components API, I think that `largest_connected_component` should obey it and thus we should have two functions, one that returns a graph and one that returns a set of nodes.

**Comment by hagberg** [comment]
The timing tests are quite as bad if you use `copy=False` for `connected_component_subgraphs`.
But still more than 2 times slower than `connected_components`

**Comment by jtorrents** [comment]
In my machine with `copy=False` connected components is x3 slower and biconnected components x1.7 slower when returning subgraphs. Indeed, not as bad as deep copying everything as we do now by default. I think that, as suggested by @Midnighter at #1164 , we should extend @ysitu approach in that PR to `subgraph` and use shallow copy or structure copy by default almost everywhere. Maybe we can start with making `copy=False` the default in `[bi]connected_component_subgraphs`.

**Comment by ysitu** [comment]
If `nx.largest_connected_component` is merely a shorthand for `max(nx.connected_component_subgraphs(G), key=len)`, I do not see a pressing need for it. `max(...)` works, is already concise and is extensible. You can define "largest" in terms of number of nodes, number of edges, node/edge weight, average node/edge weight, etc., etc.

**Comment by jtorrents** [comment]
Well, is true that is one of many useful one liners, and most of them do not require a dedicated function. But I think this is a good candidate because, it's very useful in interactive sessions doing exploratory analysis, and there, the number of keystrokes is much lower for a dedicated function due to tab completion: `Gc = nx.lar[tab]`. Moreover, from an efficientcy point of view, an user might be tempted to use sort for getting the largest connected component (which is `O(N log(N))`) instead of using `max` (O(N)).

But I assume that everyone has their favorite one liner that would want to see as a function. I'm ok in defining this function locally in my projects.

**Comment by hagberg** [comment]
After thinking about this I agree with @ysitu that this is a one-liner that should be an example (it's very useful).  I'd like to see many more examples liek this as IPython notebooks....

**Comment by jtorrents** [comment]
Ok, sound good. I'll keep this function locally for my projects. 

I'll open an issue for refactoring the components API (for `networkx-future`) as a reminder of the discussion that we had here about removing `*_subgraphs` functions and make `connected_components` return subgraphs.

**Comment by Michael-E-Rose** [comment]
Sorry guys to add a comment to an already closed issue, but I disagree with ysitu's claim: 
> You can define "largest" in terms of number of nodes, number of edges, node/edge weight, average node/edge weight, etc., etc.

It's not. Scientific work and handbooks (on (social) network analysis) only speak of a giant component in terms of the number of nodes. Additionally, the largest connected subcomponent is always called the giant component. See for example [this handbook chapter of J. de Martí and Y. Zenou](http://www.iza.org/en/webcontent/publications/papers/viewAbstract?dp_id=4621).

Furthermore, the giant component is quite important in scientific work because it often stands as representative for the entire network, at least when we need centralities. Everyone knows, centralities can only be calculated for connected components. We think it's still better to use centralities of the giant component than none at all. An example is [this](https://ideas.repec.org/a/ucp/jpolec/v114y2006i2p403-432.html) Journal of Political Economy paper by S. Goyal, M. J. van der Leij and J. L. Moraga-Gonzalez.

In total, the giant component is widely used in scientific work and networkx would definitely do us a favor when implementing such a function, even though it's a one-liner for a one-liner (which networkx already has, btw.).

**Comment by jtorrents** [comment]
@Michael-E-Rose I agree, but the one liner to get the largest connected component is quite straightforward and readable:
```python
Gc = max(nx.connected_component_subgraphs(G), key=len)
```
This is now documented in the docstrings of `nx.connected_components` and friends (see #1501). NetworkX policy is to not include one liners as functions but explain them in the documentation.
