### ISSUE TITLE
problem in spring layout

### ISSUE THREAD

**Issue by ginger954** [networkx/networkx#1409]
Hi,
I want to report an problem in the spring layout algorithm in 1.9.1, which tend to print distorted layout of network. For example, if you try the following piece of code, you will find two or three nodes are distant from the cluster, which is highly centered in the middle. I did some investigation. If the line pos=_rescale_layout(pos) is removed from the for loop in  both _sparse_fruchterman_reingold and  _fruchterman_reingold methods, then the layout will look good. I am not sure how exactly it causes the problem, but hope it helps to solve the problem in the future edition. 

import networkx as nx
import matplotlib.pyplot as plt
G = nx.gnp_random_graph(100,0.2)
pos=nx.spring_layout(G)
nx.draw(G, pos=pos)
plt.show()

yongren

**Comment by hagberg** [comment]
I guess what must be happening is that two or three nodes are disconnected from the rest of the graph. This isn't the case all of the time since the gnp_random_graph() generator produces random graphs with varying structure.

There is not really a great fix for this.  You might consider using pygraphviz or pydot to do the position layout (e.g. pos = nx.graphviz_layout(G)).

**Comment by ginger954** [comment]
Thanks for your response. I also want to let you know is that the layout algorithm works fine in networkx 1.7, so I guess there should be unintended changes in 1.1.9.

**Comment by hagberg** [comment]
If you can show an example of incorrect behavior we can look into it.

**Comment by ginger954** [comment]
I did have an example in the original post. You can run it on the system
with networkx 1.9.1 and 1.7. I also attached two plots that are generted
from these two versions of networkx for comparison.

**Comment by hagberg** [comment]
The example is non-deterministic so I might not be seeing what you are seeing.  And I don't see the attached plots.
