### ISSUE TITLE
networkx.info() can't handle directed networkx

### ISSUE THREAD

**Issue by Michael-E-Rose** [networkx/networkx#1410]
The `info()` function (I know, it's not officially mentioned in the docs for 1.9.1) yields wrong results for directed graphs. The error is that average in degree and average out degree are the same.

    G = nx.DiGraph()
    G.add_nodes_from(range(0,10))
    G.add_path([0,1,2,3,4,5,6,7,8,9])
    nx.info(G)

> 'Name: \nType: DiGraph\nNumber of nodes: 20\nNumber of edges: 9\nAverage in degree:   0.4500\nAverage out degree:   0.4500'

**Comment by dschult** [comment]
average in degree and average out degree should be the same... right?

(also, your output has 20 nodes for some reason---should be 10?)

**Comment by Michael-E-Rose** [comment]
I came up with a little calculation on a star network with 5 nodes (where the center node attracts all directed links), and then realized that I expect the wrong information from `info()`.

In the example network, the center node has in-degree 4, out-degree 0, while the other four nodes have in-degree 0, out-degree 1. I expected information like *Average in-degree: 4 Average out-degree: 1*. Hence, a mean excluding the zeros.

But I see, this information would be too much for a little info display.
