### ISSUE TITLE
NetworkX logo proposal

### ISSUE THREAD

**Issue by gcetusic** [networkx/networkx#1411]
After several years of development, networkx still doesn't have a logo as commented in #1170. After playing with a logo idea and a somewhat positive reaction on the  GSOC gitter page, I've decided to propose at least a temporary logo and open a discussion. Here is the proposed logo: https://github.com/gcetusic/gcetusic.github.io/blob/master/images/networkx3.svg. Variations of this are the other networkx*.svg files.
![networkx3](https://cloud.githubusercontent.com/assets/1023690/6686517/861f2f62-cca2-11e4-9c61-ce1bea18a42f.png)

I know it's not the most exciting thing to do on a project but I think it's worthwhile to spend a little effort to make a logo so please voice your opinion. Before commenting on this, please fill in the form if you haven't already: http://goo.gl/forms/kALqCq4dFn

@chebee7i @jtorrents @hagberg @ysitu @dschult @loicseguin @bjedwards

**Comment by jtorrents** [comment]
I like it! Good job @gcetusic! Did you build it with actual NetworkX + matplotlib code or is it a drawing?

**Comment by OrkoHunter** [comment]
Nice job @gcetusic. The way it says 'Nx' using graph is really a good idea! I don't know whether it is the best color combination, but did you try making it simply black and white?

**Comment by gcetusic** [comment]
@jtorrents It's a vector drawing in Inkscape but there's an idea! I could do that once we decide on the logo
@OrkoHunter I can try with that - here's my first try https://github.com/gcetusic/gcetusic.github.io/blob/master/images/networkx.svg

**Comment by OrkoHunter** [comment]
As the edges got thinner and black, it looks better, I think.

**Comment by jtorrents** [comment]
@gcetusic I was only curious. I think is OK if the logo is not actually generated via nx + matplotlib (but would be cool indeed!).

**Comment by ysitu** [comment]
LGTM. But perhaps you can hand-roll the SVG to avoid the Inkscape bloat.

**Comment by soh-i** [comment]
:+1:

**Comment by hagberg** [comment]
It would be nice to have some other ideas for logos.  They don't have to be literal (graphs) or based on the text in "networkx".    e.g. https://github.com/logos

**Comment by gcetusic** [comment]
I agree and if I get any ideas for the logo, I'll propose them here but I'm not a graphics designer and Github's octocat is slightly more complicated so progress is generally slow. In any case, if no one here has any experience with tools like Inkscape and GIMP or Photoshop, I'd be willing to create the logo based on sketches other people propose :)

**Comment by OrkoHunter** [comment]
Maybe we can ask our close friends who come to be experts in Photoshop. I have some.

**Comment by harrymvr** [comment]
For us, programmers, it feels almost natural to think algorithmically and transform our abstract ideas into code. In the same way, when designers are working for a logo, they follow a thought procedure that seems almost subconscious to them. However, when it comes to programming, even if they learn how to write Python, it will require a lot of time and effort before they get accustomed into our way of thinking. 

My opinion is that if we are indeed interested into getting a logo (it shouldn't be a priority, only a few packages have one), we should ask a designer to create one, as it will become the single representative and most recognizable image for networkx.

**Comment by sieben** [comment]
:+1:

**Comment by jg-you** [comment]
My proposal (good way to blow off a friday afternoon with "work" :D)
![networkx_logo](https://cloud.githubusercontent.com/assets/6925003/7208304/cfc39206-e50d-11e4-9b78-b14a5847a951.png)

**Comment by ysitu** [comment]
@jg-you Looks nice. Took the colors from the Python logo?

**Comment by jg-you** [comment]
@ysitu Yes

**Comment by OrkoHunter** [comment]
@jg-you Nice ones. Did you try thinner lines in the 'N'? I feel some need of it.

**Comment by MridulS** [comment]
@jg-you :+1:

**Comment by sieben** [comment]
Could we combine both?

**Comment by soh-i** [comment]
@jg-you its sweet... :+1:

**Comment by jg-you** [comment]
@OrkoHunter Great suggestion, looks way better with a thinner "N"
@sieben  I don't really see how it could be done :/.

![networkx_logo_thin](https://cloud.githubusercontent.com/assets/6925003/7216083/ccb0dbf2-e5bf-11e4-865e-29e6d243b346.png)

**Comment by OrkoHunter** [comment]
It looks very nice. If I vote for the one in white.

**Comment by chebee7i** [comment]
Probably both are useful. Is this vector or raster?

**Comment by gcetusic** [comment]
The latter's "N" with the dark background could turn out great as a favicon.

**Comment by jg-you** [comment]
@chebee7i  It's a svg vector image.

**Comment by jg-you** [comment]
Apologies for the spam, I asked for advises from a designer friend; she recommends this thinner version: (I included some favicon as well)
![v3](https://cloud.githubusercontent.com/assets/6925003/7244101/4f2b41e0-e7a4-11e4-87a4-ae2a5515038e.png)

If there is interest toward making this official or temporary, let me know where I need to place the favicon, svg version, full res version, etc.

**Comment by SanketDG** [comment]
This really looks professional. Given that the X and N are already being shown in the logo, may be tone down the size of the last x? Would love to see this implemented.

**Comment by jg-you** [comment]
![g9167-1](https://cloud.githubusercontent.com/assets/6925003/7600341/39e8ce2a-f8d8-11e4-8f0c-25792c024dd1.png)

@SanketDG Sorry for the delay, had not checked on this issue for a while.

**Comment by SanketDG** [comment]
Um, yeah, the one with the large X looks better. But still the large X just looks a little more prominent than it should. Just a thought.

**Comment by python27** [comment]
cool

**Comment by chebee7i** [comment]
@hagberg is the X in NetworkX related to the X division?  Do they have any special ways of visualizing the X that we might latch onto?

**Comment by hagberg** [comment]
The X just stands for X.  Like Planet X.

**Comment by chebee7i** [comment]
Do we want to move forward on this? It's been sitting a while, and I think we should be able to make a decision. 

Personally, I don't think any positive decision we make has to be permanently binding---we can always change logos in the future. While the logo is literal in a sense, it also looks nice. So I am for adopting it as a logo, and if someday we come up with something different that we'd like to use, then so be it.

**Comment by hagberg** [comment]
I was hoping somebody might come up with something a little less literal.

If we want to use this logo I suggest separating the NX symbol part from the text and use transparent background (no background).  Then create two versions of the logo - 1) just the symbol and 2) the symbol with the letters "networkx" following it on the right.  Just like the Python logo...

**Comment by chebee7i** [comment]
I like the idea of making the symbol separate from the name, and this indeed makes having a non-literal logo a bit more important. I wonder if something like a preferential attachment graph that shows a maximum spanning tree highlighted could do the trick. Maybe the spanning tree could spell networkx? That last part would probably not be legible.

**Comment by jg-you** [comment]
![nx](https://cloud.githubusercontent.com/assets/6925003/8123144/447621ae-1092-11e5-8feb-7562d5c6805b.png)

![nx_text](https://cloud.githubusercontent.com/assets/6925003/8123147/5b5e0134-1092-11e5-9be3-3093509a71d3.png)

**Comment by jg-you** [comment]
And here is the svg, sorry about the slow response time.

https://github.com/jg-you/jg-you.github.io/blob/master/img/nx.svg

**Comment by MridulS** [comment]
Any decision on this ?
