### ISSUE TITLE
Expose `transitive_clousure` and `antichains` in the public API

### ISSUE THREAD

**Issue by jtorrents** [networkx/networkx#1412]
Working on #1391 we found that it would be useful to expose `transitive_clousure` and `antichains` (now two helpers for the `all_node_cuts` function) in the public API. We can move them to `algorithms/dag.py` and add proper documentation and tests.

The function `antichains` was contributed by Peter Jipsen and Franco Saliola, from the SAGE project, they also send me a reference for their implementation: Free Lattices, by R. Freese, J. Jezek and J. B. Nation, AMS, Vol 42, 1995, p. 226. Any suggestion for references for the `triadic_clousure` function? The implementation used in #1391 is based on David Eppstein's [PADS/partial_order.py]( http://www.ics.uci.edu/~eppstein/PADS/PartialOrder.py) but there is no reference there. 

We still do not have labels for difficulty, but I think this one is easy. If someone wants to take this I can review the changes.

**Comment by MridulS** [comment]
@jtorrents I am on it :)

**Comment by jtorrents** [comment]
@MridulS great!
