### ISSUE TITLE
GSoC sign-up at Melange

### ISSUE THREAD

**Issue by ysitu** [networkx/networkx#1416]
@hagberg @dschult @bjedwards @Midnighter @SanketDG @rashoodkhan @OrkoHunter @leliel12 @gcetusic @MridulS and anyone who anticipates to get involved somehow (formally or informally)

Mentors:
I presume that mentor sign-up should be done by now. I lost track of Google's and PSF's deadlines for that. If you have not signed up, you probably want to do that ASAP. (Note: Besides registering on Melange, you also need to request connection with PSF and fill out a [form](http://goo.gl/forms/PMXVM1CUAS).)

Students:
Melange is now accepting student applications (my inbox has been flooded by forwarded copies of those). You need to use PSF's [template](https://wiki.python.org/moin/SummerOfCode/ApplicationTemplate2015) and have until Mar 27 7pm UTC (firm deadline) to finalize the submission. Review PSF's [GSoC page](https://wiki.python.org/moin/SummerOfCode/2015) for any needed information.

Am I missing anything?

**Comment by OrkoHunter** [comment]
Thanks for letting us know. I'm still working on my proposal. I'll push it to the melange as soon as I'm done with the initial draft.

**Comment by bjedwards** [comment]
I assumed that since it looks like we have more active/senior developers acting as mentors I did not register. Can you guys handle it from here on out?

**Comment by Midnighter** [comment]
I signed up both on melange and for the form and was accepted as mentor. I'm a little unclear about how we'll approach the selection process. Any recommendations?

**Comment by MridulS** [comment]
Would like to know your views and suggestions regarding my proposal at https://github.com/networkx/networkx/wiki/NetworkX-GSoC-2015-Application:-NetworkX-2.0-API---Mridul-Seth

**Comment by ysitu** [comment]
@bjedwards No worry. I think we will have enough capacity for at least one or two students.

@Midnighter I propose that we have an open review process but make decisions behind the door, with @hagberg making the final call. For review, neither GitHub nor Melange seems to be a good platform for comments and responses. Perhaps we should have copies of the documents on MS Word Online/Google Docs and archive them to the GitHub wiki after they are finalized.

**Comment by leliel12** [comment]
sorry the delay tomorrow i will end all the application.

2015-03-19 16:49 GMT-03:00 ysitu <notifications@github.com>:

> @bjedwards <https://github.com/bjedwards> No worry. I think we will have
> enough capacity for at least one or two students.
>
> @Midnighter <https://github.com/Midnighter> I propose that we have an
> open review process but make decisions behind the door, with @hagberg
> <https://github.com/hagberg> making the final call. For review, neither
> GitHub nor Melange seems to be a good platform for comments and responses.
> Perhaps we should have copies of the documents on MS Word Online/Google
> Docs and archive them to the GitHub wiki after they are finalized.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/networkx/networkx/issues/1416#issuecomment-83737090>.
>



-- 
Juan B Cabral

**Comment by MridulS** [comment]
@ysitu The project ideas page should also be updated with possible mentors for each project.

**Comment by ysitu** [comment]
@MridulS I have put together a [proposal summary page](https://github.com/networkx/networkx/wiki/GSoC-2015-proposal-summary) with potential mentor assignments, although frankly speaking, I do not know exactly who has signed up or is willing to take up which project.

@lucjon I saw your proposal on Melange. Please provide a copy in the wiki here to let more people see it.

Additional note to students: When you submit a your proposal to Melange, make sure that "NetworkX" is the first word of the title to make it easily discoverable (the "Title" column of Melange's proposal list is wide enough for just one word, sigh).

**Comment by MridulS** [comment]
@ysitu The potential mentors can confirm it @hagberg @dschult @ysitu @Midnighter @chebee7i  . And we should have at least 3 mentors signed up.

PS: Confirmed with Terri (PSF), 3 mentors have registered. She said that mentors can sign up well after the student deadline 27th March.

**Comment by Midnighter** [comment]
@ysitu that's the way I thought about the projects. I can definitely confirm that I'd like to mentor projects related to backends and linear algebra.

**Comment by ysitu** [comment]
Small update: According to Terri, we had five mentors signed up as of Mar 23.

**Comment by leliel12** [comment]
hi guy i going to decline my proposal. saddly i can't obtain the forms from
the university at time. If someone need to help on database abstraction
layers issues (Sqlalchemy, peewee, pydal, django-orm) i going to be on
touch.



2015-03-25 13:21 GMT-03:00 ysitu <notifications@github.com>:

> Small update: According to Terri, we had five mentors signed up as of Mar
> 23.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/networkx/networkx/issues/1416#issuecomment-86102803>.
>



-- 
Juan B Cabral

**Comment by gcetusic** [comment]
@Midnighter I've submited my backend proposal: http://www.google-melange.com/gsoc/proposal/review/student/google/gsoc2015/gcetusic/5707702298738688

It's basically the same one that you reviewed on the wiki page and said it looks good on gitter. That's it from me for now. Best of luck to other students applying :)

**Comment by Midnighter** [comment]
Hey everyone, what's our preferred way of reviewing proposals going to be? Comments and ratings on Melange, private gitter chatrooms per proposal or public issues per proposal? Something else entirely?

We have until April 13 to decide on the minimum and maximum number of slots and about a week after that we have to make final calls on the applications and decide on allocating mentors to students.

**Comment by ysitu** [comment]
@Midnighter Terri wants the slot count from us by Apr 10.

**Comment by Midnighter** [comment]
As mentioned in #1446 I will be away for the next few days. So yes, I forgot about the -48hrs for Terri :smile: I might be able to comment quickly on Friday but I think 2 slots is probably the most realistic.

**Comment by MridulS** [comment]
I think this can be closed now.
