### ISSUE TITLE
issue in draw_networkx_labels if label has key not in pos

### ISSUE THREAD

**Issue by joelmiller** [networkx/networkx#1417]
I was plotting a network with labels.  The dict of labels I created was defined for a larger set of things than just the nodes in the graph I was drawing.  That caused a problem here in draw_networkx_labels:

```
for n, label in labels.items():
    (x,y)=pos[n]
```

the key wasn't a key of pos.  This could be fixed by something like:

```
for n, label in labels.items():
     if n not in pos:
        continue
    (x,y) = pos[n]
```

Here's a discussion of possibly [better approaches](http://stackoverflow.com/questions/29139012/iterating-over-shared-keys-in-two-dictionaries) to this part: 

Further, I think it would be nice to be able to send a nodelist to draw...labels so that the user has a bit more direct control over what labels to draw without having to create a new dict for each case.

Here's some sample code:

```
G = nx.Graph()
G.add_node(1)
labels = {1:'a', 2:'x'}    
pos = nx.spring_layout(G)
nx.draw_networkx_labels(G, pos, labels = labels)
```

---

KeyError                                  Traceback (most recent call last)
<ipython-input-24-7cfdd938fadd> in <module>()
----> 1 nx.draw_networkx_labels(G, pos, labels = labels)

/Users/jomiller/anaconda/lib/python2.7/site-packages/networkx/drawing/nx_pylab.pyc in draw_networkx_labels(G, pos, labels, font_size, font_color, font_family, font_weight, alpha, ax, **kwds)
    709     text_items = {}  # there is no text collection so we'll fake one
    710     for n, label in labels.items():
--> 711         (x, y) = pos[n]
    712         if not cb.is_string_like(label):
    713             label = str(label)  # this will cause "1" and 1 to be labeled the same

KeyError: 2

**Comment by hagberg** [comment]
I'm not sure I like the silent "failure" that this fix would generate.  Say you think you have a node label 1 when you really have instead the string '1'.  You set labels ={1:'a'} but it never shows up....and there is no error.  

I'd prefer a better interface where e.g. you can apply labels by setting them explicitly as node attributes.

**Comment by hagberg** [comment]
Closed due to inactivity.
