### ISSUE TITLE
Using `not_implemented_for` decorator vs G.is_directed() or G.is_multigraph()

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#1419]
There are many algorithms which are defined only for certain kind of graphs. We can either check the type of graph in the algorithm itself by doing something like
``` python
if G.is_directed():
    raise some error
```

but a NetworkXNotImplemented error can also be raised by the decorator `not_implemented_for` by doing something like
``` python
@not_implemented_for('directed')
def func(arg1,arg2):
    ....
```
Which method is preferable?

**Comment by chebee7i** [comment]
I think we preferred using the decorator since the error messages are normalized. With the top method, the error message must be re-written each time (typos, different words, etc).

**Comment by MridulS** [comment]
@chebee7i  This is not uniform over the whole codebase. So, I think I can add this as a part of my GSoC project proposal to change this over the whole codebase. What do you think?

**Comment by chebee7i** [comment]
Sure, but it's not what I'd call high priority or anything, and it seems to be more in the "maintenance" category, closer to PEP8 fixes, etc. I'm not sure if that makes for a better project proposal or not.

**Comment by MridulS** [comment]
A part of my proposal is to clean and reorganize the existing code as
decided and required. It will be a part of that.

**Comment by chebee7i** [comment]
Sounds good!

**Comment by MridulS** [comment]
Can you have a look at my proposal at the wiki? I would like to know your
views and suggestions.
