### ISSUE TITLE
To find a Hamiltonian circuit in a graph

### ISSUE THREAD

**Issue by OrkoHunter** [networkx/networkx#1422]
I was wondering if there's a way to find if a graph whether directed or undirected has a Hamiltonian path or not _i.e. a path visiting each vertex exactly once_. For graphs with small number of nodes, it can be done easily, but it won't be easy for bigger graphs with more branches. I was thinking to implement a way to find the Hamiltonian circuit in such graphs.

Any suggestions?

**Comment by MridulS** [comment]
@OrkoHunter https://github.com/networkx/networkx/blob/a822b491c6b53a2819915a8c620e97a36ba6c060/networkx/algorithms/simple_paths.py#L11 and https://github.com/networkx/networkx/blob/a822b491c6b53a2819915a8c620e97a36ba6c060/networkx/algorithms/tests/test_simple_paths.py#L40

**Comment by OrkoHunter** [comment]
@MridulS Thanks for pointing that out. At least it is there already. 
But I have no idea how can we use it. 
And why is it under the tests? 
There's no mention of it in the documentation either

**Comment by ysitu** [comment]
Implementing "a way" is easy. Implementing "a good way" is hard.

**Comment by OrkoHunter** [comment]
@ysitu So, I think a way exist here https://github.com/networkx/networkx/blob/a822b491c6b53a2819915a8c620e97a36ba6c060/networkx/algorithms/tests/test_simple_paths.py#L40

But I can't figure out how can someone make use of it. It's under tests.

**Comment by MridulS** [comment]
@OrkoHunter You do realise that the hamiltonian path problem is a NP-Complete problem. As @ysitu pointed out it will be a hard to implement it in a "good way" .

**Comment by hagberg** [comment]
Closed due to inactivity.
