### ISSUE TITLE
Documentation Error

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#1423]
Was going through the documentation for `from_numpy_matrix` 
![screen shot 2015-03-22 at 4 22 50 pm](https://cloud.githubusercontent.com/assets/5363860/6769038/204093ea-d0b0-11e4-910e-34bea61cf8cb.png)

create_using and parallel_edges are surrounded by single backticks, they should be surrounded by double backticks, I presume this will be in a lot of places in the documentation.

**Comment by chebee7i** [comment]
Yup. It's a disconnect between Sphinx and Markdown :)

**Comment by jfinkels** [comment]
That's my bad, sorry: I guess the single backticks means "math mode" for NetworkX documentation!
