### ISSUE TITLE
Few points for the developing community

### ISSUE THREAD

**Issue by OrkoHunter** [networkx/networkx#1428]
Hello developers,

No doubt, NetworkX is a great python library . Also being fully written in python, it is not brainstorming to get familiar with the code base. But what I have felt which can make it more awesome, is creating a welcoming inspiration for people who use it, who wish to contribute at least one patch into it.

According to pypi, NetworkX had **113,321** downloads in the last month.
Currently, it has 408 forks on Github and there are about 25 people who have 5 or more commits. That's just **6%** of the total forks. We can *definitely* improve this. Here are some of my ideas for this.

##### 1. A nice Home of networkx wiki

Currently, people can't figure out much from the [Home](https://github.com/networkx/networkx/wiki). However, the page [GSoC 2015](https://github.com/networkx/networkx/wiki/GSoC-2015) contains some of the sections which can be shown in the Home like 'Communicating with NetworkX' and 'Getting started with NetworkX development'. But this is something misguiding.

##### 2. Development is not all about GSoC

While GSoC is a very good period for new people to join the community but it should not be the primary. Personally I believe that we should emphasize more on this to get more "hero" contributors.
Writing a development workflow would be a good point to start with.

##### 3. A page always having some ideas.

Just like we created ideas page for GSoC, we can have a permanent page(updated at times) which should contain information about features that can be added to NetworkX to reach the goal.

Sorry for creating an issue on GitHub but I believe this is a good way to start discussion on it.

Thank you.

**Comment by harrymvr** [comment]
I agree with most of your ideas. I just wanted to point out that a development workflow already exists [here](http://networkx.github.io/documentation/development/developer/index.html), but maybe it's not drawing enough attention.

**Comment by OrkoHunter** [comment]
>  (is your Home link deliberately pointing to SumPy?)
No. My bad. I meant the NetworkX home.

> but maybe it's not drawing enough attention.
Yea maybe. 

There have been frequent contributions which everyone would agree. What I totally meant was a nice and provoking wiki with vivid ideas plotted on it.

**Comment by jg-you** [comment]
A good start would be a proper `CONTRIBUTING` file which explains the desired code style, the development philosophy, current targets, etc. The website "only" explains how to use git, which is not that helpful when it comes to *how* to write your code, *where* to place it, *what* to code.

**Comment by OrkoHunter** [comment]
@jg-you +1
Also, what about picking up points like #1456 and putting it in the "development philosophy" ?

**Comment by hagberg** [comment]
Let's keep up this kind of thinking - open new issues for specific items.
