### ISSUE TITLE
Refactor components API

### ISSUE THREAD

**Issue by jtorrents** [networkx/networkx#1431]
Following from the discussion on #1404, it would be good to remove the `[bi]connected_component_subgraphs` functions and make `[bi]connected_components` yield subgraphs (now they yield sets of nodes).

We decided to not make this change right now, on the one hand, in order to not overwhelm users with API changes (2.0 release will come with many changes), and on the other hand, because right now generating subgraphs (with `copy=True` which is the default) is much slower than generating sets of nodes.

We expect that the speed of generating subgraphs will improve in the short term if we extend #1164 approach to subgraph generation. Once we do that we can revisit this to see if the speed penalty for subgraph generation is a showstoper for this API change.

**Comment by hagberg** [comment]
Worth revisiting now with networkx-2.0 subgraphs.  @dschult

**Comment by dschult** [comment]
It looks like the timing for all four ```connected_component_subgraphs``` functions is within a few percent of the corresponding ```connected_components``` functions. For worst case trials (10000 isolated edges) subgraphs can get up to 20% slower. For gnp_random_graphs they are within a few percent.  These tests were performed with the option ```copy=False```.  With the ```copy=True``` keyword the times for biconnected and strongly_connected took 7 times longer, while weakly_connected was 45 times longer and connected was 80 times longer. So, ```copy=False``` should be the default.

The most recent comment I can find on this is by @jtorrents back in May 2015 in ticket #1501
expressing a change in heart about making subgraph creation automatic.

> Yielding sets of nodes forces user code to be more explicit about subgraph copy handling, I think that this pattern:
> 
>     for component in nx.connected_components(G):
>         Gc = G.subgraph(component) # or G.subgraph(component).copy() 
>         # Do stuff with Gc
> 
> Is better than:
> 
>     for Gc in nx.connected_components(G): # Assume that we yield subgraphs with default to no copy 
>         # Do stuff with Gc
> 
> Because the former forces the user to think, do I need to modify Gc? do I want these modifications to propagate to G? If we yield subgraphs with no copy as default and the user changes Gc it can lead to bugs/surprises.

I believe this is an argument for simply removing the ```connected_component_subgraphs``` method and NOT changing the current ```connected_components``` function.   Ideas?

**Comment by hagberg** [comment]
I agree with @dschult here.  It makes sense to remove the connected_component_subgraphs methods to make the user explicitly decide on copy/no copy.  We can add subgraphs as an example.
