### ISSUE TITLE
Meaning of the node size

### ISSUE THREAD

**Issue by oscarcapote** [networkx/networkx#1432]
Hello, I want to draw nodes like a ring chart. For example I want a three rings node of three of size = 400 with three colors, I plot for example that every ring has 1/3 of the area of the original size. The problem is that it seems that they don't have the same area. For that reason I want to know the meaning of the size, if is a radius, an area...

**Comment by hagberg** [comment]
The drawing of nodes is done by matplotlib's scatter() function.   So the size is the radius of the nodes.
