### ISSUE TITLE
KeyError in all_shortest_paths() with missing source node

### ISSUE THREAD

**Issue by pebenito** [networkx/networkx#1433]
I use DiGraph with all_shortest_paths(). I was adding error path unit tests for my project, and I found that the all_shortest_paths() function will raise a KeyError instead of NetworkXError if the source node is not in the graph:

```python
Traceback (most recent call last):
  File "/home/pebenito/projects/setools/tests/infoflow.py", line 378, in test_932_all_shortest_paths_source_excluded
    paths = list(a.all_shortest_paths("node1", "node2"))
  File "/home/pebenito/projects/setools/setools/infoflow.py", line 211, in all_shortest_paths
    for p in nx.all_shortest_paths(self.subG, s, t):
  File "/usr/lib64/python3.3/site-packages/networkx/algorithms/shortest_paths/generic.py", line 357, in all_shortest_paths
    pred = nx.predecessor(G,source)
  File "/usr/lib64/python3.3/site-packages/networkx/algorithms/shortest_paths/unweighted.py", line 338, in predecessor
    for w in G[v]:
  File "/usr/lib64/python3.3/site-packages/networkx/classes/graph.py", line 319, in __getitem__
    return self.adj[n]
KeyError: <Type(<qpol_policy_t id=140070666001936>,"node1")>
```
I'm seeing this with NetworkX 1.9.1.

**Comment by alexnikleo** [comment]
@pebenito can you, please, provide example of such graph?

**Comment by pebenito** [comment]
I can provide an example graph, as I hit it as part of the unit testing for
my project. How should I do this?

On Mon, Apr 6, 2015 at 7:36 AM, alexnikleo <notifications@github.com> wrote:

> @pebenito <https://github.com/pebenito> can you, please, provide example
> of such graph?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/networkx/networkx/issues/1433#issuecomment-90024822>.
>



-- 
Chris PeBenito

"Engineering does not require science. Science helps
a lot, but people built perfectly good brick walls
long before they knew why cement works."-Alan Cox

**Comment by chebee7i** [comment]
If it is large, are you able to make something smaller (possibly by removing nodes that you know are not relevant) and paste it here? If not, put it in a [gist](https://gist.github.com/).

**Comment by pebenito** [comment]
I think I misunderstood the original question (I thought you wanted a graph
I generated in my project).  Reproducing the problem is straightforward:

>>> import networkx as nx
>>> G = nx.DiGraph()
>>> G.add_edge("A","B")
>>> G.add_edge("B","C")
>>> list(nx.all_shortest_paths(G, "D", "C"))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File
"/usr/lib64/python2.7/site-packages/networkx/algorithms/shortest_paths/generic.py",
line 357, in all_shortest_paths
    pred = nx.predecessor(G,source)
  File
"/usr/lib64/python2.7/site-packages/networkx/algorithms/shortest_paths/unweighted.py",
line 338, in predecessor
    for w in G[v]:
  File "/usr/lib64/python2.7/site-packages/networkx/classes/graph.py", line
319, in __getitem__
    return self.adj[n]
KeyError: 'D'


On Mon, Apr 6, 2015 at 11:00 AM, chebee7i <notifications@github.com> wrote:

> If it is large, are you able to make something smaller (possibly by
> removing nodes that you know are not relevant) and paste it here? If not,
> put it in a gist <https://gist.github.com/>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/networkx/networkx/issues/1433#issuecomment-90091781>.
>



-- 
Chris PeBenito

"Engineering does not require science. Science helps
a lot, but people built perfectly good brick walls
long before they knew why cement works."-Alan Cox

**Comment by chebee7i** [comment]
That's great. Sorry for the confusion. Additional discussion now appears here: #1445
