### ISSUE TITLE
is passing nx.draw_networkx_edges width as a list/array of floats supported functionality?

### ISSUE THREAD

**Issue by gregcaporaso** [networkx/networkx#1441]
I'm exploring using networkx in [An Introduction to Applied Bioinformatics](www.applied-bioinformatics.org) and I want to display edges where their widths are based on their weights. The ``width`` option to ``draw_networkx_edges`` works as I would expect when passed a list of floats, but [the documentation](https://github.com/networkx/networkx/blob/c92f43c40e5a6d1682ae4157ef5255c84ec47f49/networkx/drawing/nx_pylab.py#L422) indicates that it only takes a single float. 

Is passing a list of floats as ``width`` to ``draw_networkx_edges`` officially supported? I want to know if I can rely on that, or if that behavior could change without warning in the future.

Here's an [ipynb illustrating my usecase](http://nbviewer.ipython.org/urls/gist.githubusercontent.com/gregcaporaso/8cc4cf3e347b7158cd06/raw/e28516b8be9608e618708051055158d0734448be/networkx-dna-test.ipynb).

Thanks!

**Comment by SanketDG** [comment]
[These](https://github.com/networkx/networkx/blob/c92f43c40e5a6d1682ae4157ef5255c84ec47f49/networkx/drawing/nx_pylab.py#L505-508) lines of code check if the `width` parameter is iterable or not, so yeah as of now it's supported. The documentation probably needs to be changed.

**Comment by gregcaporaso** [comment]
Great, thanks! I submitted a pull request (#1442) updating the doc string.
