### ISSUE TITLE
GSoC slot request

### ISSUE THREAD

**Issue by ysitu** [networkx/networkx#1446]
Although I [mentioned](https://github.com/networkx/networkx/issues/1416#issuecomment-86102803) the other day that we had five mentors signed up, it turns out that we have only four (@hagberg, @dschult, @Midnighter, @ysitu) because there is a duplicate entry for @dschult. I think that this means we can take on two students. Three just seems too many for four mentors. Can we agree on two?

BTW, if we do not suggest a different number by Apr 11, Terri will request two slots for us.

**Comment by Midnighter** [comment]
I will be gone until Sunday evening (GMT +1) so I'll probably miss most of the discussion. I think 2 slots is the safe number. Three might be possible if we do a "floating" mentoring where each one of us feels responsible for all projects. On the upside I expect many of the community to comment on code anyway, on the downside it's less clear for the students and ourselves who the immediate contact partner is and who is responsible in the end.

**Comment by chebee7i** [comment]
Yeah 2 seems fine. I'll definitely be participating in the discussions.

**Comment by OrkoHunter** [comment]
Has Terri allotted the slots by now?

**Comment by coder006** [comment]
> Has Terri allotted the slots by now?

Malange declared their slot allocations. PSF seems to have got enough slots. c.f. their IRC header " We got lots of slots! Thank you, Google!" :)

**Comment by OrkoHunter** [comment]
> Malange declared their slot allocations. PSF seems to have got enough slots. c.f. their IRC header " We got lots of slots! Thank you, Google!" :)

I heard that PSF always has plenty of slots left in the end, unused !

**Comment by OrkoHunter** [comment]
@ysitu @Midnighter @hagberg @dschult 
Just a quick reminder about the student rankings.
PSF's IRC header also says "Sub-org admins: get your student rankings in by April 17."

**Comment by MridulS** [comment]
I think this can be closed now.
