### ISSUE TITLE
Bug with dev version of write_gml

### ISSUE THREAD

**Issue by jg-you** [networkx/networkx#1449]
I've stumbled upon a "bug" that involves `write_gml`

    jgyou:networkx-master$> python2.7
    >>> import networkx as nx
    >>> nx.__version__
    '2.0.dev_20150412140538'
    >>> G=nx.random_partition_graph([20,20],0.6,0.1)
    >>> G.graph["partition"]
    [set([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]), set([32, 33, 34, 35, 36, 37, 38, 39, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])]
    >>> nx.write_gml(G,path="test_path.gml")
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "<string>", line 2, in write_gml
      File "networkx/utils/decorators.py", line 220, in _open_file
        result = func(*new_args, **kwargs)
      File "networkx/readwrite/gml.py", line 717, in write_gml
        for line in generate_gml(G, stringizer):
      File "networkx/readwrite/gml.py", line 636, in generate_gml
        for line in stringize(attr, value, ignored_keys, '  '):
      File "networkx/readwrite/gml.py", line 613, in stringize
        for line in stringize(key, value, (), next_indent, True):
      File "networkx/readwrite/gml.py", line 623, in stringize
        raise NetworkXError('%r is not a string' % (value,))
    networkx.exception.NetworkXError: set([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]) is not a string
    >>> nx.write_gml(G,path="test_path.gml",stringizer=repr)
    >>> quit()
    jgyou:networkx-master$> head test_path.gml 
    graph [
        partition "set([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])"
        partition "set([32, 33, 34, 35, 36, 37, 38, 39, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31])"
      node [
        id 0
        label 0
      ]
      node [
        id 1
 

Essentially `write_gml` fails to convert `G.graph["partition"]` to a string unless a stringizer is specified explicitly. Is this intended? Shouldn't the default stringizer be set to `repr`? Or perhaps the representation of a partition changed to something stringable (`list`)? The latter would break the API contract slightly.

**Comment by chebee7i** [comment]
We discussed this a bit in #1269. In particular, see https://github.com/networkx/networkx/pull/1269#issuecomment-61442401. So the intention was to require the user to make an explicit choice. When using `read_gml`, you must make the corresponding choice. @ysitu may have some additional comments, but I think this is "as designed".

**Comment by jg-you** [comment]
Fair point.
Code that works with 1.9.1 might be broken when the next release is made though.

**Comment by ysitu** [comment]
It has been quite some time since I wrote the code, so my memory may not be accurate. I did not make `repr` the default probably due to concern about Python 2/3 compatibility. `repr` and `ast.literal_eval` are not entirely interoperable across Python 2/3:

```python
Python 3.4.0 (default, Apr 11 2014, 13:05:11) 
[GCC 4.8.2] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ast
>>> ast.literal_eval('set([1, 2, 3])')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/ast.py", line 84, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python3.4/ast.py", line 83, in _convert
    raise ValueError('malformed node or string: ' + repr(node))
ValueError: malformed node or string: <_ast.Call object at 0x7fdee1f044a8>
```
```python
Python 2.7.6 (default, Mar 22 2014, 22:59:56) 
[GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import ast
>>> ast.literal_eval('{1, 2, 3}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/ast.py", line 80, in literal_eval
    return _convert(node_or_string)
  File "/usr/lib/python2.7/ast.py", line 79, in _convert
    raise ValueError('malformed string')
ValueError: malformed string
>>> 
```

Another example is that `repr`ing a `unicode` in Python 2 produces a `u` prefix, which is not recognized by Python 3.2 and below.

Without a default the user needs to explicitly do something so that when something breaks, he/she knows where to look for the problem.

**Comment by jg-you** [comment]
So basically unless someone can come up with *any* Python 2,3 compatible stringizer, it's a non-fixable "issue"?

**Comment by chebee7i** [comment]
Seems like a consequence of storing "non-simple" Python code in strings.

For comparison, note what json does:
```
>>> import json
>>> json.dumps({1,2,3})
TypeError: set([1, 2, 3]) is not JSON serializable
```

We act similarly in that an exception is raised (provided no stringizer is provided). It will work if choosing repr, but you don't get 2/3 compatible code for roundtrips. We should probably add a note in the docstring highlighting this fact. 

Any stringizer that does some conversion (e.g. from sets to lists) will not have enough information (unless you do something custom) during decoding to convert the lists back into sets. So I wonder if it makes more sense in this particular situation to convert the partition into a list of lists?

Alternatively, would pickle.dumps() be a good stringizer for you? Seems like overkill and I'm not sure what the 2/3 compatibility concerns would be.

**Comment by jg-you** [comment]
With all the raised concerns here, `None` might just be the way to go until someone finds something better.

**Comment by chebee7i** [comment]
Yeah, ok. Thanks for the discussion. Helpful.

**Comment by chebee7i** [comment]
TODO: Update the docstring to make some of the conversion issues more obvious.
