### ISSUE TITLE
NetworkX summit and/or sprints at Scipy 2015?

### ISSUE THREAD

**Issue by jtorrents** [networkx/networkx#1450]
It would be great if we could repeat the NetworkX summit and sprints at Scipy that we did in 2011. I also attended 2012 when we did not do a summit but had very productive sprints. Among other things, we performed a not very graceful, but successful, migration from trac to Github.

With all the changes to the new API for 2.0 and related issues, I think that high bandwidth meeting would help a lot with the discussion and implementation. If we manage to gather enough of us in the same room for a couple of days we can do a lot of work and have a lot of fun. I'd love to catch up with @hagberg @dschult @chebee7i @bjedwards @loicseguin @drewconway and to meet in person @ysitu @Midnighter and many others.

The conference is in early July but I mention this now because I just realized that the deadline to apply for financial aid finishes tomorrow! You can apply here (I just did):

http://scipy2015.scipy.org/ehome/115969/259279/?&

What do you guys think? Would you be able to make it to Austin early July?

**Comment by hagberg** [comment]
LANL is sponsoring SciPy 2015 and I am planning on being there.  I'm not sure which dates yet.
I am happy to meet up with NetworkX developers and users there.  If there is enough interest perhaps we can have a formal gathering or sprint.

**Comment by Midnighter** [comment]
Although I agree that it'd be really exciting to meet everyone in person and have a sprint or just a chat, I will not be able to attend. I was able to go to EuroScipy once but would have a hard time convincing my current employer that I should go to Austin.

Definitely a separate issue/mailing list discussion: The IPython team has regular hangouts which especially with GSoC coming up could be a nice idea and would ameliorate somewhat that we all live in different countries.

**Comment by MridulS** [comment]
I am still new to this community, but still I would love to attend SciPy and meet you guys and work further with NetworkX.
@jtorrents Thanks for the link, lets hope to get some financial aid :)

**Comment by jtorrents** [comment]
@hagberg that's great! Let's see if there is enough critical mass for something more formal (I can help organizing if needed), but even if there isn't, sprints can also help bring more people to contribute or to just use NetworkX. I also plan to be there (in my case will depend on financial support).

@Midnighter , too bad. I'm sure that we will find the occasion in the future. Also, convincing employers is always a tricky thing. Regarding the hangouts, maybe the coordination costs of very different time zones can be a problem, but I think is worth trying.

@MridulS I hope to see you there. The scipy conference is really great!

**Comment by chebee7i** [comment]
Wish I could make it, but SciPy is definitely a fun conference.
