### ISSUE TITLE
Update `write_gml` docstring.

### ISSUE THREAD

**Issue by chebee7i** [networkx/networkx#1454]
See discussion in #1449.  I think it would be helpful if we added a few comments to the docstring to make some of the conversion issues more transparent for `write_gml`.

**Comment by SanketDG** [comment]
Was this resolved? As per as the discussion in #1486, this needs more work.

**Comment by ysitu** [comment]
@SanketDG Do you have any concrete suggestions?

**Comment by SanketDG** [comment]
@chebee7i said that it was best to link to user documentation. I think using the [cross referencing feature](http://sphinx-doc.org/domains.html#cross-referencing-python-objects) from sphinx will be a good way to link to the documentation, in this case [`readwrite.gml.html`](http://networkx.github.io/documentation/latest/reference/readwrite.gml.html)

We write the issues involved with the stringizers along with examples in the module level docstring of `networkx.readwrite.gml`. Then using ``:mod:`~networkx.readwrite.gml` `` (cross referencing) in the docstring of `write_gml()` should create a link to `readwrite.gml.html`. This will be version independent.

I think the only downside I can see is that I can't name the link so the link will just look like this: [gml](#). With a proper message, this shouldn't be a problem.

**Comment by ysitu** [comment]
Can we defer this and release 1.10 now?

**Comment by SanketDG** [comment]
Yes, creating the examples for this will require a discussion, so it's best if we keep it out of `1.10` if its release is near.

**Comment by hlin117** [comment]
Until I looked up online why my `write_gml` wasn't working, I was confused why I couldn't write nodes that had underscores in them.

Can we add to the documentation that graph, node, and edge attributes cannot have underscores when writing using `write_gml`?

**Comment by hagberg** [comment]
It might be better to point to the specification http://www.fim.uni-passau.de/fileadmin/files/lehrstuhl/brandenburg/projekte/gml/gml-technical-report.pdf
since there are also other restrictions on what keys and values can be.

**Comment by hlin117** [comment]
Good suggestion, @hagberg.

@chebee7i, are you still interested in working on this PR? Can you add this to the list of things to fix?
