### ISSUE TITLE
Avoid sort-and-compare pattern in doc/unittests

### ISSUE THREAD

**Issue by ysitu** [networkx/networkx#1456]
There are many uses of the sort-and-compare pattern

``` python
assert_equal(presorted, sort(unordered_iterable))
```

in tests. This is awkward and obscures what is being tested. `assertItemsEquals`/`assertCountEquals` (choice depends on Python version) in the `unittest` module is a better solution should be used instead. This is especially useful for doctests as they are intended to be read by humans.

**Comment by chebee7i** [comment]
Yes, please! :)
