### ISSUE TITLE
Incremental topological sort and strongly connected components.

### ISSUE THREAD

**Issue by chebee7i** [networkx/networkx#1457]
Recently, I needed an incremental algorithm for detecting strongly connected components. NetworkX does not currently have such functionality. Here are two papers that describe an algorithm. An incremental algorithm for topological sorts is also described:

http://www.cs.princeton.edu/~sssix/papers/dto-journal.pdf
http://homepages.ecs.vuw.ac.nz/~djp/files/tr0903.ps

Previously, we had a incremental implementation for detecting connected components, but it was never integrated into NetworkX proper. So if someone takes this issue on, we should look into adding the code in that ticket (or some modification of it) as well:

https://networkx.lanl.gov/trac/ticket/457
https://networkx.lanl.gov/trac/changeset/1464/networkx

**Comment by aweltsch** [comment]
I read the papers, and this seems doable. I would like to work on this.

**Comment by dschult** [comment]
Sounds good -- looking forward to it. :)
