### ISSUE TITLE
Question: PageRank algo convergence condition

### ISSUE THREAD

**Issue by darkjh** [networkx/networkx#1465]
Hi, just a question when reading the code of PageRank algorithm. I found this:

https://github.com/networkx/networkx/blob/master/networkx/algorithms/link_analysis/pagerank_alg.py#L155

So the `tol` param is normalized by the graph size by multiplying. Can you explain a little bit why? 

Thanks.

**Comment by dschult** [comment]
I'm not sure what your question is, but the variable ```err``` equals a sum over all nodes, so it will increase as N increases. Normalizing the tolerance by N seems reasonable.
