### ISSUE TITLE
strongly_connected_components_recursive documentation

### ISSUE THREAD

**Issue by JonathanShor** [networkx/networkx#1473]
This is similar to #1216. `strongly_connected_components_recursive`  documentation states `A list of nodes for each component of G. The list is ordered from largest connected component to smallest.` when it seems that the order in fact not guaranteed, like the other SCC methods.

**Comment by SanketDG** [comment]
I guess this can be closed.

**Comment by chebee7i** [comment]
Fixed in #1510
