### ISSUE TITLE
range should be equated to xrange for Python2

### ISSUE THREAD

**Issue by debugger22** [networkx/networkx#1479]
For instance, see this:
https://github.com/networkx/networkx/blob/master/networkx/algorithms/flow/networksimplex.py#L22-L25

**Comment by debugger22** [comment]
One solution:

```diff
diff --git a/networkx/compatibility.py b/networkx/compatibility.py
new file mode 100644
index 0000000..80f4188
--- /dev/null
+++ b/networkx/compatibility.py
@@ -0,0 +1,30 @@
+"""
+This module manipulates some constructs which generalizes their behavior
+across different Python versions.
+
+Example
+=======
+
+In order to use ``range`` in any module in networkx, proceed as following:
+
+import networkx as nx
+from nx.compatibility import range
+
+"""
+
+import sys
+
+
+PY3 = sys.version_info[0] > 2
+
+if PY3:
+    range = range
+    long = int
+    unicode = str
+    unichr = chr
+else:
+    range = xrange
+    long = long
+    unicode = unicode
+    unichr = unichr
```

**Comment by chebee7i** [comment]
There are libraries for that. See `six` or `futures`. However, we've opted to use list(range()) in the codebase.

**Comment by hagberg** [comment]
Or just range() when appropriate.

**Comment by debugger22** [comment]
> See six or futures

Dependencies. :)

Lazy computation is good for memory management. Using `range` and `list(range())` everywhere might be an overhead.

Anyway, if everyone's ok with using `range`, no problems.

**Comment by hagberg** [comment]
Exactly.  Fewer dependencies and cruft are good.  
And, use Python 3.

**Comment by chebee7i** [comment]
I may have overstated a bit, I think we mostly just use `range()` and so Python 3 users will get the lazy evaluation while Python 2 users will not.  In cases were we need the list immediately, then we use `list(range())`.
