### ISSUE TITLE
Write a CONTRIBUTING file

### ISSUE THREAD

**Issue by jg-you** [networkx/networkx#1480]
Suggested in https://github.com/networkx/networkx/issues/1428, but I feel like it needs a separate issue.

It would be good if a maintainer or a core developer could take the time to write a proper `CONTRIBUTING` file that explains
- the desired code style;
- the preferred choice of python statements when multiple are available (e.g. https://github.com/networkx/networkx/issues/1479);
- the proper way of implementing core that do not come with classes (e.g. partitions);
- the desired code organization (what goes where);
- the current main development targets.

And probably other things that I can't come up with just now.

**Comment by hagberg** [comment]
I don't mind making suggestions.  But I don't like being overly prescriptive ("should", "must").  
Any document we create with that info will be inconsistent in some ways with the current code base.  

Do you think this is holding up contributions and workflow?

**Comment by jg-you** [comment]
Well, it would probably reduce the length of the "learning phase" for new contributors (i.e. takes less time to get familiar with the code base when there's a guide).
It would also lead to better PR which, in turn, would lead to a lessened need for back and forth on small commenting on small details. Hence, quicker merges.

`CONTRIBUTING` files are not law either, they're bound to be loosely followed.
As such, inconsistencies between the "standard" and the current code base would be also resolved as the code evolves (e.g. PEP vs the core python codebase).

See https://github.com/blog/1184-contributing-guidelines .

**Comment by hagberg** [comment]
Those are good arguments.  Let's do it.  @jg-you  would you like to create a draft?

**Comment by jg-you** [comment]
Yes, I can draft it. I'll submit a PR on which we can all work in the upcoming days.

**Comment by chebee7i** [comment]
@jg-you since you opened this PR, you should be able to attach code to it instead of opening a new PR. See: http://stackoverflow.com/questions/4528869/how-do-you-attach-a-new-pull-request-to-an-existing-issue-on-github

**Comment by MridulS** [comment]
I think that something like this https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt should also be a part of this file.

**Comment by chebee7i** [comment]
Or just a link to it. The numpydoc standard is pretty standard. :)

**Comment by MridulS** [comment]
Yeah, that would work too :)

**Comment by SanketDG** [comment]
The networkx documentation explains lot on the workflow, as I see it.
[http://networkx.github.io/documentation/development/developer/index.html](http://networkx.github.io/documentation/development/developer/index.html)

**Comment by OrkoHunter** [comment]
@SanketDG The documentation is mainly focusing on setting up the environment and being familiar with git. I think `CONTRIBUTING` file would be able to explain much about the coding paradigm and preferred choice of python statements etc. @jg-you has explained this in his comments.

**Comment by SanketDG** [comment]
@OrkoHunter Well, what I meant was it covers a major part of the workflow. But yes, we need a `CONTRIBUTING.md` for beginners to get acquainted with the codebase quickly.

The contents of this file could probably to added to `Developer Guide` as well later.

**Comment by Michael-E-Rose** [comment]
Reviving an 11 months old issue... To me the idea of a separate `CONTRIBUTING.md` looks redundant to what the [wiki](https://github.com/networkx/networkx/wiki) fulfills.

**Comment by jg-you** [comment]
The wiki now address some of the issues, I agree.
Some very useful information is still missing though: are "uninvited feature" pull requests welcome? Would an external developer's time be better spent addressing open issues. How is the codebase organized? What are the middle / long term plan of the development team.

**Comment by Michael-E-Rose** [comment]
I see, some useful information is indeed missing. Now the question is:
Should this information be part of the wiki or the only content of
CONTRIBUTING.md?
Am 30.03.2016 00:44 schrieb "Jean-Gabriel Young" <notifications@github.com>:
