### ISSUE TITLE
Maintenance: Outdated bilbilography

### ISSUE THREAD

**Issue by jg-you** [networkx/networkx#1483]
Will drafting the `CONTRIBUTING` file (see issue #1480 ), I realized that [doc/source/bibliography.rst](https://github.com/networkx/networkx/blob/master/doc/source/bibliography.rst) is largely outdated and does not contain most of the references. It should be either auto generated from the `References` sections of the doc, or brought up to date and manually maintained with every new feature release (ouch).

**Comment by MridulS** [comment]
:+1: on generating these using `References` section of the doc.

**Comment by chebee7i** [comment]
This is tricky stuff, and unfortunately, I don't think there are good solutions available presently. You'll have to hack into sphinx and sphinxcontrib-bibtex. There has been some work done on this, and so, perhaps it is much easier now. See https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/52. 

Ideally, you'd want two bibliographies---one for all of the documentation and one for each docstring (e.g. at a function, method, class, and even module level).  The docstring should create a link using a unique and globally defined tag, such as [Hopcroft1969]_, and this should link locally down to the references section of the docstring. The number/reference-tag that is presented in the references section could also be a link to the global bibliography as well. Ultimately, you want to maintain one bibtex file and be able to use citations in the user documentation and docstrings in the same manner.

**Comment by mcmtroffaes** [comment]
I'm just spotting this issue now - the idea of two types of bibliographies sounds quite appealing to me, and I think it would cover a lot of use cases. I'm not sure yet of the implementation (particularly if we want both global as well as local bibliographies), but you can track the issue here: https://github.com/mcmtroffaes/sphinxcontrib-bibtex/issues/87

**Comment by hagberg** [comment]
Closed due to inactivity.
