### ISSUE TITLE
Mark *_iter functions as deprecated

### ISSUE THREAD

**Issue by ysitu** [networkx/networkx#1485]
This is to make a clear indication that those functions are slated for removal in 2.0.

**Comment by chebee7i** [comment]
In #1476, I just realized that degree() returns a dict, while nodes() returns a list. We'll definitely need have a very clear migration guide for people.

Also, is it weird to say that the *_iter functions are deprecated when there is no valid migration route for them in the same NetworkX version? The behavior of the non-iter function is completely different and will also change in the next version.

**Comment by ysitu** [comment]
@chebee7i The migration path is to replace the `_iter`-suffixed functions with their unsuffixed counterparts and treat the latter like iterables instead of lists. Of course, that does not work for `degree`, but it covers most cases.

**Comment by MridulS** [comment]
On a different note, we should start discussing about an appropriate design specification for the new API, which is the second part of my GSoC project (and further).

**Comment by chebee7i** [comment]
For the `*degree_iter()` functions. Should we special case singletons? I'd be a little inconvenient to have to type:   `next(G.in_degree("A"))` just to get the indegree for node A.  I'm not sure it is even possible to special case it---if the degree functions become generators, we can't have yield and return simultaneously.

**Comment by ysitu** [comment]
@chebee7i You can return a generator.

**Comment by chebee7i** [comment]
Sure, but returning a generator means we'll have to type `next(G.in_degree("A"))` to get the indegree for node A. Maybe we are okay with that.

**Comment by ysitu** [comment]
@chebee7i You can do `return len(G[u]) if u is not None else ((u, len(G[u])) for u in G)`.

**Comment by chebee7i** [comment]
Doh, ok yes I see now.

**Comment by ysitu** [comment]
@MridulS Let's not hijack this thread for broader discussion on the 2.0 API. Could you start a wiki page summarizing the current ideas?

**Comment by MridulS** [comment]
Should we remove `*iter` functions from timingclasses.py file also?
