### ISSUE TITLE
write_graphml does not recast properties with same name but different value types

### ISSUE THREAD

**Issue by gdbassett** [networkx/networkx#1487]
```
g = nx.DiGraph()
g.add_node('a')
g.add_node('b')
g.node['a']['count'] = 1
g.node['b']['count'] = float(.5)
nx.write_graphml(g, "g.graphml")
```
The above code will result in two separate attribute keys within the XML file, one for the int and one for the float.

Expected operation would be for the 'count' property to be abstracted to the broadest type which could contain all values (in this case, float), and saved as a single attribute.

**Comment by chebee7i** [comment]
Good catch. I think we do a single-pass right now. This will require two passes but probably should be done.

**Comment by gdbassett** [comment]
If you wait to write the attribute type until the end, you can keep track of the property types encountered for a property and write the appropriate type to encompass them all at the end.

**Comment by hagberg** [comment]
This could get tricky if the types are not so easily abstracted.  For example if someone has an attribute with  '1', 1, True ,and "True" as values, etc.  Maybe we shouldn't attempt to do something fancy here?

**Comment by chebee7i** [comment]
I def don't think we should be converting non-numeric types to numeric...and worrying about the numerous ways of representing bools is a pain. But numeric attributes seem like an easy use case to handle specially. 

I'd imagine the cases where one wants mixed numeric types is near nonexistant, and so if we see both int and float, there seems to be an obvious answer in terms of what the user would like during conversion...very similar to what most (friendly) CSV readers when a column contains numeric looking data but with only some having decimals in them. I guess we'd at least need to allow this inference to be be able to be disabled.

**Comment by gdbassett** [comment]
boolean -> int -> long, float -> double -> string.  Take the one most to the right?

**Comment by chebee7i** [comment]
@gdbassett, if there were an interface that allowed you to specify the type for each attribute, would that be sufficent? Or would you want it automatically inferred?

**Comment by gdbassett** [comment]
I think it should be inferred.  The simple nature of the write_* functions is one of the benefits of the module.
