### ISSUE TITLE
Is it possible to use Axes3D ?

### ISSUE THREAD

**Issue by orena1** [networkx/networkx#1502]
Hi is it possible to use 
```python
from mpl_toolkits.mplot3d import Axes3D
```
with networkx package ?

Thanks.

**Comment by chebee7i** [comment]
What does that mean?

**Comment by chebee7i** [comment]
Did you want to 3D plot a graph? If so, we don't currently support that. But it's certainly possible.

**Comment by orena1** [comment]
![image](https://cloud.githubusercontent.com/assets/8983713/7447178/f413829e-f1f9-11e4-86a8-1a5c630f1448.png)

**Comment by tanjia123456** [comment]
Hello, I also want to use networkx to draw a 3D graph. In addition, if I use matplotlib to draw a three-dimensional graph, how can I find its adjacency matrix?
