### ISSUE TITLE
Can't install development version

### ISSUE THREAD

**Issue by noelmas** [networkx/networkx#1505]
Keen to use 2.0 functionality and want to install development version here. Bit of a newbie question I'm afraid, but hopefully simple one to fix.

Tried using:

pip install git://github.com/networkx/networkx.git#egg=networkx --upgrade

Get error:

Sorry, 'git://github.com/networkx/networkx.git#egg=networkx' is a malformed VCS url. The format is <vcs>+<protocol>://<url>, e.g. svn+http://myrepo/svn/MyApp#egg=MyApp

**Comment by chebee7i** [comment]
Note, not all 2.0 functionality has been implemented yet.

I would do the following instead:

```
git clone http://github.com/networkx/networkx.git
cd networkx
pip install -e .  # Don't forget the period (.)
```

This installs NetworkX similarly to what you'd get with a symbolic link. Any changes you make or pull from the git repository will seamlessly appear in your installed version.

**Comment by noelmas** [comment]
Thank you! Enjoying my nx.from_pandas_dataframe now
