### ISSUE TITLE
Update Johnson's algorithm so that graph is not modified

### ISSUE THREAD

**Issue by chebee7i** [networkx/networkx#1506]
There was some additional discussion on how to modify Johnson's algorithm #1481 so that it doesn't require a graph copy or modifying the input graph. The main point appears here in https://github.com/networkx/networkx/pull/1481#discussion_r29732490.

Here is the relevant bit:

"""
Copying the graph is unnecessary. In order to compute node potentials using Bellman--Ford you do not need to add a separate node. You just assign zero distance labels of all nodes and start the relaxation loop.

The following Dijkstra using reduced costs (w[u][v] + p[u] - p[v]) instead of raw weights (w[u][v]) warrants introducing a dedicated function for that purpose. It has use cases in other algorithm such as augmenting path-based minimum cost flow algorithms. (Maybe we can use unify this with #762.)
"""

**Comment by chebee7i** [comment]
@theosotr any interest in tackling this?

**Comment by theosotr** [comment]
Yes, of cource. First of all, I have some questions to understand the whole concept about what @ysitu suggested.
To be more specific, I do not understand how exactly dist values using Belman - Ford algorithm are going to be calculated without adding a new node. 
Moreover, in all cases or in certain cases iteration order is going to be changed after calling ``johnson``.

**Comment by ysitu** [comment]
@theosotr If you think at how Bellman--Ford works, you will notice that adding a new node merely serves to seed the algorithm. The new node causes the distance labels to be zeroed in the first iteration and is not used afterwards. You can achieve this without the new node.

**Comment by theosotr** [comment]
Ok, Johnson's algorithm uses Bellman - Ford with source node, the node which just added to the graph. Therefore, how are we going to use Bellman-Ford? Which node we should set as a source node to compute dist values? A random node? (Sorry for my repeated questions but I still do not understand your approach.)

**Comment by ysitu** [comment]
@theosotr You put *all* nodes into Bellman--Ford's node queue and start the relaxation loop. If you absolutely need to know the source node, the answer would be: all nodes are, at the same time.

**Comment by theosotr** [comment]
Ok I think I understand. So, we must use a customized implementation of Bellman-Ford and not ``belman_ford`` function. Please correct me if I am wrong.

**Comment by ysitu** [comment]
@theosotr We can use some refactoring to avoid duplicating the implementation. The relaxation loop of `bellman_ford` can be put into a separate function named say `bellman_ford_relaxation` and reused here. We do the same for Dijkstra and create a version that defines edge weights in a generic fashion (e.g., a lambda). Then we use it here and some other places and also resolve #762.

**Comment by theosotr** [comment]
Interesting! I will try to prepare a code for this.

**Comment by ysitu** [comment]
After deferring some minor issues, this should be the last issue blocking the 1.10 release.
