### ISSUE TITLE
Algorithms for Combinatorial Optimization Problems

### ISSUE THREAD

**Issue by theosotr** [networkx/networkx#1507]
It is widely accepted that graphs have many applications in different aspects of science such as Computer Science, Operational Research, Biology, Maths, Sociology, etc. One of these applications is that many Combinational Optimization problems can be represented as graphs. The characteristic  and the interesting thing of these problems is that even computers fail to solve them because there is not any algorithm which can solve them in polynomial time. Travelling Salesman Problem (TSP), Vehicle Routing Problem (VRP) are example of such problems. However, many heuristic, metaheuristic algorithms have been published over the past years to solve / approximate the solution of these problems such as Simulated Annealing, Variable Neighborhood Search, Tabu Search, Ant Colony Optimization, etc.

Also, there is an implementation of algorithm to solve a combinatorial optimization problem in NetworkX  in ``algorithms.coloring``

The solution to these problems have enormous significance and they can be translated in terms of graph. For example, output of such algorithms is the Hamiltonian circuit with the minimum cost in case of TSP.

**Comment by jfinkels** [comment]
I'm not sure what the issue is here. Are you requesting something specific?

**Comment by dschult** [comment]
See #1508
