### ISSUE TITLE
all_shortest_paths() fails with negative weights on edges

### ISSUE THREAD

**Issue by rdebroiz** [networkx/networkx#1511]
Hello

I'm trying to get the longest paths in a directed graph by finding the shortest paths with a weight of -1 on all the edges but it fails on a diamond graph:
```
    src
  /     \
 A       B
  \     /  
    dest
```
returning only one of the paths.

```python
#[~]$ pip show networkx
#---
#Name: networkx
#Version: 1.9.1

>>> import networkx as nx
>>> 
>>> G = nx.DiGraph()
>>> G.add_nodes_from(('src', 'A', 'B', 'dest'))
# without any weights
>>> G.add_edge('src', 'A')
>>> G.add_edge('src', 'B')
>>> G.add_edge('A', 'dest')
>>> G.add_edge('B', 'dest')
>>> print([path for path in nx.all_shortest_paths(G, source='src', target='dest')] )
[['src', 'B', 'dest'], ['src', 'A', 'dest']]
>>> 
>>> 
# with negative weights
>>> G.add_edge('src', 'A', weight=-1)
>>> G.add_edge('src', 'B', weight=-1)
>>> G.add_edge('A', 'dest', weight=-1)
>>> G.add_edge('B', 'dest', weight=-1)
>>> print([path for path in nx.all_shortest_paths(G, source='src', target='dest', weight='weight')])
[['src', 'B', 'dest']]
```
Am I doing something wrong ?

**Comment by jfinkels** [comment]
After a quick look at the code for `all_shortest_paths`, I think this is because `all_shortest_paths` runs an implementation of Dijkstra's algorithm, an algorithm that does not correctly handle negative weights.

**Comment by ysitu** [comment]
If your graph is a DAG, you can take a look at #1438. Otherwise, I don't think we have anything that handles the NP-hard general problem.

**Comment by rdebroiz** [comment]
@jfinkels There are other functions related to distance between nodes having explicitly Dijkstra in their names, so i thought  that maybe `the all_shortest_paths()` function use an other algorithm that handle negative weights.

@ysitu Exactly what I'm looking for :)

Thanks to both of you.
