### ISSUE TITLE
Highly parallel algorithm for finding 2-cores in a graph

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#1524]
NetworkX currently includes a linear time sequential algorithm for computing the _k_-core of a graph, that is, the maximal subgraph of minimum degree _k_; see `networkx.algorithms.core`. There is a highly parallel algorithm for finding the 2-core of a graph, according to [this technical report](http://infolab.stanford.edu/pub/cstr/reports/cs/tr/84/1014/CS-TR-84-1014.pdf) from 1984. Rephrasing Theorem 2, it is possible to find the 2-core of a graph by a parallel algorithm using a polynomial number of processors in a polylogarithmic amount of time. Their description of the algorithm is quite terse, but maybe someone else can help me figure it out.

Here's the relevant text. Where they say _HDS<sub>k</sub>(G)_, they mean the _k_-core of the graph _G_, and where they say _NC_, they mean "with a highly parallel algorithm".

> For the case _k_ = 2, it is possible to find _HDS<sub>k</sub>(G)_ in _NC_. The algorithm for computing _HDS<sub>2</sub>(G)_ has log _n_ phases, where each phase removes all _chains_. A chain is a path of vertices that starts with a vertex of degree 1 and contains no vertex of degree greater than 2. The chains can easily be identified by path doubling techniques. When the chains are deleted, more nodes of degree 1 might be created, however each new node of degree 1 required the removal of at least two chains, so the number of chains removed decreases by at least half at each phase.

And that's it. So if anyone could clarify the "path doubling techniques" and how to ensure that each of the log _n_ phases requires only a polylogarithmic amount of work for each processor, that would be helpful.

**Comment by jfinkels** [comment]
Apparently here is an article on path doubling, also known as [pointer jumping][1].

[1]: https://en.wikipedia.org/wiki/Pointer_jumping

**Comment by hagberg** [comment]
Closed due to inactivity.
