### ISSUE TITLE
Overhead in reverse function?

### ISSUE THREAD

**Issue by SeanWhipple** [networkx/networkx#1525]
I have the following code

```
import networkx

def reverse_graph(g):
    reversed = networkx.DiGraph()
    for e in g.edges():
        reversed.add_edge(e[1], e[0])
    return reversed


g = networkx.DiGraph()

for i in range(500000):
    g.add_edge(i, i+1)

g3 = reverse_graph(g)
g2 = g.reverse()
```

And my line profiler says that `networkx.reverse` implementation takes about 20 seconds where as mine takes about 7.  What I don't understand is what's happening under the hood here.  Why does the `networkx` implementation take so much longer

**Comment by dschult** [comment]
You can look at the source code... in this case at : https://github.com/networkx/networkx/blob/master/networkx/classes/digraph.py
The general version handles isolated nodes and edge attributes as well as graph and node attributes.
