### ISSUE TITLE
Controllability of Complex Network ? 

### ISSUE THREAD

**Issue by python27** [networkx/networkx#1526]
The controllability of complex network has been a hot research topic, is there someone developing  related algorithms, for example, calculate the number of Driver Node N_D using bipartite matching or using max multiplicity method ? 

More details about these algorithms, refer to 
[1] Liu, Y. Y., Slotine, J. J., & Barabási, A. L. (2011). Controllability of complex networks. Nature, 473(7346), 167-173.
[2] Yuan, Z., Zhao, C., Di, Z., Wang, W. X., & Lai, Y. C. (2013). Exact controllability of complex networks. Nature communications, 4.

**Comment by bjedwards** [comment]
I messed with this a bit when the paper first came out. Note I haven't played with this code in quite a while so it may or may not work. Also no promises on whether this is an accurate reflection of what Lui et al did. I think I vaguely remember it working for some of the networks in the original paper, but really I am just copy and pasting. 

One scholarly note [this paper](http://www.researchgate.net/profile/Baowen_Li/publication/51947433_Controllability_of_Complex_Networks_with_Nonlinear_Dynamics/links/0c960533c6fb7c6178000000.pdf) notes that "Interestingly, for one-dimensional nonlinear nodal dynamics, any bidirectional network system can be fully controlled by a single driver node, regardless of the network topology." Also if you consider transport networks where each node has a self loop under linear dynamics this is trivially controllable by a single 'control node'. I'd be curious about more current work on this.

I could potentially turn this into a pull request, but I probably won't have time to do it for a few weeks...

```python
import networkx as nx

def to_bipartite(G):
    """Converts Directed graph G to an undirected bipartite graph
    H."""
    if not G.is_directed():
        raise nx.NetworkXError("G must be a directed Graph")
    if G.is_multigraph():
        H = nx.MultiGraph()
    else:
        H = nx.Graph()
    for n in G:
        H.add_node((n,'+'))
        H.add_node((n,'-'))
    for (u,v) in G.edges_iter():
        H.add_edge((u,'+'),(v,'-'))

    return H

def control_nodes(G):
    H = to_bipartite(G)
    M = nx.max_weight_matching(H,True)
    matched = set(v for (v,sign) in M.values() if sign == '-') | \
              set(u for (u,sign) in M.keys() if sign == '-')
    n_D = set(G) - matched
    if len(n_D) == 0:
        return [G.nodes_iter().next()]
    else:
        return list(n_D)

def controllability(G):
    return len(control_nodes(G))/float(len(G))
```

**Comment by python27** [comment]
@bjedwards did you have any interest in developing more about controllability of networks algorithms ?  In fact, I am currently doing research on controllability, I will be very happy to help to contribute code, but I am a little worried if no one else does this job, since I am very new to contribute code on github.

**Comment by bjedwards** [comment]
My summer is pretty busy, and I haven't done much on controllability since the initial paper(2011) came out. Even then, I was mostly just messing around.

Contributing is actually quite easy. If you haven't already check out the [Developer's Guide](http://networkx.github.io/documentation/networkx-1.9.1/developer/index.html). If you submit pull requests, I would be happy to review them.

**Comment by MridulS** [comment]
@bjedwards @python27 I could help around if needed :)

**Comment by hagberg** [comment]
Closed due to inactivity.
