### ISSUE TITLE
Approximate dominating set not even minimal?

### ISSUE THREAD

**Issue by bbphd** [networkx/networkx#1527]
EDIT: THERE IS A BUG AND THE ALGORITHM IS NOT THE ONE ADVERTISED.  SEE LAST 2 POSTS BY ME BELOW.  EDIT 2: Algorithm may be OK, just needs bug fix.  See my final post below.
I imagine this must be a bug in networkx.algorithms.approximation.min_weighted_dominating_set.
The result it gives is 0,1,2 and that set is still dominating even if the 0 and 1 are removed.

    >>> import networkx as nx
    >>> from networkx.algorithms import *
    >>> 
    >>> G=nx.path_graph(5)
    >>> H=nx.power(G,2)
    >>> print nx.nodes(H)
    [0, 1, 2, 3, 4]
    >>> print nx.edges(H)
    [(0, 1), (0, 2), (1, 2), (1, 3), (2, 3), (2, 4), (3, 4)]
    >>> s = min_weighted_dominating_set(H)
    >>> print s
    set([0, 1, 2])

(I am using the development version so I can use power)

**Comment by bbphd** [comment]
I looked up the reference for the algorithm, and it seems the weighted version is only guaranteed optimal within a factor of 3 (would be 2 for unweighted, but that's a slightly different algorithm?).  For the sake of elegance perhaps, the textbook does not try to improve on the approximation.  Time is O(E), how long does it take to just greedily remove any unneeded vertices?  In this example that gets you from the above solution to optimal with probability 1.

**Comment by bbphd** [comment]
It is not at all apparent that the source code is attempting to implement the algorithm in the reference.  The latter requires squaring a series of graphs and then find maximal independent sets in each, then returning the set with the best score.  The networkx algorithm seems to add nodes one at a time to the dominating set, no mention of squaring or maximal independent sets...

**Comment by bbphd** [comment]
Here's an example which I think supports my understanding of the code, which I now take to be a simple greedy algorithm with a bug in it.
The optimal answer for a star graph is just the center node.  If you label that node 0 it works.  But if you give it the highest label you get the worst possible answer (though it is a dominating set):
>>> H=nx.path_graph(1)
>>> H.add_edge(0,3)
>>> H.add_edge(1,3)
>>> H.add_edge(2,3)
>>> print nx.nodes(H)
[0, 1, 2, 3]
>>> s = min_weighted_dominating_set(H)
>>> len(s)
3
>>> print s
set([0, 1, 2])

**Comment by bbphd** [comment]
If you try the above with a 5 node star the behavior is the same, it returns 4 nodes instead of 1, so it is definitely not as good as the algorithm that is referenced. I think I know how to fix the bug so it would work in this case, but it would still just be a greedy algorithm, not the approximation cited in the reference.

**Comment by hagberg** [comment]
@mancuso can you help @bbphd with this issue?

**Comment by bbphd** [comment]
OK, I read the reference more thoroughly and it seems the algorithm I was looking at was really only for the k-sets problem.  I don't think the book gives an algorithm for dominating sets, but based on the Wikipedia article, the greedy algorithm is probably the best bet.  Now I just have to fix the bug?

**Comment by bbphd** [comment]
Well the problem is the cost function.  It is summing the weight of the node and its neighbors.  It should be just the node.  Might have to change the number of arguments to that function...

**Comment by bbphd** [comment]
So the bug should be fixed as the results are nonsense (and I'm considering trying it but I don't do much python).  But, while at it, here is a recent paper which reviews the need for post processing to make sure the result is minimal (and gives a reference), and also provides a preprocessing step that can only make it better.  Plus it indicates that in the unweighted case it is worth doing 30 iterations with random tie breaking.  Then it gives a completely different metric that is a little slower but usually gives better results.

**Comment by bbphd** [comment]
I've fixed the basic bug.  I have not done any enhancements.  Here's the fixed function
'''
   References                                                                                                                                
    ----------                                                                                                                                
    .. [1] Vazirani, Vijay Approximation Algorithms (2001)                                                                                    
    """
    if not G:
        raise ValueError("Expected non-empty NetworkX graph!")

    # min cover = min dominating set                                                                                                          
    dom_set = set([])
    cost_func = dict((node, nd.get(weight, 1)) \
                     for node, nd in G.nodes_iter(data=True))

    vertices = set(G)
    sets = dict((node, set([node]) | set(G[node])) for node in G)

    def _cost(node,subset):
        """ Our cost effectiveness function for sets given its weight                                                                         
        """
        cost = cost_func[node]
        return cost / float(len(subset - dom_set))

    while vertices:
        # find the most cost effective set, and the vertex that for that set                                                                  
        dom_node, min_set = min(sets.items(),
                                key=lambda x: ( _cost(x[0],x[1]),x[0])) # second x[0] is tie breaker, not really needed                       

        # add the node to the dominating set and reduce what we must cover                                                                    
        dom_set.add(dom_node)
        del sets[dom_node]
        vertices = vertices - min_set

    return dom_set

**Comment by jfinkels** [comment]
If you are able, can you [create a pull request][1] with the code changes and the test case you presented in your previous comments? If you are unable, let us know and someone else can do it.

[1]: https://help.github.com/articles/using-pull-requests/

**Comment by bbphd** [comment]
I might be able to figure out how to do that later, before I start
figuring that out I'd like to see what is involved to implement the
post-processing method described in the reference I cited.  For your
reference the test case I"ve looked at is star graphs n>2.  The old
code only worked if the center node had the lowest node label.  The
algorithm should always return the center node only.

**Comment by jfinkels** [comment]
I made the change suggested by @bbphd in pull request #1566.

**Comment by bbphd** [comment]
Thanks!

**Comment by chebee7i** [comment]
Fixed in #1566
