### ISSUE TITLE
Hosting a separate repository 'networkx-metis'

### ISSUE THREAD

**Issue by OrkoHunter** [networkx/networkx#1528]
@hagberg @dschult @jtorrents @ysitu 
As we are on our way to enable Add-ons for NetworkX, the first goal in this project is graph partitioning with METIS, through which I guess the idea of add-on implementation was discussed. The prototype is going to be like this
```python
>>> import networkx as nx
>>> from networkx.addons import metis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: Please install networkx-metis to enable this add-on
```
```sh
$ pip install networkx-metis
```
```python
>>> import networkx as nx
>>> from networkx.addons import metis
>>> metis.partition(nx.Graph(...), nparts)
```

So, a separate repository named 'networkx-metis` needs to be hosted for the work to start.

**Comment by chebee7i** [comment]
Looks good. @hagberg @dschult or @jtorrents should be able to create that repository for you. Question:  It says they need to install "networkx-metis" but the actual pip install command is for "metis". Should these be in agreement?

**Comment by OrkoHunter** [comment]
@chebee7i Sorry, that was a typo. It is now `pip install networkx-metis`

**Comment by SanketDG** [comment]
@OrkoHunter will `networkx-metis` will be a python wrapper for the `METIS` library?

**Comment by OrkoHunter** [comment]
@SanketDG `networkx-metis` will hold all the wrappers as well as the source codes of the `METIS` library. You can take a look at the design of `networkx.addon` [here](https://github.com/networkx/networkx/wiki/Design-and-Structure-of-the-Add-on-system).

**Comment by jfinkels** [comment]
Just a heads-up, watch out for copyright licenses when distributing source code from two different projects in a single new project (for example in a GitHub repository). NetworkX is [licensed under a BSD license][0], [METIS under an Apache License][1]. I believe they are compatible, just make sure the license requirements are met.

[0]: https://github.com/networkx/networkx/blob/master/LICENSE.txt
[1]: http://glaros.dtc.umn.edu/gkhome/metis/metis/faq?q=metis/metis/faq#distribute

**Comment by OrkoHunter** [comment]
@jfinkels Thanks for the check. I think LEMON is also compatible with NetworkX. It is licensed as [Free Software (Boost Software license)](https://lemon.cs.elte.hu/trac/lemon/wiki/License).

**Comment by ysitu** [comment]
Distribution should not be a problem. The add-ons will be hosted in their own repositories and distributed separately from the NetworkX core.

**Comment by jfinkels** [comment]
Right, but any new code (that is, the wrapper code) must be licensed under a compatible license. I assumed you would require a BSD license to match the NetworkX core.

**Comment by chebee7i** [comment]
Is it actually necessary for the addons to have a compatible license?  Honest question. 

If these addons were separately installed and not officially part of NetworkX, it seems no different than if NetworkX had imported NumPy which, on some particular computer, had been compiled to make use of Intel's MKL. In principle, users can put whatever they want in the package that NetworkX will try to import. It just has to implement an interface that the NetworkX code has been written to expect.

**Comment by jfinkels** [comment]
As usual, the answer is "it depends". If you publish a repository, say
"networkx-metis", that includes both the METIS source code licensed under
Apache and additional wrapper code licensed under BSD, then you might be
considered to be distributing a derivative work of METIS. If the repository
"networkx-metis" includes only the wrapper code, then it is probably not
considered a derivative work. (Although the jury's still out on [whether an
API itself is copyrightable][1] :\ .)

[1]: https://en.wikipedia.org/wiki/Oracle_America,_Inc._v._Google,_Inc.

**Comment by chebee7i** [comment]
If we are talking about the wrapper code, then sure.  What I meant was that the wrapper code need not have the same license as NetworkX itself.  So if necessary, the wrapper code could be Apache licensed to match METIS, and NetworkX could still import it. Right?

**Comment by jfinkels** [comment]
That's true, but I assumed you might want everything distributed under the
"NetworkX" brand to have the same license, for consistency.

**Comment by OrkoHunter** [comment]
@hagberg Ping.

**Comment by ysitu** [comment]
@jfinkels The value in license consistency is limited in this case. Be it BSD, Apache or Boost, the license terms are quite permissive. In most situations, users have no need to worry about mixing them in their projects. I would rather spend time on software engineering than (most likely incorrectly) interpreting license legalese. We should just use the same license as the wrapped code and call it a day.

**Comment by SanketDG** [comment]
The repo is up at [networkx-metis](https://github.com/networkx/networkx-metis).

**Comment by jfinkels** [comment]
@ysitu That's fine, this was basically just a heads up that there are copyright issues at play here.
