### ISSUE TITLE
Most utility functions should not be exposed to the end user

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#1533]
Many functions in the `networkx.utils` package are [documented][1] and exposed to the end user, but most of them should not be. The purpose of NetworkX is to provide graph data structures, generators, algorithms, etc., not to provide functions like `flatten` or `is_list_of_ints`. These are used internally, and implementation details should not be exposed to the user. For a few of these, you might make a (weak) case for exposing to the end user, for example, `cuthill_mckee_ordering`, but if these should be made available, they should not be under the `networkx.utils` package.

[1]: http://networkx.github.io/documentation/development/reference/utils.html

**Comment by dschult** [comment]
I don't see the harm in keeping them public. Is pollution of the namespace the concern? How many such functions are we talking about?

**Comment by hagberg** [comment]
We don't import them into the networkx namespace other than at networkx.utils.  We could not import them at all by default if that helps.

**Comment by jfinkels** [comment]
There are several issues: the utility functions are documented, tested, and
importable as part of the public API. These helper functions are part of
the *internal implementation* of the functions in the project. This is a
problem for the following reasons.

- Implementation details should not be documented (with the possible
exception of asymptotic complexity due to implementation). Unnecessary
documentation adds noise to the (already quite lengthy) documentation, and
therefore makes it more difficult for the user to use efficiently.
- Implementation details should not be tested, only behavior of public
functions should be tested.
- Implementation details should not be exposed to the user. If you feel
that a function should be exposed to the user, that function should not be
considered a "helper function", and it should live in the main package, not
a `utils` package.

**Comment by jfinkels** [comment]
Allow me to clarify the first item I listed above:

>  - Implementation details should not be documented [...]

Implementation details should not be documented *as part of the public documentation*. Every function should have complete docstring explaining how to use it.

Allow me also to respond to @dschult's [comment][1] on a different issue.

> It's also a little disappointing to see essentially arbitrary rules stated with such rigidity.

Well, these are rules that I have personally found beneficial in practice.

> The overarching principles we look for are ease for new users to do simple things and learn more while they do it, and ease for experienced users to do complicated things without a lot of trouble.

I agree of course! That's why I suggest putting functions that you intend users to use in a relevant "main" package, not a `utils` package (the name of which doesn't provide much hint as to what the functions might do).

> [...] making helper functions public and documenting them [...] makes them easy to find and people can get ideas from them (and maybe even USE them...horrors...)

Well, the question is then "why should users find these functions?" If they are important enough that they should be visible to a user, then they should be in a "main" package. If it is to learn from them, they can often find that information elsewhere (`flatten()` and `is_list_of_ints()` are good examples of functions whose implementations could be find by a search on StackOverflow, for example).

[1]: https://github.com/networkx/networkx/pull/1673#issuecomment-123478595

**Comment by hagberg** [comment]
If you look around the utils package there is a pretty diverse collection of code and algorithms.  I'd say most of them are not very closely related to graph theory or network science which is likely why they ended up there.  I don't see any reason to be prescriptive for what belongs there or why.  In general I would argue it is good to keep the amount of code there somewhat limited so we don't end up with a package of utility functions copied from stackoverflow that  also happens to have graph algorithms.

**Comment by hagberg** [comment]
I think we are agreeing to disagree here.  So let's leave it at the status quo until we find a good reason we agree on to make a change.
