### ISSUE TITLE
Possible bug in nx.relabel_nodes

### ISSUE THREAD

**Issue by AgostinoSturaro** [networkx/networkx#1539]
Relabeling nodes to their own id when `copy=False` can create problems

    import networkx as nx
    
    G = nx.Graph()
    G.add_nodes_from([(0, {'data': 0}), (1, {'data': 0}), (2, {'data': 0}), (3, {'data': 0}), (4, {'data': 0})])
    print('G.nodes(data=True) = ' + str(G.nodes(data=True)))
    
    # this will print an empty graph, or a graph where nodes lost their data
    nx.relabel_nodes(G, mapping={0: 0, 1: 1, 2: 2, 3: 3, 4: 4}, copy=False)
    print('G.nodes(data=True) = ' + str(G.nodes(data=True)))
    
    # this works
    nx.relabel_nodes(G, mapping={0: 1, 1: 2, 2: 3, 3: 4, 4: 5}, copy=False)
    print('G.nodes(data=True) = ' + str(G.nodes(data=True)))

Now, why would I want to relabel nodes the same as before?
This was actually a corner case of an algorithm that did relabeling. It was supposed to do nothing in this case, but instead it messed the graph, so I got to notice.

**Comment by hagberg** [comment]
That looks like a bug.  Suggestions for a fix?

**Comment by AgostinoSturaro** [comment]
Well, if you are asking me, the quickest fix could be checking if the ids are the same as before and doing nothing.
There is probably a better one, but I would need to look through the code of the function.

**Comment by hagberg** [comment]
I can't think of a better way right now.  I think the corner case is that the mapping function ( a dictionary) has exactly the same keys as values.  So that is pretty simple to check - something like list(mapping.keys()) == list(mapping.values())
?

**Comment by AgostinoSturaro** [comment]
That's what I do in my code right now. Having this fix in the library would avoid nasty surprises like the one I had.

However, I can't quite understand why the function would behave like that, maybe it's worth having a look at it.

**Comment by chebee7i** [comment]
Fixed in #1544
