### ISSUE TITLE
Add algorithm for computing toughness of a graph

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#1553]
[Graph toughness](https://en.wikipedia.org/wiki/Graph_toughness) is a measure of connectivity of a graph. Even for a fixed arbitrary toughness value, determining whether the graph has that particular toughness value is [coNP-complete](http://dx.doi.org/10.1016/0166-218X%2890%2990001-S), so finding the minimum toughness is even harder. Indeed, even [approximating the minimum toughness of a graph is hard](http://dx.doi.org/10.1016/j.disc.2003.10.013). That being said, NetworkX does include exact algorithms for some intractable problems, so this may be of interest.

**Comment by hagberg** [comment]
Closed due to inactivity,
