### ISSUE TITLE
Expanded datatypes for graphml writer

### ISSUE THREAD

**Issue by chebee7i** [networkx/networkx#1556]
The GraphML writer doesn't handle NumPy floats since it only knows to accept Python floats. I'm sure we can make this a bit easier for users.

**Comment by SanketDG** [comment]
The writer should work with `numpy.float` variables, since `numpy.float` is just an alias to python's `float` type:

```python
>>> import numpy as np
>>> x = np.float(32.45)
>>> type(x)
<type 'float'>
```
Are you talking about `float32` and `float64` in numpy? Worth noting that they are single and double precision datatypes respectively.

**Comment by chebee7i** [comment]
I don't think the precision matters, since we don't seem to care about the precision when writing regular Python floats to GraphML either.

**Comment by dschult** [comment]
@chebee7i do you have some ideas for how to approach this? 
Otherwise I'm going to bump it to networkx-2.1

**Comment by zfrenchee** [comment]
This is still an issue in networkx 2.1.
