### ISSUE TITLE
relabel_nodes removes disjoint nodes for identity mapping with copy=False 

### ISSUE THREAD

**Issue by pbattaglia** [networkx/networkx#1561]
import networkx
G = networkx.Graph([(0, 1)])
G.add_node(2)
mapping = {1:1, 2: 2}
print("before: ", G.nodes())
nx.relabel_nodes(G, mapping, copy=False)
print("after: ", G.nodes())

The simplest fix is probably just to filter out identity mappings at the beginning of "relabel_nodes.py":
fixed_mapping = {k: v for k, v in mapping.iteritems() if k != v}

**Comment by dschult** [comment]
I think this has been reported and subsequently fixed in #1544 
Are you using those changes? Do they fix it?

**Comment by SanketDG** [comment]
Disjoint nodes are not removed in the lastest build of `networkx`.

**Comment by dschult** [comment]
I'm going to close this...  You can reopen if the recent changes don't fix the problem.
