### ISSUE TITLE
Add clique?

### ISSUE THREAD

**Issue by chebee7i** [networkx/networkx#1562]
We have methods for adding paths, cycles, but not cliques. Should we add this?

**Comment by OrkoHunter** [comment]
Sounds nice! Although searching for a clique in a graph is not so efficient, we can have `add_clique` like `add_cycle`, `add_star` etc.

**Comment by OrkoHunter** [comment]
Looks like we already have `find_cliques`. I didn't know that.

**Comment by hagberg** [comment]
We have considered this before.  What does DiGraph.add_clique() do?
If I remember right I think last time I advocated for removing add_path, add_star, etc at the end of the discussion.

**Comment by OrkoHunter** [comment]
@hagberg As of now, I didn't find any `add_clique` in Digraph class. Maybe it had been already removed? Was it there before anytime?

**Comment by dschult** [comment]
We've never had add_clique before...  I think @hagberg is pointing out that it is not so clear what it would actually do. Would it require an iterable of nodes to put into the clique? etc...
I think there is probably a good way to approach this.... somehow...  but I do remember @hagberg eventually advocating for removing add_star/path/etc :)

**Comment by OrkoHunter** [comment]
@dschult Some good usecase of these methods are still not so much known to me. Maybe @chebee7i would suggest some for `add_clique`?

**Comment by chebee7i** [comment]
That's right, I remember that discussion as well. If we want to remove them, this would be a nice time. It's not even clear what `add_clique` would do for directed graphs and I think we'd have to use multiple inheritance to make this work properly. 

I do think these would be better served as functions. Then `add_clique` would only work on undirected graphs.  What would this be used for? Constructing a graph where you want to subsets of nodes to form a clique.

**Comment by OrkoHunter** [comment]
Wikipedia says few lines about this
> Although the study of complete subgraphs goes back at least to the graph-theoretic reformulation of Ramsey theory by Erdős & Szekeres (1935),[1] the term clique comes from Luce & Perry (1949), who used complete subgraphs in social networks to model cliques of people; that is, groups of people all of whom know each other. Cliques have many other applications in the sciences and particularly in bioinformatics.

If all such functions are to be removed then no problem, else we can go with this implementation in `Graph` class.
```python
def add_clique(self, nodes, **attr):
    nlist = list(nodes)
    edges = itertools.combinations(nodes, 2)
    self.add_edges_from(edges, **attr)
```

**Comment by hagberg** [comment]
See #1883.
