### ISSUE TITLE
maximal_matching in v1.9.1 (latest)

### ISSUE THREAD

**Issue by AgostinoSturaro** [networkx/networkx#1564]
I have found a case where a maximal matching between 14 nodes can be found, but the algorithm only finds it for 12 of those nodes.

Here is a hand built example.
![graph to match](https://cloud.githubusercontent.com/assets/1441393/7997658/34c159e6-0af6-11e5-9de0-4ab8d285b373.png)

This is a maximum matching I found by hand.
![correct maximal matching](https://cloud.githubusercontent.com/assets/1441393/7997662/39309eba-0af6-11e5-9a30-f30ba9f5409d.png)

When running `maximal_matching` on that undirected graph, NetworkX v1.9.1 proposes me this matching, which is not maximal (node 3 and node 8 are not matched).
![wrong graph matching](https://cloud.githubusercontent.com/assets/1441393/7997682/9dbc3c7c-0af6-11e5-877f-1bc0789a081f.png)

Here is the adjacency list representing the graph

    11 5
    10 1 5
    13 1 0 3 2 5 4
    12 3 6
    1
    0 9
    3
    2 7
    5
    4 9 8 7
    7
    6
    9
    8

Maybe this is a residual problem from version 1.8.1, mentioned in  #1558?

EDIT: I just found out that *maximAL* matching is not the same as a *maximUM* matching, so this behavior is probably technically correct
however,
if I search on Google "maximal matching", the first page of results is all about "maximUM matching".
Moreover, if I search "maximal matching networkx", the very first result points to the [matching doc](https://networkx.github.io/documentation/latest/reference/algorithms.matching.html)
It doesn't even warn "maybe you meant...".

The problem people are commonly facing is to search for a maximUM matching.
That maximAL matching thing there is just tricky.

**Comment by ysitu** [comment]
There is nothing tricky. Both "maximal" and "maximum" (and their min- counterparts) are well-defined technical terms. You may find them ambiguous in nontechnical contexts. But NetworkX is not one of those.

**Comment by AgostinoSturaro** [comment]
A notice, however small, that they are different things, and what makes them different, could do a lot of good to people arriving to the doc page from Google.

Besides, it would be nice to have maximum matching for at least bipartite graphs.

Thanks.

**Comment by ysitu** [comment]
`max_weight_matching` serves the purpose of finding maximum matchings.

**Comment by AgostinoSturaro** [comment]
That worked. Thanks.

I read the worst case complexity is O(n**3). Is that true for bipartite graphs also?
If so, would it be faster to solve the problem as a maximum network flow when the graph is bipartite?

Here's a link to give the idea (see slide 15)
https://www.cs.cmu.edu/~ckingsf/bioinfo-lectures/matching.pdf

Some libraries, like igraph, provide a separate function for just that case, i.e. [maximum_bipartite_matching](http://igraph.org/python/doc/igraph.Graph-class.html#maximum_bipartite_matching).

**Comment by ysitu** [comment]
See #1322.

**Comment by AgostinoSturaro** [comment]
That algorithm will actually be in `networkx.algorithms.bipartite.matching`, maybe referencing it in the matching section of the doc would make it easier to find?

Thanks.
Looking forward to v1.10.

**Comment by jfinkels** [comment]
Yes, this is a documentation bug. The documentation for `networkx.algorithms.matching` should indicate that bipartite graphs can be matched via the `networkx.algorithms.bipartite.matching` functions.
