### ISSUE TITLE
Documentation is not automatically built on commit

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#1571]
Does someone manually build and upload the documentation for NetworkX? Why is it not automatic?

**Comment by chebee7i** [comment]
I think it is manually done or periodically (but not on each commit).  A port to use ReadTheDocs would be a nice task to complete if someone had the time.

**Comment by SanketDG** [comment]
Yeah, this really needs to be automated, or for the meantime passed onto someone who has time to make and push it.

**Comment by jfinkels** [comment]
FYI, [does ReadTheDocs work with numpydoc?][1]

[1]: http://docs.readthedocs.org/en/latest/faq.html#does-read-the-docs-work-well-with-legible-docstrings

**Comment by chebee7i** [comment]
I think they use napolean which is now part of Sphinx proper, and it supports both Google docstring and numpydoc.

**Comment by chebee7i** [comment]
https://github.com/networkx/networkx/issues/1221

**Comment by hagberg** [comment]
#1597 fixes the issues that were breaking the doc builds. 

I have been building the docs nightly at around midnight US Mountain time.  But it's too hard to stay up that late. If we can use RTD to build them automatically that would be great.

Note that there are also pdf versions.  I'm not sure if anyone looks at those though.

**Comment by hagberg** [comment]
The documentation was correctly built with my automated scripts and appears at http://networkx.github.io/documentation/development/

But this isn't resolved.  It would be better to have the documentation built with a system that is not dependent only on me (not noticing it is broken, machine down, etc).

**Comment by chebee7i** [comment]
Can you enable the readthedocs GitHub hook for the networkx repo? I've got the initial configuration ready at readthedocs.org. All maintainers will have access to it if they give readthedocs access to their Github account.

**Comment by SanketDG** [comment]
Yeah, using `napolean` and readthedocs will minimize documentation related issues. I built the docs using napolean, it really renders nicely with the default theme, and everything is automated.

**Comment by hagberg** [comment]
OK - I added the readthedocs hook.

**Comment by dschult** [comment]
I'm going to close this issue since we have readthedocs turned on now.
But I'm going to open another issue about what to do until readthedocs updates to a version of sphinx that allows autosummary to work.
