### ISSUE TITLE
Add postprocessing heuristic to improve approximate dominating set

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#1572]
Add the postprocessing heuristic that improves the approximate dominating set algorithm as suggested by @bbphd in https://github.com/networkx/networkx/pull/1566#issuecomment-110189242. The suggested change is in a gist at https://gist.github.com/jfinkels/9ea6ef5cb50789328c42.

I'll create a pull request implementing this change.

**Comment by jfinkels** [comment]
@bbphd, your comment from issue #1566 was

> Any node in the dominating set is redundant if its neighborhood (including itself) is a subset of the union of the neighborhoods of the other elements of the dominating set. The depth of redundancy is the smallest number of extra times any element in a node's neighborhood is covered. The most deeply redundant node is removed first--(highest cost first in case of ties). This continues until the answer is minimal (i.e., all nodes have zero redundancy).

How does this affect the running time of the algorithm?

**Comment by jfinkels** [comment]
Also, your reference seems to be [this paper][1], is that correct? If so, can you indicate the place in the paper that has the postprocessing algorithm you suggest, so that we can find it easily?

[1]: http://dx.doi.org/10.1016/S0377-2217(96)00161-0

**Comment by jfinkels** [comment]
The example graph you give at the bottom of the file does not have any dominating set of size two, the smallest is size three, so without the postprocessing, the approximate dominating set should be at least size three.

**Comment by jfinkels** [comment]
Oh, sorry I see the dominating set of size two, nevermind that last comment.

**Comment by bbphd** [comment]
That is the correct reference, but it's just a paragraph that is
rather hard to read and no useful commentary.  To actually read
something easy to follow look at section 3.5 in
http://arxiv.org/abs/1305.3584

**Comment by bbphd** [comment]
First of all, there's a copyright claim in there I had not noticed.
Is that valid?  If it is I don't know that we can modify this and
should revert or rewrite or get permission?
The claim in the code that the greedy algorithm runs in O(|E|) seems
wrong.  It seems to me that on a large path graph it will be like
O(|V|^2), and in general probably O(|E|+|V|^2).
I think in practice the post-processing will be of the same order,
usually much faster, but to be safe probably should only update
redundancy on nodes where it might change.  But let's resolve the
copyright...

**Comment by jfinkels** [comment]
Are you referring to the copyright notice at the head of the `approximate/dominating_set.py` file? The original author licensed his work under [the BSD license][1], so as long one abides by the requirements of that license (and NetworkX does), that's not a problem. (The "All rights reserved" is dubious; only *some* rights are reserved when a work is distributed under a BSD license. This is something the Creative Commons organization calls ["Some rights reserved"][2].)

This is why free and open source software is good: it subverts the "permissions culture" surrounding creative works (in the United States) in order to "[promote the progress of science and useful arts][3]", the original intent of copyright!

[1]: https://github.com/networkx/networkx/blob/master/LICENSE.txt
[2]: https://wiki.creativecommons.org/Frequently_Asked_Questions#What_does_.22Some_Rights_Reserved.22_mean.3F
[3]: https://en.wikipedia.org/wiki/Copyright_Clause

**Comment by bbphd** [comment]
OK good.  Tomorrow I'll add one if statement and hopefully do some
timing experiments?

**Comment by jfinkels** [comment]
I'm not sure which if statement you're thinking of, but please do take a look at the code I modified from your original suggestion at pull request #1573 and make any new suggestions there. Alternately, if you think my code is way off, make a new pull request with your own changes.

**Comment by bbphd** [comment]
Unfortunately I did not see your message while I was working on fixing
another little bug that was in the old function.  I found a test case that
illustrates it well, (in particular with post_process=False).
Here's a link to my revised code on gist, which has the example at the
bottom, and also has efficiency improvements.  Unfortunately I broke the
code, but you  can copy the test case if you want.  I'll try to fix it
and/or look at what you did...
https://gist.github.com/bbphd/72543f4d37ac965dd7e4

**Comment by bbphd** [comment]
I am not qualified to judge coding quality but yours looks nicer than mine
to my untrained eye.  However, there are two lines where you define
redundancy that end with "for u in G".  In both cases it should be "for u
in dom_set"  which will make it faster but ultimately give the same result.

I do think the comment claiming running time of O(E) is wrong, don't you?

**Comment by bbphd** [comment]
OK I got my version to run right again.
Turns out one of the test cases needs to be modified so that it works
reliably right with the corrected code (and depends only on the graph, not
the labels).
https://gist.github.com/bbphd/72543f4d37ac965dd7e4

**Comment by bbphd** [comment]
There was one bug I forgot to fix when I updated the revision of
jfinkels.  The cost function should only consider the nodes not yet
covered.  Subtracting dom_set doesn't do it; you also have to subtract
all of their neighborhoods.  Or, just intersect with vertices.  See my
Gist; same one as my last post.
