### ISSUE TITLE
No demo screenshots in your documentation?

### ISSUE THREAD

**Issue by jyuhuan** [networkx/networkx#1576]
Wouldn't it be better if screenshots of graphs were provided in your documentation? It would greatly help people who are scanning through the document to find a particular way to use your library.

**Comment by jfinkels** [comment]
Can you give a specific example that you found confusing in the
documentation and would be clearer with a visual example?

**Comment by OrkoHunter** [comment]
@jyuhuan Ping.

**Comment by hagberg** [comment]
Let's use Jupyter notebooks for this #1754
