### ISSUE TITLE
IPython Notebooks based networkx tutorials 

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#1581]
I have started writing tutorials using IPython notebooks for NetworkX at https://github.com/MridulS/NetworkX-Tutorial .

Please feel free to correct me and contribute to it :)

**Comment by OrkoHunter** [comment]
Seeing the tutorial part in the official documentation and then imagining the equivalent iPython notebooks, I wish there was some Scipy/PyCon workshop based on it. Divided it into 2-3 videos and having it online would be extremely helpful. Those video tutorials also come very handy and are preferred as equivalently as written tutorials.
Let's see if it's possible in new feature.

@MridulS Commendable start! +1

**Comment by harrymvr** [comment]
You could also check the notebooks on graph analysis that we developed as part of a data science course. 

http://nbviewer.ipython.org/github/dataminingapp/dataminingapp-lectures/blob/master/Lecture-17/GraphAnalysis-I.ipynb

http://nbviewer.ipython.org/github/dataminingapp/dataminingapp-lectures/blob/master/Lecture-18/GraphAnalysis-II.ipynb

The material is under a CC Attribution license.

**Comment by MridulS** [comment]
@harrymvr Thanks for pointing out these files.

**Comment by MridulS** [comment]
A new repo for ipython notebooks is made for examples and tutorials. networkx/notebooks
