### ISSUE TITLE
to_agraph failing on node attribute name `n`

### ISSUE THREAD

**Issue by jdrudolph** [networkx/networkx#1582]
I have some graph where I add the node attribute `n`

```
G = nx.DiGraph([(1,2)])
G.node[1]['n'] = 1
nx.to_agraph(G)

networkx/drawing/nx_agraph.py:146
TypeError: add_node() got multiple values for argument 'n'
```

Is this behavior wanted? For semantic reasons I would enjoy having 'n' as a node attribute. I am aware that `G.add_node(3, n=10)` has the same behavior. This is the part of `to_agraph` where the error occurs:

```
def to_agraph(N)
    ...
    # add nodes
    for n,nodedata in N.nodes(data=True):
        A.add_node(n,**nodedata)
    ...
```

I would suggest the following change: Allow for a keyword argument to define the attributes one wants to export.

```
def to_agraph(N, node_attr=None):
    ...
    # add nodes
    for n,nodedata in N.nodes(data=True):
        A.add_node(n,**{k: v for k,v in nodedata.values() if node_attr is None or k in node_attr})
    ...
```

The argument would have to be propagated upwards to `nx.draw_networkx` etc. but would allow for an easy attributes filter.

**Comment by chebee7i** [comment]
This is definitely a bug. `n` should be an acceptable node attribute.

**Comment by chebee7i** [comment]
The issue, of course, is that we have to use some name for the parameter to `add_node`. We could change it to `def add_node(self, _n, attr_dict=None, **attr)` or you can pass it in as: `G.add_node(3, attr_dict={'n': 10})`. Not sure if we should change or you should.

**Comment by jdrudolph** [comment]
@chebee7i This is why I'm asking here before I decide to change my personal networkx branch or my project.

Currently it is at least consistent that both `nx.Graph.add_node` and `pygraphviz.AGraph.add_node` do not allow 'n' to be passed in as keyword argument. The latter does not allow for a `attr_dict` though. Should I propose the change in `pygraphviz` instead?

**Comment by chebee7i** [comment]
I'm not sure. 

I just opened #1583 which would change the `n` in `add_node` to a `u` (but `u` as an attribute name would still be problematic). This is mostly a consistency issue, but it would address your problem (at least for networkx). As for pygraphviz, you should definitely open an issue there and link to it here. I think adding an `attr_dict` makes sense, independent of whether `n` is changed to `u` throughout the code.

**Comment by jdrudolph** [comment]
I opened an issue in pygraphviz/pygraphviz#57

**Comment by yashu-seth** [comment]
@chebee7i @jdrudolph @hagberg @dschult
Is this issue still open? I would like to work on this.

**Comment by hagberg** [comment]
We could at least fix the (narrow) issue posed here with the suggested
```python
def to_agraph(N, node_attr=None):
    ...
    # add nodes
    for n,nodedata in N.nodes(data=True):
        A.add_node(n,**{k: v for k,v in nodedata.values() if node_attr is None or k in node_attr})
   ```
