### ISSUE TITLE
Normalize node variable in function signatures.

### ISSUE THREAD

**Issue by chebee7i** [networkx/networkx#1583]
For methods/functions like `G.add_node` and `G.add_edge`, we allow arbitrary attributes to be passed in at the same time. The name choice for the arguments essentially excludes them from being keyword arguments at call time.

For example, `G.add_node` does not allow passing attributes with names `n` or `attr_dict`, while `G.add_edge` does not allow attributes with names `u` or `v`, or `attr_dict`.

We probably should mention somewhere that `n`, `u`, `v`, `attr_dict` are "special" attribute names that cannot be specified in some function signatures, but can still be added via other routes.

I'm wondering if we should normalize usage and always use `u` whenever we are using `n`. This would make `u`, `v`, and `attr_dict` the only special attribute names. This frees us `n` which is perhaps a more common choice for an attribute name having to deal with "the number of".

**Comment by hagberg** [comment]
How many places do we need to consider this?  Could we switch to *args processing instead?
It would make the function signature less nice.

**Comment by dschult** [comment]
It looks like this is pervasive: 
```add_node, add_nodes_from, add_edge, add_edges_from, __init__, add_weighted_edges_from, add_star, add_path, add_cycle```
And these are just from the graph.py file.

In most cases, it means we can't have attributes named: ```self, nodes, n, u, v, attr_dict, ebunch``` and I agree that n,u,v are poor choices to rule out.  But I think worse is for ```__init__``` we have ruled out ```data``` as a graph attribute name.

We could get around all of this by using ```(*args, **kwargs)``` and implementing our own argument parsing. For add_node it is not much slower (~15%), but it's ugly and cumbersome: 

    def add_node(*args, **attr):
        nargs = len(args)
        try:
            self = args[0]
            n = args[1]
        except:
            e="add_node() takes at least 2 arguments ({} given)"%nargs
            raise TypeError(e)
        if nargs>3:
            e="add_node() takes at most 3 arguments ({} given)"%nargs
            raise TypeError(e)
        # set up attribute dict
        if nargs==2:
            attr_dict = attr
        else: # nargs==3
            attr_dict = args[2]
            try:
                attr_dict.update(attr)
            except AttributeError:
                raise NetworkXError(\
                    "The attr_dict argument must be a dictionary.")
        #Now we're ready to add the node

Maybe the best thing is to change these names to more obscure spellings so the difficulty won't arise often.  Perhaps 

    def add_node(self, node_to_be_added, attr_dict=None, **attr)
    def add_nodes_from(self, nodes_to_be_added, **attr)
    def __init__(self, init_data=None, **attr)

**Comment by dschult** [comment]
Another approach to help with this issue is to use underscores for argument names.

```def add_node(self, _n, **attr)```

**Comment by NeilGirdhar** [comment]
This might become a bigger issue with the next release since `attr_dict` has been removed in a lot of places.  I suggest using more descriptive names than `n`, `u`, and `v`.  E.g., `node_name`.

**Comment by dschult** [comment]
How is ```ekey``` for the keyword name of the edge key variable in all graph methods?  
@chebee7i any thoughts?

I'm working on changing keyword arguments so they don't get clobbered.
The one I'm having the most trouble with is ```key``` for ```G.add_edge()```.
I should rename it because it can get clobbered by ```**kwargs``` and it is a potentially very common name for edge attributes.  Bu then G.remove_edge and others should change so they don't use ```key``` while ```add_edge``` uses something else.

**Comment by dschult** [comment]
In #2824 I'm leaving key as an argument for the edge key. 
I think this could potentially be trouble, but changing the name introduces a lot of subtle bugs for anyone who currently uses ```key=``` (which a lot of our tests do). We haven't had requests for avoiding ```key``` yet. So I'm just going to leave it and fix the others.
