### ISSUE TITLE
N-Path graphs

### ISSUE THREAD

**Issue by pabloem** [networkx/networkx#1584]
I'd like to jump in to implement a function to calculate N-Path graphs. For a graph `G=(V,E)`, it's n-path graph is `Gn = (V, E')`, where `(c,b)` belongs to `E'` iff there is an path in G with n-steps that connects c and b.
If the adjacency matrix for graph `G` is `A`, then, the adjacency matrix for a 2-path graph `G2` is `AA`, and for a 2-path graph `G3` is `AAA`, and so on.

This is more thoroughly defined here:
Escalante, F., L. Montejano, and T. Rojano. "Characterization of n-path graphs and of graphs having nth root." Journal of Combinatorial Theory, Series B 16.3 (1974): 282-289.

Also, this can also be used to calculate cocitation, and bibliographic coupling networks.

Is there will in networkx to have this algorithm implemented? I'd do all/most of the work : )
Regards

**Comment by jfinkels** [comment]
I essentially started this in #1307 but ran into some issues with terminology, multigraphs, etc. You may want to check out what I did there, and check out #1399 as well.

**Comment by pabloem** [comment]
I see that it has been implemented in #1399. Fair enough, then. : )

**Comment by jfinkels** [comment]
I would call this the "power graph", but if there is another well-known name, it should be documented, at least...

**Comment by pabloem** [comment]
Well, the paper that I cite is the first one defining it, and has been cited 30 times only. I feel that it might not be well known. "Power graph" might be enough. What do you think?

**Comment by pabloem** [comment]
I am seeing in http://mathworld.wolfram.com/GraphPower.html that the power of a graph is the **sum** of  the first `k` powers of an adjacency matrix (e.g. the power 3 of a graph represented by a matrix `A` is `P=A+AA+AAA`). This is different from what I suggest here. An n-path graph is represented only the n-th power of its adjacency matrix. Is there place in here for a function of this kind?

**Comment by jfinkels** [comment]
Yeah, that's what I originally had in #1307; see [line 223][1]. I called that a "power graph" but the name seems to be overloaded in different parts of computer science. Perhaps you can rename the functions I have there?

[1]: https://github.com/networkx/networkx/pull/1307/files#diff-414eaa09098b00206eecbff1d545bbf4R223

**Comment by pabloem** [comment]
Yeah that makes sense. I see that it's all implemented. So it'd just be rename the function, and convince everyone of including it?

**Comment by chebee7i** [comment]
I don't think it'd take much convincing. We were just caught up on the naming; being able to take the n-th power in this manner is certainly a useful operation.

**Comment by pabloem** [comment]
Okay then : ) how should I proceed? Clone @jfinkels 's repo, do the changes and make a pull request?

**Comment by jfinkels** [comment]
You can just check out my pull request as a branch on your local machine.
Here's one way to do that:
http://nedbatchelder.com/blog/201407/fetching_github_pull_requests.html

Then you can just add your commits on top of mine and create a new pull
request.

**Comment by pabloem** [comment]
okay then. I'll be back soon : )
