### ISSUE TITLE
nx.MultiGraph.degree_iter() reports wrong degree for Graphs with self loops

### ISSUE THREAD

**Issue by debsankha** [networkx/networkx#1585]
For multigraphs with self loops, degree() method returns wrong result:

 ```python
In [41]: L=nx.MultiGraph()

In [42]: L.add_edge(1,2)

In [43]: L.add_edge(1,1)

In [44]: L.add_edge(2,2)

In [45]: L.degree()
Out[45]: {1: 3, 2: 3}

In [46]: L.edges()
Out[46]: [(1, 1), (1, 2), (2, 2)]
```

Obviously, both  the degrees should be 2, not 3.

**Comment by hagberg** [comment]
We are using the convention that a self-loop adds 2 to the degree.

**Comment by debsankha** [comment]
Ahh I see. Thanks a lot for so quick reply. 
Closing the issue.
