### ISSUE TITLE
Removal of adjacency_list() 

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#1591]
Currently we have two ways to report adjacency, by `adjacency_list()` and `adjacency_iter()`. It seems that no algorithm uses `adjacency_list()`. Is there any specific reason of keeping `adjacency_list()` , should we remove it from the base classes and go forward with `adjacency_iter()` only?

@hagberg @ysitu @dschult @chebee7i @jfinkels

**Comment by dschult** [comment]
That sounds good to me.

**Comment by hagberg** [comment]
I'm not trying to generate a long sidetrack here but...

How about exposing the adj dictionary as Graph.adjacency()?  Then (with Python3 anyway) you get iterable views with Graph.adjacency().items(), etc.

**Comment by MridulS** [comment]
Exposing adj dictionary sounds like a good idea. I'm +1 on this.

**Comment by dschult** [comment]
Is there an difference/advantage of G.adjacency().items() over G.adj.items()?

**Comment by hagberg** [comment]
Yes, it doesn't expose the internal data structure but instead provides an interface to it.
But I was thinking it would be exactly the same thing.

Which brings up a question - on which PR/Issue should I raise it or maybe we already have? - is the plan to return actual iterators for methods or, like the one proposed above, is an iterable view OK too?

**Comment by dschult** [comment]
Am I right that exposing the internal data structure and providing an
interface that returns it are the same thing?
Now if G.adjacency() could provide an interface that gave an immutable
(maybe view?) version of G.adj then I see nice advantages.

As for iterators vs iterable views:  Right now the changes are creating
iterators. For python 3 we create an iterator of a view like:
```iter(self.node.items())```

Is there an easy way to create views of dicts in python 2.7?  If so we
could think about shifting to returning views instead of iterators.

As part of this dicsussion, can you lay out what the trade-offs are for
views vs iterators?​

**Comment by jfinkels** [comment]
In Python 2.7 you need to use, for example, [`dict.viewkeys()`][1] to get a view. In Python 3, `dict.keys()` does the same thing.

[1]: https://docs.python.org/2.7/library/stdtypes.html#dict.viewkeys

**Comment by hagberg** [comment]
Yes, G.adj and G.adjacency() would be the same then for this implementation. 
But perhaps somebody wanted to use a different "backend", then this would facilitate that without having to make adj be a dict-like object (which of course is also do-able).

**Comment by dschult** [comment]
Is there a way to get viewkeys() without using version speciifc syntax? 
We currently use e.g. ```iter(self.adj.items())``` to get an iterator.
Is there a version agnostic way to get a view?

**Comment by hagberg** [comment]
The question is whether we are specifying that we return an iterator or a no-copy iteratable for the graph classes.
Python 3 gives us iterable views that allow low memory traversal of e.g. dicts.  But do we get much with that here?  e.g. re-use.  

One reason we wanted to use iterators was to reduce the memory of building a potentially large list or other data structure in cases where it wasn't needed (G.edges()).

**Comment by hagberg** [comment]
No there is no version-agnostic way to do it as far as I know.  But adj.items() works for both Python2 and Python3 with the benefit of being a view in Python3.   

And I don't care about improving Python2 performance...

I'm too busy improving my FORTRAN77 code. :smiley:

**Comment by hagberg** [comment]
We're all using Python3 right?

**Comment by dschult** [comment]
Using pypy more than Python 3 at this point, right?      (ok... almost always python2.7 here...:)

I think I prefer an iterator for G.edges() but perhaps I don't really grok the advantage of a view.
For G.edges() wouldn't a view be a consistently updated no memory edgelist? Each time it is accessed we must compute all the edges?  What is a view of graph edges?

**Comment by dschult** [comment]
View vs iterator:   skip the blogs/stackoverflow, etc and go straight to the docs and python introspection.

A view is a low-memory object that provides three methods:
```__iter__```   -- returns the iterator we are comparing views with
```__len__```  -- returns the number of objects in the view
```__contains__```   -- allows testing for membership in the view

dict.keys() is "set-like" and provides ```__and__```, ```__or__```, ```__xor__```, ```__sub__```
But this is not the case for dict.values() or dict.items().

So:  what about G.edges() and G.degree()?
Should they return "views" that provide ```__len__``` and ```__contains__```?

Default input:   G.edges()
```__len__``` would return the number of edges in G
```__contains__``` looks up a 2-tuple edge and/or checks 3-tuple for multigraph.

nbunch input:   G.edges([2,3])
The view object would store both set(nbunch) and G.
```__contains__``` could look up the edge and then check that one node is in nbunch.
```__len__``` could compute the edges and count them...

    count=0
    for e in iter(self):
        count += 1
    return count


I think it is possible... probably a nightmare to get all the in/out_edges, data/key options working conveniently. What do people think? Is it worth that effort to provide ```__len__``` and ```__contains__``` for  the edges() methods?

**Comment by chebee7i** [comment]
We should be careful about making edges() return a "view". I know I have a ton of code right now that *modifies* the data dict from edges(data=True). The entire point is to change the graph. So I'm sure others are doing similar things.

**Comment by chebee7i** [comment]
Err...I guess a view wouldn't change that fact. Continue on...

**Comment by chebee7i** [comment]
I don't see how we can make edges() provide a `__len__` without first iterating through all the edges that are to be returned.

**Comment by dschult** [comment]
I  think ```__len__``` and ```__contains__``` have issues for G.edges()...   

Maybe edges() is not a good example.  The view is of a subgraph induced on all nodes in nbunch and their neighbors...    That's a strange beast.

OK Then, what is a good example...

Even if G.adjacency() returns G.adj.items() so that it is a view, it doesn't seem like a good interface for anything but iterating.  

Come to think of it, how often do you use len() or ```__contains__``` on a dict view?
You can just check the dict itself...   ...ok, maybe ```n in d.values()```
I'm not convinced.  Other views on views?

**Comment by hagberg** [comment]
There are (at least) two  issues here that are getting conflated
1. What should G.adjacency() return?
2. Should we consider returning (Python3) iterable views instead of iterators in some cases (e.g. G.node.items() or iter(G.node.items())

I'm thinking
1. Yes
2. No

**Comment by dschult** [comment]
So, if I understand correctly you are proposing:   [not sure what Yes and No mean :]
1. G.adjacency()  should return G.adj.items()
2. G.nodes(data=True) should return iter(G.node.items()); G.nodes() should return iter(G.node)

**Comment by hagberg** [comment]
I was just being snarky and checking to see if anyone was reading.  Of course you all are.

I don't know if I have a proposal for 1).

But yes that is what I was thinking for 2).  It seems simpler to explicitly return iterators (with a __next__) even though we could get away with iterable data structures such as lists or views.

Maybe we should think of use cases for adjacency() to try to discover what it really would be good for?
Apparently we weren't using it much?
I can see the value of something like G.adj.items() to look at all edges but also G.adj.values() if, say, you wanted to build an adjacency matrix.

**Comment by MridulS** [comment]
@dschult @hagberg Should we go ahead with the iterator version until a final consensus is reached?

**Comment by dschult** [comment]
Yes, let's implement adjacency() to be what adjacency_iter used to be and remove adjacency_list.
Not sure how much this is used in the code so it will be interesting to see.
