### ISSUE TITLE
Removal of degree()

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#1592]
`degree()` returns a dictionary with nodes as keys and degree as values or a number if a single node is specified and `degree_iter()` returns a two-tuples iterator of (node, degree).
What should the new `degree()` function in 2.0 return? 
IMO we should go with the current two-tuples iterator of (node, degree).

**Comment by OrkoHunter** [comment]
If we go with the two-tuples iterator of (node, degree), would it be possible to get the old dictionary with nodes and degrees paired up? How much effort will have to be made to get the dictionary?

**Comment by hagberg** [comment]
`dict(G.degree())`

**Comment by MridulS** [comment]
@hagberg So should I continue with the current two-tuples iterator ?

**Comment by hagberg** [comment]
That seems like a good place to start for further discussion anyway.

**Comment by chebee7i** [comment]
The 2-tuple seems fine.

**Comment by dschult** [comment]
Yes, I think the 2-tuple is a good choice.
This will come up again for functions which return node properties (or even edge properties).
triangles, clustering coefficient, betweenness_centrality, etc...
So we should look at it for degree() because it should probably be done similarly for the others.

**Comment by dschult** [comment]
@MridulS, how are you thinking about handling G.degree(n) vs G.degree()?
Is G.degree(n) going to return a single value while G.degree() returns an iterator?
That seem the closest to the current API, but it is sometimes tricky to check all cases correctly.

**Comment by MridulS** [comment]
@dschult Right now G.degree_iter(n) returns a generator object
``` python
In [1]: import networkx as nx

In [2]: G = nx.path_graph(5)

In [3]: G.degree_iter()
Out[3]: <generator object degree_iter at 0x1125573c0>

In [4]: G.degree_iter(3)
Out[4]: <generator object degree_iter at 0x1125576e0>

In [5]: list(G.degree_iter())
Out[5]: [(0, 1), (1, 2), (2, 2), (3, 2), (4, 1)]

In [6]: list(G.degree_iter(3))
Out[6]: [(3, 2)]
```
I plan to keep the same interface.

**Comment by MridulS** [comment]
@dschult @hagberg @chebee7i Should I go ahead with this?

**Comment by hagberg** [comment]
Yes, go ahead.

**Comment by dschult** [comment]
What do people think about 
```G.degree(3) # where 3 is a node in G```

Should it return a single integer value? (as it currently does)
Or should it return an iterator for which you need to use next to get the integer value?

The first makes it more backward compatible and probably easier for users who want degree of individual nodes.
The second is more consistent with asking for the degree of many nodes, easier to code in the classes.

**Comment by dschult** [comment]
Im worried that the idiom ```d=G.degree(n)``` is popular and common enough to make changing it troublesome.  Also I don't like ```d=next(G.degree(n))``` as a replacement.

So, I would propose that G.degree() return an iterator of (node,degree) 2-tuples when more than one node is in nbunch and that it return a single integer value -- the degree -- when nbunch is a single node.

**Comment by jfinkels** [comment]
@dschult `G.degree(v)` should return a single value, the degree of the node `v`. Anything else would be extremely surprising.

**Comment by hagberg** [comment]
Single value.  Didn't we discuss a good way to do this somewhere else?  Lots of interconnected PRs and issues here.

**Comment by MridulS** [comment]
I think it should be the second one where it returns a iterator. It will be
confusing if `g.degree(3)` returns an integer and`g.degree([3,4])` returns
an iterator. This is more consistent.

**Comment by dschult** [comment]
@MridulS can you combine degree and degree_iter to make it treat single valued input differently? 
That will be more work in the classes, but much less work elsewhere. Also the inconsistency is actually a feature in this case... :)

**Comment by MridulS** [comment]
Sure :)

**Comment by MridulS** [comment]
How about something like this:
``` python
def degree(self, nbunch=None, weight=None):
        if nbunch is None:
            nodes_nbrs = self.adj.items()
        else:
            nodes_nbrs = ((n, self.adj[n]) for n in self.nbunch_iter(nbunch))
        if nbunch in self:
            if weight is None:
                for n, nbrs in nodes_nbrs:
                    yield (len(nbrs) + (n in nbrs))
                    return
            else:
                for n, nbrs in nodes_nbrs:
                    yield (sum((nbrs[nbr].get(weight, 1) for nbr in nbrs)) +
                    (n in nbrs and nbrs[n].get(weight, 1)))
                    return

        if weight is None:
            for n, nbrs in nodes_nbrs:
                yield (n, len(nbrs) + (n in nbrs))  # return tuple (n,degree)
        else:
            # edge weighted graph - degree is sum of nbr edge weights
            for n, nbrs in nodes_nbrs:
                yield (n, sum((nbrs[nbr].get(weight, 1) for nbr in nbrs)) +
                    (n in nbrs and nbrs[n].get(weight, 1)))
```

**Comment by MridulS** [comment]
We still need to do `list(G.degree(2))` to get the integer output. A generator function can't have a return value. One other way could be to have different function then.

**Comment by jfinkels** [comment]
yield (len(nbrs) + (n in nbrs))
                    return

is a silly thing to do.

If you want to consider two separate functions, I would do `G.degree(v)` for a single node, `G.degrees([v1, v2, v3])` for multiple nodes.

**Comment by MridulS** [comment]
@jfinkels yes that return statement is a silly thing. :)
What do you suggest the output of `G.degree([v1, v2])`, `G.degree()`? Should they produce an error or call `G.degrees()` instead?

**Comment by jfinkels** [comment]
`G.degree(v)` would check if `v in G`, and if not, raise an exception,
suggesting to the user the possibility that perhaps they meant to use
`G.degrees()` instead.

**Comment by hagberg** [comment]
I'm not enthusiastic about two functions (degree(), degrees()).

**Comment by dschult** [comment]
For a single argument, return the single value.
For a multiple node argument (including None) then define a generator (function with yield) and return that.
Something like:

    def degree(nbunch):
        if nbunch in self:
            return len(self.adj[nbunch])+(nbunch in self.adj[nbunch])
        def degree_iter(nodes_nbrs):
             #all that stuff
             yield stuff
        nodes_nbrs = 
        return degree_iter(nodes_nbrs)

**Comment by jfinkels** [comment]
While you're making changes here, using the Boolean-valued expression `(v
in self.adj[v])` as a 0 or 1 is a little non-obvious to those who don't
come from a C background and fragile in case `True` and `False` are no
longer interpreted as 0 and 1 in the future. I like something like

    neighbors = self.adj[v]
    return len(neighbors) + 1 if v in neighbors else len(neighbors)

**Comment by jfinkels** [comment]
Or closer to what you have, I guess: `return len(neighbors) + (0 if v in neighbors else 1)`.

**Comment by MridulS** [comment]
``` python
def degree(self, nbunch=None, weight=None):
    if nbunch in self:
            if weight is None:
                return len(self.adj[nbunch])+(nbunch in self.adj[nbunch])
            else:
                return (sum((self.adj[nbunch][nbr].get(weight, 1) for nbr in self.adj[nbunch])) +
                        (nbunch in self.adj[nbunch] and self.adj[nbunch][nbunch].get(weight, 1)))
        def degree_iter(nbunch, weight):
            if nbunch is None:
                nodes_nbrs = self.adj.items()
            else:
                nodes_nbrs = ((n, self.adj[n]) for n in self.nbunch_iter(nbunch))
            if weight is None:
                for n, nbrs in nodes_nbrs:
                    yield (n, len(nbrs) + (n in nbrs))  # return tuple (n,degree)
            else:
                # edge weighted graph - degree is sum of nbr edge weights
                for n, nbrs in nodes_nbrs:
                    yield (n, sum((nbrs[nbr].get(weight, 1) for nbr in nbrs)) +
                        (n in nbrs and nbrs[n].get(weight, 1)))
        return new_deg(nbunch, weight)
```
Does this look fine?

**Comment by MridulS** [comment]
@jfinkels Yes I think you're right. This is a little non-obvious.

**Comment by MridulS** [comment]
@dschult We are defining a function inside a function. If I remember correctly this slows the first(master) function, in this case `degree`. Will this affect the speed of `degree`?

**Comment by dschult** [comment]
I think the indentation is too deep for the function and return statements. They should be the same as the first "if" statement.

As for speed, you can start up ipython and use %timeit <statement> to test the speed interactively. But be careful--you often can't just re-import networkx--might be easier to create a number of versions in the same file and then run them all in a single ipython session. True interactivity would involve writing the function at the command line and the editor isn't very good IMHO.

I suspect you will do better speedwise if you make two different functions depending on whether weight is None. Might be fastest with 4 different functions weight/None and nbunch/None.
But:  optimizing without knowing where the bottenecks are is a tricky business.

The slow-down due to creating a function should not be much if we do it once per call of degree().
Notice that we aren't defining the function is nbunch in a single node.

**Comment by dschult** [comment]
Maybe you can make a commit with just the graph.py module changed. That way we can look at it and if something larger needs to be changed you don't have to revise the entire package.  It will cause travis to go crazy, but that's OK... We can ignore the errors outside that one module for now...  OR if you prefer, just commit it to the branch on your account and dont make it a PR yet. Then we can look at that before you go through changing the whole package.  Whatever works best for you really. :)

**Comment by dschult** [comment]
I did a small time test comparing defining one function which includes the if statements with two functions and also with four functions. I also tested whether its better to use function arguments or just let the value of the variable be used when defining the function. And I compared with the speed of the current functions. There isn't much speed difference between any of these. The only exception is that the current code for getting the degree of a single node is about 4 times slower than any of these. (it creates the iterator and then picks off the only value from that iterator).  So pretty much any version is about the same time.  The following is slightly better than the others in the test I did.

    def degree(self, nbunch=None, weight=None):
        if nbunch in self:
            nbrs=self.adj[nbunch]
            if weight is None:
                return len(nbrs) + (1 if nbunch in nbrs else 0) # handle self-loops
            return sum(dd.get(weight, 1) for nbr,dd in nbrs.items()) +\
                    (nbrs[nbunch].get(weight, 1) if nbunch in nbrs else 0)

        if nbunch is None:
            nodes_nbrs = self.adj.items()
        else:
            nodes_nbrs = ((n, self.adj[n]) for n in self.nbunch_iter(nbunch))
        if weight is None:
            def d_iter():
                for n, nbrs in nodes_nbrs:
                    yield (n, len(nbrs) + (1 if n in nbrs else 0))  # return tuple (n,degree)
        else:
            def d_iter():
                for n, nbrs in nodes_nbrs:
                    yield (n, sum((nbrs[nbr].get(weight, 1) for nbr in nbrs)) +
                        (nbrs[n].get(weight, 1) if n in nbrs else 0))
        return d_iter()

**Comment by MridulS** [comment]
Ok so I did some testing with the new implementation @dschult provided
``` python
In [1]: import networkx as nx

In [2]: G=nx.path_graph(4)

In [7]: %timeit G.degree_new(2)
The slowest run took 10.70 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 1.03 µs per loop

In [15]: %timeit G.degree_iter(2)
The slowest run took 9.78 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 829 ns per loop

In [23]: %timeit G.degree_iter()
The slowest run took 13.43 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 817 ns per loop

In [24]: %timeit G.degree_new()
The slowest run took 11.93 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 2 µs per loop

In [9]: H=nx.Graph()

In [10]: H.add_edge(1,2,weight=1)

In [11]: H.add_edge(3,2,weight=3)

In [16]: %timeit H.degree_iter(2,weight='weight')
The slowest run took 9.42 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 835 ns per loop

In [17]: %timeit H.degree_new(2,weight='weight')
The slowest run took 7.82 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 2.29 µs per loop

In [21]: %timeit H.degree_new(weight='weight')
The slowest run took 8.59 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 1.86 µs per loop

In [22]: %timeit H.degree_iter(weight='weight')
The slowest run took 16.00 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 819 ns per loop



```
`degree_new` is the proposed implementation and `degree_iter` is the original one.

**Comment by MridulS** [comment]
It looks like the proposed `degree_new` is slower than `degree_iter`.

**Comment by MridulS** [comment]
https://github.com/networkx/networkx/commit/ee170a4bfe6b3a4fad5d16f7faa2fffb81fc34d2 new degree implementation in graph.py

**Comment by dschult** [comment]
Try it with a bigger graph:    G=binomial_graph(1000,0.3)  or something similar.  
I don't trust results that include a warning about cached results.

**Comment by MridulS** [comment]
OK so after some not so "beautiful" optimisation
``` python
    def degree_new(self, nbunch=None, weight=None):
        if nbunch in self:
            nbrs=self.adj[nbunch]
            if weight is None:
                return len(nbrs) + (1 if nbunch in nbrs else 0) # handle self-loops
            return sum(dd.get(weight, 1) for nbr,dd in nbrs.items()) +\
                    (nbrs[nbunch].get(weight, 1) if nbunch in nbrs else 0)

        if nbunch is None:
            nodes_nbrs = self.adj.items()
        else:
            nodes_nbrs = ((n, self.adj[n]) for n in self.nbunch_iter(nbunch))
        if weight is None:
            def d_iter():
                for n, nbrs in nodes_nbrs:
                    yield (n, len(nbrs) + (1 if n in nbrs else 0))  # return tuple (n,degree)
        else:
            def d_iter():
                for n, nbrs in nodes_nbrs:
                    yield (n, sum((nbrs[nbr].get(weight, 1) for nbr in nbrs)) +
                        (nbrs[n].get(weight, 1) if n in nbrs else 0))
        return d_iter()

    def degree_v2(self, nbunch=None, weight=None):
        if nbunch in self:
            nbrs = self.adj[nbunch]
            if weight is None:
                return len(nbrs) + (1 if nbunch in nbrs else 0) # handle self-loops
            return sum(dd.get(weight, 1) for nbr,dd in nbrs.items()) +\
                    (nbrs[nbunch].get(weight, 1) if nbunch in nbrs else 0)

        if nbunch is None and weight is None:
            def d_iter():
                for n, nbrs in self.adj.items():
                    yield (n, len(nbrs) + (1 if n in nbrs else 0))  # return tuple (n,degree)
        elif nbunch is None:
            def d_iter():
                for n, nbrs in self.adj.items():
                    yield (n, sum((nbrs[nbr].get(weight, 1) for nbr in nbrs)) +
                        (n in nbrs and nbrs[n].get(weight, 1)))
        elif nbunch is not None and weight is None:
            def d_iter():
                for n, nbrs in ((n, self.adj[n]) for n in self.nbunch_iter(nbunch)):
                    yield (n, len(nbrs) + (1 if n in nbrs else 0))  # return tuple (n,degree)
        else:
            def d_iter():
                for n, nbrs in ((n, self.adj[n]) for n in self.nbunch_iter(nbunch)):
                    yield (n, sum((nbrs[nbr].get(weight, 1) for nbr in nbrs)) +
                        (n in nbrs and nbrs[n].get(weight, 1)))
        return d_iter()
```
`degree_new` is the implementation suggested by @dschult and `degree_v2` is some optimization.

Result
``` python
In [21]: G=nx.binomial_graph(1000,0.3)

In [22]: %timeit G.degree_iter()
The slowest run took 9.79 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 828 ns per loop

In [23]: %timeit G.degree_new()
10000 loops, best of 3: 41.1 µs per loop

In [24]: %timeit G.degree_v2()
The slowest run took 14.30 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 1.55 µs per loop
```

**Comment by MridulS** [comment]
There is big difference between `G.degree_new()` and `G.degree_iter()` It is 50 times slower.

**Comment by hagberg** [comment]
Let's not get too hung up in timing creation of iterators.  That doesn't seem so interesting right?
How about using list(G.degree_*) to produce the data?  That is the use case.

**Comment by MridulS** [comment]
In that case
```python
In [15]: %timeit list(G.degree_iter())
The slowest run took 4.92 times longer than the fastest. This could mean that an intermediate result is being cached 
1000 loops, best of 3: 375 µs per loop

In [16]: %timeit list(G.degree_new())
1000 loops, best of 3: 373 µs per loop

In [17]: %timeit list(G.degree_v2())
The slowest run took 4.23 times longer than the fastest. This could mean that an intermediate result is being cached 
1000 loops, best of 3: 353 µs per loop

In [18]: %timeit (G.degree_v2(2))
The slowest run took 13.01 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 1.08 µs per loop

In [19]: %timeit (G.degree_new(2))
The slowest run took 13.29 times longer than the fastest. This could mean that an intermediate result is being cached 
1000000 loops, best of 3: 1.06 µs per loop

In [20]: %timeit list(G.degree_iter(2))
The slowest run took 7.84 times longer than the fastest. This could mean that an intermediate result is being cached 
100000 loops, best of 3: 3.44 µs per loop
```

**Comment by chebee7i** [comment]
Also, testing `nbunch in self` is not going to work since nbunch (without preprocessing) might be a list.

**Comment by hagberg** [comment]
Wait, `nbunch in self` is OK right?
It'll check to see if a specified list or iterator is a node which should never work since nodes must be hashable.

We could get in trouble with nbunch=None though since we discourage but allow None as a node.

**Comment by chebee7i** [comment]
I think it's only an issue when `nbunch` is actually a bunch of nodes:  `nbunch=['A', 'B']`

**Comment by hagberg** [comment]
It's OK no?

```python
In [17]: G = nx.path_graph(4)

In [18]: G.nodes()
Out[18]: [0, 1, 2, 3]

In [19]: [1,2] in G
Out[19]: False
```

**Comment by MridulS** [comment]
I think `nbunch in self` should be OK. Regarding `nbunch = None` this has been discussed in https://github.com/networkx/networkx/issues/1381

@chebee7i 
```
In [2]: g=nx.Graph()

In [3]: g.add_edge('a','b')

In [6]: nbunch = ['a','b']

In [8]: nbunch in g
Out[8]: False

In [9]: 'a' in g
Out[9]: True

**Comment by hagberg** [comment]
Yes I remember #1381.  I was advocating documentation (don't do that!) instead of checks.
Which I still like.  
I was worried there that we'd need to put checks in many places to be consistent.

**Comment by dschult** [comment]
The ```nbunch in self``` and not discouraging ```None``` are the same as in the current degree().
(Sometimes hidden in nbunch_iter().) 

@MridulS, You time tests match my results so that degree_new and degree_v2 are essentially the same. You should pick between them based on which is easier to read.

I'm glad removing degree_iter() speeds up single node lookups. :)

**Comment by MridulS** [comment]
@dschult `degree_new` is definitely easier to comprehend than `degree_v2`. So I think we should go with `degree_new`

**Comment by chebee7i** [comment]
Ahh, it is OK because we do a try/except in `__contains__`. Otherwise, it would not be ok:

```
>>> d = {}
>>> [1,2] in d
TypeError
```

**Comment by chebee7i** [comment]
Aside, I think it is a bit unintuitive why we do a try/except in `__contains__`. Using unhashables with the `in` operator in Python *should* return a `TypeError`, not `False`, in my opinion.  That would keep NetworkX consistent with the rest of Python.

**Comment by dschult** [comment]
consistency is the bane of ......     oh never mind....

I don't think Python is consistent on this. 
I can make a list-like class (a mutable object) with no hash method and still use it as a key in a dict. 
It's only the built-in unhashables that create a TypeError.

I think Pieter first argued that __contains__ should just return False instead of raising an error.
But I don't think he got much resistance.  It's such a common use case that writing try/except all the time gets tedious, and since python isn't consistent anyway... 

Anyway, this way is at least self-consistent and natural:  
return True if n is in the graph else False.
No need for a "third truth value" which really means "is not and could not be in the graph".

Besides... it lets us test whether something is a node by simply using 
```if n in self```         :)

**Comment by chebee7i** [comment]
Yeah it is probably too late to change now, but I think it warrants a comment in `degree` or other similar functions. 

When we test, `nbunch in self`, it looks as if we are testing to see if there is a node that is equal to a list in the graph, but that is not really what we are *after* when we do that query. Rather, we are trying to determine if `nbunch` is a node that is in the graph of `nbunch` is an iterable of nodes.  If the latter, there is no expectation that the iterable of nodes is also a node in the graph. So while I think this works just fine, I think the code looks is out-of-sync from what we are trying to achieve at a high level, and so, a could make the code easier to read.

**Comment by chebee7i** [comment]
Buuuut...it's also just a NetworkX idiom that people can get used to seeing (as I have).

**Comment by MridulS** [comment]
I am with @chebee7i here. Initially `nbunch in self` wasn't that intuitive. I had to try it out before figuring out the exact meaning of the statement. A comment regarding this can't hurt.

**Comment by dschult** [comment]
Yes, I agree a comment would be helpful.
The problem is that nodes CAN be iterables. So we have to figure out if nbunch is a node or an iterable of nodes.
We assume that if nbunch is a node, we do not interpret it as an iterable of nodes.

It is possible to cause trouble with this:  

    G=nx.Graph()
    G.add_edge( (1,2), 1)
    G.add_edge(1,2)
    G.degree( (1,2) )  # returns the degree of the node (1,2)
    # we can get the degree of both nodes 1 and 2 without something fancy (though G.degree( (2,1) ) would work in this case)

How about this for a comment:

    # Test to see if nbunch is a single node, an iterator of nodes or None(indicating all nodes)
    # (nbunch in self) is True when nbunch is a single node.

**Comment by MridulS** [comment]
I guess this can be closed now. :)
