### ISSUE TITLE
Disallow robots on networkx.lanl.gov

### ISSUE THREAD

**Issue by chebee7i** [networkx/networkx#1598]
Occasionally, Google still returns results pointing directly to lanl.gov pages, even though we are now redirecting the root page directly to the github doc site. Perhaps we should add:

```
User-agent: *
Disallow: /
```

to `/robots.txt`. The trac site is still live and helpful for historical queries. Trac does have it's own search, so perhaps we don't need it indexed? If we do, I think the following works:

```
User-agent: *
Allow: /trac
Disallow: /
```

**Comment by hagberg** [comment]
I will try to get those implemented ASAP.

**Comment by hagberg** [comment]
Done.
