### ISSUE TITLE
Add efficient algorithms for graph isomorphism of restricted classes of graphs

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#1602]
Graph isomorphism can be decided in polynomial time for certain classes of graphs, such as trees and planar graphs (for more classes, see the Wikipedia article on the [graph isomorphism problem](https://en.wikipedia.org/wiki/Graph_isomorphism_problem#Solved_special_cases)). It would be interesting to see which of these can be implemented under the `networkx.algorithms.isomorphism` package.

The interface I'm envisioning is that the user will decide beforehand whether the graph belongs to a given class or not (for example, `if nx.is_planar(G) and nx.is_planar(H): ...`, though it appears there is currently no function that tests for planarity...that's a different issue), then call the appropriate isomorphism testing function (for example `nx.isomorphism.planar.is_isomorphic(G, H)`, a function that has planarity of its two input graphs as a pre-condition).

**Comment by chebee7i** [comment]
This is a good idea. I already have code that can do this in linear(?) time for DFAs, but these require labeled edges and determinism. It just seemed to special case to include in NetworkX. Some of the ones you describe seem like better candidates.

**Comment by kosii** [comment]
A long-long time ago I implemented an algorithm to check unrooted tree isomorphism, but I never created a pull request for e37cb912509bcb59e2b6a19833fbbfbb465550f8. If this algo has a place in networkx, I'd be glad to clean it up or even rewrite it (hey, 4 years is a long time, haha).

**Comment by kosii** [comment]
now I'm not even sure whether I pushed every commit back then, but the idea was to implement these two algorithms http://crypto.cs.mcgill.ca/~crepeau/CS250/2004/HW5+.pdf

**Comment by kosii** [comment]
[a](e37cb912509bcb59e2b6a19833fbbfbb465550f8)

**Comment by hagberg** [comment]
I'd like to see those algorithms get implemented.  It would be a good start to @jfinkels program to make efficient isomorphism checkers

**Comment by jfinkels** [comment]
There's a simple functional algorithm for rooted tree isomorphism: convert the trees into canonical forms and compare them, where the canonical form is the (sorted) balanced parenthesization. Something like this:

    def canonical_form(G, root):
        if len(G) == 0:
            return ()
        return tuple(sorted(canonical_form(G, v) for v in children(G, root)))

    def is_isomorphic(T1, T2, root1, root2):
        return canonical_form(T1, root1) == canonical_form(T2, root2)

Should be much simpler to deal with, at least as an initial implementation.

**Comment by kosii** [comment]
The unrooted isomorphism checker does the same thing by finding the center of both trees, and checking if they are isomorphes when rooted to the centers. If there are two centers, then we must do two checks.

**Comment by kosii** [comment]
Something like
````Python
from networkx.algorithms.distance_measures import center

def is_isomorphic(T1, T2):
    for center1 in center(T1):
        for center2 in center(T1)[:1]:
            if is_isomorphic(T1, T2, center1, center2): 
                return True
    return False
````

**Comment by hagberg** [comment]
See #1811
