### ISSUE TITLE
Add test for planarity

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#1603]
A _[planar graph](https://en.wikipedia.org/wiki/Planar_graph)_ is a graph that can be embedded in the Euclidean plane with no edge crossings. Wikipedia knows about a few algorithms for [planarity testing](https://en.wikipedia.org/wiki/Planarity_testing).

**Comment by hagberg** [comment]
If I remember right the good algorithms are tricky.  Here is a Python interface to John Boyer's planarity package: https://github.com/hagberg/planarity/

**Comment by jfinkels** [comment]
Boost has a planarity test: http://www.boost.org/doc/libs/1_59_0/libs/graph/doc/planar_graphs.html

**Comment by hagberg** [comment]
Looks like the boost planarity tester is calling the Boyer-Myrvold code like ttps://github.com/hagberg/planarity/ does.

**Comment by hagberg** [comment]
Functionality available in https://github.com/hagberg/planarity/
