### ISSUE TITLE
Sparsification of Graphs

### ISSUE THREAD

**Issue by chebee7i** [networkx/networkx#1609]
It might be nice to get some functions in NetworkX for sparsifying graphs. cut sparsification and spectral sparsification are two options. For example,

http://arxiv.org/abs/0808.4134

Spectral Sparsification of Graphs
Daniel A. Spielman, Shang-Hua Teng

We introduce a new notion of graph sparsificaiton based on spectral similarity of graph Laplacians: spectral sparsification requires that the Laplacian quadratic form of the sparsifier approximate that of the original. This is equivalent to saying that the Laplacian of the sparsifier is a good preconditioner for the Laplacian of the original. We prove that every graph has a spectral sparsifier of nearly linear size. Moreover, we present an algorithm that produces spectral sparsifiers in time $\softO{m}$, where m is the number of edges in the original graph. This construction is a key component of a nearly-linear time algorithm for solving linear equations in diagonally-dominant matrcies. Our sparsification algorithm makes use of a nearly-linear time algorithm for graph partitioning that satisfies a strong guarantee: if the partition it outputs is very unbalanced, then the larger part is contained in a subgraph of high conductance.

**Comment by dschult** [comment]
This would be very cool. I've read enough to know I'd like to see it in NetworkX. But I haven't tried implementing anything. Some of the proposed low-stretch tree algorithms would be needed as they build on those.

**Comment by harrymvr** [comment]
This reference might also prove more useful
http://arxiv.org/pdf/1402.3851v2.pdf

Most of these algorithms return graphs that are sparsifiers at least with some probability.

**Comment by hagberg** [comment]
Spielman said (in a lecture) that his group intends to release some code in the next 6 months or so.  If anyone on that team wants help integrating with NetworkX or with a Python wrapper we can help.

**Comment by JaKasb** [comment]
Code by Spielman:
https://github.com/danspielman/Laplacians.jl

**Comment by gmyr** [comment]
There is a (relatively) simple algorithm due to Fung, Hariharan, and Harvey (see Theorem 1.3 in [1]) for computing cut sparsifiers in undirected graphs. While this only provides cut sparsifiers and not spectral sparsifiers, it would be a first step towards supporting sparsifiers at all. If this is of any relevance to the project, I would be interested in taking a shot at implementing the algorithm.

[1] https://users.cs.duke.edu/~debmalya/papers/stoc11-sparsification.pdf

**Comment by dschult** [comment]
>As an example, the more advanced algorithm immediately returns the original graph if m <= 2028 / (0.38 * epsion^2) * n ln(n). 

Hmmm...  a quick calculation says a 1% error needs 1billion nodes to even make reaching that cutoff possible. Maybe that's not such a good algorithm to implement.  Have you looked at the other links:
Koutis (cited by @harrymvr above) or the Spielman code/papers (cited above by @chebee7i )

**Comment by gmyr** [comment]
I looked a bit at the paper of Koutis and Xu. Their algorithm seems to exhibit a similar problem: Assuming I use Baswana-Sen-spanners for the spanner construction required for the algorithm, we get m > 96 * n * log^3(n) / epsilon^2 as a cutoff before the algorithm removes any edges. So for a 1% error, we need at least tens of millions of nodes.

At this point, I think I will leave this issue unresolved. Maybe someone else is interested in working on it. One useful thing that came out of my efforts is an implementation of Baswana and Sen's algorithm for spanner construction (see [1]) that seems to work well. If this is interesting for the project, I'd be happy to clean up the code and submit a pull request.

[1] http://www.cse.iitd.ernet.in/~ssen/journals/randstruc.pdf

**Comment by dschult** [comment]
Yes, The implementation the spanner construction would be of interest. Thanks very much for diving into this!!
