### ISSUE TITLE
Document dag_longest_path

### ISSUE THREAD

**Issue by sjackman** [networkx/networkx#1611]
The algorithms [`dag_longest_path`](https://github.com/networkx/networkx/blob/master/networkx/algorithms/dag.py#L395) and `dag_longest_path_length` are not documented.

http://networkx.github.io/documentation/development/reference/algorithms.html

Thanks!

**Comment by MridulS** [comment]
This is weird. It is documented and it shows on http://networkx.readthedocs.org/en/latest/reference/algorithms.html

**Comment by sjackman** [comment]
Interesting. These algorithms are missing from "Directed Acyclic Graphs". `http://networkx.github.io/documentation/development` appears to be stale.
```
transitive_closure
antichains
dag_longest_path
dag_longest_path_length
```

**Comment by MridulS** [comment]
This should be closed https://github.com/networkx/networkx/issues/1626

**Comment by sjackman** [comment]
Thanks!
