### ISSUE TITLE
Python 2 and Python 3 reading pickles

### ISSUE THREAD

**Issue by ericmjl** [networkx/networkx#1616]
In a Python 2 environment, I have a pickled network saved using `nx.write_gpickle()`.

If I want to open the same file in a Python 3.4 environment, I get a `UnicodeError`: `UnicodeDecodeError: 'ascii' codec can't decode byte 0xd0 in position 0: ordinal not in range(128)`.

How might I be able to specify encoding when opening a Py2 pickle?

**Comment by SanketDG** [comment]
Try this after pickling in `python3`:

```python
import pickle
pickle.load(open(filename, "rb"), encoding='bytes')
```
where `filename` is the name of your saved pickle file.

**Comment by OrkoHunter** [comment]
@ericmjl Any updates?

**Comment by ericmjl** [comment]
My apologies, I've not got a chance to try this out yet, but it's on my list! (There's a number of other projects I'm working on that don't require pickling.) Thanks for replying, I'll let you guys know how it works.

**Comment by dschult** [comment]
Let's go ahead and close this. If it doesn't work feel free to reopen this issue.
