### ISSUE TITLE
write_gml doesn't wait until file is properly written to disk in all cases

### ISSUE THREAD

**Issue by rajanski** [networkx/networkx#1620]
I have a setup where I write a graph to a gml file and immediately afterwards read it with another tool which is not of importance for this issue.

it happens in about 5% of the cases that the gml file is not completely written to disk before the next command (the reading process) is called.

I can see the decorator @open_file(1, mode='wb') [here](https://github.com/networkx/networkx/blob/57e96144d58cb8d47fc0780aa798e110944798e6/networkx/readwrite/gml.py#L672) but dont have time to look furrtherly into the decorator [code](https://github.com/networkx/networkx/blob/57e96144d58cb8d47fc0780aa798e110944798e6/networkx/utils/decorators.py#L156)

Is there sth that can be done in the decorator to avoid this behaviour?

**Comment by dschult** [comment]
Do you specify the file name as a string (the name of the file), or do you open the file yourself and pass the file object into write_gml?

If you are using a string to specify the name of the file then the decorator should close the file object before returning and your symptoms indicate a bug in the decorator.

If you specify a file object/handler, (or anything not string-like) then the file object is not closed during this call and you will have to close it manually after the call to write_gml. The idea is that if you opened the file yourself then you might want to write more after the function call, so we put you in charge of closing the file.

**Comment by rajanski** [comment]
HI, I am using a string like write_gml('/path/to/file/file.gml')

**Comment by chebee7i** [comment]
Can you explain a bit more how you are receiving the error then? When `write_gml` is finished, the file should be closed---assuming everything is implemented correctly.

**Comment by chebee7i** [comment]
Essentially, the decorator does:

```python
        try:
            result = func(*new_args, **kwargs)
        finally:
            if close_fobj:
                fobj.close()
```

If you pass a string in, then `close_fobj` is `True` and so it definitely closes the file. I don't see how what we are doing could cause a failure every so often.

**Comment by hagberg** [comment]
Closing due to no update.
