### ISSUE TITLE
Documentation not generated for some modules

### ISSUE THREAD

**Issue by jtorrents** [networkx/networkx#1626]
It seems that in the online documentation there are some modules for which documentation is not generated. See for instance:

http://networkx.github.io/documentation/development/reference/algorithms.connectivity.html
http://networkx.github.io/documentation/development/reference/algorithms.approximation.html

I added these modules recently, so far I didn't find the same problem in any other module. I cannot reproduce it locally, in my machine the html builds fine. Any idea on where the problem might be?

This is relevant for #1590

**Comment by hagberg** [comment]
Something is probably not working correctly on the machine I am using to build that documentation.
I'll take a look.

**Comment by chebee7i** [comment]
@jtorrents, as a developer you might consider setting up your own readthedocs build for NetworkX.

https://github.com/networkx/networkx/wiki/readthedocs

This will allow you to test out commits on your own networkx fork and see how they build on readthedocs.

**Comment by chebee7i** [comment]
Also, they seem to be generated on the readthedocs latest:

http://networkx.readthedocs.org/en/latest/reference/algorithms.approximation.html
http://networkx.readthedocs.org/en/latest/reference/algorithms.connectivity.html

**Comment by jtorrents** [comment]
@hagberg thanks for looking at this!

@chebee7i Thanks for the pointer, that's quite nice! I'll set up a readthedocs build for my fork.

**Comment by hagberg** [comment]
There are a bunch of errors in the build.  No time to trouble shoot right now.
This is a good reason to host the complete documentation at readthedocs.
Is there anything keeping us from doing that?

**Comment by chebee7i** [comment]
I think we can move over. Will you be able to keep the existing, older versions of NetworkX documentation available? I think we can only do 1.10 forward on readthedocs since it builds documentation from a particular commit.

The documentation.rst file has already been updated:

https://github.com/networkx/networkx-website/blob/master/documentation.rst

All future versions will point to ReadTheDocs. Since 1.10 hasn't yet been released, that link is current broken.  The links to older versions of the docs need to stay active. That should be possible correct? And we will never need to rebuild them.

**Comment by jtorrents** [comment]
@chebee7i that's great! Handling a custom document build pipeline is a waste of developer time (our scarcest resource).

**Comment by hagberg** [comment]
Some of those old versions are at networkx.github.io.
And the rest are at http://networkx.lanl.gov/archive/ (those are probably only if historical interest now).
I should be able to keep that working as long as the networkx.lanl.gov machine is running.

**Comment by chebee7i** [comment]
The versions (like 1.9) that are on networkx.github.io should be fine and unaffected by us moving future documentation builds to readthedocs. So as soon as we release 1.10, we should re-push networkx-website to networkx.github.io.

**Comment by hagberg** [comment]
I'm not going to take the time to debug the failing automatic builds I am doing since readthedocs is working well.
