### ISSUE TITLE
Hosting a separate repository 'networkx-lemon'

### ISSUE THREAD

**Issue by OrkoHunter** [networkx/networkx#1629]
We are in the 5th week of the GSoC period and according to my [proposed timeline](https://github.com/networkx/networkx/wiki/GSoC-2015-Application-Himanshu-Mishra-:-Add-On-System-for-Networkx#timelinetentative) the work on [networkx-metis](https://github.com/networkx/networkx-metis/) should nearly be complete and the work on networkx-lemon should start now. 

So, @dschult @hagberg @jtorrents, may one of you please create `networkx-lemon` so as I can start working on it. 

Well, there are few things left to do with networkx-metis, including some documentation. I hope that will be covered by this week.

**Comment by OrkoHunter** [comment]
The [licence terms](http://lemon.cs.elte.hu/trac/lemon/wiki/License) of [lemon](http://lemon.cs.elte.hu/trac/lemon) is very permissive this time. So, we don't need to think about that.

**Comment by jtorrents** [comment]
@OrkoHunter I just created the repository. Let me know if something needs adjusting.

**Comment by OrkoHunter** [comment]
Thank you. You've also added the dev team so, everything's good.

**Comment by ysitu** [comment]
@OrkoHunter Before you work on the code, please write up a design in the wiki and start an issue for review of the design.

**Comment by OrkoHunter** [comment]
@ysitu Yeah sure. The design part will be pretty much important in case of lemon. I'll start with that.

**Comment by OrkoHunter** [comment]
I've opened an issue about the design of the package here https://github.com/networkx/networkx-lemon/issues/1. New ideas or suggestions about this are most welcome.
