### ISSUE TITLE
Design of G.query()

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#1631]
This was a initial design proposed by @ysitu regarding a G.query() function. https://github.com/networkx/networkx/issues/1246#issuecomment-53139093

> G.query is just a placeholder name. G.**call** may well be a better option. I have the following sketch design in mind (assuming that it is implemented as G.**call**):
> - None and a set-like type ANY are reserved for internal use, so None, ANY and instances of ANY cannot be used as nodes or edge/data keys.
> - G(u, v, key, data) is a generator of (u, v, key, data, value) tuples, although some components of the tuples may be suppressed per the rules below. If data is suppressed, value is also suppressed.
> - Each of the parameters of G(u, v, key, data) can be None, some concrete value, ANY or ANY([value1, value2, ...]). The parameters are interpreted as query filters.
> - None and ANY are both universal wildcards, but None also causes the corresponding component in the output tuple to be suppressed.
> - value is equivalent to ANY([value]). ANY([value1, value2, ...]) discards a tuple if the corresponding component is not in [value1, value2, ...].
> - None of G(u, v=None, key=None, data=None), G(u, v, key=None, data=None) or G(u, v, key, data=None) returns duplicate tuples.
> - For undirected graphs, each edge is not handled as a pair of reciprocal edges.
> - Backends may provide additional constraints.

Looking for inputs regarding this.
@dschult @hagberg @jtorrents @jfinkels @chebee7i @ysitu

**Comment by hagberg** [comment]
I'm not sure this is a such a good idea.  Maybe I haven't through through all of the implications but it feels like we are suggesting a more database-like approach to an API and not one that is, say, familiar to a graph theorist or network scientist.  At some point it just comes down to how we want the user to be able to interact with the data structure.

**Comment by chebee7i** [comment]
@hagberg If it were not a method, but a function instead, does that change anything?

**Comment by ysitu** [comment]
To provide some background, at the time we were discussing having alternative back ends than dicts. What I had in mind was indeed relational databases, where dict-style access is awkward. So this `G.query()` idea came up.

**Comment by hagberg** [comment]
I remember that discussion.

I think my biggest concern is keeping the interface simple and focussed on on graph theory/network science.  

So it doesn't really matter if it is a method or a function if in the end we write algorithms using that interface and it becomes "less graph-like" and more "database-like".

**Comment by dschult** [comment]
So, what applications/algorithms are we thinking of for the G.query() interface?
If we can come up with a good network science problem that this would help with 
it will help us design the interface.  If we can't, maybe we should hold off.
