### ISSUE TITLE
Use dict comprehensions

### ISSUE THREAD

**Issue by NeilGirdhar** [networkx/networkx#1640]
Now that networkx has dropped Python 2.6, it should be safe and faster to use dict comprehensions instead of applying the dict constructor to generators.

networkx/algorithms/approximation/kcomponents.py:        return dict((node, all_edge_dict) for node in
networkx/algorithms/approximation/tests/test_kcomponents.py:    labels = dict((v, k) for k, v in rlabels.items())
networkx/algorithms/approximation/tests/test_kcomponents.py:    labels = dict((v, k) for k, v in rlabels.items())
networkx/algorithms/connectivity/tests/test_kcutsets.py:    labels = dict((v, k) for k, v in rlabels.items())
networkx/algorithms/connectivity/tests/test_kcutsets.py:    labels = dict((v, k) for k, v in rlabels.items())
networkx/algorithms/core.py:    node_pos = dict((v,pos) for pos,v in enumerate(nodes))
networkx/algorithms/flow/tests/test_maxflow.py:    excess = dict((u, 0) for u in flowDict)
networkx/algorithms/flow/tests/test_maxflow_large_graph.py:    excess = dict((u, 0) for u in flow_dict)
networkx/algorithms/flow/utils.py:        flow_dict[u] = dict((v, 0) for v in G[u])
networkx/algorithms/shortest_paths/weighted.py:    d = dict((u, inf) for u in G)
networkx/algorithms/traversal/breadth_first_search.py:    return dict((t,s) for s,t in bfs_edges(G,source))
networkx/algorithms/traversal/depth_first_search.py:    return dict((t,s) for s,t in dfs_edges(G,source=source))
networkx/drawing/nx_pylab.py:        labels = dict((n, n) for n in G.nodes())
networkx/readwrite/graphml.py:        data=dict((k,v) for (k,v) in  G.graph.items()
networkx/relabel.py:                               dict((v,k) for k,v in mapping.items()))

**Comment by hagberg** [comment]
I don't see why that would obviously be faster (at least with Python3) in cases where we aren't generating a list of items to pass to dict().  It's less characters to type.

**Comment by MisterSheik** [comment]
It's definitely faster in CPython because one looks up the constructor and calls it on a generator of tuples each of which has to be assembled and unpacked.  The dict comprehension uses direct MAP_ADD instructions.

In any case, dict comprehensions are simpler, and simple is better than complex :)  They are fewer characters to type, not more.

Below are the disassemblies so that might help give some insight into why they are faster.

    In [7]: import dis

    In [8]: def f():
       ...:     return dict((a, b) for a, b in l)
       ...:

    In [9]: dis.dis(f)
      2           0 LOAD_GLOBAL              0 (dict)
                  3 LOAD_CONST               1 (<code object <genexpr> at 0x102287db0, file "<ipython-input-8-5ca574b9195e>", line 2>)
                  6 LOAD_CONST               2 ('f.<locals>.<genexpr>')
                  9 MAKE_FUNCTION            0
                 12 LOAD_GLOBAL              1 (l)
                 15 GET_ITER
                 16 CALL_FUNCTION            1 (1 positional, 0 keyword pair)
                 19 CALL_FUNCTION            1 (1 positional, 0 keyword pair)
                 22 RETURN_VALUE

    In [10]: dis.dis(f.__code__.co_consts[1])
      2           0 LOAD_FAST                0 (.0)
            >>    3 FOR_ITER                23 (to 29)
                  6 UNPACK_SEQUENCE          2
                  9 STORE_FAST               1 (a)
                 12 STORE_FAST               2 (b)
                 15 LOAD_FAST                1 (a)
                 18 LOAD_FAST                2 (b)
                 21 BUILD_TUPLE              2
                 24 YIELD_VALUE
                 25 POP_TOP
                 26 JUMP_ABSOLUTE            3
            >>   29 LOAD_CONST               0 (None)
                 32 RETURN_VALUE

    In [11]: def g():
       ....:     return {a: b for a, b in l}
       ....:

    In [12]: dis.dis(g)
      2           0 LOAD_CONST               1 (<code object <dictcomp> at 0x10308c0c0, file "<ipython-input-11-9740c75b978b>", line 2>)
                  3 LOAD_CONST               2 ('g.<locals>.<dictcomp>')
                  6 MAKE_FUNCTION            0
                  9 LOAD_GLOBAL              0 (l)
                 12 GET_ITER
                 13 CALL_FUNCTION            1 (1 positional, 0 keyword pair)
                 16 RETURN_VALUE

    In [13]: dis.dis(g.__code__.co_consts[1])
      2           0 BUILD_MAP                0
                  3 LOAD_FAST                0 (.0)
            >>    6 FOR_ITER                21 (to 30)
                  9 UNPACK_SEQUENCE          2
                 12 STORE_FAST               1 (a)
                 15 STORE_FAST               2 (b)
                 18 LOAD_FAST                2 (b)
                 21 LOAD_FAST                1 (a)
                 24 MAP_ADD                  2
                 27 JUMP_ABSOLUTE            6
            >>   30 RETURN_VALUE

**Comment by hagberg** [comment]
Wow, nice.  That is better.  Thanks for posting that.

**Comment by jfinkels** [comment]
I wholeheartedly support this. I made an argument based on readability, not speed, on some commit a few weeks ago.

**Comment by Michael-E-Rose** [comment]
May I ask, what's the status on this one? The first PR looks quite clean but the longer one waits, the more merge conflicts there will be.

**Comment by hagberg** [comment]
Bumped the PR #1700 which needs conflict merge.
