### ISSUE TITLE
Update reference link for [R174]

### ISSUE THREAD

**Issue by joelmiller** [networkx/networkx#1641]
The link given in the closeness_centrality documentation for 

> [R174]	(1, 2) Freeman, L.C., 1979. Centrality in networks: I. Conceptual clarification. Social Networks > 1, 215–239. http://www.soc.ucsb.edu/faculty/friedkin/Syllabi/Soc146/Freeman78.PDF

is broken.  I can find the paper at http://leonidzhukov.net/hse/2014/socialnetworks/papers/freeman79-centrality.pdf, or with a paywall at http://www.sciencedirect.com/science/article/pii/0378873378900217

**Comment by MridulS** [comment]
Fixed in #1319

**Comment by MridulS** [comment]
The current documentation is broken at places. This is the link for latest documentation http://networkx.readthedocs.org/en/latest/

**Comment by MridulS** [comment]
Oh wait.... It is broken at readthedocs too :/
https://networkx.readthedocs.org/en/latest/reference/algorithms.centrality.html

**Comment by chebee7i** [comment]
Should this be closed?

**Comment by MridulS** [comment]
@chebee7i Yes it is fixed.

**Comment by MridulS** [comment]
@chebee7i I opened a new issue regarding the failure #1642

**Comment by dschult** [comment]
It might be best to use the doi:10.1016/0378-8733(78)90021-7
<http://dx.doi.org/10.1016/0378-8733(78)90021-7>  (which ends up pointing
to the sciencedirect page).
That is likely to be longer lasting, and from information there people can
search for a free pdf version if they want to.
