### ISSUE TITLE
Algorithms.centrality not rendered in documentation

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#1642]
https://networkx.readthedocs.org/en/latest/reference/algorithms.centrality.html

The page is not rendered.

**Comment by AgostinoSturaro** [comment]
[The link](http://networkx.readthedocs.org/en/networkx-1.10/) to the 1.10 documentation found [here](https://networkx.github.io/documentation.html) is broken.

**Comment by SanketDG** [comment]
Looks like [this](http://networkx.readthedocs.org/en/stable/) should be the link.

**Comment by chebee7i** [comment]
The link was correct, we just needed to update readthedocs after releasing 1.10.
