### ISSUE TITLE
meeting at scipy conference this week

### ISSUE THREAD

**Issue by jtorrents** [networkx/networkx#1644]
This week is the Scipy conference at Austin. Maybe we can plan for an informal meeting of developers and users at some point. Perhaps people that was not able to attend the conference can join remotely. Who is at the conference? I just landed there yesterday late night. We can use this issue to coordinate things, even if it's only to grab some drinks and chat.

**Comment by hagberg** [comment]
I'm around some of the week.  If you can't find me try aric.hagberg@gmail.com.
