### ISSUE TITLE
Setting up appveyor

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#1650]
Travis is capable of running tests for Linux, but we also support Windows. So should we use something like https://ci.appveyor.com for testing the package over windows.
@OrkoHunter did this for `networkx-metis`

**Comment by MridulS** [comment]
We can also use container-based infrastructure in travis for faster builds. But that would need a bit of messing around with current travis.yml to make it work.
@ysitu @hagberg @dschult @jtorrents

**Comment by OrkoHunter** [comment]
Well yeah. Apart from adding `sudo: false` there will be a good amount of changes for installing apt or custom packages. I believe this http://docs.travis-ci.com/user/migrating-from-legacy helps.

**Comment by OrkoHunter** [comment]
I'm working on it. Someone of the owners will have to set up the hook on ci.appveyor.com so that I can send a PR to test the build.

**Comment by ysitu** [comment]
@OrkoHunter Can you port the necessary files from `networkx-metis` to here?

**Comment by OrkoHunter** [comment]
I have some of the work done. I was waiting for anyone to set up the hook so that I can send a PR.

**Comment by ysitu** [comment]
@chebee7i Can you help set up the necessary hooks on AppVeyor?

**Comment by ysitu** [comment]
@OrkoHunter You can send in a PR whenever it is ready. The AppVeyor setup can be managed separately.

**Comment by OrkoHunter** [comment]
We have the code for appveyor already merged (#1699), but it's not being used right now because it hasn't been activated yet. _One of the owners_ need to do look into this and set up a hook over [appveyor](https://www.appveyor.com/).

Ping @hagberg @dschult

**Comment by dschult** [comment]
I've got it working on my fork, but thought it strange to createa hook from
the main repo to my personal account on appveyor.  Is there a way to get a
globally viewable account on appveyor so we can all look at the build
results?

I'll look into it...

**Comment by dschult** [comment]
It looks like appveyor is set up as a webhook service for networkx.
It lists the payload URL as https://ci.appveyor.com/api/github/webhook?id=y09ce4gwjxamp5m4

I can connect to it from my appveyor account and start a build. But I'm not sure that's helpful for anyone else and I can't find a nice way to have it report back to github the way travis-ci does.  Any help would be appreciated.

**Comment by OrkoHunter** [comment]
@chebee7i had troubles the last time too, as I can recall. I'll try to find out how other orgs do it.. for instance sckit-image. They have it running on every PR.

**Comment by dschult** [comment]
@orkohunter, I set up the hook for appveyor and it is working. The results show up on the PR page like for travis-ci (see #1950). But the ["details" link](https://ci.appveyor.com/project/dschult/networkx-pqott/build/1.0.10) goes to my personal appveyor account--can you see it?  If so, maybe this is enough for now and we can move it to a more communal account on appveyor later if needed.

**Comment by OrkoHunter** [comment]
@dschult Great work ! Yes, I can see the details and that's how it's supposed to be, I guess. Appveyor should do something about it. I think the work here is done.
