### ISSUE TITLE
iter_refactor branch review

### ISSUE THREAD

**Issue by hagberg** [networkx/networkx#1655]
Let's make one more review of the iter_refactor branch before we merge.
Look especially for documentation that didn't get updated to reflect the fact that we are returning iterators for (most) methods that formerly returned containers.

**Comment by hagberg** [comment]
Here are some fixes in Graph().  They probably appear in DiGraph(), MultiGraph(), and MultiDiGraph too.

1) https://github.com/networkx/networkx/blob/iter_refactor/networkx/classes/graph.py#L176
Advanced section on "subclasses" is moderately confusing and needs to be rewritten.  As a consequence of the list/iterator refactor the use of the word "list" here makes it worse.  Also it should probably not be called "subclass" since it really isn't about subclasing the graph class?

2) https://github.com/networkx/networkx/blob/iter_refactor/networkx/classes/graph.py#L393
Clarify Graph.neighbors() returns an iterator (not list)

3) https://github.com/networkx/networkx/blob/iter_refactor/networkx/classes/graph.py#L1462
Returns an iterator

4) https://github.com/networkx/networkx/blob/iter_refactor/networkx/classes/graph.py#L1487
Returns an iterator

**Comment by hagberg** [comment]
1) https://github.com/networkx/networkx/blob/iter_refactor/examples/algorithms/blockmodel.py
Blockmodel needs update for connected components iterator
2) https://github.com/networkx/networkx/blob/iter_refactor/examples/subclass/antigraph.py
Antigraph example needs update for degree iterator

**Comment by hagberg** [comment]
Tutorial needs updating for iterators.
https://github.com/networkx/networkx/tree/iter_refactor/doc/source/tutorial

**Comment by MridulS** [comment]
I have ported the current tutorial to a ipython notebook. https://github.com/networkx/networkx/pull/1663

pydot was last tested for python 2.6 and we have dropped support for 2.6
I think we should mention this as a note.

**Comment by hagberg** [comment]
1) Document changes in API section of reference manual

**Comment by MridulS** [comment]
@hagberg https://github.com/networkx/networkx/pull/1693 and https://github.com/networkx/networkx/pull/1676

**Comment by dschult** [comment]
Regarding @hagberg first comment about using the term adjacency list:
1a) We use the term ```adjacency list``` and ```adjlist``` in the docs and we store the adjacency info in a dict-like structure created by ```adjlist_dict_factory```. The term ```adjacency list``` can be replaced with ```adjacency information``` easily. The term ```adjlist``` could be changed to ```adjlist_dict```.

But: Would it be better to change the name from ```adjlist_dict_factory``` to ```adj_dict_factory```? It's not backward compatible, but adjlist_dict_factory has only been around for about a year. I'm for leaving it as adjlist_dict, but am willing to change if desired.

1b) I think the section heading ```subclasses``` is appropriate here. Do I understand that terminology wrong? The examples make a new class which inherits from the original class.

**Comment by hagberg** [comment]
Are we done here?

**Comment by dschult** [comment]
As far as I know we are done here...
@MridulS ?

**Comment by MridulS** [comment]
Yeah :)
