### ISSUE TITLE
Convert examples (or create new ones) for Jupyter/IPython notebooks

### ISSUE THREAD

**Issue by hagberg** [networkx/networkx#1656]
Notebooks now render in github so this is a great time to create some for NetworkX http://blog.jupyter.org/2015/05/07/rendering-notebooks-on-github/

The tutorial and examples would be better as notebooks.

**Comment by MridulS** [comment]
I did start doing this https://github.com/MridulS/NetworkX-Tutorial . I started righting a tutorial.
Should I just convert the current examples (and add a few) to IPython notebooks?

**Comment by hagberg** [comment]
Perhaps the notebooks should be in a separate repository (with the tutorial)?

**Comment by MridulS** [comment]
I think this a good idea. We should go ahead and do this. :)

**Comment by dschult** [comment]
Should the new repository be called ```networkx-examples```?  (Should we move the examples there too?)
Or would it be better to call it ```networkx-ipynb``` an/or just have notebooks there?

**Comment by hagberg** [comment]
I was proposing we convert the examples to notebooks and put them in a separate repository with other notebooks for tutorials, lectures, books,....
Maybe we just call it `notebooks`?

**Comment by MridulS** [comment]
something like this https://github.com/MridulS/nx-examples

**Comment by dschult** [comment]
I've created a repository for notebooks at https://github.com/networkx/notebooks
I think @MridulS examples will fit there nicely.

**Comment by hagberg** [comment]
Discussion continued at #1754
