### ISSUE TITLE
Having a Requirements.txt or completing install_requires

### ISSUE THREAD

**Issue by OrkoHunter** [networkx/networkx#1661]
While writing the script for appveyor, I realize that NetworkX misses a requirements.txt and hence does not avail the `pip install -r requirements.txt` option while installing. Some of the packages are optional but should be included in the `requirements.txt` to provide the option of *complete* installing of all the dependencies. In my opinion, populating `install_requires` of `setup.py` for this purpose is not a good idea.

**Comment by jfinkels** [comment]
The way I've done this in the past is *minimum* installation requirements in `setup.py` and *maximum* installation requirements in `requirements.txt`. This way, when building the egg/wheel/whatever via `python setup.py ...` you get the minimum requirements, but when installing via pip, like in testing or development environments, you get all the optional dependencies as well. I don't know how other people do it or what the "best practice" is.

**Comment by chebee7i** [comment]
That's how I prefer it too as well, and I don't mind a bit of duplication in the `requirements.txt`. It's not like we're managing a stadium full of dependencies.

**Comment by hagberg** [comment]
Would someone be willing to implement this?

**Comment by OrkoHunter** [comment]
@karrtikr Are you interested in this?

**Comment by karrtikr** [comment]
@OrkoHunter I'll be sending a PR shortly
