### ISSUE TITLE
Order of nodes

### ISSUE THREAD

**Issue by OrkoHunter** [networkx/networkx#1670]
I have a question regarding the order in which `add_nodes_from` adds nodes to a Graph.
```py
In [1]: import networkx as nx
In [2]: node_list = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 1, 2, 3, 4, 5, 6]

In [3]: G = nx.Graph()
In [4]: G.add_nodes_from(node_list)

In [5]: list(G.nodes())
Out[5]: ['a', 1, 'c', 'b', 'e', 'd', 'g', 'f', 'i', 'h', 'j', 2, 3, 4, 6, 5]
```

Why is the order changed? How can I make it in the same order as `node_list`.

I can understand that in a graph, the order of nodes doesn't make much sense. But in a python list, the order has a good role in various operations.

**Comment by MridulS** [comment]
I think ordered dict, mentioned in the subclasses section of graph.py, will
solve this. Give it a try :)

**Comment by SanketDG** [comment]
The nodes in any `networkx` graph is fundamentally a python dict, and python dicts are arbitrary as stated [here](https://docs.python.org/3/library/stdtypes.html#mapping-types-dict).

Also, adding to @MridulS's sugesstion, you can use the standard library's [OrderedDict](https://docs.python.org/3/library/collections.html#collections.OrderedDict) too to retain key order.

**Comment by OrkoHunter** [comment]
Thanks guys.. I found the [example in the docstring](https://github.com/networkx/networkx/blob/master/networkx/classes/graph.py#L208).
