### ISSUE TITLE
NetworkX Jython compability

### ISSUE THREAD

**Issue by hagberg** [networkx/networkx#1671]
We are not officially supporting Jython.  But it might be nice to try to fix these small things so that it can be installed.
http://stackoverflow.com/questions/30302622/installing-networkx-1-9-1-on-jython-2-7-0/31438974#31438974

**Comment by jfinkels** [comment]
Would it help to put the atlas graphs into a separate data file?

**Comment by hagberg** [comment]
Maybe, I'm not a Jython user so I don't have any technical suggestions.  It looks like removing lib2to3 is a good suggestions.

**Comment by ysangkok** [comment]
If you need any input from a Jython user, let me know. What is required for progress on this issue?

**Comment by hagberg** [comment]
NetworkX will be a 'best-effort' to support Jython in that many small fixes have been made, mostly to ordering issues in the tests.  If someone wants to take this on as a project that would be welcomed.
