### ISSUE TITLE
Draw Graph with self loops

### ISSUE THREAD

**Issue by OrkoHunter** [networkx/networkx#1672]
I was looking around for a way to plot a Graph with self loops using `nx.draw()` or something similar but  I couldn't find one. Instead, I found [an old mail](https://groups.google.com/forum/#!topic/networkx-discuss/pfyLwp6TDI0) in the list, which says that it was not implemented back then. Is there any progress in this regard since then?

**Comment by SanketDG** [comment]
I think it is not implemented yet, same reason on why we parallel edges can't be drawn. Its probably very hard to implement these in matplotlib.

**Comment by hagberg** [comment]
It's not that hard.  But nobody has created a robust implementation.
Similar to the arrow drawing...
Graphviz works well to draw self loops.

**Comment by OrkoHunter** [comment]
Graphviz is really sweet for this.
