### ISSUE TITLE
Contributors should agree to license their contributions under NetworkX's copyright license

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#1675]
As with any free and open source software developed in the open, NetworkX ought to have a [contributor license agreement](https://en.wikipedia.org/wiki/Contributor_License_Agreement). [Here](https://github.com/clahub/clahub) is an example of a web service that integrates with GitHub that requires contributors to agreement to the terms of such a contract.

**Comment by MridulS** [comment]
We already use a BSD license. Doesn't that automatically make all the code contributed BSD licensed.

Are you talking about something like this http://www.harmonyagreements.org/index.html

**Comment by ysitu** [comment]
IANAL, but the license may be revoked.

**Comment by jfinkels** [comment]
@MridulS No. Basically, someone who publishes a computer program immediately gains copyright on that work. By default no one except the author has the right to duplicate, perform, redistribute modified versions of, etc. the work unless the author distributes it under a copyright license that *explicitly* specifies otherwise. Copyright law is complicated, especially for collaboratively built software: although small enough contributions may not be copyrightable, many of them in aggregate may be. (This applies to copyright law in the United States, by the way.)

@ysitu Yes maybe, assuming the contributor publishes his or her code under the Modified BSD license. This is a problem with the BSD license: it does not specify an *irrevocable* license. But I'm not totally clear on that process, since I've never seen it happen.

**Comment by hagberg** [comment]
There is discussion over at #1878 that should be here.

**Comment by dschult** [comment]
The discussion from #1878 that should be here is:

@jfinkels wrote

Don't add lines to this attribute. Your copyright ownership is noted in the file header.

@dschult wrote

I'm not clear on this spec. I understand that we're going to be slowly moving through the code shifting __author__ lines to comments. But I never saw a discussion of how that should appear.

Are we going to list authors in a comment line, or list them as part of a copyright statement? If we list them as part of a copyright, how do we handle the year, etc... @hagberg I think you have talked to lawyer types about this sort of thing. How should we annotate authors in the source?

@jfinkels wrote

This is why I suggested #1675 (which I consider not really a "Documentation" issue, but a "Defect", for the problems you propose here). This is how, for example, Python Software Foundation does it.

The way it roughly seems to have been done until now is this: a contributor distributes the code that he or she authors (and on which he or she has a copyright) to NetworkX under an appropriate license (i.e. the Modified BSD License), and the copyright for that bit of contributed code (i.e. the author and year) is listed.

@hagberg wrote:

This is off topic from this PR but...
I'd like to keep the barrier as low as possible for contributing.

There is no networkx organization at this point. If we wanted to consider a copyright license agreement we'd have to create something like that first.

The current situation is as @jfinkels describes. We accept code contributions from authors who must have the authority and ability to distribute the code under the modified BSD license. We don't require a copyright statement if the author does not provide one and are willing to add the standard NetworkX copyright if requested. I'd prefer not to include any code without an explicit copyright statement.

We have no clear license on the documentation other than BSD (which isn't quite appropriate for documentation).

@dschult wrote 

So, if we have a copyright line in the header for the file, do we put their name in the comment listing authors? Or is the authors comment line optional if/when we have copyright lines?

**Comment by hagberg** [comment]
Copyright and authorship are different things.  So they could be the same or not.
Since we haven't been very strict about these things I wouldn't assume anything regarding either.
For example there are certainly some places where my name is on the copyright but I didn't write the code.  

I suggest something like
If there is an `__author__`  variable change it to an author comment.
If there is no author then there is no author other than we can determine from commits.
If there is an author with no copyright we might consider asking the author to be more clear about copyright intent.

**Comment by dschult** [comment]
I added a section to the "Developer Notes" wiki page on how to format the module header lines. It would be great to make that text match what we want to head for.  I think it is close already.  I invite people to please adjust/change that whole page as you think fit....

**Comment by dschult** [comment]
The original post here points to CLAHUB as a service that collects and checks if contributors agree to the CLA as part of the pull request process. It looks cool--but (see [clahub issue #111](https://github.com/clahub/clahub/issues/111)) the maintainer is looking for a permanent host for the service. In that issue are pointers to other similar services.  Would someone like to find an appropriate service for us?

**Comment by hagberg** [comment]
Closed due to inactivity.
