### ISSUE TITLE
Add `bfs_predecessors_iter` function

### ISSUE THREAD

**Issue by harlowja** [networkx/networkx#1694]
In taskflow (and openstack project) we have this function, which I don't think networkx provides,

https://github.com/openstack/taskflow/blob/master/taskflow/types/graph.py#L104

Does this seem useful to add to networkx, if so, I can make a PR and it can be included.

**Comment by MisterSheik** [comment]
You can write this as `(x for x, y in bfs_edges(G, reverse=True))` :)

**Comment by MisterSheik** [comment]
However, there is a lot of cleanup possible in the file `breadth_first_search` in terms of optimizing the functions `bfs_successors` and `bfs_predecessors`.

**Comment by harlowja** [comment]
Doing ``(x for x, y in bfs_edges(G, reverse=True))`` would seem to duplicate ``x`` potentially > 1 time right?

**Comment by MisterSheik** [comment]
You're right.  My guess is `bfs_edges` should be changed to output pairs `(node, children)`.  This would make `bfs_successors` faster, and solve your use case.

**Comment by harlowja** [comment]
That'd work to, would that change be acceptable (or should it be a new function?)

**Comment by MisterSheik** [comment]
It's not up to me :)

**Comment by harlowja** [comment]
Someone needs to fix that :-P

**Comment by MisterSheik** [comment]
@harlowja Check this out: https://github.com/networkx/networkx/pull/1693  Looks like they are working on this general problem (but not your specific problem).

**Comment by harlowja** [comment]
#1693 kills my browser trying to open it, lol.

**Comment by MisterSheik** [comment]
They are making all methods return iterators, so I guess they ultimately want bfs_predecessors to also return an iterator.  I think it wouldn't hurt for you to write the patch for that file.  There are no significant changes to it in their patch so far.

**Comment by MridulS** [comment]
@harlowja I'll send in a PR regarding this. Right now we are looking into making traversal algorithms return iterators instead of dict/list, this will be a part of the 2.0 release :)

**Comment by harlowja** [comment]
Cool, feel free to take that code mentioned above @ https://github.com/openstack/taskflow/blob/master/taskflow/types/graph.py#L104 , or something else (Both projects are apache licensed, so afaik they can just share).

**Comment by dschult** [comment]
It looks like bfs_predecessor was made into an iterator in #1825 
I'm closing this. If that PR doesn't do what you want we can open it again.
