### ISSUE TITLE
Use the six library

### ISSUE THREAD

**Issue by harlowja** [networkx/networkx#1702]
I see some places in the code that do things like

```
try:
    basestring
except NameError:
    basestring = str
```

Or:

```
PY2 = sys.version_info[0] == 2
```

Or:

```
unicode = str
...
isinstance(key, (str, unicode))
```

I'm thinking the six library could just be used to do most of this instead, that's pretty much what its designed for.

**Comment by hagberg** [comment]
I don't think there are many places where we are using that kind of nonsense.  Maybe there are more than I remember (didn't check now) and we should try to eradicate them.  They are likely in the code where we are trying to interface to an external library or tricky standard.

**Comment by harlowja** [comment]
Ya I didn't see to many from doing a `grep` but seems like low-hanging fruit for someone if they want to just fix these with the six library.

**Comment by hagberg** [comment]
I am not enthusiastic about adding that dependency for a few cases.  I'd like to *remove* the ugly code not add to it.

**Comment by harlowja** [comment]
That works to, remove the code or fix it with six is fine by me :stuck_out_tongue:

**Comment by ysitu** [comment]
Those hacks are mostly for Python 2/3 compatibility. `six` is the perfect tool for this purpose. But if that is not allowed, you have to resort to the hacks.

**Comment by harlowja** [comment]
I'd hope we can get past the not allowed question, six is widely used for this, but many many many projects, so IMHO if we want to retain these 'hacks' we should use six to make the hacks better, or the other option is to remove the hacks entirely (which also fixes the problem).

**Comment by MisterSheik** [comment]
I am also +1 on six.  I noticed that too when reading the code.

**Comment by hagberg** [comment]
I'm not enthusiastic about six.  As you can see it more or less replaces one hack with another.
Worse, if we depend on it then some overachievers will find lots more places to use it to try to "optimize" code.  I'd prefer we leave the hacks and focus on writing good Python3 code.

**Comment by MisterSheik** [comment]
@hagberg I agree with your point about minimizing code churn.  However, the "hacks" in six are [extremely well-tested](http://pypi-ranking.info/alltime).

**Comment by harlowja** [comment]
Some of this is done @ https://github.com/networkx/networkx/pull/1709 (I probably missed more cases, hopefully did mess up to many of the existing ones...)

**Comment by ysitu** [comment]
If the concern is attempts to use `iteritems()` and alike in Python 3, those can be blocked during code review. But incompatibility of Python 2/3 string types is a major cause of well-intentioned hacks that should just be replaced with `six`.

**Comment by hagberg** [comment]
Yes, I have fought off using iteritems() and friends  with six several times before.  We should be thinking Python3. 

The places where #1709 uses `six` are not compelling to me.
- we don't need flatten() in layout.py
- I don't understand the nx_pydot() need to test for strings (and it is a simple hack)
- the graphml.py change is no simpler or clearer
- the gml.py reader and writer are so amazing already - it would be great to simplify there including not using lib2to3.

**Comment by MisterSheik** [comment]
I have to disagree that the changes in https://github.com/networkx/networkx/pull/1709 are "no simpler or clearer".  At the very least they are 30 lines fewer.

I agree with you that we should "be thinking in Python3", which means that things like `basestring` should not appear in the code.

**Comment by dschult** [comment]
30 lines shorter does not correspond to simpler or clearer. Besides, how
many lines of six are there that we are effectively adding?

One power of python is its indentation structure which tends to use more
lines, but makes code more readable.

**Comment by hagberg** [comment]
If you ignore the gml.py code (which is already very complicated) it
doesn't simplify things.
I'm fine with making these modules Python3 only.

**Comment by MisterSheik** [comment]
The lines of six don't count in my opinion.  They don't count as sources of potential bugs because they have been tested by millions of users.  And they don't count as contributing to complication because they are common between the many projects that use six and so as users we only have to learn them once.

I don't like dependencies either, but `six` might as well be a standard library given how much it's used.

Anyway, like you all, I am looking forward to day that python 2 is dead :)

**Comment by hagberg** [comment]
No, you misunderstood.  I like Python2 and fine with me if it lives forever.  But we can write Python3 code so why not?

**Comment by OrkoHunter** [comment]
@MisterSheik I agree with you that `six` is more or less like a standard library when it comes to Python 2/3 compatibility. We can't simply ignore the number of installations of it through pypi.

Further, Python 3 is great but the legacy version is not yet "dead". :) As long as ubuntu has default Python 2 as `python`, it can't be dead. And that's why IMHO, we must take backwards compatibility as an important concern. So, we should write Python 3 but we can't ignore version 2.

**Comment by MisterSheik** [comment]
I never said we should ignore python 2.  I said that we should use six because it's standard and that I agreed with Aric that we should be thinking in Python 3.  I was just trying to close my comment that seemed harsh with a conciliatory remark.

**Comment by OrkoHunter** [comment]
#1775

**Comment by hagberg** [comment]
Can we agree we disagree and close this?  And not use six :-)

**Comment by harlowja** [comment]
Oh, u mean like agree to use six, sweet :stuck_out_tongue:

**Comment by hagberg** [comment]
I mean agree to close :smiley:
