### ISSUE TITLE
Remove "NetworkX" prefix from exceptions

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#1705]
The `NetworkX` prefix is redundant information and can be safely removed from exception class names without affecting the user's understanding of the source of the exception. The final line of the following stack trace demonstrates that the exception's package is output by Python along with the exception class name:

```
$ python3 -c "import networkx as nx; nx.Graph().remove_edge(0, 0)"
Traceback (most recent call last):
  File "/home/foo/src/networkx/networkx/classes/graph.py", line 938, in remove_edge
    del self.adj[u][v]
KeyError: 0

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/foo/src/networkx/networkx/classes/graph.py", line 942, in remove_edge
    raise NetworkXError("The edge %s-%s is not in the graph" % (u, v))
networkx.exception.NetworkXError: The edge 0-0 is not in the graph
```

Furthermore, as an appeal to authority, Django, for example, one of the most popular Python projects, doesn't use prefixes: https://github.com/django/django/blob/master/django/core/exceptions.py (unless the exceptions are related by some topic more specific than just "Django").

This change would mean that places where `NetworkXError` is raised must be modified to raise more meaningful exception classes (or use built-in exception classes). This is tedious work, but totally worth it.

**Comment by harlowja** [comment]
I very much agree with not using prefixes. :+1:

**Comment by harlowja** [comment]
(although do note it would have to be a 2.0 change to do this); because people actually use those exception names as they exist right now, so a backward compat. set of 'aliases' would have to be retained if this was done before 2.0 is released.

**Comment by MisterSheik** [comment]
@harlowja All of your examples do inherit from a base class like `NetworkXException`, which is probably something that should be copied.

**Comment by harlowja** [comment]
Do note that most of those do have a root level exception that is inherited from for all other exceptions, so we should still do that.

**Comment by priyanklodha** [comment]
Someone please guide me over this. I want to start contributing, this issue seems a good starting point.
If not, suggest me something to start with.
PS- I don't have much understanding of the code.

**Comment by jfinkels** [comment]
Start with this, for example:

  https://github.com/networkx/networkx/blob/master/networkx/algorithms/simple_paths.py#L80

Change this line so that it raises a new exception, `NodeNotFound` instead of the generic `NetworkXError`. Perhaps create an exception class `NodeNotFound`, inheriting from `NotFound`, inheriting from `NetworkXException`. These exception classes can live in `networkx.exception`.

**Comment by MridulS** [comment]
I'll keep on updating this PR, https://github.com/networkx/networkx/pull/1894

**Comment by MridulS** [comment]
Instead of merging one huge PR, I guess we can start updating errors like PEP8. Update them only when you work on them.

**Comment by harlowja** [comment]
Sounds good to me :+1:

**Comment by kpetridis24** [comment]
I removed all prefixes from NetworkX errors, inside the exception.py file, and replaced all their old occurences inside the project. Can i somehow check that everything works correctly in the entire project? Is there a specific way to check everything (for example run all doctests)?

**Comment by rossbar** [comment]
What's the motivation for this aside from the fact that it's the pattern followed by other projects? Is there a major gain or improvement from renaming the exceptions to remove the prefix? Having shorter exception names is nice and I understand that the information is redundant, but neither of these seem to be a major improvement --- at least not when weighed against the potential for breaking existing code that is catching specific NX exceptions by name.

Just curious about the background if there's any info on this topic that isn't captured in the above discussion!

**Comment by rossbar** [comment]
This was [recently discussed](https://github.com/networkx/archive/blob/main/meetings/2022-04-08.md#long-term-tracking-items) and the general consensus was that there wasn't a lot of motivation for this change.

@boothby noted that there would be a way to go about this without breaking user code by creating new, non-prefixed exceptions that inherit from the current exceptions, e.g.

```python
class AlgorithmError(NetworkXAlgorithmError)
```

then replace all internal instances of `NetworkXAlgorithmError` with the preferred exception name. That way, any user code that's catching `NetworkXAlgorithmError` will still work as expected with the new exception name.

While this approach would alleviate the concerns of breaking user code, there is still low appetite for this change without a more concrete motivation to justify the churn. If you feel strongly about this or have additional points to add to the discussion, please feel free to reopen!
