### ISSUE TITLE
Add a not_implemented_for() handler for the null graph

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#1706]
There are several functions whose first line rejects empty graphs. This can be abstracted and placed in a decorator, for example, `not_implemented_for('null')`. The exception raised would be `NetworkXPointlessConcept`.

**Comment by dschult** [comment]
Do we really need to be doing this?
Can't we spend our time on some new graph algorithms?

**Comment by jfinkels** [comment]
Well, the intent of this suggestion is to remove a lot of repeated code and bring some more cohesion to the library so that authors can focus on writing clear functions that implement the graph algorithms, without having to include code like `if len(G) == 0: ...`, which detracts from readability and forces authors to write their own error messages (likely different from those in other functions that have such a check).

This, like most of my suggestions, is for the sake of readability, and I don't mind spending time improving that.

**Comment by hagberg** [comment]
Sure, I see the point but these changes require review and attention by developers so they aren't free.  It looks like more than half of the last 20 pull requests are of this type (not bug fixes or feature additions).

**Comment by jfinkels** [comment]
Those are mostly mine, so if you don't have the time for them or are not
interested in that sort of revision to the code, feel free to close them.
