### ISSUE TITLE
Lose digraph ordering when creating a duplicate

### ISSUE THREAD

**Issue by harlowja** [networkx/networkx#1718]
I am seeing the following, which doesn't look right at all.

```
>>> import networkx as nx
>>> g = nx.OrderedDiGraph()
>>> g.add_node('a')
>>> g.add_node('b')
>>> g.add_node('c')
>>> list(g)
['a', 'b', 'c']
>>> g1 = nx.OrderedDiGraph(g)
>>> list(g1)
['a', 'c', 'b']
```

It seems the order is being lost when the graph is being copied (which is the recommended way to generate a new graph, if the prior one is frozen for example); this doesn't feel like what would be the expected result here.

```
$ pip freeze | grep networkx
networkx==1.10
$ python --version
Python 2.7.10

**Comment by harlowja** [comment]
Trying to work around this using the convert routine directly, didn't seem to fix the issue.

```
>>> from networkx import convert
>>> g2 = convert.to_networkx_graph(g, create_using=nx.OrderedDiGraph())
>>> list(g2)
['a', 'c', 'b']
```

**Comment by harlowja** [comment]
The following does seem to work, but likely isn't really a *good* solution.

```
>>> g3 = nx.OrderedDiGraph()
>>> g3.add_nodes_from(g.nodes_iter())
>>> g3.add_edges_from(g.edges_iter())
>>> list(g3)
['a', 'b', 'c']
```

**Comment by dschult** [comment]
This looks like a bug.... Thanks for reporting it. I'll look into it.

**Comment by harlowja** [comment]
Thanks!
