### ISSUE TITLE
maximal_matching and self loops

### ISSUE THREAD

**Issue by aureooms** [networkx/networkx#1736]
`maximal_matching` does allow self-loops
```py
>>> G = nx.Graph([[1,1]])
>>> nx.matching.maximal_matching(G)
{(1, 1)}
```
whereas `max_weight_matching` does not
```py
>>> nx.matching.max_weight_matching(G)
{}
```
Is this expected behaviour? If not, a simple `u != v` check should fix it.

**Comment by hagberg** [comment]
Interesting.  I don't know what the correct definition is.  But we should be consistent.
Maybe don't allow self loops?  If we document that and give an example of how to remove self loops then both cases should be covered.

**Comment by hagberg** [comment]
Anyone have comments on how to resolve this?

**Comment by jfinkels** [comment]
I suggest not allowing self-loops in maximal matchings. Consider the path graph on two nodes with self-loops on both nodes. If self-loops are allowed, the maximum matching would be the set of two self-loops, which is a little surprising. This may be desirable in certain situations, but I think we should leave that as an example in the documentation if necessary.
