### ISSUE TITLE
Predecessor Ideas?

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#1738]
Issues #1696 and #1715 seem to suggest that there is demand for an API to access the predecessors dict in a similar way that G[u] accesses the successors dict. I'm opening an issue to collect the discussion on this question.

G.pred[u] has always been the way I do this, but that refers to a data structure element directly which makes it hard to generalize to new base classes. 
    - G.predecessors() and G.in_edges() are what we currently offer. 
    - #1696 suggests G.has_predecessor() though that could be written `0 < len(G.in_edges(u))` 
    - #1715 toyed with switching G.succ and G.pred to reverse the graph. (very shallow copy?)

Should we add has_predecessor? Should we add an analogue to G[u]? Maybe G.in_edges_dict(u)?
Thoughts?

**Comment by dschult** [comment]
I also realize that G.adjacency() accesses the G.succ dict. So a corresponding method to G[u] could be G.in_adjacency().  If preferred we could use an optional G.adjacency(u) and G.in_adjacency(u).

Is there a problem with treating G.adj, G.succ and G.pred as read-only ways to access the connectivity info? I know that users could change them and break the data structure. But do we actually need a method when we have graph attributes available directly?

**Comment by harlowja** [comment]
Personally I'd be ok with methods or just direct attribute access, just having something that is recommended and 'one way' would be super :smile: (vs having many ways, each with different drawbacks).

**Comment by MisterSheik** [comment]
I agree with Joshua that there should be one way to do things.  I just want to point out that calling `G.edges` is different than say `G[u]` with multigraphs.  Multiple edges show up multiple times in the former, but not the latter.  If possible, this quirk should be more obvious.

**Comment by dschult** [comment]
I don't agree that there should be only one way to do things if there are tradeoffs involved. Choose good defaults of course, but don't restrict it to only one possible way.

We want to make it easy to do simple things, but also possible to do complex things.

**Comment by MisterSheik** [comment]
Isn't `has_predecessors(u)` equivalent to `in_degree(u)==0`?

**Comment by dschult** [comment]
Yes, ```has_predecessors(u)`` is the same as ```in_degree(u)==0```.   :)

The fact that it took many developers many days to come up with that idiom suggests it is not obvious, but that is the current best way to check for "no predecessors" in our API.

**Comment by MisterSheik** [comment]
Good point.  I'm not against adding convenience methods :)

**Comment by hagberg** [comment]
Closed due to inactivity.
