### ISSUE TITLE
Implicit graphs?

### ISSUE THREAD

**Issue by vergenzt** [networkx/networkx#1745]
I didn't see this anywhere in the documentation so I thought I'd ask. Is there support for implicit graphs in NetworkX? (I.e. the ability to specify a graph using only a starting node and a neighbor function, and having the rest be generated.)

If not, any tips on alternative approaches? Can a graph object be modified during traversal to simulate this?

**Comment by MridulS** [comment]
@vergenzt We currently don't support implicit graphs.

> If not, any tips on alternative approaches? Can a graph object be modified during traversal to simulate this?

Something like this, maybe?
``` python
In [1]: import networkx as nx

In [2]: G = nx.Graph()

In [3]: g = lambda x: x in range(0, 10, 2)       # neighbor function

In [4]: for i in range(0,10):
   ...:     if g(i):
   ...:         G.add_edge(0, i)           # 0 is the starting node
   ...:

In [5]: list(G.edges())
Out[5]: [(0, 0), (0, 8), (0, 2), (0, 4), (0, 6)]
```

What kind of neighbor function are you working with?

**Comment by vergenzt** [comment]
I was toying with trying to implement a state graph for a basic sliding-block puzzle game (i.e. you have blocks that start in a particular location and can move in particular directions and have to get to a goal state), and wanted to see if I could apply A* to it.

**Comment by vergenzt** [comment]
So for example a starting state could be a dictionary of locations to block types. (The puzzles are small, on the order of there only existing a few thousand states total.)

Pseudocode for the neighbor function could then look something like:
```python
def neighbors(state):
  for (pos, block) in state if moveable(block):
    for direction in which block can be moved:
      # yield state with block moved in direction
```

**Comment by dschult** [comment]
Here's a draft(untested) of some code that could create a graph from a
neighbors function and a starting state.  :)

G=nx.Graph()
states= {initial_state}   # or a set of starting states
seen={}
while states:
    node = states.pop()
    if node in seen: continue
    for s in neighbors(node):
        G.add_edge(node, s)
        states.add(s)
    seen[node] = 1

**Comment by jfinkels** [comment]
To implement this you would essentially have to rewrite the `Graph` class and require the neighbors function as an initial argument. A lot of the existing methods wouldn't make sense (`add_edge`, for example).

**Comment by vergenzt** [comment]
Okay, thanks for the info, all. Pursuing other options.
