### ISSUE TITLE
Anyone interested in mixing times of random walks on graphs?

### ISSUE THREAD

**Issue by sbordt** [networkx/networkx#1746]
Hi guys,
I'm writing a masters thesis concerned with the mixing times of Markov chains. My Markov chains often result from simple- or non-backtracking random walks on simple (random) graphs. So I started writing python code that allows to compute mixing times using your networkx package to represent my graphs (I am a newbie to python). With some additional effort, I could write a Python package having methods like

```
srw_mixing_time(G, node)
plot_nbrw_mixing(G, node)
```

Before doing this I'd like to know if anyone here is interested in the mixing times of random walks on graphs? Hope this is the right place to ask the question :)

**Comment by dschult** [comment]
Probably a better place (more viewers with broader perspective) is the
NetworkX-discuss <https://groups.google.com/forum/#!forum/networkx-discuss>
email list.
This tends to be just developers.

That said, I imagine many people are interested in mixing times.
Enjoy Python and NetworkX. If you come up with a useful function/module
this would be a good place to propose it and get feedback on the code. :)

**Comment by sbordt** [comment]
Thanks a lot for your comment, once I have something to show I'll get feedback from the email list!
