### ISSUE TITLE
graph module self.size() function has an bug.

### ISSUE THREAD

**Issue by litaotju** [networkx/networkx#1748]
`networkx.classes.graph` has a problem:

    def size():
    ....
        s = sum(self.degree(weight=weight).values()) / 2
    ....

but `self.degree()` returns an `int` or a `dict`, so when it returns an `int`, the `int` object has no attribute `values()`.

**Comment by MridulS** [comment]
@litaotju self.degree() returns an int only if a single node is passed as an argument, which is not the case here.

So, this won't be a problem :)

**Comment by litaotju** [comment]
Thanks for anwsering this. I.have sovled the problem.
