### ISSUE TITLE
Layouts in 1.10 behave differently

### ISSUE THREAD

**Issue by AgostinoSturaro** [networkx/networkx#1750]
Just updated my Anaconda distribution (v 2.3) to NetworkX 1.10.
I noticed the same code for graph layouts returns very different plots.

    import networkx as nx
    import matplotlib.pyplot as plt
    
    G = nx.random_regular_graph(2, 20)
    nx.draw_networkx(G, pos=nx.random_layout(G))
    plt.show()
    nx.draw_networkx(G, pos=nx.circular_layout(G))
    plt.show()
    nx.draw_networkx(G, pos=nx.spring_layout(G))
    plt.show()
    plt.close()

Circular layout and spring layout (and possibly others) are double the size and centered differently
Output of v 1.9.1, plot is 1x1 and centered on (0.5, 0.5)
![circular_layout_v1 9 1](https://cloud.githubusercontent.com/assets/1441393/9502170/f2bb65ca-4c2f-11e5-90b0-f631dad7f538.png)
Output of v 1.10, plot is 2x2 and centered on (0.0, 0.0)
![circular_layout_v1 10](https://cloud.githubusercontent.com/assets/1441393/9502139/bab9bff0-4c2f-11e5-8bbd-423c53b1e275.png)

UPDATE: [the documentation](networkx.readthedocs.org/en/stable/reference/generated/networkx.drawing.layout.spring_layout.html) for `spring_layout` says it should position nodes "in a box of size [0,scale] x [0,scale]". But they get positioned in a totally different area, and the size of the box can be triple that.

    import networkx as nx
    import random
    import matplotlib.pyplot as plt
    
    G = nx.barabasi_albert_graph(20, 3, 130)
    G.add_edge(21, random.choice(G.nodes()))
    
    nx.draw_networkx(G, pos=nx.spring_layout(G))
    plt.show()
    plt.close()

Notice how the height of the plotted graph is 3, from -2.0 to 1.0.
![spring_layout_v1 10_bug](https://cloud.githubusercontent.com/assets/1441393/9507383/2700fe30-4c4e-11e5-92d6-7f3d6fd51fff.png)

**Comment by AgostinoSturaro** [comment]
Please note that `random_layout` still behaves like in 1.9.1 (not centered at 0, 0), and in fact it lacks the scale parameter.

I used layouts to position nodes randomly/appropriately in an area.
I was using the API as documented, and after updating to 1.10 my code works differently.

Is this the kind of change to expect during a minor revision?
Nodes are now spread over a much larger area, my simulations got skewed, if I didn't have unit tests I would not have noticed it.

This introduced an incompatibility between versions, now I have to checks `nx.__version__` in my code and maintain two different code paths to make it work. Not really an elegant solution.

Here's the topic about [the change](https://github.com/networkx/networkx/pull/1354).

**Comment by dschult** [comment]
There are other bugs/issues I am finding with the layout routines in v1.10.  (see #1759)
I haven't come up with any good work-arounds yet. I'm proposing we make a v1.10.1 release.

Thanks for pointing this out!

**Comment by AgostinoSturaro** [comment]
Thank you for considering this issue.

You may also be interested in [this issue](https://github.com/networkx/networkx/issues/1749), when it comes to harmonizing layout methods in v2.0.

**Comment by dschult** [comment]
@AgostinoSturaro -- Can you take a look at PR #1760 and see whether it solves the problems for you?
It only changes the one file layout.py

**Comment by hagberg** [comment]
Is this now resolved? (with v1.11)

**Comment by dschult** [comment]
Yes, v1.11 resolves this issue.
