### ISSUE TITLE
example notebooks on try.jupyter.org

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#1754]
There is a subfolder `communities` at https://github.com/jupyter/docker-demo-images for organisations to publish example notebooks.

We can add networkx/notebooks repo to `notebooks/communities/networkx`.

**Comment by dschult** [comment]
Is there a good way to tie in the notebooks repository with our documentation?
How do people know to look there?

**Comment by MridulS** [comment]
We should add a link to the notebooks repo in the README file. People can
try these notebooks out using try.jupyter.org or nbviewer.

I remember someone suggesting ipython examples in the documentation. It
would be nice to go through the documentation examples once and making them
more clear and precise.

On a different note. I guess the README file should be more detailed.

**Comment by MridulS** [comment]
On a different note. I guess the README file should be more detailed.

**Comment by MridulS** [comment]
@dschult @hagberg The only way to put up ipython notebook on try.jupyter.org is to send a PR, and regularly update the `jupyter/docker-demo-images/notebooks/communities/networkx` with `networkx/notebooks`. [I guess this will serve our purpose as notebooks won't be changed frequently]

Other way is to deploy our own https://github.com/jupyter/tmpnb service, but do we have the resources for that?

**Comment by dschult** [comment]
When you say "regularly update" the repository, could that be done by a hook based on commits to a branch on networkx/notebooks?  Then it wouldn't be very difficult to keep it synced with our repo.

**Comment by MridulS** [comment]
To sync two repos on github (using hooks) we would need a custom server to detect commit events in the first repo and push it to the second repo.
But again for this we would need commit access to the `jupyter` repo.

**Comment by dschult** [comment]
Maybe we don't need to sync two github repos. The notebooks in networkx/notebooks are accessible in many ways. Github displays them of course. But ipython now provides [nbviewer](http://nbviewer.ipython.org) with direct urls to our github repository [notebooks](http://nbviewer.ipython.org/github/networkx/notebooks).

The resulting URLs are even similar:
Github:  https://github.com/networkx/notebooks/blob/master/tutorial.ipynb
NBViewer:  http://nbviewer.ipython.org/github/networkx/notebooks/blob/master/tutorial.ipynb

The surrounding graphics are slightly different, but both provide static views of our notebook examples.

Let's update the main README and maybe the main website page to have a link to our example ipynb files.  And we should make those example notebooks as good as we can.

**Comment by dschult** [comment]
I think I misunderstood... try.jupyter.org gives a dynamic view of the notebooks. nbviewer and github give static views of the notebooks.  Maybe static with a download link will be enough for now?

Also, we should probably have tags and/or branches of the notebook examples for the different versions of networkx. We'll have to be careful to be using the correct version of networkx when we update the ipynb files. And we should find a way to automate their updating since they currently don't get built during our ```make doc``` sequence.

**Comment by hagberg** [comment]
FYI http://mybinder.org/

**Comment by hagberg** [comment]
This is great.  I think we are pretty close to this being usable and to replace the examples and tutorial in the reference documentation.  That is what we are doing at #2054. 

The next steps are to finish #2054, make the notebooks nicer, and create a new landing page  at networkx.github.io (some kind of single page, easy-to-update) that points to all of our infrastructure - pypi, github, readthedocs, notebooks, stackoverflow, ...

**Comment by MridulS** [comment]
discussion moved to https://github.com/networkx/networkx/issues/2518
