### ISSUE TITLE
Python 3 incompatability: nx.read_shp uses xrange

### ISSUE THREAD

**Issue by GeospatialPython** [networkx/networkx#1755]
Python 3 eliminated xrange() but making range() an interator.  The nx.read_shp shapefile reader uses xrange() which is the only item in this module preventing Python 3.x compatibility.  Using range() should work reasonably well in Python 2.  The issue can be worked around in code with: 
```
nx.read_shp.xrange = range
```

**Comment by MridulS** [comment]
This has been already fixed https://networkx.readthedocs.org/en/v1.10/reference/generated/networkx.readwrite.nx_shp.read_shp.html
You can update your networkx distribution to v1.10 using https://pypi.python.org/pypi/networkx/

**Comment by MridulS** [comment]
fixed in https://github.com/networkx/networkx/commit/dda332ea88ac344a4acd9d54579c3f838f82c126
