### ISSUE TITLE
Make successors consistent with edges

### ISSUE THREAD

**Issue by MisterSheik** [networkx/networkx#1757]
For multigraphs, `successors` coalesces non-unique target nodes, whereas `edges` reports non-unique edges separately.  I think they they should be consistent, and they both should report the multiple copies separately.

    In [22]: import networkx as nx

    In [23]: a = nx.MultiDiGraph()

    In [24]: a.add_edges_from([(1,2), (1,2)])

    In [25]: a.successors(1)
    Out[25]: [2]

    In [26]: a.edges(1)
    Out[26]: [(1, 2), (1, 2)]

I think returning each of the edge copies separately is better than changing `edges` to coalesce them.  If the user asks for the data on the edges, then the edges returned will have different pieces of data, so you won't be able to coalesce them.

**Comment by dschult** [comment]
These two methods were designed for different activities. The successors method was intended to give information about nodes -- specifically, which nodes are successors. The edges method is really about edges.  So I feel the edges method should return a multi-edge as multiple copies of a 2-tuple. But successors is asking for the nodes, so we should not repeat that information.

If we make them return the same information, we might as well have one method.  I see them as having different uses.

**Comment by MisterSheik** [comment]
Ah, I see your point.

**Comment by jfinkels** [comment]
Maybe it wouldn't hurt to document this distinction with a brief note in the relevant methods.
