### ISSUE TITLE
New release 1.10.1?

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#1759]
There are a number of bugs/problems with the v1.10 layout routines. (initially noted in #1750)

I propose that we fix them in a way that keeps the ```_rescale_layout()``` function as it was for v1.9. We then need to fix the new version of ```_rescale_layout()``` for v2.0. There are many other fixes needed for ```spring_layout()``` and maybe others too.  So, I am tempted to do the same for that routine: revert it to the v1.9.1 functionality in a release v1.10.1.   Then fix  the new functionality for v2.0. 

Is this the right way forward?

Problems with layout.py in v1.10:  
 - rescale changes from ```[0, scale]``` box to ```[-scale, scale]``` box so users supporting both versions must check for version number to know what "scale" value to use.
 - the size of scale only uses the maximum position value instead of ```max(abs( ))``` so large negative positions are not in the box ```[-scale, scale]```
 - the new version has an error (```dom_size used before it is assigned```) if ```fixed is not None``` and ```pos is None```.
 - If the input is not an instance of ```nx.Graph``` the new code throws out all edges and spring_layout doesn't even make sense with no springs.
 - spectral layout also throws out all edge info in the input is not an instance of ```nx.Graph```.

**Comment by ysitu** [comment]
Separate from the layout problem, shall we also cherrypick #1707? According to @OrkoHunter's test on AppVeyor, installation on Windows is broken.

**Comment by OrkoHunter** [comment]
Yes, the installation for Python 3 on Windows is broken. Ref. https://ci.appveyor.com/project/OrkoHunter/networkx-metis

**Comment by hagberg** [comment]
I suggest we release 1.11 with these and any other small annoying bugs including doc fixes.
But let's try to do it soon.

**Comment by dschult** [comment]
Are there any other fixes we should add before making a release for v1.10.1?

**Comment by AgostinoSturaro** [comment]
I propose
Build errors on readthedocs  #1667 
Documentation is not automatically built on commit #1571 
Graphml default attribute values are not applied #1398 

Thanks.

**Comment by hagberg** [comment]
Fixing the doc builds would be great. 
The #1398 GraphML decision is not quite resolved.

**Comment by AgostinoSturaro** [comment]
I guess #1783 could also be considered for the next release.

**Comment by AgostinoSturaro** [comment]
Now that release 1.10 is included in Anaconda, I have to tell people to manually patch against this issue #1760 
Is there any news on 1.10.1?
Thanks.

**Comment by hagberg** [comment]
Yes, we should make a release ASAP.  Are there any loose ends to take care
of before we do that?

**Comment by dschult** [comment]
I think v1.11 is the number we have assigned to the fix issues with v1.10.  
All the pull requests for v1.11 are complete. 
I haven't investigated issue #1857 for v1.11 yet. 
I think it should be OK because we are using sphinx from github instead of pip on v1.111 now.
But I'll make sure its working first. 

That's the last thing I know of to allow v1.11 release to go forward.

**Comment by dschult** [comment]
OK... I have resolved all issues for v1.11 (or declared them not to be for v1.11 -- e.g. the GraphML stuff).

I think we are ready to make a release candidate.

**Comment by hagberg** [comment]
See #1882
