### ISSUE TITLE
Weighted and unweighted all-pairs shortest path lengths behave differently

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#1765]
The unweighted versions of the all-pairs shortest path lengths function returns an iterator, whereas the weighted version returns a dictionary. Presumably, the weighted version should be changed to return an iterator as well.

**Comment by MridulS** [comment]
I am working on it :)

**Comment by MridulS** [comment]
https://github.com/networkx/networkx/blob/master/networkx/algorithms/shortest_paths/generic.py#L234

This is also an inconsistency

**Comment by jfinkels** [comment]
Fixed in #1777.
