### ISSUE TITLE
Degree histogram figure misleading

### ISSUE THREAD

**Issue by Seondong** [networkx/networkx#1774]
Hey! I found out that the degree distribution from the below page is wrong.

It is not possible that multiple rank can exists for certain degree.

When you plot 'degree_sequence', you should change 'x' and 'y' axis.

https://networkx.github.io/documentation/latest/examples/drawing/degree_histogram.html

**Comment by hagberg** [comment]
I guess the issue is that the title of the example should be "degree rank" or something similar?

**Comment by Seondong** [comment]
@hagberg  No no, as I explained, it's more than a title issue. 

Just by plotting, nx.degree(G) result, you will get the wrong result.

Here is my solution.

degreelist = nx.degree(G).values() # print list(G.degree().values())
import collections
degreeRank=collections.Counter(degreelist)
orderedRank = collections.OrderedDict(sorted(degreeRank.items()))
plt.loglog(orderedRank.keys(), orderedRank.values(),'b-',marker='o', markersize=1, mfc='black')

**Comment by dschult** [comment]
```On the graph, number of nodes which degree is 4 = 1, 2, 3, 4, 5 : which isn't true logically)```

This is a degree rank plot.  That is the rank order of the degree values.
So, the rank 1 degree is 4. So is the rank 2, 3, 4 and 5.  The the 6th ranked degree value is 3.

That's what is actually plotted. Your code plots the histogram. We should change the name... You could also add your code as an example--then we'd have a histogram too.
