### ISSUE TITLE
Import of lib2to3 in gml.py prevents to use Py2exe or PyInstaller

### ISSUE THREAD

**Issue by goulu** [networkx/networkx#1775]
Since updating to 1.10 I cannot "compile" my application anymore because gml.py (which I don't use) imports lib2to3 . 
Tried several workarounds (exclusion, mockups ...) but couldn't fix this.
I think networkx should use six instead of lib2to3 ...

**Comment by dschult** [comment]
It seems to me this is a case where we don't need six or lib2to3. lib2to3 is used to get rid of u before unicode strings (for python3.2) and to label exceptions that don't really need to be labeled.

It is especially easy to remove these dependencies if we stop supporting python3.2.

**Comment by hagberg** [comment]
Fine with me to stop supporting 3.2.
