### ISSUE TITLE
Minor inefficiency in dijkstra algorithms

### ISSUE THREAD

**Issue by joelmiller** [networkx/networkx#1784]
The dijkstra algorithms seem to all have `c=count()` in them.  The variable `c` is used a few times, but never for anything that actually affects the calculation.  I suspect it was put in during some testing.  In my (limited) testing, it can be removed without altering any results.

**Comment by dschult** [comment]
It looks like c is used in the tuple that gets pushed onto the heap. So presumably the position in the heap will be different if we remove the ```c``` variable. Currently we push 3-tuples (uv-dist, next(c), u). If we push (uv-dist, u), and uv-dist is the same for two nodes, then the heap comparison will depend on comparison of nodes ```u```.  We want to allow nodes that can't be compared.  I think this is the reason we include the value c here.  Maybe a comment in the code to that effect would be helpful.
