### ISSUE TITLE
autosummary docs dont work on readthedocs

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#1796]
Sphinx version 1.3.1 contains a bug in autosumary that doesn't allow it to work with our (and the commonly used) syntax.  The one-line code fix in https://github.com/sphinx-doc/sphinx/pull/1892 works like a charm. So we are Ok in the long run with readthedocs.org

But in the short run (and who knows how long that will be) we've got v1.10 and latest documentation that doesn't connect  the generated documentation pages to the toctree.  To see the effect compare:

  http://networkx.readthedocs.org/en/latest/reference/algorithms.centrality.html
  http://networkx.github.io/documentation/latest/reference/algorithms.centrality.html  

The docs build locally just fine with the fix installed, but readthedocs indicates https://github.com/rtfd/readthedocs.org/issues/1290   that they will not be fixing the problem until Sphinx makes a release.

We could return to network.github.io until that time.
We could continue as is (its been broken since late April).
Other ideas?

**Comment by dschult** [comment]
Another possibility to replace autosummary would be to manually add links to the generated doc pages in the rst files.

**Comment by OrkoHunter** [comment]
I think we can replace the `autosummary` with manually making the table of contents and linking the generated doc pages. I can help. However, that won't look much pretty. :)

**Comment by hagberg** [comment]
It's not clear from the Sphinx project pages when this fix will be released.  But it seems like a lot of work (and error prone) to create all of those lists.  So I suggest we build the pages ourselves and push them to networkx.github.io for now.

**Comment by dschult** [comment]
I've updated the docs in networkx-website to point to networkx.github.io and sent the results working from networkx-1.10 to the networkx-github.com repository.  I think it is working for that latest release. Could someone check and see if there are any obvious errors.  [note--this doesn't fix any of the doc errors that were in v1.10. It just makes the v1.10 version available in a form where the autosummary works.]

**Comment by chebee7i** [comment]
Another option is to downgrade sphinx manually on readthedocs. I tried doing this on my fork, but rtd recently imposed some build time limits and we exceeded them. I haven't had time to look further, but if someone wanted to investigate, see my fork's master branch.

**Comment by dschult** [comment]
@chebee7i 
Could you describe the settings needed on readthedocs to get it to build?
I've tried the default and using a virtual env pointing to docs/requirements.txt and both don't get passed trying to build matplotlib.  

It looks like your fork has built the 2.0 docs with autosummary working. Did the fail of taking too long get rerun in shorter time?

**Comment by chebee7i** [comment]
The only changes required were in the .travis.yml.  Specifically, we explicitly use an older version of Sphinx via pip and go back to using the napolean extension:

https://github.com/chebee7i/networkx/commit/2e2e40e200253f0986f3baa32e59a00b9e1190f0

However, I wasn't able to take it further due to a build timeout, and I hadn't spent any time since then trying to get it to build faster. I wonder if this is just due to it being the a build with no cache. More details here:

https://github.com/rtfd/readthedocs.org/issues/1767

**Comment by chebee7i** [comment]
Also relevant for anyone wanting to try out your own builds:

https://github.com/networkx/networkx/wiki/readthedocs

**Comment by chebee7i** [comment]
Just had another thought. I believe that pip now supports github links to install:

http://codeinthehole.com/writing/using-pip-and-requirementstxt-to-install-from-the-head-of-a-github-branch/

So maybe we do this:

1) Fork our own branch of Sphinx 1.3.2
2) Apply the one line fix in https://github.com/sphinx-doc/sphinx/pull/1892
3) Point our `requirements.txt` to our (temporary) fork.
4) Build happy.

This might side-step the build timeout issue since Sphinx 1.3 seems to build faster than 1.2.

**Comment by dschult** [comment]
Even better than that... the sphinx .3.1 branch on github
<https://github.com/sphinx-doc/sphinx/blob/stable/sphinx/ext/autosummary/__init__.py>
HAS the change -- even though it doesn't show up in their pipy version
<https://pypi.python.org/pypi/Sphinx>.
So maybe we can just point our requirements.txt file to our temporary fork.

I've got my builds working on RTD so I'll try it.

**Comment by dschult** [comment]
Thanks @chebee7i !
Pointing the requirements.txt to github's version of sphinx-1.3.1 did the trick.
The docs compiled in 851 secs which is close to the limit of 900 but within it.

We need to rebuild the v1.10 docs on RTD, but it is linked to a commit instead of a branch, so even if we update the branch RTD won't get the new requirements.txt file.

Could @chebee7i or @ysitu either reconfig the RTD networkx-1.10 pointer to the branch v1.10, or add me as an owner on RTD so I can get that set up?   Thanks very much!

**Comment by chebee7i** [comment]
Added!

**Comment by dschult** [comment]
Warning: [I don't think this will be an issue, but thought I should give a warning]
I changed requirements.txt on the v1.10 branch so readthedocs will build.
I then **moved the tag** for networkx-1.10 to this new commit!
This means the tag has changed and that could cause conflicts for developers who manipulate these tags but have the old tag on their local repo...  I also made the tag an annotated tag (like with previous releases) so it is a git object instead of just a pointer to a commit.

If you have any trouble with a tag conflict between your local repo and the github networkx repo you should delete your local tag for networkx-1.10 and then fetch the new tag.

    git tag -d networkx-1.10
    git fetch <upstream> --tags   # replace <upstream> with the remote name you give to the github repo

I've checked many of your forks of the repo on github and none have the tag networkx-1.10 so I don't think it should be an issue. The old tag was a ["lightweight" tag instead of an "annotated" tag](http://stackoverflow.com/questions/4971746/why-should-i-care-about-lightweight-vs-annotated-tags) with a tagging message, and many systems--perhaps including github forking-- don't bother with lightweight tags.

Let me know if you have questions.

**Comment by dschult** [comment]
Looks like readthedocs is working with autosummary at this point.
Thanks @chebee7i
