### ISSUE TITLE
Better error message if odd degree sum in configuration_model

### ISSUE THREAD

**Issue by joelmiller** [networkx/networkx#1800]
A student came to me a bit confused by an error message from `configuration_model`: 

    if not sum(deg_sequence)%2 ==0:
        raise nx.NetworkXError('Invalid degree sequence')

I think this is a hold-over from an earlier version which checked whether the degree sequence is graphical.  Now it just checks whether it is odd.  Could the error instead say 'odd degree sum'?

**Comment by hagberg** [comment]
How about both?  i.e. "Invalid degree sequence: odd sum".

**Comment by joelmiller** [comment]
Sounds good to me.

**Comment by dschult** [comment]
Fixed in #1819
