### ISSUE TITLE
Bibtex authors line broken

### ISSUE THREAD

**Issue by AgostinoSturaro** [networkx/networkx#1801]
I noticed [this Bibtex](http://math.lanl.gov/~hagberg/Publications/hagberg-2008-exploring.shtml) to cite NetworkX in a paper

The `author` line is missing commas between surnames and names, so Latex shortens everything

    @inproceedings{hagberg-2008-exploring,
        author = {Aric A. Hagberg and Daniel A. Schult and Pieter J. Swart},

>  H. A. A., S. D. A., and S. P. J.

The fix is trivial and produces a readable result

    @inproceedings{networkx_paper,
        author = {Hagberg, Aric A. and Schult, Daniel A. and Swart, Pieter J.},

>  A. A. Hagberg, D. A. Schult, and P. J. Swart

**Comment by hagberg** [comment]
I'm pretty sure BibTeX is supposed to handle that case correctly and it is a typical example :https://en.wikibooks.org/wiki/LaTeX/Bibliography_Management#Authors

**Comment by AgostinoSturaro** [comment]
Sure, it should.
With the [IEEE LaTeX template](http://www.ieee.org/conferences_events/conferences/publishing/templates.html), however, everything is shortened without a comma.
I had to put a comma for your surname to be readable in my article.

**Comment by hagberg** [comment]
I use the IEEEtran bib style and it works fine.  In fact there are even examples for IEEEtran.bst style that don't have commas. e.g.

```
an article in a journal
Note the use of the IEEE_J_EDL string, defined in the IEEEabrv.bib file,
for the journal name. IEEEtran.bst defines the BibTeX standard three
letter month codes per IEEE style.
From the June 2002 issue of "IEEE Transactions on Electron Devices",
page 996, reference #16.
@article{IEEEexample:article_typical,
  author        = "S. Zhang and C. Zhu and J. K. O. Sin and P. K. T. Mok",
  title         = "A Novel Ultrathin Elevated Channel Low-temperature 
                   Poly-{Si} {TFT}",
  journal       = IEEE_J_EDL,
  volume        = "20",
  month         = nov,
  year          = "1999",
  pages         = "569-571"
}
```

**Comment by AgostinoSturaro** [comment]
I tried cleaning up the temp files before recompiling and this it worked without commas.
Thank you.

BTW cited you ;)
