### ISSUE TITLE
Better error message for eccentricity

### ISSUE THREAD

**Issue by joelmiller** [networkx/networkx#1803]
The error message in `eccentricity` from these lines

    if L != order:
        msg = "Graph not connected: infinite path length"
        raise networkx.NetworkXError(msg)

can occur in directed networks if the network is weakly connected but not strongly connected.  This causes confusion as the network is connected, but the error message says it isn't.  I suggest changing to 

     if L != order:
        msg = "Undirected graph not connected or directed graph not strongly-connected: infinite path length"
        raise networkx.NetworkXError(msg)

Here is [an example](http://stackoverflow.com/questions/33114746/find-diameter-of-a-graph-in-networkx/33116490?noredirect=1#comment54048488_33116490) where someone had trouble with this.

**Comment by hagberg** [comment]
It might be more clear if we use different error messages based on whether the graph is directed or not (use the is_directed() method).

**Comment by dschult** [comment]
Fixed in #1820 and #1821
