### ISSUE TITLE
dijkstar path vs path length

### ISSUE THREAD

**Issue by scheung38** [networkx/networkx#1804]
sorry but what is the difference between a function that is:

dijkstar shortest path vs
dijkstar shortest path length 

and which function could one use to get the weight of a specific path
if 
```
A-B is with weight=1.5
B-C is with weight=2.5
```
then
if querying for:
```
A-B-C returns 4
```

**Comment by MridulS** [comment]
`Dijkstra shortest path` returns the shortest <b>path</b> between two nodes and `Dijkstra shortest path length` returns the <b>length</b> between them.
For example:
``` python
In [2]: G = nx.Graph()

In [4]: G.add_edge('A', 'B', weight=1)

In [5]: G.add_edge('B', 'C', weight=2)

In [6]: G.add_edge('A', 'C', weight=5)

In [7]: nx.dijkstra_path(G, 'A', 'B')
Out[7]: ['A', 'B']

In [8]: nx.dijkstra_path(G, 'A', 'C')
Out[8]: ['A', 'B', 'C']

In [9]: nx.dijkstra_path_length(G, 'A', 'C')
Out[9]: 3
```
If you only want the weight of specific path you should use `Dijkstra shortest path length `

**Comment by scheung38** [comment]
Thanks Dijkstra shortest path length? Could you give example, thanks

**Comment by dschult** [comment]
https://networkx.github.io/documentation/latest/reference/algorithms.shortest_paths.html
