### ISSUE TITLE
Wrong doc or behavior for simple_cycles

### ISSUE THREAD

**Issue by nilgoyyou** [networkx/networkx#1808]
On 1.9.1, we can read on simple_cycles' documentation:
Returns:	cycle_generator: generator
A generator that produces elementary cycles of the graph. **Each cycle is a list of nodes with the first and last nodes being the same.** [emphasis added]

I wrote a simple test case and the result doesn't respect the sentence in bold.
```python
>>> import networkx as nx
>>> graph = nx.DiGraph()
>>> graph.add_nodes_from(['A', 'B', 'C'])
>>> graph.add_edges_from({('A', 'B'), ('B', 'C'), ('C', 'A')})
>>> list(nx.simple_cycles(graph))
[['A', 'B', 'C']]
```

I thought the result would be `[['A', 'B', 'C', 'A']]`
I also tested on the latest release 1.10 and I obtain the same result.

**Comment by dschult** [comment]
Thank you!!  ...  I'll get that fixed.  
Looks like it was changed in 1.8 without changing documentation. oops. 

```Each cycle is represented by a list of nodes along the cycle.```
