### ISSUE TITLE
set_node_attributes creates dependency between node attributes

### ISSUE THREAD

**Issue by neverforgit** [networkx/networkx#1818]
I am not sure if this is an issue with the code, or we just need to update the documentation. I was trying to use `set_node_attributes` to initialize all nodes with a empty list for a 'cliques' attribute. I then want to fill in the lists with values appropriate for that node. 

However, it appears each node's 'cliques' attribute is actually pointing at the same list in memory. So when I add a clique to one node, it adds it to every node's 'cliques' list. 

If this behavior is intentional, it would be nice to update the doc to reflect this. 

Thanks everyone for your work on NetworkX. I use it regularly.

**Comment by jfinkels** [comment]
This is not a problem with the code; the calling code has the responsibility of creating a new `list` object for each node. I assume you are doing something like

    G.set_node_attributes('cliques', [])

but intended

    G.set_node_attributes('cliques', {v: [] for v in G})

but the [documentation for `set_node_attributes`][1] already states this behavior:

> If *values* is not a dictionary, then it is treated as a single attribute value that is then applied to every node in *G*.

[1]: networkx.github.io/documentation/development/reference/generated/networkx.classes.function.set_node_attributes.html#networkx.classes.function.set_node_attributes

**Comment by neverforgit** [comment]
I see. This distinction was unclear to me.

**Comment by jfinkels** [comment]
Is there a way the documentation could be clearer? Maybe an example?

**Comment by neverforgit** [comment]
What was unclear to me was that the "single attribute value" is a single object in memory. I would add one sentence to the values description:

"Updates to non-dictionary values will propagate to every node in the graph."

But I think a better suggestion is to simply include another example of how to properly initiate empty lists. The example you gave above is very clear.
