### ISSUE TITLE
Default version on readthedocs?

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#1827]
Should the link http://networkx.readthedocs.org/ link to the "latest" docs (which build off of our master branch) or to the most recent release docs?

BTW readthedocs has a "stable" version that automatically finds the most recent version based on tag and branch names. Unfortunately our branch names like v1.11 appear more recent than our tag names networkx-1.10.  So it thinks v1.11 is the most recent release even though it is not a release yet. We could turn off the stable version on rtd, or we could change our branch names by adding a letter at the end: v1.10a (rtd will ignore those version numbers as a pre-release branch).  I've turned off the stable version on rtd for now.

**Comment by hagberg** [comment]
It still looks a little confusing when you look for versions since there is networkx-1.10 and v1.11 there.

**Comment by dschult** [comment]
I added the v1.11 2 days ago to test that it rendered OK...  I have removed it again now.
Once we create a tagged networkx-1.11 I believe the readthedocs will automatically pick that up. 
But I'm not positive so we should check it.  (it ignores the networkx-1.11rc1 by default).
