### ISSUE TITLE
Minimum Edge Cover

### ISSUE THREAD

**Issue by mortonjt** [networkx/networkx#1831]
I was sifting through the networkx docs and didn't find functionality for [minimum edge cover](https://en.wikipedia.org/wiki/Edge_cover).

Is this functionality available?  If not, would there be any interest in adding this to networkx?

**Comment by nishnik** [comment]
I would like to work on it. 
I think it will be categorized in approximation algorithms.
As I am new, could you please guide me?

**Comment by OrkoHunter** [comment]
Ping @dschult.

**Comment by jfinkels** [comment]
It should be straightforward to do this for both general undirected graphs and for bipartite graphs.

There are already algorithms for finding a maximum matching in a graph (`nx.max_weight_matching(G, maxcardinality=True)`) and for finding a maximum matching in a bipartite graph (`nx.bipartite.maximum_matching(G)`). You can use those matchings to compute an edge cover; see [edge cover algorithms][1] and [bipartite graph properties][2] on Wikipedia.

[1]: https://en.wikipedia.org/wiki/Edge_cover#Algorithms
[2]: https://en.wikipedia.org/wiki/Bipartite_graph#K.C3.B6nig.27s_theorem_and_perfect_graphs

**Comment by mortonjt** [comment]
Right, but what if you want to find the minimum cost edge cover (i.e. the edge cover with the minimum edge weights)?

I believe

**Comment by mortonjt** [comment]
Incomplete comment.  Please ignore

**Comment by mortonjt** [comment]
I don't think minimum edge cover requires an approximation - it should be poly time (as mentioned by @jfinkels).  I realize that it isn't difficult to implement - but it would be a nice function to have if it were available.

**Comment by nishnik** [comment]
Fine! I will try to implement it.
Thank you @jfinkels !

**Comment by jfinkels** [comment]
To be more clear, I was suggesting writing one function for general graphs
and a separate function for bipartite graphs (in the `bipartite` package).

**Comment by jfinkels** [comment]
This feature was added in pull request #1915.
