### ISSUE TITLE
find_cycle() raises NetworkXNoCycle, contrary to doc

### ISSUE THREAD

**Issue by rbcarson** [networkx/networkx#1832]
The [doc for find_cycle() says](https://networkx.github.io/documentation/latest/reference/generated/networkx.algorithms.cycles.find_cycle.html#networkx.algorithms.cycles.find_cycle)

> edges – A list of directed edges indicating the path taken for the loop. If no cycle is found, then edges will be an empty list.

But the following snippet raises NetworkXNoCycle:
```python
import networkx
from networkx.algorithms.cycles import find_cycle
G = networkx.DiGraph([(0,1), (1,2)])
find_cycle(G)
```

I'm using networkx 1.10.

**Comment by SanketDG** [comment]
Yup, looks like no changes were made to the docs in d053488b1331e6f0205fafe4db198f6a815816fe where `NetworkXNoCycle` was implemented.

**Comment by rbcarson** [comment]
I've proposed #1834 to fix this.
