### ISSUE TITLE
Failed to 'pip install' on Mac OS X El Capitan

### ISSUE THREAD

**Issue by BastiPaeltz** [networkx/networkx#1833]
Installing networkx via pip on Mac OS X El Capitan does not work because of SIP, which makes the directory /System not writable.  
Output:
...
...
 running install_data
    creating /System/Library/Frameworks/Python.framework/Versions/2.7/share
    error: could not create '/System/Library/Frameworks/Python.framework/Versions/2.7/share': Operation not permitted

Command "/usr/bin/python -c "import setuptools, tokenize;__file__='/private/tmp/
pip-build-KaS_Ne/networkx/setup.py';exec(compile(getattr(tokenize, 'open', open)
(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-2O8kAW-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-KaS_Ne/networkx

**Comment by MridulS** [comment]
http://apple.stackexchange.com/questions/209572/how-to-use-pip-after-the-el-capitan-max-os-x-upgrade

**Comment by BastiPaeltz** [comment]
Thanks, so it is not a network related problem I guess. I will try the suggested solution.
