### ISSUE TITLE
BUG: network simplex algorithm cannot handle floating points

### ISSUE THREAD

**Issue by mortonjt** [networkx/networkx#1846]
I've been messing around with the networkx simplex algorithm and just realized that it cannot handle floating points.  Below is an example.

```python
>>> import networkx as nx
>>> G = nx.Graph()
>>> G.add_nodes_from(['i', 'j', 'k', 'l'])
>>> G.node['i']['demand'] = -1
>>> G.node['j']['demand'] = 1. / 3
>>> G.node['k']['demand'] = 1. / 3
>>> G.node['l']['demand'] = 1. / 3
>>> G.add_edge('i','j', {'weight': 1})
>>> G.add_edge('j','k', {'weight': 11})
>>> G.add_edge('k','l', {'weight': 21})
>>> nx.network_simplex(G.to_directed())
NetworkXUnfeasible: total node demand is not zero
```
And this is silly, because the sum of the demands is clearly zero.
But if you actually sum up the demands, there is some floating point rounding errors occurring

```python
>>> -1 + 1. / 3 + 1. / 3 + 1. / 3
-1.1102230246251565e-16
```

Is it possible to modify the algorithm to handle these sorts of floating point errors?
If not, mind if I submit a PR to throw an exception, stating that this algorithm can only handle integer demands?  This could really save users time debugging.

**Comment by jfinkels** [comment]
Could change [this line][1] from `if sum(D) != 0:` to `if abs(sum(D)) < tolerance:`, where tolerance is a small positive floating point number. 

[1]: https://github.com/networkx/networkx/blob/master/networkx/algorithms/flow/networksimplex.py#L239
