### ISSUE TITLE
copy node and graph data in create_empty_copy()

### ISSUE THREAD

**Issue by varun-kr** [networkx/networkx#1849]
Why is there no option to copy node and graph data to the new graph? . I think it would be better if create_empty_copy() takes copy_data as a boolean parameter . 
If it sounds a good feature then I can do a PR.

**Comment by hagberg** [comment]
You are probably looking for the `copy()` method of the graph classes.
http://networkx.readthedocs.org/en/latest/reference/generated/networkx.Graph.copy.html

**Comment by varun-kr** [comment]
I want to keep only node data and do not need edges. Can I achieve this goal using copy() ?
Thanks

**Comment by hagberg** [comment]
Oh, I see what you want to do.  I don't think there is a function to do that.  You could call the copy() method and remove the edges but that isn't so efficient.  

In looking at the create_empty_copy() function I'm not sure why we aren't adding a way to copy the data so you proposal make sense.  Also I'm not sure why we have the option to add the nodes.  Do we really need that?

**Comment by varun-kr** [comment]
I needed such functionality in two cases. First, when I was doing some dependency parsing and I wanted a graph which has the same nodes and data as the old one but without edges. Second, while analyzing online communities for edge prediction given the node data.  In both cases, I needed a graph with same nodes and data except the edges. So I think it might be useful .

**Comment by hagberg** [comment]
Yes, I agree with you.  

We might consider removing the with_nodes= argument too unless we can remember or figure out why that is useful.

**Comment by dschult** [comment]
I agree. And I can't see why anyone would need the with_nodes=False option. Not sure why we put it in there.

The documentation should also "see also" the empty_graph function.

So: 
- remove with_nodes argument
- add a with_data argument   ??default value??  I would guess "True"... other opinions?
- add a "see also" in the doc_string
- update tests accordingly (There is only one test function now besides the test of the doc_string.)

**Comment by varun-kr** [comment]
May I do a PR for this ?

**Comment by dschult** [comment]
Yes, please. :)

**Comment by varun-kr** [comment]
Should we add two separate boolean parameters for graph data and node data ?

create_empty_copy(G, with_graph_data=True, with_node_data=True)
or 
create_empty_copy(G, with_data=True)

**Comment by dschult** [comment]
Which do you think is better. I like the simplicity of with_data, but the flexibility is also nice.
How likely is it for someone to want node data without graph data? 

I'm open to suggestion, but have slight preference for ```with_data```

**Comment by varun-kr** [comment]
I agree with you . I can not think of a use case when one needs node data without graph data.
