### ISSUE TITLE
How to find example of path that achieves diameter?

### ISSUE THREAD

**Issue by hickford** [networkx/networkx#1855]
I calculated the diameter of my graph using the diameter function. How can I find an example of a pair of points that are diameter apart and a path between them?

http://networkx.github.io/documentation/latest/reference/generated/networkx.algorithms.distance_measures.diameter.html#networkx.algorithms.distance_measures.diameter

**Comment by dschult** [comment]
This question might be better placed on the [networkx-discuss email list](https://groups.google.com/forum/#!forum/networkx-discuss) to get a wider audience.

The green ```source``` link on the page you cite shows you the code for diameter and friends. But I suspect you will want to compute using [```all_pairs_shortest_path```](http://networkx.github.io/documentation/latest/reference/generated/networkx.algorithms.shortest_paths.unweighted.all_pairs_shortest_path.html#networkx.algorithms.shortest_paths.unweighted.all_pairs_shortest_path)

You would have to compute the maximum path length using your own code, but the path would be there when you find the maximum.
