### ISSUE TITLE
Girvan Newman community detection not defined

### ISSUE THREAD

**Issue by gg4u** [networkx/networkx#1863]
Hi guys!
I want to undertand better community detection algorithms, I would like to try girvan newman on my data structure.

I read that is implemented in nx:
http://networkx.readthedocs.org/en/latest/reference/generated/networkx.algorithms.community.centrality.girvan_newman.html

But I found now way to run it:

>>> g = nx.path_graph(10)
>>> comp = girvan_newman(g)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
NameError: name 'girvan_newman' is not defined

(Instead, nx.k_clique_communities() is working)

Could you please debrief?
Here running latest version 1.10.

Thank you!

**Comment by SanketDG** [comment]
The documentation in the link is a little bit unclear. It needs to be fixed. You have to use the `girvan_newman` as part of the networkx package (which you previously imported as `nx`). So:

```python
>>> import networkx as nx
>>> G = nx.path_graph(10)
>>> comp = nx.girvan_newman(G)
>>> comp
[([0, 1, 2, 3, 4], [8, 9, 5, 6, 7]), ([0, 1], [2], [3, 4], [5, 6], [7], [8, 9]), ([0], [1], [2], [3], [4], [5], [6], [7], [8], [9])]
>>> 
```

**Comment by gg4u** [comment]
Sure, I did it. But got that message.

>>> import networkx as nx
>>> 
>>> nx.path_graph(10)
<networkx.classes.graph.Graph object at 0x10e073a50>
>>> 
>>> nx.girvan_newman(G)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'girvan_newman'
>>>

**Comment by SanketDG** [comment]
Looks like `girvan_newman` was added recently, and isn't on pypi yet. You are welcome to upgrade to the latest master branch:

```
pip install git+https://github.com/networkx/networkx.git --upgrade
```

then you can easily use `girvan_newman`

**Comment by gg4u** [comment]
it worked, thanks!

**Comment by SanketDG** [comment]
> How to eventually downgrade to official dist ?

I am not sure, what you mean by this. NetworkX has a new iterator-based [api](http://networkx.readthedocs.org/en/latest/reference/release_2.0.html#api-changes), which works on both Python2 and Python3.

An [iterator](http://www.diveintopython3.net/iterators.html) just throws values sequentially until there are no more values left. For your case, casting `G.nodes()` into a list works just fine:

```python
len(list(G.nodes()))
```

**Comment by gg4u** [comment]
I mean that there are a little differences respect to previous version 1.10 (I have it stil live on one terminal, for test against the new one upgraded):

g.nodes() was returning by itself a list:
like this:
>>> G.nodes()
[1, 2, 3, 'spam']

see in doc:
https://networkx.github.io/documentation/latest/tutorial/tutorial.html#nodes

Maybe the tutorial should be updated because there are here and there mismatching examples.
However thanks for the hint!

**Comment by SanketDG** [comment]
> g.nodes() was returning by itself a list

Yes, but that is only upto `v1.*`
In NetworkX `v2.0`, everything will be iterator-based.



> Maybe the tutorial should be updated because there are here and there mismatching examples.
> However thanks for the hint!

The tutorials have been updated at the right places. What you were seeing is documentation of `v1.10`. Since, you are using the development branch, you should refer to the development docs [here](http://networkx.github.io/documentation/development/index.html) and [here](http://networkx.readthedocs.org/en/latest/index.html)

**Comment by gg4u** [comment]
Gotcha! Thank you very much Sanket.

**Comment by dschult** [comment]
Also, ```len(g)``` is the best way to calculate how many nodes are in ```g```. ```len(list(g.nodes()))``` is not the best way--though it does explain the iterator nature of g.nodes().
