### ISSUE TITLE
Getting node data in iterator behaves differently from getting edge data in iterator

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#1864]
I know that `G.edges(data='foo')` returns an iterator over tuples that include the value of the `'foo'` edge attribute instead of the full edge attribute dictionary. I would expect `G.nodes(data='foo')` to behave the same way, but instead it returns an iterator over tuples that include the full node data dictionary.

**Comment by hagberg** [comment]
I like that suggestion; it makes sense to be consistent.  Anyone want to do the implementation?

**Comment by MridulS** [comment]
on it :)

**Comment by MridulS** [comment]
https://github.com/networkx/networkx/pull/1884

**Comment by MridulS** [comment]
This can be closed now, fixed in https://github.com/networkx/networkx/pull/1884
