### ISSUE TITLE
Python 2 graphviz layout throws exception if node labels contain quotation marks.

### ISSUE THREAD

**Issue by sergeny** [networkx/networkx#1872]
This works:
```
import networkx as nx
G = nx.Graph()
G.add_nodes_from(["first", 'second'])
nx.draw_graphviz(G, node_size=1000, with_labels=True, arrows=True)
```

This doesn't:
```
import networkx as nx
G = nx.Graph()
G.add_nodes_from(["first", 'sec"ond'])
nx.draw_graphviz(G, node_size=1000, with_labels=True, arrows=True)
```

It might be a pydot issue, not sure. 
Ubuntu 15.10.
anaconda                  2.4.0               np110py27_0    defaults
matplotlib                1.4.3               np110py27_2    defaults
networkx                  1.10                     py27_0    defaults
python                    2.7.11                        0    defaults
pydot                     1.0.28                   py27_0    defaults

Error message:
---------------------------------------------------------------------------
InvocationException                       Traceback (most recent call last)
<ipython-input-37-4dda3c0f7738> in <module>()
      2 G = nx.Graph()
      3 G.add_nodes_from(["first", 'sec"ond'])
----> 4 nx.draw_graphviz(G, node_size=1000, with_labels=True, arrows=True)

/home/.../anaconda2/lib/python2.7/site-packages/networkx/drawing/nx_pylab.pyc in draw_graphviz(G, prog, **kwargs)
    980        See networkx.draw_networkx() for a description of optional keywords.
    981     """
--> 982     pos = nx.drawing.graphviz_layout(G, prog)
    983     draw(G, pos, **kwargs)
    984 

/home/.../anaconda2/lib/python2.7/site-packages/networkx/drawing/nx_pydot.pyc in graphviz_layout(G, prog, root, **kwds)
    255     This is a wrapper for pydot_layout.
    256     """
--> 257     return pydot_layout(G=G,prog=prog,root=root,**kwds)
    258 
    259 

/home/.../anaconda2/lib/python2.7/site-packages/networkx/drawing/nx_pydot.pyc in pydot_layout(G, prog, root, **kwds)
    275         P.set("root",make_str(root))
    276 
--> 277     D=P.create_dot(prog=prog)
    278 
    279     if D=="":  # no data returned

/home/.../anaconda2/lib/python2.7/site-packages/pydot.pyc in <lambda>(f, prog)
   1800             self.__setattr__(
   1801                 'create_'+frmt,
-> 1802                 lambda f=frmt, prog=self.prog : self.create(format=f, prog=prog))
   1803             f = self.__dict__['create_'+frmt]
   1804             f.__doc__ = '''Refer to the docstring accompanying the 'create' method for more information.'''

/home/.../anaconda2/lib/python2.7/site-packages/pydot.pyc in create(self, prog, format)
   2021             raise InvocationException(
   2022                 'Program terminated with status: %d. stderr follows: %s' % (
-> 2023                     status, stderr_output) )
   2024         elif stderr_output:
   2025             print stderr_output

InvocationException: Program terminated with status: 1. stderr follows: Error: /tmp/tmpPnQQec: syntax error in line 2 near ''

**Comment by SanketDG** [comment]
Can't you just escape that double quote:

```python
import networkx as nx
G = nx.Graph()
G.add_nodes_from(["first", 'sec\"ond'])
nx.draw_graphviz(G, node_size=1000, with_labels=True, arrows=True)
```

**Comment by hagberg** [comment]
I think this is a pydot bug (works correctly with pygraphviz).

```python
In [1]: import pydot

In [2]: n = pydot.Node('foo"bar')

In [3]: P = pydot.Dot()

In [4]: P.add_node(n)

In [5]: print(P.to_string())
digraph G {
foo"bar;
}


In [6]: P.create_dot()
Warning: /tmp/tmp6RkNEi: syntax error in line 2 near ''

Out[6]: ''

In [7]: pydot.needs_quotes('foo"bar')
Out[7]: False

In [8]: pydot.needs_quotes('foo\nbar')
Out[8]: True
```

**Comment by hagberg** [comment]
I'm going to close this since there isn't a simple networkx workaround that I can see.   This does work correctly with pygraphviz so I suggest using that if you can.
