### ISSUE TITLE
all_node_cuts returns too few and incorrect cuts.

### ISSUE THREAD

**Issue by chrisjcameron** [networkx/networkx#1875]
This could be a documentation issue, a bug or a user understanding issue. Are these cases pathological for the algorithm?

Given a square graph:

     a -- b
     |    |
     c -- d

Based on a cursory reading of the documentation, I would have expected all_node_cuts() to return:

    [{'a','d'}, {'c','b'}]

I get `[{'a','c'}]` but if this is a valid node cut then surely {a,b}, {b,d}, {c,d} are also equally valid and a function called "all node cuts" should return them. 

    G = nx.Graph([('a','b'), ('a','c'), ('c','d'), ('b','d')])
    print( G.nodes() )
    print( G.edges() )
    print( list(nx.all_node_cuts(G)) )

    >>> ['a', 'c', 'b', 'd']
    >>> [('a', 'c'), ('a', 'b'), ('c', 'd'), ('b', 'd')]
    >>> [{'a', 'c'}]

Expanding to a hexagon, we see similar pattern of node cuts. There are many isometric node cuts omitted from the results list. Two of the proposed cuts fail to create "two or more connected components" as the documentation suggests.

    G = nx.Graph([('a','b'), ('b','c'), ('c','d'),('d','e'), ('e','f'),('f','a')])
    list(nx.all_node_cuts(G))
    >>> [{'a', 'c'}, {'a', 'b'}, {'b', 'c'}]

**Comment by karrtikr** [comment]
It seems to me like a bug. As you said many isometric node cuts are being omitted and in these polygon cases some of the node cuts mentioned in the result fail to create "two or more connected components". 

I tried some more graphs and I think maybe it has got issues handling graphs with all vertices having the same degree. For eg,

<pre>
K_5=nx.complete_graph(5)
list(nx.all_node_cuts(K_5))
>>> [{0, 1, 2, 3}]
</pre>

but should actually also return all other isometric node cuts.

Did you noticed any other pattern of graphs for which <code>all_node_cuts</code> gives incorrect results?

**Comment by chrisjcameron** [comment]
I did not test additional network configurations and filed this report on behalf of another user who was trying to understand the output. After testing their example and the hexagon network, I suspected that there was either an documentation issue or a algorithm issue. It may be the network does not conform to the scope of the algorithm and the right fix is to simple raise an error and add to the documentation.

**Comment by jtorrents** [comment]
Sorry for the late reply, and thanks for looking at this! Indeed this is a bug. I think I've fixed it in the PR referenced above. Instead of trying to handle these corner cases in the implementation of Kanevsky's algorithm, the PR handles them separately. See #1976 for details. With that PR merged:

```python
In [6]: G = nx.cycle_graph(4)

In [7]: list(nx.all_node_cuts(G))
Out[7]: [{0, 2}, {1, 3}]

In [8]: list(nx.all_node_cuts(G))
Out[8]: [{0, 2}, {1, 3}]

In [9]: G = nx.cycle_graph(6)

In [10]: list(nx.all_node_cuts(G))
Out[10]: [{0, 2}, {0, 3}, {0, 4}, {1, 3}, {1, 4}, {1, 5}, {2, 4}, {2, 5}, {3, 5}]

In [11]: G = nx.complete_graph(5)

In [12]: list(nx.all_node_cuts(G))
Out[12]: [{0, 1, 2, 3}, {0, 1, 2, 4}, {0, 1, 3, 4}, {0, 2, 3, 4}, {1, 2, 3, 4}]

In [13]: G = nx.complete_graph(6)

In [14]: list(nx.all_node_cuts(G))
Out[14]: 
[{0, 1, 2, 3, 4},
 {0, 1, 2, 3, 5},
 {0, 1, 2, 4, 5},
 {0, 1, 3, 4, 5},
 {0, 2, 3, 4, 5},
 {1, 2, 3, 4, 5}]
```
