### ISSUE TITLE
Method write_graphml removes json escaping

### ISSUE THREAD

**Issue by AlexeyShaykov** [networkx/networkx#1880]
Have a nice day.
My problem: when I write an attribute in the graphml disappears json escape
NetworkX 1.9.1

``` python
import json
import networkx as nx

a = dict(a='{"a":"123"}')
x = json.dumps(a)
# >>> {"a": "{\"a\":\"123\"}"}

g = nx.Graph()
g.graph['test'] = x
nx.write_graphml(g, '/tmp/text.graphml')
```

`text.graphml`

``` xml
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
  <key attr.name="test" attr.type="string" for="graph" id="d0" />
  <graph edgedefault="undirected">
    <data key="d0">{"a": "{"a":"123"}"}</data>
  </graph>
</graphml>
```

**Comment by hagberg** [comment]
I'd say that is a bug.  A workaround is to use 

```python
x = unicode(json.dumps(a))
```
for python2 (it works correctly with Python3).

The issue comes up because of the 'unicode_escape' in https://github.com/networkx/networkx/blame/master/networkx/utils/misc.py#L104

@chebee7i can you comment on why that is there and what the best solution is here?

**Comment by AlexeyShaykov** [comment]
Hi. 
Thanks for the answer. This simple solution x = unicode(json.dumps(a)) helped me.

**Comment by hagberg** [comment]
Not sure if this requires a fix or not - @chebee7i do you have an opinion?

**Comment by dschult** [comment]
After a lot of searching and playing with possible solutions, it looks like @hagberg solution is the best one:  make sure that strings you want protected are already unicode when they enter the ```write_graphml``` function.  This is probably good practice for Python2 code with many libraries.

It is possible that a better way exists for this, but the python3 code works very well and this working solution seems sufficient.  I'm going to close this and put a comment in the docstring as part of #2515
