### ISSUE TITLE
Remove add_path, add_cycle, add_star

### ISSUE THREAD

**Issue by hagberg** [networkx/networkx#1883]
Remove from base classes and consider putting in as functions along with add_clique? #1562

**Comment by karrtikr** [comment]
@hagberg I can't find the add_clique function, so I'm not sure where to put these functions after removing them from the base classes. If there is no add_clique function, where should we put add_path, add_cycle and add_star?

**Comment by hagberg** [comment]
There is no add_clique function and as you can see in #1562 we didn't agree on what it should do exactly for directed graphs.  Maybe we shouldn't add it?  And just remove add_path, add_star, add_cycle?

**Comment by karrtikr** [comment]
@hagberg I think as the functionality of add_clique is not clear for directed graphs , maybe we should not add it then.
But are we supposed to totally remove add_path, add_cycle, and add_star from base classes and not put it anywhere? If not, where do we need to put these functions?

**Comment by dschult** [comment]
If we are to get rid of add_path we will have to change quite a few tests and doc_strings.
It seems that is a common way to make a simple connected graph.  @hagberg what is your suggested replacement for quickly adding a bunch of connected nodes.  Something like 
```G.add_edges_from(zip(nlist[:-1], nlist[1:]))```. But that's a little cumbersome.  Another way?

add_star and add_cycle are used less in tests and doc_strings, but they are used. Suggestions for replacement idioms?

We could also move them from the base classes to the function.py module, but I think if we want them gone we should do it in a way that we don't have to fix again later.

**Comment by MridulS** [comment]
I think we shouldn't completely remove `add_path`, `add_cycle`, `add_star`. The alternates like `G.add_edges_from(zip(nlist[:-1], nlist[1:]))` are not easy to get right for beginners, and is used at various places in doctests.

They should definitely be removed from the core graph classes and moved to someplace like `function.py` as suggested by @dschult or maybe some file like `algorithms/add_structure.py`.

**Comment by jfinkels** [comment]
@dschult wrote:

> Something like `G.add_edges_from(zip(nlist[:-1], nlist[1:]))`.

Or `G.add_edges_from(nx.utils.pairwise(nodes))`.

> add_star and add_cycle are used less in tests and doc_strings, but they are used. Suggestions for replacement idioms?

My suggestions are `G.add_edges_from((r, v) for v in leaves)` and `G.add_edges_from(pairwise(nodes, cycle=True))`, assuming we add the `cycle` keyword argument to pairwise.

**Comment by hagberg** [comment]
Should we add some functions like `make_path(nodes)`?  Or overload `path_graph(nodes)` to accept an iterable?  Then you get `G.add_edges_from(path_graph(nodes))` etc.  
  I don't have any strong preference here but this is the 2.0 opportunity to make an adjustment like this in the graph class interface.

**Comment by jfinkels** [comment]
@hagberg wrote:

> Should we add some functions like `make_path(nodes)`?

This seems reasonable to me. It would essentially just be a convenience function for the expression `pairwise(nodes)`. However, it has the benefit that its name indicates its function in graph theoretic terms, instead of the more generic `pairwise`.

> Or overload `path_graph(nodes)` to accept an iterable?  Then you get `G.add_edges_from(path_graph(nodes))` etc.

I don't think this is a good idea, since none of the other functions in the `generators` package accept a list of nodes as input. If I learned that `path_graph` accepted a list of nodes, I might expect `cycle_graph`, `complete_graph`, `grid_graph`, etc. to accept a list of nodes.

**Comment by dschult** [comment]
@jfinkels wrote:

>If I learned that path_graph accepted a list of nodes, I might expect cycle_graph, complete_graph, grid_graph, etc. to accept a list of nodes.

The other functions in the generators package could also accept either a list of nodes or a number of nodes. I think a decorator could make this reasonable to implement (though a fair amount of work). 

    @arg_is_nodes_or_number([0,1])
    def grid_2d_graph(m1, m2, ...):
        # If m1 and m2 are numbers they become range(m) via the decorator
        ...

I think it would be a good feature to add.  e.g. ```grid_2d_graph(range(4,7), range(15,18))```.
There aren't too many functions we'd want this feature for.

    empty_graph
    complete_graph
    path_graph
    cycle_graph
    star_graph
    wheel_graph
    grid_2d_graph
    random_geometric_graph
    geographical_threshold_graph
    waxman_graph
    ?? grid_graph
    ?? lollipop_graph
    ?? complete_multipartite_graph
    ?? random_partition_graph

**Comment by dschult** [comment]
See #1913 for overloading path_graph
See #1905 for extending pairwise to cycles.

**Comment by dschult** [comment]
Should we name the new function ```nx.add_path(G, [2,3,4])``` or ```nx.make_path(G, [2,3,4])``` or something else?

**Comment by jfinkels** [comment]
I like `add_path`, but will it always "add" edges? For example, if a (simple) graph already has edges (2, 3) and (3, 4)? Not sure if that's much of a problem (but it should be documented).

**Comment by hagberg** [comment]
add_path() is good
this needs a PR

**Comment by dschult** [comment]
See #1970
