### ISSUE TITLE
Node and Edge Views

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#1896]
Now that we have iterators for `G.nodes` and `G.edges` we can reflect a little on the API change before we release it. I like the change so far but miss a few features of the old system and wonder if new users will miss them too.

**feature 1**: `__str__` for edges and nodes
If I'm just playing around with a small Graph to see what works I will often print the nodes and edges to make sure I know what it is. When I `print(G.edges())` I don't get the edges. I have to `print(list(G.edges()))`. I can handle that and I will adapt... but new users might have trouble "looking" at their graph. 

**feature 2**: re-useable result from G.edges
When I try `es=G.edges()`, sometimes I'd like to iterate through them more than once and I can't use `es` for that unless I use `es=list(G.edges())`. I can of course use `G.edges()` again, but...?@! 

**Views**
Running up against this second trouble reminded me of Python3 dictviews. I also remembered @hagberg lobbying for subgraph-views long ago.  Views are low cost objects that allow multiple iterators to be generated from them, update contents when the graph updates, allow nice printing, allow `__contains__`, and many set-like operations. 

I have created a [gist](https://gist.github.com/dschult/37c28fa27b613be64d4f)  with one attempt at `NodesViews` and `EdgesViews`.

**What do people think about using NodesViews and EdgesViews to enrich `G.nodes()` and `G.edges()`?**

Example:

```
>>> G=nx.path_graph(9)
>>> nv=G.nodes()
>>> ev=G.edges()
>>> print("nodes:", nv)
nodes: [0, 1, 2, 3, 4, 5, 6, 7, 8]
>>> print("edges:", ev)
edges: [(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8)]
>>> G.remove_edge(7,8)
>>> print("edges:", ev)
edges: [(0, 1), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7)]
>>> for e in G.edges(data=True):
...     print(e)
(0, 1, {})
(1, 2, {})
(2, 3, {})
(3, 4, {})
(4, 5, {})
(5, 6, {})
(6, 7, {})
```

I think @MridulS has already done the hard work of making these methods generators and finding how that affects our codebase. This suggestion should be relatively easy compared to that because the change will only involve the class methods themselves. @MridulS already found all the places where iterators cause trouble. Changing the iterators to views only adds features so he coding impact should be smaller. 

If there is interest I will try to put together a PR.

**Comment by jfinkels** [comment]
This seems like a good idea to me, mirroring the behavior of `dict.items()`, etc. in Python 3.

**Comment by hagberg** [comment]
Looks nifty.  Why not make a PR so we can play with it?

**Comment by hagberg** [comment]
Feature in network-2.0
