### ISSUE TITLE
Font-Size dynamic

### ISSUE THREAD

**Issue by kalloc** [networkx/networkx#1904]
Hi!

I wish using degree to set font_size.

Example code:

```
import networkx as nx
import numpy as np


D = np.random.randn(10, 10) * 10
D[D < 5] = 0
D[D != 0] = 1

g = nx.from_numpy_matrix(D)
pos=nx.fruchterman_reingold_layout(g, weight=10)
labels = dict([(item, item) for item in g.nodes()])
font_sizes = g.degree()
nx.draw_networkx_nodes(g, pos)
nx.draw_networkx_labels(g, pos, labels=labels, font_size=font_sizes)
```

Can I create pull-request with adding dict type for font_size?

**Comment by dschult** [comment]
We certainly wont discourage a pull request. I don't know of any reasons this would not work. If you get it working for node labels the update for edge labels would be similar.
:)

**Comment by hagberg** [comment]
Closed due to inactivity.
