### ISSUE TITLE
G.name incorrect in some graph generators

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#1906]
I have found that a few graphs have an incorrect `G.name` property. e.g. (I didn't look hard--there may be others)

```
>>> B=nx.balanced_tree(3,3)
>>> print(B.name)   # empty_graph is used to start the construction
empty_graph(40)
>>> G=nx.caveman_graph(3,3)
>>> print(G.name)   # parameter arguments are not correct
cavemen_graph(9, 3)
```

It seems that G.name is trying to play the role of `__repr__` in some cases. Perhaps that is too hard to keep correct over the years.  Also if we start allowing `path_graph(nodes)` the name could become cumbersome for long lists `nodes`.

Do people use the G.name property? Would the name without parameters be enough? What is the best way forward for maintaining the name property?

**Comment by hagberg** [comment]
I'd like to keep some way to attach a string label or identification to a graph e.g. to implement https://github.com/networkx/networkx/issues/1373 
It could be that Graph.graph would work too.

**Comment by Michael-E-Rose** [comment]
As for the question: I use the name, but it was long useless as the name wasn't written to `.gexf` files (and hence not ported). PR #2010 changed that (but will only take effect in networkx-2.0). However, I think that the name without parameters is enough. It's very easy to change the name if people create more than one generated graph of the same type (which is the only case when a name is needed to discriminate based on the name).

**Comment by dschult** [comment]
I agree that G.name is an easy identifier.

What about removing the *setting* of that attribute in the graph generator routines? So people can use the name feature, but it doesn't get set in confusing ways by our generators (like with nx.balanced_tree called an empty_graph and nx.caveman_graph having the wrong input values).

**Comment by hagberg** [comment]
I'm for not setting (against setting?) the defaults in the generators.
