### ISSUE TITLE
Pickle problem for low memory graph

### ISSUE THREAD

**Issue by huxuan** [networkx/networkx#1907]
Code snippet to reproduce the problem.
```python
import networkx as nx

class ThinGraph(nx.Graph):
    """Copied from docs"""
    all_edge_dict={'weight': 1}
    def single_edge_dict(self):
        return self.all_edge_dict
    edge_attr_dict_factory = single_edge_dict

def main():
    graph = ThinGraph()
    graph.add_edge(1, 2)
    nx.write_gpickle(graph, 'test.gpickle')


if __name__ == '__main__':
    main()
```
with the traceback as following
```
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    main()
  File "test.py", line 12, in main
    nx.write_gpickle(graph, 'test.gpickle')
  File "<decorator-gen-172>", line 2, in write_gpickle
  File "/lib/python2.7/site-packages/networkx/utils/decorators.py", line 220, in _open_file
    result = func(*new_args, **kwargs)
  File "/lib/python2.7/site-packages/networkx/readwrite/gpickle.py", line 70, in write_gpickle
    pickle.dump(G, path, protocol)
cPickle.PicklingError: Can't pickle <type 'instancemethod'>: attribute lookup __builtin__.instancemethod failed
```
Any ideas about how to solve this problem?

**Comment by francis-liberty** [comment]
Just tried it on my Mac EI Caption. Same error here.

**Comment by dschult** [comment]
Pickle doesn't seem to work with instancemethods. Something about infinitely recursive inspection. Here is a [discussion on stackoverflow](http://stackoverflow.com/questions/1816958/cant-pickle-type-instancemethod-when-using-pythons-multiprocessing-pool-ma) which points to a fix. 

The [fix involves creating a simple handler](https://bytes.com/topic/python/answers/552476-why-cant-you-pickle-instancemethods#edit2155350) and registering it using copy_reg. I can't verify that this is a complete fix, but it works for me.

    def pm(f):
         func_name=f.im_func.__name__
         obj=f.im_self
         cls=f.im_class
         return upm, (func_name, obj, cls)
 
    def upm(fn,obj,cls):
        for c in cls.mro():
            try:
                func=c.__dict__[fn]
            except KeyError:
                pass
            else:
                break
            return func.__get__(obj,cls)
    import copy_reg
    import types
    copy_reg.pickle(types.MethodType, pm, upm)

    # now pickle should work
    nx.write_gpickle(graph, 'test.gpickle')

**Comment by huxuan** [comment]
@dschult Thanks, this seems to work for me, too.
