### ISSUE TITLE
triadic census (migrated from Trac #190)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#191]
Original ticket https://networkx.lanl.gov/trac/ticket/190
Reported 2008-11-24 by @hagberg, assigned to @hagberg.

Triadic Cencus (triads) is a way for looking for motifs in a directed graph.
Commonly there are 16 motifs defined:
http://www.educa.fmf.uni-lj.si/datana/pub/networks/pajek/triade.pdf
the interface of JUNG is:
http://jung.sourceforge.net/doc/api/edu/uci/ics/jung/algorithms/metrics/TriadicCensus.html

**Comment by jfinkels** [comment]
Implemented in #1474.
