### ISSUE TITLE
Add structural holes measure (migrated from Trac #191)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#192]
Original ticket https://networkx.lanl.gov/trac/ticket/191
Reported 2008-11-24 by @hagberg, assigned to @hagberg.

Structural holes:
http://jung.sourceforge.net/doc/api/edu/uci/ics/jung/algorithms/metrics/StructuralHoles.html

**Comment by dschult** [comment]
Fixed by #2378
