### ISSUE TITLE
Unexpected behaviour of eppstein_matching

### ISSUE THREAD

**Issue by nishnik** [networkx/networkx#1927]
I saved this code as test.py:
```python
import networkx as nx
import networkx.algorithms.bipartite as bipartite
G = nx.Graph()
G.add_nodes_from([1, 2, 3, 4], bipartite=0)
G.add_nodes_from(['a', 'b', 'c'], bipartite=1)
G.add_edges_from([(1, 'a'), (1, 'b'), (2, 'b'), (2, 'c'), (3, 'c'), (4, 'a')]
print ("eppstein: ")
print (bipartite.eppstein_matching(G))
print ("hopcroft karp: ")
print (bipartite.hopcroft_karp_matching(G))
```
Sometimes it gives the right results:
```python
$ python3 test.py #right result 
eppstein: 
{1: 'b', 2: 'c', 4: 'a', 'b': 1, 'c': 2, 'a': 4}
hopcroft karp: 
{1: 'b', 2: 'c', 4: 'a', 'b': 1, 'c': 2, 'a': 4}
```
But sometimes, it gives the wrong results:
```python
$ python3 test.py #wrong result
eppstein: 
{'c': 3, 2: 'c', 4: 'a', 1: 'b', 'a': 1, 'b': 2}
hopcroft karp: 
{1: 'a', 2: 'b', 3: 'c', 'b': 2, 'a': 1, 'c': 3}
```

`hopcroft_karp` works perfectly fine.

**Comment by jfinkels** [comment]
That's probably on me, I introduced that function in pull request #1322. I modified the code from [PADS][1]; you can see a copy of the original PADS code on GitHub here at [jfinkels/pads][2]. Would you mind running your test with the original bipartite matching code from PADS to make sure there is no error in that code?

[1]: http://www.ics.uci.edu/~eppstein/PADS/
[2]: https://github.com/jfinkels/PADS/blob/master/pads/bipartite_matching.py

**Comment by nishnik** [comment]
It works fine and gives the result:
`{'a': 1, 1: 'a', 'c': 3, 'b': 2, 2: 'b', 3: 'c'}`
And it gives the same result every time.

**Comment by nishnik** [comment]
I did this change in [jfinkels/pads](https://github.com/jfinkels/PADS/blob/master/pads/bipartite_matching.py) at the start of function `matching` (PADS function) \:
`matching = {}`
`"""`
`for u in graph:`
`    for v in graph[u]:`
`        if v not in matching:`
`            matching[v] = u`
`            break`
`print ("init matching")`
`print matching`
`"""`
`matching['a'] = 1`
`matching[1] = 'a'`
`matching['c'] = 2`
`matching[2] = 'c'`

It gave the result:
`{'a': 4, 1: 'a', 'c': 2, 3: 'c', 2: 'b', 'b': 1}`

And test.py sometimes gives the same result:
`eppstein: `
`{'a': 4, 1: 'a', 'c': 2, 3: 'c', 2: 'b', 'b': 1}`
`hopcroft karp: `
`{'a': 4, 1: 'b', 'c': 2, 'b': 1, 4: 'a', 2: 'c'}`

I got those specific values for initializing `matching`(variable) after tweaking with `eppstein`(networkx function) \:
`matching = {}`
`for u in G:`
`    for v in G[u]:`
`        if v not in matching:`
`            matching[v] = u`
`            break`
`print matching`

So, I think there is a problem with the greedy matching.
