### ISSUE TITLE
Allow G.edges(keys=True) in non-multigraphs?

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#1934]
There are many places in the code where we have

```
if G.is_multigraph():
    edges = G.edges(keys=True)
else:
    edges = G.edges()
```

It would be simpler to just allow the `Graph.edges()` method to have a keyword argument `keys` and just ignore it (or have `**kw`).

**Comment by dschult** [comment]
We did have it that way in some iteration.....
Anyone recall why we didn't make the Graph and MultiGraph method arguments
match?

**Comment by hagberg** [comment]
I don't recall exactly why we did it that way.  Perhaps it was because we were thinking of eventually making a more sophisticated edge object (other than tuples) and didn't want to make a more complicated interface until we worked that out.

**Comment by dschult** [comment]
Yes, I think edge objects were a large part of it. 

I also vaguely recall it might be confusing to have ```G.edges(keys=True)``` return a 2-tuple for Graph and 3-tuple for MultiGraph.  Currently the output of all the variants of ```G.edges(data=..., keys=...)``` are the same tuple for both Graph and MultiGraph (when they are allowed). So you know how large a tuple to expect. This proposal would make it easier to create a bug where ```keys=True``` is used without an output check for multiedges.  The code idiom in the original post serves as a reminder that we have to handle the output carefully.  

We could have ```G.edges(keys=True)``` for a Graph return a 3-tuple (u,v,0) for each edge...
Would that simplify code in these places that use the code idiom in OP?

**Comment by hagberg** [comment]
I didn't find very many places where this occurs, function.py, graphmatrix.py, binary.py - so maybe this isn't an important thing to fix.  It looks like it would be a bad idea (or at least require some more code) to make the three-tuple for graphs return (u,v,0) in binary.py

**Comment by jfinkels** [comment]
@dschult Okay, I see the argument against this change: the presence of the argument `keys` is "effective redundancy" because it indicates to the user that the edges are multigraph edges instead of simple graph edges.

**Comment by dschult** [comment]
It would be nice to make a smooth difference between multiedge 3-tuples and edges 2-tuples. I would say its a NetworkX "wart". Been looking at it again with the edge views idea. Suggestions are welcome.

**Comment by yash14123** [comment]
I will like to take this up. :)

**Comment by hagberg** [comment]
Closed due to inactivity.
