### ISSUE TITLE
Error building networkx on windows

### ISSUE THREAD

**Issue by Insoleet** [networkx/networkx#1938]
Hello,

When I install networkx on windows, I get the following error : 

```
  creating build\bdist.win-amd64\wheel\networkx-1.10.data\data\share\doc\networkx-1.10\examples\drawing
  error: can't copy 'examples\drawing\atlas.py': doesn't exist or not a regular file
  
  ----------------------------------------
  Failed building wheel for networkx
```

Any idea of what is happening here ?

**Comment by OrkoHunter** [comment]
Hey @Insoleet, can you tell the python version you are using and the method of your installation?

**Comment by Insoleet** [comment]
I'm using python 3.5 and I'm running `pip install networkx` .

**Comment by OrkoHunter** [comment]
I believe this concerns the issue #1695 which was fixed in #1707 and was included in the release 1.11(?) hopefully. And from your error log it seems that v1.10 is being installed. So, either you can install it directly from the source or you may wait for a new release.

**Comment by Insoleet** [comment]
Could the reason that 1.11 is not being installed be that the versioning is strange on pypi ? ( https://pypi.python.org/pypi/networkx/1.11rc1 ) . Maybe "1.11rc1" is wrongly parsed by pip.

**Comment by OrkoHunter** [comment]
Or maybe the installed python is v3.5 and the egg is labelled v3.4 only? Although, I'm not an expert on this subject.

**Comment by Insoleet** [comment]
pip uses the src and builds the package if no egg / wheel is found if I'm not mistaken.

**Comment by dschult** [comment]
There has not been a v1.11 release yet. The release candidate v1.11rc1 is a release candidate and it does include the fix, but you will have to point pip to it explicitly.  pip will install 1.10 by default until there is a v1.11 release.
