### ISSUE TITLE
Reachability

### ISSUE THREAD

**Issue by nishnik** [networkx/networkx#1940]
Should we add the functionality of [Reachability](https://en.wikipedia.org/wiki/Reachability) ?
If yes, where ?

**Comment by jfinkels** [comment]
There is a `has_path` function. I started working on space-efficient reachability on a branch in my repository. https://github.com/networkx/networkx/compare/master...jfinkels:reachable

**Comment by nishnik** [comment]
Cool!
I was going through [`PADS/AcyclicReachability`](https://www.ics.uci.edu/~eppstein/PADS/AcyclicReachability.py). It takes linear time to initialize the class and then constant time to answer queries about reachability, but the repercussion being, it is only valid for DAG. If plausible, I would like to add this feature.

**Comment by jfinkels** [comment]
That's a separate function, so you should create a pull request separate from my code.

**Comment by hagberg** [comment]
Needs 2 PRs.  One for the general problem and one for DAGs.
