### ISSUE TITLE
Adding dominator Tree 

### ISSUE THREAD

**Issue by Arafatk** [networkx/networkx#1941]
Networkx has [immediate_dominators](https://networkx.github.io/documentation/development/reference/generated/networkx.algorithms.dominance.immediate_dominators.html) and [dominance_frontiers](https://networkx.github.io/documentation/latest/reference/generated/networkx.algorithms.dominance.dominance_frontiers.html#networkx.algorithms.dominance.dominance_frontiers). I was thinking of adding a simple **dominator_tree** function.
I was wondering if would there be any interest in adding this to networkx?  I would be happy to make a pr for that.

**Comment by Arafatk** [comment]
Aside from that the current implementation uses [Paper by Keith D. Cooper, Timothy J. Harvey and Ken Kennedy](http://web.cse.ohio-state.edu/~rountev/788/papers/cooper-spe01.pdf) with run time O(n*n)
I will also try  [Lengauer-Tarjan algorithm](https://www.cs.princeton.edu/courses/archive/fall03/cs528/handouts/a%20fast%20algorithm%20for%20finding.pdf) with run time of O(n Log(m)). And see which one works better in practice, by testing them.

**Comment by jfinkels** [comment]
Please make a pull request when you are ready.

**Comment by Arafatk** [comment]
@jfinkels I will work on it. 
And by the way,I have this existing [pr](https://github.com/networkx/networkx/pull/1928). What else can do with it so that it gets fit for merging?  
Thanks.
