### ISSUE TITLE
Bug in export to Pajek format

### ISSUE THREAD

**Issue by vpodpecan** [networkx/networkx#1948]
The second to last line in function `generate_pajek(.)` in file `networkx/networkx/readwrite/pajek.py` is redundant and should be deleted because it produces duplicate of every k,v pair for edge data.

Also, it should be checked whether the value of the attribute is not an empty string (for nodes and for eges) before writing it out. As it is now, the function can produce strange results. The Pajek program itself is quite tolerant and will parse the file containing errors but other programs which accept Pajek files may not.

**Comment by Michael-E-Rose** [comment]
Yes, line 75 in [`networkx/readwrite/pajek.py`](https://github.com/networkx/networkx/blob/master/networkx/readwrite/pajek.py) looks also redundant to me. At the same time, we should update the file to PEP8 and replace `__author__` tag.

**Comment by hagberg** [comment]
Definitely looks wrong.  Please make a PR to fix.

**Comment by Michael-E-Rose** [comment]
So I believe this issue can be closed.
