### ISSUE TITLE
xml version and meta tags for .gexf files

### ISSUE THREAD

**Issue by Michael-E-Rose** [networkx/networkx#1949]
Networkx' `.gexf` files lack the starting `<?xml version="1.0" encoding="UTF-8"?>` tag which are needed by some editors to highlight text. It's easy to implement this and I can do this.

While I am at it, how's your feeling on `<meta`> tags? Other programs (Gephi) state `lastmodifieddate` as well as `creator`.

**Comment by hagberg** [comment]
Yes, we should fix that starting tag. 
I don't have any strong opinions about meta tags.   It might not be a bad idea to note that it was networkx that created the broken gexf file :smiley:

**Comment by Michael-E-Rose** [comment]
I now realize that 806489a34006f2754e92a3d4ef680ba4bc424150 already fixed the issue with printing the xml declaration.

The code however needs a cleanup (it's far from PEP8) and while I'm at it, I'll add the meta tags.
