### ISSUE TITLE
json_graph.node_link_data() doesn't get node IDs right

### ISSUE THREAD

**Issue by Michael-E-Rose** [networkx/networkx#1951]
There is a bug with writing json files related to node IDs.

Let's create a simple graph with nodes `k` and `l` with a undirected edge between them:

    >>> import networkx
    >>> from networkx.readwrite import json_graph
    >>> G = networkx.Graph([('k', 'l')])
    >>> data = json_graph.node_link_data(G)

Let's create a `.json` output:

    >>> print json_graph.node_link_data(G)
    {'directed': False, 'graph': [], 'nodes': [{'id': 'k'}, {'id': 'l'}], 'links': [{'source': 0, 'target': 1}], 'multigraph': False}

A link is created between `1` and `0`, but these nodes are not existent. That's clearly a bug, as the resulting file is quite useless.

I can think of two fixes:
1. The result should be: `{'source': 'k', 'target': 'l'}` -> change in [`networkx/readwrite/json_graph/node_link.py`](https://github.com/networkx/networkx/blob/master/networkx/readwrite/json_graph/node_link.py)
2. The result should be: `{'id': 0, 'label': 'k'}, {'id': 1, 'label': 'l'}` -> change somewhere in [`classes/graph.py`](https://github.com/networkx/networkx/blob/master/networkx/classes/graph.py)

**Comment by hagberg** [comment]
If I remember correctly how this format works this is a correct output. 

The 'nodes' key in the output data tells you that node 0 (the first element of the list) is called 'k' and node 1 is called 'l'.  Then you have the links key which says source 0 is connected to target 1.

**Comment by Michael-E-Rose** [comment]
Hmm, this may actually be the case. I was only checking with [Sigma js](http://sigmajs.org/), which expects a differently formatted file, where node IDs are given rather than numbered. I think that's the kind of `.json` that comes from Gephi.

But it's still confusing to give an ID in the node list when it's a redundant entry to label. The example json used in [d3's Force-Directed Graph](http://bl.ocks.org/mbostock/4062045#miserables.json) just calls it `names`.

**Comment by hagberg** [comment]
There are many json graph formats.  This one is based on d3's style.

You can configure the name of the attributes.  e.g.

```python
In [11]: json_graph.node_link_data(G,{'id':'name','source':'source','target':'target'})
Out[11]: 
{'directed': False,
 'graph': {},
 'links': [{'source': 0, 'target': 1}],
 'multigraph': False,
 'nodes': [{'name': 'k'}, {'name': 'l'}]}
```

Maybe that should be the default?

**Comment by Michael-E-Rose** [comment]
Yes, I think it is less confusing to call that property name and not id.

Also, I think we can remove `'graph': {},` (caused by `data['graph'] = G.graph`, line 82 of [`networkx/readwrite/json_graph/node_link.py`](https://github.com/networkx/networkx/blob/master/networkx/readwrite/json_graph/node_link.py)). It's always empty and `.graph` or `.graph()` is not documented.

**Comment by hagberg** [comment]
I'm not sure why we are using `id` instead of `name` as the default.  If the latter is more common I support changing that.

G.graph is not always empty and allows us to round-trip all of the data we store with networkx graphs.
It can be ignored by any program that doesn't want it.

```python
In [5]: G.graph['title']='my title'

In [6]: json_graph.node_link_data(G,{'id':'name','source':'source','target':'target'})
Out[6]: 
{'directed': False,
 'graph': [('title', 'my title')],
 'links': [{'source': 0, 'target': 1}],
 'multigraph': False,
 'nodes': [{'name': 'k'}, {'name': 'l'}]}
```

**Comment by Michael-E-Rose** [comment]
While we're at it, we can also add an additional keyword to `attrs`, such that "links" may be called "edges".

**Comment by hagberg** [comment]
Yeah, we can certainly do that.  The great part about graph data formats is that there are so many standard ones.

**Comment by hagberg** [comment]
Needs PR.

**Comment by Michael-E-Rose** [comment]
I'm working on it. A somewhat tricky part is to make `node_link_graph()` work with either `links` or `edges` as well.

I will also change the `id` keyword. It's not an ID what we're having but a label or a name (two different words for the same thing). An ID is a number or the name, but not always given (namely in the case when a user chooses to call node names `name`).
