### ISSUE TITLE
Google Summer of Code 2016 participation?

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#1954]
@dschult @hagberg @chebee7i @jfinkels @ysitu @bjedwards @jtorrents and anyone who is interested. 

PSF will be applying as a mentor org https://wiki.python.org/moin/SummerOfCode/2016. We can participate again as a suborg. If we have three or four mentors on board we can work on a couple of projects (like last year). Deadline to contact PSF is 7 March, 2016 (nice one and half months to build up on ideas page)

Various ideas were proposed and discussed https://github.com/networkx/networkx/issues/1341 last year.

Some more ideas
* I think https://github.com/networkx/networkx/issues/1076 can be a good summer project. 
* Extending last year's project, https://github.com/networkx/networkx/issues/1632 and https://github.com/networkx/networkx/issues/1738.
* More work on  https://github.com/networkx/networkx-metis.

**Comment by OrkoHunter** [comment]
* Work on [`nxlemon`](https://github.com/networkx/networkx-lemon/), perhaps.
* Separate plotting library for NetworkX is still on hold.

**Comment by hagberg** [comment]
Apparently no interest this year.
