### ISSUE TITLE
函数average_shortest_path_length()考虑欠缺点

### ISSUE THREAD

**Issue by Wuyanan520** [networkx/networkx#1960]
调用该函数计算由单个节点构成的网络（经判定该网络是联通网络）的平均最短路径长度，则会报错。
原因是，该情况未被考虑在内。
如：
网络G中仅有一个节点0，用nx.is_connected(G)判定结果为Ture.故G为联通网络。
而该网络的节点为1，故1-1=0，average_shortest_path_length()函数计算中分母为0，出错

**Comment by dschult** [comment]
Fixed in #1961
