### ISSUE TITLE
node_link_graph: convert keys back to tuples 

### ISSUE THREAD

**Issue by fjmalass** [networkx/networkx#1975]
When the nodes are tuples, json serialization converts the "id" into a list. This breaks the node_link_graph.py add_node() functions

I would propose to pipe the nodes and edge_info "id"s to a  "to_tuple" function. 
with to_tuple being something like that. 
```python
def to_tuple(x):
    if isinstance(x, list):
        x = tuple(x)
    if isinstance(x, tuple):
        x = tuple([to_tuple(xx) for xx in x])
    return x
```

**Comment by fjmalass** [comment]
or even simpler.. (Wrong cut and paste).. 
```python 
def to_tuple(x):
    if isinstance(x, (tuple, list)):
        return tuple([to_tuple(xx) for xx in x])
    return x
```

**Comment by hagberg** [comment]
OK - that makes sense.  Would you like to add that with a pull request?

**Comment by fjmalass** [comment]
I will do that. May take a couple of days to make sure I don't break anything..

**Comment by hagberg** [comment]
Needs PR.

**Comment by fjmalass** [comment]
Just submitted one. [As a newbie, i hope it did not mess it up.. even my test file was sent with a "bad character".. ]
