### ISSUE TITLE
LaTeX rendering problem

### ISSUE THREAD

**Issue by ritz301** [networkx/networkx#1979]
I'm not sure about this. [Link] (https://github.com/networkx/networkx/blob/master/doc/source/tutorial/tutorial.rst#id1)
Is `:class: Graph` not rendered properly as LaTeX? Shouldn't it be just displayed as `Graph`? I know this done for the corresponding generated webpage. Can we improve its readability for the `rst` file?

**Comment by OrkoHunter** [comment]
Hello Ritvik,
I'm sure you must have found that the `:class: Graph` is properly rendered on the [doc page](https://networkx.readthedocs.org/en/stable/tutorial/tutorial.html).

The link you have provided is simply a prettified "view" of the source, which is created by GitHub. IMO there's nothing unusual about it.
