### ISSUE TITLE
from_pandas_dataframe(create_using=nx.MultiGraph()) -- unhashable type: 'dict'

### ISSUE THREAD

**Issue by arvkevi** [networkx/networkx#1982]
Didn't see much response on SO, linking the question [here](http://stackoverflow.com/questions/35210724/networkx-multigraph-from-pandas-dataframe) to see if anyone can comment?

```python
import pandas as pd
import networkx as nx

df = pd.DataFrame([['geneA', 'geneB', 0.05, 'method1'],
                   ['geneA', 'geneC', 0.45, 'method1'],
                   ['geneA', 'geneD', 0.35, 'method1'],
                   ['geneA', 'geneB', 0.45, 'method2']], 
                   columns = ['gene1','gene2','conf','type'])

MG= nx.from_pandas_dataframe(df, 'gene1', 'gene2', edge_attr=['conf','type'], 
                             create_using=nx.MultiGraph())

TypeError                                 Traceback (most recent call last)
<ipython-input-49-d2c7b8312ea7> in <module>()
----> 1 MG= nx.from_pandas_dataframe(df, 'gene1', 'gene2', ['conf','type'], create_using=nx.MultiGraph())

/usr/lib/python2.7/site-packages/networkx-1.10-py2.7.egg/networkx/convert_matrix.pyc in from_pandas_dataframe(df, source, target, edge_attr, create_using)
    209         # Iteration on values returns the rows as Numpy arrays
    210         for row in df.values:
--> 211             g.add_edge(row[src_i], row[tar_i], {i:row[j] for i, j in edge_i})
    212 
    213     # If no column names are given, then just return the edges.

/usr/lib/python2.7/site-packages/networkx-1.10-py2.7.egg/networkx/classes/multigraph.pyc in add_edge(self, u, v, key, attr_dict, **attr)
    340             datadict.update(attr_dict)
    341             keydict = self.edge_key_dict_factory()
--> 342             keydict[key] = datadict
    343             self.adj[u][v] = keydict
    344             self.adj[v][u] = keydict

TypeError: unhashable type: 'dict'
```

**Comment by dschult** [comment]
It's a bug.  The line with g.add_edge should declare the dict as an attr_dict because multigraphs have different positional arguments to the add_edge method.  I'll put in a PR (or you can).  Line 211 of convert_matrix.py should add the text ```attr_dict=``` as in:

    g.add_edge(row[src_i], row[tar_i], attr_dict={i:row[j] for i, j in edge_i})

You can probably edit it by hand in 
```/usr/lib/python2.7/site-packages/networkx-1.10-py2.7.egg/networkx/convert_matrix.py```
if you want a quick fix.

**Comment by Wuyanan520** [comment]
I met the same error, and i have edit it by hand, however, it's still failed to work
![qq 20160621101348](https://cloud.githubusercontent.com/assets/16913304/16215911/e687cafa-3798-11e6-96b0-6695ea83613d.png)

**Comment by LancelotHolmes** [comment]
It works exactly the same for `MultiDiGraph`

**Comment by DinosC** [comment]
Hi, I m experiencing the same issue. Although I replaced line 211, "TypeError: unhashable type: 'dict'" still exists.  I want to build a MultiGraph using the following dataframe:

	l_id	       v_id_1	v_id_2	 v	         f
0	3483	        739	         2232	 380000	 50
1	3482 	717	         2196        380000	 50
2	3482	        717	         2196        220000	 50
3	3480	        1058 	2250 	 220000	 50

Trying to run this "G=nx.from_pandas_dataframe(links,'v_id_1','v_id_2',edge_attr=['v','f'],create_using=nx.MultiGraph())", I m getting the error. What am I missing?

Thanks in advance!

**Comment by jtorrents** [comment]
Hello @DinosC , thanks for the report. Your example works with the last development version of NetworkX:
```python
In [20]: data = {'1_id':[3483, 3482, 3482, 3480], 'v_id_1':[739, 717, 717, 1058], 'v_id_2':[2232,2196, 2196, 2250], 'v':[38000, 38000, 22000, 22000], 'f':[50, 50, 50, 50]}

In [21]: links = pd.DataFrame(data)

In [22]: links
Out[22]: 
   1_id   f      v  v_id_1  v_id_2
0  3483  50  38000     739    2232
1  3482  50  38000     717    2196
2  3482  50  22000     717    2196
3  3480  50  22000    1058    2250

In [23]: G=nx.from_pandas_dataframe(links, 'v_id_1', 'v_id_2', edge_attr=['v','f'], create_using=nx.MultiGraph())

In [24]: list(G.nodes())
Out[24]: [1058, 739, 2196, 2232, 2250, 717]

In [25]: list(G.edges(data=True))
Out[25]: 
[(1058, 2250, {'f': 50, 'v': 22000}),
 (739, 2232, {'f': 50, 'v': 38000}),
 (2196, 717, {'f': 50, 'v': 38000}),
 (2196, 717, {'f': 50, 'v': 22000})]

In [26]: print(nx.__version__)
2.0.dev_20161206165920
```

If you can I'd recommend that you install the development version of NetworkX from github.

**Comment by DinosC** [comment]
H JTorrents. Really thanks for your assistance. Indeed, the reason was that I had installed the version 1.11.

**Comment by pazz** [comment]
Hi! Sorry to bring this up again but I might have run into a related issue:
I've dug up an old project of mine to generate particular random graphs
(https://github.com/pazz/egsolver) and noticed that my code fails in a similar way as you describe here.

It happens in `function.py` instead of `multigraph.py` though.
To reproduce quickly:

```
git clone git@github.com:pazz/egsolver.git && cd egsolver
./setup.py develop --user
```

Now, the command

```
egsolver generate 5 0.5 0.5 10
```

should generate some graph and print it. However:



```
ERROR unhashable type: 'dict'
Traceback (most recent call last):
  File "/home/pazz/projects/mpg/egsolver/egsolver/main.py", line 144, in main
    COMMANDS[args.cmd](args)
  File "/home/pazz/projects/mpg/egsolver/egsolver/main.py", line 37, in generate
    args.nosinks)
  File "/home/pazz/projects/mpg/egsolver/egsolver/generators.py", line 32, in random_energy_game
    nx.set_edge_attributes(eg, 'effect', effect)
  File "/home/pazz/.local/lib/python2.7/site-packages/networkx-2.1rc1.dev20171008103319-py2.7.egg/networkx/classes/function.py", line 763, in set_edge_attributes
    data[name] = values
TypeError: unhashable type: 'dict'
```


As the trace suggests, This happens on a networkx version from a recent master branch from github.

An example value of the variable `effect` is this.

```
{(0, 1): -9, (1, 3): 0, (4, 1): -10, (3, 1): -5, (2, 1): -3, (2, 4): -6, (2, 0): -3, (2, 3): -4, (4, 2): 1, (0, 3): -8, (3, 4): -10, (0, 2): -8, (4, 0): -7}
```

**Comment by pazz** [comment]
Oh snap! Sorry for the spam.

I just realized that the signature of `set_edge_attributes` must have changed since I last checked. The order of its parameters is now `(graph, values, name)` and not `(graph, name, values)`.
I wasn't aware of this change (and will now use named arguments to be sure).

Sorry again.
