### ISSUE TITLE
AttributeError: 'module' object has no attribute 'write_dot'

### ISSUE THREAD

**Issue by polosecki** [networkx/networkx#1984]
Error when  typing:
```
import networkx as NX
G=NX.grid_2d_graph(5,5)  # 5x5 grid
NX.write_dot(G,"grid.dot")
```
This produces the error
```
Traceback (most recent call last):

  File "<ipython-input-4-742fbc2aa48b>", line 1, in <module>
    NX.write_dot(G,"grid.dot")

AttributeError: 'module' object has no attribute 'write_dot'
```
The following libraries are installed:
graphviz (0.4.9)
pygraphviz (1.3.1)
pydot (1.0.28)
networkx (1.11)

It does seems as if, even though Python recognizes all the packages as installed, somehow networkx doesn't acknowledge it. I tried uninstalling and reinstalling all these packages, which happens successfully, but doesn't correct the issue.

**Comment by hagberg** [comment]
In networkx-1.11 and later you need to say
```from networkx.drawing.nx_agraph import write_dot```
or
```from networkx.drawing.nx_pydot import write_dot```

then 

```python
write_dot(G,"grid.dot")
```

An example is at 

https://networkx.readthedocs.org/en/stable/examples/pygraphviz/write_dotfile.html

**Comment by polosecki** [comment]
That worked, thank you. I was following the online documentation, which seems to be outdated on that aspect: https://networkx.github.io/documentation/latest/examples/pygraphviz/write_dotfile.html

**Comment by hagberg** [comment]
Thanks for pointing out the documentation issue. We have moved our documentation home from github to readthedocs but haven't clearly marked the older versions.  I'll fix that.

**Comment by hagberg** [comment]
Added redirects to networkx documentation to point "latest" and "development" docs to networkx.readthedocs.org.  That won't fix all of the old links and some will make 404s but it's the best we can do using simple techniques at networkx.github.io.
