### ISSUE TITLE
example link for sparsegraph6 file format is broken

### ISSUE THREAD

**Issue by megansquire** [networkx/networkx#1994]
[https://networkx.github.io/documentation/latest/reference/readwrite.sparsegraph6.html](https://networkx.github.io/documentation/latest/reference/readwrite.sparsegraph6.html)
the ~bdm user's account is no longer working on the http://cs.anu.edu.au server

**Comment by hagberg** [comment]
Perhaps it was temporary?  This link works for me http://cs.anu.edu.au/~bdm/data/formats.txt 
(redirects to http://users.cecs.anu.edu.au/~bdm/data/formats.txt)

**Comment by megansquire** [comment]
Thanks. So flaky. It was definitely returning 404. I even went so far as to look up that professor in their directory and try to find out if he even still had a university account :) Ah, internets.
