### ISSUE TITLE
The edge_load() function has only placeholder documentation

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#1998]
The `edge_load` function is exposed in the documentation, but not documented.

http://networkx.readthedocs.org/en/latest/reference/generated/networkx.algorithms.centrality.edge_load.html#networkx.algorithms.centrality.edge_load

**Comment by yash14123** [comment]
What to put in the references section for this?

**Comment by yash14123** [comment]
I want to work on this. Please give me the file reference where to edit this. 
Thanks.

**Comment by yash14123** [comment]
PR for Issue #2015
