### ISSUE TITLE
Draw multiple paths in a graph. (migrated from Trac #199)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#200]
Original ticket https://networkx.lanl.gov/trac/ticket/199
Reported 2008-12-02 by trac user qrancik, assigned to @hagberg.

Hi all,

First of all - thanks a lot for NetworkX ! It is something I was looking for: easy to use, flexible and powerful. 

I would like to contribute to the project. I have written a module to draw paths in a graph. I find it quite handy. It smoothly integrates with the existing drawing functions such as nx.draw().

To make the visualization nicer and easier to digest, the path corners are rounded with the help of quadratic and cube Bezier curves. Moreover, if two or more paths traverse the same edge, they are automatically shifted to make them all visible. 

I attach the module and two figures generated with it. Looking forward to your comments!

qrancik

**Comment by hagberg** [comment]
Closed due to inactivity.
