### ISSUE TITLE
agedge key error in agraph.py 

### ISSUE THREAD

**Issue by 4c656554** [networkx/networkx#2012]
I am getting a key error when try to get node positions for a multigraph.

This code should reproduce the error:

```
G=nx.MultiGraph()
fromnodes=[0,0,1,1,1,1,1,2,3,4,5,5,5,7,8,9,10]
tonodes=[1,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16]
dupedgeind=0
for x,y in zip(fromnodes,tonodes):
    if G.has_edge(x,y):
        dupedgeind=dupedgeind+1
        G.add_edge(x,y,key=dupedgeind)
    else:
        dupedgeind=0
        G.add_edge(x,y,key=dupedgeind)
pos=nx.nx_agraph.pygraphviz_layout(G,prog='sfdp')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\networkx\drawing\nx_agraph.py", line 262, in pygraphviz_layout
    A=to_agraph(G)
  File "C:\Python27\lib\site-packages\networkx\drawing\nx_agraph.py", line 155, in to_agraph
    A.add_edge(u,v,key=str(key),**str_edgedata)
  File "C:\Python27\lib\site-packages\pygraphviz\agraph.py", line 484, in add_edge
    eh = gv.agedge(self.handle, uh, vh, key, _Action.find)
KeyError: 'agedge: no key'
```

Note I am using networkx v1.11, pygraphviz v1.3.1, graphviz 2.38 on windows7.
I installed pygraphviz from [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/#pygraphviz): 

See also [my stackoverflow question](http://stackoverflow.com/questions/35610736/passing-a-string-to-agedge-in-agraph-py-issue-with-networkx-and-pygraphviz). 

Thanks to all the contributors to this great library!

**Comment by 4c656554** [comment]
Also posted an issue [here](https://github.com/pygraphviz/pygraphviz/issues/88) as am unsure whether it is a networkx, pygraphviz or a graphviz issue.

**Comment by hagberg** [comment]
This is not a networkx issue.  It is a pygraphviz/graphviz issue.  (I can't reproduce it though).
