### ISSUE TITLE
Link on networkx account not working

### ISSUE THREAD

**Issue by yash14123** [networkx/networkx#2018]
https://github.com/networkx has a link : 
[http://networkx.lanl.gov/](url)
It does not work.

**Comment by hagberg** [comment]
It's 2 problems.
1) The link should be updated to point to networkx.github.io
2) The redirected at networkx.lanl.gov is broken (I'll fix that)

**Comment by chebee7i** [comment]
I fixed part 1).

**Comment by chebee7i** [comment]
And the redirect seems to be working fine now.

Thanks for the report!
