### ISSUE TITLE
Power function is not described in documentation

### ISSUE THREAD

**Issue by theaverageguy** [networkx/networkx#2019]
https://networkx.github.io/documentation/development/reference/algorithms.operators.html
![l](https://cloud.githubusercontent.com/assets/9817962/13389628/72679e54-deef-11e5-8439-ea6820d53043.png)

**Comment by jfinkels** [comment]
This seems to be working on readthedocs: http://networkx.readthedocs.io/en/latest/reference/algorithms.operators.html
