### ISSUE TITLE
Hybrid Algorithms not described in Documentation

### ISSUE THREAD

**Issue by theaverageguy** [networkx/networkx#2020]
https://networkx.github.io/documentation/development/reference/algorithms.hybrid.html

![c](https://cloud.githubusercontent.com/assets/9817962/13391317/c785ce38-def9-11e5-895d-5fff547fd537.png)

**Comment by yash14123** [comment]
I don't know where the code for these lie exactly. I have 3 issues I want to create PRs for but I just don't find the code where to edit this. Please help me out.

**Comment by hagberg** [comment]
networkx/algorithms/hybrid.py

**Comment by dschult** [comment]
It looks like the ```__all__``` variable in hybrid.py is ```_all__``` (missing one underbar) so the automatic generation of docs is not working.  The source for docs that are not autogenerated is doc/source/reference

**Comment by yash14123** [comment]
Can I fix this?

**Comment by yash14123** [comment]
Can I fix this?

**Comment by yash14123** [comment]
Can I fix this?

**Comment by yash14123** [comment]
Can I fix this?

**Comment by yash14123** [comment]
So it is just one underbar to add? would it fix that?
