### ISSUE TITLE
add_cycle, add_path, etc. must be removed from Graph documentation

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#2025]
The documentation for, for example, the `Graph` class includes an entry in autosummary for `add_cycle`, etc., but these methods were removed in #1970 in favor of functions. The autosummary entries must be removed.

**Comment by dschult** [comment]
Looks like they should be added to the "functions" autosummary entries as well.

There are quite a few other errors in the [sphinx doc builds](http://readthedocs.org/projects/networkx/builds/3764367/) too... 
mostly with communicability and cuts.

I'll try to clean that up.
