### ISSUE TITLE
Inconsistency between v1.11 and current master algorithms

### ISSUE THREAD

**Issue by OrkoHunter** [networkx/networkx#2028]
Hi !

Inside [`networkx.algorithms.tree.mst`](https://github.com/networkx/networkx/blob/master/networkx/algorithms/tree/mst.py) module there are functions for minimum and maximum spanning trees/edges. But in the version 1.11, there is no such function for maximum spanning tree in the main namespace. Also the `mst` module is at the root directory of `algorithms` module, without the maximum spanning functions. I found this weird and hence I would like to know if there is any particular reason for this?

**Comment by hagberg** [comment]
This change was part of https://github.com/networkx/networkx/pull/1577
