### ISSUE TITLE
Use the matplotlib plot directive when generating documentation

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#2030]
The `plot` directive in the Sphinx extension [`matplotlib.sphinxext.plot_directive`](http://matplotlib.org/sampledoc/extensions.html#inserting-matplotlib-plots) automatically generates matplotlib plots in the rendered HTML from Sphinx documentation. This can replace the "manual" generation of examples currently in use in the `doc/make_gallery.py` script.

**Comment by jfinkels** [comment]
I am working on a branch that implements this.

**Comment by hagberg** [comment]
See #2054.

Let's use notebooks for examples #1754 and we can avoid this issue.

**Comment by jarrodmillman** [comment]
@hagberg , @dschult   This should be closed.  We don't need the matplotlib plot directive, since we are using the sphinx-gallery now.
