### ISSUE TITLE
Weight functions in paths should be available in all functions

### ISSUE THREAD

**Issue by borisdan** [networkx/networkx#2032]
Following this pull request:
#1690 

Thanks for the change, but the weight function is still not supported in all functions, for example in dijkstra_path_length - the weight function is ignored.

**Comment by jfinkels** [comment]
That was an oversight on my part. I also messed up the documentation there on `dijkstra_path_length`. I'll make a pull request with a fix.

**Comment by dschult** [comment]
Fixed in #2033
