### ISSUE TITLE
random graph generator performance improvement using multiprocessing

### ISSUE THREAD

**Issue by Cona19** [networkx/networkx#2036]
I'm a novice about networkX. so I'm just using some random graph generating functions in networkX, but it sometimes takes too long time. I think that it can be done faster when we use multiprocessing techniques. If you don't mind, how about implement some functions with multiprocessing techniques?

**Comment by hagberg** [comment]
Any speedup using multiprocessing will depend on the algorithm.  You don't say what kind or size of graph you are trying to generate it isn't possible to determine if your code can be improved.
