### ISSUE TITLE
atlas example is duplicated in two directories

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#2046]
The file `examples/drawing/atlas.py` and `examples/graph/atlas.py` are the same file. I recommend keeping only the former.

**Comment by jfinkels** [comment]
There are two more examples that are duplicated: `knuth_miles` and `unix_email`.

**Comment by jfinkels** [comment]
Here's another: `examples/multigraph/chess_masters.py` and `examples/drawing/chess_masters.py`.

**Comment by hagberg** [comment]
Yes, the duplicate can be removed - either one.
