### ISSUE TITLE
Small feature proposal (feature request)

### ISSUE THREAD

**Issue by jg-you** [networkx/networkx#2049]
The function / method `size()` is quite useful because it allows the user to sum an edge attribute "on the fly", e.g..:

``` python
G = nx.Graph()
G.add_edge(0, 1, weight=2)
G.add_edge(0, 2, weight=2)
G.add_edge(0, 3, weight=10)
print(G.size(weight='weight'))
>>> 14
print(G.size(weight='width'))
>>> 3
```

I'm pretty sure that there is no equivalent for node attributes.
Would it be a useful feature?

The code is quite simple. If the default attribute value is 0, then something along the line of

``` python
def sum_node_attribute(G, attribute):
"""Documentation string here."""
    return sum([v for k, v in nx.get_node_attributes(g, attribute).items()])
```

should suffice. A simple conditional clause could deal with different defaults.

At least it's a function I found myself writing a lot, since I started dealing with annotated graph way more often.

**Comment by dschult** [comment]
I think of ```get_node_attribute``` as supplying this feature... but you are correct that to sum all the attribute values is another step. Am I correct in summarizing that your suggestion is to create a function that returns:

```sum(nx.get_node_attributes(g, attribute).values())```

With ```size()``` there is a literature that commonly defines this quantity and algorithms which refer to it. Do you know of anything like that for the sum of node attributes?

Thanks

**Comment by jg-you** [comment]
Yes it's mostly a syntactic sugar thing. There's also some notion of symmetry there, i.e. what exists for nodes could exists for edges and vice versa. But I agree that it might be irrelevant. 

There is some common occurrence, but none that I can think of which pertains to graph theory _directly_ (maybe some variants of max flow?).

Once you enter the realm of annotated graphs, this is a different story.
e.g. in power grid graphs, you typically assign attributes to each nodes such as `power_generated`,  `demand` etc. Then the sum of this value across a connected component _is_ meaningful.

**Comment by hagberg** [comment]
Closed due to inactivity.
