### ISSUE TITLE
Feature proposal - Graph Read/write formats

### ISSUE THREAD

**Issue by Temigo** [networkx/networkx#2051]
Hi,

I realized that Networkx cannot handle graphs in formats such as Ucinet DL, which is handy because of the datasets available in this format. In comparison with Gephi (https://gephi.org/users/supported-graph-formats/) several formats are missing, if I'm not mistaken. 

Would this be a feature that you would appreciate to be added to Networkx ? If it is the case, I would be glad to implement it.

Thanks !

**Comment by hagberg** [comment]
PR in #2052
