### ISSUE TITLE
Implementing Canadian Travelling Problem (CTP)

### ISSUE THREAD

**Issue by lamprini-koutsokera** [networkx/networkx#2055]
CTP is a generalization of the shortest path problem to graphs that are partially observable. You can find more information here: https://en.wikipedia.org/wiki/Canadian_traveller_problem.

I would like to implement a problem like this. 

Does networkx want to have this problem implemented?

**Comment by hagberg** [comment]
Hi @lamprini-koutsokera  - NetworkX is primarily about data structures and algorithms for graphs.  Are you proposing implementing an algorithm to for solutions to the CTP?

**Comment by lamprini-koutsokera** [comment]
Hi @hagberg! For solutions to the CTP, I would like to implement a **repositioning algorithm**. More specifically:
- If **f** is the node from which we start, and **t** is the node where we want to go, we perform the **Dijkstra's algorithm** to find the shortest path from **f** in **t**.
- We begin to follow the path. If along the way, when we are ready to cross link **(u, v)**, we see that the link is closed, then we return to our original **f** node and perform the Dijkstra's algorithm to find the shortest path from **f** to **t** having removed from our link graph **(u, v)**.
- We begin to execute the new path found by **f** in **t.** If we see that a link we are going to cross is closed, we go back to the beginning, we remove the enclosed link of the graph, we execute the algorithm of Dijkstra, etc.
So again we perform the Dijkstra's algorithm as many times as we fall in a closed link, but each time we return to the beginning. Our overall path resulting from the union of the individual paths that we find.

What do you think?

**Comment by hagberg** [comment]
I see that algorithm mentioned here http://erikdemaine.org/papers/CanadianTraveler_ICALP2014/paper.pdf along with a greedy algorithm.  
(It's an interesting paper too).

If you want to implement that algorithm we will consider it for inclusion in networkx.  Take a look at some examples of existing algorithms to understand how to format things and ask here for help.

**Comment by hagberg** [comment]
See #2153
