### ISSUE TITLE
Idea for implementing the Orienteering Problem.

### ISSUE THREAD

**Issue by AthinaSpanou** [networkx/networkx#2056]
I am interested in implementing the Orienteering Problem (OP) for networkx. 

OP is something like a Prize-Collecting Travelling Salesman Problem (PC-TSP). In the orienteering problem, start and end points are specified along with other locations which have associated scores. Given a fixed amount of time, the goal is to determine a path from the start point to the end point through a subset of locations in order to maximize the total path score.

Should I proceed with the implementation?

**Comment by hagberg** [comment]
Hi @AthinaSpanou - thanks for suggesting this addition.  NetworkX is primarily about data structures and algorithms for graphs and we are interested in adding new algorithms.  Are you proposing adding an algorithm that can approximate the PC-TSP solution?

**Comment by AthinaSpanou** [comment]
Hi @hagberg ! I am thinking of implementing a [tabu search](https://en.wikipedia.org/wiki/Tabu_search) algorithm for the solution of the OP. Would that be possible to be included in networkx ?

**Comment by hagberg** [comment]
See #2152

**Comment by alessio-locatelli** [comment]
Should this really be closed? There is no implemented functionality, the PR has been closed, following the chain of links from https://github.com/networkx/networkx/pull/2152 and others leads to nothing or dead links.

**Comment by dschult** [comment]
It was closed in 2017 -- :)
