### ISSUE TITLE
Missing function for breadth-first search on edges

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#2057]
There is an `edge_dfs` function, for performing a depth-first search on edges, but no `edge_bfs` function for performing a breadth-first search on edges.

The behavior I'm imagining is:

```
>>> import networkx as nx
>>> G = nx.DiGraph([(0, 1), (0, 2), (1, 3), (2, 3)])
>>> list(nx.edge_dfs(G))
[(0, 1), (1, 3), (0, 2), (2, 3)]
>>> list(nx.edge_bfs(G))
[(0, 1), (0, 2), (1, 3), (2, 3)]
```

I would like to be able to use such a function for converting a directed acyclic graph to an "equivalent" tree.

**Comment by hagberg** [comment]
I think `edge_dfs` was written to specifically handle multigraphs and also to avoid overhead of reversing the graph if you needed that.  

For your purposes could you use bfs_edges?

```python
In [10]: G = nx.DiGraph([(0, 1), (0, 2), (1, 3), (2, 3)])

In [11]: list(nx.bfs_edges(G,0))
Out[11]: [(0, 1), (0, 2), (1, 3)]
```

You probably don't want that (2,3) edge if you need a tree.

**Comment by hagberg** [comment]
Closed due to inactivity.
