### ISSUE TITLE
networkx.write_dot() function often produces memory error.

### ISSUE THREAD

**Issue by litaotju** [networkx/networkx#2065]
I have a networkx graph with about 25000 nodes and 75000 edges, and use the write_dot() function to save the graph to a xxx.dot file,  the memory usage increased from about **300M to 1.9G**, and will produce a **"Memory Error"** exception with no other prompt. So I think maybe this is a weak point of write_dot function, anyone can **improve the memory performance** of this function?

**Comment by hagberg** [comment]
We won't fix this as part of networkx.  The `write_dot` function either uses the pygraphviz or pydot package to output the graph data in the dot language.  Those are maintained separately.   I'd suggest contacting those projects.
