### ISSUE TITLE
Small bug in networkx.algorithms.dominance

### ISSUE THREAD

**Issue by RazorBladed** [networkx/networkx#2070]
There is a small bug in ```networkx.algorithms.dominance``` package. 

Function ```immediate_dominators``` should be given digraph and starting point. However, if a given graph has several entry points, say ```entry_1``` and ```entry_2``` (e.g. dead code block in control flow graph), and the starting point is specified as ```entry_1```, ```entry_2``` will not be present in ```idom``` dict (return value) as key. This is correct behavior concerning the definition of dominators, but this can lead to ```KeyError``` exception in a call to ```dominance_frontiers``` function, because it does not check predecessors to be reachable from start.

Below is a snippet representing an issue. 
```
import networkx as nx
from networkx.algorithms.dominance import *

g = nx.DiGraph()

edges = [
            ('entry_1', 'b1'),
            ('b1', 'b2'),
            ('b2', 'b3'),
            ('b3', 'exit'),
            ('entry_2', 'b3')
        ]

# entry_1
#   |
#   b1
#   |
#   b2  entry_2
#    |  /
#    b3
#    |
#   exit

g.add_edges_from(edges)

# will raise KeyError on entry_2 when parsing b3
# because entry_2 does not have immediate doms (no path)
dominance_frontiers(g,'entry_1') 
```

Suggestion is to parse only those predecessors that have path from given starting point to them. This can be achieved by adding ```v in idom``` check which is equivalent to having a path from start point in this context.

P.S. tested on networkx version 1.11

**Comment by hagberg** [comment]
Can you be more specific on the fix?  I'm not an expert in this algorithm.

**Comment by RazorBladed** [comment]
Just add v in idom check before doing something in for loop in dominance_frontiers function, as I suggested before. After computing immediate dominators, idom keys will be only those nodes, that have immediate dominator, which is equivalent to having path from starting point.
