### ISSUE TITLE
Possible bug in dominance package

### ISSUE THREAD

**Issue by RazorBladed** [networkx/networkx#2071]
While working with ```dominance_frontiers``` algorithm I have noticed some strange line of code, which I think leads to incorrect results.

My question is: why try to discard element ```u```?
```
p.discard(u)
```

Given the following example it produces wrong results.
```
import networkx as nx
from networkx.algorithms.dominance import *

g = nx.DiGraph()
g.add_edges_from([
('b0','b1'), 
('b1', 'b2'),
('b2', 'b3'),
('b3','b1'), 
('b1','b5'), 
('b5', 'b6'), 
('b5', 'b8'), 
('b6', 'b7'), 
('b8', 'b7'), 
('b7', 'b3'), 
('b3', 'b4')
]

df = dominance_frontiers(g, 'b0')

print df
```

It yields:
```
{'b0': [],
 'b1': [],
 'b2': ['b3'],
 'b3': ['b1'],
 'b4': [],
 'b5': ['b3'],
 'b6': ['b7'],
 'b7': ['b3'],
 'b8': ['b7']}
```
However, I expect to see ```b1``` in ```df[b1]```, as if I use general algorithm for ```b1```, while parsing its predecessors, ```b1``` itself will be passed before its immediate dominator ```b0```, so it should be added to ```df[b1]```.

**Comment by hagberg** [comment]
Is this a definition issue?  Is a node a dominator if itself?

**Comment by RazorBladed** [comment]
Yes, every node is a dominator of itself.

**Comment by hagberg** [comment]
Thanks. Let's fix this bug then.

**Comment by hagberg** [comment]
If someone can help me with the definition/algorithm of dominance frontier I will fix this.

**Comment by dschult** [comment]
This has definitions and an algorithm...  hope it helps.
https://en.wikipedia.org/wiki/Dominator_(graph_theory)

**Comment by hagberg** [comment]
That helps a little.  Though I'll probably have to read http://www.hipersoft.rice.edu/grads/publications/dom14.pdf to get it right.

**Comment by RazorBladed** [comment]
You don't need to dive deep into the algorithm to fix this bug, just remove redundant call to discard instruction. However, if you are interested I can recommend the book, where you can find good info: Keith Cooper. Linda Torczon "Engineering a compiler"

**Comment by hagberg** [comment]
Sure I can remove the discard(u).

But I got stuck when I looked at 
```
g = nx.DiGraph()
g.add_edges_from([('a','b'),('b','c'),('b','a')])
df = dominance_frontiers(g, 'a')
```
Should df['a']=['a']? or [] that the code produces.

**Comment by RazorBladed** [comment]
It should be empty, because 'a' does not have immediate dominators. This case will be parsed correctly if no nodes without immediate dominators are parsed in for loop from dominance_frontier function( this is suggested in #2070).

**Comment by hagberg** [comment]
I updated according to what @RazorBladed suggested.
I am still not sure I understand what happens with loops.  There are two examples in the tests that show this implementation is not producing the stated result.  See eg https://github.com/hagberg/networkx/commit/321364aeabec891ac9d3023fbc07cf618b6fd265#diff-095a9a6207b37916664a95b2f3bdf9b5R229

**Comment by RazorBladed** [comment]
I'm sorry, currently don't have the ability to test. I see, comment ```# missing 4```, does that mean that test does not pass because there is no 4, or is it passing without it?

**Comment by hagberg** [comment]
Sorry, that comment wasn't very helpful.  The tests pass the way they are written.
But in the example I linked above at http://ecee.colorado.edu/~waite/Darmstadt/motion.html
there is a 4 in node 4's dominance frontier which our algorithm doesn't produce.  It could be related or the same as the question I asked above in the a->b->a graph.

**Comment by RazorBladed** [comment]
I don't think it is related, think it's more about self-loop on a node. I believe I know what's the issue. Could you please give me the output for ```idom['4']``` on this test?

**Comment by hagberg** [comment]
```python
print nx.immediate_dominators(g,'entry')
{'exit': 'entry', '1': 'entry', '3': '2', '2': '1', '5': '4', '4': '3', '6': '5', 'entry': 'entry'}
```

**Comment by RazorBladed** [comment]
Thanks, everything is alright with idom. I finally solved it. We also forgot to change ```if len(G.pred[u]) - int(u in G.pred[u]) >= 2:``` to ```if len(G.pred[u]) >= 2:```. Node '4' could add itself to it's df only on iteration where ```u=='4'``` (predecessors of '4' are '3' and '4'), but this condition was not true, that's why we ignored that step. 

I also suggest to completely get rid of p set, as it is unnecessary, and make df dictionary of sets. We can update df on the fly. The final code should look like this:
```
  df = {u: set() for u in idom}
  for u in idom:
            for v in G.pred[u]:
                if v in idom: # better move this check from loop for more efficiency
                  while v != idom[u]:
                      df[v].add(u)
                      v = idom[v]
                
```
Sorry once more for lack of machine to test, there may be some typos. Please, give it a try and provide the feedback.

**Comment by hagberg** [comment]
Good suggestions.  I wondered why we weren't using sets there. 
Updated #2092 and all looks good.

**Comment by RazorBladed** [comment]
That's great!
