### ISSUE TITLE
Bug in modularity_matrix with weights

### ISSUE THREAD

**Issue by deusebio** [networkx/networkx#2072]
I believe there is a bug (tested on networkx 1.11) in the implementation of modularity_matrix in the cases when links have weights. 
The definition of the modularity_matrix is 

Bij = Aij - k_i k_j / (2 m) 

The problem is due to the fact that the adjacency matrix and the degrees of the nodes k_i and k_j are calculated with the weights, whereas the total sum of edges m does not account for it. The following snippet should show the issue 

```
import numpy as np

import networkx as nx

w = "weight"

# Create a graph with random weights
graph = nx.erdos_renyi_graph(50, 0.5)
for n1, n2 in graph.edges_iter():
    graph.edge[n1][n2][w] = np.random.rand(1)[0]

# Compute adjacency matrix and degrees
A = nx.adjacency_matrix(graph, weight=w).todense()

k1 = sum(A, axis=1)
k2 = k1.transpose()

# HERE IS THE ISSUE
# The number of edges should be calculated with weights
nEdges_wrong = graph.number_of_edges()
nEdges_correct = sum([ith[2][w]
                      for ith in graph.edges_iter(data=True)])

B_wrong = A - k1*k2*1.0/(2*nEdges_wrong)
B_correct = A - k1*k2*1.0/(2*nEdges_correct)

M = nx.modularity_matrix(graph)

print(" Wrong Implementation error: " + str(np.sum(B_wrong - M)))
print(" Correct Implementation error: " + str(np.sum(B_correct - M)))
```

The best and cleanest solution would be to introduce a key argument to decide whether one wants to compute the modularity matrix with weights or not. I have a working version with such features and the corrected computation of the number of edges. 

*On a side note, I believe the documentation of the modularity matrix should account for a factor 2 before the "m", as in the formula above.*

**Comment by hagberg** [comment]
I wouldn't say this is a bug.  It is a feature request to add a weighted option to the modularity matrix.
That seems like a good idea and should be pretty straightforward to implement.  It needs

1) Modified code in modularitymatrix.py to add a weight=None optional keyword
2) Tests for the weighted case added to test_modularity.py
3) Updated documentation including reference to the definition.

**Comment by deusebio** [comment]
Well, the bug comes when modularity_matrix is used for graphs with weighted links. I do not think that current results are what is to be expected. 

I also compared the results to the outputs of R libraries and in those cases m (the total number of edges used to normalize ki kj) are computed using weights. I believe this is the correct way to go around it.

I can go ahead and implement the changes if you want, they are pretty straightforward.

**Comment by hagberg** [comment]
Yes, please do implement the changes.

**Comment by deusebio** [comment]
Done!
