### ISSUE TITLE
nodes() performance issue in Python2.

### ISSUE THREAD

**Issue by wuhaochen** [networkx/networkx#2078]
nodes() function calls dict.items() and in Python 2 dict.items() returns a list instead of an iterator which could cause significant overhead compare to Python 3 especially when the graph is large. It seems it's not so easy to have an elegant solution to this. Should we do something about this? Any suggestions?

**Comment by hagberg** [comment]
Yes, we should definitely do something about this.  I suggest we all start using Python 3. 😃
