### ISSUE TITLE
Help with pickled graph sizes

### ISSUE THREAD

**Issue by ericmjl** [networkx/networkx#2097]
Hi everybody! I'm having an issue with saving my graph objects to disk, in which the graph objects are taking up large amounts of disk space regardless of whether or not I have node or edge metadata attached to them. I'd like to know if there's a way in which I can reduce the graph file size on disk. (For those who are interested in the research question behind all of this, I am trying to do deep learning using convolutional neural networks operating on graph-structured data.)

This is what I've done. In order to model protein structures as graphs, I have sub-classed NetworkX's `DiGraph` object into a `ProteinInteractionNetwork` object, which can be found [here][1]. (Code may be a few commits behind what I have locally; haven't pushed yet.) I use that code to construct my graphs from Protein Data Bank files that contain mutant versions of one protein. Each node has a bunch of metadata, and a `numpy` "features" array. Each edge also has a `numpy` "features" array. All "features" arrays are computed based on node and edge metadata. 

If I pickle this graph to disk, it's size is 20MB-ish. Not a big deal individually, except that I have `3401 * 3` models that I'm creating, and taken together, this can easily take up ~200GB of space. To see if removing metadata helps with saving disk space, on my graph, I set the metadata to be an empty set, by running the following code:

    # remove metadata
    for n, d in p.nodes(data=True):
        p.node[n] = dict()
    #     for k, v in d.items():
    #         del p.node[n][k]

    for u1, u2, d in p.edges(data=True):
    #     for k, v in d.items():
    #         del p.edge[u1][u2][k]
        p.edge[u1][u2] = dict()
        
    nx.write_gpickle(p, 'no_metadata.pkl')

The file size of `no_metadata.pkl` is still ~20 MB.

I'm not quite sure why this is the case. Is there a different disk storage format that I can use instead of pickling, that can handle `set`s and (optionally) `numpy` arrays? (Optional, because I can always opt to compute on the fly the `numpy` array based on node metadata.)

[1]: https://github.com/ericmjl/protein-interaction-network/

**Comment by hagberg** [comment]
Are you compressing the data?  That would help some.


```python
import networkx as nx
G = nx.fast_gnp_random_graph(10000,0.01)
print G.number_of_nodes(),G.number_of_edges()

import gzip
import bz2
import cPickle as pickle
with open('foo.pkl', 'w') as f:
    pickle.dump(G, f)

with bz2.BZ2File('foo.pkl.bz2', 'w') as f:
    pickle.dump(G, f)

with gzip.GzipFile('foo.pkl.gz', 'w') as f:
    pickle.dump(G, f)
```
```bash
[aric]$ ls -lh foo.pkl*
-rw-r--r-- 1 aric aric  16M Apr 20 17:51 foo.pkl
-rw-r--r-- 1 aric aric 4.1M Apr 20 17:51 foo.pkl.bz2
-rw-r--r-- 1 aric aric 5.4M Apr 20 17:51 foo.pkl.gz
```

**Comment by jfinkels** [comment]
or lzma: https://docs.python.org/3/library/lzma.html

**Comment by ericmjl** [comment]
Interesting. All compression methods worked on my disk, with the LZMA method compressing the most, though read/write times were a tad slower (not a deal breaker here), which means it is feasible. Thank you @hagberg and @jfinkels for the comments and help!

Meanwhile, I still remain curious about why the pickled Python object retains remains so large in size even after removing all attributes from the graph. Is there a reason for this?

**Comment by hagberg** [comment]
The empty dicts still take 160 bytes each or something like that.
Aric
