### ISSUE TITLE
Pagerank algorithms should verify that personalization is non-negative

### ISSUE THREAD

**Issue by hlin117** [networkx/networkx#2106]
We should raise an Error when input pageranks are negative, and check when each personalization is zero.

Example:

```
>>> import networkx as nx
>>> G = nx.DiGraph()
>>> G.add_nodes_from("ABCD")
>>> G.add_edges_from([("A", "B"), ("B", "D"), ("D", "B"), ("B", "C"), ("A", "C")])
>>> """
The graph network

(A) ----> (B) ----> (D)
   \      /
    \   /
     (C)
"""
>>> nx.pagerank(G)
{'A': 0.09985962280170124,
 'B': 0.35566461384457854,
 'C': 0.2934581626557564,
 'D': 0.25101760069796386}
>>> nx.pagerank(G, personalization={"A": 1, "B": 1, "C": 1, "D": 1})
{'A': 0.09985962280170124,
 'B': 0.35566461384457854,
 'C': 0.2934581626557564,
 'D': 0.25101760069796386}
>>> # The next calculation is invalid, but it doesn't catch it
>>> nx.pagerank(G, personalization={"A": 1, "B": -1, "C": -1, "D": -1})
{'A': -0.21266619043527665,
 'B': 0.4744408497018217,
 'C': 0.3239210217246239,
 'D': 0.4143043190088311}
>>> nx.pagerank(G, personalization={"A": 0, "B": 0, "C": 0, "D": 0})
ZeroDivisionError: float division by zero
```

For the last case, I've also seen the situation when the pagerank reaches 100 iterations (it doesn't converge).

I would like to work on this PR, if this issue is approved.

**Comment by hagberg** [comment]
I like catching confusing errors and we should do that.   I don't like so much the idea of checking input data for validity.  In this case the errors aren't that subtle or confusing to me.  If you get a negative page rank your input data is probably suspect and if you put zeros in the personalization parameter you'll get an explicit ZeroDivisionError.  

Was there something particularly difficult to understand with the results you got that we might clarify with a clearer message?

**Comment by hlin117** [comment]
I think a more interesting case if when we have something like this:
```
>>> nx.pagerank(G, personalization={"A": 1, "B": 1, "C": -1, "D": 1})
{'A': 0.12478059373545425,
 'B': 0.4444254316644426,
 'C': 0.11713245458380475,
 'D': 0.31366152001629843}
```
In this case, `C=-1`, but we still come out with valid pageranks. I've been in the situation before where pagerank is in the middle of my pipeline, and I unknowingly input negative values into the personalization.

I do agree that checking input data can be slow though, especially if the data is in a dictionary. If we're using `pagerank_scipy`, on the other hand, input validation is much faster, because the personalization gets converted into a numpy array.

**Comment by hagberg** [comment]
I think the user should check for valid input.  It's just going to be too hard to check for all combinations of strange input.
