### ISSUE TITLE
networkx problem with reading in gml files

### ISSUE THREAD

**Issue by ajpowel** [networkx/networkx#2108]
Hello --

The "read_gml" function/method in networkx doesn't seem to work with files containing large-ish graphs.

It was tested with a couple of different gml files (one from Gephi enclosed), & only the very simple graph worked (also enclosed).

Would you please correct this issue as soon as possible?

Many thanks!  

Best,

AJP
[lesmiserables.txt](https://github.com/networkx/networkx/files/243169/lesmiserables.txt)
[test_1.txt](https://github.com/networkx/networkx/files/243170/test_1.txt)

**Comment by hagberg** [comment]
This is a bug that is fixed in the current development version (2.0) of networkx.

**Comment by ajpowel** [comment]
Awesome!  

I checked my version:
**************************************************

pip show networkx
---
Metadata-Version: 1.1
Name: networkx
Version: 1.11
Summary: Python package for creating and manipulating graphs and networks
Home-page: http://networkx.github.io/
Author: NetworkX Developers

**************************************************

and tried to upgrade to 2.0:

**************************************************

pip install networkx --upgrade
Requirement already up-to-date: networkx in ./Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages
Requirement already up-to-date: decorator>=3.4.0 in ./Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages (from networkx)

**************************************************
But version 2.0 does not appear to be available via pip install.  

Would you please make the latest & greatest stable version (i.e., >= 2.0) available in pip?

Many thanks! 

Best,

AJP

**Comment by hagberg** [comment]
Version 2.0 isn't released yet.
Use
pip install https://github.com/networkx/networkx/zipball/master

**Comment by ajpowel** [comment]
ok thanks!  will do!

On 29 April 2016 at 17:20, Aric Hagberg <notifications@github.com> wrote:

> Version 2.0 isn't released yet.
> Use
> pip install https://github.com/networkx/networkx/zipball/master
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/networkx/networkx/issues/2108#issuecomment-215905672>
>



-- 
Regards, AJP
