### ISSUE TITLE
maximal_independent_set does not work for DiGraph

### ISSUE THREAD

**Issue by enj** [networkx/networkx#2109]
Currently [maximal_independent_set](https://github.com/networkx/networkx/blob/d7d906e1d16ef331da0bc1d149953e7532155acc/networkx/algorithms/mis.py#L70) returns the wrong results for a `DiGraph` because it uses the `G.neighbors` method which returns only the successor nodes in a `DiGraph`.  I believe the [all_neighbors](https://github.com/networkx/networkx/blob/13b373bf6938c077d1e61adc60a48cb910a75755/networkx/classes/function.py#L540) function should be used instead to make `maximal_independent_set` work correctly for both graph types.

**Comment by hagberg** [comment]
Is your suggestion a standard definition of maximal independent set for directed graphs?  It makes sense that it would be but I didn't find a definition after a little searching.  The alternative would be to return an error when the function is called with a directed graph.

**Comment by enj** [comment]
I am not sure if MIS applies to directed graphs or not actually.  I just noted that `all_neighbors` would give the correct result, and I did not particularly see a reason to raise an exception.  Then the user would be forced to use `to_undirected` to get the MIS (hence making an unnecessary copy of the `DiGraph`).  However, if the literature states that MIS only applies to undirected graphs, then raising an exception makes the most sense.

**Comment by hagberg** [comment]
Needs PR to raise exception if called with directed graph.
