### ISSUE TITLE
Website links to examples are dead

### ISSUE THREAD

**Issue by sahmed95** [networkx/networkx#2110]
Hi, 
The links on the page https://networkx.github.io/examples.html to [gallery](http://networkx.github.io/documentation/latest/gallery.html) and [complicated examples](http://networkx.github.io/documentation/latest/examples/) are dead. I understand that everything has been shifted to https://networkx.readthedocs.io/en/stable/ but the main website doesn't lead to any examples. Maybe a link to readthedocs can be provided in the examples page.

**Comment by hagberg** [comment]
Fixed in https://github.com/networkx/networkx-website/commit/2523f5e25fcacbc2204db73ea8d7cb964d81dbd7
