### ISSUE TITLE
MultiGraph.add_edge overwrites edges in certain non-explicit cases

### ISSUE THREAD

**Issue by thegreathippo** [networkx/networkx#2112]
```
>>> import networkx
>>> mg = networkx.MultiGraph()
>>> mg.add_edge("n1", "n2", weight=0)
>>> mg.add_edge("n1", "n2", key=0, weight=1)
>>> print(mg["n1"]["n2"])
{0: {'weight': 1}}
```
The same problem pops up when adding edges with `add_edges_from`:
```
>>> my_edges = [("e1", "e2", {"weight": 0}), ("e1", "e2", 0, {"weight": 1})]
>>> mg.add_edges_from(my_edges)
>>> print(mg["e1"]["e2"])
{0: {'weight': 1}}
```
It's a fairly fringe case, but potentially important when dealing with tuples of asymmetric size. The expected behavior would be for unspecified keys to never collide with specified keys. The problem seems to be [this](https://github.com/networkx/networkx/blob/992eec97fa68647ccd67f6e1f3faa743a443247e/networkx/classes/multigraph.py#L325-L332) piece of code, in `multigraph.py`'s `add_edge` method:
```
        if v in self.adj[u]:
            keydict = self.adj[u][v]
            if key is None:
                # find a unique integer key
                # other methods might be better here?
                key = len(keydict)
                while key in keydict:
                    key += 1
```
The simple fix that springs to mind is that in cases where we don't care enough to specify the key, we should use a non-int key that can't be reproduced (but can be copied); something like:
```
class UnspecifiedKey(object):
    _id = 0
    def __init__(self, _id=None):
        if _id is None:
            _id = self._id
            type(self)._id += 1
        self.id = _id

    def __eq__(self, other):
        if type(self) == type(other):
            return self.id == other.id

    def __hash__(self):
        return hash((type(self), self.id))

    def __copy__(self):
        return type(self)(self.id)
```
...which shouldn't raise any notable exceptions (actually, double-checking -- it breaks `test_remove_edges_from` [here](https://github.com/networkx/networkx/blob/d7d906e1d16ef331da0bc1d149953e7532155acc/networkx/classes/tests/test_multigraph.py#L213-L230), but I strongly suspect that's because the test _assumes_ that unspecified keys will increment from 0 upward; the equivalent test for `MultiDiGraph` _doesn't_ break, probably because it _doesn't_ make that assumption).

(Also, posting this issue only because I noticed it while dealing with my pull request, but didn't want to take anything else on -- just wanted to make a notation somewhere so I wouldn't forget to mention it!)

**Comment by hagberg** [comment]
Yes, that is the expected, possibly annoying, behavior of the way keys work with the current Mulitgraph class.  If you specify an existing edge in add_edge (including using the key) it will be replaced.
The only safe way is to check if the edge exists first.   We have considered changing this and the design needs some thought, #1654.

**Comment by thegreathippo** [comment]
Oops -- pardon! I missed the issue on account of looking for 'add_edges_from' instead of just 'add_edges'. Nevermind, then!
