### ISSUE TITLE
Latex formatting for code

### ISSUE THREAD

**Issue by domoritz** [networkx/networkx#2113]
On https://github.com/networkx/networkx/blob/v1.11/doc/source/reference/drawing.rst

<img width="252" alt="screen shot 2016-05-02 at 15 14 51" src="https://cloud.githubusercontent.com/assets/589034/14964962/ac1af3a2-1078-11e6-9304-9b584f41e88e.png">

**Comment by Michael-E-Rose** [comment]
The correct link is http://networkx.readthedocs.io/en/stable/reference/drawing.html.

**Comment by dschult** [comment]
In v1.11 we still used a default formatting for sphinx single-ticks of math mode. The error is that in combination with this doc_string using single ticks around that word. In the latest docs the trouble has been fixed (by changing the formatting for single ticks to be ```'obj'```)
http://networkx.readthedocs.io/en/latest/reference/drawing.html
(or https://github.com/networkx/networkx/blob/master/doc/source/reference/drawing.rst)
