### ISSUE TITLE
Branchings.py - A new approach

### ISSUE THREAD

**Issue by Loveuse** [networkx/networkx#2115]
Hi everybody! I'm glad to be here! 
I am working on my master degree thesis using the Edmonds algorithm and I made some changes to the original Networkx implementation.
Particularly, I removed the two structures that store the graphs and branchings for every step, in favor of an unique structure able to rebuild the graphs needed for the second phase of the algorithm. 
I would like that what I made could be part of networkx.
I hope this is the right place to post my patch!
[branchings.patch.tar.gz](https://github.com/networkx/networkx/files/246766/branchings.patch.tar.gz)

**Comment by Michael-E-Rose** [comment]
Welcome. Are you familiar with the concept of forks and pull requests? NetworkX has a section on it: https://networkx.readthedocs.io/en/stable/developer/index.html

**Comment by Loveuse** [comment]
No, but I am going to be familiar with them! Thank you

**Comment by Michael-E-Rose** [comment]
No need to close the issue. You can leave it open and refer to it from the pull request (PR), which will get it's own number. Once the PR has been merged (i.e. accepted), this issue can be closed as well.

Also refer to the [Wiki](https://github.com/networkx/networkx/wiki) for NetworkX' coding style.

**Comment by chebee7i** [comment]
Glad to see this portion of the code getting some extra eyes on it!  @Loveuse I will try to take a look at this (#2117) in the next few days.
