### ISSUE TITLE
Multigraph key simplification?

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#2119]
It seems that the way we handle multigraph edge keys is sometimes hard to maintain (see #2107 but true elsewhere too).  Is there a way to handle it more simply?

Some thoughts include: 
- defaulting to ```key=None``` for all add_edge actions. The first ```G.add_edge(1,2)``` gives ```(1,2,None)```. The second does nothing! To get a multiedge one must specify a key.
- default to using a UUID for the key to each multiedge.  (unique key within the MultiGraph and actually across all MultiGraphs).  Here ```G.add_edge(1,2)``` twice does add two separate edges.

Other thoughts?

**Comment by chebee7i** [comment]
https://github.com/networkx/networkx/issues/1654 https://github.com/networkx/networkx/pull/1376

Can you explain how these proposals solve the problems you mentioned?

I think the first option makes the API confusing---if it is a multigraph and we want to say that explicit keys are required to get multiedge functionality, then the API should just make the key be required. But doing so is overkill, since one often doesn't care about the particular key that was assigned.

The second option could work, but my opinion is that uuid is overkill. Either way, it should be customizable. I also think an always increasing global integer could work just as well, while being more memory efficient.  In this case, the key signifies the total number of edges that have ever been added to the graph.

```
G = nx.MultiDiGraph()
G.add_edge(0, 1)  # key = 1
G.add_edge(0, 1)  # key = 2
G.add_edge(1, 2)  # key = 3
G.remove_edge(0, 1)
G.add_edge(3, 4)  # key = 4
```

**Comment by jfinkels** [comment]
@chebee7i Auto-incremented integers could be just as uninformative as UUIDs. If I add and remove many edges, I may end up with several edges joining a pair of nodes with keys that appear to be totally random integers.

**Comment by chebee7i** [comment]
Yes, so the argument is: if one is in favor of uuids (which I am not), then one should like auto-incremented, global integers more since they use less memory, are faster to generate and handle too. They also don't put potentially sensitive information inside a graph that you might distribute, while uuid1 does.

**Comment by chebee7i** [comment]
My broader point is that if the user doesn't care about the meaning, then global ints are better than uuids, and they still have some meaning that is at least relevant to the graph. If the user wants to have keys that are meaningful in other ways, we should allow them to provide a generator.

**Comment by dschult** [comment]
Perhaps I(we) need to state more clearly what the problems are with the current key setup...
I suspect that most of the trouble arises when we design code for Graph and then try to adapt it to work with MultiGraph as well.

Here's the most recent trouble:  we want to add an edge (using a default key) and then update its datadict. How do we figure out which edge we just added? In this case the workaround was to use the fact that we are creating the MultiGraph from scratch so given the way defaults are assigned we know the most recent edge must have the maximum edge key. But this seems likely to come back and bite us since it depends on the algorithm for assigning default edge keys.

**Comment by chebee7i** [comment]
Yeah, that is a pain and it is one reason why I advocated in #1376 that the autogenerated key should be returned by `add_edge`. They is required to query the graph for a particular multiedge. If we provide a mechanism to autogenerate that required key, then it seems reasonable to me that we ahould return it. Or not provide the mechanism at all, but that seems rather awkward for users.

**Comment by dschult** [comment]
Right -- if we don't return it, it is hard to figure out what it is.

If we do return the edge key, what do we return from ```add_edges_from```? Also, do we return just the key, or an edge tuple (u,v,key)?

If we remove the default key generation, that makes it harder for users to create a MultiGraph. Can we make it less awkward by providing key generation methods they can use? If the MultiGraph has an edge counter that simply counts how many edges have ever been generated, then we could provide ```G.new_edge_key()``` and a user could do:

    G.add_edge(u,v,G.new_edge_key())
    G.add_edges_from((u,v,G.new_edge_key()) for u,v in elist)
    key=G.new_edge_key()
    G.add_edge(u,v,key)
    multi_elist = [(u,v,G.new_edge_key()) for u,v in elist]
    G.add_edges_from(multi_elist)

Essentially we are still uing a default edge key generator, but we're making it available outside of the add_edge method.  Of course, we are requiring users to use it explicitly, so it's more work for them.

**Comment by chebee7i** [comment]
My opinion is that we do both: return the key and expose the generation mechanism :)  

As to what is returned, I could see either the key or the tuple. No strong opinion. In #1376, I provided a custom subclass that I use for primarily edge-based algorithms. It has an extra dict that associates keys to (u, v, data) tuples. This enables quicker access to and iteration over edges.

**Comment by hagberg** [comment]
We do provide a slightly awkward way to get the edge keys for a pair of edges

```
In [1]: import networkx as nx
 
In [2]: G = nx.MultiGraph()

In [3]: G.add_edge('a','b', color='red')

In [4]: G.add_edge('a','b', color='blue')

In [5]: G.get_edge_data('a','b')
Out[5]: {0: {'color': 'red'}, 1: {'color': 'blue'}}

In [6]: list(G.get_edge_data('a','b'))
Out[6]: [0, 1]
```

**Comment by chebee7i** [comment]
By luck, I found my original ticket on this point! #278

We decided at that time not to implement it. I still needed it, so my own implementations of `MultiDiGraph` have had this feature for some time. In that sense, I am not particularly tied to the decision this time around either, but I'm chiming in nonetheless. :)

**Comment by jfinkels** [comment]
What seems to make sense to me is:

1. Add a `new_edge_key(u, v)` method to the `MultiGraph` class. This method takes the nodes as input and generates a new edge key, presumably based on information about the current edge keys for edges currently joining the nodes. Most of the time, users can ignore this method, but subclasses can override this.
2. The `add_edge` function uses `new_edge_key` and returns the key of the edge created.
3. The `add_edges_from` method returns a list of keys in the same order as the input iterable.

So for example:

```python
>>> G = nx.MultiGraph()
>>> G.add_edge(0, 1)
0
>>> G.add_edges_from([(0, 1), (1, 2), (0, 1)])
[1, 0, 2]
>>> G.new_edge_key(0, 1)
3
>>> G.new_edge_key(0, 1)  # should be the same as the edges haven't changed
3
```

**Comment by dschult** [comment]
I like this approach.

It does mean there is one more API difference between Graph and MultiGraph. But if we think of the Graph class as using edge key ```None``` for all edges then ```Graph.add_edge``` does return the edge key (no return statement means return value ```None```. :)

**Comment by hagberg** [comment]
I think @jfinkels idea is the simplest approach that doesn't break things too much.  So let's do that.
