### ISSUE TITLE
dict.pop in json_graph.adjacency_graph

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#2120]
Why are we copying the dict `d` and popping from it instead of just looking up the value? 
(near line 150 of `networkx/readwrite/json_graph/adjacency.py`)

**Comment by hagberg** [comment]
Not sure.  I probably had a good reason to do that at some point 😄

**Comment by dschult** [comment]
We are copying and popping and then using the result to set node attributes. The pop saves us an id_ attribute for every single node.
