### ISSUE TITLE
Functions in draw.nx_pylab can not draw self-loop edges

### ISSUE THREAD

**Issue by litaotju** [networkx/networkx#2121]
Using the code bellow:

import networkx as nx
import matplotlib.pylab as plt
g = nx.DiGraph()
g.add_edge(1.1)
nx.draw_networkx(g)
plt.show()

There is only one node in the graph, and no edges are displayed. I don't kniw this is a defeat or in some other purpose to keep self-loop edge away from drawing in the figure.

Because in some sceniros , to display self-loop edges do make sense. Here I propose to add the self-loop edges  drawing feature in nx_pylab module , and I will work on it if this is indeed necessory.

**Comment by hagberg** [comment]
It's not so simple to do this nicely.  You are welcome to work on an implementation.  The long-term plans are to rewrite the matplotlib graph drawing in a separate module that could include self-loop drawing and many other features like parallel edge drawing, interactive adjustment of layouts, etc but so far nobody has taken that on.

**Comment by hagberg** [comment]
Closed due to inactivity.
