### ISSUE TITLE
Can't read edges from adjacency matrix with read_pajek

### ISSUE THREAD

**Issue by chase0213** [networkx/networkx#2123]
Hi,

I've been trying to import a graph from a file with `read_pajek` method, and I found that adjacency matrix is not parsed by the method.

https://github.com/networkx/networkx/blob/master/networkx/readwrite/pajek.py

Are there any reasons or concepts not to implement it?

Actually, I found matrix descriptions in Pajek datasets, such as [Journals](http://vlado.fmf.uni-lj.si/pub/networks/data/2mode/journals.htm).

**Comment by rafguns** [comment]
Are you referring to the [Pajek matrix (*.mat) format](http://wiki.cns.iu.edu/pages/viewpage.action?pageId=2200189)? This is indeed not (yet) implemented in networkx, only the *.net format is currently supported.

I assume that the core developers are open to pull requests that implement reading (and writing) this additional format.
