### ISSUE TITLE
Bug in categorical_node_match?

### ISSUE THREAD

**Issue by rstmr** [networkx/networkx#2125]
I just came across a failing unit test for 'networkx.algorithms.isomorphism.match_helpers.categorical_node_match':
```
from nose.tools import assert_true
from networkx.algorithms import isomorphism as iso


def test_categorical_node_match():
    nm = iso.categorical_node_match(['x', 'y', 'z'], [None]*3)
    assert_true(nm(dict(x=1, y=2, z=3), dict(x=1, y=2, z=3)))
    assert_true(not nm(dict(x=1, y=2, z=2), dict(x=1, y=2, z=1)))
```
It's the second one that fails.

Looking into the function, I found this:
```
categorical_doc = """
Returns a comparison function for a categorical node attribute.

The value(s) of the attr(s) must be hashable and comparable via the ==
operator since they are placed into a set([]) object.  If the sets from
G1 and G2 are the same, then the constructed function returns True.

Parameters
----------
attr : string | list
    The categorical node attribute to compare, or a list of categorical
    node attributes to compare.
default : value | list
    The default value for the categorical node attribute, or a list of
    default values for the categorical node attributes.

Returns
-------
match : function
    The customized, categorical `node_match` function.

Examples
--------
>>> import networkx.algorithms.isomorphism as iso
>>> nm = iso.categorical_node_match('size', 1)
>>> nm = iso.categorical_node_match(['color', 'size'], ['red', 2])

"""

def categorical_node_match(attr, default):
    if nx.utils.is_string_like(attr):
        def match(data1, data2):
            return data1.get(attr, default) == data2.get(attr, default)
    else:
        attrs = list(zip(attr, default)) # Python 3

        def match(data1, data2):
            return all(data1.get(attr, d) == data2.get(attr, d) for attr, d in attrs)
    return match
```

So, basically `categorical_node_match` compares the set of values for the nodes. Therefore it evaluates to `True` for nodes with different attribute dicts, because set of values of these attribute dicts is the same. I don't see why the function would do this (and by the docs, this is intended behavior?!).

**Comment by chebee7i** [comment]
Has this always been failing? That would strike me as odd, since no one has brought it up before.

The the intended behavior, can you explain why you think it is important that two nodes have the same attribute dictionaries?  If I have X number of attributes on node A and Y number of attributes on node B, but my isomorphism tests only cares about attribute 'weight', then it seems the only that that should matter is that `'weight' in set(X).intersection(set(Y))`.

**Comment by chebee7i** [comment]
And in fact, the 'weight' attribute need not even be in the attribute dictionaries, since this function accepts a default value for whatever attributes you care about.

**Comment by rstmr** [comment]
My mistake, I'm sorry. I had NetworkX installed with pip before I now forked it. I got confused by the different files and this bug has already been fixed and they're not put into sets anymore as can be seen in the code (even though the docs say so).

**Comment by chebee7i** [comment]
No worries! I'm just happy that someone is looking at and using this code.  The more eyes, the better.
