### ISSUE TITLE
Closeness centrality - normalisation flag - clarity necessary for what normalisation means in this context.

### ISSUE THREAD

**Issue by shongololo** [networkx/networkx#2126]
When trying the `networkx.algorithms.centrality.closeness` method it seems to return the same values whether setting `normalisation` to true or false.

Looking at the code:

```
closeness_centrality = {}
for n in nodes:
    sp = path_length(G,n)
    totsp = sum(sp.values())
    if totsp > 0.0 and len(G) > 1:
        closeness_centrality[n] = (len(sp)-1.0) / totsp
       # normalize to number of nodes-1 in connected part
        if normalized:
            s = (len(sp)-1.0) / ( len(G) - 1 )
            closeness_centrality[n] *= s
    else:
        closeness_centrality[n] = 0.0
```

In most cases the length of the `sp` dictionary will be the same as the number of nodes in the graph, thus multiplying `closeness_centrality[n]` by 1 and having no effect?

It seems like the intent is to normalise values across disconnected graphs?

**Comment by shongololo** [comment]
On further investigation normalisation doesn't appear to work for single node or whole graph. Is there something I'm missing?

**Comment by dschult** [comment]
The intent is indeed to normalize relative to the minimum distance possible within the component. I think the documentation is fairly clear about this. But there are other issues going on.

In the cited article, inverse closeness is the sum of the distances divided by (number of nodes -1). Closeness is then (number of nodes -1) divided by sum of distances.  Let N be the number of nodes and n be the number of nodes in the component.

Questions:
- without normalization we have ```C = (n-1)/sum_of_dict```.  So normalization already occurs even when ```normalized is False```. That should be made clear in docs.
- with normalization we have ```C = (n-1)/(N-1) * (n-1)/sum_of_dict``` which looks like the reciprocal of what we want to multiply by. Shouldn't the scale factor ```s=(n-1)/N-1)``` be instead ```s=(N-1)/(n-1)```?

The tests don't check normalization so its hard to tell what was intended.

**Comment by hagberg** [comment]
I'm pretty sure I'm guilty here https://github.com/networkx/networkx/commit/7df946596899468c0b114adf3fb581d830b7c051.
I'm not sure what the right answer is.

**Comment by shongololo** [comment]
If I'm not mistaken, Closeness centrality by default takes into account the number of nodes, i.e.
`(n-1)/sum(distances from node to all others)`

So in one sense normalisation is a misnomer? That said, in my case I would find it beneficial to simply return the raw sum of distances.

**Comment by hagberg** [comment]
Some earlier discussion 
#824
https://groups.google.com/forum/?hl=en#!topic/networkx-discuss/ZfCQDrZcvYI
#241

**Comment by dschult** [comment]
Following up on the previous discussion, Wasserman and Faust do indeed suggest an "improved" closeness centrality measure that scales as we scale it.  The result is "a ratio of the fraction of actors in the group who are reachable, to the average distance" to the reachable actors [W&F pg 201].  So we've got the right scaling and it matches our documentation.

The only issue I see here is the word "normalized" and whether the documentation sufficiently stresses what that means. I think @shongololo was able to figure out what was going on... but was concerned that it might not be what was intended. I'll change the docs... 

Should I change the name "normalized"?

BTW, to get the sum of the distances on can use the shortest_path routines directly:

    dict((node, sum(d for _,d in nx.single_source_shortest_path_length(G, node))) for node in nodes)

**Comment by hagberg** [comment]
Yes, "normalized" does seem a little bit of a stretch for what this does.  Got a better name?

**Comment by shongololo** [comment]
@dschult the 'improved' closeness centrality is the method I like to use.

Perhaps an 'improved_formula' flag with an explanation that this 'normalises' based on Wasserman and Faust's method vs. the conventional method?

**Comment by hagberg** [comment]
Or we could just write another function with a different name.

**Comment by hagberg** [comment]
See #2391 for more confusion over normalization.

**Comment by dschult** [comment]
PR #2595 fixes this.
