### ISSUE TITLE
Inconsistent GML Underscore Handling in Reading/Writing with Proposed Solution

### ISSUE THREAD

**Issue by jmercouris** [networkx/networkx#2131]
In the official GML documentation (http://www.fim.uni-passau.de/fileadmin/files/lehrstuhl/brandenburg/projekte/gml/gml-technical-report.pdf) there are a list of regular expressions representing valid strings for every field. In the field for keys; the regular expression is:

`::=[a-z A-Z][a-z A-Z0-9]*`

In the tokenization for reading in networkx/readwrite/gml.py there is the following pattern:

(parse_gml_lines)
`r'[A-Za-z][0-9A-Za-z_]*\b',  # keys`

As you can see this supports key names with underscores in them such as "underscore_string". This by itself would be fine, the issue results in the incongruence with the writing keys which are:

(generate_gml)
`valid_keys = re.compile('^[A-Za-z][0-9A-Za-z]*$')`

As you can see, the specifications for reading and writing valid GML are different. I believe they should be the same. Personally I am a proponent for allowing underscores even though it is not in the official documentation. Thank you for your time.

**Comment by hagberg** [comment]
I'd suggest to only to write valid GML.  But I don't mind accepting somewhat out-of-spec data on input - in this case underscores.  Of course that means you could potentially read a (broken) GML file with NetworkX that you can't output with the GML writer.

**Comment by jmercouris** [comment]
The thing is though, that the GML spec was written by c or java developers who prefer the camel case preference. I think there is a large community of python users who use underscores in their variable names, if the writer is not to be changed, then there should be some sort of utility that automatically converts parameters with underscores to a camel case notation or something of the like.

**Comment by hagberg** [comment]
Having a remove_underscores converter would be OK.  

It's too bad the spec doesn't include underscores.  But if we don't write GML spec files then the next Github issue will be "NetworkX GML files can't be read by X"

**Comment by jmercouris** [comment]
Okay, so should I submit a PR or something? should we have a function or
just a simple regex replace?

**Comment by dschult** [comment]
I agree that we shouldn't write non-GML files even if that means we can read a file we can't produce.
In this case underscores can be read, but can't be written to a GML file.
I'm going to close this issue.
