### ISSUE TITLE
relabel_nodes adds a graph attribute when copy=True

### ISSUE THREAD

**Issue by movermeyer** [networkx/networkx#2134]
I would have expected the following to work:

```
import networkx as nx
graph_a = nx.DiGraph()
graph_b = nx.relabel_nodes(graph_a, {}, copy=True)
print "graph_a.graph", graph_a.graph
print "graph_b.graph", graph_b.graph
assert graph_a.graph == graph_b.graph
```

However, it does not since [_relabel_copy attempts to copy a non-existent graph attribute, 'name'](https://github.com/networkx/networkx/blob/1675a824d6cdb17c3144ef46ff52a0c2b53a11d1/networkx/relabel.py#L150).

I would have expected relabel_nodes to only change the node labels, while maintaining all graph/node/edge attributes.

**Comment by dschult** [comment]
I agree that this handles the 'name' attribute incorrectly. Fix is on the way.
