### ISSUE TITLE
Implement algorithms for reverse line graph

### ISSUE THREAD

**Issue by jachymb** [networkx/networkx#2139]
Implement algorithm for reconstruction of original graph from a line graph. The Roussopoulos' algorithm or  MARINLINGA.  see http://mathworld.wolfram.com/LineGraph.html

**Comment by JamesClough** [comment]
In case anyone else is working on this I have implemented Roussopoulos' algorithm and so will create a pull request with this feature soon.

**Comment by chebee7i** [comment]
This was merged in #2241.
