### ISSUE TITLE
Misquoted max iteration during exception handling for hits

### ISSUE THREAD

**Issue by ssmolash** [networkx/networkx#2140]
When `max_iter` is set to 1 and hits fails to converge, exception message states that hits failed to converge after 3 iterations. Should the following line be `i-1` instead? I'd be happy to write a pull request for this.

https://github.com/networkx/networkx/blob/d7d906e1d16ef331da0bc1d149953e7532155acc/networkx/algorithms/link_analysis/hits_alg.py#L111

**Comment by dschult** [comment]
Yes, you are correct. And a PR would be great. Thanks!

**Comment by jfinkels** [comment]
Fixed in pull request #2142.

**Comment by jfinkels** [comment]
Thanks!
