### ISSUE TITLE
Also list dependencies in setup.py

### ISSUE THREAD

**Issue by timdiels** [networkx/networkx#2147]
I've just now installed master and noticed scipy and other things listed in requirements.txt weren't installed with it. Could they be added to setup.py's `install_requires` please?

**Comment by OrkoHunter** [comment]
Hey @timdiels, there was a discussion about it some time ago [here](https://github.com/networkx/networkx/issues/1661). As I recall, `install_requires` was not supposed to list _all_ the dependencies of networkx.

**Comment by timdiels** [comment]
Hi @OrkoHunter. I see, so `numpy` and such are optional dependencies then. You are right not to include them in `install_requires`, but you should include them in `extras_require` as setup.py. If you make an `extras_require={'all': [all deps]}`, I could depend on those from a setup.py with `networkx[all]`. (I generate a requirements.txt from my list of dependencies using `pip-compile` (pip-tools) which I then use across my testing venv's; when I list `networkx==version` in it, I get minimum dependencies only, so I'd like `networkx[all]==version`.)
