### ISSUE TITLE
eigenvector_centrality_numpy gives (sometimes) smaller zero values

### ISSUE THREAD

**Issue by philippschw** [networkx/networkx#2155]
I noticed that the function eigenvector_centrality_numpy gives (sometimes) for nodes values that are smaller than zero. I am sure that is not the expected behavior!

Example csv file:
https://www.dropbox.com/s/4lhklpq2ss4t459/example.csv?dl=0
```
testdf = pd.read_csv('example.csv', index_col=0)
rm = testdf .values
G= nx.from_numpy_matrix(rm)
n_eigenvector = nx.eigenvector_centrality_numpy(G)
min(n_eigenvector.values())
```
Note, if I just run the code several times 8 out of 10 times the smallest eigenvector values is smaller than 0.

**Comment by hagberg** [comment]
I just ran this and got -1.054905350542667e-18 for the minimum of the eigenector.  That is effectively floating point zero on my machine.

**Comment by philippschw** [comment]
@hagberg 
Yes, exactly but an eigenvector has to be always larger than 0 !
For reference: http://www.math.harvard.edu/archive/20_spring_05/handouts/ch05_notes.pdf

**Comment by hagberg** [comment]
The eigenvector that goes with your largest eigenvalue (which is about 398077) is not the zero vector.  It does have some entries that are close to zero.  Try plotting it to see, use `plot(sorted(n_eigenvectors.values())`.
 Note also that the result from the `eigenvector_centrality_numpy` algorithm is normalized with the "l2-norm" - the sum of the squares of the values is 1.
