### ISSUE TITLE
maximal matching documentation

### ISSUE THREAD

**Issue by sanghack81** [networkx/networkx#2156]
networkx.algorithms.matching.maximal_matching is documented as 

"Find a maximal cardinality matching in the graph."

If it is just "maximal matching", then the use of 'cardinality' seems confusing.
Since the algorithm is not "maximum cardinality" matching.

For example, given a graph 'c'--'a'--'b'--'d' 
the method might return {('a', 'b')} as a maximal matching, which is not a maximum cardinality matching {('a', 'c'),('b', 'd')}.

```
import networkx as nx
g=nx.Graph()
g.add_edge('b','a')
g.add_edge('c','a')
g.add_edge('b','d')
print(nx.maximal_matching(g))
```

(The above test depends on the order of edges, which is not deterministic. If you get two edges as a result, you might restart python console and rerun the code.)

Could you remove 'cardinality' from the document?

**Comment by hagberg** [comment]
You are right, that is confusing.  Thanks for pointing this out.
