### ISSUE TITLE
add_path adds edges with a single node as endpoints

### ISSUE THREAD

**Issue by heltonbiker** [networkx/networkx#2161]
When I add a path where one or more consecutive nodes have the same value, an edge is created having that same node as endpoints:

```
import networkx

graph = networkx.Graph()

graph.add_path([1,2,2,3])

print graph.nodes()
print graph.edges()

> [1, 2, 3]
> [(1, 2), (2, 2), (2, 3)]
> ----------^ edge with same endpoints
```

This behavior has given me a little trouble till I figured it out, and I was a bit surprised that a collapsed edge was even created in this case, since I expected that consecutive nodes with the same value wouldn't be considered an edge. On the other hand, I'm not experienced with graph theory, so perhaps this is what should happen after all.

Anyway, I am not sure this violates some test or not (or even if there is a test for this), so that's why I am opening this issue.

**Comment by dschult** [comment]
An edge from a node to itself is often called a self-loop. The ability to create self-loops as part of a path is a "feature" not a "bug", though I must admit it does not get used very often. 
If you can figure out different wording in the documentation that would have helped you avoid this issue please let us know.

**Comment by heltonbiker** [comment]
@dschult thanks for the reply.

As I imagined, the self-loops are a valid construct for graphs, and as such the `add_path` behavior is valid as it is.

What I would imagine, as a possibility, is to add some flag or "mode" to the method, or even create a separate method that would avoid creation of self-loops.

But frankly, any of these two alternatives is somewhat ugly, and an unnecessary pollution of the API.

I'm gonna take a look at the docs for `add_path` and perhaps think of a way to improve it if needed.

**Comment by hagberg** [comment]
You could use itertools.groupby to remove repeated elements in your list.

```python
In [1]: l = [1,2,2,3,2]

In [2]: import itertools

In [3]: [i for i,_ in itertools.groupby(l)]
Out[3]: [1, 2, 3, 2]
```
