### ISSUE TITLE
Fastest way to instanciate a digraph

### ISSUE THREAD

**Issue by vallettea** [networkx/networkx#2162]
Hello,

I'm using `G = DiGraph(data = edges)` to instanciate a networkx graph and it takes me about half a second (22k nodes and 60k edges).

Is there a faster way ?
Thanks

**Comment by hagberg** [comment]
That is the fastest way if you have a container of edge tuples.   It takes less than 200ms on my setup.
```python
In [1]: import networkx as nx

In [2]: G = nx.gnm_random_graph(22000,60000)

In [3]: edges = list(G.edges())

In [4]: %timeit G = nx.DiGraph(edges)
10 loops, best of 3: 165 ms per loop
```

**Comment by vallettea** [comment]
thanks for me it takes about 600ms but my nodes are custom objects.
So I guess there is no better way...

**Comment by dschult** [comment]
If your nodes are custom objects, you may be able to save a little time in the instantiation (but pay for it with lookups later) by using integers for nodes and keeping a list of the custom objects.  When you get graph results with integers as nodes and need to use the custom objects you'd look up the custom object in the list using the node (an integer) as the index.   Not sure it would speed up the overall processing--depends how much you would have to do lookups.
