### ISSUE TITLE
DiGraph arrowheads not colored properly with numeric edge_color

### ISSUE THREAD

**Issue by ChrisMyers** [networkx/networkx#2163]
In draw_networkx_edges, the edge_color argument can be passed in as a numeric list/array which gets mapped to colors via edge_cmap, edge_vmin, edge_vmax.  Even though the edges are colored correctly, the mapped edge_colors do not get attached correctly to the arrow heads drawn for a DiGraph.  (Note: arrowheads are colored properly if a non-numeric edge_color list is passed.)  Even though the arrow colors are set to the edge colors (arrow_colors=edge_colors), for the numeric mapping case, edge_colors=None and the colors are instead set directly in the edge_collection.  No such similar mapping is carried out for the arrow_collection.  One can replicate the same "if edge_colors is None" logic inside the arrow drawing block (setting instead the array for the arrow_collection), but perhaps there is a cleaner way to organize this so as not to duplicate that logic.

**Comment by hagberg** [comment]
That code is patches on hacks and really does need a cleaner overall approach (and proper arrow drawing).  But maybe another patch like you suggest is the best approach at this point.

**Comment by hagberg** [comment]
We can add this feature to #2760 which is making "proper" arrows.
