### ISSUE TITLE
Problem 'Graph' object has no attribute 'successors'

### ISSUE THREAD

**Issue by Filip90** [networkx/networkx#2165]
Hi. I don't know why but when I run my script show this problem:
'Graph' object has no attribute 'successors'

I installed the package networkx 2.0 from GitHub so I don't know how resolve it. Thank you

**Comment by dschult** [comment]
DiGraph has successors and predecessors. But Graph only has neighbors.
This basic tutorial has some more details:
http://networkx.readthedocs.io/en/stable/tutorial/index.html
