### ISSUE TITLE
alghoritm used in single_source_shortest_path subroutine

### ISSUE THREAD

**Issue by maq123** [networkx/networkx#2166]
Hi,

I've been inspecting `networkx/networkx/algorithms/shortest_paths/unweighted.py`  file and the documentation but I am not seeing any information about exact algorithm implemented.

Could it be clarified is it some home brewed solution used?

Thx.

**Comment by maq123** [comment]
Will it be safe to state that BFS would *always* give the *same* result as Dijkstra?
Spent some time reading about it and I got quite confused.

**Comment by dschult** [comment]
Dijkstra considers edges with a weight and finds the lowest weighted path.
BFS treats all edges the same (essentially using weight=1 for every edge).
The routines give the same result if every edge weight is 1.

Note though that both routines use an arbitrary ordering of neighbors when
traversing the graph.  That order can affect how ties are resolved when
finding
shortest paths. If two paths are the same length you may get either of these
paths depending on the order in which neighbors are reported. So it is
possible
to have BFS report different results for the same graph.  Thus BFS can
differ
from Dijkstra in this way also.

**Comment by maq123** [comment]
Thank you, now I get the subtle difference!
