### ISSUE TITLE
temporal networks

### ISSUE THREAD

**Issue by Wuyanan520** [networkx/networkx#2169]
whether are there some implementations about temporal networks?
if i hava a temporal networks' data looks like this:
![image](https://cloud.githubusercontent.com/assets/16913304/16193316/fccf12a0-3720-11e6-984f-6ba4a880d7cb.png)
how to read it to a  temporal networks graph?
if there is a weighted networks data, i can do it look like this:
![adqlkz okme9 p0smip7 t0](https://cloud.githubusercontent.com/assets/16913304/16193292/d4f18e7a-3720-11e6-8978-3d7780fcf8b7.png)
I failed to found whether the networkx has the same methods
if not, My idea is  to with edge attributes stored timestamp, it's ok?

**Comment by MridulS** [comment]
Storing time stamps as edge attributes is not a problem.

If you are working with actual date/time (something like "13/04/2015 10:20 AM")  I would recommend using https://docs.python.org/3/library/datetime.html objects as edge attributes, easier to manipulate and play with.

Hope this helps :)

**Comment by dschult** [comment]
Also, with read_weighted_edgelist() the attribute is named 'weight'.
To name it 'time' use:

G = nx.read_edgelist(ss, data=(('time', int), ))  # int could be float or
datetime type

**Comment by Wuyanan520** [comment]
@MridulS  @dschult whether you aware that line 1 and line 10 (please see sample file i provide),node1 and node2 have two timestamp,so i think that one way is to create graph using nx.MultiGraph()

**Comment by Wuyanan520** [comment]
I creat the graph looks like:
![qq 20160617201448](https://cloud.githubusercontent.com/assets/16913304/16218663/8a69477a-37b2-11e6-9765-9bf90834aff1.png)
it seems ok
if I want to copy the edge_attr of (1,2) to a new edges, what should i do?

**Comment by hagberg** [comment]
If you want specific handling of edge attributes for mulitgraphs you'll need to write your own code to transform your data input.    If you post an example of your input and desired output we can help you.
