### ISSUE TITLE
[Improvement] Graph subscript notation - creating a custom dict-like object?

### ISSUE THREAD

**Issue by CrazyPython** [networkx/networkx#2171]
For example, the subscript notation could return a wrapper class like this:
```
class WrapperDict(object):
    def __init__(self, basedict):
        self.basedict = basedict
        self.__getitem__ = basedict.__getitem__
```

This way, when programmers mistakenly assign to the resulting dictionary, `TypeError: 'int' object does not support item assignment` is raised instead of messing up the graph's internal state. Another fix would be copying the dictionary, but that might use unnecessary computation. A helper method could be defined to easily copy the wrapper dictionary.

**Comment by hagberg** [comment]
So far we have been trying to avoid custom classes for performance reasons.  I'm not sure I understand what you are proposing to add here.  We definitely allow users to mess up the internal data structures in any way they like and are trusting that if they do that they know what they are doing.
