### ISSUE TITLE
MinCost Max flow: MultiGraph and MultiDiGraph not supported (yet)

### ISSUE THREAD

**Issue by jliebana** [networkx/networkx#2174]
Hi,

I want to execute the max_flow_min_cost function for a multidigraph but I get the error:

>   File "/usr/lib/python2.7/site-packages/networkx/algorithms/flow/utils.py", line 100, in build_residual_network
>     'MultiGraph and MultiDiGraph not supported (yet).')
> 
> NetworkXError: MultiGraph and MultiDiGraph not supported (yet).

Is there a plan to implement this? I couldn't find any clue about it.

Thanks!

**Comment by dschult** [comment]
You need to figure out how best to compute the flow between two nodes with more than one edge between them (this depends on the problem). Once you do this, create a new Graph from the MultiGraph with the edges acting as a combined version of the multiedges. Run max_fow_min_cost on the Graph.

**Comment by jliebana** [comment]
Uhm that is an option, but that's only a (potentially problematic) workaround, as if I have to combine the cost and the capacity of multiple edges in 1 I will lose information, and the option of selecting "one, none, some or all" for the max flow, it would be limited to "none or all".

**Comment by hagberg** [comment]
Another approach would be to add extra nodes on the parallel edges to transform to a graph with unique edges, e.g. A->B, A->B transforms to  A->x->B, A->y->B

**Comment by jliebana** [comment]
That solution worked better. I added those nodes as you proposed, and then I kept the weight and capacity in the edge A->x, but put infinite capacity and 0 weight for the edge x->B (so the cost and flow is kept). Thanks for the idea @hagberg .
