### ISSUE TITLE
'module' object has no attribute 'read_dot'

### ISSUE THREAD

**Issue by Eisenbarth** [networkx/networkx#2175]
Hello

I noticed a little problem with the import of the function read_dot.
In version 1.9.1 there is no problem :
```sh
$ pip freeze
decorator==4.0.10
networkx==1.11
pygraphviz==1.3.1
```

```python
import networkx as nx

nx.read_dot("file.dot")
```

But recently I have upgrade the libs in my project and networkx is now in version 1.11 :

```sh
$ pip freeze
decorator==4.0.10
networkx==1.9.1
pygraphviz==1.3.1
```

```python
import networkx as nx

nx.read_dot("file.dot")
```
Result :
Traceback (most recent call last):
  File "parse_dex_opcodes.py", line 121, in <module>
    main()
  File "parse_dex_opcodes.py", line 24, in main
    graph = load_call_graph(args.call_graph_path)
  File "parse_dex_opcodes.py", line 29, in load_call_graph
    return nx.read_dot(call_graph_path)
AttributeError: 'module' object has no attribute 'read_dot'

I should write instead : 
```python
import networkx as nx

nx.drawing.nx_agraph.read_dot("file.dot")
```

Am I doing something wrong or it is a real issue ?

Thank you

**Comment by MridulS** [comment]
https://networkx.readthedocs.io/en/stable/reference/api_1.11.html#api-changes

**Comment by Eisenbarth** [comment]
Oh yes ... I missed this page

Thank you !

**Comment by MridulS** [comment]
@Eisenbarth Can you please close the issue :)

**Comment by abitofalchemy** [comment]
this issue is still there with version 10.11 and with the developer version: `2.1rc1.dev_20171013143330` are there work arounds to read and write  `.dot` files?

**Comment by hagberg** [comment]
Use 
`from networkx.drawing.nx_agraph import read_dot` if you have `pygraphviz` installed or 
`from networkx.drawing.nx_pydot import read_dot` if you have  `pydot` installed.

**Comment by abitofalchemy** [comment]
I'm trying to install on a macOS system using the notes in this page: `networkx/examples/pygraphviz/pygraphviz_simple.py`

After I do: 
```
git clone https://github.com/pygraphviz/pygraphviz.git
cd pygraphviz/
python setup.py install

```
this is the error msg: `subprocess.CalledProcessError: Command '['pkg-config', '--libs-only-L', 'libcgraph']' returned non-zero exit status`

**Comment by abitofalchemy** [comment]
pydot works: 

> `from networkx.drawing.nx_pydot import read_dot` if you have pydot installed.
