### ISSUE TITLE
Implement transitive reduction for directed graphs

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#2185]
The [transitive reduction](https://en.wikipedia.org/wiki/Transitive_reduction) of a directed graph is the minimal graph (in terms of number of edges) in the equivalence class comprising all directed graphs that have the same transitive closure.

This should be easier to compute for directed acyclic graphs first. For directed acyclic graphs, this complements the existing [`transitive_closure` function](https://networkx.readthedocs.io/en/stable/reference/generated/networkx.algorithms.dag.transitive_closure.html).

**Comment by hagberg** [comment]
Fixed in #2215
