### ISSUE TITLE
Graph.number_of_nodes() should be a property, not a method

### ISSUE THREAD

**Issue by CrazyPython** [networkx/networkx#2186]

**Comment by hagberg** [comment]
It could be.  But it is a matter of taste and we have chosen it to be a method.
It is shorter to say `Graph.order()` or `len(graph)`.

**Comment by CrazyPython** [comment]
`len(graph)` is ambiguous and unpythonic.

**Comment by CrazyPython** [comment]
@hagberg then `Graph.order()` should be a property

**Comment by CrazyPython** [comment]
you should deprecate one of the methods and/or have it emit a warning and/or put a recommendation to use the other - 

> There should be one-- and preferably only one --obvious way to do it.

Arguably, `Graph.order()` is simpler than `Graph.number_of_nodes()`

**Comment by CrazyPython** [comment]
@hagberg I think if we're going to have an alias we should have a *good* alias - or at least make the original good. But I don't know how to do this without breaking backwards compatibility - unless you guys decide to make a version where you do break compatibility.

**Comment by jfinkels** [comment]
Hi @CrazyPython. Thanks for the suggestion, but unless there is a very good reason to change this, we're going to leave it as-is for now.
