### ISSUE TITLE
Simple shortcut method to get in edges/out edges of one vertex for DiGraph

### ISSUE THREAD

**Issue by CrazyPython** [networkx/networkx#2187]
right now we have to do `graph.in_edges((vertex, ))` and likewise for `out_edges`.

**Comment by hagberg** [comment]
We decided to make `G.edges()` for DiGraphs be the same as `G.out_edges()`.
It was confusing to users (and developers) to return both in- and out-edges for `G.edges()` and it was causing bugs in some algorithms.  It may not be ideal but some of our decisions are a compromise between Python programmers and graph theorists to reach a middle ground in naming and notation.

**Comment by CrazyPython** [comment]
@hagberg Agreed. Needs docs though.
