### ISSUE TITLE
Formatting doesn't comply with PEP 8

### ISSUE THREAD

**Issue by CrazyPython** [networkx/networkx#2189]
I'll try to submit some PR's for this. It's fine if you don't accept them.

**Comment by CrazyPython** [comment]
I'll wait before submitting any more to see if you guys are fine with all this.

**Comment by hagberg** [comment]
Please don't submit PEP-8 changes only.  We are improving our PEP-8ness when we update or add code.

**Comment by CrazyPython** [comment]
@hagberg My IDE (PyCharm) has a fantastic PEP-8-ifier so I thought I might be able to help out. ;)
