### ISSUE TITLE
Graph representing complete graph whose edges are the euclidean distance of the coordinates of two nodes

### ISSUE THREAD

**Issue by CrazyPython** [networkx/networkx#2192]
Yeah, it's a mouthful. (Just like Objective-C class names! Heh.)

This arises often in problems such as the Traveling salesman problem, often phrased as such:

Given a list of nodes with (x, y) pairs representing a complete graph in which each edge connecting two nodes is the euclidean distance between such two nodes. 

Obviously, it would be too costly to compute the distance between every node and add it as an edge, rather it would be simpler (and easier) to simply dynamically compute the edge length as a property.

I think a graph along the lines of my description would be useful for many graph algorithms.

**Comment by jfinkels** [comment]
Hi @CrazyPython, the following brief code explicitly creates such a graph.

```python
from math import sqrt
from itertools import combinations

from networkx import Graph

def dist(u, v):
   return sqrt(sum((a - b) ** 2 for a, b in zip(u, v)))

def create_euclidean_graph(nodes):
    # Assuming `nodes` is an iterable of coordinate vectors...
    G = Graph()
    G.add_weighted_edges_from((u, v, dist(u, v)) for u, v in combinations(nodes, 2))
    return G
```

This should be sufficient for many situations and can probably be left to the user to implement outside of NetworkX. Do you have a specific example in mind where the distance needs to be computed on-demand and that's common enough that it should be included in the library? (For shortest path functions, you can specify a function to use as the weight of an edge, so for this particular family of algorithms, we do allow on-demand computation of edge weights.)

**Comment by jfinkels** [comment]
Without a very good reason to include a Euclidean graph implementation in NetworkX, I think we should just leave this to the user to implement.
