### ISSUE TITLE
communicability_centrality_exp fails for graphs with >= 200 nodes

### ISSUE THREAD

**Issue by SenyorDrew** [networkx/networkx#2194]
Trying to calculate communicability_centrality_exp with graphs with more than 199 nodes gives the following error:

e.g. for 200 nodes
shapes (200,200) and (1,200) not aligned: 200 (dim 1) != 1 (dim 0)

**Comment by hagberg** [comment]
Could you post more details on the error and networkx version including a small non-working example.  Some of this code has changed (including the names) in networkx and it might be helpful to update to a newer version.   See #1887 #1950 #1958

**Comment by SenyorDrew** [comment]
Installed libraries:

networkx==1.11
scipy==0.17.1
numpy==1.11.1

Example:

import networkx as nx

g199 = nx.complete_graph(199)
g200 = nx.complete_graph(200)

comm199 = nx.communicability_centrality(g199)
comm199_exp = nx.communicability_centrality_exp(g199)

comm200 = nx.communicability_centrality(g200)
# fails on line below
comm200_exp = nx.communicability_centrality_exp(g200)

**Comment by dschult** [comment]
This error occurs in both nx 1.11 and dev version.
The problem seems to be with ```scipy.linalg.expm``` when calling a ```matrix``` object instead of an ```array``` object.  The size 199x199 woks, but no 200x200.

    import scipy.linalg as LA
    import numpy as np
    a = np.ones((199,199)) - np.eye(199)
    LA.expm(a)  # works fine
    A = np.matrix(a)
    LA.expm(A)  # works fine
    b = np.ones((200,200)) - np.eye(200)
    LA.expm(b)  # works fine
    B = np.matrix(b)
    LA.expm(B)  #  gives the error

I'm not sure of the consequences of using an array vs a matrix in this routine.  Can someone closer to that code check the impact of np.matrix vs np.array there?  If no difference, we could use

    A = np.array(nx.to_numpy_matrix(G, nodelist))

**Comment by jtorrents** [comment]
According to numpy documentation we should use `np.array`:

https://docs.scipy.org/doc/numpy-dev/user/numpy-for-matlab-users.html#array-or-matrix-which-should-i-use

I think that `np.matrix` is mainly legacy code.
