### ISSUE TITLE
Add an approximation algorithm for the minimum Steiner tree problem

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#2195]
The [Steiner tree problem](https://en.wikipedia.org/wiki/Steiner_tree_problem) is the problem of computing a minimum weight tree connecting a given subset of nodes. This problem is NP-complete, but there approximation algorithms (Wikipedia describes one). There are also approximation algorithms with better approximation ratios for certain classes of graphs, like [quasi-bipartite graphs](https://en.wikipedia.org/wiki/Quasi-bipartite_graph).

**Comment by NareshPeshwe** [comment]
https://gist.github.com/NareshPeshwe/7f1300103982ad7967d4f03c5eed7f2d
Hey, could you please take a look at this.

**Comment by jfinkels** [comment]
Your proposal seems to be a greedy algorithm. This algorithm I think may sometimes produce cycles, so I think you might need to break cycles at the end of such an algorithm. But does this algorithm have an approximation guarantee? If not, I'd rather follow the relatively simple algorithm given in the Wikipedia article, which is (better than) a 2-approximation.

**Comment by NareshPeshwe** [comment]
Thank you. I understood the flaws in my algorithm. For approximation guarantee I think I will have to find a minimum spanning tree on the sub-graph induced by the vertices obtained. But I think the algorithm in the Wikipedia article is clearer.
https://gist.github.com/NareshPeshwe/28e50861ed1d591ef0d72fc5e497afc7
Does this look good?

**Comment by jfinkels** [comment]
This is the right idea, but the implementation could use some more thought, I think. Most importantly, I think it's probably best for `metric_closure()` to be its own function so that it can be tested separately. Can you create a new pull request introducing the `metric_closure()` function?

How about something like this for an implementation of the metric closure for undirected graphs:
```python
from itertools import combinations

def metric_closure(G, weight='weight'):
    H = nx.Graph()
    for u, v in combinations(G, 2):
        distance, path = nx.single_source_dijkstra(G, u, v, weight=weight)
        # Each edge knows its corresponding shortest path/distance in the original graph.
        H.add_edge(u, v, distance=distance[v], path=path[v])
    return H
```
and this for the approximation algorithm:
```python
from itertools import chain

from networkx.utils import pairwise

def steiner_tree(G, weight='weight'):
    M = metric_closure(G, weight=weight)
    # Use the 'distance' attribute of each edge provided by the metric closure graph.
    mst_edges = nx.minimum_spanning_edges(M, weight='distance', data=True)
    # Create an iterator over each edge in each shortest path; repeats are okay.
    edges = chain.from_iterable(pairwise(d['path']) for u, v, d in mst_edges)
    T = G.edge_subgraph(edges)
    return T
```
(I haven't tested these, but this is how I envision this algorithm.) It's basically the same as yours, just using a few more convenient functions provided by NetworkX.

**Comment by jfinkels** [comment]
It seems you have added a commit to pull request #2191 that added the metric closure. However, that pull request is for an unrelated function (computing the independence number of a graph), so you should not add the `metric_closure()` function there. Instead, what I'm suggesting is to

1. create a new branch on your local machine,
2. add a file `networkx/algorithms/approximation/steinertree.py` that includes the two functions I've suggested above,
3. add unit tests for both functions in `networkx/algorithms/approximation/tests/test_steinertree.py`,
4. commit those changes,
5. push that branch to your fork of NetworkX,
6. create a new pull request that proposes merging that branch on your fork into the master branch of the main NetworkX repository.

If you'd like more help, see the [GitHub help pages][1].

[1]: https://help.github.com/

**Comment by NareshPeshwe** [comment]
Thanks a lot @jfinkels . Will do it. I just had one doubt. Shouldn't the steiner_tree function take in a set of terminal nodes as an input and return a steiner tree induced by only those nodes ? 
And how do I undo the commit to the other pull request ?

**Comment by jfinkels** [comment]
Yes i overlooked that step when writing the comment above, good catch.

You can "undo" a commit by using `git rebase -i master` and deleting the offending commit on your branch.

**Comment by jarmarshall** [comment]
Thanks, this is great functionality, but you assume the graph supplied is connected, which may not be the case... see issue #2979

**Comment by dschult** [comment]
This was closed by @2252
