### ISSUE TITLE
is_isomprphic depends on nodes being orderable

### ISSUE THREAD

**Issue by purpleP** [networkx/networkx#2198]
Everything works fine in python 2.7, but not in python3.5 (probably any python3).
The reason it works in python 2.7 is because it seems any type is orderable in python2 by default (probably by using their id()), but not in python3

python 2.7

```
In [1]: class A(object):
   ...:     pass
   ...:

In [2]: A() < A()
Out[2]: False
```

Python 3.5

```
In [1]: class A:
   ...:     pass
   ...:

In [2]: A() < A()
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-2-465a92f65f9f> in <module>()
----> 1 A() < A()

```

I haven't had time understanding how the algorithm works, but the exception is generated here
https://github.com/networkx/networkx/blob/master/networkx/algorithms/isomorphism/isomorphvf2.py
line 539.

**Comment by jfinkels** [comment]
(See also issues #1989, #1111, and #554 for more issues with unorderable nodes.)

**Comment by purpleP** [comment]
@jfinkels Are you talking to me or the author? I saw this issues, they all closed.

**Comment by jfinkels** [comment]
Just adding some references for background information for anyone who might try to fix this issue.

**Comment by chebee7i** [comment]
Line 539 is: `node_2 = min(G2_nodes - set(self.core_2))`

This doesn't assume orderability but hashability. The algorithm performance will drop dramatically if we cannot assume that. So I don't think this is going to be fixed.

**Comment by jfinkels** [comment]
The `G2_nodes - set(self.core_2)` part requires only hashability, but the `min()` requires orderability, I believe.

**Comment by chebee7i** [comment]
Opps, missed that. Yes that's correct.

Feel free to read the paper here, but this algorithm does indeed seem to require orderability.
Page 4, Line 2: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.101.5342&rep=rep1&type=pdf

I'm not sure it is worth changing the algorithm to relax this constraint. After all, every graph with unorderable nodes is isomorphic to one with orderable nodes. :)

**Comment by jfinkels** [comment]
I'm fine with requiring orderability of nodes, but this should be documented, maybe in `networkx.algorithms.isomorphism.isomorphvf2`, along with an example provided for using, e.g. `convert_node_labels_to_integers`.
