### ISSUE TITLE
Many tests depend on CPython's ordering

### ISSUE THREAD

**Issue by ProgVal** [networkx/networkx#2203]
I started to look at #1671.

The first thing I noticed is that hundreds of tests fail. Most (all?) of them because of ordering issues, like the order of nodes, edges, or nodes in an edge.

I see three solutions to this:
1. Order everything in networkx's main code.
2. Use `sorted()` (or `set()` if the content is hashable) everywhere in tests.
3. Design and implement a small module for making comparisons in tests, eg. `assert_node_list_equal` or `assert_adjacency_list_equal`, and rewrite tests to use them.

I believe 3. to be the best solution, because 1 may slow it significantly on large graphs, and 2 will make tests a lot less readable.
Additionally, this small module could be use by projects using networkx to write their own tests.

**Comment by ProgVal** [comment]
While I was writing this, I learned that you already implemented 3 :blush: : https://github.com/networkx/networkx/issues/2201#issuecomment-236271994

**Comment by jfinkels** [comment]
FYI, Python 3.2+ has [`unittest.TestCase.assertCountEqual`][1]. In Python 2.7 it is named [`unittest.TestCase.assertItemsEqual`][2].

[1]: https://docs.python.org/3/library/unittest.html#unittest.TestCase.assertCountEqual
[2]: https://docs.python.org/2/library/unittest.html#unittest.TestCase.assertItemsEqual

**Comment by hagberg** [comment]
Thanks for checking in on this.  If we still have places where tests rely on ordering let's get them fixed.  The tests do pass for pypy and for later versions of Python using randomized hashing so hopefully there aren't that many fixes required.

**Comment by ProgVal** [comment]
> The tests do pass for pypy and for later versions of Python using randomized hashing so hopefully there aren't that many fixes required.

I noticed that, and I find it surprising. Do you know why?

**Comment by ProgVal** [comment]
Other issue: what about doctests?

**Comment by hagberg** [comment]
It's not surprising to me that we have passing tests.  We designed them that way.  The randomized hashing gave us a good reason to fixof the tests that depended on ordering of nodes or edges.  Maybe we missed a few and so far have had no reports for some reason.  

 I'm not sure what is happening with your Jython tests.  If you want to explore that further go ahead.  As pointed out in #1671 we are not supporting Jython though making NetworkX work with Jython would be a plus.

The doctests are primarily for showing some use cases so we don't need such thorough testing there.  In some cases it doesn't make sense to write a complicated doctest that handles the arbitrary ordering.

**Comment by ProgVal** [comment]
I started working on this: https://github.com/ProgVal/networkx/commit/7c4d66e67b239507244234fc5b90687dc0668815

I dropped the number of failing tests from 314 to 211, by making node/edge lists inequalities (hopefully without ading false negatives).

Unfortunately, the remaining failures are more tricky. Most of them seem to be other ordering issues, but trickier; for instance an algorithm giving an other solution. And fixing these would take a lot more time to fix, as one has to understand how tested algorithms work.
So… I probably won't work further on this issue, but I can help if anyone else wants to do it.

**Comment by hagberg** [comment]
Those fixes generally look good (using assert_nodes_equal and assert_edges_equal).  We could include them now.  
Some I don't understand why they would fail with Jython.  e.g. replacing

```python
-        assert_equal(sorted(d for n, d in G.in_degree()),[0, 0, 0, 0, 1, 2, 2])
+        assert_nodes_equal((d for n, d in G.in_degree()),[0, 0, 0, 0, 1, 2, 2])
```

Why should the first line fail?  All values are numeric.  They should sort correctly regardless of the Python implementation.

**Comment by ProgVal** [comment]
Indeed, it worked before. I just thought it made more sense, semantically.

**Comment by hagberg** [comment]
Oh, I see.  Would you be willing to make a PR with those test changes? I'd like to incorporate those. 
Also if you would add here the Jython test output that might inspire someone to look into that further.

**Comment by ProgVal** [comment]
[jython.log.txt](https://github.com/networkx/networkx/files/392016/jython.log.txt)


> Also if you would add here the Jython test output that might inspire someone to look into that further.

Attached.
You could also add a Travis build (with “allowed failures”).

By the way, I installed/use Jython like this:

```
hg clone http://hg.python.org/jython
cd jython
ant
wget https://bootstrap.pypa.io/get-pip.py
./dist/bin/jython get-pip.py
~/src/jython/dist/bin/jython -m pip install --user nose coverage decorator
cd ~/dev/networkx
~/src/jython/dist/bin/jython `which nosetests` -v
```

**Comment by hagberg** [comment]
This was very helpful.   I think we should follow up and fix these issues.

With the changes from #2207 and #2209 the tests all pass with Jython in networkx/classes/test and networkx/test.  There are still many failing tests in other parts which as you pointed out might simple ordering of edges and nodes.  Some are clearly more complicated and might be algorithms with multiple alternate solutions.   It's certainly possible this could expose some bugs which is why I advocate for making the tests work with Jython.

**Comment by hagberg** [comment]
See #2207 and #2209.
