### ISSUE TITLE
write_gexf is incompatible with from_pandas_dataframe

### ISSUE THREAD

**Issue by esafak** [networkx/networkx#2204]
Graphs created using pandas dataframes can not be exported with write_gexf because they use numpy data types:

``` python
...gexf.py in add_attributes(self, node_or_edge, xml_obj, data, default)
    428                 # static data
    429                 mode='static'
--> 430                 attr_id = self.get_attr_id(make_str(k), self.xml_type[val_type],
    431                                            node_or_edge, default, mode)
    432                 e=Element("attvalue")

KeyError: <class 'numpy.int64'>
```

I suggest modifying write_gexf rather than from_pandas_dataframe.

**Comment by hagberg** [comment]
This is going to break in other writers too.  It might make sense to decide on a comprehensive solution.  At this point if you are not using a built-in Python type the text-based graph format writers may not always work.   The workaround is to convert the attributes to Python types.

**Comment by Michael-E-Rose** [comment]
Just bumped into the same problem.  Why not running a (conditional) conversion to integers or floats somewhere in `.write_gexf()`?
