### ISSUE TITLE
Retrieving edge data in directed graphs has an asymmetric API

### ISSUE THREAD

**Issue by pimotte** [networkx/networkx#2205]
[DiGraph.out_edges](http://networkx.readthedocs.io/en/latest/reference/generated/networkx.DiGraph.out_edges.html) has the useful feature that you can retrieve a single value from the data dictionary by specifiying a string.

[DiGraph.in_edges](http://networkx.readthedocs.io/en/latest/reference/generated/networkx.DiGraph.in_edges.html), [MultiDiGraph.out_edges](http://networkx.readthedocs.io/en/latest/reference/generated/networkx.MultiDiGraph.out_edges.html) and [MultiDiGraph.in_edges](http://networkx.readthedocs.io/en/latest/reference/generated/networkx.MultiDiGraph.in_edges.html) lack this. 

I'll likely prepare a PR for this myself, but I wanted to make this issue first, in case I missed something or anyone has useful information in relation to this.

**Comment by dschult** [comment]
It would be good for them all to have that feature. Thanks!
