### ISSUE TITLE
convert.from_dict_of_dicts' result depends on ordering

### ISSUE THREAD

**Issue by ProgVal** [networkx/networkx#2210]
I modified the code like this:

```
        else: # Undirected
            if G.is_multigraph():
                seen=set()   # don't add both directions of undirected graph
                for u,nbrs in d.items():
                    for v,datadict in nbrs.items():
                        print(datadict)
                        if (u,v) not in seen:
                            print('not seen')
                            G.add_edges_from( (u,v,key,data)
                                               for key,data in datadict.items()
                                              )
                            seen.add((v,u))
                print('foo')
                try:
                    print(G[1])
                except:
                    pass
```

and I run the test `test_to_undirected`.

On CPython 2.7, the output is:

```
{0: {}}
not seen
{0: {}}
not seen
{0: {}}
{0: {'foo': []}}
not seen
{0: {}}
{0: {}, 1: {'foo': []}}
foo
{0: {0: {}}, 2: {0: {'foo': []}}}
```

On Jython, it is:

```
{0: {}}
not seen
{0: {}}
not seen
{0: {}}
{0: {}, 1: {'foo': []}}
not seen
{0: {}}
{0: {'foo': []}}
foo
{0: {0: {}}, 2: {0: {}, 1: {'foo': []}}}
```

As you can see, the final value of `G[1])` depends on whether `{0: {}, 1: {'foo': []}}` or `{0: {'foo': []}}` as been explored first.

If you can't debug this easily, I can try to do it, but I don't really understand the dict structure here.

**Comment by hagberg** [comment]
The way we convert directed multigraphs to multigraphs is problematic.  As you discovered the result is dependent on order that the graph is explored.  I can't think of a good fix for this other than removing this option.

**Comment by ProgVal** [comment]
Ok.
But why does the directed graph have a simple dict in one case, and a dict of dict in the other one?

**Comment by hagberg** [comment]
I'm not sure I understand what is going on there. It could be a bug.

**Comment by ProgVal** [comment]
I got it. I don't think it's a bug.
In `TestMultiDiGraph.setUp`, a complete 3-digraph with no attribute is constructed. In `BaseAttrGraphTester.add_attributes`, `(1, 2)` is removed, and `(1, 2)` and `(2, 1)` are added with attributes. So `(2, 1)` is a double arc.
Hence `{0: {}, 1: {'foo': []}}` as a dict of attributes for `(2, 1)`.

So no bug here, just the “undirectionalization” problem you mentionned.

**Comment by ProgVal** [comment]
Actually, when converting from MultiDiGraph to MultiGraph, the set of edges between u and v is defined as the set of arcs from u to v or from v to u.
What about making it the union of sets of arcs from u to v and from v to u?
