### ISSUE TITLE
How to represent Input & Output node slots

### ISSUE THREAD

**Issue by brupelo** [networkx/networkx#2216]
I was interested on using networkx on one pyqt widget similar to blender's node graph editor. What's the proper way to have input & output slots on my graphs/subgraphs?

I know having a DiGraph i'd have access to in_edges and out_edges but not sure if that's what i'm looking for, any advice?

Also, any well-known pyqt software using networkx behind the curtains?

**Comment by jfinkels** [comment]
Hi @brupelo, this question is probably more appropriate for the discussion group at: https://groups.google.com/forum/#!forum/networkx-discuss.
