### ISSUE TITLE
'alpha' parameter is unused in `draw_networkx_labels`

### ISSUE THREAD

**Issue by sanghack81** [networkx/networkx#2217]
Each of `draw_networkx_labels` and `draw_networkx_edge_labels` in `networkx.drawing.nx_pylab` defines `alpha` as a parameter, but the passed argument is not used in the code failing to generate transparent text.

**Comment by aryamccarthy** [comment]
Seems like @Zsailer fixed this; can we close it?

**Comment by sanghack81** [comment]
Closed #2269
