### ISSUE TITLE
dag_longest_path_length doesn't produce what it should for graphs with weighted edges

### ISSUE THREAD

**Issue by cmtm** [networkx/networkx#2229]
I believe the `dag_longest_path_length` function isn't returning what it should in the case where the edges weights aren't all one.

The `dag_longest_path` function returns the path through the DAG where the sum of the weights of all the edges is higher (or equal to) than the same for all other paths. It represents this path as a list of nodes.

The `dag_longest_path_length` function behaves like this:
```
return len(nx.dag_longest_path(G)) - 1
```

I would expect this function to return the sum of the weights of the edges on the longest path. More concisely, it should return the length of the longest path.
Instead, it's returning the number of edges on the path , not the sum of the weights of the edges on the path. Is this intentional? This isn't what the "longest path problem" generally aims to solve.

If you agree with my interpretation of what it should produce, I can submit a pull request which fixes the behavior of the function.

**Comment by jfinkels** [comment]
I agree with you. This should match the behavior of `shortest_path_length`, which returns the sum of the weights (distances) on the edges:
```python
>>> import networkx as nx
>>> G = nx.Graph()
>>> G.add_edge(0, 1, weight=10)
>>> nx.shortest_path_length(G, 0, 1, weight='weight')
10
```

**Comment by cmtm** [comment]
Another potential issue I found when writing the test cases for my fix is that dag_longest_path doesn't raises a ValueError when passed an empty graph. Should this be supported? If so, would you like me to fix it along with this PR, or as a separate one?
