### ISSUE TITLE
graphviz rendering issue

### ISSUE THREAD

**Issue by monkeynut** [networkx/networkx#2231]
If I have a networkx (version 1.11 from pip) graph G whose nodes are objects. The **repr** of these objects may be the same although they are distinct nodes. By manually setting label attribute on nodes I can happily have two distinct nodes rendered with the same text in them. I then convert this to AGraph and use the to_string() method to obtain the .dot graph.

However, when the edges are written into the dot file, they appear to use the **repr** of the nodes at either end, ignoring the label attribute set on those nodes. This leads to a graph being rendered with a completely different topology.

Happy to submit a working example if its not obvious what to do. I think (hope)someone more intimately familiar with the import structure and interplay between agraph and networkx will be able to recognise this problem immediately. Thanks all.

**Comment by hagberg** [comment]
I don't think this is a bug.  If two of your node objects have the same `__repr__` (and I'm guessing the same `__str__`) then any string-based output from networkx will generate the same node string for both.  If you want distinct nodes then they should have distinct `__repr__` or at least `__str__`.  As you have discovered you can have the same `label` (or other) attribute for multiple nodes if you want to draw them with the same name, color, shape, etc.
