### ISSUE TITLE
shortest_path_length behavior in disconnected graph

### ISSUE THREAD

**Issue by idc9** [networkx/networkx#2234]
Currently shortest_path_length(G, u, v) raises an error if there is no path between nodes u and v. It might be worth changing this to return infinity (or at least adding the option to do so). Some algorithms, such as global_efficiency, treat the path length between two disconnected nodes as infinity.

**Comment by dschult** [comment]
It seems like raising an exception is the way to go here... Then users can handle it explicitly.

**Comment by jfinkels** [comment]
The workaround would be something like

```python
def shortest_path_length(G, source, target):
    try:
        return nx.shortest_path_length(G, source, target)
    except NetworkXNoPath:
        return float('inf')
```

**Comment by idc9** [comment]
I would argue that the **default behavior should be to return inf** if the graph is disconnected and the user can then choose how to deal with it. I recognize this is a matter of taste but here is my argument:

- both behaviors arise in the wild i.e. there are cases when you want an error if you try to compute the paths in a disconnected graph and there are cases when you want to return inf (or something else). 

- inf is a natural choice for two nodes lacking a connecting path

- the user can use a try/except to catch inf and return an exception if they so desire

- inf will automatically carry through in many cases (i.e. the average path length will be inf if one pair of nodes returns an inf)

- **most importantly**: asking for the path between two disconnected nodes is **not** an error in networkx, it's a user error i.e. the user decides that the input graph should be connected. If it's the case that the graph should be connected but the user fed in a disconnected graph that's on the user, not networkx

**Comment by hagberg** [comment]
Raising an exception here doesn't mean that it is a software error it means that there is a problem with the output of the algorithm.  In this case the error is trying to compute the shortest path between disconnected nodes.   We have other exceptions like that where we try to catch input errors that cause the algorithms to produce results that are reasonable by wrong. Those are hard to spot.

I'd prefer raising the exception to be explicit about the disconnected nodes and lack of a path.  In that case the user has to decide how to handle the situation - setting to inf if that is appropriate.  There is less chance of a silently ignored error when dividing by inf or some similar situation.
