### ISSUE TITLE
Abandon All pydotplus, Ye Who Graph Here

### ISSUE THREAD

**Issue by leycec** [networkx/networkx#2235]
NetworkX 1.11 unilaterally [dropped support](https://github.com/networkx/networkx/pull/1924) for**[`pydot`](https://github.com/erocarrera/pydot)**in favour of**[`pydotplus`](https://github.com/carlos-jenkins/pydotplus)**– breaking backward compatibility with upstream projects requiring the former.

Breaking backward compatibility isn't _necessarily_ a problem per se. Sometimes you gotta [crack the world's shell](https://www.youtube.com/watch?v=McKR0IgCM34) in order to make a tender omelette worthy of Iron Chef. :egg: 

Dropping support for the _only_ well-maintained pure-Python GraphViz library (`pydot`) in favour of its worst-maintained alternative (`pydotplus`) smells like a rotting wound waiting to fester, however.
## Then There Were Three

There are three `pydot`-like projects. In order of increasing commit and release activity, these are:
1. **[`pydotplus`](https://github.com/carlos-jenkins/pydotplus),** a `pydot` fork circa 2007. `pydotplus` is moribund, on life support, and effectively dead – and has been for nearly two years. It lasted seven glorious years before unceremoniously kicking the bit bucket. Only the good forks die young. This fork's:
   - [Last commit](https://github.com/carlos-jenkins/pydotplus/commits/master?page=1) was at **December 8th, 2014.** 
   - [Last stable release](https://pypi.python.org/pypi/pydotplus) was at **December 9th, 2014.**
2. **[`pydot-ng`](https://github.com/pydot/pydot-ng),** yet _another_ `pydot` fork also circa 2007. `pydot-ng` is _also_ moribund, on life support, and effectively dead – and has been for nearly a year. It lasted eight glorious years and then silently fell into a [sarlacc pit](https://www.youtube.com/watch?v=oezZTXzXs90), one-upping `pydotplus` by several months. All forks succumb to GitHub winter, in the end. This fork's:
   - [Last commit](https://github.com/pydot/pydot-ng/commits/master) was at **March 15th, 2015.** 
   - [Last stable release](https://pypi.python.org/pypi/pydot-ng) was at **February 26th, 2015.**
3. **[`pydot`](https://github.com/erocarrera/pydot),** the canonical `pydot` project with over 100 commits spanning nearly a decade. Unlike its now-disabled rivals, `pydot` remains highly active, responsive to issue submissions and pull requests, and dedicated to the cause of righteousness. Recent codebase improvements include [Travis](https://github.com/erocarrera/pydot/blob/master/.travis.yml)-based continuous integration (CI), Python 3-oriented [optimizations](https://github.com/erocarrera/pydot/commit/9b3c1a1d1101fd8523c0efbb9a1b3997a914e5a2), improved [unicode handling](https://github.com/erocarrera/pydot/commit/5df24ff318bcc73e92f9531c2ed37678268b8beb), improved [PEP8 compliance](https://github.com/erocarrera/pydot/commit/0d023928f42f1448eedfb9d2c46165e1d221c46e), improved [setuptools integration](https://github.com/erocarrera/pydot/commit/69dce474f6fbcaa6055586611453e43f3f20230d), and the list just exhaustively goes _on and on_.
   This project's:
   - [Last commit](https://github.com/erocarrera/pydot/commits/master) and [last stable release](https://pypi.python.org/pypi/pydot) were both at **July 2nd, 2016.**

It's _not_ simply activity, however. It's availability:
- The cross-platform Anaconda distribution officially supports both the Python 2.x and 3.x versions of both [`pydot`](https://anaconda.org/anaconda/pydot) and [`pydot-ng`](https://anaconda.org/anaconda/pydot-ng). Isn't that nice? By compare:
  - The Python 2.x and 3.x versions of `pydotplus` are only [unofficially supported](https://anaconda.org/conda-forge/pydotplus) via a [third-party `conda` forge](https://github.com/conda-forge/pydotplus-feedstock).
- Ubuntu has officially supported the Python 2.x version of `pydot` since [Precise (12.04)](http://packages.ubuntu.com/search?keywords=python-pydot) and the Python 3.x version of `pydot` since [Wily (15.10)](http://packages.ubuntu.com/search?keywords=python3-pydot). By compare:
  - The Python 2.x but _not_ 3.x version of `pydot-ng` has been officially supported since [Wily (15.10)](http://packages.ubuntu.com/search?keywords=python-pydot-ng).
  - The Python 2.x and 3.x versions of `pydotplus` will only be officially supported as of the yet-unreleased [Yakkety (16.10)](https://launchpad.net/ubuntu/+source/python-pydotplus).
- Arch Linux [officially supports](https://packages.gentoo.org/packages/media-gfx/pydot) both the Python 2.x and 3.x versions of `pydot`. By compare:
  - The Python 2.x and 3.x versions of `pydot-ng` are [unofficially supported](https://aur.archlinux.org/packages/python-pydot-ng) via the Arch User Repository (AUR).
  - `pydotplus` remains unsupported, both officially and otherwise.
- Gentoo Linux [officially supports](https://packages.gentoo.org/packages/media-gfx/pydot) the Python 2.x version of `pydot`. I'm contemplating adding unofficial support for the Python 3.x version via my [third-party overlay](https://github.com/leycec/raiagent). <sup>_Time, what is time?_</sup> By compare:
  - `pydot-ng` remains unsupported, both officially and otherwise.
  - The Python 2.x and 3.x versions of `pydotplus` are only unofficially supported via a [third-party overlay](https://github.com/gentoo-science/sci/tree/master/dev-python/pydotplus).
- The OS X-specific:
  - MacPorts package manager [officially supports](https://trac.macports.org/browser/trunk/dports/python/py-pydot/Portfile) the Python 2.x version of `pydot`. A port for the Python 3.x version has been [submitted](https://trac.macports.org/ticket/46509) but remains in ticket limbo. By compare:
    - `pydot-ng` remains unsupported, both officially and otherwise.
    - `pydotplus` remains unsupported, both officially and otherwise.
  - Homebrew package manager supports _no_ `pydot`-like library. <sup>_Thanks alot, beer._</sup>

A suspicious pattern emerges.
## Then There Was One

In the endless circle game of unpaid GitHub volunteerism, he who is willing to do hard stuff for free wins. **`pydot` wins.** `pydotplus` and `pydot-ng` lose because they are dead. Can't complain. Had their chance and, in modern parlance, "blew it."

May the dark days ahead be leavened with wisdom, clarity, and developer omniscience. The dawn of a NetworkX-graphed Age beckons.

> <sup>I have no dead horse in this race. I'm a perfectly impartial bystander unaffiliated with any `pydot`-like project. I do this solely for the glory and continued longevity of NetworkX.</sup>

**Comment by dschult** [comment]
Nice --  :)

We moved to pydotplus because pydot was not maintained.... in particular, it had never moved to be compatible with python3.  There were a number of forks of the pydot repo and we picked pydotplus. 
I haven't kept up with the social interplay between the pydot options. Perhaps pydot is now ready to take over from the people who made it work during its low activity period. 

Can you either 1- find the backstory.... did the person who took over pydot include the improvements made by the others --  or 2- change and test NetworkX's dev version to use pydot and make sure it passes the tests?   We'd love a PR. :)

**Comment by leycec** [comment]
> We moved to pydotplus because pydot was not maintained....

_Totally._ I definitely grok that. `pydot` appears to have had a tumultuous development history – although the radioactive dust appears to be finally settling. <sup>_maybe_</sup>

> find the backstory.... did the person who took over pydot include the improvements made by the others

**Good question.** I'm curious myself. What a tangled web developers weave.

I note that the current principal maintainer of [`pydot`](https://github.com/erocarrera/pydot), [erocarrera](https://github.com/erocarrera), appears to have _also_ been the principal maintainer of [`pydot-ng`](https://github.com/pydot/pydot-ng). I also note that there appear to be a [countably infinite number of `pydot` forks](https://github.com/erocarrera/pydot/issues/121) – far more than noted above, even. Anyone ever heard of [`pydot3k`](https://pypi.python.org/pypi/pydot3k/1.0.17), [`pydot2`](https://pypi.python.org/pypi/pydot2/1.0.32), [`pydot3`](https://github.com/log0/pydot3/), [`mrv-pydot`](https://github.com/mrv-developers/mrv-pydot), or [`pydot_modern`](https://pypi.python.org/pypi/pydot_modern/1.0.29)? **Me neither.**

Teasing sanity out of this undocumented history is probably infeasible. I do note, however, that `pydot` developers [politely request](https://github.com/erocarrera/pydot/issues/121) that downstream fork changes be merged into the upstream `pydot` codebase:

> For the (non-fork) repositories that a GitHub search for `pydot` returns, the following appear to contain changes to be reviewed/edited/merged:
> ...
> Please add any additional repositories that you think would be useful for updating `pydot`, or better open pull requests.

Awareness of the confusion exists. Yet confusion remains.

> change and test NetworkX's dev version to use `pydot` and make sure it passes the tests?

Happily, this sounds like low-hanging fruit. I'd be happy to throw my flea-bitten hat into the ring for this. :tophat: 

`pydot` support is sufficiently critical for our [scientific use case](https://gitlab.com/betse/betse) that we've [temporarily blacklisted](https://gitlab.com/betse/betse/blob/master/betse/metadata.py#L362) NetworkX >= 1.11 in our `setup.py`. Since we have a vested interest in restoring `pydot` support, I'll see what I can cobble together over the next several weeks.

Thanks for the welcome reply, dschult. <sup>_...and sorry for the unwelcome delay!_</sup>

**Comment by leycec** [comment]
**Done.** After migrating NetworkX from `pydotplus` to `pydot`, all tests locally pass on [my fork](https://github.com/leycec/networkx). Since `pydot >= 1.2.0` breaks [backward API compatibility](https://github.com/erocarrera/pydot/blob/master/ChangeLog) in numerous beneficial ways (e.g., by unconditionally returning lists rather than sometimes lists and sometimes singletons), the requisite changes were slightly less... _trivial_ than a mere `sed -i -e 's/pydotplus/pydot'`.

Nonetheless, all's well that's done. I'll get off the [couchlock](https://www.urbandictionary.com/define.php?term=couchlock&defid=1946765) tomorrow and submit a proper pull request. :couch_and_lamp:

**Comment by jfinkels** [comment]
Fixed in pull request #2272. Thanks for the help.

**Comment by johnyf** [comment]
To answer the questions [above](https://github.com/networkx/networkx/issues/2235#issuecomment-243125481) about the backstory and inclusions of existing improvements scattered among `pydot` forks:

1. The current `pydot` maintainer is me. I asked the author of `pydot`, who allowed me to take maintenance responsibilities.

2. Yes, I have included most changes worth including from the main forks. Fortunately, the forks with most work in them were mostly linearly related in terms of history. I have carefully read through the histories of those forks, as I was reviewing and rewriting changes (usually as several more commits, and some of them different, for various reasons).
