### ISSUE TITLE
networkx.ancestors is inconsistent with networkx.has_path

### ISSUE THREAD

**Issue by hklarner** [networkx/networkx#2240]
the function **networkx.ancestors(G, source)** is supposed to 

> Return all nodes having a path to (source) in G.

but

```
>>> g = networkx.DiGraph()
>>> g.add_edge(1,1)
>>> networkx.has_path(g,1,1)
True
>>> networkx.ancestors(g,1)
set([])
```

where the answer should be `set([1])`, right? Apparently ancestors ignores loops.

BTW: docstring of **networkx.ancestors** contains uninterpreted markdown

**Comment by jfinkels** [comment]
First, the definition for a path allows a path of length zero, i.e., from a node to itself, so the self-loop in your example is unnecessary:
```python
>>> G = nx.DiGraph()
>>> G.add_node(0)
>>> nx.has_path(G, 0, 0)
True
```
Second, the `networkx.dag.ancestors` function is only guaranteed to work for directed acyclic graphs, and your graph has a cycle of length one, or in other words, a self-loop. In general, the functions in `networkx.dag` don't check for acyclic-ness, so it is up to the user to check for that. You can remove self-loops by doing `G.remove_edges_from(G.selfloop_edges())`.

**Comment by hklarner** [comment]
> Second, the networkx.dag.ancestors function is only guaranteed to work for directed acyclic graphs
shouldn't this be in the documentation?

**Comment by jfinkels** [comment]
The documentation is a bit spread out because the project is so large, unfortunately. But it would be nice for the precondition that graphs are directed and acyclic to be stated somewhere, like at the `netwrokx.algorithms.dag` package-level docstring.
