### ISSUE TITLE
Graph.to_undirected()

### ISSUE THREAD

**Issue by michaelkkim** [networkx/networkx#2242]
Hello,

I'm currently working on a big citation network data ('older' nodes cannot cite 'newer' nodes, whereas 'newer' nodes can cite 'older' nodes).

When I convert my graph to an undirected version using 'Graph.to_undirected()', the number of nodes stay the same, but the number of edges decreases for some reason. Why is this so?

The only reason I can think of is that if two nodes 'cite' each other (have two directed edges pointing to each other), 'Graph.to_undirected()' forms this as one edge. However, this should not be possible in a citation network data... (assuming my edgelist data is correct)

**Comment by ProgVal** [comment]
> However, this should not be possible in a citation network data...

I wouldn't be so sure.

You can get a list of the missing edges this way:

```
from collections import Counter
original_edges = Counter(frozenset((u,v)) for (u,v) in G.edges())
G2 = G.to_undirected()
undirected_edges = Counter(frozenset((u,v)) for (u,v) in G2.edges())
missing_edges = original_edges - undirected_edges
for ((u,v), count) in missing_edges.items():
    if count != 0:
        print('Missing edge: {} - {}'.format(u, v))
```

This creates two edge-to-int dictionaries, which count the number of occurences of each edge, regardless of its direction (thanks to frozenset, which is unordered like a set, but is also hashable).
Then it substracts the two, so you get t

**Comment by dschult** [comment]
I have seen articles which cite each other -- they may be written at the
same time but published at different times. Still the second can cite the
first (either in anticipatory form, or in a preliminary form which the
citation databases correctly match to the actual article).

**Comment by jfinkels** [comment]
@michaelkkim Do these answers help resolve your issue?

**Comment by michaelkkim** [comment]
@jfinkels Yes they did! Thank you all.
