### ISSUE TITLE
AttributeError: 'module' object has no attribute 'graphviz_layout' with networkx 1.11

### ISSUE THREAD

**Issue by brupelo** [networkx/networkx#2245]
Any clue about this [issue](http://stackoverflow.com/questions/39411102/attributeerror-module-object-has-no-attribute-graphviz-layout-with-networkx)?

**Comment by bharatahuja** [comment]
http://bfy.tw/7vw0

First link to SO.

**Comment by jfinkels** [comment]
@brupelo The question there seems to be answered. In the future, you may consider discussing things like this on the [NetworkX mailing list][1] before opening a GitHub issue.

[1]: https://groups.google.com/d/forum/networkx-discuss
