### ISSUE TITLE
Single source dijkstra has confusing output if target is specified

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#2248]
I would expect `single_source_dijkstra(G, source=u, target=v)` to return a pair in which the left element is the length of the shortest path from `u` to `v` and the right element is the shortest path from `u` to `v`. However, the return value seems to be the dictionary of lengths keyed by destination node and the dictionary of paths keyed by destination node that together represent the state of Dijkstra's algorithm at the point that the target node was found. Should this be changed?

**Comment by hagberg** [comment]
It seems the implementation isn't quite complete for using source and target together.
