### ISSUE TITLE
nx.nx_agraph.read_dot should be able to parse dot from a string or a file-like object

### ISSUE THREAD

**Issue by josch** [networkx/networkx#2249]
Hi,

Currently, `nx.nx_agraph.read_dot` seems to be unable to parse dot data from memory but I would like to avoid having to write a temporary file to be able to parse my dot graph.

Currently this works:

```
python3 -c 'import sys,networkx as nx; nx.nx_agraph.read_dot("out.dot")'
```

and so does this:

```
python3 -c 'import sys,networkx as nx; nx.nx_agraph.read_dot(sys.stdin)' < out.dot
```

But this will segfault:

```
python3 -c 'import sys,io,networkx as nx; nx.nx_agraph.read_dot(io.StringIO("out.dot"))'
```

The underlying reason seems to lie in pygraphviz and I reported the issue as pygraphviz/pygraphviz#101.

The problem could easily be fixed by `nx.nx_agraph.read_dot` checking if the argument is either a string or a file-like object. In the former case, it should use `pygraphviz.AGraph(filename=...)` (and not the deprecated `file` argument as it is currently doing) and in the latter case it could slurp in the content behind the file descriptor and do `pygraphviz.AGraph(string=...)`.

Or am I missing an existing way that allows me to parse my dot data without writing a temporary file?

**Comment by hagberg** [comment]
The calling argument file= is wrong as you say and should be replaced with filename=

I don't think we want to read the file into memory before handing off to pygraphviz (AGraph) if we don't need to.  The typical case is reading from a file into a graph data structure and it is more efficient to not read the data into memory first.

**Comment by josch** [comment]
I agree that the file should not be read into memory unconditionally. That would be wasteful.

In my own code I currently have a workaround which calls `pygraphviz.AGraph` with the `filename` argument if a string was passed and if a file-like object was passed, it calls `read()` and passes it to `pygraphviz.AGraph` via the `string` argument.

Could this not also be done by networkx? Then it would support both: filenames and file-like objects as arguments.

**Comment by hagberg** [comment]
Sure that could be done.  But note that when pygraphviz loads a string (the `from_string` method) a temporary file is written and then read back in using the graphivz c library.  So you proposal would end up reading the file data twice (and writing it once).  This is a limitation of pygraphviz that could be fixed.

**Comment by josch** [comment]
I was not aware that pygraphviz has to create a temporary file itself.

Nevertheless I think that it would make sense for the networkx interface to be able to accept file-like objects. How the backend handles these can still be fixed at a later point. Would you agree?

I'm currently doing something like this in my code:

            if data is None:
                g = nx.nx_agraph.read_dot(path)
            else:
                import pygraphviz
                A = pygraphviz.AGraph(string=data)
                g = nx.nx_agraph.from_agraph(A)

**Comment by hagberg** [comment]
This is really a pygraphviz issue.  If pygraphviz accepted file-like objects than this could be implemented.
