### ISSUE TITLE
dag_longest_path_length and dag_longest_path can be refactored

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#2251]
The pull request #2237 corrected a bug in the behavior of `dag_longest_path_length`. However, the code could be refactored with `dag_longest_path` into a shared common private function that returns both the longest path and the weight, with each public function exposing either the path or the length,, respectively. This prevents O(n) additional work done by `dag_longest_path_length`.

**Comment by hagberg** [comment]
I doubt there will much practical benefit from this though:
```python
In [16]: G = nx.gnc_graph(1000)

In [17]: %timeit nx.dag_longest_path(G)
100 loops, best of 3: 11.9 ms per loop

In [18]: %timeit nx.dag_longest_path_length(G)
100 loops, best of 3: 11.7 ms per loop
```
