### ISSUE TITLE
Inaccurate output (missing features) while reading a shapefile into networkx

### ISSUE THREAD

**Issue by Nobik2** [networkx/networkx#2254]
Hi, I am doing some work with networkx, which involves the conversion of a point and polyline shapefile into a graph with nodes and links. The documentation
about the read_shp() method states that it:

> Generates a networkx DiGraph from shapefiles. Point geometries are
> translated into nodes, lines into edges. Coordinate tuples are used as
> keys. Attributes are preserved, line geometries are simplified into
> start and end coordinates. Accepts a single shapefile or directory of
> many shapefiles.

My first observation is that the  method does not read all the features in the shapefiles e.g. there are over 31000 points in my nodes shape file but the length of nodelist returns only 4991 as against 31760 nodes. I observed the same behaviour for the lines shapefile. I have a small code snippet below as an illustration.

```
import networkx as nx
G = nx.read_shp("Sample_nodes.shp", simplify=False)
print len(G.nodes()) 

#output: 4991 instead of 31760 
```

Is there something I am missing?

**Comment by dschult** [comment]
Take a look at:
http://networkx.readthedocs.io/en/stable/reference/generated/networkx.readwrite.nx_shp.read_shp.html
In particular, there is a "source" link which takes you to the source code for the function. It looks fairly straightforward -- simply using getGeometryType to determine nodes (if 1) or edges (if 2).  Perhaps your file uses a different convention for GeometryType?  

Its hard to see what could be wrong without more info. Can you make a small example that doesn't work?

**Comment by zooloo10** [comment]
I have a small example in which this happens Contained in Shapes.zip.  Export_output.shp is the shape before converting to a NX graph. Edges.shp is the output from NX after converting the original shape to a graph then back to a shapefile.  One edge is lost, but no manipulations are done to the graph.  There is another case where when converting from a DiGraph to a UnDiGraph i lose multiple more edges.  it will be included in Shapes2.zip When converting to DiGraph we lose the same edge again, then when covnerting to UnDiGraph we lose a few more.
[shapes.zip](https://github.com/networkx/networkx/files/817328/shapes.zip)
[Shapes2.zip](https://github.com/networkx/networkx/files/817348/Shapes2.zip)

**Comment by jarrodmillman** [comment]
See #4366.
