### ISSUE TITLE
Implementation for TextRank

### ISSUE THREAD

**Issue by prakhar21** [networkx/networkx#2255]
Hi, I am trying to use networkx's PageRank algorithm for my implementation of TextRank.
https://web.eecs.umich.edu/~mihalcea/papers/mihalcea.emnlp04.pdf
The scoring matrix that they have used uses weights for edges. 
So, if I pass in weight parameter while constructing the graph, then what does the scoring function look like ?

**Comment by hagberg** [comment]
Questions are better on the mailing list.
https://groups.google.com/forum/#!forum/networkx-discuss
