### ISSUE TITLE
Allow nx.double_edge_swap to take edgelist as an input

### ISSUE THREAD

**Issue by joelmiller** [networkx/networkx#2256]
double_edge_swap is a relatively slow algorithm.  This is because it has to sample edges uniformly at random from the edges.  

In some applications I find I need to do this many, many times, and so this is the bottleneck.  I find that I can do much faster if I get the edgelist in advance and pass it as an argument.  Then I just need to select two edges from this list, do a bit of testing, do the swap, and update the edgelist.

I have attached sample code that runs much faster when an edgelist is provided (mostly copied and pasted from the current version and then edited to include optional edgelist.  I didn't copy over all the comments):

[my_double_edge_swap.txt](https://github.com/networkx/networkx/files/481586/my_double_edge_swap.txt)

**Comment by jfinkels** [comment]
Thanks @joelmiller, it would be helpful if you post a pull request, or at least a diff, so that we can see the changes more easily.

**Comment by hagberg** [comment]
Closed due to inactivity.
