### ISSUE TITLE
Any way to write graph attributes to dot files?

### ISSUE THREAD

**Issue by anderspitman** [networkx/networkx#2264]
I'm trying to set the `rankdir=LR` graph attribute to get my graphviz file to layout horizontally. I tried both the pygraphviz and pydot writers but neither seems to preserve the attribute. I'm trying to get the resulting file to look like this:

```
digraph G {
	graph [rankdir=LR];
...
```

I'm setting it like this:

```python
g = nx.DiGraph(rankdir='LR')
```
 Is that the wrong way for the desired effect?

**Comment by hagberg** [comment]
That would make sense but it is not how it currently works.   You need to set the "graph" attribute of the graph attribute (ugh) like this

```python
In [1]: import networkx as nx

In [2]: G = nx.DiGraph()

In [3]: G.graph['graph']={'rankdir':'LR'}

In [4]: import sys

In [5]: nx.drawing.nx_agraph.write_dot(G, sys.stdout)
strict digraph  {
	graph [rankdir=LR];
}
```

**Comment by anderspitman** [comment]
Beautiful, thank you. Confirmed that it also works using pydot.
