### ISSUE TITLE
Add approximation algorithm for feedback vertex set

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#2270]
The _minimum feedback vertex set problem_ is the problem of finding the smallest subset of vertices that, when removed, cause a graph to become acyclic. The problem is NP-complete in general, but there is [a 2-approximation algorithm](http://dx.doi.org/10.1137/S0895480196305124).

**Comment by JamesClough** [comment]
I've had an attempt at this in #2279

**Comment by babara2** [comment]
I was wondering if any progress has been made on this project. If not, I would like to give this a try and see what I can come up with.

**Comment by dschult** [comment]
Look at #2316 for the current status. It's been almost a year since the last activity so you should give it a try.
