### ISSUE TITLE
adding attr dict to non-existent edge causes graph inconsistency

### ISSUE THREAD

**Issue by gdbassett** [networkx/networkx#2271]
G.edge[node1][node2] = {"test":"test}

where G is of type networkx.classes.graph.Graph

will add an edge from node1 to node2, but node1 will not be in node2's neighbor list (G.neighbors(node2). This can lead to an inconsistent graph with an edge leading to a non-existent node.

(tested on networkx 1.11)

**Comment by jfinkels** [comment]
The method for adding edge to a graph is `G.add_edge(u, v)`. Modifying the underlying data structure dictionaries directly will certainly cause inconsistencies, but there's not much we can do about that (that's a feature of Python). So I guess all we can say in this situation is "don't do that". Is there some change to the code or documentation that you are requesting here?

**Comment by gdbassett** [comment]
I'll be honest, I didn't realize `G.edge[node1][node2] = {"test":"test}` wasn't a supported way of doing it.  I suppose some way of warning users not to use it would be best.

**Comment by jfinkels** [comment]
Perhaps a note in the [Edge Attributes][1] section of the tutorial and the class-level documentation for the `Graph` class to only read from `Graph.edge`, not write to it?

[1]: https://networkx.readthedocs.io/en/latest/tutorial/tutorial.html#edge-attributes
