### ISSUE TITLE
Protect master?

### ISSUE THREAD

**Issue by chebee7i** [networkx/networkx#2276]
Should we protect master now?  You can disable merges unless the status checks pass, but you can also require at least 1 "review".  This is a new feature in GitHub.

**Comment by MridulS** [comment]
Another new feature: https://github.com/networkx/networkx/projects .
It's a good way to keep track of short time and long time goals, example https://github.com/scikit-learn/scikit-learn/projects/5

**Comment by hagberg** [comment]
I don't think we need to protect the master branch but we could. Given then general way we work on this project i don't think it would change much.

I added a project page for networkx-2.0 https://github.com/networkx/networkx/projects/2
