### ISSUE TITLE
PDF Documentation Links are broken

### ISSUE THREAD

**Issue by thecapacity** [networkx/networkx#2281]
As an example: http://networkx.github.io/documentation/latest/_downloads/networkx_tutorial.pdf

Both (a) on the home page: https://networkx.readthedocs.io/en/stable/index.html

and (b) on the download page: https://networkx.readthedocs.io/en/stable/download.html

**Comment by Michael-E-Rose** [comment]
The links for https://networkx.readthedocs.io/en/stable/index.html are non-clickable (how could even know where they link to?), and were removed in 0ec1e80632d93ff91f0cc9729028387f828f87ce.  With the next networkx update the changes will go live and remove the text.

**Comment by hagberg** [comment]
Closed by #2344
