### ISSUE TITLE
The tools/ directory is out-of-date

### ISSUE THREAD

**Issue by aryamccarthy** [networkx/networkx#2283]
These files are dated and no longer used, now that Travis is used for continuous integration. The files have also not been updated to handle recent versions of Python.

This line in `/tools/test_pr.py` makes it clear:

``` python
supported_pythons = ['python2.6', 'python2.7', 'python3.2','python3.3']
```

**Comment by jfinkels** [comment]
I generally agree. The functions from `tools/test_pr.py` and `post_pr_test.py` seem to be covered by Travis. The functions from `tools/gh_api.py` are provided by other libraries (search "GitHub command line interface" and you'll find several).

**Comment by jtorrents** [comment]
Indeed this is a left over of the early migration to Github (circa 2012). That code was adapted from ipython but it's now obsolete (actually has been obsolete and unused for quite some time). I've created a pull request that removes the whole thing.
