### ISSUE TITLE
Networkx is missing

### ISSUE THREAD

**Issue by priyambial123** [networkx/networkx#2286]
Hi,
 I am using Python 2.7. I have installed  networkx, version 1.11-3. But when I tried to run the python file, I get the following error:error: networkx is missing, install it from https://networkx.lanl.gov/. I have also upgraded networkx using pip. Pls find the attached file
[network.txt](https://github.com/networkx/networkx/files/528885/network.txt)

Thank you
Regards
Priya

**Comment by pelegm** [comment]
Try, on your command line, executing the following line:
```sh
python -c "import networkx; print networkx.__version__"
```

If you get an `ImportError` then you don't have the module installed.

Look [here](https://networkx.github.io/documentation/development/install.html) for instructions.
