### ISSUE TITLE
NetworkX2 release TBA?

### ISSUE THREAD

**Issue by joanlopez** [networkx/networkx#2288]
Hi,

I'm currently using `networkx2`. 

I need this version because i'm using the Transitive Reduction method, so I want to know when this version will be published for production environments (PyPI, etc)?

Thanks!

PD: Are there any way to define this version as a dependency in my `setup.py`? Or it has to be released?

**Comment by hagberg** [comment]
Release date has been updated to March 15 2017 https://github.com/networkx/networkx/milestone/3
