### ISSUE TITLE
Networkx is missing

### ISSUE THREAD

**Issue by priyambial123** [networkx/networkx#2290]
Hi,
I have installed networkx 1.11-3 in Python 2.7. When I run the python rile, I get this error message: **\* error: networkx is missing, install it from https://networkx.lanl.gov/

I am sure that the networkx has been installed, but don't understand why I get this error message. I have attached the python file which throws up the error message.I have also attached the timemodel.txt file required for running the timemodel-python file. I have attached the python file in txt format as python couldn't be attached (timemodel-python.txt) Pls find it. Kindly help me to sort this issue.
Thank you
Regards
Priya
[timemodel-python.txt](https://github.com/networkx/networkx/files/537919/timemodel-python.txt)
[timemodel.txt](https://github.com/networkx/networkx/files/537920/timemodel.txt)

**Comment by jfinkels** [comment]
Hi @priyambial123. For help installing NetworkX, please send a message describing your issue to the NetworkX discussion group: https://groups.google.com/forum/#!forum/networkx-discuss. Briefly, if the command `python -c "import networkx"` produces no output, then NetworkX is installed correctly.
