### ISSUE TITLE
current_flow_betweenness_centrality self loops

### ISSUE THREAD

**Issue by kijoshua** [networkx/networkx#2292]
The result for current_flow_betweenness_centrality is quite different depending on whether or not you have self loops, but the documentation doesn't indicate which way is correct.  The networks I work with typically come from correlation matrices, so I by default have self loops.  But I assume in this case I need to remove them first?  Ideally self loops would just be ignored automatically.

Compared to the documentation for clustering, which clearly states "Self loops are ignored".

**Comment by hagberg** [comment]
Self loops are definitely included in the current flow betweenness centrality calculation.  Whether they are included *correctly* or not is a good question.  You can easily remove self-loops with `G.remove_edges_from(G.selfloop_edges())` where `G` is your networkx graph object.

**Comment by hagberg** [comment]
Closed due to inactivity.
