### ISSUE TITLE
write_graph6 uses excessive amounts of memory

### ISSUE THREAD

**Issue by basimr** [networkx/networkx#2295]
I am working with a graph of roughly 650,000 edges, with each vertex being a short string of <100 characters. I found that calling the write_graph6() function to write my graph to disk uses too much memory and takes significantly longer than the most other formats (I've tried adjlist, gexf, gml, pickle, YAML, and more).

In my tests, write_graph6() uses gigabytes of memory and over two minutes to write a 20,000 edge graph to disk, other methods take significantly less memory and mere seconds for my original 650,000 edge graph.

More specifically, for 10,000 edges the function uses ~5GB and with 20,000 edges it uses ~20GB of memory. When I try to use my 650,000 edge graph, my system (with 32GB of memory) runs out of memory and starts thrashing.

I've attached the 20,000 edge graph as an adjlist (delimited by two pipes: ||) and YAML.
[graph.adjlist.zip](https://github.com/networkx/networkx/files/563135/graph.adjlist.zip)
[graph.yaml.zip](https://github.com/networkx/networkx/files/563136/graph.yaml.zip)

**Comment by jfinkels** [comment]
Hi @basimr, thanks for the report. It looks like with a bit of review, the function can be rewritten to reduce its memory usage. Which version of Python are you using?

**Comment by basimr** [comment]
I'm using Python 3.5.2 and NetworkX 1.11-1.

**Comment by jfinkels** [comment]
I am working on a fix for this. The function seems to create the contents of the graph6 file as a string in memory before writing it to a file. Rewriting it so it makes better use of iterators and writes each chunk of data directly to the file should help.

**Comment by hagberg** [comment]
It looks like your graph.yaml.zip example has 20,000 edges and only 19967 nodes.  That is very sparse. 

The fact that your nodes are strings is not relevant because a label information is discarded with these formats. 

If you want to use a format like graph6 I suggest using sparse6 which will easily be able to handle large sparse graphs quickly and without so much memory.

```python
In [21]: G = nx.gnm_random_graph(100000,200000)

In [22]: %timeit len(nx.generate_sparse6(G))
1 loops, best of 3: 1.96 s per loop
```
