### ISSUE TITLE
node_link_data from readwrite.json_graph 

### ISSUE THREAD

**Issue by Beatzekatze** [networkx/networkx#2301]
I think I stumbled upon a bug in `node_link_data` function from `networkx.readwrite.json_graph `. Below the minimal example of what I mean .
```
import networkx.readwrite.json_graph as jg
import networkx as nx
G = nx.Graph()
G.add_nodes_from([3,4,5,6,7])
G.add_edge(3,4)
G.add_edge(4,5)
d = jg.node_link_data(G)
d["links"]
```
the return of it is `[{'source': 0, 'target': 1}, {'source': 1, 'target': 2}]`. The nodes are stored with their original id. 

(I use MacOs (10.11.5), python 2.7 and updated all packages to current pip version)

**Comment by hagberg** [comment]
On my test of your code the full value of d is
```python
In [2]: d
Out[2]: 
{'directed': False,
 'graph': {},
 'links': [{'source': 0, 'target': 1}, {'source': 1, 'target': 2}],
 'multigraph': False,
 'nodes': [{'name': 3}, {'name': 4}, {'name': 5}, {'name': 6}, {'name': 7}]}
```

The nodes are ordered in the list.  So your edge 3-4 translates to 0-1 etc.
