### ISSUE TITLE
`Accessing edges` of tutorial

### ISSUE THREAD

**Issue by LancelotHolmes** [networkx/networkx#2304]
When I am trying the sample one by one through the tutorial of NetworkX, I found a trivial error in the end of chapter of `Accessing edges`

```
for (u,v,d) in FG.edges(data='weight'):
      if d<0.5: print('(%d, %d, %.3f)'%(n,nbr,d))
```
and here I thought it should be 
`      if d<0.5: print('(%d, %d, %.3f)'%(u,v,d))`

**Comment by jfinkels** [comment]
Thanks for the report @LancelotHolmes! This has been fixed in the latest version of NetworkX: https://networkx.readthedocs.io/en/latest/tutorial/tutorial.html#accessing-edges
