### ISSUE TITLE
Waxman graph parameters interchange roles

### ISSUE THREAD

**Issue by joelmiller** [networkx/networkx#2310]
In the Waxman Graph, edges are placed with probability 

alpha x math.exp(-r/(beta x l))

However, in the usual definition the roles of alpha and beta are interchanged.

For example:
http://www.huaxiaspace.net/academic/classes/fa00/cse202/project/08Waxman.pdf

May be a tough one to fix for backwards compatibility.

**Comment by dschult** [comment]
Could we switch the order in the calling sequence when we change the names?
That should take care of backward compatibility when people haven't used keywords.
But it makes the parameter order out of alphabetic order: ```waxman_graph(100, beta, alpha)```

What do you think?

**Comment by joelmiller** [comment]
Seems reasonable to me.  But others may have stronger opinions.
