### ISSUE TITLE
Networkx can not read the attributes from .gexf file

### ISSUE THREAD

**Issue by sdrgroup** [networkx/networkx#2312]
1) networkx only supports .gexf of version 1.1, but now .gexf has already been version 1.3
2) after I change the .gexf to 1.1(by changing the head of xml), networkx can load the file but the attributes of node are only color, size and position, the other attributes between <attributes></attributes> are missing.

I use networkx of version 1.11
The operation system is ubuntu 16.04

**Comment by Michael-E-Rose** [comment]
Yes, networkx' standard version (xml namespace) is still on `'1.1draft'`, which is [deprecated](http://www.gexf.net/format/schema.html).

Would it be sufficient to simply change the default value of the version parameter?

**Comment by hagberg** [comment]
The gexf reader needs updating to version 1.3.

**Comment by Michael-E-Rose** [comment]
PR is live.

But why do you want version 1.3?  According to http://www.gexf.net/format/schema.html (January 2017) the recommended version is 1.2draft.
