### ISSUE TITLE
Feature request, persisting a graph

### ISSUE THREAD

**Issue by Charlesoxmt** [networkx/networkx#2313]
Whilst there are ample means of converting data types to basic Python types, Numpy, Pandas etc. that have their own methods of persisting, we also have Pickle.  Would there be any advantages in being compatible with some of the leading No-SQL graph databases as well?  NEO 4J or Orient DB?

**Comment by hagberg** [comment]
Sure, there would be some benefit from that.  If you have an implementation or plan please share it.

**Comment by Charlesoxmt** [comment]
No plan
