### ISSUE TITLE
Add SPQR tree for finding triconnected components and 2-vertex cuts

### ISSUE THREAD

**Issue by jfinkels** [networkx/networkx#2315]
NetworkX has a function for computing [biconnected components][1], maximal 2-vertex-connected subgraphs. It would be nice to have a function for computing [triconnected components][2], maximal 3-vertex-connected subgraphs, those subgraphs in which the removal of three vertices causes the graph to become disconnected. (Note: even though a subgraph may be 3-vertex-connected, the entire graph itself may only be 2-vertex-connected.) The [SPQR tree][2] data structure gives the algorithm for finding triconnected components, as well as an algorithm for finding each 2-vertex cut in the graph (that is, a pair of vertices whose removal disconnects the graph).

[1]: https://en.wikipedia.org/wiki/Biconnected_component
[2]: https://en.wikipedia.org/wiki/SPQR_tree

**Comment by jtorrents** [comment]
That would be a great addition to NetworkX. The tricky thing might be to do a linear time implementation. I attach here a dense paper on the subject for reference. 
[triconnected_components.pdf](https://github.com/networkx/networkx/files/621161/triconnected_components.pdf)

**Comment by JamesClough** [comment]
Is anybody else working on this? If not then I will have a go.

**Comment by jtorrents** [comment]
Hi @JamesClough , I'm not sure if @jfinkels is working on this. A PR adding this feature will be very welcome. I'll help you in any way I can to get it merged. Thanks!

**Comment by jfinkels** [comment]
I'm not working on it right now. Go for it!
