### ISSUE TITLE
Can networkx support  operations research？

### ISSUE THREAD

**Issue by fangqian** [networkx/networkx#2318]
Hello, I want to find some operations research methods,such as Queuing Theory（https://en.wikipedia.org/wiki/Queueing_theory）？

**Comment by jfinkels** [comment]
Hi @fangqian, I'm not sure exactly what you're looking for, but advice on how to use NetworkX in your own projects is best discussed on the [NetworkX mailing list][1].

[1]: https://groups.google.com/forum/#!forum/networkx-discuss
