### ISSUE TITLE
What is the difference between topological_sort and topological_sort_recursive?

### ISSUE THREAD

**Issue by anentropic** [networkx/networkx#2325]
The docs don't describe any difference, except that the latter is 'recursive'.

Are they expected to return the same result?

Is it just a matter of using a different algorithm, so they may have different performance depending on your graph structure?  (this is how it looks to me from reading the source)

It would be nice to have a hint about why both methods exist.

**Comment by dschult** [comment]
It looks like topological_sort_recursive was replaced in pull request #1756 
It is not in the latest development version.

**Comment by anentropic** [comment]
ok, thanks
