### ISSUE TITLE
Personalization in PageRank

### ISSUE THREAD

**Issue by pimotte** [networkx/networkx#2327]
In https://github.com/networkx/networkx/blob/master/networkx/algorithms/link_analysis/pagerank_alg.py in all algorithms, the personalization dict accepted needs a value for every node. In my personal application, most values are 0. I suspect that in a lot of applications, including the default, most nodes will have the same probability.
Furthermore, for all but the PageRank algorithm, the docstring suggests that each of these values needs to be non-zero. As far as I know, there is no code-technical or mathematical basis for this and it should be "at least one non-zero value".

My proposal:

- Add a parameter specifying a default value for personalization.
- Do not force presence of all keys in personalization, instead use default value for non-existant values.
- Rewrite docstrings to specify "at least one non-zero value"

I'll be happy to implement this. Feedback appreciated. :)

**Comment by hagberg** [comment]
I'm not sure why the documentation is unclear.  It should be "at least one non-zero value" as you suggest.

I'm less excited  about adding another keyword parameter for a default value.  In your use case the default is 0.  How about just allowing a dictionary with only some of the node keys and the rest get set to zero inside the pagerank functions?  If a user requires a different default from 0 then the full dictionary would need to be specified.

**Comment by pimotte** [comment]
The use case for a default value would be "values x, y, z for these nodes, then uniform over the rest".

I do agree with your reluctance for another parameter, and I suppose above use case is uncommon enough to require a full dict for it. I'll adopt your suggestion when implementing.

**Comment by hagberg** [comment]
It's reasonably easy to do that using dict.fromkeys()

```python
In [1]: import networkx as nx

In [2]: G = nx.path_graph(10)

In [3]: d = dict.fromkeys(G,0.5)

In [4]: d
Out[4]: 
{0: 0.5,
 1: 0.5,
 2: 0.5,
 3: 0.5,
 4: 0.5,
 5: 0.5,
 6: 0.5,
 7: 0.5,
 8: 0.5,
 9: 0.5}

In [5]: d.update({0:1,2:1})

In [6]: d
Out[6]: {0: 1, 1: 0.5, 2: 1, 3: 0.5, 4: 0.5, 5: 0.5, 6: 0.5, 7: 0.5, 8: 0.5, 9: 0.5}
```
