### ISSUE TITLE
json_graph.node_link_graph only accepts integer indicies in links

### ISSUE THREAD

**Issue by rhilenova** [networkx/networkx#2328]
The d3.js example [here](http://bl.ocks.org/mbostock/4062045) has the node names for the sources and targets. However, this graph fails to load using json_graph.node_link_graph:
```
.../anaconda/lib/python2.7/site-packages/networkx/readwrite/json_graph/node_link.py in node_link_graph(data, directed, multigraph, attrs)
    168             edgedata = dict((make_str(k), v) for k, v in d.items()
    169                             if k != source and k != target and k != key)
--> 170             graph.add_edge(mapping[src], mapping[tgt], ky, **edgedata)
    171     return graph

TypeError: list indices must be integers, not unicode
```

Shouldn't node_link_graph only use `mapping` if it gets integer indices?

**Comment by Michael-E-Rose** [comment]
This is the opposite of #2332, which is about producing a json graph, while this issue is about reading a json graph.

It's best to answer both issues together:  Should the mapping onto indexes still be possible (optional) or not?

**Comment by hagberg** [comment]
See #2332.  No need to map on to indices.
