### ISSUE TITLE
JSON exports no longer follow D3's preferred format as of D3 v4

### ISSUE THREAD

**Issue by bjlange** [networkx/networkx#2332]
The D3 [node/link JSON example](https://bl.ocks.org/mbostock/4062045), linked in the documentation, now expects source and target IDs in the link objects that are an attribute of the node objects which you specify when setting up the force-directed graph (e.g. `d.id`). Previously they expected indexes into the node list, you can see the change in the example gist [here](https://gist.github.com/mbostock/4062045/revisions?diff=split#diff-8143eda70191fa184211ddbe84974fbdL81). 

Should make things simpler for networkx users but assuming `node_link_data` is designed to target d3, the behavior of that should probably change (or at least, the link in the documentation should be taken out until it does).

Related to #2328 as well.

**Comment by Michael-E-Rose** [comment]
It's easy to change this behaviour by removing the mapping (i.e. `mapping = dict(zip(G, count()))` and subsequent use of this).

The question is: Should it still be possible to use indexes corresponding to the node list?  I could implement this with an optional parameter.

**Comment by hagberg** [comment]
I think we should just make it match the D3 v4 approach.  Integer indices were just there to make this work with D3.

**Comment by rhilenova** [comment]
I'm attempting to create a PR for this, but I'm not sure how to handle tuple nodes. The current code creates a node with the name `[0, 1]`, and then can successfully create edges by index. However, a quick test with [the example](https://bl.ocks.org/mbostock/4062045#index.html) doesn't look like it handles that format well.

**Comment by Michael-E-Rose** [comment]
Don't you just need to remove the mapping?  Because then the algorithm will just use the id's which are already there.

I had nearly finished a PR but wanted to wait for the others to be accepted.  It seem you're more advanced, @rhilenova, so go ahead with a PR and we have a look on the code!

**Comment by rhilenova** [comment]
If I just remove the mapping, `TestNodeLink.test_graph_with_tuple_nodes` fails (unhashable type list). I haven't tried to fix that issue yet, because it made me wonder what D3 would expect and if it even made sense for tuple nodes to be output to json.

**Comment by Michael-E-Rose** [comment]
Yes of course you need to adapt the test files. They expect integers but this must change.
