### ISSUE TITLE
timeformat undefined in gexf writing

### ISSUE THREAD

**Issue by DanielKinsman** [networkx/networkx#2336]
See the code [here](https://github.com/networkx/networkx/blob/networkx-1.11/networkx/readwrite/gexf.py#L567). There is no final `else`, meaning that if the type of the object isn't one of those listed (e.g. it is instead something like `unicode` in python 2.7.x), `timeformat` is undefined and things blow up.

Might submit a PR if I get some time.

**Comment by hagberg** [comment]
A fix would be appreciated.

Historical context for this kind of bad behavior:
http://users.csc.calpoly.edu/~jdalbey/SWE/Papers/att_collapse.html
