### ISSUE TITLE
Appveyor error in test_asyn_lpa.test_two_communities

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#2338]
About half the time one of the Appveyor configurations doesn't pass the test for two_communities.
That registers a failure for the Appveyor tests on many PRs that don't touch the asyn_lpa code. No such errors are found when done on Travis. 

The docstring for asyn_lpa_communities in algorithms/community/asyn_lpa.py says:

    The algorithm is probabilistic and the found communities may vary on different executions.

When the error occurs, it is because one large community is found instead of two.  Does it make sense to allow that test to produce a single community OR the "correct" two communities?

**Comment by jfinkels** [comment]
See pull request #2329 for a proposed solution.
