### ISSUE TITLE
Default value for set_node_attributes() with incomplete dictionaries

### ISSUE THREAD

**Issue by Michael-E-Rose** [networkx/networkx#2343]
When the dictionary that contains node attributes in `set_node_attributes()` has keys not present in the graph, there will be a KeyError.  That's because the algorithm iterates over the entries in the dictionary.

I find this annoying and would like to change this.  Instead the algorithm should iterate over the nodes.  To handle missing values I would add a few lines to either skip those entries (i.e. do not pass a value at all, as it's implicitly the case now) or to set a standard value.  The latter can also be achieved right now by two consecutive `set_node_attributes()` calls: the first one with a string and the second one with a dictionary.

I thought I ask first how you guys feel about.

**Comment by dschult** [comment]
When does the KeyError occur? The code only sets the attributes with keys
in the passed in dict. So it should not matter whether the graph nodes have
the attribute key present or not.

This routine could create a KeyError if a node in the passed in dict is not
a node in the Graph. Perhaps the confusion is whether ```values``` should
be a dict-of-attribute-dicts (e.g. {node:{key:value}}or an attribute-dict
(e.g. {key:value}).

**Comment by Michael-E-Rose** [comment]
Yes sorry, I updated/corrected my post in the meantime.  It is really about dictionaries with information on nodes not present in the graph.  This forces the user to first check and possibly reduce the dictionary.

**Comment by dschult** [comment]
Yes, it seems better to me also that we simply ignore nodes in the incoming dict that don't exist in the graph.  Thanks!

**Comment by Michael-E-Rose** [comment]
I will provide a PR once the other active PRs have been pulled with.  Otherwise, I believe, my suggestions build on other suggestions rather than the current head of master, don't they?

**Comment by dschult** [comment]
Which others that are active will delay this one?

**Comment by Michael-E-Rose** [comment]
#2344 and #2326, where the latter one is older.

**Comment by dschult** [comment]
#2344 and #2326 are now merged so we could take on set_node_attributes now.
Or we could bump it to networkx-2.1 instead. Its not a new feature so much as an enhancement.

**Comment by Michael-E-Rose** [comment]
I am now working on this. The relevant function is is [classes/function.py:369](https://github.com/networkx/networkx/blob/master/networkx/classes/function.py#L369)

There are basically three and a half approaches:

1. The simple fix where we still iterate over the dictionary: 

```
for node, value in values.items():
        try:
            G.node[node][name] = value
        except KeyError:
            pass
```

2. Iterating over nodes rather than keys:

```
for node in G.nodes():
        try:
            G.node[node][name] = values[node]
        except KeyError:
            pass
```

The second approach can be rewritten to use a default value (which requires a new optional parameter with default = `None`) that should be used when the node is not in the dictionary:

```
for node in G.nodes():
        G.node[node][name] = values.get(node, fill)
```

3. Finally we can rewrite the function such that it accepts dict-of-dicts, as in `{node: {attribute: value}}`.  In this case we can use the `.update()` method, but it requires us to transform an attribute-dict (`{attribute: value}`) if the passed dict is one:

```
# without transformation or check, which can probably be based on whether `name` is empty 
for node in G.nodes():
        G.node[node].update(values[node])
```

**Comment by dschult** [comment]
I'm inclined not to do option 2 because defaults can so easily be created by sending in a constant first. I'd really like to train people to make sure they are dealing with all nodes unless they really want not to.

I like the first option and the third option.  And I think we should simplify the case when values is a constant so that it just sets every node to that value rather than creating a potentially large dict in hard to read manner just to make it fit with the next lines of code.

So:   I see three cases:
 - name is None: ```for n,d in values.items(): G.node[n].update(d)```
 - values is dict/mapping:  ```for n,v in values.items(): G.node[n][name]=v```
    can try/except this looking for attributeError to see if values is dict/mapping 
 - values is not a dict/mapping:  ```for n in G: G.node[n][name]=values```
 
I'm slightly concerned about making this too complicated to manage (for users and maintainers). What do you think?

**Comment by Michael-E-Rose** [comment]
Agreed, proposal two is not optimal.

I also agree that a combination of parameters to achieve the same outcome (updating node attributes) from different input containers is quite complicated.

pandas has a different approach: They really want the user to pass a keyword based on which an incoming container is being handled.[ `.from_dict()`](https://pandas.pydata.org/pandas-docs/stable/generated/pandas.DataFrame.from_dict.html) is one such example.

For us this would mean to introduce another keyword (with or without default), come up with names for the three cases, and depending on the case throw errors when not sufficient additional parameters are filled.

The beauty of the last approach: We can later extend the code to cater for doing something with attributes. For example, when attributes are numbers I sometimes I want to sum them rather than replace them.

The downside of course is that it we make potentially common and simple operations complex for the sake of clarity of other, potentially less common operations. Then again, I have no clue what's more common: To update with dictionaries or with scalars.

**Comment by dschult** [comment]
If I understand you correctly the example of ```.for_dict()``` isn't actually passing a keyword based on which incoming container is being handled. It is a separate method for each incoming container type.

Ideally we would provide simple operations that can easily be connected together to do complicated things. I think your example of summing the attributes should be easy to construct with the current ```set_node_attributes``` and ```get_node_attributes```, right?  And the changes we're discussing here ought to help that -- allowing entire dicts lets us use ```G.node``` to update ```H.node```. And ignoring nodes in ```values``` let's us provide dicts with extra nodes not in G.

**Comment by Michael-E-Rose** [comment]
Yes, I guess my example was the opposite direction.

I finally came up with the following code:

```
def set_node_attributes(G, values, name=None):
    """"
    ....
    """"
    # Set node attributes based on type of `values`
    if name is not None:  # `values` must not e a dict of dict
        try:  # `values` is a dict
            for n, v in values.items():
                try:
                    G.node[node][name] = values[node]
                except KeyError:
                    pass
        except AttributeError:  # `values` is a constant
            for n in G:
                G.node[n][name] = values
    else:  # `values` must be dict of dict
        for n, d in values.items():
            try:
                G.node[n].update(d)
            except KeyError:
                pass
```

It's the three cases outlined above with the corresponding `KeyError` clause.  I guess could be simplified by transforming a dict to a dict-of-dict, or a simple scalar-like value case to a dict, which is however to the detriment of performance.

If you find this useful I will go ahead and update/amend the tests.

**Comment by dschult** [comment]
Yes, that looks good!   Go ahead and update/amend the tests. 
Thanks!

**Comment by Michael-E-Rose** [comment]
When we accept that `name` gets a default value (namely `None`) then it must come after parameter `values`.  This means we change the ordering of attributes so I would have to add a text for the release notes.  I see this issue is now assigned for networkx2.1, but there are no release notes for 2.1 yet.  Where should I add this then?

The more sever thing however is `.set_edge_attributes()`.  To stay consistent we should change the ordering there as well.  And while we're at it, we can as well implement above code for the edge attributes.  Maybe some of the code can be outfactored in a private function.  Do you agree?

**Comment by dschult** [comment]
If we're changing the order of parameters we ought to make this v2.0

Yes we should change the ```set_edge...``` interface to match this.  Stick with the current requirement for tuples as edges.  Multi graph must include key.  

I don't think these will become complex enough to warrant out factored code, but you can be the judge of that.  Whatever makes it easy to maintain and understand.

**Comment by Michael-E-Rose** [comment]
PR is live. There's a merge conflict in doc/source/reference/release_2.0.rst but I cannot solve it.

The code for `set_edge_attributes()` looks quite ugly, but it works and is consitent with `set_node_attributes()`.
