### ISSUE TITLE
add verbosity to find_cliques

### ISSUE THREAD

**Issue by DonBeo** [networkx/networkx#2345]
I am wondering if it is possible to add a sort of progression bar to the find_cliques algorithm. 

I think it would be useful to give the user an idea of how long the algorithm will take.

**Comment by dschult** [comment]
The generic answer is "a long time". :)  Finding cliques is hard.

Do you have suggestions on how to estimate the progression?
The time remaining depends on things like ram and cpu speed.
Maybe there's another measure other than time?

**Comment by DonBeo** [comment]
I am not familiar with the algorithm that is used to find the cliques. 

The time is probably not an option.   I was thinking on a log that reports the number of nodes already scanned and the number of nodes still remaining or something like that. 

I was using it and after 10 minutes it was still processing. Then I was wondering would it finish in one hour or will it take one year?   Having a measure of the size of the graph that was already processed would be useful but I do not know if it is possible.

**Comment by hagberg** [comment]
We don't have any progress bar technology set up.  As @dschult points out it is difficult to estimate run time for some algorithms.
