### ISSUE TITLE
Add bellman-ford as alternative algorithm in generic shortest path solving method

### ISSUE THREAD

**Issue by dzhuang** [networkx/networkx#2346]
As documented [here](https://networkx.readthedocs.io/en/latest/reference/algorithms.shortest_paths.html)(**UPDATE**, the url was moved to [here](https://networkx.github.io/documentation/latest/reference/algorithms/shortest_paths.html#module-networkx.algorithms.shortest_paths.generic)), some generic method for solving undirected and directed shortest path problem, including ``shortest_path``, ``all_shortest_paths``, ``shortest_path_length`` and ``average_shortest_path_length``.

Those method are actually using dijkstra algorithm according to the source code. I think it reasonable if we are using those method for problems (e.g., social networks) with non-negative edge weights. However, since the naming of those method are not method-specific, they should be able to deal with situations when there exists negative weighted edges in a graph. Bellman-ford is also able to solve undirected graphs if there exist no negative weighted edges, and for undirected graphs with negative weighted edges, it will raise errors since that graph will be views as a graph having negative loops if converting to a directed graph. Therefore, I think we should integrate bellman-ford method into those methods, at least allow it as an alternative method when users are calling those functions.

**Comment by AvijitGhosh82** [comment]
This was a problem I genuinely faced in my research project, as I had a task of finding the path with the highest product of weights. Taking negative log and then applying shortest path was giving me incorrect answers. 

Will be great if this is solved.

**Comment by dschult** [comment]
Fixed in #3098

**Comment by dzhuang** [comment]
@dschult Thank you for the fix!

**Comment by scutsmash** [comment]
Teacher zhuang,I do not know what you want to say.If you can express it more clearly,I think it would be better.

**Comment by scutgeorge** [comment]
@scutsmash new bee
