### ISSUE TITLE
Problem With Networkx Hash Function

### ISSUE THREAD

**Issue by kris-singh** [networkx/networkx#2349]
https://gist.github.com/kris-singh/8b89ae2ea40c6a966795556e788212bd
Can you look at this. I am not able to figure why this is happening.

**Comment by hagberg** [comment]
I think the most likely problem is in the `__hash__` or `__eq__` functions of the custom object you are using for nodes (`DiscreteFactor`) .  Those look pretty complicated and might not be working they way you expect. 
We had a longer discussion about using custom objects here https://github.com/networkx/networkx/issues/2282 of you are interested in the topic.
