### ISSUE TITLE
Multiple test failures on Python 3.6

### ISSUE THREAD

**Issue by matthew-brett** [networkx/networkx#2350]
Both current master (commit 862cc2b) and release 1.11 have multiple test failures when running the test suite on Python 3.6 (in my case, on OSX, with Python.org Python). On master:

```
----------------------------------------------------------------------
Ran 2996 tests in 51.441s

FAILED (SKIP=10, failures=70)
```

For release 1.11: 

```
----------------------------------------------------------------------
Ran 2742 tests in 30.889s

FAILED (SKIP=10, failures=69)
```

**Comment by hagberg** [comment]
Thanks for the bump.  We have been working on this in #2319.  I think all of the test are passing now except for the doctests.  We'll need to figure out what to do with those and then merge.

**Comment by matthew-brett** [comment]
Thanks for the feedback, sorry I didn't notice the other PR.    I'll close this one in favor of the other.
