### ISSUE TITLE
Depth-limited Breadth First Search

### ISSUE THREAD

**Issue by Abdulhakeem135** [networkx/networkx#2352]
It would be very good to have a new parameter to the breadth-first search function like "distance" which is  None by default – the maximum distance from the start nodes to traverse. 

bfs_tree(G, source,**distance=None**, reverse=False)

I want to start breadth first search from start node for a specific distance.

**Comment by jfinkels** [comment]
I believe this is the same as #2258, but for breadth-first search instead of depth-first search.

**Comment by Abdulhakeem135** [comment]
Yes, it is exactly the same. I also found this #2116. But it might be better to rename the variable as breadth_limit, since we have here a breadth-first search technique. I am not sure if this has been done or not yet. This is my first contribution to open-source and still do not know what is going one here.

**Comment by mohdkashif93** [comment]
If nobody else is working on this issue, can I work on it ?

**Comment by dschult** [comment]
Yes, that would be helpful! Why don't you structure it as a module within ```algorithms/traversal``` with naming similar to ```edgedfs.py``` along with a test module ```tests/test_edgebfs.py``` Look around at other code for example, the github networkx wiki for odds and ends and ask questions here.

Thanks very much!

**Comment by dschult** [comment]
Sorry... I got confused in my previous answer about depth_limit for ```bfs_*``` functions. Please see my edits to that message.  Thanks

**Comment by gmyr** [comment]
I would also be interested to help out on this issue, but Mohammed was quicker. :)
Are there any other issues on this project a new-comer to open source development could tackle?

**Comment by dschult** [comment]
Take a look at the issues with the tag: "Good first issue", or "Needs PR".
Some are quite involved -- others more straightforward.

Some very interesting ones that will get you reading the literature as well as coding are #1609 and #1457

**Comment by dschult** [comment]
@gmyr would you like to take a look at this one (depth limit on breadth-first-search) #2352
we've got a PR but it has been almost 3 weeks since any activity and I think the code would be quick to get right.  Let me know -- if you don't, I will get to it :)

**Comment by mohdkashif93** [comment]
Sorry for the delay. I am still working on it and will get this done by this weekend positively. Sorry for the inconvenience caused.

**Comment by gmyr** [comment]
I will take a shot at it if it's still open after the weekend. :)
