### ISSUE TITLE
Replace "making a patch" with "Creating a PR"

### ISSUE THREAD

**Issue by OrkoHunter** [networkx/networkx#2353]
As being pointed out in the mailing list, I think [making a patch](https://networkx.readthedocs.io/en/stable/developer/gitwash/index.html) page in the documentation is little misleading and we should remove or replace with "Creating a Pull Request" page.

**Comment by Michael-E-Rose** [comment]
Given that there is extensive explanation of pull requests in the [development workflow](https://networkx.readthedocs.io/en/stable/developer/gitwash/development_workflow.html), I'd suggest to dump the section on patching altogether.

**Comment by dschult** [comment]
I agree...  We should just have info for how to create a PR on github. I believe the current instructions have them use github to create the repos and then create a patch and by that time a PR is quite straightforward.
