### ISSUE TITLE
number_of_edges between two nodes returning incorrect number 

### ISSUE THREAD

**Issue by simonvanderveldt** [networkx/networkx#2356]
I'm running into a strange issue where `number_of_edges()` doesn't return the actual edges between 2 nodes, but seems to be either returning 0 when there are no edges between and 1 in all other cases even when there are multiple edges between the 2 nodes.

I'm using networkx 1.11

Example code:
```
type(G)
> <class 'networkx.classes.multidigraph.MultiDiGraph'>
G.in_edges('node1')
> [('node2', 'node1')]
G.out_edges('node1')
> [('node1', 'node2')]
G.number_of_edges('node1', 'node2')
> 1
```

Am I doing something wrong/misunderstanding things or is this really not working the way it should?

**Comment by hagberg** [comment]
In this case, since you have a digraph, the method `number_of_edges` counts the directed edges between the source ('node1') and target ('node2').   That is consistent with using `number_of_edges` on the whole graph (edges are only counted once).   The documentation should say (and doesn't) that it counts directed edges.

**Comment by simonvanderveldt** [comment]
> In this case, since you have a digraph, the method number_of_edges counts the directed edges between the source ('node1') and target ('node2'). That is consistent with using number_of_edges on the whole graph (edges are only counted once). The documentation should say (and doesn't) that it counts directed edges.

@hagberg Thanks for the clarification. Adding it to the docs to prevent confusion would be nice :)

I'd actually expect `number_of_edges` to return the actual number of edges for every type of multigraph. Otherwise what's the use of `number_of_edges`?

For now I worked around it by checking:
```
if G.get_edge_data('node1', 'node2') and G.get_edge_data('node2', 'node1')
```
And then creating a unique list of those node combinations, which seems to work.
