### ISSUE TITLE
The documentation for shortest_path() is confusing

### ISSUE THREAD

**Issue by edouardklein** [networkx/networkx#2363]
I have a Directed, potentially cyclic graph. I need to find the shortest path between two nodes.

shortest_path() won't work (quite randomly so, I believe serializing the graph and then loading it back up (and thus changing the order of nodes and edges in the internal representation) made it work once) because it assumes that G is undirected.

I think it would be nice if shortest_path()'s doc made that fact clear. I can write a proposal and make a pull request if the maintainers agree this is the way to go.

In order to solve my problem, I tried dijkstra_path(), which appear to work on directed graphs. Looking at the code, I fail to understand why shortest_path exists as anything more than a wrapper for dijkstra_path with all weight set at 1. Is there a reason for shortest_path having its own, separate implementation of a less generic dijkstra ?

**Comment by dschult** [comment]
My understanding is that shortest_path works fine on DiGraphs (and thus on
DAGs).  It may not be as efficient as a shortest path algorithm that is
designed specifically for DAGs, but it is the standard algorithm for
general DiGraphs.

In what sense do you mean that shortest_path "won't work"?  Can you provide
a simple example?

The reason we have dijkstra versions separate from the algorithms for
unweighted graphs is efficiency. If all weights are 1 (a common case) we
use the more efficient algorithm for that case.

**Comment by edouardklein** [comment]
Thank you for your answer.

shortest_path(), when provided with a source and target, will call bidirectional_shortest_path()

https://github.com/networkx/networkx/blob/master/networkx/algorithms/shortest_paths/generic.py#L142

which sometimes fails with a networkx.exception.NetworkXNoPath if one part of the path is directional.

I can not give you the graph as is, because it contains data that I can not share, and when I serialize and deserialize it, the problems sometimes disappears.

If you feel that shortest_path() should work on directed graphs (as I do, too) then I'd be happy to construct a minimal (not)working example that we can then use as a test case.

**Comment by edouardklein** [comment]
I can't reproduce the bug with a nice minimal working example, so instead I'll strip the offending graph of all that data that I can not share, and see where I can go from there. It may take a while.

**Comment by hagberg** [comment]
The network.convert_node_labels_to_integers() function might help.

**Comment by edouardklein** [comment]
When I serialize using write_edgelist, and deserialize using read_edgelist, the error  networkx.exception.NetworkXNoPath disappears.

I have a iPython console on a instance of my program where the bug exists, I'll try my best to serialize the graph in a way that  makes the bug appear when loading the data. Then I'll strip the data (thanks for the ref, hagberg). I'll keep you posted ASAP.

**Comment by ericmjl** [comment]
@edouardklein when you re-read the edgelist, do you instantiate it as a Directed graph? I'm assuming you do, but just wanted to do a sanity check.

**Comment by edouardklein** [comment]
@ericmjl I actually didn't, but when I do, it still works.

The GML serialization is unhappy with boolean attributes (I serializes them as a raw False or True in the file, and that can't be read back). I'm running s/False/0/ s/True/1/ on the file as a workaround for now

**Comment by edouardklein** [comment]
Hurray ! I can reproduce the bug with pickle serialization/deserialization

**Comment by edouardklein** [comment]
When I use convert_node_labels_to_integers(), the bug does not happen in the returned graph

**Comment by edouardklein** [comment]
When I try to relabel in-place, I hit the following Exception, which may be tied to the problem at hand
```
 nx.relabel_nodes(G2, hash, copy=False)
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-56-07e85138ffc3> in <module>()
----> 1 nx.relabel_nodes(G2, hash, copy=False)

/usr/local/lib/python3.4/dist-packages/networkx-2.0.dev20170126091612-py3.4.egg/networkx/relabel.py in relabel_nodes(G, mapping, copy)
     93         return _relabel_copy(G, m)
     94     else:
---> 95         return _relabel_inplace(G, m)
     96
     97

/usr/local/lib/python3.4/dist-packages/networkx-2.0.dev20170126091612-py3.4.egg/networkx/relabel.py in _relabel_inplace(G, mapping)
    142                 new_edges += [(new if old == source else source,new,data)
    143                               for (source,_,data) in G.in_edges(old, data=True)]
--> 144         G.remove_node(old)
    145         G.add_edges_from(new_edges)
    146     return G

/usr/local/lib/python3.4/dist-packages/networkx-2.0.dev20170126091612-py3.4.egg/networkx/classes/digraph.py in remove_node(self, n)
    458             raise NetworkXError("The node %s is not in the digraph."%(n,))
    459         for u in nbrs:
--> 460             del self.pred[u][n] # remove all edges n-u in digraph
    461         del self.succ[n]          # remove node from succ
    462         for u in self.pred[n]:

KeyError: 'REDACTED'
```

**Comment by edouardklein** [comment]
Okay, there's a highly suspect line in my code, where the edge dict gets modified behind networkx's back.

I'll correct that and see if the bug persists.

**Comment by edouardklein** [comment]
I have change a line like this
```
G.edge[src][dst_new] = G.edge[src][dst_old]
```
to

` G.add_edge(src, dst_new, **G.edge[src][dst_old])`

and now it seems to be working.

I apologize for incorrectly assuming that shortest_path() did not work on directed graphs, and thus wasting your time here. Thank you for your help. I hope my next contributions will be more helpful :)

**Comment by edouardklein** [comment]
Still it's amazing how long that bug flew under the radar. This code was deployed for month before a particular input made shortest_path fail. Plus, the edge modification was far away (both conceptually in the code and time-wise) from the path search.
