### ISSUE TITLE
Can't find documentation about networkx versioning

### ISSUE THREAD

**Issue by zfrenchee** [networkx/networkx#2367]
Hello! 

I was wondering if I could build a graph from a pandas dataframe, and lo and behold, discovered [this page on read the docs](http://networkx.readthedocs.io/en/latest/reference/generated/networkx.convert_matrix.from_pandas_dataframe.html). It seems this method is only available in networkx version 2.0:

<img width="598" alt="screen shot 2017-02-22 at 2 07 28 pm" src="https://cloud.githubusercontent.com/assets/2761597/23227848/5c9f0d9e-f908-11e6-8c70-9b46ba53698d.png">

Which gets me into trouble when I try to:

```
» pip3 install -V 2.0 networkx 
Collecting 2.0
  Could not find a version that satisfies the requirement 2.0 (from versions: )
No matching distribution found for 2.0 
```

Strangely enough though, with version 1.11, 

```
>>> from networkx import from_pandas_dataframe
>>>
```

I'm a little confused but don't have an immediate problem. I might be making a silly mistake somewhere, but if not, there should be some more clarity as to what versions support what methods, imo. 

Thanks!

**Comment by dschult** [comment]
I'm confused... There are similar readthedocs webpages with that method for V1.10 and V1.11.
Why do you think the method is only available for version 2.0?

**Comment by zfrenchee** [comment]
@dschult because that's what showed up in google, but since it's in previous versions this isn't an acute issue for me anymore. Nevertheless it would be nice if information about versioning were in the README (or anywhere, really)

**Comment by hagberg** [comment]
Version info is on the networkx.github.io front page.

http://networkx.github.io/

**Comment by zfrenchee** [comment]
Got it. This page is also relevant: https://github.com/networkx/networkx/milestone/3
