### ISSUE TITLE
CONTRIBUTING.md

### ISSUE THREAD

**Issue by zfrenchee** [networkx/networkx#2368]
Hello! 

I have a fast algorithm for the Prize Collecting Steiner Problem, a generalization of MST which might be of use to some people using this library. It might make sense to add it, but I don't see any information about contributing to this repo. It might make sense for people like me for you to add a `CONTRIBUTING.md` file. Just my two cents =)

**Comment by Michael-E-Rose** [comment]
If I understood the developers correctly they rather use the wiki: https://github.com/networkx/networkx/wiki

**Comment by zfrenchee** [comment]
@Michael-E-Rose there's no information on the wiki about what to contribute. E.g. if I wanted to contribute my algorithm, there's no information as to whether that would be welcome, what the governance structure for the project is, or what direction it wants to move in.

**Comment by Michael-E-Rose** [comment]
There's also a part on contributing in the Developer Guide on read the docs: https://networkx.github.io/documentation/networkx-1.9/developer/index.html
It's unfortunately a bit outdated, which #2371 is going to fix.

Whether networkx should have `CONTRIBUTING.md` or not is up to the developers, I would say.
