### ISSUE TITLE
Could networkx draw imported shape files like OSMnx?

### ISSUE THREAD

**Issue by joaokho** [networkx/networkx#2376]
Could networkx import simple shape files, then drawing using matplotlib or other that can view like OSMnx graph like this?

![az-simplify-strict](https://cloud.githubusercontent.com/assets/943439/23544748/c2bafaba-002a-11e7-9d04-af4981e08675.png)

**Comment by hagberg** [comment]
Yes, but that is what OSMnx was designed to do.  It uses matplotlib and networkx.

**Comment by joaokho** [comment]
Thanks @hagberg , I already found the easy way.
After nx.read_shp(), then nx.write_shp() that's will produce 2 shape files (for nodes & edges), that will easily open using gis desktop tool like qgis to screen capture the view. :-)
