### ISSUE TITLE
nx.relabel_nodes does not relabel nodes when exported to JSON

### ISSUE THREAD

**Issue by jeffzemla** [networkx/networkx#2377]
I have a graph and I relabel the nodes:

`g2 = nx.relabel_nodes(g, items, copy=False)`

However when I go to export the graph to JSON format, the node `id`s have changes but the edge `id`s have not.

e.g., 

`json_graph.node_link_data(g2)`

results in 

`[{'id': 'canary'}, {'id': 'crocodile'}, ...
'links': [{'source': 0, 'target': 26, 'weight': 1}, {'source': 0, 'target': 7, 'weight': 1}, ...
`

Which obviously is no use, because I don't know which number goes with which label.

**Comment by hagberg** [comment]
Aren't the source and target indices ordered, 0,1,... in the node list (the first array above)?

**Comment by jeffzemla** [comment]
I suspect they probably are initially, but JSON objects are inherently
unordered. Importing and exporting JSON objects is likely to cause problems
because order is not guaranteed to be preserved.

**Comment by hagberg** [comment]
I thought the list order would be preserved.    This JSON format for graphs is not one NetworkX invented.  It is/was used in d3.js.  See also #2332

**Comment by jeffzemla** [comment]
Ah, #2332 appears to the same issue.
n Per json.org, JSON objects are `unordered set of name/value pairs`. For that matter Python `dict`s are unordered as well. I suspect that's why D3 [no longer uses indices](https://gist.github.com/mbostock/4062045/revisions?diff=split).

Swapping indices for labels in the links array shouldn't affect the ordering of nodes, so it should work for anyone using D3 v3 *or* v4. I agree with your comment in [the other thread](https://github.com/networkx/networkx/issues/2332#issuecomment-272744667), the JSON format should match the current D3 approach.

**Comment by hagberg** [comment]
Let's fix this in #2332.
