### ISSUE TITLE
compute the average_shortest_path_length for the components of multi-directed graph got a 'not implemented for directed type' exception

### ISSUE THREAD

**Issue by LancelotHolmes** [networkx/networkx#2379]
I'd like to calculate the `average_shortest_path_length` in my multi-directed graph but there is a node not connected with other nodes
![figure_1-1.png](https://ooo.0o0.ooo/2017/03/07/58be169a5d952.png)

but according to the notes in [NetworkX](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.algorithms.shortest_paths.generic.average_shortest_path_length.html?highlight=average%20path%20length#networkx.algorithms.shortest_paths.generic.average_shortest_path_length)
> For disconnected graphs you can compute the average shortest path length for each component: >>> G=nx.Graph([(1,2),(3,4)]) >>> for g in nx.connected_component_subgraphs(G): ... print(nx.average_shortest_path_length(g)) 1.0 1.0

 it should work with components, so I try the code before
```python
for g in nx.connected_component_subgraphs(sub_MDG):
    print nx.average_shortest_path_length(g)
```
but ends up with an exception like
`networkx.exception.NetworkXNotImplemented: not implemented for directed type`
however if I remove the single node from the network,I can compute the average shortest path length for the network, so I wonder how I can calculate the average shortest path length in a multi-directed graph with several node not connected?

**Comment by hagberg** [comment]
Try using
`nx.weakly_connected_component_subgraphs()`
since your graph is directed.
