### ISSUE TITLE
k-regular graph produces a RuntimeWarning on degree_assortativity_coefficient

### ISSUE THREAD

**Issue by mojaie** [networkx/networkx#2380]
Environment: Python 3.6.0, NetworkX Version: 1.11

k-regular graph produces a RuntimeWarning on degree_assortativity_coefficient because of no variance in degree distribution.

Input
```
import networkx as nx

G = nx.random_regular_graph(5, 10)
nx.degree_assortativity_coefficient(G)
```

Output
```
RuntimeWarning: invalid value encountered in double_scalars return (xy*(M-ab)).sum()/numpy.sqrt(vara*varb)
nan
```

**Comment by dschult** [comment]
This sounds like what it should do. What do you think it should do?

**Comment by mojaie** [comment]
Actually I encountered this warning in network analysis with various threshold of edge formation. Regular graph can accidentally occur in some type of analysis and I think RuntimeWarning is not preferrable because we cannot get information why it has failed.

So my opinion is

- Catch if degree variance of degree distribution is zero
- And document that this function can return nan if given graph is a regular graph.
