### ISSUE TITLE
Depending on fiona instead of gdal for reading shapefiles

### ISSUE THREAD

**Issue by oztalha** [networkx/networkx#2382]
Big spatial packages now read shapefiles using different libraries, e.g. @sgillies stated that

> Fiona and Rasterio pretty much replace osgeo.ogr and osgeo.gdal

NetworkX conflicts with Shapely, better come to a common term: https://github.com/Toblerity/Shapely/issues/262#issuecomment-285791048

**Comment by hagberg** [comment]
Needs a shapefile expert to sort this out please.

**Comment by MridulS** [comment]
Support for shapefiles I/O is deprecated in NetworkX https://github.com/networkx/networkx/pull/4298. There are a bunch of [new examples in our gallery for users who want to work with geospatial data and networkx](https://networkx.org/documentation/latest/auto_examples/index.html#geospatial).

https://github.com/geopandas/geopandas/issues/1592 discusses the enhancement proposal of interop between geopandas and networkx.
