### ISSUE TITLE
is my MST really the minimum?

### ISSUE THREAD

**Issue by lxkain** [networkx/networkx#2390]
I'm doing:

```
P = squareform(pdist(X))
graph = nx.Graph(P)
tree = nx.minimum_spanning_tree(graph)
edges = tree.edges(data=True)

plt.plot(X[:,0], X[:,1], 'b.')
for i, j in tree.edges():
    plt.plot(X[[i, j], 0], X[[i, j], 1], 'r')
```

which gives the attached plot. However, looking at the place where the tree bifurcates, it seems like there would be a better solution by connecting the two top dots. Bug? User error? Nearly-optimal algorithm?
![figure_1](https://cloud.githubusercontent.com/assets/15930505/24009241/9976153e-0a31-11e7-9026-b1c35983796a.png)
?

**Comment by chebee7i** [comment]
Can you construct the path that you think would be optimal and see if it is actually lower? We don't have your data :)

**Comment by lxkain** [comment]
I must sheepishly admit that I - obviously - did not scale the axes equally. Which is why I made the graphical argument. I apologize for taking up your time with my mistake. Case closed!
