### ISSUE TITLE
Is the closeness centrality being normalised correctly?

### ISSUE THREAD

**Issue by jorgecarleitao** [networkx/networkx#2391]
The code to compute the [closeness centrality](https://networkx.github.io/documentation/development/reference/generated/networkx.algorithms.centrality.closeness_centrality.html#networkx.algorithms.centrality.closeness_centrality) of a node `n` [is given by](https://github.com/networkx/networkx/blob/master/networkx/algorithms/centrality/closeness.py)

```
sp = path_length(G,n)  # all shortest paths from n to all other nodes.
totsp = sum(sp.values())  # the sum of all shortest paths.
if totsp > 0.0 and len(G) > 1:
    closeness_centrality[n] = (len(sp)-1.0) / totsp
    # normalize to number of nodes-1 in connected part
    if normalized:
        s = (len(sp)-1.0) / ( len(G) - 1 )  ## FOCUS HERE
        closeness_centrality[n] *= s
else:
    closeness_centrality[n] = 0.0
```

I am struggling to understand why, in the normalized case,

```
closeness_centrality[n] = (len(sp)-1.0)*(len(sp)-1.0)/( len(G) - 1 ) / totsp
```

Shouldn't the normalized case be given by 

```
closeness_centrality[n] = ( len(G) - 1 )/ totsp 
```

So it corresponds to the formula given in the documentation?

(corresponds changing `closeness_centrality[n] *= s` to `closeness_centrality[n] /= s` in the source). I can PR this.

**Comment by ulfaslak** [comment]
I concur this appears to be a pretty serious bug. The normalization term should be inverted or divided onto `closeness_centrality[n]`.

**Comment by hagberg** [comment]
Take a look at our earlier discussion and give your opinion on what we
should do https://github.com/networkx/networkx/issues/2126

**Comment by hagberg** [comment]
I'm going to close this.  Please add discussions to the longer thread at #2126.
Let's try to get consensus on what the best (or least confusing) approach is.

**Comment by dschult** [comment]
#2595 should address this concern.
