### ISSUE TITLE
Broken link in documentation

### ISSUE THREAD

**Issue by tdhopper** [networkx/networkx#2392]
https://github.com/networkx/networkx/blob/91d3de2ce319c60f8217c08b2e6831ee6ee45284/networkx/drawing/nx_pylab.py#L102 links to  http://networkx.github.io/documentation/latest/gallery.html which doesn't exist.

**Comment by changebias** [comment]
Hello.

I found the same bug. The page https://networkx.github.io/documentation/stable/tutorial.html#drawing-graphs has link _See Drawing for additional details_ to https://networkx.github.io/documentation/latest/gallery.html, but https://networkx.github.io/documentation/latest/gallery.html returns 404.

**Comment by dschult** [comment]
Perhaps we should put a redirect to https://networkx.github.io/documentation/latest/auto_examples/index.html
