### ISSUE TITLE
maximal_matching and max_weight_matching have different matchings on unweighted graph

### ISSUE THREAD

**Issue by jlaw9** [networkx/networkx#2393]
On this simple, unweighted graph, maximal_matching and max_weight_matching return different sizes of matchings.
A maximal matching would be (a,f), (c,d) and (b,e), however, the maximal_matching function only finds two matchings instead of three.

``` python
>>> import networkx as nx
>>> g = nx.Graph()
>>> g.add_edges_from([('a','e'),('a','d'),('a','f'),('b','c'),('b','e'),('c','d'),('c','e'),('e','f')])
>>> nx.max_weight_matching(g)
{'a': 'f', 'c': 'd', 'b': 'e', 'e': 'b', 'd': 'c', 'f': 'a'}
>>> nx.maximal_matching(g)
set([('c', 'b'), ('a', 'e')])
```
 
![figure_1](https://cloud.githubusercontent.com/assets/7592559/24074645/3227f790-0be3-11e7-95bc-90a11adcf5e8.png)

**Comment by jlaw9** [comment]
Sorry this is a duplicate of #1564 and #2156

**Comment by hagberg** [comment]
The functions might be a little hard to understand by the names - they should perhaps be maximal_matching and maximum_matching.  I think you are getting the correct answers for both algorithms though - set([('c', 'b'), ('a', 'e')]) is a maximal matching - you can't add any other edge and still have a matching.
