### ISSUE TITLE
Interim 1.12 Release – Can It Be?

### ISSUE THREAD

**Issue by leycec** [networkx/networkx#2396]
Thanks for all the graph, NetworkX. Sadly, time waits for no coder.

It's been well over a year since the [last stable release](https://github.com/networkx/networkx/releases) (1.11). NetworkX's release schedule had been quite proactive up until that inexplicable roadblock, with most pre-1.11 releases tagged within several months of the prior release. For... _reasons_, post-1.11 development fully stalled out and has failed to release a stable version since then.

The **[NetworkX 2.0](https://github.com/networkx/networkx/projects/2)** project page suggests 10 pull requests require review and 11 outstanding issues require pull requests... *that don't exist yet.* It's the latter dependency that concerns me.

I'd love for NetworkX 2.0 to happen tomorrow. It's pretty self-evident that it's not, though – which is probably a good thing. All good things come to those who patiently post issues, integrate NetworkX into downstream applications, and endlessly bicker on [/r/Python](https://www.reddit.com/r/Python). <sup>_Maybe not that last one._</sup>

In the interests of opening up this massive changeset to a larger QA audience and incrementally creeping up to the congratulatory fireworks of 2.0, would an interim pre-2.0 release be feasible? Say, either a stable 1.12 release *or* an unstable 1.99 pre-release *or* **[**`insert good idea here`**]**?

If not, that's cool. It's just been *soooo* long. You know? Sad face. 😂

**Comment by hagberg** [comment]
I agree that we should make a release ASAP.  

We made quite a few changes with the base graph class functions since 1.11.   I'd like to label the next release 2.0 to indicate that.  

I think the short-term options are either to 
1) drop some of the 2.0-tagged issues and milestones and expedite the 2.0 release
2) make a networkx-1.99 release as a 2.0 pre-release

Other ideas or comments?

**Comment by jtorrents** [comment]
I think it's better to drop some of the 2.0-tagged issues and expedite the 2.0 release. Looking at the issues and pull requests currently tagged 2.0, I think most of them are not actually show stoppers and can be safely postponed. We should figure out the travis problems with python 3.6 in #2413 as I think it's essential to be fully compatible with 3.6 for the release.

However the big thing that still needs to be done (both if we release 2.0 or do a 1.99 pre release) is writing up all API changes and new features in the documentation.

**Comment by MridulS** [comment]
Side note: for API changes we have this https://github.com/networkx/networkx/blob/master/doc/source/reference/release_2.0.rst

**Comment by jtorrents** [comment]
Nice! didn't notice that we already had a draft for 2.0 API changes.

**Comment by dschult** [comment]
I'd like to get views instead of iterators for edges/nodes/degree/etc.
I will have some time in May to work on that. I guess it could also be in 2.1 if needed.

**Comment by hagberg** [comment]
I agree with @dschult. 
I propose we target an new networkx-2.0 release date for June.  

Let's reprioritize the open issues and pull requests for 2.0 to make this doable.

**Comment by MridulS** [comment]
Then I think we shouldn't have any release with the iterator version as it will unnecessarily change the API twice.

What about a 1.99 release with cherry picked commits in the coming days?

**Comment by hagberg** [comment]
I don't think that helps much.  There have been many changes since 1.11 and which few do you pick and why?

**Comment by joelmiller** [comment]
As a user, I'd push for delaying 2.0 until views is available.

In going from 1.x to 2.0, I expect that a fair amount of my existing code may no longer work.  Going from 2.0 to 2.1 I'm generally expecting existing code will continue to work, but new functionality may exist and some bugs may be fixed.

**Comment by jtorrents** [comment]
I also think that having views instead of iterators is worth waiting several weeks for releasing 2.0. We shouldn't break backwards compatibility twice in the base classes API in two consecutive releases.

**Comment by FRidh** [comment]
Bumping this issue. 

Somewhere in June or July a next Python 3.5 maintenance release will be made available, after which 3.5 goes into "security fixes only" mode. That means most distributions will also change their default (3.x) interpreter to 3.6. With networkx 1.11 we get 17 failures on 3.6. Now, I've seen commits fixing them so we could take those patches, however, networkx is used widely so I strongly recommend creating a release that works on 3.6 and passes its test suite.

**Comment by leycec** [comment]
> With networkx 1.11 we get 17 failures on 3.6.

As a downstream consumer of NetworkX, that's deeply concerning. Canada Day (*...yay!*) has come and gone, yet NetworkX 2.0 remains a dream. While I appreciate the difficulty of refactoring the entire codebase to leverage the new iterator API, a stable release passing Python 3.6 is arguably the first priority.

**Comment by jarrodmillman** [comment]
It appears 2.0 is near.  This doesn't seem relevant any more.
