### ISSUE TITLE
Spectral Clustering

### ISSUE THREAD

**Issue by zfrenchee** [networkx/networkx#2401]
Would this repo invite PRs with spectral clustering techniques? Is there a reason there aren't any yet?

**Comment by zfrenchee** [comment]
I imagine a lot of people use this: http://scikit-learn.org/stable/modules/generated/sklearn.cluster.SpectralClustering.html#sklearn.cluster.SpectralClustering

**Comment by hagberg** [comment]
Is there something not available with sklearn that you are thinking of?  Else I suggest we use the ML functionality in sklearn.

**Comment by zfrenchee** [comment]
Spectral clustering is not really ML, and since I think it's a sort of analysis people may want for graphs, I think it might make sense to include here as well @hagberg . I agree it would be at least partially duplication of what sklearn has implemented. Is sklearn a dependency for networkx? If so, this should be pretty easy. If not, would it be inappropriate to add it?

**Comment by hagberg** [comment]
We could make sklearn an optional dependency (if you want to use this feature).

**Comment by zfrenchee** [comment]
@hagberg how do you specify optional dependencies?

**Comment by zfrenchee** [comment]
@hagberg If I wanted to add this, where would I do it, and how would I specify the optional dependency?

**Comment by dschult** [comment]
You would specify the optional dependency by importing the package, but making sure everything loads OK if that import fails. Numpy and Scipy are optional dependencies in exactly this manner.  You could take a look at the ```networkx/linalg``` folder for example code. 

If I understand what you mean by spectral clustering it seems like the ```linalg``` folder would be a good place to add a module for spectral clustering. If you think that another place makes more sense, propose it. :)

Thanks!

**Comment by zfrenchee** [comment]
Thanks @dschult I've opened a provisional PR at #2682
