### ISSUE TITLE
import networkx is slow

### ISSUE THREAD

**Issue by rakhimov** [networkx/networkx#2405]
Importing networkx takes from 0.2 to 0.5s.

Example project: https://github.com/rakhimov/cppdep
Platform: Ubuntu 16.04, virtualenv with python 2 and 3.

**Comment by hagberg** [comment]
How long should it take?

**Comment by rakhimov** [comment]
As fast as Pythonically possible :)
Hopefully, to reach a point when it doesn't matter (<< 0.1s).

**Comment by hagberg** [comment]
Ok. Suggestions?

**Comment by rakhimov** [comment]
Googling hints that slow imports is a general Python problem.
One optimization option seems to be lazy imports.

**Comment by hagberg** [comment]
Sure, I bet importing, numpy, pandas, scipy, and matplotlib takes some time.  And all of those load when you import networkx.

**Comment by hagberg** [comment]
Closed due to inactivity.

**Comment by TomekTrzeciak** [comment]
I'm also interested in speeding up networkx load times to make it a better fit for use in command line utilities. Not all applications require the full functionality offered by networkx. In some cases only the core data structures are of interest. Would it be possible to split off the core of networkx into a separate module? This would allow to import the core classes and utils without pulling in all of numpy, scipy, etc.

**Comment by TomekTrzeciak** [comment]
@hagberg, is there any interest in this issue from core devs?

**Comment by ericmjl** [comment]
@TomekTrzeciak, I’m not an active core dev, but I’m nonetheless curious to hear what your thoughts are on what constitutes “core” and what constitutes “peripheral”. Would you be kind enough to elaborate?

**Comment by TomekTrzeciak** [comment]
> what modules would constitute the “core”

I'd say everything in `networkx.classes` classifies as core, `networkx.exception`, `networkx.utils`. 

> and what modules would constitute the “peripheral”.

Everything else: algorithms, conversion, drawing, ...

Perhaps it's not so much about core vs. non-core as being more frugal with imports within the package (more local imports on use, better namespace hygiene). At the moment almost every submodule does top-level `import networkx as nx`, which imports everything regardless of what's being actually needed/used.

**Comment by cao13jf** [comment]
Hi, everyone, 

I also suffered this problem these days. At first, I thought it was caused by the IDE (PyCharm). But I just found it takes much less time when I didn't import `networkx`.  FYI, the codes I tried are listed as follows, 

* Test with `networkx`
```
import time
start_time = time.time()
import os
import glob
import statistics
from tqdm import tqdm
import numpy as np
import torch
import networkx as nx

print("\n Runing time %s seconds" % (time.time() - start_time))
```
![image](https://user-images.githubusercontent.com/26733725/87221716-ba89d400-c3a0-11ea-914b-795a9e944dfc.png)

* Test without `networkx`
```
import time
start_time = time.time()
import os
import glob
import statistics
from tqdm import tqdm
import numpy as np
import torch
# import networkx as nx  <-- comment this

print("\n Runing time %s seconds" % (time.time() - start_time))
```
![image](https://user-images.githubusercontent.com/26733725/87221784-50bdfa00-c3a1-11ea-9f3f-c120eef4fd0a.png)

The `pytorch36` is the `conda` environment. `networkx` is a great work which helps me a lot in my research. Hope you guys can help me out if you have any good suggestion. Thanks.

**Comment by dschult** [comment]
Wow -- I have never had it take anywhere close to 2 minutes to import networkx... sometimes a few seconds, usually hardly any time at all.  Do you get much shorter times outside of this conda environment, or by just importing networkx without the others?  I can't think of what in the setup could cause this...  Does it improve the time if you switch the order of the timings? (without first then with)  Maybe there is something going on with memory caching or something...

**Comment by rossbar** [comment]
Can you run `python -X importtime -c 'import networkx'` from the environment that you're having problems in and share the results?
