### ISSUE TITLE
no self-loops in random (di)graphs?

### ISSUE THREAD

**Issue by pazz** [networkx/networkx#2408]
I'm using `networkx.fast_gnp_random_graph` to generate random directed graphs but I've just realized that this explicitly excludes self-loops, as suggested in the docstring:
https://github.com/networkx/networkx/blob/master/networkx/generators/random_graphs.py#L66

Out of interest, why is that?
For comparison, a [haskell implementation I've found](https://hackage.haskell.org/package/graph-generators-0.1.3.0/docs/Data-Graph-Generators-Random-ErdosRenyi.html) handles self-loops differently.

Would you be interested in a patch that optionally changes this behaviour?

**Comment by hagberg** [comment]
The mathematical definition excludes self loops.  I'm not familiar with the Haskell implementation you are using.  Perhaps the authors had a good reason to include self loops?

**Comment by pazz** [comment]
Right, I didn't read those papers before and wasn't aware that they only consider *simple* graphs.
As far as I can see, both the Erdos paper and the Batagelj paper cited in the docs don't bother to define (directed) graphs but implicitly only ever talk about simple ones.

In any case, maybe that's worth a notice box in the docs...
