### ISSUE TITLE
How can I guarantee that subgraphs from kernighan_lin algorithm are contiguous?

### ISSUE THREAD

**Issue by azlefty** [networkx/networkx#2409]
I am using the [Kernighan-Lin algorithm ](https://github.com/networkx/networkx/blob/6e20b952a957af820990f68d9237609198088816/networkx/algorithms/community/kernighan_lin.py)to bisect my graph.  Is there a way to specify that the subgraphs are all necessarily fully connected (contiguous), or is there some other algorithm that will bisect a graph subject to the constraint that the child subgraphs are fully connected?

For example, the script pasted at the bottom of this post generates a simple 4-node "star" graph with one central node (Node 1) connected to 3 other nodes.  By default, the KL algorithm splits it into 2 subgraphs, each with 2 nodes.  Since all edges connect to Node 1, the KL algorithm keeps nodes 1 and 4 connected, but breaks nodes 2 and 3 which end up as singletons, since the parent graph had no 2-3 edge.  This is shown in the "default" pictures.  I would prefer that the algorithm instead break off a single node in order to avoid a broken subgraph, as in the "contiguous" pictures.

Does anyone have any ideas on this?   Thanks for your help.

![stardefault](https://cloud.githubusercontent.com/assets/26798426/24516653/4ebe05ec-1530-11e7-9151-6894f8ea81ff.png)
![starcontiguous](https://cloud.githubusercontent.com/assets/26798426/24516658/564a8498-1530-11e7-9569-e2b097fe489e.png)

# 4-node Star Graph Example script
import networkx as nx
import matplotlib.pyplot as plt
import kernighan_lin

# build parent graph
G = nx.Graph()
G.add_edge(1,2)
G.add_edge(1,3)
G.add_edge(1,4)

# use Kernighan-Lin with default setting to split into children
C1,C2 = kernighan_lin.kernighan_lin_bisection(G)
D1 = nx.subgraph(G,C1)
D2 = nx.subgraph(G,C2)

# plot the parent and default child graphs
plt.figure(1)
plt.subplot(3,1,1)
nx.draw_networkx(G)
plt.title("Parent Graph")

plt.subplot(3,1,2)
nx.draw_networkx(D1)
plt.title("Child 1 Graph, default")

plt.subplot(3,1,3)
nx.draw_networkx(D2)
plt.title("Child 2 Graph, default")

# manually create the subgraph I want, which are contiguous
E1 = nx.subgraph(G,{1,3,4})
E2 = nx.subgraph(G,{2})

# plot the parent and manually created contiguous subgraphs
plt.figure(2)
plt.subplot(3,1,1)
nx.draw_networkx(G)
plt.title("Parent Graph")

plt.subplot(3,1,2)
nx.draw_networkx(E1)
plt.title("Child 1 Graph, contiguous")

plt.subplot(3,1,3)
nx.draw_networkx(E2)
plt.title("Child 2 Graph, contiguous")

**Comment by hagberg** [comment]
The problem is known to be difficult.  Here is an interesting CS stack exchange discussion that explains it well https://cstheory.stackexchange.com/questions/20767/partition-a-graph-into-2-connected-subgraphs

**Comment by azlefty** [comment]
Thanks for adding this to the future list.  It is still relevant to me.  If you happen to implement it in the near future, I would definitely use it.  Thanks very much for your maintenance of networkx; it is very useful and easy to use.
