### ISSUE TITLE
Parameter verification for LFR_benchmark_graph is incorrect

### ISSUE THREAD

**Issue by aryamccarthy** [networkx/networkx#2410]
The team which [developed the LFR benchmark](https://sites.google.com/site/santofortunato/inthepress2) uses the default values 2 and 1 for `tau1` and `tau2` respectively. This combination is forbidden in networkx, which demands values "strictly greater than 1".

**Comment by hagberg** [comment]
OK.  Needs a PR.

**Comment by dschult** [comment]
Looks like the underlying probability distribution functions impose the strict inequalities, so this may be more than a simple fix.  Should be bump it to v2.1?

**Comment by hagberg** [comment]
Yes, I see that.  Moved.

**Comment by hagberg** [comment]
I looked at the algorithm as coded.  The reason why you cant set `tau2=1` is that it is an exponent of a powerlaw as in x^-tau2 so you the value 1 doesn't make sense.  The paper does say it uses the value 1 in some experiments (\beta=1 in the paper) it must be using a cutoff or some non-powerlaw approximation.  I suggest we leave this as it stands unless someone can come by and re-open this with a detailed description of the model.
