### ISSUE TITLE
Node attributes as functions of other nodes

### ISSUE THREAD

**Issue by tbsexton** [networkx/networkx#2417]
Being able to set node attributed that update automatically based on, for example, parent nodes' attributes, doesn't seem to be implemented directly. I.e: 

```
G.add_node(0, att = 1)
G.add_node(1, att=G.node[0]['att']+1)
G.node
``` 
gives `{0: {'att': 1}, 1: {'att': 2}}`, but performing 
```
G.node[0]['att'] += 1
G.node
```
gives `{0: {'att': 2}, 1: {'att': 2}}`, meaning that the  attribute is not referencing the other node directly, but sets the value at instantiation. 

Are there any ways around this, other than having to make a separate class+variable for this attribute (making the attribute a class instance) or constantly updating the attributes with `set_node_attributes()` and a dict full of functions? 

I'm wanting to store variables as nodes and represent functional relationships with edges, programmatically  inserting node "parents" into some kind of node attribute function.

**Comment by jfinkels** [comment]
I think the attributes are designed to work well as static key/value pairs. They were not designed with this particular use case in mind.

As I think you suggest in the second-to-last paragraph, you might try setting the attribute on each node to be a distinct object that knows about the graph and the node. Another possibility is setting the attribute on each node to be a unique "global" object that knows about the graph. Finally, you might try creating your own (hashable) `Node` class that has the information you want.

**Comment by dschult** [comment]
It seems this could be done with a subclass of Graph which overwrites ```add_node``` and ```add_edge``` so that any change in the node attribute triggers a flow of corrections to all children nodes. I don't see this becoming a major part of NetworkX any time soon but it would sure make for a cool example!
