### ISSUE TITLE
Error message from eigenvector_centrality has typo.

### ISSUE THREAD

**Issue by joelmiller** [networkx/networkx#2419]
When `eigenvector_centrality` fails, the error message says: 

> power iteration failed to converge in %d iterations."%(i+1))

It doesn't actually say how many iterations occured.  It should be something more like

> power iteration failed to converge in 100 iterations.

The current code for it is:
`raise nx.NetworkXError("""eigenvector_centrality():
power iteration failed to converge in %d iterations."%(i+1))""")`

**Comment by dschult** [comment]
PR #2143 fixed this issue.
