### ISSUE TITLE
The number of minimal cuts

### ISSUE THREAD

**Issue by fangpin** [networkx/networkx#2421]
Is there a way to calculate the number of minimal-cut sets. thanks

**Comment by fangpin** [comment]
Is there a way to calculate the number of minimal s-t cut sets.

**Comment by jtorrents** [comment]
Hi @fangpin, until now you had to compute all `n(n-1)/2` minimum s-t cuts. But In PR #2425 I added the Gomory-Hu tree algorithm which computes a tree that represents all minimum s-t cuts of an undirected graph performing only `n-1` minimum cut computations. In the docstrings of that function I also explain how to compute the set of edges that separate s from t in the input graph.
