### ISSUE TITLE
GML Format

### ISSUE THREAD

**Issue by arudhir** [networkx/networkx#2426]
Apologies if this has been dealt with, but I couldn't find anything.

This is my first time using Networkx and playing with graphs at all, but from what I gather, the file format typically used here is a .gml

Per [http://stackoverflow.com/questions/32895291/unexpected-error-reading-gml-graph](this) StackOverflow answer, it seems as if there are two formats that .gml files present themselves in, only one of which networkx's read_gml() function will properly read.

Is there a utility function that can quickly reformat .gml files that have a newline after things like "node" and "graph" and/or is it possible to throw in a parameter like "old_format=True" so that it automatically reformats it in the background? There are still files that are in the "old" format (e.g., [http://networkdata.ics.uci.edu/data/adjnoun/](here) and it seems like it would be worth doing.

If there isn't, it seems like a simple task for regex—I'd be more than happy to try and whip something up real quick!

**Comment by hagberg** [comment]
There is (probably!) only one GML spec.  The latest version of networkx can read files with or without newlines.  That was handled in this fix #1962.
