### ISSUE TITLE
NetworkX not showing the data attributes of nodes

### ISSUE THREAD

**Issue by kohaugustine** [networkx/networkx#2428]
I am having a trouble as mentioned in the title to this post, and have also made a post up on [Stackoverflow](http://stackoverflow.com/questions/43474554/networkx-not-showing-the-data-attributes-of-nodes). Here is the post as it is:

I am having this weird behavior with NetworkX that is not following what would be expected based on the documentation on the Graph object.

Here is my code:

```
In [22]: G = nx.Graph()

In [23]: G.add_node("Roasted",attr_dict={"css_color":"#454463"})

In [24]: G["Roasted"]
Out[24]: {}

In [25]: G.nodes(data=True)
Out[25]: [('Roasted', {'css_color': '#454463'})]
```
At `In [23]` I added a node with an attribute dictionary. In `In [24]`, I was simply indexing the graph G like I would on a dictionary and expected it to return `{'css_color':'#454463'}`but I got back an empty dictionary instead. I only get to see that dictionary if I were to call for a printout of the list of nodes with their data displayed.

In the documentation, it showed that:

```
>>> G.add_node(1, time='5pm')
>>> G.add_nodes_from([3], time='2pm')
>>> G.node[1]
{'time': '5pm'}
```
you should be able to obtain the dictionary simply by indexing on the node name itself. Why did it not work for my case?

EDIT: In case the problem could have been that I used a string instead of an int for the node name, I tried this:

```
In [29]: G.add_node(1,attr_dict={"css_color":"#454463"})

In [30]: G[1]
Out[30]: {}
```
And the problem still persists! Could this be a bug???

**Comment by hagberg** [comment]
The `G[n]` syntax shows the internal edge dictionary.  Since you have no edges it is empty.
```python
In [1]: import networkx as nx

In [2]: G = nx.Graph()

In [3]: %paste
>>> G.add_node(1, time='5pm')
>>> G.add_nodes_from([3], time='2pm')
>>> G.node[1]

## -- End pasted text --
Out[3]: {'time': '5pm'}

In [4]: G.edge
Out[4]: {1: {}, 3: {}}

In [5]: G.edge[1]
Out[5]: {}

In [6]: G[1]
Out[6]: {}

In [7]: G.node[1]
Out[7]: {'time': '5pm'}
```

**Comment by kohaugustine** [comment]
Oh right! I see it now! Gosh silly me! Thank you very much for your clarification!
