### ISSUE TITLE
Arrows for edges

### ISSUE THREAD

**Issue by pwichmann** [networkx/networkx#2431]
I know 'arrows for edges' has been a feature that was requested a lot. And I've also read loads of reasons why it wasn't implemented.

At the same time I saw a few pull requests that seem to have implemented arrows for directional graphs.

Are arrows now implemented for edges?
I could not find this in the documentation.

Could anyone clarify and help me out?

EDIT: If it's not implemented, what is the best workaround? The current stubs are unacceptable for a visualisation.

**Comment by hagberg** [comment]
There is still no implementation for drawing arrows correctly with matplotlib and networkx.  As you have seen this is tricky to get right.  The best workaround is to export your results and draw them with a dedicated graph drawing package like Graphviz.

**Comment by AllanLRH** [comment]
Haven't tried it yet, but have a look at this repo: https://github.com/paulbrodersen/netgraph
