### ISSUE TITLE
_random_subset is very inefficient

### ISSUE THREAD

**Issue by ynovick** [networkx/networkx#2433]
In networkx.generators.random_graphs the function _random_subset is very inefficient. It leaves seq unaltered after choosing and adding x, so it can keep selecting the same element indefinitely before finding one that has not yet been added. In a Barabasi Albert graph where there is preferential attachment this can be especially costly because there will usually be nodes that will be selected with relatively high probability, so multiple repetitions is actually very likely. Considering that this loop is called for every element added to the graph, as n grows this can really slow down the performance. It is worth the extra overhead of making a copy of seq and removing every node after it has been selected to remove this repetition.

**Comment by hagberg** [comment]
Could you give an example where the performance is bad?  I could see this being an issue but it would be nice to have a real-world case to check the practical consequences of making a copy or swapping in a weighted choice without replacement algorithm.

**Comment by ynovick** [comment]
Hey, thanks for the quick attention to this. I don't have a "real-world"
example beyond what I myself was doing. I was testing the behavior of
Barabasi Albert graphs for different values of m and different values of n.
In order to normalize my tests I was working with sets of graphs for each
pair of m,n values instead of a single graph. So you can imagine, I was
creating many graphs for the mxn possibilities, so we're already at cubic
running time, and then when each one of these was taking a longer time than
necessary to actually add each node... But it's not like I bench-marked it
against an altered version or anything like that.

Ultimately, I decided I would save even more time by manually adding nodes
to existing graphs to go from, say n = 100 to n = 1000 instead of
requesting a brand new set of graphs with n = 1000 so I had to write my own
version anyway. But I still think this is an important optimization.

Please let me know if I can be of any further assistance.

Best,

YN

**Comment by jfinkels** [comment]
If I understand correctly, you are suggesting
```python
random.sample(set(seq), m)
```
as an alternate implementation, which is more costly in terms of memory usage?

**Comment by hagberg** [comment]
The nodes need to be chosen proportionally to degree.  That is being done by sampling uniform from the list `seq` with repeated nodes.

Alternatively networkx.utils.random_weighted sample(degree_dict,m) would probably work.  But it might be slower for all but pretty unusual cases.  There may be better algorithms.

**Comment by jfinkels** [comment]
So this?

```python
nodes, degree = zip(*G.degree())
random.choices(nodes, degree)
```
(On Python 3.6 only: https://docs.python.org/3/library/random.html#random.choices)

**Comment by ynovick** [comment]
I'm sorry, Python's not my first language so I can't give the syntax off
the top of my head, but the point is this:

If you choose 3 random elements from { 1, 2, 2, 3, 3, 3, 4, 4, 4, 4, 10,
10, 10, 10, 10, 10, 10, 10, 10, 10 } without repetition, it will be more
efficient to remove the elements as you select them than to simply rely on
the property of sets to prevent duplicates and keep repeating the loop
indefinitely until you've chosen 3 unique elements. Say you choose 10
first. If you keep repeating the loop as is, you'll never add 10 again
because of the properties of sets, but you can *select *it many times. If
you reduce the set to { 1, 2, 2, 3, 3, 3, 4, 4, 4, 4 }, yes you will spend
linear time removing each element, but the number of times you select an
element will be bounded by m. I think this is a worthwhile trade off,
especially as this function is used in preferential attachment graphs where
there could be some numbers with relatively high liklihood of being
selected. The extra memory is required because you don't want to modify the
original set so you will have to make one copy of it before the loop starts.

Thanks,

YN

**Comment by hagberg** [comment]
Almost,  but we want "without replacement". Interesting weighted random choice  is now in Python3.6.
The current solution is probably fastest in most cases.

**Comment by ynovick** [comment]
I don't want to overstate the point, in a Barabasi Albert graph you also
have a lot of nodes with small degree so the loop shouldn't run very long
before it finds a unique node, but it still adds time to the innermost loop
of multiple nested loops. And it may be used in some other case where you
might have some insanely lopsided distribution of values and it could in
fact take a very long time to run.

YN

**Comment by hagberg** [comment]
It's less typing to write some code and benchmark.
Here is code that I think implements the same BA algorithm with a weighted choice. 

https://gist.github.com/hagberg/9b81be32933551b324ed40ef6cb8c73f

Benchmarking left as an exercise.

**Comment by jfinkels** [comment]
Sorry, I was being a dummy :). I'm with you now, I promise. Weighted random sample without replacement.

**Comment by hagberg** [comment]
Needs review and benchmarking.

**Comment by dschult** [comment]
I've done a comparison with a bunch of possible choices. 
networkx.utils.random_weighted_sample
np.random.choice with weights and replace=False
removing the nodes from the list as proposed by OP.

All are much (5-10x) slower than the implemented method for n=100, m=3 and all scale worse than the implemented method as n and m increase.

I'm going to close this Issue
