### ISSUE TITLE
is there a way to "softly" set_node_attributes?

### ISSUE THREAD

**Issue by zfrenchee** [networkx/networkx#2434]
In my case, the node may or may not exist in my graph. I'd like to 

```
set_node_attributes(graph, attribute, dictionary_with_potential_superset_of_nodes_in_my_graph)
```

It would be nice if such a method existed. =)

**Comment by dschult** [comment]
for n,val in sset_dict.items():
    if n in G:
        G.node[n][attribute]=val
??

**Comment by zfrenchee** [comment]
Are you suggesting a way of working around this or citing the existing networkx code @dschult ?

**Comment by dschult** [comment]
That is a short bit of code (untested) that I think does what you are
requesting.
Does it do what you are thinking about?

**Comment by zfrenchee** [comment]
@dschult I solved this for myself before opening this issue using a dict comp. I only opened the issue because I think it makes more sense for networkx to do this by default than otherwise. Let me know if you would welcome a PR on this front, or if not, why you think the current behavior is more sensible.

**Comment by hagberg** [comment]
I think the current behavior reflects the Python principle that "errors should never pass silently".  In many cases I'd expect that passing a dictionary with keys (nodes) that aren't in the graph is an error by the user.  In this case it is pretty straightforward to filter the input dictionary to only contain nodes in the graph.

**Comment by zfrenchee** [comment]
@hagberg Would you send me some references about the python idiom that "errors should never pass silently"? I'm not sure I agree. Take, for example, [dictionary's get method](https://docs.python.org/3/library/stdtypes.html#dict.get):

> Return the value for key if key is in the dictionary, else default. If default is not given, it defaults to None, so that this method never raises a KeyError.

 I think that there seem to be good arguments for both ways. I think that's why python usually provides one method which throws an error and one method which doesn't, e.g. the distinction between `dict['key']` and `dict.get('key')`.

**Comment by hagberg** [comment]
I was thinking of PEP-20 https://www.python.org/dev/peps/pep-0020/.  That actually mentions both that "errors should never pass silently"  and "unless explicitly silenced" as in the dict example you give.   

I am not dogmatic about these kind of things and generally like to follow the common practice or whatever is "least surprising".   

If we decide we would like to include a method that sets attributes and ignores errors we might as you suggest call it something else - like `update_node_attributes`.

**Comment by zfrenchee** [comment]
Sounds reasonable.
