### ISSUE TITLE
typo error: test_maxflow_large_graph.py

### ISSUE THREAD

**Issue by leopeng1995** [networkx/networkx#2435]
In networkx/algorithms/flow/tests/test_maxflow_large_graph.py line 14, https://github.com/networkx/networkx/blob/master/networkx/algorithms/flow/tests/test_maxflow_large_graph.py#L14:
```
from networkx.algorithms.flow import boykov_kolmogorov
```

However, the actual filename is `boykovkolmogorov.py` in networkx/algorithms/flow. It seems to be omitted the underscore. Can the official team fix it?

**Comment by hagberg** [comment]
I think it is OK.  We are importing the function name not the module.  
We could import the module but then we'd need to refer to the function name too e.g
```python
In [1]: from networkx.algorithms.flow import boykovkolmogorov

In [2]: boykovkolmogorov.boykov_kolmogorov
```
