### ISSUE TITLE
Tutorial incorrectly states that shortest_path is not valid for MultiGraphs

### ISSUE THREAD

**Issue by adrianheron** [networkx/networkx#2437]
Referring to MultiGraphs and MultiDiGraphs the tutorial states that "...many algorithms are not well defined on such graphs. Shortest path is one example."
https://github.com/networkx/networkx/blob/v1.11/doc/source/tutorial/tutorial.rst#multigraphs

However, this is not mentioned in any of the documentation for the shortest path functions, and with a bit of digging it appears that in fact multigraphs are handled in the code: https://github.com/networkx/networkx/blob/8b9c2677461c385c2e6d86938c97d31703d629fb/networkx/algorithms/shortest_paths/weighted.py#L85

Seems like another example should be picked for the tutorial to avoid confusing me.

**Comment by hagberg** [comment]
That is confusing.  Let's just remove the "shortest path is one example" sentence.
