### ISSUE TITLE
Reverse breaks DiGraphs with default-hashed objects

### ISSUE THREAD

**Issue by zneak** [networkx/networkx#2442]
The NetworkX documentation [states that graph nodes can be any hashable object](https://networkx.github.io/documentation/networkx-1.10/reference/introduction.html#networkx-basics), and the glossary [defines hashable](https://networkx.github.io/documentation/networkx-1.10/reference/glossary.html#term-hashable) per the Python definition (that is, implements `__hash__` and a comparison method). It goes out of its way to state that instances of user-defined classes are hashable (and unique) by default:

> All of Python’s immutable built-in objects are hashable, while no mutable containers (such as lists or dictionaries) are. **Objects which are instances of user-defined classes are hashable by default; they all compare unequal, and their hash value is their id().**

That would seem to suggest that NetworkX supports graphs made of default-hashed objects (and nodes are considered the same if they're reference-equal). However, I found that the `reverse` method doesn't respect this property. Example:

```python
import networkx as nx

class Unique(object):
    pass

u = Unique()

g = nx.DiGraph()
g.add_edge("A", u)
assert "A" in g
assert u in g # passes
g.nodes() # ['A', <__main__.Unique object at 0x102e0fe10>]
g.edges() # [('A', <__main__.Unique object at 0x102e0fe10>)]

rev = g.reverse()
assert "A" in rev
assert u in rev # fails ಠ_ಠ
rev.nodes() # ['A', <__main__.Unique object at 0x102e0fd10>]
rev.edges() # [(<__main__.Unique object at 0x102e0fe10>, 'A')]
# Unique address is different in nodes() and edges(): `fd10` vs `fe10` ಠ_ಠ
```

What seems to happen is that `reverse` "deep copies" the graph (this is where it calls `Unique.__new__`, at least), and then seemingly doesn't keep track of objects that it has already copied.

**Comment by hagberg** [comment]
See #2282.

**Comment by jfinkels** [comment]
I think this is a slightly different issue, one with DiGraph.reverse. The test case here should be something like

```python
    def test_reverse_hashable(self):
        class Foo(object): pass
        x = Foo()
        y = Foo()
        G = nx.DiGraph()
        G.add_edge(x, y)
        self.assertCountEqual(G.nodes(), G.reverse().nodes())
        self.assertCountEqual(map(reversed, G.edges()), H.edges())
```
Is the contract for `DiGraph.reverse` supposed to be that the nodes are the exact same objects?

**Comment by zneak** [comment]
@hagberg #2282 looks different to me. The core issue was that distinct objects with the same hash that compared equal were referenced inconsistently between nodes and edges. The reporter said that this was probably not a bug, and I'd tend to agree with that, since the graph contract is that nodes are distinguished with their hash and equality property.

In this case, `reverse` appears to make *two copies of one single object* whose hash and equality are derived from its `id()`, destroying the equality relationship in the process. That result is inconsistent with the promise that NetworkX graphs can take objects that use the default hash and equality.

**Comment by hagberg** [comment]
I see what you are saying.  You are right - this is different than that earlier issue and a bug.
I think the fix should be in digraph.reverse()
```python
#            H.node=deepcopy(self.node)
            for n in self.node:
                H.node[n]=deepcopy(self.node[n])
```

Thanks for your careful look at this.

**Comment by dschult** [comment]
This just needs a PR with @hagberg fix and add @jfinkels test to the tests.

**Comment by zneak** [comment]
I appreciate that this is getting attention. Unfortunately, my company makes it absurdly hard to contribute source code to open-source projects. Pointing out issues is about as much as I can do, right now. 😕
