### ISSUE TITLE
`erdos_renyi_graph` is a possible misnomer

### ISSUE THREAD

**Issue by aryamccarthy** [networkx/networkx#2443]
Erdos and Renyi introduced the G(n, M) model. Gilbert [introduced](http://www.jstor.org/stable/2237458) the G(n, p) model in the same year. Erdos and Renyi analyzed the G(n, p) model shortly after. 

Is it correct to call the G(n, p) graph an `erdos_renyi_graph` (as one of its many synonyms)? Or would `gilbert_graph` be a better fit, and `erdos_renyi_graph` slowly move (by deprecation and reintroduction) to meaning the G(n, M) random graph?

**Comment by hagberg** [comment]
We primarily use `gnp_random_graph` and `gnm_random_graph` to refer to these graphs without ambiguity or potential attribution confusion.   As for the use of the name "Erdős–Rényi" to refer to gnp it is pretty common in the community literature.  As you point out it is probably another example of Stigler's law.   We do cite both 1959 papers in the documentation.
