### ISSUE TITLE
nx.draw() NOT working on python 3.6

### ISSUE THREAD

**Issue by necklace010** [networkx/networkx#2445]
I recently used upgraded my python from 3.5 to 3.6 and realized that the nx.draw() does NOT work now. Does anybody know how to fix this issue?

The error message is something like this:
MatplotlibDeprecationWarning: pyplot.hold is deprecated. Future behavior will be consistent with the long-time default: plot commands add elements without first clearing the Axes and/or Figure.

**Comment by MridulS** [comment]
@necklace010 It should work. 

> MatplotlibDeprecationWarning: pyplot.hold is deprecated. Future behavior will be consistent with the long-time default: plot commands add elements without first clearing the Axes and/or Figure.
This is just a warning it shouldn't impact the output.

Are you using a jupyter notebook?

**Comment by hagberg** [comment]
Fixed in #2397

**Comment by necklace010** [comment]
@MridulS Yes, I'm using jupyter. And when I run nx.draw() there's no graph output, just these warning message saying pyplot.hold is deprecated.

**Comment by MridulS** [comment]
make sure you execute 
```
%matplotlib inline
```
in one of the cells.
![screen shot 2017-05-04 at 11 18 12 pm](https://cloud.githubusercontent.com/assets/5363860/25717425/0cc81ca2-3120-11e7-9e6f-15e51061ed4a.png)

**Comment by necklace010** [comment]
@MridulS Yes, it worked! Thank you so much!

**Comment by MridulS** [comment]
@necklace010 happy to help :) Can you please close this issue.
