### ISSUE TITLE
str function for default graphs

### ISSUE THREAD

**Issue by ccoffrin** [networkx/networkx#2447]
The two print statements below produce the same output which is the empty string.  It would be nice if the later call provided some indication that the graph is non-empty.
```
import networkx as nx
G = nx.Graph()
print(G)
G.add_edges_from([(0,1),(1,2),(2,0),(2,3)])
print(G)
```

**Comment by dschult** [comment]
The print statement for a graph prints the name of the graph. That is G.name
It is hard to know ahead of time what the user would expect here. So we provided one alternative and rely on you printing ```G.nodes``` and ```G.edges``` if you want to know about those sets. Other options allow printing the node and edge data. Printing ```G.graph```, ```G.node``` and ```G.adj``` give you essentially the entire data structure (including the name as that is stored in ```G.graph```.
