### ISSUE TITLE
nx.power does not preserve zero-degree nodes

### ISSUE THREAD

**Issue by aravind-pg** [networkx/networkx#2454]
```shell
>>> G = nx.Graph()
>>> G.add_nodes_from([0, 1, 2])
>>> G.add_edge(0, 1)
>>> G2 = nx.power(G, 2)
>>> G.nodes()
[0, 1, 2]
>>> G2.nodes()
[0, 1]
```

Here `nx.power` fails to preserve the zero-degree node 2 in `G2`. This happens for all graphs in all such scenarios.

It is easy to see the problem: [the implementation](https://github.com/networkx/networkx/blob/master/networkx/algorithms/operators/product.py#L415-L434) adds nodes only as a byproduct of adding edges, and never actually initializes the result to contain all original nodes. A simple fix would be to change [this line](https://github.com/networkx/networkx/blob/master/networkx/algorithms/operators/product.py#L415) to `H = G.copy()` or `H = nx.Graph(); H.add_nodes_from(G.nodes())`. I can make a quick PR if this fix makes sense.

**Comment by dschult** [comment]
Yes, that looks right.  I think ```H.add_nodes_from(G)``` is a good way.
