### ISSUE TITLE
Time complexity in method documentation

### ISSUE THREAD

**Issue by robertour** [networkx/networkx#2457]
I am  working with a computer simulation and constantly trying to optimize parts of code that runs multiple times. It would be great if there is a note in the documentation indicating the time complexity of, at least, the basic methods. For example, I had previously assumed ***constant (O(1))*** times for the [nodes()](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.Graph.nodes.html) and [neigbors()](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.Graph.neighbors.html) in the Graph class, but it is actually linear (O(N))

I understand that it could be difficult for some complicated algorithms, and the big O is not always a good criteria, but I think it would be useful to point out the complexity of the basic methods (or an approximate). Ideally, point out to alternatives, e.g. it is possible to use self.g.adj[n1]  (O(1)) instead of neighbors() (https://github.com/networkx/networkx/issues/2438) (O(N))

**Comment by hagberg** [comment]
Yes, this should be documented somewhere since it does depend on the implementation choices in the code.  @dschult should it be https://github.com/networkx/networkx/wiki/Design-Specification or somewhere in the doc tree?

**Comment by dschult** [comment]
Big O of what? edges, nodes, neighbors, creating an iterator, creating a list from an iterator, iterating over an iterator...
There are so many choices of ways to report this that I don't even know where to start.

Perhaps a Wiki page (design spec? as suggested by @hagberg) could include a section on various choices for reporting things like neighbors and maybe even evidence for which performs best. But I don't think that is reporting complexity.... is it?

@robertour you mention that you previously thought nodes() and neighbors() were linear. What do you think they are now? I'm not sure I understand what you desire here...

**Comment by robertour** [comment]
@dschult, just the time complexity of calling networkx methods. If I call `nodes()`, it actually takes O(n), as the operation `list(self.nodes_iter(data=data))` in [the code](https://networkx.github.io/documentation/networkx-1.10/_modules/networkx/classes/graph.html#Graph.nodes) transform an iterator into a list. Well, now that I think about it, and check the code again. The documentation should mention the existance of `nodes_iter()`. 

Also, I was generally thinking that it is important to be aware of time complexity when you pick up certain algorithm, as sometimes the developer is flexible with the details. For example, the [followings algorithms](https://networkx.github.io/documentation/networkx-1.10/reference/generators.html#degree-sequence) "generate graphs with a given degree sequence or expected degree sequence". If the programmer doesn't care very much about the small differences but wants something efficient, then it would be convenient to select the faster algorithm (this has happened to me often as I have built computer simulations, and usually I just want a good fast approximation)

> you mention that you previously thought nodes() and neighbors() were linear. What do you think they are now? 

I indirectly answered this question, but, to be sure, `nodes()` is O(n), and I am not sure about `neighbors()` (`list(self.adj[n])`? I think this creates a new list traversing the elements... am I wrong). In any case, my suggestion is that this should be reported in the documentation, with the linear time alternatives. 

Note: I just realized that there might be a neighbors_iter(), and effectively there is, but this is exactly the reason why i think it should be documented - if I google "get neighbors of a node in networkx" I might end getting the `neighbors()` method and neglecting `neighbors_iter()`.

**Comment by dschult** [comment]
My understanding is that whenever there are multiple methods they have the same complexity. For example, ```G.neighbors(n)```, ```G.neighbors_iter(n)``` and ```G.adj[n]``` are all linear in the number of neighbors. But the constants are different. Of course, creating an iterator doesn't take much time at all -- it is using the iterator that takes time. Creating a list that holds the neighbors is the same complexity as creating an iterator over the neighbors.

so maybe complexity is not what we need...  perhaps a description of the relative speed of similar methods. That makes me realize that memory usage is important too. Again, complexity is probably not what we need, but a comparison of the memory footprint of the various methods.

Am I on the right track?

**Comment by robertour** [comment]
I wouldn't worry to much about the memory, as with graphs it should be more or less clear that it would something similar to Number of nodes (N) x Number of edges (M). For a flat graph (max. one edge between two nodes), the worst case would be O(N^2).

The problem is with the time complexity, in which case, the following sentence doesn't really make sense:

> `G.neighbors(n)`, `G.neighbors_iter(n)` and `G.adj[n]`  are all linear in the number of neighbors

I would say, 

- `neighbors(n)`  takes time O(n) and the return value takes memory O(n)
- `neighbors_iter(n)`  takes time O(1) and the return value takes also memory O(1), because internally the iterator only has and index, and a pointer to the vector of nodes (this is of course a matter of interpretation, but as a I said memory shouldn't be an issue).
- `G.adj[n]` takes time O(1) and the return value takes O(n) because it is the list of nodes itself (similar to `neighbors(n)`)

Consider the following cases:

A:
    for i in g.neighbors():
        pass

B:
    for i in neighbors_iter():
        pass

C:
    for i in g.adj[n]:
        pass

The case A would take twice as much as the others, as `neighbors()` creates a list, and the loop traverse the list. In case B and C, a new list is not created, so the elements are traverse only once.

This is why I think that the time complexity of algorithms should be reported, together with other alternatives of usage. 

PO. I just re-read my original post, and I realized I have been using `linear` instead of `constant`. O(1) is constant, O(n) is linear. I will correct my coments regarding this.

**Comment by dschult** [comment]
Hmmm...   "The case A would take twice as much as the others"  means that it is still O(n).  Twice O(n) is still O(n).  This is what I mean by the complexity is not the right measure. It's the constant in front of the "n" that you are asking about -- not the big-O.  The big-O is the same for all of them.

Also, I don't think ```G.neighbors_iter(n)``` is O(1) in this usage.  I believe "creating" the iterator is O(1). But you still have to iterate through it to make it useful and that takes O(n). I don't think you can process all the neighbors without having an algorithm that is at least O(number of neighbors).

**Comment by dschult** [comment]
I've started a part of the [Design Specification Wiki page](https://github.com/networkx/networkx/wiki/Design-Specification) to discuss relative performance of Graph methods. Is this the kind of thing you are looking for?

**Comment by robertour** [comment]
@dschult, in order to avoid looping twice through the nodes, the programmer should be aware which method should call (according to its complexity). Traversing the nodes twice could be already bad when thins are done multiple times, and things can easily get worse if the programmer is not aware of the complexity. For example:

    for i in nodes_iter() :
        x = ... # some calculation for x
        y = nodes()[x]   # call nodes to access x
        ....

 The big-O is NOT the same for all of them. When you say

>  I don't think G.neighbors_iter(n) is O(1) in this usage.

Yes, it is O(1)! It is used N times!, but using the method itself is O(1). `networkx` cannot be bother with what the programmers do after they call the method, but I think it should tell them how much calling the method cost.

> I don't think you can process all the neighbors without having an algorithm that is at least O(number of neighbors).

Of course you cannot, but some algorithms doesn't require you to iterate over all elements always (for example, searching).

The Wiki is a good idea, though imho this kind of recommendations should be in the documentation. "node() creates a new list of nodes every time you call it, consider using nodes_iter() or accessing the nodes directly with g.node[]"

**Comment by hagberg** [comment]
The discussion here covers this topic
https://github.com/networkx/networkx/wiki/Design-Specification

It may be worth having a separate "performance" wiki page if we want to make this easier to find.
