### ISSUE TITLE
NetworkX sprints at SciPy 2017?

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#2462]
SciPy 2017 is in Austin (10-16 July), we could have a networkx sprint and I guess it will be great way to finish up the work on 2.0 (if 2.0 isn't still released).

The last date to apply is 31st May.

Google form: https://docs.google.com/forms/d/e/1FAIpQLSeAIbbcw0xPZzR8k20MovLpBdhQ5CSSpWYjvyvqxiimfjJQ0A/viewform

@hagberg @dschult @jtorrents @chebee7i

**Comment by hagberg** [comment]
Hi @MridulS - good idea.  I won't be in Austin this year.  I'm willing to help frame up some sprint items.

**Comment by MridulS** [comment]
@hagberg Thanks for the help!

some ideas not explicitly related to the codebase, and a great way for newcomers and beginners to get familiar with networkx

- porting examples to jupyter notebooks (http://mybinder.org is pretty much always down http://mybinder.org/status), we can deploy binder on our own, related issues https://github.com/networkx/networkx/issues/1754 , repo for notebooks https://github.com/networkx/notebooks

- documentation https://github.com/networkx/networkx/pull/2054 , with 2.0 release close we need to make sure it's nicely documented and an updated and detailed new tutorial?

- making website pretty? https://github.com/networkx/networkx-website/issues/9 https://github.com/networkx/networkx/issues/1657 , my experiment with this issue https://nxtestweb.github.io

Also it would be great if we can have some of the core devs to attend the sprints @dschult @chebee7i @jtorrents . Is anyone planning to attend SciPy this year?

**Comment by chebee7i** [comment]
I will be there, but unsure if I will be able there for the full sprint.

**Comment by MridulS** [comment]
@dschult @chebee7i @hagberg We need to fill this up https://docs.google.com/forms/d/e/1FAIpQLSeAIbbcw0xPZzR8k20MovLpBdhQ5CSSpWYjvyvqxiimfjJQ0A/viewform to formally register as a sprint. @chebee7i Are you willing to be the sprint lead?

I won't be able to attend but definitely help out remotely ( didn't get finaid :/)

**Comment by MridulS** [comment]
Regarding networks notebooks:
https://beta.mybinder.org is the new place for mybinder. So I guess we don't need our own deployment to get it to work. The UI doesn't work right now but you can start the build for a repo using https://beta.mybinder.org/v2/gh/networkx/notebooks/master , the build is failing right now because of pygraphviz. Need to look into that.

https://github.com/jupyterhub/binderhub

**Comment by dschult** [comment]
Let's shift any discussion from SciPy sprints to 
Notebooks: #1754    and
Website landing page:  #1657
