### ISSUE TITLE
to_pandas_dataframe is not the inverse of from_pandas_dataframe

### ISSUE THREAD

**Issue by rundong08** [networkx/networkx#2464]
The function `from_pandas_dataframe` assumes that the data frame has edge-list like structures, but `to_pandas_dataframe` generates an adjacency matrix. 

Personally, I think the edge-list like structures are more useful because:
(1) Otherwise these two functions are just (wrapped) duplications of `numpy_matrix` related functions
(2) The edge-list like data frames are convenient for other interfaces such as `py2cytoscape`. 

Some related commits:
[52eb3d3](https://github.com/networkx/networkx/commit/52eb3d38ff78e4002a424ae5e8976998afdaf1a2): `from_pandas_dataframe` and `to_pandas_dataframe` were added. At that time both functions were about adjacency matrix.  
[f0c22dd](https://github.com/networkx/networkx/commit/f0c22dd3305ff236860c651d8a08fbabcb8b0a77): `from_pandas_dataframe` was changed to current behavior, but it seems that `to_pandas_dataframe` was forgotten to be changed accordingly.

**Comment by dschult** [comment]
As far as I can tell from the discussions on github this change may not have been intentional. 

It looks like we might need functions for pandas adjacency matrix as well as pandas edge list. Can anyone involved in the previous commits comment on the best way to fix this?

**Comment by jarrodmillman** [comment]
I don't use Pandas, but it also seems to me that there could be a use for both adjacency matrices and edge lists.  So maybe we should provide either (1) four functions or (2) modify the to/from functions to have a flag indicating whether we are using an adjacency matrix or an edge list.  I haven't looked at the code yet, but I am happy to provide an implementation of either solution.   @dschult , @hagberg 

If we go with 4 functions, maybe we should delete the two existing functions and provide something like:

```
def from_pandas_edgelist(df, source='source', target='target', edge_attr=None, create_using=None):

def to_pandas_edgelist(G, nodelist=None, dtype=None, order=None,
                                             multigraph_weight=sum, weight='weight', nonedge=0.0):

def from_pandas_adjacency(df, create_using=None, mask_zero=True, mask_nan=True):

def to_pandas_adjacency(G, nodelist=None, dtype=None, order=None,
                                                multigraph_weight=sum, weight='weight', nonedge=0.0):
```

Then in `to_networkx_graph`, we could do something like:

```
if isinstance(data, pd.DataFrame):
    if data.shape[0] == data.shape[1]:
        <call from_pandas_adjacency(data)
    else
         <call  from_pandas_edgelist(data, edge_attr=True, create_using=create_using)
```

Thoughts?  Should I try implementing something for comment?

**Comment by hagberg** [comment]
I like the idea of explicit separate functions.

**Comment by dschult** [comment]
Yes, have a go at it!  :)  At the moment we have one written for adjacency and one written for edgelist. You can find the other edgelist in the history, but it might be just as well to rewrite it.   Have fun!
