### ISSUE TITLE
All pairs shortest path lengths using too much memory

### ISSUE THREAD

**Issue by sapostolou** [networkx/networkx#2476]
Is it normal that I need more than 24 GBs or RAM to calculate the all pairs shortest path lengths for a graph with 62078 vertices and 216104 edges?

I assume that something must be wrong somewhere but I can't find out where. Could someone share some more insight on the implementation and the memory footprint?

Thanks in advance

**Comment by dschult** [comment]
It completely depends on what your nodes and edges are. By that I mean what objects represent your nodes and what type of data you use for edges.  Typical use of integers for nodes and without any edge data uses less memory than you report. In any case, it should not grow a huge amount when calling all pairs shortest path lengths.

**Comment by hagberg** [comment]
If you are using the latest version of networkx (probably the development version here at github) you can iterate over the single source shortest path  lengths and not have to build all of the path lengths in memory.  e.g.
```python
In [1]: import networkx as nx

In [2]: g = nx.path_graph(4)

In [3]: for p in nx.all_pairs_shortest_path_length(g):
   ...:     print(p)
   ...:     
(0, {0: 0, 1: 1, 2: 2, 3: 3})
(1, {0: 1, 1: 0, 2: 1, 3: 2})
(2, {0: 2, 1: 1, 2: 0, 3: 1})
(3, {0: 3, 1: 2, 2: 1, 3: 0})```

**Comment by sapostolou** [comment]
@dschult I am in fact using integers for IDs and use not data on the edges.

@hagberg So it returns a generator now? Maybe if I iterate over all vertices and create an overall dictionary it will save some memory? I doubt it will succeed if the problem is in the way the data are stored. I will try it later this evening. Thank you.

**Comment by hagberg** [comment]
Yes, it is a generator.  So if you don't need to store all of the path lengths this is a more memory efficient way to compute them.  If you do need to store them there might be 2 x 10^9 values in your case (assuming a connected graph).

**Comment by sapostolou** [comment]
@hagberg Of course. I don't know why I never bothered to actually calculate the number of integers I will have to store to keep it all in memory. Maybe it would be nice to set the max memory size of the values stored in the dictionary if I could (based on the diameter maybe?).

Thanks anyway everybody.
