### ISSUE TITLE
Is relabeling safe for partially overlapping names?

### ISSUE THREAD

**Issue by JohannesBuchner** [networkx/networkx#2477]
If I have nodes (1-2-3-4-5) and I rename 5->6, 4->5, 3->4, networkx should not get confused and rename 3 to 4 first, followed by another rename to 5.

If I read the first if-clause of _relabel_inplace correctly, then it is safe to rename nodes when some of the old and new names overlap. So I suspect networkx is doing this correctly, but it would be nice if the doc would confirm this explicitly, especially for copy=False.

**Comment by hagberg** [comment]
Your mapping will work but there are cases where you can't do it in place.  
e.g.
```python
import networkx as nx                                                           
G = nx.Graph()                                                                  
nx.add_path(G,[1,2,3,4,5])                                                      
mapping= {3:4,4:3}                                                              
G = nx.relabel_nodes(G, mapping, copy=False)
```

**Comment by dschult** [comment]
The docs say:  

    The keyword setting copy=False modifies the graph in place. This is not always possible if the 
    mapping is circular. In that case use copy=True.

These seem accurate and maybe address your concern? Is there better wording?

**Comment by JohannesBuchner** [comment]
This sentence only makes sense if one understands that the function generates a directional mapping graph and follows it. Even then, the function could conceivably do it incorrectly -- 5->6, 4->5, 3->4 is non-circular, but where the relabeling starts is not specified (it could do 4->5 first). Even for copy=True, the description is ambiguous (at least to me).

Maybe something like:
relabel_nodes builds from mapping a directed graph which specifies the order or remappings. This resolves naming collisions, such as a->b, b->c, such that "b" gets renamed to "c" before "a" becomes "b". In cases of circular mappings (e.g. a->b, b->a), modifying the graph is not possible in-place. In that case, use copy=True.

**Comment by dschult** [comment]
Thanks very much...
