### ISSUE TITLE
is networkx available for getting the next `shortest_path`?? (the second or n-th shortest Path)

### ISSUE THREAD

**Issue by DanielTimLee** [networkx/networkx#2478]
is networkx available for getting the next `shortest_path`?? (the second or n-th shortest Path)

**Comment by dschult** [comment]
Take a look at: [shortest_simple_paths](http://networkx.readthedocs.io/en/stable/reference/generated/networkx.algorithms.simple_paths.shortest_simple_paths.html)
Also #1447 and connections from there for discussion.
