### ISSUE TITLE
Add {to, from}_numpy_array functions

### ISSUE THREAD

**Issue by harryscholes** [networkx/networkx#2479]
Should we add a `to_numpy_array` function to generate an `np.array` from a graph and a `from_numpy_array` function for the reverse? These would be similar to the existing `{to, from}_numpy_matrix` functions.

**Motivation:**
* Times have changed since #895.
* `np.matrix` is as good as deprecated, especially after the introduction of the `@` operator for matrix multiplication of arrays in Python 3.5.
* `np.matrix` doesn't always produce the same results as `np.array` and can lead to confusion.

**Comment by dschult** [comment]
NetworkX uses matrix and sparse_matrix for consistency and because the SciPy sparse matrix collection has  many good tools associated with it. The sparse matrix mimics the matrix structure though I have read that there are a few differences. Also, to change from a matrix object to an array is fast and easy with ```numpy.asarray(M)```, ```M.A```, ```M.getA()``` and perhaps other methods.

I would be Ok with adding a conversion function ```to_numpy_array``` so long as it is easy to maintain.

**Comment by harryscholes** [comment]
The `to_numpy_array` could be implemented using the existing `to_numpy_matrix` function, so that it remains easy to maintain:
```
def to_numpy_array(G, nodelist=None, dtype=None, order=None, multigraph_weight=sum, weight='weight', nonedge=0.0):
    M = to_numpy_matrix(G, nodelist=nodelist, dtype=dtype, order=order, multigraph_weight=multigraph_weight, weight=weight, nonedge=nonedge)
    return M.A
```
`from_numpy_array` would require a bit more work, but could be based on `from_numpy_matrix` implementation.

I'm very willing to do this and create a PR if you're happy to give me the go ahead.

**Comment by dschult** [comment]
Yes - if you could create PR I'll work to get it in. Thanks

**Comment by AllanLRH** [comment]
Should this be part of the Networkx 2 milestone?
As @harryscholes mentions, Python 3-5+ have the @-operator, and the Numpy Matrix class is all but deprecated... Networkx 2 is a release for the future, so it should be convenient to use the more modern array-class instead of the Matrix.

**Comment by harryscholes** [comment]
@AllanLRH sounds like a good idea to me. I'll get working on it soon
