### ISSUE TITLE
_relabel_copy and OrderedGraph

### ISSUE THREAD

**Issue by mys007** [networkx/networkx#2482]
The current behavior of `_relabel_copy()` is somewhat unintuitive for OrderedGraphs, where the nodes in the newly created graph are ordered according to the edge iterator of the original graph, not the node iterator. I think this would be fixed by placing `H.add_nodes_from(mapping.get(n, n) for n in G)` at the beginning of the function.

**Comment by dschult** [comment]
I agree. This would bring that function into line with other graph copy/subgraph code.
I suggest the order should be:

    1. update the graph attribute dict.
    2. add nodes and update node attributes.
    3. add edges and edge attributes.

**Comment by hagberg** [comment]
+1
