### ISSUE TITLE
Status of `graphviz` -- abandoned?

### ISSUE THREAD

**Issue by jhpratt** [networkx/networkx#2486]
How is this supposed to work? The documentation is out of date, as the provided examples simply do not work, and don't match the examples (which also don't work) in previous issues.

After thorough searching, this has been around for well over a year (see #1997, #2023, #2128, #2176). Nothing appears to have been worked on regarding this since the first of the issues listed.

I am trying to show a large graph, and any other layout for my purpose needlessly complicates the visual. I fail to understand why nothing has been worked on, but I'm certainly not the only one that is waiting for a solution.

**Comment by ericmjl** [comment]
@jhpratt - just out of curiosity, is the large graph that you're trying to show amenable to `nxviz`? (It's a package I'm creating for visualizing large graphs, built on top of `matplotlib`, and implements Circos plots with Hive Plots in the works right now.) 

Unfortunately I don't have an answer for you re: `graphviz`.

**Comment by jhpratt** [comment]
@ericmjl I'm certainly open to using other rendering packages, so long as they're relatively stable. Just from checking out the single example in README, it looks similar to `networkx`, so I'm up for trying it.

**Comment by ericmjl** [comment]
@jhpratt the API is designed to be declarative (and hence stable) going forth; it's also been used in a Network Analysis course I've taught on DataCamp, which means I've got to keep it stable for them too :smile:.

Please give it a shot and let me know what you think - to the best of my knowledge, the only thing you'll have to be worried about is plots taking some time to render, so I'd start with a subsample of edges in your graph and work up from there. Happy to discuss any issues on `nxviz`'s GH repo.

**Comment by jhpratt** [comment]
@ericmjl Will do! My graph isn't terribly large yet, but I'm expecting multiple thousand nodes as it nears completion.

**Comment by dschult** [comment]
All the issues you refer to have been closed.
Can you state what your issue is and what symptoms/difficulties you are having?

And BTW, declaring that no work has been done for over a year when it has been and then implying that your trouble ought to be solved by someone else -- indeed that someone else should make your problem a priority is really against the whole spirit of open source software. 

Let's start again -- open an issue.  Explain what you are trying to do and describe what problem you are having. Provide a simple example of code that does not work.  Oh yes, and read the issues that you refer to. Try to understand what the issue is in the code and how we have worked to fix it.  I would start with #2023

**Comment by jhpratt** [comment]
I'll be right to the point here. The issue is that this part of the package does not work, as is described in the other issues (that are all closed despite not being fixed).

I said it _appears_ no work has been done for over a year, as that's when the last issue was closed, yet the examples provided in the documentation and the linked issues still are non-functional. I **never** implied that this should be a priority, rather I was simply asking the status of a fix, if one was in the works, as I'm no doubt not the only one that would use it.

Having such a breaking change introduced into software in a minor version is contrary to what versioning is for. When I release a package, I support it fully and follow semver for versioning, which would have prevented such a breaking change being introduced in a minor version.

I will be using Eric's package, and I suggest you integrate this with networkx, as your current version does not work, even using the examples provided verbatim in the documentation.

I'm not one to debate, but a direct attack on myself is unacceptable. I clearly stated the issue and referenced code that does not work, yet you fully ignore that and accuse me of being contrary to the spirit of OSS.

**Comment by dschult** [comment]
For anyone who finds this later:

I'm not sure which examples and documentation are not working. The issues referred to above have been resolved AFAIK and I can run the programs without error. 
If you use pygraphviz:

    pos = nx.drawing.nx_agraph.graphviz_layout(G)
    nx.draw(G, pos=pos)

If you use pydotplus:

    pos = nx.drawing.nx_pydot.graphviz_layout(G)
    nx.draw(G, pos=pos)

More details can be found on the [layout docs](http://networkx.readthedocs.io/en/stable/reference/drawing.html)
