### ISSUE TITLE
Tutorial PDF is not found

### ISSUE THREAD

**Issue by fedorov** [networkx/networkx#2491]
This URL appears to be invalid: http://networkx.github.io/documentation/latest/_downloads/networkx_tutorial.pdf

Referenced from the documentation:
https://networkx.readthedocs.io/en/stable/download.html

**Comment by dschult** [comment]
See #2344   My quick take is that this is fixed in the latest version but not in the stable v1.11 release.

**Comment by Michael-E-Rose** [comment]
Yes, it's a duplicate to #2281.

**Comment by fedorov** [comment]
#2281 was closed 6 month ago. The broken link I reported is broken today.

**Comment by Michael-E-Rose** [comment]
That's true, but the commit that fixes the broken link is _not yet_ live. That's why you see the same error as the other OP six months ago.

**Comment by fedorov** [comment]
Feel free t close this issue if you want to completely confuse me! :-D

**Comment by dschult** [comment]
@Michael-E-Rose can you be more specific about the fixes?  Is the link broken in the latest code (master from github)? Is it broken in the latest stable release (v1.11)?  

My understanding is that it is fixed in the master branch of github but not in the v1.11 release.

**Comment by Michael-E-Rose** [comment]
> My understanding is that it is fixed in the master branch of github but not in the v1.11 release.

That is absolutely the case. In the above referenced PR, I changed `download.rst` such [that](https://github.com/networkx/networkx/pull/2344/files#diff-ff8e8d6c0c2c8db1b04b9e4e2563bd06) there is no section called PDF any more.  Eiter it is not live yet, or the docs have not been updated.

**Comment by dschult** [comment]
Hmmm... This is mixed up.  
The readthedocs sites are consistent, but because the stable readthedocs pages point to the github.networkx.io pages we don't match up and it just doesn't work.

Got to find a simpler doc system to keep this working well.

**Comment by Michael-E-Rose** [comment]
> Got to find a simpler doc system to keep this working well.

Maybe no github.io docs at all? Or we redirect rtfd.org to point to the build.

**Comment by hagberg** [comment]
I might be not following the details here - but the goal was to put the reference documentation at readthedocs and have the landing page be at networkx.github.io.   More discussion at #2054

**Comment by fedorov** [comment]
> but the goal was to put the reference documentation at readthedocs

I am **definitely** not following all the details here, but as summarized in the initial report, the documentation page is indeed on readthedocs, and the broken link points to a content on networkx.github.io. I have no clue whether this is how it is supposed to be, all I know is that the link is broken.

**Comment by hagberg** [comment]
I guess it is just the links on that page that that are wrong.  The PDF is here https://media.readthedocs.org/pdf/networkx/stable/networkx.pdf

**Comment by dschult** [comment]
I attempted to fix this on:
- the v1.11 stable readthedocs page (removing the inactive links from the front page and correcting the links on the Downloads page) fb8a8ca6ecd9c99ba3f5e3c2654fdf6df5b4e7c2  and ceadb923fe60c648c47bf4d0ede595822bdbfec0
- the master latest readthedocs page (changing the download page links from the stable version to the latest version)  54227d56880e389e8aea03f44d936c5d9a2dfc72

It appears to be working now -- you might have to reload the page.  Note: no links to pdfs from the front page any more -- links work from the Download page.

Thanks for persisting with this until we fixed it and feel free to reopen if needed...
