### ISSUE TITLE
the one which installed by pip can't run but that installed by building this repo is ok

### ISSUE THREAD

**Issue by kungcn** [networkx/networkx#2494]
I am learning how to read gml by networkx, so I write such code.

```
import networkx as nx
import matplotlib.pyplot as plt

if __name__ == '__main__':
    graph = "./karate.gml" # Karate Club dataset
    Graph = nx.read_gml(graph, label='id')
    nx.draw(Graph)
    plt.show()
```

Terminal shows such error:

However, my classmate installed networkx by downloading code to build and code works normally. After I installed it by his way, it succeeded.

I think there is sth. wrong in pip release or it isn't the latest one. It will be better if you can update the release in pip.
![2017-07-01 00-57-17](https://user-images.githubusercontent.com/12772780/27746359-7ca48b36-5df9-11e7-92f9-0fe532a9c186.png)

**Comment by aryamccarthy** [comment]
Have you followed the discussion at #1783?
