### ISSUE TITLE
bug when creating a plot with a legend if edges have arrowheads

### ISSUE THREAD

**Issue by joelmiller** [networkx/networkx#2503]
Currently, it appears to me that when you plot an edge in a directed graph with an arrowhead and assign a label, the legend in the plot will show both the edge and the arrowhead with whatever label.  

Looking at the source code, it appears that the error is in the command `arrow_collection.set_label(label)`.  I don't think this serves any purpose other than to ensure that the arrowhead is labelled but the edge itself is already labelled from the earlier command `edge_collection.set_label(label)`

See https://stackoverflow.com/q/44966874/2966723 for an example of this.

**Comment by viraj96** [comment]
Hi, I am willing to submit a PR if this is still open and no one is assigned to it. All there needs to be changed is removing `arrow_collection.set_label(label)`?

**Comment by dschult** [comment]
Go for it!   Yes -- I think that's it -- try it to make sure of course...

**Comment by dschult** [comment]
Fixed in #2503
