### ISSUE TITLE
missing commits

### ISSUE THREAD

**Issue by jarrodmillman** [networkx/networkx#2531]
@hagberg , @dschult  I just noticed that there is no ``doc/release/api_1.11.rst``, but there is one here:
  https://github.com/networkx/networkx/tree/v1.11
in ``doc/source/reference/api_1.11.rst``.  It appears this file was never committed on the master branch.

The v1.11 branch is " 59 commits ahead, 1066 commits behind master. "  So it looks like there may be a number of missing commits on master.  For example, this is also missing:
  https://github.com/networkx/networkx/commit/5665c71f3a9aec0325078de2de43537aee03386d
As this shows:
```
$ git lg networkx/drawing/tests/test_agraph.py
* d8ada85 - Make graph attributes work both to/from with agraph  (#2507) (11 days ago) [Dan Schult]
* 7bfb768 - Improve drawing test scripts (typos, newlines, methods) (1 year, 5 months ago) [Michael-E-Rose]
* f5031dd - Adjust imports in drawing layouts with graphviz (1 year, 6 months ago) [Dan Schult]
* 9922ec7 - doc, formatting, and whitespace cleanup (5 years ago) [Aric Hagberg]
* 47565b1 - Handle name in translation between pygraphviz (AGraph) and networkx. Fixes #734 (5 years ago) [Aric Hagberg]
* 3665bc1 - Update tests (6 years ago) [Aric Hagberg]
* d41d15f - More imports cleanup and exceptions fixed. (6 years ago) [Loïc Séguin-C.]
* baceff1 - Added tests for multigraph conversion to/from agraph. Changed from_agraph() so that the tests pass. (8 years ago) [dschult]
* ca6df32 - Convert drawing tests to functional tests and use SkipTest if optional packages are not available. (8 years ago) [aric]

```

I suspect that this was unintentional and that I should go through the missing commits and either cherry-pick the appropriate ones or make a new commit when cherry-picking doesn't work.  I just wanted to check whether I am correct before I go through the effort.  I will make a PR so you can review the commits I grab before merging to master.

**Comment by hagberg** [comment]
Looks like some bad hygiene there.   Those should be folded in.

**Comment by jarrodmillman** [comment]
OK, I will submit a PR today or tomorrow.
