### ISSUE TITLE
deleting old branches

### ISSUE THREAD

**Issue by jarrodmillman** [networkx/networkx#2533]
I plan to clean up some old branches.  The following branches have nothing not already in ``master``:
- [attrgraph](/networkx/networkx/tree/attrgraph)
- [beam-log-2](/networkx/networkx/tree/beam-log-2)
- [digraph-edge-subgraph](/networkx/networkx/tree/digraph-edge-subgraph)
- [doc-isom-orderable](/networkx/networkx/tree/doc-isom-orderable)
- [remove-beam-notes](/networkx/networkx/tree/remove-beam-notes)

I will delete them.  I will also delete:
- [revert-1806-patch-numpy-compatible](/networkx/networkx/tree/revert-1806-patch-numpy-compatible)
It has one commit not in ``master``:   ec5e42e

**Comment by hagberg** [comment]
Yep.  Delete.
