### ISSUE TITLE
EdgeDataView output for more than one node arguments in G.edges()

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#2541]
@dschult Is this expected behaviour for `` G.edges(0, 1, 'foo')`` and `` G.edges(0, 1)`` ?
``` python
In [5]: G.edges()
Out[5]: EdgeView([(0, 1), (0, 2), (0, 3), (0, 4), (1, 2), (1, 3), (1, 4), (2, 3), (2, 4), (3, 4)])

In [6]: G.edges(0)
Out[6]: EdgeDataView([(0, 1), (0, 2), (0, 3), (0, 4)])

In [7]: G.edges(0, 1)
Out[7]: EdgeDataView([(0, 1, None), (0, 2, None), (0, 3, None), (0, 4, None)])

In [8]: G.edges(0, 1, 'foo')
Out[8]: EdgeDataView([(0, 1, 'foo'), (0, 2, 'foo'), (0, 3, 'foo'), (0, 4, 'foo')])
```

**Comment by dschult** [comment]
Hmmm...   What would you expect from G.edges(0, 1)?   The nbunch is `0`.  But the data requested is named `1`.  This is the same for v1.11 and v2.0.  The calling form is ```G.edges(nbunch, data, default)```

Perhaps you want ```G.edges([0, 1])```?

Also, I haven't written the docs for the views, but it goes something like this:

    G.edges      # is what you will use most of the time.  Note: No parentheses!  This is an object.
    G.edges()    # backward compatible and returns exactly the same as G.edges without ()
    G.edges(data='weight')    # get edges as tuple with (u, v, weight)
    G.edges(data=True)    # get edges as tuple with full data dict  (u, v, datadict)
    G.edges(data=False)    # get edges as tuple with only nodes (same as G.edges)

These all act like sets of edge tuples.

For multigraph, we have to worry about the ```keys```.  So

    MG.edges      # set of (u, v, key)
    MG.edges()    # backward compatible so set of (u, v)
    MG.edges(data='weight')    # get edges as tuple with (u, v, weight)
    MG.edges(data=True)    # get edges as tuple with full data dict  (u, v, datadict)
    MG.edges(data=False)    # get edges as tuple with only nodes (same as G.edges())
    MG.edges(data='weight', keys=True)    # get edges as tuple with (u, v, key, weight)
    MG.edges(data=True, keys=True)    # get edges as tuple with full data dict  (u, v, key, datadict)
    MG.edges(data=False, keys=True)    # get edges as tuple (u, v, key) (same as G.edges)


The EdgeView and EdgeViewData objects are set-like, but EdgeView also itself allows lookup of the edge data.  So it's a set with dict-like lookup.

    G.edges[u, v]    # provides the edge data dict  (what G.edge[u][v] == G.adj[u][v] used to provide)
    MG.edges[u, v, k]    # multigraph edge lookup requires a 3-tuple at the moment

Neighbor lookup should be done with the ```G.adj/G.succ/G.pred``` objects instead of the functions ```G.neighbors```, and friends.   I wonder if ```G.adj``` should be renamed ```G.nbrs```...

Hope this helps.

**Comment by MridulS** [comment]
Thanks for the explanation :)

For some reason I never tried doing `G.edges(0, 1)` with v1.11, I was just playing around with views and found this. 😆

**Comment by dschult** [comment]
Another way to summarize the ```G.edges``` migration path is that it is backward compatible for most uses.  Iteration should work the same as before. ```list(G.edges())``` should still be the same. ```(u, v) in G.edges()``` should still be the same. ```G.edges(data='weight')``` should iterate and check contains the same as it did before.

The features are almost all backward compatible. But we get extra features if we leave off the parentheses. We get data lookup ````G.edges[u,v]['weight']```. We get set operations ```G.edges & H.edges```.

Python ```dict``` has methods ```.keys()```, ```.values()``` and ```.items()```.   To those options we add ```G.edges.data()```  This is like ```.items()``` but can return one attribute from the datadict if you use it as ```G.edges.data('weight')```.

There is a tricky bit that ```G.edges(data=True)``` is still set-like, AND it doesn't allow lookup.  It is actually ```G.edges.data(True)```.  And just like dicts don't allow lookup on ```keys/values/items```, the ```EdgeView``` family doesn't allow lookup on keys/values/items/data views. So the ```EdgeDataView``` family is set-like while the ```EdgeView``` family is set-like and dict-like.
