### ISSUE TITLE
Assign closed issues to 2.0 milestone

### ISSUE THREAD

**Issue by jarrodmillman** [networkx/networkx#2550]
I plan to assign closed issues currently labelled as part of the ``2.1`` and ``future`` milestones to ``2.0``:
https://github.com/networkx/networkx/milestones

As I am going to use the GitHub API for autogenerating the contributors file for the release notes (PR #2542) , I want to make sure all PRs closed on master prior to the 2.0 tag are correctly labelled.

If I am overlooking something, please let me know.

**Comment by dschult** [comment]
This is a good idea.  Thanks!
