### ISSUE TITLE
contracted_nodes can fail if original graph has self-loops

### ISSUE THREAD

**Issue by joelmiller** [networkx/networkx#2575]
See https://stackoverflow.com/q/45476424/2966723 for more details.

    G = nx.Graph([(1,2), (2,2)]) # Two nodes
    H = nx.contracted_nodes(G, 1, 2, self_loops=False)
    H.edges() 

Fails to give expected output of a single node.

**Comment by dschult** [comment]
It also looks like it doesn't work for multigraphs. The code also uses ```G.edges(v)``` to find the neighbors of ```v```, which could be updated using the new views.
