### ISSUE TITLE
graphviews make H=G.__class__() fail

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#2580]
Now that we have multiple subclasses of the graph classes which require arguments to their creation (like ```G.subgraph(nodes)```), the idiom ```H=G.__class__()``` no longer works.  I think something like ```H=G.fresh_copy()``` would fix the trouble.

As for the name, suggestions welcome.  I like ```fresh_copy``` better than anything with ```empty```, or ```new``` in the name.

**Comment by hagberg** [comment]
Can you expand on the change that makes this break?

**Comment by dschult** [comment]
Sorry for the cryptic report.

Graphviews appear to be graphs, and so get used in code expecting Graph/DiGraph, etc.
If that code uses the idiom ```H = G.__class__()``` to create a new graph of the same type as G, it works as expected when ```G``` is a Graph/DiGraph etc.  But when G is a e.g., SubGraph, ```G.__class__()``` is not a valid calling sequence. The correct syntax is ```H = SubGraph(G, nodes)``` so ```G.__class__()``` does not have enough arguments.  This occurs in a few places in the codebase, not all of  which are in the classes directory.

Typically ```G.__class__()``` is an attempt to create an empty version of the graph, without having to guess the underlying data structure.  With Views, we now have an explosion of graph types floating around. And we generally don't want  to create empty versions of them (like SubGraph).  We want to create empty versions of the underlying Graph/DiGraph class upon which they are based.

My best suggestion at the moment is to create a new method:  ```G.fresh_copy()```  (empty graph means something else and new_graph is not as descriptive). For the base classes it just returns Graph()/DiGraph()/ etc.  But views can safely/easily inherit it without change and allow users to create graphs using ```G.fresh_copy()``` even if ```G``` is a view.

**Comment by dschult** [comment]
#2585 is an example of how to meld graphviews into the graph classes and alleviate this issue.

**Comment by dschult** [comment]
```deepcopy(G)``` on a view can be surprising too if you expect it to return a Graph and G is a SubGraph. You end up ```deepcopy```ing the subgraph which includes the original graph too. So we have to be careful using ```G.__class__()``` and ```deepcopy(G)```.  For deepcopy, it doesn't break anything to do the deepcopy, but it might not be what people expect.

**Comment by dschult** [comment]
Recursive algorithms that could use views can run into unwieldy chains of views of views of views....
One example is ```approximation/ramsey.py```.  In such cases, use ```G.subgraph().copy()``` or ```G.reverse().copy()``` to break the chain of views before recursing.
