### ISSUE TITLE
inter_community_non_edges ignore directionality

### ISSUE THREAD

**Issue by NicolasRobitaille** [networkx/networkx#2600]
Hi,

I think the function:

nx.algorithms.community.quality.inter_community_non_edges()

does not work properly for directed graph. It always return the non-edge of a undirected graph, basically halving the number of edges. This mean that the performance function (nx.algorithms.community.performance) will never by higher than 50% for a directed graph.

I'm using version '2.0.dev_20170801111157', python 3.5.1

Best,

Nicolas

**Comment by dschult** [comment]
Can you provide a short example to demonstrate this?
I will be helpful to know more precisely what the trouble is.
Thanks!

**Comment by NicolasRobitaille** [comment]
Hi,
In the example below, you will find that the number of intra_community_edges is multiplied by two when the graph is transform in a directed one, but the number of inter-community non-edge do not change. I found this bug using real life data imported from panda dataframes.

Thanks!

Nicolas

import networkx as nx
G = nx.random_partition_graph([10,10,10],.25,.01, seed=12345)

partition = G.graph['partition']
perf = nx.algorithms.community.performance(G,partition )
intra_edges = nx.algorithms.community.quality.intra_community_edges(G, partition)
inter_edges = nx.algorithms.community.quality.inter_community_non_edges(G, partition)
print('undirected')
print(perf)
print(intra_edges)
print(inter_edges)


G2 = G.to_directed()
partition = G2.graph['partition']
perf = nx.algorithms.community.performance(G2,partition )
intra_edges = nx.algorithms.community.quality.intra_community_edges(G2, partition)
inter_edges = nx.algorithms.community.quality.inter_community_non_edges(G2, partition)
print('directed')
print(perf)
print(intra_edges)
print(inter_edges)
