### ISSUE TITLE
Cumulative nomination scheme as a centrality measure (migrated from Trac #261)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#261]
Original ticket https://networkx.lanl.gov/trac/ticket/261
Reported 2009-08-17 by trac user dheerajrav, assigned to @hagberg.

Cumulative nomination scheme, also known as CNS is a centrality measure which works on the principle of ranking a graph based on the nominations it gets.

The individuals(nodes) in a graph gets the initial nomination of 1. and at every stage, each individual(node) gets additional nominations their contacts already have( 1 is the nomination in the first stage).
Thus, the individual with more nominations will be considered more important than the contacts with only a few nominations.

The process is repeated till the growth of every individual is a constant.

I've attached the CNS code (which works for both connected and disconnected components)

Reference:-   Dynamical systems to define centrality in social networks by Poulin, Boily and Masse

**Comment by hagberg** [comment]
See #1737
