### ISSUE TITLE
min_cost_max_flow with constant costs?

### ISSUE THREAD

**Issue by colegleason** [networkx/networkx#2616]
Hi, I hope this question isn't too off base to bring up here.

Is it possible to have fixed costs, independent of flow amount, in a Minimum Cost Max Flow problem? Would it be possible to have both per unit costs and fixed costs? Finally, if either is possible, could any of the algorithms available in NetworkX be modified to support this use case? I looked at the code for network_simplex, but am not familiar enough with the algorithm to see if it would still work with this modification.

I'm imaging a case where moving flow from one node to another incurs a one-time cost, or it incurs both a one time cost and a per unit cost. Think of a credit card fee, which could be $0.20 + 2.7%.

**Comment by dschult** [comment]
You might try asking on the NetworkX discussion list. 
That has a broader audience and someone might have tried something similar.
