### ISSUE TITLE
PyPI has the development version

### ISSUE THREAD

**Issue by vladsaveliev** [networkx/networkx#2627]
2.0b1 was uploaded to PyPI: https://pypi.python.org/pypi/networkx/

It breaks compatibility with the libraries that still assume that the latest stable version is 1.11. Also, the [website's](http://networkx.github.io/) link under "networkx-1.11" points to the beta as well.

I'm wondering if the stable version can be re-uploaded back to PyPI?

**Comment by dschult** [comment]
I have un-hidden the stable release v1.11.  Apparently all older versions automatically get hidden by default when a new version is uploaded. I've un-checked that box on the admin page. I assume that means we will need to manually do it in the future. 

I've tested installing networkx via pip in a conda virtual environment and it pulled down v1.11 as desired.  I can then install the new beta version using ```pip install networkx==2.0b1```.

**Comment by dschult** [comment]
Thanks @vladsaveliev !!

**Comment by ewels** [comment]
Great stuff - thanks for the fast response and fix @dschult!

This may be a blessing in disguise as it alerted us to what will presumably be a breaking change when v2 is released for real and gives us time to get a fix in place...

**Comment by vladsaveliev** [comment]
That's great, thanks for the fast fix @dschult!
