### ISSUE TITLE
eccentricity() doesn't efficiently handle its sp parameter

### ISSUE THREAD

**Issue by innovate-invent** [networkx/networkx#2628]
When iteratively reducing a graph based on its eccentricity, there is no reason to recalculate all path lengths for sub-graphs. 
The exception networkx.exception.NetworkXError: Graph not connected: infinite path length
occurs when passing the result of all_pairs_dijkstra_path_length() calculated on the initial super-graph.
The function should just make use of the relevant paths and ignore any removed paths from the sub-graph.

**Comment by dschult** [comment]
Can you give a simple example which shows the problem?
Also, which function are you sending the eccentricity to?
If I understand what you are saying correctly, he infinite path length error should only occur if you remove nodes which make the rest of the graph disconnected.

**Comment by innovate-invent** [comment]
Here is a simplified example:
graph = path_graph(5)
paths= all_pairs_dijkstra_path_length(graph)
graph.remove_edge(3,4)
for component in connected_component_subgraphs(graph):
   eccentricity(component, sp=paths) # Exception thrown

**Comment by hagberg** [comment]
Maybe I'm not understanding your exact use case.  But you definitely need to calculate the correct shortest path lengths (and those could change if removing edges.  e.g. like your example slightly modified)

```python
import networkx as nx
graph = nx.cycle_graph(5)
paths= dict(nx.all_pairs_dijkstra_path_length(graph))
graph.remove_edge(3,4)
for component in nx.connected_component_subgraphs(graph):
    print(nx.eccentricity(component, sp=paths))
    print(nx.eccentricity(component))
#{0: 2, 1: 2, 2: 2, 3: 2, 4: 2}
#{0: 3, 1: 2, 2: 3, 3: 4, 4: 4}
```

The eccentricity code is very simple so if you have a way to quickly update the shortest paths in your graph perhaps you could just update the eccentricities that change?

**Comment by innovate-invent** [comment]
I think I simplified my example to the point that the issue went away. I have a minimum spanning tree with node and edge weights that I am partitioning. I have to remove one edge at a time and reevaluate the eccentricity to decide to continue. There is only one path between nodes so removing an edge doesn't invalidate the shortest paths of the components. I was trying to avoid recalculating the shortest paths or search the calculated paths removing the affected ones.

**Comment by hagberg** [comment]
So you have a special use case (a tree) where the path lengths don't change.  

Here is a way (untested) you could compute eccentricity on trees without recomputing the paths. 

```python
import networkx as nx
graph = nx.path_graph(5)
paths= dict(nx.all_pairs_dijkstra_path_length(graph))
graph.remove_edge(3,4)
for component in nx.connected_component_subgraphs(graph):
    print(nx.eccentricity(component))  # compute sp every time
    print({u: max(d for v,d in paths[u].items() if v in component) for u in component})
```

**Comment by innovate-invent** [comment]
I wouldn't expect my use case to be special. It seems to be exactly what the sp parameter was intended for. What is its purpose if not to avoid recalculating the path lengths when evaluating subgraphs?

**Comment by dschult** [comment]
The original purpose was to avoid recalculating paths on the same graph more than once. If you've already got the paths then you can compute the eccentricity cheaply. 

But if you change the graph (move to a subgraph) you change the shortest paths.  Unless you have a special case, there isn't a nice way to know the shortest paths of a subgraph from the shortest paths of a graph.
