### ISSUE TITLE
get all edges between two nodes in nx 2

### ISSUE THREAD

**Issue by gboeing** [networkx/networkx#2629]
I have a MultiDiGraph. I want to retrieve all the edges (possibly multiple/parallel edges) between two nodes. In networkx 1.x I could do:

```python
import networkx as nx
G = nx.MultiDiGraph()
G.add_edges_from([(0,1),(1,2),(1,2)])
G.edge[1][2]
```

Returns: `{0: {}, 1: {}}`

In networkx 2.x I update my syntax to:

```python
import networkx as nx
G = nx.MultiDiGraph()
G.add_edges_from([(0,1),(1,2),(1,2)])
G.edges[1,2]
```

Returns: `ValueError: not enough values to unpack (expected 3, got 2)`

nx 2 seems to require that I provide a key -- how do I retrieve *all* the edges between u and v? I'm using networkx 2.0b1.

**Comment by hagberg** [comment]
Do you want just the edge data? 
Then `G.get_edge_data(1,2)` does that.

Note also https://github.com/networkx/networkx/issues/2630 on `G.edge`.

**Comment by dschult** [comment]
In addition to ```G.get_edge_data(1, 2)``` you can use ```G[1][2]``` (though it provides a read-only version. To be specific -- I mean a read-only dict keyed by edge-key to values that are read-write dicts of edge attributes.)

We could put this functionality into ```G.edges[1,2]```, but I wonder if you expect to be able to change the resulting dict or are you only using it for reporting those edges? If we go this route I think it should report the read-only version just as ```G[1][2]``` does.

**Comment by gboeing** [comment]
Thanks @hagberg @dschult. My use cases require *both* reporting edge data (read-only is ok) as well as accessing edge data to update attributes. I don't need to remove keys/edges from the resulting dicts, but I do sometimes need to update/add elements in the edge data dicts. Based on your comments, I'm updating my codebase to use a mix of `G.get_edge_data(u,v)` and `G[u][v]`. 

https://github.com/gboeing/osmnx/pull/84

**Comment by dschult** [comment]
I'm not sure why I didn't think of this earlier, but the straightforward way to get code to work with both v1.x and v2 is to replace ```G.edge[1][2]```   with ```G.adj[1][2]```.   That should give what you want.  The ```get_edge_data``` and ```G[1][2]``` will work too, but a simply replace of the name might be easiest.

**Comment by gboeing** [comment]
Thanks. To clarify, are `G[1][2]` and `G.adj[1][2]` equivalent?

**Comment by dschult** [comment]
Yes, in both v1.x and v2.x they are equivalent.   
In v1.x they are both equivalent to ```G.edge[1][2]```. But the ```edge``` attribute has been removed for v2.x.
