### ISSUE TITLE
Question re: API change for add_path/star/cycle

### ISSUE THREAD

**Issue by JDWarner** [networkx/networkx#2634]
Looking through the 2.0 dev docs, I noticed these methods have been removed from the `Graph` namespace in favor of the base `networkx` namespace.  Trying to understand the justification I've perused the discussion in #1562, #1883, and #1970.  What I see is a light stylistic discussion, not a deep dive into something that was really problematic before to justify it.  I don't understand is why this was done.

If there is a huge push to make the entire package functional, a la NumPy, and there are some Python purists who live by 'one best method' around here I can see why this was pursued.  But there are many other Graph-specific methods, and my feel by using NetworkX for several years has been that the overall style was - appropriately - more OO than functional.   When you are using a graph and you want this functionality, some of it is exposed via methods - indeed, all of these functions are barely more than wrappers around the still-public `add_edges_from` - but these functions are no longer available as Graph methods.  They are, thus, less discoverable to early or novice users.  A partial paradigm shift greatly weakens the stylistic argument.

Also, from the Pythonic ideal of maximally readable code, the new method is inferior:

``` python
nx.add_path(G, [1, 2], kwarg=something)  # Add path from G to 1 and/or 2... oh, that's not it...
G.add_path([1, 2], kwarg=something)  # In graph G, add a path from 1 to 2.
```

This is a hard-breaking API change, with no path forward for supporting dual 1.x and 2.0 branches.  When there is good reasons to do this, I fully understand.  But not only does this cause headaches, but the new API _is less intuitive and more cumbersome_ than having these as graph methods!  In addition to the inferior semantics above, every time these methods are called, they now require an additional argument (the graph) and more characters than before to contribute to repetitive stress injury.

Finally, it's trivial to wrap these and expose the functionality in both places here in the package.  It is not anywhere near so trivial to do this from the user's or maintainer's standpoint.  In such cases, when reasonable it's probably best to think of the user.

__IMHO, these methods should be returned to Graph and wrapped in the main namespace.__

**Comment by dschult** [comment]
Thanks for this feedback. Your careful description and analysis is very helpful.

The self-loop methods also were moved from the graph class to functions in the main namespace. I'm guessing they have smaller impact, but potentially similar arguments. Still, they are reporting methods, while ```add_path```, etc are mutating methods/functions.  It's hard to know where the line should be drawn. Simple interfaces are nice: as simple as possible but not simpler.  :)
