### ISSUE TITLE
Cannot create a reversed copy of a reverse view

### ISSUE THREAD

**Issue by kyukyukyu** [networkx/networkx#2648]
In version 2.0b1, creating a reversed copy of a reverse view like

```python
G: nx.DiGraph
G_rev = nx.reverse(G, copy=False)
G_rev_rev = nx.reverse(G_rev, copy=True)
```

raises an exception as follows:

```
  File ".../python3.6/site-packages/networkx/classes/digraph.py", line 1255, in reverse
    H = self.__class__(name="Reverse of (%s)" % self.name)
TypeError: __init__() got an unexpected keyword argument 'name'
```

It seems that referring to `self.__class__` on the reverse view object `G_rev` is resolved to class `ReverseView`, which does not have argument `name`. To enable creating a reversed copy of a reverse view, I think this should be resolved to a directed graph class instead of the reversed view class.

**Comment by dschult** [comment]
Thank you!
That is a bug -- the __class__ method is no longer effective when "self" is a view. 
We need to change that to something like:

    H = self.fresh_copy()
    H.name = "Reverse of (%s)" % self.name
