### ISSUE TITLE
Inefficiency in _weighted_triangles_and_degree_iter

### ISSUE THREAD

**Issue by tlarock** [networkx/networkx#2668]
The line 
`max_weight=float(max(d.get(weight,1.0) 
                             for u,v,d in G.edges(data=True)))`

in _weighted_triangles_and_degree_iter is inefficient. The list of edges should be generated first, then iterated over. Running the following code on my machine, iterating over the pre-generated edgelist is twice as fast as not:
`import timeit`
`setup = 'import networkx as nx;G = nx.fast_gnp_random_graph(20000, 0.01); edges = G.edges(data=True)'`
`timeit.timeit('m = float(max(d.get("weight", 1.0) for u,v,d in edges))', setup=setup, number = 5)`
`timeit.timeit('m = float(max(d.get("weight", 1.0) for u,v,d in G.edges(data=True)))', setup=setup, number = 5)`

**Comment by hagberg** [comment]
This timing statement isn't running the complete task
`timeit.timeit('m = float(max(d.get("weight", 1.0) for u,v,d in edges))', setup=setup, number = 5)`

In that case `edges` in an iterator that gets exhausted during the first loop of the test.  For the next four loops it is empty.   Those loops will run faster but give the wrong (no) result.
