### ISSUE TITLE
networkx.simple_cycles fails to run

### ISSUE THREAD

**Issue by stgeorges** [networkx/networkx#2669]
Hello,

I would like to use networkx to find simple cycles in an undirected graph. I tried a couple of undirected graph examples, and they worked without any issues. However, some of them failed. By failing, I mean the networkx.simple_cycles never returned anything, and the Command prompt window just runs to infinity.
Here is one graph which fails:
![graph_preview](https://user-images.githubusercontent.com/4411411/30512077-e78f6fc2-9ae6-11e7-962d-1c18392fb910.png)

Here is the code that I used:

```
import networkx

graph = {
0: [30, 29, 3, 2], 
1: [29, 27, 4, 3], 
2: [26, 0, 5, 22], 
3: [0, 1, 6, 5], 
4: [1, 25, 20, 6], 
5: [2, 3, 8, 7], 
6: [3, 4, 9, 8], 
7: [22, 5, 10, 18], 
8: [5, 6, 11, 10], 
9: [6, 20, 17, 11], 
10: [7, 8, 13, 16], 
11: [8, 9, 15, 13],
12: [64, 15, 63, 13], 
13: [10, 11, 12, 14], 
14: [62, 13, 61, 16], 
15: [11, 12, 40, 17], 
16: [10, 14, 60, 18], 
17: [9, 15, 41, 19], 
18: [7, 16, 59, 21], 
19: [42, 17, 43, 20], 
20: [4, 9, 19, 23], 
21: [18, 58, 57, 22], 
22: [2, 7, 24, 21], 
23: [44, 20, 45, 25], 
24: [22, 56, 55, 26], 
25: [4, 23, 46, 27], 
26: [2, 24, 54, 30],
27: [1, 25, 47, 28], 
28: [48, 27, 49, 29], 
29: [1, 0, 28, 31], 
30: [0, 26, 52, 31], 
31: [50, 29, 51, 30], 
32: [59], 
33: [40], 
34: [61], 
35: [56], 
36: [43], 
37: [46], 
38: [50], 
39: [53], 
40: [15, 33, 64, 41], 
41: [17, 40, 42], 
42: [19, 41, 43], 
43: [19, 36, 42, 44], 
44: [23, 43, 45], 
45: [23, 44, 46], 
46: [25, 37, 45, 47], 
47: [27, 46, 48], 
48: [28, 47, 49], 
49: [28, 48, 50], 
50: [31, 38, 49, 51], 
51: [31, 50, 52], 
52: [30, 51, 53], 
53: [39, 52, 54], 
54: [26, 53, 55], 
55: [24, 54, 56], 
56: [24, 35, 55, 57], 
57: [21, 56, 58],
58: [21, 57, 59], 
59: [18, 32, 58, 60], 
60: [16, 59, 61], 
61: [14, 34, 60, 62],
62: [14, 61, 63], 
63: [12, 62, 64], 
64: [12, 40, 63]
}

G = networkx.DiGraph(graph)
print "simple_cycles: ", (list(networkx.simple_cycles(G)))
```

I have python 2.7.13, and when networkx is installed I got the following infromation: decorator 4.1.2 networkx 1.11.

Is this some sort of bug?

I would be grateful for any kind of reply.

Kind regards,
Djordje

**Comment by dschult** [comment]
How long would you expect it to take?

Replacing your last line with:

    n=0
    for c in networkx.simple_cycles(G):
        n += 1
        if n % 100000 == 0: print(n)

runs to at least 55million (I stopped it). I imagine storing all those cycles in a list would use a lot of RAM which would slow it down if your machine starts swapping. You may be running into the combinatorics headache of large numbers.

**Comment by stgeorges** [comment]
Dear Mr. Schult,

Thank you for the detailed reply.
So the issue is basically that supplied graph has enormous number of simple cycles?

If this is so, do you mind if I ask another question please?
I am actually not interested in all of simple cycles but in fact in just those which are non inclusive in other cycles.
For example: 
cycle1 = [0,30,31,29]
cycle2 = [1,3,0,29]
cycle3 = [3,5,2,0]
...

![graph_non_inclusive](https://user-images.githubusercontent.com/4411411/30513959-12d3d1de-9b0d-11e7-84fc-18b2faedbd3a.jpg)

The node indices in the cycle can be either clockwise or counter-clock wise, it is not important. Starting node in the cycle does not need to correspond to the very name of the cycle also (cycle1 = [0...).
Does networkx have this functionality?

**Comment by dschult** [comment]
If clockwise and counterclockwise does not matter then you really have an undirected graph.
It looks like you want a "cycle basis".  We have an algorithm in NetworkX called ```cycle_basis``` which works on undirected graphs. Take a look online for definitions of cycle basis and see if it is what you want.

**Comment by stgeorges** [comment]
Dear Mr. Schult,

Indeed I always work with undirected graphs. The reason why I "converted" them to directed ones, is because that has been done in an example code for the [simple_cycles function](https://networkx.github.io/documentation/networkx-1.9/reference/generated/networkx.algorithms.cycles.simple_cycles.html).

But it seems that I mistakenly chose simple_cycles, instead of basis_cycles. Thank you.
The [online documentation](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.algorithms.cycles.cycle_basis.html) for the later one is quite short actually.
The example code requires the cycles to be defined on the very beginning before running the cycles_basis function (eg: `G.add_cycle([0,1,2,3])`)?

Instead of that, I just ran it on the graph itself, like this:

```
G = networkx.Graph(graph)
print "cycle_basis: ", networkx.cycle_basis(G)
```

If this is the correct approach then the function returned 45 cycles in total: 36 non-inclusive cycles and 9 inclusive ones. By "non-inclusive" ones I mean: those that are not encompassed in other cycles. So 9 upper mentioned ones are huge and encompass other cycles as well.
Interestingly exactly 9 non-inclusive cycles are missing from the function return. These:

```
[52,30,26,54,53],
[26,2,22,24],
[0,3,5,2],
[1,4,6,3],
[4,20,9,6],
[6,9,11,8],
[9,17,15,11],
[8,11,13,10],
[7,10,16,18]
```

Is my code wrong, or do I need to use some other networkx function to find only non-inclusive cycles?
My apologies for using such a bad terminology.

**Comment by dschult** [comment]
Your code is not wrong. You are using the function correctly.

Just as a vector space has many choices for basis, and a coordinate system has many choices for coordinate axes, graphs have many choices for cycle basis.  Your picture makes it clear to us humans how to choose the cycles to be as short as possible. But many/most graphs don't look so symmetric when drawn.  From the algorithm's perspective it is not easy to pick which cycles to be in the basis.

In your example, the 45 cycles are a basis for all cycles. You can add them together (going across an edge in opposite directions removes that edge from the sum) to get other cycles. You can also subtract them to get them going the other direction. They are a basis because you can get all cycles by adding and subtracting these 45 (they span the cycles of the graph) and you can't write any one of them as sums/differences of the others (they are linearly independent).  The 9 big ones the function found COULD be replaced with the 9 that you found -- that would give a different basis. But each of the small ones you found could also be constructed as a sum/difference of the 45 that the function returned.

So the ```cycle_basis`` function did return a correct basis for the cycles of the graph. It was not the basis you were expecting (which I think is a basis with minimal number of nodes in the basis cycles).  But it is a valid basis. I don't know any algorithm to find the basis with minimal number of nodes.

Also- it is no accident that the number of long cycles reported in the basis is the same as the number of short cycles not reported. The size of each possible basis is the same (45). Just as the number of coordinate axes needed is the same when changing coordinate systems. It's like the dimension of the cycle space of the graph.

**Comment by stgeorges** [comment]
Thank you for the detailed reply Mr Schult,

> I don't know any algorithm to find the basis with minimal number of nodes.

I didn't know this.

> In your example, the 45 cycles are a basis for all cycles. You can add them together (going across an edge in opposite directions removes that edge from the sum) to get other cycles. You can also subtract them to get them going the other direction. They are a basis because you can get all cycles by adding and subtracting these 45 (they span the cycles of the graph) and you can't write any one of them as sums/differences of the others (they are linearly independent). The 9 big ones the function found COULD be replaced with the 9 that you found -- that would give a different basis. But each of the small ones you found could also be constructed as a sum/difference of the 45 that the function returned.

Is it possible to provide some sort of small code example for this?
