### ISSUE TITLE
Possible bug in nx.graph.degree() returning incorrect degree

### ISSUE THREAD

**Issue by TheShadow29** [networkx/networkx#2674]
![screenshot from 2017-09-19 11-17-32](https://user-images.githubusercontent.com/10602903/30577507-51cd0f6a-9d2c-11e7-8a24-a444b0a708a9.png)
Code to reproduce:
```
import networkx as nx
import numpy as np
A = np.random.random((3,3))
G = nx.from_numpy_matrix(A)
G.edges(data=True)
G.degree()
```
`G.degree()` should have returned 2 but instead it is returning 4. 
If instead `G.degree(weight='weight')` is used it also doesn't return the expected sum of the weights.

If A is created as a 5x5 matrix, `G.degree()` returns degree of 6 for each of the nodes. I am not completely sure but [degree documentation](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.DiGraph.degree.html) says it is for Digraph degree. Is that the reason for the issue?

**Comment by dschult** [comment]
The difference from what you are expecting is due to self-loops.
In your example, node 0 is connected to itself, node 1 and node 2 in an undirected graph. The self-loop represents two connections to node 0. So the number of connections to node 0 is four. Similarly for the other nodes.  In general is you connect all N nodes to all nodes, the self-loops will make the degree of each node N+1.

This could/should be better described in the docs.

**Comment by TheShadow29** [comment]
@dschult But isn't the Degree Matrix D calculated as 
`D = diag(sum(Adj, axis=0))` ? 
Suppose n1 is a self-loop node. So Adj(n1,n1) should be 2? But then this isn't consistent with the `nx.adjacency_matrix(G)` which would give Adj(n1, n1) = 1 instead of 2.
![screenshot from 2017-09-19 17-53-40](https://user-images.githubusercontent.com/10602903/30592245-a617440a-9d63-11e7-87f1-09bd4fa6799e.png)
Code to reproduce:
```
import networkx as nx
import numpy as np
G = nx.path_graph(3)
G.add_edge(0,0)
G.edges(data=True)
Adj = nx.adjacency_matrix(G)
Adj2 = Adj.todense()
print(Adj2)
print(G.degree())
```
Degree of all nodes are correct except for those with self loops. Is there some obvious mistake that I am glossing over?

**Comment by dschult** [comment]
The usual [definition for degree](https://en.wikipedia.org/wiki/Degree_(graph_theory)) of a node is the number of edges incident to the node with loops counted twice. Your characterization using the sum of the adjacency matrix works for graphs without loops. But self-loops are counted twice in [the degree matrix](https://en.wikipedia.org/wiki/Degree_matrix).
