### ISSUE TITLE
Reading shapefiles fails because  add_node() expects a kwargs

### ISSUE THREAD

**Issue by aerispaha** [networkx/networkx#2676]
It seems that in v2.x, `G.add_node()` no longer accepts a dictionary to add attributes to the node and instead accepts kwargs. This breaks `nx.read_shp()` because the dictionary, `attributes`, (created for each feature in the shapefile), is passed into `add_node()`. 

I think this can be fixed by simply unpacking the `attributes` dictionary.

**Comment by dschult** [comment]
closed via #2678
