### ISSUE TITLE
A* documentation typo

### ISSUE THREAD

**Issue by mwillsey** [networkx/networkx#2683]
I'm fairly certain there's a small but confusing typo in the [documentation for A*](https://github.com/networkx/networkx/blob/fbc901aa2d30c8dfbe145af747097e92d9b5e5c9/networkx/algorithms/shortest_paths/astar.py#L123). Specifically "<" in the following paragraph (linked):

```python
# if qcost < ncost, a longer path to neighbor remains
# enqueued. Removing it would need to filter the whole
# queue, it's better just to leave it there and ignore
# it when we visit the node a second time.
```

After staring at it for a while, I think this should read "if qcost > ncost", as it's referring to the negation of the following `if qcost <= ncost` statement. Also, the text refers the enqueued path being longer.

**Comment by dschult** [comment]
Is it possible that this comment is at the place were we "ignore it when we visit the node a second time"?  Certainly the comment should either be changed or removed. It may be easier to follow the code than the comment.

**Comment by lonnen** [comment]
This is resolved by https://github.com/networkx/networkx/pull/2959

**Comment by dschult** [comment]
Thank you!
