### ISSUE TITLE
in_degree values

### ISSUE THREAD

**Issue by sevmardi** [networkx/networkx#2686]
The [docs](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.MultiDiGraph.in_degree.html?highlight=in_degree#in-degree)  says `list(G.in_degree([0,1]).values())` should return the values. 2.0 [docs](https://networkx.github.io/)   doesn't mention anything about values just returning a tuple. So the question is how to fetch the values of the in_degree? What are the options?

**Comment by dschult** [comment]
You are the second person to ask about this. So clearly we should change something in the docs or the code. Here are some suggestions:

    deg = G.in_degree   # sets up a view -- can access all nodes, but doesn't until you use it.
    [d for n, d in deg]   # gets all nodes' degree values
    (d for n, d in deg)    # iterator over degree values
    [deg[n] for n in [0, 1]]   # using lookup for only some nodes

    dict(G.in_degree([0, 1])).values()    # works for nx-1 and nx-2
    # G.in_degree(nlist) creates a restricted view that only allows lookup of those nodes.
    # but see the fourth option above for using lookup instead.
    list(d for n, d in G.in_degree([0, 1]))

    [len(nbrs) for n, nbrs in G.pred.items()]    # probably slightly fastest for all nodes
    [len(G.pred[n]) for n in [0,1]]               # probably slightly faster for only some nodes

**Comment by sevmardi** [comment]
Thanks! I will give it a try. Please do consider either updating the docs or the code.
