### ISSUE TITLE
networkx 1.1 vs 2.0 gpickle

### ISSUE THREAD

**Issue by jeremy886** [networkx/networkx#2688]
I got a pickle file from network 1.1 but I couldn't open it under 2.0.

Interestingly, I tried all possible file formats (like json, gexf, gml etc.) but all failed in different ways.
(mainly issues related to numpy.float64).

At the moment, I tried to use to transfer graphs by:
from 1.1
old.nodes(data=True)
old.edges(data=True)

Copy the output text to 2.0
new = nx.Graph()
new.add_nodes_from(....)
new.add_edges_from(....)

Is there a better way to solve this compatibility issue? Thanks.

[pickle file](https://www.dropbox.com/s/qwb0d1g035agneg/major_us_cities?dl=0)

**Comment by dschult** [comment]
It is true that pickle doesn't store the class definitions, only the data itself. So you won't be able to read a pickled v1 Graph using v2.  You can still use pickle to do that transfer of the node and edge information though.

    # in v1.x
    pickle.dump([G.nodes(data=True), G.edges(data=True)], file)
    # then in v2.x
    nodes, edges = pickle.load(file)
    G=nx.Graph()
    G.add_nodes_from(nodes)
    G.add_edges_from(edges)

If you don't have node attributes and you don't have isolated nodes, you can just pickle the edges. Then creating ```G``` is simply ```G = nx.Graph(pickle.load(file))```

Your comment about ```numpy.float64``` indicates that you have numpy arrays in your node/edge attributes. Make sure you have a compatible version of numpy when you read the pickle file to the version of numpy when you wrote the pickle file.

**Comment by jeremy886** [comment]
@dschult thanks. I have created a v2.x compatible pickle using your instructions.
