### ISSUE TITLE
argument create_using of nx.from_pandas_adjacency() is used in a wrong place

### ISSUE THREAD

**Issue by kyukyukyu** [networkx/networkx#2689]
https://github.com/networkx/networkx/blob/6bdf9810667bedd2712cb7ad73ebee34a8abb8bd/networkx/convert_matrix.py#L191

Since `from_numpy_matrix()` in the same file accepts argument `create_using` as the third argument, the function call above should be fixed.

**Comment by dschult** [comment]
Yes -- that's a bug. Your fix looks like a good one. Do you want to make a PR or should I fix it?

**Comment by kyukyukyu** [comment]
Thanks. I'll make a PR for it.

**Comment by dschult** [comment]
Fixed in #2693
