### ISSUE TITLE
Subgraph isomorphism

### ISSUE THREAD

**Issue by anso-sertier** [networkx/networkx#2697]
Hello,

I'm working on detection of subgraph isomorphism with : GM.subgraph_isomorphisms_iter() function.
In a working example, my G1 should be isomorphic to G2 and the function return nothing.
I take a look at the code and made some print to understand. And finally, the printing inside the match() function from GraphMatcher class return an error on line 71 of _semantic_feasibility function in vf2userfunc.py).

File "/home/anneso/myroot/lib/python2.7/site-packages/networkx-1.11-py2.7.egg/networkx/algorithms/isomorphism/vf2userfunc.py", line 71, in _semantic_feasibility
    G2_adj[G2_node][core_1[neighbor]]):
KeyError: 'AB2a'

I don't know if I'm right or not, but if I understand well, the edge en G2 (between G2_node and core_1[neighbor]) might not exist, by construction the edge G1_node/neighbor exists but in G2, this edge could not exist and thus return a KeyError that stop all the current process (the match() function return nothing).
Am I write ?

Thanks in advance.

**Comment by chebee7i** [comment]
If you can construct a small example that we can run to reproduce the problem, that would be helpful.

**Comment by dschult** [comment]
Idle for too long...
