### ISSUE TITLE
pareto_sequence,create_degree_sequence and configuration model missing/changed

### ISSUE THREAD

**Issue by Larckov** [networkx/networkx#2700]
I have an not so old code (one month old) that uses the Pareto sequence function from "nx.utils.random_sequences", to put as parameter in the "nx.utils.create_degree_sequence", to finally, use in the configuration model.

But stopped to work the moment I updated. I work in Arch, and I have networkx 2.0-1.

I have searched into the docs here in GitHub, and have seen some changes into the code, some functions missing, and stuff like that. 

Any idea what can I do?

**Comment by dschult** [comment]
Pareto_sequence and create_degree_sequence were deprecated with a warning 4 years ago -- and have now been removed.  They can be replaced by:

    import random
    max_deg = n
    try=0
    while try < max_tries:
        raw_seq = (random.paretovariate(exponent) for i in range(n))
        seq = [min(max_deg, max(int(round(s)), 0) for s in raw_seq]
        if networkx.is_valid_degree_sequence(seq):
            break
        try += 1

Configuration_model has not been changed so you can pass it the valid sequence as before.

**Comment by Larckov** [comment]
Thank you, I didn't know about it.
