### ISSUE TITLE
overly strict key requirements in generate_gml?

### ISSUE THREAD

**Issue by zfrenchee** [networkx/networkx#2701]
In function `generate_gml`, the first non-docstring line is:

```
    valid_keys = re.compile('^[A-Za-z][0-9A-Za-z]*$')
```

Which seems overly strict. [The wikipedia article seems to suggest you can have spaces](https://en.wikipedia.org/wiki/Graph_Modelling_Language). I wanted underscores. Why is this regex so strict?

**Comment by hagberg** [comment]
It's likely just following the spec here http://www.fim.uni-passau.de/fileadmin/files/lehrstuhl/brandenburg/projekte/gml/gml-technical-report.pdf
which says ``Key ::= [ a-z A-Z ] [ a-z A-Z 0-9 ]``

**Comment by zfrenchee** [comment]
@hagberg thanks for getting back to me and my apologies. I think I had assumed graphml and gml were the same. I think I can just switch to graphml to solve my issues.
