### ISSUE TITLE
GraphML writer does not support <class 'numpy.float64'> as data values.

### ISSUE THREAD

**Issue by zfrenchee** [networkx/networkx#2702]
Pretty straightforward. I'm trying to write a graph to graphml. I get this error. 

```
networkx.exception.NetworkXError: GraphML writer does not support <class 'numpy.float64'> as data values.
```

I'm going to try casting to floats for my use case for now, but this should be a pretty quick fix, I suspect? There aren't limitataions on the format that cause this to be impossible..?

**Comment by hagberg** [comment]
duplicate #1556
