### ISSUE TITLE
import networkx <- this code prints something

### ISSUE THREAD

**Issue by ftatp** [networkx/networkx#2707]
Hi I'm using networkx in my recent project. I'd met a problem when I Import networkx.

When I open python3 and start with "import networkx", something prints out. Those logs are something that I had printed before, that time also I used networkx. After the "import networkx", followed by the logs, I also did "from networkx.algorithms import approximation as approx" and it gave me an error like this:
"ImportError: No module named 'networkx.algorithms'; 'networkx' is not a package"

I thought this was a problem for my networkx module in my computer, so I removed all of the things that is related with networkx. But when I typed "import networkx" even when I didn't installed it again, the same logs printed out and even there was no error message that networkx does not exist. Simply speaking, all the things was the same before and after the removing networkx.

What's the problem?

**Comment by ftatp** [comment]
I'd found a weird solution. I had put the python code that imports networkx outside of my original directory and it worked perfectly.
Why is this happening? Actually I also used notebook. Is this something that makes me crazy?

**Comment by harryscholes** [comment]
Did you create a Python script called `networkx.py`?

```
$ echo "from networkx.algorithms import approximation" > networkx.py; python networkx.py

ModuleNotFoundError: No module named 'networkx.algorithms'; 'networkx' is not a package
```

**Comment by ftatp** [comment]
Omg how stupid I am. Ya I've made that file for testing the networkx....
Sorry for my stupid job and thank u very much.

2017. 10. 17. 오후 6:48에 "Harry" <notifications@github.com>님이 작성:
