### ISSUE TITLE
Code breaking change in v2.0 with hyperopt!

### ISSUE THREAD

**Issue by dsanalytics** [networkx/networkx#2708]
It seems that networkx v2.0 breaks hyperopt (error: TypeError: 'generator' object is not subscriptable). Rolling networkx back to 1.11 fixes the issue.

Environment:
Python v3.6.3 (64bit)
hyperopt 0.1
OS 1: Windows 7 SP1 64bit Home Premium
OS 2: Windows 10 64bit Home Premium
Jupyter Notebook Server v5.0.0

steps to reproduce:
pip install hyperopt

run the code below in jupyter notebook:
from hyperopt import fmin, tpe, hp
best = fmin(fn=lambda x: x ** 2,space=hp.uniform('x', -10, 10),algo=tpe.suggest,max_evals=100)
print(best)

Error reported (screenshot attached): TypeError: 'generator' object is not subscriptable

Workaround: run the following line under the command prompt in python\scripts folder
pip install networkx==1.11

Links:
https://github.com/hyperopt/hyperopt 
http://hyperopt.github.io/hyperopt/ 
https://www.youtube.com/watch?v=Mp1xnPfE4PY

![hyperopt-jupyter-error-generator-not-subscriptable](https://user-images.githubusercontent.com/32625394/31502439-acfce7c6-af32-11e7-8770-357205499dee.png)

**Comment by MridulS** [comment]
https://github.com/hyperopt/hyperopt/commit/2442bb24aca594bd566044fce276afbd377e0c03

It is fixed in the master repo of hyperopt.

**Comment by dsanalytics** [comment]
Thanks - it seems that they still have not packaged that for pip install yet for I got the error yesterday.

**Comment by dsanalytics** [comment]
Does this ticket closing mean that this fix has been packaged and available with pip install?

**Comment by hagberg** [comment]
Not sure - but my understanding that this is a hyperopt issue.
