### ISSUE TITLE
Mimic behavior of pre-2.0 `connected_component_subgraphs`

### ISSUE THREAD

**Issue by standage** [networkx/networkx#2714]
First, I want to say thank you for your awesome library!

I have created a subclass of the `networkx.Graph` class (let's call it `MyGraph`), and am trying to figure out how to mimc the behavior I used to see with pre-version-2.0 code. When I would call `connected_component_subgraphs(G)` on a `MyGraph` instance, each connected component returned would in turn be instantiated as a `MyGraph` instance with access to the custom data and methods I had defined.

Now with the new subgraph views I'm struggling to figure out how to instantiate each CC as a `MyGraph` instance.  From [this page](https://networkx.github.io/documentation/latest/reference/classes/generated/networkx.Graph.subgraph.html) I figured out that `G.subgraph(cc).copy()` will give the full graph node / edge structure. However, these revert to instances of `networkx.Graph` instead of `MyGraph`, so I lose access to the custom data and attributes.

Any pointers on how I can instantiate graph CCs as instances of `MyGraph`? Thanks.

The networkx functionality I rely on most is finding connected components. Previously when I would call `connected_component_subgraphs(G)`, it would return

**Comment by dschult** [comment]
Please try adding one method to your ```MyGraph``` class which will help it make copies of the right object.  The method is ```G.fresh_copy()```. It should return an empty graph object of the type you want to use for copies.

    def fresh_copy(self):
        return MyGraph()

Note that any subgraph views of MyGraph will be View objects that inherit from NetworkX Graph. So you might also need to overwrite the subgraph method. Try just adding ```fresh_copy``` first though.

If that doesn't work, try overwriting the subgraph method in your MyGraph class.  The current code is something like:

    def subgraph(self, nodes):
        induced_nodes = nx.filters.show_nodes(self.nbunch_iter(nodes))
        SubGraph = nx.graphviews.SubGraph
        # if already a subgraph, don't make a chain
        if hasattr(self, '_NODE_OK'):
            return SubGraph(self._graph, induced_nodes, self._EDGE_OK)
        return SubGraph(self, induced_nodes)

The new code will require a subgraph class and a tweaked subgraph method of MyGraph.

    class MySubGraph(nx.graphviews.SubGraph, MyGraph):
        pass

    # then inside MyGraph create a subgraph method that uses MySubGraph instead of SubGraph
    ...
    def subgraph(self, nodes):
        induced_nodes = nx.filters.show_nodes(self.nbunch_iter(nodes))
        SubGraph = MySubGraph
        # if already a subgraph, don't make a chain
        if hasattr(self, '_NODE_OK'):
            return SubGraph(self._graph, induced_nodes, self._EDGE_OK)
        return SubGraph(self, induced_nodes)


Please let me know how this works for you. This is an unanticipated complication for which we might need to create a workaround.
Thanks!

**Comment by standage** [comment]
I ended up doing something like the following (see [the PR diff](https://github.com/dib-lab/kevlar/pull/145/files#diff-1ad294730b3cf07444e0cf1d1311edc9)).

```python
# in MyGraph
def full_cc(self, cc):
    sg = self.subgraph(cc).copy()
    sg = MyGraph(data=sg)
    sg.customdata1 = self.customdata1
    sg.customdata2 = self.customdata2
    return sg
```

It's not super clean, but it's not much worse than any of the suggested solutions. If there's an easier way to do this in future releases please let me know. Thanks!

**Comment by dschult** [comment]
If you will call MyGraph on the data anyway, you don't need the copy of the subgraph.
You can use ```sg = MyGraph(self.subgraph(cc))``` and then add the customdata.

Also, just to be clear -- the ```customdata``` was not copied to the subgraph under pre-2.0 subgraphs. 
Only the methods were in the new subgraph.

Finally, your class' ```copy``` method will create a networkx Graph unless you add the method ```fresh_copy``` (or overwrite the copy method).
