### ISSUE TITLE
Limiting the size of a simple cycle

### ISSUE THREAD

**Issue by danielbyler** [networkx/networkx#2715]
I'm searching for simple cycles in a large graph and despite having 2 TB of RAM, am running out of memory. I am considering implementing a limiting optional argument for the simple cycle. 

Basically, if you go over X links in the chain then just stop searching because the loop is too long to be useful. 

If I did this, would this be of use/something you'd be interested in having as a contribution?

Thanks!

**Comment by hagberg** [comment]
`simple_cycles` is a generator so you can stop the iteration after a certain number of cycles.  One way to do it is with islice

```python
In [1]: import networkx as nx

In [2]: G = nx.DiGraph([(0, 0), (0, 1), (0, 2), (1, 2), (2, 0), (2, 1), (2, 2)])
   ...: 

In [3]: list(nx.simple_cycles(G))
Out[3]: [[0, 2], [0, 1, 2], [0], [1, 2], [2]]

In [4]: from itertools import islice

In [5]: list(islice(nx.simple_cycles(G),3))
Out[5]: [[0, 2], [0, 1, 2], [0]]
```
