### ISSUE TITLE
What is the proper way to create a networkx 1.x style subgraph?

### ISSUE THREAD

**Issue by danse-macabre** [networkx/networkx#2716]
Hello,

First of all, I would like to thank you for your continuous effort, that you put into this library. The constant flow of improvements and new features, along with a great quality of code and documentation, are really impressive!

The last major version of the *networkx* package has brought us a great amount of cool features and ideas, with the `SubGraph` class among them, which is here a particular subject of interest. 

If I understand correctly, the `SubGraph` was designed to represent a sort of a live view over it's parent graph. The *liveness* here is achieved through the usage of a various node and edge filters, which tells the subgraph of what particular nodes and edges should be included in the view.

However, one might encounter a case, where the usage of *old-style* subgraphs are more preferable, due to speed considerations. Thus, here is the question about what is the proper way to create a netoworkx 1.x style subgraph? During my works, I've came up with the following solution: 

```python
def old_style_subgraph(G, nbunch):
    """
    Make a subgraph of `G`, which consist only of nodes in `nbunch`.
    """
    H = G.fresh_copy()
    H.add_edges_from(nx.induced_subgraph(G, nbunch).edges(keys=True, data=True))
    return H
```

But I wonder, if there is a more nice and clean way to do this?

Thank you in advance!

**Comment by danse-macabre** [comment]
Following the previous question, have you considered using the *Observer/Observable* model in application to *SubGraph/Graph* objects? 

In this way, the particular `Graph` instance could be an *Observable* object, which will constantly notify it's *Observers* (i.e. `SubGraph` instances) about events, such as a new node/edge has been added or an old one has been removed. 

In their turn, the `SubGraph` objects, which are registered as the observers of the parent graph, would react to the notifications with the corresponding actions (i.e. adding/removing their internal nodes/edges).

IMHO, the particular advantage here is that the calls to internal `EDGE_OK` and `NODE_OK` will happen only once per new edge/node, and not every time the `edges` or `nodes` view is requested. Thus, the amount of time that is necessary to build the views will be greatly reduced.

As for example, please, consider a graph with approximately 50,000 nodes and 150,000 edges, and it's subgraph, which consists only of 2-3 parent's nodes. if I understand correctly, an access to the `nodes` property of that subgraph will result in internal call to `FilterAtlas.__iter__`, which is 

```python
    def __iter__(self):
        return (n for n in self._atlas if self.NODE_OK(n))
```

, where `self._atlas` is the view over the whole set of the parent's nodes. Now, just imagine that this will happen every time you access the `nodes` property, and you will get the idea.

I will greatly appreciate, if you will share some thoughts on this matter.
Thanks again!

**Comment by dschult** [comment]
To do what v1.x ```G.subgraph(nodes)``` did, you could use:

    H=G.subgraph(nodes).copy()

That's what I think of as the best generic way to create a non-view version of a node induced subgraph. It does go through all the induced nodes (and filter them) when creating the copy. But it only does that once (same as the older-style subgraph).

Creating the subgraph view is actually quite fast.  And we do put in some shortcuts for iterating over the nodes.  For example, you mention iterating over ```G.nodes```. The code for FilterAtlas is actually

    def __iter__(self):
        if hasattr(self.NODE_OK, 'nodes'):
            return iter(self.NODE_OK.nodes & set(self._atlas.keys()))
        return (n for n in self._atlas if self.NODE_OK(n))
 
For a node induced subgraph the first ```if``` condition holds True,  so, we iterate over a set created by the intersection of the induced nodes and the graph nodes. Looking at the guts of intersection, we actually only iterate over the 2-3 induced nodes -- not the 50,000 nodes.  Still, it is true that every node/edge access requires lookups of some sort. The subgraph view construct has slower lookup and vastly faster creation time than the older-style subgraphs.  But the slower lookup isn't too bad either -- it's looking up in a hash (dict or set).

We didn't make subgraph views with the idea of creating a live view of a graph -- though that is a nice benefit. The goal for subgraph views was to have a fast/light way to make induced subgraphs using the data already in the Graph. This was motivated by Python 3's ```dict``` methods ```items/values/keys```.  They also create live views of the dict. But most people don't use them that way. The big benefit is that we don't create a list every time we call items/values/keys. We create a fast/light object that uses the dict data. Python 2 has methods for iterators iteritems, et.al. But those can only iterate. The views provide many other features beyond iteration. The Subgraph Views (and the edge/node/adj views) of NetworkX also don't copy any data. They report what is in the original graph.

For cases where you must lookup nodes often... and ```G.subgraph(nodes).copy()``` feels too slow, you could always do:

    nodes=set(nodes)
    H=nx.Graph((u, v, dd) for u in nodes for v,dd in G[v].items() if v in nodes)
    H.add_nodes_from((n, G.node[n]) for n in nodes)

It doesn't look at any nodes other than neighbors of the induced nodes.  If you don't need data attributes, or don't have isolated nodes you can make it even faster.   

But in the end, I would suggest ```G.subgraph(nodes).copy()```

**Comment by danse-macabre** [comment]
Thank you for detailed explanation! The  `G.subgraph(nodes).copy()` is the solution I was look for.
