### ISSUE TITLE
Erroneous results in cluster._weighted_triangles_and_degree_iter

### ISSUE THREAD

**Issue by mcognetta** [networkx/networkx#2724]
I was working on #2243 (my branch is https://github.com/mcognetta/networkx/blob/weighted_transitivity/networkx/algorithms/cluster.py) and I think that there is some issue with the cluster._weighted_triangles_and_degree_iter helper function.
The function signature is:
```
def _weighted_triangles_and_degree_iter(G, nodes=None, weight='weight')
```
In it, there is an if statement to set the max_weight

```
    if weight is None or G.number_of_edges() == 0:
        max_weight = 1
    else:
        max_weight = max(d.get(weight, 1) for u, v, d in G.edges(data=True))
```

The problem here is, consider the case that we are using a normalized weighted graph (all edges have weight 0 <= w <= 1). The maximum weight of the graph may not be 1. However, later in the method, the geometric mean of triangles around vertex _v_ is computed with:
```
    def wt(u, v):
        return G[u][v].get(weight, 1) / max_weight
```
and
```
            wij = wt(i, j) # Note: I am not sure why this is computed here
            weighted_triangles += sum((wij * wt(j, k) * wt(k, i)) ** (1 / 3)
                                      for k in inbrs & jnbrs)
```

This will give erroneous results when using the iterator for the weighted transitivity function since we could have a max_weight of less than 1.

For example, using my branch, consider the case:

```
>>> G=nx.Graph()
>>> G.add_edge('a','b',weight=0.6)
>>> G.add_edge('a','c',weight=0.2)
>>> G.add_edge('c','d',weight=0.1)
>>> G.add_edge('c','e',weight=0.7)
>>> G.add_edge('c','f',weight=0.9)
>>> G.add_edge('a','d',weight=0.3)
>>> nx.transitivity(G,weight='weight')
0.030285343213868998
```
when the actual weighted transitivity is ~0.0272568.

Anyway, maybe there should be something in the parameters that determines if max_weight should ever be considered in computations.

**Comment by dschult** [comment]
Are you suggesting an optional keyword ```max_weight```?

I think if you have a normalized weight between 0 and 1 then the max_weight will be 1.  Perhaps you are choosing random weights between 0 and 1 and haven't normalized the results to be between 0 and 1. In any case, I can certainly see why you would not want ```max_weight``` to be used.

My inclination is to remove the max_weight code. Is there a use-case where it is helpful? Can't people use ```set_edge_attributes``` to scale all the edge weights?

Also, the ```wij``` is computed before entering the loop because it doesn't change as we loop over ```k```.

**Comment by hagberg** [comment]
I vote for removing the max_weight code in favor of letting the user scale the weights.
