### ISSUE TITLE
Add a node when add_path involves no edge.

### ISSUE THREAD

**Issue by sanghack81** [networkx/networkx#2726]
`add_path` is convenient for adding edges without adding nodes explicitly.
Consider a case where there exists no edge to be added:

```
G = nx.Graph()
nx.add_path(G, [0])
```
If one wants to test the neighbors of a node in a graph, `G.neighbors(0)` will throw networkx.exception.NetworkXError: The node 0 is not in the graph.

Obviously, one can check whether the argument for `add_path` is a singleton and explicitly do

```
path = [0]  # or something else
G = nx.Graph()
if len(path) == 1:
    G.add_node(path[0]) 

nx.add_path(G, path)
G.neighbors(0)
```

Should adding a zero-edge path with a single node add a node in the graph if the node isn’t already in the graph?
This also applies to `add_star`.

**Comment by hagberg** [comment]
I think I have to agree that a path of length zero (and a star with no leaves) should be included.  Would you like to create a PR with this fix?

**Comment by Kentzo** [comment]
Please re-open the issue: it was solved for `add_path`, but `add_star` still does not add a node if it's single.

**Comment by dschult** [comment]
I will open a new issue.  This issue is pretty old and closed long ago. It certainly should be fixed.
