### ISSUE TITLE
Graph.add_edge_from() is reversing edge order

### ISSUE THREAD

**Issue by vaibhavskarve** [networkx/networkx#2727]
Minimal working example:
```
G = nx.Graph()
[G.add_edge(*i) for i in [(0, 4),(3, 4)]]
print(G.edges)

# Current output is: [(0, 4), (4, 3)]
# instead of [(0, 4), (3, 4)]
```
I understand that this is because I initialized an empty graph and it sees nodes in the order 0 then 4 then 3.
But I think this can create gotchas if a user is not aware of it.

**Comment by hagberg** [comment]
The ordering of edges in for NetworkX Graphs is arbitrary.  The edge has no direction so either (u,v) or (v,u) represents the same edge.  If you want ordered edges then the correct NetworkX graph class is DiGraph (or MultiDiGraph if you want parallel edges).
