### ISSUE TITLE
Reading graphs with certain node/edge properties

### ISSUE THREAD

**Issue by mddddd** [networkx/networkx#2728]
There is a common pattern in functions designed to read/parse various fileformats to use `G.add_node(n, **attrs)` or `G.add_edge(u, v, **attrs)`. Usually `**attrs` is a dictionary with properties of currently processed node/edge. Unfortunately this approach breaks when node/edge has an `'n'` or `'v'` attribute. Here is a minimal example:

    #!/usr/bin/env python
    import networkx as nx

    d = {'nodes': [{'id': 0, 'n': 'foo'}], 'links': []}
    G = nx.node_link_graph(d)

This leads to:

    TypeError: add_node() got multiple values for keyword argument 'n'

I've experimented with some parsing functions and this issue show up in `read_shp`, `node_link_graph`, `read_multiline_adjlist` and probaby some other file-reading functions.
As `n`, `v` or `u` attributes are quite possible in real world data therefore I think this issue can cause some troubles to users. What is your opinion on this?

**Comment by hagberg** [comment]
It's a known issue that has come up in other parts of networkx #1582.
So far we have only made a few changes to address the name clashes.  There is really no great solution since you either have to pick "obscure" keyword argument names or live with potential clashes.

**Comment by mddddd** [comment]
I see. Maybe adding a new method called `add_edge_dict(self, u, v, attr)` would be a solution (where `attr` is simply a dict)? This would give users a choice: to use an user friendly `add_edge(self, u, v, **attr)` or more robust `add_edge_dict(self, u, v, attr)` method.

**Comment by dschult** [comment]
If the edge already exists, then use ```G.edges[u,v].update(attr)```
If not and you need to avoid attribute names ```self```, ```u``` and ```v```, then

    G.add_edge(u,v)
    G.edges[u, v].update(attr)

**Comment by mddddd** [comment]
Thanks for clarifying this. 
I think that this info in docstring in `class Graph` is therefore outdated? (line 148 in graph.py):
```
    Warning: we protect the graph data structure by making `G.edges[1, 2]` a
    read-only dict-like structure. Use 2 sets of brackets to add/change
    data attributes. (For multigraphs: `MG.edges[u, v, key][name] = value`).
```

**Comment by dschult** [comment]
Ahh...   Yes, that should at least be reworded, if not removed.  That refers to the fact that ```G.edges[u,v]={'foo':'bar'}``` is not allowed.  You can't assign to ```G.edges[1, 2]```.  But you can change and update the dict that it represents.

**Comment by mddddd** [comment]
Thank you all for explanation.
