### ISSUE TITLE
len(G.edges) unexpected values

### ISSUE THREAD

**Issue by jwerts** [networkx/networkx#2734]
I'm not sure if this is a bug or expected behavior but it's at least confusing.  This is using 2.0 nx.Graph() - I would provide the data to recreate, but it's private and I'm not sure why this is occurring, which might just be my lack of knowledge
```
>>> len(G.edges())
300
>>> G.number_of_edges()
312
>>> count = 0
>>> s = set()
>>> for edge in G.edges():
...     seen = edge in s or (edge[1], edge[0]) in s
...     if not seen:
...         count += 1
...     s.add(edge)
>>> count
312
```
What would be likely reasons that len() would give a different answer than number_of_edges()?  I thought it was because of reversed edges, but that doesn't seem to be the case either.

**Comment by dschult** [comment]
This looks like a bug.  Thanks for the report!
I believe the cause is selfloops.  It looks like ```len(G.edges)``` does not count selfloops.

Short term fix is to use ```G.size()``` or ```G.number_of_edges()``` but tweak the following in more complex situations:

    sum(len(nbrs)+(n in nbrs) for n, nbrs in G.adj.items()) // 2

or

    sum(1 for e in G.edges)

**Comment by jwerts** [comment]
I do have self loops in the data, so that is likely the case.  Thanks!
