### ISSUE TITLE
Calculating hitting time, commute time : NetworkX snippet

### ISSUE THREAD

**Issue by srikanthBezawada** [networkx/networkx#2737]
```
def findBoundedHittingTime(G, node1, node2, limit):
    currentnode = node1
    steps = 0

    while(currentnode != node2) :
        if(steps > limit):
            return -1
        currentnode = random.choice(list(G[currentnode].keys()))
        steps = steps + 1

    return steps
```

I performed the random walk to find the hitting time as shown in the snippet above. 
But looks like the hitting time is actually defined as the _expected_ number of steps from nodeA to nodeB  and is calculated using probability distribution/linear algebra/laplacian (_[1]_). Is there a snippet already available which does the same.. Please let me know and correct me if I'm wrong anywhere. 

Thanks in advance!

[1] - (I'm currently going through the theory behind it)  http://be.amazd.com/link-prediction/

![hittingtime](https://user-images.githubusercontent.com/7630967/32417128-2a15ee9e-c26e-11e7-8c53-41f5ad226e24.PNG)

**Comment by harryscholes** [comment]
The commute time (CT) between nodes *i* and *j* in some graph *G* is defined as:

CT*ij* = H*ij* + H*ji*

where H is the hitting time you outline above. The expected CTs between all pairs of nodes in *G* can be obtained without directly calculating the random walks. The pseudoinverse of the Laplacian matrix results in a kernel, whose entries correspond to the pairwise dot products of node vectors in a Euclidean space where nodes are exactly separated by their expected CTs. This kernel can be obtained by:

```python
import networkx as nx, numpy as np

G = nx.erdos_renyi_graph(20, 0.3)
L = nx.laplacian_matrix(G, nodelist=sorted(G.nodes)).toarray().astype(float)
CTK = np.linalg.pinv(L)
```
For more information I recommend reading papers by Francois Fouss where he derives and explains the properties of this kernel:

http://www.sciencedirect.com/science/article/pii/S0893608012000822
http://ieeexplore.ieee.org/document/4053117/

**Comment by srikanthBezawada** [comment]
Thanks for your response @harryscholes , I'm going through the reference.
It feels magic to me everytime how linear algebra and graphs are connected.
