### ISSUE TITLE
ShortestPath-Algorithm ignores weight-attributes with MultiDiGraph

### ISSUE THREAD

**Issue by Birdy3000** [networkx/networkx#2738]
import networkx
graph = networkx.MultiDiGraph()
graph.add_nodes_from(range(1,2))
graph.add_edge(1,2,key=0,attr_dict={"time":5})
print networkx.shortest_path_length(graph, 1, 2, weight="time")

Test with Networkx 2.0
should return 5, but returns 1 because it ignores the weight="time" attribute
When will this be resolved?

**Comment by hagberg** [comment]
The `attr_dict` argument is no longer use.  Use keywords for networkx-2.0 instead `graph.add_edge(1,2,key=0,time=5)`

```python
In [13]: import networkx
    ...: graph = networkx.MultiDiGraph()
    ...: graph.add_nodes_from(range(1,2))
    ...: graph.add_edge(1,2,key=0,time=5)
    ...: print(networkx.shortest_path_length(graph, 1, 2, weight="time"))
    ...: 
5
```
