### ISSUE TITLE
Possible syntax error in gml.py (readwrite)

### ISSUE THREAD

**Issue by Tleysens** [networkx/networkx#2740]
https://github.com/networkx/networkx/blob/e3566e53793cdccc19a8c2ff9c056e0d7b524634/networkx/readwrite/gml.py#L680

I've got an error when I want to write a .gml file from a network using the write_gml() function. At line 680 there is "test" instead of "text" I think.

**Comment by hagberg** [comment]
Yep, that is a bug.  Thanks for the report.   This is a simple fix.

**Comment by Tleysens** [comment]
You're welcome. 
By the way, very great and useful functions !
