### ISSUE TITLE
(Digraph) object has no attribute '_adj'

### ISSUE THREAD

**Issue by stablum** [networkx/networkx#2741]
While trying `copy.deepcopy` of a graph, I am encountering the following exception:
```
File "/home/francesco/.local/lib/python3.6/site-packages/networkx/classes/reportviews.py", line 894, in __setstate__
    self._adjdict = G._succ if hasattr(G, "succ") else G._adj
AttributeError: 'TrackGraph' object has no attribute '_adj'
```

where TrackGraph is a subclass of DiGraph:
```
class TrackGraph(nx.DiGraph):
    ...
```

Version is the following:

```
>>> nx.__version__
'2.0'
```
Any idea on how to fix it?

**Comment by dschult** [comment]
I think we need a little more info about TrackGraph. Does the same thing happen with DiGraph?
Ideally, you could construct a short example that recreates the problem. Based on what you report above ny first thought is that maybe TrackGraph doesn't call ```DiGraph.__init__``` in its ```__init__``` method.

**Comment by dschult** [comment]
Reopen this if you can provide more info.

**Comment by stablum** [comment]
I think this might be reopened. 
My hypothesis is that the order in which the unplicking of the attributes happens is relevant.
Apparently one of these attributes is an OutEdgeView.  I cannot see which attribute because python's pickle is notoriously uninformative during debugging.

Anyways, I think that that attribute is being set (and hence `__setstate__` triggered) before `_adj` or other attributes are set. In that case the `OutEdgeView.__setstate__` is faced with an almost empty object, without `_adj`.

Opinions?
