### ISSUE TITLE
How to build graph with C or C++ Interfaces?

### ISSUE THREAD

**Issue by Samurais** [networkx/networkx#2747]
hi, 

I am a new bee, I notice networkx has implemented with C, C++ codes.  I have a large dataset, once build it as graph with networkx, it is slower then dict object for accessing the elements. 
```
an interface to existing numerical algorithms and code written in C, C++, and FORTRAN; and
```

networkx is install with pip. So, how to leverage the C, C++ codes. I guess networkx can be compile with cython to get C Interfaces enabled, is that true?

**Comment by hagberg** [comment]
NetworkX is a pure-python library.  It does take advantage of other libraries for algorithms (though not for data structures) for calculations such as dense and sparse matrix algebra.    There is no "C interface" to the NetworkX library but the other way around - interfaces to existing C libraries which are typically provided by other Python packages.
