### ISSUE TITLE
Attributes with whitespace not quoted when generating DOT representation

### ISSUE THREAD

**Issue by Cerebus** [networkx/networkx#2749]
DOT attributes are defined as follows:

> attr_list | : | '[' [ a_list ] ']' [ attr_list ]
> a_list | : | ID '=' ID [ (';' \| ',') ] [ a_list ]
> An ID is one of the following:
>   Any string of alphabetic ([a-zA-Z\200-\377]) characters, underscores ('_') or digits ([0-9]), not beginning with a digit;
>   a numeral [-]?(.[0-9]+ | [0-9]+(.[0-9]*)? );
>   any double-quoted string ("...") possibly containing escaped quotes ('")1;
>   an HTML string (<...>).

When an attribute name contains whitespace, NetworkX does not quote the string; e.g. the following is emitted from nx.drawing.nx_pydot.write_dot():

> strict graph  {
> n0 [Node Label="A", label="9.0"];
> }

**Comment by hagberg** [comment]
You are right.  NetworkX does not add quotes in that case. If you want a double quoted string you could make one.  I'm not sure if this is a bug or a not?

```python
import networkx as nx
G = nx.Graph()
G.add_node('n0',label=9.0)
G.node['n0']['\"Node Label\"']='A'
import sys
nx.drawing.nx_pydot.write_dot(G,sys.stdout)```

```
$ python foo.py
strict graph  {
n0 [label="9.0", "Node Label"=A];
}```

**Comment by Cerebus** [comment]
It's a bug.  The DOT spec is clear that spaces are not allowed in IDs unless inside text double quotes or an HTML tag.  NX doesn't produce conforming output.

**Comment by hagberg** [comment]
Yes, right.  Definitely needs a double-quoted string.  But is this a user bug (user didn't provide a double quoted string) or a bug in write_dot (not automatically adding double quotes to an ID with  whitespace)?   This might apply to other cases to - e.g. we don't automatically check if you have written a XML string and automatically add <>.
