### ISSUE TITLE
Installation Error on OSX EI Capitan

### ISSUE THREAD

**Issue by zjpjack** [networkx/networkx#2752]
Hello,

When I installed networkx using "sudo pip install networkx", it always has the following error in the last.

Although I can still import networkx, just would like to figure it out.

Thanks

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-build-Zp_QXW/networkx/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-GeskfW-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/tmp/pip-build-Zp_QXW/networkx/

**Comment by dschult** [comment]
Take a look at:   https://stackoverflow.com/questions/35991403/python-pip-install-gives-command-python-setup-py-egg-info-failed-with-error-c

Reopen this if that doesn't solve the issue.

**Comment by ericmjl** [comment]
@zpjack I noticed you're using system python on a Mac. If it's possible, do consider giving the Anaconda Python distribution a shot - at that point, NetworkX will be a simple `condo install networkx` away.

**Comment by zjpjack** [comment]
@ericmjl thanks, I used conda to install it successfully

**Comment by zjpjack** [comment]
@dschult That link doesn't solve my problem, but I use conda to install it successfully.
