### ISSUE TITLE
[QUESTION] Straightness Centrality

### ISSUE THREAD

**Issue by gabrielspadon** [networkx/networkx#2755]
I'm wondering to know if is there any intention to implement Latora's Straightness Centrality in NetworkX library?

> Crucitti, P., Latora, V. and Porta, S., 2006. Centrality in networks of urban streets. Chaos: an interdisciplinary journal of nonlinear science, 16(1), p.015113.

**Comment by hagberg** [comment]
There are currently no open issues to add this.  Would you be interested in contributing the algorithm?

**Comment by gabrielspadon** [comment]
Absolutely! How can I help?

**Comment by gabrielspadon** [comment]
Thank you! I will reach you as soon as it is ready.
