### ISSUE TITLE
Pydot vs Agraph `write_dot` inconsistencies

### ISSUE THREAD

**Issue by mayanez** [networkx/networkx#2756]
Behavior between the generated `.dot` file between `agraph` and `pydot` drawing is inconsistent. `agraph` is what I would expect the dot file to look like. Below is the code to reproduce the issue.

Code:
```
import networkx as nx
import networkx.drawing.nx_pydot as pd
import networkx.drawing.nx_agraph as ag

g = nx.DiGraph([(0,1),(1,2)])
pd.write_dot(g, 'pd.dot')
ag.write_dot(g, 'ag.dot')
```

ag.dot
```
strict digraph "" {
        0 -> 1;
        1 -> 2;
}
```

pd.dot
```
strict digraph  {
0;
1;
2;
0 -> 1;
1 -> 2;
}
```

**Comment by hagberg** [comment]
Thanks for the report.   The pygraphviz/agraph interface uses the graphviz libraries directly (with python wrappers) and pydot is a pure-python implementation of the dot format data and output.  Fortunately those graphs are both isomorphic.  Unfortunately the text is different.  

It may be possible to adjust this in the pydot package - you might consider asking there.

Aric
