### ISSUE TITLE
Improvement to arrowheads of a DiGraph edges.

### ISSUE THREAD

**Issue by rodogi** [networkx/networkx#2757]
I was wondering if there was  planing on changing the arrowheads of the edges of directed graphs to be more arrow like (triangular shape instead of thicker line). For instance see [this question](https://stackoverflow.com/questions/47213650/changing-arrowhead-type-in-networkx) on stackoverflow.

**Comment by hagberg** [comment]
That would be a great addition the the networkx/matplotlib drawing package.  It is technically possible but so far there have been no contributions that solve the general arrow drawing problem.

**Comment by flying-sheep** [comment]
> so far there have been no contributions that solve the general arrow drawing problem.

that’s incorrect, except if you mean something different with that: https://groups.google.com/d/msg/networkx-discuss/uV_amBP65n0/7nVubHNyBNMJ

**Comment by hagberg** [comment]
See #2760
