### ISSUE TITLE
Subgraph isomorphism with GraphMatcher

### ISSUE THREAD

**Issue by danmarsh** [networkx/networkx#2758]
Hi, I'm testing for subgraphs in small graphs.  I'm unclear why this code only returns False.  I tested it in another library and it returned True for one of the cases.

import networkx as nx

G = nx.Graph()
H = nx.Graph()

G.add_edges_from([[1,2], [2, 3]])
H.add_edges_from([[1,2], [2, 3], [3, 1]])

matcher = nx.algorithms.isomorphism.GraphMatcher(G, H)
print matcher.subgraph_is_isomorphic()

matcher = nx.algorithms.isomorphism.GraphMatcher(H, G)
print matcher.subgraph_is_isomorphic()

**Comment by hagberg** [comment]
It's correct for the definition of subgraph isomorphism that NetworkX uses in this case.   My understanding is that the terminology is fairly confusing - the NetworkX VF2 algorithm is for node-induced subgraphs so in your case the node-induced subgraph on nodes [1,2,3] will always contain the edge (1,3) for H.

There is discussion of this in the networkx documentation at https://networkx.github.io/documentation/stable/reference/algorithms/isomorphism.vf2.html#subgraph-isomorphism

There is some further discussion on the terminology differences in SO at https://stackoverflow.com/questions/459799/whats-the-difference-between-subgraph-isomorphism-and-subgraph-monomorphism
