### ISSUE TITLE
node-mapping bug expected_degree_graph

### ISSUE THREAD

**Issue by lushl9301** [networkx/networkx#2767]
Hi I used the NX1 expected_degree_graph generator. It has the same interface as the NX2.

https://networkx.github.io/documentation/stable/reference/generated/networkx.generators.degree_seq.expected_degree_graph.html#networkx.generators.degree_seq.expected_degree_graph

But NX2 will not generate the graph correctly. The total number of edge is always 1. No further error message provided. 
Same script works well for NX1. (I downgrade to older version.

```python
D = 10
N = 1000
degree_l = [D for i in range(N)]
G = nx.expected_degree_graph(degree_l, seed=datetime.now(), selfloops=False)
```

**Comment by dschult** [comment]
That is certainly a bug -- Thanks for the report!

I think it was introduced two years ago in an attempt to make it more simple... but a typo snuck into the mapping on line 429:  ```mapping = {c: v for c, (u, v) in enumerate(order)}```   should be ```mapping = {c: u for c, (u, v) in enumerate(order)}```   Looks like we will need more tests (I haven't looked at them yet).

**Comment by hagberg** [comment]
Yep, that looks like the right fix.
