### ISSUE TITLE
connected_component_subgraphs generator slow in v2.0

### ISSUE THREAD

**Issue by yuracpp** [networkx/networkx#2772]
hi

iteration over connected_component_subgraphs result generator is slow for attached graph comparably with 1.11 version (tested on Anaconda2/3 Win64/Linux64 1.11v take few seconds, v2.0 takes few hours)

thank you

[test.zip](https://github.com/networkx/networkx/files/1503157/test.zip)

**Comment by dschult** [comment]
Fixed in #2743 and #2744 
You can get it from github, or wait for v2.1 which should be coming fairly soon.
