### ISSUE TITLE
Variable name conflict in MultiDiGraph.add_node()

### ISSUE THREAD

**Issue by TK-21st** [networkx/networkx#2786]
I am using `networkx 2.0` from `pip` with `python3.6`

I have encountered a naming conflict between my node attribute `n` and the argument `n` of  `MutliDiGraph.add_node(n,**attr)`. 

Trace of the error when invoking `networkx.read_gexf()` is as follows:
``` 
~/.../networkx/readwrite/gexf.py in add_node(self, G, node_xml, node_attr, node_pid)
    740                 self.add_node(G, node_xml, node_attr, node_pid=node_id)
    741 
--> 742         G.add_node(node_id, **data)
    743 
    744     def add_start_end(self, data, xml):

TypeError: add_node() got multiple values for argument 'n'
```

This seems to be an unfortunate side-effect of `python3`'s convention of making positional arguments addressable as keyword arguments. 

Any idea how I could get around this? Or if there would be a need of re-naming either the argument or my node attributes? For the work that I am doing, I use `n` attribute a lot 😢

**Comment by dschult** [comment]
There is an issue #1583  related to reducing this kind of problem in our codebase. 
But a short term fix is:

    G.add_node(node_id)
    G.nodes[node_id].update(data)
