### ISSUE TITLE
TypeError: iter() returned non-iterator of type 'Layer' for Python 3

### ISSUE THREAD

**Issue by Asterrea** [networkx/networkx#2789]
Why does TypeError gets raised in Python 3 when in fact the same code being run in Python 2 gets executed with no errors?

**Code**
```
net = nx.DiGraph()
print(path)
shp = ogr.Open(path)
for lyr in shp:
    print (type(lyr))
    print (lyr)
    fields = [x.GetName() for x in lyr.schema]
    print (lyr.schema)
    print(fields)
    for f in lyr:
         print(f)
```

**Error**

> File "/home/gridlockdev/Desktop/heroku/grace/env/lib/python3.5/site-packages/networkx/readwrite/nx_shp.py", line 81, in read_shp for f in lyr: TypeError: iter() returned non-iterator of type 'Layer'

Posted another question regarding `read_shp` which seems to be all correlated to Python 3 bug? : [NetworkX read_shp works on Python 2.7 but not on Python 3?](https://gis.stackexchange.com/questions/264676/networkx-read-shp-works-on-python-2-7-but-not-on-python-3)

**Comment by dschult** [comment]
Can you check your example code? It doesn't actually use read_shp anywhere.
Your stackexchange post suggests that you are using Python3.0. NetworkX requires 3.4 or later. Can you try with 3.6?
It will be hard to recreate your error to investigate it without a simple shp file that causes that error. Our tests are working for python 3.4-3.6, but they are not very extensive.
