### ISSUE TITLE
ImportError decorator with Networkx 2.0 Python 3.6

### ISSUE THREAD

**Issue by pierluigi-failla** [networkx/networkx#2791]
I was trying the basic:

```
import networkx

def main():
   pass

if __name__ == '__main__':
    main()
```

and I got `ImportError: cannot import name 'decorator'` 

Did I miss something?

Here is the stacktrace:

```
Traceback (most recent call last):
  File "[...]\main.py", line 3, in <module>
    import networkx
  File "[...]\Anaconda\envs\my_env\lib\site-packages\networkx\__init__.py", line 98, in <module>
    import networkx.utils
  File "[...]\Anaconda\envs\my_env\lib\site-packages\networkx\utils\__init__.py", line 2, in <module>
    from networkx.utils.decorators import *
  File "[...]\Anaconda\envs\my_env\lib\site-packages\networkx\utils\decorators.py", line 7, in <module>
    from decorator import decorator
ImportError: cannot import name 'decorator'
```

My current set up is `Python 3.6.3` with `Networkx 2.0`.

**Comment by dschult** [comment]
It needs the decorator package. That is our only "hard" requirement. (meaning NumPy and SciPy are nice but not necessary. ```decorator``` is necessary). 

Most installing systems (pip, conda, etc) will install it when you install NetworkX, but if you install from github or from source, you will need to install the decorator package as well.  Look for version 4.1 or later.

**Comment by pierluigi-failla** [comment]
Yep, indeed, also `decorator==4.1.2` it is installed, but I think that the issue is on PyCharm side, because trying to manually run the above code in the same virtual env does not produce any issue. Definitely not an issue on `networkx` side.
