### ISSUE TITLE
support for multimodal networks and cross edges

### ISSUE THREAD

**Issue by kanihal** [networkx/networkx#2797]
Let's say I have a biological dataset containing genes, diseases and drugs which form node groups(also called modes) of different types.
Disease-disease interactions, disease-gene interactions and gene-drug interactions form cross edges between these edge groups.

SNAP has support for this kind of networks - https://snap.stanford.edu/snappy/doc/reference/multimodal.html

How would I do the same thing in NetworkX? If it's already not there It would be nice add support for this kind of networks.

**Comment by jfinkels** [comment]
I'm not familiar with "multimodal" networks, but you can set a node attribute to indicate which type of node it is; see https://networkx.github.io/documentation/latest/reference/classes/generated/networkx.Graph.add_node.html#networkx.Graph.add_node. For example,

```python
import networkx as nx
G = nx.Graph()
G.add_node(0, mode='gene')
G.add_node(1, mode='drug')
```
Any edge in which the endpoints are of a different "mode" are "cross" edges. Is that what you're looking for?

**Comment by kanihal** [comment]
yes, I think using node attributes and edge attributes also would yield the same effect. Thanks.

**Comment by dschult** [comment]
The SubGraph view objects can provide a way to specify which types of nodes/edges to include in a subgraph. So, with a full set of info stored on a ```MultiDiGraph``` with node attributes for mode and edge attributes for crossnet ('dis-dis', 'dis-g', 'g-drug') you could access the network of 'dis-dis' edges using:

    G = MultiDiGraph()
    ... add nodes and edges
    def disdis_edges(u, v, k):
        return G[u][v][k]['crossnet'] == 'dis-dis'
    disdis = SubMultiDiGraph(G, show_edges=disdis_edges)
    print(disdis.edges)

This is a relatively new feature and isn't particularly well documented, but I think it is closely related to what you are looking for.
