### ISSUE TITLE
Trivial issue with neighbors

### ISSUE THREAD

**Issue by ggrrll** [networkx/networkx#2802]
Hi,

thanks for the nice module.

I am having however a basic issue (maybe related to the latest update? - 2.0) with degree and neighbours - or maybe I am doing something trivially wrong - please, see the screenshot

Thanks for your help

(I am on python 3.6 - networkx 2.0)

<img width="1085" alt="screen shot 2017-12-18 at 19 15 19" src="https://user-images.githubusercontent.com/15370425/34121051-0d2f3e12-e428-11e7-8ab1-b2f9c1ee52c9.png">

**Comment by dschult** [comment]
The degree of a node is not necessarily the number of neighbors. If you have self-loops for example, the results you show would occur.

**Comment by ggrrll** [comment]
Thanks @dschult  true indeed...then there must be a bug in my code - simply didn't plan to have self-loops
