### ISSUE TITLE
Numpy array printing changes causing test failures

### ISSUE THREAD

**Issue by hagberg** [networkx/networkx#2806]
Here is the info on the changes to the Numpy array printer format.  This change is showing up as errors in the Travis builds for 2.7 pip='--pre'.

https://github.com/numpy/numpy/blob/master/doc/release/1.14.0-notes.rst#many-changes-to-array-printing-disableable-with-the-new-legacy-printing-mode

The errors are in the doctests for `convert_matrix.py` and `attrmatrix.py`

**Comment by dschult** [comment]
Is there a way to ```set_printoptions``` when we run the nosetests doctests?
But still have it not set for general use...   I guess for now we can just load legacy mode always, but it seems better to use the new functionality when we can.

**Comment by dschult** [comment]
Fixed by #2810 but popped up again in the sphinx doctest code a week later.
