### ISSUE TITLE
Community detection algorithms

### ISSUE THREAD

**Issue by zjpjack** [networkx/networkx#2808]
Hi,

Just wonder if there is any community detection algorithms such as Louvain algorithm and Infomap algorithm.

If there is no merged version for them, I can implement them.

Thanks

**Comment by dschult** [comment]
Check out #1090 and #1092 for previous attempts at Louvain.
Please help us out with this if you can.

**Comment by vlado-s** [comment]
Hi,
Now I'm using the NetworkX implementation of the Louvain community detection algorithms. I'm not 100% sure about the interpretation of the edge weights in this algorithm. In NetworkX the general assumption is that weight is made equal to node distance, i.e. larger weight = larger distance / weaker connection. Right?
I contacted Renaud Lambiotte (co-author of the Louvain code) about this. He ensured me that in their code the interpretation of weight is reversed. To quote: "... I can tell you is that our C++ code deals with weights as a notion of “importance” of a link. Stronger links hence imply stronger connections."
So my question is - how should I use weights in the NetworkX implementation?
Thank you.

**Comment by dschult** [comment]
For the PRs referred to above, a larger weight is not more distant. Larger weight means closer -- see the reference (Blondel) paper.

I don't think you need to convert your weights.  But if you ever do, new_weight = 1/old_weight
if a standard way to convert.  

I'm going to close this issue in favor of #1090 and #1092
