### ISSUE TITLE
duplicate edge IDs when exporting to GraphML

### ISSUE THREAD

**Issue by stiebels** [networkx/networkx#2827]
Hello,

I used the following code to create the graph from a list of tuples [(start, end)] and export it to graphml:

```
import networkx as nx
g = nx.MultiDiGraph()
dir_edges = reduce(lambda x, y: x + y, map(list, self._walked_path.values())) # list of tuples
g.add_edges_from(dir_edges)
pos = nx.spring_layout(g)
nx.draw_networkx_nodes(g, pos, node_size=75)
nx.draw_networkx_edges(g, pos, arrows=True)
```

When yEd showed me all the nodes but no edges, I looked into the graphml file and saw the following:

```
<?xml version='1.0' encoding='utf-8'?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd"><graph edgedefault="directed">
<node id="1node"/>
<node id="2node"/>
<node id="3node"/>
<node id="4node"/>
<edge id="0" source="1node" target="2node"/>
<edge id="0" source="1node" target="3node"/>
<edge id="0" source="3node" target="4node"/>
<edge id="0" source="1node" target="4node"/>
</graph></graphml>
```

After changing the IDs to unique values, yEd displayed the graph perfectly fine. Is there some issue with the generation or am I overlooking something?
Also, yEd does not seem to be able to extract node IDs as nodes remain unnamed.

Python3.6
Ubuntu 17.10
networkx2.0

**Comment by dschult** [comment]
Can you show us the Graph g and the code used to produce the graphml file?

    print(g.nodes)
    print(g.edges(data=True))
    # whatever write_graphml code you used

**Comment by stiebels** [comment]
```
print(g.nodes)
['1node', '2node', '3node', '4node']
print(g.edges(data=True))
[('1node', '2node', {}), ('1node', '3node', {}), ('1node', '4node', {}), ('3node', '4node', {})]
```
Code used to generate the graphml file:
```
nx.write_graphml(g, path='/home/usr/graph.graphml')
```

**Comment by dschult** [comment]
Thanks for that. It looks to me like you will need to include data attributes for the edges (and the nodes). The edge keys used by default in NetworkX are integers starting at 0 for each edge pair.  Those edge keys are what gets used in the "id" field in write_graphml. I'm not sure what the node name field is for yEd but if it is "name", then you will need to create a node data attribute called "name" for each node.

    # not tested
    G=nx.MultiDiGraph()
    for n in range(4):
        nodename = "{}node}.format(n + 1)
        G.add_node(nodename, name=nodename)
    dir_edges = reduce(lambda x, y: x + y, map(list, self._walked_path.values())) # list of tuples
    G.add_edges_from((x, y, id) for id,(x,y) in enumerate(dir_edges))

**Comment by stiebels** [comment]
Thanks a lot! Indeed, for yEd you need to specify edge ID explicitly as attribute in the graph. For other attributes, the property mapper can be used to actually make them show up in yEd.
