### ISSUE TITLE
dfs_edges does not correctly traverse directed multi graph?

### ISSUE THREAD

**Issue by gabrielStanovsky** [networkx/networkx#2840]
Somewhat related to #2792, I expected ```dfs_edges``` to return all edges in a connected component. 
However, this doesn't seem to be the case:

```python
import networkx as nx
g = nx.MultiDiGraph()
g.add_node(1)
g.add_node(2)
g.add_node(3)
g.add_edge(1, 2, label = 'A')
g.add_edge(1, 2, label = 'B') # Another edge between 1, 2
g.add_edge(1, 3, label = 'C')
print(g.edges()) # [(1, 2), (1, 2), (1, 3)] -- Three edges overall, two between nodes 1, 2 
print(list(nx.dfs_edges(g))) # [(1, 2), (1, 3)] -- Only two edges. Also, unclear which of the edges between 1, 2 is chosen.
```
Is there anything I'm missing here? Should I use some other function?
If not, I'll probably implement something for my application, and I'll be happy to PR if there's interest.

Thanks!

**Comment by dschult** [comment]
Does ```edge_dfs``` do what you want?  (i.e. is our naming scheme in need of revamping?)

    >>> print(list(nx.edge_dfs(g)))
    [(1, 2, 0), (1, 2, 1), (1, 3, 0)]

**Comment by gabrielStanovsky** [comment]
Yes, this looks like what I need. 
Thank you very much!

I wasn't aware of ```edge_dfs```, and I guess the naming can be a bit confusing  :)
