### ISSUE TITLE
Typo in comment of asyn_fluidc algorithm

### ISSUE THREAD

**Issue by camontanezp** [networkx/networkx#2845]
In the code says

if len(G) < k:
        raise NetworkXError("k must be greater than graph size.")

But I understand that it should say "k must be smaller than or equal to the graph size".

[code](https://networkx.github.io/documentation/stable/_modules/networkx/algorithms/community/asyn_fluidc.html#asyn_fluidc)

**Comment by dschult** [comment]
Looks like some other typos in there too -- like "muts" instead of "must"
