### ISSUE TITLE
why the nx.all_neighbors(G,node)return<dictionary-keyiterator object at 0x000000001432D818>

### ISSUE THREAD

**Issue by chordlee** [networkx/networkx#2851]
![image](https://user-images.githubusercontent.com/32956671/35479074-9c9a1124-0428-11e8-96b7-175852f2731f.png)
![image](https://user-images.githubusercontent.com/32956671/35479077-aa8a7e22-0428-11e8-9cc9-42a4124a664c.png)
it's the screenshots
the version:python 2.7 ; networkx 2.1
i'm a beginner for nx. I want to get the neighbors of one node,so I read the pdf. but the method dosen't work. I don't know why ,thank you!
Is there other method can achieve that too?

**Comment by dschult** [comment]
The [documentation for all_neighbors](https://networkx.github.io/documentation/stable/reference/generated/networkx.classes.function.all_neighbors.html) states that the return value is an iterator over the neighbor nodes. That is what you see when you print it: a ```dictionary-keyiterator```.  To get a list (if that's what you want) use ```print node, list(neigh)```.

But you probably should work through the tutorial (available from the sidebar of the documentation). There are other ways to get the neighbors of a node that are better in many cases.  ```G[node]``` returns a dict keyed by neighbors with values being the edge attribute dicts. So, ```list(G[node])``` is a list of neighbors.
