### ISSUE TITLE
Parsing bug in  `read_weighted_edgelist`

### ISSUE THREAD

**Issue by lewisrobbins** [networkx/networkx#2856]
Code to recreate the issue:

```python
def make_network():

    G = nx.Graph()
    rows = range(ROWS)
    columns = range(COLUMNS)

    #https://networkx.github.io/documentation/networkx-1.10/_modules/networkx/generators/classic.html#grid_graph
    G.add_nodes_from( ((i,j) for i in rows for j in columns))
    G.add_edges_from( ((i,j),(i-1,j)) for i in rows for j in columns if i>0 )
    G.add_edges_from( ((i,j),(i,j-1)) for i in rows for j in columns if j>0 )   
    
    print(G.edges())

    pos = {n:n for n in G.nodes()}

    print("The network is size: {}x{}".format(max(rows)+1, max(columns)+1))
    nx.draw(G, pos, **options)
    plt.show()
    
    # Now to make the graph easier to serialise (consecutive)
    sG = nx.convert_node_labels_to_integers(G)
    print(sG.edges())
    
    #Now add resistances to edges
    for edge in sG.edges():
        sG[edge[0]][edge[1]]['weight'] = 1 # for 1 Ohm, so apparently has to be 'weight' to save to a file :(
    nx.write_weighted_edgelist(sG, NAME)
```

Then to parse:

```python
try:
        DG = nx.read_weighted_edgelist(NAME)  # parsing edge list with weights to create graph
    except IOError:
        raise FileNotFoundError("Could not find Graph with name {}".format(name_of_file))

    G = nx.convert_node_labels_to_integers(DG)
```

If we print the edges using: print(G.edges()) in the parse function just above we get:
`[(0, 1), (0, 2), **(1, 4),** (1, 3), (2, 3), (3, 5), (4, 5)]`

but if we print the file saved on disk we get:

```bash
$ cat notebooks/network.txt 
0 2
0 1
1 3
**2 4**
2 3
3 5
4 5
```
There is a bug. The edge (1,4) should actually be (2,4). This seems to occur in bigger network sizes too. The smallest networks size I can recreate this bug with is 3X2.

I'm not doing anything stupid am I? :(

**Comment by dschult** [comment]
There is nothing to guarantee that the relabeling of nodes to integers will give the same integers for two (even identical) graphs. You can use some of the optional ```ordering``` arguments to [relabel_node_labels_to_integers](https://networkx.github.io/documentation/latest/reference/generated/networkx.relabel.convert_node_labels_to_integers.html) to try to get the same ordering.  
But I wonder: do you need to relabel the nodes in the parsing code?

**Comment by lewisrobbins** [comment]
@dschult But even if you get different labels the edge is still wrong. If all the edges still had different labels for the node the Graph should still be the same, but it's not. 

When I draw the graph the edge is in the wrong place.

**Comment by lewisrobbins** [comment]
Actually I think I understand now. There is no guarantee the relabelling of nodes will be in sequential order. I need the nodes to be in sequential order so I can position each node in a lattice/grid/matrix.

**Comment by dschult** [comment]
If you've got sortable nodes (which you do) use the ```ordering``` keyword as mentioned above.

**Comment by lewisrobbins** [comment]
@dschult Yep figured it out, cheers. I'm gonna submit a pull request so the documentation is clear about this :)
