### ISSUE TITLE
Confusing doc of networkx.Graph.copy : deep copy or shallow copy?

### ISSUE THREAD

**Issue by xuhdev** [networkx/networkx#2859]
The [doc](https://networkx.github.io/documentation/stable/reference/classes/generated/networkx.Graph.copy.html) reads as follows:

> The copy method by default returns a shallow copy of the graph and attributes. That is, if an attribute is a container, that container is shared by the original an the copy. 

but later on, it reads

> Deepcopy – The default behavior is a “deepcopy” where the graph structure as well as all data attributes and any objects they might contain are copied.

Is this a deep copy or shallow copy?

**Comment by dschult** [comment]
Fixed in #3024
