### ISSUE TITLE
Eulerization of a Graph

### ISSUE THREAD

**Issue by msramalho** [networkx/networkx#2869]
# Eulerization of a Graph
What I propose is that the **Euler** functionality be expanded to handle the transformation of a non-euler graph into one, with as little additions and removals as possible. This would be useful because many programs need such features and it would be a disruptive feature. 

[File to update](https://github.com/networkx/networkx/blob/master/networkx/algorithms/euler.py)

I would like to do it, but I don't know wether I'll have enough time.

[Instructions](http://www.math.unl.edu/~bharbourne1/M203Spr07/EulerizationHandout.pdf)

**Comment by dschult** [comment]
Maybe this would be best to implement as its own function rather than an extension of the existing euler functionality. This might be a reasonable project for someone looking to contribute.

**Comment by mtrenfield** [comment]
I am willing to work on this.  This would be my first PR for NetworkX and only my second on Github, so I may need a bit of guidance.

Three questions:

1. Should the graph be Eulerized in place by default?
2. Does it make sense to Eulerize weighted graphs?  I can think of a few reasonable ways one might re-assign weights to new edges, but nothing unique.  Should the function throw an exception or raise a warning if the edges are weighted?
3. Where should I look to get a sense of what tests I should write for the function and where should the tests go?

**Comment by dschult** [comment]
I think you should put the code in ```networkx/algorithms/euler.py``` with the tests in ```networkx/algorithms/tests/test_euler.py```.  Take a look at what is in there to see how it is set up. Also read the NetworkX github Wiki to general style ideas. 

Read the links from the original poster.  Also search for "eulerization of a graph" or similar and read what those pages say about how to do this.

It looks like you will need to create a MultiGraph to be able to handle duplicate edges. I think you should ignore edge weights altogether unless you can find a reference that uses them. The tests should be unittests -- that is, tests of specific features and/or aspects of the code. The idea is that they should flag us if we change something that breaks your code. -- one way to do this is to check that the answers are right in some important specific cases. :)  vague enough?

Put your name with the authors at the top and if you want in the ```CONTRIBUTORS.rst``` file.
If you have questions about overall structure ask here -- or submit your unfinished PR and ask your questions in the PR.  In this case, people often put ```[WIP]``` at the beginning of the PR title.

Thanks!

**Comment by mtrenfield** [comment]
That's very helpful.  I have started working on this.
