### ISSUE TITLE
Doc missing for Similarity Algorithm

### ISSUE THREAD

**Issue by mozark24** [networkx/networkx#2876]
I'm using the similarity algorithm graph_edit_distance method 'as-is', but it would be most helpful to have it included in the official documentation.  A lingering question I have is if I can get a floating point from the graph_edit_distance calculation instead of an int (higher precision would be optimum).

**Comment by aparamon** [comment]
@mozark24 The quick answer to your question is yes, please see `test_graph_edit_distance_edge_cost` for an example.
Agree that the more comprehensive documentation would be a valuable addition; for now please see the doc-strings for a basic description.

**Comment by mozark24** [comment]
Thank you.  Yes, I found the edge cost and that has somewhat solved my question.  Though I found an odd case where the having a substitution cost can sometimes cause a non-zero GED between identical graphs.

**Comment by dschult** [comment]
I am going to classify this as a request for documentation.  @aparamon can you close it when you feel it has been satisfied?  Thanks.

**Comment by aparamon** [comment]
I'll prepare a documentation update, but don't promise it too happen soon. Also, I'm not sure what to include there in addition to what's already present in doc-strings and tests :-)

**Comment by tjengel** [comment]
I would like to work on this, but don't know how the documentation works. I tried the steps from the readme, and my documentation won't build.

**Comment by dschult** [comment]
The docs look wonderful to me!
