### ISSUE TITLE
Question regarding all_pairs_shortest_path_length

### ISSUE THREAD

**Issue by kristianeschenburg** [networkx/networkx#2882]
In previous versions, all_pairs_shortest_path_length (among other methods) would return a dictionary mapping a source node to target nodes as such {source: {target: distance}}.   The newest version of Networkx, 2.1, returns an iterator, which can be converted to a dictionary via dict(iterator object).

Why has this functionality changed in the newest release?

**Comment by dschult** [comment]
For large Graphs it is expensive to build the entire dictionary. The iterator allows you to process all the distances without creating a large data structure in memory to hold all that data.  One of the big changes in NetworkX 2.0 is moving to a more iterator/view approach to graph reporting for precisely this reason.

**Comment by kristianeschenburg** [comment]
Good to know -- thank you!
