### ISSUE TITLE
Neighbor information example from Graph.adj is not working

### ISSUE THREAD

**Issue by donpatrice** [networkx/networkx#2884]
The documentation for `Graph.adj` states:

> The neighbor information is also provided by subscripting the graph. So `for nbr, foovalue in G[node].data('foo', default=1):` works.

But this is not working.
```python
G = nx.Graph([(0, 1), (1, 2), (2, 0)])
colors = {0: 'red', 1: 'green', 2: 'blue'}
nx.set_node_attributes(G, colors, 'colors')
for nbr, foovalue in G[0].data('color'):
    print(nbr, foovalue)

'AtlasView' object has no attribute 'data'
````

Do I misunderstand the usage or is this statement wrong.

**Comment by dschult** [comment]
That example does not work with NetworkX.  Perhaps it should, but at the moment it doesn't.

The first sentence you quote is true:  
```The neighbor information is also provided by subscripting the graph.```

But the example should read:   ```for nbr, datadict in G[node].items():```

Thank for reporting this. 
Would it be helpful to include functionality to iterate over nbrs and a single attribute? It can be done now using two lines:

    for nbr, dd in G[node].items():
        foovalue = dd.get('foo', default=1)

**Comment by donpatrice** [comment]
Unfortunately this does not work either.

```python
>>>> G.nodes[1]
{'colors': 'green'}
```
but
```python
>>>> G[1].items()
ItemsView(AtlasView({0: {}, 2: {}}))
```
I think it would be nice if it was possible to write: `for nbr, foovalue in G[node].data('foo', default=1):`

But for now it would be good to know what is the current suggested way to solve this.

**Comment by dschult** [comment]
The syntax ```G.nodes[1]``` shows the NODE attributes for node 1, while ```G[1].items()``` shows the neighbors and EDGE attributes connecting to those neighbors.    Said another way, ```G[node]``` gives the adjacency information, not the node information.

Edge information:

    for nbr,dd in G[node].items():
        print(nbr, dd.get('color','red)

Node information:

    print(G.nodes(data='color'))

Node information about neighbor nodes:

    nodecolor=G.nodes(data='color')
    [(nbr,nodecolor[nbr]) for nbr in G[node]]

OR

    [(nbr, G.nodes[node]['color']) for nbr in G[node]]

**Comment by donpatrice** [comment]
Thanks a lot!
