### ISSUE TITLE
weakly_connected_component_subgraphs deprecation and slow runtime

### ISSUE THREAD

**Issue by gboeing** [networkx/networkx#2887]
OSMnx uses networkx's `weakly_connected_component_subgraphs` function to extract the largest connected component of a street network: https://github.com/gboeing/osmnx/blob/52b7cc473192461ba36d21440f7ea51ad03b5171/osmnx/utils.py#L251

On a large graph (e.g., 1.2 million nodes, 2.3 million edges), with nx 2.0 and osmnx 0.6 the following line runs in ~10 minutes:

```python
G = max(nx.weakly_connected_component_subgraphs(G), key=len)
```
But with nx 2.1 (and all else equal), that line is still running 24 hours later. Why has this run time increased so drastically (2+ orders of magnitude) with nx 2.1?

Separately, it appears weakly_connected_component_subgraphs is being [deprecated](https://github.com/networkx/networkx/blob/7e63811866e86e87e244790b5310098737c22ec4/networkx/algorithms/components/weakly_connected.py#L116). Even if I [replace that function](https://github.com/gboeing/osmnx/commit/ef95dcb4f1b85fc439f776c39e3e5509e13b5c4b) with the snippet suggested in the deprecation message, the code still hasn't finished running 24 hours later.

**Comment by gboeing** [comment]
I've tracked this nx 2.0 vs 2.1 execution time issue down more narrowly.

Let `G` be a disconnected MultiDiGraph with ~1.2 million nodes, ~2.3 million edges, and ~1000 weakly connected components (with the largest of these components comprising 97% of the graph's total nodes and edges).

If I run the following code:

```python
%%time
is_wc = nx.is_weakly_connected(G)
wccs = nx.weakly_connected_components(G)
largest_wcc = max(wccs, key=len)
subgraph = G.subgraph(largest_wcc)
```

It executes in a similar wall time of ~10 seconds with either nx 2.0 or 2.1. So far so good. But if I then run the following line of code after that (to convert my SubMultiDiGraph back to an actual MultiDiGraph):

```python
%%time
G2 = subgraph.copy()
```

It executes in a wall time of ~50 seconds with nx 2.0 but has been running indefinitely (well over an hour so far) with nx 2.1.

**Comment by dschult** [comment]
Thanks for tracking this down to this level!!

Just to help me out, can you tell me what size the node attributes and/or edge attributes are?
If you don't store any node or edge attributes, that indicates we've got a bad design for subgraph views. If the attribute dicts are big, what kind of size?

Thanks

**Comment by gboeing** [comment]
@dschult The nodes are integers, and here's a sample node attribute dict:

```
{'highway': 'motorway_junction',
   'osmid': 25457926,
   'ref': '356',
   'x': -121.5559232,
   'y': 36.9990984}
```

Here's a sample edge attribute dict:

```
{'highway': 'motorway',
   'lanes': '2',
   'length': 87.9717018361987,
   'maxspeed': '65 mph',
   'name': 'South Valley Freeway',
   'oneway': True,
   'osmid': 36022187,
   'ref': 'US 101'}
```

The graph itself also has an attribute dict like this:

```
{'crs': {'init': 'epsg:4326'}, 'name': 'unnamed'}
```

**Comment by gboeing** [comment]
@dschult here's a gist MWE for you to reproduce with nx 2.0 vs 2.1: https://gist.github.com/gboeing/84649719e2500c13358c813b7cfd1fbf

It looks like with nx 2.0, `subgraph.copy()` takes ~55 seconds to execute regardless of whether or not there are attributes on the nodes and edges. With nx 2.1, it takes forever to execute (still hasn't finished yet so I can't give you an actual run time).

**Comment by dschult** [comment]
I have tried a case that takes 5 minutes in nx 2.0 in python 2.7 and 50 seconds in nx 2.2 in python2.7.  Same case takes 35 seconds for nx 2.2 and nx 1.11 in python3.6.   I'll try to get a better test setup soon.

    import networkx as nx
    n=1000
    G=nx.grid_2d_graph(n,n)  # million nodes
    ns=list(G)
    sg=G.subgraph(ns[10:-10])
    %%time
    S=sg.copy()

**Comment by gboeing** [comment]
This case you just shared similarly takes ~35 seconds for me with nx 2.1 and py3.6. The example in the gist I linked earlier takes much longer (~50 seconds with nx 2.0 and indefinite execution time with nx 2.1).

**Comment by gboeing** [comment]
Just ran [that gist](https://gist.github.com/gboeing/84649719e2500c13358c813b7cfd1fbf) again with nx 2.2rc1.dev_20180222225423, with the same results as 2.1: the subgraph.copy() steps run indefinitely even though they complete in seconds with nx 2.0.

**Comment by dschult** [comment]
If you replace the two lines in the gist code that 1) create the subgraph and 2) copy the subgraph, with the following, the speedup is tremendous:

    G2=G.fresh_copy()
    G2.add_nodes_from((n, G.nodes[n]) for n in largest_wcc)
    G2.add_edges_from((n, nbr, d)
            for n, nbrs in G.adj.items() if n in largest_wcc
            for nbr, d in nbrs.items() if nbr in largest_wcc)
    G2.graph.update(G.graph)

There were changes from 2.0 to 2.1 in the subgraph view's treatment of node lookup.  The intent was to speed up the common case of a small number of nodes in the induced subgraph.  This is the opposite case where a small number of nodes are NOT in the induced subgraph. So, perhaps I need to tweak the special handling again by looking for the smaller of "nodes in" vs "nodes out".

**Comment by gboeing** [comment]
Thanks @dschult. The method you showed here does offer a big speedup. However, it seems to produce a slightly different resulting graph at the end than did the method I'd shared. I made a gist file to demonstrate here: https://gist.github.com/gboeing/84649719e2500c13358c813b7cfd1fbf#file-nx-20-largest-weakly-connected-component-ipynb

**Comment by dschult** [comment]
Ahh..   The code I put doesn't account for multiedges.

    H2 = H.fresh_copy()
    H2.add_nodes_from((n, H.nodes[n]) for n in largest_wcc)
    if H2.is_multigraph:
        H2.add_edges_from((n, nbr, key, d)
            for n, nbrs in H.adj.items() if n in largest_wcc
            for nbr, keydict in nbrs.items() if nbr in largest_wcc
            for key, d in keydict.items())
    else:
        H2.add_edges_from((n, nbr, d)
            for n, nbrs in H.adj.items() if n in largest_wcc
            for nbr, d in nbrs.items() if nbr in largest_wcc)
    H2.graph.update(H.graph)

**Comment by gboeing** [comment]
Thanks. I'll adapt a piece of code like that into OSMnx in the meantime to be able to handle large graphs. Regarding your earlier comment:

> So, perhaps I need to tweak the special handling again by looking for the smaller of "nodes in" vs "nodes out".

That seems like a good solution.
