### ISSUE TITLE
[Feature request] Graph fingerprinting

### ISSUE THREAD

**Issue by pckroon** [networkx/networkx#2890]
Hi all,

for my work I need to create graph fingerprints. 
I'm thinking of ECFP [1] (extended connectivity fingerprint, a Morgan type circular fingerprint) in particular, but I think other variants such as MACCS, LINGO, Path and Tree will also be valuable additions.

[1] https://pubs.acs.org/doi/abs/10.1021/ci100050t
https://docs.eyesopen.com/toolkits/python/graphsimtk/fingerprint.html

**Comment by dschult** [comment]
Try the [email discussion group](https://groups.google.com/forum/#!forum/networkx-discuss) for a wider audience. Send email to: networkx-discuss@googlegroups.com
