### ISSUE TITLE
unable to add colorbar to a MultiDiGraph for networkx >= 2.1

### ISSUE THREAD

**Issue by zingale** [networkx/networkx#2893]
In networkx 2.0, `nx.draw_networkx_edges()` returned a `LineCollection`, which you could then pass to matplotlib's `colorbar()` to get a colorbar showing the scale of the colors for the edges.

In networkx 2.1, it now returns a list of `FancyArrowPatch`s, and `colorbar()` complains that these are not mappable.  Is there a new way to add a colorbar to a directed graph for networkx >= 2.1?  I couldn't find anything in the docs.

**Comment by dschult** [comment]
Too bad this feature was lost (or not as easy). The FancyArrowPatchs give us many nice features.

It looks like the colorbar features of Matplotlib include a ColorbarPatch. 
Can you try the answers in [this stackoverflow answer](https://stackoverflow.com/questions/18658047/adding-a-matplotlib-colorbar-from-a-patchcollection) to see if something similar can work here?

**Comment by zingale** [comment]
thanks, I'll give that a try

**Comment by zingale** [comment]
that worked great.  See the issue I liked above for example output -- the new arrows are much nicer.  For the record, here's what I had to do:

 `draw_networkx_edges` returns a list of `FancyArrayPatch`s now

```
           pc = mpl.collections.PatchCollection(edges_lc, cmap=plt.cm.viridis)                                                         
           pc.set_array(weights)                                                                                                       
           plt.colorbar(pc)                                                                                                            
```

where `weights` is the array of weights I used for `edge_color` in the call to `draw_networkx_edges()`

I'll explore adding a simple example of this to your gallery via a PR later today.

**Comment by zingale** [comment]
here's a simple example using one of the gallery examples from the networkx documentation:

https://networkx.github.io/documentation/stable/auto_examples/drawing/plot_directed.html#sphx-glr-auto-examples-drawing-plot-directed-py

```
from __future__ import division
import matplotlib as mpl
import matplotlib.pyplot as plt
import networkx as nx

G = nx.generators.directed.random_k_out_graph(10, 3, 0.5)
pos = nx.layout.spring_layout(G)

node_sizes = [3 + 10 * i for i in range(len(G))]
M = G.number_of_edges()
edge_colors = range(2, M + 2)
edge_alphas = [(5 + i) / (M + 4) for i in range(M)]

nodes = nx.draw_networkx_nodes(G, pos, node_size=node_sizes, node_color='blue')
edges = nx.draw_networkx_edges(G, pos, node_size=node_sizes, arrowstyle='->',
                               arrowsize=10, edge_color=edge_colors,
                               edge_cmap=plt.cm.Blues, width=2)
# set alpha value for each edge
for i in range(M):
    edges[i].set_alpha(edge_alphas[i])

pc = mpl.collections.PatchCollection(edges, cmap=plt.cm.Blues)
pc.set_array(edge_colors)
plt.colorbar(pc)

ax = plt.gca()
ax.set_axis_off()
plt.savefig("digraph_colorbar.png")
```

gives:

![digraph_colorbar](https://user-images.githubusercontent.com/7817509/37105507-596e1da8-21fd-11e8-90bd-e54d026c4895.png)

**Comment by JulianWgs** [comment]
Hi,

I had the same problem and the workaround worked nicely :) I originally found this question on StackOverflow. I will add the workaround there as well if you dont mind.

Is the core issue worth revisiting and fixable (may be upstream)? The workaround isnt quite convenient and I dont know if new users will find the answer as easily.

Currently I'm using matplotlib 3.5.1 and networkx 2.6.3.

Greetings
Julian

**Comment by MridulS** [comment]
https://github.com/networkx/networkx/pull/4825 added LineCollections back, but for directed graphs you need to explicitly ask of LineCollections by passing in `arrows=False`. Something like `nx.draw_networkx_edges(G, pos, arrows=False)`

This behavior is already documented at https://networkx.org/documentation/latest/reference/generated/networkx.drawing.nx_pylab.draw_networkx_edges.html, any suggestions how can we improve the docs?

**Comment by JulianWgs** [comment]
Wow! Thanks for the quick reply! Yeah, that's what [this StackOverflow](https://stackoverflow.com/a/53070467) answer suggests. However then you dont get arrows. Why isn't it possible to get arrows and make it work without a workaround? What changes would be necessary? I think documentation is important and the networkx docs are amazing, but in this case wouldn't it be better to have is just work without special cases?

**Comment by dschult** [comment]
The arrows are a PatchCollection, not a LineCollection. So you have to use matplotlib code for  PatchCollections to make the colorbar. The workaround is only 3 lines of code instead of 1 line for the LineCollection, right?

**Comment by JulianWgs** [comment]
For me it's not about the amount of lines of code of the workaround, but about the friction using networkx. In the end a workaround will be copied either way, so it doesnt matter if its 3 lines or 10 lines, but it will definitely take the developer out of the flow and send him/her on a google spree.

Another idea would be to give `draw_networkx_edges` the argument `cbar` like [`seaborn.heatmap`](https://seaborn.pydata.org/generated/seaborn.heatmap.html) does and handle both cases internally.
