### ISSUE TITLE
Varying  color intensity to color nodes

### ISSUE THREAD

**Issue by pinkfloyd06** [networkx/networkx#2895]
Hello,

l have generated a fully connected random graph :
```
n=15
G=nx.complete_graph(n)
```
l would like to  color each node with a different color from the following colors :  

```
colors = ['red', 'blue', 'green']
color_gen = random.choices(colors, k=l)
node_color = color_gen
nx.draw(G, node_color=node_color, with_labels=True)
```

Now l would like to change the intensity of the color to form an extended vector of colors rather than (colors = ['red', 'blue', 'green']).

for each color in colors=['red', 'blue', 'green' ]
     increase/decrease intensity of red
    increase/decrease intensity of blue
    increase/decrease intensity of green

How can l do that ?

**Comment by dschult** [comment]
You should check the [matplotlib documentation about colors](https://matplotlib.org/api/colors_api.html).  In particular, if you specify which color using a finer scale of colors (like RGB values) then lots of things are possible:

    colors = [(0.1, 0.2, 0.5), (0.1, 0.5, 0.2), (0.5, 0.1, 0.2)]
