### ISSUE TITLE
Creating a graph using "nx.from_pandas_adjacency()"

### ISSUE THREAD

**Issue by kahanad** [networkx/networkx#2896]
When using: 
`nx.from_pandas_adjacency(df, create_using=nx.DiGraph) `
the created instance is of class Graph regardless of the value of the `create_using` parameter.

**Comment by dschult** [comment]
You need to create the create_using object. Put () after nx.DiGraph and it will work. As written it tries to use the class itself and that doesn't work so reverts to Graph.

**Comment by kahanad** [comment]
Hi,
It still the same, for example:

` In [7]: nx.from_pandas_adjacency(df, create_using=nx.DiGraph())
Out [7]: <networkx.classes.graph.Graph at 0x1d243bad3c8>
`

`In [8]: nx.from_pandas_adjacency(df, create_using=nx.MultiGraph())
<Out [8]: networkx.classes.graph.Graph at 0x1d243b34780>
`

**Comment by dschult** [comment]
I don't have that happening. In fact, I don't see how that could happen with the code... So:
what version of python and what does nx.__version__ show? Can you show us what code you are using to create df, etc?
