### ISSUE TITLE
incorrect plot labels for Unicode nodes

### ISSUE THREAD

**Issue by a-vodka** [networkx/networkx#2897]
Hello, I've found an issue. When nodes are Unicode string Matplotlib shows labels in incorrect way. 
As far as I understand the problem in draw_networkx_labels(...) in nx_pylab.py. After unpacking  from dictionary string become an nonunicode.

For represent bug use this code:

![1](https://user-images.githubusercontent.com/6401696/37168052-53480be0-230c-11e8-9454-7913a9eee96a.png)

```
# -*- coding: utf-8 -*-

import networkx as nx
import matplotlib.pyplot as plt

G=nx.Graph()
G.add_edges_from( [(u"привет", u"мир")] )
nx.draw_kamada_kawai(G, with_labels = True)

plt.show()
```

**Comment by dschult** [comment]
This works fine for me (python 3.6, nx from git) I suspect it is a problem with drawing the unicode characters using the ```text``` feature in matplotlib. In particular, the unicode does not get lost anywhere.

**Comment by a-vodka** [comment]
I have suggestion, that was trouble with fonts. Now it works fine.
