### ISSUE TITLE
Mutation troubles with copy and set_node_attributes

### ISSUE THREAD

**Issue by dustinmichels** [networkx/networkx#2899]
Hi! I've been having some troubles with node attributes and graph copies. Here is a MWE; G2 is a copy of G1 and changing an attribute of G2 also changing G1:

```python
import networkx as nx

g_dict = {'a':'b'}
g_vals = {'a':[1,2],'b':[1,2]}

G1 = nx.Graph(g_dict)
nx.set_node_attributes(G1, name='stuff', values=g_vals)
G2 = G1.copy()

print('G1:', G1.nodes(True))
print('G2:', G2.nodes(True))

G2.nodes['a']['stuff'].remove(1)

print('G2:', G2.nodes(True))
print('G1:', G1.nodes(True))

# OUTPUT:
# G1: [('a', {'stuff': [1, 2]}), ('b', {'stuff': [1, 2]})]
# G2: [('a', {'stuff': [1, 2]}), ('b', {'stuff': [1, 2]})]
# G2: [('a', {'stuff': [2]}), ('b', {'stuff': [1, 2]})]
# G1: [('a', {'stuff': [2]}), ('b', {'stuff': [1, 2]})]
```

Perhaps I misunderstood something, but:
- [The documentation for `set_node_attributes`](https://networkx.github.io/documentation/stable/reference/generated/networkx.classes.function.set_node_attributes.html) says "If `values` is not a dictionary, then...updates to that object will be reflected in the node attribute for each edge." So I make sure to use a dictionary!

- [The documentation for `Graph.copy`](https://networkx.github.io/documentation/latest/reference/classes/generated/networkx.Graph.copy.html#networkx-graph-copy) says "the default behavior is a 'deepcopy' where the graph structure as well as all data attributes and any objects they might contain are copied."

Which made me think this was the way to copy and then change a graph's node attributes?

**Comment by dschult** [comment]
Thanks for this!   The documentation is wrong.  deepcopy is not the default (you can get that by using deepcopy). The first paragraph of the same docstring you quote contradicts the quoted claim.

    The copy method by default returns a shallow copy of the graph and attributes. 

The first paragraph is correct, while the 3rd paragraph's claim about "default" is incorrect.

**Comment by dustinmichels** [comment]
Ah okay, great! Thank you!
