### ISSUE TITLE
Long import times

### ISSUE THREAD

**Issue by pb-cdunn** [networkx/networkx#2900]
Using [**import_profiler**](https://pypi.python.org/pypi/import-profiler/0.0.3), I've traced slow imports to **networkx**, especially:

* `networkx.generators` (300ms)
* `networkx.linalg` <- `.algebraicconnectivity` <- `numpy` (200ms)
* `networkx.readwrite` <- `.graphml` <- `xml.etree.cElementTree` (100ms)

I'm not using `linalg` at all, and I rarely need `readwrite`. I don't think I need `generators` either. These three trees represent 60% of the import-time for **networkx**.

When my filesystem is slow, the import-times can be much worse.

I have a couple of ideas for you:
* If possible, avoid importing these unless they are needed.
* Or, depend on and use [**lazy-import**](https://pypi.python.org/pypi/lazy-import) for at least these 3 sub-trees.

**Comment by pb-cdunn** [comment]
@hagberg , Why is this "closed"? Did someone implement lazy loading? Or are those large sub-trees no longer loaded always?

**Comment by SeanDS** [comment]
@hagberg I'd also be interested to know why this issue was closed - import times in NetworkX are in my experience pretty slow and some refactoring/lazy importing could speed things up a lot when only parts of NetworkX are being used.

**Comment by dschult** [comment]
Can you elaborate on this a little...  We're talking about small fractions of a second and potentially costing a fair amount of maintainer time to keep the lazy imports working well. What are the benefits to you of this change? I know in an ideal world it'd be nice to have imports take no time and we'd just load the functions we need. But it's not an ideal world. So, can you expose the cost/benefit for us a little?   Thanks!

**Comment by SeanDS** [comment]
I'm using NetworkX as part of an application that uses a CLI. The CLI imports only `DiGraph` by doing `from networkx import DiGraph` but this seems to be pulling in loads of algorithms from other modules immediately, which adds a noticeable delay. Naively, to me it seems like NetworkX, as a collection of algorithms and data structures, should really be importing only the essentials at the top level and then importing each submodule as it is needed by a `DiGraph.xyz()` call.

To take a concrete example, is it really necessary to pull in all of this stuff in [`networkx.__init__`](https://github.com/networkx/networkx/blob/master/networkx/__init__.py)?
```python
# These are import orderwise
from networkx.exception import *
import networkx.utils

import networkx.classes.filters
import networkx.classes
from networkx.classes import *

import networkx.convert
from networkx.convert import *

import networkx.convert_matrix
from networkx.convert_matrix import *


import networkx.relabel
from networkx.relabel import *

import networkx.generators
from networkx.generators import *

import networkx.readwrite
from networkx.readwrite import *

# Need to test with SciPy, when available
import networkx.algorithms
from networkx.algorithms import *
import networkx.linalg

from networkx.linalg import *
from networkx.testing.test import run as test

import networkx.drawing
from networkx.drawing import *
```

**Comment by dschult** [comment]
That was not my question.  Of course, we can pull in exactly the code you want to use and nothing else... but at a large cost of making sure this works for eac usch user. We would obviously not customize it to each user. But have chunks of the package.

But what I'm asking is: what is the benefit to you of us doing that?  How much difference does this make and how costly is that?

**Comment by SeanDS** [comment]
On some tests we did a few months ago commenting out the stuff we don't need from the top level of networkx and timing the import with `python -X importtime <(echo "import networkx")` it was of the order 0.25 seconds improvement on the machine used for the test. As I said in my last post, for a CLI (which is also pulling in our own application and others, adding another few hundredths of a second or so) this is pretty noticeable for the user.

If it's a large cost, we can probably live with this import time, but I guess my complaint is more philosophical: it doesn't seem like a good approach to pull in everything on import, but leave it up to the user to pull in the stuff they want.

**Comment by rossbar** [comment]
@SeanDS the reason this was closed is not because changing imports wouldn't be considered, but because there was no followup. PRs with concrete suggestions for improvements would be evaluated. That being said, @dschult 's point is very important too - there are always tradeoffs to consider (user convenience, performance, maintenance burden, etc.). Bearing that in mind, PRs with proposals to improve the import system (for all users, not just specific use-cases) would certainly be considered.

**Comment by dschult** [comment]
Well said @rossbar !   I agree...
We'll certainly merge PRs that help with import time if they don't introduce other maintenance or performance issues.

**Comment by SeanDS** [comment]
Well, as far as I know the only way to speed up imports is to stop importing so much stuff on the top level. That necessarily means that users will have to instead add manual `from network.algorithms.dag import topological_sort` etc. into their scripts instead of relying on these being automatically available from `import networkx`. This definitely impacts user convenience, breaks backwards compatibility so probably needs a new major version, requires lots of changes to docs, and I guess breaks lots of existing test and example scripts. I don't expect a non-core committer submitting a PR that changes essentially everything about the project would be well received. With respect, this to me sounds like something to be added to milestones for a future release rather than a simple PR. That said, maybe @pb-cdunn had something different in mind to speed up imports?

**Comment by rossbar** [comment]
> Well, as far as I know the only way to speed up imports is to stop importing so much stuff on the top level.

This is a type of change that I would be very much against for all of the reasons you listed, regardless of who proposed it. I agree with @dschult that all of the downsides you've listed vastly outweigh the potential benefit of shaving 100-200ms from the import time. There are other approaches, so if someone wants to investigate & make a case for them, they would indeed be considered!

**Comment by pb-cdunn** [comment]
> the potential benefit of shaving 100-200ms from the import time

It was at least 600ms last time I measured, and that was over 60% of start-up time. Surely there is some amount of time that is too much.

The cost of doing nothing is that any executable using **networkx** has a slow start-up time, for no reason. We might as well be using Java.

The maintenance cost? It's [so simple](https://pypi.org/project/lazy-import/)! Just wrap the lazy-import in a try block. Nothing else changes. Anybody who has `lazy_import` in their site-packages automatically has a benefit.

I'll post a quick PR and you can see what I mean...

(Of course, it would be better only to import what you actually need, but _that_ requires diligence early or a lot of work today. It's a bit too much to expect of a large project like this one.)

**Comment by pb-cdunn** [comment]
Here are runtimes for the latest **network** on a node at work (3GHz Xeon):
```
  cumtime (ms)    intime (ms)  name
        2206.6            0.5  networkx
           7.8            0.3  +networkx
           7.2            3.8  ++datetime
...
         101.5            0.2  +networkx.utils
        1868.7            0.3  +networkx.generators
        1548.5            2.1  ++networkx.generators.community
        1546.4           14.3  +++scipy.special
          46.1            0.3  +networkx.readwrite
         158.9            0.2  +networkx.linalg
```
It's interesting that `readwrite` has gotten so much faster. Anyway, those are numbers on my company's NTFS. On a local disk, the total is much quicker:
```
  cumtime (ms)    intime (ms)  name
         766.8            2.6  networkx
         553.3            0.4  +networkx.generators
```
That's probably why some people think this is not needed. But we do not all have fast local disks.

**Comment by pb-cdunn** [comment]
Btw, I also deal with a lot of uncached latency, so measurements over time are difficult.

Here, `foo.py` imports `networkx` and nothing else.
```
% time python foo.py

real    0m7.825s
user    0m1.020s
sys     0m3.807s

% time python foo.py

real    0m1.206s
user    0m1.018s
sys     0m3.757s
```
To me `1.2s` is a lot, but `7.8s` is untenable. But yes, it does get faster with filesystem caching.

**Comment by pb-cdunn** [comment]
> On some tests we did a few months ago commenting out the stuff we don't need from the top level of networkx and timing the import with python -X importtime <(echo "import networkx") it was of the order 0.25 seconds improvement on the machine used for the test.

There seem to be some cross-imports. If I exclude 4 -- `generators, linalg, readwrite, algorithms` -- the import time drops dramatically. But if I keep one, it takes almost along as with all of them. They probably all import scipy/numpy/etc.

At least it's only 4 that matter.

**Comment by pb-cdunn** [comment]
Ok, I have it working _in principle_. But only by not importing `*` to the top-level. (You could look into `lazy_import.lazy_callable(...)`, but that's way too much work.)

```diff
+try:
+    import lazy_import
+    lazy_import.lazy_module('networkx.generators')
+    lazy_import.lazy_module('networkx.readwrite')
+    lazy_import.lazy_module('networkx.algorithms')
+    lazy_import.lazy_module('networkx.linalg')
+except ImportError:
+    pass

-from networkx.generators import *
+#from networkx.generators import *

-from networkx.readwrite import *
+#from networkx.readwrite import *

-from networkx.algorithms import *
+#from networkx.algorithms import *

-from networkx.linalg import *
+#from networkx.linalg import *
```
```py
from import_profiler import profile_import

with profile_import() as context:
    import networkx.release
    print(networkx.release.version)

    # Print cumulative and inline times. The number of + in the 3rd column
    # indicates the depth of the stack.
    context.print_info()
```
```
  cumtime (ms)    intime (ms)  name
         109              0.8  networkx.release
```
That's off our slow NTFS disk!

In short, I don't see a simple way to do this without requiring users to import these 4 (at least) themselves.

**Comment by dschult** [comment]
Interesting... Do I read correctly that it's the import of scipy.special that is the hold-up?
If so, we can easily move that inside a function so it only gets done if that function is called. It is only used in one place in one function.  But maybe I am not read the profiling output correctly.

**Comment by pb-cdunn** [comment]
About 2/3 is under `scipy.special`. Also significant are `scipy.spatial` and `scipy.sparse`.

If you push that change onto a branch, I'd be happy to test it for you.

**Comment by dschult** [comment]
Cool -- I don't see where it would import scipy.sparse on the initial import.
But both scipy.special and scipy.spatial are imported at the module level when those imports could be moved inside a function. I'll try to put together a branch to try...

**Comment by dschult** [comment]
How about this branch:
https://github.com/dschult/networkx/tree/time_imports
I can make it a PR if that's better for you.  I found a number of places where an import could be delayed.

Not sure if lazy-imports would work to reduce this even more, but just with these changes it is faster...
Surely not worth the time on its own, but the code is probably better because it got cleaned up a little.

**Comment by pb-cdunn** [comment]
I haven't tested runtime, but it seems like you might have to go a different route now, right? Simply importing inside each function? That's fine.

**Comment by SeanDS** [comment]
Thanks @dschult for your work on #4296! Much appreciated.
