### ISSUE TITLE
Unable to use nx.from_pandas_dataframe  function

### ISSUE THREAD

**Issue by wangxiaoyunanne** [networkx/networkx#2902]
I use network 2.1 version to run my previous code. It has the following issue

 G = nx.from_pandas_dataframe(bipart, 0, 1)
AttributeError: 'module' object has no attribute 'from_pandas_dataframe'

**Comment by dschult** [comment]
Take a look at [the docs for reading/writing](https://networkx.github.io/documentation/stable/reference/convert.html)
The syntax you are using is for an older version of networkx that doesn't specify whether the dataframe holds adjacency info or edgelist info.
