### ISSUE TITLE
min_cost_flow does not throw an exception when the graph is disconnected

### ISSUE THREAD

**Issue by sshravan** [networkx/networkx#2906]
According to the docs ([here](https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.flow.min_cost_flow.html)), `min_cost_flow` is supposed to throw an exception if the source vertex is not connected to destination vertex. 
On the contrary, the following code is stuck in an infinite loop:

```
G = nx.DiGraph()
G.add_nodes_from(range(5), demand=0)
G.node[4]['demand'] = -13
G.node[3]['demand'] = 13

edges = [
(0, 2, {'capacity': 20, 'weight': 0.1}),
(0, 3, {'capacity': 20, 'weight': 0.1}),
(2, 1, {'capacity': 20, 'weight': 0.1})]
G.add_edges_from(edges)
flowDict = nx.min_cost_flow(G)
```

Is this a bug?
I am using version 2.1

**Comment by dschult** [comment]
Thanks for this bug report!  I can verify that an infinite loop occurs with this example.

In the method that looks for cycles when 1 edge is found, the edge is duplicated (line #388) when it shouldn't be.  I'll put a PR in shortly.
