### ISSUE TITLE
Drawing flow graph in django using elements from database

### ISSUE THREAD

**Issue by Shawnmhy** [networkx/networkx#2908]
I have a table named 'Reactions', and there is a column named 'Metabolites'. Is it possible when I finished searching one kind of reactions using the id or name, and when I clicked on the reaction, and the flow graph of the metabolites can be generated(maybe using networkx or graphviz?).

For example, if reaction 'ABC' is my search result, and A,B and C are the metabolites of the reaction, then we can get the graph which indicates a + b -> c. Is there anyway do achieve this function?

The code of my models are written as follow:

`class Genes(models.Model):
id = models.CharField(primary_key=True, max_length=255)
name = models.CharField(max_length=255, blank=True, null=True)
notes = models.CharField(max_length=255, blank=True, null=True)

class Meta:
    managed = False
    db_table = 'Genes'

class Metabolites(models.Model):
id = models.CharField(primary_key=True, max_length=255)
name = models.CharField(max_length=255, blank=True, null=True)
compartment = models.CharField(max_length=255, blank=True, null=True)
charge = models.CharField(max_length=255, blank=True, null=True)
formula = models.CharField(max_length=255, blank=True, null=True)
notes = models.CharField(max_length=255, blank=True, null=True)

class Meta:
    managed = False
    db_table = 'Metabolites'

class Reactions(models.Model):
id = models.CharField(max_length=255, primary_key=True)
name = models.CharField(max_length=255, blank=True, null=True)
metabolites = models.TextField(blank=True, null=True)
lower_bound = models.CharField(max_length=255, blank=True, null=True)
upper_bound = models.CharField(max_length=255, blank=True, null=True)
gene_reaction_rule = models.TextField(blank=True, null=True)
subsystem = models.CharField(max_length=255, blank=True, null=True)
notes = models.CharField(max_length=255, blank=True, null=True)

class Meta:
    managed = False
    db_table = 'Reactions'`

**Comment by dschult** [comment]
Yes, I suspect either networkjx or graphviz could do this. You'll need to create the nodes and edges to be drawn and then draw them.
