### ISSUE TITLE
Please update documentation to reflect changes from 1.X to 2.X - set_node_attributes

### ISSUE THREAD

**Issue by achilleasatha** [networkx/networkx#2916]
Hello,

After having spent a good few hours trying to figure out why the following wouldn't work (copied from the documentation page on set_node_attributes).

>>> G = nx.path_graph(3)
>>> bb = nx.betweenness_centrality(G)  # this is a dictionary
>>> nx.set_node_attributes(G, 'betweenness', bb)

**TypeError: unhashable type: 'dict'**

I had almost managed to convince myself that NetworkX hadn't been updated to work with Python 3.X

Turns out in the migration from NetworkX 1.X to 2.0 the argument order was swapped around to:

nx.set_node_attributes(G, bb, 'betweenness')

Please make an update to the documentation page for set_node_attributes here: 
[http://pelegm-networkx.readthedocs.io/en/latest/reference/generated/networkx.classes.function.set_node_attributes.html](url)

So that poor new users to NetworkX and Python don't have to suffer through this. It shouldn't be a requirement to have to go through this [https://networkx.github.io/documentation/stable/release/migration_guide_from_1.x_to_2.0.html](url)
to get the right format to make it work. 

Many thanks!

**Comment by dschult** [comment]
Yes -- we should put a note/warning in the docstring for ```set_node_attributes``` that the order was changed between 1.x and 2.x

**Comment by norrishd** [comment]
@achilleasatha Amen! Just went through the same ordeal myself.
