### ISSUE TITLE
KeyError when there are more node labels than nodes in graph

### ISSUE THREAD

**Issue by austinlostinboston** [networkx/networkx#2917]
I'm running Python3.5, NetworkX 1.11, and Matplotlib 2.0.2

**The Problem:** When drawing a graph with labels, networkx throws an error if a node listed in the label table is not mentioned in the pos table. In networkx.drawing.nx_pylab.py (lines 720-721), nodes in the label table are iterated over, and each node's position is subsequently looked up. This triggers a KeyError when a node's position can't be found. This is inconvenient when a label table has been created for an entire graph, but a user wishes to visualize only a subgraph. ~~As shown in the attached notebook~~ (I guess I can't attach code), this case results in the labels dict containing more nodes than the pos dict, thus throwing the error.

**The Solution:** Adding a key check before doing the position lookup for a node in labels will avoid key errors, ensuring that only nodes in the pos dict have labels created for them. This should not have impacts on any other parts of the code.

I will submit the few lines of code in the day or two that fixes this. In the meantime, please let me know if this fix agrees with the overall design decisions of networkx's drawing module.

```
## Python 3.5
import networkx as nx ## 1.11
import matplotlib.pyplot as plt ## 2.0.2

## Create barbell graph
#       2          6
#     /   \      /   \
#   1      3 - 5     7
#    \   /       \  /
#      4          8

e_bunch = [
    (1,2),(2,3),(3,4),(4,1),
    (3,5),(5,6),(6,7),(7,8),(8,5)]

labels = {1:1,2:2,3:3,4:4,5:5,6:6,7:7,8:8}

g = nx.Graph()
g.add_edges_from(e_bunch)
g.remove_edge(3,5) ## We remove edge 3-5 for whatever reason, leaving us with two connected components
subgraphs = nx.connected_component_subgraphs(g)

## Now we want to quickly visualize each of these subgraphs without having to worry about creating a new label dict
for subgraph in subgraphs:
    print(subgraph.nodes())
    pos = nx.spring_layout(subgraph)
    nx.draw(subgraph, pos=pos, labels=labels) ## Throws Key error
    
## The first subgraph contains nodes 1,2,3, and 4
## But networkx looks for node 5 in the pos dict, can't find it, and throws the unnecessary error below.
'''
/Users/austinankney/anaconda/lib/python3.5/site-packages/networkx/drawing/nx_pylab.py in draw_networkx_labels(G, pos, labels, font_size, font_color, font_family, font_weight, alpha, bbox, ax, **kwds)
    719     text_items = {}  # there is no text collection so we'll fake one
    720     for n, label in labels.items():
--> 721         (x, y) = pos[n]
    722         if not cb.is_string_like(label):
    723             label = str(label)  # this will cause "1" and 1 to be labeled the same

KeyError: 5
'''
```

**Comment by dschult** [comment]
It seems like this has a simple solution:   ```labels={k, v for k, v in labels if v in pos}```
If there is a simple solution in networkx code that works as well, I'd be fine to look at it, but it needs to work both ways -- that is, labels and pos are both dicts. We then need to decide which takes precedence. Perhaps better to make the user specify exactly what they want so we avoid surprises.
