### ISSUE TITLE
Generating layout with some coordinates fixed

### ISSUE THREAD

**Issue by fjhheras** [networkx/networkx#2918]
It would be great to have the ability to fix one of the coordinates while generating the layouts of the graphs. That would be useful to produce, for example, a layout with the nodes ordered along one dimension following a given property, while minimising energy along the other dimensions.

**Comment by dschult** [comment]
The ```pos``` dicts can be manipulated to do this:  find the energy minimizing positions in the other dimensions, and then add an additional coordinate to each node based on the given property.  If you get an example working for this feature I'd help you include it in our examples.  Reopen this issue if you want to pursue this approach.
