### ISSUE TITLE
Possible typo on min_weighted_dominating_set documentation

### ISSUE THREAD

**Issue by Carpetfizz** [networkx/networkx#2927]
[Click here](https://networkx.github.io/documentation/latest/reference/algorithms/generated/networkx.algorithms.approximation.dominating_set.min_weighted_dominating_set.html#networkx.algorithms.approximation.dominating_set.min_weighted_dominating_set) for the function in question.

I believe the section

> weight (string) – The node attribute storing the weight of an **edge**. If provided, the node attribute with this key must be a number for each node. If not provided, each node is assumed to have weight one.

should read

> weight (string) – The node attribute storing the weight of **a node**. If provided, the node attribute with this key must be a number for each node. If not provided, each node is assumed to have weight one.

**Comment by dschult** [comment]
Yup -- that's  typo.  Thanks! I've created a pull request for it.  #3031
