### ISSUE TITLE
Selecting the type of marker on a node per node bases

### ISSUE THREAD

**Issue by xNok** [networkx/networkx#2932]
I noticed that it is not possible to select the marker (or shape) for a network on a node per node basis. Ideally I think we should be able to select the type of maker for a node as we define the color or the suze of the node.

Something like that:

``` python
for i,node in enumerate(O):
    color             =  "r" if i in V2  else "grey"
    node_size     = 200 if i in V2 else 50
    node_shape  =  "s" if i in V2  else "o"
    G.add_node(i, pos=(-pb["Longitude"][i],pb["Latitude"][i], ),color=color,node_size=node_size,node_shape=node_shape)

nx.draw(G, nx.get_node_attributes(G, 'pos'),with_labels=False,
            node_color=list(nx.get_node_attributes(G, 'color').values()),
            node_size=list(nx.get_node_attributes(G, 'node_size').values()),
            node_shape=list(nx.get_node_attributes(G, 'node_shape').values()))

```

**Comment by dschult** [comment]
Take a look at how matplotlib handles shapes in scatterplots. It might be possible to make this happen.

**Comment by acburigo** [comment]
How can I do that with the current version of the library?
I would like to select both color and shape on a per node basis.

**Comment by dschult** [comment]
Use the ```nodelist``` argument to draw only some of the nodes. Use a separate drawing command for each marker style. If each node has its own shape, then draw one node at a time.

Color can be specified by a sequence of colors in the same order as the nodes in nodelist.

**Comment by acburigo** [comment]
I did that and some of the nodes became invisible, for some reason (only the label is showing). Any ideas?

**Comment by acburigo** [comment]
I've actually removed the edges and they are still duplicated.
My code looks like the following:
```
    graph = nx.Graph()
    graph.add_nodes_from(df.name_h)
    graph.add_nodes_from(df.name_y)
    graph.add_edges_from(df[['name_y', 'name_h']].values.tolist())

    plt.figure(figsize=(20, 10))

    nx.draw(
        graph,
        with_labels=True,
        nodelist=df.name_h.tolist(),
        node_color=df.color_h,
        node_shape='o',
        font_size=8,
    )

    nx.draw(
        graph,
        with_labels=True,
        nodelist=df.name_y.tolist(),
        node_color=df.color_y,
        node_shape='v',
        font_size=8,
    )

    plt.show()
```

**Comment by acburigo** [comment]
For example:

```
import networkx as nx

graph = nx.Graph()
graph.add_nodes_from(['a', 'b', 'c'])
graph.add_nodes_from(['1', '2', '3', '4', '5', '6', '7', '8', '9'])
graph.add_edges_from([
    ('a', '1'), ('a', '2'), ('a', '3'),
    ('b', '4'), ('b', '5'), ('b', '6'),
    ('c', '7'), ('c', '8'), ('c', '9'),
])

plt.figure(figsize=(20, 10))

nx.draw(
    graph,
    with_labels=True,
    nodelist=['a', 'b', 'c'],
    node_color=['r', 'g', 'b'],
    node_shape='o',
)

nx.draw(
    graph,
    with_labels=True,
    nodelist=['1', '2', '3', '4', '5', '6', '7', '8', '9'],
    node_color=['r', 'r', 'r', 'g', 'g', 'g', 'b', 'b', 'b'],
    node_shape='v',
)

plt.show()
```
gives me

![index](https://user-images.githubusercontent.com/20728609/68913655-cc947380-073a-11ea-9a1b-dca2fc909863.png)

**Comment by dschult** [comment]
Yup -- I see what happened... The nx.draw() command is too coarse for what you are trying to do. See [the drawing docs](https://networkx.github.io/documentation/stable/reference/drawing.html) for more info. I think you will need to draw the nodes using ```nx.draw_networkx_nodes``` multiple times and separately draw the edges with ```nx.draw_networkx_edges```.  When you do it yourself like this then you don't use the ```nx.draw``` command (which just calls these other functions anyway).

**Comment by dschult** [comment]
Once this is working for you, maybe we can think about how to put in some code to automagically do this when nodeshape is a sequence of shapes... :)

**Comment by acburigo** [comment]
This worked:
```
import networkx as nx
import matplotlib.pyplot as plt

graph = nx.Graph()

graph.add_nodes_from(['a', 'b', 'c'])
graph.add_nodes_from(['1', '2', '3', '4', '5', '6', '7', '8', '9'])
graph.add_edges_from([
    ('a', '1'), ('a', '2'), ('a', '3'),
    ('b', '4'), ('b', '5'), ('b', '6'),
    ('c', '7'), ('c', '8'), ('c', '9'),
])

plt.figure(figsize=(20, 10))
pos = nx.drawing.spring_layout(graph)

nx.draw_networkx_nodes(
    graph,
    pos,
    nodelist=['a', 'b', 'c'],
    node_color=['r', 'g', 'b'],
    node_shape='o',
)

nx.draw_networkx_nodes(
    graph,
    pos,
    nodelist=['1', '2', '3', '4', '5', '6', '7', '8', '9'],
    node_color=['r', 'r', 'r', 'g', 'g', 'g', 'b', 'b', 'b'],
    node_shape='v',
)

nx.draw_networkx_edges(graph, pos)
nx.draw_networkx_labels(graph, pos)

plt.show()
```

![index](https://user-images.githubusercontent.com/20728609/69020018-e8458700-0991-11ea-9a74-927dd243d5f6.png)

**Comment by MridulS** [comment]
I'll close this as we have a solution here already :)
