### ISSUE TITLE
[request] automatic access to node with maximum/minimum degree?

### ISSUE THREAD

**Issue by ayaanhossain** [networkx/networkx#2934]
Hi, is it possible to efficiently find the maximum degree or minimum degree node from an undirected graph, without traversing the nodes of the graph in the first place? If not, then is it maybe too much to ask for as a feature? Thanks.

**Comment by dschult** [comment]
If this is requesting that we compute the min and max degree as each node is added or removed then I'll just say that we aren't going to do that. Reopen if the request differs from that.
