### ISSUE TITLE
Treewidth Heuristic

### ISSUE THREAD

**Issue by Johannes-S** [networkx/networkx#2935]
We are a group of 8 students working on a project to improve graph libraries.
We first plan on implementing heuristics for an upper bound on the treewidth.
Many NP-complete problems can be solved efficiently if the treewidth is bound.
We are implementing a minimum degree based heuristic and a minimum fill-in heuristic.
They are described in section 4.3 in the paper linked below.
We can submit a pull-request probably within the next 2 weeks.

[https://dspace.library.uu.nl/bitstream/handle/1874/22171/2005-018.pdf](https://dspace.library.uu.nl/bitstream/handle/1874/22171/2005-018.pdf)

**Comment by dschult** [comment]
Fixed in #2951
