### ISSUE TITLE
Bug Report: problem when importing from pandas

### ISSUE THREAD

**Issue by nickmatheus** [networkx/networkx#2940]
Hi!

I was working with a adjacency matrix witch was a DataFrame of Pandas. There is a Networkx function capable of exporting a graph of this. But it never recognizes when the graph is directed. I tried even writing the optional condition, but or it turns a error or it creates a undirected graph.

The solution for me was exporting from pandas to numpy and using the nx function for numpy.

**Comment by dschult** [comment]
If you are not using at least NetworkX v2.1 you should upgrade  (See #2902) 
There was a bug in ```from_pandas_adjacency``` before NetworkX2.1
Was the trouble you are seeing with ```to_pandas_adjacency``` also fixed?
