### ISSUE TITLE
networkx.exception.NetworkXNotImplemented: not implemented for multigraph type

### ISSUE THREAD

**Issue by dragonxtek** [networkx/networkx#2947]
I have networkx 2.1 running on python3
I downloaded AttMpls topology from [here](http://www.topology-zoo.org/files/AttMpls.graphml) and I'm trying the following:

g = nx.read_graphml('AttMpls.graphml')
nx.shortest_simple_paths(g, '20', '14', 2)

but I get the following error:

> File "<decorator-gen-262>", line 2, in shortest_simple_paths
>   File "/usr/local/lib/python3.5/dist-packages/networkx-2.0.dev20170321173742-py3.5.egg/networkx/utils/decorators.py", line 71, in _not_implemented_for
>     raise nx.NetworkXNotImplemented(msg)
> networkx.exception.NetworkXNotImplemented: not implemented for multigraph type

**Comment by dschult** [comment]
You need to turn your ```MultiGraph``` into a ```Graph``` before calling ```shortest_simple_paths```.
If you just want ```shortest_paths``` you can use that instead. If you really want ```shortest_simple_paths``` then figure out how to handle any multiedges that might occur in your data.  One very simple way to handle them is to combine them into a single edge.

    G=nx.Graph(g)

**Comment by dragonxtek** [comment]
Thanks!
Do you know how to access quickly to paths generated?
I usually convert the output (class generator) to a list, but in this case, it takes more than a minute to convert from generator to list type.

g = nx.read_graphml('AttMpls.graphml')
G=nx.Graph(g)
paths=nx.shortest_simple_paths(G, '20', '14', 2)
paths_list=list(paths)  <-- It takes more than a minute to convert
path_list[0]  <-- show the first path

**Comment by dschult** [comment]
The generator is the fast way to access the paths.

    for path in nx.shortest_simple_paths(G,'20','14',2):
        # do something with the path

That way you don't have to hold all the paths in memory at once. 
If you create a list of all the paths, it will require a lot of memory/time.

**Comment by dragonxtek** [comment]
Thanks!
