### ISSUE TITLE
Finding paths in multigraphs

### ISSUE THREAD

**Issue by vporton** [networkx/networkx#2948]
https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.shortest_paths.generic.shortest_path.html refers to a "shortest path" algorithm implementation.

This algorithm is not suitable for multigraphs, as for a multigraph a path is not specified by a node list.

Please add multigraph version of this algorithm, which should return a list of edges, not a list of nodes.

**Comment by vporton** [comment]
Note that the same applies to `all_shortest_paths()` et al.

**Comment by vporton** [comment]
It may be better to implement it this way, but API should be easy to use, not be the multistage process which you described.

Specifically think about existence of several shortest paths in a multigraph. `all_shortest_paths()` should enumerate all of them.

**Comment by vporton** [comment]
Not quite understanding the usage of the English word "stab" here. Do you mean that you propose me to make a pull request?

We need first agree on the API.

I propose to add keyword argument `edges=` with boolean value (default `False`) to all relevant functions. When it is `True`, it could return a list of edges instead a list of vertices.

Agree?

**Comment by vporton** [comment]
@dschult You haven't answered my questions: Do you want me to work on pull req? Is it OK to add `edges=` with boolean value (default `False`) to all relevant functions? or do you propose another API?

**Comment by dschult** [comment]
I think it would be better to provide functions that convert lists of nodes to lists of edges.
Sorry I haven't had time to look at this more.

**Comment by vporton** [comment]
@dschult The very reason I requested the change is, that it is _impossible_ to convert lists of nodes to lists of edges for the case of a multigraph.

Please either solve this issue yourself or allow me to patch it. I need it for my application.

**Comment by dschult** [comment]
I thought we worked out that it is not impossible to convert lists of nodes to list of edges. You just need to find the shortest edge between each pair of nodes in the list. If there is more than one shortest edge then you have two shortest paths.  I think I am missing something...

**Comment by vporton** [comment]
1. I think it is a little more efficient to create the list of edges in the process of searching a path than to enumerate all edges between two nodes every time again.

1. If we follow my idea (`edges=True`) then it will work seamlessly for both regular graphs and multigraphs, producing either a single path or a set of paths. If we follow your idea, then it may be necessary (at least from the point of efficiency) to behave differently on regular graphs and multigraphs.

1. It seems that the simplest change in the code is what I propose not what you propose.

1. My idea is consistent through the entire set of shortest path finding functions, not sure about yours.

**Comment by vporton** [comment]
One more reason not to do it in your way:

I would be like (with a new function `nodes_to_edges()`):

    nodes = nx.shortest_path(G, source=0, target=4)
    edges = nx.nodes_to_edges(G, nodes)

This requires passing the value `G` two times. It is not quite good.

Well, one more reason:

`nx.nodes_to_edges()` would necessary have several variants: for one path, for a set of paths. It also would need to sometimes return a single path and sometimes a set of paths.

I think, I pointed enough reasons not to do it in two steps as you proposed.

**Comment by dschult** [comment]
I think you are optimistic and perhaps not realistic about how "seamless" or "efficient" this method would be. I think both methods could be consistent -- but it would take an incredible amount of work to make your method consistent across all the functions.  The maintenance effort required would rise too -- and that is a real concern for this project. 

Here's a compromise: you could rewrite the functions you intend to use in this way. Try to make the API for them easily extendable across all the shortest_path functions.  But mostly work to get it working for what you need.  You'll get working code and if it looks easy to use and not a maintenance drain then we can work to expand to the other functions.  I think that's what I mean by "take a stab at it".  Do enough to see how it will turn out (and solve your troubles even if it turns out to be too much for the package).

**Comment by vporton** [comment]
I insist on doing it in a single step rather than in two steps as you proposed.

I forked `networkx`, but I have an obstacle before I can begin work:

The module `networkx.algorithms.shortest_paths.unweighted` contains this function:

    def shortest_path(G, source=None, target=None, weight=None):

I wonder how `unweighted.py` can contain `weight` parameter. Please explain for me to be able to understand it and start working.

**Comment by vporton** [comment]
What concerning maintaining `networkx`, I consider to help you to do it, if you need help. Feel free to ask.

**Comment by dschult** [comment]
I think the shortest_path function is in ```networkx.algorithms.shortest_paths.generic```. The functions in unweighted.py do not have the weight argument.

**Comment by vporton** [comment]
You are right. Sorry for this stupid comment

**Comment by vporton** [comment]
After re-reading the specification of my application, I've realized that I do not need the set of all shortest paths from a given source to a given destination. I need only the first edges of such paths.

So what I was going to do before (enumerating all shortest paths in a multigraph) may be inefficient.

As such, I am going just to call `all_shortest_paths()` and after this enumerate only the first edges of the paths it returned.

So, I am not now involved into development of `networkx`. Sorry, I am more focused on my application not on your library. Goodbay @dschult
