### ISSUE TITLE
Should document the behavior for zero-weight edges

### ISSUE THREAD

**Issue by vporton** [networkx/networkx#2953]
How do "shortest path" family of functions behave on weighted graphs some of whose nodes have `weight=0`? It should be documented (now it isn't!) at https://networkx.github.io/documentation/stable/reference/algorithms/shortest_paths.html

I will describe the actual problem I am facing:

I have a set of "transformations" whose source and destination are finite sets of URLs.

A "chain" of transformations is a finite sequence `s_0 ... s_n` where `Dst s_i <= Src s_{i+1}` (`<=` denotes "is subset of"). I need to find shortest chain(s) of transformations with given source and destination of the chain.

My proposed solution is to add to the multidigraph of transformations nodes `(i, j, weight=0)` for every `i <= j` (may be a little inefficient but OK for the first version of my software). After the search is done, I remove nodes of this form.

Then I can reconstruct sequences `s_0 ... s_n` of transformations.

So, I face the question: May `networkx` ("stupidly" by human mind measure) add zero-weight nodes where they are non-necessary?

**Comment by dschult** [comment]
shortest_path ignores node weights. It looks at edge weights if requested to do so. 

So I guess the answer to your question is that zero-weight nodes are treated as regular nodes.
