### ISSUE TITLE
How PageRank for directed weighted graph works?

### ISSUE THREAD

**Issue by Ananthan-Rajasekharan** [networkx/networkx#2956]
Hai, 

I would like to know how PageRank for directed weighted graph works. The NetworkX PageRank can be used to calculate PageRank of a node in directed weighted graph. I am working on a project in which I give weighted graph to the algorithm, I would like to know, **based on which paper you guys do it.** Because it’s not mentioned in “Page, Lawrence; Brin, Sergey; Motwani, Rajeev and Winograd, Terry, The PageRank citation ranking: Bringing order to the Web. 1999”

Thanks

**Comment by ericmjl** [comment]
@Ananthan-Rajasekharan thanks for posting! I'm not 100% sure of the source myself, but I have dug out the source code that you can inspect: https://github.com/networkx/networkx/blob/master/networkx/algorithms/link_analysis/pagerank_alg.py

**Comment by Ananthan-Rajasekharan** [comment]
Thanks @ericmjl. But it  would have been great to know the source.

**Comment by dschult** [comment]
The pagerank is originally for directed graphs. The [Wikipedia PageRank page](https://en.wikipedia.org/wiki/PageRank) describes extensions as do many other sources. It would be difficult to pin down precisely which source was used to create this code. Most likely it was more than one source.
