### ISSUE TITLE
How to retrieve all paths of a source node without a target node

### ISSUE THREAD

**Issue by Skullflow** [networkx/networkx#2957]
Is there a way to retrieve all paths from a source node without passing a target node?

Now i'm using `all_simple_paths(G,source,target)` but i have to specify 2 nodes, and for my problem is not possible because i'm workin with very large graphs (from 10 MB to 50MB).

The target nodes are the leaves that are reachable starting from source node.

Thanks

**Comment by dschult** [comment]
This feature is not included directly from NetworkX.
Can you suggest an algorithm to implement?

If not, there may be a way to adjust the code from ```all_simple_paths``` or ```shortest_path```.
