### ISSUE TITLE
Could I use the module to draw a multiplex network?

### ISSUE THREAD

**Issue by shihangwen** [networkx/networkx#2958]
I want to draw a multiplex network, but previously I only used this module to draw a monoplex network. The graph which I want to draw likes this below:
![image](https://user-images.githubusercontent.com/13978535/39556654-61613976-4eb4-11e8-9e0b-62fc2fdf15e9.png)

**Comment by dschult** [comment]
This is certainly possible to draw if you can figure out the position of the nodes.
NetworkX doesnt currently restrict our position layout functions to preserve multiplex features.
If you want to implement it, or if you find an algorithm published somewhere, let us know.
