### ISSUE TITLE
Apply graph rotation with 90 degree and permutation

### ISSUE THREAD

**Issue by mazariahmed06** [networkx/networkx#2964]
Hello,

Now l would like to permute nodes and rotate the graph with (80°, 90°,120° degree)

How can l apply permutation and rotation on graphs with NetworkX ?

Given an adjacency matrix of a graph, l would like to rotate the graph in the way that it preserves the edges and vertices link. The only thing that changes is the position of nodes.

What l would like to do is to rotate my graph with 90 degree.

Input :

Adjacency matrix of graph G

process :

Apply rotation on G with 90 degree

Output :

Rotated adjacency matrix

It means, the graph preserves its topology and just the index of adjacency matrix that changes position.

For example nodes 1 at index 0 after rotation will be at index 4 for instance.

Thank you

**Comment by dschult** [comment]
It sounds like you are confusing the graph G with the positions of the nodes. By default, graphs don't store positions of the nodes -- though you can add them if you like.  The various layout functions create position dictionaries keyed by node to position vectors (usually 2-d). If you create a rotation matrix/array using numpy you can multiply that matrix by the position of each node to get the new positions.  No need to change the index of the node -- just operate on the position vectors.
