### ISSUE TITLE
Facilitate direct graphviz output

### ISSUE THREAD

**Issue by parthi2929** [networkx/networkx#2967]
Hi

I wanted to extract graphviz out of networkx and draw with neato engine. Currently afaik, networkx exports only to pygraphviz or pydot. 

pygraphviz has lot of installation issues (being 64 bit, unable to find and mend with installed graphviz 32-bit files [[1]](https://github.com/pygraphviz/pygraphviz/issues/132), graphviz not yet released official 64-bit [[2]](https://stackoverflow.com/questions/4571067/installing-pygraphviz-on-windows?rq=1), etc) Spent whole day trying to solve trying patches here and there which didnt help.

pydot is too limited, that not even able to draw the graphviz without writing down to a file the dot notation and reading via graphviz
```
P = nx.nx_pydot.to_pydot(G)
nx.nx_pydot.write_dot(G,'test.dot')                 # write to dot file
(graph,) = pydot.graph_from_dot_file('test.dot')    # read to dot file
print(graph)
```
This is currently buggy to be used with neato as explained in pydot thread [here](https://github.com/erocarrera/pydot/issues/174#issuecomment-387607404)

Given that, graphviz python API is directly available [here](http://graphviz.readthedocs.io/en/stable/manual.html), I strongly wish, I was able to export networkx directly to graphviz, and able to draw the diagram without above hassles.

Can you kindly help?

**Comment by dschult** [comment]
It would be reasonable to add a graphviz converter module the ```networkx/readwrite``` folder on NetworkX. To build such a conversion system you need functions to add nodes, add edges, get nodes and get edges from the graphviz structure. Having it work with the node and edge attributes would be important too.  If you can get that part of it done (maybe with some tests) and submitted as a PR I can help getting the rest of the structure and docs and so forth.  It's Ok if your tests are not in the right style for networkx. I'll change them. The important thing is to get the functaions that add/report nodes and edges.

**Comment by astrojuanlu** [comment]
@hagberg was this already implemented?

**Comment by hagberg** [comment]
As far as I know this hasn't been implemented.   It would be fairly simple to write something basic to just output nodes and edges (I wrote such a thing in 2002). As soon as you start thinking about more interesting features like labels, attributes, subgraphs/clusters, ports, etc it becomes complex.
