### ISSUE TITLE
How to find all paths to a node within n edges

### ISSUE THREAD

**Issue by hffqyd** [networkx/networkx#2978]
I'm wondering how I can use `networkx` to find all paths to a node within n edges. For example: 

```python
import networkx as nx
import matplotlib.pyplot as plt
% matplotlib inline

graph = nx.DiGraph()
nodes_list  = [1, 2, 3, 4, 5, 6]
edges_list  = [(1, 2), (1, 3), (1, 4), (2, 5), (3, 5), (3, 6), (4, 6)]
edge_length = [1 + 0.1*i for i in range(len(edges_list))]
for n in nodes_list: 
    graph.add_node(n)

for i, e in enumerate(edges_list): 
    graph.add_edge(*e)

nx.draw_networkx(graph)

```

![unknown](https://user-images.githubusercontent.com/10190817/40180710-094588d4-5a1a-11e8-9472-deea007526de.jpg)

Could I find all paths, as in this example the paths [[1, 3, 6], [1, 4, 6]], to node `6` within `2` edges?

Thank you very much!

**Comment by dschult** [comment]
See #2981 and #2975 
In summary, use the cutoff argument to all_simple_paths with more info in those answers.
