### ISSUE TITLE
How to get the list of all nodes

### ISSUE THREAD

**Issue by LiuQiang8650** [networkx/networkx#2980]
Recently,I have used a useful software named SCI2(Science of Science) created by Indiana University.From some python scripts of this software.I find command like `numbywork = g.nodes[:]`It attempts to make a copy of the list of all nodes in graph g.But when I tried something like that by `a = g.nodes[:]` It tell me "TypeError:unhashable type:'slice'".  
What I used is python3 and networkx 2.1.So I want to find someone knows about the python2 and earlier version of networkx to tell me how can command like `numbywork = g.nodes[:]` be run correctly. 
 
Somebody has told me that in earlier version of networkx g.nodes() can get the list of all nodes.But why can the command without brackets also work?

**Comment by CurtLH** [comment]
You can return the nodes in a network with the command `g.nodes` or `g.nodes()`.  The type of object that is returned is called a NodeView.  If you want the results to be returned as a list, you can either `list(g.nodes)` or `list(g.nodes())`.  If you want to save the list containing the nodes, and not just print it to the screen, you can use the command `nodes = list(g.nodes)`.

Refer to the documentation to learn more about [`g.nodes`](https://networkx.github.io/documentation/stable/reference/classes/generated/networkx.Graph.nodes.html)

**Comment by LiuQiang8650** [comment]
Thank you for your answer.But when I do the command like `node = list(g.nodes)` I just get a list with some numbers and lost the attributes of nodes.Later,I find the command like `nodes = list(g.nodes(data=True))`And I just wonder if the command like `a = g.nodes[:]` correct in python2 and earlier version of networkx.I need a answer of YES or NO?I think just the `g.nodes` can not be a list and can not be sliced.But that seems to be right from the command in SCI2's python script.

**Comment by LiuQiang8650** [comment]
Thank you for everyone.I have used a method to know something.

I used print type(g)and print type(g.nodes)and found something like the picture. the type of g and g.nodes
So this is created by Jython which combine python and Java and it is not an object of networkx.
Okay,now I can convince myself.

Thanks for everyone again!

**Comment by LiuQiang8650** [comment]
Thank you for everyone.I have used a method to know something.

I used `print type(g)`and `print type(g.nodes)`and found something like the picture. the type of g and g.nodes
So this is created by Jython which combine python and Java and it is not an object of networkx.
Okay,now I can convince myself.

Thanks for everyone again!

**Comment by CurtLH** [comment]
I'm glad to hear you got what you need.  If this complete, please consider closing the issue.
