### ISSUE TITLE
All simple paths having weight less than a given weight in a directed graph

### ISSUE THREAD

**Issue by ajay2611** [networkx/networkx#2981]
Hi,

I need a variant of `all_simple_paths` where I need all paths between two nodes of a directed weighted graph which has a path-weight less than given weight `k`. I think this must have been already implemented in Networkx but I'm not able to find that.

Please let me know if this functionality is built or do I need to write this on my own. Thanks.

**Comment by dschult** [comment]
I believe the ```cutoff``` argument to ```all_simple_paths``` is what you are looking for.

**Comment by ajay2611** [comment]
`cutoff` argument checks for the number of edges. I need to check the weight of path so far.

**Comment by ajay2611** [comment]
Okay. I'll probably write it on my own. Thanks @dschult
