### ISSUE TITLE
Minimal of a value of edges of a path

### ISSUE THREAD

**Issue by vporton** [networkx/networkx#2988]
I need to find all paths with highest (among all paths) minimal "preservance" along the path of a given multidigraph starting from a given node and ending with a given node.

"Preservance" is a numeric characteristic of an edge (like weight, but different).

It is like finding the shortest path, but instead to take a sum of weights I take the minimum of preservances.

Maybe a method to do this already exists, but I can't find a reference to it in https://networkx.github.io/documentation/latest/reference/algorithms/shortest_paths.html - In this case, it is a documentation bug. That page should refer to this algorithm.

**Comment by dschult** [comment]
Hmm...   Maybe I am misunderstanding, but isn't this:

    p=nx.shortest_path(G, source, target, 'preservances')

**Comment by dschult** [comment]
Ahh... now I understand better.  I think you will need to build your own version of Dijkstra for this. It would be cool to submit it as a Pull Release for inclusion in NetworkX.  I haven't checked this definitively, but my basic idea is to invert(i.e. reciprocate) the edge weights (preservances) and then find the minimal maximum. To find the "minimal maximum" use a version of djikstra which replaces addition with maximum. The code in networkx/algorithms/shortest_paths/weighted.py:729-819 should do it with the only change on line 798.

You could also create a number class where addition is overwritten as maximum and store all preservances as that class, but that seems like overkill.

**Comment by vporton** [comment]
@dschult Hm, probably I should not make a pull req for NetworkX for my algorithm. The reason is the following:

I need a list of edges in a (directed) multigraph not list of nodes.

Remember our discussion of shortest path algorithms modifies to return list of edges rather than list of nodes? You concluded that this is not feasible to fully implement and maintain now.

For my purposes however, it is feasible to implement it for list of edges rather than nodes, what would by not in "theme" of NetworkX, and thus it probably should remain only in my application rather than pushed back into NetworkX.

Your opinion?

**Comment by vporton** [comment]
Also it is unclear what should be the API for both "maximum of minima" and "minimum of maxima".

**Comment by dschult** [comment]
Good points -- though I don't think it is all that critical whether the end result is a list of edges or a list of nodes -- so long as it is consistent within the package and easy for people to write short code to convert if they want. 

As far as API for maxl min or minl max, I would guess its best to write one of them and have the user convert their edge attributes (using presumably easy functions to write that do that -- like get/set_edge_attributes?). But that's my bias -- there may be a cool organization for functions that do either.
