### ISSUE TITLE
from_pandas_dataframe() not working for MultiGraph and  MultiDiGraph in version 1.11

### ISSUE THREAD

**Issue by avineet07** [networkx/networkx#2989]
`G=nx.from_pandas_dataframe(df,'Start Node','End Node',edge_attr= True,create_using=nx.MultiDiGraph())`
gives the following error:

`C:\ProgramData\Anaconda2\lib\site-packages\networkx\convert_matrix.pyc in from_pandas_dataframe(df, source, target, edge_attr, create_using)
    209         # Iteration on values returns the rows as Numpy arrays
    210         for row in df.values:
--> 211             g.add_edge(row[src_i], row[tar_i], {i:row[j] for i, j in edge_i})
    212 
    213     # If no column names are given, then just return the edges.

C:\ProgramData\Anaconda2\lib\site-packages\networkx\classes\multidigraph.pyc in add_edge(self, u, v, key, attr_dict, **attr)
    342             datadict.update(attr_dict)
    343             keydict = self.edge_key_dict_factory()
--> 344             keydict[key] = datadict
    345             self.succ[u][v] = keydict
    346             self.pred[v][u] = keydict

TypeError: unhashable type: 'dict'`

Adding the argument 'edge_attr' in the case of MultiGraph and MultiDiGraph leads to this error but not for other Graph types

**Comment by dschult** [comment]
I believe the API changed from v1 to v2 of NetworkX.
With a newer version you should use ```nx.from_pandas_edgelist``` instead of ```nx.from_pandas_dataframe``` but at least it ought to work. :)

Are you using a version of NetworkX from v1.11 or earlier?  ```print(networkx.__version__)```

**Comment by avineet07** [comment]
Yes I'm using v1.11. Upgrading to v2 seems to be a workaround,
