### ISSUE TITLE
"nondeterministic" behavior (migrated from Trac #300)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#299]
Original ticket https://networkx.lanl.gov/trac/ticket/300
Reported 2009-12-22 by @chebee7i, assigned to unknown.

I'm trying to write some unit tests for in converting networkx graphs to pygraphviz graphs.  There are probably other ways of testing, but I am now curious about the behavior I was seeing.

Essentially, the string representation of the graph is not constant and seems to fluctuate.  Is there anyway this can be made "deterministic"?  That is, if the graph's nodes/edges are created in the same order each time, then the string representation of the graph should be the same each time as well.

Currently, this does not appear to be the case.  Is this because the underlying graphviz implementation is using an unordered data structure?  Strangely, if you run the code sample below multiple times, you get "deterministic" behavior.  That is, it will fail on the same iteration EACH time (or so it seems).  The exact iteration it fails on seems to depend on the system, the file size, or something else....try, for example, to add "import os" at the top of the code snippet.  For me, it failed (repeatedly) on iteration 2 with the import. Without the import, it failed (repeatedly) on iteration 4.

'''
import pygraphviz

i = 0
x = None
while i < 50:
    i += 1
    print i

```
g = pygraphviz.AGraph(directed=True)
g.add_edge(0,1)
g.add_edge(0,2)
g.add_edge(2,1)
y = g.to_string()

if x is not None:
    if x != y:
        print x
        print 
        print y
        break

x = y
```

'''

**Comment by hyanwong** [comment]
There is hidden non-determinism with clusters in graphviz: https://forum.graphviz.org/t/clustering-gives-undeterministic-results/989

**Comment by dschult** [comment]
Yes, this is a known behavior in graphviz (as stated in the link you provide).
Is there anything we should know or do about this? Or is this comment to help people who come to this closed issue looking for a reason why it isn't deterministic?

**Comment by hyanwong** [comment]
For us, this issue seemed to be resolved by using pydot rather than pygraphviz. From that issue, I'm unclear as to why this should be, but it might be helpful to others who face the same problem.

**Comment by rossbar** [comment]
I'm going to re-close this one as I don't think there's anything to be done about it in NetworkX. The [underlying graphviz issue](https://gitlab.com/graphviz/graphviz/-/issues/1789) is well-known and there's [quite a bit of discussion](https://forum.graphviz.org/t/clustering-gives-undeterministic-results/989) on the topic.

While the "use-pydot-instead" approach may skirt this issue, users may run into other pydot issues so YMMV - I don't think it's recommended given that the plan is to remove `nx_pydot` in the future #5723.

Aside from adding a warning to the docs somewhere in `nx_agraph`, I don't think there's any obvious workarounds we could implement in networkx itself. If there are concrete suggestions please feel free to re-open this, preferably with an accompanying PR.

**Comment by hyanwong** [comment]
A warning would be good, thanks.
