### ISSUE TITLE
Shortest path from any of multiple destinations

### ISSUE THREAD

**Issue by vporton** [networkx/networkx#2992]
I need to find the set of shortest paths from any of s1, ..., sN to d.

I think, it would be good to have direct support for this (multiple sources and/or destinations while searching for a shortest path) in NX.

**Comment by dschult** [comment]
Take a look at ```multi_source_dijkstra```.   Maybe there would be a way to get a similar framework for the unweighted shortest_path functions too.

**Comment by dschult** [comment]
Reopen if this is still of interest...
