### ISSUE TITLE
graph edit distance doesn't work for non-large special, but not circular example

### ISSUE THREAD

**Issue by kleinias** [networkx/networkx#2997]
I stumbled about it, the programe doesn't come to end.
That's some minimal example:

> 
> #!/usr/bin/env python
> import networkx as nx
> import time
> 
> g1 = nx.Graph()
> g1.add_edges_from([(5, 4), (5, 6), (5, 7), (21, 8), (2, 1), (2, 0), (5, 3)])
> g2 = nx.Graph()
> g2.add_edges_from([(15, 13), (23, 16), (23, 24), (100, 7), (18, 19), (100, 23), (19, 20), (22, 21)])
> 
> start_time = time.time()
> print "starting"
> dst = nx.graph_edit_distance(g1, g2)
> print('  GED={0} took {1:.2f} seconds'.format(dst, time.time() - start_time))

**Comment by aparamon** [comment]
Hi @kleinias , 
probably you'll have more luck with `optimize_graph_edit_distance`.

**Comment by dschult** [comment]
Any resolution here?  Should we change the docs somewhere to suggest trying the optimize version of the function? Should we just close this? What do you suggest?

**Comment by aparamon** [comment]
@dschult I believe the procedure should **ultimately** work for the particular example, quickly.

However, **current** algorithm/implementation is sub-optimal, for this example. Moreover, I'm pretty sure it will always be possible to find an example for which exact GED calculation is slow, as it's NP-hard. So, `optimize_graph_edit_distance` will always have it's uses. The algorithm interface was designed to be both simple (`graph_edit_distance`) and flexible (`optimize_graph_edit_distance`/`optimize_edit_paths`), and if the simple interface doesn't yield good results, one has to go a bit deeper.

**Comment by dschult** [comment]
That's a great summary. Maybe I'll try to put a paragraph "docstring" for the module (at the top) that simply says what you jut said. That way people know a little more which functions to try. I'll take a stab at the difference between optimize_edit_paths and optimal_edit_paths too.
