### ISSUE TITLE
nx.write_gpickle fails when supplied a filepath string as a destination

### ISSUE THREAD

**Issue by zfrenchee** [networkx/networkx#3012]
The docs state that the `write_gpickle` function can be supplied a filepath:

[`write_gpickle`  docs](http://jfinkels-networkx.readthedocs.io/en/latest/reference/readwrite/generated/networkx.readwrite.gpickle.write_gpickle.html): 

Parameters: | graphpath (file or string)  – File or filename to write. Filenames ending in .gz or .bz2 will be compressed.protocol (integer) 
-- | --

But in practice, this causes an error: 

```
  File "/usr/local/lib/python3.6/site-packages/networkx/readwrite/gpickle.py", line 70, in write_gpickle
    pickle.dump(G, path, protocol)
TypeError: file must have a 'write' attribute
```

I'm using networkx 2.0:

```
>>> nx.__version__
'2.0'
```

Responsible line: 

https://github.com/networkx/networkx/blob/e97abea688a471a8422a676ea7c93d079bfa0f1f/networkx/readwrite/gpickle.py#L70

`pickle.dump` requires a file object, not a filepath. [python docs](https://docs.python.org/3/library/pickle.html#pickle.dump)

However, it would be nice if networkx took a filepath instead of a file object, most higher-level libraries support this, I believe. So it may make sense to add an `open(file)` in networkx, if `file` isn't a file object. 

It may also be nice to add tests to these functions, since this is the sort of thing a simple test would have picked up.

**Comment by dschult** [comment]
This commit https://github.com/networkx/networkx/commit/b7af06af9ecd885c3b311520cc01ded673987083 added exactly that capability to NetworkX.  Though it didn't make it into the v2.0 release. It is in v2.1 and also in the latest code.

**Comment by dschult** [comment]
Also -- be careful with the docs -- you are reading an old version from jfinkels fork of the readthedocs webpage.  You should get the docs from networkx.github.io
