### ISSUE TITLE
nx.from_pandas_edgelist() iterates over DataFrame.values which changes dtypes

### ISSUE THREAD

**Issue by zfrenchee** [networkx/networkx#3013]
I arrived here through:

```
>>> df = pd.DataFrame([[1, 2, '0.1']], columns=['source', 'target', 'other'])
>>> nx.from_pandas_edgelist(df).nodes()
NodeView((1, 2))

>>> df = pd.DataFrame([[1, 2, 0.1]], columns=['source', 'target', 'other'])
>>> nx.from_pandas_edgelist(df).nodes()
NodeView((1.0, 2.0))
```

I initially thought this would be an issue with [`from_pandas_edgelist`](https://github.com/networkx/networkx/blob/9ac4941c1cb25bf47c85d2bb19f7557f5c807694/networkx/convert_matrix.py#L241) but that code just hands off directly to add_edge:

https://github.com/networkx/networkx/blob/9ac4941c1cb25bf47c85d2bb19f7557f5c807694/networkx/convert_matrix.py#L346-L350

which means that [Graph().add_edge](https://github.com/networkx/networkx/blob/e97abea688a471a8422a676ea7c93d079bfa0f1f/networkx/classes/graph.py#L812-L874) must be responsible.

This is in networkx version 2.1

**Comment by zfrenchee** [comment]
Update: This is happening before `Graph.add_edge()`

I changed the lines in convert_matrix to:
```
    else:
        for row in df.values:
            print(row)
            print(row[src_i])
            print(row[tar_i])
            print(type(row[src_i]))
            print(type(row[tar_i]))
            g.add_edge(row[src_i], row[tar_i])
```

and I'm seeing the types change before g.add_edge. That means this is an issue with `from_pandas_edgelist` or maybe... (gasp) an issue with pandas?

**Comment by dschult** [comment]
This "feature" is documented in both networkx and pandas. It involves ```DataFrame.values``` using a flexible type for numeric values.   From [the docstring for](https://networkx.github.io/documentation/stable/reference/generated/networkx.convert_matrix.from_pandas_edgelist.html) ```nx.from_pandas_edgelist```:

    Note: This function iterates over DataFrame.values, which is not
    guaranteed to retain the data type across columns in the row. This is only
    a problem if your row is entirely numeric and a mix of ints and floats. In
    that case, all values will be returned as floats. See the
    DataFrame.iterrows documentation for an example.

**Comment by zfrenchee** [comment]
And could you explain why networkx iterates over `.values`? the docstring only lists the disadvantage. It seems like my issue could be fixed by iterating over the dataframe another way than `.values`

**Comment by zfrenchee** [comment]
Ahh, I see the pandas docs: It's documented right with [df.values()](http://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.DataFrame.values.html)

**Comment by zfrenchee** [comment]
@dschult why networkx iterates over `.values`?

**Comment by dschult** [comment]
That's the way to iterate over the matrix of values in the dataframe. Other suggestions?

**Comment by zfrenchee** [comment]
1M edges: 
```
CPU times: user 2.76 s, sys: 83.7 ms, total: 2.85 s
Wall time: 2.85 s
```
vs
```
CPU times: user 6.9 s, sys: 330 ms, total: 7.23 s
Wall time: 7.23 s
```
And 10M edges:
```
CPU times: user 28.1 s, sys: 211 ms, total: 28.3 s
Wall time: 28.3 s
```
vs
```
CPU times: user 1min 13s, sys: 7.86 s, total: 1min 21s
Wall time: 1min 22s
```
Looks like a consistent factor of 3.

**Comment by zfrenchee** [comment]
@dschult here's a slightly messy, but faster way to do it: 
```
n = 1000000  # 1M edges
df = pd.DataFrame(np.random.randint(0,1000,(n,2)),columns=['source','target'])
```
```
%%time
nx.from_pandas_edgelist(df)
```
```
CPU times: user 2.58 s, sys: 59.5 ms, total: 2.64 s
Wall time: 2.64 s
```
```
%%time
g = nx.Graph()
[g.add_edge(s,t) for s,t in zip(df['source'], df['target'])]
```
```
CPU times: user 2.03 s, sys: 82.8 ms, total: 2.12 s
Wall time: 2.12 s
```

**Comment by dschult** [comment]
You shifted from testing that it worked to testing its speed.  But assuming all the above works, could you put together a PR with the improved version?  Thanks!

**Comment by zfrenchee** [comment]
@dschult #3068
