### ISSUE TITLE
spam link in the testing version documentation

### ISSUE THREAD

**Issue by katthomp** [networkx/networkx#3022]
Hi! There's a spam link in the testing [package documentation](https://networkx.github.io/documentation/networkx-1.10/test.html#testing-an-installed-package). 
The somethingaboutorange site is not a documentation page. Thanks.

**Comment by dschult** [comment]
The documentation you link to is for version 1.10 of NetworkX.  That link is clearly being used for other purposes now.

The [link to testing documentation](https://networkx.github.io/documentation/stable/install.html#testing) shows the correct link for nose software:  https://nose.readthedocs.org/

**Comment by dschult** [comment]
This might be improved with #2730 solved. But Im going to close this issue. We won't be updating links on old documentation pages.  Thanks for letting us know...
