### ISSUE TITLE
all_node_cuts misses some cuts

### ISSUE THREAD

**Issue by rrssl** [networkx/networkx#3025]
I'm using networkx 2.1 with python 3.5.2. Here's a simple case that seems to fail ('b' is missing):

```
G = nx.Graph()
G.add_edges_from(['ab', 'bc', 'cd', 'de'])
list(nx.all_node_cuts(G))
>>> [{'d'}, {'c'}]

```
If I keep adding nodes, more are missing:
```
G.add_edges_from(['ab', 'bc', 'cd', 'de', 'ef', 'fg'])
list(nx.all_node_cuts(G))
>>> [{'d'}, {'c'}, {'e'}]
```

**Comment by dschult** [comment]
I can verify that with networkx dev and python 3.6 the same trouble occurs (although it isn't always the same node).  Also, it doesn't happen with the isomorphic ```path_graph(5)``` where the nodes are integers. So the bug has something to do with nodes being strings.

**Comment by wuhaochen** [comment]
I have read the paper and code carefully and I'm not sure the implementation follows the algorithm described in the paper closely.

In particular, I don't understand why antichains map to closed sets in:
[https://github.com/networkx/networkx/blob/master/networkx/algorithms/connectivity/kcutsets.py#L153](url)

I'm also not sure why the cycle graph need to be addressed separately. [https://github.com/networkx/networkx/blob/master/networkx/algorithms/connectivity/kcutsets.py#L92](url)

It seems that @jtorrents wrote the code originally. Could you take a look? Thanks.

**Comment by wuhaochen** [comment]
It also seems that we don't have a function for [Closure](https://en.wikipedia.org/wiki/Closure_problem). It might be a good time to implement it if it's the case.

**Comment by jtorrents** [comment]
@rrssl thanks for reporting this bug, and thanks @wuhaochen for looking at this closely.

It could be that the implementation does not follow the algorithm described in the paper closely enough. So far we have only encountered corner cases (like cycles and path graphs) in which the implementation fails to report the correct results. I think it would help to have a non trivial case in which we miss a cut.

The reasoning behind special casing cycles was that all cuts are easily computed without using the fancy algorithm, and is quite faster. The same could be said for path graphs but this might be a clue that the implementation is not good enough.

Regarding why antichains map to closed sets, the author of the algorithm assumes this is so, and cites as authoritative sources: 

J. C. Picard, M. Queyranne, "On the structure of all minimum cuts in a network and applications,"
Mathematical Programming Study 13,1980, pp. 8-16.

M. O. Ball, J. S. Provan, "Calculating bounds on reachability and connectedness in stochastic net­
works," Networks, vol. 13, 1983, pp. 253-278. 

When implementing this, a while ago, I found the extended report [kavensky_kcutsets.pdf](https://github.com/networkx/networkx/files/2138305/kavensky_kcutsets.pdf) very useful, as it's more detailed than the paper.

In any case, implementing a function for Closure, would be a great addition to NetworkX and might help with this algorithm. I don't have much time right now to look at this closely, so if you can try to figure out what is the problem with the implementation, that would be great. If not, I'll try to work on it in the coming weeks.

**Comment by wuhaochen** [comment]
Thank you. I found several places that need to be fixed and I'm finalizing them now.

We do have a function to compute the transitive closure so I don't think we need another function for  closures.
