### ISSUE TITLE
Width canvas

### ISSUE THREAD

**Issue by Signorini** [networkx/networkx#3026]
I try to find into documentation where I can set canvas size. Its possible to set this type of configuration?

The problem is, my chart are very crowded because the canvas always is created with the same width.

 my config is:
options = {
    'with_labels': True, 
    'font_weight': 'bold', 
    'cmap': plt.cm.Blues, 
    'arrowsize': 30, 
    'node_shape': 's',
    'node_size': 1500,
    'node_color': 'skyblue',
    'font_color': 'white',
    'alpha': 0.5,
    'linewidths': 40,
    'height': 6000
}
pos=graphviz_layout(G,prog='dot', root='root')
nx.draw(G, pos, **options)
plt.savefig("path.svg")

thanks

**Comment by JasperNL** [comment]
You need the option figsize in options: https://matplotlib.org/api/_as_gen/matplotlib.pyplot.figure.html
For example: 'figsize' = (30, 30)

**Comment by dschult** [comment]
Setting the canvas size for use with matplotlib is a matplotlib feature.
You can use their functionality -- or if you prefer, you can scale the values in ```pos``` in your code. (Scaling the values of ```pos``` will likely show the same picture unless you turn off the automatic choice of canvas size done by matplotlib.)
