### ISSUE TITLE
Travis nbconvert giving error

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#3030]
We are building the docs on Travis and converting the examples to Jupyter notebooks for the gallery. (This is using python2.7).  It started showing [a new error this weekend](https://travis-ci.org/networkx/networkx/jobs/396510217)  It looks like libpng is not behaving nicely. I'm not sure where to look for answers to this one.

**Comment by dschult** [comment]
@jarrodmillman do you have time to look at the travis doc-build errors that started about 3 days ago? Even some quick tips on how to go about debugging it would be really helpful.  Thanks!   :)

**Comment by jarrodmillman** [comment]
I'll take a look later today (at this and a couple other outstanding items).
