### ISSUE TITLE
Remove or improve create_using argument

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#3036]
In #1393 we started to formulate an API that would remove the ```create_using``` keyword in favor of generating (or passing around) ```(edges, nodes)``` pairs. 

A first step was #3028 which added a base class method to add nodes and edges to a graph. This allow ```G.update(generate_path(9))``` so long as ```generate_path``` creates any of:

- ```edgelist```
- ```(edges, nodes)```  tuple
-  a graph object

With the update method present, we can remove the ```create_using``` argument and document that people should replace the idiom:

    G = nx.path_graph(9, create_using=nx.MultiGraph)

with: 

    G = nx.MultiGraph().update(nx.path_graph(9))
    # we might be able to change the constructor to allow nx.MultiGraph(nx.path_graph(9))

We might also consider changing the generators to yield edges or return (edges, nodes).  This could become a v3.0 feature, but for now I'm putting v2.3 as the milestone.

Reread the discussion in #1393 and then discuss here what the design should be.  :)

**Comment by leotrs** [comment]
Is this issue open to anyone for comment? If so, before I can contribute to this conversation, there's something I may be missing. What is the expected difference between
```
G = nx.MultiGraph().update(nx.path_graph(9))
```
and
```
G = nx.MultiGraph(nx.path_graph(9))
```
?

**Comment by dschult** [comment]
Arguments to ```MultiGraph``` currently can include many container types. It can be a graph, or a list of edges, or a dict-of-lists adjacency or dict-of-dict, etc. Many possibilities. 

The update method allows adding to an already existing graph.

Both constructions depend on what ```nx.path_graph(9)``` returns. If it is returning a graph, then we are creating a ```Graph``` which then gets read to create the ```MultiGraph```.  That seems wasteful especially with large digraphs, or even large graphs that someone wants to store as a subclass of Graph.

**Comment by leotrs** [comment]
Thanks, I understand now that the main advantage of `update` is that it can be called on an already existing graph. And I understand that the point of this issue is to get rid of `create_using`. However, I still don't understand why the documentation would encourage `G = nx.MultiGraph().update(nx.path_graph(9))` over `G = nx.MultiGraph(nx.path_graph(9))`. 

Apologies if I'm becoming an obstacle in the development of this issue. I just want make sure I'm up to speed in the conversation before working on a PR.

**Comment by dschult** [comment]
The first case (update) was what I was working on when I wrote that and the comment was a realization that we could make the constructor work directly. So you are seeing some of the evolution of the ideas.  The bulk of the good new ideas are in #1393 so look there for the background.

Personally I don't like either of those two sentences because (reading left to right) it makes the writer think in backwards order. I generally think: I want a path_graph...  that is also a multigraph.  But that may be my habits formed from function arguments. Similarly the reader may find it easier to identify that this is a path_graph using the current syntax: 

    nx.path_graph(9, create_using=nx.MultiGraph)

I guess its easier to see that it is a multigraph of some sort using

    nx.MultiGraph(nx.path_graph(9))

But perhaps the biggest decision to be made is whether ```nx.path_graph(9)``` should return a graph or some sort of generator that can form a graph.

**Comment by boothby** [comment]
I've read over this thread and those feeding into it, and the notion of returning `(nodes, edges)` does sound quite nice.  However, when I want to use networkx as a "desk calculator for graphs", I want the very nice `nx.complete_graph`, `nx.path_graph`, etc to work as expected.

I propose that this could be accomplished through a couple decorators, which could be adopted gradually -- a big patch initial decorating all existing generators with `@graph_generator` would immediately support the notation `nx.complete_graph.nodes_and_edges(...)` without impacting existing code, and later generators could use `@node_and_edge_generator`.   I haven't given much thought to this naming; bikeshedding (and other comments) very welcome.

```
def node_and_edge_generator(f):
    @wraps(f)
    def graph(*args, **kwargs):
        nodes, edges = f(*args, **kwargs)
        g = nx.Graph(nodes)
        g.update(edges = edges)
        return g
    graph.nodes_and_edges = f
    return graph

def graph_generator(f):
    @wraps(f)
    def nodes_and_edges(*args, **kwargs):
        g = f(*args, **kwargs)
        return g.nodes(), g.edges()
    f.nodes_and_edges = nodes_and_edges
    return f

@node_and_edge_generator
def path_graph(n):
    """an overly simplified path graph implementation"""
    return range(n), list(zip(range(n-1), range(1, n)))

@graph_generator
def complete_graph(n):
    """an overly simplified complete graph implementation"""
    g = nx.Graph(range(n))
    g.update(edges = list(itertools.combinations(range(n), 2)))
    return g
```

**Comment by dschult** [comment]
Wow -- this sounds nice!   
So, let me see if I understand.  Each graph generator (say, path_graph) could be used like:
```python
nodes, edges = path_graph.nodes_and_edges(4)
G = path_graph(4)
MG = nx.MultiGraph()
MG.update(*path_graph.nodes_and_edges(4))
# or if we change update to return the graph
MG = nx.MultiGraph().update(*path_graph.nodes_and_edges(4))
# or if we change the constructor to use update
MG = nx.MultiGraph(path_graph.nodes_and_edges(4))
```

This last line becomes the way to create a MultiGraph path graph.  That is,
```MG = nx.path_graph(4, create_using=nx.MultiGraph)``` becomes
```MG = nx.MultiGraph(path_graph.nodes_and_edges(4))```

This suggestion makes me think bigger...   
I'd love to get to: (maybe with some ```__getattr__``` magic, or a GraphGenerator class)
```n, e = path_graph.nodes_and_edges(4)```      maybe renamed path_graph.parts(4)?
```MG = path_graph.MultiGraph(4)```               Graph/DiGraph/MultiGraph/MultiDiGraph available
```CG = path_graph.CustomGraph(4)```                CustomGraph available if name in globals?

Let's think big:   What is the best way to have people ask for a path_graph that is a multigraph? 
I think @boothby magic can get us there...   :}

**Comment by boothby** [comment]
> Graph/DiGraph/MultiGraph/MultiDiGraph available
`CG = path_graph.CustomGraph(4)` CustomGraph available if name in globals?

Oooh, that *is* magic.  Scary magic.  I was pondering if such a syntax would work, and hadn't thought of `__getattr__`'s visibility into globals.

Fleshing out my original thought a bit more, I intended for decorators to use `create_using` as you mention -- `nx.path_graph(4, create_using = nx.MultiGraph)`.

But let's play!

```
from functools import partial as _partial, wraps as _wraps
import networkx as nx

graph_class_names = {'DiGraph', 'Graph', 'MultiDiGraph', 'MultiGraph', 'OrderedDiGraph', 'OrderedGraph', 'OrderedMultiDiGraph', 'OrderedMultiGraph'}

graph_classes = {name: eval('nx.{}'.format(name)) for name in graph_class_names}

class graph_parts:
    def __init__(self, gen):
        self._gen = gen
        self.__default__ = self.Graph

    def __call__(self, *a, **k):
        return self.__default__(*a, **k)

    def __creator__(self, create_using):
        @_wraps(self._gen)
        def create(*a, **k):
            n, e = self._gen(*a, **k)
            g = create_using()
            g.update(nodes = n, edges = e)
            return g
        return create

    def __getattr__(self, name):
        try:
            gclass = eval(name)
        except NameError:
            if name in graph_class_names:
                gclass = graph_classes[name]
            else:
                raise
        return self.__creator__(gclass)

@graph_parts
def path_graph(n):
    """basic docstring for a very basic graph"""
    return range(n), zip(range(n-1), range(1, n))

if __name__ == "__main__":
    print(list(path_graph(5).edges())) # good
    print(path_graph.__doc__) # nope! but IPython figures it out somehow
    print(list(path_graph.MultiGraph(5).edges())) # good
    print(path_graph.MultiGraph.__doc__) # good
```

However things go awry when you use this from another module:

```
import networkx as nx

if __name__ == "__main__":
    CustomGraph = nx.Graph
    p5 = nx.path_graph.CustomGraph(5) # boom, NameError
```

However, I do notice that `Graph` et al do not support `Graph(callable)` in general.  I think that similar shenanigans could be used here: `MultiGraph(path_graph)` could return a function or class; supporting the oddish notation `MultiGraph(path_graph)(5)` but it would probably break a lot of code that depends on knowing the type `nx.Graph` etc.

The signatures for `Graph`, etc., already take keyword arguments, which are passed into the `g.graph` dictionary, so I'm disinclined to overload that behavior with something like `MultiGraph(path_graph, 5)`

But!  Python's system for custom codecs gives me an idea.  If we return to the `path_graph.CustomGraph` issue... there's a solution in sight.  We need only add a system to register new graph classes:

```
graph_classes = {name: eval('nx.{}'.format(name)) for name in graph_class_names}

def register_graph_class(graphclass):
    graph_classes[graphclass.__name__] = graphclass
```

```
import networkx as nx

if __name__ == "__main__":
    class CustomGraph(nx.Graph): pass
    nx.register_graph_class(CustomGraph)
    p5 = nx.path_graph.CustomGraph(5) # good!
```

**Comment by dschult** [comment]
For ```path_graph.CustomGraph``` we might be trying too hard...
Maybe it would be simpler just to create a function attached to the "graph generator" path_graph (is "graph generator" a reasonable name?) like this:
```python
nx.path_graph.CustomGraph(MyCustomGraphClass, 4)
```
where we peel off the first argument to CustomGraph, use it to construct an empty graph we then fill using the rest of the arguments.

I'm starting to think of a graph generator object that has attributes .Graph, .DiGraph, .MultiGraph, .MultiDiGraph, .nodes_and_edges, .CustomGraph, .sparse_matrix (??maybe?).  It could be created by decorators of functions that create edge lists, functions that create edges, nodes 2-tuples or functions that create networkx graphs.  It doesn't have to be a class itself, but maybe it should be to define the API more.

**Comment by boothby** [comment]
That's a nice idea with a nice solution.  My preliminary implementation had a `__creator__` private method, which provides precisely the functionality of your `CustomGraph` method above.  What do you think of this?

``` python
class graph_generator:
    ...
    def create_using(self, graph_class): # was __creator__
        @_wraps(self._gen)
        def create(*a, **k):
            return self._gen(*a, create_using = graph_class, **k)
        return create

    def __getattr__(self, name):
        if name in graph_classes:
            gclass = graph_classes[name]
        else:
            raise TypeError("Unknown graph class name.  Please use the create_using method of this object.")
        return self.create_using(gclass)
```

Then, we support `path_graph.MultiGraph(5)` and `path_graph.create_using(CustomClass)(5)` (is this preferable to `path_graph.create_using(CustomClass, 5)`?  I'm leaning away from that).

Note that I've left some details out; namely `return self._gen(*a, create_using = graph_class, **k)` is written with the expectation that `_gen` is wrapped in an appropriate decorator.  I'll have to think about how we could support things like `path_graph.sparse_matrix`, but I've finished my breakfast and it's time for the day job.

**Comment by dschult** [comment]
I believe #4254 shows some additional evidence that it would be good to have a class-agnostic representation of a graph.  The binary operators could return a graph generator.

One possible graph representation in the model of ```edges_and_nodes``` uses a sequence of nodes, edges and attributes as follows (based on length and on dict-like object-type). The sequence contains tuples and dicts, each of which are processed independently.

```
if dict-like:  Graph Attribute -> use G.graph.update() 
if length 1, not dict-like:     isolated node
if length 2, 2nd dict-like:     isolated node + data 
if length 2, 2nd not dict-like: edge 2-tuple 
if length 3, 3rd dict-like:     edge + data 
if length 3, not dict-like:     multiedge with key 
if length 4, 4th dict-like:     multiedge with key
```

An example sequence: 
```python
graph_stream = [{'name'="fred"}, (c,), (a, b), (d, {'color':'red'}), (d, b, {'capacity':5}), (a, b, 'k'), (a, b, 'j', {'capacity':3})] 
```

Some possible code to process this:
```python
G = # the graph class object we are inserting this graph representation into
for obj in sequence:
    if hasattr(obj, "items"):
        G.graph.update(obj)
        continue
    N = len(obj)
    if hasattr(obj[-1], "items"):   # last entry in obj is dict-like
        if N==2:
            G.add_node(obj[0], **obj[1])
        elif N >=3:
            G.add_edge)obj[:-1], **obj[-1])        
    elif N == 1:
        G.add_node(obj[0])
    elif N >= 2:
        G.add_edge(*obj)
```

**Comment by Erotemic** [comment]
I'm just learning about NXEP3, so I might be missing some context, but I thought I'd offer my $0.02 on this issue.

Having a generator that  only produces nodes and edges lists is a great idea, but I'm against removing the `create_using` parameter. That is partially due for backwards comparability, but mostly because it makes it non-obvious on how to parameterize logic that uses `create_using` without using `getattr`.

My understanding of the proposal is that: 

```
nx.path_graph(3)  # works as is
elist = nx.path_graph.edgelist(3)  # is the more efficient edges
```

I think having the above two methods is a great idea, and I'm 100% for it.

But instead of using `nx.path_graph(3, create_using=nx.DiGraph)`  the proposal says that should be replaced by `nx.DiGraph.path_graph(3)`. I think having the latter API is neat and makes a lot of sense, but what I think doesn't make sense is the argument that `create_using` should then be removed to prevent more than one way of doing something from existing.

If I have a function that parameterizes the type of graph I'm using, I want to pass it in as a variable. I don't want to have to do something like `getattr(nx.path_graph, cls.__name__)(3)` to use a generator in function that is parameterized over multiple types of graphs.

This is related to the topic of custom graphs which is also raised, and the syntax: `nx.path_graph.CustomGraph(3, cls)` was proposed. But doesn't this also introduce a second way of doing something? Under this proposal I could be using `nx.path_graph.CustomGraph(3, nx.DiGraph)` or `nx.DiGraph.path_graph(3)`. 

So summarize my point, what is the difference between: `nx.path_graph.CustomGraph(3, nx.DiGraph)` and just keeping the original `nx.path_graph(3, create_using=nx.DiGraph)` around?

Thus, I would propose adding the new `.edgelist` attr (I love small efficiency gains like that) and also `.DiGraph`, `.Graph` attrs (I think they make a lot of sense when you _statically_ know what type of graph you want). But for cases when you need to _dynamically_ tell networkx what type of graph to use, I think the `create_using` argument is already the best way of doing that, and it shouldn't be removed.

**Comment by rossbar** [comment]
Thanks for the input @Erotemic , I have to say that I very much agree - both re: having the more efficient option for producing edgelists and keeping the `create_using` keyword :+1:

**Comment by MridulS** [comment]
`create_using` is here to stay :) I'll close this issue for now, more conversations can happen in NXEP 3.
