### ISSUE TITLE
Return values of `edge_dfs` could use cleanup

### ISSUE THREAD

**Issue by winni2k** [networkx/networkx#3037]
From the documentation of `edge_dfs` in networkx 2.2: 

> If orientation is ‘reverse’ or ‘ignore’, then edge takes the form (u, v, key, direction) where direction is a string, ‘forward’ or ‘reverse’,  that indicates if the edge was traversed in the forward (tail to head) or reverse (head to tail) direction, respectively.

I often find myself wanting to use `edge_dfs` with the `original` and with the `reverse` direction (dynamically set) in the same loop, but in the former case I get a tuple of two or three values, and in the latter case I get a tuple of three or four  values to work with, depending on whether I am working with a multigraph. I think it would be cleaner if `edge_dfs` always returned the direction value if the `direction` parameter to `edge_dfs` is not `None`. 

Here is a wrapper that I think would do what I am talking about (untested code):

```python
def my_edge_dfs(G, source=None, orientation=None):
    add_orientation = False
    if orientation is None:
        orientation = 'original'
    elif orientation == 'original':
        add_orientation = True
    for edge in nx.edge_dfs(G, source=source, orientation=orientation):
        if add_orientation:
            edge = edge + (orientation,)
        yield edge
```

What do people think?

**Comment by dschult** [comment]
I like that interface change. :)
Might break backward compatibility, but in a fairly obvious way. We will need to flag it in the release notes.

**Comment by dschult** [comment]
```find_cycle``` has the same ```orientation``` interface, so this should probably be done there too.
