### ISSUE TITLE
ENH: Addition of the Equitable coloring algorithm.

### ISSUE THREAD

**Issue by musically-ut** [networkx/networkx#3042]
I recently implemented an [equitable coloring](https://en.wikipedia.org/wiki/Equitable_coloring) algorithm for degree bounded graphs from a paper by [Kierstead et. al.](https://link.springer.com/article/10.1007%2Fs00493-010-2483-5) here: [musically-ut/equitable-coloring](https://github.com/musically-ut/equitable-coloring).

From Wikipedia:

>    In graph theory [..] an equitable coloring is an assignment of colors to the vertices of an undirected graph, in such a way that
>
>   * No two adjacent vertices have the same color, and
>   * The numbers of vertices in any two color classes differ by at most one.

----

I wanted to get an idea of whether there is any interest in including `equitable_color` from my package as a potential coloring strategy under `networkx.algorithms.coloring`, next to the `greedy_color` strategies already there.

If so, I could work on a PR which will port the code and the test cases to `networkx`.

**Comment by dschult** [comment]
Yes, I think that would be a good place to include your equitable-coloring functionality. 
Thanks very much!
