### ISSUE TITLE
nx.set_node_attributes  Typeerror:unhashable type "dict"

### ISSUE THREAD

**Issue by Monarch1995** [networkx/networkx#3044]
nx.set_node_attributes(G,'state',state_ini)

state_ini is a dict,but i have read the manual,the mistake is Typeerror:unhashable type "dict"

**Comment by dschult** [comment]
You've got the order of your arguments switched. 

    nx.set_node_attributes(G, state_ini, 'state')

**Comment by Monarch1995** [comment]
Thank you very much!
