### ISSUE TITLE
Can't set layers in a shell_layout with nodes added from add_weighted_edges_from(): 'Node 'foo' has no position.'

### ISSUE THREAD

**Issue by colinrsmall** [networkx/networkx#3048]
`g = nx.Graph()`

`g.add_weighted_edges_from(test, 'weight')`

`weights = [w['weight'] for t,f,w in g.edges(data=True)]`

`labels = [t for t,f,w in g.edges(data=True)]`

`nx.draw(g, nx.shell_layout(g, [list(g.nodes())[0],list(g.nodes())[1:]]), width=weights, with_labels=True)`

Test is a list of tuples containing the necessary to, from, and weight values for the edges. Importing the edges and building graphs of any layout works fine. However, as soon as I try denoting which nodes belong in which layers, I am met with a 'Node 'foo' has no position' error. 

Solutions to this problem for other layouts suggest building the layout first, however I don't know if its possible to add the list of nodes per layer after the fact.

**Comment by dschult** [comment]
I'm not sure if this is your problem, but as written ```list(g.nodes())[0]``` should result in a list and it results in a singleton. Instead use: ```list(g.nodes())[:1]```

With that change, the code works on my setup (python 3.6.5, matplotlib 2.2.2, networkx dev)

**Comment by colinrsmall** [comment]
You're a life-saver. Didn't know Python would return a singleton that way.
