### ISSUE TITLE
`algorithms.clique.graph_clique_number` fails for graphs without cliques

### ISSUE THREAD

**Issue by lonnen** [networkx/networkx#3050]
If you pass a graph without cliques into the `algorithms.clique.graph_clique_number` function you'll get an unexpected ValueError. Something like this:

```
======================================================================
ERROR: test_clique.TestCliques.test_clique_number2
----------------------------------------------------------------------
...stuff...
  File "/Users/lonnen/repos/networkx/networkx/algorithms/clique.py", line 426, in graph_clique_number
    return max([len(c) for c in cliques])
ValueError: max() arg is an empty sequence
```

I expect it to return 0 when there are no cliques in the graph

**Comment by lonnen** [comment]
Two of the environments tested have errors but they appear unrelated to this change

**Comment by dschult** [comment]
I agree -- the tests seem to be due to a change in pandas rather than anything from this PR.

Thanks for filling in this corner case!! :)
