### ISSUE TITLE
Would it be possible to tell whether there is any plan using Fibonacci heap to speed up Dijkstra Algorithm?

### ISSUE THREAD

**Issue by enerai** [networkx/networkx#3057]
Dear developers, 

Would it be possible to tell whether there is any plan using Fibonacci heap to speed up Dijkstra Algorithm? Or is it possible to provide a way to replace the current heap with Fibonacci heap?

**Comment by dschult** [comment]
There is no plan to use a Fibonacci heap in the networkx dijkstra routines. But that doesn't mean we can't -- only that we don't currently have such a plan. Do you have an easy Python implementation of Fibonacci heap in mind?
