### ISSUE TITLE
'NodeDataView' object has no attribute 'pop'

### ISSUE THREAD

**Issue by StacyAOI** [networkx/networkx#3061]
in graph.py: 

def nodes(self):
        """A NodeView of the Graph as G.nodes or G.nodes().
        Can be used as `G.nodes` for data lookup and for set-like operations.
        Can also be used as `G.nodes(data='color', default=None)` to return a
        NodeDataView which reports specific node data but no set operations.
        It presents a dict-like interface as well with `G.nodes.items()`
        iterating over `(node, nodedata)` 2-tuples and `G.nodes[3]['foo']`
        providing the value of the `foo` attribute for node `3`. In addition,
        a view `G.nodes.data('foo')` provides a dict-like interface to the
        `foo` attribute of each node. `G.nodes.data('foo', default=1)`
        provides a default for nodes that do not have attribute `foo`.
        .........

-------------------------------------------------------
when I tried to do in Python 3.6.5: 

`nodes = G.nodes(data=True)
nodes.pop()`

I got the error like:

`AttributeError: 'NodeDataView' object has no attribute 'pop'`

-------------------------------------------------------

I am confused. Should it be compatible with set operation?

**Comment by dschult** [comment]
```pop``` is typically a mutating operation for lists, dicts etc. Graph mutations should be done through the graph object itself rather than through the reporting methods ```nodes``` and ```edges```.  If you want to mimic removing a node from the graph and returning it you could use:

    node = nx.utils.arbitrary_element(G)
    G.remove_node(node)

or equivalently

    for node in G:
        break
    G.remove_node(node)
