### ISSUE TITLE
kamada_kawai_layout fails with dim=1

### ISSUE THREAD

**Issue by asanakoy** [networkx/networkx#3065]
`nx.kamada_kawai_layout(G, dim=1)` Fails when called without initializations through `pos` argument.
This is cased by the default initialization which calls [circular_layout](https://github.com/networkx/networkx/blob/27dd93dda901171631fba92dc02a521cfc9e057e/networkx/drawing/layout.py#L667).

But `circular_layout()` ignores parameter `dim=1` and overwrites it with 2 without any notification. 
`circular_layout` should throw an exception if it cannot handle `dim=1`.

```
import networkx as nx

def create_bipartite_graph(n, m):
    assert n <= m
    dist_matrix = np.ones((n+m, n+m), dtype=float) * 255
    matches = n + np.random.permutation(m)[:n]
   
    dist_matrix[np.arange(n), matches] = 75
    dist_matrix[matches, np.arange(n)] = 75
    
    G = nx.Graph()
    
    edges = (dist_matrix <= 75).nonzero()
    dists = dist_matrix[edges]
    edges = (edges[0], edges[1], 
             [{'weight': x} for x in dists])
    edges = zip(*edges)
    G.add_edges_from(edges)
    return G

G = create_bipartite_graph(10, 10)
pos = nx.kamada_kawai_layout(G, dim=1) # THIS FAILS
pos = nx.kamada_kawai_layout(G, dim=1, pos=np.random.rand(20)) # THIS WORKS
```

**Comment by dschult** [comment]
Thanks for this. Seems like a good suggestion for fix: circular_layout should raise an exception for ```dim``` values it can't handle.
