### ISSUE TITLE
graph from geopandas?

### ISSUE THREAD

**Issue by ljwolf** [networkx/networkx#3067]
I was wondering whether it'd be useful to implement methods to provide graphs to/from geopandas dataframes, rather than directly from shapefiles? 

We've got a lightweight graph implementation for graphs in geographic data with converters [to](https://github.com/pysal/libpysal/blob/master/libpysal/weights/weights.py#L299)/[from](https://github.com/pysal/libpysal/blob/master/libpysal/weights/weights.py#L319) networkx graphs already. 

I think it'd be neat if something similar could live in `networkx` as a `from_geodataframe` method, and I think it wouldn't be too hard to adapt our implementation, and I'm sure this'd be relevant/helpful to `osmnx` users and `geopandas` users alike.

**Comment by dschult** [comment]
Yes, I think this could be useful.  Probably best to add a module in ```networkx/readwrite``` with tests in the ```tests``` subfolder of that.  Thanks!

**Comment by bwalsh0** [comment]
Supporting this enhancement, I'm currently trying to find a means to do this and would find it useful if built into NetworkX.

**Comment by ljwolf** [comment]
@bwalsh0 are you wanting that from a `linestring`-type geodataframe?
