### ISSUE TITLE
repeatedly reading and writing dot files does not converge on the same dot file

### ISSUE THREAD

**Issue by josch** [networkx/networkx#3079]
Steps to reproduce
---

Suppose the following Python command:

    python3 -c 'import networkx as nx, sys; nx.nx_agraph.write_dot(nx.nx_agraph.read_dot(sys.stdin), sys.stdout)'

Essentially this is just writing the same dot graph to stdout that it read from stdin.

And then also this trivial dot input:

```dot
digraph G {
	graph ["edge"="{}",
		"graph"="{}",
		name=G,
		"node"="{}"
	];
}
```

Now I'm executing:

    command < graph1.dot > graph2.dot
    command < graph2.dot > graph3.dot
    command < graph3.dot > graph4.dot
    ...

Expected behaviour
---

Since the command is writing out the same graph it is reading without modifying it, it should not matter how often I read in and write out the same dot file. At least after the first invocation, what networkx writes out should remain the same over the remaining invocations. That is, the file should converge to a stable version that doesn't change independent how often the script is executed on it.

Reality
---

The `graph` attribute gets more and more populated. The more often this is executed the bigger the file becomes.

`graph2.dot`:

```dot
digraph G {
	graph ["edge"="{}",
		"graph"="{'edge': '{}', 'graph': '{}', 'name': 'G', 'node': '{}'}",
		name=G,
		"node"="{}"
	];
}
```

`graph3.dot`:
```dot
digraph G {
	graph ["edge"="{}",
		"graph"="{'edge': '{}', 'graph': \"{'edge': '{}', 'graph': '{}', 'name': 'G', 'node': '{}'}\", 'name': 'G', 'node': '{}'}",
		name=G,
		"node"="{}"
	];
}
```

`graph4.dot`:

```dot
digraph G {                   
	graph ["edge"="{}",
		"graph"="{'edge': '{}', 'graph': '{\'edge\': \'{}\', \'graph\': \"{\'edge\': \'{}\', \'graph\': \'{}\', \'name\': \'G\', \'node\': \'{}\'}\", \'\
name\': \'G\', \'node\': \'{}\'}', 'name': 'G', 'node': '{}'}",
		name=G,
		"node"="{}"
	];
}
```

**Comment by dschult** [comment]
This looks like it is putting the entire graph into the ```graph``` attribute.  
Your initial graph shouldn't use the special attribute ```graph```. Am I right?
Does that create a subgraph within the bigger graph? I;m not sure why you have it there.

I certainly messes up reading and writing as you demonstrate.  What if it isn't there? Does the same thing happen one iteration later?

Do you have suggestions for how to handle this?

**Comment by josch** [comment]
If my initial graph doesn't have the `graph` attribute, then it will be put in by networkx and the issue is the same. Try this initial graph instead:

```dot
digraph G {
}
```

After passing this through the command, it becomes:

```dot
digraph G {
	graph ["edge"="{}",
		"graph"="{}",
		name=G,
		"node"="{}"
	];
}
```

It doesn't matter why *I* have it there. As you can see, it is put in by networkx itself and not by me. I noticed this issue specifically because I didn't put the attribute there but networkx did.

So yes, if it isn't there, networkx will put it and we have the same problem again.

Did you not try to reproduce the issue yourself?

**Comment by dschult** [comment]
I added a test to verify that this fix works. 
We still add the graph/node/edge attributes to G.graph each time we use ```from_agraph```, but now ```to_agraph``` doesn't add them to the dot file repeatedly.

Thanks!
