### ISSUE TITLE
from_numpy_matrix creates edges with numpy datatypes 

### ISSUE THREAD

**Issue by mtrenfield** [networkx/networkx#3086]
The function `from_numpy_matrix` creates graphs where some nodes in the edge tuples have numpy datatypes.

    >>> G = nx.cycle_graph(4)
    >>> A = nx.adj_matrix(G).todense()
    >>> H = nx.from_numpy_matrix(A)
    >>> [(type(x), type(y)) for x, y in H.edges()]
    [(<class 'int'>, <class 'numpy.int64'>), (<class 'int'>, <class 'numpy.int64'>), (<class 'int'>, <class 'numpy.int64'>), (<class 'int'>, <class 'numpy.int64'>)]

This can cause problems when trying to serialize a graph.  For example:

    >>> import json
    >>> json.dumps(nx.json_graph.node_link_data(H))
    TypeError: Object of type 'int64' is not JSON serializable

**Comment by dschult** [comment]
It looks like the adjacency dict-structure uses ```int``` for the nodes and ```int64``` for the neighbors.  Should be fixed...

**Comment by mtrenfield** [comment]
I think that what is causing the problem is that the nodes are created first with `range` and then the edges are created with `np.nonzero`.  `range` creates a generator of `int` but `np.nonzero` makes  of `np.int64` which are then reshaped into a list of tuples.  In any case I just submitted a pull request that I think fixes it.
