### ISSUE TITLE
inconsistent behavior of predecessor-and-distance functions

### ISSUE THREAD

**Issue by gfetterman** [networkx/networkx#3094]
While working on #2346 , I ran into the following slightly surprising behavior:

* `dijkstra_predecessor_and_distance()` sets `pred[source]` to be `[]`
* `bellman_ford_predecessor_and_distance()` sets `pred[source]` to be `[None]`

This behavior should be replicated by the following (as of commit `1a521966`):
```
>>> import networkx as nx
>>> G = nx.path_graph(2)
>>> nx.dijkstra_predecessor_and_distance(G, 0)[0]
{0: [], 1: [0]}
>>> nx.bellman_ford_predecessor_and_distance(G, 0)[0]
{0: [None], 1: [0]}
```

(From the [code for `_bellman_ford()`](https://github.com/networkx/networkx/blob/1a52196699668ec5531711590621b0d4821e57ae/networkx/algorithms/shortest_paths/weighted.py#L1166), `None` is being used as a sentinel value when constructing paths.)

This produces an error when trying to use the two algorithms' output interchangeably.

The inconsistency is small, but does seem like a bug. These two functions' return values should probably have similar conventions; the behavior of `dijkstra_predecessor_and_distance()` makes the most sense to me.

**Comment by dschult** [comment]
I've put together a pull request to address this API inconsistency.
I think it should make it easier to use dijkstra or bellman_ford interchangeably.
Any thoughts before I merge that pul request?
Thanks!

**Comment by dschult** [comment]
Well -- I'm sure the behavior was intended for each individual algorithm, but I doubt anyone specifically looked at the fact that it was different for the two algorithms. Thanks for pointing it out!
Hope this helps with #2346
