### ISSUE TITLE
UsageError: Invalid GUI request 'ps'

### ISSUE THREAD

**Issue by pipothy** [networkx/networkx#3096]
Hi,

Playing around with a directed graph in Ipython Notebook. Paste of version stuff below:

You are using Jupyter notebook.

The version of the notebook server is: 5.5.0
The server is running on this version of Python:
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]

Current Kernel Information:
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 6.4.0 -- An enhanced Interactive Python. Type '?' for help.

When I try run the draw graph test in the tutorial, I get an error. The code is below, then the error:

`import networkx as nx`
`import matplotlib.pyplot as plt`
`test = nx.petersen_graph()`
`plt.subplot(121)`
`nx.draw(test, with_labels=True, font_weight='bold')`
`plt.subplot(122)`
`nx.draw_shell(test, nlist=[range(5, 10), range(5)], with_labels=True, font_weight='bold')`

> UsageError: Invalid GUI request 'ps', valid ones are:dict_keys(['inline', 'nbagg', 'notebook', 'ipympl', 'widget', None, 'qt4', 'qt', 'qt5', 'wx', 'tk', 'gtk', 'gtk3', 'osx', 'asyncio'])

Any idea why this is happening?

**Comment by dschult** [comment]
Try getting matplotlib to work with a simple non-networkx picture. It's most likely a config error for matplotlib. 

It looks like your config is trying to use the 'ps' interface (create a 'ps' file) by default rather than drawing to an interactive GUI.
