### ISSUE TITLE
Test names not found by nose for some tests doubled for others

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#3102]
Some of our tests are not being found and others are being found more than once.
This is especially noticeable in ```classes/tests/test_special.py```
Time for an overhaul... maybe time to move to ```pytest``` too sinc nose isn't supported anymore?

**Comment by nandahkrishna** [comment]
Are PRs welcome for this issue? I see it's been opened a long time back, and if possible I'd like to work on it.

**Comment by dschult** [comment]
This is going to be quite a large project. The problem is that when we subclass a test class and use the name "test" in both, then nose finds the test functions in the super class and runs them, and then finds the functions in the subclass and runs them again.

This issue also intends that we switch from nose to pytest.  I have not looked at this much.

I would love to have this issue fixed and done with.  But I must admit I don't have time to review it unless it turns out to be a fairly straightforward process. It should also probably be 2 PRs. One for switching to pytest and one for making sure each test is run once on CI-Travis.

**Comment by nandahkrishna** [comment]
I'd like to try this, I understand it's going to be quite large. I did find resources to convert from nose to pytest, so I think I'll give that a shot.
