### ISSUE TITLE
G.predecessors(node) documentation could benefit from additional explanation

### ISSUE THREAD

**Issue by xtiansimon** [networkx/networkx#3113]
I'm on a _tree_ network similar to this toy,

    [('total_fruits', 'apples'),
     ('total_fruits_and_vegetables', 'total_fruits'),
     ('total_fruits_and_vegetables', 'total_vegetables'),
     ('total_vegetables', 'carrot')]

To find the root node I'm using this solution on StackOverflow: [NetworkX find root_node for a particular node in a directed graph](https://stackoverflow.com/a/47191030/343215). This solution works, but I think the documentation could be clearer. 

The documentation for predecessor [networkx.DiGraph.predecessors](https://networkx.github.io/documentation/stable/reference/classes/generated/networkx.DiGraph.predecessors.html) says: 

> DiGraph.predecessors(n)[source]
> Return an iterator over predecessor nodes of n.

For my tree I expected G.predecessors(node) output to return _all_ of the predecessors to the root,

    [n for n in G.predecessors('apples')]
    >>> ['apples', ''total_fruits', 'total_fruits_and_vegetables']

But what I get:

    [n for n in G.predecessors('apples')]
    >>>['total_fruits']

Finally, I realized _nodes_ refers to the predecessors one level or edge from the node parameter, because the network may not be a tree. 

In this edge case I'm asking if maybe the documentation could benefit further description.

**Comment by dschult** [comment]
Yes -- and that docstring is really VERY minimal...  It doesn't even say what the input or output arguments are. There may be others in that category like ```G.successors``` but I haven't checked.
Pull requests would be helpful...

**Comment by leotrs** [comment]
See #3114.
