### ISSUE TITLE
shortest path fail on connected network

### ISSUE THREAD

**Issue by insanefurion** [networkx/networkx#3115]
Hello,
I have a network of navigation point (file 20180807_edges2.txt, in the format nodeA nodeB weight.)

[20180807_edges2.txt](https://github.com/networkx/networkx/files/2270620/20180807_edges2.txt)

If I extract the giant component, the network is connected (except two nodes linked each other).
If I try to run the shortest_path_length between each couple, for a huge amount of couple I get an error: there is no path between two nodes. I tried to double the link (having a->b, adding b->a) but the problem persists!
Am I doing something wrong or is it a bug?
Best

**Comment by leotrs** [comment]
How are you extracting the largest component? How do you determine that it's connected? If you are using `nx.weakly_connected_component_subgraphs` or something similar that returns *weakly* connected components, not every pair of nodes is guaranteed to have a directed path joining them.
