### ISSUE TITLE
total nodes of composed graph is more than sum of nodes for each subgraph

### ISSUE THREAD

**Issue by gg4u** [networkx/networkx#3116]
I scratched my head for a couple of ours, until I found this strange result in my code:
total nodes of a composed graph is more than sum of nodes for each subgraph.

Could you help me explain how **compose_all** and **subgraph** methods works?

I'll tell you what I do:

```
def induce_Subgraph(graph, fromNode, toNode):
      graphs = []     
     // I extract some paths in graph, and then I extract a subgraph according to the path
     graphs.append( graph.subgraph(path) )
     // I repeat it, then merge all graphs induced from the original one
     graph = nx.compose_all( graphs)
     return graph
```

Now, I found out that the sum of nodes for each subgraphs is less then the total nodes in the induced graph made with function above.
```
x =0 
for graph in graphs : x+= len(graph.nodes())
graph = nx.compose_all( graphs )
y = len(graph.nodes()
print('total graph nodes, ', y, x )  // y > x

```

I could not figure out why.
I was expecting subgraph would return a new graph like this pseudo-code:
```
for u, v in make_pairs( path ):
     g = nx.Graph()
     g.addEdge(u, v)
```

I want to also copy attributes of the edge, that's why I was happy for using subgraph.

What compose_all in the example above should contains more nodes than sum of nodes in subgraphs ?

**Comment by dschult** [comment]
The number of nodes after ```compose_all``` should not be more than the sum of the number of nodes of the graphs you are composing.   ```compose_all``` should return the union of the node sets and the union of the edge sets.  Your code here is missing a parentheses but maybe your real code isn't

But induced subgraphs are not as you describe. Induced subgraphs keep the specified nodes and keep **all** edges between those nodes. If you want a subgraph that is just the path itself, use ```nx.path_graph(path)```
