### ISSUE TITLE
Unable to read "Pajek" file

### ISSUE THREAD

**Issue by ncdingari** [networkx/networkx#3122]
I am getting the following error. I have raised the issue on Orange3-Network Github (https://github.com/biolab/orange3-network/issues/81), they suggested me to raise it here

![image](https://user-images.githubusercontent.com/6037028/44170628-f11c1e80-a0a5-11e8-98ba-ab553b4add9c.png)

**Comment by dschult** [comment]
It looks like your Pajek file is not a valid Pajek file. But it is hard to tell from this information.
Can you try making a very small graph in Pajek format and then opening it in an editor and copy/pasting it over here?

**Comment by ncdingari** [comment]
Here is the Data and Graph

Vertices

name | age | gender
-- | -- | --
Alice | 48 | F
Bob | 33 | M
Cecil | 45 | F
David | 34 | M

Pajek File (in Editor)
*Vertices 5
*Edges
1 2
2 3
1 3
1 4
2 4
1 5

Esmeralda | 21 | F

Edges

from | to | same.dept | friendship | advice
-- | -- | -- | -- | --
Bob | Alice | FALSE | 4 | 4
Cecil | Bob | FALSE | 5 | 5
Cecil | Alice | TRUE | 5 | 5
David | Alice | FALSE | 2 | 4
David | Bob | FALSE | 1 | 2
Esmeralda | Alice | TRUE | 1 | 3

Graph
![image](https://user-images.githubusercontent.com/6037028/44208476-70edcb80-a12e-11e8-9703-c12ee6d69215.png)

**Comment by dschult** [comment]
For some reason the pajek file is not getting the list of nodes. After the line ```*Vertices 5```, there should be 5 lines describing the vertices. Instead the file goes straight to the ```*Edges```.

In your post on orange3 you say the pajek file was created using R and igraph. Perhaps they need more help in specifying the node labels?  Somehow you have 5 nodes but no node_labels in the "local variables" listed at the end of your error trace.
