### ISSUE TITLE
DiGraph.in_edges and out_edges has different behaviour

### ISSUE THREAD

**Issue by tidues** [networkx/networkx#3126]
When call both functions with data equal to a string, the in_edges method returns a dict as the third element in tuple, but the out_edges method returns the value in that dict.

**Comment by dschult** [comment]
I get them both returning the value as the 3d entry in the edge tuple.

**Comment by tidues** [comment]
Hi Dan,

Thank you for the reply. I just tried again with following code:

import networkx as nx

myg = nx.gn_graph(20)
for e in myg.edges():
    myg[e[0]][e[1]]['type'] = 10

print(myg.in_edges([0], data='type'))
print(myg.out_edges([1], data='type'))

the output is:

[(1, 0, {'type': 10}), (2, 0, {'type': 10}), (8, 0, {'type': 10}), (13, 0, {'type': 10}), (19, 0, {'type': 10})]
[(1, 0, 10)]

They are still inconsistent. Maybe this only happens on digraph?


I checked my current version is the newest version 2.1.

**Comment by dschult** [comment]
When I use that code, I get different output.
Can you try

    import networkx as nx
    print(nx.__version__)
    myg = nx.DiGraph()
    myg.add_edge(0, 1, type=10)
    print(myg.in_edges(data='type'))
    print(myg.out_edges(data='type'))
    print(myg.in_edges([1], data='type'))
    print(myg.out_edges([0], data='type'))

**Comment by tidues** [comment]
My results:

1.11
[(0, 1, {'type': 10})]
[(0, 1, 10)]
[(0, 1, {'type': 10})]
[(0, 1, 10)]

weird...
Is 2.1 the newest version?

**Comment by dschult** [comment]
That's what I wondered.  You probably have NetworkX 2.1 install on one installation of python and NetworkX 1.11 installed on another installation of python. Make sure you are using the installation of Python that you think you are. Each one has its own set of installed packages.

**Comment by tidues** [comment]
Yes, you are right. In my python3.6, both 1.11 and 2.1 are installed. I removed and reinstalled. Everything is good now.

Thank you very much!
