### ISSUE TITLE
nx.rescale_layout input problem. 

### ISSUE THREAD

**Issue by frhyme** [networkx/networkx#3129]
I am using `networkx.drawing.layout.rescale_layout`.

However, in this function, input is fixed to `np.array`.
In fact, other layouts (`nx.spring_layout`, `nx.spectral_layout`, etc.) return a dictionary (key: node label, value: pos tuple (x, y)).

So, for `networkx.drawing.layout.rescale_layout`, I think it would be useful to change the input to dictionary (key: node label, value: pos tuple (x, y)).

To change to the code:

I think this case is more versatile and I would like to ask you what you think.

```python
def rescale_layout(pos, scale=1):
    pos_v = np.array([[v[0], v[1]] for v in pos.values()])
    lim = 0  # max coordinate for all axes
    for i in range(pos_v.shape[1]):
        pos_v[:, i] -= pos_v[:, i].mean()
        lim = max(abs(pos_v[:, i]).max(), lim)
    # rescale to (-scale, scale) in all directions, preserves aspect
    if lim > 0:
        for i in range(pos_v.shape[1]):
            pos_v[:, i] *= scale / lim
    return {k: tuple(v) for k, v in zip(pos.keys(), pos_v)}
```

**Comment by dschult** [comment]
We wrote ```rescale_layout``` with those inputs to reduce the number of times we have to convert back and forth between arrays and dicts.  How about implementing your suggestion as a new function rather than replacing the current one:

    def rescale_layout_dict(pos, scale=1)
        pos_array = np.array([[px, py] for px, py in pos.values()])
        new_pos_array = rescale_layout(pos_array, scale=scale)
        return {v: tuple(p) for v, p in zip(pos, new_pos_array)}
