### ISSUE TITLE
How can I create multilayer networks with networkx?

### ISSUE THREAD

**Issue by EmanuelFontelles** [networkx/networkx#3132]
I'm looking how to create multilayer networks on `networkx` but I think it's not possible because node index are dictionaries and I can't merge two different  graphs. What should I try?

**Comment by wuhaochen** [comment]
What I'm doing with my research is basically adding labels containing layer information to nodes and edges. I'm also working on an extension for multiplex network but it's still very preliminary and it may not work well with more general multi-layer networks.

**Comment by EmanuelFontelles** [comment]
@wuhaochen thanks a lot, I've seen your project `multinet`  and the idea of create different labels to identify multilayers can be work. Thanks again!
