### ISSUE TITLE
Hashable graphs?

### ISSUE THREAD

**Issue by ryanpeach** [networkx/networkx#3133]
The behavior of hashing a graph is not ideal.

For reference, this is how hashing a graph currently works:

```python
In[10]: G = nx.balanced_tree(4,2)
In [11]: hash(G)
Out[11]: 275084920
In [12]: G.add_node(100)
In [13]: hash(G)
Out[13]: 275084920
```

Further:

```python
In [14]: G.nodes()
Out[14]: NodeView((0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 100))
In [15]: G = nx.balanced_tree(4,2)
In [16]: hash(G)
Out[16]: -9223372036579765409
In [17]: G.nodes()
Out[17]: NodeView((0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20))
```

So basically, the way it works now is that graphs are assigned a hash upon creation, and it does not change if they change. It is also not the case that two graphs which are exactly similar have the same hash.

Further, the following:

```python
In [18]: nx.balanced_tree(4,2) == nx.balanced_tree(4,2)
Out[18]: False
```

This is not ideal if you want to memoize a function that has a graph as a parameter (my specific use case), or compare graphs.

My proposed solution would be to create a hashing function something akin to the following:

```python
def __hash__(self):
    return hash(set(self.nodes()) | set(self.edges()))
```

Since nodes and edges are already inherently hashable.

This would ignore changes to node attributes, but given that node attributes need not be hashable, this is to be expected. Users can create their own custom hash functions in these cases, and perhaps a user warning could be raised as well.

**Comment by ryanpeach** [comment]
Sorry, I forgot that set's aren't hashable either. That complicates things, but it is possible to hash a sorted tuple of the edges and nodes instead. An error should be raised if sorting is impossible. As it is currently, if this idea is not implemented, hashing should be removed as it is not intuitive, and can easily hide bugs in your code.

**Comment by ryanpeach** [comment]
Also added memoization.

set self.__unchanged to False in __init__, add_node, add_edge, etc.

```python
def __hash__(self):
    if self.__unchanged:
        return self.__hash
    else:
        out = tuple(sorted(list(self.edges()))+sorted(list(self.nodes())))
        self.__hash = out
        self.__unchanged = True
        return hash(out)
```

**Comment by ryanpeach** [comment]
You can even do it like this if the elements aren't sortable (you can sort them by their hash).

`out = tuple(sorted(map(hash,list(self.edges())))+sorted(map(hash,list(self.nodes()))))`

**Comment by ryanpeach** [comment]
```python
In [24]: nx_hash = lambda G: hash(tuple(sorted(map(hash,list(G.edges())))+sorted(map(hash,list(G.nodes())))))

In [25]: nx_hash(nx.balanced_tree(4,2)) == nx_hash(nx.balanced_tree(4,2))
Out[25]: True

In [26]: nx_hash(nx.balanced_tree(4,2)) == nx_hash(nx.balanced_tree(5,2))
Out[26]: False
```

**Comment by winni2k** [comment]
I've always found hashing of mutable objects problematic. Maybe it would be better to remove the `__hash__` function from nx graphs altogether?  Mutable base objects such as `set` aren't hashable either ...

**Comment by winni2k** [comment]
For example, what happens when someone changes a graph after it has been memoized? Will the memoization function return the changed or the original graph?

**Comment by ryanpeach** [comment]
I agree. Maybe itd be cool to make a finalize function? Then it becomes immutable.

Python has a frozenset for instance when you want to hash its sets.
________________________________

**Comment by dschult** [comment]
There is currently no ```__hash__``` function in NetworkX. There is also no ```__eq___``` function. So according to the Python 3.7 docs:

    User-defined classes have __eq__() and __hash__() methods by default; with them, all objects 
    compare unequal (except with themselves) and x.__hash__() returns an appropriate value such 
    that x == y implies both that x is y and hash(x) == hash(y).

So, Graphs are allowed to be contained in dicts and sets, but equality is determined by being the same object -- not by equality of objects. This is a default minimalist approach for non-builtin objects in Python and I don't see a good justification for changing that. Equality of graphs opens up the mutable can-of-worms and also the isomorphic can-of-worms. Explicitly turning off the default behavior to raise an error when hashing removes a potentially useful construct -- graphs can be nodes in another graph.

I think if someone wants to use ```hash/eq``` then they know what features of hash they want provided and they can likely subclass and implement their version of hash more easily than we can predict what they want.

BTW - NetworkX has a ```freeze``` function that makes the graph immutable.

**Comment by ryanpeach** [comment]
I didnt know that, thanks for your answer, and I agree with it. I wonder if there is a way we can add something like my hashing function to maybe a recipes doc. It's very easy to subclass like you said, or even just to do a function injection.

**Comment by dschult** [comment]
Yes, it could be added as an example in the ```examples/subclass``` folder.
That would be helpful for people trying this -- and also trying other "simple" subclasses.

**Comment by winni2k** [comment]
More subclassing examples would be much appreciated!
