### ISSUE TITLE
networkx is unable to display some unicode characters

### ISSUE THREAD

**Issue by mpenkov** [networkx/networkx#3137]
I'm trying to draw a graph using Japanese characters. I've set up a Japanese font, and _most_ characters display OK. There are some characters, however, that display as a box with an X inside of it. It doesn't seem to be a font problem, because in that case, I'd be seeing a box _without_ an X inside of it.

Reproducing the problem is a little bit involved, so I did it in this [jupyter notebook](https://github.com/mpenkov/heisig/blob/master/nx-font-problem.ipynb).

The notebook shows three nodes:

1. Japanese character, font configured properly, displays OK (expected).
2. Japanese character, font _not_ configured properly, displays box _without_ an X (expected)
3. **Japanese character, font configured properly, displays box _with_ an X (unexpected)**

How can I get that third character to display correctly?

Many thanks!

**Comment by dschult** [comment]
Are you able to make the characters show using ```plt.text```? NetworkX is using matplotlib's text feature to draw the characters. I think the next step in debugging is to figure out whether the problem lies in the config for NetworkX or in Matplotlib or in something deeper.

    plt.text(0,0,'雨')
    plt.text(1,0,'風')
    plt.text(2,0,'⿱')
    plt.show()

**Comment by mpenkov** [comment]
Thanks for the quick replies everyone.

@wuhaochen Sorry, I glossed over that detail. It is indeed a translingual symbol. However, I've confirmed that the font I'm using supports that character.

@dschult I get the same results using plt.text, so it looks like a matplotlib problem. Shall I take it up with them, or is there anything else I could try while I'm here?

**Comment by dschult** [comment]
I dont know of anything we can do with NetworkX to fix this.
