### ISSUE TITLE
Cannot get the edges

### ISSUE THREAD

**Issue by felix-tracxpoint** [networkx/networkx#3144]

**Comment by chewbacca89** [comment]
As far as I am aware of you have to use G.edj() in case you are using networkx version >2.0

**Comment by dschult** [comment]
This should work in networkx versions >2.0.  ```print(G.edges())``` is the preferred way to print edges.

It looks like a bug. Python is not allowing descriptor ```_graph``` for the ```EdgeView``` object created by the ```G.edges()``` command. I will try to recreate the trouble. Thanks for your report.

**Comment by dschult** [comment]
I am not able to recreate the trouble. Is there a simple version of ```d_lab``` that makes this break? One that you can have me use?
