### ISSUE TITLE
bfs returns generators instead of dicts 

### ISSUE THREAD

**Issue by drdeford** [networkx/networkx#3148]
The bfs and dfs traversals return different object types for their predecessors and successors. The documentation [here](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.algorithms.traversal.breadth_first_search.bfs_predecessors.html#networkx.algorithms.traversal.breadth_first_search.bfs_predecessors ) suggests that they should all return dicts but bfs returns a generator of the edges:

```
>>> G=nx.Graph()
>>> G.add_path([0,1,2])
>>> print(nx.dfs_predecessors(G,0))
{1: 0, 2: 1}
>>> print(nx.bfs_predecessors(G,0))
<generator object bfs_predecessors at 0x000002141B81E518>
>>> print(nx.dfs_successors(G,0))
{0: [1], 1: [2]}
>>> print(nx.bfs_successors(G,0))
<generator object bfs_successors at 0x000002141B81E518>

```

**Comment by dschult** [comment]
Your pointer to docs is for Version 1.10. The stable release is v2.1 and we're close to releasing v2.2.

The [documentation aligns with the actual behavior](https://networkx.github.io/documentation/stable/reference/algorithms/traversal.html) where ```dfs_*``` routines return dicts and ```bfs_*``` routines iterate over ```(node, result)``` pairs.

**Comment by drdeford** [comment]
Oh, thanks! That is entirely my fault, I saw the different behavior and then clicked the first google link without checking the version.

**Comment by dschult** [comment]
It is a little strange that the two sets of functions return different types of objects. Seems like in a better world they would both return the same thing -- perhaps the generator version because it is easy to build the dict from the generator. There may be an efficiency reason they are different, but I don't recall.
