### ISSUE TITLE
Update isomorphism VF2 algorithm

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#3152]
@chebee7i says (from discussion in #3136):
 
    I just noticed that someone put out a paper on VF2++ 
    (https://www.sciencedirect.com/science/article/pii/S0166218X18300829). Looks very nice. Would 
    be interesting to offload the isomorphism checks to that LEMON library.

So I suggest either implement the new algorithm in python or find a way to offload to the LEMON library.

**Comment by BasLaa** [comment]
Hi,

I recently started looking into NetworkX and saw that there was this open project to implement this VF2++ algorithm for subgraph isomorphism. To my knowledge, it hasn't been implemented yet in Python, nor has it been offloaded to the C++ LEMON library. I think it would be a great challenge for me as a computer science student to actually implement the algorithm, so I would be interested in taking it on me. I will look more into both NetworkX and the VF2++ algorithm over the next week, and prepare a short write-up on my thoughts and ideas on the project as well as things I might be stuck with. I will send that here, and hope to hear from the community any relevant thoughts on this. Thanks!

**Comment by rossbar** [comment]
The plan here is not to *replace* VF2 with VF2++, but to implement VF2++ alongside the existing isomorphism functionality. @kpetridis24 is currently working on this problem, so I think we can safely remove this from the "wishlist".
