### ISSUE TITLE
Generalized Modularity for Community Detection

### ISSUE THREAD

**Issue by xiaoylu** [networkx/networkx#3153]
Is there any way we can integrate the generalized modularity into the current implementation of 
> networkx.algorithms.community.quality
> networkx.algorithms.community.modularity_max

The definition of the generalized modularity is just a simple extension of modularity with one extra \gamma parameter. And it can easily improve the resolution limit of modularity-based community detection.

See Newman's paper in 2016.

[Equivalence between modularity optimization and maximum likelihood methods for community detection](https://journals.aps.org/pre/abstract/10.1103/PhysRevE.94.052315)

**Comment by elplatt** [comment]
Probably easy for the quality module. In the modularity_max module, the change in modularity is calculated at each step, rather than the modularity itself. The formulas for the modularity updates would need to be determined for both directed and undirected networks.

**Comment by xiaoylu** [comment]
Update multiple places in the modularity_max module to change the modularity definition.
Appreciate that if someone can review #3260

**Comment by willpeppo** [comment]
hi I'd like to start contributing to networkx and it looks like this is still open.

**Comment by somyabhargav** [comment]
Hello! I would like to contribute to networkx and wanted to know if there is something still unresolved here that I can help with. Thanks.

**Comment by dschult** [comment]
Closed by #3260
