### ISSUE TITLE
NodeNotFound when drawing ego_graph

### ISSUE THREAD

**Issue by Cindy1122334455** [networkx/networkx#3154]
Here is my code to draw the ego_graph, 
" g_problock " is the networkx graph I created.
# find node with largest degree
largest_degree=max([val for (node, val) in g_problock.degree()])
largest_hub=[node for (node, val) in g_problock.degree() if val==largest_degree]
# Create ego graph of main hub
hub_ego=nx.ego_graph(g_problock,largest_hub)
# Draw graph
pos=nx.spring_layout(hub_ego)
nx.draw(hub_ego,pos,node_color='b',node_size=50,with_labels=False)
# Draw ego as large and red
nx.draw_networkx_nodes(hub_ego,pos,nodelist=[largest_hub],node_size=300,node_color='r')
plt.show()

Then the error information is 
NodeNotFound: Source ['1dice97ECuByXAvqXpaYzSaQuPVvrtmz6'] is not in G

Actually, I have examined the node in the graph I built and it exists in G. Can anyone help me to figure that out?

**Comment by dschult** [comment]
Your ```largest_hub``` object is a list of nodes. The ```ego_graph``` function [expects a single node](https://networkx.github.io/documentation/latest/reference/generated/networkx.generators.ego.ego_graph.html#networkx.generators.ego.ego_graph) so the square brackets around your long node name mean it is actually looking for the LIST as a node... note the string you think it is looking for.

**Comment by Cindy1122334455** [comment]
Actually I specified the the node and guarantee that it is a single node but I still got the same error information.

**Comment by dschult** [comment]
It is not a single node if it is a list. A list cannot be a node because it is not hashable.
Try ```hub_ego=nx.ego_graph(g_problock,largest_hub[0])```

**Comment by Cindy1122334455** [comment]
Now it worked, thank you so much!
