### ISSUE TITLE
Improve output object for asyn_lpa_communities

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#3163]
Current returns an iterator of a dict-value view. But since the dict exists we might as well return the dict. Iteration doesn't save anything.

**Comment by amerghazal** [comment]
thanks for your work on this! i'm looking to contribute and would like to pick this up. 
if the dict is returned, what's the value in the key? it seems indeterminate because of the node shuffle.

**Comment by dschult** [comment]
Are you saying that the dict would be confusing to use?
If so, let's return the dict-value view  ```d.values()``` rather than an iterator of it.
Is there an easy way to make it clear how to use the dict?

**Comment by amerghazal** [comment]
I don't think the usage of the dict is confusing so much as the key is unnecessary to return because it's indeterminate due to line 76 `seed.shuffle(nodes)`, iinm: 

```
diff --git a/networkx/algorithms/community/label_propagation.py b/networkx/algorithms/community/label_propagation.py
index 424b773d..fd3315d7 100644
--- a/networkx/algorithms/community/label_propagation.py
+++ b/networkx/algorithms/community/label_propagation.py
@@ -98,7 +98,7 @@ def asyn_lpa_communities(G, weight=None, seed=None):
             cont = cont or len(best_labels) > 1

     # TODO In Python 3.3 or later, this should be `yield from ...`.
-    return iter(groups(labels).values())
+    return groups(labels)

>>> import networkx as nx
>>> y = nx.social.davis_southern_women_graph()
>>> list(nx.community.asyn_lpa_communities(y).keys())
[20]
>>> list(nx.community.asyn_lpa_communities(y).keys())
[24]
>>> list(nx.community.asyn_lpa_communities(y).keys())
[18]
>>> list(nx.community.asyn_lpa_communities(y).keys())
[22]
```

I like your suggestion of returning a dict-value view.
