### ISSUE TITLE
networkx missing modules when installed on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by arshiya-singh** [networkx/networkx#3166]
to replicate the issue:
1. `python3.7 -m pip install networkx` 
2. write a python file (in this case, network_testing.py) with just the line `import networkx as nx`.

The error that pops up is this:
`Traceback (most recent call last):
  File "network_testing.py", line 2, in <module>
    import networkx as nx
  File "/home/username/.local/lib/python3.7/site-packages/networkx/__init__.py", line 98, in <module>
    import networkx.utils
ModuleNotFoundError: No module named 'networkx.utils'`

I looked into the location of the networkx package and found that the only module it had was `algorithms.`

**Comment by mrecachinas** [comment]
Hi @arshiya-singh -- did you ever solve this? If not, what happens if you try `pip uninstall networkx` and then `pip install networkx` or `pip install -U networkx`?

**Comment by arshiya-singh** [comment]
I manually installed the zip file for networkx and cut + pasted the algorithms folder at the time. Also, I was using the Ubuntu app for Windows so this might have caused some issues? Not sure.
