### ISSUE TITLE
read_graphml fails to open graph generated by write_graphml

### ISSUE THREAD

**Issue by abhinavagarwalla** [networkx/networkx#3167]
I get the following error when reading a graph generated by write_graphml, using read_graphml:
**networkx.exception.NetworkXError: Bad GraphML data: no key d10**

On debugging, I found out an issue with write_graphml. 
Below is a snippet from the code that can reproduce the error. If the datatype of _penalty_attr_ attribute passed to the add_edge function is different for different edges, write_graphml creates multiple data keys (in my example, _d10_) in graphml output file. There is no additional key information in the _<key>_ tag which only has description for keys upto _d9_, but _<edge>_ tag contains the extra key _d10_. This results in the key error while parsing graphml file using _read_graphml_.

```
penalty_attr = ''
if random() < 0.5:
    penalty_attr = 1.0  #datatype: double

G.add_edge(from_node,
           to_node,
           penalty = py)
```

Please let me know if I need to rephrase or elaborate on the issue.

**Comment by dschult** [comment]
I can verify that edge attribute types with the same name but different type cause ```write_graphml``` to create two differently named edge attributes -- one to hold edge attributes of each type. Furthermore, the second attribute does not get an entry in the graphml file describing it in a <key> element. That may be why ```read_graphml``` is giving the ```no key d10``` error.

Anyone have suggestions on how to make the writer add the edge attribute to the list of <key> elements? The edge attribute has the same name, but different type.

**Comment by iamjli** [comment]
We ran into this issue as well when setting node attributes using a dictionary generated from a pandas dataframe. 

I'd imagine scenario comes up not infrequently: If there are missing values in the dataframe, this can result in features with mixed types which breaks `nx.write_graphml`.

**Comment by dschult** [comment]
@iamjli you correctly mention that networkx should handle the missing values (or any other case where the same attribute name includes values of different type).

Do you have any suggestions for what the "right" way to handle missing values is?

**Comment by dschult** [comment]
Should we make ```write_graphml``` raise an error if the type of an edge attribute is not consistent?
That would force the user to go back and change the attributes. Kind of a pain, but no surprises that way.  Is that the "right" way to handle missing values?

**Comment by iamjli** [comment]
@dschult That's certainly an acceptable way to handle missing values, but you're right, it's a bit of a pain. 

I think raising an error if the edge attribute type is not consistent is a good solution, since this does break `write_graphml`. Ideally, edge attributes would be able to handle multiple types (pandas does this by specifying the type of the column as `object`), but I'm not sure how feasible this solution is to implement,. 

Another possible idea might be to have a method `set_edge_attributes_from_pandas_dataframe` which could appropriately deal with scenarios of mixed types and nans?
