### ISSUE TITLE
Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated

### ISSUE THREAD

**Issue by jbarnoud** [networkx/networkx#3170]
Running code that depends on networkx with the upcoming python 3.8 yields the following warnings:

```
/coarse/jon/Envs/pygit/lib/python3.8/site-packages/networkx/classes/graph.py:23: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping

/coarse/jon/Envs/pygit/lib/python3.8/site-packages/networkx/classes/reportviews.py:95: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping, Set, Iterable
```

The abstract syntax classes are in the `collections.abc` module since python 3.3. Python 2.7 still defines them directly in the `collections` module.

**Comment by khpeek** [comment]
I'm getting the same warnings using NetworkX 2.2 on Python 3.7. Perhaps this can be handled while not breaking support for Python 2.7 by using `six.moves_collections_abc` once it is implemented (cf. https://github.com/benjaminp/six/pull/241).

**Comment by wkschwartz** [comment]
From tip of master as of right now:
```
$ git describe
networkx-2.2-33-g61419bf1
$ git grep -n "from collections import.*Mapping"
networkx/algorithms/approximation/kcomponents.py:8:from collections import defaultdict, Mapping
networkx/algorithms/lowest_common_ancestors.py:13:from collections import defaultdict, Mapping, Set
networkx/classes/coreviews.py:13:from collections import Mapping
networkx/classes/graph.py:23:from collections import Mapping
networkx/classes/reportviews.py:95:from collections import Mapping, Set, Iterable
```

**Comment by dschult** [comment]
We are not supporting Python2.7 anymore so it is fine to switch to the ```collections.abc``` namespace. We should not use the ```six``` package.

**Comment by jbarnoud** [comment]
> We are not supporting Python2.7 anymore so it is fine to switch to the collections.abc namespace. We should not use the six package.

I removed the python 2.7 support in #3171, then.
