### ISSUE TITLE
Declare a runtime dependency on setuptools

### ISSUE THREAD

**Issue by maxking** [networkx/networkx#3173]
`networkx` uses `pkg_resources` in the source code, without declaring a dependency on `setuptools`. This causes an `ImportError` when setuptools isn't available during runtime. 

https://github.com/networkx/networkx/blob/bf1c7cc9b144767523e5abcf84f949d4223848a0/networkx/drawing/nx_pydot.py#L27

**Comment by dschult** [comment]
I think this dependency should be removed.

We only use it to raise an importerror if the version of pydot is too old.
We already have a version requirement on pydot in requirements/extras.txt
We shouldn't create a dependency to check another dependency

**Comment by maxking** [comment]
That should be even better :)

**Comment by dschult** [comment]
This seems to be fixed already.
