### ISSUE TITLE
After installing I have "No module named networkx"

### ISSUE THREAD

**Issue by aborruso** [networkx/networkx#3175]
Hi all,
I have installed it via pip, but If I import it (`python -c "import networkx"`) I have always "No module named networkx".

And idea on how to solve it?

Thank you

**Comment by mrecachinas** [comment]
What environment are you in and what Python are you using?

My first thought is I'd recommend making sure the `pip` you're using corresponds to the `python` you're using. If you have multiple versions of Python globally installed, they can pretty easily become out of sync. To avoid this case, I usually try to use virtual environments or be explicit with which binary I'm calling -- e.g., `pip2` vs `pip3` and `python2` vs `python3`.

A quick way to rule this out is to run:

```
$ python -V
Python 2.7.15
$ pip -V
pip 18.1 from /usr/local/lib/python2.7/site-packages/pip (python 2.7)
```

If this checks out, and you still can't run `python -c "import networkx"`, I'd then see where `pip` installed `networkx`. You can do this with `pip show`.

```
$ pip show networkx
...
Location: /usr/local/lib/python2.7/site-packages
```

**Comment by aborruso** [comment]
I have just installed in my new system and it works!

**Comment by aborruso** [comment]
Thank you
