### ISSUE TITLE
A tiny typo (“integer”, not “iteger”) in the document about from/to_pandas_edgelist

### ISSUE THREAD

**Issue by komo-fr** [networkx/networkx#3176]
I think that they are “integer”, not “iteger” (I'm sorry if I'm wrong).

**networkx.convert_matrix.to_pandas_edgelist**
https://networkx.github.io/documentation/stable/reference/generated/networkx.convert_matrix.to_pandas_edgelist.html#networkx.convert_matrix.to_pandas_edgelist
> source (str or int, optional) – A valid column name (string or **iteger**) for the source nodes (for the directed case).
> target (str or int, optional) – A valid column name (string or **iteger**) for the target nodes (for the directed case).

**networkx.convert_matrix.from_pandas_edgelist**
https://networkx.github.io/documentation/stable/reference/generated/networkx.convert_matrix.from_pandas_edgelist.html#networkx.convert_matrix.from_pandas_edgelist
> source (str or int) – A valid column name (string or **iteger**) for the source nodes (for the directed case).
> target (str or int) – A valid column name (string or **iteger**) for the target nodes (for the directed case).

I think that these lines are to be modified.
If there is no problem, I will send a PR.

**to_pandas_edgelist**
https://github.com/networkx/networkx/blob/4d265a62206916fecc61afe151f77b21fbe36e6e/networkx/convert_matrix.py#L204-L208

**from_pandas_edgelist**
https://github.com/networkx/networkx/blob/4d265a62206916fecc61afe151f77b21fbe36e6e/networkx/convert_matrix.py#L265-L269

**Comment by dschult** [comment]
Yes -- you are correct.  Thank you!!
