### ISSUE TITLE
Subgraph of a bipartite network fails

### ISSUE THREAD

**Issue by codercahol** [networkx/networkx#3177]
Taking the subgraph of a bipartite network yields a graph that only contains the nodes from the 0th partition of the bipartite network. The nodes from the 1st partition are dropped.

I was specifically using a DiGraph, so maybe it's only a problem in that case.

**Comment by dschult** [comment]
We need more specifics to fix the problem.
Can you create a short example that does the same thing?

**Comment by codercahol** [comment]
`import networkx as nx

net = nx.DiGraph()

top_nodes = list('abcd')
bottom_nodes = list('ABCD')

net.add_nodes_from(top_nodes, bipartite=0)
net.add_nodes_from(bottom_nodes, bipartite=1)
net.add_edges_from([('a','A'),('a','D'),('D','d'),('c','C'),('b','B'),])

subnet = net.subgraph(['a','d'])`

Investigating the `subnet` yields:
`
>> subnet.nodes()
>> NodeView(('a', 'd'))

>> subnet.edges()
>> OutEdgeView([])
`

Even though you would expect the subgraph 'a'->'D'->'d' to be returned

**Comment by dschult** [comment]
The ```subgraph``` method returns an **induced** subgraph.  That means it includes the listed nodes and any edges that connect between those nodes.  Edges from the listed nodes to other nodes are NOT part of the subgraph.  In your case, there are no edges between nodes 'a' and 'd' so no edges are in the subgraph.

You might consider ```pnet = nx.projected_graph(net, ['a','d'])```.  To get the common neighbor node 'D' that makes the projection have an edge, look at the ```multigraph``` optional keyword.

**Comment by codercahol** [comment]
Thanks! I had assumed that the subgraph was returning the closed graph that connected the two nodes, when possible.

I am not interested in getting just one of the node partitions. In 2.2 the `multigraph` keword just adds an edge between `'a'` and `'d'` for each unique path through the other partition.

Is there a way to get all paths from `'a'` to `'d'`? Or is the best way to recursively find (and remove) shortest paths?

**Comment by dschult** [comment]
You should take a look at the [shortest_path](https://networkx.github.io/documentation/latest/reference/algorithms/shortest_paths.html) and [traversal](https://networkx.github.io/documentation/latest/reference/algorithms/traversal.html) functions.  I'm not sure what you mean by "all paths", but there is a function called [nx.all_simple_paths](https://networkx.github.io/documentation/latest/reference/algorithms/simple_paths.html) which might help.
