### ISSUE TITLE
read_gml() differs from documentation

### ISSUE THREAD

**Issue by clayadavis** [networkx/networkx#3184]
The documentation for [networkx.readwrite.gml.read_gml](https://networkx.github.io/documentation/stable/reference/readwrite/generated/networkx.readwrite.gml.read_gml.html#networkx.readwrite.gml.read_gml) states the following:

> * label (string, optional) – If not None, the parsed nodes will be renamed according to node attributes indicated by label. Default value: ‘label’.

Expected behavior: `nx.read_gml('karate.gml', label=None)` will read the file and not rename the nodes.

Current behavior: `nx.read_gml('karate.gml', label=None)` reads the file and attempts to rename the nodes according to their 'label' attribute, which may not exist. In fact, any string passed to the `label=` kwarg is currently ignored because the string `'label'` is used instead of the `label` kwarg: https://github.com/networkx/networkx/blob/be7c67553d2d27db4c66ce20942e6e443c39bef5/networkx/readwrite/gml.py#L424

PR incoming.

**Comment by dschult** [comment]
fixed in #3185 3185
