### ISSUE TITLE
[Feature Request] Topological overlap implementation in networkx? 

### ISSUE THREAD

**Issue by jolespin** [networkx/networkx#3186]
I cannot express how valuable this function would be if it was implemented in `networkx` because as of now I have to use `rpy2` with a very specific environment to use `WGCNA`.  This function takes in an adjacency matrix as a graph and calculates the topological overlap for it.  I usually use this resulting matrix as my fully-connected networkx graph. 

Ideally it would be really useful if there could be 2 functions:
`topological_overlap_from_pandas_adjacency` => from a pandas datafame
`topological_overlap` => from a networkx graph`

Here is the original function from WGCNA: 
https://rdrr.io/cran/WGCNA/man/TOMsimilarity.html

This seems to be a wrapper for some `C` backend? but I'm not entirely sure since I don't know `C` at all. 
https://github.com/cran/WGCNA/blob/master/src/networkFunctions.c

Please let me know if this sounds appealing and I can try to help out. 

Example of this usage in this [preprint](https://www.biorxiv.org/content/early/2018/05/21/325407)

```python
import pandas as pd
import networkx as nx
from sklearn.datasets import load_iris
import numpy as np

# Get iris data
def iris_data(return_target_names=True):
    iris = load_iris()
    # Iris dataset
    X = pd.DataFrame(iris.data,
                     index = [*map(lambda x:f"iris_{x}", range(150))],
                     columns = [*map(lambda x: x.split(" (cm)")[0].replace(" ","_"), iris.feature_names)])

    y = pd.Series(iris.target,
                           index = X.index,
                           name = "Species")
    if return_target_names:
        y = y.map(lambda k: iris.target_names[k])
    return (X, y)

# Force range (-1,1) into (0,1)
def signed(X):
    return (X + 1)/2
X, y = iris_data()
# print(X.shape, y.shape)
# (150, 4) (150,)

# Create pairwise correlations and force values between (0.0-1.0)
df_adj = signed(X.T.corr())
# print(df_adj.shape)
# (150, 150)

# Topological overlap wrapper that uses the function above
# This code essentially just converts the pandas dataframe to r-matrix 
# runs the computation and then brings it back into pandas
df_tom = topological_overlap_from_pandas_adjacency(df_adj)
# print(df_tom.shape)
# (150, 150)

# Fully-connected tom graph
graph = nx.from_pandas_adjacency(df_tom, create_using=nx.Graph(name="iris"))
# print(graph.number_of_nodes())
# 150
```

**Comment by dschult** [comment]
It makes sense to have a ```topological_overlap``` function that acts on NetworkX graphs. The conversion from pandas/numpy/etc can be done by existing functions. It should be written in a module named something like ```topological_overlaps.py``` and put in the algorithms directory.

It would be nice to have a reference rather than code to work from. This concept should have been defined mathematically somewhere. I'm not in favor of defining a concept using the code that computes it, and we should have a reference to cite if we're to include it anyway. So, I guess that is step 1).  Then we need someone to attempt to translate the C coe or the math definition to python. That is usually easier than you might think.

**Comment by jolespin** [comment]
I think that’s a great idea to have a separate module for these functions.  I looked into the literature briefly on my phone and found this publication with the methods: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.93.329&rep=rep1&type=pdf

I am not sure if this extends to fully connected networks or not so I will dig into more details when I get back to my computer. 

I will try to look the C code to see if I can derive some of the meaning . Does networkx use any C code back end scripts beside the graphviz integration or is it mostly pure python ?

**Comment by dschult** [comment]
NetworkX is all pure python. 
We use other packages (like numpy, scipy, matplotlib, pygraphviz,  pydot, etc) that use C backend.  

Your link has a clear definition in Eqn (2) that might be easy to compute in NetworkX. Something like:

    # untested...
    deg = dict(G.degree())
    for i,u in enumerate(G):
        for j,v in enumerate(G):
            if u == v:
                tom[i, j] = 1
            else:
                numer = len(set(G[u]) & set(G[v])) + (v in G[u])
                denom = min(deg[u], deg[v]) + (v not in G[u])
                tom[i. j] = numer / denom
