### ISSUE TITLE
Shell Layout incorrectly rescales for single element shells.

### ISSUE THREAD

**Issue by davidkuhta** [networkx/networkx#3188]
Hi there!

I had a shell layout that used to work with the 1.1 release, but incorrectly overlaps nodes when there is only one element in the shell in the latest build.

Upon inspection, I believe the `rescale_layout` function to be the culprit.
https://github.com/networkx/networkx/blob/794323b9ca4fcd5bb270137ba2fe51bcb78b9a6f/networkx/drawing/layout.py#L252

For a two shell graph with one element in the outer shell: `nlist [[1], [2]]`, `shell_layout` outputs:
`{1: array([0., 0.]), 2: array([0.0, 0. ])}`
where it used to output:
`{1: array([0., 0.]), 2: array([1.0, 0. ])}`

For a two shell graph with two element in the outer shell: `nlist [[1], [2, 3]]`, `shell_layout` correctly outputs:
```
{1: array([0., 0.]),
 2: array([5.00000000e-01, 2.18556941e-08]),
 3: array([-5.00000000e-01, -2.18556941e-08])}
```

We see in the `rescale_layout`, that the positions are being normalized. Unfortunately this means for single node shells, they shift to zero as it's position value is also the mean.
https://github.com/networkx/networkx/blob/794323b9ca4fcd5bb270137ba2fe51bcb78b9a6f/networkx/drawing/layout.py#L889

I believe a simple solution is to first check that there is more than one element:
```python
if len(pos[:,i]) > 1:
            pos[:, i] -= pos[:, i].mean()
```

This results in an acceptable set of positions, while not changing any instances for shells with more nodes:
`{1: array([0., 0.]), 2: array([0.5, 0. ])}`

I'd be happy to submit a PR, once I check to ensure no other issues with the other layouts.

**Comment by davidkuhta** [comment]
### Problem
I believe if we tried to delegate that responsibility `shell_layout` we'd run into issues where only partially rescaling would result in distorted graphs.
For example lets say in shell_layout we tried to rescale only if there were more than one node in a shell:
```python
if len(node) > 1:
    pos = rescale_layout(pos, scale=scale * radius / len(nlist)) + center 
```
Then a call to `shell_layout(nlist=[[1],[2,3],[4]])` would result in:
```python
{1: array([1., 0.], dtype=float32),
 2: array([3.33333343e-01, 1.45704631e-08]),
 3: array([-3.33333343e-01, -1.45704631e-08]),
 4: array([1., 0.], dtype=float32)}
```

### Alternative:
What if we modified the `rescale_layout` such that normalization was optional by means of a default parameter `norm=True`. This would allow the caller to decide the conditions under which the rescaling should include normalization and by using a default argument which encapsulates the current functionality, would not break any other functions.

So `rescale_layout` would become:
```python
def rescale_layout(pos, scale=1, norm=True):
    """
    Parameters
    ----------
    ...
    norm : boolean (default: True)
        normalize positions as part of rescaling.
    ...
    """
    for i in range(pos.shape[1]):
        if norm:
            pos[:, i] -= pos[:, i].mean()
        lim = max(abs(pos[:, i]).max(), lim)
````

Then we could leave it up to the caller on when to rescale.
Therefore `shell_layout` would elect to only normalize when there was more than one node in the shell:
```python
   norm = len(nodes) > 1
   pos = rescale_layout(pos, scale=scale * radius / len(nlist), norm=norm) + center
```

```python
shell_layout2(nlist=[[1],[2,3],[4],[5,6],[7,8,9,10],[11]])

{1: array([0., 0.]),
 2: array([1.66666672e-01, 7.28523153e-09]),
 3: array([-1.66666672e-01, -7.28523153e-09]),
 4: array([0.33333334, 0.        ]),
 5: array([5.00000000e-01, 2.18556941e-08]),
 6: array([-5.00000000e-01, -2.18556941e-08]),
 7: array([6.66666687e-01, 9.93410776e-09]),
 8: array([-2.11942996e-08,  6.66666687e-01]),
 9: array([-6.66666687e-01, -4.83477436e-08]),
 10: array([ 1.58965481e-08, -6.66666687e-01]),
 11: array([0.83333331, 0.        ])}
```

**Comment by dschult** [comment]
I'm suggesting that we *do* scale when there is only one node in a shell. Just not using the ```rescale_layout``` code. Of course, the outer shells have a different radius than inner shells, so we have to scale each shell.  It should be something like:

    if len(node) > 1:
        pos = rescale_layout(pos, scale=scale * radius / len(nlist)) + center 
    else:
        pos = [(scale * radius + center[0], center[1])]    # or something similar

**Comment by davidkuhta** [comment]
While my own coding ideology prefer to modify `rescale_layout` to accommodate optionally scaling without shifting the mean and thereby consolidate all scaling operations, I completely understand the rationale for leaving it untouched (particularly when an if-else will suffice).

`pos = [(scale * radius + center[0], center[1])]` works great.

I'd be happy to pull a PR if you'd like.

**Comment by dschult** [comment]
A PR would be really helpful.  Thank you for being flexible.

**Comment by davidkuhta** [comment]
On a stylistic note, is it also OK in the same PR to modify (I know some repos prefer those type of changes separate):
https://github.com/networkx/networkx/blob/794323b9ca4fcd5bb270137ba2fe51bcb78b9a6f/networkx/drawing/layout.py#L805
to `pos = rescale_layout(pos, scale=scale) + center`

to match the other invocations:
https://github.com/networkx/networkx/blob/794323b9ca4fcd5bb270137ba2fe51bcb78b9a6f/networkx/drawing/layout.py#L174
https://github.com/networkx/networkx/blob/794323b9ca4fcd5bb270137ba2fe51bcb78b9a6f/networkx/drawing/layout.py#L252
https://github.com/networkx/networkx/blob/794323b9ca4fcd5bb270137ba2fe51bcb78b9a6f/networkx/drawing/layout.py#L326
https://github.com/networkx/networkx/blob/794323b9ca4fcd5bb270137ba2fe51bcb78b9a6f/networkx/drawing/layout.py#L340
https://github.com/networkx/networkx/blob/794323b9ca4fcd5bb270137ba2fe51bcb78b9a6f/networkx/drawing/layout.py#L469
https://github.com/networkx/networkx/blob/794323b9ca4fcd5bb270137ba2fe51bcb78b9a6f/networkx/drawing/layout.py#L688

**Comment by wuhaochen** [comment]
I remember we had some discussions about the `rescale_layout` function when I introduced a layout for bipartite networks. You might find #2976 and #2986 helpful.

**Comment by dschult** [comment]
Yes -- ```scale=scale``` is better for line 805.
