### ISSUE TITLE
wrong assortativity formula at least in the documentation

### ISSUE THREAD

**Issue by rLannes** [networkx/networkx#3189]
In the documentation at this link for the attribute_assortativity_coefficient function it is stated that the coefficient = trace(M)-sum(M)) / (1-sum(M))
(https://networkx.github.io/documentation/networkx-1.9.1/reference/generated/networkx.algorithms.assortativity.attribute_assortativity_coefficient.html#networkx.algorithms.assortativity.attribute_assortativity_coefficient)

This is not True the formula from the reference given:
(https://arxiv.org/pdf/cond-mat/0209450.pdf) states that the coefficient = trace(M)-sum(M^2)) / (1-sum(M^2))

I tried to check the code but I don't understand it. So may be is just a documentation flaw...

**Comment by dschult** [comment]
You are correct that the documentation is wrong. The actual formula used in the code is:

(trace(M)-sum(M^2))/(1-sum(M^2))

This documentation error occurs in ```attribute_ac()``` as well as ```attribute_assortativity_coefficient()```
