### ISSUE TITLE
Longest path (diameter) in an undirected graph [question]

### ISSUE THREAD

**Issue by sjackman** [networkx/networkx#3207]
I have a weighted undirected graph, and I'd like to determine the longest path(s) in the graph (any path would do if there are more than one). `distance_measures.diameter` would return the length of that path. `distance_measures.eccentricity` would allow determining the source and target vertices of that path.

As a special case, I've already used `tree.mst.maximum_spanning_tree` to find a maximum spanning tree, and I'm interested in determining the longest path of that tree.

**Comment by sjackman** [comment]
It looks as though `eccentricity` and `diameter` don't accept a `weight` edge attribute.

**Comment by dschult** [comment]
I'm assuming you want the longest shortest-path rather than the longest path.... :)
The eccentricity and diameter functions have an argument ```sp=``` which allows you to provide all-pairs-shortest-path-lengths as a dictionary.  So if you need weighted paths, first use ```sp=dict(all_pairs_shortest_path_length(G, weight='attrname'))``` then send that to the eccentricity function. 

By the way, eccentricity doesn't provide the source and target vertices of that path. Best way to get that is to loop over the ```sp``` dict-of-dict-of-lengths looking for the max and storing that length, source and target as you go.

**Comment by sjackman** [comment]
I want the longest longest simple path, with longest defined as the maximum sum of weights. So, I'm not sure that `all_pairs_shortest_path_length` does what I want. If it helps to restrict the problem domain to trees rather than all undirected graphs, that works for me.

**Comment by sjackman** [comment]
I've just realized that for the case of a tree `all_pairs_shortest_path_length` does do what I want, though it wouldn't for the more general graph. I'll try it out.

**Comment by sjackman** [comment]
I feel like `all_pairs_shortest_path_length` is doing more work than I need though. I only want the maximal path, not all pairs of paths. Is their a function to find the maximal path?

**Comment by sjackman** [comment]
Here's a version that finds the longest path measured in number of vertices, and if there's multiple of those, returns the path with the maximum weight.
```python
        ecc = nx.algorithms.distance_measures.eccentricity(g)
        diameter = nx.algorithms.distance_measures.diameter(g, e=ecc)
        sources = [u for u, d in ecc.items() if d == diameter]
        u, v, length = max(
            ((u, *max(
                single_source_dijkstra_path_length(g, u, weight="n").items(),
                key=lambda x: x[1]))
            for u in sources),
            key=lambda x: x[2])
        path = nx.algorithms.shortest_paths.generic.shortest_path(g, u, v)
```

**Comment by sjackman** [comment]
I'm closing this issue as I've found a solution that works for my particular case. A function that returns the longest path (either unweighted or weighted) in a graph (or a tree) would be awesome though.

**Comment by jfinkels** [comment]
Hi @sjackman. In general, computing the longest path in a graph is an NP-hard search problem! Only if the graph is acyclic (i.e. a directed acylic graph, or a tree in particular) is the problem of finding the longest path solvable in polynomial time. For more information, see https://en.wikipedia.org/wiki/Longest_path_problem

**Comment by sjackman** [comment]
Is there an algorithm in NetworkX to find the longest path in an undirected tree?

**Comment by dschult** [comment]
Be careful -- one of you means "longest path" and the other means "longest shortest path".

**Comment by sjackman** [comment]
This function is much faster than using `eccentricity` and `diameter` to compute the diameter of a tree. It reduced run time from ~30s to <1s with Pypy3. With CPython3 it reduced the run time from 141s to <1s.

@dschult @jfinkels Shall I submit `diameter_of_tree` as a pull request?

```python
    def diameter_of_tree(g, weight=None):
        """
        Compute the diameter of a tree.
        The diameter of an arbitrary component is returned if there are multiple components."
        """
        u = next(iter(g.nodes))
        paths = nx.shortest_path_length(g, u, weight=weight)
        u, _ = max(paths.items(), key=lambda x: x[1])
        paths = nx.shortest_path_length(g, u, weight=weight)
        v, diameter = max(paths.items(), key=lambda x: x[1])
        print(int(timeit.default_timer() - t0), "Computed the diameter of the tree", file=sys.stderr)
        return (u, v, diameter)
```

**Comment by ggrrll** [comment]
> I'm assuming you want the longest shortest-path rather than the longest path.... :)
> The eccentricity and diameter functions have an argument `sp=` which allows you to provide all-pairs-shortest-path-lengths as a dictionary. So if you need weighted paths, first use `sp=dict(all_pairs_shortest_path_length(G, weight='attrname'))` then send that to the eccentricity function.
> 
> By the way, eccentricity doesn't provide the source and target vertices of that path. Best way to get that is to loop over the `sp` dict-of-dict-of-lengths looking for the max and storing that length, source and target as you go.

a little update for ppl using updated v. of nx:
if you want  _weighted_ paths, you have to use now `all_pairs_dijkstra_path_length` , as `all_pairs_shortest_path_length` does not accept weights anylonger
