### ISSUE TITLE
modularity fail with input community as generator 

### ISSUE THREAD

**Issue by saibalmars** [networkx/networkx#3211]
Hi all,
I tried to compute the modularity with build-in community detection algorithm, and figure out that the `is_partition` check of modularity make it fail if the input is a generator of a community.

Basically when modularity called, it feeds the `community` into `is_partition` to check if the given `community` is a valid one, then compute the modularity. However, if you feeds the default output of every current community detection algorithm, which is a generator of `community`, this generator is modified by `is_partition` and cause the follow up computation to fail. 

A quick and dirty fix Is always convert the `community` into a list, or make a copy of generator when `is_partition` is called,  but it seems to against the idea of using generator in 2.0. 
Is there any better idea for that? Or at least mentioned that in the document?

Thanks all!

Here is some sample failing code:
```python
import networkx as nx
G = nx.karate_club_graph()
community = nx.algorithms.community.label_propagation_communities(G)
modularity = nx.algorithms.community.modularity(G,community)
```

Error message:
```
---------------------------------------------------------------------------
NotAPartition                             Traceback (most recent call last)
<ipython-input-4-a4ef4ed5d1fb> in <module>()
----> 1 modularity = nx.algorithms.community.modularity(G,community)

/usr/local/lib/python3.7/site-packages/networkx/algorithms/community/quality.py in modularity(G, communities, weight)
    293     """
    294     if not is_partition(G, communities):
--> 295         raise NotAPartition(G, communities)
    296
    297     multigraph = G.is_multigraph()

NotAPartition: Zachary's Karate Club is not a valid partition of the graph <generator object label_propagation_communities at 0x11c1cfc78>
```

**Comment by dschult** [comment]
I believe the docs say that the input to ```modularity``` must be a list.
Is there any benefit to allowing the input to be an iterator?
I would prefer to require a list as input over allowing an iterator 
that we immediately turn into a list.

**Comment by saibalmars** [comment]
I mentioned this since most of the community detection algorithms networkx yields output as generator, and it's straight forward to feed the result directly to modularity to get the result. It took me a while to figure it out it's the problem of generator and list, so I guess it would be nice to have an example or highlight that in modularity's documentation?

**Comment by dschult** [comment]
Right -- I can definitely see that something in the documentation could emphasize this more than just the type of the input argument. Is there a simple example you know of that we could put in the doc_string that would highlight this?  For example, calling ```modularity``` with the input being the output of a function that returns a generator -- so you have to enclose it in a list...

**Comment by saibalmars** [comment]
Here is a working example, please feel free to revise it as needed.

```python
import networkx as nx
G = nx.karate_club_graph()
community = list(nx.algorithms.community.label_propagation_communities(G)) # Convert returned community generator to list since modularity take list of community structure as input.
modularity = nx.algorithms.community.modularity(G,community) 
print("The modularity of detected communities with label propagation method is %f."%modularity)
```

**Comment by dschult** [comment]
Thanks -- I'll try to incorporate it or something similar into docs...
