### ISSUE TITLE
Switch doc build to Python 3.x

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#3212]
We currently build the docs with python 2.7.
We stop support for python 2.7 after NetworkX v2.2.
So we need to switch the doc building over to some version of Python 3. (probably 3.7?)
I haven't started looking at this seriously yet, but I think most of it will be straightforward changes.

**Comment by jarrodmillman** [comment]
I will create a PR for this sometime next week.   I'll also update related CI items.
