### ISSUE TITLE
ISMAGS subgraph isomorphism algorithm

### ISSUE THREAD

**Issue by pckroon** [networkx/networkx#3216]
Hi all,

First off, thanks for the library; I make heavy use of networkx, and it always seems to have the tools I need already implemented.

Recently however, this was not the case ( :'( ). I work with molecules which to a layman can be described as highly symmetric graphs, and I needed to find subgraph isomorphisms. When using the available VF2 algorithm, this caused a combinatorial explosion of equivalent isomorphisms wrecking performance.

As a result I had to implement the ISMAGS (Index-based Subgraph Matching Algorithm with General Symmetries) [1]. This algorithm find all subgraph isomorphisms that are not symmetrically equivalent. I'm still in the progress of polishing and cleaning, but do you think this would make a nice addition to networkx? If so, I'd be more than happy to open a PR.

[1] https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0097896

**Comment by dschult** [comment]
Yes, I'm interested in this addition to the library!
I'm familiar with the problem of finding general symmetries of a graph -- that can be prohibitively long. If I understand correctly, your PR would use the symmetries to examine subgraphs, reporting one from each symmetry equivalence class.   
Thanks very much!

**Comment by pckroon** [comment]
Effectively, yes. The subgraph isomorphism problem (and by extension automorphism) are still NP-hard, and that doesn't go away unfortunately, 

The ISMAGS algorithm finds a (small? minimal?) set of permutations in the subgraph given, and uses those to generate constraints on the isomorphisms found, So there is only ever one isomorphism found between a graph and itself; any others are de facto symmetery equivalent.

As I said before, the code as I have it now still needs polishing (and there is still the occasional bug), but it's progressing nicely. At the moment my implementation only works for undirected graphs though. I think I know where I need to change it to make work for directed graphs as well, but that's WIP (and not actually my use-case, but that's ok).

Shall I open an "early stage" PR with the proviso that it's still WIP, so that 1) I get an extra pair of eyes on it, and 2) I can unify the code style a bit? I addition, how are tests and coverage currently handled in networkx? At the moment I rely heavily on https://github.com/HypothesisWorks/hypothesis and https://github.com/pckroon/hypothesis-networkx (shameless plug) for testing.
I also have  PR open in my own project to get this in, if you want a sneak peak (https://github.com/marrink-lab/vermouth-martinize/pull/155).

**Comment by dschult** [comment]
It would be great to see an early stage PR. Tests are restricted to unit test style tests using ```nose```. That also tests any examples included in the docstrings. Each directory has a ```tests/``` directory with test modules. The tests are not exhaustive but rather make sure that basic functionality works and that we don't break something inadvertently. The tests are run after each commit to any PR so the idea is to make short routines that test one idea.  It looks like Hypothesis is much more involved than what we use -- but I didn't look at it closely.

**Comment by pckroon** [comment]
Great, I'll get on it ASAP. I have another code review incoming on the project for which I actually implemented it. I'll wait until I have that processed before I open a PR here, that should reduce some duplicate effort. I can work on some of the tests/docs in the meantime.

As you describe it the networkx tests are mostly to prevent (obvious) regressions. Hypothesis is designed more to be sure that code is correct, and 100% coverage is reached. It runs your code with not quite random examples (it's really good at hunting down edge cases). So it works best if you have some invariants that you can check based on input, or if you have a reference implementation.
