### ISSUE TITLE
Would you like to coordinate with Boost Graph Library?

### ISSUE THREAD

**Issue by anadon** [networkx/networkx#3225]
Hello,

I'm helping maintain BGL, and I was looking through some of the older tickets yesterday.  It seems that we lacked functionality you guys needed.  Given the BGL should be able to run things faster and should be somewhat compatible with NetworkX, I'd like to know if someone would be interesting in pointing out where some functionality is wrong or needs to be added, then to merge some functionality?  I think this would be excellent for users.

**Comment by dschult** [comment]
Yes, we're interested in coordinating with BGL -- though the timing is not going to allow (from me) much more than talking about it until the new year.  But if we can talk about what needs to be done maybe we can open issues and others will pitch in.

What old tickets are you referring to?

Any others interested in chiming in with how we could make BGL and NetworkX work together?

**Comment by anadon** [comment]
In particular, these:

https://github.com/boostorg/graph/pull/92
https://svn.boost.org/trac10/ticket/11092

In some ways, BGL has stagnated while NetworkX has been much more lively.  I don't think getting BGL to feature parity is feasible, I would like both general feedback and a list of blockers which would prevent using BGL as a back end for NetworkX.

By the end of this, I would hope that BGL becomes a more sturdy library, the graph ecosystem becomes less divergent, and NetworkX picks up some C++ goodness.  These are all general right now, but as time wears on we can make goals and tasks more explicit.

**Comment by rossbar** [comment]
It's been about ~3.5 years since this was last commented on, so I'm going to go ahead and close this. That's not to say it isn't interesting or worth pursuing! If there's still interest and bandwidth on this front, let's go ahead and open a new issue to start the discussion anew - it'd be good to have a fresh picture of the current status of the project.
