### ISSUE TITLE
Broken links in documentation

### ISSUE THREAD

**Issue by anadon** [networkx/networkx#3226]
Looks like the pages to the GraphML specification are broken.

https://networkx.github.io/documentation/networkx-1.11/reference/readwrite.gml.html

**Comment by dschult** [comment]
Thanks! 

It looks like it has been updated on more recent releases.
https://networkx.github.io/documentation/latest/reference/readwrite/graphml.html

**Comment by anadon** [comment]
Huh, it seems older links are floating around.
