### ISSUE TITLE
Heterogeneous Network

### ISSUE THREAD

**Issue by DeepDeer** [networkx/networkx#3228]
Hi, I'm dealing with a heterogeneous network with Networkx and wondering when using the function "to_scipy_sparse_matrix" is that possible to assign some nodes to the row and other nodes to the column ？
For example, I have a network with paper nodes,  author nodes and conference nodes. Can I use networkx to compute the paper-author adjacent matrix?

**Comment by dschult** [comment]
Probably easiest to form the paper-author subgraph and then see if you need the matrix.

    G=biggraph(...)
    paper_nodes = {n for n in G if G.nodes[n]['type']=='paper'}
    author_nodes = {n for n in G if G.nodes[n]['type']=='author'}
    pa_graph = G.subgraph(paper_nodes | author_nodes)

    # if its really big, maybe use the oneliner
    pa_graph = G.subgraph((n for n in G if G.nodes[n]['type'] in ['author', 'paper']))

The subgraph is a view on the original graph, so it doesn't use up memory. If you plan to change it then create a copy:  ```pa_graph = pa_graph.copy()```
