### ISSUE TITLE
Default color for draw_networkx() is not colorblind-safe

### ISSUE THREAD

**Issue by elplatt** [networkx/networkx#3233]
Currently black labels on red background, which can't be read by some red-green colorblind individuals (including myself). The safest would be to go with a blue color. Any objections?

**Comment by dschult** [comment]
That seems good to me.

Here's a plug for a project related to this stuff that needs some energy: -- there is a package called GraVE which integrates ideas and code from Matplotlib and NetworkX to ease and enable better drawing.   https://github.com/networkx/grave
