### ISSUE TITLE
pyspark load hdfs pickle file fail

### ISSUE THREAD

**Issue by karterotte** [networkx/networkx#3235]
HI:
   I've used pyspark to generate network graph on hdfs. 
and it works:
`pickle.load(local file)`
but it doesn't work:
 `nx.read_gpickle(G, hdfs file)`
The Report is 

> G = pickle.loads(rh.readByte())
> 
> File "/home/master/platform/spark210/python/lib/py4j-0.10.4-src.zip/py4j/java_gateway.py", line 1133, in __call__
> 
> File "/home/master/platform/spark210/python/lib/pyspark.zip/pyspark/sql/utils.py", line 63, in deco
> 
> File "/home/master/platform/spark210/python/lib/py4j-0.10.4-src.zip/py4j/protocol.py", line 319, in get_return_value
> 
> py4j.protocol.Py4JJavaError: An error occurred while calling o1095.readByte.
> 
> : java.io.EOFException
> 
> at java.io.DataInputStream.readByte(DataInputStream.java:267)
> 
> at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
> 
> at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
> 
> at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> 
> at java.lang.reflect.Method.invoke(Method.java:498)
> 
> at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
> 
> at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:357)
> 
> at py4j.Gateway.invoke(Gateway.java:280)
> 
> at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
> 
> at py4j.commands.CallCommand.execute(CallCommand.java:79)
> 
> at py4j.GatewayConnection.run(GatewayConnection.java:214)
> 
> at java.lang.Thread.run(Thread.java:745)

What should I do to load graph file from hdfs?
Thanks

**Comment by ericmjl** [comment]
Looking at the traceback, this looks like a Spark issue, and not a NetworkX issue, because the final Python call in the traceback comes from `py4j` and not NetworkX. 

Have you raised this issue with the pyspark team?

**Comment by karterotte** [comment]
It seems there is no issue-entry in pyspark github page.
Thanks for your reply.
