### ISSUE TITLE
Converting a 2D list to a Graph

### ISSUE THREAD

**Issue by ekohilas** [networkx/networkx#3236]
Hi,

Is there existing functionality to convert a 2D grid (list of lists) of nodes into a networkx graph?

Cheers!

**Comment by ericmjl** [comment]
@ekohilas check out the docs: https://networkx.github.io/documentation/stable/reference/classes/graph.html

A number of class methods exist to add nodes and edges from a Python iterable.

**Comment by ekohilas** [comment]
Thanks @ericmjl 
However the to_networkx_graph() function only says that it supports

-          any NetworkX graph
-          dict-of-dicts
-          dict-of-lists
-          list of edges
-          Pandas DataFrame (row per edge)
-          numpy matrix
-          numpy ndarray
-          scipy sparse matrix
-          pygraphviz agraph

Instead I have a 2D Grid, which is a list of lists containing node values, and I would like to import them as a graph where each value is connected to the values above, below left and right.

I would like to perform BFS on this graph to find the shortest paths from a given node.

Is there no known method of doing so?

**Comment by ericmjl** [comment]
I see, your question is clearer now. It appears that this is not implemented in NetworkX, unless my cursory search of the docs was incomplete.

If you figure it out, though, I'd encourage you to contribute it to the library. Good software gets built that way, and NetworkX (and other contributions) are full of similar contributions that the rest of us have benefited from! A name for a function that does what you're trying to do might be `from_lattice()` or `from_grid()`.

**Comment by jfinkels** [comment]
The `grid_2d_graph()` generator might be useful to you: https://networkx.github.io/documentation/stable/reference/generated/networkx.generators.lattice.grid_2d_graph.html#networkx.generators.lattice.grid_2d_graph
