### ISSUE TITLE
write_graphml doesn't like custom object 

### ISSUE THREAD

**Issue by gabri94** [networkx/networkx#3237]
I'm using the attributes of my graph to store custom object that i need for my software. 
I'd like to be able to export it in graphml without removing this object, but i understand that graphml cannot compose the xml for a custom object. 
However I expected to be able, by defining the __str__ or __repr__ method, to allow the graphml method to use its string representation in the graphml. 

By looking at the code I don't think this has been implemente, but would it be possible?

**Comment by dschult** [comment]
How hard would it be to 
1) copy the graph
2) iterate over the edges and replace each custom object with its string representation
3) write the result as graphml
That might be the most straightforward way.

**Comment by gabri94** [comment]
Yes, this was my idea. That would also work for the lists
Are u going to implement it soon or I can give it a try?

**Comment by dschult** [comment]
Please go ahead and write some code! :)  If you have questions, ask... and its fine to submit a PR that is incomplete for feedback.  It is easy to update and add commits to the PR.  There might even be a way to attach the PR to this issue, but the easy way is to make a PR that simply says "Fixes #3237" somewhere in the description.    Thanks!!

**Comment by gabri94** [comment]
can you give it a look? i used str because it was already there, and i just had to change 1 line of code.
