### ISSUE TITLE
Allow curved edges

### ISSUE THREAD

**Issue by adamhaber** [networkx/networkx#3240]
Hi,

I'm interested in plotting a bidirectional directed graph in a way that the arrows aren't overlapping. It seems like it should be relatively easy to tweak the call `FancyArrowPatch` to include such curved arrows. Would that be a relevant/interesting pull request? 

Sorry if it's a silly question, first time I'm trying to contribute to an OSS at this scale :-)

EDIT: Also tried to label this as an "enhancement" but wasn't able to. Would be happy to understand why.

**Comment by CatcherGG** [comment]
It's pretty old question and probably no longer relevant for you.
But for documentation purposes, you can do it this way:
`nx.draw_networkx_edges(G, pos, width=edge_width, connectionstyle='arc3,rad=0.1', ...)`

**Comment by dschult** [comment]
fixed in #3307
