### ISSUE TITLE
Geometric network downstream accumulation

### ISSUE THREAD

**Issue by thomasbalstroem** [networkx/networkx#3241]
Hi all,

lI'm new to Networkx and very impressed how easy and quick I can carry out a downstream and upstream tracing in a graph. 

Now, does anyone know, if I can use NetworkX to accumulate water volumes being transported downstream in a so called geometric network (GN)? 
 
What I'm interested in is presented in Figure 7 in my article from Computers & Geosciences [https://doi.org/10.1016/j.cageo.2018.04.010]:

Long story told short: I have a graph with nodes representing sinks, and edges representing downstream water paths from sink to sink. What I need to consider is if there is a spill over at each sink (node). If yes carry the spill over along the downstream edges into the next sink, consider if there is a spill over etc. 

Are you aware of any NetworkX alghorithm(s) that can do so for a hierarchical network? 
     
Best regards, 
     
Thomas Balstrøm
Associate Professor in Geoinformatics
Dept. of Geosciences and Natural Resources Management
University of Copenhagen
Denmark

**Comment by jfinkels** [comment]
I'm not familiar with a "geometric network", but you it looks like you have a directed acyclic graph. After a cursory glance, one thing you might want to try is doing a [`topological_sort()`](https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.dag.topological_sort.html#networkx.algorithms.dag.topological_sort), then traversing the sorted list of nodes in order and adding any overflow from each node to its neighbors.

**Comment by thomasbalstroem** [comment]
Thank you very much for this hint. I'm 'the geographer' meeting the graph professionals, so I appreciate your guidance. I will look into the documentation ASAP on this topic and re-enter the discussion if necessary.
Best regards, Thomas
