### ISSUE TITLE
all_node_cuts stuck when load of work is high

### ISSUE THREAD

**Issue by yaakovML** [networkx/networkx#3244]
Hi.

I have a dataframe (pandas) with many rows, I then groupby the df by using an indicator and using every group as a graph.

While receiving other features (is_connected, number_connected_components, ...) works well.
Trying to apply all_node_cuts fails.

short debuting showed that it stopped after around 1000 rows (or around 300 of groups).

The code:

```
def create_bipartite_graph(df):
    G = nx.Graph()
    G.add_nodes_from(df['device'].values, bipartite=0)
    G.add_nodes_from(df['screen'].values, bipartite=1)
    G.add_weighted_edges_from([tuple(x) for x in df[['device', 'screen', 'weight']].values])
    return G

def assign_graph_properties2(df):
    G = create_bipartite_graph(df)
    node_cuts = 0 if not nx.is_connected(G) else len(list(nx.all_node_cuts(G)))
    return pd.DataFrame([node_cuts] * len(df))

c = d.groupby(by=['user'])[['device', 'screen', 'weight']].apply(func=assign_graph_properties2).values
```

After way many hours of trying things, I would love to get any advise what's wrong.

**Comment by hagberg** [comment]
Needs more information to be able to debug any issue here.
