### ISSUE TITLE
Speeding up double edge swap (migrated from Trac #328)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#325]
Original ticket https://networkx.lanl.gov/trac/ticket/328
Reported 2010-03-21 by trac user joelmiller, assigned to @hagberg.

I've come across some cases where it is relatively rare for a network to remain connected after an edge swap.  For the current code it will check if the entire network is still connected, which is slow.  If successful, then it will do two swaps before checking if the entire network is still connected, at which point if there is a failure it will undo both swaps and start over.

There is a faster test when only one edge swap has been done.  The disadvantage of testing each time is that in many cases the vast majority of swaps leave a connected network, and so it may be faster to do many swaps and then use the slower test.  The existing code makes this assumption, and tries to estimate the optimal number of swaps by dynamically increasing the number as there are more successes and halving the number if there is a failure.

I have created a modified code.  If the 'optimal' number of swaps appears to be small (at present <3), then it will simply check after each swap if the network is still connected.  If the number gets larger it will switch to checking only after many swaps.  I believe this code will always be faster than the pre-existing code.  

However, it may be able to make it faster by changing the cutoff between the two methods to a larger value.  In fact, if we test the cpu time each time it tests whether the network is still connected, we can get a good idea of which method is faster.  If the slower test takes 10 times as long, then the window should be a bit larger than 10 before we switch to that test.  I haven't tried to implement that but it would probably be a significant speed up and ensure that the approach is working well for all sorts of different network types.

**Comment by jfinkels** [comment]
@chebee7i This should be closed due to merging of #1475.

**Comment by chebee7i** [comment]
Thanks!
