### ISSUE TITLE
configuration_model is incorrect for normal nx.Graph

### ISSUE THREAD

**Issue by tjiagoM** [networkx/networkx#3257]
I needed to use `configuration_model` (https://networkx.github.io/documentation/stable/reference/generated/networkx.generators.degree_seq.configuration_model.html) in a project but for normal `nx.Graph`.

In the documentation it is obvious that your return is a `MultiGraph`, but I want a `Graph` without any self-loops or parallel edges. The only thing you have for `Graph`s is to use `G.remove_edges_from(nx.selfloop_edges(G))`. However, by using this method it is also obvious that your resulting degree distribution will not be the same as the initial one that I want to mimic.

I ended up implementing a solution for this and would be able to make a PR with that, but I wanted to check whether you are already aware of this problem and implementing a solution already, in which case I don't need to make any PR.

**Comment by hagberg** [comment]
There is a good (short) discussion on self-loop and parallel edges here https://en.wikipedia.org/wiki/Configuration_model#Algorithm

Self-loops and parallel edges are not a problem but a consequence of the algorithm.   It may be possible to swap some edges to realize a graph (without parallel edges or self loops) and with the same degree distribution.  If you would like to contribute such an algorithm please do make a PR.
