### ISSUE TITLE
Problem with nx.partial_duplication_graph

### ISSUE THREAD

**Issue by edgaramorim** [networkx/networkx#3258]
Hi everyone,
the operations on the partial_duplication_graph algorithm are out of order. One should first select a node to replicate and then include a new node. 

Also, the edge connecting the original node and the replica should be added after the other edge. If you do it before, the replica is considered a neighbor of the original one and you won't have the desired result.

**Comment by dschult** [comment]
You are correct that the new node should not get self-loop edges and by adding an edge to ```u``` before duplicating the neighbor edges, we make it possible to create a self-loop edge ```v-v```.  This doesn't align with the doc_string order either.  That should be fixed... Probably good to check the article to check whether the code aligns with the paper, or the doc_string aligns with the paper (are self-loops created for the new node or not).

I pretty sure the order of selecting ```u``` and then adding ```v``` doesn't impact the results.  But we might as well make it agree with the doc_string description.

**Comment by edgaramorim** [comment]
In fact, the deal about selecting "u" and adding "v" is that we choose a node "u" randomly to be duplicated and then add a node "v" to be "u"'s replica. If you add "v" before selecting "u", there is a slight chance that you select the recently added node "v" to be replicated, and that would make no sense for the model and does not agree with the doc_string description. But it's certainly good to check the article.

thank you for the attention.

**Comment by dschult** [comment]
Yes -- I agree with you that you can't choose u to be v.  But the code doesn't allow that because it doesn't choose from all nodes, only from ```range(0,newN)``` which excludes the new node.

**Comment by edgaramorim** [comment]
Here is the part of the code that selects the node to be replicated:

- src_node = random.randint(0, new_node)

In fact, the node to be duplicated have to be chosen from range(0, newN). But the function random.randint(), that is used to select the node to be replicated, takes into account "newN" to the selectable nodes. Maybe the alternative should be:

- src_node = random.choose(range(0, new_node))

or

- src_node = random.randint(0, new_node-1)

**Comment by dschult** [comment]
Ahh -- thank you for persisting -- now I understand where my confusion is coming...

The code actually doesn't use the ```random.randint``` function.  It uses ```seed.randint``` where ```seed``` created by the decorator ```@py_random_state```. The function ```numpy.Random.randint``` does not include the upper endpoint, while the ```random.randint``` does. I got those two confused...

So... better to switch the order to what the docs say, and also to make that code clearer... Otherwise we could (as the current code allows) choose u to be ```new node``` which is not good.

Thanks again...
