### ISSUE TITLE
Making an nxn torus interconnect with networkx

### ISSUE THREAD

**Issue by krishvishal** [networkx/networkx#3264]
I'm trying to make a 2D dimensional torus interconnect using `networkx` library in python. I have achieved this using the following code in matlab.

```matlab
    %..points for grid....%
    S=4;  % Side length of grid
    N=S^2;    % Number of nodes in network
    
    v1=[1:S];
    [c1 c2]=meshgrid(v1,v1);
    
    points(:,1)=2*c1(:);
    points(:,2)=2*c2(:);
    %...end of points for grid...%
     
    D=squareform(pdist(points));   % Caluclate distances between points
    D1=D+eye(N);
    
    Dbin=D<RI;                      % Deciding conflicting nodes
    
    %......Extra edges for torus.....%
    for i=1:S
        Dbin(i,i+(S-1)*S)=1;
        Dbin(i+(S-1)*S,i)=1;
        
        Dbin(S*i,S*(i-1)+1)=1;
        Dbin(S*(i-1)+1,S*i)=1;
    end
    %......Extra edges for torus.....%
```

I can do something similar in python using numpy, but I want to use `networkx` library. I don't know how to do this. 

Edit:

I've created a square lattice using the following code. But have to figure out how to connect the peripheral edges as shown in the figure below.

```python
    import networkx as nx
    
    G = nx.grid_graph(dim = [4,4])
```

Is there a way to generalize this to an nxn grid with peripheral connections.

This is how the graph looks like. [![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/gtUox.png

**Comment by dschult** [comment]
I think [```grid_2d_graph``` ](https://networkx.github.io/documentation/stable/reference/generators.html) should do what you want. 

Use the ```periodic=true``` optional argument to make it a torus.

```grid_graph``` also has the ```periodic``` optional argument. They may be equivalent for what you want... but ```grid_graph``` can do an n-dim lattice.

**Comment by krishvishal** [comment]
Thank you, I have overlooked `periodic` parameter while reading the documentation. Can you tell me why it was named periodic ?
