### ISSUE TITLE
Add Floyd-Warshall for average_shortest_path_length

### ISSUE THREAD

**Issue by wuhaochen** [networkx/networkx#3266]
I just find that the function `average_shortest_path_length` by default is using the Dijkstra's algorithm to computer all pairs of shortest path, which is inefficient for dense graph. It doesn't support using Floyd-Warshall algorithm. I'm no sure if we should make this as the default as well.

I can send a PR if you think this change is reasonable.

**Comment by dschult** [comment]
Right now the ```average_shortest_path_length``` function allows methods dijkstra, bellman-ford or unweighted. It would make sense to add the option of using Floyd-Warshall. 

The default method for most shortest path computations is dijkstra.  It should stay that way -- that is what "most people" will want. If you have a dense network then you should change from the default.

Thanks!

**Comment by wuhaochen** [comment]
Sounds good. I just noticed one more thing there.
Currently `average_shortest_path_length` only require a directed network to be weakly connected and count the length of unreachable pairs as 0. I don't think this is a correct behavior. For example, in a network with two nodes a and b and only an edge a, b, the function will return 0.5.

I think the right thing to do here is to require it to be strongly connected. Should I open a separate PR for this?

**Comment by dschult** [comment]
Yup -- two PRs are appropriate for these two items.

I think the definition of average shortest path length should depend on a literature search if possible. The application to directed graphs ought to do what is standard in the literature -- or provide both possibilities if both are popular in the literature.

(I'm actually not sure why an average of 0.5 for the graph a->b is bad.... isn't that what you would want?)

**Comment by wuhaochen** [comment]
One of the issue is that average for the graph a<->b is 1. Adding edges reduced connectivity should be counter-intuitive.

**Comment by dschult** [comment]
Ahh..  you are pointing out that the other path (from b to a) has infinite shortest path length so the average should be (1+\infty)/2 or something like that... that's why it shouldn't be allowed.  Am I understanding?

it's hard to find examples where average shortest path is used... even for undirected graphs. Are there any papers/books with this defined for directed graphs?

**Comment by dschult** [comment]
In the case of strongly connected graphs, the current code gives the same result. So restricting it to only work for that type of directed graph means we are removing something without adding anything except possibly protecting a user from misunderstanding what is happening. I would prefer to do this with the docs rather than with code.  The same could be said for disconnected undirected graphs. But there we have an obvious alternative -- take average of each component. 

What do we suggest to users who want the average for a weakly connected graph?

**Comment by wuhaochen** [comment]
I think this is a good point.

The alternative could be as I mentioned before, i.e. only averaging over number of reachable pairs, in which case the denominator shall not be n(n-1).

The alternative for undirected graph is not so obvious. Are you suggesting a weighted average or just simple average? What weight should be used among components? If we are only taking simple average. Consider a large network with `n` nodes where the `n-2` nodes are in a components with average path length roughly `log n` and the other two nodes are an isolated pair. The simple average would be `(log n)/2`. Adding one edge between one of these two nodes to the connected components would raise the average to `log n`.
Similar problem exists if the average is weighted by number of nodes or number of edges.
If weighted by the number of possible pairs of nodes, it reduced to what I mentioned in the last paragraph and can be extended to weakly connected directed graph and disconnected graph.


We can add another argument to the function to let the user choose if they want to allow the computation on disconnected graph.
However, a similar argument as you just mentioned can be raised here: This extension will give the same result as current code on connected undirected graph and strongly connected directed graph. Therefore this new option may not be necessary.
Nonetheless personally I would like to introduce such option so that users are aware of the potential problem.
If this is what we want, the signature of the function could become:
`def average_shortest_path_length(G, weight=None, method=None, allow_disconnected=False):`
and the code should raise error on weakly connected digraph if `allow_disconnected` is `False`.

**Comment by dschult** [comment]
I am thinking that we already have an alternative for undirected graphs.  The code gives an error and the docs show you what to do with an explicit example. (Compute the average on each component separately.) 

That doesn't work so nicely for directed graphs. Many people will want to recreate what has already been done in previous papers (using the denominator n(n-1)). If we make it raise an error for a weakly (and not strongly) connected network, then what do we put in the docs to suggest for those people to recreate this measure that is apparently popular?

Maybe 2 examples with something like this:

    # commonly used definition
    path_length = nx.shortest_path_length(G)
    s = sum(length for u, pl_dict in path_length for length in pl_dict.values())
    print("Average path length: ", s / (n * (n - 1)))

or for a more "correct" denominator use:

    # perhaps more sensical definition (dividing by number of actual paths)
    path_length = nx.shortest_path_length(G)
    (s,num_paths) = (0,0)
    for u, pl_dict in path_length:
        num_paths += len(pl_dict)
        s += sum(pl_dict.values())
    print("Average path length: ", s / num_paths)

**Comment by wuhaochen** [comment]
I don't think the measure as what is defined in wikipedia is popular by any means, it looks more like a typo to me as I've never seen this measure defined this way anywhere else. I think the most common practice for weakly connected graph is to calculate this for its undirected version (like what we did in `to_undirected`), which is not the same as what the function is returning now.
Besides, google suggests [this page](https://mathinsight.org/definition/network_mean_path_length) for the definition and it adopt infinity for unreachable pairs.

As what I put on the previous examples, I would think that treating distance between unreachable pairs as 0 will render an usefulness measure and should not be called average path length. Therefore we probably should prevent people to do that accidentally.

On the other hand I'd be happy to hear about how such definition could be useful, but unless there is any paper or a compelling reason stating how this definition is useful, I would hold my standings.

We might want to do a more thorough literature review for this for now and leave it open to see how other people feel about this issue.
