### ISSUE TITLE
Parallel betweenness

### ISSUE THREAD

**Issue by visez** [networkx/networkx#3270]
Hi, I was looking at the parallel betweenness example as it is the only one in the repo that gives an idea of how to parallelize the networkx functions. 

In line 50, node_divisor is defined as 
`    node_divisor = len(p._pool) * 4`

Is there any reason for that 4x multiplication? It means that it creates 4 times as many groups as there are cores available, which I cannot see a reason for.

Can anyone explain its function?

**Comment by LucaCappelletti94** [comment]
It isn't uncommon to split the job in a number of tasks bigger than the processors, it clearly depends on the expected size of the graph. Therefore, it may be more proper to adjust the number of blocks on the size of the graph: I may be looking into this soon enough, if it is decided to proceed for implementing a number of functions using multiprocessing.

As to why not using exactly `n=size of pool`, it generally has to do with the expected size of the resulting object or just to receive partial results every n blocks. For instance, it is common to store the partial results in case something goes wrong down the line (memory errors, for example). In the code you pointed out it doesn't seem to be the case, if I'll get the time I'll fix up the code.
