### ISSUE TITLE
An encoding error dealing with '\0'

### ISSUE THREAD

**Issue by penelope24** [networkx/networkx#3273]
Here is the story:
First I have an dot file which contains a node with label "\000"
Then I changed the file's format from dot to gexf.  the "\0" becomes "NUL" and the "00" after it despaired.
At last I wanted to read the gexf file using
```
nx.read_gexf(g)
```
and I got an error
```
 "cElementTree.ParseError: not well-formed (invalid token)"
```
 which indicates that the gexf(xml) format is somehow wrong. After checking I found this error is caused by "\0" in the initial dot file, which is "NUL" in the gexf file.
So I think this might be a bug.

**Comment by dschult** [comment]
You don't say much about how you are converting formats.
It sounds like the bug is in the format conversion code.

**Comment by penelope24** [comment]
@dschult the convert process is simply the following code: 
```
g = read_dot (file_path)
write_gexf(g, output_path)
```

**Comment by dschult** [comment]
Do you know enough about the formats to tell me what the change should be or where the bug might be. For example, is NUL the right thing to put in the gexf file? How should \000 be handled?
