### ISSUE TITLE
duplicated node in one connected component

### ISSUE THREAD

**Issue by handsomefun** [networkx/networkx#3274]
`
         
      g = nx.Graph()

      for (a, b) in pairs:

           g.add_edge(a, b)

      for community in nx.connected_components(g):

            print '%s' % (','.join([str(node) for node in community]))
`
I have used the code above to build a graph with nodes more than 1 million , Then generate 160000 connected components.

But I found there are  many node belong to  two components(i think they should be merged), and one node appears in one component twice.

I want to know is it an issue, or i have some misunderstandings about graph or connected components.

**Comment by dschult** [comment]
Each node should appear in only one component and a single node cannot appear twice in the same component.

Almost certainly it looks like one node in one component twice and it is actually two different nodes. And/or it looks like the same node in more than one component and they are actually different nodes.

Basically, it is likely that reporting results using ```str(node)``` is not showing you enough information to distinguish node from each other.  Nodes in NetworkX are key objects in a dict and if they don't satisfy ```node1==node2``` they aren't the same even if ```str(node1)==str(node2)```

**Comment by handsomefun** [comment]
@dschult 
In this case, each node( such as a, b in code snippet) is a long type number, which is an item id.
I find same item ids in one connected component.

**Comment by dschult** [comment]
The connected components are stored as sets of nodes, and sets cant have the same object more than once. I'm not sure what the problem is, but it is deeper than what is apparent.
