### ISSUE TITLE
barabasi_albert_graph does not start off with a connected network

### ISSUE THREAD

**Issue by voronaam** [networkx/networkx#3281]
`barabasi_albert_graph` starts with `G=empty_graph(m)` instead of `G = complete_graph(m)`.
As a result, the early new nodes are almost certain to become hubs, since the distribution is heavily skewed in their favour. The initial `m` nodes have almost zero chance to be a hub.

To reproduce:
```
hubs = []
for i in range(100):
    G = nx.barabasi_albert_graph(1000,500)
    hubs.append(sorted(G, key=lambda n: len(G[n]), reverse=True)[0])
count_dict={}
for hub in hubs:
    count_dict[hub]=hubs.count(hub)
print ('\nfrequency:\t',count_dict)

# prints
# frequency:	 {500: 34, 501: 27, 502: 13, 503: 10, 504: 11, 505: 2, 506: 3}
```

The first new node (500) has the highest chance of becoming the hub. This is not random enough.

Quote from Wikipedia ( https://en.wikipedia.org/wiki/Barab%C3%A1si%E2%80%93Albert_model ):
> The network begins with an initial connected network of m_0 nodes. 

And logically it has to start from a connected network for the initial `m` nodes to have a chance to be a hub.

The effect would not be noticeable in "small world" kind of networks (medium node degree << number of nodes) but is profound in networks with n and m close enough to each other.

**Comment by hagberg** [comment]
Hi Aleksey - Thanks for your code and comments.
There are many different "preferential attachment" models one could use
(and many have been explored in the literature). I think the goal for the
barabasi_albert_graph code was to implement the model in this paper
http://barabasi.com/f/67.pdf.
Can you take a look and see if that is the case?

It looks like there are a couple of other barabasi-albert variants in the
networkx code base - see
https://github.com/networkx/networkx/blob/master/networkx/generators/random_graphs.py
If there are other useful variants perhaps suggest adding them?

Aric

**Comment by voronaam** [comment]
Unfortunately, neither of the original papers by those authors indicate the edges between the original `m_0` nodes. This is the reason I had to use Wikipedia link above to support this issue.

Logically, the original `m` nodes has to be fully connected. Consider what happens if `m=1000` and they are not. The first new node added will have to form `1000` connections, so it will connect to every single pre-existing one. The second new node will arrive and see a thousand nodes with degree 1 and 1 node with degree 1000. It will be 1000 times more likely to connect to the first new node, than to any of the other existing ones.

If the original 1000 nodes form a connected graph, the second new node will see 1001 nodes with degree 1000 and will have equal chance of connecting to any of them. Thus, it will be much harder to predict which of the early nodes will grow to become a hub.

**Comment by hagberg** [comment]
Yes, I agree with your assessment.    And for the barabasi_albert_graph algorithm in networkx I'm advocating to keep it as written to match the original paper. 

I'd recommend either adding an option (not the default) to fully connect the initial nodes or a separate algorithm that implements that variant.   In principle one could initialize the algorithm with any graph on m nodes.

**Comment by voronaam** [comment]
If it helps, here is a snippet of what I am using now.

```
from networkx.utils import random_weighted_sample

def generate_sf(n, m0, m):
    """
        Create a Barabási–Albert graph
    """
    G = nx.complete_graph(m0)
    while len(G) < n:
        degrees = {node: val for (node, val) in G.degree()}
        node = len(G)
        G.add_node(node)
        targets = random_weighted_sample(degrees, m)
        G.add_edges_from(zip([node]*m,targets))
    return G
```

It also allows for `m < m_0`, as in the original paper.
Performance is not great, though. I think his is due to reinitialization of weights (`degrees`) on every iteration. This snippet can be improved for inclusion into networkx.
