### ISSUE TITLE
undirected_view() (migrated from Trac #332)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#329]
Original ticket https://networkx.lanl.gov/trac/ticket/332
Reported 2010-04-12 by @chebee7i, assigned to @chebee7i.

Currently, to_undirected() makes a deep copy of the graph.  It might be nice to have the returned graph be a "view" where only the structure is rebuilt (but all the graph, node, edge data is the same).  This would additionally require adding the reverse of every edge...this would make the returned graph not a pure "view".

Use case?  Perhaps people might be interested in seeing how their directed graphs behave in undirected graph algorithms (without having to do an expensive deepcopy).

**Comment by hagberg** [comment]
Implemented in networkx-2.0
