### ISSUE TITLE
`draw_networkx` behaves differently when `node_size` is provided

### ISSUE THREAD

**Issue by rubenvereecken** [networkx/networkx#3295]
If I call `draw_networkx` with something like

```
nx.draw_networkx(g, edgelist=[(0, 1, 0)])
```
that is, with the egelist a list of tuples of length 3, all works well. However, if I in addition pass a `node_size` argument that is an iterable, the behaviour changes and it expects edgelist to consist of tuples of length 2:
```
nx.draw_networkx(g, edgelist=[(0, 1, 0)], node_size=[10, 20])
```
```
/home/ruben/anaconda3/lib/python3.6/site-packages/networkx/drawing/nx_pylab.py in draw_networkx_edges(G, pos, edgelist, width, edge_color, style, alpha, arrowstyle, arrowsize, edge_cmap, edge_vmin, edge_vmax, ax, arrows, label, node_size, nodelist, node_shape, **kwds)
    659             shrink_target = 0  # space from  head to target
    660             if cb.iterable(node_size):  # many node sizes
--> 661                 src_node, dst_node = edgelist[i]
    662                 index_node = nodelist.index(dst_node)
    663                 marker_size = node_size[index_node]

ValueError: too many values to unpack (expected 2)
```
It may have got something to do with an assumption on graph type, my graph was of type `MultiDiGraph`.

This is not a big issue and easily worked around, but I thought I'd point out the inconsistent behaviour, if indeed it is.

**Comment by dschult** [comment]
Thank you for reporting this!

It is a bug. The offending line should allow edge 3-tuples from multigraphs by the code:

    src_node, dst_node = edgelist[i][:2]

We should check that section of code for other similar bugs and add a test that reveals this issue.

**Comment by rubenvereecken** [comment]
:tada:
