### ISSUE TITLE
edge_subgraph() (migrated from Trac #333)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#330]
Original ticket https://networkx.lanl.gov/trac/ticket/333
Reported 2010-04-12 by @chebee7i, assigned to @dschult.

I'm interested in adding methods for returning edge-induced subgraphs.  For my use, I definitely do not need copies at all...I need these to be views, because all I want to do is analyze the properties of these subgraphs.  I'll wait to hear on #314 before writing the code.  Does this sound like something of general interest?

**Comment by jfinkels** [comment]
There seems to be an `edge_subgraph` implementation in `networkx.algorithms.trees.branchings`, for some reason. (It is not used anywhere, and definitely doesn't belong in its current module.)

**Comment by dschult** [comment]
Closed by #1740.  But it isn't a view.  It is a shallow copy however. 
When we get a view version we can update it.
