### ISSUE TITLE
nx.shortest_path ignores `weight` parameter

### ISSUE THREAD

**Issue by pavelmk** [networkx/networkx#3300]
Hi, [according to the nx 2.2 documentation](https://networkx.github.io/documentation/networkx-2.1/reference/algorithms/generated/networkx.algorithms.shortest_paths.generic.shortest_path.html#networkx.algorithms.shortest_paths.generic.shortest_path), the `nx.shortest_path` function should take an edge attribute as a distance metric when computing path length. However, as you can see, in the screenshot + paste below, that's not the observed behavior: 
<img width="718" alt="screen shot 2019-01-13 at 11 00 19 pm" src="https://user-images.githubusercontent.com/9423009/51099717-347ad600-1787-11e9-80ab-464b2b653cf8.png">

same thing as above, but selectable:
```
>>> import networkx as nx
>>> G = nx.DiGraph()
>>> G.add_edges_from([(0, 1), (1, 3)], attr_dict={'custom_weight': 10})
>>> G.add_edges_from([(0, 2), (2, 3)], attr_dict={'custom_weight': 1})
>>> nx.shortest_path(G, source=0, target=3)
[0, 1, 3]
>>> nx.shortest_path(G, source=0, target=3, weight='custom_weight')
[0, 1, 3]
>>> G.edges()
OutEdgeView([(0, 1), (0, 2), (1, 3), (2, 3)])
>>> G.edges(data=True)
OutEdgeDataView([(0, 1, {'attr_dict': {'custom_weight': 10}}), (0, 2, {'attr_dict': {'custom_weight': 1}}), (1, 3, {'attr_dict': {'custom_weight': 10}}), (2, 3, {'attr_dict': {'custom_weight': 1}})])
```

Best,
Pavel

**Comment by dschult** [comment]
The ```attr_dict``` argument to ```G.add_edges_from``` is not supported in v2.2. It has been replaced with

    G.add_edges_from([(0,1), (1,3)], custom_weight=10)
    G.add_edges_from([(0,2), (2,3)], custom_weight=1)

You can see this because in your example, the edge attribute dict has one key: ```attr_dict``` instead of the key ```custom_weight``` as desired. When ```shortest_path``` looks up the edge, it doesn't find an attribute called ```custom_weight``` so the weight defaults to 1.

**Comment by pavelmk** [comment]
Thank you for your quick response @dschult -- I must have been referring to an older (1.X) version of the `add_edges_from` API! I'll mark the issue as resolved.
