### ISSUE TITLE
How many nodes do networkx support?

### ISSUE THREAD

**Issue by YuanliangZhang** [networkx/networkx#3303]
Hello,
I have a grah which has 500,000 nodes, I want to get Shortest Path Algorithm with networkx in python, does networkx support?
I read doc but haven't found max nodes support.
Thanks a lot.

**Comment by ericmjl** [comment]
With shortest path, and many more, it’s possible to use NetworkX, though you’re limited at that point by computational complexity rather than memory. I’d encourage you to try it out on a subset of nodes or a smaller graph first if you’re feeling unsure.
