### ISSUE TITLE
Let has_path(G, source, target) return False if either node is not in G

### ISSUE THREAD

**Issue by kumom** [networkx/networkx#3305]
I am implementing an agent-based model lately and need to maintain a subgraph that is dynamically calculated at each step. So when I was checking whether there exists a path from node v to w by looping through all nodes, v or w might not be in the subgraph.

I was expecting `has_path(G, source, target)` to return `False` if either node is not in the graph, but it raised `NodeNotFound` instead. I looked at the source code and see it is calling `nx.shortest_path(G, source, target)` internally. Can I add a few lines to check the existence of nodes before calling the path finding method?

**Comment by dschult** [comment]
It seems to me that it is a feature that this raises an exception if the nodes are not present in G.
Otherwise it might hide a bug in someone's code.  Can you use something like this instead?

    source in G and target in G and has_path(G, source, target)

**Comment by kumom** [comment]
I am using exactly this solution to implement the model. Thanks for clarifying the design choice.
