### ISSUE TITLE
problem of installation pygraphviz in windows 8.1 64 bit

### ISSUE THREAD

**Issue by kurdmanrasol** [networkx/networkx#3310]
Hey everyone,

I have a problem with pygraphviz library during installation. I am using windows 8.1 64 bit. and also I installed C++.  Please how can I solve it

Command "e:\python_64_372\python.exe -u -c "import setuptools, tokenize;__file__
='C:\\Users\\Kurdman\\AppData\\Local\\Temp\\pip-install-1y961u4y\\pygraphviz\\se
tup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n'
, '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Use
rs\Kurdman\AppData\Local\Temp\pip-record-banftlge\install-record.txt --single-ve
rsion-externally-managed --compile" failed with error code 1 in C:\Users\Kurdman
\AppData\Local\Temp\pip-install-1y961u4y\pygraphviz\

**Comment by hagberg** [comment]
See https://github.com/pygraphviz/pygraphviz/issues/207
