### ISSUE TITLE
networkx.nx_pydot.graphviz_layout fails for graphs with a lot of attribute information

### ISSUE THREAD

**Issue by FFroehlich** [networkx/networkx#3311]
`graphviz_layout(G, prog='dot')` passes the full graph (including edge and node data) to dot.
When (indiviual?) edges or nodes have too much data, dot with fail with an error message like

> syntax error in line 2 scanning a quoted string (missing endquote? longer than 16384?)\nString starting: ...

This error goes away when simply passing a copy of the graph without the edge/node data to graphviz_layout: `graphviz_layout(nx.Graph(G.edges), prog='dot')`. Might be worthwhile to always do that as edge/node data should not affect layout generation, right?

**Comment by dschult** [comment]
The code ```nx.Graph(G.edges)``` will not include isolated nodes in the layout.
Perhaps better to use what is called a "Fresh Copy" in [the G.copy docs](https://networkx.github.io/documentation/latest/reference/classes/generated/networkx.Graph.copy.html).  Something like:

    H=G.__class__()
    H.add_nodes_from(G)
    H.add_edges_from(G.edges)
    pos = graphviz_layout(H, prog='dot')
