### ISSUE TITLE
getting error with nx.read_gpickle 

### ISSUE THREAD

**Issue by SriSatyaLokesh** [networkx/networkx#3319]
sc = nx.read_gpickle('Datasets/Synthetic Social Network.pkl')

plt.figure(figsize=(10,7))

nx.draw_networkx(sc,node_color='c',node_size=900,with_labels=True)

#### I'm getting the following error
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-9375c01ff16d> in <module>
      3 plt.figure(figsize=(10,7))
      4 
----> 5 nx.draw_networkx(sc,node_color='c',node_size=900,with_labels=True)

~/.local/lib/python3.6/site-packages/networkx/drawing/nx_pylab.py in draw_networkx(G, pos, arrows, with_labels, **kwds)
    273 
    274     if pos is None:
--> 275         pos = nx.drawing.spring_layout(G)  # default to spring layout
    276 
    277     node_collection = draw_networkx_nodes(G, pos, **kwds)

</home/satya/.local/lib/python3.6/site-packages/decorator.py:decorator-gen-782> in fruchterman_reingold_layout(G, k, pos, fixed, iterations, threshold, weight, scale, center, dim, seed)

~/.local/lib/python3.6/site-packages/networkx/utils/decorators.py in _random_state(func, *args, **kwargs)
    403         new_args = list(args)
    404         new_args[random_state_index] = random_state
--> 405         return func(*new_args, **kwargs)
    406     return _random_state
    407 

~/.local/lib/python3.6/site-packages/networkx/drawing/layout.py in fruchterman_reingold_layout(G, k, pos, fixed, iterations, threshold, weight, scale, center, dim, seed)
    441         pos_arr = None
    442 
--> 443     if len(G) == 0:
    444         return {}
    445     if len(G) == 1:

~/.local/lib/python3.6/site-packages/networkx/classes/graph.py in __len__(self)
    430 
    431         """
--> 432         return len(self._node)
    433 
    434     def __getitem__(self, n):

AttributeError: 'Graph' object has no attribute '_node'

**Comment by dschult** [comment]
The pickled graph was created from an old version of NetworkX. Judging from the date on a version of a file named that which I found with a google search, that graph was created with NetworkX v1.11.

To convert the graph in that file to a NetworkX v2.x graph, you should get a version of Python that has NetworkX v1.11 installed and:

- read the pickle file
- pickle the nodes, edges and graph attributes using something like:

    pickle([sc.nodes(data=True), sc.edges(data=True), sc.graph])  # not tested

- start a new python session with a version of python that has NetworkX v2.x installed.
- read in the pickled list of nodes/edges/attributes
- create a graph from that info:

    sc=nx.Graph()
    sc.add_node_from(stuff[0])
    sc.add_edges_from(stuff[1])
    sc.graph.update(stuff[2])

- Then pickle sc to a file called ```Synthetic_Social_Network_v2.x.pkl``` or similar.
