### ISSUE TITLE
Error in min cycle basis

### ISSUE THREAD

**Issue by msollami** [networkx/networkx#3321]
In the following example, I think it the first item in the list returned should be [1,2,5,4] not [1,2,4,5] which is not a cycle since 2 is not incident to 4:

```
import networkx as nx
G = nx.Graph()
G.add_edge(1,2);G.add_edge(1,4);G.add_edge(2,3);G.add_edge(2,5);G.add_edge(3,6);G.add_edge(4,5);G.add_edge(4,7);G.add_edge(5,6);G.add_edge(5,8);G.add_edge(6,9);G.add_edge(7,8);G.add_edge(8,9)
nx.minimum_cycle_basis(G)
# [[1, 2, 4, 5], [2, 3, 5, 6], [4, 5, 7, 8], [5, 6, 8, 9]] 
```

**Comment by dschult** [comment]
The [docs for minimum_cycle_basis](https://networkx.github.io/documentation/latest/reference/algorithms/generated/networkx.algorithms.cycles.minimum_cycle_basis.html) warn that the cycle list does not order the nodes in the order they appear in the cycle.
