### ISSUE TITLE
is_graphical treats numpy int as not integers

### ISSUE THREAD

**Issue by sukhwanchung** [networkx/networkx#3322]
There is a minor issue with using `is_graphical` function with numpy array.
When passing a numpy array with integers as the argument, `is_graphical` automatically returns `False` because numpy `int` type is not an instance of python `int` type.

Also there is no warning regarding the data type of input so I was very confused for a while when I had a clearly graphical degree sequence passed to the `is_graphical` and was returned `False`.

I would suggest considering numpy int as a valid integer type, otherwise I have to recreate a list of python integers from the array of numpy integers.

Also I think it is reasonable to raise an exception or print a warning when the data type of the input degree sequence is not a valid integer, because this case is fundamentally different from not being able to pass HH or EG tests. 

```
>>> import networkx as nx
>>> import numpy as np
>>> a = np.array([2,2,2])
>>> b = [2,2,2]
>>> nx.is_graphical(a)
False
>>> nx.is_graphical(b)
True
```

**Comment by dschult** [comment]
Thanks for this.
