### ISSUE TITLE
RecursionError maximum recursion depth networkx.pagerank

### ISSUE THREAD

**Issue by YEslahi** [networkx/networkx#3331]
I am running the page rank from networkx as follows:

` rankingDict = networkx.pagerank(G, alpha=0.85)`
in my directed graph G, I have 32 nodes.

and the error I get is:

> RecursionError maximum recursion depth exceeded while calling a Python object

As it was recommended, I have changed my stack to 8000
 `sys.setrecursionlimit(8000)`
and still, I am facing the same exception and I imagine I cannot make any improvement on this line to avoid it.  

please let me know what further information I need to provide. 

Thanks in advance.

**Comment by dschult** [comment]
Hmmmm... This seems strange. I don't think there is any recursion in the pagerank function.
Could the recursion be coming from some other code? Am I missing something that recurses?

**Comment by YEslahi** [comment]
No i don't think you are missing something. it is as simple as that. and to be sure it comes exactly from here:
try:
        rankingDict = networkx.pagerank(G, alpha=0.85)
except RecursionError:
            print("RecursionError maximum recursion depth exceeded while calling a Python object- Handled! )

and it is handled !

**Comment by dschult** [comment]
Definitely strange. I don't see how this could arise -- and I cant reproduce it.
If your DiGraph has only 32 nodes can you describe it for us? 
Any node attributes? edge attributes? simple code to construct?

**Comment by YEslahi** [comment]
as an example, one of the graphs that i have this exception on it is:
`print("G.Nodes: \n",G.nodes)`

> G.Nodes: 
>  [729168, 1231426, 335987, 253879, 1235290, 1235053, 551054]

`print(G.edges(data=True))`

> [(729168, 1231426, {'weight': -0.247}), (729168, 335987, {'weight': 0.617}), (729168, 253879, {'weight': -0.15}), (729168, 1235290, {'weight': 0.591}), (729168, 1235053, {'weight': 0.262}), (729168, 551054, {'weight': -0.072}), (1231426, 729168, {'weight': -1.076}), (1231426, 335987, {'weight': 0.241}), (1231426, 253879, {'weight': -0.639}), (1231426, 1235290, {'weight': 0.053}), (1231426, 1235053, {'weight': 0.228}), (1231426, 551054, {'weight': 2.193}), (335987, 729168, {'weight': -0.192}), (335987, 1231426, {'weight': -0.017}), (335987, 253879, {'weight': 0.023}), (335987, 1235290, {'weight': 0.749}), (335987, 1235053, {'weight': 0.319}), (335987, 551054, {'weight': 0.119}), (253879, 729168, {'weight': 0.28}), (253879, 1231426, {'weight': 0.273}), (253879, 335987, {'weight': 0.138}), (253879, 1235290, {'weight': -0.507}), (253879, 1235053, {'weight': 0.86}), (253879, 551054, {'weight': -0.045}), (1235290, 729168, {'weight': -0.209}), (1235290, 1231426, {'weight': -0.004}), (1235290, 335987, {'weight': 0.851}), (1235290, 253879, {'weight': -0.096}), (1235290, 1235053, {'weight': 0.266}), (1235290, 551054, {'weight': 0.194}), (1235053, 729168, {'weight': -0.133}), (1235053, 1231426, {'weight': -0.027}), (1235053, 335987, {'weight': 0.521}), (1235053, 253879, {'weight': 0.235}), (1235053, 1235290, {'weight': 0.382}), (1235053, 551054, {'weight': 0.022}), (551054, 729168, {'weight': 0.14}), (551054, 1231426, {'weight': -0.974}), (551054, 335987, {'weight': 0.738}), (551054, 253879, {'weight': -0.047}), (551054, 1235290, {'weight': 1.059}), (551054, 1235053, {'weight': 0.084})]


in case it is needed:

`Sigma_kInV_dict = {}
    #calculating the denominator and save in dict:
    for k1, k2 in itertools.permutations(G.nodes,2):
        if(k1 in Sigma_kInV_dict):
            Sigma_kInV_dict[k1] += model.similarity("Q" + str(k1), "Q" + str(k2))
        else:
            Sigma_kInV_dict[k1] = model.similarity("Q" + str(k1), "Q" + str(k2))


#TODO: use itertools.permutations and merge two directions of edges
#first direction of edges
for k1, k2 in itertools.combinations(Keys, 2):
            G.add_edges_from(((u, v, {'weight':round( model.similarity("Q" + str(u), "Q" + str(v))/Sigma_kInV_dict[u],3) })
                    for u, v in itertools.product(Vertices[k1], Vertices[k2])))
    
#second direction of edges
for k1, k2 in itertools.combinations(Keys, 2):
            G.add_edges_from(((u, v, {'weight': round( model.similarity("Q" + str(u), "Q" + str(v))/Sigma_kInV_dict[u],3) })
                    for u, v in itertools.product(Vertices[k2], Vertices[k1])))
    
print(G.edges(data=True))`

**Comment by dschult** [comment]
I don't get any error message. What version of networkx? 

 ```
In[23]:    G.nodes
Out[23]: NodeView((729168, 1231426, 335987, 253879, 1235290, 1235053, 551054))

In [24]: G.edges(data=True)
Out[24]: EdgeDataView([(729168, 1231426, {'weight': -1.076}), (729168, 335987, {'weight': -0.192}), 
(729168, 253879, {'weight': 0.28}), (729168, 1235290, {'weight': -0.209}), (729168, 1235053, 
{'weight': -0.133}), (729168, 551054, {'weight': 0.14}), (1231426, 335987, {'weight': -0.017}), (1231426, 
253879, {'weight': 0.273}), (1231426, 1235290, {'weight': -0.004}), (1231426, 1235053, {'weight': 
-0.027}), (1231426, 551054, {'weight': -0.974}), (335987, 253879, {'weight': 0.138}), (335987, 
1235290, {'weight': 0.851}), (335987, 1235053, {'weight': 0.521}), (335987, 551054, {'weight': 0.738}), 
(253879, 1235290, {'weight': -0.096}), (253879, 1235053, {'weight': 0.235}), (253879, 551054, 
{'weight': -0.047}), (1235290, 1235053, {'weight': 0.382}), (1235290, 551054, {'weight': 1.059}), 
(1235053, 551054, {'weight': 0.084})])

In [25]: nx.pagerank(G, alpha=0.85)
Out[25]: 
{729168: -0.13400158128832415,
 1231426: -0.25457331794498744,
 335987: 0.4078567642526132,
 253879: 0.116677068471361,
 1235290: 0.4142263868147926,
 1235053: 0.20887382796901605,
 551054: 0.24094085172552873}
```

**Comment by YEslahi** [comment]
my version is 2.2.

**Comment by YEslahi** [comment]
thanks for all the replies. the problem was from my side and multiprocessing package. 
thanks.
