### ISSUE TITLE
Why there are different results of shortest path in the Graph while using different API?

### ISSUE THREAD

**Issue by LouisYZK** [networkx/networkx#3333]
I want get the shortest path in one graph and i try some apis like *The shortest_path_length, shortest_path, dijkstra_predecessor_and_distance*.
but the results are different, some are right and some are wrong!

```python
a, b, c, d, e, f, g, h = range(8)
G = {
    a: {b:2, c:1, d:3, e:9, f:4},
    b: {c:4, e:3},
    c: {d:8},
    d: {e:7},
    e: {f:5},
    f: {c:2, g:2, h:2},
    g: {f:1, h:6},
    h: {f:9, g:8}
}
nx_G = nx.Graph()
edges = [(u, v, G[u][v]) for u in G for v in G[u]]
nx_G.add_weighted_edges_from(edges)

print(dijkstra_predecessor_and_distance(nx_G, a))
print(shortest_path_length(nx_G, a))
print(shortest_path(nx_G, a))
```
result:
(path: {0: [], 1: [0], 2: [0], 3: [0], 4: [1], 5: [2], 6: [5], 7: [5, 6]}, distance:{0: 0, 2: 1, 1: 2, 3: 3, 5: 3, 6: 4, 4: 5, 7: 12}) 
{0: 0, 1: 1, 2: 1, 3: 1, 4: 1, 5: 1, 6: 2, 7: 2}
{0: [0], 1: [0, 1], 2: [0, 2], 3: [0, 3], 4: [0, 4], 5: [0, 5], 6: [0, 5, 6], 7: [0, 5, 7]}

First api output the wrong distance and path, the last one outputs alright, and the 2nd ignores the weight.... 
How could it be??

**Comment by dschult** [comment]
The docs for these function describe default values that affect the path calculation.
The most obvious one is which edge attribute to use as a weight. 
The default for ```shortest_path_length``` is all edges have weight 1.
You need to specify more info if the default values aren't giving you what you want.
