### ISSUE TITLE
Bug in networkx/algorithms/shortest_paths/unweighted.py

### ISSUE THREAD

**Issue by ghareth** [networkx/networkx#3338]
Line 415/416 of **networkc/algorithms/shortest_paths/unweighted.py** reads

`    if target not in G:
        raise nx.NodeNotFound("Target {} not in G".format(source))`

should read 

`    if target not in G:
        raise nx.NodeNotFound("Target {} not in G".format(target))`

**Comment by dschult** [comment]
Thank you -- see #3339
