### ISSUE TITLE
Closeness centrality assumes symmetric distance when "distance" parameter is used

### ISSUE THREAD

**Issue by jlopezpena** [networkx/networkx#3341]
At the beginning of `nx.closeness_centrality` code there is this logic:

```python
    if distance is not None:
        # use Dijkstra's algorithm with specified attribute as edge weight
        path_length = functools.partial(nx.single_source_dijkstra_path_length,
                                        weight=distance)
    else:  # handle either directed or undirected
        if G.is_directed() and not reverse:
            path_length = nx.single_target_shortest_path_length
        else:
            path_length = nx.single_source_shortest_path_length
```

This means that if `distance` parameter is passed then the direction of the edges is ignored, and the `reverse` parameter has no effect.

Is this a design decision? I have directed networks with non-symmetric distances and am interested in both inbound and outbound centralities. It looks to me this would be a simple change (checking `reverse` and using `nx.single_target_dijkstra_path_length` if needed). Am willing to make a PR if this is deemed an appropriate change.

**Comment by dschult** [comment]
This actually looks like a bug to me -- at least on first look.
The dijkstra method works for an undirected graph. 
Does it even work for a directed graph? Say: a single edge (0, 1). 

Also, there is no function ```single_target_dijkstra_path_length```, so the quick fix is different. Now that we have an efficient way to reverse graphs (nx 2.x), it might be best to simply check the reverse flag at the beginning and just use ```G=G.reverse()``` or similar to handle that case. 

But first thing is to check that a directed graph is treated correctly for weighted edges.

Thanks!

**Comment by jlopezpena** [comment]
> Does it even work for a directed graph? Say: a single edge (0, 1).

It looks like so:

```python
g = nx.DiGraph()
g.add_nodes_from([0,1])

g.add_edge(0, 1, distance=1)
g.add_edge(1, 0, distance=2)

nx.closeness_centrality(g, distance="distance")
```
outputs `{0: 1.0, 1: 0.5}`, and using `nx.reverse(g)` instead of `g` transposes the numbers as expected.
If the second edge is removed, then output is `{0: 1.0, 1: 0.0}`, as expected (and also works after manually reversing).  

If `nx.reverse` is efficient and not too memory taxing, I agree that adding a conditional

```
if reverse:
    G = nx.reverse(G)
```
at the beginning of the computation makes more sense. My networks are small, so for me that will not be an issue, but larger networks might take a hit. Perhaps `nx.reverse_view` instead, or using `copy=False` if that is more resource friendly?

**Comment by dschult** [comment]
Your edited comment is key:  The djikstra shortest path computes outward closeness, not inward as we advertise.  I think that means that currently if our graph has all edge weights 1, we get reversed results for using weighted as compared to unweighted methods.   Hmmm... 

Fixing this could provide a backward compatible headache. We should document it with strong warnings that for NX2.3+ using directed weighted edges gives correct (inward) values whereas for previous versions the directed weighted edges give correct (outward) values and ```reverse``` had no affect.

Assuming ```reverse=False```, in order to compute the inward closeness, we will need to reverse the edges in the weighted case. For the unweighted case, we essentially do that inside ```single_target_shortest_path_length```.  Maybe it would be cleaner to reverse the edges in both cases and use ```single_source_shortest_path_length``` for the unweighted case.  

When ```reverse=True```, then we would NOT reverse the edges...   A little turned around perhaps, but it stems from closeness centrality being defined as looking at inward connections.  

Thoughts?

**Comment by jlopezpena** [comment]
I don't see a way of fixing this without breaking backwards compatibility. On the other hands, the old results are not what was documented, so I believe it is a necessary collateral damage; documentation and strong warnings can certainly alleviate the pain.

Regarding the API,  I think is is perverse that `reverse=True` means that the graph is not reversed, but I don't see an easy way out of it. Options are redefine closeness to be outwards by default (breaking all the old code!), or changing the `reverse` flag name to something else that is more sensible.

In either case, we could keep raising `DeprecationWarning` for a while until whatever the new API/defaults settles. Since I am not a core developer, I will defer this decision to the people that are more involved with the code, I am willing to help implementing the PR with whatever is agreed on.

**Comment by dschult** [comment]
I'm leaning toward getting rid of the ```reverse``` argument. We can reverse graphs easily now so users can simply call it on ```G.reverse()``` instead of ```G```. Fewer arguments also makes the interface that much cleaner. In the code we can reverse any directed graph input in order to provide the inward closeness as advertised.
