### ISSUE TITLE
issues about the function 'preferential_attachment_graph' for bipartite networks

### ISSUE THREAD

**Issue by jiaoyang2018** [networkx/networkx#3342]
Hi, when using the function of  'preferential_attachment_graph'  to generate  a random bipartite network, how to set the probability 'p'?

I have checked the journal paper,  'Jean-Loup Guillaume and Matthieu Latapy, Bipartite structure of all complex networks, Inf. Process. Lett. 90, 2004, pg. 215-221', which gives a formula to calculate 'p'. But I wonder if the 'p' is the ratio of number of nodes to the sum of the sizes of the cliques, not 1 minus the ratio. 

Looking forward to your reply.

**Comment by dschult** [comment]
Hmmm..    Perhaps the best way to figure this out is to take an extreme case and see what ```p``` is.
For example, if ```p=1``` do you get the ratio or 1 minus the ratio?

The function requests ```p```, so you can choose to set it however you like. But I think you are seeking info about what impact that choice has on the structure.

**Comment by jiaoyang2018** [comment]
Thank you for your reply. 

The author had made a mistake in this paper. I have found their another paper, 'Guillaume, J.L. and Latapy, M., 2006. Bipartite graphs as models of complex networks. Physica A: Statistical Mechanics and its Applications, 371(2), pp.795-813.', in which p equals the ratio.

**Comment by jiaoyang2018** [comment]
I recommend that the reference paper be changed to the correct one, or the current one for this function may make people confused.

Thank you

**Comment by dschult** [comment]
Maybe both references would be helpful.
