### ISSUE TITLE
handling of numpy dtypes

### ISSUE THREAD

**Issue by mdeff** [networkx/networkx#3343]
Networkx doesn't seem to handle well attributes that are of NumPy types.

An instance of the problem is with writers. The following works with floating point dtypes, but fails for integer dtypes.
 
```python
import networkx as nx
import numpy as np
from scipy import sparse

adjacency = sparse.csr_matrix([
    [0, 1, 2],
    [1, 0, 0],
    [2, 0, 0],
], dtype=np.float)
graph = nx.from_scipy_sparse_matrix(adjacency)

type(graph.edges()[(0, 1)]['weight'])  # returns numpy.float64

nx.write_graphml(graph, 'graph.graphml')
nx.write_gml(graph, 'graph.gml')
nx.write_gexf(graph, 'graph.gexf')
```

By replacing `dtype=np.float` with `dtype=np.int`, we get the following:
* For GraphML: `NetworkXError: GraphML writer does not support <class 'numpy.int64'> as data values.`.
* For GML: `NetworkXError: 1 is not a string`.
* It works for GEXF, and is saved as an int (e.g., `<edge id="0" source="0" target="1" weight="1" />`).

Other instances of the general problem I could find are #2204 and #3322.

Wouldn't the best approach be to internally convert NumPy dtypes to Python types?

**Comment by MridulS** [comment]
Thanks for filing this! All of the formats should have better support now.

 - GraphML succeeds (it's saved as a string but it can recovered back to ints
 ``` python
>>> nx.write_graphml(graph, 'graph.graphml')
>>> G = nx.read_graphml('graph.graphml',node_type=int)
>>> nx.is_isomorphic(G, graph)
True
```
 - It also works with GML by using (de)stringizer
``` python
>>> nx.write_gml(graph, 'graph.gml', stringizer=str)
>>> G = nx.read_gml('graph.gml', destringizer=int)
>>> nx.is_isomorphic(G, graph)
True
```
I'm closing this one, feel free to open a new issue if there are any issues :)
