### ISSUE TITLE
Faster Triangle Counting

### ISSUE THREAD

**Issue by shellshock1911** [networkx/networkx#3345]
I've noticed the networkx triangle counting algorithm is quite slow - about 5 minutes for a graph with 2^10 vertices and 16 times as many edges. One reason is that triangles are explicitly double counted, which is corrected by dividing the counts by two at the end. I have a method, call it "minimal count", that sorts the nodes in a manner prior to counting that avoids double-counting - saving double the time or more. Is this something worth putting in a pull request for? It doesn't involve any C or Cython - just Python. Thanks!

**Comment by dschult** [comment]
We don't require nodes to be sortable. So if a graph didn't have nodes that could be sorted, you'd need a way to circumvent that when using your strategy. One idea would be to create a 2-way mapping from the nodes to an ordered set (say-- the integers 0 to n-1 where n is number of nodes). Then sort based on that ordered set.
node_list = list(G.nodes)   # node number to node => node_list[number]
node_map = {n: i for i, n in enumerate(G)}   # node to node number  =>  node_map[node]

You'd spend more time looking up the node values in the mapping, but less time counting triangles. I don't know whether it would be faster in the end or not.

**Comment by shellshock1911** [comment]
Ah I see. The kind of sort I'm doing is to first sort by degree (which should be universal?) -- and then by integer ID, i.e. topological sort. I didn't consider the case where nodes are strings for example. The times I was reporting did include all intermediate data structure building, but building an ID map would incur more overhead, so I'll look into it, and see it might still be worth it for more general graphs.
