### ISSUE TITLE
Passing arguments to graphviz_layout

### ISSUE THREAD

**Issue by apeano** [networkx/networkx#3348]
It seems there is no way to pass arguments to the graphviz's programs, e.g.:
`pos = graphviz_layout(G, prog='dot', args='-Grankdir=LR')`
where G is a networkx graph.

I tried in different ways, like "args='-Grankdir=LR'" but "dot" is never affected by this.

Any idea?

**Comment by dschult** [comment]
Unfortunately, there are two versions of ```graphviz_layout``` in the networkx package. Which are you referring to?  It might be better to call them ```pydot_layout``` and/or ```pygraphviz_layout```.  Looking at the code, it seems that ```pydot_layout``` ignores any ```args``` while ```pygraphviz_layout``` at least forwards the ```args``` keywords on to the pygraphviz package.  It also seems to me that the doc_strings in ```pydot_layout``` and its version of the wrapper ```graphviz_layout``` should be updated to at least list the possible arguments correctly.
