### ISSUE TITLE
Consider views for graphs (migrated from Trac #338)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#335]
Original ticket https://networkx.lanl.gov/trac/ticket/338
Reported 2010-04-14 by @dschult, assigned to @dschult.

It would be nice to have a fast way to process parts of a graph.
A view could be faster than creating the induced subgraph
because it might not have to create the whole graph structure.
Let's see if that is really true.

**Comment by dschult** [comment]
This is implemented in #2523
