### ISSUE TITLE
Fix slow implementation of networkx.algorithms.community.quality.performance

### ISSUE THREAD

**Issue by ecastrillov** [networkx/networkx#3350]
Hi,

I was using the quality function **performance** on a small graph with 4039 nodes 88234 edges and 186 communities, but the current implementation takes minutes to complete, while using the alternate implementation of functions **inter_community_edges**, **inter_community_non_edges** and **intra_community_edges** (which you have # commented in the code) takes a fraction of a second.

Why do you prefer the current implementation over the alternate one? The alternate is clean, easy to understand and way faster.

Thanks.

**Comment by dschult** [comment]
I don't see any good reason not to use the commented out code.  Perhaps the current code could be left as a code comment in case it is easier to understand what it is intending to compute.

**Comment by rossbar** [comment]
It looks like this was likely closed by #4536. If there are further performance gains to be made, please feel free to reopen this or submit a new issue/PR.
