### ISSUE TITLE
Add function to calculate weight of a specific path

### ISSUE THREAD

**Issue by patsumby-sohonet** [networkx/networkx#3357]
I can create a graph with edges with multiple attirbute weights on the edges (ie $cost and latency).

I can identify the shortest path based on cost or the shortest path based on latency.

What I can't do is find the cost of the shortest latency path or find the latency of lowest cost path.

I've worked around this by writing a helper function as follows:

```python
def cost_of_path(graph,path,metric):
        total = 0
        hops = len(path)
        for i in range(1,hops):
                value = min([v[metric] for v in graph[path[i]][path[i-1]].values()])
                total += value
        return total

cost_of_path( G, [A,B,C], "latency") # returns latency of this path
cost_of_path( G, [A,C], "cost") # returns $ cost of this path
```

[A.B,C] is the lowest $ cost path.
[A,C] is the lowest latency path

Seems this should be easy enough to add in and would be a useful function of the system.

The "min([v[metric] for v in graph[path[i]][path[i-1]].values()])" line is because I'm using a multigraph and there are potentially multiple edges between some pairs of nodes.

Loving networkx though, very useful.

**Comment by dschult** [comment]
This seems like a reasonable addition. Let's make it work for directed/undirected/multiedge 
A good place for it could be in classes/functions.py but I'm open to suggestions...

**Comment by manesioz** [comment]
To generalize this you essentially want a function to calcluate the cost of *any* arbitrary path, not necessarily the shortest one (relative to your weight).

Surprisingly there doesn't seem to be any general function for this (`all_simple_paths()` is close but it generates paths unnecessarily, we already have a single one in mind), but it seems like it would be easy to implement (using the available `traversal` methods). What do you think?

**Comment by dschult** [comment]
No traversal is needed. The path is already known and provided. You just need to loop over the edges and add up the edge attributes along that path.

```python
    def path_weight(G, path, weight):
        for n, nbr in nx.utils.pairwise(path):
            sum G[n][nbr][weight]
```
Obviously this pseudocode doesn't work, but something close to it should work.
Then make it work for multiedge, etc.

**Comment by manesioz** [comment]
I was thinking of also implementing some error checking to determine if the sequence of nodes is valid before we blindly compute the cost but I noticed that I don't think there's a function that accepts a sequence of nodes and a graph ([here](https://networkx.github.io/documentation/networkx-1.9.1/_modules/networkx/algorithms/shortest_paths/generic.html#has_path) we see `has_path()` which accepts a start and end node, but in this case we care about what intermediary nodes) so do you think it would be helpful to implement that as well?

**Comment by dschult** [comment]
I guess this function will do that -- if the path doesn't exist in the graph, there will be a KeyError we could catch and raise a NoPathFound error.   

And yes, you could create a function ```is_path``` to return True/False based on whether a path is found or not.

I'm sure there are many ways to construct these functions. So if another way makes more sense, go with it. :)
