### ISSUE TITLE
networkx causes its own warning

### ISSUE THREAD

**Issue by pb-cdunn** [networkx/networkx#3359]
I understand from #3230 that python2 is no longer supported. However, my *goal* is to switch to python3, and in order to achieve that I am first running `python2.7 -3 -Werror ...` on my own code. I cannot do this because networx warns about networkx:
```py
  File "/scratch/cdunn/.git/BASE/lib/python2.7/site-packages/networkx/classes/digraph.py", line 1180, in reverse
    H = self.fresh_copy()
  File "/scratch/cdunn/.git/BASE/lib/python2.7/site-packages/networkx/classes/graph.py", line 1446, in fresh_copy
    warnings.warn(msg, DeprecationWarning, stacklevel=2)
DeprecationWarning: G.fresh_copy is deprecated. Use G.__class__ instead
```
This really causes a problem in migration.

**Comment by dschult** [comment]
Fixed in #3278 
Sorry about this. It'll be fixed in version 2.3 (coming pretty soon).
