### ISSUE TITLE
Make `shortest_path` use `bidirectional_dijkstra` as a default

### ISSUE THREAD

**Issue by joelmiller** [networkx/networkx#3368]
Currently by default if a user calls `shortest_path` with a source and a target but no weight, the algorithm will use `bidirectional_dijkstra` regardless of the method the user inputs.

But when the user has a weighted network, it will use either `bellman_ford` or `dijkstra` depending on the user's choice (with `dijkstra` the default).  I think `dijkstra` is slower than `bidirectional_dijkstra` in every case I've encountered.  So I feel like that should be added as an option, and perhaps it should be the default when source and target are known and the user hasn't specified which method to use.

**Comment by mohdkashif93** [comment]
Is it okay if I look into this issue ?
