### ISSUE TITLE
Incorrect betweenness centrality calculation for directed weighted graphs

### ISSUE THREAD

**Issue by deemeetree** [networkx/networkx#3369]
I calculate betweenness centrality of a directed, weighted graph using this measure: 

https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.algorithms.centrality.betweenness_centrality.html

However, as it turns out, your algorithm gives a higher betweenness centrality score to the nodes that have lower edge weight (even if they are embedded similarly in the graph). Is this normal? 

My intuition is that it should be the other way round: the higher is the combination of edge weights for a node, the higher is the chance that the shortest path will go through that node. Don't you think so?

**Comment by deemeetree** [comment]
I thought I would provide the dataset I use 
https://www.dropbox.com/s/zsmq57ofv0d8w7e/cytoscape-infranodus-elements.json?dl=0

If you calculate betweenness centrality on this dataset with no weights you'll see that the node statement ("id": "5f11d0e3-b214-11e3-80d3-6150cb20a1b9") will have a higher BC score (which is should) but as soon as you add weights to the settings of BC calculation above you have the node reliabl ("id": "1b9cf3c3-5e2d-4aaa-b310-1ffa901921d9") have a higher BC score even though, as you can see from the data, it's connected to the same nodes as the statement one (with one less connection) and its weights are lower (total 12 vs 20 with statement).

**Comment by MridulS** [comment]
> My intuition is that it should be the other way round: the higher is the combination of edge weights for a node, the higher is the chance that the shortest path will go through that node. Don't you think so?

This will be the other way round. Higher the combination of edge weights for a node, lower the change the shortest path will go through that node. 
When we calculate the shortest path between 2 nodes we try to find the path which has the lowest possible cost, for example, let's create a cycle graph.
``` python
In [6]: G = nx.cycle_graph(4)
In [7]: G.edges()
Out[7]: EdgeView([(0, 1), (0, 3), (1, 2), (2, 3)])
In [8]: nx.betweenness_centrality(G)
Out[8]:
{0: 0.16666666666666666,
 1: 0.16666666666666666,
 2: 0.16666666666666666,
 3: 0.16666666666666666}
```
We get expected results in the case of an unweighted network.

Let's add a weight between node 0 and node 1.
``` python
In [11]: G[0][1]['weight'] = 2
In [14]: nx.betweenness_centrality(G, weight='weight')
Out[14]: {0: 0.0, 1: 0.0, 2: 0.3333333333333333, 3: 0.3333333333333333}
```
The all_pairs_shortest_path function (which is used underneath while calculating betweenness centrality) will try to avoid the path between node `0-1` as its expensive to go through that, hence higher the combination of edge weights for a node, lower the change the shortest path will go through that node.

One way to counter this and for what you are looking for would be take the inverse of weight.
``` python
In [11]: G[0][1]['weight'] = 1/2
In [14]: nx.betweenness_centrality(G, weight='weight')
Out[14]: {0: 0.3333333333333333, 1: 0.3333333333333333, 2: 0.0, 3: 0.0}
```
NOTE: You need to be careful with the inverses as edges without weights will have a default weight of 1, which can skew the exact numerical values.

**Comment by deemeetree** [comment]
Thank you for this detailed answer, but do you assume that a path with a higher weight is more expensive? The stronger is the weight of the path, the higher is its capacity, the easier it is to go through this weight. 

This is the case on multiple scales: from neural networks to social networks. The more weight a path has, the more capacity it has. Why would an edge with a higher capacity be more expensive? If you need to take a route to your work, for example, you will choose the path with a higher capacity as it is less expensive and less likely to get congested. 

Also consider that in some applications people use weights to convert parallel edges, so, for example, if you have two parallel edges between the nodes [0,1] you would sum up their weight and convert it into one edge with the sum of the weight. This makes it possible to process this network using the tools that don't support parallel edges.

I understand that sometimes the weight measure may designate the length of the road, ok, but then we need to integrate the capacity to distinguish between the two types of weights. Otherwise this will lead to errors in calculations and in case of biological networks, for example, where a higher weight is associated with higher capacity, this may even lead to disastrous outcomes.

**Comment by MridulS** [comment]
Oh yes definitely, this makes sense. For some use cases having a high capacity or channel throughput is good for an edge. But the standard definition of dijkstra (which is again used underneath and implemented in networkx) interprets weight in the sense of a road network (finding the shortest path between cities, etc.) https://github.com/networkx/networkx/blob/master/networkx/algorithms/shortest_paths/weighted.py#L828
We should probably add a note in the documentation about this so that users keep this in mind while using these centrality measures, and one way to counter this (which I personally use) is to use the inverse function for weights.
Do you think there is a better way of keeping both these interpretations?

**Comment by deemeetree** [comment]
Yes, I think definitely it is very important to add a note into documentation. Should I do it?

Ultimately it would be great to add a setting to inverse the weights in all calculations where the results may be affected. Something like `weight_inverse=True' (you could keep it `False` by default).

Another related question: does this also affect the community detection algorithms in the same way?

**Comment by MridulS** [comment]
> Yes, I think definitely it is very important to add a note into documentation. Should I do it?

Yeah!

> Ultimately it would be great to add a setting to inverse the weights in all calculations where the results may be affected (and the function you said you use). Something like weight_inverse=True (you could keep it False by default).

This is my way of doing it, this is not really a standard way. We should probably wait for more people to weigh in on this.

> Another related question: does this also affect the community detection algorithms in the same way?

This pretty much depends on the community detection algorithm in question. The python-louvain implementation has a weighted case, but I need to read the code to see how it takes care of it.

**Comment by deemeetree** [comment]
Interestingly, it seems like modularity detection algorithms in `networkx` treat weights differently ascribing more weight to the communities, where the edge weights have a higher value.

**Comment by dschult** [comment]
NetworkX follows the standards written in the literature. In general edge weights may designate connection strength (bigger is more connected) or connection resistance (bigger is less connected). Different algorithms and papers in the literature treat the weights differently. We have tried to maintain consistency with the literature for each algorithm so people reading that literature can easily implement code to run the algorithm.

It's definitely something you have to keep in mind when crossing the literature from one area to another. Similarly, you have to keep it in mind when crossing our code from one algorithm to another.

**Comment by deemeetree** [comment]
@dschult I think it is good to keep this in mind, but think about how a graph object is constructed — all the same data gets fed to all kinds of algorithms. 

I think it would really make sense to at least add a notice in the documentation and, even better, add some setting into the code to make this more explicit. 

Otherwise you'll have people coming up with all kinds of wrong results especially on large networks where it'll be much harder to detect this problem.

I understand your point that everyone is responsible for their own use of the tools and that we can check the literature, but it seems very counterintuitive to me that when you calculate betweenness centrality weight means one thing, while for community detection it's something completely different.

**Comment by maxkfranz** [comment]
To quote from another repo:

> It seems like it's just an issue of the ambiguity of the word "weight". The word "weight" just means a number. It doesn't necessarily mean that a higher weight is better or stronger; that depends on the context.

Ultimately, I think this comes down to a clarity of documentation issue.  Because the word "weight" is inherently ambiguous, each algorithm that uses the word should provide an explicit definition in its documentation.  Regardless of whether you've read the literature or not, it can be a usability issue in a lib if the parameters aren't clear.  It's easy to forget, and it's easy to make a mistake generally because "weight" is so ambiguous.  I'll be updating the documentation for Cytoscape.js to clarify things.

I think making the documentation clearer for tools like Cytoscape.js and NetworkX is the only reasonable approach to this issue.  It's not practical to try to make every weight for every algorithm have the same semantics, especially since consistency with the literature is very important --- in my opinion, anyway.

**Comment by dschult** [comment]
Yes -- Let's get some PRs that try to make the documentation clearer about the use of edge weights!

**Comment by hagberg** [comment]
Please open new specific issues as documentation updates on use of weights.
