### ISSUE TITLE
spring_layout extreme points

### ISSUE THREAD

**Issue by szufix** [networkx/networkx#3376]
I'm using spring_layout from networkx (python 2.7) to embed multidimensional array into 2D. My question is why almost always I'm left with two extreme points?
![iquique](https://user-images.githubusercontent.com/21236547/55398871-e1285080-5549-11e9-9a52-13b1652f8907.png)

**Comment by dschult** [comment]
There isn't anything in the spring_layout algorithm that would ensure two nodes are separated from the others. However, the positions from spring_layout are scaled to be at most length 1 from the center in the widest dimension that results from the spring algorithm. That is the maximum distance is found from the center considering all dimensions, and all distances are scaled to make that 1.0.

So, I'm not surprised that the farthest node from the origin has one coordinate being 1.0.
I am a little surprised that two nodes seem to be pulled farther than expected from their groups.
If spring_layout is doing that I suspect a bug. But more likely it is some artifact of the data that makes two nodes separate from the others. 

Can you ensure that these two nodes are not different from the others in their group? 
Can you find a simple case that shows the same behavior to explore more?
When I run spring_layout on a path of 4 nodes it gives:
In [22]: G=nx.path_graph(4)
In [23]: nx.spring_layout(G)
Out[23]: 
{0: array([ 0.43834003, -1.        ]),
 1: array([ 0.1555344, -0.3549743]),
 2: array([-0.15576722,  0.35528535]),
 3: array([-0.43810721,  0.99968895])} 

These values are scaled so max coordinate absolute value is 1 (center is origin by default).
But no point is pulled toward (0,0) which it seems to be in your example.

**Comment by szufix** [comment]
Hi,

even for such simple example:
p1, p2, distance

0 1 0.2
0 2 0.1
0 3 0.1
1 2 0.1
1 3 0.1
2 3 0.1


I'm getting extreme points.

**Comment by szufix** [comment]
I was using python 2.7, after changing the version for 3.6 everything works
correctly, and I have the same results as you, and there are no extreme
points anymore :)
Thanks a lot for your time -- I really appreciate it.
