### ISSUE TITLE
smallworld.random_reference run very slowly 

### ISSUE THREAD

**Issue by foxet** [networkx/networkx#3380]
is there any bug with smallworld.random_reference?
very slow, even use niter=1
 smallworld.random_reference(giant, niter=1,seed=0)
it still took 10min,
[version networkx 2.2]

**Comment by dschult** [comment]
Even with niter=1 you still need to find edges that can swap. How long that takes depends a lot on what ```giant``` looks like. :}

**Comment by foxet** [comment]
the size is 8090, is it too big?

**Comment by dschult** [comment]
Not enough info...
