### ISSUE TITLE
Add function for group betweenness centrality

### ISSUE THREAD

**Issue by nandahkrishna** [networkx/networkx#3388]
Recently I worked on a program to calculate the betweenness centrality of a group of nodes in a graph, rather than the individual betweenness of each node. I was wondering if I could add a function to do the same, as I believe it's a useful centrality measure. Would this be fine?
<img width="333" alt="GBC" src="https://user-images.githubusercontent.com/33784207/55827819-b4b39c00-5b28-11e9-96ad-ad5326373cf9.png">

**Comment by dschult** [comment]
One image of a formula without definitions or context is not enough information to say if this is useful.
Do you have a reference/article that describes this centrality measure?

**Comment by nandahkrishna** [comment]
Sorry about that, should have linked you to my references. Group centrality measures were discussed by Everett and Borgatti in 1999, as part of their extensive studies on social network analysis. Here's the link to their paper: http://www.casos.cs.cmu.edu/events/summer_institute/2006/reading_list/borgatti/Borgatti_Centrality_of_Groups.pdf

Ulrik Brandes gives us a brief mention of group betweenness in this paper, on page 12: http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.72.9610&rep=rep1&type=pdf

The importance of group betweenness centrality is also highlighted in the introduction of these papers: 
https://pdfs.semanticscholar.org/f3d6/dfef4f99896c31ea8dbb521b4a785fd63ca9.pdf
http://www.cs.ucsb.edu/~arlei/pubs/sdm18.pdf

And here's a paper highlighting an application of this measure: https://www.elektrokomponenten.ch/media/files/09e4150bd20e58c913000000.pdf

I do hope these help, do tell me if you require anything else. If you find this measure worthy of inclusion, would it be fine if I try to implement it, being a first time contributor? Thank you for your time.

**Comment by dschult** [comment]
Yes -- these links would be good to include in the docs for the function(s) too.

It might be best to create a new module in networkx/algorithms/centrality/ named something like group_betweenness.py 
If you have questions about how to organize the code or how to use github, ask.  It's often helpful to create a "close to finished" PR (rather than wait for it to be polished) so we can look at the code and ask questions -- and you can ask questions.  Adding new commits and pushing to your github automatically updates the PR in networkx after the PR is created.

**Comment by nandahkrishna** [comment]
Alright, thanks. Shall I add a new module named group.py? There are other centrality measures discussed by Everett such as closeness and degree centrality, so I thought a module named 'group' could contain all these functions. I'll create a 'close to finished' PR like you said once I'm almost done with it. Thank you.

**Comment by dschult** [comment]
group.py sounds like a good module name.  Thanks!

**Comment by nandahkrishna** [comment]
I've created PR #3421 with the new module, which currently contains a function for group betweenness calculation. I'll add the other measures too I guess, once I've properly figured them out and got their references ready. Do tell me if anything needs to be changed so far.
