### ISSUE TITLE
Floyd Warshall algorithm to return all shortest paths between node pairs

### ISSUE THREAD

**Issue by fsquillace** [networkx/networkx#3391]
I was interested to propose an additional function for the Floyd-Warshall algorithm to return for each node pair in the graph, the predecessor structure which allows to reconstruct all the shortest paths for the given node pair.

This requires a slight modification of `floyd_warshall_predecessor_and_distance` function.

I already have a code change which provides an additional function `floyd_warshall_multi_predecessors_and_distance`. Both `floyd_warshall_multi_predecessors_and_distance` and `floyd_warshall_predecessor_and_distance` re-use the same common function: https://github.com/fsquillace/networkx/commit/b947ffa8cb1f8a032b430f067e916aee2e47e7a5

There is still additional work to do (i.e. unit tests, clean up and better generalization of the function which reconstructs the paths) but if that's a reasonable code change for you, I can continue working on it.

Thank you

**Comment by hagberg** [comment]
Re-open if a PR is submitted.
