### ISSUE TITLE
transitive_reduction loses node data

### ISSUE THREAD

**Issue by totorigolo** [networkx/networkx#3392]
Hi!

I'm using `networkx` for small dependency graphs, and I'm especially interested in the transitive_reduction algorithm. However, I noticed that all nodes lose their associated data after using this algorithm. Is that the expected behavior?

https://github.com/networkx/networkx/blob/fedc37f8cb342b2f630f7bbd080ebe076a3217e9/networkx/algorithms/dag.py#L546

I made a quickfix locally by just replacing by this:
```python3
TR.add_nodes_from(G.nodes.items())
```

Do you want a PR?

---
Somehow related, `transitive_reduction` creates a new OrderedGraph with:

https://github.com/networkx/networkx/blob/fedc37f8cb342b2f630f7bbd080ebe076a3217e9/networkx/algorithms/dag.py#L545

Shouldn't that be something like `TR = type(G)()` instead (modulo good Python practices)? I'm using `OrderedDiGraph`s because I want determinism with Python 3.4+.

**Comment by totorigolo** [comment]
Hello ! Any updates for this? Thanks :)

**Comment by dschult** [comment]
Thanks for the gentle nudge.
If you think of ```transitive_reduction``` as just returning the graph relationships, the current approach makes sense. You can convert them to any graph type and copy over the edge/node attributes. But the algorithm doesn't do this (to save space and copying time). 

The following copies all the attributes and sets the type of the graph class.

```python
H = nx.OrderedDiGraph(nx.transitive_reduction(G))
H.add_nodes_from(G.nodes.items())
H.add_edges_from((u, v, G[u][v]) for (u, v) in H.edges())
H.graph.update(G.graph)
```

**Comment by totorigolo** [comment]
Ok, I see the approach that networkx takes. Thank you for the explanation!

**Comment by dhimmel** [comment]
Ah this surprised: see https://github.com/related-sciences/nxontology/pull/18. I'm a bit puzzled why `nx.transitive_reduction` wouldn't want to preserve node/edge/graph data. Silently dropping it seems dangerous and inconsistent with other functions like `graph.reverse` and `nx.DiGraph(graph)`, which preserve data.

> the algorithm doesn't do this (to save space and copying time).

Can't the algorithm just copy everything over at the end? Or take an option to preserve data?

I ended up using the 3 lines suggested by @dschult to preserve data, but I don't think we want users having to do that... seems error-prone and low level.
