### ISSUE TITLE
draw_network_edges allows curved edges or dashed edges, but not both.

### ISSUE THREAD

**Issue by djinnome** [networkx/networkx#3398]
Hi folks,

I would very much like to create curved, dashed  edges for either directed or undirected graphs.

However, it seems I can only have curved, **but not dashed** edges for directed graphs, even though I specify `style="dashed"`
```python
G = nx.DiGraph([('X','Y')])
pos = nx.spring_layout( G )
nx.draw_networkx_nodes(G, pos,
                       nodelist=list(G.nodes))
nx.draw_networkx_edges(G, pos,
                       edgelist=list(G.edges),
                       style='dashed',
                       connectionstyle="arc3,rad=0.3",
                      )
plt.savefig('solid-curved-directed-edge.png')
```

![solid-curved-directed-edge](https://user-images.githubusercontent.com/144210/56476144-5354cc80-6448-11e9-94ef-28c311ad9dac.png)

Furthermore, it seems I can only get dashed, **but not curved**, edges for undirected graphs. 
even though I specify `connectionstyle="arc3,rad=0.3"`

```python
G = nx.Graph([('X','Y')])
pos = nx.spring_layout( G )
nx.draw_networkx_nodes(G, pos,
                       nodelist=list(G.nodes))
nx.draw_networkx_edges(G, pos,
                       edgelist=list(G.edges),
                       style='dashed',
                       connectionstyle="arc3,rad=0.3",
                      )
plt.savefig('dashed-straight-undirected-edge.png')
```

![dashed-straight-undirected-edge](https://user-images.githubusercontent.com/144210/56476149-610a5200-6448-11e9-9dfd-061270f0c235.png)

Please advise.

Thanks so much,

Jeremy

**Comment by dschult** [comment]
Take a look at the code for [draw_networkx_edges()](https://github.com/networkx/networkx/blob/33980ffeef6de64fa543692bcc713e2b1fcdbcce/networkx/drawing/nx_pylab.py#L429) to understand more.

The directed graph edges are drawn with a matplotlib ArrowCollection. The connectionstyle keyword argument is only used in this case.
The undirected graph edges are drawn with a matplotlib LineCollection. The style collection keyword argument is only used in this case.

See if you can look at the matplotlib docs for these two collections to figure out how to make e.g. a dashed arrow.  NetworkX doesn't do this, so if you figure it out please let us know how (and maybe create a pull request)
