### ISSUE TITLE
LFR benchmark in wrong location

### ISSUE THREAD

**Issue by jg-you** [networkx/networkx#3404]
Following the convention of the module, I'd expect to find LFR_benchmark (and the whole content of that file) under networkx.generators.community instead of networkx.algorithms.community.community_generators

**Comment by dschult** [comment]
Can you elaborate? Why do you expect it there? What rule are your expectations based on? How does this choice break that rule. 
It's probably also good to describe more carefully whether it is only one function that should be moved or a module, or what...

**Comment by jg-you** [comment]
Sorry for the vagueness! 

As far as I know, all the functions that generate graphs are under [networkx.generators](https://github.com/networkx/networkx/tree/master/networkx/generators), and the ones that include explicit communities are in the [community.py](networkx.generators.community) submodule of generators.

So the implicit rule is: All generators in the generators submodule.
I'd expect to find the `LFR_benchmark_graph` there too.

For some reasons, it is instead with the community detection algorithms, in its own file called [networkx.algorithms.community.community_generators](https://github.com/networkx/networkx/blob/master/networkx/algorithms/community/community_generators.py) (presumably because benchmark community detection algorithms is its main use).

The submodule only contains`LFR_benchmark_graph` and auxiliary private functions, so it could be moved wholesale to  [community.py](networkx.generators.community), or placed in its own submodule.

Moving the submodule would be easy since the function is only called from the file itself, the associated test file ([networkx.algorithms.community.tests.test_generators.py](https://github.com/networkx/networkx/blob/master/networkx/algorithms/community/tests/test_generators.py)), and from the global test random function file [networkx.tests.test_all_random_functions.py](https://github.com/networkx/networkx/blob/master/networkx/tests/test_all_random_functions.py).

**Comment by dschult** [comment]
Thanks -- this helps. I'll take a look at the history and try to figure out why it might historically be like this. Looks like to move it we would move community_generators and test_generators to the generators directory.

**Comment by jg-you** [comment]
Sounds about right. You'd end up with weird naming though (generators.community_generators).
Perhaps even better to rename to LFR_benchmark, or rip the code an place it in the already existing   generators.community.

I can put in a PR for the preferred solution---if this is indeed a "problem" that needs resolving.

**Comment by dschult** [comment]
Yes -- there is nothing in the history that indicates this should be where it is.
It makes more sense to pull the code and put it in generators.community.py
If you could put together such a PR, that would be great. Thanks!

**Comment by jg-you** [comment]
While I'm at it, there are some bipartite generators also found in algorithms (algorithms.bipartite.generators). I think that's all. Should they also be moved? Or none of the two?

**Comment by dschult** [comment]
The bipartite generators are currently named in such a way that we can't easily combine them.
Basically, they use many of the names we already use for non-bipartite generators. But in that subpackage the functions refer to bipartite generators.  Let's leave them there.
I think the idea for putting LFR benchmark in community was a similar philosophy that code could be compartmentalized somewhat using imports and namespaces. But it hasn't been implemented widely in the NetworkX package. I think you found the places I know of for generators.  There are other places where we have isolated the namespace somewhat like the isomorphism checkers.  

Let's move the community_generators and keep the bipartite generators where they are.

**Comment by jg-you** [comment]
Fair enough, this would be a lot of compatibility breaking changes.
