### ISSUE TITLE
subgraph fails when subclassing Graph with additional argument

### ISSUE THREAD

**Issue by donpatrice** [networkx/networkx#3406]
I run into problems when subclassing like this:
```
class MyGraph(nx.Graph):
    def __init__(self, foo):
        super().__init__()
        self.foo = foo

mg = MyGraph(5)
mg.__class__()

TypeError: __init__() missing 1 required positional argument: 'foo'
```

And therefore mg.subgraph() will fail.

```
edges = [(1,2), (2,3), (3,4)]
mg.add_edges_from(edges)
mg.subgraph([1,2])

TypeError: __init__() missing 1 required positional argument: 'foo'
````

Is there a way to bypass this.

I think this is related to https://github.com/networkx/networkx/issues/2889 and https://github.com/networkx/networkx/pull/3073

**Comment by dschult** [comment]
It looks like your troubles are not related to previous issues.
When you subclass an object you need to think about the arguments for instantiating the new class. If you want it to handle inputs in a similar way to the super-class, you need to build those into the arguments for your sub-class.

As written, you require an argument ```foo```, and do not allow any other arguments. So, any code that treats your new class as a NetworkX class (either with or without arguments) will not work.  Think about what you want the value of ```foo``` to be when your new object is instantiated using syntax for NetworkX graphs. Make that the default value for ```foo```.  That will get rid of the TypeError complaining about required positional arguments.

Next, you need to build into your sub-class the ability to handle input meant for the sub-class. Take a look at ```nx.Graph.__init__()``` and make the subclass ```__init__()``` mimic that calling syntax (while adding ```foo``` of course).  Once ```MyGraph(edges)``` and ```MyGraph()``` work you should be ready to go.

**Comment by donpatrice** [comment]
If I got you right, you suggest something like this:

```
class MyGraph(nx.Graph):
    def __init__(self, foo=None, **kwargs):
        super().__init__(**kwargs)
        self.foo = foo
        nodes = some_function(foo)
        self.add_nodes_from(nodes)
```
Is that what you meant?
At least this is working!
Thank you!

**Comment by dschult** [comment]
That looks better -- but it specifies an ordering of arguments that makes ```foo``` first and then the super-class arguments. If something calls ```MyGraph(edges)``` then edges will be the value of ```foo``` instead of ```data```.  It would probably be safer to actually specify what input arguments you want in which order, rather than using ```kwargs```. And put ```foo``` last on the list so calls that treat MyGraph like the super-class will work properly.

**Comment by donpatrice** [comment]
Thanks a lot!

For completeness, now I have:
```
class MyGraph(nx.Graph):
    def __init__(self, incoming_data=None, foo=None, **kwargs):
        super().__init__(incoming_data, **kwargs)
        self.foo = foo
        nodes = some_function(foo)
        self.add_nodes_from(nodes)
```
If this is what you meant this issue can be closed, and hopefully helps others.
