### ISSUE TITLE
Add option to `in_edges` and `out_edges` to include edge key in the results

### ISSUE THREAD

**Issue by Makman2** [networkx/networkx#3414]
Similar to `graph.edges(key=True)` :smile:

I currently use the keys themselves to store my relevant data (I want to make use of the automatic uniqueness by employing keys instead of the data-dict).

**Comment by Makman2** [comment]
Obviously, this feature only applies to `DiGraph` and `MultiDiGraph` :+1:

**Comment by dschult** [comment]
The ```keys``` argument to edges only works for MultiGraphs. And it already is a valid argument for edges/in_edges/out_edges with MultiDiGraphs.

**Comment by Makman2** [comment]
Indeed. I'm sorry for bothering. I guess I accidentally confused that with `DiGraph` :sweat_smile:
