### ISSUE TITLE
UnionFind - Use union by rank

### ISSUE THREAD

**Issue by sumerc** [networkx/networkx#3416]
Hi,

How about implementing union by rank for the UnionFind structure instead of union by weight? It has a better asymptotic running time(a tight bound). (With weighted union, there is always a possibility to merge a taller tree to a shorter tree.)

Is there any design decision behind this?

Thanks!

**Comment by sumerc** [comment]
I have implemented an example implementation here: 
https://gist.github.com/sumerc/cfebba6336ec44b21aaf5628f5f50a1b

I can convert to a pull req. if it is OK.

**Comment by dschult** [comment]
Hi -- thanks for thinking about this. My understanding is that union-find with {by-rank or by-weight} and {path compression, path_splitting, or path_halving} all have the same level of complexity. So, if what you and Wikipedia say is true about a tight bound, then it seems likely the bound is tight for all these algorithms. 
I'm not able to spend the time to dive into this too deeply. My inclination is to stick with what we've got unless there is an advantage to -by-rank.  Can you explain or point me to something that does explain which is better?  My understanding is that they are the same.

**Comment by sumerc** [comment]
Hi,

You are right. I mis-interpreted some document union-by-rank having better amortized complexity than  union-by-weight. They seem to have same amortized complexity(O(inverse ackermann)) if any of {path compression, path_splitting, or path_halving} is used just like you indicated. 

Thanks,
