### ISSUE TITLE
Bug in algebraic_connectivity() implementation

### ISSUE THREAD

**Issue by ws4u** [networkx/networkx#3418]
Hi all and @ysitu ,

I have the following block of code calculating the algebraic connectivity of random regular graphs. 
`import networkx as nx

for i in range(10):
    g = nx.random_regular_graph(5,100)
    ac=nx.algebraic_connectivity(g)
    print(ac)`

The code is successful on some of the graphs, but it will mostly halt one one of the graphs. According to my experiments, this error only happens on random regular graphs, not other types of graphs. So I think there is a bug in algebraic_connectivity() implementation in handling this particular situation. Please advise. Thanks.

**Comment by dschult** [comment]
The "working forever" symptom is almost certainly due to numerical error issues. You can try increasing the tolerance. But I suspect it will work it you simply switch methods to e.g. 

    ac = nx.algebraic_connectivity(g, method='tracemin_lu')

**Comment by ws4u** [comment]
Thanks, @dschult . Yes, changing the method to 'tracemin_lu' fixes this problem.
