### ISSUE TITLE
[Feature proposal] Iterator which traverses graph by neighbors "rings"

### ISSUE THREAD

**Issue by Daiver** [networkx/networkx#3419]
Hello! First of all I'm sorry for my possible English mistakes (I'm not a native speaker)

Recently I faced the need of iterator which will traverse graph by "neighbors rings" (I'm not sure how to name it right) https://stackoverflow.com/questions/55939790/networkx-traverse-graph-by-waves
I've created a simple iterator which performs such king of traversing, for example:
```python
>>> g = nx.Graph()
>>> g.add_edges_from([(0, 1), (0, 2), (3, 1), (4, 2)])
>>> list(traverse_rings(g, source=0, depth_limit=None))
[[1, 2], [3, 4]]]
```
I can create a PR but i have 2 questions:
1) Does networkx need such an algorithm?
2) Which name is appropriate for such kind of algorithm?

This is an implementation:
```python
def traverse_rings(graph: nx.Graph, source, depth_limit=None):
    """docs are omitted for simplicity """
    # Complex graphs are not supported now
    assert not graph.is_directed()
    assert not graph.is_multigraph()

    depth_limit = depth_limit if depth_limit is not None else graph.number_of_nodes()

    visited_nodes = {source}
    current_ring = [source]
    next_ring = []

    current_depth = 0
    while current_depth < depth_limit and len(current_ring) > 0:
        for current_node in current_ring:
            neighbourhood = graph.neighbors(current_node)
            for neighbour in neighbourhood:
                if neighbour not in visited_nodes:
                    next_ring.append(neighbour)
                    visited_nodes.add(neighbour)
        if len(next_ring) > 0:
            yield next_ring
        current_depth += 1
        current_ring = next_ring
        next_ring = []
```

Also i have ~10 unittests which can be easily transformed to `nose`

**Comment by dschult** [comment]
The function ```nx.single_source_shortest_path_length(G, source=0, cutoff=7)``` should provide the information you need. But it returns a dict keyed by node to distance from source. So you have to process it to get it into groups by distance.  Something like this should work:

    from itertools import groupby
    spl = nx.single_source_shortest_path_length(G, source=0, cutoff=7)
    rings = [set(nodes) for dist, nodes in groupby(spl, lambda x: spl[x])]

**Comment by Daiver** [comment]
@dschult Thank you for answer! But as far as i see iterator allow me to stop traversing whenever i want. `nx.single_source_shortest_path_length` can be stopped only by cutoff. It can be crucial for big graphs.

**Comment by dschult** [comment]
Yes -- I see that our choice to make single_source_spl return a dict doesn't allow it to be an iterator. That was a hard choice to make -- long ago we changed many shortest_path functions to iterators.  Perhaps it is worth taking a look again.

But -- there is a private function which returns an iterator rather than the dict. It even yields the nodes in ring level order.  So something like this:

    spl_iter = nx.algorithms.shortest_paths.unweighted._single_shortest_path_length
    spli = spl_iter(G, {0}, cutoff=7)   # note: source should be a singleton in a set/dict/list
    while dont_stop_me_now():   # some criteria
        (node, level) = next(spli)
        # do stuff to collect rings based on level...
