### ISSUE TITLE
Consider adding a 'hierarchical' positioning algorithm for plotting trees.

### ISSUE THREAD

**Issue by joelmiller** [networkx/networkx#3420]
This answer I wrote on stackoverflow for positioning nodes in trees seems to be fairly popular - by far the most popular of the "tools" I've written there.  Assuming there are no license issues, could this be added as a default algorithm for networkx?

https://stackoverflow.com/a/29597209/2966723

**Comment by dschult** [comment]
That seems like a good addition to the layout.py tools.
My understanding is that you'd have to release the version in our package under the BSD license if its in NetworkX, but I'm not an expert.
Thanks!

**Comment by ericmjl** [comment]
@joelmiller that'd be an awesome addition! And if you add it to NetworkX, I'll create a consistent viz API on nxviz by wrapping your implementation. (And yes, I'm still developing nxviz to create a declarative, seaborn-like API for graphs!)

**Comment by joelmiller** [comment]
Lost track of this.  Just reminded of it today.

I'd like to see this added to networkx.  Given that I'm the author, there must be a way for me to get it into networkx under whatever license networkx uses.  Any idea what magical incantation I need to give?

**Comment by dschult** [comment]
If you make a pull request to a file that has the copyright used in much of networkx (which says BSD license) that is sufficient magic to release it under that license. Be sure to put yourself as an author in the way described in the networkx github wiki. 
If you want to create a separate module with your own license attribute (would still need to be BSD license or compatible) you can adapt the module heading to be your copyright.

Thanks!

**Comment by joelmiller** [comment]
I've got very little experience with pull requests...

I use SourceTree (on a Mac).  I've attempted to follow the instructions they provide for creating a pull request.  Ended up with an error message:

> git -c diff.mnemonicprefix=false -c core.quotepath=false -c credential.helper=sourcetree push -v --tags --set-upstream origin refs/heads/hierarchy_layout_edits:refs/heads/hierarchy_layout_edits 
> Pushing to https://github.com/networkx/networkx/
> remote: Permission to networkx/networkx.git denied to joelmiller.
> fatal: unable to access 'https://github.com/networkx/networkx/': The requested URL returned error: 403
> Completed with errors, see above

Not sure whether you need to give me permission or I need to do something different.

**Comment by dschult** [comment]
The way I know for making a pull request is to fork networkx/networkx into your own account. Pull/push to that fork (or a branch within that repo) and then on the github page for that repo, a button allows you to create a pull request to the original repo.  There may be other fancier ways to do it involving the command line only, but I don't know them.

**Comment by joelmiller** [comment]
Been too busy to properly do this, but I've put a modified version of `hierarchy_pos` into my own package for infectious disease spread.  

https://epidemicsonnetworks.readthedocs.io/en/latest/functions/EoN.hierarchy_pos.html#EoN.hierarchy_pos

I think it's in pretty good shape.  Hopefully I'll get around to making a pull request soon.
