### ISSUE TITLE
read_gml does not show labels 

### ISSUE THREAD

**Issue by ChangyuYan** [networkx/networkx#3426]
I tried to visualize the NetScience [Coauthorship data](http://users.cecs.anu.edu.au/~xlx/teaching/comp4650-sma/files/netsci_subgraph.gml), which looks like this:
Creator "Mark Newman on Sat Jul 22 06:24:59 2006"
```
graph [
  node [
    id 306
    label "HOPCROFT, J"
  ]
  node [
    id 1123
    label "LEICHT, E"
  ]
  node [
    id 1081
    label "MONTOYA, J"
  ]
  node [
    id 759
    label "GHOSHAL, G"
  ]
  node [
    id 305
    label "CALLAWAY, D"
  ]
...
```
I typed in the following code in my jupyter-notebook: 
```
gs = nx.read_gml('netsci_subgraph.gml', label = "label")
nx.draw_spring(gs)
plt.show()
```
Which gives me a graph of no labels:
![Screen Shot 2019-05-07 at 9 00 16 AM](https://user-images.githubusercontent.com/27938057/57314477-8c2aad80-70a6-11e9-83cd-d9d236d03d9a.png)

I tried to use "relabel" in my code, but it gives me an error:
![Screen Shot 2019-05-07 at 9 00 49 AM](https://user-images.githubusercontent.com/27938057/57314518-a49ac800-70a6-11e9-857f-1c3c272fe180.png)

Could you help me fix this please? 

P.S., I tried it on both Python2 and Python 3. Same error gets produced.

**Comment by dschult** [comment]
nx.draw_spring does not put labels on nodes by default (neither does nx.draw).
Use ```nx.draw_spring(G, with_labels=True)```
