### ISSUE TITLE
Cannot layout graphs with nodes containing colons

### ISSUE THREAD

**Issue by FFroehlich** [networkx/networkx#3430]
Example:

```
import networkx as nx

g = nx.DiGraph()
g.add_edge('foo:foo', 'foo:bar')
print(nx.nx_pydot.graphviz_layout(g))
```

The problem is a result of two issues: https://github.com/networkx/networkx/issues/1568 and https://github.com/networkx/networkx/issues/2050 

Essentially, pydot interprets everything after colons as port and shortens names accordingly.
I think most of the dot string issues seem to have been resolved in python 3, so I think it might be worthwhile to revisit how this is issue is handled.

In complex graphs, this is an issue that might easily go unnoticed and debugging is all but straightforward.

**Comment by FFroehlich** [comment]
On a related note the workaround that is propsed in the pydot docstring does not work for this problem (there is an error in the docstring, pydot_layout should be applied to H, not G):
```
import networkx as nx

G = nx.DiGraph()
G.add_edge('foo:foo', 'foo:bar')

H = nx.convert_node_labels_to_integers(G, label_attribute='node_label')
H_layout = nx.nx_pydot.pydot_layout(H, prog='dot')
G_layout = {H.nodes[n]['node_label']: p for n, p in H_layout.items()}
```
errors with `AssertionError: 1` due to
```
stdout, stderr:
 b''
b"Error: /var/folders/jk/dwv8fvns5q58ht4z1x184jb80000gp/T/tmpfzqy_ks3: syntax error in line 2 near ':'\n"
```

**Comment by hagberg** [comment]
I took a look at #2050 and my previous grumpy assessment that this is a pydot bug.   I still agree but I am open to figuring out if there is a way to make it work with networkx instead of fixing pydot.  Suggestions?

I don't see on quick inspection why the workaround is throwing an exception but that one I think we can fix.

**Comment by FFroehlich** [comment]
Pydot interprets `:` as specification of a port (see https://renenyffenegger.ch/notes/tools/Graphviz/examples/index). This syntax is documented in the graphviz manual (https://www.graphviz.org/pdf/dotguide.pdf, page 18 section 3.1 Node ports) and explicitely mentioned in the pydot code https://github.com/pydot/pydot/blob/48ba231b36012c5e13611807c9aac7d8ae8c15c4/pydot.py#L607.

One solution to this issue would be to prefix `"` to node labels when writing to pydot. Another one would be to just throw an exception/warning when a node label that contains a `:` is converted to pydot.

I suppose that the exception I encountered is due to a similar issue where the colon is now causing trouble in a node attribute instead of a node label.

**Comment by hagberg** [comment]
Yes, I get the graphviz node port syntax with a colon.  What I think is wrong is for pydot to strip the colon and later from the name of the node e.g. https://github.com/networkx/networkx/issues/2050#issuecomment-203707913  

I've weighed in as negative on automatically adding quotes but could be convinced.  The idea of throwing an exception and suggesting adding quotes by hand might be better.

I think what you are saying is that graphviz node attributes can't have colons so the workaround as stated in the docstring fails.   I could believe that- hard to tell from the error messages.

**Comment by FFroehlich** [comment]
> Yes, I get the graphviz node port syntax with a colon. What I think is wrong is for pydot to strip the colon and later from the name of the node e.g. [#2050 (comment)](https://github.com/networkx/networkx/issues/2050#issuecomment-203707913)

It kinda makes sense as Ports should all have the same location as the parent node. So even if the port was stripped from the name, layouting all ports to the same position as the parent node is not what you want in networkx, but it is what pydot does. 
For the export as dot file I agree with you that it is a questionable decision to make it non-optional to not preserve the input syntax.

**Comment by hagberg** [comment]
My understanding probably comes from my pygraphviz bias which interacts with the dot language through the graphviz libcgraph interface.  In that case you wouldn't label a node with a port "colon" syntax but would instead specify the headport and tailport when creating an edge with those nodes.   This is a consistent approach that round-trips write/read.  Any name with a colon is automatically double quoted as an allowed double quoted string type.  

This works reasonably with networkx/pygraphviz like this
```In [23]: G = nx.Graph()

In [24]: G.add_edge('foo','foo',headport='n',tailport='s')

In [25]: G.add_node('bar:bar') # automatically double quoted

In [26]: nx.nx_agraph.write_dot(G,'foo.dot')

In [27]: cat foo.dot
graph "" {
	foo:s -- foo:n;
	"bar:bar";
}

In [28]: H = nx.nx_agraph.read_dot('foo.dot')

In [29]: H.nodes(data=True)
Out[29]: NodeDataView({'foo': {}, 'bar:bar': {}})

In [30]: H.edges(data=True)
Out[30]: MultiEdgeDataView([('foo', 'foo', {'headport': 'n', 'tailport': 's'})])
```

Pydot works similarly but as we know treats names of nodes with colons as special so you get this kind of confusion
```
In [34]: G.add_edge('bar:n','bar:s')

In [35]: nx.nx_pydot.write_dot(G,'foo.dot')

In [36]: cat foo.dot
graph  {
foo;
bar;
bar;
bar;
foo -- foo  [headport=n, tailport=s];
bar:n -- bar:s;
}

In [37]: H = nx.nx_pydot.read_dot('foo.dot')

In [38]: H.nodes(data=True)
Out[38]: NodeDataView({'foo': {}, 'bar': {}, 'bar:n': {}, 'bar:s': {}})

In [39]: H.edges(data=True)
Out[39]: MultiEdgeDataView([('foo', 'foo', {'headport': 'n', 'tailport': 's'}), ('bar:n', 'bar:s', {})])

```

Maybe the simplest solution is to double quote any strings with colons before sending them to pydot?
```
In [41]: G = nx.Graph()

In [42]: G.add_node('"bar:bar"') 

In [43]: nx.nx_pydot.write_dot(G,'foo.dot')

In [44]: cat foo.dot
strict graph  {
"bar:bar";
}
```
That way the names would be preserved and you can still use 'ports' if you want by setting keywords as above.
