### ISSUE TITLE
Heads-Up: cuGraph!

### ISSUE THREAD

**Issue by ericmjl** [networkx/networkx#3434]
I'm very excited with this development from NVIDIA: cuGraph, which is one of their RAPIDSAI projects!

In particular, I have been nudging them to "just copy the NetworkX API", because it's so beginner-friendly and would really help with adoption if I could just `import cugraph as nx`, and be done with the rest of my code.

Tagging here @seunghwak and @dschult, in case you two haven't (e-)met each other just yet.

**Comment by seunghwak** [comment]
Thank you very much for posting this, and providing NetworkX compatibility is a main objective of cuGraph 0.8 release (we just released 0.7).

Visit https://github.com/rapidsai/cugraph for more information about cuGraph and https://rapids.ai for the RAPIDS project.

**Comment by dschult** [comment]
Thanks very much @ericma!
And happy to meet you @seunghwak 
cuGraph looks promising. Hopefully we can make it easy for people to use both of these packages.
