### ISSUE TITLE
Providing a topological order to DAG-related algorithms

### ISSUE THREAD

**Issue by alabarre** [networkx/networkx#3446]
A few functions in `dag.py` rely on `topological_sort`. Chances are people who know they are working on a DAG in an application may need to compute a topological order anyway, and it would make sense to allow them to feed that order to functions that need it instead of having each function recompute such an order for their own needs. 

Would you agree to transform `some_dag_function(G, ...)` as follows?

```python
    def some_dag_function(G, ... , order=None):
        if order is None:
            order = topological_sort(G)
        # rest of the function
```

**Comment by dschult** [comment]
Yes, this looks like a good addition.

Would this be worth making into a decorator like ```not_implemented_for```?
That may be more trouble than its worth. I'm fine with whichever way it's implemented.

Is the name ```order``` descriptive enough that it won't be confused with something else?
It seems like ```topolocial_sort_order=None``` is too long. ```top_sort``` seems short enough to be convenient, but still descriptive enough that it won't be confused with another concept. I'm OK with whatever you choose to make the keyword. I'm just asking for you to think about it.

**Comment by alabarre** [comment]
I think I'll go for the simpler option of appending a default parameter. Decorators are probably more elegant but I don't have a broad view of `networkx` and how this might affect or break existing code, so it's probably safer to start that way and let others improve on it if they wish. I'll try and get this done today, it shouldn't take long.

**Comment by alabarre** [comment]
I've created a pull request but I can't seem to figure out how to tag this issue accordingly.
