### ISSUE TITLE
Iterators not available anymore?

### ISSUE THREAD

**Issue by vlavorini** [networkx/networkx#3452]
Hi,

  just replicating the exmaple in the [documentation](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.DiGraph.nodes_iter.html):

    G = nx.Graph()
    G.add_path([0,1,2])
    [d for n,d in G.nodes_iter(data=True)]

gives:

    ---------------------------------------------------------------------------
    AttributeError                            Traceback (most recent call last)
    <ipython-input-47-91f3d939c1a6> in <module>
          1 G = nx.Graph()
          2 G.add_path([0,1,2])
    ----> 3 [d for n,d in G.nodes_iter(data=True)]

    AttributeError: 'Graph' object has no attribute 'nodes_iter'

Networkx version: `2.3`

**Comment by MridulS** [comment]
The documentation you have linked is for version 1.10 and iter methods were
removed from 2.0 onwards.
Google indexing isn’t that good for distinction between different versions.
