### ISSUE TITLE
Eulerization of Graphs - Enhancement

### ISSUE THREAD

**Issue by pthangeda** [networkx/networkx#3456]
As mentioned in #2869 Eulerization of a graph is essential for many applications. While #3076 implemented a function for Eulerizing graph, it is limited to undirected graphs and is also restricted to using the path length as the cost that is minimized during Eulerization. 

I've implemented Eulerization scheme that works for directed graphs and also lets the user pick the attribute he wants to use as the weight that he wants to minimize during Eulerization of the graph. I will have the PR ready in a few days - seeking comments from others before I go ahead and do a PR.

**Comment by dschult** [comment]
Are you intending to add directed or undirected (you say undirected for both existing and your implementation)? Also, what algorithm are you using -- has it been published somewhere or are you creating a new algorithm?

**Comment by pthangeda** [comment]
Thanks for the comments. I meant directed, I've corrected my original issue note. 

I intend to modify `eulerize` function in `networkx/algorithms/euler.py` to work for both directed and undirected graphs. Further, I also want to add the option of letting the user pick the weight he is trying to minimize while adding additional edges to Eulerize the graph.

The problem of Eulerizing a directed graph can be reduced to sub-problems that have well-established polynomial time algorithms. The approach I followed is roughly based on the notes in the 'Eulerian Cycle/Chinese Postman' section of [The Algorithm Design Manual](http://www.algorist.com/) and is as follows:

1) Find out unbalanced nodes (non-zero difference of in and out-degree) in the graph. Find the shortest paths (any acceptable weight attribute) between them, using Dijkstra's algorithm or Floyd-Warshall algorithm.

2) Decide the additional edges to be added to balance the nodes by using any of the bipartite minimum weight optimal matching algorithms.

Let me know if you need any further clarifications!

**Comment by dschult** [comment]
That sounds good. 

It also sounds like it might make sense to have it included as a separate function.
Have you thought about how to make the API?

Also, I would suppose this should go into the euler.py module. Is that what you expect? If you are planning to use existing bipartite minimum weight optimal matching algorithms then maybe it should go with that code instead... ?...

**Comment by pthangeda** [comment]
Sorry for the significant delay, got caught up in some deadlines. Here is what I was thinking about the API:

1) Changes to the existing API would be minimal. Currently, `eulerize(G)` in `networkx/algorithms/euler.py` is used to eulerize an undirected graph G and raises an exception if G is directed. I plan to update this function to `eulerize(G,w)` where w is the weight that I seek to minimize during eulerization (default weight would be the length of the path). 

2) I need an algorithm to find a solution for the minimum weight perfect matching problem (assignment problem). The matching algorithms in the bipartite module seem to solve the maximum cardinality matching problem and hence cannot be used in our case. The `networkx.algorithms.matching` module has a function `max_weight_matching` which can be used by setting the `maxcardinality` input as `False`. Just wanted to note that the algorithm could return a slightly suboptimal matching due to numeric precision errors when weights are not integer values. 

3) I think this implementation would be more relevant to people trying finding a Euler path and hence I think it is best to have it in the `euler.py` module rather than with the bipartite functions.

**Comment by dschult** [comment]
Qs: 
1. "w is the weight that I seek to minimize"...  What is w? a string? a function?
2. You should add a warning to the docstring that edge weights should not be numeric due to floating point errors. Rather they should be integer values.
3. I agree that the new function should go with the euler.py code.

Only API issue left is whether this should be a new function or make ```eulerize()``` use this algorithm.  I'm concerned that the current eulerize function does not optimize the choice of edge matching, but your new function would. Am I misunderstanding?  If that is the case, I'd prefer you create a new function... maybe ```eulerize_optimally```?
