### ISSUE TITLE
plot_knuth_miles.py does not link to knuth_miles.txt.gz

### ISSUE THREAD

**Issue by peterjc** [networkx/networkx#3469]
The website has this example:

https://networkx.github.io/documentation/stable/auto_examples/drawing/plot_knuth_miles.html

It references a dataset, without a download link needed to run the example.

The page source is here:

https://github.com/networkx/networkx/blob/master/examples/drawing/plot_knuth_miles.py

I found a copy of the sample data here - although it might also be on the website with a nicer URL?

https://github.com/networkx/networkx/blob/master/examples/drawing/knuth_miles.txt.gz

**Comment by dschult** [comment]
Yes... the file is at:
https://raw.githubusercontent.com/networkx/networkx/master/examples/drawing/knuth_miles.txt.gz

A link should be added to the docstring of the example.
Thanks!!

**Comment by planetb113** [comment]
hello! here I need some help:

file from this link
[https://networkx.org/documentation/stable//auto_examples/drawing/plot_knuth_miles.html#sphx-glr-auto-examples-drawing-plot-knuth-miles-py](url)

is not readable:
`fh = gzip.open("knuth_miles.txt.gz", "r")
for line in fh.readlines():
    break`

` OSError: Not a gzipped file (b'\n\n') `

can you let me know where could I find the right file?

**Comment by peterjc** [comment]
Make sure you've downloaded the raw gzip file from GitHub, not just the webpage about the file.
