### ISSUE TITLE
networkx.draw() hides axes on different subplot

### ISSUE THREAD

**Issue by przecze** [networkx/networkx#3475]
I try to have a graph visualization on one subplot and a line plot of some values on another subplot. However, after I draw the graph on the first subplot, axes on the other subplot disappear (although I did not allow any shared axes). And I cannot bring them back.
```
import networkx as nx
import matplotlib.pyplot as plt
fig = plt.figure()
ax1 = fig.add_subplot(211)
ax2 = fig.add_subplot(212)
G = nx.graph_atlas(1)
nx.draw(G, ax=ax1)
plt.show()
```
Results in `ax2` having the ticks for both axes hidden, whereas if I run the same code without `nx.draw(...)` line the ticks are visible on both subplots.

How is it possible that `nx.draw(G, ax=ax1)` affects `ax2`?

**Comment by dschult** [comment]
Looks like #3476 fixes this issue.
