### ISSUE TITLE
3D shapefile not supported

### ISSUE THREAD

**Issue by NicolasCadieux** [networkx/networkx#3478]
When reading a Shapefile using the  read_shp(path, simplify=True), 3D Shapefiles are not supported. Error message does not make sense to user.

**Comment by dschult** [comment]
What do you suggest? Is there an easy way to test that the shapefiles are 2D as we process?

**Comment by NicolasCadieux** [comment]
Hi,
This very first thing would be to have an error message that make sense for that error.  After that, it can be possible to change the format to a 2D shapefile or possibly read with geopandas and not gdal.

**Comment by dschult** [comment]
Before we can give an error message we have to know how to identify that the file is 3d or 2d. 
If using geopandas instead of gdal would work, then maybe a separate function for 3d would be better and the user can decide which function to use.

**Comment by NicolasCadieux** [comment]
https://gis.stackexchange.com/questions/166523/remove-3d-geometry-in-shapefile-using-ogr

https://gdal.org/python/osgeo.ogr.Geometry-class.html  Search for FlattenTo2D(self, *args)

**Comment by NicolasCadieux** [comment]
As for the geopandas, I can give you my code when I am back from vacation.

**Comment by dschult** [comment]
I guess the first thing is to raise an error message when there is 3D data in a shape file.
That's the first PR, perhaps.
Then it'd be nice to implement a way to handle 3D shape files. Not sure how much code that takes though.

**Comment by NicolasCadieux** [comment]
https://gis.stackexchange.com/questions/67210/convert-3d-wkt-to-2d-shapely-geometry
I believe the problem comes from the Shapely library as my code, using geopandas was the same problem.

**Comment by NicolasCadieux** [comment]
By the way, my code in found here: https://gitlab.com/njacadieux/upstream_downstream_shortests_path_dijkstra . I use GeoPandas to read the shapefile and then when I build the graph, I check for parallel edges.  If I find a parallel edges, I modify it by snapping it in two edges of equal length.   This way, shapefile with parallel edged are completely loaded in the graph.

**Comment by NicolasCadieux** [comment]
Hi,
I would like to contribute fix this problem.  I now have the experience to improve this function. I would like the function to check for multi line objects, 3D geometries, and parallel edges that are removed by this function.  I have never directly contributed code to a project.  Can you point me in the right direction?
Nicolas
