### ISSUE TITLE
Shapefile read, rounding of decimals in u,v , wkt and Json all different.

### ISSUE THREAD

**Issue by NicolasCadieux** [networkx/networkx#3479]
When making a graph using  read_shp(path, simplify=True):, u,v, and first and last vertex in Wkt and Json are all rounded differently.  Some values are rounded to 9,10 and 16 or more decimals making it more difficult to query the coordinate in the Wkt. I have not checked wkb.

**Comment by dschult** [comment]
Suggestions?  Is the rounding done in networkx?  It sounds like the problem is when the file is created, not when it is read...

Reopen if I didn't understand or if there is another suggestion for how to fix this.

**Comment by NicolasCadieux** [comment]
Hi, 
We should be able to select a format that we want for the edges tuples.  Currently, it's impossible too find the u,v in the first or last nodes of the wkt string.  This was important for me.  I basically had to rewrite the read_shp() using geopandas instead.  I also fixed the problem of parallel edges disappearing in the digraph.  I could send you the code if you want.

**Comment by NicolasCadieux** [comment]
Hi,
I can't figure out how to reopen the issues???
Nicolas

**Comment by dschult** [comment]
There should be a button at the bottom (next to the comment button) that says "reopen issue" or "reopen and comment". If not then just keep commenting and we'll get someone to reopen it.

I don't understand your comment about the format for the edges tuples. Are you saying that instead of converting a floating point number to a string in the default way we should be converting them to a string with a specified format string that could be chosen by the user? I am not an expert  in shapefiles Wkt Wkb etc. 

In what way does geopandas help?

**Comment by NicolasCadieux** [comment]
I will be happy to work with you when I am back from vacation in about two week.  The problem is the the u,v nodes tuples, that make up the edges will be extracted from the geometry that has 15 decimal points.  I can find out exactly what iso standard gdal is using.  The Wkt format is rounded at 10 decimals.  I think that is the standard.  The u and v correspond to the first and last nodes of the geometry.  The problem is that if you want to know if the u or v are the  first or last node of the line, you cannot use the u,v tuple as they will not correspond to the values in the Wkt.

**Comment by NicolasCadieux** [comment]
Nothing next to the comment button.  Maybe it’s a browser bug or an administrator thing.

**Comment by dschult** [comment]
Might be an administrator thing. I thought the original poster could reopen... sorry.

I still don't understand the sentences in your description of u,v, first last, Wkt etc.
I understand what roundoff error is and that the error will depend on the hardware used and order of operations.

**Comment by NicolasCadieux** [comment]
When creating the network from a line geometry, edges u,v are created by taken the first (u) and last (v) nodes (or vertex) in the line.  If a line is the following: LineString(0 0, 1 1, 2 2) that will create edge((0,0) (2,2)).  The first  vertex of the line is at coordinates 0,0 and the last vertex is at coordinates 2,2.  The problem is that the edged could be ((0.0,0.0) (2.0,2.0)) (but with 10 to 15 decimals). Better?  If not, I will give you the exact example when I am back from vacation.

**Comment by dschult** [comment]
It looks like you are reading the file and the program converts the values to floating point. When you then try to print the floating point values, round-off error naturally arises and you get lots of decimals. Is this the problem?

How do the many decimals arise? Are you printing the edges?

**Comment by rossbar** [comment]
I'm going to close this one due to inactivity. If the issue persists, please reopen. A minimum reproducing example would be very helpful in determining what the problem is and how it can be resolved.
