### ISSUE TITLE
k_clique_communities return communities included into each other

### ISSUE THREAD

**Issue by Yquetzal** [networkx/networkx#3482]
In some particular cases, k_clique_communities algorithm can return a community whose nodes are totally included in another community. This is not a bug as it is a consequence of the definition of the algorithm, but since it is counterintuitive, I point it here.

Below, a minimal working example:
```
import networkx as nx
g = nx.Graph()
g.add_edges_from([(1,2),(2,3),(1,3)])
g.add_edges_from([(1,4),(1,5),(2,6),(2,7),(3,8),(3,9)])
for i in range(4,10):
    for j in range(i+1,10):
        g.add_edge(i,j)
list(nx.algorithms.community.k_clique_communities(g,k=3))
```
-----
=>`[frozenset({1, 2, 3}), frozenset({1, 2, 3, 4, 5, 6, 7, 8, 9})]`

**Comment by dschult** [comment]
Should anything be done about this? I will close it (still searchable). Reopen it if there is something we should do.
