### ISSUE TITLE
dfs_preorder_nodes docstring says "edges" instead of "nodes"

### ISSUE THREAD

**Issue by tbitai** [networkx/networkx#3483]
https://github.com/networkx/networkx/blob/09c3da707d12aec42f3c0b2f91b60007bb436d37/networkx/algorithms/traversal/depth_first_search.py#L284

**Comment by dschult** [comment]
See comment: https://github.com/networkx/networkx/pull/3484#issuecomment-504570647
about this same change being needed elsewhere. I am going to merge #3484 
but we still need to check the other functions in that module (and fix them in another PR).
