### ISSUE TITLE
pygraphviz should be added to networkx requirements

### ISSUE THREAD

**Issue by marcotama** [networkx/networkx#3486]
### Subject of the issue
The module `pygraphviz` is required (not having it yields an exception), and thus it should be added to requirements.txt and to `networkx` requirements.

### Your environment
* networkx version 1.11
* Python version 3.7
* Operating System MacOS 10.13 (High Sierra)

### Steps to reproduce
```
nx_graph = nx.DiGraph(directed=True)
nx_graph.add_edges_from([('A', 'B'), ('C', 'B')])
graph = nx.drawing.nx_agraph.to_agraph(nx_graph)
```
raises a `ImportError`:
```
  File "/path/to/my/script.py", line 1116, in generate_graph
    graph = nx.drawing.nx_agraph.to_agraph(nx_graph)
  File "/usr/local/lib/python3.7/site-packages/networkx/drawing/nx_agraph.py", line 135, in to_agraph
    'http://pygraphviz.github.io/')
ImportError: ('requires pygraphviz ', 'http://pygraphviz.github.io/')
```

**Comment by nandahkrishna** [comment]
I'm afraid NetworkX 1.11 is an older version, current version is 2.3 and development is 2.4, and this issue doesn't exist in the newer versions. Do check [here](https://github.com/networkx/networkx/blob/master/requirements/extras.txt) to see the new requirements file for extras (which includes `matplotlib`, `pygraphviz`, etc). 

I'd suggest updating NetworkX to the latest version, `pip install networkx[all]` should help install all the requirements. Hope this was helpful!

**Comment by marcotama** [comment]
Good to know, apologies for opening this then, and thanks for the suggestion!

**Comment by nandahkrishna** [comment]
No problem at all, issues are always welcome. Do create a separate environment for this though, to avoid conflicting package versions.
