### ISSUE TITLE
read_edgelist using a file handle fails in python3

### ISSUE THREAD

**Issue by ak-watson** [networkx/networkx#3491]
I am reading in a network from a file as follows using networkx 2.3.

with open('network.edgelist', 'r') as fh:
    my_network = nx.read_edgelist(fh)

This still works in python2 but switching to python3 throws up an error based on the use of "line.decode(encode) on line 366 of "networkx/readwrite/edgelist.py". (Full error message below).

The line in question is:

"line.decode(encoding) for line in path" 

This is based on a change in python3, where the string is already decoded, so has no ".decode" attribute.

Deleting ".decode(encoding)" resolved the problem for me and the edgelist file is read correctly.

Traceback (most recent call last):
  File "script.py", line 33, in <module>
    yeast_network = nx.read_edgelist(fh)
  File "</home/user/.local/lib/python3.6/site-packages/decorator.py:decorator-gen-584>", line 2, in read_edgelist
  File "/home/user/.local/lib/python3.6/site-packages/networkx/utils/decorators.py", line 240, in _open_file
    result = func_to_be_decorated(*new_args, **kwargs)
  File "/home/user/.local/lib/python3.6/site-packages/networkx/readwrite/edgelist.py", line 369, in read_edgelist
    data=data)
  File "/home/user/.local/lib/python3.6/site-packages/networkx/readwrite/edgelist.py", line 250, in parse_edgelist
    for line in lines:
  File "/home/user/.local/lib/python3.6/site-packages/networkx/readwrite/edgelist.py", line 366, in <genexpr>
    lines = (line.decode(encoding) for line in path)
AttributeError: 'str' object has no attribute 'decode'

**Comment by dschult** [comment]
This works with ```with open('network.edgelist', 'rb') as fh:```
I think you need 'rb' to make it work. 
Is there a way to easily handle either 'r' or 'rb' in python3?

**Comment by ak-watson** [comment]
Ah excellent thanks.

My bad for being a late mover to python3. With reading in 'rb' mode it works fine. 

I can't think of an easy way... The only thing I could think of would be to use try to catch attribute errors (below, sorry for the lack of tabulation...). But I'm not sure if that might come with its own problems.

My bad for not spotting 'rb' was recommended anyway. Thank you!

try:
lines = (line.decode(encoding) for line in path)
except AttributeError:
lines = (line for line in path)

**Comment by dschult** [comment]
That seems good.  Let's use:

    try:
        lines = (line.decode(encoding) for line in path)
    except AttributeError:
        lines = (line for line in path)

**Comment by PalAditya** [comment]
Rather than using try-except, can't it be done by *detecting* the python version (using the sys module), and using an **if-else** construct, since exceptions are relatively more expensive?

Also, is this issue still open for grabs? I'd love to make a PR on it then and help out this amazing project 😁

**Comment by dschult** [comment]
My understanding (and timing from long long ago) is that try-except is faster than if-else when it doesn't throw an exception and slower when it does. Also, I don't think this is a matter of checking the Python version. Which processing should be done depends on the input.

Yes! Please create a PR for this. :)

**Comment by PalAditya** [comment]
Sure, that makes sense. Will work on the PR now 😄
