### ISSUE TITLE
Error exporting Graph with write_shp

### ISSUE THREAD

**Issue by pglah** [networkx/networkx#3492]
Hello, 
I am trying to export my graph using the write_shp function. 
My graph contains nodes and edges. The nodes have the following attributes:
{'loc': (406314.08793068246, 5757058.536303686)}
The edges have the following attributes:
{'coord': {'startEast': 404345.15315909754, 'startNorth': 5755594.779988128, 'endEast': 404334.2216339487, 'endNorth': 5755595.912515098}, 'dist': 18.51}

When I use this Graph in the function write_shp, I get the following error: 

> NotImplementedError: Wrong number or type of arguments for overloaded function 'Feature_SetField'.
  Possible C/C++ prototypes are:
    OGRFeatureShadow::SetField(int,char const *)
    OGRFeatureShadow::SetField(char const *,char const *)
    OGRFeatureShadow::SetField(int,double)
    OGRFeatureShadow::SetField(char const *,double)
    OGRFeatureShadow::SetField(int,int,int,int,int,int,float,int)
    OGRFeatureShadow::SetField(char const *,int,int,int,int,int,float,int)

If I comment out the lines using the setField() method, everything works.
I know it is most likely an issue with ogr, but I thought that maybe someone here experienced something similar. 

Are my graph attributes formatted wrong?

**Comment by dschult** [comment]
This looks to be more of an issue with OGR than with NetworkX.
