### ISSUE TITLE
Bug in lexicographical_topological_sort()

### ISSUE THREAD

**Issue by smite** [networkx/networkx#3493]
### Bug

In NetworkX 2.3 `lexicographical_topological_sort` fails with a `TypeError: '<' not supported between instances of 'Node' and 'Node'` when the key function returns the same priority for two topological-order-equivalent nodes, and the nodes lack the `__lt__` method.

The `__lt__` method should not be required, since in NetworkX the graph nodes can be any hashable object.

### Cause

`lexicographical_topological_sort` uses the `heapq` module to implement the algorithm.
The graph nodes are stored in the priority queue as (priority, node) pairs, and `heapq`compares them using the < operator, which works on tuples lexicographically, i.e. first it compares the first elements, if they are equal it compares the next elements etc.
Thus if two elements have the same priority it tries to compare the nodes themselves using `__lt__` so you have to define it in order to avoid an error.

The `heapq` documentation proposes a solution to this specific issue (use triples instead of pairs):
https://docs.python.org/3.7/library/heapq.html#priority-queue-implementation-notes

### Example

    import networkx as nx

    class Node:
        def __init__(self, n):
            self.label = n
            self.priority = 1

        def __repr__(self):
            return 'Node({})'.format(self.label)

    def sorting_key(node):
        return node.priority

    nodes = [Node(n) for n in range(4)]
    G = nx.DiGraph()
    G.add_edges_from([(nodes[a], nodes[b]) for a,b in [(0,1), (0,2), (0,3), (2,3)]])
    F = nx.algorithms.dag.lexicographical_topological_sort(G, key=sorting_key)
    print(list(F))
    # fails if nodes have equal priority and lack the __lt__ method

**Comment by dschult** [comment]
Your description makes sense -- though I haven't looked at any code yet.
I suspect the solution is something like using triples where the middle element is a unique number for each node.  ```nodeid = {n: i for i, n in enumerate(G)}``` sets up the values and then the tuple is ```(priority, nodeid[node], node)```

**Comment by subhrm** [comment]
I am now working on it.
