### ISSUE TITLE
[FEA Proposal] Graph generators and embedding methods

### ISSUE THREAD

**Issue by j1c** [networkx/networkx#3496]
@bdpedigo and I are developers of [GraSPy](https://github.com/neurodata/graspy), which is a package for studying random graphs, and want to know if networkx is interested in these features that already exist in GraSPy:

1. [Random dot product graphs](https://graspy.neurodata.io/reference/simulations.html#graspy.simulations.rdpg) - a generative model for random graphs that is more flexible then the stochastic block model.
2. Degree-corrected stochastic block models - an extension of SBMs where nodes have degree heterogeneity.
3. [Adjacency spectral embedding](https://graspy.neurodata.io/reference/embed.html#graspy.embed.AdjacencySpectralEmbed) - embedding method for estimating parameters under RDPG model
4. [Laplacian spectral embedding](https://graspy.neurodata.io/reference/embed.html#graspy.embed.LaplacianSpectralEmbed) - a version of this exists in networkx but it is only used for [plotting](https://networkx.github.io/documentation/stable/auto_examples/drawing/plot_spectral_grid.html?highlight=spectral)

You can think of 2 and 3 are methods for generating features given a single graph.

Papers:
1. [Statistical Inference on Random Dot Product Graphs: a Survey](http://www.jmlr.org/papers/volume18/17-448/17-448.pdf)
2. [A Consistent Adjacency Spectral Embedding for Stochastic Blockmodel Graphs](https://amstat.tandfonline.com/doi/full/10.1080/01621459.2012.699795)

@jovo

**Comment by dschult** [comment]
Yes, we are interested in those features.

I think 4 (the laplacian spectral embedding) may already be included in spectral_layout().
Our plotting code is supposed to be independent of our layout code... so the example which uses spectral_layout does plot the result, but the layout algorithm doesn't require plotting...

So, I think the two embedding algorithms could be included in our layout algorithms.
The first two seem to naturally fit with the code on stochastic block models, though 
it may make more sense to create a new module for them.

Thanks!
