### ISSUE TITLE
Why does all_shortest_paths find a much shorter route through a weighted graph than shortest_path?

### ISSUE THREAD

**Issue by dt99jay** [networkx/networkx#3497]
When I run...

`shortest_path(G, start, end, weight="length")`

...on a graph (with 2,346 nodes and 13,231 edges, and where `length` is an edge attribute with value of anything between 1 and 5,107) it returns a path of length 9,495.

But when I run...

`all_shortest_paths(G, start, end, weight="length")`

...for the same `start` and `end` of the same graph, it returns two paths: the one already found in the previous step, but also a shorter one with length 7,940.

Why is the shorter path not returned by `shortest_path` (and why does `all_shortest_paths` include the much longer route at all)?

(My graph is a road network with each node a coordinate in the EPSG:27700 CRS. I'm calculating the length of each route by making a LineString of the nodes produced by `shortest_path` / `all_shortest_paths` and using Shapely to measure the length.)

**Comment by dschult** [comment]
You haven't given enough info to say whether it is a bug or a feature... :}

Is it possible that you have negative lengths? 
Djikstra doesn't give shortest paths in that case.

**Comment by dt99jay** [comment]
Thanks for getting back to me! The minimum value of `length` is 1, so no negative weights.

I've uploaded the graph data here: http://www.sharecsv.com/s/b64a368b9021108a8263cc3a549a398e/G.csv

The following code shows the behaviour I described above:

```
import pandas as pd
import ast
import networkx as nx
from shapely.geometry import LineString

df = pd.read_csv("G.csv", converters={"source": ast.literal_eval, "target": ast.literal_eval}) # Source and target are tuples
G = nx.from_pandas_edgelist(df, edge_attr="length")

start = (438932.0, 114718.0)
end = (444888.76, 115014.87)

route = nx.shortest_path(G, start, end, weight="length")
print(LineString(route).length) # Gives 9495.11245285627

routes = nx.all_shortest_paths(G, start, end, weight="length")
for r in routes:
    print(LineString(r).length) # Gives 9495.11245285627, then 7939.613295612634
```

**Comment by dschult** [comment]
Thanks for this example. I can verify that it gives a strange result with 2 paths reported for ```all_shortest_paths```: the one from ```shortest_path``` and another which is apparently shorter than the one returned by ```shortest_path```.  

Just to make sure it isn't a problem with double precision round-off when comparing nodes, I converted the graph to integer nodes and I find the same issue.  Also, the first 141 nodes of the second path are the same as the first path. The last 120 or so nodes differ...

Any ideas how to track this bug down (I'm assuming it is a bug until shown otherwise)?

**Comment by dt99jay** [comment]
I've run the below to choose up to 500 pairs of random nodes from the same graph and compare the result of `shortest_path` with the shortest value found by `all_shortest_paths`.

There are often about 5 pairs of nodes within the 500 for which one of `all_shortest_paths`'s results is shorter than `shortest_path`. Usually the difference is small (>1m for a route of 3-6,000m) but quite often there's a a bigger difference e.g. a few 100m. I've not noticed any feature of the longer ones yet e.g. it's not a problem that only occurs with longer routes.

Here's typical data from one of these tests – `all_shortest_paths` seems to show a 3322m route which is 317m shorter than `shortest_path`'s 3639m: http://www.sharecsv.com/s/d93d5cf20c54003621108ac5c827e0e1/lengths.csv

Test code:

```
import pandas as pd
import ast
import networkx as nx
from shapely.geometry import LineString
from random import choice

df = pd.read_csv("G.csv", converters={"source": ast.literal_eval, "target": ast.literal_eval})
G = nx.from_pandas_edgelist(df, edge_attr="length")

def calc_lengths(start, end):
    shortest_path = nx.shortest_path(G, start, end, weight="length")
    all_shortest_paths = list(nx.all_shortest_paths(G, start, end, weight="length"))
    shortest_path_length = LineString(shortest_path).length
    all_shortest_paths_length = [LineString(l).length for l in all_shortest_paths]
    return {
        "start": start,
        "end": end,
        "shortest_path": shortest_path,
        "shortest_path_length": shortest_path_length,
        "all_shortest_paths": all_shortest_paths,
        "all_shortest_paths_length": all_shortest_paths_length
    }

lengths = []

for test in range(0,499):
    start = choice(list(G.nodes()))
    end = choice(list(G.nodes()))
    if nx.has_path(G, start, end) and start != end:
        lengths.append(calc_lengths(start, end))

df_lengths = pd.DataFrame(lengths)
df_lengths["difference"] = df_lengths["shortest_path_length"] - [min(l) for l in df_lengths["all_shortest_paths_length"]]
df_lengths.to_csv("lengths.csv", index=False)
```

**Comment by dt99jay** [comment]
Oh, when `method="bellman-ford"`, the same test usually returns only one entry where `all_shortest_paths`'s shortest route is different to `shortest_path`, and I've not seen any for which the difference is more than 1m.

Also, using `nx.shortest_path(G, start, end, weight="length", method="bellman-ford")` on the original start and end returns the shorter 7939m route. `nx.all_shortest_paths(G, start, end, weight="length", method="bellman-ford")` still returns both 7939m and 9495m routes, but has the 7939m one first.

**Comment by dschult** [comment]
Hmmm... more mystery.  When I calculate the length of the paths given using the 'length' edge attribute I get the lengths of the two paths as the same. (And I do believe that Djikstra is implemented OK... we have used it for many many years without issues -- OK... so I would LIKE Djikstra to be bug-free so am projecting that desire... :)

What is LineString(path).length computing?  Could it be something other than the length computed by networkx?

**Comment by dt99jay** [comment]
Ah! My mistake – the `length` in the graph is wrong :roll_eyes:.

Your comment was really helpful: the sum of the path's edge lengths was >> than the geographic distance returned by the `LineString` of the node coords, and printing the edge lengths showed lots where the same length was repeated two or three times in a row along the path.

When making the graph, where I had a section of road made up of several segments, I forgot to divide the length by the number of segments, so many roads had `length` two or three times longer than they should have been. So `all_shortest_paths` was finding multiple solutions when going by (the incorrect) `length` but these were of different geographic distance.

Now `all_shortest_paths` matches `shortest_path` when measured by the sum of edge `length`s or the `LineString` of the nodes.

Anyway, many thanks for your help and apologies for wasting your time!
