### ISSUE TITLE
breadth-first search is not exhaustive

### ISSUE THREAD

**Issue by bertsky** [networkx/networkx#3498]
I believe it is an error that `bfs_edges` does not yield **all** edges reachable from the source node, but only one edge per reachable target node.

This is true for the [PADS blueprint](http://www.ics.uci.edu/~eppstein/PADS/BFS.py), with the difference that this fact is clearly stated in the docstring there:

> Edges that connect vertices within the same level are not included in the output.

Minimal example:
```Python
import networkx as nx

graph = nx.DiGraph()
graph.add_nodes_from(range(9))
graph.add_edge(0, 1)
graph.add_edge(0, 2)
graph.add_edge(1, 2)
graph.add_edge(2, 3)
graph.add_edge(3, 4)
graph.add_edge(4, 5)
graph.add_edge(5, 6)
graph.add_edge(6, 7)
graph.add_edge(6, 8)
graph.add_edge(7, 8)

edges = nx.bfs_edges(graph, 0)
assert set(edges) == set(graph.edges)
```

**Comment by dschult** [comment]
It is not an error to report only edges that reach new nodes. Just a different definition than you want to use. My understanding is that this is at least a common definition of a BFS ordering of edges.

Maybe we just need to update the docstring so it says more clearly what it does... :}

**Comment by bertsky** [comment]
I don't think so. A _BFS ordering_ always contains a complete set of edges. One could perhaps argue that the current behaviour returns a BFS view of _nodes_.

My PR does not incur much extra cost. Maybe I should modify it to allow exhaustive search as a (non-default) **option**?

**Comment by dschult** [comment]
I think this is already taken care of in ```edge_bfs```.  We need to make the docstrings of both these functions much more clear and they should point to each other and explain the difference.

**Comment by bertsky** [comment]
Ouch! I did not notice that. Indeed, `edge_bfs` was exactly what I was looking for!

Fixing docstrings then – I will close my PR.
