### ISSUE TITLE
get_edge_data() returns not all edges in MultiDiGraph

### ISSUE THREAD

**Issue by Sultan91** [networkx/networkx#3500]
Having `f.get_edge_data(0, 1):`
returns: `{0: {'weight': 3}, 1: {'weight': 2}, 2: {'weight': 1}} `
In case in `adj {0: {'weight': 3}, 1: {'weight': 2}, 2: {'weight': 1}}`.
However when a graph has `adj {0: {'weight': 3}, 2: {'weight': 1}, 1: {'weight': 2}}` not in order.
`get_edge_data()` returns: only one edge: `0: {'weight': 3}`

**Comment by dschult** [comment]
Hmmm... Not sure I understand. The order of a dict should have no impact. 
Can you give code for a small example?

**Comment by Sultan91** [comment]
Sorry it w as mistake on my side. There was sort of these adjacency
`{0: {'weight': 3}, {2:{1: {'weight': 2}, 2: {'weight': 1}}} `
