### ISSUE TITLE
Numeric assortativity coefficient does not work on weighted graphs

### ISSUE THREAD

**Issue by bwildi** [networkx/networkx#3501]
The numeric [assortativity coefficient function](https://networkx.github.io/documentation/networkx-1.9/reference/generated/networkx.algorithms.assortativity.numeric_assortativity_coefficient.html#networkx.algorithms.assortativity.numeric_assortativity_coefficient) does not work when applied on weighted graphs -- it treats them as unweighted graphs.

Below is a code example - I generate an adjacency matrix, calculate the assortativity coefficient using NetworkX  (incorrect output) and then the correct output in Numpy. I also tried converting the weighted network to an unweighted network to see if I  would get the coefficient then, but it is still inaccurate - I'm unsure why that is the case.

```python
import networkx as nx
import numpy as np
import pandas as pd
```

```python
# Incorrect nx
array = np.array([[5,3,0], [5,9,1],[0,3,3]])
G = nx.from_numpy_array(array)
att = {0:3,1:4,2:6}
nx.set_node_attributes(G, att, 'Att')
print(nx.algorithms.numeric_assortativity_coefficient(G,'Att'))
```

    0.4696969696969706
    

```python
# Correct NumPy
att2 = np.array(list(att.values()))
array2 = array / np.sum(array)
a_x = np.sum(array2, axis=1)
b_y = np.sum(array2, axis=0)
stdx = np.sqrt(np.sum(att2**2 * a_x) - np.sum(att2 * a_x)**2)
stdy = np.sqrt(np.sum(att2**2 * b_y) - np.sum(att2 * b_y)**2)

print(np.sum(np.outer(att2, att2) * (array2 - np.outer(a_x, b_y))) / (stdx * stdy))
```

    0.6057726688418602
    

```python
# Attempted nx correction
df = {'source': [], 'target':[]}
attrib = {}
l = 0
for i in range(3):
    for j in range(3):
        for _ in range(array[i,j]):
            df['source'].append(l)
            df['target'].append(l+1)
            attrib[l] = att[i]
            attrib[l+1] = att[j]
            l += 2
df = pd.DataFrame(df)
G = nx.from_pandas_edgelist(df)
nx.set_node_attributes(G, attrib, 'Att')
nx.algorithms.numeric_assortativity_coefficient(G, 'Att')
```

    0.5857142857142826

**Comment by dschult** [comment]
Hi... 
The current implementation doesn't involve edges weights at all. Only node attributes.
Does the edge weighted version you show come from a reference somewhere?

Finally, can you say a few words about your workaround? It looks like you set up a new graph to mimic the original edge-weighted graph using an unweighted graph. But what's going on there?

**Comment by bwildi** [comment]
Hi,

I am using the same [Newman](https://arxiv.org/pdf/cond-mat/0209450.pdf) reference as the NetworkX documentation. My implementation is just that equation. You are correct that my workaround was mimicing the original edge-weighted graph using an unweighted graph.

In the network I was using, edge weights represented the number of connections between two nodes. I have now realised that by setting up the graph as a multi-directional graph I get the right answer. Apologies that I did not realise this before.



```python
import networkx as nx
import numpy as np

array = np.array([[5,3,0], [5,9,1],[0,3,3]])
G = nx.from_numpy_array(array, parallel_edges=True, create_using=nx.MultiDiGraph)
att = {0:3,1:4,2:6}
nx.set_node_attributes(G, att, 'Att')
print(nx.algorithms.numeric_assortativity_coefficient(G,'Att'))
```

    0.6057726688418602
    
I don't think this is ideal though for two reasons:

1. It is quite common for edge weight to represent a number of connections (e.g. the number of trips made between A and B), so it's unclear to me why you can't just run this algorithm with a weighted network in that way.
2.  The multigraph option is substantially slower than my NumPy version. It both takes a long time to set up the multigraph, and to calculate numeric assortativity. A simple benchmark is below: using 100 nodes, each of which can have up to 100 connections to other nodes, where each node has one of 10 possible attributes. With much larger graphs, this would not be useable.



```python
import networkx as nx
import numpy as np
```


```python
# n is number of nodes
# h is the max number of connections between nodes
# a is the number of possible attributes
n = 100
h = 100
a = 10
array = np.random.randint(0,h,(n,n))
```


```python
%%timeit
# Creating the network
G = nx.from_numpy_array(array, parallel_edges=True, 
                        create_using=nx.MultiDiGraph
                       )
```

    2.13 s ± 24.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
    


```python
G = nx.from_numpy_array(array, parallel_edges=True, 
                        create_using=nx.MultiDiGraph
                       )
# Adding attributes
att2 = np.random.randint(0,a,n)
att = dict(enumerate(att2)) 
nx.set_node_attributes(G, att, 'Att')
```


```python
%%timeit
# Calculating numeric assortativity via NetworkX
nx.algorithms.numeric_assortativity_coefficient(G,'Att')
```

    308 ms ± 7.78 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
    


```python
%%timeit
# Calculating numeric assortativity via NumPy
array2 = array / np.sum(array)
a_x = np.sum(array2, axis=1)
b_y = np.sum(array2, axis=0)
stdx = np.sqrt(np.sum(att2**2 * a_x) - np.sum(att2 * a_x)**2)
stdy = np.sqrt(np.sum(att2**2 * b_y) - np.sum(att2 * b_y)**2)

np.sum(np.outer(att2, att2) * (array2 - np.outer(a_x, b_y))) / (stdx * stdy)
```

    152 µs ± 1.58 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)

**Comment by dschult** [comment]
It looks like your timing doesn't include translating the NetworkX graph to a numpy matrix.  If so, that's perhaps not the right comparison. I guess if you start with the data in a numpy matrix, it is useful, but then I would expect it to be faster.

Currently the function (and all others in that module) ignore edge weights. I am fine with you adding the functionality of computing assortativity by interpreting the edge weights as numbers of parallel edges. You will need to document it carefully so people understand that is what is being assumed. And you'll need to make the interface simple; with defaults that align with what currently happens.

Before you start that though, can you make the following timing comparison.
-  start with a graph G with weighted edges. time 2 things: 
    1) nx.numeric_assortativity_coefficient
    2) converting the graph to a numpy matrix, then computing the coefficient.
Make sure they give the same result too.

Thanks!

**Comment by bwildi** [comment]
See below. I have to create two versions of the graph - one weighted DiGraph, and one unweighted MultiDiGraph with parallel edges - in order to get comparable results.

The NumPy implementation on the DiGraph is a couple of orders of magnitude faster than NetworkX on the MultiDiGraph with 100 nodes, with edge weights between 0 and 100. For the MultiGraph, increasing the weights will make the implementation even slower, while increasing the weights on the NumPy version should have barely any affect.

The NumPy implementation is even a few times faster than NetworkX on the unweighted network. The NumPy implementation probably could be optimised more by actually creating a mixing matrix.

There are some small rounding errors, not sure why.


```python
import networkx as nx
import numpy as np
```


```python
# n is number of nodes
# h is the max number of connections between nodes
# a is the number of possible attributes
n = 100
h = 100
a = 100
array = np.random.randint(0,h,(n,n))
att = np.random.randint(0,a,n)
```


```python
def numpy_num_assort_coef(G2, attribute, weight='weight'):
    # Get the matrix and the attributes: x and y
    array2 = nx.to_numpy_array(G2, weight=weight)
        
    att2 = np.array(list(nx.get_node_attributes(G2, attribute).values()))
    
    # Convert to proportional matrix
    array2 = array2 / np.sum(array2)
    
    # Get fraction of edges starting at x and fraction ending at y
    a_x = np.sum(array2, axis=1)
    b_y = np.sum(array2, axis=0)
    
    # Get standard deviations
    stdx = np.sqrt(np.sum(att2**2 * a_x) - np.sum(att2 * a_x)**2)
    stdy = np.sqrt(np.sum(att2**2 * b_y) - np.sum(att2 * b_y)**2)
    
    # Computer correlation coefficient (i.e. numeric assortativity)
    return np.sum(np.outer(att2, att2) * (array2 - np.outer(a_x, b_y))) / (stdx * stdy)
```


```python
# Set up networks - one multi, one weighted
G = nx.from_numpy_array(array, parallel_edges=True, 
                        create_using=nx.MultiDiGraph
                       )
G2 = nx.from_numpy_array(array, create_using=nx.DiGraph)

att = dict(enumerate(att)) 
nx.set_node_attributes(G, att, 'Att')
nx.set_node_attributes(G2,att,'Att')
```


```python
# Correct answer with NetworkX using parallel edges
nx.algorithms.numeric_assortativity_coefficient(G,'Att')
```




    -0.0009470472508935576




```python
# Same answer for NumPy on the weighted graph (with a rounding error)
numpy_num_assort_coef(G2,'Att')
```




    -0.0009470472508934433




```python
# NetworkX answer from treating weighted graph as unweighted
nx.algorithms.numeric_assortativity_coefficient(G2,'Att')
```




    -9.003841181043387e-05




```python
# NumPy unweighted
numpy_num_assort_coef(G2,'Att',None)
```




    -9.003841181598456e-05




```python
print('Weighted/Multigraph:')
%timeit nx.algorithms.numeric_assortativity_coefficient(G,'Att')
%timeit numpy_num_assort_coef(G2,'Att')
print()
print('Unweighted:')
%timeit nx.algorithms.numeric_assortativity_coefficient(G2,'Att')
%timeit numpy_num_assort_coef(G2,'Att', None)
```

    Weighted/Multigraph:
    263 ms ± 10.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
    3.3 ms ± 44.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
    
    Unweighted:
    12.4 ms ± 422 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
    3.27 ms ± 102 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

**Comment by dschult** [comment]
Thanks for this -- it looks like computing with numpy is quite efficient.

I'm still having trouble with how node assortativity is defined when accounting for edge weights. The Newman article doesn't actually discuss edge weights except to say that one can account for them. Other searching shows that some people have used edge weights to replace degree with "degree strength" -- meaning the sum of the edge weights replaces the number of edges when computing degree.  I think this is what you are proposing.  Can you find a reference where they use/define this type of assortativity?

I'm also wondering if this is something universal to the assortativity collection of routines we offer. Are other users probably going to want edge weighted versions of the many assortativity routines we offer? Perhaps we should be looking at changing this on a deeper level?
