### ISSUE TITLE
pydot includes

### ISSUE THREAD

**Issue by michaelkalab** [networkx/networkx#3506]
networkx.drawing.nx_pydot.read_dot needs pydot installed
however, this package is not necessarily included in networkx and no corresponding exception is thrown

**Comment by dschult** [comment]
pydot is an optional dependency; like numpy, you can run networkx without it so long as you don't use any functions that require it. If you try to run it an exception is thrown telling you that you need to install pydot.  Perhaps [this page](https://github.com/networkx/networkx/tree/master/requirements) can help.
