### ISSUE TITLE
graph becomes NoneType after using functions to add nodes

### ISSUE THREAD

**Issue by flawnson** [networkx/networkx#3509]
Not sure why, but the type of my graph changes to NoneType and refuses to accept node attributes using functions like add_nodes_from and set_node_attributes.

**Comment by dschult** [comment]
You will need to supply more info for us to help you.
Maybe a short example piece of code that shows the trouble. 
Most likely you will find the trouble as you are preparing the example to show us what is wrong :}

**Comment by flawnson** [comment]
Yes usually it helps to explain a problem to get a bigger picture of what's wrong.

`G = nx.Graph()
node_feature_df = node_feature_df.transpose()
node_feature_dict = node_feature_df.to_dict()
nx.set_node_attributes(G, node_feature_dict)
print(list(G.nodes.data()))`

node_feature_df is a pandas dataframe containing a list of all the nodes (rows) and their features (columns) in a csv file. There is no error, but the print statement returns an empty list.

**Comment by dschult** [comment]
You never added any nodes. G is created as a graph with no nodes or edges.
When you use ```nx.set_node_attributes``` it sets the node attributes for all the nodes in G, but there aren't any yet. 

Try creating the graph with something like:

    n = node_feature_df.shape[0]
    G = nx.empty_graph(n)

**Comment by flawnson** [comment]
I see, ok I assumed that by adding attributes, the nodes would also be added to the empty graph. Thanks for the help, it works perfectly!

Would the same concept apply for edge attributes? Say if I wanted to use from_pandas_edgelist, would I have to add edges first? Could I add both node and edge attributes?

**Comment by dschult** [comment]
Take a look at the ```add_edges_from``` and ```add_weighted_edges_from``` methods at
https://networkx.github.io/documentation/stable/reference/classes/graph.html
