### ISSUE TITLE
`global_efficiency` is inefficient

### ISSUE THREAD

**Issue by joelmiller** [networkx/networkx#3510]
See https://stackoverflow.com/a/57032282/2966723

Currently the code takes every single pair of nodes (in both directions), and finds the length of the path between those two.  

An obvious factor of 2 speedup is to change the denominator by a factor of 2 and use `combinations` rather than `permutations` to do the calculation, so that the path is only considered once.  (presumably would need to check that the graph is undirected first)

Alternately, another option is to use this code that I provided in my answer.

    def my_global_efficiency(G):
        '''author Joel C Miller
           https://stackoverflow.com/a/57032282/2966723
        '''

        n = len(G)
        denom = n*(n-1)
        if denom>0:
            efficiency = 0
            for path_collection in nx.all_pairs_shortest_path_length(G):
                source = path_collection[0]
                for target in path_collection[1]:
                    if target != source:
                        efficiency += 1./path_collection[1][target]    
                return efficiency/denom
        else:
            return 0

**Comment by dschult** [comment]
This looks good to me.
