### ISSUE TITLE
DAG shortest path

### ISSUE THREAD

**Issue by Pascal-Ortiz** [networkx/networkx#3513]
Does NetworX provide a specific algorithm to solve the single-source shortest-paths problem on a weighted DAG? There is a [well known algorithm](https://www.boost.org/doc/libs/1_37_0/libs/graph/doc/dag_shortest_paths.html) solving this problem and it has better complexity than Dijkstra algorithm. 

According to issue  #1161, seems that NetworkX doesn't provide it. Do you think this algorithm could be useful to add?

**Comment by dschult** [comment]
The hard part here is not providing the code for shortest-paths on a DAG but how to include it in NetworkX in a way that can be found easily and doesn't confuse people. For the DAG code see [this comment](https://github.com/networkx/networkx/pull/1118#issuecomment-41171119) on #1118. Maybe the algorithm you found is even better, I didn't look. 

So, does it go in dag.py? How will users find it? Will it check for DAG as part of the function? Will it allow the user to supply the topological sort on nodes? There are many docstrings to change to advertise it including functions in weighted.py and unweighted.py.

**Comment by Pascal-Ortiz** [comment]
> For the DAG code see [this comment](https://github.com/networkx/networkx/pull/1118#issuecomment-41171119) on #1118. Maybe the algorithm you found is even better, I didn't look.

It's exactly the same algorithm, the one referenced by the wikipedia [Shortest path article](https://en.wikipedia.org/wiki/Shortest_path_problem#Directed_acyclic_graphs_(DAGs)).


> 
> So, does it go in dag.py? 

Cormen's [book](http://staff.ustc.edu.cn/~csli/graduate/algorithms/book6/chap25.htm) references the problem in the *Single-Source Shortest Paths* chapter (section 25.4). Sedgewick's book does the same, as you can see on the [online book](https://algs4.cs.princeton.edu/44sp/), look a the *Acyclic edge-weighted digraphs* paragraph. Same schema for Wikipedia. In the 
[Dasgupta, Papadimitriou, Vazirani](http://algorithmics.lsi.upc.edu/docs/Dasgupta-Papadimitriou-Vazirani.pdf) book, the question is referenced in chapter 4 just after Dijkstra and Bellman-Ford algorithms.


So, in my opinion, the question traditionally takes place in `shortest_paths.weighted.py`.

**Comment by dschult** [comment]
Putting it in weighted.py sounds good to me. 
Unless there is a quick way to check for a dag, I think we should not have ```shortest_path``` check for a dag before deciding which routine to call. But maybe we can put something in the doc_string that tells users that for DAGs we have a special routine available. 

Sounds good!

**Comment by Pascal-Ortiz** [comment]
> Putting it in weighted.py sounds good to me.

OK. I'm planning to mimic the way similar functions (such as `single_source_bellman_ford` or `single_source_dijkstra`) are laid out in this file.

> Unless there is a quick way to check for a dag, I think we should not have `shortest_path` check for a dag 

I suppose you are referring to the `shortest_path` function in the `generic.py` file.

> before deciding which routine to call. But maybe we can put something in the doc_string that tells users that for DAGs we have a special routine available.

I agree with your suggestion. In any case, the algorithm needs to build a topological sorting of the graph and the `topological_sort()` function will raise an exception if the graph is not a DAG.

I will put the tests in the relevant test directory. Is there another file I need to modify? 


> 
> Sounds good!


Thanks!

**Comment by dschult** [comment]
You'll need to change the .rst files in the doc/reference/algorithms part of the repository to reflect the new function so sphinx will know to find the function and include its docstring.

Yes, I was referring to the ```shortest_path``` function in ```generic.py``` but there may be other places where it is appropriate (maybe the module docstring for all shortest paths). It might be good to add it somewhere in the docs for DAGs that this function exists in the shortest path section.

**Comment by Pascal-Ortiz** [comment]
After doing extensive tests, it appears that Dijkstra NetwokX implementation executes faster (about twice) than a dedicated shortest-path-for-dag algorithm. On some rare cases, Dijkstra is (twice) slower. Hence I doubt implementing  a dedicated algorithm to be really adding a bonus to NetworX.


NetworkX topological sort implementation has a narrow interface, you cannot get a partial topological sort from a given set of vertices (in our case, the single source of the shortest path). And, since the implementation is degree-based (and not dfs-based), you have to rewrite from scratch the function code in order to fix the problem. But anyway, even with a new version, Dijkstra remains faster.


Some code for tests:

```python


from random import randrange, sample
from time import clock
import networkx as nx

def random_acyclic(n):
    # This idea comes from SageMath code
    gnp = nx.erdos_renyi_graph(n, 0.3)
    G=nx.DiGraph()
    for u, v in sorted(gnp.edges()):
        if u>v:
            u, v=v, u
        G.add_edge(u,v,weight=float(randrange(1,10)))
    assert nx.is_directed_acyclic_graph(G)
    return G

def grid_graph(W, H, ratio_to_remove=0.1):
    G=nx.DiGraph()
    # horizontal edges
    for y in range(0, H+1):
        for x in range(0, W):
            a=(x, y)
            b= (x+1,y)
            w=float(randrange(1, 10))
            G.add_edge(a, b, weight=w)
            
    # vertical edges
    for x in range(0, W+1):
        for y in range(0, H):
            a=(x, y)
            b= (x,y+1)
            w=float(randrange(1, 10))
            G.add_edge(a, b, weight=w)
    nb_to_remove=int((W*H)*ratio_to_remove)
    ebunch=sample(G.edges(),nb_to_remove)
    G.remove_edges_from(ebunch)
    

    return G


def ssp_dag_nx(Gnx,origin):

    topo_sort=nx.topological_sort(Gnx)

    n=len(Gnx)
    sources=[origin]
    INF=float("inf")
    dist={u:INF for u in Gnx}
    dist[origin]=0
    for s in topo_sort:
        d=dist[s]
        for t,dd in Gnx[s].items():
            w=dd["weight"]
            if w+d< dist[t]:
                 dist[t]=w+d
    return {u:d for (u,d) in dist.items() if d!=INF}


def test_grid(side, ratio_to_remove=0.2):
    
    W=side
    H=side
    G=grid_graph(W,H)


    print("Graph ready!")
    print("------------")
    print("Vertices:", len(G))    
    print("Edges:", G.number_of_edges())  
    print()

    origin=(0, 0)
    begin=clock()
    dist_dijkstra=nx.single_source_dijkstra(G,origin)[0]
    print("Dijkstra: %.2f" %(clock()-begin))


    begin=clock()
    dist_toposort_nx=ssp_dag_nx(G,origin)
    print("NetworkX toposort: %.2f" %(clock()-begin)) 
    
    print("Checking:", dist_toposort_nx==dist_dijkstra)
    
    print("--------------------")


def test_er(n):    
    G=random_acyclic(n)

    print("Graph ready!")
    print("------------")
    print("Vertices:", len(G))    
    print("Edges:", G.number_of_edges())  
    print()
    
    
    Ntest=2

    for i in range(Ntest):
        
        
        origin=randrange(len(G)//10)
        print("origin:", origin)    

        begin=clock()
        dist_dijkstra=nx.single_source_dijkstra(G,origin)[0]
        print("Dijkstra: %.2f" %(clock()-begin))

        begin=clock()
        dist_toposort_nx=ssp_dag_nx(G,origin)
        print("NetworkX toposort: %.2f" %(clock()-begin)) 
        
        print("Checking:", dist_toposort_nx==dist_dijkstra)
        
        print("--------------------")


test_grid(side=500, ratio_to_remove=0.1)
test_er(4000)
```

outputting:


```
Graph ready!
------------
Vertices: 251001
Edges: 476000

Dijkstra: 4.96
NetworkX toposort: 2.36
Checking: True
--------------------
Graph ready!
------------
Vertices: 4000
Edges: 2400586

origin: 155
Dijkstra: 0.80
NetworkX toposort: 1.67
Checking: True
--------------------
origin: 355
Dijkstra: 0.72
NetworkX toposort: 1.66
Checking: True
--------------------
origin: 106
Dijkstra: 0.83
NetworkX toposort: 1.68
Checking: True
--------------------
origin: 252
Dijkstra: 0.76
NetworkX toposort: 1.68
Checking: True
--------------------
origin: 114
Dijkstra: 0.83
NetworkX toposort: 2.19
Checking: True
--------------------
origin: 251
Dijkstra: 0.75
NetworkX toposort: 1.60
Checking: True
--------------------
origin: 101
Dijkstra: 0.82
NetworkX toposort: 1.62
Checking: True
--------------------
origin: 157
Dijkstra: 0.81
NetworkX toposort: 1.81
Checking: True
--------------------
origin: 286
Dijkstra: 0.74
NetworkX toposort: 1.61
Checking: True
--------------------
origin: 91
Dijkstra: 0.83
NetworkX toposort: 1.61
Checking: True
--------------------
```

**Comment by dschult** [comment]
Thank You!!
