### ISSUE TITLE
cannot import name 'LFR_benchmark_graph'

### ISSUE THREAD

**Issue by agosztolai** [networkx/networkx#3517]
I cannot import the LFR_benchmark

`from networkx.generators.community import LFR_benchmark_graph`

The code is no longer contained in the site-packages/networkx/generators/community.py file.

Could someone help where can I find the LFR benchmark code?

**Comment by dschult** [comment]
It is accessible from ```nx.LFR_benchmark_graph```
The code is in networkx/generators/community.py
Do you have the right version of NetworkX installed?

**Comment by agosztolai** [comment]
I am not sure. I seem to have networkx-2.2, not I upgraded to 2.3 and still have the same problem. 

AttributeError: module 'networkx' has no attribute ‘LFR_benchmark_graph'

Is this the correct version?

**Comment by dschult** [comment]
I looked at the history of this function ( #3411 ) and it used to be in 
networkx/algorithms/community/community_generators.py
Try importing it as:
import networkx.community.LFR_benchmark_graph
or perhaps
from networkx.community import LFR_benchmark_graph

As of #3411 (this past Spring) it is housed in 
networkx/generators/community.py
and it is accessible as nx.LFR_benchmark_graph
