### ISSUE TITLE
Minimum weight perfect bipartite matching

### ISSUE THREAD

**Issue by fuglede** [networkx/networkx#3520]
I'm wondering if there would be appetite for an algorithm to solve the problem of finding minimum weight perfect bipartite matchings in bipartite graphs: Let *G* = ((*U*, *V*), *E*) be a weighted bipartite graph. We then want to find a perfect matching, i.e. one of cardinality min(|*U*|, |*V*|), so that the sum over all weights in the matching is minimal. This is also known as the [linear assignment problem](https://en.wikipedia.org/wiki/Assignment_problem).

There are algorithms for solving several related problems in NetworkX already, but I didn't seem to be able to find one specialized to this problem. Some related algorithms are the following:

* The linear assignment problem is a special case of a minimum cost flow problem, obtained by adding a source incident to all vertices in *U* and a sink incident to all vertices in *V*, and letting the demand for these two vertices be min(|*U*|, |*V*|) with appropriate signs. This could then be solved using `networkx.algorithms.flow.min_cost_flow`. A specialized algorithm would take advantage of the bipartite structure to improve performance. Moreover, as far as I can tell, `min_cost_flow` assumes that all weights are integral, which we wouldn't have to here.
* On the other hand, `networkx.algorithms.bipartite.maximum_matching` can detect if a feasible solution exists, i.e. a matching with the desired cardinality, but it doesn't take into account the weights.
* `networkx.algorithms.matching.max_weight_matching` takes weights into account but operates on arbitrary graphs and does not require that the matching be perfect in the bipartite case.

A large number of different algorithms exist to solve the problem. Assuming that the inclusion of an algorithm is relevant, the first thing I'm wondering is the following: SciPy already has an efficient implementation of an algorithm to solve the problem in [`scipy.optimize.linear_sum_assignment`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.linear_sum_assignment.html), and since NetworkX already depends on SciPy, it would be only a few lines of code to simply make use of the SciPy implementation. However, as NetworkX is generally focused on bundling Python implementations of its algorithms, simply making use of the SciPy implementation might be going against the spirit of the library, and it would be preferable to include a Python version of one of the algorithms instead?

**Comment by Pascal-Ortiz** [comment]
In some cases, NetworkX provides his own Python implementation **and** a Numpy based implementation. For instance, this occurs for the Floyd-Warshall algorithm with a very efficient implementation (see timings below).


By the way, another very interesting option is Numba + Numpy I'm experimenting for the moment: it provides sometimes still faster execution than  C++. Some  Floyd-Warshall  algorithm timings (in seconds) for a graph with parameters n=800, m=100000:

```
Networkx                        : 82.66 
Python (no dict)                : 34.58
Python 
(no dict and multiprocessing)   : 21
Numpy from Networkx             : 1.67 (no predecessors calculation) 
Numba-Numpy-nx                  : 1.33
Graph-tool                      : 0.91 
Numba-Numpy-nx-paral            : 0.5
Scipy (Cython)                  : 0.50 
Simple C/C++ code               : 0.40 
Numba opt-lignes                : 0.37
C++                             : 0.30
Numba                           : 0.24
C++ threads                     : 0.14
Numba parallel                  : 0.11
C++ openMP                      : 0.09
```

I tried Numba under GPU but didn't get nice results (I'm new to GPU programming).

**Comment by dschult** [comment]
In an ideal world we would have a scipy and base python implementation of each algorithm, but it is certainly fine to just implement a scipy version. The vast majority of our users have scipy available. Those that don't would not be able to use the function. We could leave it at that, or implement a python version. But since you suggest the Scipy version would be very straightforward I think it is reasonable to start with that and add a pure python version if you think it would be helpful.

**Comment by fuglede** [comment]
Thanks. The algorithms generally aren't particularly complicated, but if I were to do it, I would probably just port what's already in SciPy. I think it's hard to tell how helpful that would be. I definitely understand the value in pure-Python implementations. You know the user base best.

And yes, it would be straightforward to adopt the SciPy version; really it amounts to the following:

```python
from scipy.optimize import linear_sum_assignment

def minimum_weight_perfect_matching(G):
    left, right = nx.bipartite.sets(G)
    # Ensure that the graph is complete and that the two node sets contain the same
    # number of rows. This is currently a requirement in the underlying optimization
    # algorithm from SciPy, but the constraint will be removed in SciPy 1.4.0, at which
    # point it may also be removed here.
    if len(left) != len(right):
        raise ValueError('The two node sets in the bipartite graph must have equal cardinality.')
    if len(G.edges()) != len(left)*len(right):
        raise ValueError('The bipartite graph must be complete.')
    U = list(left)
    V = list(right)
    weights = nx.bipartite.biadjacency_matrix(G, row_order=U, column_order=V).toarray()
    assignment = linear_sum_assignment(weights)[1]
    return {U[v]: V[assignment[v]] for v in range(len(U))}
```

One downside is, as mentioned in the comment, that the requirement of equal cardinality and completeness will only be lifted in the upcoming version of SciPy.

Anyway, I'm happy to provide a PR if you think this would be useful.

**Comment by dschult** [comment]
Yes, I think this would be useful. You should add the function, some simple unit-tests and/or smoke tests and a link in the doc/reference files. You might want to look at another module that uses scipy to see how we arrange the testing so the tests get skipped if scipy is not present.
Thanks!

**Comment by fuglede** [comment]
Thanks for the kick start; I'll look into it and hunt for inspiration in the existing modules. Do you have a favorite example of a module that does things just right?

**Comment by dschult** [comment]
```networkx/algorithms/bipartitie/spectral.py``` has the code that handles imports well for testing.
