### ISSUE TITLE
Center(s), centroid(s) of a tree

### ISSUE THREAD

**Issue by Pascal-Ortiz** [networkx/networkx#3525]
NetworkX has a function to find the [center](https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.distance_measures.center.html?highlight=center#networkx.algorithms.distance_measures.center) of a graph. This function has quadratic complexity. The case where the graph is a tree is a special case where it is known that there exists a [linear algorithm](http://www.cs.kent.edu/~dragan/ST/papers/HEDETNIEMI-COCKAYNE-HEDETNIEMIR-83.pdf). AFAIK, NetworX doesn't provide a tree-dedicated function. Do you think this algorithm could be useful to add? In the same vein, could be useful to provide a function to compute the centroid(s) of a tree.

**Comment by dschult** [comment]
There are a number of tree algorithms placed in the files ```networkx/algorithms/tree``` and these algorithms could be placed there. It looks like you would need to implement a new data structure -- at least if you were going to match the linear time dependence stated in the paper.  There is an alternate data structure to represent threshold graphs in ```threshold.py```. I don't see any reason to exclude these.
