### ISSUE TITLE
Troubles importing shapefiles and working with them

### ISSUE THREAD

**Issue by M-nes** [networkx/networkx#3530]
Hello,

## Context
I am currently working on a project for which I need to import a road network in .shp format and then calculate the shortest path between two points of my domain. 
I first started working with osmnx where I got my domain edges and nodes and followed the tutorial that was given here : https://automating-gis-processes.github.io/2018/notebooks/L6/network-analysis.html

However, it troubles me to have to download the network each time I run my script (which will be used frequently) so instead, I saved the edges.shp and nodes.shp and would like to work with them using networkx.

## Problem
Someone posted their method on importing their shapefiles here : https://gis.stackexchange.com/questions/227909/from-shapefile-to-python-networkx

I first tried that script on a small portion of my domain and it worked wonderfully. I had my nodes and edges where they should have been.
I then tried it on a bigger part of the domain and an error was found.

<details open><summary><code>Script I used</code></summary><p>

```
G   = nx.read_shp('/Users/im/Desktop/temp/test_map.shp')  #Importing the edges.shp
pos = {k: v for k,v in enumerate(G.nodes())}

X = nx.Graph() #Empty graph
X.add_nodes_from(pos.keys()) #Add nodes preserving coordinates
l = [set(x) for x in G.edges()] #To speed things up in case of large objects
edg = [tuple(k for k,v in pos.items() if v in sl) for sl in l] #Map the G.edges start and endpoints onto pos
    
fig, ax = plt.subplots(figsize=(15,10))

nx.draw_networkx_nodes(X, pos, node_size=50, node_color='skyblue')
X.add_edges_from(edg)
nx.draw_networkx_edges(X, pos)
#plt.xlim(2.4625, 2.4765)
#plt.ylim(48.775, 48.7817)
plt.xlabel('X [m]')
plt.ylabel('Y [m]')
plt.title('From shapefiles to NetworkX')
```
</p></details>

### And this is the error I get
<details><summary><code>Error message</code></summary><p>

```
NetworkXError                             Traceback (most recent call last)
<ipython-input-10-8e4cfd733afa> in <module>
      1 fig, ax = plt.subplots(figsize=(15,10))
      2 nx.draw_networkx_nodes(X, pos, node_size=50, node_color='skyblue')
----> 3 X.add_edges_from(edge)
      4 nx.draw_networkx_edges(X, pos, edge_color='b')
      5 

~/anaconda3/lib/python3.6/site-packages/networkx/classes/graph.py in add_edges_from(self, ebunch_to_add, **attr)
    967             else:
    968                 raise NetworkXError(
--> 969                     "Edge tuple %s must be a 2-tuple or 3-tuple." % (e,))
    970             if u not in self._node:
    971                 self._adj[u] = self.adjlist_inner_dict_factory()

NetworkXError: Edge tuple (35,) must be a 2-tuple or 3-tuple.
```
</p></details>

From what I understand, the edg variable must be a tuple of (x,y) coordinates basically. For some reasons, some nodes are either in the (x,) format or in the ((x,y),) format, which does not allow the script to run. I put in the box bellow the part that arises the error when I print edg.

<details><summary><code>print(edg)</code></summary><p>

```
[ ...
(33, 292),
 (33, 293),
 (31, 34),
 (34, 380),
 (2, 35),
 (35,),
 (2, 36),
 (37, 38),
 (38, 41),
 (38, 43),
 (37, 39),
 (39, 200),
... ]
```
</p></details>

I don't understand what the origin of the problem is and how to fix it. I really just want to import my shapefiles and get the shortest path between two nodes...
I am not very experimented with python and english is not my native language so I'm sure my problem is not explained very well but I would very much appreciate any help that could be given to me. 

## Edit

I checked every variables used and found out that the "l" one might be the problem.
Each edges gets two sets of coordinates which are the start and end of the edge but some only have one set.

<details><summary><code>print(l)</code></summary><p>

```
[ ...
 {(2.455183, 48.7774425), (2.455329, 48.7774934)},
 {(2.4553081, 48.7776195), (2.455329, 48.7774934)},
 {(2.455329, 48.7774934), (2.4576711, 48.7775673)},
 {(2.455183, 48.7774425), (2.4551873, 48.7776523)},
 {(2.454872, 48.7820323), (2.4551873, 48.7776523)},
 {(2.4574735, 48.7736999), (2.4577528, 48.7738954)},
 {(2.4574735, 48.7736999)},
 {(2.4577528, 48.7738954), (2.4578287, 48.7723847)},
 {(2.4586793, 48.7825114), (2.4595176, 48.7825368)},
 {(2.4585674, 48.7823935), (2.4586793, 48.7825114)},
 {(2.4583212, 48.7825048), (2.4586793, 48.7825114)},
 {(2.4595176, 48.7825368), (2.4596865, 48.7825375)},
 {(2.4596865, 48.7825375), (2.45971, 48.7826767)},
 ... ]
```
</p></details>

What does it mean for an edge to only have one set of coordinates? Isn't that supposed to be just a node? Is there a way I can 'fill' the missing set by duplicating the first set, so instead of having something like this:

```
 {(2.4574735, 48.7736999)},
```

I'd have something more like this which, I think, might get my code to run:

```
 {(2.4574735, 48.7736999), (2.4574735, 48.7736999)},
```

Thank you in advance for taking time to read all that.

**Comment by dschult** [comment]
The problem is your line:

    l = [set(x) for x in G.edges()] 

This is no longer a list of edges. If an edge is a self-loop it looks like (35, 35) but after set(x) it looks like {35} and in the next line you form a tuple with it so it look like (35,)
The G.edges() is going to iterate to 2-tuples so you don't have to worry about long tuples "x".
Form the edges something like this (untested):

    node_at_pos = {v: k for k,v in enumerate(G.nodes())}
    edges = [(node_at_pos[u], node_at_pos[v]) for u,v in G.edges()]  
    # or use ( ) instead of [ ] for speed
    # edges = ((node_at_pos[u], node_at_pos[v]) for u,v in G.edges())  
    ...
    X.add_edges_from(edges)

**Comment by M-nes** [comment]
I will give it a try thank you very much.
