### ISSUE TITLE
Shortest_path appear to select routes that are not really the shortest

### ISSUE THREAD

**Issue by jeremysze** [networkx/networkx#3533]
I am using the shortest_path api with [NYC's LION Single Line Street Base Map](https://www1.nyc.gov/site/planning/data-maps/open-data/dwn-lion.page) to find the shortest distance between two nodes. 

I have [cleaned](https://nbviewer.jupyter.org/github/jeremysze/GIS_exploration/blob/master/code/networkdistance_lion.ipynb) up the file so that non-pedestrians accessible routes are not included. 

In this [example](https://nbviewer.jupyter.org/github/jeremysze/GIS_exploration/blob/master/code/networkdistance_lion.ipynb), the shortest_path api worked fine. And so I used this as a template to calculate the shortest_path for a much larger set of nodes. 

However, when I was comparing the distances that I've calculated vs. the distance that was calculated by my colleague using ArcGIS, I found large differences in some of the measurements. Even though, we both used the same clean lion line file. 

Digging deeper to see why we were getting such huge differences, I found some routes that appeared to be taking a longer route than necessary. 

I pulled out a [sample case](https://nbviewer.jupyter.org/github/jeremysze/GIS_exploration/blob/master/code/networkdistance_lion-issues.ipynb) to illustrate this. 

This is my first time using networkx. Perhaps, I could missed something that was absolutely important in order to calculate the network distance correctly. Thank you!

**Comment by jeremysze** [comment]
Figured it out. Turns out I should have specified distance as the weights in the function.

**Comment by jeremysze** [comment]
After running the networkx shortest_path api with the distance weights specified, there are still some routes that appear to be taking a longer route than necessary. Please see this [sample case](https://nbviewer.jupyter.org/github/jeremysze/GIS_exploration/blob/master/code/networkdistance_lion-issues2.ipynb). 

Thank you!

**Comment by dschult** [comment]
Be careful...  It's not a sure thing that the nodes will be in the same order when you relabel as integers. So, you created a mapping from node integers to positions, but it may not be correct.
To do this more carefully, try something like:

    G = nx.convert_node_labels_to_integers(G, first_label=0, label_attribute='pos')
    pos = nx.get_node_attributes(G, 'pos')
    node_df = pd.DataFrame(pos.items(), columns=['node_id', 'geometry'])

**Comment by jeremysze** [comment]
I just tried your suggestion. But I still get back the same routes as before. I also calculated a distance attribute in an earlier step, and use that attribute as the weight, but it [did not change things](https://nbviewer.jupyter.org/github/jeremysze/GIS_exploration/blob/master/code/networkdistance_lion-issues2.ipynb).

**Comment by dschult** [comment]
You've got way more code in there than I can parse easily. 
Can you compute the length of the path using the weights you specified?
Can you compare that length to another path you think is shorter?

**Comment by jeremysze** [comment]
Sorry, I've cleaned up the notebook so that it is more organized. I've computed the lengths as well. Please see [notebook](https://nbviewer.jupyter.org/github/jeremysze/GIS_exploration/blob/master/code/networkdistance_lion-issues2.ipynb).

**Comment by jeremysze** [comment]
The one thing that I noticed was that the shorter route passes through a lot of nodes compared to the route selected by networkx.shortest_path. Do you think that could be the issue?

**Comment by jeremysze** [comment]
Is there anyone here who can help me with this? I'm really reluctant to go the ArcGIS route.

**Comment by dschult** [comment]
Can you compute the length of the path using the weights you specified?
Can you compare that length to another path you think is shorter?

The number of edges in the path should not matter so long as you have successfully chosen an attribute for the edge weights.

**Comment by jeremysze** [comment]
I did compute the length using the weights. Using the routes I specified I got the distance 0.005815, and with the networkx route I got the distance of 0.010277.

**Comment by dschult** [comment]
It's hard for me to tell exactly, but I think you are computing the distance of these paths using distances as calculated from LineString?  Can you compute the length as NetworkX sees it.  That is, see if NetworkX agrees that the length of the route you specify is shorter. Most likely, the values you think are being used are not the ones actually being used. We need to check both ways of storing the network to make sure they agree. 

    # find length of path "pathnodes"
    distance = 0
    for n,nbr in nx.utils.pairwise(pathnodes):
        distance += G[n][nbr]['distance']


Actually -- I just realized that you don't define 'distance' as an attribute on the NetworkX graph. Am I correct?  If so, when you use it for "shortest_path" it will not find the attribute and substitute the value 1 for each edge.  Essentially that means you aren't doing a weighted path. 

Can you check that you actually define the length of each edge in the attribute that you use for the shortest_path calculation?

**Comment by jeremysze** [comment]
I got the distance of `0.0122... ` for the networkx specified route and ` 0.0573...` for the manually created route. You are right that networkx sees its route as shorter. I think I have distance as an attribute because when i run `list(G.edges(data=True))[0]` to examine my attributes. I see `distance` inside the attribute dictionary. 

`distance` of each edge was created when I was creating the shapefile.

**Comment by dschult** [comment]
Hmmmmm....  interesting. It sounds like "distance" may be a different value than LineString's "length".  I'm glad to hear that NetworkX is finding the shortest route based on how it understands distance. But it means you will have to do some digging to figure out which measure of path length is better for your application.

**Comment by jeremysze** [comment]
Thank you for helping me out! I noticed that with `nx.read_shp` there is an option to `simplify`. I've set that to False thinking that I just want networkx to read my shapefile as is. But perhaps that might be causing some repetitions in the attributes.  

> simplify (bool) – If True, simplify line geometries to start and end coordinates. If False, and line feature geometry has multiple segments, the non-geometric attributes for that feature will be repeated for each edge comprising that feature.
