### ISSUE TITLE
Problem with nx.from_nested_tuple()

### ISSUE THREAD

**Issue by ch728** [networkx/networkx#3541]
When I trying reading in a nested tuple into a tree as follows:

nx.from_nested_tuple((((('9502008-A', 'DREW'), ('CFX 26', 'WELLS')), ('CPRS', ('CFX 29', ('AR 1142', 'LA 2031')))), 'CL 161')) 

I get  RecursionError: maximum recursion depth exceeded while calling a Python object

Is there something wrong with my input tuple that would be causing this?

**Comment by jfinkels** [comment]
Hi @ch728. The `from_nested_tuple()` function doesn't allow providing node labels (or other data) within the tuple. It only allows tuples whose elements are other tuples, like `((), ())` for the balanced binary tree of depth one, or `(((), ), )` for the path graph on three nodes. For example usage, see here https://github.com/networkx/networkx/blob/ec36a0e10a455bc7ca1a3d27b9d52ac6bb4c4df4/networkx/algorithms/tree/coding.py#L177-L178

You may need to adapt the code in the `from_nested_tuple()` function to allow providing specific labels for nodes in the tree.

**Comment by ch728** [comment]
Ah, okay, I see.  Thanks!
