### ISSUE TITLE
zerodivisionerror by rich_club_coefficient 

### ISSUE THREAD

**Issue by ggrrll** [networkx/networkx#3543]
Hi, 

I just run  `rich_club_coefficient` on a WS network generated with `erdos_renyi_graph` and I get this error (no idea why)...and I was wondering if this is a bug -- or I did something wrong

Thanks

![Screenshot 2019-08-14 at 12 46 05](https://user-images.githubusercontent.com/15370425/63019127-d045ff00-be9a-11e9-9b8b-087c871a846f.png)

**Comment by dschult** [comment]
The normalized rich_club coefficient involves scaling the unnormalized rich_club coefficient by the coefficient of a graph with the same degree distribution as your graph, but with some edges swapped to randomize it. This allows comparison of the normalized value to 1 so greater than 1 means the rich_club effect exists in your network.

In your example, the rich_club coefficient is zero for some value of k, so the scaling doesn't work. You could either turn off the scaling using ```normalized=False```, or change the number of edge swaps ```Q```. 

Most likely you will just want to use the unnormalized option.  If anyone knows a correct value to set rich_club to when the normalization factor is zero, we could catch this error and replace with that value.
