### ISSUE TITLE
Bad practice for ensuring only python3.5 and up

### ISSUE THREAD

**Issue by WisdomPill** [networkx/networkx#3546]
In setup.py there's the check that python version should be equal or higher than python3.5, 
but the python_requires in the setup method should take care of it, using this

https://github.com/networkx/networkx/blob/98e0a6ebd25a0183b6a0f6375cccaf5619209b59/setup.py#L22

breaks dependencies such as scikit-image for people using python3.5 and lower.
Like I said in scikit-image/scikit-image#4094

python_requires should be used like it says here https://www.python.org/dev/peps/pep-0440/#version-specifiers

Can I make a PR for fixing this?

**Comment by dschult** [comment]
Hmmm...   With that code removed, ```python2 setup.py install``` installs networkx just fine on Python2.7 when it shouldn't. I'm not sure what you mean when you say that ```python_requires``` should take care of it.  Perhaps you should create a PR that works so we can see what you mean.

**Comment by WisdomPill** [comment]
Which version of pip are using to install it and which version of setuptools you've used to build the package?

https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires

Shows that you need to have setuptools higher that 24.0 to generate the package and pip higher than 9 to interpret the metadata

**Comment by dschult** [comment]
I think running ```python2 setup.py install``` does not involve pip.
(I have pip version 18.1 and setuptools version 39.2)

**Comment by WisdomPill** [comment]
The issue is not related to networkx at all, the explanation is on #scikit-image/scikit-image#4094
