### ISSUE TITLE
Graph attributes missing in dotfile output?

### ISSUE THREAD

**Issue by GPMueller** [networkx/networkx#3547]
If I understand attributes correctly, the graph itself should also be able to have attributes (e.g. `rankdir=BT` to invert the ordering). The only way I currently know how to add them is via the constructor:
```Python
import networkx as nx
G = nx.DiGraph(rankdir="BT")
G.add_edge("A", "B")
nx.drawing.nx_pydot.write_dot(G, 'test.dot')
```
I would expect this to give me a dotfile containing
```
strict digraph  {
rankdir=BT;
A;
B;
A -> B;
}
```

**The `rankdir=BT;` attribute is missing. Is this expected/intended behaviour or is it maybe a bug?**

*Note: I believe that `get`/`set` functions for graph attributes would be nice to have.*

--------------------------------

If I modify a single line in the `to_pydot` function:

https://github.com/networkx/networkx/blob/98e0a6ebd25a0183b6a0f6375cccaf5619209b59/networkx/drawing/nx_pydot.py#L201

to read `graph_defaults = N.graph`, then the output is expected.

**Comment by dschult** [comment]
You can get/set update all graph attributes easily using the dictionary ```G.graph```

    G.graph['rankdir']='BT'

But a look at the to_pydot code makes it clear that for pydot we use ```G.graph['graph']``` as a dictionary of default values for graph attributes. So I think you need to use

    G.graph['graph'] = dict(rankdir="BT")

Notice that a few lines down in th code from your link it sets default values for Nodes and Edges using ```G.graph['node']``` and ```G.graph['edge']```

**Comment by GPMueller** [comment]
Thanks!
This clears up how to add the attribute, as `G.graph['graph'] = dict(rankdir="BT")` worked. I would still suggest adding functions, as `G.set_attribute('rankdir', "BT")` or something similar would more clearly express intent.
*Note:* `G.graph['rankdir']='BT'` instead adds another node (at least in terms of the dotfile output).

I still don't understand what the point of the `G.graph` dict is, though. After
```Python
G = nx.DiGraph()
G.graph['graph'] = dict(rankdir="BT")
G.add_edge("A", "B")
```
the `G.graph` dict still only contains `{'graph': {'rankdir': 'BT'}}`, meaning `G.graph['edge']` is still empty.
IMO this code is a bit confusing and it seems to me like it could be tidied up, but I cannot judge what the reasoning behind it might be.

**If the developers believe that no `set_attribute` (or similar) function should be added and that `nx.drawing.nx_pydot.write_dot` works as intended, this issue can be closed**
I have my workaround ;)

**Comment by hagberg** [comment]
Any bad engineering decisions here are likely my fault.   Here is how it works.

For handling dot files in NetworkX the G.graph attribute dictionary has to take into account graph, node, and edge default scope.  For example  for a dot file (from tonyballantyne.com/graphs.html) with graph, node, and edge level defaults 

```
digraph hierarchy {

		nodesep=1.0 // increases the separation between nodes
		
		node [color=Red,fontname=Courier,shape=box] //All nodes will this shape and colour
		edge [color=Blue, style=dashed] //All the lines look like this

		Headteacher->{Deputy1 Deputy2 BusinessManager}
		Deputy1->{Teacher1 Teacher2}
		BusinessManager->ITManager
		{rank=same;ITManager Teacher1 Teacher2}  // Put them on the same level
}

```

the resulting networkx graph looks like this

```
In [1]: import networkx as nx

In [2]: G = nx.drawing.nx_pydot.read_dot('a.dot')

In [3]: G.graph
Out[3]: 
{'edge': {'color': 'Blue', 'style': 'dashed'},
 'graph': {'nodesep': '1.0'},
 'name': 'hierarchy',
 'node': {'color': 'Red', 'fontname': 'Courier', 'shape': 'box'}}
```

The graph level attributes are keyed with 'graph', node keyed with 'node', and edge keyed with 'edge'.    The attribute 'name' is just the name of the dot graph (might be empty).

**Comment by GPMueller** [comment]
Thanks for clarifying! I think I understand now -- so the `graph` dict is for the global attributes? In that case everything seems to work as intended and I would only recommend renaming the `graph` dict to `attributes`, as that might be clearer (cannot judge if it would be worth the effort though).
