### ISSUE TITLE
[Question] Implementing Temporal Networks (e.g. Timeseries)

### ISSUE THREAD

**Issue by jolespin** [networkx/networkx#3548]
Is there any documentation on using [MultiDiGraph](https://networkx.github.io/documentation/networkx-1.9.1/reference/classes.multidigraph.html) to build [temporal networks](http://statnet.csde.washington.edu/workshops/SUNBELT/current/ndtv/ndtv_workshop.html) with a forward directing time component? 

Also, do any algorithms apply to temporal networks in networkx?

I found https://github.com/networkx/networkx/blob/master/networkx/algorithms/isomorphism/temporalisomorphvf2.py for one of the algorithms but it's not clear how this would work for multiple timepoints. 

A natural visualization for this would be the following with an option for edges to connect between timepoints.

![image](https://user-images.githubusercontent.com/9061708/63227146-6da17b80-c198-11e9-9b8d-df69ac970c96.png)

**Comment by dschult** [comment]
It seems that temporal networks have so many different approaches that it's hard to settle on a single approach.  We do indeed have a temporal-isomorph checker code that you have already found. I am not aware of other temporal network algorithms that have been explored sufficiently to have a body of literature--but they could be out there and we'd love a pull request or even just a pointer to such algorithms. 

That said, many features of temporal networks can easily be implemented in NetworkX using the base classes through edge attributes that store the time of interaction (for example). Nodes can similarly store information about time in their attributes.

**Comment by jolespin** [comment]
I'll definitely try to find some resources to post here.  Do you know of any other packages that build on top of networkx that try to address this domain (e.g. temporal networks)?

**Comment by dschult** [comment]
I don't know of any others. But other people might... Anyone?

**Comment by MridulS** [comment]
There are a bunch of other packages for temporal networks.

https://github.com/IngoScholtes/pyTempNets

https://github.com/benmaier/tacoma/

Haven’t used them a lot.

As already suggested I usually put in a time attribute in edges to make a
networkx graph a temporal graph, it works for majority of cases.

**Comment by jolespin** [comment]
I've also found this package: https://teneto.readthedocs.io/en/latest/teneto.networkmeasures.html

![image](https://user-images.githubusercontent.com/9061708/63291090-bc721280-c277-11e9-84ab-1fcf700c2eab.png)


I'm always very skeptical about using network packages in Python that are not at least built on networkx.

**Comment by dschult** [comment]
I'm going to close this issue as people will still be able to find it searching for temporal networks. If/when the field settles down a little we can revisit algorithms and data structures to add.

**Comment by boothby** [comment]
Gabriel Kissin contacted me privately and mentioned the R packages tsna (Temporal Social Network Analysis) and ndtv (Network Dynamic Temporal Visualization)

**Comment by Gabriel-Kissin** [comment]
> Gabriel Kissin contacted me privately and mentioned the R packages tsna (Temporal Social Network Analysis) and ndtv (Network Dynamic Temporal Visualization)

Just came across this, thanks Kelly @boothby for locating this discussion and adding my two cents! 

In connection to what the OP brought up about a natural way to _visualise_ changes in a network over multiple phases, I had to do this a bit in July. In case helpful to anyone else who comes across this page, IIRC I used the following approach: Imagine that all the phases are one long phase, and all nodes and edges belong in that one phase. This "combined phase" can then be visualised by merging the graphs from all the phases into one graph, and using standard visualisation methods (I found `nx.nx_agraph.pygraphviz_layout` and `nx.kamada_kawai_layout` worked well for me). So those methods will find a good layout for all the nodes in the "combined phase". Once that is done, the same layout can be used for the nodes in each separate phase, i.e. in every phase all the nodes will be in the position they are assigned in the "combined phase".  

The advantage of this over simply visualising each phase as a new network, is that all nodes will now always be located in the same position. This makes visual identification of any changes far easier!

Another tip I found helpful was to output the visualisations for each of the phases as separate pages of one pdf. The pdf can then be opened (optionally set to full screen) and displayed with "Single Page View", so the mouse wheel etc doesn't scroll, but jumps pages. That way you can easily jump from one graph to the next and easily see what has changed. The last page of the pdf can be the combined graph with nodes from all phases. I'll upload a couple of examples of this, one using just a small subset of the network I was working with, the second using the entire network.

This won't help for the OP's request for "an option for edges to connect between timepoints", but for cases where phases are distinct then for primitive comparison between phases I found this was a very simple but very helpful approach. 

[3 neighbourhood of node6 in all phases.pdf](https://github.com/networkx/networkx/files/10252517/3.neighbourhood.of.node6.in.all.phases.pdf)
[3 ALL nodes in all phases.pdf](https://github.com/networkx/networkx/files/10252520/3.ALL.nodes.in.all.phases.pdf)

**Comment by jolespin** [comment]
I've been developing this on top of networkx:

https://github.com/jolespin/soothsayer/blob/cd202396d0bdaf6f6ee0a4d3b841661bba46a4a6/soothsayer/networks/networks.py#L1309
