### ISSUE TITLE
Katz centrality is not being initialized correctly. Especially problematic if beta=0.

### ISSUE THREAD

**Issue by ogreen** [networkx/networkx#3549]
By default the array X is set to value zero in Line 157:
https://github.com/networkx/networkx/blob/master/networkx/algorithms/centrality/katz.py#L157

Now if beta is set to zero (which is a valid value for Katz, especially if a closer estimation to the actual Katz score is desirable), then the following computation in Line 176 and Line 178 results in all zeros:
https://github.com/networkx/networkx/blob/master/networkx/algorithms/centrality/katz.py#L176.

There are two viable solutions for overcoming this problem. Both involve updating:
 x = dict([(n, 0) for n in G])
to either:
 x = dict([(n, beta) for n in G])
or
 x = dict([(n, 1.0) for n in G])

**Comment by dschult** [comment]
If you are computing a closer estimation, wouldn't you specify the X array? Then it is not zero.
Also, if beta is set to zero then your first solution is the same as the existing result. The second solution will change the result from a Katz centrality to something new.

**Comment by ogreen** [comment]
I agree that my first solution is the same if beta is zero. But if beta is not zero than the result is different. 
I personally prefer my second solution as it sets the number of paths each vertex has to itself (in a 0-hop traversal) to be 1.

**Comment by dschult** [comment]
Well -- we don't get to call it Katz centrality if it is something different whatever your personal preference is. What is Katz Centrality?

**Comment by ogreen** [comment]
This isn't an issue of preference: Katz centrality doesn't actually define beta.
https://en.wikipedia.org/wiki/Katz_centrality

The introduction of beta seems to be an artifact of the current implementation as beta is used to help to converge. Convergence is done to avoid matrix inverse operation which is computationally more expensive.

**Comment by dschult** [comment]
Hmmmm.... That doesn't agree with the NetworkX docs, nor the Newman book cited in the doc_string. It looks like the Wikipedia version sets beta=0, though I'm not sure.
In that reference, beta plays a role in reducing the problem (in eigenvector centrality) of nodes with zero in-degree contributing nothing to the centrality of the nodes they connect to. In that description, it is clear that beta is not just for convergence. It impacts the final value fairly strongly in some cases.  It would be great to connect the Wikipedia definition to Newman's definition and find out which (or both) are related to Katz's version. :}

Is it true that starting with 0 will lead to "beta" on the next iteration?

In any case, it is good that beta is available as an input so it can be changed.

**Comment by ogreen** [comment]
I am less familiar with the formulation given by Newman, however in my experience with Katz centrality I have not seen beta in the equation. 
Beta is not "visible" in the original paper: http://www.cse.cuhk.edu.hk/~cslui/CMSC5734/katz-1953.pdf. 
From my understanding, beta is very useful to the power-convergence method in getting faster convergence. Given that alpha is typically very small for large networks(millions of vertices and onwards), beta is probably playing a very significant role especially.

Btw, the approach in NetworkX is close to the one suggested by Foster et al:
https://www.researchgate.net/profile/John_Potterat/publication/220556936_A_Faster_Katz_Status_Score_Algorithm/links/55ea60e708ae3e1218450c6a.pdf

**Comment by dschult** [comment]
If someone finds a good citation for good choices of initial values when computing Katz Centrality, we welcome that as an improvement. I'm going to close this issue, at least for now.
