### ISSUE TITLE
[Typo][Doctring][graph.py][get_edge_data()]

### ISSUE THREAD

**Issue by sara-02** [networkx/networkx#3550]
The doc string of the `get_edge_details` fucntion of `graphy.py` seems to have a minor typo.
```
    def get_edge_data(self, u, v, default=None):
        """Returns the attribute dictionary associated with edge (u, v).
        This is identical to `G[u][v]` except the default is returned
        instead of an exception is the edge doesn't exist.
```
 **is** `the edge doesn't exist.` should be **if** `the edge doesn't exist.`
Line: https://github.com/networkx/networkx/blob/master/networkx/classes/graph.py#L1331

**Comment by dschult** [comment]
Thanks!
