### ISSUE TITLE
draw_networkx_nodes: Error doesn't show my mistakes exactly.

### ISSUE THREAD

**Issue by Shumpei-Kikuta** [networkx/networkx#3552]
Hi, 

I passed nodelist to draw_networkx_nodes method as it needs.
But if I set nodelist as ndarray in numpy, it shows the following error.

```
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

The nodelist I passed is like as follows.

```
a = np.array([1, 2, 3, 4, 5)]
nx.draw_networkx_nodes(G, pos=pos, nodelist=a)
```
I'm sure G has each node in a, and pos is exactly what it needs.

I managed to solve this problem by transforming ndarray to list like this.

```
a = np.array([1, 2, 3, 4, 5)]
nx.draw_networkx_nodes(G, pos=pos, nodelist=a.tolist())
```

I believe that error confuses us, so we should either allow to pass ndarray or show a more accurate error.

Thank you for your consideration.

**Comment by dschult** [comment]
This looks like a bug. Thanks for the report!

Line 392 of ```nx_pylab.py``` should be changed from

    if not nodelist or len(nodelist) == 0: 
    # to something similar to this (untested)
    if len(nodelist) == 0 or not nodelist: 

Your workaround works in the meantime.
