### ISSUE TITLE
`style` doesn't work for directed graphs

### ISSUE THREAD

**Issue by jolespin** [networkx/networkx#3553]
There's no use of the `style` argument.  I ended up adding `linestyle=style` and it worked for the `FancyArrowPatch`

            arrow = FancyArrowPatch((x1, y1), (x2, y2),
                                    arrowstyle=arrowstyle,
                                    shrinkA=shrink_source,
                                    shrinkB=shrink_target,
                                    mutation_scale=mutation_scale,
                                    color=arrow_color,
                                    linewidth=line_width,
                                    connectionstyle=connectionstyle,
                                    zorder=1)  # arrows go behind nodes

Here's a screenshot of using the function:
![image](https://user-images.githubusercontent.com/9061708/63396793-2e804f80-c37d-11e9-9e12-f919aaa033e5.png)

**Comment by dschult** [comment]
FancyArrowPatch doesn't accept a ```style``` argument. 
Any ideas for how to make this work?

**Comment by jolespin** [comment]
It can accept a linestyle argument.  I added it to my Networkx installation and it worked.

**Comment by dschult** [comment]
FancyArrowPatch doesn't have a ```style``` argument, but it does have a ```linestyle``` argument. Looks like ```linestyle=style``` is reasonable. Does the LineCollection style and the FancyArrowPatch linestyle accept the same values? If not, we had better document the style argument carefully. I guess we should do that in any case. :)

Thanks!

**Comment by jolespin** [comment]
I'm not sure b/c I haven't used the FancyArrowPatch outside of networkx before.   I think it does take the same arguments.  I've tried `"-", ":", "--", and "-."` which all worked!

**Comment by dschult** [comment]
According to the docs for [LineCollection](https://matplotlib.org/3.1.1/api/collections_api.html#matplotlib.collections.LineCollection) and for [FancyArrowPatch](https://matplotlib.org/3.1.1/api/_as_gen/matplotlib.patches.FancyArrowPatch.html)

FancyArrowPatch linestyle allows {'-', '--', '-.', ':', '', (offset, on-off-seq), ...}.
LineCollection linestyles allows [ 'solid' | 'dashed' | 'dashdot' | 'dotted' ], or a dash-tuple (offset, on-off-seq).

So, we'll have to adjust the docs carefully.

**Comment by jolespin** [comment]
I just tried giving FancyArrowPatch linestyle="dashed", "dotted", and "solid" which all worked.  It looks like they can handle alias terms like ":", "-", etc. too.

**Comment by fairliereese** [comment]
Will this be implemented in later releases?

**Comment by dschult** [comment]
I believe this was closed mistakenly by PR #3554 due to a typo on my part.
I apologize. I have reopened the issue and hope it can be fixed for NetworkX 2.5

We need to add "linestyle=style" to the fancyarrowpatch call (similar to the LineCollection call).
Then we need to expand the docs to tell people what is available for the linestyle (or refer to matplotlib docs).

Thanks for the nudge. :)

**Comment by dschult** [comment]
Fixed in #3747
