### ISSUE TITLE
Deprication Warning while running nx.draw_networkx

### ISSUE THREAD

**Issue by sara-02** [networkx/networkx#3556]
`nx.draw_networkx(g)`
```
python3.6/site-packages/networkx/drawing/nx_pylab.py:579: MatplotlibDeprecationWarning: 
The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
  if not cb.iterable(width):
```
Hoping this is being tracked :)

**Comment by dschult** [comment]
I'm hoping #3458 is taking care of all these iterable warnings.
Are you seeing the warning with NetworkX 2.3 or with the github repository (dev version)?
Thanks!

**Comment by sara-02** [comment]
pip installed networkx 2.3, python 3

**Comment by dschult** [comment]
Yes -- good.  Then #3458 should take care of the problem.
Thanks!
