### ISSUE TITLE
 ParseError when creating documentation with sphinx and numpydoc

### ISSUE THREAD

**Issue by Micromegass** [networkx/networkx#3560]
Using sphinx and numpydoc to document code the following an error is thrown, leading back to ```nx.Graph``` which custom class inherits: 

```
 File "/Users/micromegas/anaconda3/envs/sphinx/lib/python3.7/site-packages/numpydoc/docscrape.py", line 330, in _parse_see_also
    raise ParseError("%s is not a item name" % line)
numpydoc.docscrape.ParseError: order, __len__  which are identical is not a item name in 'Returns the number of nodes in the graph.\n\nReturns\n-------\nnnodes : int\n    The number of nodes in the graph.\n\nSee Also\n--------\norder, __len__  which are identical\n\nExamples\n--------\n>>> G = nx.path_graph(3)  # or DiGraph, MultiGraph, MultiDiGraph, etc\n>>> len(G)\n3'
```
When inheriting from ```object``` instead of ```nx.Graph``` error is not thrown.  

Workaround: Using  ```sphinx.ext.napoleon``` instead of ```numpydoc``` solves this.

**Comment by dschult** [comment]
Yes. NetworkX uses  ```sphinx.ext.napoleon``` instead of ```numpydoc```.
I'm not sure if there is a way to use either, but it sounds like a maintenance nightmare. 
I'm going to close this, but if you know an easy way to support either napoleon or numpydoc add another comment.
