### ISSUE TITLE
`from_pandas_edgelist` creates empty graph if there are no attributes

### ISSUE THREAD

**Issue by jtpdowns** [networkx/networkx#3562]
Using `from_pandas_edgelist` with `edge_attr=True` results in an empty graph if there are no attribute columns. If a user passes in a dataframe which _may_ contain attribute columns, it will yield an empty graph if there are no non-source/target columns.

**Comment by dschult** [comment]
That doesn't sound good.... Do you have a short piece of code that shows  the problem?
Thanks!

**Comment by jtpdowns** [comment]
Thanks for your response! Here's a snippet that illustrates the issue.
```
import networkx as nx
import pandas as pd
edgeframe = pd.DataFrame([
        {"src": 0, "tgt": 1},
        {"src": 1, "tgt": 2},
        {"src": 2, "tgt": 0}])
graph = nx.from_pandas_edgelist(edgeframe, source="src", target="tgt", edge_attr=True)
print(graph.order()) # 0
print(graph.size()) # 0
edgeframe["weight"] = 0
graph = nx.from_pandas_edgelist(edgeframe, source="src", target="tgt", edge_attr=True)
print(graph.order()) # 3
print(graph.size()) # 3
```

**Comment by dschult** [comment]
Good -- thanks for that code. It is clear that near line 325 the code presumes that the dataframe has a column that is not indicating source or target. And if that column doesn't exist it will cause the ```zip()``` function later on to terminate before any edges are added.

This is a bug and should be easy to fix.  What do you suggest for the behavior if no ```edge_attr``` columns exist? Should we just raise an exception? That might be cleanest...
