### ISSUE TITLE
Set attributes as a dict like

### ISSUE THREAD

**Issue by CJ-Wright** [networkx/networkx#3563]
Would it be possible to set the attributes of a node to be a dict like? I have a dict which is backed by JSON so when it is updated it updates its associated file and when serialized only writes out the path to that file making the resulting files smaller and more readable. I would like to set node attributes to this class. Is that possible?

**Comment by dschult** [comment]
Node attributes are stored in an attribute dict (e.g. ```G.nodes```) that is intended to be keyed by the attribute name to an arbitrary python object as the value. So something like this should work:

    G.nodes[node]['json_info'] = json_dict_like_object
    # or... if the node has not been added
    G.add_node(node, json_info=json_dict)

**Comment by CJ-Wright** [comment]
I was thinking about that approach, but I have gotten used to having all the keys at the top level. Is that possible?

**Comment by dschult** [comment]
Interesting.... what do you mean by the top level. Can you give an example?

**Comment by CJ-Wright** [comment]
Currently we have
```
G = nx.path_graph(3)
G.nodes[0] = {'hi': 'world'. 0: 1}
...
```
Here the `hi` and `0` keys are at the "top level" in the attrs dict.
It would be nice to be able to keep the existing attrs structure
Encasing this inside a dict
```
payload = lazyjson({'hi': 'world'})
G.node[0] = {'payload': payload}
```
would require the API to move so that everything interacts with the `payload` key rather than the attrs itself.

**Comment by dschult** [comment]
I still don't get it... do you want to add another layer to the current dict-of-dict structure that we use for node attributes? So to access attributes use: ```G.nodes[0]['payload']['hi']```
That is completely available to do right now using code similar to what you just wrote.

**Comment by CJ-Wright** [comment]
I want to replace the node attributes dict with another dict-like so I can access 'hi' via `G.nodes[0]['hi']` rather than having to explicitly wrap the dict-like inside the attributes dictionary.

**Comment by dschult** [comment]
OK...  I think I finally understand. :) We have a mechanism for replacing the dict-like structure used for most of the Graph class data storage. In the beginning of the code for the graph class a number of dict-like factory variables are assigned values. One of them is called ```node_attr_dict_factory```. That is the one you would use to replace the node attribute dict with a node-attribute json_dict.

To make a new class with the change use something like (untested):

    lazyjson_factory = lambda : lazyjson({})
    class MyGraph(nx.Graph):
        node_attr_dict_factory = lazyjson

The ```lazyjson_factory``` function should take no arguments and return a dict-like structure. I used lambda here, but you could probably just use ```lazyjson_factory = lazyjson``` if that doesn't require an input.

If you prefer not to create a new class, but instead change one graph at a time use code like this:

    G = nx.Graph()
    G.node_attr_dict_factory = lazyjson

Hopefully we have included enough functionality that this works smoothly for you.

**Comment by CJ-Wright** [comment]
Thank you very much!
