### ISSUE TITLE
bipartite.projected_graph loses edge information

### ISSUE THREAD

**Issue by Trizali** [networkx/networkx#3571]
Hi everyone,

I have a bipartite network 'g' with nodes from set X and R. When I launch the projection to get the graph with the nodes of set R, it works perfectly. However, I lose the edge information. I would like to know how I can retrieve the edge information and add them to the R set projection graph, so in which I can have the name of the edges with the nodes of the X set.

```
## The directed bipartite graph
g = json_graph.node_link_graph(graph_data, directed=True)

## Draw the projection set R graph
g_over_r = bipartite.projected_graph(g, r_set)

pos = nx.layout.spring_layout(g_over_r)
nx.draw(g_over_r, pos=pos, edge_labels=labels_edge)
nx.draw_networkx_labels(g_over_r, pos=pos)

```

I tried add this, but does not work:
```
labels_edge = {(s,t): data['label'] for s,t, data in g.edges(data=True)}
nx.draw_networkx_labels(g_over_r, pos=pos, labels=labels_edge)

#[(n, nbrdict) for n, nbrdict in g.adjacency()]
```

Thank you in advance

**Comment by dschult** [comment]
According to [the docs for projected_graph](https://networkx.github.io/documentation/latest/reference/algorithms/generated/networkx.algorithms.bipartite.projection.projected_graph.html#networkx.algorithms.bipartite.projection.projected_graph) you can use the argument ```multigraph=True``` to create a multigraph that has each edge key being the node of the neighbor that connected them.

So something like this could work (untested):

    g_over_r_multi = nx.projected_graph(g, r_set, multigraph=True)
    g_over_r = nx.DiGraph(g_over_r_multi.edges())

    e_labels = {(u,v): list(g_over_r_multi.adj[u][v]) for u, v in g_over_r.edges()}

    pos = nx.spring_layout(g_over_r)
    nx.draw(g_over_r, pos=pos)
    edge_info = nx.draw_networkx_edge_labels(g_over_r, pos=pos, edge_labels=e_labels)

**Comment by dschult** [comment]
This issue seems to have been solved.
