### ISSUE TITLE
GEXF output does not conform to GEXF and XML Schema standards

### ISSUE THREAD

**Issue by wkschwartz** [networkx/networkx#3573]
On master (currently 0d8d93a0e43829d6020e8babf59d411af6259a6c) and Python 3.7.3, if I run the following script:

```python
import io
import networkx

g = networkx.Graph()
g.add_node(1, weight=float('inf'))
g.add_node(2, weight=float('nan'))
with io.BytesIO() as f:
	networkx.write_gexf(g, f)
	print(f.getvalue().decode())
```
I get the following output:
```xml
<?xml version='1.0' encoding='utf-8'?>
<gexf version="1.2" xmlns="http://www.gexf.net/1.2draft" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/XMLSchema-instance">
  <graph defaultedgetype="undirected" mode="static" name="">
    <attributes class="node" mode="static">
      <attribute id="0" title="weight" type="double" />
    </attributes>
    <meta>
      <creator>NetworkX 2.4rc1.dev_20190906193120</creator>
      <lastmodified>06/09/2019</lastmodified>
    </meta>
    <nodes>
      <node id="1" label="1">
        <attvalues>
          <attvalue for="0" value="inf" />
        </attvalues>
      </node>
      <node id="2" label="2">
        <attvalues>
          <attvalue for="0" value="nan" />
        </attvalues>
      </node>
    </nodes>
    <edges />
  </graph>
</gexf>
```
This contains three errors in conformance with the GEXF specification. Below is a diff showing what the output should have been.
```diff
--- is.gexf	2019-09-06 14:34:24.000000000 -0500
+++ should_be.gexf	2019-09-06 14:50:28.000000000 -0500
@@ -1,22 +1,21 @@
 <?xml version='1.0' encoding='utf-8'?>
-<gexf version="1.2" xmlns="http://www.gexf.net/1.2draft" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/XMLSchema-instance">
+<gexf version="1.2" xmlns="http://www.gexf.net/1.2draft" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.gexf.net/1.2draft http://www.gexf.net/1.2draft/gexf.xsd">
+  <meta lastmodifieddate="2019-09-06">
+    <creator>NetworkX 2.4rc1.dev_20190906193120</creator>
+  </meta>
   <graph defaultedgetype="undirected" mode="static" name="">
     <attributes class="node" mode="static">
       <attribute id="0" title="weight" type="double" />
     </attributes>
-    <meta>
-      <creator>NetworkX 2.4rc1.dev_20190906193120</creator>
-      <lastmodified>06/09/2019</lastmodified>
-    </meta>
     <nodes>
       <node id="1" label="1">
         <attvalues>
-          <attvalue for="0" value="inf" />
+          <attvalue for="0" value="INF" />
         </attvalues>
       </node>
       <node id="2" label="2">
         <attvalues>
-          <attvalue for="0" value="nan" />
+          <attvalue for="0" value="NaN" />
         </attvalues>
       </node>
     </nodes>
```
For the error in the schema location (see section 2.2 of the [GEXF primer](https://gephi.org/gexf/1.2draft/gexf-12draft-primer.pdf)), the line to blame is
https://github.com/networkx/networkx/blob/0d8d93a0e43829d6020e8babf59d411af6259a6c/networkx/readwrite/gexf.py#L246

I'm not sure where floats are converted to text, but I'm guessing that the current code relies on Python to do it. However, the [XML Schema spec](https://www.w3.org/TR/xmlschema-2/#double-lexical-representation), which the GEXF spec relies on for data type definitions, says that not-a-numbers should be spelled as `NaN`,  infinity as `INF`, and negative infinity as `-INF`.

For what it's worth, fixing the schema location issue made Gephi 0.9.2 start displaying my graphs correctly.

The GEXF primer says the `meta` tag must be declared before the `graph` tag, and that `lastmodifieddate` is an attribute, not a tag, and should contain the date in ISO (yyyy-mm-dd) format.

**Comment by Nirusu** [comment]
+1 this issue/PR. Adding lastmodified as a tag does not allow me to import the GEXF file into Cytoscape (with gexf-app). Changing it to lastmodifieddate as attribute fixed it for me.

For the time being, I just patched the function as below in my local file (~/.local/lib/python3.6/site-packages/networkx/readwrite/gexf.py) [Ubuntu 18.04 / Python 3.6.8 x64 / installed via pip3]

```
def add_meta(self, G, graph_element):
        # add meta element with creator and date
        meta_element = Element('meta', lastmodifieddate = time.strftime('%Y-%m-%d'))
        SubElement(meta_element, 'creator').text = 'NetworkX {}'.format(nx.__version__)
        graph_element.append(meta_element)`
```

Would appreciate a merge so others can profit from the fix. But yeah, for the time being I just patched it this way :man_shrugging:
