### ISSUE TITLE
Order of nodes is not preserved while adding an edge 

### ISSUE THREAD

**Issue by DeepaMahm** [networkx/networkx#3584]
While adding a new edge using G.add_edge(u,v), the order of node is changed from  (u,v) to (v,u).
An example is [here](https://stackoverflow.com/questions/57934885/how-to-stop-networkx-from-changing-the-order-of-head-and-tail-nodesu-v-to-v-u)

**Comment by dschult** [comment]
The order of edges is not preserved [in networkx.](https://networkx.github.io/documentation/stable/reference/introduction.html#networkx-basics)
This is similar (and directly related to) dictionary ordering. The order is likely to be consistent from run-to-run especially once Python 3.6 changed dict ordering. But it can change from implementation to implementation and it certainly does not depend on sorting of nodes.

**Comment by DeepaMahm** [comment]
I'm sorry, that didn't answer my question. My question is on the order in which the nodes are saved in the edge list. I'd like to explain a bit more.

```
import networkx as nx
import matplotlib.pyplot as plt
from pprint import pprint

G = nx.OrderedGraph()
head_nodes = range(0, 9)
tail_nodes = range(1, 10)
edge_ls = list(zip(head_nodes, tail_nodes))
G.add_nodes_from(range(0, 10))
G.add_edges_from(edge_ls)

head = 0
tail = 1
G.remove_edge(head, tail)
Nnodes = G.number_of_nodes()
newnodes = [head, Nnodes+1, Nnodes+2, Nnodes+3, tail] # head and tail already exists
newedges = [(x, y) for x, y in zip(newnodes[0:len(newnodes)-1], newnodes[1:len(newnodes)])]
G.add_edges_from(newedges)
I = nx.incidence_matrix(G)
pprint(I)
pprint(G.edges())
nx.draw(G, with_labels=True)
plt.show()

```
I have a graph created using the above code.

The output of using an undirected graph is:
EdgeView([(0, 11), (1, 2), (1, 13), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8), (8, 9), (11, 12), (12, 13)])

From the output, we can observe that the edge that was created using G.add_edge(13,1) is displayed as (1,13). I understand this happens because the graph is undirected.

When a directed graph (G.OrderedDiGraph)is used, the output is:
EdgeView([(0, 11), (1, 2), (2, 3), (3, 4), (4, 5), (5, 6), (6, 7), (7, 8), (8, 9), (11, 12), (12, 13), (13, 1)])

(13, 1) is as I expected the result to be.

However, I am interested to know if there is a particular way the nodes can be named so that one can avoid Networkx from reordering the nodes from (u,v) , which is the user input, to (v,u) in an undirected graph.

**Comment by dschult** [comment]
It is related to the order that the dict's store neighbors. So the answer is "no"...  An undirected graph will report the edges in an arbitrary order, no matter how they are added. 

What are you trying to do? Most likely there is a way to work around this difficulty. Perhaps 

    edges = [set(e) for e in G.edges]
