### ISSUE TITLE
Feature request - Lattice - periodic on a single axis? 

### ISSUE THREAD

**Issue by MrBenGriffin** [networkx/networkx#3586]
Could it be possible to extend the 'periodic' argument to be a dimension-sized tuple of bools, so that periods could be limited to a subset of axes? This would enable eg. frieze groups more easily....

**Comment by dschult** [comment]
I guess the logic would check if 'periodic' was True or False and if neither, then assume it is a list of length 'dim'.  It needs to be backwards compatible and not slow down the usual case too much (I don't think it will).
