### ISSUE TITLE
Release schedule for the next version (2.4)

### ISSUE THREAD

**Issue by cai-lw** [networkx/networkx#3597]
I am working on a project that needs [networkx.algorithms.bipartite.matching.minimum_weight_full_matching](https://networkx.github.io/documentation/latest/reference/algorithms/generated/networkx.algorithms.bipartite.matching.minimum_weight_full_matching.html), which is only available in the development version of NetworkX. Until this function gets into a release available on PyPI, users have to manually clone this repo and install from source to use it.

Are there any schedule about the release date of the next version?

**Comment by dschult** [comment]
The milestones list October 15 for version 2.4. I think we are on schedule for that. 
It's possible it would be later though...

**Comment by jarrodmillman** [comment]
@cai-lw The first release candidate for 2.4 is now available:
https://pypi.org/project/networkx/2.4rc1/

You can install it via pip:
```
pip install networkx==2.4rc1
```
If all goes well, 2.4 final will be released in about 1 week.
