### ISSUE TITLE
nx.draw_networkx does not show any edge

### ISSUE THREAD

**Issue by sw-gong** [networkx/networkx#3602]
Thanks for the perfect library!

Is there anyone nodes why `nx.draw_networkx` does not show any edge? It shows edges with `G.nodes()`. See images below.

![image](https://user-images.githubusercontent.com/39670256/65531958-e790f700-def2-11e9-8e0c-9552e0a08cba.png)
![image](https://user-images.githubusercontent.com/39670256/65532062-1313e180-def3-11e9-8a99-682ee5ad46f3.png)

The graph is created with the code below:
```
def to_networkx(data, node_attrs=None, edge_attrs=None):

    G = nx.DiGraph()
    G.add_nodes_from(range(data.num_nodes))

    values = {key: data[key].squeeze().tolist() for key in data.keys}

    for i, (u, v) in enumerate(data.edge_index.t().tolist()):
        G.add_edge(u, v)
        for key in edge_attrs if edge_attrs is not None else []:
            G[u][v][key] = values[key][i]

    for key in node_attrs if node_attrs is not None else []:
        for i, feat_dict in G.nodes(data=True):
            feat_dict.update({key: values[key][i]})

    return G
```

**Comment by dschult** [comment]
Try drawing a smaller graph. If that works, then the edges are probably being shown--you just can't see them.
Also try zooming in on your image. Maybe the edges are there.

**Comment by sw-gong** [comment]
> Try drawing a smaller graph. If that works, then the edges are probably being shown--you just can't see them.
> Also try zooming in on your image. Maybe the edges are there.

I can other graphs with networkx. I'm not sure what you mean by zooming the image. I drew the graph inside the jupyter notebook, which does not allow zooming I think.

**Comment by dschult** [comment]
For the edges to not show up on that picture, they would need to be covered up by nodes.
Instead of zooming, for example you could compute how many isolated nodes are in the network.
Maybe even just draw the non-isolated nodes.

    G.remove_nodes_from(list(nx.isolates(G)))    # untested
    nx.draw_networkx(G)

**Comment by dschult** [comment]
I'm assuming that the image did actually show edges that were just not visible. I'll close this issue
