### ISSUE TITLE
Provide a function arg to contracted_nodes to prevent copying

### ISSUE THREAD

**Issue by nanodan** [networkx/networkx#3607]
For large graphs, with a lot of contraction steps, the `H = G.copy()` step is by far the bottleneck in speed. It would be nice to have an option to pass an argument like copy=False to the function to operate directly on G instead of making a copy for each contract step.

**Comment by dschult** [comment]
This seems like a good idea and easy to implement as you describe.
Thanks!

**Comment by KanishkT123** [comment]
@dschult @nanodan is anyone working on this? I have some downtime this week and could probably give it a shot if not.

**Comment by dschult** [comment]
That's be great!

**Comment by MridulS** [comment]
Should be closed, PR merged in https://github.com/networkx/networkx/pull/3646
