### ISSUE TITLE
Possible bug in version attribute in GEXF.py

### ISSUE THREAD

**Issue by PalAditya** [networkx/networkx#3610]
In ```gexf.py```, from lines 769 to 773, we currently have https://github.com/networkx/networkx/blob/4a0f42b477e5b20377ba7502de555b67b429adc3/networkx/readwrite/gexf.py#L769-L773

while in lines 822-830, it is:

https://github.com/networkx/networkx/blob/4a0f42b477e5b20377ba7502de555b67b429adc3/networkx/readwrite/gexf.py#L822-L830

which seemed somewhat inconsistent to me (**version** vs **VERSION**). So I looked above, and found:

https://github.com/networkx/networkx/blob/4a0f42b477e5b20377ba7502de555b67b429adc3/networkx/readwrite/gexf.py#L159-L161

which indicates that the ```version``` parameter would only accept ```1.1draft/1.2draft```, while the ```VERSION``` parameter will have ```1.1/1.2``` in it. 

https://github.com/networkx/networkx/blob/4a0f42b477e5b20377ba7502de555b67b429adc3/networkx/readwrite/gexf.py#L250-L251
Hence, the checks in both add_edges and add_nodes with ```self.version``` fails always.

**How to test?**

```python
import networkx as nx
G=nx.Graph()
G.add_node(0, label='1', color='green')
G.nodes[0]['viz']['color'] = {'r' : 0, 'g' : 0, 'b' : 256}
fh = io.BytesIO()
nx.write_gexf(G, fh, version='1.1draft')
fh.seek(0)
H = nx.read_gexf(fh, node_type=int)
```
The above code will execute fine, but as soon as we omit the version parameter (which defaults to 1.2draft), it raises the exception as it expects a ```rgba``` tuple. Clearly, the VERSION parameter is working.

However:

```python
import networkx as nx
G=nx.Graph()
G.add_node(0, label='1', color='green', version='1.1draft')
G.nodes[0]['spells']=[(1,2)]
print("\n".join(nx.generate_gexf(G)))
```
will still have the spell attribute, but neither will have slice. Same for version=1.2draft (can be checked via **print()** in them too)

Thus, I believe that all the ```self.version = 1.1 ``` checks should be made into ```self.VERSION = 1.1 ```, unless I am misunderstanding it? At any case, the code should be consistent for the check.

**Additional context:** I am currently working on a PR to improve the code coverage of test_gexf.py as per discussion in #3606 and noticed this weird issue. Clarification regarding this bug(?) will be welcome so that I could incorporate it in my PR

**Comment by dschult** [comment]
Yes!  Anywhere it checks ```self.version == '1.1'```, that should be ```self.VERSION```.
I guess that means we need a test that slices work.

Thanks!
