### ISSUE TITLE
GEXF output does not round-trip

### ISSUE THREAD

**Issue by wkschwartz** [networkx/networkx#3612]
On master (currently 269c5721100797514aa0469d58e637ec3a29e984) and Python 3.7.3, if I run the following script:
```python
import io, math
import networkx

g = networkx.Graph()
g.add_node(1, weight=float('inf'), data='inf')
g.add_node(2, weight=float('nan'), data='nan')
with io.BytesIO() as f:
	networkx.write_gexf(g, f)
	f.seek(0)
	h = networkx.read_gexf(f, node_type=int)
if h.nodes[1]['data'] != 'inf':
	print(f"h.nodes[1]['data'] == {h.nodes[1]['data']!r} != 'inf'")
if h.nodes[2]['data'] != 'nan':
	print(f"h.nodes[2]['data'] == {h.nodes[2]['data']!r} != 'nan'")
if not isinstance(h.nodes[1]['weight'], float) or not math.isinf(h.nodes[1]['weight']):
	print(f"h.nodes[1]['weight'] == {h.nodes[1]['weight']!r} != float('inf')")
if not isinstance(h.nodes[2]['weight'], float) or not math.isnan(h.nodes[2]['weight']):
	print(f"h.nodes[2]['weight'] == {h.nodes[2]['weight']!r} != float('nan')")
```
I get the following output:

```
h.nodes[1]['data'] == 'INF' != 'inf'
h.nodes[2]['data'] == 'NaN' != 'nan'
h.nodes[1]['weight'] == 'INF' != float('inf')
h.nodes[2]['weight'] == 'NaN' != float('nan')
```

It appears that dc21ca4, which fixed #3573, caused `write_gexf` to write `float('inf')` to XML file as `INF` by transforming text without checking data types first, and that `read_gexf` does not cast `float` or `double` XML types to the `float` Python type.

**Comment by dschult** [comment]
Yes -- you are right... I understand the issue. 
It'd be nice to read 'INF', 'NaN' and '-INF' as floats (and maybe 'inf', etc too)...

**Comment by wkschwartz** [comment]
I think to conform to the standard, you just rely on the data type definitions at the top of the GEXF file. This line should tell the reader how to convert the data:

```xml
<attribute id="0" title="weight" type="double" />
```

If the type is double or float, convert it to a Python `float`.

**Comment by dschult** [comment]
Thanks very much for this report!  
It looks like the lines added to the "reader" at line 800 of the file should not be there. The ```decode_attr_elements``` handles them so we don't have to. 
Also, the lines in the writer should check the type to ensure it is float before converting.

And we'll add your example as a test.  Thanks again!
