### ISSUE TITLE
Orthogonal layout

### ISSUE THREAD

**Issue by samiit** [networkx/networkx#3615]
Is it possible in networkx to view the graph layout as orthogonal, wherein, the edges are either vertical or horizontal between the nodes?

Something along the lines of [graphviz](https://stackoverflow.com/questions/8939973/how-can-i-generate-rectangle-style-edges-instead-of-curves-in-graphviz).

**Comment by dschult** [comment]
Controlling the drawn networks is done using the layout routines as described in [the drawing section](https://networkx.github.io/documentation/latest/reference/drawing.html).
There are a couple of interfaces to graphviz available there: pygraphviz and pydot
Whichever one you decide to install, hopefully the options available in graphviz_layout will suffice to do what you want.  :)

**Comment by samiit** [comment]
Thanks @dschult for answering. Only is there any way we can do this within networkx and plot it in matplotlib, just as we can render other layouts?

**Comment by dschult** [comment]
Yes -- use something like ```pos = pygraphviz_layout(G)``` and then ```nx.draw_networkx(G, pos=pos)```

**Comment by samiit** [comment]
Thanks. The following worked for me:
```
G = nx.petersen_graph()
pos = nx.nx_agraph.pygraphviz_layout(H, prog='dot')
nx.draw_networkx(G,pos)
```

The only thing left is how I can pass the `splines = ortho` attribute to ensure that the edges are drawn in an orthogonal fashion. Is there a way to specify in `networkx` how the edges ought to be drawn (spline, orthogonal format, etc)?

**Comment by dschult** [comment]
The ```splines``` argument/attribute in GraphViz determines how the edges are routed as they travel from node to node. The edges do not affect the position of the nodes, and the position of the nodes is all we get back from ```pygraphviz_layout```. Matplotlib is controlling how the edges are routed. So, to get the GraphViz edges you would need to stick to drawing with Graphviz.

Luckily, pygraphviz does allow you to [draw with Graphviz](http://pygraphviz.github.io/documentation/pygraphviz-1.5/tutorial.html#layout-and-drawing). Something like this should work:

    PG = G.to_agraph()
    PG.draw('filename.png', prog='dot', args='-Gsplines=ortho') . # untested...
