### ISSUE TITLE
Issue with the separation of dijkstra_path and dijkstra_path_length functions 

### ISSUE THREAD

**Issue by manesioz** [networkx/networkx#3618]
Hello, 
I was wondering if there was any reason to separate `dijkstra_path()` and `dijkstra_path_length()` into separate functions? Since we can see from the [source code](https://github.com/networkx/networkx/blob/master/networkx/algorithms/shortest_paths/weighted.py#L162) that we are only returning part of the information in `dijkstra_path()`: 

```python 
(length, path) = single_source_dijkstra(G, source, target=target,weight=weight)
return path
```
Which means that if the user wants to find the path length in addition to the path itself, one would have to call the other function `dijkstra_path_length()`, thereby increasing the computational overhead unnecessarily. 

Wouldn't it be easier to return a NamedTuple of both path and length and let the user parse the information accordingly?

**Comment by dschult** [comment]
Looks like if you want both, you'd use ```single_source_dijkstra```.
Maybe that should be in the docs for dijkstra_path.
