### ISSUE TITLE
Degree Centrality inconsistency 

### ISSUE THREAD

**Issue by mohdalattar** [networkx/networkx#3623]
Hi all, 

I am calculating degree centrality (using degree_centrality) for a street network (called from OSMNx package), however, there is inconsistency with the results I am not sure how it can be interpreted. 

<img width="696" alt="Screen Shot 2019-10-02 at 10 28 21 PM" src="https://user-images.githubusercontent.com/50058721/66083386-139c2000-e564-11e9-8417-2430ddc2b859.png">

As you can see edge with value of 9 is in fact connected to 6 other edges
the same goes for the one with the value 7. 

How can you interpret the results

**Comment by manesioz** [comment]
Would it be possible to show us the actual list of nodes and edges connected to the above points (the 9, 7, and 6 ones respectively)? It's possible that the visualization is not perfectly reflective of the actual graph relationships (depending on how you rendered/coloured it). For example, in OSM, some Ways span multiple Nodes which could account for the greater-than-anticipated degree centrality for some nodes.

**Comment by mohdalattar** [comment]
I am not sure how to print out the list of nodes and edges connected to these points on python. 

When you say ( visualization is not perfectly reflective of the actual graph relationships ) does that mean degree centrality account for the direction of the street ?  as I think a see an influence for the direction (visually)

![Capture](https://user-images.githubusercontent.com/50058721/66097194-604c1f00-e595-11e9-83a0-ea0a319c2645.JPG)

Is there anyway to get the absolute number of connected edges (regardless of the direction of the street) ?

**Comment by dschult** [comment]
Showing the visualizations doesn't help us figure out the degree... You need to work with the actual data, not a picture. It could be that more than one edge connects 2 nodes -- or that you are using a weighted edge.  Best case: find a small example that shows the same problem. For example, get the ego_graph of a node and then you can print out the entire graph with edge data and node data and see what the degree of each node is.
