### ISSUE TITLE
Inconsistent read_edgelist

### ISSUE THREAD

**Issue by Zoher15** [networkx/networkx#3624]
So initially my edgelist.txt consisted of numbers:
`7945 9590`

`6526 9590`
When I load this edgelist using **read_edgelist()** I get **|N|=9540 |E|= 23369**

These were actually IDs of URLs. I decided to store them in string format called edgelist_full.txt:

`http://www.ontologydesignpatterns.org/ont/vn/data/Reject_77000000 http://www.ontologydesignpatterns.org/ont/fred/domain.owl#Afford`

`http://dbpedia.org/resource/Consolidated_city-county http://www.ontologydesignpatterns.org/ont/fred/domain.owl#Afford`
When I load this edgelist **read_edgelist()** I get **|N|=3052 |E|= 8069**

I was baffled. All the nodes, strings and IDs are unique and have 1 to 1 correspondence. There are no duplicate edges (and even if they were it should have been caught even in the ID edgelist)

Then I tested it again, this time loading the edgelist_full.txt as an array and feeding it to my **nx.Graph** using **add_edges_from()** and passing the array to it. Voila once again **|N|=9540 |V|= 23369**

I would love to know why this is happening. Is it some character that is making **read_edgelist()** skip so many edges (and as a consequence also nodes) or is it something else?

**Comment by dschult** [comment]
Hard to see what's going on without seeing it... :)
You've got 4 URLs that aren't hyperlinks and at least the first ones don't work.
You haven't shown us any code that you tried. How can we tell what's going on?

The code adds an edge for any line that 1) has two or more numbers separated by spaces, and 2) doesn't have a comment character (# by default) in front of those two numbers. What you describe should work -- and your loading it as an array and feeding it to add_edges_from() makes me think it is working... but that something else is wrong. Your two methods should return the same graph.

**Comment by dschult** [comment]
I need to see your code for an example file that shows the problem. 
When I run it on your "file" or four numbers it works fine. Same for the file with 4 uris.
But I can't see what your code is. Maybe you are doing something with read_edgelist() that it isn't expecting.

Does it work for you with just the 4 numbers?

**Comment by Zoher15** [comment]
Hey Dan,

TFCG_intersect_central |N|=4169 |E|=15128
I write them to file using:
`nx.write_edgelist(TFCG,"TFCG_intersect_central.edgelist.txt",data=True)`
 |N|=4169 |E|=15128
I read them using:
`nx.read_edgelist("TFCG_intersect_central.edgelist.txt")`
|N|=1561 |E|=4792
[TFCG_intersect_central.edgelist.txt](https://github.com/networkx/networkx/files/3704810/TFCG_intersect_central.edgelist.txt)

I am attaching the said edgelist.

Thanks!

Best,
Zoher

**Comment by dschult** [comment]
Aha -- you've got ```#``` symbols in your text file which is the default character for the comments argument. ```nx.read_edgelist``` is trying to handle each hashtag as a comment symbol. 
Use:

    nx.read_edgelist(filename, comments='@') 

or any other character that doesn't show up (or more than one character is one is too restrictive).

**Comment by Zoher15** [comment]
Thanks Dan! I was thinking that but I assumed it would have to be start of the line for it to be considered a comment.

Best,
Zoher
