### ISSUE TITLE
Incorrect clustering coefficient calculation

### ISSUE THREAD

**Issue by osilkin98** [networkx/networkx#3640]
The clustering coefficient is calculated incorrectly for multiple of the terms. This is due to the fact that computing the number of edges isn't correct in the closed neighborhood for a node u ∈ G.

Consider the following graph G:
![image](https://user-images.githubusercontent.com/16809287/66355646-fdaca780-e935-11e9-85fb-ce1149b25cb8.png)
 
In the above graph, the clustering coefficient is computed as follows: 
```py
>>> edges = [('a', 'b'), ('a', 'c'), ('a', 'e'), ('b', 'c'), ('c', 'e'), ('c', 'd'), ('d', 'e')]
>>> G = nx.Graph(edges)
>>> nx.clustering(G)
{'a': 0.6666666666666666, 'b': 1.0, 'c': 0.5, 'e': 0.6666666666666666, 'd': 1.0}
```
However, 'a' and 'd' should both be `5/6`, and `c` be `7/10`

The following computation calculates the correct clustering coefficient:
```py
def clustering_coefficient(G: nx.Graph, *nodes):
    nodes = nodes or G.nodes
    clusters = {}
    for v in nodes:
        # Here we calculate the number of edges contained 
        # in the subgraph induced by v and its adjacent neighbors
        closed_hood = list(G.neighbors(v)) + [v]   
        induced = nx.induced_subgraph(G, closed_hood)  

        # The most edges that the induced subgraph can have is: deg(v) * (deg(v) - 1) / 2  
        max_edges = len(induced) * (len(induced) - 1) / 2
        
        # Thus we compute cc(v) = |E(N[v])| / |E(K_deg(v)+1)|
        clusters[v] = len(induced.edges) / max_edges

    return clusters
```

And we see that:

```py
>>> clustering_coefficient(G)
{'a': 0.8333333333333334, 'b': 1.0, 'c': 0.7, 'e': 0.8333333333333334, 'd': 1.0}

>>> cc_G = sum(cc for cc in clustering_coefficient(G).values())/len(G)
0.8733333333333334

>>> true_cc = (5/6 + 5/6 + 1 + 1 + 7/10) / 5
>>> math.isclose(true_cc, ccG)
True
```

**Comment by dschult** [comment]
I don't think your definition of clustering_coefficient aligns with ours. 
You are counting edges in the induced subgraph of the inclusive neighborhood.
Our definition counts triangles incident on the node of interest. This can be thought of as counting edges in your induced subgraph that don't connect to the node of interest. In other words, counting edges in the induced subgraph WITHOUT including the node of interest. 
Your definition inflates the clustering coefficient for high degree nodes because it counts all the edges from the node to its neighbors.

**Comment by osilkin98** [comment]
[Combinatorics and graph theory by Harris, Hirst and Mossinghoff](https://doc.lagout.org/science/0_Computer%20Science/3_Theory/Graph%20Theory/Combinatorics%20and%20Graph%20Theory.pdf#12) define it as follows:

![image](https://user-images.githubusercontent.com/16809287/66373845-9a436980-e977-11e9-80db-9d4fc939e6cf.png)

Perhaps we can define it as a separate function.

**Comment by dschult** [comment]
Reading that pdf of the textbook (pages 29 and 30 are the only places where clustering coefficient is discussed), it is clear that they are discussing the results of the Watts and Strogatz work on small world graphs and clustering. But the definition does not align with that work. I do not think we should replicate this definition -- which appears to be a mistake.

**Comment by osilkin98** [comment]
Understandable, closing.
