### ISSUE TITLE
networkx.algorithms.community.asyn_lpa_communities

### ISSUE THREAD

**Issue by esysss** [networkx/networkx#3642]
this function sometimes sticks on an infinite loop.
it's better to use a counter among
while count:

**Comment by manesioz** [comment]
Can you give a specific case when the function would be stuck in an infinite loop?

**Comment by esysss** [comment]
of course ...
i made the LFR network in [here](https://drive.google.com/file/d/1d4d7So6EZx6kQ34zjTFto3d5r0LaM-96/view?usp=sharing)

```
net = #get the graph using gpickle
LPcommunities = networkx.algorithms.community.asyn_lpa_communities(net)
```

this code will stuck in an infinite loop

**Comment by rossbar** [comment]
Unfortunately the given example isn't sufficient to reproduce the behavior. Since this has been inactive for a while I'm going to close it. However, if you have a minimum reproducing example that does not depend on loading external data, please share and reopen this!
