### ISSUE TITLE
GN networks (girvan-newman benchmart)

### ISSUE THREAD

**Issue by esysss** [networkx/networkx#3643]
we want to make a network with parameters N = 128, l = 4, g= 32, ⟨k⟩ = 16, the range of kout can be change from 1 to 8.

**Comment by manesioz** [comment]
I'm not sure what you're asking, but there is an implementation of the [GN algorithm](https://networkx.github.io/documentation/latest/reference/algorithms/generated/networkx.algorithms.community.centrality.girvan_newman.html) if you were looking for that.

**Comment by esysss** [comment]
Girvan and Newman introduced an artificial network benchmark to test out community detection algorithms on it.
and the properties of these networks are as I mentioned above. between girvan and newman algorithm to detect communities and girvan and newman's artificial network bechmark people always mixed them up !!!
