### ISSUE TITLE
Issues saving a Graph as a Shapefile

### ISSUE THREAD

**Issue by M-nes** [networkx/networkx#3654]
Hello,

I am working with GTFS files and OSMNX to generate a Graph (called G2) containing roads of the Paris region in France. 
I found a very interesting tutorial [here](http://kuanbutts.com/2018/12/24/peartree-with-walk-network/) that I followed and allows to generate said Graph and I then calculate the shortest path between two points with:
```
nx.shortest_path_length(G2, source = source, target = target, weight = None, method = 'dijkstra')
```
I have an issue with how big the Graph is. As I am working with big data, I find myself having to restart the kernel from time to time and have to re-run everything which is quite restrictive as the generation of G2 takes me about <i> 6-7 hours </i> each time.

So I would like to save G2 as a shapefile so I'll just have to read it with nx next time my notebook bugs. However nx.write_shp raised an error:

```
nx.write_shp(G2, '/Users/mnes/Desktop/Shapefile/')
```
<details closed><summary><code>TypeError</code></summary><p>

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-101-764a76abb78d> in <module>
----> 1 nx.write_shp(G2, '/Users/mnes/Desktop/Shapefile/G2.shp')

~/anaconda3/envs/inox/lib/python3.6/site-packages/networkx/readwrite/nx_shp.py in write_shp(G, outdir)
    304     for n in G:
    305         data = G.nodes[n]
--> 306         g = netgeometry(n, data)
    307         attributes, nodes = create_attributes(data, node_fields, nodes)
    308         create_feature(g, nodes, attributes)

~/anaconda3/envs/inox/lib/python3.6/site-packages/networkx/readwrite/nx_shp.py in netgeometry(key, data)
    227         elif 'Wkt' in data:
    228             geom = ogr.CreateGeometryFromWkt(data['Wkt'])
--> 229         elif type(key[0]).__name__ == 'tuple':  # edge keys are packed tuples
    230             geom = ogr.Geometry(ogr.wkbLineString)
    231             _from, _to = key[0], key[1]

TypeError: 'int' object is not subscriptable
```

</p></details>

---

Bellow are prints that could maybe help you further:
<details closed><summary><code>G2.graph</code></summary><p>

```
{'name': 'unnamed',
 'crs': '+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs',
 'simplified': True,
 'streets_per_node': {272629764: 3,
  1933574168: 1,
  371195933: 4,
  6587154464: 3,
  274726948: 4,
  1933574180: 1,
  274726950: 4,
  274726951: 3,
  1933574184: 3,
  1933574189: 3,
  1933574191: 3,
  1933574192: 3,
  1933574200: 3,
  1933574201: 1,
  1933574203: 3,
  1933574207: 3,
  1933574208: 1,
  1583349835: 3,
  2585788512: 4,
  2780823653: 3,
  2780823656: 1,
  2585788524: 1,
  2585788525: 3,
  2585788526: 3,
  1583349880: 3,
  3340763260: 3,
  2585788543: 1,
  3340763263: 1,
  1583349890: 3,
  520093828: 4,
  2585788548: 1,
  2585788550: 3,
  2585788551: 1,
  2585788552: 3,
  2585788549: 1,
  274727050: 4,
  499122309: 3,
  2585788559: 3,
  499122321: 3,
  499122325: 1,
  520093848: 4,
  499122329: 3,
  499122331: 1,
  499122335: 1,
  5995757736: 3,
  3307208874: 3,
  3307208875: 3,
  3307208880: 3,
  3307208882: 3,
  3307208884: 3,
  3307208885: 3,
  5995757749: 3,
  3307208890: 3,
  5995757754: 3,
  3307208893: 3,
  3307208895: 3,
  3307208896: 3,
  5995757760: 3,
  3307208899: 3,
  5995757763: 3,
  3307208911: 3,
  3307208913: 3,
  3307208916: 3,
  3307208918: 3,
  3307208923: 3,
  3307208924: 3,
  1583349980: 3,
  3307208926: 3,
  1583349983: 3,
  773849313: 4,
  5163188457: 3,
  3307208938: 4,
  3307208941: 3,
  1755316464: 4,
  1755316466: 3,
  3307208950: 3,
  1583350009: 1,
  213909753: 4,
  1231028483: 3,
  2789212422: 1,
  274727184: 4,
  1952448806: 3,
  5163188527: 3,
  5163188530: 3,
  ...}}
```

</p></details>

The nodes have attributes I would like to also save in the shapefile:
<details closed><summary><code>print(list(G2.nodes(data=True))[0])</code></summary><p>

```
(272629764, {'y': 48.8949291, 'x': 2.2500055, 'osmid': 272629764, 'boarding_cost': 0})
```

</p></details>

**Comment by manesioz** [comment]
Seems like you have `keys` which are of type `int`, therefore they are not [subscriptable](https://stackoverflow.com/a/216980/10981911).

**Comment by dschult** [comment]
The [docs for write_shp](https://networkx.github.io/documentation/stable/reference/readwrite/generated/networkx.readwrite.nx_shp.write_shp.html#networkx.readwrite.nx_shp.write_shp) state that nodes must be of the right type to make this work. My experience is that if you don't need the shapefile, you should not bother to change your nodes to make it work with the shapefile standard.  Instead store it another way.  

For example you can pickle it using [write_gpickle](https://networkx.github.io/documentation/stable/reference/readwrite/gpickle.html)

**Comment by M-nes** [comment]
Thank you @dschult I tried write/read_gpickle and it is working wonderfully.
