### ISSUE TITLE
Kamada Kawai layout not outputting 3rd dimension

### ISSUE THREAD

**Issue by milcent** [networkx/networkx#3658]
When playing with positions for 3d graphs, contrary to the usual srping layout, when I set it to be 
`pos = nx.kamada_kawai_layout(G, dim=3)`, it doesn't work.
An inspection in the resulting dict will show the same as below, with zeros in the third dimension.
`In [40]: pos
Out[40]: 
{'A': array([0.73517262, 0.0116334 , 0.        ]),
 'D': array([0.99999997, 1.        , 0.        ]),
 'E': array([0.01163338, 0.73517261, 0.        ]),
 'F': array([-0.25083676,  0.27272334,  0.        ]),
 'G': array([-0.91055632, -0.0634198 ,  0.        ]),
 'H': array([-0.79471643, -0.79471641,  0.        ]),
 'I': array([-0.06341983, -0.91055634,  0.        ]),
 'J': array([ 0.27272335, -0.2508368 ,  0.        ])}`

**Comment by dschult** [comment]
I have verified this problem. It stems from using ```circular_layout``` as the initial positions for the nodes when ```dim >= 2```.  But "circular" layouts are two-D with zeros in all dimensions above 2.

Perhaps we can find a good initial position that works for ```dim>2```.

**Comment by milcent** [comment]
ThaT would be nice.

Em qua, 16 de out de 2019 às 23:34, Dan Schult <notifications@github.com>
escreveu:

**Comment by milcent** [comment]
I've checking the code to see if I could help.
Is it True to say that the circular_layout is the initialization for the kamada_kaway, and hence that implementing the third dim to the circular_layout would automatically fix the kamada_kaway??

**Comment by milcent** [comment]
Or maybe initialize the positions with the spring layout, which is already force-directed, and hope that the kamada_kaway_solver will converge appropriately.

**Comment by dschult** [comment]
It is true to say that the circular_layout is the initialization for the kamada_kawai_layout. But it isn't clear how to implement the third dimension for circular_layout.  I mean, it already does work for 3-D, it is still a circle... just in 3D.

Your idea of force-directed as init may work, but check that spring_layout does what you expect in 3D first... :)

**Comment by stefanhannie** [comment]
I am just coming across this issue as well. Would it be appropriate to initialize the vertices on a sphere? This is an analogue of the 2D circle.

**Comment by dschult** [comment]
How would you do a spherical layout? A circular layout is fairly straightforward -- evenly spaced about the circle -- but what does a spherical layout look like with say 10 nodes?

**Comment by stefanhannie** [comment]
I was thinking about this; a quick and dirty implementation could be a random placement. Each point could be generated with 2 random numbers--one for the azimuthal angle and one for the polar angle.

**Comment by Radcliffe** [comment]
One approach is to choose points along a spiral, as described in equation (8) of this article:
http://www.math.vanderbilt.edu/saffeb/texts/161.pdf

Here is a quick-and-dirty implementation of the algorithm.
```python
# Arrange N points on the surface of a sphere along a spiral.
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

%matplotlib notebook

def points_on_sphere(n):
    h = -1 + 2 * np.arange(0, n) / (n - 1)
    theta = np.arccos(h)
    phi = np.zeros(n)
    phi[1:-1] = np.cumsum(3.6/np.sqrt(n) * (1 - h[1:-1]**2)**(-0.5)) % (2 * np.pi)
    return theta, phi


def spherical_to_cartesian(theta, phi, r=1):
    s = r * np.sin(phi)
    x = s * np.cos(theta)
    y = s * np.sin(theta)
    z = r * np.cos(phi)
    return x, y, z


def plot_points(n):
    fig = plt.figure()
    ax = fig.add_subplot(111, projection='3d')
    theta, phi = points_on_sphere(n)
    x, y, z = spherical_to_cartesian(theta, phi)
    ax.scatter(x, y, z, marker='o')
    plt.show()


plot_points(200)
```

**Comment by stefanhannie** [comment]
@Radcliffe Nice! This doesn't really have a higher dimensional analogue does it?

**Comment by milcent** [comment]
Very nice indeed!
Now, is it safe to assume that the Kamada_kaway algo in networkx would work as expected in this case as it does with 2-dim circles?

**Comment by boothby** [comment]
It looks like the spiral method suggested by @Radcliffe is quite biased towards the poles, and I share concerns about higher dimensions.  To add another candidate to the mix, there's a fast method to pick uniformly random points on a hypersphere due to Muller; 1959: pick a set of *d*-dimensional points with each coordinate normally distributed, and divide by their 2-norm to obtain unit vectors.

    import numpy as np
    import matplotlib.pyplot as plt
    from mpl_toolkits.mplot3d import Axes3D

    def hypersphere_points(n, dim):
        points = np.random.normal(size=(dim, n))
        return points / np.linalg.norm(points, axis=0)

    def plot_points(n):
        fig = plt.figure()
        ax = fig.add_subplot(111, projection='3d')
        P = hypersphere_points(n, 3)
        ax.scatter(P[0,:], P[1,:], P[2,:], marker='o')
        plt.show()

    plot_points(200)

![image](https://user-images.githubusercontent.com/569654/72377800-0810d700-36c5-11ea-9c77-7c90701be0ca.png)

    see: http://mathworld.wolfram.com/HyperspherePointPicking.html

**Comment by boothby** [comment]
@milcent that's a great question.  I did a little study to compare the uniform initialization as @stefanhannie suggested, to the hypersphere initialization that I contemplate above.

https://gist.github.com/boothby/007bfbfc632e9328b0260f1437aac7cb

My interpretation of the results is both initialization methods result in equally good layouts, so it's best to go with the simplest one.

**Comment by milcent** [comment]
Great Job!!

**Comment by dschult** [comment]
Yes, I agree -- Great Job @boothby !!

**Comment by milcent** [comment]
I also would liked to thank you and everyone else involved.
For me this was a great example of open source collaboration!

Em seg, 20 de jan de 2020 às 16:37, Dan Schult <notifications@github.com>
escreveu:
