### ISSUE TITLE
Add flake8 style check to travis

### ISSUE THREAD

**Issue by sbellem** [networkx/networkx#3662]
Wondering whether you would like to add the flake8 check to travis. I could probably make a pull request for it if you are welcoming the addition.

When browsing the code in a text editor that performs flake8 checks, some style-related errors pop out here and there and these errors could easily be caught on travis, so that is why I wonder if you wish to add the check to travis.

**Comment by jarrodmillman** [comment]
Thanks for the suggestion.  Rather than add a flake8 check to travis, we enabled pep8speaks.  You can see what it looks like here: #3669
