### ISSUE TITLE
About the order of the edges returned by the nx.connected_component_subgraphs

### ISSUE THREAD

**Issue by DEEMOALICE** [networkx/networkx#3668]
`component = list(nx.connected_component_subgraphs(Gn_1))[1]
list(component.edges())`

OUT：('4042123', '7097284'),
 ('4072357', '7097284'),
 ('5097796', '7097284'),
 ('7703755', '7097284'),
 ('7097284', '5567325'),
 ('7097284', '6745586'),
 ('7097284', '1602379'),
 ('7097284', '1615579'),
 ('7097284', '1593193'),
 ('7097284', '1613458'),

When I build a network，and use connected_component_subgraphs try to output the edge of the connected subgraph，I found that the order of the nodes on both sides of the edge changes relative to the original data.  In the above output，the correct mapping should be like （‘7097284’，‘4042123’），but some of its output is wrong(One to four lines). So someone know how to solve this problem? Thx！

**Comment by yx14** [comment]
Can you add a line where the Gn_1 graph is created so others can reproduce this problem? Thanks!

**Comment by dschult** [comment]
Why do you say that the order should be the other way? For an undirected graph, order of the edge nodes doesn't matter. Are you trying to do something with the edges that requires an order on the nodes?

**Comment by DEEMOALICE** [comment]
Because I need to get the point-to-point correspondence by nx.write_edgelist, and then get the number of motif through FANMOD, so the order of the edge nodes is very important to the result of the motif type.And&nbsp;I found that the output of version 2.0 is ordered, and the later versions are out of order.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Dan Schult"<notifications@github.com&gt;; 
发送时间: 2019年10月20日(星期天) 中午11:46
收件人: "networkx/networkx"<networkx@noreply.github.com&gt;; 
抄送: "梦幻那一夜"<854655253@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [networkx/networkx] About the order of the edges returned by the nx.connected_component_subgraphs (#3668)




Why do you say that the order should be the other way? For an undirected graph, order of the edge nodes doesn't matter. Are you trying to do something with the edges that requires an order on the nodes?

**Comment by dschult** [comment]
If order of the nodes in a 2-tuple of an edge is important then maybe you should be using DiGraph????
