### ISSUE TITLE
GED incredibly slow on small graph

### ISSUE THREAD

**Issue by RamonBeast** [networkx/networkx#3673]
Hello,
I'm trying to calculate the GED  between 2 very small graphs, it's been over 3 hours on a Xeon@3GHz and still it's going on. I managed to get a _slight_ speedup by  hashing all strings to int (just an experiment) but still, at the 3h mark, it's still going on with no end in sight.

Any idea if this is normal or I'm doing something wrong? Attached the 2 graphs and below my very simple code.

`for dist in nx.algorithms.similarity.optimize_graph_edit_distance(G, g, node_match=lambda a,b: a['pr'] == b['pr']):
            minD = dist
`

Update: after 15h it's still running :(

[Graphs.zip](https://github.com/networkx/networkx/files/3747132/Graphs.zip)

**Comment by RamonBeast** [comment]
An update on the above: I've found several (smaller) graphs that ends up in taking forever to process and the main process core dumps after 18/20h on my machine. I'm talking about graphs (trees in reality) with no more than 20 nodes. Anyone have suggestions on how to calculate the edit distance as the library seems to be unable to converge?

**Comment by dschult** [comment]
Edit distance is computationally hard. Any suggestions for improvements?

**Comment by RamonBeast** [comment]
I haven't got into profiling the code yet but yes I do agree with you it's computationally hard of course. Do you think it is possible that there's something else behind this specific case? I ran tests on much larger graphs and got a distance if minutes/hours, this one (and many others) are very very small and I can't even manage to get a result as the process core dumps after a day or so.

**Comment by zsxing99** [comment]
I had the same issue. Any fix or update?

**Comment by dschult** [comment]
Its not a matter of a fix or update. The algorithm is what it is. If someone has developed a new algorithm, then we've got something to work on. Otherwise it's just a hard problem...
