### ISSUE TITLE
Wrong random_lobster implementation?

### ISSUE THREAD

**Issue by silent567** [networkx/networkx#3701]
Hi, it seems that [networkx.random_lobster's implementation logic](https://github.com/networkx/networkx/blob/4e9771f04192e94a5cbdd71249a983d124a56593/networkx/generators/random_graphs.py#L1009) is not aligned with the common definition as given in [wolfram mathworld](http://mathworld.wolfram.com/LobsterGraph.html) or [Wikipedia](https://en.wikipedia.org/wiki/List_of_graphs#Lobster).
For example, it can not produce the simplest lobster graph examples such as ![lobster_example](https://www.researchgate.net/profile/Dr_Nasreen_Khan/publication/256292297/figure/fig5/AS:669566174756876@1536648424468/A-diameter-2-lobster-graph.png).

**Comment by dschult** [comment]
I believe it can produce such monster lobsters :)
What makes you think that it can't?
It creates random lobsters -- you can't request a specific lobster.

**Comment by silent567** [comment]
Hi, in my understanding as well as my experiments, the implementation can generate at most one first-leaf and one second-leaf. It doesn't support multiple leaves~

**Comment by silent567** [comment]
Here is my simple beta-version implementation if you are interested in. The definitions of p1 and p2 are different from yours.
```py
def random_lobster(n, p1, p2):
    path_edges = [list(range(n)), list(range(1,n+1))]
    first_leaf_num = np.random.binomial(n, p1)
    first_leaf_edges = [np.random.randint(low=0, high=n, size=first_leaf_num).tolist(),
                        np.arange(n, n+first_leaf_num).tolist()]
    second_leaf_num = np.random.binomial(first_leaf_num, p2)
    second_leaf_edges = [np.random.randint(low=n, high=n+first_leaf_num, size=second_leaf_num).tolist(),
                         np.arange(n+first_leaf_num, n+first_leaf_num+second_leaf_num).tolist()]
    rol = path_edges[0]+first_leaf_edges[0]+second_leaf_edges[0]
    col = path_edges[1]+first_leaf_edges[1]+second_leaf_edges[1]
    edges = [rol, col]
    return edges
```

**Comment by dschult** [comment]
So, you agree that it creates lobsters -- just not the lobsters you would like to see?

None of the references you point to specify anything specific about creating lobsters other than it is a tree where when you remove leaves twice you end up with a path.

It looks like you are proposing a new random model of lobster generation. Would you mind describing your model, where you got the algorithm from, why you think it is good, how it might be included in NetworkX, etc?

**Comment by silent567** [comment]
It seems that you agree that the current implementation is not able to generate multi-leaves lobster graphs... And as a random generator of a specific set of graphs, it should be able to generate any element in the set. Can you imagine that `np.random.choice(10)` will never generate 5? If you can't do that, maybe you should not include this function in the package, or use another clearer name. 

My codes just resulted from my one-minute thinking. It's super easy but can generate a much larger subset of lobster graphs than yours. It's not ideal of-course. The correct implementation logic given your function name should be able to generate any element with equal probability in the set of lobster graphs of some specific properties.

I appreciate your efforts on sharing the codes and networkx is probably one of the most popular python libraries about graphs. But please remind that influence implies responsibility. The more users use your codes, the more influential a mistake will be. The stable version should be stable and reliable.

BTW, I don't care if my codes will be included; no responsibility as well. Just wanna remind of this issue and if the team cares about the users, they should do something to fix this.

**Comment by dschult** [comment]
The current implementation can/does implement multi-leaf lobsters. But it only generates at most one second level leaf for each first level leaf.  As is true for many of our random graph algorithms, we don't claim uniformly likely outcomes from the set. That is often too difficult, though it is the ideal we'd all appreciate. Perhaps we should be more clear in the documentation.

I would like to replace/improve the lobster generator if there is interest. And it would be nice to use a method established in the literature. As you say, influence implies responsibility. Since you are suggesting the change, would you be willing to search for established methods of creating random lobsters? Thanks either way -- it's good to have this on our radar.

**Comment by silent567** [comment]
Hi, feel free to do whatever you want. This is just a suggestion of common misunderstanding.
I was using your function for building datasets for training and evaluation methods. I have to say that the distribution of generated samples does matter in this case. As for the established methods, I don't think of me as an expert in the algorithm area, and I don't have enough time for learning everything from scratch.
And sorry for being harsh these days. I was freak out for wasting several days on a small-variant dataset. I took networkx's reliability as granted and spent lots of time debugging other pieces of my codes. You can at least mention something in the documents to avoid such situations. Thanks.
