### ISSUE TITLE
grid_graph says it takes a tuple, but will only take a list

### ISSUE THREAD

**Issue by dHannasch** [networkx/networkx#3703]
Using the latest master, networkx.grid_graph works when passing in a list, but crashes when passing in a tuple:

```
$ ~/anaconda3/envs/python37env/bin/python --version
Python 3.7.4
$ ~/anaconda3/envs/python37env/bin/python -c "import networkx; networkx.grid_graph([10,5])"
$ ~/anaconda3/envs/python37env/bin/python -c "import networkx; networkx.grid_graph((10,5))"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/networkx/networkx/generators/lattice.py", line 129, in grid_graph
    dlabel = "%s" % dim
TypeError: not all arguments converted during string formatting
```

https://networkx.github.io/documentation/stable/reference/generated/networkx.generators.lattice.grid_graph.html
> dim (list or tuple of numbers...)

**Comment by dschult** [comment]
That's a bug in grid_graph.  The first line is ```dlabel = "%s" % dim``` and should be ```dlabel = "%s" % (dim,)```.  But I'm not sure why that line is even there... ```dlabel``` is never used.

It looks like that line is a mistake that appeared 2 years ago when taking out the G.name attribute in the grid_graph and moving it to lattice.py.
We should simply remove that line.

As a workaround, you can use:  nx.grid_graph(((2,3),))
