### ISSUE TITLE
single_source_shortest_path_length does not contain all nodes

### ISSUE THREAD

**Issue by jsignell** [networkx/networkx#3718]
I was seeing sporadic failures on the [hvplot network docs](https://hvplot.pyviz.org/user_guide/NetworkX.html) and realized that `single_source_shortest_path_length` does not always return a dict of the same length as `G`. I assume this is a bug.

## Minimal example

Note that the failure is transient. I am seeing it about once every 3 times, so you might need to run the following snippet several times to see the behavior.

```python
import networkx as nx

G = nx.random_geometric_graph(200, 0.125)
p = nx.single_source_shortest_path_length(G, 0)

print(len(G) , len(p))
```

I am on networkx version 2.4

**Comment by dschult** [comment]
If a graph is not connected, the dict will not have as many keys as there are nodes in the graph.
The dict only returns keys that can be reached by the source node.

The doc description is:
```Compute the shortest path lengths from source to all reachable nodes.```

**Comment by jsignell** [comment]
Ah ok. Thanks for the explanation and sorry for the noise.
