### ISSUE TITLE
Issue in sample code to create subgraph

### ISSUE THREAD

**Issue by ynux** [networkx/networkx#3733]
In https://github.com/networkx/networkx/blob/master/networkx/classes/graph.py#L1653 , i think it should say `if SG.is_multigraph():` , not `if SG.is_multigraph:`. I can also create a pull request if this simplifies things.

**Comment by dschult** [comment]
Yikes -- you are correct. That code won't work as written.  Well, it works for multigraphs, but not for graphs. :{

If you can put together the pull request that would be great!  Thanks!

**Comment by ynux** [comment]
i created [https://github.com/networkx/networkx/pull/3734](https://github.com/networkx/networkx/pull/3734)
the sample code is very useful, both for making clear that Graph.subgraph() creates only a view, and as a practical help to create a new graph.
