### ISSUE TITLE
Cannot import Ford Fulkerson

### ISSUE THREAD

**Issue by spirpinias** [networkx/networkx#3739]
I am relatively new to programming, and attempting to implement a ford fulkerson algorithm on a DiGraph. Upon attempting to import, I get this error message. Can somebody help? Be greatly appreciated. 

ImportError: cannot import name 'ford_fulkerson' from 'networkx.algorithms.flow'

It could be a minor mistake, or something larger. Unfortunately, I am trying my best to decipher this one and I could use a bit of advice.

**Comment by dschult** [comment]
ford_fulkerson is a name used long ago in NetworkX (deprecated in v1.9).
Try the edmonds_karp() function [described here](https://networkx.github.io/documentation/stable/reference/algorithms/flow.html)
