### ISSUE TITLE
Heuristically Optimized Trade-offs (migrated from Trac #378)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#374]
Original ticket https://networkx.lanl.gov/trac/ticket/378
Reported 2010-07-27 by @bjedwards, assigned to @hagberg.

A random graph model for heuristically optimized trade-offs presented by Fabrikant, Koutsoupia, and Papadimitriou. Function and Test included.

**Comment by hagberg** [comment]
See #1523
