### ISSUE TITLE
BibTeX link broken in the docs

### ISSUE THREAD

**Issue by iliakur** [networkx/networkx#3740]
The following bibtex citation link on [this page of the docs](https://networkx.github.io/documentation/stable/citing.html) is broken:
http://math.lanl.gov/~hagberg/Publications/hagberg-2008-exploring.shtml

I tried to fix it, but Aric Hagberg's website now uses some JS magic to display the BibTeX entries for publications, I don't really know how to turn them into links. I'd be willing to fix this if someone were to give me pointers on how :)

**Comment by MridulS** [comment]
You can change the link to points towards the Scipy website instead for the BibTex and pdf entry 
BibTeX: http://conference.scipy.org/proceedings/SciPy2008/paper_2/reference.bib
PDF: http://conference.scipy.org/proceedings/SciPy2008/paper_2/full_text.pdf

**Comment by CsatiZoltan** [comment]
On the [documentation page](https://networkx.github.io/documentation/stable/citing.html), the BibTeX and the PDF links are still broken.

**Comment by iliakur** [comment]
That page refers to the latest release (2.4) which was published in October 2019 and thus predates this fix.
I'd expect the links to work after the next version.
