### ISSUE TITLE
Percolation Centrality gives Key error

### ISSUE THREAD

**Issue by PranavMahajan25** [networkx/networkx#3743]
I am building a graph from the adjacency matrix as follows:
`adj_mat = loadmat('my_adj_mat.mat')`
`adj_mat = np.array(adj_mat['adj_mat'])`
`G = nx.from_numpy_array(adj_mat)`

When I call `print(nx.percolation_centrality(G))`, I get the following error:

`Traceback (most recent call last):`
 ` File "metric_calc.py", line 14, in <module>
    print(nx.percolation_centrality(G))`
`  File "C:\Users\Pranav Mahajan\AppData\Local\Programs\Python\Python38\lib\site-packages\networkx\algorithms\centrality\percolation.py", line 107, in percolation_centrality
    percolation = _accumulate_percolation(percolation, G, S, P, sigma, s,`
`  File "C:\Users\Pranav Mahajan\AppData\Local\Programs\Python\Python38\lib\site-packages\networkx\algorithms\centrality\percolation.py", line 128, in _accumulate_percolation
    pw_s_w = states[s] / (p_sigma_x_t - states[w])`
`KeyError: 0`

What does this error mean and how do I resolve this?

**Comment by hagberg** [comment]
Need more info on the graph data to troubleshoot this.
