### ISSUE TITLE
importing json file as directed graph

### ISSUE THREAD

**Issue by fabisch30** [networkx/networkx#3748]
Hello everyone,
i have this json file named test.json:

`{"nodes": [{"id": "1"}, {"id": "2"}, {"id": "3"}, {"id": "4"}], "links": [{"target": "2", "source": "1"}, {"target": "4", "source": "2"}, {"target": "3", "source": "4"}, {"target": "2", "source": "3"}]}`

which shall be an directed graph. But i having trouble importing it as an directed graph in python:

```
def read_json_file(filename):
    with open(filename) as f:
        js_graph = json.load(f)
    return nx.json_graph.node_link_graph(js_graph)

G = read_json_file("test.json")
DG = nx.DiGraph(G)
```
Because still i have an undirected graph:

![test](https://user-images.githubusercontent.com/58147719/70791480-7a755b00-1d97-11ea-90dc-f69a4abde9e7.PNG)

What am i doing wrong? Should not be that hard to do...

**Comment by dschult** [comment]
You are turning the graph into a directed graph after reading it as an undirected graph. Converting an undirected graph to a directed graph is done by adding edges in both directions.

Instead use ```node_link_graph(js_graph, directed=True)```. That will load it as a directed graph. Also, in this way no post-processing is needed.

**Comment by fabisch30** [comment]
@dschult : THANKS a lot! Knew it was something simple.
