### ISSUE TITLE
A* outperforms Dijkstra when heuristic=None

### ISSUE THREAD

**Issue by esidebo** [networkx/networkx#3749]
I'm finding the shortest path in a graph, and comparing Dijkstra vs. A* without heuristic, which should reduce to Dijkstra. However, I find the solution much quicker with A*. Is this expected (different implementations?)? I'm routing on a graph with some 500k nodes and 1.3M edges representing a part of the Swedish road network. The time to find the solution is evaluated as `end-start` according to the below.
```
start = time.time() # start clock
if algo == "dijkstra":
    cost, path = nx.algorithms.shortest_paths.weighted.single_source_dijkstra(grph, nodeA, nodeB, weight=weight)
elif algo == "astar":
     path = nx.algorithms.shortest_paths.astar.astar_path(grph, nodeA, nodeB, weight=weight, heuristic=None)
     cost = sum(grph[u][v].get(weight, 1) for u, v in zip(path[:-1], path[1:])) # taken from implementation https://networkx.github.io/documentation/networkx-2.4/_modules/networkx/algorithms/shortest_paths/astar.html#astar_path_length
end = time.time()
```
Below is a comparison between the algorithms for some different routes. The cost is always the same between Dijkstra and A*, last number shows the time (in seconds).

Route                          Algorithm          Cost             Time (s)
208624 -> 60399    dijkstra           470798.71       34.5
208624 -> 60399    astar             470798.71        2.0
208624 -> 38901    dijkstra         449584.69       18.8
208624 -> 38901    astar               449584.69        1.8
208624 -> 399031   dijkstra          334905.85        9.4
208624 -> 399031   astar             334905.85        1.5

**Comment by dschult** [comment]
Hmmm...   I tried using random graphs of similar size to yours and just timing the shortest_path functions gives astar about 5-10% more time. When I used a grid_2d_graph(1000,100) I got astar about 80% of the time of dijkstra. Neither is even close to the extreme difference you are getting.
I just assigned edge weights using random.random(), so floats.

I'm using the dev version of NetworkX from github, but this code hasn't changed for a few releases. Are you using an older version of NetworkX? I'm using Python 3.7. 
Anything else funky about your graph? lots of edge attributes or anything? 
I don't see what could make such a big difference.

**Comment by esidebo** [comment]
Hm OK, isn't it odd that you get longer time for A* on the random graph?

In any case, I'm using NetworkX 2.4 with python 3.7.3 (in a conda environment). Apart from a distance attribute which I use as weight, I have two more attributes on the edges that I don't use, so nothing excessive: 
```
for i_edge,edge in enumerate(grph.edges(data=True)):
    print(edge)
    if i_edge > 3: break
(0, 1, {'dist': 166.56224232599575, 'trafficFlow': None, 'otherprop': 'dummy'})
(0, 7, {'dist': 486.643439513967, 'trafficFlow': None, 'otherprop': 'dummy'})
(0, 185, {'dist': 32.64592389813953, 'trafficFlow': None, 'otherprop': 'dummy'})
``` 

If I understand the documentation about shortest paths right, edge weights should not be floats (due to overflow and rounding issues). I can try making them ints, but apart from that I don't see what could be wrong with the graph.

**Comment by dschult** [comment]
OK... Sounds like nothing is different between our environments. 
I suspect it is the structure of the network then. But I can't test that in any effective way.
Do you get longer times for A* with random graphs too?

**Comment by esidebo** [comment]
No, at least not with `fast_gnp_random_graph(200000, 4/200000, seed=None, directed=True)`, for which I get the following (repeating the solving 5 times):

```
Dijkstra
#it 0, time = 1.48 seconds, #it 1, time = 1.44 seconds, #it 2, time = 3.00 seconds, #it 3, time = 1.44 seconds, #it 4, time = 1.45 seconds,
A*
#it 0, time = 1.95 seconds, #it 1, time = 1.94 seconds, #it 2, time = 1.95 seconds, #it 3, time = 1.93 seconds, #it 4, time = 2.05 seconds,
Route              Algorithm                      Cost   Time (s)
105 -> 120000      dijkstra                      14.25       1.76
105 -> 120000      astar                         14.25       1.96
```
i.e. not so different. It indeed seems to have to do with my graph somehow. For my graph, I noticed the spread of computing time is quite large for Dijkstra (repeating the solving 4 times)
```
A*
#it 0, time = 5.77 seconds, #it 1, time = 4.65 seconds, #it 2, time = 4.71 seconds, #it 3, time = 4.55 seconds,
Dijkstra
#it 0, time = 68.24 seconds, #it 1, time = 31.20 seconds, #it 2, time = 38.35 seconds, #it 3, time = 25.78 seconds,
Route              Algorithm                      Cost   Average Time (s)
208624 -> 60399    astar                     470798.71       4.92
208624 -> 60399    dijkstra                  470798.71      40.90
``` 
i.e. more than a factor 2.5 between shortest and longest computing time. And, almost a factor 10 difference between Dijkstra and A*. I find both of these facts hard to understand, since in principle exactly the same nodes should be expanded on each solve and for both algorithms. When profiling with cProfile all I see that the program spends 49.2 seconds per call to `single_source_dijkstra` and 36.9 seconds per call to `_dijkstra_multisource`, whereas each call to `astar_path` takes 4.06 seconds.

**Comment by dschult** [comment]
It looks to me that something is different about your graph that makes dijkstra quite variable in time spent. Perhaps the computer is running into memory issues and having to swap to disk? It is hard for me to investigate because I don't get it being that slow or that variable in speed for the networkx I generate.
