### ISSUE TITLE
Shell radius too big for shells of 1 element.

### ISSUE THREAD

**Issue by Bob-May** [networkx/networkx#3753]
This bug appears to be the opposite of issue #3188 where shells of one element collapsed to zero radius.

```
nx.__version__
'2.4'
```

Shells with one element now get assigned an X position equal to their location +1 in nlist.

shell_layout(nlist=[[1,2],[3, 4],[5, 6], [7], [8]])

{1: array([2.00000003e-01, 8.74227801e-09]),
 2: array([-2.00000003e-01, -8.74227801e-09]),
 3: array([4.00000006e-01, 1.74845560e-08]),
 4: array([-4.00000006e-01, -1.74845560e-08]),
 5: array([6.00000024e-01, 2.62268340e-08]),
 6: array([-6.00000024e-01, -2.62268340e-08]),
 7: array([4., 0.]),
 8: array([5., 0.])}

Resulting in plots that look like:

![bokeh_plot](https://user-images.githubusercontent.com/47577359/71023057-f5a87b00-20cf-11ea-8465-07b0d9027cf8.png)

**Comment by Bob-May** [comment]
Conceptual solution:


```
    npos = {}
    
    radii = np.linspace(0, 1, len(nlist) )
    
    for nodes, radius in zip(nlist, radii):
        # Discard the extra angle since it matches 0 radians.
        theta = np.linspace(0, 1, len(nodes) + 1)[:-1] * 2 * np.pi
        pos = np.column_stack([np.cos(theta) * radius, np.sin(theta)])
        npos.update(zip(nodes, pos))

    return npos
```

**Comment by Bob-May** [comment]
Suggested solution:

```
def shell_layout_suggestion(nlist=None, scale=1, center=[0,0] ):

    import numpy as np

    npos = {}
    # Create array of radii with outer radius = 1 * scale
    radii = np.linspace(1, len(nlist), len(nlist) ) * scale / len(nlist)

    for nodes, radius in zip(nlist, radii):
        for node in nodes:
            i = nodes.index(node)
            # Discard the extra angle since it matches 0 radians.
            theta = np.linspace(0, 2 * np.pi, len(nodes) +1)[:-1]
            pos = np.column_stack([radius * np.cos(theta[i]) + center[0], radius * np.sin(theta[i]) + center[1]])
            npos.update({node: pos[0]})

    return npos
```

**Comment by Bob-May** [comment]
Updated - to stagger the first point of each shell around the circle to avoid shell having its first point at Y=0.

```
def shell_layout_suggestion(nlist=None, scale=1, center=[0,0] ):

    import numpy as np

    npos = {}
    # Create array of radii with outer radius = 1 * scale
    radii = np.linspace(1, len(nlist), len(nlist) ) * scale / len(nlist)

    for nodes, radius in zip(nlist, radii):
        for node in nodes:
            i = nodes.index(node)
            # Discard the extra angle since it matches 0 radians.
            theta = np.linspace(0, 2 * np.pi, len(nodes) +1)[:-1] + (np.pi * nlist.index(nodes)/len(nlist))
            pos = np.column_stack([radius * np.cos(theta[i]) + center[0], radius * np.sin(theta[i]) + center[1]])
            npos.update({node: pos[0]})

    return npos


```
![bokeh_plot (2)](https://user-images.githubusercontent.com/47577359/71101573-efc0a180-2184-11ea-949c-1183ecdb4088.png)

**Comment by dschult** [comment]
This is a bug.
The code checks whether there is one node in the shell but doesn't scale the radius by the number of nodes in the graph in that case (and it does scale the radius when the shell has more than one node).

Thanks for this!

**Comment by Bob-May** [comment]
You're welcome.

I couldn't figure out why the original code treated shells differently based on the number of nodes in the shell.  Nor could I figure out why it should.

So my approach treats all shells the same, regardless of the number of nodes.

Also, I didn't see why it was necessary to rescale when it seems straight forward to scale first, then fit all the nodes into that scale.

**Comment by dschult** [comment]
The old code treated shells with single nodes specially because it couldn't use ```rescale_layout``` with a single node (of course, then it didn't rescale at all -- which isn't right either). You are correct that we don't need to rescale using the generic rescale function in shall_layout because we can easily set the scale directly.

Your code can be improved by using ```enumerate()``` to avoid the fairly slow ```list.index``` method in two places. 
If you want to make a pull request that would be great. Otherwise I will make the fix.
