### ISSUE TITLE
`bidirectional_dijkstra` does not use the `weight` function

### ISSUE THREAD

**Issue by mohamed--abdel-maksoud** [networkx/networkx#3754]
I'm on 2.4:
```
In [16]: nx.__version__
Out[16]: '2.4'
```

Here is a minimal example to reproduce:
```python
def cost(a,b,*_):
    print('cost is called')
    return 1

g = nx.grid_graph(dim=[10, 10])
nx.bidirectional_dijkstra(g, (0,0), (9, 1), weight=cost)
```

"cost is called" is never printed.

**Comment by dschult** [comment]
This is a bug -- that function uses "weight" as if it is a string -- not a function. The documentation clearly says it can be either a string or a function. We need to update it to use either a string or a function. Not sure on the history here...
Thanks!
