### ISSUE TITLE
Aric Hagberg

### ISSUE THREAD

**Issue by GCPBigData** [networkx/networkx#3755]
project
https://colab.research.google.com/drive/1Jf-rgGsGtMALNYQznNdlwFoTYE4K4Ecz

Base you project:
https://networkx.github.io/documentation/stable/auto_examples/drawing/plot_weighted_graph.html

The label property, does not work, does not show anything in the graph!

`#!/usr/bin/env python
"""
An example using Graph as a weighted network.
"""
__author__ = """Aric Hagberg (hagberg@lanl.gov)"""
try:
    import matplotlib.pyplot as plt
except:
    raise

import networkx as nx

G=nx.Graph()

G.add_edge('a','b',weight=0.6)
G.add_edge('a','c',weight=0.2)
G.add_edge('c','d',weight=0.1)
G.add_edge('c','e',weight=0.7)
G.add_edge('c','f',weight=0.9)
G.add_edge('a','d',weight=0.3)

elarge=[(u,v) for (u,v,d) in G.edges(data=True) if d['weight'] >0.5]
esmall=[(u,v) for (u,v,d) in G.edges(data=True) if d['weight'] <=0.5]

pos=nx.spring_layout(G) # positions for all nodes

# nodes
nx.draw_networkx_nodes(G,pos,node_size=700)

# edges
nx.draw_networkx_edges(G,pos,edgelist=elarge,
                    width=6)
nx.draw_networkx_edges(G,pos,edgelist=esmall, label='XXXXXXXXXXX'
                    width=6,alpha=0.5,edge_color='b',style='dashed')

# labels
nx.draw_networkx_labels(G,pos,font_size=20,font_family='sans-serif')

plt.axis('off')
plt.savefig("weighted_graph.png") # save as png
plt.show() # display`

Tanks.

**Comment by MridulS** [comment]
@GCPBigData the 'a', 'b', 'c' .. on the nodes you see *are* the labels.

with labels

<img width="465" alt="Screenshot 2019-12-21 at 12 06 24 PM" src="https://user-images.githubusercontent.com/5363860/71311109-64e0e080-23ea-11ea-90a0-372288c52f6f.png">

without labels

<img width="413" alt="Screenshot 2019-12-21 at 12 06 35 PM" src="https://user-images.githubusercontent.com/5363860/71311111-6c07ee80-23ea-11ea-9b81-00d80086a114.png">

**Comment by ericmjl** [comment]
Closing this issue. I think @MridulS has resolved it sufficiently. Please feel free to re-open if this is not the case.

@GCPBigData, we appreciate your posting here, though I think it would also be helpful to take advantage of being able to format your posting properly so that it's easier for the rest of us to read. Please do consider that in the future.
