### ISSUE TITLE
Sudoku graph generator

### ISSUE THREAD

**Issue by Radcliffe** [networkx/networkx#3756]
I propose adding a graph generator for Sudoku graphs.

The Sudoku graph has 81 vertices, corresponding to the cells of an empty Sudoku grid. Two vertices are adjacent if and only if the corresponding cells belong to the same row, column, or 3x3 box. Solving a Sudoku puzzle is equivalent to finding a vertex coloring with nine colors, extending a partial coloring given by the clues.

A Sudoku graph generator would be useful for people who are interested in developing algorithms to solve or generate Sudoku puzzles. The Sudoku graph is also an object of interest for researchers in graph theory and related fields.

I have written code to generate Sudoku graphs and I will submit a pull request. Thank you for your consideration.

**Comment by ericmjl** [comment]
Woohoo! I think this is a pretty rad idea :smile:! Yes, happy to review the PR, please don’t forget to tag me as a reviewer, and don’t forget docstrings and tests!

**Comment by Radcliffe** [comment]
Thanks @ericmji. I have submitted a pull request. #3757

**Comment by ericmjl** [comment]
Awesomeness :smile: I’m on a road trip right now, so if I can, I’ll try to squeeze in some time for a more thorough review. Meanwhile, from a cursory glance, things look good to me. Final approval will have to be on @jarrodmillman and @dschult, naturally.

**Comment by jarrodmillman** [comment]
PR #3757 was merged.
