### ISSUE TITLE
Usage of pygraphviz library which is not compatible with Windows 10, 64bit

### ISSUE THREAD

**Issue by racinmat** [networkx/networkx#3758]
Methods for drawing graphs use pygraphviz library, which is compatible with windows, 64bit library. 
Wouldn't be better to use e.g. pydot library,which is multiplatform?

**Comment by dschult** [comment]
Both pygraphviz and pydot are supported by networkx.
You should be able to use either depending on what you have installed on your machine.

**Comment by racinmat** [comment]
Oh, I see, there is module for that and I totally overlooked it, my bad, thanks.
