### ISSUE TITLE
shortest_path: Return the internal nodes

### ISSUE THREAD

**Issue by bforte** [networkx/networkx#3765]
When using objects that implement their own hash and equality methods this is pretty unexpected behaviour:

```python
import networkx as nx

class Foo:
    def __init__(self, id, foo=None):
        self.id  = id
        self.foo = foo

    def __eq__(self, other):
        return hash(self) == hash(other)

    def __hash__(self):
        return self.id

    def __repr__(self):
        return str(self)

    def __str__(self):
        return f'Foo({self.id}, {self.foo})'

G = nx.Graph()
nodes = [Foo(0, foo='zero'), Foo(1, foo='one')]
G.add_node(nodes[0])
G.add_node(nodes[1])
G.add_edge(nodes[0], nodes[1], weight=1)
w = 'weight'

print(f'{nx.shortest_path(G, Foo(0), Foo(1))}')
print(f'{nx.shortest_path(G, Foo(0), Foo(1), method="dijkstra", weight=w)}')
print(f'{nx.shortest_path(G, Foo(0), Foo(1), method="bellman-ford", weight=w)}')
```

The above program prints

```
[Foo(0, None), Foo(1, one)]
[Foo(0, None), Foo(1, one)]
[Foo(0, None), Foo(1, None)]
```

which seems rather odd. Ie. it reflects the source for all three shortest path methods, but uses the internal node object of the target for `'unweighted'` and `'dijkstra'`.

Since the library will need to use the internal objects for nodes on the path (otherwise one wouldn't need to call `nx.shortest_path`..) it would make for the library to always use the internal nodes. Keeping everything consistent.

So I would expect the above code to print the following:

```
[Foo(0, zero), Foo(1, one)]
[Foo(0, zero), Foo(1, one)]
[Foo(0, zero), Foo(1, one)]
```

**Comment by rossbar** [comment]
I'm not sure I understand the premise. This seems more like an misuse of `__hash__` than a problem in the shortest path algorithms.

**Comment by MridulS** [comment]
Yeah, I'm not sure why would there be an expectation of getting this as the result
```
[Foo(0, zero), Foo(1, one)]
[Foo(0, zero), Foo(1, one)]
[Foo(0, zero), Foo(1, one)]
```
The `source` and `target` are just keys in the dictionary underneath, we do not do anything with the data structure of the node itself. It just needs to be hashable so it can be a key in the dictionary and well if people use the `__hash__` to construct these kinds of classes, we can't really make any promises about how it will work out :)

I'll go ahead and close this issue, feel free to put in any more details if you think that can help us get a better understanding of this! :D
