### ISSUE TITLE
Why is MultiDiGraph.edges.data(keys=False) the default?

### ISSUE THREAD

**Issue by kiryph** [networkx/networkx#3771]
Consider a MultiDiGraph
```
type(G)
Out[275]: networkx.classes.multidigraph.MultiDiGraph
```
`G.edges` returns as expected the source and target nodes and the edge id:
```
G.edges
Out[276]: OutMultiEdgeView([('1_17_0', '2_16_0', 'e001'), ('1_17_0', '2_15_0', 'e002'),
```

However, `G.edges()` and `G.edges.data()` do only return the nodes and not the edge id:
```
G.edges()
Out[277]: OutMultiEdgeDataView([('1_17_0', '2_16_0'), ('1_17_0', '2_15_0'), ...])

G.edges.data()
Out[278]: OutMultiEdgeDataView([('1_17_0', '2_16_0', {'index': 2, 'type': 't', 'transformation': '[[1,0],[0,1]]'}), ('1_17_0', '2_15_0', {'index': 2, 'type': 't', 'transformation': '[[1,0],[0,1]]'}), ...])
```

I have to enable explicitly that the keys should be returned as well:
```
G.edges(keys=True)
Out[279]: OutMultiEdgeView([('1_17_0', '2_16_0', 'e001'), ('1_17_0', '2_15_0', 'e002'),...])
```

Why is this the case?

**Comment by dschult** [comment]
The idea behind that choice of default is to allow code that handles both Graph and MultiGraph. That is, the return value of ```G.edges.data('weight')``` has the same structure whether G is a Graph or a MultiGraph. I think you are pointing out that ```G.edges.data()``` might more naturally include the keys for MultiGraphs. We decided that making people use ```G.edges.data(keys=True)``` would make the code more clear (at least avoid one type of  confusion). If you only use MultiGraphs it might seem unnecessary, but many users use Graph and MultiGraph. Also many developers write code for Graphs and then extend it for MultiGraph. This choice of default makes that easier too.

**Comment by kiryph** [comment]
Thanks for your insight.

Partly, I understand the motivation for this. However, if someone assumes to correctly address edges the same way for `Graph` and `MultiGraph`, he/she also runs into problems and must specialize the code for both types. If the algorithm does not care if there are multi-edges, explicit down conversion from `MultiGraph` to `Graph` could be done as a first step after a `MultiGraph` has been detected. Afterwards the code deals only with one type.
This similar structure of the return value leads easily people to not properly distinguish between the two types.

Anyhow, this certainly looks like a major breaking change which would trigger many issues/problems in codebases relying on this.

**Comment by kiryph** [comment]
Related issue [*Allow G.edges(keys=True) in non-multigraphs* #1934](https://github.com/networkx/networkx/issues/1934)
