### ISSUE TITLE
subgraph_is_monomorphic throws an error

### ISSUE THREAD

**Issue by kanghj** [networkx/networkx#3775]
`subgraph_is_monomorphic` throws a KeyError in some cases. Here is an example for reproduction.

```
import networkx as nx
import networkx.algorithms.isomorphism as iso

G = nx.MultiDiGraph()
G.add_node(1)
G.add_node(2)
G.add_edge(1,2, label="A")
G.add_edge(2,1, label="B")

SG = nx.MultiDiGraph()

SG.add_node(5)
SG.add_node(6)
SG.add_edge(5,6, label="A")

gm = iso.MultiDiGraphMatcher(G, SG, edge_match=iso.categorical_edge_match('label', None))
gm.subgraph_is_monomorphic()
```

Let me know if I can help to fix this. My guess is that the semantic feasibility check in `algorithms/isomorphism/vf2userfunc.py` should do something different when test='mono', but I will need more pointers on this. 

Running `nx.__version__` returns '2.4'

Edit:
Perhaps a fix would be to iterate the edges of G2 (the subgraph) instead of G1 in the semantic feasibility check: 

```
         if self.test == 'mono':
            core_2 = self.core_2
            # 
            for neighbor in G2_adj[G2_node]:
                # G1_node is not in core_1, so we must handle R_self separately
                if neighbor == G2_node:
                    if not edge_match(G1_adj[G1_node][G1_node],
                                      G2_adj[G2_node][G2_node]):
                        return False
                elif neighbor in core_2:
                    if not edge_match(G1_adj[G1_node][core_2[neighbor]], G2_adj[G2_node][neighbor]):
                        return False
```

**Comment by dschult** [comment]
Thanks for the Issue...  and for the Edit--Proposed Fix. 
 
I can verify that this is happening. Haven't been able to look at it hard yet. 
Seems like a bug apparently not covered by any tests...

**Comment by dschult** [comment]
That'd be great! You might start by adding your example as a test... make sure it fails and then put in the fix. :)
