### ISSUE TITLE
What is the difference between enumerate_all_cliques(G) and find_cliques(G)

### ISSUE THREAD

**Issue by alexlenail** [networkx/networkx#3776]
They return different answers, but the documentation does not make clear what distinguishes what they are searching for.

**Comment by dschult** [comment]
Can you be more specific? The documentation seems pretty clear:
https://networkx.github.io/documentation/stable/reference/algorithms/clique.html

**Comment by alexlenail** [comment]
@dschult thank you. For some reason I hadn't visited that page. My apologies.
