### ISSUE TITLE
strange behavoir for contracted_nodes

### ISSUE THREAD

**Issue by hany-mha-ibrahim** [networkx/networkx#3778]
The code below makes a strange behavior as far as I understand the documentation and the source code of the function contracted_nodes.
contracted_nodes is supposed to delete the node contracted, but for some reason, this does not happen in this case. Also, the deleted node should not appear as an incident vertex.

`import networkx as nx`

`G = nx.MultiGraph()`
`G.add_node('3')`
`G.add_node('4')`
`G.add_node('7')`

`G.add_edge('3', '4')`
`G.add_edge('3', '7')`
`G.add_edge('4', '4')`

`print G.nodes() , G.edges()`
`GG= nx.contracted_nodes( G , '3' , '4' );`
`print GG.nodes() , GG.edges()`
G is a multigraph and has a self loop on the node which is suposed to be deleted.

**Comment by dschult** [comment]
When I run that code, it deletes node 4 and replaces the edges with two edges (3, 3).
What do you get? What do you expect? What version of NX are you using (it looks like you are using Python 2 based on print statements)?

**Comment by hany-mha-ibrahim** [comment]
I use Python 2.7

this is what I get when I run the above code
python2.7 testCntractNetworkx.py 
['3', '4', '7'] [('3', '4'), ('3', '7'), ('4', '4')]
['3', '4', '7'] [('3', '3'), ('3', '4'), ('3', '7')]

I expect it to delete node 4 and no edges would appear to node 4 after deleting, but this do not happen as you see.

**Comment by dschult** [comment]
Those problems were fixed in #2586 and #2598
You should probably upgrade to a more recent version of NetworkX.

**Comment by hany-mha-ibrahim** [comment]
Then sorry for posting a repeated one, but thanks for mentioning.
