### ISSUE TITLE
maximum_independent_set results in KeyError: 'Key 1 not found'

### ISSUE THREAD

**Issue by bigmw** [networkx/networkx#3791]
my code:
g1 = nx.from_scipy_sparse_matrix(amat1)
mis = maximum_independent_set(g1)

g1 is an object of networkx.classes.graph.Graph class, with 190 nodes and 1340 edges. the maximum_independent_set() call produced error message below. Not sure what happens except that ramsey_R2() is responsible. Please help. thank you!
Note my networkx version is 2.3, which is needed by another dependent package.

---------------------------------------------------------------------------

KeyError                                  Traceback (most recent call last)

<ipython-input-14-ab4ed828edd9> in <module>()
----> 1 mis = maximum_independent_set(g1)

75 frames

/usr/local/lib/python3.6/dist-packages/networkx/algorithms/approximation/independent_set.py in maximum_independent_set(G)
     60        BIT Numerical Mathematics, 32(2), 180–196. Springer.
     61     """
---> 62     iset, _ = clique_removal(G)
     63     return iset

/usr/local/lib/python3.6/dist-packages/networkx/algorithms/approximation/clique.py in clique_removal(G)
     92     """
     93     graph = G.copy()
---> 94     c_i, i_i = ramsey.ramsey_R2(graph)
     95     cliques = [c_i]
     96     isets = [i_i]

/usr/local/lib/python3.6/dist-packages/networkx/algorithms/approximation/ramsey.py in ramsey_R2(G)
     33     nbrs = nx.all_neighbors(G, node)
     34     nnbrs = nx.non_neighbors(G, node)
---> 35     c_1, i_1 = ramsey_R2(G.subgraph(nbrs).copy())
     36     c_2, i_2 = ramsey_R2(G.subgraph(nnbrs).copy())
     37 

(skip the part repeating the note above on ramsey_R2(G) for ~70 times)

/usr/local/lib/python3.6/dist-packages/networkx/algorithms/approximation/ramsey.py in ramsey_R2(G)
     33     nbrs = nx.all_neighbors(G, node)
     34     nnbrs = nx.non_neighbors(G, node)
---> 35     c_1, i_1 = ramsey_R2(G.subgraph(nbrs).copy())
     36     c_2, i_2 = ramsey_R2(G.subgraph(nnbrs).copy())
     37 

/usr/local/lib/python3.6/dist-packages/networkx/classes/graph.py in copy(self, as_view)
   1547         G.add_nodes_from((n, d.copy()) for n, d in self._node.items())
   1548         G.add_edges_from((u, v, datadict.copy())
-> 1549                          for u, nbrs in self._adj.items()
   1550                          for v, datadict in nbrs.items())
   1551         return G

/usr/local/lib/python3.6/dist-packages/networkx/classes/graph.py in add_edges_from(self, ebunch_to_add, **attr)
    958         >>> G.add_edges_from([(3, 4), (1, 4)], label='WN2898')
    959         """
--> 960         for e in ebunch_to_add:
    961             ne = len(e)
    962             if ne == 3:

/usr/local/lib/python3.6/dist-packages/networkx/classes/graph.py in <genexpr>(.0)
   1548         G.add_edges_from((u, v, datadict.copy())
   1549                          for u, nbrs in self._adj.items()
-> 1550                          for v, datadict in nbrs.items())
   1551         return G
   1552 

/usr/lib/python3.6/_collections_abc.py in __iter__(self)
    742     def __iter__(self):
    743         for key in self._mapping:
--> 744             yield (key, self._mapping[key])
    745 
    746 ItemsView.register(dict_items)

/usr/local/lib/python3.6/dist-packages/networkx/classes/coreviews.py in __getitem__(self, key)
    279         if key in self._atlas and self.NODE_OK(key):
    280             return self._atlas[key]
--> 281         raise KeyError("Key {} not found".format(key))
    282 
    283     def copy(self):

KeyError: 'Key 1 not found'

**Comment by dschult** [comment]
That's a recursion of 75 frames... Seems pretty big -- this algorithm does that. It's recursive.
But it doesn't seem like so many recursions to mess something up.

It's really hard (for me) to see what is going on from that error report. It is clearly looking for the node 1. I believe that, despite the error message, node 1 is in the "self._atlas" view because the call to ```getitem``` is from a loop like:

```python
for key in self._mapping:
    yield (key, self._mapping[key])
```
So 1 should be in ```self._mapping```.  
I'm guessing that means that self.NODE_OK(1) returns False for some reason. 

Any way to narrow this down a little?

**Comment by hagberg** [comment]
No follow up.
