### ISSUE TITLE
Providing some sort of "Edge Flipping" functionality

### ISSUE THREAD

**Issue by aanastasiou** [networkx/networkx#3795]
Just a suggestion, at the moment, it is impossible to flip the direction of an edge (in a directed graph) in a simple way. Instead, what you have to do is recover the edge, get its attributes, remove it and immediately add it in the opposite direction with the exact same attributes (including the edge's ID which would still be used to uniquely identify that edge as part of a path).

**Comment by dschult** [comment]
I think it just amounts to adding and removing an edge something like this:

```python
# setup 
G=nx.path_graph(9, create_using=nx.DiGraph)
G[1][2]['weight']=44
G[1][2]['id']=33
MG=nx.MultiDiGraph(G)
MG.add_edge(1,2,'edgekey1',**{'weight':77})

# flip digraph edge u,v
u,v = 1,2
G.add_edge(v, u, **G[u][v])
G.remove_edge(u, v)

# flip multigraph: edge (u, v, k)
u,v,k = 1,2,'edgekey1' 
G.add_edge(v, u, k, **G[u][v][k])
G.remove_edge(u, v, k)
```

**Comment by aanastasiou** [comment]
Yes. This is what I end up doing. But this results in two recalls (find the edge, grab its data) and one update (add the edge, with its data) when all that is really hapenning for that operation is reversing the direction of the edge.

So, the suggestion is for providing a way to do this quicker, in one modifying operation if such a thing is possible.

**Comment by dschult** [comment]
The data structure we use is adjacency dicts. So switching edges involves changing two entries. The data is not copied anywhere (thank you Python)... only pointers to it. It really should be quite quick.

**Comment by aanastasiou** [comment]
That's good to know, thank you.
