### ISSUE TITLE
Specifying number of shortest_wanted and adding condition on edges attribute

### ISSUE THREAD

**Issue by M-nes** [networkx/networkx#3796]
Hello,

I am working with a **heavy graph** ```G``` that contains subway stations as nodes and paths between stations as edges.
Each edges have two possible attributes:
- ```'walk'``` or ```'subway'``` correspond to the time needed to go from a stop to the other either by walking (when taking the subway is impossible) or by riding the subway.
- ```'time'``` is the time needed to go from a stop to the other without considering the transport type (so for each edge, ```'time'``` = ```'walk'``` or ```'time'``` = ```'subway'```). This is what I use as ```weight``` when I compute the shortest path between two nodes so it consider the trip's total time.

<details close><summary><code> Here is a simplified example of G </code></summary><p>

```
G = nx.Graph()
G.add_nodes_from(['A', 'B', 'C', 'D', 'E', 'F'])
G.add_edges_from([('A', 'B', {'walk': 3, 'time': 3}), ('A', 'C', {'subway': 4, 'time': 4}), ('A', 'D', {'walk': 3, 'time': 3}), 
                  ('C', 'E', {'walk': 3, 'time': 3}), ('D', 'E', {'walk': 3, 'time': 3}), ('B', 'F', {'walk': 3, 'time': 3}), 
                  ('D', 'F', {'subway': 4, 'time': 4}), ('E', 'F', {'walk': 3, 'time': 3})])
nx.draw(G, with_labels=True, font_color='white')

sp = nx.shortest_path(G, 'A', 'F', weight='time')
```

</p></details>

**I have two questions in total:**

- **Is there a way to get, say, the 3 shorter paths between a specific set of nodes?**
As an example, let's consider the three shorter paths between ```'A'``` and ```'F'```: ```A -> B -> F```, ```A -> D -> F``` and ```A -> D -> E -> F```.
As I said I am working with a huge Graph and I compute up to millions of ```shortest_path```. I know I could use ```all_shortest_paths``` and select the ones that interest me but that would take too much time... Is there some options to the ```shortest_path``` algorithm that would allow to specify how many paths to return?

- **Is there a way to put a condition on the number of edges to get?**
More specifically, in this example, I would like to get the shortest path (weighted on ```time```) that has the less number of ```walk``` attribute to the edges (here it would be ```A -> D -> F```). And again, as I am working with tons of paths, using ```all_shortest_paths``` and working on that would be too time consuming...

Any help would be greatly appreciated, I found nothing that could help me with my issues...

**Comment by dschult** [comment]
```all_shortest_paths``` only reports ties. You are looking for non-shortest paths with short length. That is, the 3 shortest paths... I'm not sure that ```all_shortest_paths``` would take much more time. Have you tried it?

You could take the shortest_path algorithm (in ```_dijkdtra_multisource``` within ```networkx/algorithms/shortest_paths/weighted.py```) and try to change the stopping criteria to allow the 3 shortest paths.  It is not a feature we have tried to include up to now.

I don't understand your second question. It sounds like you want to minimize both time and walking distance. That's a 2-D optimization. So, the naive approaches I think of require you to give the relevant tradeoff between walking distance and time.  If you find a way to get a few short paths and want to measure the walking distance for each and pick the one with smallest walking distance, maybe that could work.

**Comment by M-nes** [comment]
> I don't understand your second question. It sounds like you want to minimize both time and walking distance. That's a 2-D optimization.
I would like to minimize ```time``` distance and the number of ```walk``` edges. An example would be: Two paths exist between point ```A``` and ```B```, one considers 5 ```walk``` edges for a certain ```time``` distance ; the other considers only 3 ```walk``` edges for a slightly bigger ```time``` distance. I would like to get the second one instead of the first one since there are less ```walk``` edges even though the total ```time``` is higher.

> You could take the shortest_path algorithm (in _dijkdtra_multisource within networkx/algorithms/shortest_paths/weighted.py) and try to change the stopping criteria to allow the 3 shortest paths. It is not a feature we have tried to include up to now.
I see, I am unsure my python knowledge is high enough to do that easily but I'll keep this thread updated if I find something that could help in the future.

Thank you for your advices!

**Comment by rossbar** [comment]
I'm going to close this one as resolved as it seems like the initial question has been sufficiently addressed and I'm not sure there's anything actionable here. If there are improvements that could be made related to this problem, I'd recommend opening a new issue/PR with the proposed changes (new algorithm, documentation improvements, or whatever) and link back to this one in the discussion. OTOH if I've misunderstood the above, please feel free to reopen!
