### ISSUE TITLE
Edge minimum capacity

### ISSUE THREAD

**Issue by ph4z** [networkx/networkx#3797]
Hi,

As far as I can see the current branch do not support a minimum capacity feature for edges.
It would be a very nice feature to have in a flow algorithm context especially for finance.
For example when you look for an optimal trading path between forex pairs, you do need to implement a minimum order size. 
The C++ lemon [lemon](https://lemon.cs.elte.hu/pub/doc/latest/a00269.html#aa0198dc86458cf5d9893eaac3875faff) library support this type of feature.

**Comment by dschult** [comment]
Do you mean the [minimum cut functionality](https://networkx.github.io/documentation/stable/reference/algorithms/flow.html)?

**Comment by ph4z** [comment]
In the min cost flow function there is a [capacity](https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.algorithms.flow.min_cost_flow_cost.html#networkx.algorithms.flow.min_cost_flow_cost) parameter. It would be great to have a parameter like 'min_capacity' as a capacity lower bound.

**Comment by dschult** [comment]
For the shortest_path routines, we allow the input argument ```weight``` to be a function which takes in the edge datadict and computes the numerical value used. Your request suggests that this same feature would be useful here too.

Let's make the input argument ```capacity``` be either a string (the name of the edge attribute) or a function (inputs: node1, node2, edge_dict and output: number). Then the function allows all kinds of special requests about edge capacities including setting a minimum value. 

As a temporary workaround, you could traverse all edges, creating a new edge attribute (or replacing the one there) that sets the minimum value where needed.

**Comment by boothby** [comment]
I've started looking around the `networkx.algorithms.flow` module and the first thing I noticed is:

```
def _build_residual_network(G, demand, capacity, weight):
    ...
```

Presumably, the `demand` and `weight` functions should receive the same treatment.  However, I'm unsure of how to proceed given a multigraph.  In `shortest_paths`, the situation is simple -- we take the min of edge-weights.  I haven't read enough of the internals to have a good idea if/how these parameters generalize, but at least for `capacity`, the code in `_build_residual_network` preserves the multi-edges; so outputting a single number doesn't really make sense to me.  Thoughts?

**Comment by dschult** [comment]
We'll have to think about what the capacity function should look like. The code currently ignores edge keys completely. The capacity is examined for each edge (whether a multiedge or not).

In ```shortest_path``` we called the function using the edge's node-pair and attribute dict: ```weight(u, v, edgedata)```.  The function is supposed to make sure to handle multiedges if they might arise. Note that users could create weight functions that don't work with multiedges if they don't ever expect to run into that case.

Suppose we make capacity work similarly: ```capacity(u, v, edgedata)``` but for multiedges we assume ```edgedata``` is the attribute dict (not the keydict!).  Notice that we are not allowing the capacity function to know what the edge key is. If there are multiple edges between u and v, capacity will be called with a different ```edgedata``` dict. But otherwise won't know the key of the edge being evaluated.

This code reveals our multiedge wart where we can't use ```G.edges(keys=True)``` for DiGraph. Maybe we can fix that on our way to NX v3.0.  But in meantime, we could restrict the capacity function by not providing the edge key itself to the function.

Actually, all this is unnecessary for the original poster's Issue. It is more efficient to create a new edge attribute for each edge and then run the existing code than it is to have a function compute the capacity each time the edge is observed.  Maybe we should leave it like it is.

Thoughts?

**Comment by ph4z** [comment]
> As a temporary workaround, you could traverse all edges, creating a new edge attribute (or replacing the one there) that sets the minimum value where needed.

This trick will probably work, but I did not had time to test it yet.
Having the capacity paramter as a function would be great. But for the moment I only need to have a capacity lower bound (wich is a very common constraint when you try to solve flow problems).
I guess in future other poeple might ask for this minimum capacity feature.

**Comment by dschult** [comment]
```python
def set_min_capacity(G, min_level, capacity='capacity', adjusted_capacity='adjusted_capacity'):
    for u,v,dd in G.edges(data=True):
        dd[adjusted_capacity] = max(min_level, dd[capacity])
```

**Comment by ph4z** [comment]
As far as I understand this code support only a single minimal capacity value for all edges and if the capacity is below the minimal value, the resulting flow will include paths we don't want because min capacity will be set as max capacity.
As a workaround I am actually checking if resulting flows have values < min capacity and then I delete it if any. But this is not the expected flow.
I guess the way to go is to patch simplex code in order to consider capacity as an inequation.

**Comment by dschult** [comment]
I don't understand what you mean. 
The adjusted capacity is the usual capacity, unless that capacity is below the min_capacity in which case it is t he min_capacity.

What did you want it to be?

**Comment by ph4z** [comment]
> unless that capacity is below the min_capacity in which case it is t he min_capacity.

Indeed, and then if you use the simplex function on such a gaph, it will tolerate flow that are < the adjusted capacity as it will be set a the normal (max) capacity.

The simplex algorithm in the LEMON library has the correct implementation of the flow capacity. I have found [this networkx repository](https://github.com/networkx/networkx-lemon) with the correct implementation [here](https://github.com/networkx/networkx-lemon/blob/master/src/lemon/network_simplex.h#L672)

So will you plan to implement capacities with upper and lower bounds in your simplex function?
If not how do I use this "Addon to interface with LEMON graph library" ?

**Comment by dschult** [comment]
Wow -- I still don't understand. I think either I'm not getting something or you're not. After you adjust the capacity, how come it is not being used?  Do you need to rename the edge attribute "capacity"?  Don't you get to specify which edge attribute holds the capacity value? 

What do you mean by "the correct implementation"? And are you saying that NetworkX has an incorrect implementation?

Maybe it's best to start using a small (2 edge?) example to show each other what we mean.

```python
G=nx.Graph()
G.add_edge(1,2,capacity=5, weight=2)
G.add_edge(2,3,capacity=3, weight=4)
G.node[1]['demand']=-4
G.node[2]['demand']=0
G.node[3]['demand']=4

min_level=4
for u,v,dd in G.edges(data=True):
        dd[adjusted_capacity] = max(min_level, dd[capacity])

flow_cost = min_cost_flow_cost(G, 'demand', 'adjusted_capacity', 'weight') 
```
flow_cost is 24.

**Comment by ph4z** [comment]
See the code below:

```python
import networkx as nx
G=nx.DiGraph()
G.add_edge(1,2,capacity=5, weight=2)
G.add_edge(2,3,capacity=3, weight=4)
G.nodes[1]['demand']=-1
G.nodes[2]['demand']=0
G.nodes[3]['demand']=1

min_level=2
for u,v,dd in G.edges(data=True):
    dd["adjusted_capacity"] = max(min_level, dd["capacity"])
_, flows = nx.network_simplex(G, 'demand', 'adjusted_capacity', 'weight')
print(flows)
```

Resulting flow dict is: `{1: {2: 1}, 2: {3: 1}, 3: {}}`
There is a flow from 2 to 3 of 1 despite min capacity is 2

**Comment by dschult** [comment]
Ahh... then it is not a minimum capacity.  I think you mean you want there to be a minimum flow along that edge.  In this example, what answer do you want it to give? The demand is only 1. How can the flow be 2?

**Comment by ph4z** [comment]
Resulting flow should be > capacity min and < capacity max on all edges.

**Comment by dschult** [comment]
That should probably be called "minimal flow" and "capacity" then....  not capacity min. Since capacity means the maximum flow the edge is capable of.

So, my example would have not a solution then because the demands are less than the minimal flow. This sounds like a different problem. But maybe there is a way to convert it to a problem the current code can work on. 

Does anyone know about flow problems with a minimal flow constraint?

Maybe you run through the minimal flows, changing the demands as needed. Then compute the flow on the resulting network and finally add the minimal flows to the computed flows. For example:
```python
import networkx as nx
G=nx.DiGraph()
G.add_edge(1,2,capacity=7, weight=2, min_flow=2)
G.add_edge(2,3,capacity=5, weight=4, min_flow=1)
G.nodes[1]['demand']=-4
G.nodes[2]['demand']=0
G.nodes[3]['demand']=4

for n, attrdict in G.nodes.data():
    attrdict['adjusted_demand'] = attrdict['demand']
for u, v, dd in G.edges(data=True):
    dd["adjusted_capacity"] = dd["capacity"] - dd["min_flow"]
    G.nodes[u]['adjusted_demand'] += min_flow
    G.nodes[v]['adjusted_demand'] -= min_flow

print(G.node.data())
print(G.edges.data())
_, flows = nx.network_simplex(G, 'adjusted_demand', 'adjusted_capacity', 'weight')
full_flows = {u: {v: flows[u][v] + G[u][v]['min_flow'] for v in flows[u]} for u in flows}
print(full_flows)
```
prints
```
[(1, {'demand': -4, 'adjusted_demand': -2}), (2, {'demand': 0, 'adjusted_demand': -1}), (3, {'demand': 4, 'adjusted_demand': 3})]
[(1, 2, {'capacity': 7, 'weight': 2, 'min_flow': 2, 'adjusted_capacity': 5}), (2, 3, {'capacity': 5, 'weight': 4, 'min_flow': 1, 'adjusted_capacity': 4})]
{1: {2: 4}, 2: {3: 4}, 3: {}}
```

**Comment by ph4z** [comment]
Sorry for this (very) late reply, but yes, this trick work. 
Maybe you should consider adding a note on simplex documentation regarding this case.
Thanks a bunch for your help!

**Comment by ph4z** [comment]
In fact, it seems to work only for graphs with a single simple path and if source and sink are the first and last node on path.
In the example you provided, if you add:
```python
G.add_edge(3,4,capacity=5, weight=4, min_flow=1)
G.nodes[4]['demand']=0
```
It raises the unfeasible exception

**Comment by dschult** [comment]
Yes -- changing the network can/does make the flow infeasible.  Especially if you require a minimum flow level to a node with no outputs and no demand.  That's infeasible without considering any other part of the graph.  The code still works  -- your request doesn't have a solution.

**Comment by AbhayGoyal** [comment]
Hey, maybe adding this feature might help. I guess just having a check should help ease out right? Correct me if I am wrong

**Comment by dschult** [comment]
I don't think there is any feature to add. The code works as is and does what it says it does.
The result from some examples is raising the unfeasible exception and that is what it should do when there is no solution.  

The only suggestion i see coming out of this thread is perhaps adding documentation saying that: 
If you want minimum flows across specific edges, then you should 
1) change the problem to reduce the capacities of those edges by the minimum flow desired, 
2) solve the resulting flow problem
3) add the minimum flows to the edge flows obtained in your solution.
But I'm not sure this even makes sense to put into the docstring... There are so many other similar variants of problems that can be converted into the desired form. We don't really want to get into listing all possible problems that can be converted into this problem...

**Comment by AbhayGoyal** [comment]
And where should we add it? Like this note

**Comment by dschult** [comment]
I'm going to close this as the code works as is, and the documentation for how to convert this problem into one that our function solves is very problem specific and would lead to many long variants of the problem described in the docs.  If people are interested, post to this issue and we'll see it, or open a New Issue.
