### ISSUE TITLE
want to add new feature(3d graph plotting with matplotlib)

### ISSUE THREAD

**Issue by ss-ghule** [networkx/networkx#3800]
As far as I know, drawing methods like draw(), draw_networkx() and other similar methods do not support 3d plots with matplotlib (correct me if I am wrong).
I am also aware that mayavi can be used for the 3d plotting but for my personal project I want 3d plotting functionality through methods like draw(), draw_networkx() etc.

I would like to add this feature to the networkx module, but want some feedback if its worth working on it?

**Comment by dschult** [comment]
We wrote much of the drawing code before matplotlib had 3d plotting. I don't think it would be too hard to make it work. I haven't looked at mayavi recently, but it used to be a respected and effective 3D modeling/visualizing system. I wouldn't be too concerned about whether users need to say "nx.draw" or "nx.draw_3d" or "nx.draw_mayavi". As you indicate, it would be nice to have some functions for 3d -- whether they are the default tool or not is a separate question.

We've got @ericmjl who is the primary author of nxviz. We've also got some heavy lifters in the matplotlib world (like @tacaswell ) plugged into GraVe. Learning more about those packages may be helpful in this effort too.

**Comment by boothby** [comment]
I hacked something together recently -- it's nowhere up to snuff, but it might be a start for a quick matplotlib implementation:

```
import networkx as nx
from matplotlib import pyplot as plt
def draw3d(G, pos):
    ax = plt.gca(projection='3d')
    X, Y, Z = zip(*pos.values())
    ls = [[pos[u], pos[v]] for u,v in G.edges()]
    lc = Line3DCollection(ls, linewidths=0.5, colors='b')
    ax.add_collection(lc)
    ax.plot(X, Y, Z, '.r', markersize=3)

g = nx.GridGraph([3,3,3])
draw3d(g, pos)
plt.show()
```

**Comment by ss-ghule** [comment]
Thanks for the feedback. I agree with @dschult , this may not be the desired feature by other users as it can be easily achieved using other respected libraries. As I am dealing with molecules in my project and using networkx for their representation, I felt it would be nice if I could plot 3d molecules using native drawing methods of networkx. At this point I might be the only one who wants this feature but 
I believe it might help others like me in future. Another reason is that I am interested to know how to contribute to open-source projects and starting with some easy to implement feature would a good start. Thanks @boothby for the code snippet.

**Comment by dschult** [comment]
The algorithmic part of 3d network drawing is finding good layout algorithms. 
Do you know any for molecules?

**Comment by ss-ghule** [comment]
If I understand correctly, here 'layout' means a set of cartesian coordinates (x,y,z) for each node in the graph. 
In the graph representation of a molecule, nodes are atoms and bonds are edges. Therefore, the layout is a set of cartesian coordinates of all atoms in a molecule. For the molecules, we don't need layout algorithms, but the user is supposed to provide a layout (coordinates of all atoms) for drawing. In my case it very easy to get atomic coordinates and I think anybody working with molecules should have some way to obtain them.

But networkx deals with all kinds of graphs. If I were to add 3d plotting feature, it should able to handle not only molecules but other types of graphs as well for which user may not able to provide the layout. In such scenarios, we need layout algorithms. 

To be honest, I did not think of it in general sense; I was only thinking on the line of my particular case.  If it is not very complicated, by study existing layout algorithms, I might able to extend them for 3d drawing.

**Comment by dschult** [comment]
If you already have the cartesian coordinates in a dict keyed by node to (x,y,z), then @boothby 's code looks pretty effective. If you don't have experience with 3d layout algorithms you could focus on the drawing part first. Those are currently largely separated for 2d functions in NetworkX.

**Comment by ss-ghule** [comment]
Thanks for the suggestions! As I don't have any experience with 3d layout algorithms I will focus on drawing part. If the implementation is successful I will create a pull request

**Comment by rossbar** [comment]
There hasn't been any activity here in a while so I'm going to close this for now. Please feel free to reopen this if interested in continuing the discussion!

**Comment by ss-ghule** [comment]
Sure!
I am really sorry got busy with something else, I still plan to work on this issue but it's better to keep it close for now.
