### ISSUE TITLE
Finding the most frequent path / most used path / high density path

### ISSUE THREAD

**Issue by Villa74** [networkx/networkx#3801]
Once a MultiDiGraph is created, is there any way to find the most used path.

**Comment by dschult** [comment]
Turn it into a shortest_path problem 
(??weights -> 1/weights...   use -> 1/use??  If floating point and ties are important, turn into integers)
For multiedges, use the ```weight``` *function* capability:

```python
def myweight(u, v, edgedata):
    return min([1 / datadict['use'] for key, datadict in edgedata.items()])

nx.shortest_path(G, source, target, weight=myweight)
```

**Comment by Villa74** [comment]
Thank you dschult..!

Let me briefly explain my issue.
I have like 4.5k nodes and around 2.8M edges in a network.  I don't know the source or target i want.  what i am trying to find is 

if i say n = 5 regardless of source / target, i want the most travelled(used)  'n' nodes from the Graph.

If i am not clear, let me know so i will elaborate it more.

**Comment by dschult** [comment]
It sounds like you might be looking for a measure like: ```betweenness_centrality```

If you want to know which nodes appear on the most shortest paths, that is what betweenness centrality measures. That function computes it for all nodes, but then you have to sort the results and select the top "n" of that sorted list.

**Comment by Villa74** [comment]
Thanks for the answer! I think we are not explaining it correctly,

Let me put in this way, for example :  we have 10 stations and the passengers move across these stations (without coming back to the same station again). We want to see the sequence of combination of stations that are mostly linked, 

 ex events in the graph: 
(1-4-5-7)  may have 10 people
(1-3-4-5) may have 15 people
(1-3) may have 30 people
(1-3-4-5-7) have 4 people
(1-5-2-3-4) have 1 

when we set the minimum number of stations as 4 we need to get (1-3-4-5), and if we set minimum number of stations as 5 we should be getting  (1-3-4-5-7)

Note : the passengers can also travel in any direction, we have a bi-directional graph

**Comment by rossbar** [comment]
This issue has been inactive for a while so I will close it. If the question persists please feel free to reopen, preferably with a minimum example with a small graph and the desired result(s)/behavior (the previous example didn't provide any further clarity on the problem for me).
