### ISSUE TITLE
Question: why `nx.subgraph_view` is amazingly faster than `G.subgraph().edge_subgraph()`? 

### ISSUE THREAD

**Issue by frhyme** [networkx/networkx#3802]
Last night, i just wonder the way to extract sub-Graph from original graph using NetworkX.
There are two ways to extract it. 

**The first one** is `nx.subgraph_view(G, filter_node, filter_edge)`, 
the type of parameter `filter_node`, and `filter_edge` are just function. 

**The second one** is `G.subgraph(nodes).edge_subgraph(edges)`.
Using chaining method, filtering nodes and filtering edges.
the type of parameter `nodes` and `edge` is just `list` of string(node_name, or edge tuple)

I conduct a simplex experiment to check which one is faster. 
**In conclusion, `nx.subgraph_view(G, filter_node, filter_edge)` is about 3000 times fater than `G.subgraph(nodes).edge_subgraph(edges)`**

I can't understand why it happend even if I read the documentation of Networkx.
If there are anyone to know why this happened, please tell me. 

Thanks for your help in advance. 
If you didn't understand my questions or feel impolite that, it is cause by my lack of english. 
Sorry about that. 

the ouput of experiment and code for experiment are below. 

```
== Graph Generation Done
nx.subgraph_view(G)         :     0.000141
G.subgraph().edge_subgraph():     0.485764
========================================
```

```python
import networkx as nx
import numpy as np
import time

# GENERATE Graph size
N = 1000  # 3000
p = 0.6
G = nx.fast_gnp_random_graph(N, p)

# UPDATE weight-dict for nodes and edges
node_weight_dict = {n: v for n, v in zip(G.nodes(), np.random.uniform(0, 1, len(G.nodes())))}
edge_weight_dict = {e: v for e, v in zip(G.edges(), np.random.uniform(0, 1, len(G.edges())))}
for n in (n for n in G.nodes()):
    G.nodes[n]['weight'] = node_weight_dict[n]
for e, v in edge_weight_dict.items():
    G.edges[e]['weight'] = edge_weight_dict[e]
print("== Graph Generation Done")
#print("==" * 20)

########################################
# USE nx.subgraph_view(G, filter_node, filter_edge)
########################################
start_time = time.time()
nx_subG = nx.subgraph_view(G=G,
                           filter_node=lambda n_name: True
                           if G.nodes[n_name]['weight'] > 0.5 else False,
                           filter_edge=lambda n1_name, n2_name: True
                           if G.edges[
                               (n1_name, n2_name)]['weight'] > 0.5 else False)
#print(G.nodes(data=True))
print(f"nx.subgraph_view(G)         : {time.time() - start_time:12.6f}")
#print(f"FROZEN: {nx.is_frozen(nx_subG)}")
########################################
# G.subgraph().edge_subgraph()
########################################
start_time = time.time()
# make node subg
NODE_subG = G.subgraph(
    nodes=(n for n, n_attr in G.nodes(data=True) if n_attr['weight'] > 0.5))
# make edge subg
subG = NODE_subG.edge_subgraph(
    edges=((e1, e2) for e1, e2, e_attr in NODE_subG.edges(data=True)
           if e_attr['weight'] > 0.5))
print(f"G.subgraph().edge_subgraph(): {time.time() - start_time:12.6f}")
#print(f"FROZEN: {nx.is_frozen(subG)}")
print("=="*20)

assert len(nx_subG.nodes()) == len(subG.nodes())
assert len(nx_subG.edges()) == len(subG.edges())
# Checking isomophism by is_isomorphic is better and exact but it takes much time.
# print(nx.is_isomorphic(subG, nx_subG))
```

**Comment by MridulS** [comment]
@frhyme the bottleneck here is using `(e1, e2) for e1, e2, e_attr in NODE_subG.edges(data=True)
           if e_attr['weight'] > 0.5)`  to create the filtered list of edges to keep in the new subgraph. This alone will take up the most time as for loops are generally very expensive in terms of compute time in python.
Coming to why you should use `subgraph_view` over chaining it like `subgraph(nodes).edge_subgraph(edges)`,  by using `lambda` in `subgraph_view` you force `nx_subG` to be a lazy evaluated and it always stays a view. By chaining it in `G.subgraph(nodes).edge_subgraph(edges)` it becomes a view of a view. 

To better understand what I mean by a view of a view.

``` python
>>> nx_subG._node
FilterAtlas({0: {'weight': 0.08474794689102627}, 1: {'weight': 0.7485890441372873}, 2: {'weight': 0.0069110208643630155}, 3: ..........
>>> subG._node
FilterAtlas(FilterAtlas({0: {'weight': 0.08474794689102627}, 1: {'weight': 0.7485890441372873}, 2: {'weight': 0.0069110208643630155}, 3: {'we

```
One is creating a FilterAtlas once and the other one in chaining two FilterAtlas.

This takes us to the functionality of `nx.subgraph_view(G, filter_node, filter_edge)` and  `G.subgraph(nodes).edge_subgraph(edges)`. This may look like they are doing the same thing but they won't necessarily give you same results. `nx.subgraph_view(G, filter_node, filter_edge)` will be the union of filters while `G.subgraph(nodes).edge_subgraph(edges)` will stack the edge filter on top of node filter. Example:

```
>>> import networkx as nx
>>> G = nx.Graph([(0, 1), (1, 2)])
>>> G.add_node(3)
# filter nodes 0, 1, 3 and filter edges to only (0, 1)
>>> union = nx.subgraph_view(G, filter_node=lambda x: True if x in [0, 1, 3] else False,
                    filter_edge=lambda e1, e2: True if (e1, e2) in [(0, 1)] else False)
# same done using stacking/chaining
>>> stack = G.subgraph(nodes=[0, 1, 3]).edge_subgraph(edges=[(0, 1)])

>>> union.nodes()
NodeView((0, 1, 3))
>>> stack.nodes()
NodeView((0, 1))
```

Let me know if this makes sense!

**Comment by frhyme** [comment]
@MridulS  I really appreciate your response. 
As you showed in your answer, the both results could be different. 
because `nx.subgraph_view` do it like filter union. 
and `G.subgraph` do it like filter stack(series of filter).
so, `G.subgraph().edge_subgraph` could be slower than `nx.subgraph_view`.

And then, I want to check it more. 
I conduct similar experiment, but in this time just filtering only nodes. 
However, it still, `nx.subgraph_view` is amazingly faster than `G.subgraph`
the ouput is in here.

```
== Graph Generation Done
nx.subgraph_view(G):     0.000045
G.subgraph()       :     0.001359
========================================
```

the code is below. 

```python
import networkx as nx
import numpy as np
import time

# GENERATE Graph size
N = 4000 # 3000
p = 0.6
G = nx.fast_gnp_random_graph(N, p, seed=0)

# UPDATE weight-dict for nodes and edges
node_weight_dict = {
    n: v
    for n, v in zip(G.nodes(), np.random.uniform(0, 1, len(G.nodes())))
}
for n in (n for n in G.nodes()):
    G.nodes[n]['weight'] = node_weight_dict[n]
print("== Graph Generation Done")
#print("==" * 20)

########################################
# USE nx.subgraph_view(G, filter_node, filter_edge)
########################################
start_time = time.time()
nx_subG = nx.subgraph_view(G=G,
                           filter_node=lambda n_name: True
                           if G.nodes[n_name]['weight'] > 0.5 else False,
                           filter_edge=lambda n1, n2: True)
print(f"nx.subgraph_view(G): {time.time() - start_time:12.6f}")

########################################
# G.subgraph()
########################################
start_time = time.time()
# make node subg
subG = G.subgraph(nodes=(n for n, n_attr in G.nodes(data=True) if n_attr['weight'] > 0.5))
# make edge subg
print(f"G.subgraph()       : {time.time() - start_time:12.6f}")
print("==" * 20)
#print(len(nx_subG.nodes()))
#print(len(subG.nodes()))
assert len(nx_subG.nodes()) == len(subG.nodes())
assert len(nx_subG.edges()) == len(subG.edges())
# Checking isomophism by is_isomorphic is better and exact but it takes much time.
# print(nx.is_isomorphic(subG, nx_subG))
```

I am really grateful for your support and answer.

**Comment by MridulS** [comment]
The reason for this discrepancy is because of lazy evaluations.
`G.subgraph` takes in an explicit container of nodes while `nx.subgraph_view` takes in a callable, in this case a `lambda` function.

In the following example you can look at the difference between the filters, one is a `show_nodes` and other is `lambda`.  
``` python
>>> nx_subG._node
FilterAtlas({0: {'weight': 0.00767033093403946}, .... 4: {'weight': 0.308129712638896}},
 <function <lambda> at 0xa495783b0>)
>>> subG._node
FilterAtlas({0: {'weight': 0.00767033093403946}, ... 4: {'weight': 0.308129712638896}},
<networkx.classes.filters.show_nodes object at 0xa2fa39810>)
```
`subG._node` is already evaluated while ` nx_subG._node` isn't evaluated yet as it needs to pass through the `lambda` function.

Let's see what happens once both are evaluated.

``` python
>>> %%timeit
>>>  nx_subG.copy()
19.9 s ± 2.6 s per loop (mean ± std. dev. of 7 runs, 1 loop each)

>>> %%timeit
>>> subG.copy()
11.9 s ± 59.4 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```
As you can see `nx.subgraph_view` is faster than `G.subgraph` while creating the subgraph but its the other way round once we need to copy the subgraph into a new graph. (i.e. evaluating them)

This is absolutely required if you want to play around with the this filtered subgraph as a view just gives a view of the original graph, if you try manipulate `subG` or `nx_ subG` you will end manipulating the original graph `G.`

**Comment by frhyme** [comment]
I really appreciate you response. It is really helpful to me and my understanding. 
I think that I understand the reason completely. 

Even though I am still a little confused why the two same method(`nx.subgraph_view` and `G.subgraph`) except "Lazy Evaluation" should exist at the same time. 
In my though, It might be better to keep just one function. 

I really appreciate your support. Moreover I should study `Networkx` more especially `FilterAtlas`. 
Thanks.

**Comment by dschult** [comment]
```subgraph_view``` allows any filter function. ```G.subgraph``` is the common use case.
The time spent creating the subgraph view is not usually important compared to the time using it.
So we make the common use case fast in ```G.subgraph``` and the more flexible case is slower.
