### ISSUE TITLE
Option to not rescale a layout

### ISSUE THREAD

**Issue by stefanhannie** [networkx/networkx#3808]
Hi,

I'm wondering if rescaling layouts can be an optional procedure for all layouts. I've noticed that this is implemented for the `fruchterman_reingold_layout` but no others.

**Comment by stefanhannie** [comment]
I've shared a possible solution in #3809.

**Comment by dschult** [comment]
Interesting idea. Can you say how this would help, and/or why this is a good thing?

The implementation seems to work fine. But of course, every layout has a scale. So this would probably need docs to explain what the scale would be for each layout function. ?? or maybe not and users try it to figure it out?

**Comment by stefanhannie** [comment]
My use case is probably somewhat limited, but I'm wanting this feature so that I can compute the value of the following function:
```python
sum((distance_G(u,v) - distance_layout(u,v))**2 for u, v in combinations(G,2))
```

The value of this function can change quite a bit if the `distance_layout` is a scaled layout vs the original one. 

The function above is close to the function that is being minimized in the Kamada Kawai algorithm (see equation [1] https://bit.ly/31prZP1). So in a sense, I'm sort of asking how well the Kamada Kawai algorithm is doing when it tries to match graph distance to euclidean distance. I'm also hoping to compute the above function for several different layouts--in order to compare them and see how well they are capturing the graph distance.

With regard to documenting the scale for each layout function, that's a good point. My hope was to leave default values in place and let layouts fall as they were before, and only have this feature for the curious, but perhaps that's not the best idea. Some rough idea of scale might be wise.

**Comment by dschult** [comment]
In their paper, they use L_o to denote the size of the display area. That determines the scale of their layout. So, whether you choose to scale or not, you are still choosing a scale. Isn't it better to control the scale?

Your ```distance_G -distance_layout``` is a good example. The value changes a lot depending on the scale of the layout. It also depends a lot on the scale of distance_G. You better know what those scales are to interpret your results. Most likely you will want to set the scales for both ```distance_G``` and the layout to make them comparable.

**Comment by stefanhannie** [comment]
Right, they have `L` as "the desired length of a single edge in the display plane", and I'm wanting to set `L = 1`, i.e. I'm curious what happens when `l_i,j = d_i,j`. This way I can compare distance in the graph `distance_G` (`d_i,j`) and distance in the plane `distance_layout` (`|p_i - p_j|`) and see how close they are matching.

I've been reading the implementation of `_kamada_kawai_costfn`; I'm trying to figure out where the value of `L` or `L_0` is being set, but I can't quite find it. 

But essentially what I'm hoping for is access to the raw values of the points `p_i` from the algorithm when `L = 1`--which I was thinking I could access if the layout wasn't passed through the networkx `rescale_layout` function.

**Comment by dschult** [comment]
Good -- then I think we understand each other.  I believe the paper has L related to L_0 in a way that depends on the number of edges so L can be much smaller than the size of the whole layout. 

I'm guessing that the code knew it would rescale at the end (to make L_0 be 1... or maybe it is 2 because it can go 1 each direction from the center (diameter is 1)), so it may not explicitly set L_0, just using 1 without writing it. But it has been along time since I looked carefully at that code. You'll probably need to look at the paper to get the relationship between L_0 and L and work from that.   :)

**Comment by stefanhannie** [comment]
I've found a nicer way to get a hold of what I was wanting--metric space distortion (the curious can see 1.4 in https://ttic.uchicago.edu/~harry/teaching/pdf/lecture1.pdf). The distortion is invariant under layout scaling, so instead of computing the above function I mentioned, I'm going to compute the distortion. 

With that said, I think I'll close my pull request as I don't see a need for it now. Feel free to reopen if you would like. @dschult thanks for your help :)
