### ISSUE TITLE
Is nx.communicability the sum of **Closed walks**?

### ISSUE THREAD

**Issue by frhyme** [networkx/networkx#3811]
It might be a very minor issue. 

In the documentation about [networkx - Communicability](https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.communicability_alg.communicability.html#networkx.algorithms.communicability_alg.communicability), it was written like below. 

> The communicability between pairs of nodes in `G` is the sum of **closed walks** of different lengths starting at node `u` and ending at node `v`.

I've learned that **Closed walks** means "A walk if the starting vertex is the same as the ending vertex" otherwise the walk is Open. However, `nx.communicability`computes also the communicability between different nodes so, I think it would be better **closed walks** is changed to just **walks**. 

If I'm wrong, please tell me. 
I always thanks for your help.

**Comment by dschult** [comment]
Yes -- you are right. It should just be a walk (remove "closed") for both ```communicability()``` and ```communicability_exp()```.  That's been there for over 9 years. :}

**Comment by frhyme** [comment]
Thanks for your response.
