### ISSUE TITLE
nx.adj_matrix problem.

### ISSUE THREAD

**Issue by hIxiIan** [networkx/networkx#3814]
First of all, thank you for your help.

The problem was descrbied in the picture.
![image](http://m.qpic.cn/psc?/V14Fw09m3597EF/*WtXjnRZF6sK3v08qdlmv6cA7bORdLiApt5fdpXS7ZlEbLnh2ThCKDqAb6fSMO5T430nRsWFK4HVB6XFMt*cpa8c54wmQyNxSpKRZuzsLdg!/b&bo=TAQFA0wEBQMDGTw!&rf=viewer_4)

code are as follows:

```python
def attackGraph(G,vi,vj,add_link):
    vi = str(vi)
    vj = str(vj)
    if add_link:
        G.add_edge(vi,vj)
        G.add_edge(vj,vi)
        G.edges[vi,vj]['weight'] = 1.0
        G.edges[vj,vi]['weight'] = 1.0
        print ('add link str(vi),str(vj)',vi,vj,G.has_edge(vi,vj))
    else:
        self.graph.G.remove_edge(vi,vj)
        self.graph.G.remove_edge(vj,vi)

G2 = Graph()
G2.read_edgelist(filename="data/cora/cora_edgelist.txt")
G2.read_node_label("data/cora/cora_labels.txt")
G2.read_node_features("data/cora/cora.features")


ai
G2.G[str(ai)]
**output:
2596
AtlasView({'2669': {'weight': 1.0}, '2680': {'weight': 1.0}, '2686': {'weight': 1.0}})**


ai,bi,ci,di
nx.adj_matrix(G2.G)[ai,bi]
nx.adj_matrix(G2.G)[ci,di]
**output:
(2596, 1953, 2352, 2064)
0.0
0.0**


attackGraph(G2.G,ai,bi,True)
**output:
add link str(vi),str(vj) 2596 1953 True**


G2.G[str(bi)]
**output:
AtlasView({'2107': {'weight': 1.0}, '2596': {'weight': 1.0}})**


ai,bi,ci,di
nx.adj_matrix(G2.G)[bi,ai]
nx.adj_matrix(G2.G)[di,ci]
**output:
(2596, 1953, 2352, 2064)
0.0
1.0**

```

**Comment by dschult** [comment]
The index in the matrix is not the index in the graph. 
Your graph nodes are strings if I understand right. 
Even if they were numbers, they don't get lined up with the corresponding row/column of the adjacency_matrix. To specify an order of the rows/columns, use the ```nodelist``` optional argument to ```nx.adj_matrix```.

**Comment by hIxiIan** [comment]
> The index in the matrix is not the index in the graph.
> Your graph nodes are strings if I understand right.
> Even if they were numbers, they don't get lined up with the corresponding row/column of the adjacency_matrix. To specify an order of the rows/columns, use the `nodelist` optional argument to `nx.adj_matrix`.

Thank you dschult!
Your answser inspires me to read official documents firstly.
