### ISSUE TITLE
`networkx.power()` does not preserve edge attributes

### ISSUE THREAD

**Issue by aanastasiou** [networkx/networkx#3821]
Given:

```
import networkx

G = networkx.Graph()
G.add_edge(0,1)
G.add_edge(1,2,alpha=2)
G.add_edge(2,3)

U = networkx.power(G,2)

E1 = G.edges(data=True)
E2 = U.edges(data=True)
```

E1 might carry some attributes but E2 which is a superset of E1 does not carry any attributes.

Would something like:

```
(n, nbr,{}) if not G.has_edge(n,nbr) else (n,nbr,G.edges[n,nbr]) for nbr in seen 
```

(not exactly like this, it could potentially be confined only to the edges of ``n``, since this is the node of interest at each iteration, but I hope it conveys the idea).

potentially introduce large delays at [this point](https://github.com/networkx/networkx/blob/master/networkx/algorithms/operators/product.py#L334)? Could it be activated on demand with the node/edge parameter convention of `data=True`?

**Comment by dschult** [comment]
I think it could just be ```(n, nbr, G[n][nbr]) for nbr in seen```
I guess it could make the new graph take up more memory.
But I think it is worth it. If someone cares a lot about that they 
can strip the attributes before raising it to a power.

**Comment by aanastasiou** [comment]
Thank you.

I do not see how the new graph would take more memory, at least on the basis of copying across the edge attributes...except if I am missing something here (?). Suppose a C4 had all 4 edges having data. Its square is the K4 with 6 edges but still only 4 of them copy across their original data (hence the whole edge checking).

Shall I do a PR along these lines or has it become part of another item?

**Comment by dschult** [comment]
Ahhh...  I see now... You aren't putting data on the edges that are added. Only on the dges that are copied from the original. I'm understanding better now. Sorry for not understanding better before. My suggestion for a shorter edge prescription doesn't work then... :{

Also, I now understand why you are thinking the memory won't matter much. I was worried about putting an edge attribute on all the new edges. That's not what you are saying...

But my better understanding also makes me less inclined to do the attribute copy by default. Why do you want those old edge attributes if 1) they are already on the original graph, and 2) the new power edges don't have them?

If you need them only for original edges, then look at the original graph. And if you want to expend them to all edges, its pretty easy (and problem specific) to add the edge attributes you do want. Something like:

```python
for u, v, dd in G.edges.data():
    U.add_edge(u, v, dd)  % add data from original edges in G
for u, v in U.edges:
    if v not in G[u]:   % update any edges not in G
        U[u][v][stuff] = function_to_compute_stuff
```

But I may be missing something again...

**Comment by aanastasiou** [comment]
> Why do you want those old edge attributes 

Because what I receive is a graph specification (let's say `G`) but what I actually want to work on is `G**2`

> ```
> for u, v, dd in G.edges.data():
>    U.add_edge(u, v, dd)  % add data from original edges in G
> ```

...or that which is probably the simplest. :D  (also, please see below).

I think I have been trying to obtain a difference over a multigraph (which edges were both in the original graph **and** its power) when I can form the multigraph by the union of the edge sets. Then, single edges were added by the power, double edges where there in the original graph too.

And the flaw at that moment was thinking in terms of a multigraph when `power()` still returns graph.

Thank you very much anyway :)
