### ISSUE TITLE
connected_components should return frozensets

### ISSUE THREAD

**Issue by rsokl** [networkx/networkx#3823]
`connected_components` yields sets in a way that requires that they not be mutated during iteration:

https://github.com/networkx/networkx/blob/aeeeef92f2229b0cc8ebbbbfcfc87128f546d55f/networkx/algorithms/components/connected.py#L60-L65

This can lead to silent-but-deadly behavior. E.g. If I were to pop from these sets during iteration, which is a very natural way to access a node from each connected component,

```python
# getting a node from each component
[s.pop() for s in my_connected_components]
```
then the same connected component may be visited multiple times during the iteration.

This generator should yield `frozenset` objects instead so that the user cannot unwittingly produce such corrupt behavior.

**Comment by rsokl** [comment]
(or you can just flip line 45 with line 46!)

**Comment by dschult** [comment]
Yes -- it looks like we should swap lines 64 and 65 in ```connected.py```
Thanks!!

**Comment by dschult** [comment]
@boothby has a slightly better solution in #3859 where in addition to switching lines 64 and 65, we change ```_plain_bfs``` to return a set instead of yielding each node. Look good?

**Comment by rsokl** [comment]
Looks good! Thanks
