### ISSUE TITLE
 Missing commands in networkx version 2.3

### ISSUE THREAD

**Issue by ivan-marroquin** [networkx/networkx#3824]
Hi there,

I have Python 3.6.5 on a windows machine with networkx 2.3. I used this code to convert a dataframe into a graph:

import numpy as np
import networkx as nx
import matplotlib.pyplot as plt

ind1= [5,10,3,4,8,10,12,1,9,4]
ind5=[1,1,13,4,18,5,2,11,3,8]

df = pd.DataFrame({ 'A':ind1, 'B':ind1 + np.random.randint(10, size=(10)) , 'C':ind1 + np.random.randint(10, size=(10)) , 'D':ind1 + np.random.randint(5, size=(10)) , 'E':ind1 + np.random.randint(5, size=(10)), 'F':ind5, 'G':ind5 + np.random.randint(5, size=(10)) , 'H':ind5 + np.random.randint(5, size=(10)), 'I':ind5 + np.random.randint(5, size=(10)), 'J':ind5 + np.random.randint(5, size=(10))})

corr= df.corr()
links.columns= ['var1', 'var2','value']

Then, I tried these two commands:
a) G= nx.from_pandas_dataframe(links, 'var1','var2')
b) G= nx.convert_matrix.from_pandas_dataframe(links, 'var1','var2')

Both commands produced this error message: module 'networkx' has no attribute '...'

According to online documentation, these commands should be available: https://mriduls-networkx.readthedocs.io/en/latest/reference/generated/networkx.convert_matrix.from_pandas_dataframe.html

Any suggestions?

Ivan

**Comment by dschult** [comment]
??? What is ```links```?
Also, include your code inside 

\`\`\`python
 stuff
\`\`\`
to make it appear nicely

**Comment by ivan-marroquin** [comment]
Sorry for the confusion.

Here is the line command that I missed:

'''
links= corr.stack().reset_index()
'''

**Comment by dschult** [comment]
Good -- that makes it clear that links is an edgelist stored in a dataframe.
Pandas data frames can also store adjacencies so... We split the function into two functions.
```nx.from_pandas_edgelist``` (which is what you want) and ```nx.from_pandas_adjacency```

https://networkx.github.io/documentation/stable/reference/convert.html#pandas

**Comment by ivan-marroquin** [comment]
Thanks!
