### ISSUE TITLE
I think `nx.vote_rank` make wrong result.

### ISSUE THREAD

**Issue by frhyme** [networkx/networkx#3826]
As the `vote_rank` algorithm was written in the origianl paper [Identifying a set of influential spreaders in complex networks](https://www.nature.com/articles/srep27823), **the voting ability of already elected nodes have to be zero**. 

But, in `networkx.vote_rank`, the voting ability of already elected node could be negative value. 
To check if the voting ability could be negative value, I copied the code of `nx.vote_rank` from [networkx documentation](https://networkx.github.io/documentation/stable/_modules/networkx/algorithms/centrality/voterank_alg.html#voterank), and add simple code that print node having negative value. 

```python
def voterank(G, number_of_nodes=None, max_iter=10000):
    voterank = []
    if len(G) == 0:
        return voterank
    if number_of_nodes is None or number_of_nodes > len(G):
        number_of_nodes = len(G)
    avgDegree = sum(deg for _, deg in G.degree()) / float(len(G))
    # step 1 - initiate all nodes to (0,1) (score, voting ability)
    for _, v in G.nodes(data=True):
        v['voterank'] = [0, 1]
    # Repeat steps 1b to 4 until num_seeds are elected.
    for _ in range(max_iter):
        # step 1b - reset rank
        for _, v in G.nodes(data=True):
            v['voterank'][0] = 0
        ####################################
        ####################################
        # this code was added by me to check if voting ability is negative
        for n in G:
            node_voting_ability = G.nodes[n]['voterank'][1]
            if node_voting_ability < 0.0:
                print(n, node_voting_ability)
        ####################################
        ####################################
        # step 2 - vote
        for n, nbr in G.edges():
            G.nodes[n]['voterank'][0] += G.nodes[nbr]['voterank'][1]
            G.nodes[nbr]['voterank'][0] += G.nodes[n]['voterank'][1]
        for n in voterank:
            G.nodes[n]['voterank'][0] = 0
        # step 3 - select top node
        n, value = max(G.nodes(data=True), key=lambda x: x[1]['voterank'][0])
        if value['voterank'][0] == 0:
            return voterank
        voterank.append(n)
        if len(voterank) >= number_of_nodes:
            return voterank
        # weaken the selected node
        G.nodes[n]['voterank'] = [0, 0]
        # step 4 - update voterank properties
        for nbr in G.neighbors(n):
            G.nodes[nbr]['voterank'][1] -= 1 / avgDegree
    return voterank

N = 10
G = nx.scale_free_graph(n=N, seed=0)
# Digraph => Graph
G = nx.Graph(G)
# remove self-loop
G.remove_edges_from([(u, v) for u, v in G.edges() if u==v])
assert nx.is_connected(G)
voterank(G)
```
 
the output of code execution is below. Some nodes have definitely negative value. And also, nodes that have negative voting ability are already elected nodes. 
Therefore, the result of `nx.vote_rank` could be little different with the origianl vote rank algorithm. 

```
1 -0.3333333333333333
1 -0.3333333333333333
1 -0.6666666666666666
2 -0.3333333333333333
7 -0.3333333333333333
```

If I am wrong, please let me know. 

I always thanks for your support and `networkx`.

**Comment by dschult** [comment]
@fredrike can you weigh in on this?  
It looks like any elected node should have its voterank set to ```[0,0]``` (see fig 1 in paper). 
But the code doesn't do this.  What are we missing? or is it a bug?

**Comment by manasjoshi14** [comment]
The elected node's voterank set was updated to [0,0] in the snippet :
https://github.com/networkx/networkx/blob/04e1ef2598fa494fc4b0889ef69a71b83ff32493/networkx/algorithms/centrality/voterank_alg.py#L72

Step 4 of reference paper below wasn't correctly implemented. The voting ability is updated only if the new value doesn't become negative. :
https://github.com/networkx/networkx/blob/04e1ef2598fa494fc4b0889ef69a71b83ff32493/networkx/algorithms/centrality/voterank_alg.py#L75

I have created a PR #3970 to fix the bug. Please have a look at it.
