### ISSUE TITLE
Katz raise nx.PowerIterationFailedConvergence(max_iter)

### ISSUE THREAD

**Issue by MohsenDehghanzadeh** [networkx/networkx#3830]
i generated a Barabasi Albert graph with 5000 nodes and m = 3
when i call Katz centrality on graph it raises error : 

```
raise nx.PowerIterationFailedConvergence(max_iter)
networkx.exception.PowerIterationFailedConvergence: (PowerIterationFailedConvergence(...), 'power iteration failed to converge within 1000 iterations')
```

any note will be useful thankyou!

**Comment by dschult** [comment]
The [documentation for katz_centrality](https://networkx.github.io/documentation/stable/reference/algorithms/centrality.html#eigenvector) says that there is an argument ```max_iter``` and another ```tol``` for the tolerance below which the iteration stops. You can increase ```max_iter```, increase ```tol```, or even switch to the ```katz_centrality_numpy``` method if that works better for you.
