### ISSUE TITLE
Subgraphs

### ISSUE THREAD

**Issue by sr-murthy** [networkx/networkx#3831]
Unless I'm mistaken, the documentation on getting a subgraph from a subset of the nodes of a directed graph (digraph) `G` doesn't seem to work. I'm referring to this page here

https://networkx.github.io/documentation/stable/reference/classes/generated/networkx.DiGraph.subgraph.html?highlight=subgraph#networkx.DiGraph.subgraph

	In [127]: g = nx.path_graph(4)                                                                                                    

	In [128]: g                                                                                                                       
	Out[128]: <networkx.classes.graph.Graph at 0x123e2e250>

	In [129]: g.nodes                                                                                                                 
	Out[129]: NodeView((0, 1, 2, 3))

	In [130]: g.edges                                                                                                                 
	Out[130]: EdgeView([(0, 1), (1, 2), (2, 3)])

	In [131]: H = G.subgraph([0, 1, 2])                                                                                               
	---------------------------------------------------------------------------
	TypeError                                 Traceback (most recent call last)
	<ipython-input-131-6d7126a95783> in <module>
	----> 1 H = G.subgraph([0, 1, 2])

	~/Documents/dev/devenv/lib/python3.7/site-packages/networkx/classes/graph.py in subgraph(self, nodes)
	   1688         if hasattr(self, '_NODE_OK'):
	   1689             return subgraph(self._graph, induced_nodes, self._EDGE_OK)
	-> 1690         return subgraph(self, induced_nodes)
	   1691 
	   1692     def edge_subgraph(self, edges):

	~/Documents/dev/devenv/lib/python3.7/site-packages/networkx/classes/graphviews.py in subgraph_view(G, filter_node, filter_edge)
	    156     EdgeView([(0, 1), (1, 2), (2, 3)])
	    157     """
	--> 158     newG = nx.freeze(G.__class__())
	    159     newG._NODE_OK = filter_node
	    160     newG._EDGE_OK = filter_edge

	TypeError: __init__() missing 1 required positional argument: 'x'

**Comment by sr-murthy** [comment]
I need to generate subgraphs of the strongly connected components of a digraph `G` - using `networkx.algorithms.strongly_connected_components` will give me the subset of nodes of these components but I was hoping to then generate the subgraphs using

   
    >>> component_graphs = [nx.subgraph(G, comp) for comp in nx.strongly_connected_components(G)]

but this throws the same `TypeError` as above.

**Comment by dschult** [comment]
Hmmm... that doesn't happen with my setup. I don't know of any version where the graph classes has a positional argument 'x'.  

What version of NetworkX are you using?
Or has it been played with after being installed?

**Comment by sr-murthy** [comment]
OK, closing as this is actually a custom `DiGraph` subclass I'm working with.

**Comment by dschult** [comment]
Try to find a way to make the positional argument 'x' have a default value (even if using the default is never actually done outside of these "views").  The views create a shell object that is an empty version of the class of the graph itself. The data structures of that graph are then replaced with read-only pointers to the original graph.  So, any methods your custom subclass defines are available on the subgraph view too. 

Of course, if you want the subgraph to access the original graph's value of 'x' then you should
rewrite the subgraph method on your custom class.  Something like:
```python
def subgraph(self, nodes):
    SG = DiGraph.subgraph(self, nodes)
    SG.x = self.x
    return SG
```

I'd like to make it as easy as possible to construct subclasses of the main classes. So please follow up with questions/suggestions on how to make this work better for you. I'm going to reopen this as a reminder to look at how to ease subclasses that require arguments to their ```__init__``` method.

**Comment by sr-murthy** [comment]
Thanks. I have managed to implement the custom digraph class properly, and have made the argument `x` optional.

I am somewhat new to `networkx`, but I love graph theory (and discrete mathematics in general) so I'm sure to have questions in the future.
