### ISSUE TITLE
unable to print node and edge labels in latex code.

### ISSUE THREAD

**Issue by Chinmay4400** [networkx/networkx#3844]
I've been trying to display a networkx graph with latex formulae as node and edge labels. But the graph just gets printed without any node or labels but only edges.
I have included `matplotlib.rc('text',tex=True)` but it gives no results.
I want latex equations to show as edge labels.
I am trying to draw a graph :
```%matplotlib notebook
import matplotlib.pyplot as plt
from matplotlib import rc
rc('text', usetex=True)
fig = plt.gcf()
fig.set_size_inches(10,15)
#plt.legend(formulae_alias.values(), formulae_alias.keys())
edge_label_plot = nx.draw_networkx_edge_labels(print_graph,layout,edge_labels=formulae,font_size=6,font_color='red')
nx.draw_networkx_nodes(print_graph,layout,node_size=300)
nx.draw_networkx_edges(print_graph,layout,width=0.8,edge_color='black')
nx.draw_networkx_labels(print_graph,layout,font_size=8,font_family='sans-serif')
plt.axis('off')
plt.show()
```
where the values of `formulae` are strings in latex code.
This is the graph I'm getting:
![Screenshot_20200229_171552](https://user-images.githubusercontent.com/43906657/75606893-8a3f4880-5b17-11ea-94eb-715e55c3c922.png)

**Comment by dschult** [comment]
Can you make a 2 node, 1 edge version of the example and make sure it doesn't work for you? Something we can copy and paste and test. It works for me using:

```python
import networkx as nx
import matplotlib as mpl
mpl.rc('text', usetex=True)

G=nx.path_graph(2)
pos=nx.spring_layout(G)
nx.draw(G, pos)
nx.draw_networkx_edge_labels(G, pos, edge_labels={(0,1):' $x^2$ mode'})
mpl.pyplot.show()
```

**Comment by Chinmay4400** [comment]
Thanks for responding. The issue has been resolved. The problem was in parsing the tex code, as dot2tex wasn't able to parse a \n character.
