### ISSUE TITLE
Panther Algorithm for Fast top-k Similarity Search

### ISSUE THREAD

**Issue by storopoli** [networkx/networkx#3849]
Hello,

Could we have an implementation of the Panther Algorithm (Zhang et al., 2015)[^1] ?

According to the authors, the algorithm is very fast to search for similarity when compared to other implementations. SimRank has a complexity of $mathrm{O}\left(I|V|^{2} \bar{d}^{2}\right)$, where $|V|$ is the number of vertices, $\bar{d}$ is the average degree, $I$ is the number of iterations. And Panther has a complexity of $\mathrm{O}\left(|V| \bar{R}T + |V| \bar{M}\right)$, where $\bar{R}$ is the average number of paths that contain a vertex and is proportional to the average degree $\bar{d}$, $T$ is path length, $\bar{M$} represents the average number of co-occurred vertices with a vertex and is proportional to $\bar{d}$.

![comparison](https://i.imgur.com/Fq7Hy5o.png?1)
---
[^1]: Zhang, J., Tang, J., Ma, C., Tong, H., Jing, Y., & Li, J. (2015). Panther: Fast top-k similarity search on large networks. In Proceedings of the ACM SIGKDD International Conference on Knowledge Discovery and Data Mining (Vol. 2015-August, pp. 1445–1454). Association for Computing Machinery. https://doi.org/10.1145/2783258.2783267

**Comment by mrecachinas** [comment]
@dschult @storopoli Let me know if #3886 is sufficient.

**Comment by storopoli** [comment]
Wow amazing! I will test it right away. Thanks!

**Comment by mrecachinas** [comment]
@storopoli - Note: I didn't implement Panther++ (i.e., vector similarity), just Panther (i.e., path similarity).

**Comment by storopoli** [comment]
Oh ok I will be monitoring #3886

**Comment by storopoli** [comment]
Any news guys?

**Comment by mrecachinas** [comment]
Sorry @storopoli -- see #4400 🙇
