### ISSUE TITLE
Failed simple node comparison

### ISSUE THREAD

**Issue by twinanda** [networkx/networkx#3850]
Can anybody solve this riddle for me? My graph contains objects of my own class implementation. version 2.4.0

`
for node in self.graph.nodes:
print(node in self.graph.nodes)
`

`
False
True
False
False
`

**Comment by dschult** [comment]
You will need both ```__hash__``` and ```__eq__``` to work correctly.
Test it outside your graph....
```python
d={node:1, othernode:2}
print(node in d)
print(othernode in d)
```

**Comment by twinanda** [comment]
Yep, found the issue. We change the nodes (the same object) after putting them to the graph.
