### ISSUE TITLE
Changing an attribute for one node changes the attribute for all nodes

### ISSUE THREAD

**Issue by isomjd** [networkx/networkx#3851]
I've been working to develop a subclass of networkx.Graph using edge_attr_dict_factory and node_attr_dict_factory.  When I try to use the subclass, however, I get some unexpected behavior.  Changing an attribute for one node seems to always change the attribute for all nodes.  Could you help me determine what I am doing wrong?

Here is example code showing the problem:
```python
from enum import Enum
import networkx as nx

class FlowDir(Enum):
    FORWARD=1
    BACKWARD=-1

class GPNNodeType(Enum):
    PLANT=1
    CUSTOMER=2
    JUNCTION=3

class GasPipelineNetwork(nx.Graph):
     all_edge_dict={'Direction':FlowDir.FORWARD,'Length':100,'Diameter':12}
    def GPN_edge_dict(self):
        return self.all_edge_dict
    edge_attr_dict_factory=GPN_edge_dict
    
    all_node_dict={'NodeType':GPNNodeType.PLANT}
    def GPN_node_dict(self):
        return self.all_node_dict
    node_attr_dict_factory=GPN_node_dict
       
G=GasPipelineNetwork()
G.add_nodes_from([1,2,3,4])
```

Now if I run
```python
    G.nodes[2]['NodeType']=GPNNodeType.CUSTOMER 
     list(G.nodes(data=True))
```
I get
```python
[(1, {'NodeType': <GPNNodeType.CUSTOMER: 2>}),
 (2, {'NodeType': <GPNNodeType.CUSTOMER: 2>}),
 (3, {'NodeType': <GPNNodeType.CUSTOMER: 2>}),
 (4, {'NodeType': <GPNNodeType.CUSTOMER: 2>})]
```
But if I run 
```python
  G.nodes[1]['NodeType']=GPNNodeType.PLANT 
  list(G.nodes(data=True))
```
I get
```python
[(1, {'NodeType': <GPNNodeType.PLANT: 1>}),
 (2, {'NodeType': <GPNNodeType.PLANT: 1>}),
 (3, {'NodeType': <GPNNodeType.PLANT: 1>}),
 (4, {'NodeType': <GPNNodeType.PLANT: 1>})]
```

Changing an attribute for one node changes the attribute for all nodes, which is not the desired behavior.

**Comment by dschult** [comment]
Your node factory returns the same object (```all_edge_data```) for every single node.
Perhaps you are basing that off of code for ThinGraph (where the goal is to save memory... so every edge does have the same attribute dictionary).

Why do you want to subgraph the nx.Graph class? It looks like you can just use the built-in attribute dict interface. Are you looking to provide default attribute values for all nodes and edges?  Is there something else you want the new class to accomplish?

```python
G=nx.Graph()
G.add_nodes_from([1,2,3,4], NodeType=GPNNodeType.PLANT)
G.nodes[1]['NodeType'] = GPNNodeType.CUSTOMER
# sets all nodes to same value
nx.set_node_attributes(G, GPNNodeType.JUNCTION, 'NodeType')  
# set different values for one attribute on the specified nodes 
nx.set_node_attributes(G, {2: GPNNodeType.CUSTOMER, 3: GPNNodeType.PLANT}, 'NodeType')  
```

**Comment by isomjd** [comment]
Dan,  

Thank you for your assistance.  The problem was basing the code off of ThinGraph.  I will continue to explore whether it makes sense to subclass the nx.Graph class for our application. 

Kind Regards,
Josh Isom
