### ISSUE TITLE
Is it possible to have duplicate node labels in a networkx 2.4?

### ISSUE THREAD

**Issue by sbhttchryy** [networkx/networkx#3860]
I was trying to relabel a graph with with 3 integers (i.e. the labels of the nodes will be 1 or 2 or 3) on the basis of a distance metric. The initial graph contained 10 nodes, but after using the relabel function (I used a dict which mapped the nodes to the integers) , the graph only contains 3 nodes. 
I do not want to set the labels as a node attribute as I already have other attributes.
Can this be done in some other way? Thank you very much.

**Comment by dschult** [comment]
The best way to store the labels of the nodes is as a node attribute. 
Even if you have other node attributes, you should just give this attribute
a different name and store it as another attribute. The more you discover
about the nodes, the more attributes you should have. 

You can, of course, store the node labels in a dict separate from the graph
keyed by node to the label. There is not much difference in performance or
memory between storing a property of a node as a node attribute and storing
it separately from the graph data structure.
