### ISSUE TITLE
Typo in node clustering coefficient

### ISSUE THREAD

**Issue by PatrikHolopainen** [networkx/networkx#3862]
https://networkx.github.io/documentation/networkx-1.10/reference/generated/networkx.algorithms.cluster.clustering.html#id2

In the equation for the weighted clustering coefficient of a node, the sum should be over `v` and `w` instead of `u` and `v`, as in the paper which it refers to http://jponnela.com/web_documents/a9.pdf.

**Comment by manasjoshi14** [comment]
This was already corrected in the latest versions.
