### ISSUE TITLE
Maximum cost path

### ISSUE THREAD

**Issue by moh55m55** [networkx/networkx#3864]
is there a solution to find the maximum cost path in a directed graph from source to distenation? I tried to use "all_simple_paths" method and then find the maximum cost path. However, the method itself did not scale and not even finish due to a large number of node ~ 700 and ~ 600 edges. Any suggestion?

**Comment by dschult** [comment]
Your stated goal is not well defined in almost any graph.
If there is a cycle with any positive cost, you will get an infinite maximum path.

Most likely you have some other constraint on your path and you'll want the max cost path with some restriction.  Hopefully you can convert whatever it is that you want into a shortest path problem.  For example, maybe adding the maximum weight to the negation of the weights for each edge ---- or using the reciprocal of the edge weights.  Neither of these map directly to the maximum path problem.... but most likely you don't want the maximum cost path...

**Comment by moh55m55** [comment]
Thanks for your reply. My graph does not have any cycles, that's guaranteed by some preprocessing, and all weights are positive. I did not get what you mean by "maybe adding the maximum weight to the negation of the weights ". Do you mean negating all weights edges (e.g., weight*-1)

**Comment by dschult** [comment]
I meant ```new_weight_edge_uv = max_weight_over_all_edges - old_weight_edge_uv```
That makes all edge weights positive, but the smaller weights now become the bigger weights.
Same with reciprocal ```new_weight = 1/ old_weight```.  But this is NOT max cost path...

Your graph better be directed as well -- right otherwise any edge forms a 2-cycle.

Hopefully you can figure out a way to transform the edge weights so your max cost path can be written as a min cost path.

**Comment by dschult** [comment]
You should also look at:
https://www.techiedelight.com/maximum-cost-path-graph-source-destination/
(make sure it is what you are looking for) 
You can probably use edge_bfs() to get the edges to look at.

**Comment by AbhayGoyal** [comment]
Hey, is this issue still needed, and if so what is to be done? I guess we can find max path cost in an undirected graph maybe using a set that checks we not getting into any cycles?

**Comment by dschult** [comment]
I don't think this is worth pursuing -- at least not by inventing a problem that we can then use this to solve. 
The problems we solve should be useful problems.

I'm going to close this issue. But people can still post to it...
