### ISSUE TITLE
networkx.drawing.nx_pydot.write_dot creates empty file if pydot wasn't installed

### ISSUE THREAD

**Issue by miparnisari** [networkx/networkx#3865]
Problem: this code

https://github.com/networkx/networkx/blob/02a1721276b3a84d3be8558e479a9cb6b0715488/networkx/drawing/nx_pydot.py#L24-L25

Is creating the DOT file even before checking if `pydot` has been installed. If it hasn't, then the resulting DOT file will be an empty file.

**Comment by dschult** [comment]
Hmmm.... Thanks for that!
What's the best way to handle that -- do we have to get rid of the decorator that handles paths?
Would it be easy for you to check for pydot or pygraphviz before calling networkx?

suggestions anyone?

**Comment by miparnisari** [comment]
@dschult this is what I am doing:

https://github.com/aws-cloudformation/cfn-python-lint/pull/1411/commits/60d1146b6b9adfe4baa165f8bed17e64d1153584

**Comment by dschult** [comment]
OK.. got it...    How about:
```python
try:
    import pygraphviz
    networkx.drawing.nx_agraph.write_dot(self.graph, path)
except ImportError:
    try:
        import pydot
        networkx.drawing.nx_pydot.write_dot(self.graph, path)
    except Import Error:
            LOGGER.error('Could not build the graph in DOT format. Neither `pygraphviz` nor `pydot` modules are installed, and at least one of these is needed.')
```
