### ISSUE TITLE
Parse graph properties from graphml

### ISSUE THREAD

**Issue by aanastasiou** [networkx/networkx#3868]
Would it be possible to also parse global properties referring to the graph itself from graphml files?

These are `key` XML tags with `for='graph'` as their attribute.

At the moment, it looks like yet another "redirection" based on the `for` attribute at [this point](https://github.com/networkx/networkx/blob/master/networkx/readwrite/graphml.py#L695), but for a `graph_property` attribute of the `graph` dict (?).

**Comment by dschult** [comment]
Hmmm... what is the difference between a global property for the graph and a property for the graph. The graph is only one object, so it is hard to envision any sort of "default value". Should we simply store these values in the ```graph``` dict?

Also, not sure if you are talking about reading or writing these beasts... :)

**Comment by aanastasiou** [comment]
@dschult Yeah, initially, I was talking about just reading them :)

Indeed, I do not see why these values could not go directly into the `.graph` dict. I interpreted it more like graphviz splits parameters that make sense at the node, edge or graph level and so the graph properties could have their own "page" in there.

Just a side question: Since you have the `lxml` dependency, why isn't the reading part just a series of XPath queries? For example, given some graphml file, let's call it `myfile.graphml`:

```
# Parse the file
graphml_doc = lxml.etree.parse("myfile.graphml")
# Give me all the nodes
graphml_doc.xpath("/q:graphml/q:graph/q:node", namespaces={'q':"http://graphml.graphdrawing.org/xmlns"}) 
# Give me all the edges
graphml_doc.xpath("/q:graphml/q:graph/q:edge", namespaces={'q':"http://graphml.graphdrawing.org/xmlns"}) 

# Give me all the keys that refer to node properties
graphml_doc.xpath("/q:graphml/q:key[@for='node']", namespaces={'q':"http://graphml.graphdrawing.org/xmlns"})
# Give me all the keys that refer to edge properties
graphml_doc.xpath("/q:graphml/q:key[@for='edge']", namespaces={'q':"http://graphml.graphdrawing.org/xmlns"})

# Give me the ID attribute of each node in a list
graphml_doc.xpath(""/q:graphml/q:graph/q:node/@id"", namespaces={'q':"http://graphml.graphdrawing.org/xmlns"}) 

```

And so on. 

In this example, I just hardcoded the namespaces but in general, you get them from the `xmlns` attributes of the `graphml` tag. Once `//graphml` is read in, it is then possible to decide which namespaces to use if they are available.

The writing bit is not as straightforward but only because you have to map `networkx` data/entities to `Element` entities within the hierarchy and there you really need traversing a tree like structure.

**Comment by dschult** [comment]
I'm no expert in lxml but does your suggested approach cause the file to be read many times? It looks like it only gets parsed once, so maybe this is a good way to proceed. It seems quite different from what I recall about this code, but I haven't stuck my head in there for a while. :}

**Comment by aanastasiou** [comment]
> ...does your suggested approach cause the file to be read many times?

No. On the contrary, it reads the file once in memory and then runs the queries on it. Which might become a bit slow if the XML file is too big (like hundreds of MB).

Larger files (like GB scale) are possible but not with the typical lxml parser. Rather, it is the [sax parser](https://lxml.de/sax.html). The sax parser streams through the file and emits "events" (I am entering this tag, I am entering that tag, I am leaving that tag, I am leaving this tag, and so on) which your code intercepts and interprets.

I don't know how large files you have tried to load (?). If we have a ballpark figure of size I can do some more specific tests.

I am going to put together a gist (tomorrow) and let you have a look and then you can assess the sort of impact it might have on the existing codebase. And we take it from there (?).

All the best

**Comment by aanastasiou** [comment]
[Work in progress](https://gist.github.com/aanastasiou/57b0e2dc1f9ce12c4610412a817d7635) but you can see how simplified the read-in is. And by using the information in the namespace definitions it is also possible to read-in (or write-out) more complex entity data (possibly as named tuples using [pyxb](http://pyxb.sourceforge.net/).....but you might not like the additional dependencies something like this might bring :) ).

All the best
