### ISSUE TITLE
Wrong unfeasible paths

### ISSUE THREAD

**Issue by OrionStar25** [networkx/networkx#3869]
While using the `capacity_scaling` algo, it's raising unfeasible path error between the source and destination even when all edge capacities are set to infinite. The demand has been specified like this:
```
G.add_node(source, demand = -1)
G.add_node(destination, demand = 1)
```
But using dijkstra gives a proper path. Why is this happening when a path does exist?

**Comment by dschult** [comment]
Can you provide a small example that shows the problem. It can just be two edges.

**Comment by OrionStar25** [comment]
```
G = nx.DiGraph()

G.add_node('a', demand = -1)
G.add_node('b', demand = 1)
G.add_edge('a', 'b', weight = float('inf'), length = 5)
G.add_edge('a', 'c', weight = 6, length = 2)
G.add_edge('c', 'b', weight = float('inf'), length = float('inf'))

d = nx.shortest_path(G, 'a', 'b', weight = 'weight', method='dijkstra')
d
# ['a', 'b']

d, flowDict = nx.capacity_scaling(G, weight='weight')

 ---------------------------------------------------------------------------
NetworkXUnfeasible                        Traceback (most recent call last)
<ipython-input-37-63073f8e7ef3> in <module>
----> 1 d, flowDict = nx.capacity_scaling(G, weight='weight')

/usr/local/lib/python3.6/dist-packages/networkx/algorithms/flow/capacityscaling.py in capacity_scaling(G, demand, capacity, weight, heap)
    371 
    372     if any(R.nodes[u]['excess'] != 0 for u in R):
--> 373         raise nx.NetworkXUnfeasible('No flow satisfying all demands.')
    374 
    375     # Calculate the flow cost.

NetworkXUnfeasible: No flow satisfying all demands.

```

**Comment by dschult** [comment]
It looks like you are using infinite values for the edge costs. Is that intentional?
Might be better to pick a large finite value. Depends on what you are trying to do.
Why not just remove that edge?

**Comment by OrionStar25** [comment]
> It looks like you are using infinite values for the edge costs. Is that intentional? Why not just remove that edge?

Yes, that was intentional. I wanted to ignore certain edges(by filtering out paths with infinite edge costs) but use the same edges with another edge cost at a later stage. 

> Might be better to pick a large finite value. Depends on what you are trying to do.

This seems like a better solution, thanks.
