### ISSUE TITLE
Contribution proposal: New graph similarity measures

### ISSUE THREAD

**Issue by kazimierz-256** [networkx/networkx#3874]
Encouraged by the request for improving the available choices (on the [similarity measures](https://networkx.github.io/documentation/stable/reference/algorithms/similarity.html) page) I would like to consult the NetworkX community before contributing. 
Which of the following contributions would be accepted as a pull-request:

1. Polynomial approximation of Graph Edit Distance proposed by Kaspar Riesen and Horst Bunke in 2009 _[Approximate graph edit distance computation by means of bipartite graph matching](https://www.sciencedirect.com/science/article/abs/pii/S026288560800084X)_.
2. A generalized version of the above (in the case of directed graphs) which I have personally invented and formally derived. The derivation is not publicly available, but, if required, I am willing to share it.

Are there any special requirements for the above contribution ideas (e.g. publicly sharing my derivation via github perhaps)?

**Comment by LukasBommes** [comment]
I'd love to see such an approximation of GED implemented in networkx as the current algorithm is really slow.

**Comment by kazimierz-256** [comment]
That's fantastic news! I'm so happy to hear that my invention (graduate thesis) shall become useful to somebody!
