### ISSUE TITLE
A question about program efficiency and shortest path length

### ISSUE THREAD

**Issue by hsiangyuzhao** [networkx/networkx#3875]
1. Some key functions of NetworkX seem not to be efficient enough to support large network analysis. I have built a directed network with 5000 nodes and 35450 edges. Now I decide to look into the properties of the network so I called functions below in these codes:
```
avg_shortest_path_length = nx.average_shortest_path_length(net)
density = nx.density(net)
avg_connectividy = na.connectivity.average_node_connectivity(net)
betweenness_centrality = na.betweenness_centrality(net)
closeness_centrality = na.closeness_centrality(net)
```
I started the analysis approximately 9 hours ago, and until now the program has not returned any values. It may be relavant to my PC configuration, but similar analysis in Gephi could be carried out within 1 min. So I am rather concerned that if there is some unseen problems need to solve.
Or if there is any mistake in my codes, will you please be so kind to point them out? I would be appreciated.
2. Another problem is that I do not understand why the function `average_shortest_path_length()` requires a connected or weakly connected network to perform? If the network does not meet these requirements the function will raise a error, but in Gephi same analysis could be carried out without these requirements. I think if some nodes are not connected and there is no path, we can simply ignore them and calculate the average of other paths, but current version of NetworkX seems not to support this function.
And I am interested to know how to calculate average shortest path length when the network is not connected with NetworkX.

**Comment by dschult** [comment]
Your network is not very big. It would help if you ran one property at a time so you could tell which property is the slow one.

The problem with ```average_shortest_path_length``` is one of definition. You say that it would make sense to ignore any pair of nodes for which there is no shortest path. That may be an easy way to handle it, but the result no longer measures a quantity that describes what average shortest path is trying to measure. 

The correct way to handle this case is usually to find the connected components, form subgraphs for each and compute the average shortest path of each component. But that's not always best. It depends what you are trying to measure...  That is, why are you looking for the average shortest path? The answer to that question will help tell you how to handle the case with multiple components.

**Comment by AlexanderZhaoBME** [comment]
@dschult Thanks for your response! I am grateful for your advice. After testing the functions listed above, I found that both the functions `average_shortest_path_length()` and `average_node_connectivity()` are slow compared with others. Both functions take more than 30min to execute in my case. I am sorry that I could not perform further expriments due to my urgent deadlines. Functions for betweenness centrality and closeness centrality are not fast either but the time of execution is tolerable, both within 5min.

**Comment by rossbar** [comment]
It's been a while since there's been any activity here and it doesn't seem like there is anything that is immediately actionable, so I'm going to close this. Thanks for the question @hsiangyuzhao - if you have any followups please feel free to reopen.
