### ISSUE TITLE
inaccurate node attributes for random intersection graph

### ISSUE THREAD

**Issue by joelmiller** [networkx/networkx#3876]
G = nx.uniform_random_intersection_graph(10,3,0.2) 

G.nodes(data=True)
> NodeDataView({0: {'bipartite': 0}, 1: {'bipartite': 0}, 2: {'bipartite': 0}, 3: {'bipartite': 0}, 4: {'bipartite': 0}, 5: {'bipartite': 0}, 6: {'bipartite': 0}, 7: {'bipartite': 0}, 8: {'bipartite': 0}, 9: {'bipartite': 0}})

But `G` isn't bipartite.  I assume it's because it was bipartite at the intermediate stage and that attribute was preserved.

**Comment by dschult** [comment]
Yes -- that is correct. The code of ```uniform_random_intersection_graph``` consists of:

```python
    G = bipartite.random_graph(n, m, p, seed)
    return nx.projected_graph(G, range(n))
```
