### ISSUE TITLE
Mistake importing and exporting graphs :(

### ISSUE THREAD

**Issue by shuaiwangvu** [networkx/networkx#3881]
Hi networkx developers,

There seems to be a problem with the write_edgelist and read_edgelist function. 
For me, sometimes the graph I export and import are different. 

Can anyone check if there is a bug in your code?
Thanks!
Shuai

**Comment by MridulS** [comment]
Can you post an example where  write_edgelist and read_edgelist  breaks?

**Comment by hagberg** [comment]
No update provided.
