### ISSUE TITLE
node_disjoint_path Different results on different machines

### ISSUE THREAD

**Issue by dominicdelvecchio** [networkx/networkx#3882]
I'm not sure if this is an issue so much as differences between machines. I am finding when I use node_disjoint_path across different machines the number of independent paths returned is the same, but the paths themselves are different. All on windows dell machines.
One laptop reliably returns the same paths.
Another desktop reliably returns the same paths but different form the other laptop.
The other laptop seems to return different paths each run(although we are in the process of verifying that now).

Would you shed some light on why the function behaves this way across machines?
Thank you
Dominic

**edit 
So it appears the issue is not across different machines, but the restarting of the python kernel.

**Comment by dschult** [comment]
I believe it is due to the way Python stores entries in dicts.
My understanding is that the order is not the same across machines even though it is (since Python3.6) the same from one run to another. I am actually not certain about these claims. I know for sure that prior to 3.6 the order of the keys in a dict changed based on many things. I know that it changed in Python 3.6 to be more consistent from run-to-run. But I am not sure whether dicts are guaranteed to use the same order from machine to machine now. I think they aren't.

**Comment by dominicdelvecchio** [comment]
> I believe it is due to the way Python stores entries in dicts.
> My understanding is that the order is not the same across machines even though it is (since Python3.6) the same from one run to another. I am actually not certain about these claims. I know for sure that prior to 3.6 the order of the keys in a dict changed based on many things. I know that it changed in Python 3.6 to be more consistent from run-to-run. But I am not sure whether dicts are guaranteed to use the same order from machine to machine now. I think they aren't.

Thank you. That is a huge help and another possibility to investigate. The code is using dicts in other places as well not just from the return on node_disjoint_path.

**Comment by dominicdelvecchio** [comment]
So it appears the issue is not across different machines, but the restarting of the python kernel.

**Comment by dschult** [comment]
Which version of Python?

**Comment by dominicdelvecchio** [comment]
> Which version of Python?

I am using 3.76 and my colleague is using 3.7.2. The error is repeatable for both of us.

**Comment by dominicdelvecchio** [comment]
I got it working. We were using the preflow_push as the flow algorithm. When I switched to the default edmon _karp it started working. I'm not sure if this is expected behavior from the prefow_push and there is something about it I don't understand or node_disjoint_path is working differently with it and that's a bug.

**Comment by dschult** [comment]
It looks like ```preflow_push()``` uses Python sets to store "active" and "inactive" nodes. And unlike dicts, sets are not deterministic even in Python 3.6+ (according to [this stackoverflow post](https://stackoverflow.com/questions/14956313/why-is-dictionary-ordering-non-deterministic))

You might be able to alleviate some of the trouble by setting the [PYTHONHASHSEED](https://docs.python.org/3/using/cmdline.html#envvar-PYTHONHASHSEED) environment variable.
