### ISSUE TITLE
when i use read_gml() to read a graphml file, a error occurs 

### ISSUE THREAD

**Issue by leslielee619** [networkx/networkx#3883]
error is: NetworkXError: cannot tokenize '?xml version="1.0" encoding="UTF-8"?\r' at (1, 1）

**Comment by rafguns** [comment]
For reading GraphML, you need the function [`read_graphml`](https://networkx.github.io/documentation/stable/reference/readwrite/graphml.html). [GML](https://networkx.github.io/documentation/stable/reference/readwrite/gml.html) is a different file format.

**Comment by leslielee619** [comment]
> 
> 
> For reading GraphML, you need the function [`read_graphml`](https://networkx.github.io/documentation/stable/reference/readwrite/graphml.html). [GML](https://networkx.github.io/documentation/stable/reference/readwrite/gml.html) is a different file format.

thank you, i just think func ''read_gml' means read graphml file. In fact there is a func 'read_graphml'  to read graphml file.
