### ISSUE TITLE
Pip Install Failed with Connection Error

### ISSUE THREAD

**Issue by tbpassin** [networkx/networkx#3887]
OS: WIndows 10
Python: 3.8.0
Partial pip output:

```
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.VerifiedHTTPSConnection object at 0x00000209D8EF2370>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/networkx/
```

**Comment by ha-lins** [comment]
The same error for me.

**Comment by dschult** [comment]
Do you get the same error using pip with a different package? 
I think it is unlikely to be a networkx problem...

**Comment by tbpassin** [comment]
I have never seen this error before with pip.  However, trying the install again just now, it completed  without error both on Windows and Linux.

So, a little mystery but at least networkx is now installed.
