### ISSUE TITLE
Missing pipenv support

### ISSUE THREAD

**Issue by aijanai** [networkx/networkx#3898]
Pipenv has proven to be a very robus virtualenv manager and dependency solver.
How about adding support?

Thanks

**Comment by rossbar** [comment]
Nothing needs to be changed to add support for `pipenv`: the following should work:

```bash
pipenv install networkx
```

Or, to install for development:

```bash
pipenv install -e .
```

All dependencies and requirements for any specific configuration can either be added individually as needed, or with the various requirements files in `requirements` via `pipenv -r <req_file>`.
