### ISSUE TITLE
Met this error (Segmentation fault (core dumped))

### ISSUE THREAD

**Issue by klauspa** [networkx/networkx#3904]
hello I am trying to find all the cycles in the a digraph, So I use this method:
`nx.simple_cycles(G)`
It works fine and fast when I have 5000 edges in G and 60 cycles, but when I try to test it with larger dataset, say 300000 edges and 150000 cycles, It pops out Segmentation fault (core dumped).

My computer configuration is I5 CPU and 8G memory.

I kown that simple_cycles implement jhonson's algorithm and this should be the fastest algorithm. So what makes the weak performance when it comes large graph?

Thanks!

**Comment by dschult** [comment]
The core dump sounds like a python issue...???   But maybe it's running out of memory.
It doesn't sound like a "fastest algorithm" problem. It sounds like a "lowest RAM algorithm" issue.
The current version is a low RAM improvement of the ```recursive_simple_cycles``` algorithm.
The code is not too long -- you might be able to track down where the memory is being used.

Comment again (or make a new PR/issue) if you find what's causing this.
