### ISSUE TITLE
set_node_attributes  - Documentation error

### ISSUE THREAD

**Issue by AparnApu** [networkx/networkx#3906]
Version of networkx - 2.4
Version of python - Python 3.7.6

Link to page -
([https://networkx.github.io/documentation/networkx-1.9/reference/generated/networkx.classes.function.set_node_attributes.html])

Documentation Error found in function - set_node_attributes(G, name, values)

Actual syntax for the above function should be - set_node_attributes(G, values)
                Parameters:    G = NetworkX Graph
                                       values = dict - (Dictionary of attribute values keyed by node. If \(values\) is not a dictionary, then it is treated as a single attribute value that is then applied to every node in \(G\).)

**Comment by dschult** [comment]
Your documentation is from networkx-1.9 (see the link url...)

The problem is that google's search algorithm still points to networkx 1.9 and 1.10 when you search for functions. We were able to get it to stop pointing to v2.x earlier than latest version. But 1.9 and 1.10 often still come up.

**Comment by AparnApu** [comment]
Got it, thank you!
It points to the right version when you change the version number in the link.
