### ISSUE TITLE
Where can I get an old version of networkx for python 2.7?

### ISSUE THREAD

**Issue by blackstormx** [networkx/networkx#3908]
I need it for personal use, since I'm using a library that has been deprecated few years ago. It used networkx but an old one. Unfortunately I can't find any of old downloads on the pypi.

Could anyone be kind enough to search up old folder of this library on their HDDs and upload it somewhere? I'd be grateful. 

Thanks.

**Comment by MridulS** [comment]
v2.2 was the last supported version for python 2.7, you can install it through pip


pip install networkx==2.2

**Comment by MridulS** [comment]
You can also download the source code for the previous versions through https://github.com/networkx/networkx/releases

**Comment by blackstormx** [comment]
Thanks, but I need version 1.9, before 2.0's API changes.
