### ISSUE TITLE
Pajek export assumes Graph node's id attribute to be int castable

### ISSUE THREAD

**Issue by lloesche** [networkx/networkx#3910]
In pajek export it reads https://github.com/networkx/networkx/blob/b0ca6ce081cc6e66d509c5f7fed60728da821c25/networkx/readwrite/pajek.py#L57

I was wondering, since NetworkX supports arbitrary Python objects as Graph nodes where does the assumption come from that a node's `id` attribute is `int` castable? An objects `id` attribute would have nothing to do with Python's builtin `id()`. But I'm not familiar with the Pajek file format so don't know about the relevance and special treatment of `id` in it.

I was working with a Graph whose node's `id` attribute happened to be a string. For it Pajek export failed with
```
ValueError: invalid literal for int() with base 10: 'arn:aws:iam::579763146468:role/aws-service-role/trustedadvisor.amazonaws.com/AWSServiceRoleForTrustedAdvisor'
```

**Comment by dschult** [comment]
Its not a networkx limitation -- its a Pajek standard.
You can [relabel the nodes](https://networkx.github.io/documentation/stable/reference/relabel.html) to be integers and store the string as an attribute in the Pajek file.

**Comment by lloesche** [comment]
I see, thank you for clarifying! Since this is a limitation always enforced by the Pajek standard, would it make sense to add a try/catch ValueError around the int() cast and add that information together with your suggestion to relabel? Or is there a situation where the raw `ValueError: invalid literal for int()` is a more useful output? I'd send a PR if that makes sense.

**Comment by dschult** [comment]
That's an excellent idea! 
I think the cost of a try/catch over the casting should be small and the error message probably would help some people a lot.  :}
