### ISSUE TITLE
degree_assortativity_coefficient not working with non-integer weights

### ISSUE THREAD

**Issue by Silmathoron** [networkx/networkx#3917]
Hi there,
it seems that ``degree_assortativity_coefficient`` does not work with non-integer edge weights, yet this requirement is not mentioned [in the doc](https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.assortativity.degree_assortativity_coefficient.html#networkx.algorithms.assortativity.degree_assortativity_coefficient) and seems strange to me.

    nx.degree_assortativity_coefficient(g, x="in", y="in", weight="float_weights")

leads to

    Traceback (most recent call last):
      File "script.py", line 131, in <module>
        nx.degree_assortativity_coefficient(g, x="in", y="in", weight="float_weights")
      File "/path/to/lib/python3.8/site-packages/networkx/algorithms/assortativity/correlation.py", line 77, in degree_assortativity_coefficient
        M = degree_mixing_matrix(G, x=x, y=y, nodes=nodes, weight=weight)
      File "/path/to/lib/python3.8/site-packages/networkx/algorithms/assortativity/mixing.py", line 160, in degree_mixing_matrix
        mapping = {x: x for x in range(m + 1)}
    TypeError: 'float' object cannot be interpreted as an integer

with Python 3.8, using networkx 2.4.

Is this a bug or is it supposed to be only for integers?

If I am not mistaken, changing the weights by an arbitrary factor should make no difference to the final result (apart from tiny floating point roundings) so one could probably almost always work on digitized versions of the weights.
In that case, would it be possible to easily adapt the algorithm to arbitrary weights?

EDIT: to clarify, I could obviously update the weights myself, but that would be fairly slow so my question is more "is it possible to do this somewhere in the algorithm to make this fast and avoid the creation of a new edge attribute?"

**Comment by dschult** [comment]
Closed by #4851
