### ISSUE TITLE
layout options not found

### ISSUE THREAD

**Issue by rkrishnasanka** [networkx/networkx#3918]
Here's the error I get 

```
Exception has occurred: AttributeError
module 'networkx' has no attribute 'bipartite_layout'
```

Here's the code that I have written

```
import networkx as nx
import matplotlib.pyplot as plot

...

positions = nx.bipartite_layout(G)
print(positions)
nx.draw(layout.G, positions)
plt.show()
```

`G` is a `MultiDiGraph`

Any idea why it can't find both `bipartite_layout` and `planar_layout`.

Thanks!

**Comment by dschult** [comment]
You must have an older version of networkx.

**Comment by rkrishnasanka** [comment]
Yes, it seems like it was reading an older version from cache in my MacOS environment. I switched over to Ubuntu and it works fine now.
