### ISSUE TITLE
gaussian_random_partition_graph constructor optional parameter doesn't work

### ISSUE THREAD

**Issue by zsxing99** [networkx/networkx#3926]
gaussian_random_partition_graph constructor always returns a directed graph no matter how I set the parameter "directed"

**Comment by dschult** [comment]
Yes -- indeed the function ```gaussian_random_partition_graph``` calls ```random_partition_graph``` with positional arguments in the wrong order. seed and directed are switched. Would be good to change that call to using keywords:

```python
gaussian_random_partition_graph(sizes, p_in, p_out, directed=directed, seed=seed)
```
