### ISSUE TITLE
Consider removing dependency on __file__

### ISSUE THREAD

**Issue by href** [networkx/networkx#3929]
I'm trying to use networkx in a [PyOxidizer](https://pyoxidizer.readthedocs.io/en/stable/) project. Unfortunately networkx relies on `__file__`, which is an optional attribute and should not be relied upon.

See https://github.com/indygreg/PyOxidizer/issues/69 for more information.

I see that there are a few references to `__file__ ` in networkx, so it might not be straight forward to remove them all. But it would already be a great help if `networkx.release` would not require this attribute.

Cheers!

**Comment by rossbar** [comment]
> which is an optional attribute and should not be relied upon.

Interesting, I'm not aware of any best-practices etc. that discourage the use of `__file__`. Do you have any additional resources you could point to (aside from the already linked issue) that expands on this?

**Comment by href** [comment]
I think in most contexts it is probably fine to use `__file__`. I know I used it in many Python projects. The only thing that can be said about it is, that it's not guaranteed to be there. See the [Python documentation about `__file__`](https://docs.python.org/3/reference/import.html#__file__), which states the following:

> `__file__` is optional. If set, this attribute’s value must be a string. The import system may opt to leave `__file__` unset if it has no semantic meaning (e.g. a module loaded from a database).

One could argue that one shouldn't rely on an attribute that is not necessarily there, but I guess this only bites you as your project gets big enough for people to want to use runtimes other than vanilla CPython.

That is to say, I understand why one wouldn't want to bother with this and I don't think there's a best-practice that has ever developed around this, as it's usually just not an issue.

**Comment by rossbar** [comment]
Thanks for the additional info. After reading through the linked PyOxidizer issue I was struck by the seeming lack of a standardized way to handle the replacement of `__file__` in libraries. If someone wants to take this up for NetworkX they're welcome to do so, as long as the solution is grokkable and doesn't introduce new maintenance overhead.

**Comment by MridulS** [comment]
> But it would already be a great help if networkx.release would not require this attribute.

This file doesn't exist anymore. Would this fix the issue already with [PyOxidizer](https://pyoxidizer.readthedocs.io/en/stable/)?

I have also created https://github.com/networkx/networkx/pull/6936 which removes use of `__file__` from other places in our codebase.

**Comment by href** [comment]
> This file doesn't exist anymore. Would this fix the issue already with [PyOxidizer](https://pyoxidizer.readthedocs.io/en/stable/)?

I'm not using Pyoxidizer anymore, but from what I recall `networkx.release` was required to even import networkx. So the presence of `__file__` made the whole library unusable in this context. With its removal, one would be able to use code paths that do not use `__file__`.

Once it's gone, all of `networkx` should work.
