### ISSUE TITLE
Pajek .clu readwrite

### ISSUE THREAD

**Issue by joaquincabezas** [networkx/networkx#3931]
Dear all,

I needed functions to read/write .clu files (Pajek clusters, communities) and I wrote them. I am willing to contribute with a PR, but I have a doubt with naming convention. As there are already "read_pajek" and "write_pajek" functions in the pajek.py file, is it ok to create new functions with suffix "_clu" within the same file?

My work so far: https://github.com/joaquincabezas/networkx_pajek_util

**Comment by dschult** [comment]
I like your coded names like ```read_pajek_communities```.  But does this only read .clu files? And what are .clu files? Are they a subset of pajek specification?  If it really is for .clu files only then perhaps ```read_pajek_clu``` is a better name. 

You should include in the docstring a quick description of what .clu files are and how they relate to pajek files.

**Comment by joaquincabezas** [comment]
from pages 8-9 of http://vlado.fmf.uni-lj.si/pub/networks/pajek/howto/FirstSteps.PDF there are 4 filetypes for Pajek:

.net (NETwork)
.clu (CLUster)
.vec (VECtor)
.per (PERmutation)

I think you are right, we should use read_pajek_clu as it is aligned with the Pajek documentation. It is OK to leave "read_pajek" for .net files as it is the most common one (although I would create a read_pajek_net function and make read_pajek an alias of that).

Regards,
Joaquín

**Comment by dschult** [comment]
I agree that it's good to change the existing names to ```read_pajek_net```, etc., and then have the alias ```read_pajek``` point to the net version. Looks like you've got most of ```.clu``` close to ready and we can leave .vec and .per for later.
:)
