### ISSUE TITLE
Asynchronous Topological Sort

### ISSUE THREAD

**Issue by tambulkar** [networkx/networkx#3933]
I am running tasks in parallel via MPI and want to use a DAG and topological sort to distribute these tasks to other processors. Using the topological sort algorithm provides me a generator for tasks, but it assumes that a task is completed as soon as it is generated. Does networkx provide an asynchronous topological sort generator that waits for a node to be asynchronously marked as completed before removing it a dependency for its children?

**Comment by ericmjl** [comment]
@tambulkar I'm not sure NetworkX will provide what you are looking for, but I think @dschult and @hagberg might know better.

That said, it looks like you're possibly reimplementing Dask - have you perhaps looked into it as a possible parallelization engine for your broader problem? (I'm of course writing as someone who is completely ignorant of your problem space, so please forgive me if you see my comment as mere blabbering!)

**Comment by tambulkar** [comment]
@ericmjl I think you're right however, I need to do pass information between the processes and the structure of my program requires something slightly different than DASK. I managed to implement a working prototype but thanks for the insight
