### ISSUE TITLE
Install documentation has error for zsh, easily fixed

### ISSUE THREAD

**Issue by BlueDrink9** [networkx/networkx#3934]
With zsh, `pip install networkx[all]` says

> zsh: no matches found: networkx[all]

This is easily fixed by quoting the package to be installed, which also works on bash.

`pip install 'networkx[all]'`

(Also while I'm here, consider putting a link to the source code more prominently in the documentation. I could only find it from the git command in the install section)

**Comment by dschult** [comment]
Isn't the link to the source explained well in the section above your problematic line?  In the section called "Install the Development Version"?

**Comment by BlueDrink9** [comment]
I'm not sure what you mean. If I look at https://networkx.github.io/documentation/stable/install.html I don't see any link to the source. The only url is within the git codeblock

**Comment by dschult** [comment]
On the page you show the link for, there is a section called "Install the Development Version" which describes how to get the source code using git.  I guess you are saying we should include a link to the github webpage instead (or in addition to).  Is that right?

**Comment by BlueDrink9** [comment]
Yes, exactly. The link to most open source projects' github repositories is usually prominently displayed in multiple places in the docs, whereas here the only url is a code sample with a git command, not an actual link.

**Comment by rossbar** [comment]
Note that there is a permalink in the navigation column on the right that says "source code", so the link to the github is available from every page of the docs. Nevertheless, if you have a specific ideas on how the docs could be improved, please feel free to open a PR (or share here if you're note comfortable doing so)!

**Comment by BlueDrink9** [comment]
Oops, I completely missed that. Excellent. Anyway, the source code link was just a side issue. The zsh installation issue is the main reason for opening this, and I thought adding two quotes wasn't worth a fork and PR. A response on that would close this issue

**Comment by rossbar** [comment]
Re: the zsh issue - my initial reaction is that it is the responsibility of shell users to recognize where their shell-of-choice differs from bash syntax. For instance - the change to `pip install 'networkx[all]'` would work for both `bash` and `zsh`, but would it work for others (`csh`, `tclsh`, `fish`, etc.)? AFAICT bash is the de-facto standard when it comes to documenting shell commands for many scientific Python libraries. Even though it's a small thing, I'd be hesitant to break that pattern. That's just my two cents though - if there are examples of how the shell-syntax-dependency problem is handled in other docs, please share!

**Comment by BlueDrink9** [comment]
That's a fair approach. You could mention something along the lines of 

> NOTE: Some shells required quotes around the pip argument, like `pip install 'networkx[all]'`

**Comment by jarrodmillman** [comment]
I would rather remove ``pip install networkx[all]`` than add a special case for advanced users (e.g., people who aren't using a default shell).  @BlueDrink9 which optional packages did you need to install?  Did all the optional packages install without problems?  (A couple of our optional packages are often tricky to install.)

**Comment by jarrodmillman** [comment]
BTW, @BlueDrink9 you didn't miss the source code link in the documentation earlier.  After you made this ticket, @dschult opened #3998 and I closed it with #4044.  So the links are there now thanks to this issue.

**Comment by BlueDrink9** [comment]
It's too long ago for me to remember, sorry. I don't think I had any problems with `all`…

**Comment by eikNamo** [comment]
Is this issue still ongoing? Since I have never before contributed to an open-source project I thought that this issue would be a good place to start as well as to get acquainted with the workflow.

**Comment by jarrodmillman** [comment]
@eikNamo I forgot to close this.  zsh is not a standard shell and users selecting it should now it's syntax.  The install guide is aimed more at novice users who are unlikely to have customized their own shell.

We recently add a FAQ for new contributors:
- https://networkx.org/documentation/latest/developer/new_contributor_faq.html

It would be great if you could take a look at it.  It is new and we welcome feedback.  Please take a look at some of the other issues to see if there is something that looks interesting to you.  Thanks for your interest and hopefully you can find another area to begin contributing!

**Comment by eikNamo** [comment]
Ah I see, though I have already read through the FAQ and contribution.rst document. 

Well, thanks for the quick response anyway!
