### ISSUE TITLE
Const'ifying utils.reversed?

### ISSUE THREAD

**Issue by zougloub** [networkx/networkx#3936]
I was surprised that `nx.utils.reversed` is modifying its argument instead of returning a reversed view of it, which would keep the argument unmodified.

Current:
```py
with nx.utils.reversed(G):
   ...
```

Proposed:
```py
with nx.utils.reversed(G) as G_: # or another name like reversed_view...
   ...
```

Context: I didn't expect `nx.ancestors(dg, n)` to modify `dg` and was calling it from several threads and descendants were returned sometimes. Found the problem and now I'm using a view per thread, nevertheless IMO it would be cleaner if free functions weren't unexpectedly modifying their arguments.

**Comment by dschult** [comment]
The doc_string says:
```A context manager for temporarily reversing a directed graph in place.```

You probably want a ReversedView, [most easily obtained](https://networkx.github.io/documentation/stable/reference/classes/generated/networkx.DiGraph.reverse.html) using ```G.reverse(copy=False)```.

Perhaps we should expand the documentation of the contextmanager ```reversed``` to provide other alternatives in a ```See Also``` section.

**Comment by zougloub** [comment]
@dschult my point is more about wondering whether we could do without this in-place reversal where it is used (eg. using `G.reverse(copy=False)` as you mention).

**Comment by dschult** [comment]
I'm circling back to this finally... sorry for delay...

If I understand correctly, the difficulty is that ```nx.ancestors``` reverses the graph in-place. And it shouldn't if we want to allow multiple threads to call ```nx.ancestors``` using the same graph.

Do I understand correctly?  If this is the issue, we should probably check whether this same defect arises anywhere else that uses ```nx.utils.reversed```. Also we should improve documentation about it too. Maybe (though maybe not) we should allow a way to designate that a function like ancestors reverses in-place or as a copy.

**Comment by zougloub** [comment]
Spot on @dschult.
