### ISSUE TITLE
Add option to BFS_edges to process children in order based on node attribute

### ISSUE THREAD

**Issue by tambulkar** [networkx/networkx#3938]
I would like to add the option to pass in a comparator function that will add children to the queue in an order specified by the comparator and their [node attributes](https://networkx.github.io/documentation/stable/reference/generated/networkx.classes.function.set_node_attributes.html)

**Comment by dschult** [comment]
That seems like a nice practice problem: take the code for bfs_edges, read it and understand it sufficiently to change the order of the nodes when added to the queue.  If you can make it easily understandable code and general enough to be useful for others and not detrimental to the time needed for the standard case, please create a PR for adding it to NetworkX. :}

**Comment by adnanmuttaleb** [comment]
#4029
