### ISSUE TITLE
convert_matrix.py missing from_pandas_dataframe

### ISSUE THREAD

**Issue by huyptruong** [networkx/networkx#3939]
Hello, it seems that the latest version of `networkx` has `from_pandas_dataframe` removed. You can see it from here, `__all__ = [
    "from_numpy_matrix",
    "to_numpy_matrix",
    "from_pandas_adjacency",
    "to_pandas_adjacency",
    "from_pandas_edgelist",
    "to_pandas_edgelist",
    "to_numpy_recarray",
    "from_scipy_sparse_matrix",
    "to_scipy_sparse_matrix",
    "from_numpy_array",
    "to_numpy_array",
]`
Is it possible for me to download the previous version? Or is there a workaround to view a pandas dataframe as a graph? Thanks.

**Comment by ericmjl** [comment]
Hi @huyptruong, chiming in because I've recently discovered the same deprecated API. You should use `from_pandas_edgelist`, I think.

**Comment by dschult** [comment]
With the old system, it wasn't clear whether the pandas dataframe should be an edgelist or an adjacency structure. So, you see from the list in ```__all__``` that there is now a ```from_pandas_edgelist``` and ```from_pandas_adjacency``` .  You should pick the one that corresponds to how you are storing your data in the dataframe. Pandas is very flexible, so it is possible you have it stored in yet another way. But we think those are the two common ways to store graph data. Hopefully this naming convention helps clarify -- the old name did not. :}
