### ISSUE TITLE
'root' parameter not working in 'graphviz_layout()'

### ISSUE THREAD

**Issue by padix-key** [networkx/networkx#3940]
I would like to plot a graph as a tree and I would like to determine which node to use as root. However, the following is not working:
```python
import networkx as nx
from networkx.drawing.nx_pydot import graphviz_layout
graph = nx.Graph()
graph.add_edge("B", "A")
nx.draw(
    graph,
    graphviz_layout(graph, prog="dot", root="A"),
    with_labels=True
)
plt.show()
```
Output:
![graph](https://user-images.githubusercontent.com/28051833/80982036-06614f80-8e2b-11ea-982a-d733f78c2d60.png)

I would like to have `"A"` as root, but instead `"B"` is chosen.

**Comment by dschult** [comment]
The docs for ```graphviz_layout``` say that the root argument works for some layout algorithms. Do you happen to know which? Are you using an algorithm that takes advantage of the root argument?

**Comment by padix-key** [comment]
No, unfortunately I don't know which *graphviz* programs use the `root` parameter. I think it would be helpful, if the documentation would state which programs are affected by this parameter.

If the root parameter is not the right way to achieve this, is there any other way?

**Comment by dschult** [comment]
It looks like this is an issue that has to be tracked in the GRaphViz documentation (or else we would be spending time tracking and updating what they have available.  Alternate ways to achieve "this" depends on what "this" means. Different layouts have different ways of arranging the nodes, so it really depends what layout you are using.
