### ISSUE TITLE
Inconsistent behavior when isolates is combined with remove_from_nodes

### ISSUE THREAD

**Issue by jeromemassot** [networkx/networkx#3943]
remove_from_nodes() does not act the same when it is fed with the iterator or the list of isolated nodes. Case 2 is acting as expected. Case 1 seems failing to remove any node.

Case 1:
G = nx.Graph()
G.add_nodes_from("ABCD")
my_isolates = nx.isolates(G)
G.remove_nodes_from(my_isolates)
list(G)
>> ['A', 'B', 'C', 'D']

Case 2:
G = nx.Graph()
G.add_nodes_from("ABCD")
G.remove_nodes_from(nx.isolates(G))
list(G)
>> [ ]

**Comment by dschult** [comment]
The two pieces of code you show are effectively identical. There is no way that those two pieces of code create different output. They don't do what you say they should do either.... no list of isolates is ever created.

**Comment by jeromemassot** [comment]
Hi, thanks for the comment.
sorry but, finally, is my issue valid or does the code behave accordingly as expected?
Thanks
Regards
Jerome

**Comment by dschult** [comment]
I can't tell what your issue is. It looks like a coding problem on your end... but I can't tell.
