### ISSUE TITLE
k_crust(G, k) behavior is misleading when combined to k_core(G, k)

### ISSUE THREAD

**Issue by jeromemassot** [networkx/networkx#3944]
With reference to the documentation, k_crust(G, k) returns in fact the complement of k_core(G, k+1).
But this behavior is very misleading.
What is the reason of such behavior for k_crust when k is specified?
Thanks

**Comment by dschult** [comment]
It looks like ```k_crust``` removes the k-core and so is the complement of k_core(G,k).
I think the documentation says: 
```The k-crust is the graph G with the k-core removed.```
Also ```Note: This definition of k-crust is different than the definition in [1]. The k-crust in [1] is equivalent to the k+1 crust of this algorithm.```

Are you saying the function doesn't do what it's documentation says?
Or that it agrees with the documentation but should be defined differently?

**Comment by jeromemassot** [comment]
As far as I understand the documentation about the k_crust(G, k), the code is working as explained. However, it is misleading to run :
nx.k_core(G, k=i).nodes()
nx.k_crust(G, k=i).nodes()
and to see nodes belonging to the two sets.... or I do not understand the math concept...

**Comment by dschult** [comment]
Ahhh... I think I see the confusion now:
The docs say the k-crust is G with the k-core removed. 
But it's not clear there whether we remove the nodes or the edges of the k-core.

We remove the edges as well as any isolated nodes after those edges are gone.
This seems reasonable, but I can believe there are reasons to return all nodes, and only the edges not in the k_core.

But we should not return only the nodes not in the k-core. That removes too much.
I do believe that the k_core and the k_crust must have some nodes in common. It's the edges that are the focus of this way of looking at graph structure.
