### ISSUE TITLE
DiGraph.__init__ does not allow sets

### ISSUE THREAD

**Issue by alabarre** [networkx/networkx#3945]
I find it very convenient to be able to initialise graphs using:
```python
>>> import networkx as nx  # version 2.2
>>> G = nx.DiGraph([(1, 2), (3, 4)])
>>> G = nx.DiGraph(((1, 2), (3, 4)))
```
However sets do not work and I don't understand why they have been disallowed:
```python
>>> import networkx as nx
>>> G = nx.DiGraph({(1, 2), (3, 4)})  # fails with frozenset too
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/networkx/classes/digraph.py", line 309, in __init__
    convert.to_networkx_graph(incoming_graph_data, create_using=self)
  File "/usr/lib/python3/dist-packages/networkx/convert.py", line 161, in to_networkx_graph
    "Input is not a known data type for conversion.")
networkx.exception.NetworkXError: Input is not a known data type for conversion.
```
Shouldn't DiGraph (and Graph, etc.) accept *any* iterable of tuples?

**Comment by dschult** [comment]
Graphs with nodes that are 2-tuples (like geometric graphs) are iterables of tuples, and dict-of-dict constructs are also acceptable input but should not be treated as iterables of tuples.
I haven't thought carefully about whether sets of tuples should be handled.  Probably -- (the set object became part of standard python after our initial creation and I don't know if we revisited sets of edges after it became more popular..... maybe now is the time. :)

**Comment by muratgu** [comment]
Looks like #3884 solves this issue for sets (but not for frozensets). I suspect the fix is as simple as adding the 'frozenset' to the is_instance check at the same spot.
