### ISSUE TITLE
read_gml encoding error

### ISSUE THREAD

**Issue by bigpapame** [networkx/networkx#3950]
### It seems like my GML file included Chinese texts, so whenever i try to read gml it gives me "input is not ASCII-encoded" error. So is there any way to keep the Chinese texts and make this program work at the same time?
![error](https://user-images.githubusercontent.com/56836973/81538317-2fd92880-93a1-11ea-9144-d0719cbdf2ff.JPG)
![image](https://user-images.githubusercontent.com/56836973/81538378-42ebf880-93a1-11ea-8f02-6fd79bcbff69.png)
```
import networkx as nx
import matplotlib.pyplot as plt
G = nx.read_gml('Data_sets/test.gml')

pos = nx.circular_layout(G)

# nodes
nx.draw_networkx_nodes(G, pos, node_size=100)
# edges
nx.draw_networkx_edges(G, pos)

# labels
#nx.draw_networkx_labels(G, pos)

#print (nx.info(G))
#print (nx.is_directed(G))
#nx.draw_random(G)
plt.axis('off')
plt.show()
```

This is my GML file (removed due to length)

**Comment by dschult** [comment]
Please see [the documentation for read_gml](https://networkx.github.io/documentation/stable/reference/readwrite/generated/networkx.readwrite.gml.read_gml.html) .
In particular, the note at the bottom about non-ascii character

**Comment by bigpapame** [comment]
Do you mean stringizer and destringizer ? I have no ideal what these mean. 
If not, can you be more specific where my problem is ?

**Comment by dschult** [comment]
The GML standard is 7-bit ASCII text. If you want to push the boundaries to include other forms of text, you'll need to use a custom treatment for decoding your information? [I suspect "destringizer" is not even a word..] 
It would be worth looking at the [literal_destringizer](https://networkx.github.io/documentation/stable/reference/readwrite/generated/networkx.readwrite.gml.literal_destringizer.html#networkx.readwrite.gml.literal_destringizer) option linked to in the [read_gml documentation page](https://networkx.github.io/documentation/stable/reference/readwrite/generated/networkx.readwrite.gml.read_gml.html) -- hopefully that is all you need.

**Comment by bigpapame** [comment]
Ok. Thanks for your reply😊
