### ISSUE TITLE
weird behaviour with node removal/counting

### ISSUE THREAD

**Issue by ggrrll** [networkx/networkx#3951]
Hi,

there seems to be something weird with `g.number_of_nodes` or `g.remove_nodes_from`:

as you can see from the screenshot, I get sometimes that the difference is not = N removed nodes

```
g = nx.fast_gnp_random_graph(1000, 0.1)
nx.is_connected(g)

removes_N = 10
print('init. N. nodes', g.number_of_nodes())

for i in range(int(g.number_of_nodes() / removes_N)):

    nn_1 = g.number_of_nodes()

    # select nodes to remove
    removed_nodes = np.random.choice(g.nodes(), removes_N)

    # remove selected nodes
    g.remove_nodes_from(removed_nodes)

    # double check
    nn_2 = g.number_of_nodes()

    if nn_1 - nn_2 != len(removed_nodes):
        print(nn_1 - nn_2, removed_nodes)
        print([my_node for my_node in removed_nodes if my_node in g.nodes()])
```

<img width="994" alt="Screenshot 2020-05-12 at 13 31 18" src="https://user-images.githubusercontent.com/15370425/81682184-fbbf3f80-9454-11ea-850f-c6508ee99848.png">

(this might be related to #3943 ) 

Thanks for your help!

ps: on Version: 2.4 / python3.7

**Comment by dschult** [comment]
It looks like you are probably asking it to remove the same node more than once.
Am I missing something? I you remove a node and then try to remove it again, it will silently ignore the request to remove it a second time.

Also, please just copy and paste the text rather than sending a screenshot of the text. We can't interact with a screenshot.

**Comment by ggrrll** [comment]
but how is that possible, given that I select everytime the nodes to be removed from the _updated_ graph? , as in 
```
removed_nodes = np.random.choice(g.nodes(), removes_N)
```

(the code snippet was a regular copy/paste)

**Comment by ggrrll** [comment]
more clean checks:

```
g = nx.fast_gnp_random_graph(1000, 0.1)
nx.is_connected(g)

removes_N = 10
print('init. N. nodes', g.number_of_nodes())

for i in range(int(g.number_of_nodes() / removes_N)):

    nn_1 = g.number_of_nodes()

    # select nodes to remove
    to_be_removed_list = np.random.choice(g.nodes(), removes_N)
    [my_node for my_node in to_be_removed_list if my_node not in g.nodes()] # just a check
    

    # remove selected nodes
    g.remove_nodes_from(to_be_removed_list)
    [my_node for my_node in to_be_removed_list if my_node in g.nodes()] # just a check

    # double check
    nn_2 = g.number_of_nodes()

    if nn_1 - nn_2 != len(to_be_removed_list):
        print(nn_1 - nn_2)
```

**Comment by dschult** [comment]
Try checking the nodes that are to be removed (often duplicates).
And also try checking which nodes actually were removed.

```python
nn_1 = g.number_of_nodes() 
setnn_1 = set(g)          # or set(g.nodes)

... #then later
nn_2 = g.number_of_nodes() 
setnn_2 = set(g)          # or set(g.nodes)

if nn_1 - nn_2 != len(to_be_removed_list):
    print("nodes actually removed:", setnn_1 - setnn_2)
```

It looks like ```np.random.choice``` is allowed to choose with replacement.

**Comment by ggrrll** [comment]
you're right: setting `replace=False` removes the issue 
(sorry for the misunderstanding)
