### ISSUE TITLE
Same Graph, different Simrank results.

### ISSUE THREAD

**Issue by Carghaez** [networkx/networkx#3953]
Hello there! 
![simrank](https://user-images.githubusercontent.com/297838/81880095-ccabe980-958c-11ea-9058-46bcab40ee11.PNG)

I want to reproduce the simrank of the graph linked above, so I use your FL simrank_similarity and simrank_similarity_numpy and... I noticed that the results are different!

steps to reproduce

```python
import networkx
import numpy

options = {
    'font_weight': 'bold',
    'node_color': 'red',
    'font_color': 'black',
    'edge_color': 'red',
    'node_size': 1000,
    'width': 2,
    'arrowstyle': '-|>',
    'arrowsize': 15
}

Labels = {0:'Univ', 1:'ProfA', 2:'ProfB', 3:'StudentA', 4:'StudentB'}

G = networkx.DiGraph()

G.add_node(0, label='Univ')
G.add_node(1, label='ProfA')
G.add_node(2, label='ProfB')
G.add_node(3, label='StudentA')
G.add_node(4, label='StudentB')

G.add_edges_from([(0, 1), (0, 2), (1, 3), (2, 4), (4, 2), (3, 0)])

# Debug
# networkx.draw_networkx(G, arrows=True, with_labels=True, labels=Labels, **options)

# simrank_similarity
sim = networkx.algorithms.similarity.simrank_similarity(G)
sim_array = numpy.array([[sim[u][v] for v in sorted(sim[u])] for u in sorted(sim)])
print(sim_array)

# simrank_similarity_numpy
sim_array_numpy =  networkx.algorithms.similarity.simrank_similarity_numpy(G)
print(sim_array_numpy)
```

Based on the image above, the simrank_similarity_numpy shows the expected weights as opposed to simrank_similarity which shows unexpected values.

Maybe I am missing something important or somewhat else?

Thanks in advice!

**Comment by ryan-duve** [comment]
I took a look at this and was able to reproduce the problem.  I opened [a PR](https://github.com/networkx/networkx/pull/3961) proposing a fix.

**Comment by dschult** [comment]
Thanks very much for this report!  Nicely put together... (and followed up when a fix was proposed) Thanks...
