### ISSUE TITLE
Add useful `__repr__` methods

### ISSUE THREAD

**Issue by cool-RR** [networkx/networkx#3956]
For example, instead of `<networkx.classes.digraph.DiGraph object at 0x0000000003D6DE80>` we could have `<networkx.DiGraph: 7 nodes, 5 edges>`

**Comment by ryan-duve** [comment]
I think it might be very verbose to unambiguously define the graph with `__repr__`.  Would it serve better to give classes a human-readable `__str__` instead?

**Comment by dschult** [comment]
```__repr__``` is supposed to create a string that could be used as code to generate the object. That is very hard to do well for a graph object with arbitrary attributes. It's better to use the 
```nx.info(G)``` function is you are interested...

**Comment by cool-RR** [comment]
I submitted #3968 , if you have any comments please post them there.

**Comment by dschult** [comment]
We won't be implementing this.
