### ISSUE TITLE
Example to run on CUDA

### ISSUE THREAD

**Issue by sashml** [networkx/networkx#3957]
Is that possible to support CUDA?

**Comment by MridulS** [comment]
checkout https://github.com/rapidsai/cugraph, networkx like API with GPU support.

**Comment by ericmjl** [comment]
I am going to close this issue, as I think cuGraph is the right answer. The API developments are in the right direction, though not yet at parity with NetworkX.

**Comment by sashml** [comment]
Thank you a lot! Didn´t expect to get the feedback, really appreciate!
