### ISSUE TITLE
average_clustering defaults undefined to 0

### ISSUE THREAD

**Issue by matiasmorant** [networkx/networkx#3966]
there are 3 cases:
1- nodes with clustering_coefficient undefined (if it has < 2 neighbours)
2- nodes with clustering_coefficient= 0
3- nodes with clustering_coefficient > 0

networkx takes nodes in the first case as having clustering=0 .
Gephi ignores nodes in case 1, and only averages over nodes in cases 2 and 3

This difference can have a significative impact on the result if there are many nodes in class 1

![image](https://user-images.githubusercontent.com/5036575/82391333-6d7c2800-9a17-11ea-885f-52aed506d470.png)

```
G = nx.Graph()
G.add_nodes_from([1,2,3,4,5,6])
G.add_edges_from([(1,2),(2,3),(3,1)])
result = nx.average_clustering(G)
```
in networkx, `result==0.5` while in gephi `result==1.0`

is there a 'right' answer about what to do with nodes in case 1 ?

**Comment by dschult** [comment]
People use both definitions. The measure different things. It depends what you need it for.
There is a keyword option ```nx.average_clustering(G, count_zeros=False)``` to allow you to choose which you want. ```count_zeros=True``` is the default.

**Comment by matiasmorant** [comment]
@dschult setting `count_zeros=False` would exclude nodes which have a well-defined `clustering_coefficient == 0` also, right?
I see no way of excluding only nodes which have `clustering_coefficient == undefined` (nodes with neighbours < 2)

**Comment by dschult** [comment]
Correct -- though it is not too hard to build things using ```cdict = nx.clustering(G)``` and ```deg = G.degree()``` to filter only the nodes with degree >=2 and average those.

**Comment by rossbar** [comment]
It seems like the conversation here has resolved things so I'm going to close this for now. Feel free to re-open if there are still things that need to be addressed.
