### ISSUE TITLE
Distinctiveness Centrality

### ISSUE THREAD

**Issue by iandreafc** [networkx/networkx#3969]
We recently developed a Python package to calculate **Distinctiveness Centrality**.
Here is our **code**: https://github.com/iandreafc/distinctiveness
also available on **Pypi** and already built over **Networkx**: https://pypi.org/project/distinctiveness/
Here is **the paper** that describes the metric:  https://doi.org/10.1371/journal.pone.0233276

We just created a pull request with the hope we did everything right #3978 
It would be super if you guys could help us integrate Distinctiveness directly into Networkx!

**Comment by iandreafc** [comment]
I tried to create my first pull request, which should add distinctiveness: #3971  
Please be patient if I did something wrong :)

Also I would like to provide docs for this new function, like this: https://distinctiveness.readthedocs.io/en/latest/functions/
but I still don't know how to do it.

**Comment by rossbar** [comment]
I'm going to go ahead and close this so we don't invite conversation in multiple places. Please discuss in #3978 - thanks for the contribution @iandreafc !

**Comment by iandreafc** [comment]
Thanks! :) Please let me know if I have to do something more, or just wait for your feedback on the pull request.
