### ISSUE TITLE
infinite loop with bellman ford negative cycle

### ISSUE THREAD

**Issue by hl037** [networkx/networkx#3975]
This graph causes an infinite loop with bellman ford short path. Note : I had to write it in pickle format since it seems the bug does not occurs when loading from other formats (node : the node keys are ints while with other format, they loads as str and the negative cycle is spotted).

[BUG.pickle.zip](https://github.com/networkx/networkx/files/4684398/BUG.pickle.zip)

To reproduce : (python 3.8.2) : 
```
import networkx as nx
G = nx.read_gpickle('BUG.pickle')
nx.single_source_bellman_ford(G, -1, target=-2, weight='w') 
```
With a debugger, we can see the relaxation loop is done but there is a cycle in pred.

**Comment by manasjoshi14** [comment]
Works fine with the current master. Please check again

Output using Python 3.8.2, nx version 2.5rc1.dev_20200527015108

(1.0000000023000002, [-1,124,125,274,275,424,425,576,577,728,729,880,881,1032,1033,1184,1185,1336,1337,1490,1491,1644,1645,1798,1799,1954,1955,2110,2111,2266,2267,2424,2425,2584,2585,2744,2745,2904,2905,3064,3065,3224,3225,3384,3385,3544,3545,3704,3705,-2])

**Comment by hl037** [comment]
Thanks !
Indeed, I didn't check the latest version...
Well, at least, if someone using stable encounters the probleme, now he knows Bellman-Ford is bogus in this version ^^'
