### ISSUE TITLE
girvan_newman mistakenly thinks edge is not in graph?

### ISSUE THREAD

**Issue by maya123z** [networkx/networkx#3977]
I am trying to run girvan_newman on my graph. I used the following code:

```
import operator
def get_edge(graph):
    centrality = nx.edge_betweenness_centrality(graph, k=1000)
    return(max(test.items(), key=operator.itemgetter(1))[0])
gn = nx.algorithms.community.centrality.girvan_newman(my_graph, get_edge)
communities = []
counter = 0
while counter < 10:
    communities.append(tuple(sorted(c) for c in next(gn)))
    counter += 1
```
However, this gives me an error:
`NetworkXError: The edge 4704-4693 is not in the graph`
I double checked and this edge definitely is in my graph, so I'm not sure what's going wrong here.

**Comment by manasjoshi14** [comment]
Issue seems to be with your "get_edge" function. 
I believe this : 
`return(max(test.items(), key=operator.itemgetter(1))[0])`  
should be changed to : 
`return(max(centrality.items(), key=operator.itemgetter(1))[0])`  

Girvan-Newman iteratively removes edges to discover communities in it. The case might be that the edge 4704-4693 is present in your actual graph but was removed in one of the iterations. In the next iteration, an edge from the remaining graph must be chosen but your "get_edge" function doesn't seem to use the input "graph"

**Comment by maya123z** [comment]
You are completely right, it was just a typo that I missed! Thanks for your help.
