### ISSUE TITLE
add_node attributes

### ISSUE THREAD

**Issue by evowilliamson** [networkx/networkx#3979]
Hello,

add_node on the graph accepts attributes. I know it can be used to provide your own set of attributes, but it's also used for system defined attributes like colors, sizes, etc.

Is there a list of system defined attributes available where I can choose from ? For example, I tried "linewidth" in order to determine the width of the line, but that doesn't seem to work. I've looked into the source code, but to no avail.

**Comment by dschult** [comment]
The "system defined attributes" actually isn't a well defined term here. What "system" are you referring to? It sounds like you are trying to draw perhaps using matplotlib, but perhaps using another drawing package. If it is matplotlib, then is the "system" you are talking about matplotlib?  And the attributes are defined according to what matplotlib makes available. They aren't really "system" attributes so much as matplotlib attributes.

To see the attributes commonly used check [the drawing documentation](https://networkx.github.io/documentation/stable/reference/drawing.html). For less common attributes you should look at the matplotlib documentation
