### ISSUE TITLE
Documentation for approximate_current_flow_betweenness_centrality, edge_current_flow_betweenness_centrality and current_flow_betweenness_centrality does not match

### ISSUE THREAD

**Issue by beckedorf** [networkx/networkx#3980]
In the documentation the default `solver` of nx.approximate_current_flow_betweenness_centrality nx.edge_current_flow_betweenness_centrality and nx.current_flow_betweenness_centrality is `'lu'`. In the definition of the function the default is however `'full'`.

As `'lu'` is the recommended method and it is the default is in 

- `nx.edge_current_flow_betweenness_centrality_subset`, 
- `nx.current_flow_betweenness_centrality_subset`, 
- `nx.current_flow_closeness_centrality` 

the defaults should be changed here as well.

**Comment by dschult** [comment]
Can you please change the documentation instead of changing the default?
The history of commits shows that #3981 changed the default to "full".
But it neglected to change the documentation. Let's bring it up-to-date by 
changing the documentation.    Thanks for bringing this issue to light!
