### ISSUE TITLE
contracting (merging) nodes 

### ISSUE THREAD

**Issue by moh55m55** [networkx/networkx#3984]
I Hope everyone is well.
I have an undirected graph. I want to aggregate two nodes but also do some arithmetic operation on the resultant edges's weight after the merging process. You can see in the first figure if a merge occurs between node (2) and node (0) using function `nx.contracted_nodes(G, source, target)` the result will be figure 2, but the new weight between (5) and (0) was chosen to be 27.92 instead of 23.11. It could be the order of the nodes. My question: How do I specify a certain operation on the new edge's weight; e.g. taking the average of the two edges? i.e. 25.51.  

This is a toy example.
Thanks, 

<img width="286" alt="Screen Shot 2020-06-02 at 10 36 28 PM" src="https://user-images.githubusercontent.com/16886629/83590088-f53b5980-a522-11ea-8e41-7b6e0b920409.png">
<img width="251" alt="Screen Shot 2020-06-02 at 10 38 38 PM" src="https://user-images.githubusercontent.com/16886629/83590091-f5d3f000-a522-11ea-81db-07cd7e6a1b10.png">

**Comment by dschult** [comment]
The ```nx.contracted_nodes``` function does not provide this feature, but it would not be hard to implement:  (untested)

```python
# merge v into u with edge weights the average of previous edges to u and v.
# for directed or multigraph this would be slightly more convoluted
H = G.copy()
for _, w, uw_weight in H.edges(v, data='weight'):
    if u in G[w]:
        H.add_edge(u, w, my_edge_func(uw_weight, G[w][u]['weight']))
    else:
        H.add_edge(u, w, uw_weight) 
H.remove_node(v)
```

**Comment by moh55m55** [comment]
Great! 
Does adding this feature to 'contracted_nodes'  worth a PR? 
Also just to make sure, I added `if u!=w:` to prevent self-loop. That seems correct,right?
```python
	H = G.copy()
	for _, w, uw_weight in H.edges(v, data='weight'):
		if u!=w:
			if u in G[w]:
				H.add_edge(u, w, weight=my_edge_func(uw_weight, G[w][u]['weight']))
			else:
				H.add_edge(u, w, weight=uw_weight) 
	H.remove_node(v)
```

**Comment by dschult** [comment]
The handling of self-loops is controlled in ```contracted_nodes``` by a keyword input parameter. So, whether to include that if statement depends on how you want to handle self-loops. And I guess your suggestions handles pre-existing self-loops while the parameter handles created self-loops. Add to those complications the tweaks for directed and multigraph and you can see why we haven't tried to include all the possible ways people would want to contract nodes. :}  If you can come up with a simple interface that allows the flexibility we would probably all like, then a PR is greatly appreciated. But it is not usually a quick fix in cases like this.  Maybe the thing to do is include examples of how to build your own... But if you think hard about it, it seems like its often possible to find a flexible intuitive interface. :}

**Comment by dschult** [comment]
Please comment here (or reopen) if anyone has ideas.... Or just open a new PR/issue...  Thanks!
