### ISSUE TITLE
FutureWarning on arrays to stack

### ISSUE THREAD

**Issue by alan-isaac** [networkx/networkx#3989]
> Python38\lib\site-packages\networkx\drawing\layout.py:950: FutureWarning: arrays to stack must be passed as a "sequence" type such as list or tuple. Support for non-sequence iterables such as generators is deprecated as of NumPy 1.16 and will raise an error in the future.

**Comment by dschult** [comment]
What version of NetworkX gives this warning?
It looks like #3764 fixes this error. It is in the latest (v2.5dev), but not the stable (v2.4) release.

**Comment by alan-isaac** [comment]
It is 2.4, the latest available on PyPI.

**Comment by dschult** [comment]
Good -- v2.4 is the "stable" version.   v2.5 is in the works on github and will be released this Summer.  It already has the fix in it.

Thanks for the report!
