### ISSUE TITLE
time complexity of the methods

### ISSUE THREAD

**Issue by newbie2k20** [networkx/networkx#3990]
sir i am working on community detection and trying to optimize parts of the code. It would be great help for a newbie like me if there is a note in the documentation indicating the time complexity of the methods. Can you tell me what is the time complexity of the following methods:
1. Graph.subgraph(nodes)
2. connected_components(Graph)

**Comment by ph4z** [comment]
👍 Indeed. It would be great time complexity in docs especially for algorithm methods.

**Comment by dschult** [comment]
Time complexity in terms of what variables? There is no one answer to this question. 
I agree that it would be great to know these values -- both from the perspective of algorithms and from actual tests of the time complexity as we have coded them (which hopefully matches the theoretical algorithm).  
This seems like a noble goal. But it needs to be specified more specifically.

We will certainly add complexity measures to the documentation wherever it is known and an PR is created.

For example, ```Graph.subgraph(nodes)``` should not depend on the length of nodes or the size of Graph when it is created. But will depend on those sizes when it is used.  This IS documented already, though perhaps not clearly enough.

We are open to PRs in this area.  I am closing this Issue but please comment or reopen as needed.

**Comment by newbie2k20** [comment]
can you tell what is the time complexity of the following code segment
I have an undirected graph G=(V,E) and list of list 'node' contains nodes of G.
```
node=[[1,12,3,4,6],[7,11,9,15],[5,8,13,14],[6,7]]
for sublist in node:
    sg=G.subgraph(sublist)
    comp=list(nx.connected_components(sg))
```
