### ISSUE TITLE
How to calculate the GED by the paths?

### ISSUE THREAD

**Issue by tiankonghenlan20113046** [networkx/networkx#3991]
Hi, dear code author,
I am making researching on the graph edit distance by **[A*](https://github.com/networkx/networkx/blob/7ae7f0146a33e340acbabe5a11d297e8187cb6d8/networkx/algorithms/similarity.py#L153)** .I have 2 questions.

Firstly,I know that we can get a best path (or several best path) transforming a graph to another. But GED is the number of operations transfoming a graph to another graph. That is , how to calculating the GED by paths (or mapping we get by the algorithm)? 

Secondly, I construct two graphs.The expected GED is 2, but it gives the 1.The code in my [github ](https://github.com/tiankonghenlan20113046/networkx_GED/blob/29f4367975625b35fe4150849568a09a4823b547/calculate_GED.py#L31)  shows me how to calculate it .
we should subustitue edge(1,3) which labels '1' in q to edge (1,3) which labels '2' in g2, insert edge (1,3)  labeling '1' in q to g2. These two editi operations equal **GED = 2**.But the function gives me **1**.
Please which faults did  I make ? @jwegis @lonnen

**Comment by lonnen** [comment]
As I understand it the graph_edit_distance function does not consider labels, and your result reflects only substituting the edge.

Here is how I decided that --

If you look into the [source code](https://github.com/networkx/networkx/blob/7ae7f0146a33e340acbabe5a11d297e8187cb6d8/networkx/algorithms/similarity.py#L163):
```python
	bestcost = None
	for vertex_path, edge_path, cost in optimize_edit_paths(...):
		bestcost = cost
	return bestcost
```

The `optimize_edit_paths(...)` function is the source of the 'cost' parameter, so let's look at that:

```python
    paths = list()
    bestcost = None
    for vertex_path, edge_path, cost in optimize_edit_paths(
        G1,
        G2,
		#...removed kwargs that are not useful to us...
    ):
        # assert bestcost is None or cost <= bestcost
        if bestcost is not None and cost < bestcost:
            paths = list()
        paths.append((vertex_path, edge_path))
        bestcost = cost
    return paths, bestcost
```

This function gets edit paths and costs, but those paths do not contain any label information. They only have structural data about edges and nodes. That leads me to think that maybe labels are not considered. If you want to be certain, then we have to look at the function that returns the cost info: [`optimize_edit_paths()`](https://github.com/networkx/networkx/blob/7ae7f0146a33e340acbabe5a11d297e8187cb6d8/networkx/algorithms/similarity.py#L498)

```python
def optimize_edit_paths(
    G1,
    G2,
    node_match=None,
    edge_match=None,
    node_subst_cost=None,
    node_del_cost=None,
    node_ins_cost=None,
    edge_subst_cost=None,
    edge_del_cost=None,
    edge_ins_cost=None,
    upper_bound=None,
    strictly_decreasing=True,
):
    """GED (graph edit distance) calculation: advanced interface.
	..."""
```

The documentation there is extensive and lays out what each of these arguments does. One of the arguments, `edge_match`, tells us it should be `A function that returns True if the edge attribute dictionaries for the pair of nodes (u1, v1) in G1 and (u2, v2) in G2 should be considered equal during matching.`.

If you keep tracing through library code you'll eventually find [`match_edges(...)`](https://github.com/networkx/networkx/blob/7ae7f0146a33e340acbabe5a11d297e8187cb6d8/networkx/algorithms/similarity.py#L685) used in [`get_edit_ops(...)`](https://github.com/networkx/networkx/blob/7ae7f0146a33e340acbabe5a11d297e8187cb6d8/networkx/algorithms/similarity.py#L774).

And you can keep going like that if you'd like, but it's easy to get lost diving into a complex and unfamiliar function like this. Especially when you're looking for something that is missing. You can search, but it is hard to search for the absence of something without having to understand it completely. At this point I decided I wouldn't look any deeper.

From what I can see, there is no documentation or code anywhere here that mentions or examines labels and the function `optimize_edit_paths` returns costs associated only with structural edges and nodes, so I don't believe labels are considered.

**Comment by lonnen** [comment]
I'm not really a maintainer of this repo, though, so I must defer to @jwegis (👋) to decide how to resolve this issue

**Comment by tiankonghenlan20113046** [comment]
> I'm not really a maintainer of this repo, though, so I must defer to @jwegis (👋) to decide how to resolve this issue

Anyway,Thanks for your reply .

**Comment by dschult** [comment]
@lonnen is correct. In order to consider edge attributes when matching edges, you must create the conditions for the match. That is done with the ```edge_match``` parameter of the ```optimize_edit_paths``` function. The ```edge_match``` parameter must be a function that inputs the edge data dict for the two edges, and return True when those should be considered to be matched. Importantly, the documentation says "If neither edge_match nor edge_subst_cost are specified then edge attributes are not considered."

So, if you want to match edges only when labels match, something like this ought to work:
```python
edge_match = lambda dd1, dd2: dd1['label'] == dd2['label']
```

Try it with a toy example first to make sure you understand what it does.

**Comment by dschult** [comment]
I'm going to close this, but anyone with more comments can add them or reopen as needed.
