### ISSUE TITLE
Lifetime to edge

### ISSUE THREAD

**Issue by atilaajones** [networkx/networkx#3992]
Hello. 

Does anyone know if it is possible to determine lifetime for edges in that package? For example, there is a time passing and each edge has a life span [a, b], where the edge only exists if time is in that interval.

thank you

**Comment by dschult** [comment]
That feature is not built-in. But the idea behind building it yourself is not too bad...

- Create each edge with a 'time' attribute:  ```G.add_edge(u, v, time=[a, b])```
- Store the current time e.g. as a graph attribute: ```G.graph['now'] = t```
- Build the time-checking into a ```generic_graph_view``` which requires that the edge have a 'time' attribute that includes the current time.  (this is untested)

```python
def time_filter(G, node, nbr):
    '''Return True if current time is between time endpoints for edge (node, nbr)'''
    start, end = G[node][nbr]['time']
    now = G.graph['now']
    return start <= now <= end

Graph_at_now = nx.subgraph_view(G, filter_edge = time_filter)
```

The idea is that you can change the time of the graph and still use the same subgraph_view.  Changing the graph while also changing the time might lead to trouble. Depends what you are doing.

**Comment by atilaajones** [comment]
It's a good idea. I need this functionality in the EoN package, I will try. Thanks a lot for the help.
