### ISSUE TITLE
[: Feature Request] - Syntax sugar for filtering/quering of nodes and edges

### ISSUE THREAD

**Issue by PuneethaPai** [networkx/networkx#4001]
Influenced from python-igraph:
---

python-igraph has a pretty cool sytax sugar like
ref: https://igraph.org/python/doc/tutorial/tutorial.html#querying-vertices-and-edges-based-on-attributes
- find
- select
- slicing virtices and edges, etc

Examples:
```python

# Find vertex by attributes
claire = g.vs.find(name="Claire")

# Looking up vertices by names
assert g.degree("Dennis") == g.vs.find("Dennis").degree()

# Select vertices as per filter function
g.vs.select(lambda vertex: vertex.index % 2 == 1) 

# Select vertices from the input list
g.vs.select(2, 4, 6) 

# Select vertices as per attribute condtion
g.vs.select(age_lt=30) 
g.vs(age_in=[10, 20, 30])

# Select Edge b/w men and women
men = g.vs.select(gender="m")
women = g.vs.select(gender="f")
g.es.select(_between=(men, women))

# Slicing vertices and edges
g.vs[4:40]
g.es[3:-2]
```

## I am fascinated by this following feature table:

Keyword argument | Meaning
-- | --
name_eq | The attribute/property value must be equal to the value of the keyword argument
name_ne | The attribute/property value must not be equal to the value of the keyword argument
name_lt | The attribute/property value must be less than the value of the keyword argument
name_le | The attribute/property value must be less than or equal to the value of the keyword argument
name_gt | The attribute/property value must be greater than the value of the keyword argument
name_ge | The attribute/property value must be greater than or equal to the value of the keyword argument
name_in | The attribute/property value must be included in the value of the keyword argument, which must be a sequence in this case
name_notin | The attribute/property value must not be included in the value of the the keyword argument, which must be a sequence in this case

## Feature Request:
- Even though we can do all the above with few lines of python code the examples shown above is pretty neat and handy.
- Let me know what you folks think.

Thanks

*PS: I think networkx is pretty neat and easy to start with.*

**Comment by dschult** [comment]
We've tried to keep the syntax creation/maintenance minimal by using Python native syntax (essentially list/dict comprehensions).

```python
age_lt_30 = [node for node, age in G.nodes(data="age") if age < 30]  
degree_le_4 = [node for node, deg in G.degree() if deg<4]

claire_nodes = [node for node, name in G.nodes(data="name") is name == "Claire"]
```

If this doesn't fit what you've got in mind comment more or reopen... Thanks!

**Comment by PuneethaPai** [comment]
Agreed @dschult .
These are nice to have syntax sugars. It becomes very intuitive to use with this.

What do you suggest for slicing/dicing?

```python
# Slicing vertices and edges
g.vs[4:40]
g.es[3:-2]
```
Using list comprehensions we can store nodes/edges and then slice them.

But it simply causes memory shoot. If we return generators as `python-igraph` does like (`g.vs, g.es`), we can use `itertools.islice` which will be memory efficient.

I would go for generators over syntax sugar. Let me know what you think.

**Comment by dschult** [comment]
G.nodes and G.edges are iterators over nodes and edges. Would that work with ```itertools.islice```?

**Comment by PuneethaPai** [comment]
It works, just checked.
Thanks
