### ISSUE TITLE
Unhelpful generic error message in to_networkx_graph

### ISSUE THREAD

**Issue by anentropic** [networkx/networkx#4002]
I'm trying to instantiate a `DiGraph` from a view of a `MultiDiGraph` filtered to select only one out of any parallel edges.

Right this minute I'm not sure if I constructed my graph or graph view wrong, but the point is I'm getting this error:

```
networkx.exception.NetworkXError: Input is not a correct NetworkX graph.
```

It comes from the call to `convert.to_networkx_graph` in `DiGraph.__init__` which has this code:
```python
        if hasattr(data, "adj"):
            try:
                result = from_dict_of_dicts(data.adj,
                                            create_using=create_using,
                                            multigraph_input=data.is_multigraph())
                if hasattr(data, 'graph'):  # data.graph should be dict-like
                    result.graph.update(data.graph)
                if hasattr(data, 'nodes'):  # data.nodes should be dict-like
                    # result.add_node_from(data.nodes.items()) possible but
                    # for custom node_attr_dict_factory which may be hashable
                    # will be unexpected behavior
                    for n, dd in data.nodes.items():
                        result._node[n].update(dd)
                return result
            except:
                raise nx.NetworkXError("Input is not a correct NetworkX graph.")
```

Fortunately my test graph is very small and hand-constructed and I will step through in a debugger and work out what's wrong.

But it'd be great if this code didn't swallow the source of the actual error.

How would you feel if I opened a Pull Request to change this to:
```python
    try:
        ...
    except Exception as e:
        raise nx.NetworkXError("Input is not a correct NetworkX graph.") from e
```
?

Thanks for a great library!

**Comment by dschult** [comment]
See also #4000 which suggests avoiding swallowing exceptions throughout the code.
