### ISSUE TITLE
Node_classification_hmn function and the publication

### ISSUE THREAD

**Issue by neocsbee** [networkx/networkx#4005]
The implementation [here](https://networkx.github.io/documentation/stable/_modules/networkx/algorithms/node_classification/hmn.html)  does conversion to matrix form without considering weights, however the pertinent paper on which this implementation is based stresses on having a weight matrix. 
Are there plans for further enhancement to make the implementation align better with the publication?

**Comment by dschult** [comment]
@yamaguchiyuto any thoughts on this?

**Comment by rossbar** [comment]
Is this issue still relevant? @neocsbee could you provide more specific information from the paper that is at odds with the current implementation?

**Comment by MridulS** [comment]
This hasn't been touched in a while, I'll go ahead and close this. @neocsbee feel free to open a new issue with more details :)
