### ISSUE TITLE
Python 2 links in docs

### ISSUE THREAD

**Issue by jond01** [networkx/networkx#4006]
Here is one example, but it is general:
https://networkx.github.io/documentation/latest/reference/generated/networkx.drawing.layout.bipartite_layout.html?highlight=dict
Pressing *dict* link in the `Return type` leads to:
https://docs.python.org/2/library/stdtypes.html#dict
it would be best to change it to
https://docs.python.org/3/library/stdtypes.html#dict
Or even:
https://docs.python.org/library/stdtypes.html#dict

**Comment by dschult** [comment]
Interesting...  That's a generated doc page so presumably a feature of sphinx...
Is there a sphinx option to affect this change?

**Comment by jond01** [comment]
Right, I have just found that:
https://github.com/networkx/networkx/blob/bd1c7bbb9b9e7c3500a852d1f691134310c0ecd2/doc/conf.py#L193-L195
Preferably, we can change it to `"https://docs.python.org/"` (rather than `"https://docs.python.org/3/"`).
I noticed another python 2 links in the project, they should probably be treated in the same way. For example:
https://github.com/networkx/networkx/blob/a4d024c54f06d17d2f9ab26595a0b20ed6858f5c/networkx/classes/digraph.py#L1136
Also version-specific links:
https://github.com/networkx/networkx/blob/9b02800087d6a400ce84f9e44a15eee41c27c4dd/networkx/readwrite/tests/test_gexf.py#L286
