### ISSUE TITLE
Question about flow solving with simplex algorithm

### ISSUE THREAD

**Issue by ph4z** [networkx/networkx#4011]
See the code below:

```python
import networkx as nx
G=nx.DiGraph()
G.add_edge(1,2,capacity=7, weight=1)
G.add_edge(2,3,capacity=5, weight=1)
G.add_edge(2,4,capacity=4, weight=1)
G.nodes[1]['demand']=-7
G.nodes[2]['demand']=0
G.nodes[3]['demand']=2
G.nodes[4]['demand']=5
_, flows = nx.network_simplex(G, 'demand', 'capacity', 'weight')
print(flows)
```
It will raise the exception `networkx.exception.NetworkXUnfeasible: no flow satisfies all node demands` because edge (2,4) capacity is < 5.
But there is still a valid flow 1->2->3 which satisfy demands and capacities.

Does anyone have an idea or a workaround for finding theses residual flows in case of unfeasible exception ?

**Comment by dschult** [comment]
The flow ```1->2->3``` doesn't satisfy the demands and capacities.

Flow problems must satisfy all demands and capacities. Are you looking for an algorithm that takes the specified problem and looks for all possible partial solutions? That's a much more difficult problem.  Any ideas for an algorithm to approach it?

**Comment by ph4z** [comment]
> Are you looking for an algorithm that takes the specified problem and looks for all possible partial solutions?

Yes. I will need to trigger it if simplex raises the unfeasible exception.

> Any ideas for an algorithm to approach it?

Below a naive approach.  It tries to solve flow for each source and sink node pairs, but I have not tested it yet and there few things I am not sure about.
```python
srcdict = all nodes with 'demand' < 0
tgtdict = all nodes with 'demand' > 0
for src, src_demand in srcdict.items():
 for tgt, tgt_demand in tgtdict.items():
   S = subgraph(G, src, tgt) # Not sure how to do this
   S.nodes[src]['demand'] = -min(abs(src_demand), abs(tgt_demand))
   S.nodes[tgt]['demand'] = min(abs(src_demand), abs(tgt_demand)) 
   try:
    _, flows = nx.network_simplex(S, 'demand', 'capacity', 'weight')
   if flows:
     updateOriginalDemandDicts(flows)
```

What do you think about it ? Do you see something better ?

**Comment by dschult** [comment]
I don't think the problem is well defined.

If pairwise flows is what works for you then great -- 
I think your subgraph S should include the entire graph...

**Comment by ph4z** [comment]
@dschult: Does you or your team provides dev and/or consulting services ?
