### ISSUE TITLE
Abstract base class for Graph, DiGraph, MultiGraph, and MultiDiGraph

### ISSUE THREAD

**Issue by winni2k** [networkx/networkx#4018]
I am working with a project (https://github.com/broadinstitute/pyfrost/issues/1) that is using a custom backend for graph storage instead of dicts of dicts, mostly in order to save memory. The project is attempting to create a DiGraph compliant interface in order to use networkx algorithms. I have found it challenging/error prone to create a DiGraph-compliant interface in the past and I would find it helpful to have an abstract base class for the networkx graph types. Does this already exist somewhere? Is this an [XY](http://xyproblem.info/) problem, and should I/we be thinking about our problem in pyfrost differently?

**Comment by dschult** [comment]
The NX2.x data structure was an attempt to make this easier to achieve. 
The first place to explore is the ```dict_factory``` functions. If you can make a custom backend that replaces, e.g. G._succ and G._pred you can make a new class to use that backend with code like:

```python
class MyGraph(Graph):
    adjlist_outer_dict_factory = my_backend_adjlist_factory
    adjlist_inner_dict_factory = my_backend_neighbors_dictlike_factory
```

In [the Graph docs](https://networkx.github.io/documentation/stable/reference/classes/graph.html) there is a section on "SubClasses" which might help explain more.
Check out the ThinGraph example in that same section of the docs.

Comment more here or reopen, or open a new issue if you have other questions.
