### ISSUE TITLE
drawing module silently ignores superfluous **kwds

### ISSUE THREAD

**Issue by blsqr** [networkx/networkx#4020]
The drawing methods defined in [`networkx.drawing.nx_pylab`](https://github.com/networkx/networkx/blob/master/networkx/drawing/nx_pylab.py) all define `**kwds` to grab keyword arguments.
While `**kwds` that are passed to the `draw` function are passed on (e.g. to `draw_networkx_edges`), they end up not being handled at all: `draw_networkx_edges` and `draw_networkx_nodes` make no use of `**kwds`.

In my opinion, this can be problematic for the following reasons:
1. Unexpected additional keyword arguments can end up not having an effect
   - They do not raise an exception either, which would help a user to find out about the wrong argument name
   - Example: passing `cmap` to `draw_networkx_edges` instead of the expected `edge_cmap` just ignores `cmap`
2. Lost opportunity: `**kwds` could be passed on to the matplotlib plotting function
   - Given that many of the `draw_networkx_edges`/`draw_networkx_nodes` end up in matplotlib functions anyway, this would not be unexpected, imo.

### Proposal
Adjust the `draw` functions such that superfluous `**kwds` are *not* ignored but either have some purpose or raise an error.

Three possibilities to achieve that come to my mind:

1. Still allow `**kwds`, but check for unexpected keys in the `kwds` dict and raise an informative error
2. or: Don't allow `**kwds` in `draw_networkx_edges`/`draw_networkx_nodes`, which would raise a `TypeError` due to passing an unexpected argument
3. or: Pass on `**kwds` to the `LineCollection` or `ax.scatter`, respectively, thus letting matplotlib handle any additional keyword arguments and the error message (which they already do)

Does this make sense? Is there something I'm missing?  
If this is a suitable proposal, I would be happy to open a PR for it.

**Comment by dschult** [comment]
I checked the "Blame" on those lines of code. They were put in place 14 years ago with the ironic commit message:
```put in **kwds arguments until we handle them more carefully```
So... I guess it's probably time to figure out how to include them...    :}

The issues at the time were that we wanted people to be able to include any keywords for ```draw_networkx_nodes``` and ```draw_networkx_edges``` without having to call them explicitly -- so ```kwds``` might have keywords for both of those functions and that'd be OK.  We also didn't want to have to spend effort maintaining either the keywords that are valid for Matplotlib or a list of the keywords valid for each drawing function.  

What do you think is best here?

**Comment by blsqr** [comment]
Thanks for getting back so quickly, @dschult!

> so kwds might have keywords for both of those functions and that'd be OK. We also didn't want to have to spend effort maintaining either the keywords that are valid for Matplotlib or a list of the keywords valid for each drawing function.

I totally see those points; the `**kwds` solution is the easiest in that respect. So that's also why the sets of arguments that are edge-related are prefixed with `edge_`, in order to not be handled by `draw_networkx_nodes` if invoking both via `draw` 💡😄  (When working directly with `draw_networkx_edges/nodes`, I always wondered about why that is; cc @jeremiastraub).

> What do you think is best here?

Touching on _"maintaining [...] a list of the keywords valid for each drawing function"_: I don't think the current interface of `draw` allows what I'm proposing above _without_ such a list. However, I think that list already has to be maintained anyway in form of the [`draw_networkx`](https://github.com/networkx/networkx/blob/master/networkx/drawing/nx_pylab.py#L122) docstring which lists parameters for all other `draw_networkx_*` functions afais.
If the arguments already are in the docstring and the docstring has to be maintained, they might as well be directly specified in the signature, I'm thinking, or in some keyword list that is used to pass only the relevant keywords to the drawing functions?
Superfluous arguments could then raise an error and the edge/node/label functions could drop `**kwds`.

Regarding maintenance: How stable are these interfaces? If they have mostly converged, maintenance perhaps is not that big of an issue?

A second approach could let `draw_networkx` accept the keyword arguments separately for each underlying drawing function. This would allow to not have to deal with them in `draw_networkx`. For docstrings, one could link to the `draw_networkx_edges/nodes/labels` functions.

```python
draw_networkx(G, pos=None, arrows=True, with_labels=True,
              node_kwds: dict=None, edge_kwds: dict=None, label_kwds: dict=None):
    # ...
    draw_networkx_nodes(G, pos, **{node_kwds if node_kwds else {}})
    # and analogously with the others
```
... but this is of course a breaking change _and_ it makes the `draw` invocation more complicated, so I think this is undesirable? I that light, I think the other proposal above is better.

What do you think?

**Comment by dschult** [comment]
It feels like the interfaces have converged, but there may be some matplotlib arguments that have changed without my knowledge. It seems like making a list would likely be helpful and could avoid bugs from people misspelling keywords, etc. That sounds like a  good solution.  Thanks!

**Comment by blsqr** [comment]
Glad to hear! @jeremiastraub and I will open a PR then, if it's ok with you?

**Comment by dschult** [comment]
Sounds good!

**Comment by blsqr** [comment]
FYI: The PR addressing this is #4033
