### ISSUE TITLE
When are we dropping Python 3.6 support?

### ISSUE THREAD

**Issue by NeilGirdhar** [networkx/networkx#4027]
If networkx is part of the "Scientific Python ecosystem", how does it stand on [NEP 29](https://numpy.org/neps/nep-0029-deprecation_policy.html)?
> This NEP recommends that all projects across the Scientific Python ecosystem adopt a common “time window-based” policy for support of Python and NumPy versions. Standardizing a recommendation for project support of minimum Python and NumPy versions will improve downstream project planning.

They argue that projects should drop Python 3.6 support on their next release after June 23, 2020, among other things.  Thoughts?

**Comment by jarrodmillman** [comment]
Yes, we are part of the "Scientific Python ecosystem."  We are follow NEP 29 and already dropped 3.6:
  https://github.com/networkx/networkx/commit/2df70066ecd661aa6ae0a707d10b597c9939c273
The next release in September 2020 will support Python 3.6-3.9.

**Comment by NeilGirdhar** [comment]
Good to know, thanks!

**Comment by jarrodmillman** [comment]
I may have spoken too soon.  After looking into it, it turns out dropping 3.6 will mean dropping support for PyPy.  I also checked the main projects that were behind the proposal.  It looks like NumPy, SciPy, scikit-image, scikit-learn, and yt haven't dropped 3.6 yet.

@stefanv As one of the authors of the NEP, can you give us an update on whether the projects that proposed this NEP are planning to follow it.  And what happens to PyPy support?  Is there any interest in the scientific Python ecosystem supporting PyPy with new releases?  If so, the NEP may need to be revisited.

**Comment by jarrodmillman** [comment]
Just to be clear, deciding whether to drop Python 3.6 now is not about deciding whether NetworkX is a part of the scientific Python ecosystem.  It is and has been from the start.  Whether we drop Python 3.6 now or later doesn't impact that.

**Comment by stefanv** [comment]
We are currently seeing whether we should make the NEP release based, instead of time based. There is a proposal on the NumPy repo by Stephan Hoyer.

**Comment by NeilGirdhar** [comment]
@stefanv Do you have a link?  I can't find it.

**Comment by dschult** [comment]
@NeilGirdhar The NEPs are in the github Numpy repository under doc/NEPs

We are definitely part of the scientific python community.
The strict adherence to the schedule of deprecations may inconvenience some people, and we will try hard not to inconvenience them too much.  For example, we could officially stop supporting python 3.6 but still try to keep the code working with 3.6 wherever we can (which would require testing with CI to at least know where it broke). Or maybe we don't test it, but we don't intentionally introduce code that breaks 3.6.  I'm not sure what the final decision should be. But it seems like we are interested in staying "on schedule" to the extent that it doesn't inconvenience too many users.

**Comment by NeilGirdhar** [comment]
Cool, thanks for the clarification!
