### ISSUE TITLE
"from_pandas_dataframe", small but possible enhancement 

### ISSUE THREAD

**Issue by Koukyosyumei** [networkx/networkx#4038]
This function iterates df.columns now.

            for i, col in enumerate(df.columns):
                if col is not source and col is not target:
                    edge_i.append((col, i))

I think using df.columns.values is more efficient because its type is np.array, although I know the difference is small.

**Comment by rossbar** [comment]
Thanks @Koukyosyumei , if you feel comfortable doing so, feel free to try it out and submit a PR. Performance enhancements are of course welcome!
