### ISSUE TITLE
Looking to iterate over subnetworks in graph

### ISSUE THREAD

**Issue by alexcannan** [networkx/networkx#4040]
Hi there, I'm trying to determine all the subnetworks in my graph, to omit ones less than 3 nodes large. I've searched through the documentation pretty extensively but can't find any functions that would do this. Does anyone have any recommendations for how to generate this? Ideally it would be a list of tuples containing all the nodes in each subgraph.

I'm currently trying to put something together that does this, by iterating over all nodes, and using the all_neighbors function with a list of sets. If something like this doesn't already exist, would a get_subnetworks() function be worth a PR?

**Comment by dschult** [comment]
What is your definition of subnetwork?
We have lots of features "like" what you are talking about, but none named subnetwork.

**Comment by alexcannan** [comment]
@dschult Sorry, by subnetwork I'm referring to subgraphs that share no edges between one another. So, in the following picture, there are 7 "subnetworks" visible. I'd like to return a list of tuples containing the nodes that are in each subnetwork.
![image](https://user-images.githubusercontent.com/19368028/86403079-faeba280-bc7a-11ea-902a-33f2c719d3e9.png)

**Comment by dschult** [comment]
In our lingo, those are called "Connected Components". You can get from nay
node in a connected component to the other in that component and not to
nodes outside that connected component.
Directed graphs have a more complicated structure. Take a look at these docs
<https://networkx.github.io/documentation/stable/reference/algorithms/component.html>

**Comment by alexcannan** [comment]
@dschult Thank you, that page was very helpful. I was able to generate the list I wanted with:

```
subnetworks = []
for c in nx.connected_components(G):
    subnetworks.append(c)
```

The connected_components generator returns sets of nodes, which was exactly the format I was looking for.
