### ISSUE TITLE
subgraph_isomorphisms_iter() but with approximate matchings instead of isomorphisms

### ISSUE THREAD

**Issue by utkarshmttl** [networkx/networkx#4043]
Hello,

I have a data graph and a pattern graph, both directed with categorical edge labels. Currently, I am able to use the subgraph_isomorphisms_iter() function for pattern matching to find matches of pattern graph with the (subgraphs of) data graph; which returns exact matches (subgraph isomorphisms).

However, I'd like to be able to get approximate matches as well, an example criteria for approximate matching could be ` "Graph Edit Distance < N"` (or some other similarity measures?).

Is this possible?

One way I can think of is to iterate over all the possible subgraphs of the data graph (like `for subgraph in nx.connected_component_subgraphs(data_graph):`) and calculate the GED of each such subgraph with the pattern graph. Then choose the subgraphs with GED < N. 

I am wondering if there's a better way because iterating over `2^[num_edges(data_graph)]` subgraphs would not be efficient because, for example, we need not even consider those subgraphs with `num_edges(pattern_graph) - N  < num_edges(subgraph) < num_edges(pattern_graph) + N ` as the edit distance would surely be greater than N for these subgraphs. 

Am I thinking in the right direction? 
Are there any in-built methods to achieve this? 
Are there any completely different algorithms/approaches in the literature to achieve what I am trying to?

Any help is much appreciated. Thanks.

**Comment by kazimierz-256** [comment]
Hi there!
You could use the [optimal edit paths](https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.similarity.optimal_edit_paths.html#networkx.algorithms.similarity.optimal_edit_paths) method to determine which nodes from the pattern graph get transformed into the data graph. Any such node mapping determines the approximate matching you are looking for.

**Comment by utkarshmttl** [comment]
Thank you @kazimierz-256; I will try that.
