### ISSUE TITLE
cut_size optional argument T not actually supported

### ISSUE THREAD

**Issue by harristeague** [networkx/networkx#4052]
https://github.com/networkx/networkx/blob/master/networkx/algorithms/cuts.py

def cut_size(G, S, T=None, weight=None):
   ...

Other functions in this module support the optional T by doing below.  I suspect this is intended for this function as well.

if T is None:
   T = set(G) - set(S)

**Comment by dschult** [comment]
This function uses T in the arguments for ```nx.edge_boundary``` which takes care of the default value for T.
I checked with a simple path graph and it works.  Please post again if I've missed something or it doesn't work for you.
