### ISSUE TITLE
relabel_nodes on MultiGraphs does not preserve both edges when two nodes are replaced by one

### ISSUE THREAD

**Issue by nik0sc** [networkx/networkx#4058]
When the graph contains edges (0,1) and (0,2), and I relabel both 1 and 2 to 3, I expected two edges from (0,3) but only one node is preserved.

Multi*Graph supports parallel edges between nodes and I expected it to preserve both edges when "merging" the two old nodes together.

Tested on both networkx 2.4 and the latest version on master.

```python
import networkx as nx

G = nx.MultiDiGraph([(0,1),(0,2)])
G[0][1][0]["value"] = "a"
G[0][2][0]["value"] = "b"

print(G[0])
# Output:
# {1: {0: {'value': 'a'}}, 2: {0: {'value': 'b'}}}

mapping = {1:3, 2:3}

nx.relabel_nodes(G, mapping, copy=False)

print(G[0])
# Output:
# {3: {0: {'value': 'b'}}}
# Expected:
# {3: {0: {'value': 'a'}, 1: {'value': 'b'}}}
```

**Comment by nik0sc** [comment]
This is fixed if you insert this at line 139 in networkx/relabel.py:
```python
for i, (tail, head, key, data) in enumerate(new_edges):
    if head in G[tail] and key in G[tail][head]:
        next_key = max(k for k in G[tail][head]) + 1
        new_edges[i] = (tail, head, next_key, data)
```
Of course, I am not sure if this is actually the desired behaviour.

**Comment by MridulS** [comment]
Good catch! The relabel should have preserved both values 'a' and 'b'.
Feel free to submit a pull request with a fix for this.

**Comment by dschult** [comment]
This fix assumes that key can be maximized and added to 1. Keys do not have to be numeric.
Perhaps something like:
```python
newkey = 0
current_keys = G[tail][head]
while newkey not in current_keys:
    newkey += 1
```
There may be other better ways to do this.

**Comment by dschult** [comment]
Actually, upon further reflection -- it might be better to explicitly combine nodes...
That is, we might want to impose node_contraction and not let the relabel_nodes function change the graph connections.

What do you think?

**Comment by nik0sc** [comment]
@dschult I understand what you mean, it makes the intention of the programmer clearer. But I think a casual user of networkx (like myself!) would expect the relabel_nodes operation on a MultiGraph to not silently drop all the other edges except one.

Also, node_contraction only contracts two nodes at once, but a fixed relabel_nodes would be able to handle as many nodes and edges as the programmer wants to merge together. It's a minor point and could probably be done by writing some glue code, but it is more convenient.

**Comment by dschult** [comment]
Yes, it seems that the convenience and flexibility of ```relabel_nodes``` may offset the disadvantages.  We will need a fairly strong statement in the docstring about how this relabeling affects the nodes when more than one is relabeled to the same object. 

This sounds good to me.
