### ISSUE TITLE
Tighten partite_layout if/else code.

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#4061]
Tighten up the bipartite_layout and multipartite_layout  if/else as describes in #3815

**Comment by z3y50n** [comment]
Hello I am a newcomer and would like to contribute. Can you explain a bit more about the issue? Basically you want to make one function to handle both bipartite_layout and multipartite_layout or optimize their respective if statements?

**Comment by dschult** [comment]
The [original conversation consisted of 3 comments](https://github.com/networkx/networkx/pull/3815/files#r452534386) in a previous PR #3815.
The intend was not combining those two functions, but rather to simplify the existing functions.

The `multipartite_layout` code involves duplication of very similar lines, with e.g. only "x" and "y" switched. The idea is to refactor the `multipartite_layout` code to (hopefully) improve readability, performance and ease of maintenance.

Some of the same techniques might also improve the code in `bipartite_layout`. But I think that has not been explored yet.
