### ISSUE TITLE
Add option to specify a column for edge keys in Multi(Di)Graphs when reading through pandas

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#4065]
When reading in graphs using pandas `from_pandas_edgelist` should we have an option to let users specify the columns from the dataframe for edge keys?

Example
``` python
G = nx.from_pandas_edgelist(dataframe, source=source,
       target=target, edge_attr=[attr1, attr2, attr3], create_using=nx.MultiGraph())
```
currently networkx will create keys for this graph automatically (0, 1, 2, 3 ......) and to access the edge data we would need to do something like `G[source_node][edge_node][0]`

it would be nice to add an option of adding custom edge keys (assuming we want attr1 to be edge key)
``` python
G = nx.from_pandas_edgelist(dataframe, source=source,
       target=target, edge_attr=[attr2, attr3], edge_key=attr1, create_using=nx.MultiGraph())
```
and access the edge information using  `G[source_node][edge_node][attr1_node]`

**Comment by dschult** [comment]
I don't think we've thought carefully about multigraphs, edge keys and uniqueness of edge keys in a pandas data frame. This Issue sounds like a good idea. We should probably also consider what to do when the edge keys match.  Without multiedges we just overwrite existing data when new edges come in. Maybe duplicate edge/edgekey should do that same?  But maybe not...  What are the use cases here? Are there common data frames that represent multigraphs?

**Comment by Daniel-Davies** [comment]
I think this issue could be useful for a project I am currently doing- may I investigate this? 

As you've described, one logical thing to do with multiedges/ duplicates is to overwrite the existing data- but perhaps there could be some user configurable options. For example, a default would be to overwrite, another method could be a 'log' approach (where each G[source_node][edge_node] is a list), or perhaps another option could be to take the most occuring element?

**Comment by dschult** [comment]
Yes -- please investigate this.  I think for starters you can follow the ```G.add_edge``` treatment that if the edge exists, "adding" the edge just updates the data dict. That is the simplest treatment.
Thanks!

**Comment by Daniel-Davies** [comment]
Raised a PR for the basic version at the moment, but I suppose some discussion is needed on how to deal with duplicates. I will take a closer look tomorrow and propose an option as a new issue?
