### ISSUE TITLE
Example of how to plot a degree distribution could be simplified

### ISSUE THREAD

**Issue by joelmiller** [networkx/networkx#4071]
The example for plotting a degree distribution could be simplified quite a bit through using `plt.hist`

https://networkx.github.io/documentation/stable/auto_examples/drawing/plot_degree_histogram.html

**Comment by MridulS** [comment]
Putting this here just for reference:

We can also directly use `nx.degree_histogram` with `plt.bar`

``` python
degree_hist = nx.degree_histogram(G)
deg = range(len(degree_hist))

plt.bar(deg, degree_hist, width=0.80, color='b')
plt.show()
```

if using `plt.hist`  (is there a better way to plot it?)

``` python
values = [d for n, d in G.degree()]
bins = max(values) - min(values) # multiply this by 2 to make it more "pretty"
plt.hist(values, bins)
plt.show()
```

NOTE: The `nx.degree_histogram` way will include all distribution from degree 0 even if no node exists there, one way to remove that
``` python
degree_hist = nx.degree_histogram(G)
deg = range(len(degree_hist))

for i, j  in enumerate(degree_hist):
    if j != 0:
        start = i
        break

plt.bar(deg[start:], degree_hist[start:], width=0.80, color='b')

```

**Comment by rossbar** [comment]
There are many ways to do this of course (I landed on `plt.bar(*np.unique([d for _, d in G.degree()], return_counts=True))`), but I like @MridulS 's suggestion to use `nx.degree_histogram` best as it illustrates networkx functionality.

**Comment by rossbar** [comment]
The degree histogram example was changed around in #4265 which I think closes this issue - please feel free to reopen/submit PRs with further suggestions!
