### ISSUE TITLE
nx.network_simplex returned flow dict is not ordered

### ISSUE THREAD

**Issue by ph4z** [networkx/networkx#4077]
The code snippet below create a random digraph, set demand on some nodes and then print the computed flow dict:
```python

R = nx.fast_gnp_random_graph(10, 0.5, directed=True)
nx.set_node_attributes(R, {7:{"demand":-7}, 3:{"demand":2}, 1:{"demand":-3}, 5:{"demand":3}, 6:{"demand":3}, 9:{"demand":2}})
nx.network_simplex(R, demand='demand', capacity='capacity', weight='weight')[1]
{0: {1: 0, 3: 4, 7: 0}, 1: {2: 3, 3: 0, 4: 0}, 2: {0: 0, 1: 0, 3: 3, 7: 0}, 3: {1: 0, 4: 0, 5: 0, 6: 3, 7: 0, 9: 2}, 4: {3: 0, 5: 0, 7: 0, 8: 0}, 5: {3: 0, 7: 0, 8: 0, 9: 0}, 6: {0: 0, 4: 0, 7: 0}, 7: {0: 4, 1: 0, 5: 3, 6: 0, 8: 0, 9: 0}, 8: {1: 0, 3: 0, 5: 0, 6: 0, 7: 0}, 9: {0: 0, 1: 0, 2: 0, 3: 0, 5: 0, 6: 0, 8: 0}}
```
It seems the returned dict is based on the order of the nodes, but most of time is is not consistent with the resulting flow.
On the example above, the first non null entry is about sending 4 from node 0 to node 3. 
This issue is that node 0 is neither a sink or a source node.

The flow dict that respect order flow should be (without null values):
```python
{7: {0: 4, 5: 3}, {0: {3: 4}, {1: {2: 3}, 2: {3: 3}, 3: {6: 3, 9: 2}}
````

Any idea how to make the output of network_simplex consistent with the flow order ?

**Comment by dschult** [comment]
A flow is synchronous. There is no inherent order to the flow. All the nodes are receiving and creating flow at the same time and the net flow should meet the demand. Thus if nodes 0 & 1 both are sinks with demand 1, and 2 & 3 are sources with demand -1 and they connect with a node 4 with no demand, then you can't tell whether the flow from 2 goes to 0 or 1. The demands describe the net flow over the whole network. The flow across each edge is the net flow on that edge. But you can't assign an order to the flow in the general formulation of the problem.

I'm going to close this issue, but you can keep posting and we'll see it.
