### ISSUE TITLE
small worldness of multigraphs

### ISSUE THREAD

**Issue by Pegdwende649** [networkx/networkx#4084]
It seems to be no implementation of the sigma and omega values for the multigraphs. How could i retrieve these values ?

**Comment by dschult** [comment]
Can you point to a definition of these values for multigraphs?
The first thing I think of is to treat the multiedges as redundant connections -- that is, they don't affect clustering nor length of paths between nodes. In that case, you should convert the multigraph to a graph and get sigma and omega for the graph.   What is your use case?

**Comment by Pegdwende649** [comment]
Thank you for your answer!
I actually don't see the difference in terms of the definition of these values  between the multigraphs and the graphs.  
Since it's true that the redundant connections don't affect the clustering nor the paths i think  your solution is an interesting one. In my use case it's important to have the multiedges. The goal is to build a synthetic population in which edges are the contacts between people. There are several types of contacts then it is possible to have two persons with two or more types of contacts. For example a person may have a professional and a familial contact with another person.

**Comment by dschult** [comment]
I believe that kind of contact network is quite typical. 
It's like a superposition of networks.  You might even want to store each type of contact as a separate network in some cases. So, then the question about small worldness becomes one of "which edges do we want to consider?"
If all edges provide a connection then insert ```nx.Graph(Mymultidigraph)``` to make it compute using all edges. If you want to measure just the familial contacts then you can make a separate network or you can use a graph_view with filter to only include edges of that type.

Lots of possibilities.. hard to know how to interpret the results. :)
