### ISSUE TITLE
square matrix error using from_pandas_adjacency

### ISSUE THREAD

**Issue by hfl112** [networkx/networkx#4092]
I got an error when using like this. but the matrix.shape is (521, 521), a square one. why the column shape is wrong using nx.from_pandas_adjacency?

G = nx.from_pandas_adjacency(matrix)

---------------------------------------------------------------------------
NetworkXError                             Traceback (most recent call last)
<ipython-input-9-40f2400c9b7c> in <module>
----> 1 G = nx.from_pandas_adjacency(matrix)

~/opt/anaconda3/lib/python3.7/site-packages/networkx/convert_matrix.py in from_pandas_adjacency(df, create_using)
    191 
    192     A = df.values
--> 193     G = from_numpy_matrix(A, create_using=create_using)
    194 
    195     nx.relabel.relabel_nodes(G, dict(enumerate(df.columns)), copy=False)

~/opt/anaconda3/lib/python3.7/site-packages/networkx/convert_matrix.py in from_numpy_matrix(A, parallel_edges, create_using)
    559     if n != m:
    560         raise nx.NetworkXError("Adjacency matrix is not square.",
--> 561                                "nx,ny=%s" % (A.shape,))
    562     dt = A.dtype
    563     try:

NetworkXError: ('Adjacency matrix is not square.', 'nx,ny=(521, 585)')

**Comment by rossbar** [comment]
There's nothing in the `from_pandas_adjacency` function that would modify the shape of your input `matrix`, so most likely this is a problem of the code prior to `from_pandas_adjacency` modifying the shape in the way that you expect.

More information is necessary to help chase this down. Can you provide a minimal example to reproduce the error you are seeing? For example:

```python
>>> import networkx as nx
>>> import pandas as pd
>>> df = pd.DataFrame(np.random.randint(low=0, high=2, size=(521, 521)))
>>> G = nx.from_pandas_adjacency(df)
```
which should work fine.

**Comment by hfl112** [comment]
> There's nothing in the `from_pandas_adjacency` function that would modify the shape of your input `matrix`, so most likely this is a problem of the code prior to `from_pandas_adjacency` modifying the shape in the way that you expect.
> 
> More information is necessary to help chase this down. Can you provide a minimal example to reproduce the error you are seeing? For example:
> 
> ```python
> >>> import networkx as nx
> >>> import pandas as pd
> >>> df = pd.DataFrame(np.random.randint(low=0, high=2, size=(521, 521)))
> >>> G = nx.from_pandas_adjacency(df)
> ```
> 
> which should work fine.

Thank you for your reply. Actually I found that in my matrix there're many duplicate index lead to this error, which were mainly result from my wrong dataframe with duplicates.
