### ISSUE TITLE
Modularity does not appear on documentation website

### ISSUE THREAD

**Issue by bernwaldl** [networkx/networkx#4095]
The function `networkx.algorithms.community.quality.modularity` is not featured on the [documentation website](https://networkx.github.io/documentation/latest/reference/algorithms/community.html?highlight=quality#module-networkx.algorithms.community.quality) and cannot also not be found in [search](https://networkx.github.io/documentation/latest/search.html?q=modularity&check_keywords=yes&area=default). The function does however have a documentation in the [source code](https://github.com/networkx/networkx/blob/d0dbd76ca7129c83311cd9f42e5ca0061176d7f2/networkx/algorithms/community/quality.py#L243) and is marked as importable via `from networkx.algorithms.community.quality import *` in [this line](https://github.com/networkx/networkx/blob/d0dbd76ca7129c83311cd9f42e5ca0061176d7f2/networkx/algorithms/community/quality.py#L14). This applies both to the latest and stable release.

Is it intentional that it does not appear on the website? Because not finding the function on the website caused me to implement it myself, which is not necessarily desirable.

**Comment by dschult** [comment]
No, it just got left out of the docs when implemented...  #1729  Thanks very much for reporting it!
It is just a one line addition to ```doc/reference/algorithms/community.rst``` in the quality section.

Sorry for your trouble!  Did you come up with any improvements over the existing code?

**Comment by bernwaldl** [comment]
No worries :) Thanks for the quick addtion!

At least for my use case of undirected simple graphs, my solutions seems to run faster. I am, however, unsure whether I can use the same approach for directed graphs respectively multigraphs. I'll try to test it out in the next couple of days when I have time and will create a PR, if I think my code runs faster.

**Comment by bernwaldl** [comment]
I've now proposed a change in #4103. Feedback is appreciated :)
