### ISSUE TITLE
How to print the subgraph isomorphism between two graphs?

### ISSUE THREAD

**Issue by tiankonghenlan20113046** [networkx/networkx#4098]
Dear  author, @jwegis @lonnen @cournape @alexbrc 
I have two networkx graphs g1 and g2. The g1 and g2 defines as following:
```
#This is g1's definition
g1 = nx.Graph()
g1.add_node('1',label = 'c1')
g1.add_node('2',label = 'h')
g1.add_node('3',label = 'h')
edges = [('1','2',{'label':'1'}),('1','3',{'label':'1'}),('2','3',{'label':'1'})] 
g1.add_edges_from(edges)
#This is g2's definition
g2 = nx.Graph()
g2.add_node('10',label = 'c1')
g2.add_node('11',label = 'h')
g2.add_node('12',label = 'h')
edges = [('10','11',{'label':'1'}),('10','12',{'label':'1'})] #g2 has 2 edges now
g2.add_edges_from(edges)
```
If we plot the two graphs on a paper according the g1 and g2 above ,we will see the expected "subgraph isomorphism" or "mapping"---------
{'1':'10','2':'11','3':'12'}. 
But when I [use the code](https://github.com/networkx/networkx/blob/3d1732ef5c19ccff5d491b8b2650ce606cf673a3/networkx/algorithms/isomorphism/isomorphvf2.py#L1) to check the mapping from g1 to g2, it prints nothing. the code is as following:
```
GM = nx.algorithms.isomorphism.GraphMatcher(g1,g2,
                                            node_match=lambda n1,n2:n1['label']==n2['label'],
                                            edge_match = lambda x,y:x['label']==y['label'] )

for subgraph in GM.subgraph_isomorphisms_iter():
    if subgraph:
        print("mapping:"+str(subgraph))
    else :
        print("no matching")
```

But when I deleting an edge from g2,the networkx format like this:
```
g2 = nx.Graph()
g2.add_node('10',label = 'c1')
g2.add_node('11',label = 'h')
edges = [('10','11',{'label':'1'})] #g2 only have 1 edge.
g2.add_edges_from(edges)

for subgraph in GM.subgraph_isomorphisms_iter():
    if subgraph:
        print("mapping:"+str(subgraph))
    else :
        print("no matching")
```
it gives me the answer:
```
mapping:{'1': '10', '3': '11'}
mapping:{'1': '10', '2': '11'}
```
So I have some questions :
1. How could I find all mappings from g1 to g2? The method I use is right?
2. Why did I not get the mapping when I first define the g2 who has 2 edges? why did I get the mapping after removing one edge from g2 ?

I am doing some research on "subgraph isomorphism" and I want to make the use of this algorithm. Maybe my clarification is not clear and my understanding is too shallow to express what I want. But I want to have some discussion with you. Looking forward to your reply.

**Comment by dschult** [comment]
The trouble comes from your understanding of the term “subgraph isomorphism”.  To be an isomorphism, the *induced* sub Ralph must match. That is, all the edges connected to the nodes in the subset must exist in the subgraph.  In you first example, the candidate isomorphism Maps all three nodes. So g2 must include all edges between the 3 nodes. And it doesn’t. So there is not an isomorphism.  In your second example, the isomorphism maps 2 nodes, so g2 must include all edges between those 2 nodes. There is one such edge and it exists in g2 so there is a subgraph isomorphism.

What you are thinking of is a matching of the nodes and *some* of the edges. This is called a subgraph monomorphism.

**Comment by dschult** [comment]
I'm going to close this issue, though you can still post here and we'll see it.
```print(list(GM.subgraph_monomorphism_iter()))```
might be what you're looking for.

**Comment by tiankonghenlan20113046** [comment]
> I'm going to close this issue, though you can still post here and we'll see it.
> `print(list(GM.subgraph_monomorphism_iter()))`
> might be what you're looking for.

Thanks for your tutor.BUT  it gives me the hint 
`AttributeError: 'GraphMatcher' object has no attribute 'subgraph_monomorphism_iter'`.It means the networkx has not cover this method.

**Comment by dschult** [comment]
In NetworkX 2.4 and the latest (github) versions it exists. It was put in during pull request #3435

**Comment by tiankonghenlan20113046** [comment]
> In NetworkX 2.4 and the latest (github) versions it exists. It was put in during pull request #3435

After I upgraded the networkx, I tested the code 
`print(list(GM.subgraph_monomorphism_iter()))`
But It really output nothing. I can not understand the reason.

**Comment by dschult** [comment]
I'm sorry, it is named ```GM.subgraph_monomorphisms_iter()``` I missed the "s" at the end of monomorphism.
