### ISSUE TITLE
Tests incompatible with matplotlib 3.3.0

### ISSUE THREAD

**Issue by PureTryOut** [networkx/networkx#4099]
Matplotlib 3.3.0 has been released 5 days ago, and because of it the networkx tests are failing.

```
_______________________________ ERROR collecting networkx/drawing/tests/test_pylab.py _______________________________
networkx/drawing/tests/test_pylab.py:7: in <module>
    mpl.use('PS', warn=False)
E   TypeError: use() got an unexpected keyword argument 'warn'
```

Seems the API has changed a bit.

**Comment by jarrodmillman** [comment]
That is fixed on master and will be in the next release:  https://github.com/networkx/networkx/milestone/13

If you need the fix now, you will need to install the development version:
https://networkx.github.io/documentation/latest/install.html#install-the-development-version

**Comment by PureTryOut** [comment]
Awesome! Could you point to the fixing commit by any chance? Maybe I can backport it for the Alpine Linux packaging.

**Comment by jarrodmillman** [comment]
https://github.com/networkx/networkx/commit/4b59ae42d52980852f795811426254dd06d266b3

**Comment by jarrodmillman** [comment]
That fixes a few things, here is the specific fix:  https://github.com/networkx/networkx/commit/4b59ae42d52980852f795811426254dd06d266b3#diff-9bb0b5cc53a72d31dc3ce5ed61281901
