### ISSUE TITLE
Match two graphs based on edit paths

### ISSUE THREAD

**Issue by LukasBommes** [networkx/networkx#4102]
Hey all,

I am having two undirected graphs, A and B, without any node or edge attributes. I want to recover an error-tolerant mapping of the node labels between graph A and B. As suggested in Issue #4043 I am computing an edit path with  `nx.algorithms.similarity.optimize_edit_paths`. Now, I am wondering how to retrieve the node mapping from the node_edit/edge_edit paths.

I guess, it is trivial, but I haven't used GED before and I am not really into the theory. So, does anyone have an idea, how to do this?

**Comment by dschult** [comment]
The [documentation for optimal_edit_paths](https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.similarity.optimal_edit_paths.html) describes the return values for this function as:

```
    Returns
    -------
    edit_paths : list of tuples (node_edit_path, edge_edit_path)
        node_edit_path : list of tuples (u, v)
        edge_edit_path : list of tuples ((u1, v1), (u2, v2))
    cost : numeric
        Optimal edit path cost (graph edit distance).

    Examples
    --------
    >>> G1 = nx.cycle_graph(4)
    >>> G2 = nx.wheel_graph(5)
    >>> paths, cost = nx.optimal_edit_paths(G1, G2)
    >>> len(paths)
    40
    >>> cost
    5.0
```
The return values are ```paths``` and ```cost```. It sounds like you want the paths.  In particular, you want to know which nodes are isomorphic to other nodes. So...  the output ```paths``` is a list of edit paths. You may want to look at all of them, or you may just want any one of them. Each path is made up of 2 lists. The first is a list of node tuples, the second a list of edge tuples.  It sounds like you want the node tuples list. Suppose it is [(1, 2), (9, 8)]. That means that node 1 gets changed to node 2 and node 9 gets changed to node 8.  Those are two of the changes (substitutions) needed to make the graphs isomorphic. There could also be deletions, e.g.  (3, None) or insertions (None, 4).  See the description of return values for the ```get_edit_paths``` function within the ```optimize_edit_paths``` function:

```
Returns:
            sequence of (vertex_path, edge_path, cost)
                vertex_path: complete vertex edit path
                    list of tuples (u, v) of vertex mappings u<->v,
                    u=None or v=None for deletion/insertion
                edge_path: complete edge edit path
                    list of tuples (g, h) of edge mappings g<->h,
                    g=None or h=None for deletion/insertion
                cost: total cost of edit path
```

But, alas, this only tells you the edits that make the two graphs isomorphic. It does not tell you what the resulting isomorphism is. For that you should construct the two now isomorphic graphs and use the isomorphism routines to get the isomorphism. 

Hope this helps.

**Comment by rossbar** [comment]
Thanks @dschult for the really nice, detailed answer. I'm going to close this as resolved, but please feel free to reopen if there are follow-up questions, related feature requests, etc.
