### ISSUE TITLE
Getting triad census for a node

### ISSUE THREAD

**Issue by umitkaanusta** [networkx/networkx#4104]
Seems like there is a function for getting overall triad census. However, in the case when I want to see censuses for each node I have to manually implement that function. Would you consider adding a function that creates a triadic census table showing triad census of each node?

**Comment by dschult** [comment]
That seems like a reasonable addition to the triads.py module.
You might be able to leverage ```triads_by_type``` to build a dict keyed by node to a dict keyed by triad type to the count of triads with that type that involve that node.

**Comment by ericmjl** [comment]
Hi @umitkaanusta! It looks like something that you have implemented multiple times over. Do you have a function sketch here? If you do, we'd be happy to work with you to get the function inserted into the library!

**Comment by umitkaanusta** [comment]
What I did was to get that specific node's ego network and perform a triadic census on that ego network. (Then repeat this process for all nodes if I were to iterate over nodes and get triadic censuses). My solution is not that feasible as you can see
