### ISSUE TITLE
Longest path in DAG doesn't work with a dictionary containing a list of values

### ISSUE THREAD

**Issue by saura8h** [networkx/networkx#4126]
Data in the form of `{'1': ['2'], '2': ['3', '4'], '3': [], '4': ['5'], '5': ['6'], '6': []}` does **not** work when finding the longest path in a directed acyclic graph. 

```
import networkx as nx

G = nx.DiGraph()
G.add_edges_from(data.items())
path = nx.dag_longest_path(G)
```

However, `data = {'a':'b', 'b':'c', 'c':'d'}` works with the above code.

How can I pass a dictionary containing a list of values, instead of simple key-value pairs?

Error Trace:

```
File digraph.py line 695, in add_edges_from
    if v not in self._succ:
TypeError: unhashable type: 'list'
```

**Comment by dschult** [comment]
Try ```G = nx.DiGraph({'1': ['2'], '2': ['3', '4'], '3': [], '4': ['5'], '5': ['6'], '6': []})```
Your data is in "adjacency list" form. It is not a list of edges. That determines how you add the connectivity information.
