### ISSUE TITLE
edgelist in draw_network does not support arrays

### ISSUE THREAD

**Issue by Silmathoron** [networkx/networkx#4129]
Using numpy 1.18.2 and networkx 2.4, it is not possible to use a numpy array for the `edgelist` argument of [``draw_networkx``](https://networkx.github.io/documentation/stable/reference/generated/networkx.drawing.nx_pylab.draw_networkx.html).
It raises:
```
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

I normally would not have opened an issue for that but I do not see the point of the current implementation, so in case it can be changed harmlessly to support numpy arrays, that might be a win-win.

The issue comes from lines 575-579 on 2.4 ([lines 640-647](https://github.com/networkx/networkx/blob/master/networkx/drawing/nx_pylab.py#L640) on master) that read:

```python
    if edgelist is None:
        edgelist = list(G.edges())

    if not edgelist or len(edgelist) == 0:  # no edges!
        return None
```

I am not sure what the combination of ``not edgelist`` and ``len(edgelist) == 0`` is for, here, so I would propose to change it to

```python
    if edgelist is None:
        edgelist = list(G.edges())
    elif len(edgelist) == 0:  # no edges!
        return None
```

which should still do the job for all valid inputs I can think of and would also work with numpy arrays.

**EDIT** if iterables should be supported, one could replace ``not edgelist`` by ``not isinstance(edgelist, Iterable)``

**Comment by Silmathoron** [comment]
OK, nice, I can make a PR if that helps.
Iterators do not need to be supported, if I understand correctly, then, right? I can just use the ``elif len(edgelist) == 0:``?

**Comment by dschult** [comment]
Yes, that is (I believe) the only change needed. 
It might be good to have a test to make sure that a numpy array works.

**Comment by Silmathoron** [comment]
PR is done and should be working (except for the CircleCI tests that fail because of an internal unrelated error, from what I can see)
#4132
