### ISSUE TITLE
Questions about transitivity computation

### ISSUE THREAD

**Issue by doudoubobo** [networkx/networkx#4137]
When I saw the [code](https://networkx.github.io/documentation/stable/_modules/networkx/algorithms/cluster.html#transitivity) for computing transitivity of a graph, I found that the `_triangles_and_degree_iter` function is called to compute the triangle number for both directed and undirected graph. I am wondering if the `_directed_triangles_and_degree_iter` function should be used for directed graphs?

**Comment by dschult** [comment]
The standard definition uses the data computed in ```_triangles_and_degree_iter```. I am not aware of anyone using the information from ```directed_triangles_and_degree_iter``` to compute transitivity. But there is nothing stopping us from doing so. One issue is that there are so many combinations the data which create such measures, it is hard to know which is useful. Depending on your interests and background, you could explore and publish a rigorous comparison of transitivity measures. As you can see, the code is not difficult. The difficulty is figuring out what question is relevant, what we want to describe and what measure of that feature is most effective.

On the other hand, if you want to compute the transitivity as commonly defined, the current implementation is commonly used for directed graphs. Hopefully it works for what you want to measure.
