### ISSUE TITLE
Add more useful ```__str__``` function for Graph objects

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#4139]
Currently the ```__str___``` function prints the ```G.name``` property which is ```G.graph["name"]```.
That is pretty rarely useful in my experience (often a blank string).

There is useful information in nx.info(G) and much less of it than there once was. Perhaps it would be reasonable to look at making something like ```nx.info(G)``` show for ```__str__```.  Are there reasons to avoid doing this? What implications does it have for ```__repr__```?  Issue #3956 requested a useful ```__repr__``` and so is related to this.

**Comment by parth-verma** [comment]
It would be wise to include the name of the graph in case it exists. Some additional information such as the number of nodes and edges as well as the type of graph can also be included in a format such as `DiGraph(name:"asdf",nodes:3,edges:2)`

**Comment by rossbar** [comment]
> Are there reasons to avoid doing this?

Not a reason to avoid it, but something to consider: `nx.info` includes the number_of_edges and the average degree calculation, which *might* take a long time for some graphs? e.g. 

```python
>>> G = nx.path_graph(int(1e7))
>>> %timeit nx.info(G)
4.4 s ± 47.3 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
```

N.B. @dschult I think you raised this concern before - I'm simply adding here for visibility!

**Comment by AndrewEckart** [comment]
I'd like to get into this, but I have a question: is there any particular reason that `G.number_of_edges` (or really, `G.size`) is calculated on demand and not stored as an attribute on `Graph` and maintained whenever edges are added/removed to facilitate O(1) lookups?

**Comment by rossbar** [comment]
> is there any particular reason that G.number_of_edges (or really, G.size) is calculated on demand and not stored as an attribute on Graph and maintained whenever edges are added/removed to facilitate O(1) lookups?

I think the advantage of the property is that the class/user does not have to explicitly manage state. If the e.g. `number_of_edges` were an attribute instead of a property of the graph, then all methods for adding/removing edges would have to update the value explicitly on modification which in principle 1) makes the modification itself slightly more expensive (a minor concern) and 2) makes it very easy to introduce subtle bugs (compare this situation to ref counting for example).
