### ISSUE TITLE
Coreness (core / periphery) (migrated from Trac #419)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#414]
Original ticket https://networkx.lanl.gov/trac/ticket/419
Reported 2010-09-05 by trac user alex, assigned to @hagberg.

Implements the continuous version of coreness described by Borgatti in http://dx.doi.org/10.1016/S0378-8733(99)00019-2

**Comment by hagberg** [comment]
Closed due to inactivity.
