### ISSUE TITLE
Inconsistent Attribute Handling During DiGraph Node Contraction

### ISSUE THREAD

**Issue by jtimmons** [networkx/networkx#4150]
It looks like edges which are contracted as part of the `contract_nodes` call for a DiGraph do not merge their attributes in the same way that the nodes do. Take the snippet below as an example. Here we contract two nodes (`src1` and `src2`) which each have a directed edge to the same node (`dest`). Because we're not using a multi-graph the contraction of those two nodes also forces the the contraction of their edges to `dest` as well.
```python
import networkx as nx

G = nx.DiGraph([("src1", "dest"), ("src2", "dest")]) # Shape: src1 --> dest <-- src2

G.nodes["src1"]["value"] = "src1-value"
G.nodes["src2"]["value"] = "src2-value"

G["src1"]["dest"]["value"] = "src1-value"
G["src2"]["dest"]["value"] = "src2-value"

G = nx.contracted_nodes(G, "src1", "src2") # New Shape: src1 --> dest

print(G.nodes["src1"])   # {'value': 'src1-value', 'contraction': {'src2': {'value': 'src2-value'}}}
print(G.edges[("src1", "dest")]) # {'value': 'src2-value'}
```
For the node attributes we can see that the `src1` attributes correctly take precedence, and the attributes inherited from `src2` are placed into a new `'contraction'` attribute. However, for the edge attributes the `src2-->dest` edge takes precedence which is the opposite of what I would expect; additionally we lose that additional context of the contracted `src1-->dest` edge entirely.

Tested with Python 3.7.3 and networkx 2.4

**Comment by rossbar** [comment]
Nice catch - I don't see anything in the docstring indicating how the edges are handled in the contraction, though it does seem strange that the edge resulting from the contraction takes the attribute values of the removed edge. I'm going to mark this as a defect for now even though the behavior may be undefined.

**Comment by dschult** [comment]
The code shows that the edge data is handled by simply adding edges that used to go to the disappearing node to the newly contracted node. That means any edge attributes for edges that used to go to "src1" can be silently overwritten. I'm not sure there is a definition of node contraction that imposes what we do with edge data. So I think we can choose. We can certainly do better than what is currently implemented.

Perhaps we check for each edge attribute of ```('dest', 'src2')``` whether edge ```('dest, 'src1')``` has that attribute. If it doesn't, update with the new attribute. If it does, then collect that in a datadict to store it in a 'contraction' attribute of the attribute ```('dest','src1')```.  Many other possibilities... Ideas?

**Comment by jtimmons** [comment]
I think that's a reasonable approach and solves my usecase - though the merging of attributes feels like it could become confusing in some cases since the attributes lose the context of where they came from. What are your thoughts on keeping the attributes from the existing edge and simply storing the disappearing edge attributes in the "contraction" map in the same way that node contraction is handled? This would still allow the user to trivially merge attributes if needed by doing something like `for d in e_data["contraction"].values(): e_data.update(d)`.

In the original example above, the resulting attribute dictionary of `('src1', 'dest')` post-contraction would look like:
```
{
  "value": "src1-value",
  "contraction": {
    ("src2", "dest"): {
      "value": "src2-value"
    }
  }
}
```

I took a look through the codebase and this seems like a simple enough fix - would be happy to put up a PR to address this if that'd be helpful?

**Comment by dschult** [comment]
Yes, that'd be helpful. Thanks!
