### ISSUE TITLE
Selecting an edge in a MultiDiGraph is difficult

### ISSUE THREAD

**Issue by turian** [networkx/networkx#4153]
If I have a MultiDiGraph, it is hard to select a particular edge. I would like to select by property (i.e. an ID that I assign), but there is no ergonomic way to do this.

There might be several edges between the same two nodes; I don't want to iterate over them to get the edge I want.

**Comment by MridulS** [comment]
You can create a custom key when you adding edges to your MultiDiGraph.

``` python
In [20]: G = nx.MultiDiGraph()

In [21]: G.add_edge(1, 2, key='my_key_2', weight='lol')
Out[21]: 'my_key_2'

In [22]: G.add_edge(1, 2, key='my_key_1', weight=10)
Out[22]: 'my_key_1'

In [27]: G.edges[1, 2, 'my_key_1']
Out[27]: {'weight': 10}

In [28]: G.edges[1, 2, 'my_key_2']
Out[28]: {'weight': 'lol'}
```

**Comment by rossbar** [comment]
Thanks @MridulS for the nice example! I'm going to close this as resolved. If the issue persists, please feel free to reopen with updated info.
