### ISSUE TITLE
Projection functions not defined for multigraphs

### ISSUE THREAD

**Issue by cvagg** [networkx/networkx#4165]
Why are the projection functions for bipartite algorithms not defined for multigraphs? Is there a way to project a multigraph bipartite network in this module?

**Comment by dschult** [comment]
The [docs for bipartite projection](https://networkx.github.io/documentation/stable/reference/algorithms/bipartite.html#module-networkx.algorithms.bipartite.projection) show that ```projected_graph``` works with multigraph and explains how it handles that case.

**Comment by cvagg** [comment]
Sorry if I am mistaken but the first line of the projected_graph method is 

`if B.is_multigraph():
        raise nx.NetworkXError("not defined for multigraphs")`

I can see that the parameter multigraph can be set to True but from my understanding only allows the returned projected graph to be a multigraph not the input graph and doesn't affect the error message above.

**Comment by rossbar** [comment]
@cvagg you are correct that `projected_graph` does not currently accept MultiGraph inputs. Are there any references you can provide that describe the behavior you were looking for?

**Comment by dschult** [comment]
Yes -- you are absolutely right -- the notes in the docs are about a MultiGraph output... not an input. Sorry about that.

Hmm.... what would you want it to do? I'm just repeating @rossbar here but do you have any references for what you should do?

One approach that makes sense is to treat the multigraph like a graph and connect nodes that share a neighbor no matter how many edge connect them.  Thats likely to be what you're looking for unless you are worried about edge attributes in some way.

**Comment by cvagg** [comment]
Ah yes, thank you @dschult! what I wanted to achieve was as to connect nodes that share a neighbour no matter how many other edges connect them. I am realising now that perhaps I should just change my bipartite multigraph into a graph where nodes which have multiple edges just repeated edges are merged into a single edge, which I will then be able to pass through projected_graph()?

**Comment by dschult** [comment]
That should be as straightforward as:  ```bipartite.projected_graph(nx.Graph(G), top_nodes)```
