### ISSUE TITLE
Add Borukva's (or modified) algorithm for minimum spanning tree (migrated from Trac #422)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#417]
Original ticket https://networkx.lanl.gov/trac/ticket/422
Reported 2010-09-06 by @hagberg, assigned to @hagberg.

From
http://en.wikipedia.org/wiki/Bor%C5%AFvka%27s_algorithm

Faster algorithms can be obtained by combining Prim's algorithm with Borůvka's. A faster randomized minimum spanning tree algorithm based in part on Borůvka's algorithm due to Karger, Klein, and Tarjan runs in expected O(E) time. The best known (deterministic) minimum spanning tree algorithm by Bernard Chazelle is also based in part on Borůvka's and runs in O(E α(V)) time, where α is the inverse of the Ackermann function. These randomized and deterministic algorithms combine steps of Borůvka's algorithm, reducing the number of components that remain to be connected, with steps of a different type that reduce the number of edges between pairs of components.

The attached code has an basic example implementation.
See code for references to original sources.

Also see source:networkx/networkx/algorithms/tests/test_mst.py for some tests using Kruskal's algorithm which might be helpful.

**Comment by jfinkels** [comment]
Just to clarify, @blogle's algorithm solves the minimum spanning tree for complete graphs in which the edge weights form a metric space, which is a special case of the more general problem of finding a minimum weight spanning tree.
