### ISSUE TITLE
uninstall  networkx

### ISSUE THREAD

**Issue by ramankhurana** [networkx/networkx#4170]
I install the package from source and i now need to get another version so I want to remove the existing version. Is there a way to do it in present setup.py? if not can this be added? 

Thanks.

**Comment by rossbar** [comment]
This depends on how you installed networkx. If you installed with pip, then `pip uninstall networkx` or `pip install networkx==<version>` (where `<version>` is the version you want, e.g. `2.4`).

**Comment by dschult** [comment]
I believe the ```pip uninstall networkx``` solution works even if you installed from source using ```python setup.py install``` but I haven't tested that.

**Comment by rossbar** [comment]
I am going to close this one as resolved. Please feel free to reopen with more specific information if there are still problems.
