### ISSUE TITLE
Communicability Betweenness Centrality Error For normalized=False

### ISSUE THREAD

**Issue by hcars** [networkx/networkx#4171]
If you run the method communicability_betweenness_centrality(G, normalized) where normalized is false, you will get the following error:
```
File "../../test/driver_auto_communicability_betweenness_centrality_v01.py", line 186, in main
    libraryMethodReturnTypeVariable  = nx.communicability_betweenness_centrality(Graph,normalized)
local variable 'scale' referenced before assignment
```

---------------------------------------------
```
def _rescale(cbc, normalized):
    # helper to rescale betweenness centrality
    if normalized is True:
        order = len(cbc)
        if order <= 2:
            scale = None
        else:
            scale = 1.0 / ((order - 1.0) ** 2 - (order - 1.0))
    if scale is not None:
        for v in cbc:
            cbc[v] *= scale
    return cbc
```
This is because communicability_betweenness_centrality calls the above method, and as you can see, scale is not defined on the line `if scale is not None`.

I'm not sure what scale should be if normalization is not True.

**Comment by rossbar** [comment]
Good catch and nice diagnosis. I also agree that it's not clear what the behavior *should* be when `normalization=False`, perhaps the linked reference in the docstring of `communicability_betweenness_centrality` would have some info on this?

**Comment by hcars** [comment]
> 
> 
> Good catch and nice diagnosis. I also agree that it's not clear what the behavior _should_ be when `normalization=False`, perhaps the linked reference in the docstring of `communicability_betweenness_centrality` would have some info on this?

The docstring links to https://arxiv.org/ftp/arxiv/papers/0905/0905.4102.pdf. If you go to page 7, there should be a definition of communicability betweenness. I don't even see a version without normalization.

**Comment by dschult** [comment]
Wow --- this bug has been there for 9 years. :)  
Looks like the ```_rescale``` function should be moved inline with the function and it's really just a way to avoid dividing by 0 for graphs with 2 or fewer nodes. It sets the 1/((N-1)*(N-2)) term to 1 if <=2 nodes. That's not really a "normalization"... And we can tell that no one wanted the "unnormalized version" because it leads to an exception because of this bug.

I suggest we deprecate the ```normalized``` parameter and replace the function with a scaling that occurs in the function only ```if G.order() > 2:```.

**Comment by hcars** [comment]
> 
> 
> Wow --- this bug has been there for 9 years. :)
> Looks like the `_rescale` function should be moved inline with the function and it's really just a way to avoid dividing by 0 for graphs with 2 or fewer nodes. It sets the 1/((N-1)*(N-2)) term to 1 if <=2 nodes. That's not really a "normalization"... And we can tell that no one wanted the "unnormalized version" because it leads to an exception because of this bug.
> 
> I suggest we deprecate the `normalized` parameter and replace the function with a scaling that occurs in the function only `if G.order() > 2:`.

That seems like the most reasonable course of action.

**Comment by dschult** [comment]
This Issue requires a deprecation to fix
