### ISSUE TITLE
Add arrow drawing and other improvements to Matplotlib drawing (migrated from Trac #423)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#418]
Original ticket https://networkx.lanl.gov/trac/ticket/423
Reported 2010-09-06 by @hagberg, assigned to @hagberg.

Update of tickets #78 and #293 (now closed) based on new code provided on mailing list at 

http://groups.google.com/group/networkx-discuss/browse_thread/thread/b95fda9813fae67d?hl=en_US

**Comment by hagberg** [comment]
See #2757
