### ISSUE TITLE
Does 'is_triad' method ignore self-loops?

### ISSUE THREAD

**Issue by MikeB2019x** [networkx/networkx#4186]
I am new to networkx and am using 2.5 on MacOS 10.15.6.  I have successfully implemented a directed graph and decided to experiment with the triad algorithm.  I first tried 'triadic_census' and that was successful.  I then tried 'triads_by_type' and that failed with the error:
```
'G is not a triad (order-3 DiGraph)'
```
I looked at the source and implemented a portion of it separately (below).  The output shows that 'census' is correctly identifying existing triads.  If I execute 'all_triads' as is done in the 'triads_by_type' method, a proper triad object seems to be returned and looking at the 'nodes' attribute seems to validate that.  But if I then apply the 'is_triad' method to the triad, it returns False.

If 'all_triads' is returning valid triads, how can they fail to test 'True' for that type?  I know I have many nodes with self-loops but since they are (seem to be?) ignored by census I thought they would also be ignored by the remainder of the triad methods.  Any guidance would be appreciated.

```
for index, eng in enumerate(eng_graphs.keys()):
    if index > 0:
        break
    net = eng_graphs[eng]
    display(nx.algorithms.triads.triadic_census(net))
    all_tri = nx.algorithms.triads.all_triads(net)
    for idx,triad in enumerate(all_tri):
        if idx > 0:
            break
        display(dir(triad), triad.nodes)
        name = nx.algorithms.is_triad(triad)
```
Output:
```
From 'census' -
{'003': 939,
 '012': 286,
 '102': 146,
 '021D': 4,
 '021U': 111,
 '021C': 31,
 '111D': 86,
 '111U': 34,
 '030T': 16,
 '030C': 1,
 '201': 64,
 '120D': 4,
 '120U': 7,
 '120C': 13,
 '210': 22,
 '300': 7}

From 'all_triads' -
['__class__',
 '__contains__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_adj',
 '_node',
 '_pred',
 '_succ',
 'add_edge',
 'add_edges_from',
 'add_node',
 'add_nodes_from',
 'add_weighted_edges_from',
 'adj',
 'adjacency',
 'adjlist_inner_dict_factory',
 'adjlist_outer_dict_factory',
 'clear',
 'clear_edges',
 'copy',
 'degree',
 'edge_attr_dict_factory',
 'edge_subgraph',
 'edges',
 'get_edge_data',
 'graph',
 'graph_attr_dict_factory',
 'has_edge',
 'has_node',
 'has_predecessor',
 'has_successor',
 'in_degree',
 'in_edges',
 'is_directed',
 'is_multigraph',
 'name',
 'nbunch_iter',
 'neighbors',
 'node_attr_dict_factory',
 'node_dict_factory',
 'nodes',
 'number_of_edges',
 'number_of_nodes',
 'order',
 'out_degree',
 'out_edges',
 'pred',
 'predecessors',
 'remove_edge',
 'remove_edges_from',
 'remove_node',
 'remove_nodes_from',
 'reverse',
 'size',
 'subgraph',
 'succ',
 'successors',
 'to_directed',
 'to_directed_class',
 'to_undirected',
 'to_undirected_class',
 'update']

View of 'node' from preceding 'triad' object:
NodeView(('23002', '13002', 'unk'))

Value returned when preceding object is evaluated by 'is_triad':
False
```

**Comment by dschult** [comment]
The ```is_triad``` explicitly rules out self-loops as not triads. Self-loops mess up the census identification process as none of the census types have self-loops.  You can remove the self-loops before processing with something like: ```G.remove_edges_from(nx.selfloop_edges(G))```

**Comment by MikeB2019x** [comment]
Perfect.  Thank you for the quick response!
