### ISSUE TITLE
have vertices.txt and triangle.txt, how to create a graph?

### ISSUE THREAD

**Issue by tanjia123456** [networkx/networkx#4187]
- [ vertices] 
0 [ -2.14705372 -79.11716461 -22.24082756]
1 [ -2.90098286 -78.58725739 -22.61082458]
2 [ -1.62398648 -79.33273315 -22.4699192 ]
3 [ -3.29315186 -79.55406952 -22.78844452]
4 [ -2.05146265 -79.78436279 -22.83360863]
5 [ -2.37813139 -79.81951141 -23.46728134]
6 [ -3.48356891 -78.81594849 -26.91384697]
7 [ -4.50524473 -78.91020966 -26.43970108]
8 [ -3.29619694 -78.70610046 -27.98403358]
9 [ -1.80273378 -78.89961243 -32.86447525]
10 [ -2.22650218 -79.17362976 -32.81439209]
- [ triangle]
0 0 1 3
1 0 3 2
2 0 27 1
3 28 1 27
4 0 2 27
5 31 27 2
6 2 3 4
7 5 4 3
8 2 4 35
9 2 35 31
10 4 5 35
These two data are not complete, only part of.

**Comment by dschult** [comment]
You'll need to write some code to turn the triangles into 3 edges each. Add those edges.

I'm going to "close" this (not a bug), but you can still post follow-up comments on this issue and we will see it.

**Comment by tanjia123456** [comment]
> 
> 
> You'll need to write some code to turn the triangles into 3 edges each. Add those edges.
> 
> I'm going to "close" this (not a bug), but you can still post follow-up comments on this issue and we will see it.

hi, i'm sorry to bother you .  But i don't konw how to extract edge

**Comment by dschult** [comment]
If you have a triangle "0 0 1 3" then I don't know for sure, but it seems like this means you need edges ("0","1"), ("1","3") and ("3","0").  Adding those edges will add the triangle. Is this what you want?

If so, then you need to write code to split the triangle into it's nodes and form 3 edges from those nodes. You can use something like this to split the string and add the edges (I am guessing about your file syntax so this may not be correct).
```python
number, a, b, c = triangle.split()
G.add_edges_from([(a, b), (b,c), (c,a)])
```

**Comment by tanjia123456** [comment]
Hi, I have extract edge and vertex, but I saved it by .txt file format. So, How to send it to the G?
I have tried by myself, but it's wrong. the following is my edge.txt, I think only use it can create a graph.
edge: vertex #3 [ -3.29315186 -79.55406952 -22.78844452] - vertex #0 [ -2.14705372 -79.11716461 -22.24082756]
edge: vertex #2 [ -1.62398648 -79.33273315 -22.4699192 ] - vertex #0 [ -2.14705372 -79.11716461 -22.24082756]
edge: vertex #1 [ -2.90098286 -78.58725739 -22.61082458] - vertex #0 [ -2.14705372 -79.11716461 -22.24082756]
edge: vertex #27 [ -0.83862901 -78.48338318 -22.12019348] - vertex #28 [ -1.57793117 -78.03195953 -22.43221092]
edge: vertex #27 [ -0.83862901 -78.48338318 -22.12019348] - vertex #0 [ -2.14705372 -79.11716461 -22.24082756]
edge: vertex #2 [ -1.62398648 -79.33273315 -22.4699192 ] - vertex #31 [ -0.38851529 -78.94087219 -22.59452057]
edge: vertex #4 [ -2.05146265 -79.78436279 -22.83360863] - vertex #2 [ -1.62398648 -79.33273315 -22.4699192 ]
edge: vertex #3 [ -3.29315186 -79.55406952 -22.78844452] - vertex #5 [ -2.37813139 -79.81951141 -23.46728134]
edge: vertex #35 [ -1.07843208 -79.20427704 -23.42686653] - vertex #2 [ -1.62398648 -79.33273315 -22.4699192 ]
edge: vertex #31 [ -0.38851529 -78.94087219 -22.59452057] - vertex #2 [ -1.62398648 -79.33273315 -22.4699192 ]
edge: vertex #35 [ -1.07843208 -79.20427704 -23.42686653] - vertex #4 [ -2.05146265 -79.78436279 -22.83360863]


`import string
import networkx as nx
import matplotlib.pyplot as plt

G = nx.Graph()  # 建立一个空的无向图G

'''with open("HLN-12-1vertices.txt") as node_list:
    for eachline in node_list:
        G.add_node()'''
with open("HLN-12-1edges.txt") as edge_list:
    for eachline in edge_list:
        G.add_edge()
        G.add_node()

print("number of edges:", G.number_of_edges()) # 输出边的数量
G1=nx.draw(G)
plt.show()`

could you please help me modify this code?

**Comment by tanjia123456** [comment]
Hi, I have extract edge and vertex, but I saved it by .txt file format. So, How to send it to the G?
I have tried by myself, but it's wrong. the following is my edge.txt, I think only use it can create a graph.
edge: vertex #3 [ -3.29315186 -79.55406952 -22.78844452] - vertex #0 [ -2.14705372 -79.11716461 -22.24082756]
edge: vertex #2 [ -1.62398648 -79.33273315 -22.4699192 ] - vertex #0 [ -2.14705372 -79.11716461 -22.24082756]
edge: vertex #1 [ -2.90098286 -78.58725739 -22.61082458] - vertex #0 [ -2.14705372 -79.11716461 -22.24082756]
edge: vertex #27 [ -0.83862901 -78.48338318 -22.12019348] - vertex #28 [ -1.57793117 -78.03195953 -22.43221092]
edge: vertex #27 [ -0.83862901 -78.48338318 -22.12019348] - vertex #0 [ -2.14705372 -79.11716461 -22.24082756]
edge: vertex #2 [ -1.62398648 -79.33273315 -22.4699192 ] - vertex #31 [ -0.38851529 -78.94087219 -22.59452057]
edge: vertex #4 [ -2.05146265 -79.78436279 -22.83360863] - vertex #2 [ -1.62398648 -79.33273315 -22.4699192 ]
edge: vertex #3 [ -3.29315186 -79.55406952 -22.78844452] - vertex #5 [ -2.37813139 -79.81951141 -23.46728134]
edge: vertex #35 [ -1.07843208 -79.20427704 -23.42686653] - vertex #2 [ -1.62398648 -79.33273315 -22.4699192 ]
edge: vertex #31 [ -0.38851529 -78.94087219 -22.59452057] - vertex #2 [ -1.62398648 -79.33273315 -22.4699192 ]
edge: vertex #35 [ -1.07843208 -79.20427704 -23.42686653] - vertex #4 [ -2.05146265 -79.78436279 -22.83360863]

`import string
import networkx as nx
import matplotlib.pyplot as plt

G = nx.Graph()

'''with open("HLN-12-1vertices.txt") as node_list:
for eachline in node_list:
G.add_node()'''
with open("HLN-12-1edges.txt") as edge_list:
for eachline in edge_list:
G.add_edge()
G.add_node()

print("number of edges:", G.number_of_edges())
G1=nx.draw(G)
plt.show()`

could you please help me modify this code?

**Comment by tanjia123456** [comment]
edge : vertex #0 - vertex #1
edge : vertex #1 - vertex #3
edge : vertex #3 - vertex #0
edge : vertex #0 - vertex #3
edge : vertex #3 - vertex #2
edge : vertex #2 - vertex #0
edge : vertex #0 - vertex #27
edge : vertex #27 - vertex #1
edge : vertex #1 - vertex #0
edge : vertex #28 - vertex #1

0 [ -2.14705372 -79.11716461 -22.24082756]
1 [ -2.90098286 -78.58725739 -22.61082458]
2 [ -1.62398648 -79.33273315 -22.4699192 ]
3 [ -3.29315186 -79.55406952 -22.78844452]
4 [ -2.05146265 -79.78436279 -22.83360863]
5 [ -2.37813139 -79.81951141 -23.46728134]
6 [ -3.48356891 -78.81594849 -26.91384697]
7 [ -4.50524473 -78.91020966 -26.43970108]
8 [ -3.29619694 -78.70610046 -27.98403358]
9 [ -1.80273378 -78.89961243 -32.86447525]
10 [ -2.22650218 -79.17362976 -32.81439209]

**Comment by ericmjl** [comment]
Hi @tanjia123456! Looking at your code:

```python
'''with open("HLN-12-1vertices.txt") as node_list:
for eachline in node_list:
G.add_node()'''
with open("HLN-12-1edges.txt") as edge_list:
    for eachline in edge_list:
        G.add_edge()  # <-- error on this line
        G.add_node()  # <-- error on this line
```

You have an error on the two lines I highlighted above. From observing your code, it seems to me there's a more fundamental Python problem that you might be having, as `G.add_node()` an `G.add_edge()` have to have arguments passed into them, in this case, the node that you want to add (which would come from parsing `eachline` in the "right", where "right" is specific to how your data are represented in a text file).

Can I check, have you followed the [official tutorial](https://networkx.github.io/documentation/stable/tutorial.html) to learn how to use NetworkX? If not, I'd highly recommend walking through it at least once. If you want an extended tutorial, I have one that is in the form of a YouTube recording (4 hours long) that you can use. (You can find it [here](https://ericmjl.github.io/teaching/network-analysis-made-simple/).)
