### ISSUE TITLE
Incorrect Topological Sort

### ISSUE THREAD

**Issue by hetong007** [networkx/networkx#4194]
Currently `networkx` gives this suprisingly incorrect topological sort result:

```python
>>> import networkx as nx
>>> DG = nx.DiGraph([(1, 3), (2, 4), (3, 5), (4, 5)])
>>> list(nx.topological_sort(DG))
[2, 4, 1, 3, 5]
```

The correct result should at least be something like `[2, 1, 4, 3, 5]`.

**Comment by dschult** [comment]
I believe the definition of topological sort is:

A topological sort of a directed graph is a linear ordering of its vertices such that for every directed edge uv from vertex u to vertex v, u comes before v in the ordering.

So, ```[2, 4, 1, 3, 5]``` is a perfectly good topological sort.  
There is no implication that all leaves are listed before going to non-leaf nodes.

**Comment by hetong007** [comment]
I thought again and you are correct. It is just that this current behavior doesn't fit my use case so I've made my version.
