### ISSUE TITLE
nx_agraph.read_dot() weight bug

### ISSUE THREAD

**Issue by Volodimirich** [networkx/networkx#4196]
I met a slightly unpleasant bug.
If you load the graph from the dot notation (`read_dot`) and then try to apply `all_pairs_dijkstra_path_length`, an error occurs:
_Unsupported operand type(s) for +: 'int' and 'str'._
This happens because the weights of the edges in this graph are of type str.
As a personal solution, I propose to add _dijkstra_multisource to the _weighted.py_ file instead:
`cost = weight(v, u, e)`
do
`cost = int(weight(v, u, e))`
(If the ribs are integers)

**Comment by dschult** [comment]
I think it's probably better to do the conversion to int before you run the algorithm. 
Something like: this should work:
```python
G.add_edges_from((u, v, {"weight": int(wt)}) for u, v, wt in G.edges.data("weight"))
```
This doesn't actually add new edges because they already exist. It just updates the edge attribute dict. So even if other attributes exist, this doesn't change them.

It'd be nice if ```read_dot``` had conversion capabilities for attributes, but no one has implemented it.

**Comment by Volodimirich** [comment]
Thanks for answer
Unfortunately, this solution is not quite working either: 
RuntimeError: dictionary changed size during iteration

**Comment by dschult** [comment]
Right ---  sorry about that...
Put square brackets around the input to ```G.add_edges_from```
```python
G.add_edges_from([(u, v, {"weight": int(wt)}) for u, v, wt in G.edges.data("weight")])
```

**Comment by Volodimirich** [comment]
And now it breaks down in another place :/
Error in: 
    `return lambda u, v, d: min(attr.get(weight, 1) for attr in d.values())`
TypeError: '<' not supported between instances of 'int' and 'str'

**Comment by Volodimirich** [comment]
It was my fault, I forgot to say that the graph is a multigraph.
Now I will try to apply your solution to the multigraph

**Comment by dschult** [comment]
Yes -- for multigraph you should keep track of keys too... ```G.edges.data("weight", keys=True)``` with appropriate changes elsewhere in this line...

**Comment by Volodimirich** [comment]
Yes, thank you, after:
```
for u, v, ky, wt in graph.edges.data("weight", keys=True):
    graph.add_edge(u, v, weight=int(wt), key=ky)
```
It work!
