### ISSUE TITLE
use vertex and triangle ,how to create a graph?

### ISSUE THREAD

**Issue by tanjia123456** [networkx/networkx#4197]
hello, I have vertex.txt and triangle.txt, how to create a networkx graph? my source file hasn't edge information
 I have used matplotlib to create a graph, but I can't use nx.adjacency_matrix(G) function to get adj_matrix.  My ultimate goal is to generate adjacency matrix

**Comment by ShirsenduP** [comment]
What does the information in your text files look like?

**Comment by tanjia123456** [comment]
Hi, I have extract edge and vertex, but I saved it by .txt file format. So, How to send it to the G?
I have tried by myself, but it's wrong. the following is my edge.txt, I think only use it can create a graph.
edge: vertex #3 [ -3.29315186 -79.55406952 -22.78844452] - vertex #0 [ -2.14705372 -79.11716461 -22.24082756]
edge: vertex #2 [ -1.62398648 -79.33273315 -22.4699192 ] - vertex #0 [ -2.14705372 -79.11716461 -22.24082756]
edge: vertex #1 [ -2.90098286 -78.58725739 -22.61082458] - vertex #0 [ -2.14705372 -79.11716461 -22.24082756]
edge: vertex #27 [ -0.83862901 -78.48338318 -22.12019348] - vertex #28 [ -1.57793117 -78.03195953 -22.43221092]
edge: vertex #27 [ -0.83862901 -78.48338318 -22.12019348] - vertex #0 [ -2.14705372 -79.11716461 -22.24082756]
edge: vertex #2 [ -1.62398648 -79.33273315 -22.4699192 ] - vertex #31 [ -0.38851529 -78.94087219 -22.59452057]
edge: vertex #4 [ -2.05146265 -79.78436279 -22.83360863] - vertex #2 [ -1.62398648 -79.33273315 -22.4699192 ]
edge: vertex #3 [ -3.29315186 -79.55406952 -22.78844452] - vertex #5 [ -2.37813139 -79.81951141 -23.46728134]
edge: vertex #35 [ -1.07843208 -79.20427704 -23.42686653] - vertex #2 [ -1.62398648 -79.33273315 -22.4699192 ]
edge: vertex #31 [ -0.38851529 -78.94087219 -22.59452057] - vertex #2 [ -1.62398648 -79.33273315 -22.4699192 ]
edge: vertex #35 [ -1.07843208 -79.20427704 -23.42686653] - vertex #4 [ -2.05146265 -79.78436279 -22.83360863]

`import string
import networkx as nx
import matplotlib.pyplot as plt

G = nx.Graph() 

'''with open("HLN-12-1vertices.txt") as node_list:
for eachline in node_list:
G.add_node()'''
with open("HLN-12-1edges.txt") as edge_list:
for eachline in edge_list:
G.add_edge()
G.add_node()

print("number of edges:", G.number_of_edges()) 
G1=nx.draw(G)
plt.show()`

could you please help me modify this code?

**Comment by tanjia123456** [comment]
edge : vertex #0  - vertex #1 
edge : vertex #1  - vertex #3 
edge : vertex #3  - vertex #0 
edge : vertex #0  - vertex #3 
edge : vertex #3  - vertex #2 
edge : vertex #2  - vertex #0 
edge : vertex #0  - vertex #27 
edge : vertex #27  - vertex #1 
edge : vertex #1  - vertex #0 
edge : vertex #28  - vertex #1 


0 [ -2.14705372 -79.11716461 -22.24082756]
1 [ -2.90098286 -78.58725739 -22.61082458]
2 [ -1.62398648 -79.33273315 -22.4699192 ]
3 [ -3.29315186 -79.55406952 -22.78844452]
4 [ -2.05146265 -79.78436279 -22.83360863]
5 [ -2.37813139 -79.81951141 -23.46728134]
6 [ -3.48356891 -78.81594849 -26.91384697]
7 [ -4.50524473 -78.91020966 -26.43970108]
8 [ -3.29619694 -78.70610046 -27.98403358]
9 [ -1.80273378 -78.89961243 -32.86447525]
10 [ -2.22650218 -79.17362976 -32.81439209]

**Comment by tanjia123456** [comment]
edge : vertex #0 - vertex #1
edge : vertex #1 - vertex #3
edge : vertex #3 - vertex #0
edge : vertex #0 - vertex #3
edge : vertex #3 - vertex #2
edge : vertex #2 - vertex #0
edge : vertex #0 - vertex #27
edge : vertex #27 - vertex #1
edge : vertex #1 - vertex #0
edge : vertex #28 - vertex #1

0 [ -2.14705372 -79.11716461 -22.24082756]
1 [ -2.90098286 -78.58725739 -22.61082458]
2 [ -1.62398648 -79.33273315 -22.4699192 ]
3 [ -3.29315186 -79.55406952 -22.78844452]
4 [ -2.05146265 -79.78436279 -22.83360863]
5 [ -2.37813139 -79.81951141 -23.46728134]
6 [ -3.48356891 -78.81594849 -26.91384697]
7 [ -4.50524473 -78.91020966 -26.43970108]
8 [ -3.29619694 -78.70610046 -27.98403358]
9 [ -1.80273378 -78.89961243 -32.86447525]
10 [ -2.22650218 -79.17362976 -32.81439209]

**Comment by rossbar** [comment]
This has a lot of similar aspects to #4209: Loading data from text files (with arbitrary format) is not really a networkx-specific task, but more of a general Python task. Once you have the data loaded in a format that makes sense for your specific application, you can use graph methods like `add_nodes_from` to construct a Graph object from the data.
