### ISSUE TITLE
 networkx supports 3D graph??

### ISSUE THREAD

**Issue by tanjia123456** [networkx/networkx#4204]

**Comment by tanjia123456** [comment]
hello, my node data is 3D coordinate(x,y,z). it save as node index,x,y,z.  I found that networkx seems to only support two-dimensional graphics, and currently cannot support three-dimensional graphics. If there is a 3D drawing, could you please provide the source code? Thank you very much

**Comment by rossbar** [comment]
Most of the visualization functionality in networkx itself is geared towards 2D, but it is possible to visualize in 3D. For instance, [this gallery example](https://networkx.github.io/documentation/stable/auto_examples/3d_drawing/mayavi2_spring.html) shows how to use the `spring_layout` to generate 3D node positions, and visualize the results with `mayavi`.

Hopefully this answers your question at least to the point where you can get started tackling your problem. If not, please feel free to follow up!
