### ISSUE TITLE
Construct adjacency matrix based on node pairs

### ISSUE THREAD

**Issue by tanjia123456** [networkx/networkx#4209]
hello, I have a node-node.txt.
`0  1 
 1  5 
 5  0 
 6  5 
 5  1 
 1  6 
 0  56 
 56  1`

In each row, the first number is the starting node index, and the second number is the ending node index. How to construct the adjacency matrix by node pairs

**Comment by tanjia123456** [comment]
0 1
1 5
5 0
6 5 
5 1
1 6

**Comment by rossbar** [comment]
The trick would be loading the nodes into a Graph in the format you expect, then converting it to the format you want. Note that graphs have an attribute `adj` that will give you an `AdjacencyView` showing the mapping to each other node. There are also functions like e.g. `to_numpy_array` that will produce the adjacency matrix in the form of a 2D numpy array.

Hopefully this is sufficient to address the initial question - please feel free to follow up!

**Comment by dschult** [comment]
Also, see ```read_edgelist``` in [the readwrite section of the docs](https://networkx.github.io/documentation/stable/reference/readwrite/index.html)

**Comment by tanjia123456** [comment]
ok, thank you very much!
