### ISSUE TITLE
Cut-off documentation in weighted shortest paths algorithms

### ISSUE THREAD

**Issue by alonj** [networkx/networkx#4219]
Hey,

The documentation for some shortest paths algorithms on weighted edges (mentioned below) explains the "cutoff" parameter to be:

> cutoff (integer or float, optional) – Depth to stop the search. Only return paths with **length** <= cutoff.

It seems confusing to me to use "length" here, which can also be "number of edges between nodes", rather than what is actually meant here "path weight" (or "sum of weights of edges between nodes"). Both metrics are valid on weighted paths, so perhaps it's better to make the distinction between "path weight" and "path length".
It's a small change, but I've personally spent an embarrassingly long time finding it to be the case...

Suggested documentation:

> cutoff (integer or float, optional) – Depth to stop the search. Only return paths of **summed weight** <= cutoff.

This is relevant for the following functions:
```
networkx.algorithms.shortest_paths.weighted.all_pairs_dijkstra_path_length
networkx.algorithms.shortest_paths.weighted.all_pairs_dijkstra_path
networkx.algorithms.shortest_paths.weighted.all_pairs_dijkstra
networkx.algorithms.shortest_paths.weighted.multi_source_dijkstra
networkx.algorithms.shortest_paths.weighted.multi_source_dijkstra_path
networkx.algorithms.shortest_paths.weighted.multi_source_dijkstra
networkx.algorithms.shortest_paths.weighted.single_source_dijkstra_path_length
networkx.algorithms.shortest_paths.weighted.single_source_dijkstra_path
networkx.algorithms.shortest_paths.weighted.single_source_dijkstra
networkx.algorithms.shortest_paths.weighted.dijkstra_predecessor_and_distance
```

**Comment by rossbar** [comment]
This does seem like it could be confusing. The `Notes` section does say: *Distances are calculated as sums of weighted edges traversed*, but I agree that having something in the parameter description would improve visibility. Your wording suggestion seems reasonable to me.

**Comment by AbhayGoyal** [comment]
Hey @rossbar , Could I work on this issue? I am just starting to contribute in Open Source and wanted to this.

**Comment by rossbar** [comment]
Sure @AbhayGoyal , no one's submitted a PR with a proposed fix so feel free to do so. As I mentioned in the comment above, the proposed wording change seems reasonable to me... we'll see what other reviewers think if you submit a PR!

**Comment by AbhayGoyal** [comment]
Thanks @rossbar. Could you tell me which document should I make the change to?

**Comment by rsdel2007** [comment]
Hi i am looking to fix the issue.<br> Do I have to remove the line _Distances are calculated as sums of weighted edges traversed__ from the `Notes` section?

**Comment by AbhayGoyal** [comment]
I had a similar qs, I was also trying yo figure out where to make the changes

**Comment by dschult** [comment]
I suggest we leave the line in the Notes section as it is.
And that we change the `cutoff` parameter description to:

```
Length (sum of edge weights) at which the search is stopped. 
If given a value, we only process paths shorter than `cutoff`.
```

**Comment by rossbar** [comment]
The functions with the docstrings that may need to be modified are listed in the top comment. I haven't looked at each closely, so I'm not sure if it's *every* docstring, or just some of them.

**Comment by AbhayGoyal** [comment]
I have changed the documentation for cutoff from length <= cutoff to summed weight <= cutoff. @dschult could you tell me where do have to change the parameter description. It is not present in the weighted.py file. Is there any other file where it is present?

**Comment by dschult** [comment]
The line that you changed from `length <= cutoff` is the line I was referring to.
So my suggestion was to replace that whole line (which confusingly calls it "depth" and "length" and never says it is the "sum of the edge weights".  I'm proposing replacing that whole line (and making it the two lines above).

**Comment by AbhayGoyal** [comment]
Length (sum of edge weights) at which the search is stopped.
        If given a value, we only process paths shorter than `cutoff`.
       Only return paths with summed weight <= cutoff.

Would this be a correct representation of what it is supposed to do?

**Comment by dschult** [comment]
How about:

Length (sum of edge weights) at which the search is stopped.
If cutoff is provided, only return paths with summed weight <= cutoff.

**Comment by AbhayGoyal** [comment]
Looks good.
