### ISSUE TITLE
add an advanced example, already written elsewhere

### ISSUE THREAD

**Issue by lobpcg** [networkx/networkx#4220]
add an advanced example, already written in https://github.com/lobpcg/python_examples/blob/master/networkx_example.py

**Comment by dschult** [comment]
Thanks for this!  

Perhaps it should go into the gallery examples
```examples/algorithms``` seems like a good location. Name the module ```plot_<something>``` and tweak the module to match other examples sphinx stuff.
You can check how it looks using the Circle-CI artifact that shows the documentation. 

We're trying to include more text describing the examples than our current examples...  
:}
