### ISSUE TITLE
Add a from_node_dataframe function

### ISSUE THREAD

**Issue by ericmjl** [networkx/networkx#4225]
Leaving this issue here for newcomers who might want to contribute.

--------

@dschult to address the final point:

> What about having a function from_node_dataframe?

I like the idea! I think it could be left for another newcomer to contribute, since I think the pattern is similar:

```python
def from_node_dataframe(df):
    G = nx.Graph()
    for n, d in df.iterrows():
        G.add_node(n, **d)
    return G
```

Probably could be made more efficient, more flexible with custom funcs too, but I think it's worth fleshing out in a different PR, maybe with a design sketch via discussion on the issue tracker! I'll raise this up there.

_Originally posted by @ericmjl in https://github.com/networkx/networkx/pull/4217#issuecomment-700636540_

--------

For newcomers who would like to make a contribution, this could be a good one! You would have to flesh out the function a bit more, make it look like the sibling functions in `convert_matrix.py`, and figure out good test cases.

**Comment by vessaldaneshvar** [comment]
I want to work this issue
Please help me.
Thank you

**Comment by ericmjl** [comment]
@vessaldaneshvar please do so! You might want to reference the patterns used in PR #4217, as having the flexibility to add additional metadata on the fly could be good.

**Comment by viktor-kryvyziuk** [comment]
Are there any expectations regarding how edges are specified inside DataFrame?

**Comment by vessaldaneshvar** [comment]
> Are there any expectations regarding how edges are specified inside DataFrame?

this method create Graph by Node .
input Edges after graph creation .

**Comment by dschult** [comment]
Yes, this is probably a one-liner that could be included in the doc_string of to_node_dataframe:

```python
# df already created and G a graph you want to update/add the node data attributes
G.add_nodes_from((n, dict(d)) for n, d in df.iterrows())
```

**Comment by j6k4m8** [comment]
@viktor-kryvyziuk if you're still looking for suggestions and @dschult approves, I'd recommend something like:

```python
def from_node_dataframe(
    df: pd.DataFrame, 
    source_column: str = "source", 
    target_column: str = "target", 
    directed: boolean = False
) -> nx.Graph
```

In other words, the user can specify column headers if they are nonstandard, and otherwise it'll look for `source` and `target` columns; all the rest should be edge attributes, imo :)

I have a working implementation of this here, which is all Apache 2.0 if you'd like to borrow any of it:
https://github.com/aplbrain/dotmotif/blob/master/dotmotif/ingest/__init__.py#L30-L47

**Comment by dschult** [comment]
@j6k4m8 that is the [already existing function](https://networkx.github.io/documentation/stable/reference/generated/networkx.convert_matrix.from_pandas_edgelist.html): ```nx.from_pandas_edgelist()```

This Issue deals with moving data between dataframes and the **node** attributes.

**Comment by j6k4m8** [comment]
Ack. Sorry, silly oversight! (And sorry for the github notification spam!)

**Comment by jarrodmillman** [comment]
I like Dan's suggestion to add the one-liner to the docstring.  We should add it as an example so that it is tested as part of the doctests.

**Comment by StutiV** [comment]
Hello, I'm a newcomer and I'd like to contribute. Can I be assigned this issue?

**Comment by dschult** [comment]
Well.... It will be easier to do that after #4217 is merged.
And to be clear, this issue is fixed by adding a simple example that shows the one-liner to the doc_string of the function `to_node_dataframe` (that's why you have to wait until the other PR is merged).

It might be more immediate to contribute, for example, by fixing #4432 which is also a documentation issue.

**Comment by AbhayGoyal** [comment]
Hey, I recently saw #4432 has already been closed. I am also a new comer and wanted to fix this issue. Can I now take this or is there any other that I can work on?

**Comment by dschult** [comment]
This one needs #4217 to be merged first.
Try looking at the [issues with label "Documentation"](https://github.com/networkx/networkx/issues?q=is%3Aopen+is%3Aissue+label%3ADocumentation)

**Comment by akshayamadhuri** [comment]
i would like to work on this issue

**Comment by rossbar** [comment]
@akshayamadhuri please feel free. I think the best place to start is with [dschult's suggestion](https://github.com/networkx/networkx/issues/4225#issuecomment-705956344)
