### ISSUE TITLE
Command line interpretor works, but running file with Python fails

### ISSUE THREAD

**Issue by chuckuntulis** [networkx/networkx#4232]
I am trying to generate a simple graph and I keep running into this problem. If I bring up the Windows Power Shell, start python and put the code in line by line, the code executes, the answer is printed out and NO dialog is presented nor is a graph shown

the Demo dialog box pops up when I have not asked for it when I run the the command line 
"python ./networkxTestCode.py" and the same thing happens when running the code in Visual Studio Code. The dialog has four lines ... the last of which states "Button that does nothing". If I kill the dialog, the another dialog pops up with an error about PySimpleGUI and starting with a clean unused layout. The code does not import PySimpleGUI. 

This last dialog keeps popping up and I have to go to Task Manager to kill it.

This the code from one of the examples in the documentation:
"
import networkx as nx
G = nx.Graph()

G.add_node(1)
G.add_edge('A', 'B', weight=4)
G.add_edge('B', 'D', weight=2)
G.add_edge('A', 'C', weight=3)
G.add_edge('C', 'D', weight=4)
nx.shortest_path(G, 'A', 'D', weight='weight')
"
I have used PySimpleGUI successfully with some complex dialogs. Why is it being executed in this case and what do I need to get this code to run.

**Comment by chuckuntulis** [comment]
why does import networkx as nx launch a dialog? 

Is networkx a wrapper for PySImpleGUI and if so, why isn't that stated?

**Comment by chuckuntulis** [comment]
I ran the code on a different Windows system and it ran and did not pop-up a dialog. It also did not pop-up a graph.

**Comment by MridulS** [comment]
I haven't used PySimpleGUI before so I am not sure what is happening there but the following code while NOT pop up/draw any graph, this will only calculate the shortest path between node `A` and `B`.

```
import networkx as nx
G = nx.Graph()

G.add_node(1)
G.add_edge('A', 'B', weight=4)
G.add_edge('B', 'D', weight=2)
G.add_edge('A', 'C', weight=3)
G.add_edge('C', 'D', weight=4)
nx.shortest_path(G, 'A', 'D', weight='weight')
```

Can you try adding `nx.draw(G)` at the end of your code and see what happens?

```
import networkx as nx
G = nx.Graph()

G.add_node(1)
G.add_edge('A', 'B', weight=4)
G.add_edge('B', 'D', weight=2)
G.add_edge('A', 'C', weight=3)
G.add_edge('C', 'D', weight=4)
nx.shortest_path(G, 'A', 'D', weight='weight')
nx.draw(G)
```

**Comment by chuckuntulis** [comment]
Thanks for the feedback. I will try that tomorrow morning.

**Comment by chuckuntulis** [comment]
The code never gets to your suggested draw statement.

The code hangs if:
1) from a file
2) from interactive type in
3) run from Visual Studio Code

Running this code:
import networkx as nx
G = nx.Graph()

G.add_node(1)
G.add_edge('A', 'B', weight=4)
G.add_edge('B', 'D', weight=2)
G.add_edge('A', 'C', weight=3)
G.add_edge('C', 'D', weight=4)
nx.draw(G) #????
nx.shortest_path(G, 'A', 'D', weight='weight')
nx.draw(G)

saved in networkxTestCode3.py and run in PowerShell
python .\networkxTestCode3.py

pops up the dialog as seen in the included screenshot image, the code hangs
and I have to use TaskManager to kill it

Anytime I have a file that contains  "import networkx as nx" or just
"import networkx" with or without any other code this happens so I never
get to the draw statement. If I run the same code in VIsual Studio Code the
same thing happens.

If copy this code, start Python and then paste it into the running Python,

Just putting the import  statement into Python, I get the following after I
kill python using taskmanager.
  ========================================================================
PS E:\Stuff\Python stuff> python
Python 3.8.6 (tags/v3.8.6:db45529, Sep 23 2020, 15:52:53) [MSC v.1927 64
bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> print("foo")
foo
>>> import networkx as nx
C:\Users\Charles\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.8_qbz5n2kfra8p0\LocalCache\local-packages\Python38\site-packages\PySimpleGUI\PySimpleGUI.py:7260:
UserWarning: *** YOU ARE ATTEMPTING TO RESUSE AN ELEMENT IN YOUR LAYOUT!
Once placed in a layout, an element cannot be used in another layout. ***
  warnings.warn('*** YOU ARE ATTEMPTING TO RESUSE AN ELEMENT IN YOUR
LAYOUT! Once placed in a layout, an element cannot be used in another
layout. ***', UserWarning)
PS E:\Stuff\Python stuff>
==========================================================================

I renamed the files in the directory from  networkxTestCode*.py to
netxTestCode*.py thinking that Python may have tried to load one of them
because of the leading networkx in the names, but this yielded the same
result.

I have narrowed it down to simply importing networkx.

I have no other tests that I can run.

Thanks for any ideas you might have.

Testing the code on another system, it runs to completion, exits, but no
graph is drawn

**Comment by chuckuntulis** [comment]
The following code exhibits the same behavior on the original system, but when I run it on my second system it runs as expected and generates a graph. I have convinced myself that the failure must have something to do with the Python installation and that it is importing erroneous modules, but I am at a loss to figure out how to isolate the reason for the failure. If you can suggest some places to look or a technique for identifying the issue I would appreciate whatever insights that you have or forward this correspondence to someone who might be able to help. 

import networkx as nx
import matplotlib.pyplot as plt
G = nx.Graph()
G.add_edge(1,2)
G.add_edge(1,3)
nx.draw(G, with_labels=True)
plt.show()

**Comment by chuckuntulis** [comment]
I did a "pip uninstall" of networkx and a "pip install" and the problem persists. I do not understand how or why  PySimpleGui would be invoked when it wasn't imported. Is there a flag someplace in Python that is set to automatically import PySimpleGUI when networkx is imported?

**Comment by MridulS** [comment]
If I were to take a guess it probably has something to do with matplotlib interactions inside PySimpleGUI. I am not familiar with PySimpleGUI  so can't say what's happening there. NetworkX code doesn't import/interact with PySimpleGUI.

**Comment by chuckuntulis** [comment]
This only happens on one system when the code contains the import of
networkx with or without any other python code. I am going to ask the
Python and Circuit Python Discourse communities.

Thanks again for suggestions.

**Comment by chuckuntulis** [comment]
I finally found the cause of this error which was that I had a file named html.py which contained an import of PySimpleGUI and it had a layout which was the root of the error. Renaming the file from html.py to html1.py solved the problem. Perhaps the error dialog could be more helpful if it mentioned this condition. The end result error gives no hint of where someone should look. This would be helpful to new users of PySimpleGUI.

**Comment by ericmjl** [comment]
I'm glad you found the error, @chuckuntulis! 

As for where to put the error, I have a suspicion this might be a deeper-rooted thing in the stack. Also not a user of PySimpleGUI, so I can't speak to what's going on, but in the dependency chain I can see so far, it's networkx's drawing --depends on--> matplotlib --depends on --> other stuff. If the problem is deeper-rooted, then error messages in NetworkX is only a bandage; the the earliest place in the stack where this interaction happens should be where the error message gets stuck.

**Comment by chuckuntulis** [comment]
I agree. My first investigation/code will be trying to help people find
this particular naming issue by comparing the known Python module names
with the file names in the directory. I already have code that will do part
of that search, so I will start there.

I have posted a comment in the PySimpleGUI group on GitHub and hopefully
someone in that group will contribute to a solution/recommendation. The
dialog box is partly helpful, but only identifies the final failure and not
any of the possible conditions leading up to it.

Thanks again.

**Comment by PySimpleGUI** [comment]
I'm very late to this party.

> The end result error gives no hint of where someone should look. This would be helpful to new users of PySimpleGUI.

Can you open an Issue in the PySimpleGUI project?  I am interested in the error dialog you're seeing from PySimpleGUI as well as the additional information you think would be helpful.
