### ISSUE TITLE
Add support for Python 3.9 when dependencies are ready

### ISSUE THREAD

**Issue by NeilGirdhar** [networkx/networkx#4239]
Just an issue to track progress of support Python 3.9, which was released yesterday.

**Comment by MridulS** [comment]
I believe there isn't anything needs to be done for that? NetworkX already supports 3.9.
I guess we should change the travis test from 3.9-dev to 3.9.

**Comment by MridulS** [comment]
We also need to wait for GitHub python checkout action and Appveyor to have a stable 3.9 release to turn on CI there.

**Comment by NeilGirdhar** [comment]
That's great news.  You'll also need to change https://github.com/networkx/networkx/blob/master/requirements/default.txt https://github.com/networkx/networkx/blob/master/INSTALL.rst

**Comment by jarrodmillman** [comment]
We also need to wait until their are prebuilt wheels for 3.9 for our dependencies (e.g., scipy).  That is why you see ``python_version<'3.9'`` in ``requirements/default.txt``.  Once prebuilt wheels are available for those dependencies, I will remove those lines.

Are you running into issues installing v2.5 on Python 3.9?  If so, what errors are you seeing.

**Comment by NeilGirdhar** [comment]
No, it's installing fine, sorry if this was noise…

**Comment by rossbar** [comment]
I'm going to close this one as the necessary changes for 2.6 seem to be sufficiently tracked. If there's something that should be added here for visibility, please feel free to reopen!
