### ISSUE TITLE
Does networkx implement the minimum k-cut algorithm?

### ISSUE THREAD

**Issue by JustinMBrown** [networkx/networkx#4242]
I've got an undirected, unweighted graph, and I don't have terminal nodes. According to wikipedia, there's a minimum k-cut that cuts the graph into 2 subgraphs, at the minimum cut point: https://en.wikipedia.org/wiki/Minimum_cut

I couldn't find any algorithm in the docs that does this.

**Comment by MridulS** [comment]
Have a look at https://networkx.github.io/documentation/stable/reference/algorithms/generated/networkx.algorithms.connectivity.stoerwagner.stoer_wagner.html

This should solve the min cut point problem for an undirected, unweighted graph without terminal nodes.

**Comment by JustinMBrown** [comment]
That works perfectly, thank you!. While I've got your here, my real problem is that I have a lopsided dumbbell graph with "hairs". So I'm using that algorithm as the basis for an optimization function that can cut the dumbell while ignoring the stray hairs. Is there an existing algorithm that can do this? I saw the sections on clustering which seemed like a decent fit for the problem, but I need the cut as the output. If not, no big deal.

**Comment by MridulS** [comment]
If the graph is a "proper" barbell graph (the hairballs on either sides connected) `nx.minimum_edge_cut(G)` should give you the required details about the edge in between the hairballs.
Example:
<img width="543" alt="Screenshot 2020-10-07 at 21 17 31" src="https://user-images.githubusercontent.com/5363860/95355026-b9eed400-08e2-11eb-985f-55f110c4d565.png">

**Comment by JustinMBrown** [comment]
Here's my actual graph and goal:
![image](https://user-images.githubusercontent.com/6200664/95356727-9862fd80-088c-11eb-8495-c3388ef7a265.png)

The idea here is to minimize the cut, and maximize the balance.

**Comment by MridulS** [comment]
Can you try `nx.minimum_edge_cut(G)` for this if it doesn't give you the desired cut you can pick one node from hairball A and one node from hairball B  and execute `nx.minimum_edge_cut(G, node_from_hairball_A, node_from_hairball_B)`.

**Comment by rossbar** [comment]
It's been a while without any follow up here so I'm going to close this. Feel free to reopen as needed.
