### ISSUE TITLE
'DiGraph' object has no attribute '_node'

### ISSUE THREAD

**Issue by yuguanw** [networkx/networkx#4243]
Hi I am using Python3.6 and networkx2.5. Recently I received an error message:

---------------------------------------------------------
~/anaconda3/lib/python3.6/site-packages/networkx/classes/graph.py in __len__(self)
    437 
    438         """
--> 439         return len(self._node)
    440 
    441     def __getitem__(self, n):

AttributeError: 'DiGraph' object has no attribute '_node'

---------------------------------------------------------

I googled the solution and it seems to be the problem of version. But I think I am using the latest version. Could you help me on this?

**Comment by rossbar** [comment]
Hmm, this looks like it might be some sort of installation or packaging problem. From the path in your example, it looks like you're using anaconda, can you try the following:

```
conda create --name nxtestenv python=3.6
conda activate nxtestenv
conda install networkx==2.5
```

Then try to reproduce the error from within that environment. I was unable to do so.

**Comment by yuguanw** [comment]
Thank you? 

I still got the same error message. BTW, when I tried:
---------
import networkx 
print(networkx.__version__)
---------

it returns to me 2.5.

**Comment by rossbar** [comment]
I am unable to reproduce the error you are seeing, so in order to help we'd need to know what procedure reproduces the error for you. Are you modifying the code in `site-packages` at all after installation?

**Comment by yuguanw** [comment]
No I haven't. I think I have the same graph.py as the one on the github.

**Comment by dschult** [comment]
Just to be very clear, you seem to be getting a different Graph class than what you think you are getting.  I think we've narrowed down that you have the correct version of python and networkx.  Now, can you run this short piece of code:

```python
import networkx
G=networkx.DiGraph()
len(G)
```

**Comment by yuguanw** [comment]
Hi,

The problem has been fixed. Thank you very much!

Best,
Yuguan
