### ISSUE TITLE
Issue with networkx.has_eulerian_path()

### ISSUE THREAD

**Issue by tlarock** [networkx/networkx#4244]
This issue adds to #3976 

There appears to be a problem with the `has_eulerian_path` function. It returns the wrong answer on this example:
```
test_graph = nx.DiGraph()
test_graph.add_edges_from([(0, 1), (1,2), (0,2)])
print(nx.has_eulerian_path(test_graph))
print(list(nx.eulerian_path(test_graph)))
```
Output:
```
True
[(0, 0), (0, 1), (1, 2)]
```

This directed graph does not have a Eulerian path, and, adding to #3976, the path returned by `eulerian_path` is not an actual Eulerian path, since it (1) does not include the edge `(0,2)` and (2) includes a self-loop `(0,0)` that is not in the graph.

My hunch is that the problem is in this line: https://github.com/networkx/networkx/blob/3351206a3ce5b3a39bb2fc451e93ef545b96c95b/networkx/algorithms/euler.py#L256

I think changing that `2` to be `semibalanced_ins+semibalanced_outs` may do the trick, since the definition is
>"...every _other_ vertex has equal in\_degree and out\_degree..." 

Going to see about fixing and adding this test. Appreciate any clues, ideas or tips.

**Comment by rossbar** [comment]
This does seem to be giving an incorrect result for the directed graph you mention. The thing that jumps out to me is that the description for directed graphs in the docstring does not seem to match the implementation for directed graphs.
