### ISSUE TITLE
Add to tutorial info about edge order

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#4249]
With Python 3.6 or later the behavior of Graph/DiGraph is ordered because dict's became ordered with that version.

And... The order of adjacency reporting... g.adj, g.successors, g.predecessors is now the order of edge adding.
But the order of g.edges is not always the order of edge adding. The order of g.edges is the order of the adjacencies which includes both the order of the nodes and each node's adjacencies.

```python
g = nx.DiGraph()
g.add_edge(2, 1)   # adds the nodes in order 2, 1
g.add_edge(1, 3)
g.add_edge(2, 4)
g.add_edge(1, 2)
assert list(g.successors(2)) == [1, 4]
assert list(g.edges) == [(2, 1), (2, 4), (1, 3), (1, 2)]
```

We should add this kind of info to the tutorial.  (thought of because of question #4248 )

**Comment by abdulelahsm** [comment]
I'd like to take on this issue

**Comment by abdulelahsm** [comment]
I'll take on this issue. Is this the tutorial notebook you're talking about? https://github.com/networkx/notebooks/blob/master/tutorial.ipynb @dschult
