### ISSUE TITLE
grid_2d_graph topology with write_dot question

### ISSUE THREAD

**Issue by Volodimirich** [networkx/networkx#4253]
Hello, I have a question about working with nx.grid_2d_graph topology. In this topology, the node has the type - tuple: (ylevel, xlevel).
If this topology is saved using the write_dot(G, path) method, the vertices correspond to tuple in the dot file, which leads to further problems (in other modules where this graph is used).

Is there any way to recalculate the vertices of the graph except for recreating the graph similar to the previous one?

**Comment by dschult** [comment]
Maybe the [relabel_nodes functions](https://networkx.github.io/documentation/stable/reference/relabel.html) will help.

Are these other modules within networkx or in another package? I expect all NetworkX functions to work with nodes that are tuples.

**Comment by Volodimirich** [comment]
Thank you, it's works great!

The problem was that the other modules were written in c++ using boost graph.
