### ISSUE TITLE
bug in is_isomorphic() function?

### ISSUE THREAD

**Issue by KechenQin** [networkx/networkx#4255]
I have two directed graphs and want to test isomorphism for them (see the code below). I think these two graphs are not isomorphic, but the is_isomorphic function returns True. Can anyone tell me why? I am using networkx 2.5.

```sh
import networkx as nx
from networkx.algorithms import isomorphism


G1 = nx.DiGraph()
G1.add_edges_from([(1,2), (2,3), (1,4), (4,5)])

G2 = nx.DiGraph()
G2.add_edges_from([(1,2), (2,3), (3,4), (1,5)])

GM = isomorphism.GraphMatcher(G1,G2)
print(GM.is_isomorphic()) # True
print(GM.mapping) # {1: 1, 2: 2, 4: 3, 3: 4, 5: 5}
```

**Comment by dschult** [comment]
You probably want  ```isomorphism.DiGraphMatcher``` instead of ```isomorphism.GraphMatcher```

**Comment by KechenQin** [comment]
Yeah, the problem is solved after using DiGraphMatcher(). Thank you!
