### ISSUE TITLE
Parallel betweenness example bad runtimes in docs

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#4275]
There is a nice example in the gallery for [computing betweenness centrality with multiprocessing](https://networkx.org/documentation/stable/auto_examples/advanced/plot_parallel_betweenness.html). Unfortunately, the example in the docs show poorer performance for the parallel version than the non-parallelized version, likely due to the CI service only using single-core (or otherwise not very performant) nodes for computation. At the very least it might be worth adding some text somewhere to the example to explain why the example shows performance results that differ from what is expected.

It's also probably worth taking a look at the example in its entirety and consider alternative approaches to multiprocessing, e.g. `concurrent.futures`.

**Comment by berlincho** [comment]
Hi, @rossbar. I am new to networkx community and interested in tackling this issue. Should I focus on adding texts to the example or focus more on finding other parallel alternatives? Thank you.

**Comment by rossbar** [comment]
Hi @berlincho - if you are interested in investigating other parallelization approaches that might be a fun project. It's unlikely that we can do anything to improve the parallel performance of the example in the rendered documentation, as I suspect that is just a limitation related to the CI hardware. A quick note in the explanation for that example might help clear up this point for readers.

**Comment by korbonits** [comment]
Opened a PR, #4926, adding a comment about the sphinx performance output vs. running locally. LMK what you think. I think multiprocessing, while less performant in the CI/CD, is probably faster for developers using `networkx` than `concurrent.futures`, as graph size increases.

**Comment by korbonits** [comment]
Thanks! Apologies for delay in responding, dealing with family emergency.
Might consider adding concurrent.futures example in future PR
