### ISSUE TITLE
Update matplotlib drawing with arrows and other improvements (migrated from Trac #434)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#428]
Original ticket https://networkx.lanl.gov/trac/ticket/434
Reported 2010-09-21 by @hagberg, assigned to @hagberg.

Attached is code from http://groups.google.com/group/networkx-discuss/browse_thread/thread/b95fda9813fae67d that improves the matplotlib drawing interface.
See also #78 and #293 for context.

**Comment by hagberg** [comment]
See #2757
