### ISSUE TITLE
Edge centrality measure

### ISSUE THREAD

**Issue by DeepaMahm** [networkx/networkx#4293]
Hello Everyone,

I have been looking for packages that allow the computation of centrality measures for a network. I could find implementations of node centrality measures in Networkx. However, I would like to know if implementations of edge centrality measures like Kirchhoff Index or Resistance are available. For instance, after I delete an edge in a network and use k-core to remove nodes with degree < k this will result in a subgraph. By doing this experiment, I would like to study the impact of edge deletion on the variation of effective resistance of the resulting subgraph.

**Comment by dschult** [comment]
We have a distance measure [function called resistance_distance](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.distance_measures.resistance_distance.html). 

That seems related to what you are looking for, but probably not set up to do exactly what you would like.  In particular it finds the resistance between two nodes in the circuit/network.  That's very local to those two nodes... so you might need to call it more than once to get the info you are looking for.  Indeed, you might need a wrapping function to call "all pairs resistance distance".  If that involves too much recomputation, take a look at the source (green link in upper right of the docs for that function) and see if you could save computation by computing all pairs in one call of a new function: ```all_pairs_resistance_distance()```  If that is much better than just computing it for each pair, we should implement that.

**Comment by DeepaMahm** [comment]
@dschult 

I tried something like the below


```
import networkx as nx
import matplotlib.pyplot as plt


def get_resistance_distance(H):
    """
    :return:
    """
    n = len(H.nodes())
    H.add_edges_from([(u, v) for u in retain_node_ids for v in (n + 1, n + 2)])
    H = nx.k_core(H, k=2)  # remove nodes with degree < 2
    H.remove_nodes_from([n + 1, n + 2])
    nx.draw(H, with_labels=True)
    plt.show()

    # effective resistance: original graph
    rd = nx.resistance_distance(H, nodeA=8, nodeB=19)

    return H, rd


if __name__ == '__main__':

    # ---------------------------------------------------------------------------------
    H0 = nx.gnm_random_graph(n=20, m=30, seed=1)  # generate a random graph
    retain_node_ids = [8, 19]

    H0, rd0 = get_resistance_distance(H0)
    # ---------------------------------------------------------------------------------
    # removal of 3 edges from H0
    # ---------------------------------------------------------------------------------
    H1 = H0.copy()
    H1.remove_edges_from(ebunch=[(14, 16), (16, 13), (16, 0)])  
    H1, rd1 = get_resistance_distance(H1)

    # ---------------------------------------------------------------------------------
    # removal of 3 edges from H1
    # ---------------------------------------------------------------------------------
    H2 = H1.copy()
    H2.remove_edges_from(ebunch=[(14, 15), (15, 3), (0, 10)])  
    H2, rd2 = get_resistance_distance(H2)

    print(rd0)
    print(rd1)
    print(rd2)

```
"so you might need to call it more than once to get the info you are looking for. Indeed, you might need a wrapping function to call "all pairs resistance distance".

From what I understand, I'm not sure if you meant the following
    H0, rd0 = get_resistance_distance(H0)
    H1, rd1 = get_resistance_distance(H1)
    H2, rd2 = get_resistance_distance(H2)

may be avoided if one could create a wrapper function that will pass H0 and the subgraph H1, H2 at once? Here, I'm always computing the resistance distance for a fixed pair (source, target) for all the subgraphs. So I'm not sure if what is suggested above is for multiple pairs.

Secondly,
I had a look at the source code and I understand that the implementation is for an undirected graph. I would like to know if
there are similar implementations that already exist for directed graphs. I would like to compute this measure for a flow graph with directed edges (eg. current flows and potential drops).


Thanks a lot for your time and kind attention
Deepa

**Comment by dschult** [comment]
If you are sticking with a single source and target and looking across subgraphs then I think your approach is good and what we offer...  

I don't know of any way to consider Kirchoff's laws in a directed network. There is a kind of symmetry that if our society had collectively defined voltage to be the negative of what it is, then all currents would just get reversed and electrons would be positive charge and protons would have negative charge. But of course, the physical system would give the same results.  There are a fair number of functions in networkx that compute flows on networks (directed or undirected) so you might look at those. But in terms of describing an electric circuit, I don't even know what a directed circuit would mean (other than a diode I guess).
