### ISSUE TITLE
OOM find non exist edges

### ISSUE THREAD

**Issue by Mobzhang** [networkx/networkx#4316]
If I use nx.non_edges(G), G has 20'000 nodes, the process will be killed, cause of OOM. did any one can help me ?

**Comment by dschult** [comment]
non_edges is an iterator.... So, if you process each non_edge and don't store it you can solve your memory issues.

**Comment by rossbar** [comment]
This is an application specific problem - if you have a graph with 20,000 nodes and no edges, then `non_edges` would construct a generator that produces the edges of a complete graph with 20k nodes, i.e. around 200 million edges. @dschult is correct though - if it's possible to analyze the edges without necessarily needing to store them in a data structure, then this may be fine for your application.

I don't think there's anything actionable here so I will close this!
