### ISSUE TITLE
New geospatial examples

### ISSUE THREAD

**Issue by NicolasCadieux** [networkx/networkx#4323]
Hi,
This is related to issues #3932, #3478.  When using networkX to find over 305 million the shortest paths on a river network, I quickly realized that the nx.read_shp() and nx.write_shp() function had problems (no 3D, removal of parallels edges...).  I see there is an wish to get rid of those two functions as that would simplify your life as installing GDAL seems to be a problem for users and code maintainers. 

I would like to offer simplified bits of code (and example data) based on the algorithm and paper found below.  The goal would be to help user in the GeoSpatial community figure out how to use networkX by bypassing the deprecated (or soon to be deprecated???)  nx.read_shp() and nx.write() function, using geopandas functions.  I see @iboates has contributed ideas and code to make this work and I would like to avoid duplicating some work. @adnanmuttaleb, have you done some work on this?

It would also be nice if someone could add some code to implement traffic rule for road networks as all my work so far has been on river networks where only current direction was important. 

Can you point me in the right direction for adding examples to your site? 

https://gitlab.com/njacadieux/upstream_downstream_shortests_path_dijkstra
https://www.mdpi.com/2306-5729/5/1/8

**Comment by jarrodmillman** [comment]
Thanks!  It would be great to have several examples of working with geospatial data in our gallery.  I'll setup a template and let you know where to add your example later today.

**Comment by jarrodmillman** [comment]
I am running out of steam, so I will get to this later next week.

**Comment by NicolasCadieux** [comment]
Take your time! I'am in no rush.

**Comment by NicolasCadieux** [comment]
Hi,
I see a new thread has started on geospatial examples.  Will you be need I get my help?
Nicolas

**Comment by jarrodmillman** [comment]
Yes, you should check whether your use case is covered.  If not, please add a comment to #4366 describing your use case and describing how you handle it.  @ljwolf and others should be able to provide guidance regarding whether another example is needed here or would be better handled in one of their other projects (e.g., pysal, geopandas, momepy, osmnx).

**Comment by martinfleis** [comment]
@NicolasCadieux I am curious, have already you tried generating networkx graph from your river cases using `momepy.gdf_to_nx()`? I am working on the example illustrating momepy and it would be nice to have something else apart from obvious street networks. I have tried [sample data](https://gitlab.com/njacadieux/upstream_downstream_shortests_path_dijkstra/-/blob/master/Sample_Data/SampleData_Results.zip) from the repository linked above, which seems to work with no issues, but I am curious about more complex cases (like 3D geometries).

**Comment by NicolasCadieux** [comment]
Hi,

I can put the 3D version of the geometries if you like.  I have not tried momepy but I did try creating a multiGraphs but it was too slow.  I think momepy will build a MultiGraph by default?  I had over 500 million shortest path calculations to do speed was very important. I now see multiple ways to speed and simplify my algorithm.  It was a first shot.

Nicolas

**Comment by martinfleis** [comment]
> I can put the 3D version of the geometries if you like.

That would be superb.

> I think momepy will build a MultiGraph by default?

Yes. Since it was designed for street networks, it is crucial to allow parallel edges. It may not be optimal for your case of super large data but may be good enough for smaller.

**Comment by NicolasCadieux** [comment]
3D sample is uploaded to master.

**Comment by martinfleis** [comment]
@NicolasCadieux confirmed as working without issues. Can I use this dataset within the networkx example? (how should I attribute it?)

**Comment by NicolasCadieux** [comment]
Nicolas Cadieux
https://www.mdpi.com/2306-5729/5/1/8
and 
https://doi.org/10.6084/m9.figshare.10267415.v1

**Comment by NicolasCadieux** [comment]
Is that what you are looking for?

**Comment by martinfleis** [comment]
Yes, figshare DOI is perfect. Thanks!

**Comment by NicolasCadieux** [comment]
This is the DOI for the article. 
https://doi.org/10.3390/data5010008
It's got over 4050 full read views and  1600 abstract views!?!? Weird... did not expect any attention to this article.  Anyway, if you can refer to that too, I think it could help people looking for examples.
Nicolas

**Comment by NicolasCadieux** [comment]
If you want a simplified version of my algorithm as an example, I could work on it. I could remove all the multithreading stuff, and try to clean it up a bit.

**Comment by martinfleis** [comment]
I am not going to include any algorithms, I just want to illustrate the conversion of geospatial data to networkx.(Multi)Graph and back.
