### ISSUE TITLE
PythonRandomInterface seed initialized to None 

### ISSUE THREAD

**Issue by mmghannam** [networkx/networkx#4336]
https://github.com/networkx/networkx/blob/087ed3b9ff9d92cf97a1d5a5cb3afd1c8b78298d/networkx/utils/misc.py#L341

When `None` is passed as seed, the code flow initializes to a `RandomState()` then sets it back to `None`. Maybe an else is missing?

**Comment by dschult** [comment]
That's clearly a bug.  I agree that it is likely a missing else statement.

But there is more of a problem here.  The try/catch surrounds the entire `__init__` function, so it is "try"ing to define the function -- not run it.  So, really the `import numpy` part of the code is broken.  The try should be inside the if statement and only around the import numpy statement.  AND there needs to be an else clause...

Thanks very much!!
