### ISSUE TITLE
Update plot_antigraph.py example to remove `_iter` in method name.

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#4338]
`def adjacency_iter(self)` should be `def adjacency(self)`
There may be other places (especially in the examples) where we've missed an ```_iter``` update.

**Comment by Erotemic** [comment]
I did a grep for "_iter" in examples and found: 

```
subclass/plot_antigraph.py:        nd_iter : iterator
subclass/plot_antigraph.py:                for n in self.nbunch_iter(nbunch)
subclass/plot_antigraph.py:    def adjacency_iter(self):
subclass/plot_antigraph.py:        adj_iter : iterator
```

It looks like `nbunch_iter` is still a thing? I did another grep in the repo root, and I didn't see anything else outstanding.
