### ISSUE TITLE
Question: set_node_attributes ignoring missing nodes

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#4341]
I wanted to double-check on the desired behavior of `nx.set_node_attributes` when `values` is a dictionary that contains nodes that are not in `G`.

Currently, `set_node_attributes` ignores any nodes that are in the `values` dict but not in `G`, e.g.

```python
>>> G = nx.Graph()
>>> G.add_node(0, data='foo')
>>> nx.set_node_attributes(G, values={0: 'bar', 1:'baz'}, name='data')
>>> G.nodes.data()
NodeDataView({0: {'data': 'bar'}})
```

Whereas if you tried to do the equivalent operation "by hand", you would get an exception:

```python
>>> G = nx.Graph()
>>> G.add_node(0, data='foo')
>>> G[0]['data'] = 'bar'
>>> G[1]['data'] = 'baz'
Traceback (most recent call last)
   ...
KeyError: 1
```

Ignoring the `KeyError` in `set_node_attributes` is currently not covered by the test suite, so I just wanted to double check that it is desired behavior before adding tests for it.

**Comment by dschult** [comment]
Good question...  The use-case envisioned was someone who has a large dict with attributes for nodes from many graphs (for example, the graphs are the component subgraphs of an original graph). Our idea is that they could use that same dict in a `set_node_attributes` function call and if it can't find the node it just ignores that node.  We certainly shouldn't add the node to the graph -- for that we have `add_nodes_from`.  But should we silently ignore, or loudly raise an error. I can see arguments both ways. The current code silently ignores.

**Comment by rossbar** [comment]
Thanks for the background info, it seems that the current behavior make sense given the above use-case. I've added tests & documentation examples for this behavior (the silent ignoring) in #4346 .
