### ISSUE TITLE
Networkx node ordering for undirected graphs

### ISSUE THREAD

**Issue by vymao** [networkx/networkx#4343]
How does Networkx order nodes when doing `G.edges` for undirected graphs? Is it always that the lower node index comes first (ie. so [1, 2] vs. [2, 1])?

**Comment by dschult** [comment]
The edges are ordered by the adjacency order of the underlying data structure.
So the 1st node increases in the same order that nodes were added to the graph.
Then the 2nd node on the edge appears in the order that edges incident to the 
1st node were added.  This order changed when python 3.6 changed how the order
in dicts changed. So prior to python 3.6 the order would be different.

**Comment by dschult** [comment]
I'll close this, but we'll still see posts here...
