### ISSUE TITLE
write_graphml with a MultiDiGraph is incompatible with Gephi

### ISSUE THREAD

**Issue by gboeing** [networkx/networkx#4347]
I'm not sure if this is an issue with NetworkX or with Gephi. If I save a MultiDiGraph as GraphML with NetworkX, I cannot open it in Gephi due to different handling of the edge `id` attribute between the two software packages.

```python
import networkx as nx
G = nx.MultiDiGraph(((0, 1, 0), (0, 1, 1), (1, 2, 0), (2, 0, 0)))
nx.write_graphml(G, './test.graphml')
```

Now if I open `test.graphml` in Gephi, it gives me multiple errors of: "Edge already exists id=0". It appears that NetworkX uses the edge `id` attribute to represent the Multi(Di)Graph `key` value, but Gephi expects it to be a unique identifier. Thus, only the first edge with `id` (ie, `key`) of 0 gets imported, and the rest are ignored as non-unique.

Versions: Python 3.8, NetworkX 2.5, Gephi 0.9.2

**Comment by dschult** [comment]
This makes sense to me.  My understanding is that the GraphML spec doesn't say what values the edge ids should be.
Gephi requires that ids are unique across the graph. NetworkX requires ids are unique within edges between a pair of nodes. 

What do about it?  One fix would be to create the NetworkX with your own edge keys -- instead of relying on the NetworkX default.  You could use `itertools.count` to generate an increasing sequence of edge ids and use them as edge keys.

I don't recall exactly how it works, but the `write_graphml` function has a `named_key_ids` boolean argument which when True uses an edge attribute named `attr.name` as the id when writing the graph. Here you would need to use a unique edge attribute value for each edge of the graph which could be done with something like:

```python
c = itertools.count()
edge_name = {e: next(c) for e in G.edges}
nx.set_edge_attributes(G, edge_name, "attr.name")
```
This is untested and I may be forgetting some subtleties ...

**Comment by gboeing** [comment]
@dschult interesting you mention that, because I had *thought* that was how it used to work, but AFAICT something has changed. So, previously I had been doing essentially what you suggest:

```python
import networkx as nx
G = nx.MultiDiGraph(((0, 1, 0), (0, 1, 1), (1, 2, 0), (2, 0, 0)))
uvk_range = zip(G.edges, range(len(G.edges)))
nx.set_edge_attributes(G, values=dict(uvk_range), name="key")
nx.write_graphml(G, './test.graphml', named_key_ids=True)
```

And assigning unique `key` attributes like that would result in unique `id` attributes in the graphml file. But that doesn't work anymore... now it results in:

```xml
<?xml version='1.0' encoding='utf-8'?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
  <key id="key" for="edge" attr.name="key" attr.type="int" />
  <graph edgedefault="directed">
    <node id="0" />
    <node id="1" />
    <node id="2" />
    <edge source="0" target="1" id="0">
      <data key="key">0</data>
    </edge>
    <edge source="0" target="1" id="1">
      <data key="key">1</data>
    </edge>
    <edge source="1" target="2" id="0">
      <data key="key">2</data>
    </edge>
    <edge source="2" target="0" id="0">
      <data key="key">3</data>
    </edge>
  </graph>
</graphml>
```

So, the `key` attribute gets added as a child `data` element under the `edge`, but the `edge` still has an `id` attribute value equal to the edge key itself (which seems to be separate from the new `key` attribute).

If I change that code to reflect your suggestion (`key` -> `attr.name`), I still get the same result. NetworkX does not appear to use the edge attribute named `attr.name` (or `key` either) as the edge id when writing the graphml:

```python
import networkx as nx
G = nx.MultiDiGraph(((0, 1, 0), (0, 1, 1), (1, 2, 0), (2, 0, 0)))
uvk_range = zip(G.edges, range(len(G.edges)))
nx.set_edge_attributes(G, values=dict(uvk_range), name="attr.name")
nx.write_graphml(G, './test.graphml', named_key_ids=True)
```

Generates:

```xml
<?xml version='1.0' encoding='utf-8'?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
  <key id="attr.name" for="edge" attr.name="attr.name" attr.type="int" />
  <graph edgedefault="directed">
    <node id="0" />
    <node id="1" />
    <node id="2" />
    <edge source="0" target="1" id="0">
      <data key="attr.name">0</data>
    </edge>
    <edge source="0" target="1" id="1">
      <data key="attr.name">1</data>
    </edge>
    <edge source="1" target="2" id="0">
      <data key="attr.name">2</data>
    </edge>
    <edge source="2" target="0" id="0">
      <data key="attr.name">3</data>
    </edge>
  </graph>
</graphml>
```

So we still have `id="0"` for every edge besides the one parallel edge, resulting in all edges with duplicate id values getting dropped upon Gephi import.

**Comment by MridulS** [comment]
Yeah it looks like networkx will always add the edge key irrespective of `named_key_ids` 
https://github.com/networkx/networkx/blob/8411e59ac840eecff618b20861f911ae1eecffed/networkx/readwrite/graphml.py#L537-L539

A temporary fix would be to make sure distinct keys are added while adding edges to the `MultiGraph` object.
``` python
c = itertools.count()
G = nx.MultiDiGraph(((0, 1, next(c)), (0, 1, next(c)), (1, 2, next(c)), (2, 0, next(c))))
nx.write_graphml(G, './test.graphml')
```
Generates:
```
<?xml version='1.0' encoding='utf-8'?>
<graphml xmlns="http://graphml.graphdrawing.org/xmlns" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://graphml.graphdrawing.org/xmlns http://graphml.graphdrawing.org/xmlns/1.0/graphml.xsd">
<graph edgedefault="directed">
<node id="0"/>
<node id="1"/>
<node id="2"/>
<edge source="0" target="1" id="0"/>
<edge source="0" target="1" id="1"/>
<edge source="1" target="2" id="2"/>
<edge source="2" target="0" id="3"/>
</graph></graphml>
```

**Comment by gboeing** [comment]
Thanks all. So here's what I came up with to resolve this... I had to do it a little differently than @MridulS recommends, because in my use case I have a pre-existing graph, rather than one I can initially create with unique keys.

```python
# G is a pre-existing MultiDiGraph with edge key values of 0 or 1
uvdk = zip(G.edges(keys=False, data=True), range(len(G.edges)))
uvkd = ((u, v, k, d) for (u, v, d), k in uvdk)
G_gephi = nx.MultiDiGraph(uvkd)
nx.write_graphml(G_gephi, filepath)
```

I'll leave this here in case anyone else comes upon the same challenge of MultiDiGraph GraphML compatibility between NetworkX and Gephi.

**Comment by dschult** [comment]
See also #3960          It looks like we should make selection of an attribute to be the edge `id` would be helpful.

**Comment by gboeing** [comment]
@dschult that would be helpful
