### ISSUE TITLE
Side effect when casting selfloop_edges to a list?

### ISSUE THREAD

**Issue by hayesall** [networkx/networkx#4352]
**Overview**: `nx.selfloop_edges` returns a generator expression. Casting this expression to a list appears to invoke a side effect that changes future computation.

**Version Info**: `networkx==2.5`

### Case 1: No casting

```python
import networkx as nx

gg = nx.MultiDiGraph()
gg.add_node("a")
gg.add_node("b")
gg.add_node("c")
gg.add_node("d")
gg.add_node("e")
gg.add_edge("a","b", weight=3)
gg.add_edge("a","d", weight=1)
gg.add_edge("c","a", weight=6)
gg.add_edge("d","e", weight=2)
gg.add_edge("d","c", weight=4)
gg.add_edge("e","e", weight=1)
gg.add_edge("a","b", weight=1)

loops = nx.selfloop_edges(gg)

# print(list(loops))

gg.remove_edges_from(loops)
print(gg.edges)
```

The output works as expected:

```console
[('a', 'b', 0), ('a', 'b', 1), ('a', 'd', 0), ('c', 'a', 0), ('d', 'e', 0), ('d', 'c', 0)]
```

### Case 2: Cast `selfloop_edges` to a list for printing

```python
import networkx as nx

gg = nx.MultiDiGraph()
gg.add_node("a")
gg.add_node("b")
gg.add_node("c")
gg.add_node("d")
gg.add_node("e")
gg.add_edge("a","b", weight=3)
gg.add_edge("a","d", weight=1)
gg.add_edge("c","a", weight=6)
gg.add_edge("d","e", weight=2)
gg.add_edge("d","c", weight=4)
gg.add_edge("e","e", weight=1)
gg.add_edge("a","b", weight=1)

loops = nx.selfloop_edges(gg)

# Cast the generator to a list for printing:
print(list(loops))

gg.remove_edges_from(loops)
print(gg.edges)
```

Output. Notice the selfloop is printed, but it is not actually removed from the MultiDiGraph.

```console
[('e', 'e')]
[('a', 'b', 0), ('a', 'b', 1), ('a', 'd', 0), ('c', 'a', 0), ('d', 'e', 0), ('d', 'c', 0), ('e', 'e', 0)]
```

**Comment by dschult** [comment]
That's correct. 
The iterator is exhausted when creating the list and does not restart when being used later.

If you want a list, use `loops = list(ns.selfloop_edges(gg))`.  If you want a tuple/set/etc, use `tuple()/set()` similarly.

**Comment by hayesall** [comment]
I see it now, thank you.

This feels a little counterintuitive, but more a weakness of Python itself.

It could be worth adding a 'Note' or 'Warning' to the docs for `selfloop_edges`
