### ISSUE TITLE
Keep data when computing the complement graph

### ISSUE THREAD

**Issue by leobouts** [networkx/networkx#4362]
complement(G, name=None) currently returns a new graph but does not propagate the edge/nodes data. 
This could be useful for link prediction or for someone that want to do things with edge additions algorithms.

**Comment by dschult** [comment]
Right -- the function does not copy that data because edge data doesn't exist for the new edges and node data is available in the original graph. It should be easy to copy the node data if you'd like with something like:
```python
# G is original and H is complement
nx.set_node_attributes(H, G.nodes)
```

**Comment by leobouts** [comment]
That does the trick for the node data! I thought it would be useful to get them instantly with an argument when computing the complement but it is as simple as this line.
