### ISSUE TITLE
Extremely slow calculation of numeric_assortativity_coefficient

### ISSUE THREAD

**Issue by vpozdnyakov** [networkx/networkx#4368]
This simple example takes a minute

```python
import networkx as nx
G = nx.path_graph(2)
G.nodes[0]['attr'] = 19999
G.nodes[1]['attr'] = 20000
nx.numeric_assortativity_coefficient(G, 'attr')
```

I did not check source code, but it looks like the algorithm calculates all possible combinations of integers between 0 and 20000. An equation in corresponding Newman's article is

![image](https://user-images.githubusercontent.com/12996098/99728876-2573b600-2acb-11eb-833a-0207c910e817.png)

and it is easy to see that only non-zero terms make sense.

**Comment by dschult** [comment]
Closed by #4851
