### ISSUE TITLE
Question: behavior of `node_list` kwarg in draw_networkx_edges

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#4374]
Like the other pylab drawing functions, `nx_pylab.draw_networkx_edges` currently has a `nodelist` keyword argument. It is not included in the `Parameters` listing of the docstring and so it's behavior is not well-defined. 

Naively, I would expect that any edges incident on a node *not* in the node list would not be drawn. For example, I would expect the following:

```python
>>> G = nx.path_graph(3)
>>> pos = {n: (n, n) for n in range(len(G))}
>>> nx.draw_networkx_nodes(G, pos, nodelist=[0, 1])
>>> nx.draw_networkx_edges(G, pos, nodelist=[0, 1])
```
to produce the following, without the edge (1, 2) since 2 was not included in the nodelist:

![expected](https://user-images.githubusercontent.com/1268991/99858963-8f2fa680-2b43-11eb-8292-bad080df0456.png)

Instead, the above code results in the following image:

![reality](https://user-images.githubusercontent.com/1268991/99859092-e3d32180-2b43-11eb-9d6c-c701c4766dd7.png)

Is this expected? Right now, the `nodelist` is only used internally in `draw_networkx_edges` to determine the size of the nodes. Either way, the parameter needs to be added to the docstring and the behavior tested - I just wanted to raise the question about what the desired behavior was in order to do so!

**Comment by jarrodmillman** [comment]
@rossbar I agree with you.  Edges should only be drawn if both endpoints are in the graph.

**Comment by dschult** [comment]
Maybe that keyword should be removed -- or replaced with edgelist?

If they want to draw edges that connect nodes listed in `nodelist` then they could draw the induced subgraph instead of the graph. `nx.draw_networkx_edges(G.subgraph(nodelist), ...)`

**Comment by rossbar** [comment]
The reason `nodelist` is included as an argument (originally) seems to be to handle the case when the user passes in a sequences of different sizes for `node_size`:

https://github.com/networkx/networkx/blob/28d3b930c6d6e5203afdb64e0bf4356b0026463c/networkx/drawing/nx_pylab.py#L724-L729

That's the only use of `nodelist` inside `draw_networkx_edges` as-is.

This could be rewritten to avoid needing `nodelist` at all. Given that no one seems to have ever complained about `nodelist` not working as expected, deprecating that parameter seems reasonable to me.

**Comment by rossbar** [comment]
Looking a bit more closely at this, removing `nodelist` as a parameter from `draw_networkx_edges` would also necessitate adding the nodelist checking logic in the "super" functions as well (e.g. `draw_networkx`, which calls `draw_networkx_edges` forwarding the relevant kwargs). 

One advantage of keeping `nodelist` as a parameter is that the kwarg-forwarding pattern still works without needing any changes to the other drawing functions. Deprecating `nodelist` seems like it will be a larger change than I had originally thought. LMK what you think!

**Comment by dschult** [comment]
I think we should leave it in...  
At the very least it reminds us that we need to rethink our drawing parameters.  I actually suspect drwaing will have a fairly major rewrite, probably after 3.0

For example, do we really need nodelist to get nodesize? Perhaps nodesize should be a dict so if doesn't separate nodes from data about nodes. Maybe all node data related to drawing should be contained in a single structure.  This sounds like it might be what the fiber-bundle approach being developed for matplotlib may evolve toward.

Perhaps best to leave it alone for now, especially if it requires more than simple removal.
