### ISSUE TITLE
Pickling Networkx's edge_subgraph raises an error

### ISSUE THREAD

**Issue by Thrayld** [networkx/networkx#4377]
Hi,

a few months ago I posted a [question](https://stackoverflow.com/questions/63801297/pickling-networkxs-edge-subgraph-raises-an-error) on stackoverflow about an error I received when I tried to pickle an edge_subgraph.

The question was not answered and I feel, it is time to bring it closer to the authors.

Thanks

**Comment by rossbar** [comment]
> But I would like to know what in networkx mechanics causes this error.

Your instincts form the SO post were correct - `nx.edge_subgraph` uses `nx.subgraph_view` internally, which creates a *read-only view* that refers to the original graph. The best place to look for more detail would be at the docs/code for `nx.subgraph_view`.

> Also, a more elegant way to sidestep this error.

Your solution from SO looks good. If you're looking for something that's more concise, you could try using the `copy` method, e.g.

```python
with open('subgraph.pkl', 'wb') as f:
    pkl.dump(subgraph.copy(), f)
```

The docstring for `nx.edge_subgraph` looks like it needs to be updated as `SubGraph View` is not the correct return type. Thanks for the report!

**Comment by rossbar** [comment]
I'm going to close this for now, hoping that the above answer is sufficient. If you'd like to follow up, please feel free to reopen this!
