### ISSUE TITLE
Memory Leak is reported in our CI pypy3 tests

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#4382]
Reported [here](https://github.com/networkx/networkx/pull/4379#issuecomment-732443978) by @jarrodmillman 

@jarrodmillman and @dschult have restarted an occasional failed CI text on MacOS pypy3
due to failure of the garbage collection test when copying a graph.

Manual interactive testing on pypy3 gives:
```
>>>> gc.collect()
>>>> [id(obj) for obj in gc.get_objects() if isinstance(obj,nx.Graph)]
[4517884656]
>>>> [id(obj) for obj in gc.get_objects() if isinstance(obj,nx.Graph)]
[4517884656]
>>>> G.copy()
<networkx.classes.graph.Graph object at 0x000000010c9fb0c0>
>>>> [id(obj) for obj in gc.get_objects() if isinstance(obj,nx.Graph)]
[4506759360, 4517884656]
>>>> [id(obj) for obj in gc.get_objects() if isinstance(obj,nx.Graph)]
[4517884656]
```

This is consistent, but the two nx.Graph type objects exist for longer if you don't use `gc.get_objects()`.
For example, I can print, set other variables, etc between `G.copy()` and  checking `gc.get_objects()` and there are 2 such objects. But as soon as I use `gc.get_objects()` the second nx.Graph object is collected.

The [pypy docs for garbage collection](https://doc.pypy.org/en/latest/gc_info.html) talk about how collection only occurs when `nursery` memory is depleted. So, even if a variable loses all it's references, it still might hang around for a while. I believe that is what we are seeing.

Any ideas for how to either change our test or find a way to fix it?

**Comment by rossbar** [comment]
Since PyPy handles garbage collection differently than CPython, the easiest thing to do would be to skip this test if on PyPy, e.g. something like:

```python
@pytest.mark.skipif(platform.python_implementation() == "PyPy")
def test_memory_leak():
   ...
```
