### ISSUE TITLE
Issue about "weighted closeness centrality"

### ISSUE THREAD

**Issue by knightas7** [networkx/networkx#4394]
Hi.
I don't know it has been dealt with yet, but I found a possible bug about "weighted closeness centrality"

It says nx.closeness_centrality(graph) returns inbound closeness_centrality and it worked as it.
But when you use nx.closeness_centrality(graph, distance='distance'), it returns outbound one.

I tried it with a element of distance which all has a value of 1. It gives me the exact centrality value as nx.closeness_centrality(graph).
But only with a reversed direction.

So, when I calculate inbound/outbound degree, weighted inbound/outbound degree, inbound/outbound closeness centrality, they all returns the same direction. But weighted closeness centrality returns the reversed one.

If Node1 has 0 inbound degree centrality, 0 weighted inbound centrality, 0 closeness centrality because it has no inbound connection while it has some value about outbound one, weighted closeness centrality returns some value in inbound one and 0 in outbound one.

Hope this helps to improving the module! Thanks!

**Comment by dschult** [comment]
See #3341 and #3362
Try updating your networkx version.

This short code is an attempt to implement what you wrote and it seems to work in recent versions.
```python
In [12]: import networkx as nx
In [13]: DG=nx.DiGraph([(1, 2)], weight=1)
In [14]: nx.closeness_centrality(DG, distance='weight')
Out[14]: {1: 0.0, 2: 1.0}
In [15]: nx.closeness_centrality(DG)
Out[15]: {1: 0.0, 2: 1.0}
```

**Comment by knightas7** [comment]
> See #3341 and #3362
> Try updating your networkx version.
> 
> This short code is an attempt to implement what you wrote and it seems to work in recent versions.
> 
> ```python
> In [12]: import networkx as nx
> In [13]: DG=nx.DiGraph([(1, 2)], weight=1)
> In [14]: nx.closeness_centrality(DG, distance='weight')
> Out[14]: {1: 0.0, 2: 1.0}
> In [15]: nx.closeness_centrality(DG)
> Out[15]: {1: 0.0, 2: 1.0}
> ```

Thanks dshult. I'm not sure if it was a issue in older version, but it works fine now. (I changed my computer set so I couldn't check the version of that). Again, it perfectly works. Thanks for the great module as always!
