### ISSUE TITLE
Documentation: Make classes AtlasView et. al. from networkx/classes/coreviews.py accessible from documentation

### ISSUE THREAD

**Issue by munichpavel** [networkx/networkx#4397]
Lest I seem ungrateful, I like networkx a lot, and rely on it for two of my main personal projects [fake-data-for-learning](https://github.com/munichpavel/fake-data-for-learning) and the WIP [clovek-ne-jezi-se](https://github.com/munichpavel/clovek-ne-jezi-se).

As I was trying to understand `AtlasView`s, I could find only examples in the documentation (see [this search](https://networkx.org/documentation/stable//search.html?q=AtlasView&check_keywords=yes&area=default#)), none of which pointed to the (well-documented) source code [networkx/classes/coreviews.py](https://github.com/networkx/networkx/blob/master/networkx/classes/coreviews.py).

I think the fix should just be a matter of tweaking how you have configured Sphinx to run.

**Comment by dschult** [comment]
Yes!  Thank you for this nudge. They should have been included in the sphinx docs and never were...
