### ISSUE TITLE
how to keep specific node in networkx

### ISSUE THREAD

**Issue by bigpapame** [networkx/networkx#4402]
My problem is i can remove all the node i don't want but i want to keep some specific node. Here's how i do it.
1.read gml into networkx
2.using this code to remove the website that i don't want and then write it into a new gml file
```import networkx as nx
G = nx.read_gml('test.gml')
for i in range(2000):
    for node in G.nodes:
        if "pu.edu.tw" not in node:
            G.remove_node(node)
            break
nx.write_gml(G,"finaltest.gml")
```
3.As you can see some part of the gml file, i successfully keep all 'pu.edu.tw' website
  ```
graph [
  directed 1
  multigraph 1
  node [
    id 0
    label "https://www.pu.edu.tw/"
  ]
  node [
    id 1
    label "https://alumni.pu.edu.tw/"
  ]
  node [
    id 2
    label "https://freshman.pu.edu.tw/"
  ]
  node [
    id 3
    label "https://tdc.pu.edu.tw/"
  ]
  node [
    id 4
    label "https://alcat.pu.edu.tw/"
  ]
  node [
    id 5
    label "https://www.secretary.pu.edu.tw/"
  ]
  node [
    id 6
    label "https://pugive.pu.edu.tw/"
  ]
 ```
4.The problem is when i try to draw this gml file with networkx, i got some nodes without egdes
![Figure_1](https://user-images.githubusercontent.com/56836973/100747642-49b18a00-341d-11eb-88a1-7d75bdce0db1.png)

5.And i found out the reason is that I deleted the link related to 'pu.edu.tw' so there are some egdes missing

I want to know how to not only remove the website i don't want and keep specific node that related to 'pu.edu.tw' so that edges won't missing. or some way to reconnect node. Thank you.

**Comment by MridulS** [comment]
You can use a subgraph view to filter out the nodes (not tested)
``` python
# Create a generator to find all the nodes which doesn't have a specific substring
def filter_nodes(G, node_name):
    for n in G.nodes:
        if node_name not in n:
            yield n

G = nx.subgraph(G, filter_nodes(G, "pu.edu.tw")
nx.write_gml(G, "finaltest.gml")
```

**Comment by MridulS** [comment]
>  keep specific node that related to 'pu.edu.tw' so that edges won't missing. or some way to reconnect node

ah my last comment won't solve this.

As this is a directed graph do you want keep all the nodes which are connected to `pu.edu.tw` nodes irrespective of direction or do you want to keep specific `node -> pu.edu.tw`/`pu.edu.tw-> node` connections.

**Comment by bigpapame** [comment]
I'm sorry english is not my native langunge, but i try to let you understand what my problem is. 
So if 'pu.edu.tw' is connected to non 'pu.edu.tw' website, the next node needs to be 'pu.edu.tw', so that non 'pu.edu.tw' won't be remove. But if the next node is also non 'pu.edu.tw' , then remove both.

**Comment by MridulS** [comment]
Can you check if the following code solves the issue for you?

``` python
G = nx.read_gml('test.gml')

def filter_edge(u, v, k):
    if "pu.edu.tw" in u or "pu.edu.tw" in v:
        return True
    return False

G = nx.subgraph_view(G, filter_edge=filter_edge)
nx.write_gml(G, "finaltest.gml")
```

**Comment by bigpapame** [comment]
It did't work. After running the code, gml file still stay the same

**Comment by bigpapame** [comment]
But the first code did as same as i did

**Comment by MridulS** [comment]
Can you try drawing the graph?

What does the following code outputs?
``` python
G = nx.read_gml('test.gml')

def filter_edge(u, v, k):
    if "pu.edu.tw" in u or "pu.edu.tw" in v:
        return True
    return False

G = nx.subgraph_view(G, filter_edge=filter_edge)

nx.draw(G, with_labels=True)
```

**Comment by bigpapame** [comment]
is this the output you want? or the graph?
Type: MultiGraph
Number of nodes: 1691
Number of edges: 3280
Average degree:   3.8794
False

**Comment by bigpapame** [comment]
the graph is basically unviewable
![Figure_3](https://user-images.githubusercontent.com/56836973/100757669-9d29d500-3429-11eb-93b7-66336384e939.png)

**Comment by MridulS** [comment]
ahh okay.

Let's try this one more time :)

Does the following code work for you?
``` python
G = nx.read_gml('test.gml')

def filter_edge(u, v, k):
    if "pu.edu.tw" in u or "pu.edu.tw" in v:
        return True
    return False

G = nx.subgraph_view(G, filter_edge=filter_edge).copy()
G.remove_nodes_from(list(nx.isolates(G)))
nx.write_gml(G, "finaltest.gml")

```

**Comment by bigpapame** [comment]
it did worked. let me check if the info is correct

**Comment by bigpapame** [comment]
Can you comment what each code mean? Thank you :)

**Comment by MridulS** [comment]
Sure :)

``` python
G = nx.read_gml('test.gml')

# Create a filter which returns True if the start node or the end node of
# an edge has "pu.edu.tw" in its name.
def filter_edge(u, v, k):
    if "pu.edu.tw" in u or "pu.edu.tw" in v:
        return True
    return False

# Create a subgraph view using the filter (we use copy() to create a copy
# as we want to modify this graph in the next step)
G = nx.subgraph_view(G, filter_edge=filter_edge).copy()

# isolates finds the nodes which aren't connected to any other node
# (degree = 0) and we remove all the nodes from the graph we filtered.
G.remove_nodes_from(list(nx.isolates(G)))


nx.write_gml(G, "finaltest.gml")
```

You can also read the documentation for [subgraph_view](https://networkx.org/documentation/stable//reference/generated/networkx.classes.function.subgraph_view.html) and [isolates](https://networkx.org/documentation/stable//reference/algorithms/generated/networkx.algorithms.isolate.isolates.html#networkx.algorithms.isolate.isolates)
