### ISSUE TITLE
Module 'networkx' has no attribute 'convert_matrix'

### ISSUE THREAD

**Issue by iuliacioroianu** [networkx/networkx#4420]
```
import networkx as nx
G = nx.from_pandas_edgelist(df, source='user_id1', target='user_id2', create_using=nx.Graph())
```
throws: *AttributeError: module 'networkx' has no attribute 'from_pandas_edgelist'*

```
G = nx.convert_matrix.from_pandas_edgelist(df, source='user_id1', target='user_id2', create_using=nx.Graph())
```
throws: *AttributeError: module 'networkx' has no attribute 'convert_matrix'*

I've upgraded to networkx 2.5, but I had the same issue in the previous version (hence the upgrade).

**Comment by rossbar** [comment]
Hmm I'm not able to reproduce this - how are you installing networkx?

**Comment by iuliacioroianu** [comment]
It may have had something to do with issues with the latest numpy version in Windows and cascading effects. Reverting to numpy 1.19.3 and reinstalling pandas and networkx fixed it for me. Thanks!
