### ISSUE TITLE
Support for disjunctive graph?

### ISSUE THREAD

**Issue by xplsek03** [networkx/networkx#4432]
I am about to solve FJSSP using oriented disjunctive graph with conjunctive/disjuncted graph arcs. The way I see it, MultiDiGraph structure would be suitable: is the simplex method (Dantzig) - I presume _network_simplex_ method - applyable in this case? Thanks.

**Comment by dschult** [comment]
MultiDiGraph structures are supported as of #1280 (about 6 years ago).
But it looks like the doc_string should be updated to reflect this!! 
I'm not sure what Dantzig actually refers to in terms of an algorithm, but there are [citations in the docs](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.flow.network_simplex.html) to papers describing the algorithm.

**Comment by xplsek03** [comment]
Dantzig's simplex algorithm = Simplex method. I just wanted to know if MultiDiGraph instance was supported, which it is. Thank you.

**Comment by dschult** [comment]
Good!   I'm going to leave this open as a reminder to change the docs for simplex_method (and maybe others in that module) to remove text stating an error is raised for multigraphs when it actually isn't true.
