### ISSUE TITLE
Incorret degree given by nx.degree() function

### ISSUE THREAD

**Issue by Kqiii** [networkx/networkx#4437]
Hi, 

I find that in a graph where some nodes have self-loops, the nx.degree() function would give wrong results for even nodes _without_ self-loops.

Please see the below screeshots for details, where I wrote some explanations (in orange) for my codes:

This screenshot shows that degree of the 5-th node (do not have self-loops) given by nx.degree() is not correct:
<img width="728" alt="Screen Shot 2020-12-09 at 3 08 38 PM" src="https://user-images.githubusercontent.com/38380341/101598378-082f6900-3a33-11eb-94ff-c821c87e3669.png">

This screenshot shows that this problem also occurs for some other nodes without self-loops:

<img width="482" alt="Screen Shot 2020-12-09 at 3 16 16 PM" src="https://user-images.githubusercontent.com/38380341/101598381-0a91c300-3a33-11eb-95c1-67e58e26a684.png">

Thank you!

**Comment by dschult** [comment]
You are assuming that the node is the same as the index number. That is not generally true. The sixth node does not have to be the node 5.

**Comment by Kqiii** [comment]
> You are assuming that the node is the same as the index number. That is not generally true. The sixth node does not have to be the node 5.

Hi,
Thank you for your prompt reply!

What really confused me is the summation of all node degrees. I find the summation of node degrees given by nx.degree() is notably larger than that by calculating the summation of the adjacency matrix, or by summing the neighborhood size of all nodes:
<img width="679" alt="Screen Shot 2020-12-09 at 5 00 37 PM" src="https://user-images.githubusercontent.com/38380341/101607943-16d04d00-3a40-11eb-81f9-9f53434b0886.png">

Could you please tell me why there is such a difference?

Thank you!

**Comment by MridulS** [comment]
neighbours != degree when looking at graphs with self loops.

``` python
In [2]: G = nx.Graph()

In [3]: G.add_edge(1, 1)

# Neighbours are the nodes adjacent to a node.
In [4]: list(G.neighbors(1))
Out[4]: [1]

# Degree of a node with a self loop is a special case and is counted twice.
In [5]: nx.degree(G)
Out[5]: DegreeView({1: 2})
```

**Comment by Kqiii** [comment]
> neighbours != degree when looking at graphs with self loops.
> 
> ```python
> In [2]: G = nx.Graph()
> 
> In [3]: G.add_edge(1, 1)
> 
> # Neighbours are the nodes adjacent to a node.
> In [4]: list(G.neighbors(1))
> Out[4]: [1]
> 
> # Degree of a node with a self loop is a special case and is counted twice.
> In [5]: nx.degree(G)
> Out[5]: DegreeView({1: 2})
> ```
Hi, 
Thank you for pointing out that each single self-loop is counted twice. But in my case, there are only 3 self-loops, so the difference between summing across the adj matrix and summing the outputs of nx.degree() show also be 3. But as can be seen from the previous screeshot, the difference is 42. Do you have any idea? 
Thank you!

**Comment by dschult** [comment]
You are still using the node index as if it is the node. When you set up `for node in range(len(G)):` you don't get the nodes in G necessarily. Use instead `for node in G:` or if you need the index and the node use `for idx, node in enumerate(G):`
The `nodewise_deg` variable apparently doesn't include all the nodes.

Perhaps do:  

```python
for idx, node in enumerate(G):
    if idx != node:
        print(f"index {idx} is not equal to the node {node} with degree {G.degree[node]}")
```

**Comment by Kqiii** [comment]
> You are still using the node index as if it is the node. When you set up `for node in range(len(G)):` you don't get the nodes in G necessarily. Use instead `for node in G:` or if you need the index and the node use `for idx, node in enumerate(G):`
> The `nodewise_deg` variable apparently doesn't include all the nodes.
> 
> Perhaps do:
> 
> ```python
> for idx, node in enumerate(G):
>     if idx != node:
>         print(f"index {idx} is not equal to the node {node} with degree {G.degree[node]}")
> ```

Thank you for your reply!
