### ISSUE TITLE
How to combine all same node by using networkx 

### ISSUE THREAD

**Issue by bigpapame** [networkx/networkx#4439]
How to combine specific node by using networkx ?

Here is part of my gml file
First thing is to read the gml file into networkx,
after reading the file, i want to combine all 'shu.edu.tw'  into one node
For instant：id 0 and id 4 have the same 
'shu.edu.tw' , i want to combine id 4 into id 0, same thing does the id 5 and 6, and all the edges have to make up to the previous one. 

``` 
graph [
  directed 1
  multigraph 1
  node [
    id 0
    label "https://www.shu.edu.tw/"
  ]
  node [
    id 1
    label "https://www.facebook.com"
  ]
  node [
    id 2
    label "https://www.instagram.com"
  ]
  node [
    id 3
    label "https://www.youtube.com"
  ]
  node [
    id 4
    label "http://cc.web.shu.edu.tw"
  ]
  node [
    id 5
    label "http://donate.web.shu.edu.tw"
  ]
  node [
    id 6
    label "http://english.shu.edu.tw"
  ]
```

**Comment by mrecachinas** [comment]
@bigpapame Take a look at [nx.contracted_nodes](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.minors.contracted_nodes.html). You'd probably do something like:

```python
G = nx.read_gml(...)
nx.contracted_nodes(G, "https://www.shu.edu.tw/", "http://cc.web.shu.edu.tw")
nx.contracted_nodes(G, "http://donate.web.shu.edu.tw", "http://english.shu.edu.tw")
```

If you wanted to do it based on checking the label, you'd just need to loop over `G.nodes`, something like:

```python
G = nx.read_gml(...)
for u in G.nodes:
    for v in G.nodes:
        if u != v and u.endswith("shu.edu.tw") and v.endswith("shu.edu.tw"):
            nx.contracted_nodes(G, u, v)
```

Note: `nx.contracted_nodes` also has a kwarg `self_loop=True/False` for keeping or getting rid of self-loops (i.e., by default, edges between `u` and `v` with turn into self-loops).

**Comment by bigpapame** [comment]
Will ```nx.contracted``` nodes merge the weight of the subsequent edge into the original edge?

**Comment by bigpapame** [comment]
After running this code, i got this error 
```TypeError: contracted_nodes() got an unexpected keyword argument 'copy' ```

**Comment by mrecachinas** [comment]
What version of `networkx` are you using? It looks like the `copy` keyword argument was added in 2.5. If you're using an older version of networkx, you can simply assign the returned contracted graph to a variable, like the following:

```python
G = nx.contracted_nodes(G, u, v)
```

**Comment by mrecachinas** [comment]
`nx.contracted_nodes` will merge the weights and edges for an `nx.Graph` (I believe the last contracted node will "win" -- i.e., override the edge weight); however, I think `nx.contracted_nodes` _will_ maintain all edges and associated weights for a `nx.MultiGraph`.
