### ISSUE TITLE
AttributeError: Can't pickle local object 'gridmap_to_nx.<locals>.filter_node'

### ISSUE THREAD

**Issue by ct2034** [networkx/networkx#4440]
I have created a subgraph_view (https://networkx.org/documentation/stable/reference/generated/networkx.classes.function.subgraph_view.html#networkx.classes.function.subgraph_view). 

Now I can not pickle it. This is probably because of the `filter_node`, which is obviously a function.
Do you have any idea how I can still pickle the `subgraph_view`?

**Comment by MridulS** [comment]
The `subgraph_view` should be pickleable. Where is the `gridmap_to_nx.<locals>.filter_node` part coming from?

Example:

``` python
In [2]: G = nx.erdos_renyi_graph(100, 0.2)

In [3]: def filter_node(n):
    ...:     return bool(n%2)
    ...:
In [4]: view = nx.subgraph_view(G, filter_node=filter_node)

In [5]: nx.write_gpickle(view, 'view.pickle')

In [6]: view_read = nx.read_gpickle('view.pickle')

In [7]: view_read.nodes() == view.nodes()
Out[7]: True

```

**Comment by ct2034** [comment]
Yeah, with your internal pickling function. 

But I am using https://pypi.org/project/cachier/. And that tries to just pickle the `subgraph_view` object as is. (To save it in the cache)

**Comment by MridulS** [comment]
`write_gpickle` just calls `pickle.dump`  https://github.com/networkx/networkx/blob/ef1c828560856c2dfd85c7892829202fa88a9970/networkx/readwrite/gpickle.py#L67 

not sure what `cachier` is doing underneath.

Try using `nx.subgraph()` instead of `nx.subgraph_view()` to create the subgraph?

``` python

In [2]: G = nx.erdos_renyi_graph(100, 0.2)

In [3]: def filter_nodes(G):
   ...:     return [node for node in G.nodes() if node%2 == 0]
   ...:

In [4]: nodes = filter_nodes(G)

In [5]: nx.subgraph(G, nodes)
```

**Comment by ct2034** [comment]
You are right. The problem was unrelated. The way I declared the `filter_node` as a static function tripped it up, I think. Now I made it a method of the surrounding object and all is fine.
Thanks for your help anyways.
