### ISSUE TITLE
How to click and drag nodes in Networkx?

### ISSUE THREAD

**Issue by caraevangeline** [networkx/networkx#4445]
Does anyone know how to click and drag nodes in Networkx? I referred to number of resources
Following is one of the python package that I tried but unfortunately it doesn't work
visJS2jupyter
Link: http://compbio.ucsd.edu/author/sbrosenthal/

Any help would highly be appreciated, thanks in advance!

**Comment by MridulS** [comment]
`networkx` doesn't natively support interactive drawing of graphs. You can look at other libraries like https://github.com/QuantStack/ipycytoscape or tools like D3.js (networkx graphs can be converted D3.js compatible JSON https://networkx.github.io/documentation/stable/reference/readwrite/json_graph.html)

**Comment by caraevangeline** [comment]
@MridulS Thank you!

**Comment by xiaohk** [comment]
https://networkit.github.io might be another option
