### ISSUE TITLE
group with high betweenness centrality

### ISSUE THREAD

**Issue by guyroznb** [networkx/networkx#4456]
hi,
I recently uploaded a PR #4435 improving the runtime of the group betweenness centrality using the algorithm in [1].
The authors presented in [2] two algorithms which find group of vertices with high GBC. One using heuristic search and approximated one using greedy algorithm. Both of which are based on the same basic idea as in [1]. 
The algorithms performed better on scale-free networks: heuristic search was faster and the greedy algorithm produced more accurate results. 
The running time of the heuristic algorithm is `O(n^k)` and the running time of the greedy algorithm is `O(n^3)`.

Does finding group with high GBC has any use in networkx. And if so, which algorithm should I implemented?

[1] https://journals.aps.org/pre/pdf/10.1103/PhysRevE.76.056709?casa_token=-CPVn5my8DgAAAAA%3AfUeszctJTQrKXnT_D7mQ8OsKwm5Fozx7F4s5LX7HKtlCRJC4dVMY2izzgxbNpQOUvgoF_UerEsG0gA
[2] 
https://www.researchgate.net/profile/Rami_Puzis2/publication/220308855_Finding_the_Most_Prominent_Group_in_Complex_Networks/links/0912f5081a757ed735000000.pdf

**Comment by dschult** [comment]
#4435 has been merged. Should this have been closed with that PR, or is there more to finish from this Issue?

I'm going to close this. If it should be reopened, post to it even though it is closed I will see it and reopn.
