### ISSUE TITLE
Accessing node attribute from update Graph

### ISSUE THREAD

**Issue by ntntnlstdnt** [networkx/networkx#4457]
Hello, 

I am having issues accessing attributes from a node that I updated using the set node attribute method. Below, is the exact that I ran to add the attribute to my node:  
`nx.set_node_attributes(G, {1: 1}, 'value')`

I ran `G.nodes(data=True)` to confirm update, output is `NodeDataView({1: {'value': 1}})`, but when I try to access the attribute using `G[1]['value']` it raise a `KeyError`. So I ran `G[1]` that outputs `AtlasView({})`, which I assume show that the `AtlasView` didn't receive the update. 

So is there an alternative way to get the node attribute's value OR a step to update to update the `AtlasView` as well?

**Comment by dschult** [comment]
You want `G.nodes[1]['value']`
The syntax `G[1]` returns the adjacency dict for the node 1. That is related to edges, not nodes.
Check out this [tutorial](https://networkx.org/documentation/stable/tutorial.html).

**Comment by ntntnlstdnt** [comment]
Thank you, @dschult! The tutorial answered my question
