### ISSUE TITLE
Wrong output for all_pairs_lowest_common_ancestor

### ISSUE THREAD

**Issue by caph1993** [networkx/networkx#4458]
I found a counterexample for the algorithm **all_pairs_lowest_common_ancestor** [(docs here)](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.lowest_common_ancestors.all_pairs_lowest_common_ancestor.html?highlight=lca).

The LCA of `(i,i)` must always be `i` regardless of the given DAG, but for the following DAG, it fails to meet this condition:

```python
import networkx as nx
from networkx.algorithms.lowest_common_ancestors import all_pairs_lowest_common_ancestor
print(nx.__version__)

G = nx.DiGraph()
G.add_nodes_from(range(5))
G.add_edges_from([(1, 0), (2, 0), (3, 2), (4, 1), (4, 3)])

for (i,j),a in all_pairs_lowest_common_ancestor(G):
    if i==j:
        assert a==i==j, f'Expected {i}. Got lca({i},{j}) = {a}'

```
Prints `2.5` and raises `AssertionError: Expected 0. Got lca(0,0) = 2`

You can check that the input is indeed a DAG manually, or like this:

```python
from networkx.algorithms.cycles import simple_cycles
assert list(simple_cycles(G))==[], 'Cycle found'
```

**Comment by dschult** [comment]
I can verify that this happens when there are two paths of sufficient length from a root to a single node. 
I could believe that the "corner case" of a long loop like this isn't being caught.  Any idea how to chase it down?

I suppose we could cut it off early by forcing any (i,i) pair to have ancestor i.

**Comment by caph1993** [comment]
I have no idea on how to chase it down. I am forcing `(i,i)` to have ancestor `i` in my code, but I don't really trust this simple fix because I don't understand the implementation in detail.

**Comment by dschult** [comment]
OK... Thanks for that info... and Thanks for reporting the bug!!

**Comment by rossbar** [comment]
Thanks for reporting this @caph1993 . This has been fixed in the switch to the naive LCA algorithm in #5736. I went ahead and added the case you reported to the test suite as an extra regression test.
