### ISSUE TITLE
line.py needs to be updated to use NX2.0 features

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#4459]
The line.py module in generators/  has a function that returns a function that handles multigraph edges and graph edges.
This is no longer needed because `G.edges` does exactly what this function returns. 

I suspect there are other aspects of the module that should be given a face-lift.

**Comment by rossbar** [comment]
So I think the reason it is structured this way (i.e. with the `_edge_func` indirection) is because of the difference in what is returned by the `MultiGraph.edges` when it is accessed as an attribute vs. when it is called as a method. For example:

```python
>>> G = nx.path_graph(5, create_using=nx.MultiDiGraph)
>>> G.edges  # accessed as an attribute, returns keys
OutMultiEdgeView([(0, 1, 0), (1, 2, 0), (2, 3, 0), (3, 4, 0)])
>>> G.edges(1)  # accessed as a method (with nbunch), no longer returns keys
OutMultiEdgeDataView([(1, 2)])
```

Is this expected behavior? The original issue would make more sense if the expected behavior of `G.edges()` were to return edges with keys in the case of MultiGraphs and MultiDiGraphs.

**Comment by dschult** [comment]
The attribute  `G.edges` returns 3-tuples `(u, v, key)` for MultiGraphs and has synonym `G.edges(keys=True)`. 
The method `G.edges()` returns 2-tuples `(u, v)` for MultiGraphs and has synonym `G.edges(keys=False)`.
It should not matter what the `nbunch` or `data` or `default` parameters are as far as whether the edge keys are reported.

Basically `G.edges` lets the class determines whether to use 2-tuples or 3-tuples.  
While `G.edges()` gives a universal return shape of 2-tuples. 

Another interface we thought about was to allow the `keys` parameter for non-multigraph classes. Then `G.edges(keys=False)` would work for both Graph and MultiGraph. At the moment, `keys` is not available for `Graph.edges` and we have this perhaps too subtle distinction between `G.edges` and `G.edges()`.   :}

**Comment by rossbar** [comment]
```python
>>>

> Basically G.edges lets the class determines whether to use 2-tuples or 3-tuples.
While G.edges() gives a universal return shape of 2-tuples.

Got it - so this *is* the way it's supposed to work :). In that case, the amount of "cleanup" in `line.py` is less than I had originally thought it would be. IMO It's definitely worth getting rid of the e.g. `_edge_func` wrappers in favor of direct calls to the `edges` property/method, but given the fundamental difference in what is returned by the property/method it will still require some logic for handling the graph/multigraph case.

**Comment by rossbar** [comment]
I just realized there is already an issue open for this - linking here for context: #4179
