### ISSUE TITLE
How large network can be created in networkx?

### ISSUE THREAD

**Issue by arman-zhumakhan** [networkx/networkx#4470]
I tried to create a network with about 200 million weighted edges but python file stopped running after around 90 million. Is it possible to create such a large network?
I don't know if it's because of the limit of my computer or networkx.
Do you have any suggestions on how to create a large network? Any optimizations? Maybe other packages or tools?

**Comment by MridulS** [comment]
A network with 200 million weighted edges wouldn't be possible with networkx unless you have a heavy duty server at your disposal :) You can look at tools like [graph-tool](https://graph-tool.skewed.de/), [SNAP](http://snap.stanford.edu/), [igraph](https://igraph.org/) or if you have access to a GPU [CuGraph](https://github.com/rapidsai/cugraph).

**Comment by dschult** [comment]
Just to be clear, the issue is memory. There is not a limit from a software perspective. 200 million weights takes about 1.6GB just for the weights. It's probably 8-10GB for the edge attribute dicts. Double that to overestimate node and adjacency info. Then you want to be able to do something with it... So, do you have 64-128GB of RAM?

**Comment by arman-zhumakhan** [comment]
> Just to be clear, the issue is memory. There is not a limit from a software perspective. 200 million weights takes about 1.6GB just for the weights. It's probably 8-10GB for the edge attribute dicts. Double that to overestimate node and adjacency info. Then you want to be able to do something with it... So, do you have 64-128GB of RAM?

So, it turns out that if I don't have enough RAM, it's impossible to create such a large network
