### ISSUE TITLE
Approximated Metrics - Diameter

### ISSUE THREAD

**Issue by atomassi** [networkx/networkx#4475]
Hi all,
In some cases, especially for large graphs, an exact result for a metric might not be necessary and a bound could be good enough.  
This might be the case for the *diameter*, which currently on networkx is present only as an [exact metric](https://networkx.org/documentation/stable//reference/algorithms/generated/networkx.algorithms.distance_measures.diameter.html).  

I think it might be worth to add functionalities to computed an approximated diameter (i.e., a lower bound).  
Good candidates might be the *2-sweep* [[1]](#1) and *2d-sweep* [[2]](#2)  for the undirected and directed case, respectively. 

In addition to the results on the paper, here some comparisons made on my laptop (2.9 GHz Dual-Core Intel Core i5) with a draft implementation of the *2-sweep* on undirected graphs considering the [Twitch Snap Dataset](http://snap.stanford.edu/data/twitch-social-networks.html).  
Time is expressed in seconds. The code used can be found [here](https://gist.github.com/atomassi/3ee4d827afc6f7f20e3a70bba97ed697).

| network    	| \|V\| 	|  \|E\|  	| Time (exact) 	| Value (exact) 	| Time (LB) 	| Value (LB) 	|
|------------	|:-----:	|:-------:	|:------------:	|:-------------:	|:---------:	|:----------:	|
| musae_ENGB 	| 7,126 	|  35,324 	|     166.7    	|       10      	|    0.06   	|     10     	|
| musae_RU   	| 4,385 	|  37,304 	|     63.2     	|       9       	|    0.03   	|      9     	|
| musae_FR   	| 6,549 	| 112,666 	|     255.5    	|       7       	|    0.11   	|      7     	|
| musae_DE   	| 9,498 	| 153,138 	|     602.7    	|       7       	|    0.18   	|      7     	|
| musae_ES   	| 4,648 	|  59,382 	|     101.9    	|       9       	|    0.07   	|      8     	|
| musae_PTBR 	| 1,912 	|  31,299 	|     17.5     	|       7       	|    0.02   	|      7     	|

If you think it might make sense to add this metric for the 2 cases, I can add a module (e.g., `networkx/algorithms/approximation/distance_measures.py`) with a proposed implementation and the tests for it.

## References
<a id="1">[1]</a> 
Magnien, C., Latapy, M. and Habib, M., 2009. *Fast computation of empirically tight bounds for the diameter of massive graphs*. Journal of Experimental Algorithmics (JEA), 13, pp.1-10.
<a id="1">[2]</a>
Crescenzi, P., Grossi, R., Lanzi, L. and Marino, A., 2012, June. *On computing the diameter of real-world directed (weighted) graphs*. In International Symposium on Experimental Algorithms (pp. 99-110). Springer, Berlin, Heidelberg.

**Comment by dschult** [comment]
This looks interesting, and you have chosen the correct module place and name. It would be great if you could put together a PR. Hook into the documentation with an entry at doc/reference/algorithms/approximation.rst. Hook into the namespace with an entry in `__init__.py`. If you have questions, let us know.
