### ISSUE TITLE
Does read_adjlist have a list version?

### ISSUE THREAD

**Issue by null-id** [networkx/networkx#4493]
Now I have a list variable (a list of strings just like a file) instead of file stream. How can I build a graph with some function like read_adjlist?

**Comment by dschult** [comment]
Try: [parse_adjlist](https://networkx.org/documentation/stable/reference/readwrite/generated/networkx.readwrite.adjlist.parse_adjlist.html)

**Comment by null-id** [comment]
That's what I need, and it works perfectly! Thank you!
