### ISSUE TITLE
Import EROOR

### ISSUE THREAD

**Issue by wongyufei** [networkx/networkx#4498]
import networkx as nx
  File "C:\Users\Administrator\anaconda3\envs\pytorch_37\lib\site-packages\networkx\__init__.py", line 61, in <module>
    import networkx.generators
  File "C:\Users\Administrator\anaconda3\envs\pytorch_37\lib\site-packages\networkx\generators\__init__.py", line 16, in <module>
    from networkx.generators.intersection import *
  File "C:\Users\Administrator\anaconda3\envs\pytorch_37\lib\site-packages\networkx\generators\intersection.py", line 5, in <module>
    from networkx.algorithms import bipartite
  File "C:\Users\Administrator\anaconda3\envs\pytorch_37\lib\site-packages\networkx\algorithms\__init__.py", line 79, in <module>
    import networkx.algorithms.tree
  File "C:\Users\Administrator\anaconda3\envs\pytorch_37\lib\site-packages\networkx\algorithms\tree\__init__.py", line 6, in <module>
    from .decomposition import *
  File "C:\Users\Administrator\anaconda3\envs\pytorch_37\lib\site-packages\networkx\algorithms\tree\decomposition.py", line 5, in <module>
    from networkx.algorithms import moral, complete_to_chordal_graph, chordal_graph_cliques
ImportError: cannot import name 'complete_to_chordal_graph' from 'networkx.algorithms' (C:\Users\Administrator\anaconda3\envs\pytorch_37\lib\site-packages\networkx\algorithms\__init__.py)

**Comment by dschult** [comment]
We'll need more information to track this down. Obviously this doesn't happen on most installs or we would have seen it and/or other issues about it would have appeared here. So, can you tell us how you installed it, what kind of system you are running on.  From just that error message it looks like networkx didn't get installed completely or else correctly.

**Comment by ocean-whale** [comment]
So I have this similar problem. 

### Current Behavior

I'm using python 3.7.7, an environment created with conda. 
I can successfully install the networkx package with no problem, but using `import networkx as nx` failed. 

The error msg is as following:
```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-d74fe3806494> in <module>
      1 import scipy.sparse.csgraph as sgh
----> 2 import networkx as nx

~/opt/anaconda3/lib/python3.7/site-packages/networkx/__init__.py in <module>
     59 from networkx.relabel import *
     60 
---> 61 import networkx.generators
     62 from networkx.generators import *
     63 

~/opt/anaconda3/lib/python3.7/site-packages/networkx/generators/__init__.py in <module>
     14 from networkx.generators.geometric import *
     15 from networkx.generators.internet_as_graphs import *
---> 16 from networkx.generators.intersection import *
     17 from networkx.generators.interval_graph import *
     18 from networkx.generators.joint_degree_seq import *

~/opt/anaconda3/lib/python3.7/site-packages/networkx/generators/intersection.py in <module>
      3 """
      4 import networkx as nx
----> 5 from networkx.algorithms import bipartite
      6 from networkx.utils import py_random_state
      7 

~/opt/anaconda3/lib/python3.7/site-packages/networkx/algorithms/__init__.py in <module>
     77 import networkx.algorithms.tournament
     78 import networkx.algorithms.traversal
---> 79 import networkx.algorithms.tree
     80 
     81 # Make certain functions from some of the previous subpackages available

~/opt/anaconda3/lib/python3.7/site-packages/networkx/algorithms/tree/__init__.py in <module>
      4 from .recognition import *
      5 from .operations import *
----> 6 from .decomposition import *

~/opt/anaconda3/lib/python3.7/site-packages/networkx/algorithms/tree/decomposition.py in <module>
      3 import networkx as nx
      4 from networkx.utils import not_implemented_for
----> 5 from networkx.algorithms import moral, complete_to_chordal_graph, chordal_graph_cliques
      6 from itertools import combinations
      7 

ImportError: cannot import name 'complete_to_chordal_graph' from 'networkx.algorithms' (/Users/huijing/opt/anaconda3/lib/python3.7/site-packages/networkx/algorithms/__init__.py)
```

**Comment by ocean-whale** [comment]
I have also tried to uninstall and reinstall with `pip` but no luck.

**Comment by ocean-whale** [comment]
Okay, so I was using Jupyter notebook when encountering the problem. So I stopped the jupyter notebook in the terminal, then uninstall and reinstall with `pip`, the error is gone :)

**Comment by rossbar** [comment]
It looks like you all are using conda: maybe this is a conda install and/or environment management issue? You can try the following to see if there's a problem installing networkx from conda in a fresh conda environment:

```
conda create -n nx-testenv python=3.7
conda activate nx-testenv
conda install networkx
python -c "import networkx; print(networkx.__version__)"
```

Please report if you have problems with the above.

**Comment by ocean-whale** [comment]
> It looks like you all are using conda: maybe this is a conda install and/or environment management issue? You can try the following to see if there's a problem installing networkx from conda in a fresh conda environment:
> 
> ```
> conda create -n nx-testenv python=3.7
> conda activate nx-testenv
> conda install networkx
> python -c "import networkx; print(networkx.__version__)"
> ```
> 
> Please report if you have problems with the above.

Thank you! I tried that with no problem. Actually, I think mine is due to package confliction. I specifically asked conda to install the 2.5 version of networkx, and then found that I have an old cameo package that asks networkx 1.9.1. Once I uninstall the cameo and reinstall the 2.5 version, everything worked out.

**Comment by rossbar** [comment]
I'm going to close this one as resolved - for additional installation issues, please open a new issue and share specific info on the errors you see + your installation environment.
