### ISSUE TITLE
Add graph class that tracks connected components (migrated from Trac #457)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#450]
Original ticket https://networkx.lanl.gov/trac/ticket/457
Reported 2010-11-07 by @hagberg, assigned to @chebee7i.

Add a class to incrementally maintain list of connected components.

Implementation in [1464/networkx].

**Comment by jfinkels** [comment]
It seems I can no longer access the patch from the old trac site at networkx.lanl.gov: https://networkx.lanl.gov/trac/attachment/ticket/457/networkx-components.patch redirects to networkx.github.io.

Can someone with access re-post the suggested patch?

**Comment by hagberg** [comment]
I think the code was removed in this commit
https://github.com/networkx/networkx/commit/43150a06b0b5a7a7fb6ade7e060e883f882643b0
I'm not enthusiastic about adding a class to do this.  But it could make a decent example of subclassing the Graph class to add additional functionality.

**Comment by jfinkels** [comment]
Well, one useful application of such a class would be for a smarter implementation of the Girvan-Newman algorithm: make a copy of the graph so that it tracks connected components, then repeatedly remove edges without having to manually recompute the connected components.

**Comment by hagberg** [comment]
True, but you could do that without a special class too.   Finding components isn't the expensive part of that algorithm.

**Comment by hagberg** [comment]
Closed due to inactivity
