### ISSUE TITLE
Max Clique in Directed Graph

### ISSUE THREAD

**Issue by atomassi** [networkx/networkx#4500]
Currently the [max_clique](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.approximation.clique.max_clique.html#networkx.algorithms.approximation.clique.max_clique) (approximated) function also works for directed graph

```python
>>> from networkx.algorithms.approximation import max_clique
>>> D = nx.DiGraph()
>>> D.add_edges_from([(1,2),(2,3),(3,1)])
>>> max_clique(G)
{2, 3}
```

Should this function be decorated as `not_implemented_for("directed")`?

**Comment by dschult** [comment]
It looks like all these functions should be decorated as undirected simple graphs. `ramsey.ramsey_R2()`, `max_clique`, `clique_removal`.

They should all have the decorators to match the function (from the clique module) `large_clique_size`. That is, two decorators: not_implemented_for('directed') and same for `multigraph`.

Thanks for this!

**Comment by atomassi** [comment]
In addition, I believe this also applies for `maximum_independent_set` (`networkx/algorithms/approximation/independent_set.py`)

**Comment by dschult** [comment]
Yes, those functions are all interrelated. They could probably be in the same module too, though that would require moving the docs to docstrings.
