### ISSUE TITLE
Edges from adjacency numpy array/matrix

### ISSUE THREAD

**Issue by vsocrates** [networkx/networkx#4511]
I have a node list and an adjacency matrix represented as a `np.ndarray`.

I've created a graph with nodes and attributes from the one-liner discussed in #4225 which seems to work great, but I can't find an easy way to integrate edges. 

Instead, I could create a graph using `from_numpy_array` but then adding node attributes becomes difficult. To bridge this gap and taking into account previous discussion, I think changing `add_weighted_edges_from` to accept an adjacency matrix or possibly a new function called `add_weighted_edges_from_numpy_array` may be useful. I imagine it'd look something like this: 

```
def add_weighted_edges_from_numpy_array(g, nodelist, adj_mat):
	weights = []
	i = j = 0
	for i in len(nodelist):
		for j in len(nodelist):
			weights.append((nodelist[i],nodelist[j],adj_mat[i,j]))

	g.add_weighted_edges_from(weights)
	return
```

I just wanted to know if such a function exists anywhere and I missed it. Otherwise I'd love to contribute it!

**Comment by dschult** [comment]
I think we provide this functionality -- `from_numpy_array` creates the graph with all relevant edges present, then `nx.relabel_nodes(G, dict(enumerate(nodelist)))` allows you to change from integer nodes to whatever nodes you want/need.

**Comment by vsocrates** [comment]
Using `nx.relabel_nodes` how would we add nodes that we already have attributes for?

**Comment by dschult** [comment]
The short answer is that `G.nodes[node][key] = value` is the direct way to update node attributes.
`G.nodes[node].update(attrs)` is another common idiom.

You can also use `add_nodes_from` if you prefer:   
`G.add_nodes_from((node, nodeattrdict(node)) for node in G)` 

Suppose you have the node attributes in a dict called `nodeinfo` keyed by node to an attribute dict (adapt to fit your data).
`G.add_nodes_from(nodeinfo.items())`

**Comment by vsocrates** [comment]
Sorry, I'm still a bit confused. My issue with `G.nodes[node][key] = value` is that you'd have to loop through all elements in `nodeinfo`. Even with `G.nodes[node].update(attrs)`, looping through all nodes would be required, and I figure `add_nodes_from` is implemented more efficiently under the hood.

Your second suggestion of `G.add_nodes_from(nodeinfo.items())` is the example I found at https://github.com/networkx/networkx/issues/4225#issuecomment-705956344. However, I guess my issue is once we've done that, how do we efficiently add edges into our graph. 

I appreciate the help and discussion. Thank you for taking the time!

**Comment by dschult** [comment]
I would personally add the edges first and then the node attributes -- only because the edges are coming from a numpy array. We're working on a nice way to add edges later -- at this time the best way to add them after the fact is to go through a separate graph -- something like (untested):
```python 
H = nx.from_numpy_array(adj_mat)
H.relabel_nodes(H, dict(enumerate(nodeinfo)), in_place=True)
G = nx.Graph()
G.add_nodes_from(nodeinfo.items())
G.add_weighted_edges_from(H.edges(data=True))
```

**Comment by vsocrates** [comment]
Got it, thanks! I'm still happy to contribute with making the edge addition easier, if you can point me towards the related issues. I'll close this for now though!

**Comment by dschult** [comment]
Once we get a nice way to generate edges and nodes (see 
[doc/developer/nxeps/nxep-0003.rst](https://github.com/networkx/networkx/blob/master/doc/developer/nxeps/nxep-0003.rst)  and 
 #4395 ) then you could add nodes and edges in one shot -- but you'd still have the step of relabeling the nodes from the numpy array.
