### ISSUE TITLE
simple_cycles() got 9000 cycles in a simple graph

### ISSUE THREAD

**Issue by adidasnike90** [networkx/networkx#4514]
Edges: 
OutEdgeDataView([('Conjunct_1', 'b', '-'), ('b', 'Conjunct_2', '-'), ('b', 'r', '+'), ('z', 'Conjunct_1', '+'), ('z', 't', '+'), ('n', 'Conjunct_1', '-'), ('n', 'h', '-'), ('Conjunct_2', 'c', '-'), ('c', 'l', '+'), ('c', 'n', '+'), ('c', 'o', '-'), ('c', 'f', '+'), ('c', 'z', '+'), ('e', 'Conjunct_2', '-'), ('e', 'o', '+'), ('e', 'd', '-'), ('d', 'Conjunct_2', '+'), ('d', 'c', '+'), ('d', 's', '-'), ('k', 'Conjunct_2', '-'), ('k', 'v', '+'), ('k', 'q', '+'), ('a', 'Conjunct_2', '+'), ('a', 'f', '+'), ('j', 'z', '-'), ('j', 'x', '+'), ('j', 'v', '+'), ('j', 'q', '-'), ('j', 'l', '-'), ('j', 'o', '+'), ('x', 'c', '-'), ('x', 'u', '+'), ('x', 'y', '-'), ('v', 'c', '+'), ('v', 'j', '+'), ('v', 'x', '-'), ('v', 't', '+'), ('v', 'l', '-'), ('q', 'v', '-'), ('q', 'e', '+'), ('l', 'f', '+'), ('o', 'w', '+'), ('o', 'd', '-'), ('o', 'a', '-'), ('o', 'y', '-'), ('o', 'f', '-'), ('t', 'o', '+'), ('t', 'i', '-'), ('t', 'm', '-'), ('t', 'r', '-'), ('s', 'w', '+'), ('s', 'c', '+'), ('s', 'f', '-'), ('s', 'd', '-'), ('s', 'n', '-'), ('w', 'b', '+'), ('w', 'o', '+'), ('w', 'v', '-'), ('y', 'e', '+'), ('y', 'b', '-'), ('y', 'q', '-'), ('y', 'u', '-'), ('y', 't', '+'), ('y', 'v', '-'), ('u', 'j', '+'), ('u', 'k', '-'), ('u', 'v', '-'), ('u', 'c', '+'), ('u', 'q', '+'), ('u', 'r', '-'), ('u', 'l', '+'), ('i', 'w', '-'), ('i', 'm', '-'), ('m', 'z', '-'), ('m', 'y', '-'), ('h', 'a', '+'), ('h', 'e', '+'), ('r', 'j', '+')])

Nodes
NodeView(('Conjunct_1', 'b', 'z', 'n', 'Conjunct_2', 'c', 'e', 'd', 'k', 'a', 'j', 'x', 'v', 'q', 'l', 'o', 't', 's', 'w', 'f', 'y', 'u', 'i', 'm', 'h', 'r'))

print(len(list(nx.simple_cycles(G)))):
9802

**Comment by dschult** [comment]
That sounds reasonable (I didn't look at your graph shape much though) -- 
How many did you expect?

**Comment by adidasnike90** [comment]
Sorry I made wrong expectation. It is possible to have thousands cycles for a graph with 78 edges. Thank you for your time! I will close this issue.
