### ISSUE TITLE
Consider reverting default dependencies back to optional

### ISSUE THREAD

**Issue by TomekTrzeciak** [networkx/networkx#4515]
#4190 promoted a number of optional dependencies to become required. This makes NetworkX much harder to use in projects that need to bundle it as part of the application (dependencies with compiled code like numpy and not easy to bundle).

**Comment by dschult** [comment]
Thanks for this comment. We need to make sure this is easy to do.
What is difficult about bundling code like numpy? It provides wheels for the installation.Can you describe more about your bundling process and where the difficulties arise?

**Comment by TomekTrzeciak** [comment]
By bundling I mean a single file [zipapp](https://docs.python.org/3/library/zipapp.html). This works only if there is no binary code involved ([zipimport](https://docs.python.org/3/library/zipimport.html) doesn't support loading it).

**Comment by dschult** [comment]
So the zipapp bundles the python code... Then you don't need to follow the requirements file right? You can bundle it without numpy or scipy. Obviously you can't use the functions that call routines from numpy and scipy. More important for you than the change in the requirements file are any new functionality we introduce that takes existing python based code and rewrites it to be faster using numpy or scipy.  Luckily for you we 1) usually keep around the pure python version, and 2) that process of finding out where to use numpy in the library is quite likely to be slow -- so you'll be able to bundle as a zipapp for many years (again, depending on which functions you actually use.)

What kind of application do you have where bundling with zipapp is effective and useful?

**Comment by TomekTrzeciak** [comment]
> So the zipapp bundles the python code... Then you don't need to follow the requirements file right?

Correct.

> You can bundle it without numpy or scipy. Obviously you can't use the functions that call routines from numpy and scipy. 

That is not a problem for me. I only need the basic graph data structures and topological sort ATM. NeworkX has nice APIs for working with graphs that I do not wish to reinvent.

> More important for you than the change in the requirements file are any new functionality we introduce that takes existing python based code and rewrites it to be faster using numpy or scipy.

My fear is rather that some change slips through and adds an unconditional import somewhere and therefore a hard dependency (it only takes one).

> Luckily for you we 1) usually keep around the pure python version,

That's good to know.

> and 2) that process of finding out where to use numpy in the library is quite likely to be slow -- so you'll be able to bundle as a zipapp for many years (again, depending on which functions you actually use.)

Do you have any way to ensure that this won't happen by accident, like a test that nx imports fine on python with just std libs + decorator?

> What kind of application do you have where bundling with zipapp is effective and useful?

We use nx to process and dump task execution graph into [Cylc workflow engine](https://cylc.github.io), but the requirement comes about due to running in a restricted environment with only a basic python installation available.

**Comment by jarrodmillman** [comment]
We test on PyPy without numpy, scipy, etc.

**Comment by TomekTrzeciak** [comment]
> We test on PyPy without numpy, scipy, etc.

Brilliant! I'm happy to close this issue.

BTW, why [setup.py](https://github.com/networkx/networkx/blob/3e12d76/setup.py#L194) has `zip_safe=False`? NetworkX seems to work just fine for me from the zip file (and imports much faster on nfs, cf. #2405).
