### ISSUE TITLE
Watts-Strogatts with variable neighbours.

### ISSUE THREAD

**Issue by Andre-Vitor** [networkx/networkx#4517]
![image](https://user-images.githubusercontent.com/21976913/103505314-b367ee00-4e38-11eb-883b-7d4feb44d940.png)
In the Watts-Strogatts model, shouldn't each node have a fixed amount of neighbours? Why the node 2 have only one neighbour and node 4 have 3 neighbours?

**Comment by dschult** [comment]
The Watts-Strogatz model rewires so the total number of edges remains the same. That means you are removing an edge whenever you add one.  The `newman_watts_strogatz_graph` adds edges and might be what you are intending.
Check out [these documents.](https://networkx.org/documentation/stable/reference/generators.html#module-networkx.generators.random_graphs)

**Comment by rossbar** [comment]
I'm going to close this one as resolved. If the issue persists or there are concrete suggestions on how the documentation could be improved, open a new issue or PR.
