### ISSUE TITLE
Naming of drawing routines

### ISSUE THREAD

**Issue by stefanv** [networkx/networkx#4521]
Currently, drawing routines are named `nx.draw_networkx_X` with X being `nodes`, `edges`, `labels`, etc.

The `networkx` part seems superfluous.  Also, would it make sense to move these into a submodule, `nx.draw`?

**Comment by dschult** [comment]
The `draw_networkx` is supposed to match (make a distinction from) the `draw_graphviz` function which was removed in 2016. So a renaming makes sense -- though we are looking to a larger refactoring and expansion of this code anyway so I'm not sure what the best timing is.

The module name is currently `nx_pylab.py` which should probably be changed to `nx_mpl.py`  OR we could change the name to `nx_draw` or something better.  I'm -1 on a module named `draw.py` as it is too generic and we can save the name `draw` for a function.

But, I'm not up on best practices for namespaces and modules/subpackages/etc. Any pointers to descriptions of how to do it better would be appreciated.

**Comment by stefanv** [comment]
If this is going to be refactored anyway, I'm going to close this for now since there isn't an immediately obvious route. Thanks for the context!
