### ISSUE TITLE
Attributes deleted in sparsifiers.spanner

### ISSUE THREAD

**Issue by Tobi0** [networkx/networkx#4526]
https://github.com/networkx/networkx/blob/b563423cd4359e10b3492d2fd6d0413d20d104b6/networkx/algorithms/sparsifiers.py#L70

Why do Nodes loose their attributes in the returned graph? 
It should be very easy to keep them.

**Comment by dschult** [comment]
Yes, very easy:  the next line should be `H.add_nodes_from(G.nodes.items())`

**Comment by dschult** [comment]
We've decided to not copy all attributes to the new graph in `spanner` and every similar function (I hope) in the library.
You'll need to copy the attributes if you want them:
```python
H = nx.spanner(G  10, weight='weight')
H.add_nodes_from([(node, G.nodes[node]) for node in H])
H.add_edges_from([(u, v, G[u][v] for u, v in H.edges])
```
