### ISSUE TITLE
weight in sparsifiers.spanner

### ISSUE THREAD

**Issue by Tobi0** [networkx/networkx#4527]
https://github.com/networkx/networkx/blob/b563423cd4359e10b3492d2fd6d0413d20d104b6/networkx/algorithms/sparsifiers.py#L12

Default "None" seems very arbitrary and useless. 
I suggest either remove it or change the default to "weight" (like in minimum_spanning_tree)

**Comment by dschult** [comment]
`None` is a useful way to check for whether someone set a value or if some default value should be assigned.  For weight this usually is used as a switch to turn off a weighted method. That seems to be the case here. `None` is a token to mean that no edge weight is used.

But later in the file here, `weight` is used on line 215 in an if clause `if not weight:` which means it cannot take any values that resolve to False when converted to bool.  For example, `weight` could be the value 1 but not 0.  Anyway, line 215 should be `if weight is not None:`.

It'd be even better if `weight` used the paradigm that `weight` uses for shortest _path, where it can be a string, or a function of the data dict for that edge or None.  See #4114

**Comment by Tobi0** [comment]
I'm just not understanding why weight could be None at all. If so, the edge weight is assigned to the id:
`residual_graph[u][v]["weight"] = (id(u), id(v))`
which is random and therefore the resulting graph will be arbitrary and not a usefull geometric spanner.

**Comment by dschult** [comment]
An unweighted graph can still provide a useful geometric spanner. 
If you want the spanner without weights, it is more efficient to ignore weights than to set them all to e.g. 1.
I don't know how much difference it makes, but for other routines it is significant. 
We often provide an unweighted version of algorithms alongside the weighted version.
(Also, spanners are not only used with geometric networks... So "useful" might mean "any" in other settings.)

**Comment by Tobi0** [comment]
Despite that, even after getting it working with weights, for my simple geometric network, there were no reasonable results.
I had a look into the paper the algorithm is referencing and found out that this is meant for **cluster** like networks only.
Also, after varying the strech factor and debugging, I saw that t<3 doesn't have any effect and according to the paper, stretch factor can only be **integer** t=2k-1= 3,5,7,...
The documentation is not very clear about this

**Comment by dschult** [comment]
What is it you are looking for?  That is what would "reasonable results" look like?

**Comment by Tobi0** [comment]
The goal is to connect a network graph, where distance from points over the network should be small, but also total edge length. Thus, obtaining the important edges and avoid those who connect two distant points, who are already connected through the network with only a bit longer path (->stretch factor). 
So I am looking more for algorithms like _Greedy_ Spanner or RNG.

**Comment by dschult** [comment]
My understanding is that this algorithm does what you want. Why do you say the results are not reasonable?

**Comment by dschult** [comment]
Reopen this issue if needed.
