### ISSUE TITLE
error when running next(communities_generator) on girvan_newman algorithm: module 'networkx' has no attribute 'selfloop_edges'

### ISSUE THREAD

**Issue by moyid** [networkx/networkx#4539]
I'm running community detection using girvan newman algorithm:

`from networkx.algorithms.community.centrality import girvan_newman

communities_generator = girvan_newman(nxG)

next(communities_generator)`

this produces the error:

`AttributeError: module 'networkx' has no attribute 'selfloop_edges'`

**Comment by dschult** [comment]
That looks like a namespace or installation problem. networkx certainly has an attribute selfloop_edges.

The import statement seems to be able to find `girvan_newman` so perhaps the installation is OK.
Do you have a variable, file or folder named networkx that is causing a networkx namespace collision?

Try: `networkx.__version__`
Try:  `networkx.selfloop_edges` as a command all by itself. 
And maybe `dir(networkx)`
Something is set up strangely.

**Comment by rossbar** [comment]
I agree with @dschult , this is very likely an installation/environment management issue. The discussion has been quiet for a while, so I'm going to close this. If the issue persists please feel free to reopen with up-to-date info on the current state of things.
