### ISSUE TITLE
networkx.readwrite.edgelist.read_weighted_edgelist seems to scramble edge start and end nodes

### ISSUE THREAD

**Issue by TobiasScheuer** [networkx/networkx#4543]
I created a .csv file with weighted edges using nx.readwrite.edgelist.write_weighted_edgelist(G, csvfile, delimiter = ',' ).
That worked perfectly, but if I try to read that same file some of the edges have their nodes swapped. And not all edges are read

I used the following code:
G1 = nx.DiGraph()
with open('./Edges.csv', 'rb') as f:
    G1 = nx.readwrite.edgelist.read_weighted_edgelist(f, delimiter=',')  

If I print(G1.edges) not only are half the edges missing but as said some nodes are scrambled.
I appended my full test file to replicate the issue. Commented out is also the code to create the same .csv file I am using.
I am using python 3.8 on a WSL ( Ubuntu 20) in a virtual environment with networkx 2.5

[test6.zip](https://github.com/networkx/networkx/files/5825700/test6.zip)

**Comment by MridulS** [comment]
Couple of points:
- There is no need to open and close the file, `read_weighted_edgelist` and `write_weighted_edgelist` will take care of that.
- The graph `G1` in your code is a normal `Graph` not a `DiGraph`, you need to provide `read_weighted_edgelist` with the argument `create_using=nx.DiGraph`

The following changes to your code should make this work.

``` python
G = nx.DiGraph()
weightededgelist = [[ ......... ]]
G.add_weighted_edges_from(weightededgelist)

# to write to edges.csv in the current directory
nx.write_weighted_edgelist(G, 'edges.csv', delimiter=',')

# read the edges.csv to a directed graph G1 and cast nodes as int instead of str
G1 = nx.read_weighted_edgelist('edges.csv', delimiter=',', nodetype=int, create_using=nx.DiGraph)
```

```
>>> G1.edges == G.edges
True
```

You can look at the [documentation here](https://networkx.org/documentation/stable//reference/readwrite/generated/networkx.readwrite.edgelist.read_weighted_edgelist.html#networkx.readwrite.edgelist.read_weighted_edgelist).

PS: the weights still need to converted from floats to int in the graph `G1`.

``` python
In [31]: G1[25][27]
Out[31]: {'weight': 7.0}

In [32]: G[25][27]
Out[32]: {'weight': 7}

# expected failure 
In [33]: G1.edges(data=True) == G.edges(data=True)
Out[33]: False
```

**Comment by TobiasScheuer** [comment]
Thank you, I thought passing the G1 as a DiGraph would make the option redundant, but obviously not. With your suggested fixes it worked, which shows there is no error in the function so I will close the issue.
Also your way to open the file is way simpler, so thank you for that as well :)
