### ISSUE TITLE
Random sampling from set has been deprecated in Python 3.9

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#4555]
Python 3.9 has deprecated calling `random.sample` on sets, so users will now see a warning if they do something like:

```python
>>> import networkx as nx
>>> G = nx.path_graph(25)
>>> import random
>>> random.sample(G.nodes(), k=3)
DeprecationWarning: Sampling from a set deprecated
since Python 3.9 and will be removed in a subsequent version.
[15, 1, 2]
```

It doesn't look like this will have an affect on `PythonRandomInterface`, but there are a few instances of the `sample(G.nodes(), **kwargs)` in the test suite which should be fixed.

**Comment by dschult** [comment]
Looks like it can also raise a TypeError with input `G`. The suggested fix is `sorted(G)`.

```
>>> random.sample(G, k=3)
TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).
```
