### ISSUE TITLE
Review tempfile usage in TestAGraph class

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#4564]
`TestAGraph` has an `agraph_checks` method that creates temporary files via `tempfile.mktemp` and `tempfile.mkstemp`. The docstring of the former says: `THIS FUNCTION IS UNSAFE AND SHOULD NOT BE USED.`, and the latter creates independent file name and file handle objects that don't work well with context managers, though the problem is only visible on Windows.

One solution would be to switch to one of the tempfile classes, e.g. `tempfile.NamedTemporaryFile`.

It would be best to address this after #4561 (or similar Windows CI testing) has been merged.

**Comment by stefanv** [comment]
#4593 provides a minimal patch; but we should probably remove all uses of `mkstemp` as well (and replace with `tempfile.NamedTemporaryFile` or `tempfile.TemporaryFile`).

**Comment by stefanv** [comment]
Well, scratch all that; Windows doesn't allow you to use the `name` attribute of a `NamedTemporaryFile` object more than once!  PR updated accordingly.

**Comment by rossbar** [comment]
Thanks for the info! I was hoping that we could use some sort of pattern that would work with a context manager instead of the explicit `os.close` and `os.unlink` calls, but it seems that such a solution isn't possible with the Windows constraint.

**Comment by stefanv** [comment]
I think we can write our own context manager and be fine.  It's not clear to me why the built-in one doesn't work correctly.

**Comment by danieleades** [comment]
> Well, scratch all that; Windows doesn't allow you to use the `name` attribute of a `NamedTemporaryFile` object more than once! PR updated accordingly.

you can expand on this?
does setting `delete=False` resolve this?

I thought i'd have another go at picking this up in #6554, but have fallen at the first hurdle. Any ideas where I might be going wrong?
