### ISSUE TITLE
AttributeError: module 'networkx' has no attribute 'is_path'

### ISSUE THREAD

**Issue by fluviotect** [networkx/networkx#4578]
unable to call 'is_path' or 'path_weight' functions

### Current Behavior

'is_path' returns an attribute error on a path I know to exist (confirmed via 'shortest_path')

### Expected Behavior
expecting a Boolean result from 'is_path' and an integer from 'path_weight'

### Steps to Reproduce
```
import networkx as nx
import random

G = nx.Graph()
nodeIDs_grp1 = [0,1,2,3,4,5,6,7]
nodeIDs_grp2 = [10,11,12,13,14]
nodeTypes = ["a","b","c","d","e"]
edge_lst_all = [(0,10),(10,1),(1,2),(2,11),(11,3),(2,12),(12,4),(1,13),(13,5),(5,14),(14,6),(5,7)]

G.add_nodes_from(nodeIDs_grp1, Type=nodeTypes[0])
G.add_nodes_from(nodeIDs_grp2, Type=nodeTypes[2])
G.add_edges_from(edge_lst_all)
for f,t in G.edges:
    G[f][t]['length']=random.randint(8, 100)

path_7_4 = nx.shortest_path(G,7,4)
```  

> [7, 5, 13, 1, 2, 12, 4]

nx.is_path(G,path_7_4) 

> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> <ipython-input-52-979930a25baf> in <module>
> ----> 1 nx.is_path(G,path_7_4)
> 
> AttributeError: module 'networkx' has no attribute 'is_path'

### Environment
jupyter lab 2.2.9
Windows 7 pro
miniconda

Python version: 3.7
NetworkX version: 2.5

### Additional context
I have also unsuccessfully tried:

`nx.classes.function.is_path`
and
`networkx.classes.function.is_path`

**Comment by rossbar** [comment]
My first guess is this is some sort of environment issue. Are you running jupyter lab locally? If so, are you sure you are running it in the environment in which you've installed networkx?

Can you try the following procedure:

```
conda create -n nx-testenv python=3.7
conda activate nx-testenv
conda install networkx
python -c "import networkx; print(networkx.__version__, networkx.is_path); "
```

Please report if you have problems with the above.

**Comment by dschult** [comment]
I agree with @rossbar It looks like a configuration problem. It is quite likely that your jupyter lab is running a different version of networkx than you think it is. The `is_path` function was only added in v2.5, so if the networkx version you are actually using is older this is what would happen.  The command `print(nx.__version__)` should tell you what is installed.

**Comment by fluviotect** [comment]
Cheers for replies.  Your hunches were correct.

@rossbar the first three items ran fine, but the fourth line threw an error. (apologies for not recording it). But your comment got me thinking and conda list indicated networkx was installed, but v2.4 which, after I saw @dschult message, made alot more sense. 

I've run the same code on a Win 10 machine with v2.5 and it executes properly.

Cheers
