### ISSUE TITLE
Incomplete result concerning degree_mixing_matrix and degree_mixing_dict

### ISSUE THREAD

**Issue by tinynahran** [networkx/networkx#4584]
### Current Behavior

I have a sparse, undirected and weighted network of 4200 nodes (projected from a bipartite graph). About 200 of the nodes are isolated. When I do degree_mixing_matrix, passing None for nodes or all nodes for nodes kwarg, I get a matrix of 370 by 370. 
I thought, maybe, only the giant component (about 3900 in size) is calculated? But when G=giant component, the returned matrix is still the same size.
Then I tried assortativity related functions. They return the same matrix. 
### Expected Behavior

Should return a matrix of assortativity/degree correlation of 4200. 
### Environment

Python version:
NetworkX version:
2.5

**Comment by dschult** [comment]
I think the degree mixing matrix should be a "number of different degrees" by "number of different degrees" matrix.

So if the max degree is 97 for you network then you get a 97x97 matrix.

**Comment by tinynahran** [comment]
> I think the degree mixing matrix should be a "number of different degrees" by "number of different degrees" matrix.
> 
> So if the max degree is 97 for you network then you get a 97x97 matrix.

Well, this may very well be the case here. So the function collapses my orginal all-inclusive matrix. Thanks, @dschult !!!!
