### ISSUE TITLE
Documentation and code in `floyd_warshall_numpy` are inconsistent

### ISSUE THREAD

**Issue by joelmiller** [networkx/networkx#4587]
### Current Behavior

Using `floyd_warshall_numpy` with a specified set of nodes will only find paths that are confined to that subset of nodes.  I'm not sure I agree with that choice, and certainly the documentation does not make it clear.

### Expected Behavior

Based on the documentation, I would expect it to find a path that starts at one node and ends at another, even if that path must go through additional nodes not in the provided list.

### Steps to Reproduce

https://stackoverflow.com/q/65771537/2966723

### Environment

Python version:  3.9
NetworkX version:  2.5

**Comment by dschult** [comment]
Can you explain why you thought the function would allow paths outside of the listed nodes? 
The current documentation says `The rows and columns are ordered by the nodes in nodelist.`

Looking further, the `nodelist` is passed to `to_numpy_array` which says in the doc_string:
```
When `nodelist` does not contain every node in `G`, the adjacency matrix is
built from the subgraph of `G` that is induced by the nodes in `nodelist`.
```
Perhaps we should copy that documentation to `floyd_warshall_numpy`.

**Comment by joelmiller** [comment]
But it's supposed to return:

>**distance** – A matrix of shortest path distances between nodes. If there is no path between to nodes the corresponding matrix entry will be Inf.     

**[note typo to->two]**

The fact that the documentation says the results showing distances between two nodes are ordered based on the nodelist only suggests to me that the order depends on the nodelist. 
 Not that the numerical value of the distances found will vary based on the nodelist, 

So in principle if I just want the distance between 2 nodes in the Graph, I could call it with the nodelist `[node1, node2]` and I should get the shortest path distance between the nodes.  There's nothing that suggests to me that we're only interested in the subgraph induced by the nodelist.  So I would expect `Inf` to only happen if there is no path in the Graph.  But in this case, I'll get `Inf` if they are not adjacent.

**Comment by dschult** [comment]
Unfortunately (or fortunately) this interpretation would preclude taking advantage of the dense matrix data structure that this function takes advantage of. Or, perhaps it could use the full matrix and then manipulate it after-the-fact to remove all computed path lengths except those between nodes in nodelist. I don't think that is a good design for this function.

But the current implementation makes it hard to track errors where users provide a subset of the nodes. The SO original post looks like such a difficulty. Our current implementation hides the fact that an induced subgraph has been created. That induced subgraph could easily be constructed by the user before passing into this function. I see little to be gained by providing an automated subgraph feature and it makes providing a nodelist error prone. 

I think the best solution is to raise an error if `nodelist` does not specify all nodes in G and no others.  One possible test of such could be:

```python
if nodelist is None:
    nodelist = list(G)
elif len(nodelist) == len(G) == len(set(nodelist)):
    pass
else:
    raise nx.NetworkXError("nodelist should provide an ordering of all nodes in G")
```

Does this make sense? Is it s good idea?

**Comment by joelmiller** [comment]
This would work.

An alternative would be to do the entire network, and then subsample the matrix based on the input nodelist.  However, this would change the output of the algorithm for the same inputs.  

I think it would be better for the algorithm to break than to change what it returns.  So I think I agree with your suggestion.

**Comment by dschult** [comment]
The users can subsample the rows and columns themselves...

**Comment by joelmiller** [comment]
agreed
