### ISSUE TITLE
Erroneous Tag Added To YAML

### ISSUE THREAD

**Issue by hcars** [networkx/networkx#4608]
### Current Behavior
The write yaml function is adding this tag to the graph that I output with it: 
`!!python/object:networkx.classes.graph.Graph`
When I try to read the graph back in with read yaml, I encounter the following error:
`yaml.constructor.ConstructorError: could not determine a constructor for the tag 'tag:yaml.org,2002:python/object:networkx.classes.graph.Graph'`

### Expected Behavior
The write_yaml code should produce an output that is read successfully by read_yaml; this is not the case currently.

### Steps to Reproduce
>>> import networkx as nx
>>> G = nx.Graph()
>>> G.add_edges_from([(0,1)])
>>> nx.write_yaml(G, "test.yaml")
>>> nx.read_yaml("test.yaml")

### Environment

Python version: Python 3.7.7
NetworkX version: NetworkX 2.4

**Comment by MridulS** [comment]
Could you also look at the pyyaml version on your machine?

``` python
>>> import yaml
>>> yaml.__version__
```

There are recent changes in the way yaml Loader works which could have broken this https://github.com/yaml/pyyaml/blob/master/CHANGES

The following code should work with  Python 3.7, NetworkX 2.4, PyYAML 5.1

``` python
import networkx as nx
G = nx.Graph()
G.add_edges_from([(0,1)])
nx.write_yaml(G, "test.yaml")
nx.read_yaml("test.yaml")
```

**Comment by hcars** [comment]
> 
> 
> Could you also look at the pyyaml version on your machine?
> 
> ```python
> >>> import yaml
> >>> yaml.__version__
> ```
> 
> There are recent changes in the way yaml Loader works which could have broken this https://github.com/yaml/pyyaml/blob/master/CHANGES
> 
> The following code should work with Python 3.7, NetworkX 2.4, PyYAML 5.1
> 
> ```python
> import networkx as nx
> G = nx.Graph()
> G.add_edges_from([(0,1)])
> nx.write_yaml(G, "test.yaml")
> nx.read_yaml("test.yaml")
> ```

My environment has 5.4.

**Comment by MridulS** [comment]
This has been fixed in the master branch and it should be out in the 2.6 release (https://github.com/networkx/networkx/commit/a6dd458a12ad8db161271e2271644803d4f29a96, https://github.com/networkx/networkx/issues/4569). Till then you would need to downgrade pyyaml to 5.1 for this to work.
```
$ pip install pyyaml==5.1
```

**Comment by dschult** [comment]
You can also use yaml directly:  
```python
import yaml
yaml.dump(G, path)  # write to a file
GG=yaml.load(path, Loader=yaml.Loader)   # read back in
```
