### ISSUE TITLE
k_components erroring without a clear reason

### ISSUE THREAD

**Issue by hcars** [networkx/networkx#4611]
While calling the k_components method on an acceptable input, I am receiving a strange exception.

### Current Behavior
I call k_components and receive the following:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<decorator-gen-484>", line 2, in k_components
  File "/home/hlc5v/.conda/envs/network_crawler/lib/python3.7/site-packages/networkx/utils/decorators.py", line 82, in _not_implemented_for
    return not_implement_for_func(*args, **kwargs)
  File "/home/hlc5v/.conda/envs/network_crawler/lib/python3.7/site-packages/networkx/algorithms/connectivity/kcomponents.py", line 128, in k_components
    k = nx.node_connectivity(B, flow_func=flow_func)
  File "/home/hlc5v/.conda/envs/network_crawler/lib/python3.7/site-packages/networkx/algorithms/connectivity/connectivity.py", line 341, in node_connectivity
    K = min(K, local_node_connectivity(G, v, w, **kwargs))
  File "/home/hlc5v/.conda/envs/network_crawler/lib/python3.7/site-packages/networkx/algorithms/connectivity/connectivity.py", line 209, in local_node_connectivity
    return nx.maximum_flow_value(H, '%sB' % mapping[s], '%sA' % mapping[t], **kwargs)
  File "/home/hlc5v/.conda/envs/network_crawler/lib/python3.7/site-packages/networkx/algorithms/flow/maxflow.py", line 306, in maximum_flow_value
    raise nx.NetworkXError("flow_func has to be callable.")
networkx.exception.NetworkXError: flow_func has to be callable.
```

### Expected Behavior
I expect it to output the components.

### Steps to Reproduce
Take the following edgelist:
```
0 1
0 2
2 3
5 6
0 5
6 2
```
Run the following your Python shell:
```
>>> import networkx as nx
>>> G = nx.read_edgelist("whatever_your_input_file_is")
>>> nx.k_components(G, .5)
```
### Environment

Python version: 3.7.7
NetworkX version: 2.4

**Comment by jtorrents** [comment]
Hi @hcars,

Please look at the documentation of the k_components functions:

https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.connectivity.kcomponents.k_components.html

This function accepts a positional argument, the graph G, and a keyword argument, flow_func, that has to be a function to perform the underlying flow computations. Such as the functions available in the flow module at networkx.algorithms.flow. You are passing a float as a second argument (why?), which is used as a flow_func. The error informs you that this argument has to be a callable.

As an illustration, here is an example on how you are supposed to use  the flow_func argument:

```python
In [1]: import networkx as nx

In [2]: from networkx.algorithms.flow import boykov_kolmogorov

In [3]: G = nx.karate_club_graph()

In [4]: kcoms = nx.k_components(G) # Uses edmonds_karp as a defalult flow_func

In [5]: kcoms_bk = nx.k_components(G, flow_func=boykov_kolmogorov)

In [6]: kcoms[4] == kcoms_bk[4]
Out[6]: True

In [7]: kcoms[4]
Out[7]: [{0, 1, 2, 3, 7, 8, 13, 30, 32, 33}]
```

**Comment by hcars** [comment]
https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.approximation.kcomponents.k_components.html?highlight=k_components

**Comment by hcars** [comment]
Alright, it seems that I confused the k_components from the top-level import with the one from the approximation section. Thank you.

**Comment by jtorrents** [comment]
Ok, I see the confusion. The functions from the approximation module are not imported in the top level namespace by default. You have to explicitly import them:

```python
In [8]: from networkx.algorithms import approximation as apxa

In [9]: kcoms_approx = apxa.k_components(G, 0.95)

In [10]: kcoms_approx[4]
Out[10]: [{0, 1, 2, 3, 7, 8, 13, 30, 32, 33}]
```
