### ISSUE TITLE
Deprecate `Ordered` graph classes

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#4614]
Since the next NetworkX release will drop support for Python 3.6, dictionaries should be ordered by default in all supported Python implementations moving forward (though it's worth double-checking that this is true for PyPy). Thus the `Ordered` graph classes will be redundant moving forward and can be deprecated for 2.6 in preparation for removal in 3.0.

This [SO post](https://stackoverflow.com/questions/39980323/are-dictionaries-ordered-in-python-3-6) compiles a lot of useful links re: the status of guaranteed insertion order for various Python versions. The conclusion is that insertion-order preservation is guaranteed for dictionaries from Python 3.7 onward.

**Comment by dschult** [comment]
The [What's New in Python 3.6 docs](https://docs.python.org/3.6/whatsnew/3.6.html#new-dict-implementation) documentation has a paragraph about ordered dicts. It states that this feature was pioneered by Pypy.
A [post on Pypy documentation](https://morepypy.blogspot.com/2015/01/faster-more-memory-efficient-and-more.html) announces this way back in 2015. So pypy started the whole ordered dict thing and will continue it.

**Comment by rossbar** [comment]
I read the linked post more carefully as well, and realized that though Python dictionaries now preserve insertion order, there are still some differences between default dictionaries and `OrderedDict`. The [OrdredDict docs](https://docs.python.org/3/library/collections.html#ordereddict-objects) provide a convenient list.

AFAICT, none of those differences directly impacts networkx, but I wanted to mention it just in case.

**Comment by rossbar** [comment]
> AFAICT, none of those differences directly impacts networkx, but I wanted to mention it just in case.

To verify this, I monkeypatched the `Ordered` classes to their non-ordered counterparts (i.e. `OrderedGraph = Graph`, `OrderedDiGraph = DiGraph`, etc.) and ran the test suite locally with Python 3.9. There was only one failure, and that was related to explicitly testing the graph type (i.e. `type(output) == OrderedGraph`).

Of course, this isn't a perfect guarantee that the deprecation avoids behavior changes, but it's more evidence than "AFAICT".
