### ISSUE TITLE
Add gallery example of using mpl to annotate a graph drawn with nx.draw

### ISSUE THREAD

**Issue by jarrodmillman** [networkx/networkx#4623]
NetworkX can draw graphs that can be annotated using the matplotlib drawing tools because the result of `nx.draw` is a matplotlib figure on which you can use matplotlib to draw anything else you'd like on top of the networkx drawing of the graph.

This idea is motivated by this SO post:
- https://stackoverflow.com/questions/66221054/3-dimensional-graph-lightgraphs-graphplot-julia-or-networkx-python

Someone could start with the example from the SO post; but it would be nice to have an example with more annotations and with nicer looking output.  (I suspect someone with more matplotlib skill than me would be able to make something very nice).   It also might be worth explaining a bit more about potential use cases in the example (perhaps by using real data where this type of annotation provides useful information about the underlying system).  If we add a nice example to the gallery, we should also add a link to the example to the SO post.

**Comment by sharwinbobde** [comment]
Id love to contribute to it with @SA-networkx

**Comment by jarrodmillman** [comment]
Excellent!  We are working to improve the quality of the gallery examples.  So it would be a good idea to briefly discuss what might be a good example.

Do you already have some specific ideas about what this example should be?  If so, could you quickly describe your plan?  If not, maybe it would be best to first identify a useful graph drawing from the literature.  For example, I am not sure representing nodes by vertical bars is the best thing.  (It may be.)

I am not certain what to do, so this is a list of possible ideas:

- Maybe we could use an example where there are several numerical attributes for each node.  Then the drawing could attempt to display those multiple attributes at the same time.  For example, one attribute could be represented with shades of gray; one attribute could be represented by the node diameter, and another attribute could be represented with the height of a vertical bar or column.  Maybe there is a better way to represent the magnitudes.  Ideas are welcome.
- Maybe the nodes could be icons.   For example, it could represent a network with computers and people (or something).  Then some nodes could be displayed with a person icon and other nodes could be represented by a computer icon.
- Maybe subsets of nodes could be grouped.  Often this is done with color grouped node with the same color.  However, you could also draw boxes, circles, or more custom shapes around nodes to group them.  Maybe these shapes could also include text labels.

Here are some example networks that may provide you with some ideas:
- https://www.frontiersin.org/files/Articles/445334/fgene-10-00294-HTML-r1/image_m/fgene-10-00294-g001.jpg
- https://f1000researchdata.s3.amazonaws.com/manuscripts/16899/39d3f946-bc5a-420d-ad5d-32ce7cdb768e_figure1.gif
- https://ars.els-cdn.com/content/image/1-s2.0-S240547121630360X-fx1.jpg
and
![screenshot](https://user-images.githubusercontent.com/123428/108386532-95283880-71c1-11eb-8232-194f978f9c49.png)

**Comment by sharwinbobde** [comment]
I and @ACwalker are currently working on a good general use case. 2D plot showing frequency histogram of feature and the network at the same time.
- The X-axis will represent a feature value. This will be fixed for every item/node. There will be an overlapped frequency histogram on the plot.
- The Y-axis will be used to project the nodes in a projection dimension to distribute nodes according to edge weights.

**Comment by sharwinbobde** [comment]
@jarrodmillman we believe something like this would indeed be a good demonstration.
![networkxissue](https://user-images.githubusercontent.com/31354242/108521793-62b73200-72cc-11eb-9209-c939e55c669b.png)
Something to visualize the features of data while also showing the network topology according to edge weights (using `kamada_kawai_layout()`) 

explanation: Here the feature vector is a gaussian distribution and the edges are picked from a uniform distribution and then we take the power of 3 (uniform_num^3), so the usage of kamada kawai algorithm is highly visible.

**Comment by jarrodmillman** [comment]
Thanks for sharing this plot!  It could be a useful addition to the gallery, but this is different than what I imagined as an example of using matplotlib to annotate a graph drawn with nx.draw.  I haven't looked at it carefully, so I may be missing something.  But it looks like the graph is draw directly with the nx.draw in one subplot and then a separate histogram is added in a separate subplot.  We already have an example of drawing a graph using nx.draw in one subplot and histograms in another:

https://networkx.org/documentation/latest/auto_examples/drawing/plot_degree.html#sphx-glr-auto-examples-drawing-plot-degree-py

This could still be a useful example to add, but I was hoping for some examples of graphs where matplotlib is used to add things to the subplot with the graph drawn by nx.draw.  For example, I was imaging something where the default nodes are replaced (e.g., vertical bars, icons, another graph).  Or additional information is overlaid on the subplot containing the graph drawn by nx.draw (e.g., some sort of "circling" or "grouping" of nodes/edges).  Please see the SO example or some of the figures I shared to see some examples of what I was expecting.

As I mentioned before, this could still be a useful example to add to the gallery.  I am not sure how you drew the picture, though.  Could you share the code that produced this image so we can see exactly you it is produced.  That will make it easier to see how this example differs from other examples in the gallery.

**Comment by ACWalker** [comment]
> This could still be a useful example to add, but I was hoping for some examples of graphs where matplotlib is used to add things to the subplot with the graph drawn by nx.draw. For example, I was imaging something where the default nodes are replaced (e.g., vertical bars, icons, another graph). Or additional information is overlaid on the subplot containing the graph drawn by nx.draw (e.g., some sort of "circling" or "grouping" of nodes/edges). Please see the SO example or some of the figures I shared to see some examples of what I was expecting.

We will have a look at doing this now. 

We'll also clean up the code for the above graph and share it so you can see if it is indeed a good unique example to add.

**Comment by sharwinbobde** [comment]
@jarrodmillman I have created a draft pull request to view the code. I changed the toy example a bit and added some annotations (vlines) to make things clearer.

**Comment by ACWalker** [comment]
Hi Jarrod, @sharwinbobde  and I have worked on a further example (https://github.com/networkx/networkx/pull/4633) using MPL to annotate

I think this may be closer to what you suggested initially.

**Comment by jarrodmillman** [comment]
Thanks for this contribution.  @rossbar or I will take a look and provide feedback.

**Comment by MridulS** [comment]
We now have a nice example at https://networkx.org/documentation/stable/auto_examples/drawing/plot_custom_node_icons.html#sphx-glr-auto-examples-drawing-plot-custom-node-icons-py thanks @sharwinbobde !

**Comment by sharwinbobde** [comment]
Oh wow that's great!
Thnx for letting me know 😇
