### ISSUE TITLE
Add graph sampling methods. E.g., Metropolis-Hastings random walk or weighted independent sampler (migrated from Trac #470)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#463]
Original ticket https://networkx.lanl.gov/trac/ticket/470
Reported 2010-11-17 by maciej.kurant, assigned to @hagberg.

Many real-life graphs are too big to be downloaded and analyzed in their full size. Examples are WWW or Online Social Networks. We can still learn something about such a massive graph by collecting a _sample_ of its nodes, and using it to _estimate_ whatever metric we are interested in. 

I attach a module with common graph sampling techniques and basic estimators compatible with them. They are rather simple (though the weighted versions may be a bit tricky) and you will find them in many textbooks. I think, it would be really useful to include this module in networkx. Please, let me know what you think. 

Supported sampling methods:
- uniform_independent_node_sample
- random_walk
- metropolis_hastings_random_walk
- weighted_independent_node_sample
- weighted_random_walk

Supported estimators:
- estimate_size
- estimate_mean

**Comment by hagberg** [comment]
See #1536
