### ISSUE TITLE
AttributeError: 'Graph' object has no attribute 'pred'

### ISSUE THREAD

**Issue by AprilSong0323** [networkx/networkx#4645]
I get the error in the title when I try to use the algorithm below, specifically the GM.is_isomorphic() function. https://networkx.org/documentation/stable/reference/algorithms/isomorphism.vf2.html

I had to call networkx from R  (using reticulate R package) because most of my project uses R packages. So, I have to convert an igraph object (the igraph package) to a networkx graph object.

I have tried "nx.from_pandas_adjacency" and "nx.from_pandas_edgelist" and plug the graph objects in the isomorphic mapping object listed above. I got the error shown in the title.

The tricky part is that the graph converted from igraph object works well for other algorithms in networkx, but could not work out for this one. GM.is_isomorphic() 

I would appreciate your help.

### Current Behavior

it raises an error:
Error in py_call_impl(callable, dots$args, dots$keywords) : 
  AttributeError: 'Graph' object has no attribute 'pred'

### Expected Behavior
 I expect it tells me whether G G1 are isomorphic or not. 

### Steps to Reproduce

A<-as_edgelist(subgraphs[[isomor[i,1]]])
    A<-pd$DataFrame(A,columns=c("from","to"))
    G<-nx[["from_pandas_edgelist"]](A,"from","to")
    B<-as_edgelist(subgraphs[[isomor[i,1]]])
    B<-pd$DataFrame(B,columns=c("from","to"))
    G1<-nx[["from_pandas_edgelist"]](B,"from","to")
X=nx$algorithms$isomorphism$DiGraphMatcher(G,G1)
    X$is_isomorphic()

### Environment

Python version: 3
NetworkX version: 2.5

### Additional context

<img width="440" alt="Screen Shot 2021-03-01 at 10 29 36 PM" src="https://user-images.githubusercontent.com/71058076/109592658-9c164b80-7add-11eb-80bf-c8984699582f.png">

**Comment by dschult** [comment]
This could be a problem in the R-calling-python aspect of your code.
Functions that don't ever look at the `pred` attribute of a graph will work fine if `pred` is somehow missing from the Graph object.  So 1st try a simple version in python. 2nd try the same simple version from R. 3rd find a way to list all attributes of a networkx graph object from your R session.

1st:
```
G=nx.path_graph(3)
G.pred
```

2nd:
```
G<-nx[["path_graph"]](3)
G$pred
```

3rd
```
G<-nx[["path_graph"]](3)
???
```
In python, your would use `dir(G)` to list all attributes. There must be a way to do that in R.

**Comment by rossbar** [comment]
It's been a while since there's been any discussion here, so I'm going to close it due to inactivity. If the issue persists (or better yet, a solution was found) please feel free to reopen with updated info.
