### ISSUE TITLE
Incorrect link to the paper in katz_centrality documentation

### ISSUE THREAD

**Issue by vpozdnyakov** [networkx/networkx#4648]
### Current Behavior

Link [2] in katz_centrality documentation directs to the incorrect paper: 'Universal Behavior of Load Distribution in Scale-Free Networks'

### Expected Behavior
Link [2] in katz_centrality documentation directs to the correct paper: 'A New Status Index Derived from Sociometric Index'

### Steps to Reproduce
Open the page https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.centrality.katz_centrality.html

### Additional context
I guess the correct link is https://link.springer.com/content/pdf/10.1007/BF02289026.pdf

**Comment by dschult** [comment]
Looks like that spurious link appears twice in that module/file.  Thanks!

**Comment by SumeshT** [comment]
Hi, I just started working on this issue. Searching the wrong link in the codebase does not give any result. Can u point from where I should start. I believe it should be in docs but couldn't find it. Thanks!
