### ISSUE TITLE
network_simplex is untested

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#4660]
The `networksimplex` module defines a single monolithic function `network_simplex` that currently is not explicitly tested. The function itself is very large, and includes internal definitions of quite a few other functions/generators. This will likely make it very difficult to write tests for the function. Since the `networksimplex` module defines only the one function, this also might be a candidate for a refactor, breaking out the internally-defined functions to (probably) private functions in the module, with their own unit tests. Doing so would likely greatly improve the robustness of the function.

See #4641 for additional details.

**Comment by Aufinal** [comment]
I tried to take a look at the code, and it is also quite unreadable: lots of one-letter variables, sometimes with unintuitive choices... It would maybe benefit from a full rewrite, but even understanding the existing code looks quite arduous.
