### ISSUE TITLE
Error in to_pydot if I use gradient color as fillcolor

### ISSUE THREAD

**Issue by horvatha** [networkx/networkx#4663]
### Current Behavior

Gradient color doesn't work with pydot. The code below will raise an error. This should be in quotation mark in the dot file.

E. g.

    import networkx as nx
    from networkx.drawing.nx_pydot import to_pydot
    
    G = nx.DiGraph()
    G.add_node("1.2", style='filled', fillcolor="red:yellow")
    pydt = to_pydot(G)
    print(pydt)
    pydt.write("x.png", prog="dot", format='png')

The Traceback is:

    Traceback (most recent call last):
      File "C:/Users/ArpadHorvath/ITRIX/etc/code_examples/graph_visualization/nx_pydot_stackover.py", line 10, in <module>
        pydt.write("x.png", prog="dot", format='png')
      File "C:\Users\ArpadHorvath\ITRIX\itrix\venv\lib\site-packages\pydot.py", line 1828, in write
        s = self.create(prog, format, encoding=encoding)
      File "C:\Users\ArpadHorvath\ITRIX\itrix\venv\lib\site-packages\pydot.py", line 1960, in create
        code=process.returncode,
    AssertionError: "dot" with args ['-Tpng', 'C:\\Users\\ARPADH~1\\AppData\\Local\\Temp\\tmp6hbe2sy5'] returned code: 1
    "dot" with args ['-Tpng', 'C:\\Users\\ARPADH~1\\AppData\\Local\\Temp\\tmp6hbe2sy5'] returned code: 1
    
    stdout, stderr:
     b''
    b"Error: C:\\Users\\ARPADH~1\\AppData\\Local\\Temp\\tmp6hbe2sy5: syntax error in line 2 near ':'\r\n"

### Expected Behavior

This should create:

    strict digraph  {
       "1.2" [fillcolor="red:yellow", style=filled];
    }

with quotation mark around "red:yellow" and create a file at the end.

### Steps to Reproduce

Run the code above.

### Environment

Python version: 3.6
NetworkX version: 2.5

**Comment by stefanv** [comment]
Thanks @horvatha, confirmed.

Also checked that graphviz handles `red` and `"red"` the same way, so the fix should simply be to add quotes in all cases.

**Comment by stefanv** [comment]
This is a bug in [pydot](https://github.com/pydot/pydot), not in NetworkX:

```
import pydot
n = pydot.Node('x', fillcolor='red:yellow')
print(n)
```

**Comment by stefanv** [comment]
I've reported the issue upstream; let's see what they say.

**Comment by MridulS** [comment]
@horvatha I'll close this issue for now. https://github.com/networkx/networkx/pull/5667 will atleast gracefully error out for cases where pydot isn't able to parse the node names correctly.

Thanks for the report!
