### ISSUE TITLE
Edge attributes not present: spanner

### ISSUE THREAD

**Issue by vsquareg** [networkx/networkx#4687]
Edge attributes in the original graph `G` are missing in the returned graph from the sparsifier.spanner algorithm implementation.

### Current Behavior

print(G[1][2]) -> `{'weight': 0.125, 'color': 'red'}`
print(H[1][2]) -> `{'weight': 0.125}`

### Expected Behavior

print(G[1][2]) -> `{'weight': 0.125, 'color': 'red'}`
print(H[1][2]) -> `{'weight': 0.125, 'color': 'red'}`

### Steps to Reproduce

```
import networkx as nx
from networkx.algorithms.sparsifiers import spanner

G = nx.Graph()
G.add_weighted_edges_from([(1, 2, 0.125), (1, 3, 0.75), (2, 4, 1.2), (3, 4, 0.375), (2, 3, 0.1)])
G[1][3]['color'] = "blue"
G[1][2]['color'] = "red"

# print(G.edges)
print(G[1][2])

H = spanner(G, 10, weight='weight')

# print(H.edges)
print(H[1][2])
```

**Comment by vsquareg** [comment]
Similar issue reported for node attributes #4526.

**Comment by dschult** [comment]
We've decided to not copy all attributes to the new graph in `spanner` and every similar function (I hope) in the library.
You'll need to copy the attributes if you want them:
```python
H = nx.spanner(G  10, weight='weight')
H.add_nodes_from([(node, G.nodes[node]) for node in H])
H.add_edges_from([(u, v, G[u][v] for u, v in H.edges])
```
