### ISSUE TITLE
Getting shape types from GraphML written by yEd

### ISSUE THREAD

**Issue by bra-fsn** [networkx/networkx#4693]
### Current Behavior

I have a GraphML file, written by [yEd](https://www.yworks.com/products/yed). NetworkX reads it just fine with `read_graphml()`, however, one very important information is missing: the type of the nodes (eg. `diamond`, `roundrectangle` etc).

### Expected Behavior

I would except to be able to get that information, because it's necessary for processing and understanding the exported graph.

### Steps to Reproduce

Create a graph with [yEd](https://www.yworks.com/products/yed) with various shapes. Export it to GraphML and load it back with NetworkX's `read_graphml()`. The shape types are not there.

### Environment

Python version: 3.8.5
NetworkX version: 2.5

### Additional context

yEd exports the shape type in the XML like this:
```XML
    <node id="n1">
      <data key="d5" xml:space="preserve"><![CDATA[lfx="red"
bela="2"]]></data>
      <data key="d6">
        <y:ShapeNode>
          <y:Geometry height="93.0" width="93.0" x="133.0" y="509.90625"/>
          <y:Fill color="#FFCC00" transparent="false"/>
          <y:BorderStyle color="#000000" raised="false" type="line" width="1.0"/>
          <y:NodeLabel alignment="center" autoSizePolicy="content" fontFamily="Dialog" fontSize="12" fontStyle="plain" hasBackgroundColor="false" hasLineColor="false" height="17.96875" horizontalTextPosition="center" iconTextGap="4" modelName="custom" textColor="#000000" verticalTextPosition="bottom" visible="true" width="29.16015625" x="31.919921875" xml:space="preserve" y="37.515625">RED
             <y:LabelModel><y:SmartNodeLabelModel distance="4.0"/></y:LabelModel>
             <y:ModelParameter>
               <y:SmartNodeLabelModelParameter labelRatioX="0.0" labelRatioY="0.0" nodeRatioX="0.0" nodeRatioY="0.0" offsetX="0.0" offsetY="0.0" upX="0.0" upY="-1.0"/>
             </y:ModelParameter>
          </y:NodeLabel>
          <y:Shape type="roundrectangle"/>
        </y:ShapeNode>
      </data>
    </node>
```

Reference: [yEd documentation](https://docs.yworks.com/graphml/schema-doc/http___www.yworks.com_xml_graphml/simpleType/shapeType.type.html)

**Comment by dschult** [comment]
The doc_string for `read_graphml`  says explicitly that for yEd files, the graphics information is discarded. 

The comes from the 11 year old commit https://github.com/networkx/networkx/commit/d2673781f826a97c25d0c388fe5e32039f0bfaa3

Is your solution generalizable to get all of the graphics information?  Would that be worth doing?

**Comment by bra-fsn** [comment]
> The doc_string for `read_graphml` says explicitly that for yEd files, the graphics information is discarded.
> 
> The comes from the 11 year old commit [d267378](https://github.com/networkx/networkx/commit/d2673781f826a97c25d0c388fe5e32039f0bfaa3)
> 
> Is your solution generalizable to get all of the graphics information? Would that be worth doing?

Well, that's not true anymore (see https://github.com/networkx/networkx/blob/4da254c095f8bd13610577974b749499e66f345b/networkx/readwrite/graphml.py#L917, at least I count this as a "graphics information"). :)
Getting all/most of the data is certainly doable, but I'm not familiar with NetworkX and wasn't sure about what to expect here, so wanted to do the minimum.

I can work on adding other node/shape related info if that helps to accept this change.

**Comment by dschult** [comment]
That would definitely be helpful as we don't have much yEd experience.
We could do PRs piecemeal referring to this issue if you like -- or put it all into one PR. 
Whichever is easier for you.

**Comment by bra-fsn** [comment]
@dschult, I've committed some changes to the PR, if you have time to take a look, that would be awesome.
