### ISSUE TITLE
Pypi badge for Windows testing still flags a broken Appveyor test 

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#4701]
On the pypi networkx page, one badge is "failed" -- it's the badge for appveyor.

Also, I think the copyright year needs to get bumped to 2021.

I guess that all this will get fixed for v2.6 release.

**Comment by jarrodmillman** [comment]
Yes, the PyPI site is a static copy of the README when 2.5 was released.  But the badge links to a dynamic page.   We may not run into that problem again, but I will look into pinning the badges to specific commits as part of the release process to ensure the badges don't change after we make a release on PyPI.

**Comment by dschult** [comment]
@jarrodmillman this issue might be something to keep in mind for this release.
- pinning badges to specific commits
- bumping copyright to 2021
