### ISSUE TITLE
Intersphinx mappings to NetworkX

### ISSUE THREAD

**Issue by PhilipVinc** [networkx/networkx#4704]
I am trying to link to networks documentation using inter sphinx mapping from our project's documentation.
I am using the standard link form of 
```
intersphinx_mapping = {
    "python": ("https://docs.python.org/3/", None),
    "networkx": ("https://networkx.org/doc/reference/", None),
}
```

but it fails with the error
```python
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'https://networkx.org/doc/reference/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 404 Client Error: Not Found for url: https://networkx.org/doc/reference/objects.inv
```

Are you publishing the mapping anywhere else?

**Comment by rossbar** [comment]
The objects.inv is available at the top-level of the documentation: https://networkx.org/documentation/stable.

[The intersphinx docs](https://www.sphinx-doc.org/en/master/usage/extensions/intersphinx.html#showing-all-links-of-an-intersphinx-mapping-file) provide an example to verify that the link is correct: `python -msphinx.ext.intersphinx https://networkx.org/documentation/stable/objects.inv`.
