### ISSUE TITLE
Bad TypeHint for degree

### ISSUE THREAD

**Issue by BUCKFAE** [networkx/networkx#4707]
### Current Behavior
PyCharm assumes that G.degree returns an int

### Expected Behavior
PyCharm knows that G.degree can return either an int or a nd_view

### Steps to Reproduce
```python
import networkx as nx
import matplotlib.pyplot as plt

if __name__ == "__main__":

    G = nx.Graph()

    G.add_nodes_from([1, 2, 3])
    G.add_edges_from([(1, 2), (2, 3)])

    # Getting degree of multiple Nodes
    print("Degree of nodes 2 and 3: {}".format(G.degree([2, 3])))

    nx.draw(G)
    plt.show()

```

### Environment
Python version: 3.9.2
NetworkX version: 2.5

### Image

![image](https://user-images.githubusercontent.com/33499592/112872980-4ecbd080-90c1-11eb-8689-f6347631b4c1.png)

**Comment by MridulS** [comment]
There are no `TypeHints` in NetworkX and we can't control what/how PyCharm infers them.
