### ISSUE TITLE
mismatch in the order of colours and edge widths 

### ISSUE THREAD

**Issue by DPcute** [networkx/networkx#4717]
The mismatch arises when the numbers of nodes and edges get larger, which I illustrate through the example attached.
i.e., where I asked the edge between A and B to be red, and B-C to be grey; it comes out that A-C is grey and B-C is red.
Thank you!
Best,
Darcy
[networkx_order_mismatch.zip](https://github.com/networkx/networkx/files/6248612/networkx_order_mismatch.zip)

**Comment by dschult** [comment]
The `df` (DataFrame) object has ordered columns which are not necessarily in the same order as the order of the edges stored in the `G_main` (Graph) object. You should add the 'colour' edge attribute to `G_main` so that it keeps the colour info with the edge. This will avoid the mismatch between the order of your two representations.

```python
G_main = nx.from_pandas_edgelist(df, 'from', 'to', edge_attr = ['count', 'colour'])
nx.draw_shell(...,  edge_color=G.edges.data('colour').values(), ...)
```

**Comment by DPcute** [comment]
> The `df` (DataFrame) object has ordered columns which are not necessarily in the same order as the order of the edges stored in the `G_main` (Graph) object. You should add the 'colour' edge attribute to `G_main` so that it keeps the colour info with the edge. This will avoid the mismatch between the order of your two representations.
> 
> ```python
> G_main = nx.from_pandas_edgelist(df, 'from', 'to', edge_attr = ['count', 'colour'])
> nx.draw_shell(...,  edge_color=G.edges.data('colour').values(), ...)
> ```

Hi Dan, thank you so much for helping out. What you said makes sense!
However, the code you added wouldn't run. I tried to fix it but failed.

`G_main = nx.from_pandas_edgelist(df, 'from', 'to', edge_attr = ['count', 'colour'])
figure(figsize=(20, 20))
nx.draw_shell(G_main, with_labels=True, edge_color = G_main.edges.data('colour').values())`
Gives Error: 'EdgeDataView' object has no attribute 'values'

However, If I run
`nx.draw_shell(G_main, with_labels=True, edge_color = G_main.edges.data('colour').values())`
It gives error: ValueError: Invalid RGBA argument: ('Cocoa.IFUS', 'Oats.CBT', 'lightgrey')

Could you tell me what's the correct syntax to generate this graph?


Finally, I identified another layers of mismatching: the data contained in the original DataFrame is different from the data contained in the Graph.

I illustrate these the incorrect codes and the second mismatch in the Jupiter notebook. 

Thanks,
Darcy
[mistach_2Apr2021.zip](https://github.com/networkx/networkx/files/6251536/mistach_2Apr2021.zip)

**Comment by dschult** [comment]
Sorry about the incorrect `values` syntax.
```python
nx.draw_shell(... edge_color = [c for u,v,c in G_main.edges.data("colour")])
```

**Comment by DPcute** [comment]
Thank you so much, Dan! This works.

Best,
Darcy
