### ISSUE TITLE
Patch for outdated releases (2.2)?

### ISSUE THREAD

**Issue by bblommers** [networkx/networkx#4719]
I'm workign on a project that still supports Py2, and our tests just started failing because of a new release of the `decorator` dependency. The new 5.0 release has dropped support for Py2, breaking some of our tests.

The last networkx release that supports Py2, 2.2, has an unbound dependency for `decorator`, always pulling in the latest version that now no longer supports Py2.

I realize it's a long shot, but would it be possible to release a patch for 2.2 with an upper bound for the `decorator` dependency?
```
decorator>=4.4
decorator>=4.4,<5; python_version<'3'
```

**Comment by dschult** [comment]
The decorator package released a buggy version 5.0.0, but it has already been updated to 5.0.1, so they are obviously on track to fixing it.  Just hold on a few hours and it should all be better.

**Comment by dschult** [comment]
It is not the Python 2 requirement that is breaking tests.  The tests are broken in Python 3 as well.

The problem seems to be in the v5 treatment of named positional arguments (optional arguments with default).
v4 put the default value into the tuple or args while v5 only includes the arguments explicitly provides.

v5.0.0, 5.0.1, 5.0.2 and 5.0.3 all released within 24 hours....   
perhaps other problems fixed, but this problem still remains.
[Issue 103](https://github.com/micheles/decorator/issues/104) tracks it on decorator

**Comment by bauman** [comment]
reminded me once again to be mindful when allowing my direct dependency chain to roll across a major version without second thought.

I suppose I should have always had decorator<5 in my requirements, same with the rest of them. 

While this one seems to be a departure from _expected_ behavior, I suppose they're allowed to introduce whatever backward incompatibility they want across a major tick.

**Comment by dschult** [comment]
Backward incompatibility shouldn't mean a loss of functionality though.  
As you stated, if named positional parameter's default values are gone from that API they should put somewhere else.
We'll see though.  It has been less than a day total and lots done in that day...  I guess next time they will/should make a release candidate and yell loudly for people to try it out. :}

**Comment by bauman** [comment]
maybe so, or maybe python tracks parameters not making sense semantically is the problem we are the ones relying on undocumented behavior.  

the maintainer had the good sense to know to bump major revision and my default assumption should have been major revisions aren't drop-ins.

Like I said, most of the responsibility is on me not thinking to pin to decorator<5 and pin to every other dependency to a known good major revision. 


Live and learn every day.  Seems like python still has fewer of these oops major rev updates than some of our peer scripting languages, so I guess that's good.

**Comment by jarrodmillman** [comment]
We no longer support NetworkX 2.2 or Python 2.  And it looks like the problem was handled downstream:
- https://github.com/spulec/moto/pull/3834
