### ISSUE TITLE
decorator 5.0.3 breaks nodes_or_number decorator

### ISSUE THREAD

**Issue by fxjung** [networkx/networkx#4722]
Various functionality of networkx is broken for `decorator==5.0.3`:
In [`networkx.utils.decorators.nodes_or_number`](https://github.com/networkx/networkx/blob/main/networkx/utils/decorators.py#L284), keyword arguments do not end up in `args` anymore, only in `kw`, 
which results in `IndexError`.

### Current Behavior
As a concrete example, `nx.generators.class.cycle_graph()` fails if graph order is given as a keyword argument. 
The same applies for other graph generation methods.

### Steps to Reproduce
```py
In [1]: import networkx as nx

In [2]: nx.__version__
Out[2]: '2.6rc1.dev0'

In [3]: nx.generators.classic.cycle_graph(5)
Out[3]: <networkx.classes.graph.Graph at 0x7f5ed6faceb0>

In [4]: nx.generators.classic.cycle_graph(n=5)
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-4-c2475efc656b> in <module>
----> 1 nx.generators.classic.cycle_graph(n=5)

anaconda3/envs/networkx/lib/python3.9/site-packages/decorator.py in fun(*args, **kw)
    212     else:
    213         def fun(*args, **kw):
--> 214             return caller(func, *(extras + args), **kw)
    215     fun.__name__ = func.__name__
    216     fun.__signature__ = inspect.signature(func)

networkx/networkx/utils/decorators.py in _nodes_or_number(func_to_be_decorated, *args, **kw)
    291         new_args = list(args)
    292         for i in iter_wa:
--> 293             n = args[i]
    294             try:
    295                 nodes = list(range(n))

IndexError: tuple index out of range

```

### Environment

Python version: 3.9.2
NetworkX version: [0740fe59](https://github.com/networkx/networkx/commit/0740fe59be894b2d10814cbc793d2b582adc2555)

### Additional context
Possibly related to #4718

**Comment by dschult** [comment]
It is even more complicated that keyword arguments ending up in `kw`.
The named positional arguments end up in `args` if specified by the user, but not if the user doesn't (relying on the default value). And they don't appear in `kw` either.  So the length of `args` is not consistent as provided by `@decorator`.  We will have to add logic to check it's length and update args -- or convince `decorator` to implement an option for this behavior.

**Comment by benedekrozemberczki** [comment]
GitHub actions is failing on 3 of my projects right now because of this.

**Comment by fxjung** [comment]
> It is even more complicated that keyword arguments ending up in `kw`.
> The named positional arguments end up in `args` if specified by the user, but not if the user doesn't (relying on the default value). And they don't appear in `kw` either. So the length of `args` is not consistent as provided by `@decorator`. We will have to add logic to check it's length and update args -- or convince `decorator` to implement an option for this behavior.

You are completely right. I have just tried and added a short fix for this in #4723. 
Not sure if this is too much of a stunt; but it seems to work.

**Comment by jarrodmillman** [comment]
I released NetworkX 2.5.1:
- https://pypi.org/project/networkx/2.5.1/

I also asked the folks at conda-forge to update as well:
https://github.com/conda-forge/networkx-feedstock/issues/21

**Comment by jarrodmillman** [comment]
Updated to 2.5.1 here:
https://github.com/conda-forge/networkx-feedstock

**Comment by dschult** [comment]
Decorator v5.0.5 now provides the v4 behavior and also allows the new behavior with a Boolean keyword argument. So no restriction on version should be needed anymore.
