### ISSUE TITLE
Wrong output from Steiner Tree 

### ISSUE THREAD

**Issue by i-am-tc** [networkx/networkx#4726]
Consider the following adjacency matrix of an undirected simple graph and terminal node list.

    A = np.array(
        [[0, 3, 0, 5, 2, 0],
         [3, 0, 5, 0, 2, 0],
         [0, 5, 0, 3, 0, 2],
         [5, 0, 3, 0, 0, 2],
         [2, 2, 0, 0, 0, 2],
         [0, 0, 2, 2, 2, 0]]
    )

term_nodes = [0,1,2,3]

### Current Behavior

Result gives a 4 node answer that sums to a weight value of 11. 

### Expected Behavior

Results should be a 6 node answer that sums to a weight of 10.

### Steps to Reproduce

def steiner_I():
    A = np.array(
        [[0, 3, 0, 5, 2, 0],
         [3, 0, 5, 0, 2, 0],
         [0, 5, 0, 3, 0, 2],
         [5, 0, 3, 0, 0, 2],
         [2, 2, 0, 0, 0, 2],
         [0, 0, 2, 2, 2, 0]]
    )
    term_nodes = [0,1,2,3]

    G = nx.from_numpy_array(A, create_using=nx.Graph)
    stree = approximation.steiner_tree(G, term_nodes)
    print(stree.size(weight='weight'))
    print('Should give answer for Steiner but its giving Min Span Tree')

    # Visualizing network
    isDraw = False
    if isDraw:
        nx.draw_networkx(G)
        ax = plt.gca()
        ax.margins(0.20)
        plt.axis("off")
        plt.savefig('Original Graph.png')
        plt.clf()

        nx.draw_networkx(stree)
        ax = plt.gca()
        ax.margins(0.20)
        plt.axis("off")
        plt.savefig('1st Steiner Tree.png')
        print('Drawing done!')
    return
steiner_I()

def approx_steiner_II():

    A = np.array(
        [[0, 3, 0, 5, 2, 0],
         [3, 0, 5, 0, 2, 0],
         [0, 5, 0, 3, 0, 2],
         [5, 0, 3, 0, 0, 2],
         [2, 2, 0, 0, 0, 2],
         [0, 0, 2, 2, 2, 0]]
    )
    term_nodes = [0,1,2,3]

    G = nx.from_numpy_array(A, create_using=nx.Graph)

    G_min_span_tree = nx.algorithms.tree.minimum_spanning_tree(G)

    print(G_min_span_tree.size(weight='weight'))
    print('Should give answer for Min Span Tree but its giving Steiner')

    # Visualizing network
    isDraw = True
    if isDraw:
        nx.draw_networkx(G_min_span_tree)
        ax = plt.gca()
        ax.margins(0.20)
        plt.axis("off")
        plt.savefig('Min Span Graph.png')
        plt.clf()

    return
approx_steiner_II()

### Environment

Python version: 3.6
NetworkX version: 2.5
decorator: 4.4.2
pycharm IDE, latest
Windows 10, latest

### Additional context

Using nx.algorithms.tree.minimum_spanning_tree(G) gives the answer for what would be the Steiner Tree. Using Steiner tree seem to be giving minimum spanning tree result. 

![image](https://user-images.githubusercontent.com/1066699/113584230-39284f00-965d-11eb-928d-56b84da5248b.png)

**Comment by boothby** [comment]
Hi, and thanks for submitting your first issue!  The Steiner Tree problem is NP-Hard, and the approximation algorithm is only guaranteed to be within a factor of an optimal solution.  From the docs,

> This algorithm produces a tree whose weight is within a (2 - (2 / t)) factor of the weight of the optimal Steiner tree where *t* is number of terminal nodes.

So while it is a somewhat unsatisfactory answer, the result you're getting is within that threshold.  The solution isn't wrong, per se, but sub-optimal.

As an experiment, you can double the edge weights among the nodes (0, 1, 2, 3).  This is a sufficient penalty to coax the algorithm into producing an optimal solution.

**Comment by rossbar** [comment]
I'm going to close this as resolved by @boothby 's excellent answer (thanks!)

Please feel free to reopen if you feel there is still something here that hasn't been addressed.

**Comment by i-am-tc** [comment]
OK! Thank you for the responses. =)
