### ISSUE TITLE
Snyk-High Vulnerability-Deserialization of Untrusted Data

### ISSUE THREAD

**Issue by fec-jli** [networkx/networkx#4728]
Ref: [https://app.snyk.io/vuln/SNYK-PYTHON-NETWORKX-1062709](https://app.snyk.io/vuln/SNYK-PYTHON-NETWORKX-1062709)

### Current Behavior
We get Snyk high Vulnerability warning, currently we are running networkx-1.11

### Expected Behavior
fix Snyk high Vulnerability

Python version: 3.7.9
NetworkX version: 1.11

### Additional context
We upgrade NetworkX to 2.5.1, still get Snyk-High Vulnerability-Deserialization of Untrusted Data.

**Comment by rossbar** [comment]
The offending code appears to be in the `nx_yaml` module which has been both patched (not sure if the vulnerability is the same - see e.g. #4548) and deprecated, to be removed in the next major release. I'm going to close this as duplicate/already resolved - please feel free to reopen with more specific info if there are still things to be addressed.
