### ISSUE TITLE
Review decorator dependency

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#4732]
Review the use of the `decorator` in NetworkX. It seems that nx currently only uses a [small subset of `decorator`](https://github.com/micheles/decorator/blob/949e8e0dbc251f3aa30546761f5dc220822d6e7e/src/decorator.py#L199-L272) and doesn't (currently) ever hit some of the code branches (e.g. for coroutines). Some things to keep in mind while investigating:
 - How does nx's use of decorator differ from what could be achieved with builtins like `functools.wraps`
 - Consider how any potential changes would impact import time

**Comment by boothby** [comment]
I've reviewed our decorators, and unless I missed something, they all take the form `f(x, y, z) -> f(x, g(y), z)` -- that is, we apply various functions to parameters before calling the decorated function.  In my head, I'm calling this process "chutneying", but in my code, I'm calling it "argmap"ping.

I don't see a good way to do this without inspecting the decorated function.  However!  By rolling our own, we can get away with using `inspect` once per base function (marginally speeding things up when multiple decorators are used -- I could brag about O(1) vs O(n), but I don't see us using a nest of decorators more than 2-3 deep).  I'm also calling `inspect.signature` instead of the more-expensive (and less-informative) `inspect.fullargspec`, so that should marginally improve matters.

With this approach, we can see a slight improvement in import time over the status quo.  The other consideration is call-time.  By collapsing the decorators, I'm able to generate wrapper code with a fixed call depth, which should reduce the call-time overhead of multiply-decorated functions.  Consider the below -- the three `foo` functions are equivalent.

```python
def original_foo(x, y):
    return x, y
def add_one(x):
    x = x+1

@argmap(add_one, 'y', 0) #quoted name / index syntax -- we'll call add_one on x and y before calling foo
@argmap(x=sum) #unquoted name syntax -- we'll use x = sum(x) before calling foo
def foo(x, y):
    return x, y

@argmap(add_one, 'y', 0)
def foo(x, y):
    x = sum(x)
    return original_foo(x, y)

def foo(x, y):
    x = sum(x)
    x = add_one(x)
    y = add_one(y)
    return original_foo(x, y)
```

I'll put a draft PR up in a few.

**Comment by boothby** [comment]
Phooey.  I worked my way up the file, and the `open_file` decorator is a sticky wicket because it's both an `argmap` and a `contextmanager`.  I feel that this should be approachable, but haven't got the trick yet.

**Comment by dschult** [comment]
If I understand correctly, this would make 
```python
@py_random_state(2)
def random_stuff(G, alpha, seed=None):
```
become:
```python
@argmap(nx.py_random_state, "seed")
def random_stuff(G, alpha, seed=None):
```

It might be easier to get `open_file` to work if you relax the generality to make the usage:
```python
@py_random_state("seed")
def random_stuff(G, alpha, seed=None):
```
and `py_random_seed` is come code decorated by `@argmap` to supply all but the crucial code that transforms inputs and handles outputs.  I don't know that `open_file` will work this way, but relaxing the generality of `argmap` might help (and make the ending interface easier to read).

**Comment by boothby** [comment]
In the current patch, I've simply re-implemented `py_random_state` as one-liner (not counting documentation, omitted here for brevity):

```python
def py_random_state(random_state_index):
    return argmap(create_py_random_state, random_state_index)
```

My goal thus far is to not intrude on existing decorations.  Last night, I got pretty much everything to work except for `open_file`.  The only tedium was in testing; my decorator is more fussy about generators, so some tests need a call to `next` to surface an exception.  And for what it's worth, as long as decorators are very well behaved, the mixing of argument-indices and keyword arguments isn't terribly painful.

The difficulty with `open_file` isn't merely that it needs to be a context manager... worse, it's a maybe-context-manager -- some inputs require cleanup, others don't.  I don't hate how this looks on the interface end of things, but the code generation is getting ugly.

```python
def open_file(arg):
    def _file_opener(path_or_file):
        ...
        if close_after_use:
            file.close_after_use = True
        return file
        
    @argmap.try_finally # <--- this is a 
    def _file_closer(file):
        if hasattr(file, 'close_after_use'):
            file.close()
    def decorate(func):
        with_opener = argmap(_file_opener, arg)(func)
        return argmap(_file_closer
    return lambda func: argmap(file_closer, arg)(argmap(file_opener, arg)(func))
    ```

**Comment by dschult** [comment]
The import time for decorator is faster between 4.4.x and 5.0.7.  
Here's the last line of output of `python -X importtime -c "import networkx"` which each installed.
Note: I have to run it multiple times and take the min to get systematic results. probably multitasking in background. 
```
decorator==4.4.2
import time:      1709 |     273803 | networkx  
decorator==5.0.7
import time:      1067 |     155814 | networkx
```
So, it seems that while decorator does impact import time, the new version is much faster than the old.
I also cloned #4739 to see if replacing decorator did better.  Though maybe if it was updated to include the newer wrap part of decorator it might be faster still.
```
#4739 armap branch
import time:      1440 |     186956 | networkx
```

**Comment by boothby** [comment]
I've read through the updated decorator source, and they are saving at import time, but I dislike what's they do at runtime.  Specifically, the call to `inspect.Signature.bind()` looks pretty heavyweight.

https://github.com/python/cpython/blob/823fbf4e0eb66cbef0eacb7e8dbfb5dc8ea83b40/Lib/inspect.py#L3028-L3164

I've updated my implementation to be lazy -- it makes a wrapper function which compiles the decorated function upon its first call, and then intrusively replaces the `__code__` object of the wrapper so the decorated function will be fast on all subsequent calls.

**Comment by dschult** [comment]
This provides about 10% faster imports than the new decorator. I don't have a good test yet for run-time differences.

We should remove/deprecate the `preserve_random_state` function.  It looks like it used to be defined in `test_algebraic_connectivity` and in the same PR it got moved to utils and also removed from use. :}  Classic!    #2681
Should I make a separate PR for that?

**Comment by boothby** [comment]
I don't mind nuking it here, but should we do a proper deprecation 'til 3.0?

**Comment by rossbar** [comment]
> I don't mind nuking it here, but should we do a proper deprecation 'til 3.0?

I agree that a deprecation is the way to go. I also prefer to just do that in a separate PR if for no other reason than I have a nasty habit of focusing on the wrong branch of bifurcated discussions during reviews :joy:

**Comment by boothby** [comment]
I did some runtime tests last night -- there's a fast path for `@open_file` when the filename is None -- and found that my lazy-compiled approach roughly breaks even with decorator 5.0.7 in 5 calls.  I started work on a simpler approach, which doesn't depend on inspect but requires direct access to the wrapped function's `__code__` object (which doesn't exist for all callables, but seems to work out in our codebase).  If that works out, I might post a second PR with it so we can debate merits.

**Comment by boothby** [comment]
Bad news all around.  The simpler approach is a touch too simple, and can't handle functions with defaults.  Also, I switched my test to use nodes_or_number, and the break-even point looks to be around 15 calls -- though, this is still acceptable in my mind, as the first-call overhead is around 0.35ms on my not-speedy laptop.

**Comment by boothby** [comment]
I made some progress on the defaults last night, at some cost to the simplicity of the approach, and it's looking promising in terms of performance -- but it won't/can't be as fast as the compiled approach in #4739, but it's faster than decorator-5.0.7 for both import time and call time.

**Comment by dschult** [comment]
The use of `inspect.signature.bind` in `decorator` is due to my request for being able to handle default arguments. `bind` is the way `inspect` provides access to default arguments. I'm glad to hear you've made progress on a better way for default arguments. 

My simple checks suggest that #4739 is already faster at import time than decorator 5.0.7.  But it sounds like you are working to beat both its import time and run time. Which (import or run time) is difficult to beat with 5.0.7?  Why is it fast yet doesn't do the fancy compiling and `__code__` monkey patching?  Or maybe I'm misunderstanding your results.

In any case, it's fun to watch and keep tabs on what you're developing. :}

**Comment by boothby** [comment]
In short, the approach in #4739 is to precisely duplicate the function signature, and simply copy over the `__defaults__` and `__kwdefaults__` -- this sacrifices some flexibility (like, we can't decorate builtins) to avoid calling `bind`.  The first-time call is quite slow, as it calls `inspect.signature` and later compiling code from text.    Subsequent calls are _fast_.

The newer approach (sorry, it's not in a state to PR yet) interrogates the `__code__` object and collects enough information to emulate a bare-bones `bind` with, I think, the same loss of flexibility in #4739.  The goal with this new approach is to make import time, and subsequent calls, all faster than 5.0.7, and also make first-time call faster than #4739, without the complexity of assembling and compiling function wrappers.  But, it's getting complicated and I might only be convincing myself that #4739 is okay

**Comment by alexchandel** [comment]
The `decorator<5` upper limit in 2.5.1 blocks upgrading `decorator` in installs with jupyterlab, ipython, retry, snooty-lextudio, & others.

**Comment by boothby** [comment]
Thanks, @alexchandel, after some back and forth, we're going to remove the decorator dependency for the 2.6 release.  Sorry for the inconvenience.

**Comment by dschult** [comment]
What do people think about changing nx 2.5.1 to depend on decorator <5,>=5.0.7?

**Comment by rossbar** [comment]
> What do people think about changing nx 2.5.1 to depend on decorator <5,>=5.0.7?

If it's easy to modify the release then :+1: but I don't think it'd be worth a lot of effort or e.g. a 2.5.2 release since 2.6 will be out soon and should completely eliminate this issue.
