### ISSUE TITLE
average_clustering() got an unexpected keyword argument 'trials'

### ISSUE THREAD

**Issue by DebarghaG** [networkx/networkx#4734]
Hey! 
I'm following [this](https://networkx.org/documentation/stable/_modules/networkx/algorithms/approximation/clustering_coefficient.html#average_clustering) and [this piece of documentation](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.approximation.clustering_coefficient.average_clustering.html#networkx.algorithms.approximation.clustering_coefficient.average_clustering)

### Current Behavior

On running : ```average_clustering(G, trials=1000, seed=None)```
```
TypeError                                 Traceback (most recent call last)
<ipython-input-24-7c16ef478e48> in <module>
----> 1 nx.average_clustering(G, trials=1000, seed=None)

TypeError: average_clustering() got an unexpected keyword argument 'trials'
```
However, running : ```average_clustering(G)```
It works as intended.

### Expected Behavior

average_clustering(G, trials=1000, seed=None) should be valid.

### Steps to Reproduce
Just make a Graph G and call nx.average_clustering(G, trials=1000, seed=None)

### Environment
Python version: 3.8.5
NetworkX version: 2.5.1

**Comment by MridulS** [comment]
By default [this](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.cluster.average_clustering.html?highlight=average_clustering#networkx.algorithms.cluster.average_clustering) `avergage_clustering` is imported in the nx namespace, so to access the one in the `approximation` module you would need something like
``` python
>>> from networkx.algorithms import approximation
>>> approximation.average_clustering(G, trials=1000, seed=None)
......
```

We should definitely add this as an example in the [function documentation](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.approximation.clustering_coefficient.average_clustering.html#networkx.algorithms.approximation.clustering_coefficient.average_clustering).

**Comment by DebarghaG** [comment]
Yeah, I guess that's a good addition to the documentation. Have made a PR.
