### ISSUE TITLE
find_cycle() does not find re-find a cycle if a component edge is removed and re-added

### ISSUE THREAD

**Issue by dmargul** [networkx/networkx#4750]
I have been trying to find, remove, and then rebuild cycles in a large network. I am unable to use find_cycle() to find the same cycle twice if I have removed and re-added a cyclic edge in between attempts.

### Current Behavior
get_edge_data() confirms that all component edges of should-be cycles exist. 
find_cycle() cannot find the cycle that should be closest to a source node

### Expected Behavior
I imagine I should be able to remove an edge, add it back, and be left with a graph that responds identically to a cycle finding algorithm.

### Steps to Reproduce
    import networkx as nx
    
    # Generate large graph and  look for closest cycle to source node '1'
    graph = nx.generators.random_graphs.erdos_renyi_graph(200, 0.01, seed=1, directed=True)
    test = nx.find_cycle(graph, source=1)
    print(test)

    # Confirm the same cycle is found first on same graph with same source node
    test = nx.find_cycle(graph, source=1)
    print(test)

    # Remove & re-add the first edge from the cycle that was found
    graph.remove_edge(test[0][0], test[0][1])
    graph.add_edge(test[0][0], test[0][1])

    # Look for closest cycle to source node '1'
    test = nx.find_cycle(graph, source=1)
    print(test)

    output:
    [(11, 0), (0, 14), (14, 30), (30, 77), (77, 132), (132, 44), (44, 6), (6, 48), (48, 32), (32, 71), (71, 11)]
    [(11, 0), (0, 14), (14, 30), (30, 77), (77, 132), (132, 44), (44, 6), (6, 48), (48, 32), (32, 71), (71, 11)]
    [(39, 54), (54, 2), (2, 67), (67, 104), (104, 12), (12, 85), (85, 107), (107, 11), (11, 184), (184, 50), (50, 39)]

### Environment
Python version: 3.8
NetworkX version: 2.5.1

**Comment by rossbar** [comment]
Just to clarify - is the issue that `find_cycle` doesn't find *the same* cycle after edge removal/insertion, or are there cases where a cycle is found prior to the edge removal/insertion, but *not* found afterwards?

**Comment by dmargul** [comment]
That was an important clarifier, and one which led to resolution of this in the NetworkX Google Group.  I have now learned that a node can be part of a cycle, but that this cycle may not be the first one discovered by find_cycle(). 

https://groups.google.com/g/networkx-discuss/c/IPz8pLKacm8
