### ISSUE TITLE
`eulerian_circuit` returns walk that uses the same edge twice when it should not.

### ISSUE THREAD

**Issue by dyc3** [networkx/networkx#4760]
It's possible for `eulerian_circuit` circuit to return a list of edges with duplicates if the duplicate usage does not have the nodes in the same order. In a euler circuit, each edge must be used exactly once.

### Current Behavior

It succeeds with a walk that uses the same edge more than once.

### Expected Behavior
It should fail when a euler circuit is not possible.

### Steps to Reproduce

```python
import networkx as nx
G = nx.cycle_graph(9)
G.remove_edge(0, 8)
G.add_edge(0, 3)
G.add_edge(4, 8)
G = nx.eulerize(G)
print(f"euler circuit: {list(nx.eulerian_circuit(G))}")
```
Output:
```
euler circuit: [(0, 3), (3, 4), (4, 8), (8, 7), (7, 6), (6, 5), (5, 4), (4, 3), (3, 2), (2, 1), (1, 0)]
```
Note that edge (3, 4) is used twice, but the second use is (4, 3). This is the same edge because the graph is undirected.
![image](https://user-images.githubusercontent.com/1808807/116125468-85cadd00-a693-11eb-962e-61beccd266c9.png)

### Environment

Python version: 3.9
NetworkX version: 2.5.1

**Comment by dschult** [comment]
The function `eulerize` returns a MultiGraph with a double edge (3,4,0) and (3,4,1).  Thus to be an eulerian_circuit it must traverse the (4, 3) span twice -- using each of these edges once.  Your drawing of the graph doesn't show both of those edges. Perhaps they are drawn on top of each other.

**Comment by dyc3** [comment]
You're right, my mistake. Thanks for the help!
