### ISSUE TITLE
Unable to get the same network from `soft_random_geometric_graph` on different machines

### ISSUE THREAD

**Issue by fabmazz** [networkx/networkx#4767]
I'm unable, with version 2.5 of networkx, to get the same graph from `soft_random_geometric_graph` (with same parameters of course, and same seed of random number generator)

A cause of the problem is the fact that `scipy.spatial.cKDTree` doesn't return the edges in the same order. A simple pass of "sorted(...)" solves the probelm

### Current Behavior
The generated graph has different edges on different machines, even with the same seed

### Expected Behavior
The generated graph should have the same edges, given the same seed

### Steps to Reproduce
```
import numpy as np
import networkx as nx

rng = np.random.RandomState()
rng.seed(4)
N =100
scale = 2
x_pos = np.sqrt(N)*rng.random(N)
y_pos = np.sqrt(N)*rng.random(N)
# for soft geometric graph generation
pos  = {i: (x, y) for i, (x, y) in enumerate(zip(x_pos,y_pos))}

rng = np.random.RandomState()
rng.seed(2)
G = nx.generators.soft_random_geometric_graph(N,4, pos=pos, seed=rng )
```
This snippet is sufficient to generate graphs with different edges on different machines, provided that scipy is installed

### Environment

Python version: 3.8, 3.7
NetworkX version: 2.5

**Comment by dschult** [comment]
Thanks very much for this -- I would have had a hard time identifying that there even was a problem here... :}

Two quick questions while it is fresh in your head and before I dive into it.  
1) You say that `sorted()` can fix the problem -- Did you sort the results of the `query_pair()` method, or later on, and would that work if the nodes (and thus the node-pairs) are not sortable? 
2) Do you have suggestions for how I can check that this is working or not? How different do you "two machines" have to be?

**Comment by fabmazz** [comment]
1. I have fixed the problem with sorting the edges that come from the cKDTree routine, as I have found that was this algorithm which gave different results on different machines.
2. I have found the problem on two different x86_64 machines, with same versions of the packages, but different versions of python (one 3.7, the other one 3.8). 
3. I have two different versions of scipy, one is 1.5.2 (python 3.7) and the other is 1.6.2 (python 3.8).

**Comment by dschult** [comment]
Sorted can work here...  The return value of sp.spatial.cKDTree(coords) is a **set** of 2-tuple edges.  So order is arbitrary and potentially different in different versions of Python.  But it is not a set of 2-tuples of **nodes**, it is a set of 2-tuples of **node_indexes**.  The index is the index within the list `coords` used as input.

So, there are integers and can be sorted before what is now the next line where they get mapped to nodes.
All we need is to add `sorted` inside the list comprehension where we loop over `edge_indexes` (line 55).

Is this where you had it?  Maybe I should just say:  Your suggestion looks like it will work fine!!  I'd love it if you could make a PR, or indicate if this fix matches what you were suggesting.     Thanks!

**Comment by fabmazz** [comment]
Yeah, I wrapped the result of sp.spatial.cKDTree(coords). If you can tell
me on which branch I have to commit the change, I will gladly make a Pull
Request. (Branch master doesn't seem to have the call to cKDTree)

Il Gio 29 Apr 2021, 20:12 Dan Schult ***@***.***> ha scritto:

**Comment by dschult** [comment]
Hmmm...   We changed the branch name to `main` so there shouldn't be a `master` branch anymore.
If you make a fork into your set of repositories you can name the branch whatever you want and then
create a pull request from that branch to networkx/main
I can do it pretty easily so if your setup isn't working smoothly just say so and I'll make it and ask you to check it.

**Comment by fabmazz** [comment]
I have successfully made a pull request, I think. This one #4768

**Comment by dschult** [comment]
It worked!
Thanks very much for spotting this -- ferreting out what was going on and suggesting the fix.
You are now a "contributor"! :}
