### ISSUE TITLE
Key value error when iterating through edges

### ISSUE THREAD

**Issue by Fedebindi97** [networkx/networkx#4770]
Hello everybody. I'm currently developing an agent-based model that features a network in which agents dynamically create links between each other. These links have some attributes, among which "expiry". 

At a certain point in the code, I need to create lists of all in_edges and out_edges pertaining to a certain node ("self", as I'm creating a class method; "model" is another class which is passed into the agent as an __init__ argument, and which contains the network) for which "expiry" takes certain values. I use list comprehension:

`
out_contracts_2_3=[(a,b) for a,b in self.model.modelgraph.out_edges(self) if self.model.modelgraph[a][b]["expiry"]==2 or self.model.modelgraph[a][b]["expiry"]==3]
`

`
in_contracts_2_3=[(a,b) for a,b in self.model.modelgraph.in_edges(self) if self.model.modelgraph[a][b]["expiry"]==2 or self.model.modelgraph[a][b]["expiry"]==3]
`

At the first turn, the list is empty: the model is initialized with no links among the nodes. When I run the code, Python immediately raises 

`KeyError: 'expiry'`

At first, I thought that the problem was the emptiness of the list, so I tried to enclose the above code in an if statement, that would not consider the above line of codes if `[(a,b) for a,b in self.model.modelgraph.out_edges(self)]` or `[(a,b) for a,b in self.model.modelgraph.in_edges(self)]` were empty lists, but the error is raised anyway. The funny thing is that the error is raised only for the second line of code, despite the two being exactly the same.

Does anyway have any idea of what's going on? It may be a naive issue, but I'm really a Python beginner...

Thanks!

**Comment by MridulS** [comment]
The  `KeyError` (`KeyError: 'expiry'`)  pops up when there is no key in the attribute dictionary, i.e the attribute `expiry` is not present in the edge of the `modelgraph`. I think (just a speculation) this is happening only in one case because the key `expiry` is not set properly for all the edges in the graph. A quick example:


``` python

In [1]: import networkx as nx

In [2]: G = nx.DiGraph()

In [3]: G.add_edge(1, 2, expiry=1) # the outgoing edge from node 1 has the attribute expiry set to 1

In [4]:  G.add_edge(2, 1) # the attribute expiry is missing in the incoming edge.

In [5]: [(a, b) for a, b in G.out_edges(1) if G[a][b]['expiry'] == 1]
Out[5]: [(1, 2)]

In [6]: [(a, b) for a, b in G.in_edges(1) if G[a][b]['expiry'] == 1]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-6-45b0424c3541> in <module>
----> 1 [(a, b) for a, b in G.in_edges(1) if G[a][b]['expiry'] == 1]

<ipython-input-6-45b0424c3541> in <listcomp>(.0)
----> 1 [(a, b) for a, b in G.in_edges(1) if G[a][b]['expiry'] == 1]

KeyError: 'expiry'
```
