### ISSUE TITLE
deprecation warning message

### ISSUE THREAD

**Issue by ivan-marroquin** [networkx/networkx#4780]
### Current Behavior

I just wanted to report a deprecation warning in networkx. The message is as follows:

C:\Temp\Python\Python3.6.5\lib\site-packages\networkx\drawing\nx_pylab.py:563: MatplotlibDeprecationWarning:
The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
  if not cb.iterable(width):
C:\Temp\Python\Python3.6.5\lib\site-packages\networkx\drawing\nx_pylab.py:660: MatplotlibDeprecationWarning:
The iterable function was deprecated in Matplotlib 3.1 and will be removed in 3.3. Use np.iterable instead.
  if cb.iterable(node_size):  # many node sizes

### Environment

Python version: 3.6.5
NetworkX version: 2.2
numpy version: 1.19.0
matplotlib version: 3.2.2

**Comment by rossbar** [comment]
Thanks for the report, this was [fixed in version 2.4](https://networkx.org/documentation/stable/release/release_2.4.html#pull-requests-and-commits-merged-in-this-release).
