### ISSUE TITLE
Shortest path, where you have to pass through a certain node(s) (migrated from Trac #488)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#480]
Original ticket https://networkx.lanl.gov/trac/ticket/488
Reported 2011-01-05 by ziggy.jonsson.nyc, assigned to @hagberg.

Thanks for an excellent library, it's opened my eyes to networking and allowed me to view problems in a different perspective.

I was wondering how difficult it would be to have conditions to shortest path.  In particular I was thinking about conditioning shortest path so that it must pass through certain nodes (if such nodes are provided).   The path can not backtrack once it reaches any of those conditioned nodes, i.e. it must go another way out than it came in.

I could do this by copying the graph and removing last edge for each required node, but that would be a waste of memory since I would end up copying all the data.

**Comment by MridulS** [comment]
@hagberg what do you think about an implementation like this for unweighted graphs? [untested]
``` python
import networkx as nx

def shortest_path_mustpass(G, source, target, mustpass):
    paths = list(nx.all_simple_paths(G, source, target))
    for i in range(len(paths)):
        if len(set(paths[i]).intersection(mustpass)) == len(mustpass):
            min = paths[i]
            if len(paths[i]) < min:
                min_path = paths[i]
    return min_path

if __name__ == '__main__':
    G = nx.MultiGraph()
    G.add_edge(1,2)
    G.add_edge(1,2)
    G.add_edge(2,3)
    G.add_edge(3,4)
    G.add_edge(1,3)
    G.add_edge(1,4)
    mustpass = [2,3]
    print shortest_path_mustpass(G, 1, 4, mustpass)
    print shortest_path_mustpass(G, 1, 4, [1,3])

```

**Comment by hagberg** [comment]
There must be a more efficient way.

**Comment by MridulS** [comment]
One more way could be copying the graph and then deleting the edges as already suggested in the original post. What do you suggest?

**Comment by MridulS** [comment]
Just thinking out loud.... What if we divide it into a segmented dijkstra and a TSP problem? TSP for nodes in ```mustpass``` and then find the shortest way from source to a node in ```mustpass``` nodes and the shortest way from a node in ```mustpass``` to the target using dijkstra as you suggested?

**Comment by ysitu** [comment]
@MridulS Then instead of a special-purpose Dijkstra, maybe you want to provide a TSP solver instead?

**Comment by MridulS** [comment]
@ysitu But will the TSP solver be more efficient than what I have implemented above?

**Comment by ysitu** [comment]
@MridulS Is your solution correct at all?

```python
>>> G = nx.DiGraph()
>>> G.add_edge(1, 2)
>>> G.add_edge(2, 3)
>>> G.add_edge(2, 4)
>>> G.add_edge(4, 2)
>>> shortest_path_mustpass(G, 1, 3, [4])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 8, in shortest_path_mustpass
UnboundLocalError: local variable 'min_path' referenced before assignment
```

**Comment by MridulS** [comment]
@ysitu This is a very crude implementation
``` python
import networkx as nx

def shortest_path_mustpass(G, source, target, mustpass=[]):
    paths = list(nx.all_simple_paths(G, source, target))
    min_path=[]
    maximum=0
    for i in paths:
        if len(i) > maximum:
            maximum = len(i)
    min_length=maximum
    for i in range(len(paths)):
        if len(set(paths[i]).intersection(mustpass)) == len(mustpass):
            if len(paths[i]) <= min_length:
                min_path = paths[i]
                min_length = len(paths[i])
    return min_path

if __name__ == '__main__':
    G = nx.DiGraph()
    G.add_edge(1,2)
    G.add_edge(1,2)
    G.add_edge(2,3)
    G.add_edge(3,4)
    G.add_edge(1,3)
    G.add_edge(1,4)
    mustpass = [2,3]
    print shortest_path_mustpass(G, 1, 4, mustpass)
    print shortest_path_mustpass(G, 1, 3, [1,2,3])
    print shortest_path_mustpass(G, 1, 4)
```

**Comment by MridulS** [comment]
@hagberg @ysitu I have got in wrong, this implementation misses a lot of corner cases.
Would like to know your views on the following algorithm. 
Basically this is dijkstra of dijkstra algorithm, we start with the nodes: V = source, target, mustpass. And we run a dijkstra on this while an underlying dijkstra is running to find shortest paths from source to find the next node in V.
Example:
```
source = 1
target = 5
edges = (1,4), (1,2), (1,3), (2,3), (2,4), (3,4), (4,5)
mustpass = [2,3]

We consider the graph with only 1,2, 3 and 5 as nodes.
We use dijkstra to find the shortest path from 1 to 5 which only passes through 2 and 3, 
and to travel between these nodes we find the shortest path by running dijkstra 
between respective nodes.
```
Looks interesting to me, although it seems inefficient.

**Comment by ysitu** [comment]
@MridulS The problem with your initial code is that you assumed the solution is a simple path. That is not the case. I showed you a counterexample above. An A* search looks more promising to me. During the search, you keep track of the minimum cost to reach a particular node having visited a particular subsets of the must-pass nodes.

**Comment by m-krastev** [comment]
Reviving this. Is there any way of doing this in current networkx? Maybe some version of TSP?
