### ISSUE TITLE
Unable to Iterate over Iterator returned by bfs_edges

### ISSUE THREAD

**Issue by alvaradoo** [networkx/networkx#4813]
I am attempting to compare a self-developed BFS algorithm to ensure correctness against the NetworkX bfs_edges function to compare the depth array. Using the online tutorial I am attempting to get the node depths through this method: 
`nodes = [root] + [v for u, v in resnx]`
As described on the documentation, but it returns an error saying that my root node was not found in the graph. I then attempted to just convert the returned iterator into a list, but that also returned the same error. I was hoping to figure out what I am doing wrong. Thank you!

### Current Behavior

An error is returned saying that a particular node is not in a graph when attempting to convert the iterator returned by bfs_edges to a list.

### Expected Behavior

The error should not occur, since the node is in fact in the graph.

### Steps to Reproduce

The example link [here](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.traversal.breadth_first_search.bfs_edges.html#networkx.algorithms.traversal.breadth_first_search.bfs_edges). Instead of creating a graph, I am reading one in from an edgelist. I am using the Delaunay_n10 benchmark graph. My code is here: 

```
G = nx.read_edgelist("delaunay_n10.gr")
root = int((totalV-1)/2)
resnx = nx.bfs_edges(G, root)
nodes = [root] + [v for u, v in resnx]
```

### Environment

Python version: 3.9.1
NetworkX version: 2.5

### Additional context

Error message:
Traceback (most recent call last):
  File "/rhome/oaa9/anaconda3/envs/arkouda/lib/python3.9/site-packages/networkx/classes/graph.py", line 1238, in neighbors
    return iter(self._adj[n])
KeyError: 511

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/rhome/oaa9/ArkoudaExtension/testingFiles/bfs.py", line 69, in <module>
    time_ak_bfs_delaunay_graph(i)
  File "/rhome/oaa9/ArkoudaExtension/testingFiles/bfs.py", line 52, in time_ak_bfs_delaunay_graph
    nodes = [root] + [v for u, v in resnx]
  File "/rhome/oaa9/ArkoudaExtension/testingFiles/bfs.py", line 52, in <listcomp>
    nodes = [root] + [v for u, v in resnx]
  File "/rhome/oaa9/anaconda3/envs/arkouda/lib/python3.9/site-packages/networkx/algorithms/traversal/breadth_first_search.py", line 164, in bfs_edges
    yield from generic_bfs_edges(G, source, successors, depth_limit, sort_neighbors)
  File "/rhome/oaa9/anaconda3/envs/arkouda/lib/python3.9/site-packages/networkx/algorithms/traversal/breadth_first_search.py", line 75, in generic_bfs_edges
    queue = deque([(source, depth_limit, neighbors(source))])
  File "/rhome/oaa9/anaconda3/envs/arkouda/lib/python3.9/site-packages/networkx/classes/graph.py", line 1240, in neighbors
    raise NetworkXError(f"The node {n} is not in the graph.") from e
networkx.exception.NetworkXError: The node 511 is not in the graph.

**Comment by dschult** [comment]
Does the example you point to work?
Did you check, e.g. `root in G`, or `print(G.nodes)`?
There is no reason to expect that your computed value of `root` should be a node in `G`. Check it to make sure you know what is what.

**Comment by alvaradoo** [comment]
So, I realized my mistake was that I was reading in the edge list, but I was not specifying to read in my node values as integers. So, of course I was not finding int node 511 since it was actually str node '511'. I went through the trouble to raise an issue when it was something so simple! So sorry, and thank you!
