### ISSUE TITLE
show_edges() based on show_nodes() fails

### ISSUE THREAD

**Issue by jpmaterial** [networkx/networkx#4845]
Creating a subgraph with show_edges() based on a subgraph created with show_nodes() fails.

### Current Behavior
Passing the resulting subgraph to nx.draw() results in an undecipherable exception.

### Expected Behavior
The subgraph should preferably work or at least throw an understandable exception.

### Steps to Reproduce

    import networkx as nx
    import matplotlib.pyplot as plt

    g = nx.from_edgelist( [(0,1),(1,2),(2,3),(3,4),(4,5),(5,0),(1,4)] )
    f = nx.classes.filters.show_nodes( [0,1,4,5] )
    sg = nx.subgraph_view( g, f )
    ff = nx.classes.filters.show_edges( [(5,0),(1,4)] )
    ssg = nx.subgraph_view( sg, ff )
    nx.draw(ssg)
    plt.savefig('plot.png')

### Environment
Python version: 3.7.4
NetworkX version: 2.5 (via conda-forge)

### Additional context
None

**Comment by MridulS** [comment]
```
ssg = nx.subgraph_view(sg, filter_edge=ff)
```
should fix it, python will try to map `ff` to `filter_node` so we need to be explicit.

**Comment by dschult** [comment]
We should probably make these parameters be keyword-only, so that the user is required to specify them -- it is too tempting to rely on order and get switched.  We are planning to look at adding that "feature" to many functions this summer.

**Comment by MridulS** [comment]
I think we should look into this API again. Should we force keyword only for `subgraph_view` with a deprecation cycle? We can probably get that in 3.2 @dschult

**Comment by dschult** [comment]
Yes -- I think that would be a good improvement. And probably good to get the deprecation in before v3.2.

It would/could also show where in our own codebase we get the order of these arguments mixed. :)
