### ISSUE TITLE
A table in the documentation is broken.

### ISSUE THREAD

**Issue by ytfksw** [networkx/networkx#4852]
Corruption of automatically generated documents.
A table in the documentation is broken.

![image](https://user-images.githubusercontent.com/30371920/120138351-4737bd80-c211-11eb-934f-7d2385a73df1.png)

https://networkx.org/documentation/stable/reference/generators.html#module-networkx.generators.sudoku

**Comment by rossbar** [comment]
Nice find! This is indeed still a problem in the development version of the documentation: https://networkx.org/documentation/latest/reference/generators.html#module-networkx.generators.sudoku
