### ISSUE TITLE
Conflict With flask_cors

### ISSUE THREAD

**Issue by dzg100011** [networkx/networkx#4853]
If install flask_cors 3.0.1 and networkx 2.5.1
It will raise exception
Flask_cors/decorator.py line 14 
From .core import *
ImportError: attempted relative import with no known parent package

**Comment by dschult** [comment]
How are you installing? What tools are you using to install?
It looks like the error is in the `flask_cors` code. 
Can you try to install them separately?

**Comment by rossbar** [comment]
I can't reproduce this one:

```bash
python -m pip install flask_cors==3.0.1 networkx==2.5.1
```

works fine. I'm going to close this for now, but if the issue persists please reopen with a minimal reproducing example (i.e. reproducing the exact error you're seeing, preferably with the fewest lines possible).
