### ISSUE TITLE
Documentation for conda based dev environment setup fails

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#4870]
The new contributor documentation available at https://networkx.org/documentation/latest/developer/contribute.html#development-workflow doesn't work for conda based development environment setup.

### Current Behavior

While installing developer environment dependencies 
```
$ conda install -c conda-forge `for i in requirements/{default,developer,test}.txt; do echo -n " --file $i "; done`

InvalidVersionSpec: Invalid version '1.19;platform_python_implementation!='PyPy'andpython_version<'3.10'': invalid character(s)
```
it fails to parse the pip specific requirements.txt file.
### Expected Behavior

Users should be able to setup the development environment by following the documentation.

### Steps to Reproduce

```
$ conda install -c conda-forge `for i in requirements/{default,developer,test}.txt; do echo -n " --file $i "; done`

InvalidVersionSpec: Invalid version '1.19;platform_python_implementation!='PyPy'andpython_version<'3.10'': invalid character(s)
```

### Environment

Python version: 3.9.4
NetworkX version: main branch
conda version: 4.10.1

**Comment by rossbar** [comment]
I also tried the `--file` option as suggested [here](https://stackoverflow.com/questions/51042589/conda-version-pip-install-r-requirements-txt-target-lib/51043636) but it has the same problem.

One solution is to use `conda` to create & activate the environment, then use `pip` to actually install the dependencies. I think this works assuming 1) the environment is empty to start with and 2) you don't mix conda & pip for installing packages. I don't regularly use conda though so I'm not 100% sure this is recommended.

**Comment by jarrodmillman** [comment]
Can we just remove the conda instructions?  I suspect we would have heard from someone before, if anyone is using these instructions.

**Comment by rossbar** [comment]
> Can we just remove the conda instructions?

It would make things simpler if we removed references to environment management altogether. It's clearly important, but it's a more general development practice and new users shouldn't necessarily be learning *how* to setup virtual environments from our docs. For example: [scikit-learn's dev guide](https://scikit-learn.org/stable/developers/advanced_installation.html#building-from-source) makes a reference to creating a virtual environment (see step 3) but isn't explicit about it and avoids the whole env-management-tooling problem altogether.

**Comment by jarrodmillman** [comment]
I don't think we need to remove the `venv` example.  I made a PR to remove the broken conda example.

**Comment by dschult** [comment]
I think just removing the conda example in the docs is insufficient. You are making the user either use venv or have to figure out what is required for conda. Many users are introduced to networkx via conda.  When they start to become contributtors we should help them -- not make them switch environments.

If our requirements file syntax no longer works, let's fix the requirements file or fix the docs -- not get rid of them. Then each person who tries to use the requirements files with conda will have to figure out the syntax error issue themselves.  Maybe Mridul or Ross already had to do that for the Sprint last week???

**Comment by jarrodmillman** [comment]
If we want to leave the instructions in someone needs to figure out how to fix it.

**Comment by dschult** [comment]
I think we can make the (already crazy long) conda command slightly longer and it works. The idea is to remove anything after and including the first semi-colon from the requirements as we concatenate them to list the packages desired.

```bash
conda install -c conda-forge `for i in {default,developer,test}.txt; do for n in $(sed 's/;.*//' $i); do echo -n " $n "; done; done`
```

If someone knows sed better, there is probably a way to substitute the newlines with spaces and avoid the inner loop and echo command.  Anyway, this change to the documents is sufficient to make them work with the current default.txt file.

We could also create a parallel default.txt file called `conda_default.txt` that removes the conditions on pypy. But this seemed simpler to me.

**Comment by jarrodmillman** [comment]
Is sed available on Windows and Mac?  I assume people using conda are more likely to be on Windows or Mac (but that is just a wild guess).

Actually, I bet
```
pip install -r <(cat requirements/{default,developer,test}.txt)
``` 
doesn't work on Windows (e.g., using cmd or Powershell)?  We should probably just expand this to
```
pip install -r requirements.txt    # this gets default.txt and test.txt
pip install -r developer.txt
```

**Comment by dschult** [comment]
Good point!  
Mac has sed. But I doubt Windows does. Somehow I missed the idea that these instructions were supposed to work on Windows too. Does Windows have any of these command line tools?  I haven't been able to get students to obtain a nice working setup with windows. They either end up installing linux or using one of the macs in the dept. Is there a place in the Scientific Python community where we help new users get set up with a working IDE, installation and set of tools like git? Perhaps anaconda is the best attempt at that that I know of... but I haven't looked enough to know, really...

Also -- I'm confused... how does `pip install -r requirements.txt` work -- I don't see any requirements.txt file anymore.
How do we get requirements.txt to match default and tests?

**Comment by dschult** [comment]
I guess that we should also put all the requirements files on a single `pip install` or `conda install` command:
```
pip install -r default.txt -r developer.txt -r test.txt
```
or
```
conda install --file conda_default.txt --file developer.txt --file test.txt 
```
where `conda_default.txt` removes the pypy checking syntax from `default.txt`

**Comment by jarrodmillman** [comment]
Or
```
pip install -r requirements.txt -r requirements/developer.txt
```
and
```
conda install --file conda_requirements.txt --file requirements/developer.txt
```

I suspect the path separator is an issue, though.  Maybe we should just mention the developer requirements in a comment.  We could move it to the part where we discuss `pre-commit`.

**Comment by jarrodmillman** [comment]
https://github.com/conda/conda/pull/7258
