### ISSUE TITLE
Add destringizer example to read_gml docstring

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#4877]
IMO it would be a nice addition to add a simple example of the `destringizer` parameter to the `read_gml` docstring. See #4854 for inspiration.

**Comment by randallwvr90** [comment]
Adding this with pull request #4916

**Comment by rossbar** [comment]
Thanks @randallwvr90, the rewording is indeed more clear --- it would still be nice to add a detailed example demonstrating the results of loading w/ and w/out the destringizer, so I propose to leave this open.

**Comment by randallwvr90** [comment]
@rossbar updating with pr #4925
