### ISSUE TITLE
attribute assortativity returns nan

### ISSUE THREAD

**Issue by harshal-dupare** [networkx/networkx#4882]
attribute assortativity returns `nan` when there is only a single value of the attribute for all nodes 

### Current Behavior
```
>>> G = nx.DiGraph()
>>> G.add_edges_from([(0,1),(1,2),(2,3),(3,0)])
>>> nx.set_node_attributes(G,'x','C')
>>> nx.attribute_assortativity_coefficient(G,'C')
nan
```
### Expected Behavior
```
>>> G = nx.DiGraph()
>>> G.add_edges_from([(0,1),(1,2),(2,3),(3,0)])
>>> nx.set_node_attributes(G,'x','C')
>>> nx.attribute_assortativity_coefficient(G,'C')
1.0
```

The problem is in `algorithms/assortativity/correlation.py` at `attribute_ac` line `255`

```
    r = (t - s) / (1 - s)    
```
`s=1` when there is only a single value of the attribute.

**Comment by dschult** [comment]
FWIW:  
`degree_assortativity_coefficient` also returns `nan` when the graph is of uniform degree.
Also `numeric_assortativity_coefficient` does too.

So, they are all consistent... If there is no variation in the value, assortativity is not defined.

**Comment by rossbar** [comment]
I'm going to close this one as resolved, thanks @harshal-dupare & @dschult !
