### ISSUE TITLE
dfs_edges can miss edges when no source provided

### ISSUE THREAD

**Issue by corey-biarri** [networkx/networkx#4899]
When running `dfs_edges` with a directed graph, it may not return all the edges. 

### Current Behavior
Depending on the arbitrary node selected to start the dfs search, edges may be missed.

```
>>> g = nx.DiGraph()
>>> g.add_edges_from([(1, 2), (0, 1)])
>>> list(nx.dfs_edges(g))
[(1, 2)]
```

whereas this works as expected
```
>>> g = nx.DiGraph()
>>> g.add_edges_from([(0, 1), (1, 2)])
>>> list(nx.dfs_edges(g))
[(0, 1), (1, 2)]
```

### Expected Behavior
When there is no source provided, I expected all edges to be returned. eg

```
>>> g = nx.DiGraph()
>>> g.add_edges_from([(1, 2), (0, 1)])
>>> list(nx.dfs_edges(g))
[(0, 1), (1, 2)]
```

### Steps to Reproduce
See example above. 

### Environment

Python version: 3.6.13
NetworkX version: 2.5.1

**Comment by berlincho** [comment]
It is a tricky issue depending on the input graph when the `source` parameter is `None`. But it doesn't make sense to output all unreachable edges even if the source is arbitrarily assigned.
https://github.com/networkx/networkx/blob/b442619bd60651574b733e06af79d8da17c93254/networkx/algorithms/traversal/depth_first_search.py#L46-L49

The example below also returns part of the edges. I think the best way is to set the `source` parameter to get desired results. Open for further discussions.
```python
>>> g = nx.DiGraph()
>>> g.add_edges_from([(1, 2), (0, 1)])
>>> list(nx.dfs_edges(g, source=1))
[(1, 2)]
```

**Comment by corey-biarri** [comment]
Yeah I suppose, what caught me off guard was that I did expect it to return all edges when no source was provided. 

For example on initial testing of `dfs_edges` I thought this was the behaviour, as with a slightly larger graph you can see that it's not exactly the same as calling `dfs_edges` with a source.

```
>>> g = nx.DiGraph()
>>> g.add_edges_from([(2, 3), (0, 1), (1, 2)])
>>> list(nx.dfs_edges(g))
[(2, 3), (0, 1)]  # still missing the edge (1, 2)
```

whereas 

```
>>> g = nx.DiGraph()
>>> g.add_edges_from([(2, 3), (0, 1), (1, 2)])
>>> list(nx.dfs_edges(g, source=2))
[(2, 3)]  # only edges downstream of 2 as expected
```
which is what I would expect when specifying the source.

Perhaps leaving it as is and making it clear that edges may be missed is sufficient.

**Comment by rossbar** [comment]
From [the description in the docstring](https://networkx.org/documentation/latest/reference/algorithms/generated/networkx.algorithms.traversal.depth_first_search.dfs_edges.html#networkx.algorithms.traversal.depth_first_search.dfs_edges) it looks like this is clearly documented and `edge_dfs` may be a better fit for the behavior you are looking for.

**Comment by corey-biarri** [comment]
Great, it is quite clear there.

I use an older version of networkx which didn't have that comment. My bad for forgetting to check the updated docs.
