### ISSUE TITLE
double_edge_swap for directed graphs (migrated from Trac #498)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#490]
Original ticket https://networkx.lanl.gov/trac/ticket/498
Reported 2011-02-01 by unknown, assigned to @hagberg.

Currently, double_edge_swap doesn't work for DiGraph. I have attached the patch for degree_seq.py that should make double_edge_swap work for directed graphs.

**Comment by hagberg** [comment]
Closed due to inactivity
