### ISSUE TITLE
Setting per-node attributes with `add_nodes_from` does not set attributes

### ISSUE THREAD

**Issue by c-bg** [networkx/networkx#4910]
Thanks a lot for maintaining this package, it's great! :) 
I've witnessed a potential bug and would like to contribute a bug report. 

When I set attributes with `add_nodes_from`, and then look at the nodes with `g.nodes(data=True)`, I do not see the attributes I specified. If I set them via `nx.set_node_attributes`, I can later see them. 
This is contrary to how one can add attributes to edges. 

### Current Behavior

```python
import networkx as nx
h = nx.MultiDiGraph()
nodes_with_attrs = {'A': {'color': 'yellow'}, 'B': {'color': 'blue'}, 'C': {'color': 'red'}}
h.add_nodes_from(nodes_with_attrs)
h.nodes(data=True)
```
results in output (1)
```
NodeDataView({'A': {}, 'B': {}, 'C': {}})
```
Additionally running 
```python
nx.set_node_attributes(h, nodes_with_attrs)
h.nodes(data=True)
```
results in output (2)
```
NodeDataView({'A': {'color': 'yellow'}, 'B': {'color': 'blue'}, 'C': {'color': 'red'}})
```

### Expected Behavior

Output (1) should already be output (2), I think. 

This would also be consistent with the behavior for edges: 
```python
import networkx as nx
h = nx.MultiDiGraph()
h.add_nodes_from('A B C'.split())
edges_with_attrs = [('A', 'B', {'capacity': 1}), ('B', 'C', {'capacity': 2}), ('C', 'A', {'capacity': 3})]
h.add_edges_from(edges_with_attrs)
h.edges(data=True)
```
results in output
```
OutMultiEdgeDataView([('A', 'B', {'capacity': 1}), ('B', 'C', {'capacity': 2}), ('C', 'A', {'capacity': 3})])
```

### Steps to Reproduce

(cf. the code example above)

### Environment

Python version: 3.8.2
NetworkX version: 2.5.1

Thanks much for your feedback & help in advance!

**Comment by dschult** [comment]
The current code idiom when you have a dictionary is:
```python
G.add_nodes_from(nodes_with_attrs.items())
```
But it would be possible to add some logic to slurp in the attributes when you have the dict-of-dict structure. But of course in that case `nx.set_node_attributes` works well.  Are there cases where you’d like to use the keys of a dict as the nodes to add? That would be a reason **not** to implement this.

your example with edges is **not** analogous— there you are using the `(node, nbr, data)` structure that works for `G.add_edges_from` but doesn’t work for `nx.set_edge_attributes`.  The analogous example would be `{(“A”, “B”): {‘color’: “blue”}, (“B”, “C”): {‘color’: “red”}}` which doesn’t work for G.add_edges_from but does work for set_edge_attributes. In this case adding `.items()` doesn’t work for G.add_edges_from. You just need to use the correct set_edge_attributes function.

For that reason, I’m inclined to leave the api as is.  If you have a dict keyed by nodes to an attribute dict, then use set_node_attributes.  Same with edges. If you have a dict keyed by edge-tuple to an attribute dict, use set_edge_attributes.

**Comment by c-bg** [comment]
Thanks much for your prompt and helpful reply. 

That makes so much sense, of course. I'm sorry for the inconvenience, the error is on my side -- you are absolutely right, the edges' case is _not_ analogous. 
I agree that it makes sense to leave the api as is. 

Thanks again and sorry for the noise!
