### ISSUE TITLE
descendants_at_distance appears to be untested

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#4957]
AFAICT `descendants_at_distance` is not explicitly tested anywhere. I was confused by this because the coverage report for the `breadth_first_search` module where the function is defined is at 98% (notably - the untested line is in `descendants_at_distance`), but I don't see any explicit calls to `descendants_at_distance` when grepping the test suite.

Adding some tests should help codify behavior and avoid issues like #4952 .

**Comment by dschult** [comment]
It looks like `descendants_at_distance` is [called by ](https://github.com/networkx/networkx/blob/e8914bb5681b6fad8a6764406d3c7a78ebc582ae/networkx/algorithms/dag.py#L624)`transitive_closure_dag` in the `dag.py` module.  
But that just means even more -- we should include tests for it. :}
