### ISSUE TITLE
Can't retrieve all edges for pair of nodes in Multi(Di)Graph

### ISSUE THREAD

**Issue by logan-dunbar** [networkx/networkx#4961]
According to the docs, I should be able to subscript into Multi(Di)Graph by pair of nodes and retrieve all the edges:

> Hence, **G.edges[u, v]['color']** provides the value of the color attribute for edge (u, v) while for (u, v, c) in G.edges(data='color', default='red'): iterates through all the edges yielding the color attribute. [Docs](https://networkx.org/documentation/stable/reference/classes/generated/networkx.MultiGraph.edges.html)

Either the docs or incorrect (I suspect a copy-paste from non-Multi Graph/DiGraph), or this does not work as expected.

### Current Behavior

```python
G = nx.MultiGraph()  # or MultiDiGraph
nx.add_path(G, [0, 1, 2])
key = G.add_edge(1, 2, weight=5)
G.edges[1, 2]
# G.edges[1, 2, 0] or G.edges[1, 2, 1] works
```

> ValueError: not enough values to unpack (expected 3, got 2)

### Expected Behavior

I would expect to be able to retrieve all the (multi-)edges for a pair of nodes by subscripting into the edges of the MultiGraph:
```python
G.edges[1, 2]
```

> MultiEdgeView([(1, 2, 0), (1, 2, 1)])

### Environment

Python version: 3.8
NetworkX version: 2.6.1

**Comment by rossbar** [comment]
Closing this one as duplicate

**Comment by logan-dunbar** [comment]
Link to duplicate please?

**Comment by logan-dunbar** [comment]
Oh whoops, must have double posted, sorry.
