### ISSUE TITLE
Get TypeError when use not_implemented_for decorator

### ISSUE THREAD

**Issue by acezen** [networkx/networkx#4963]
### Current Behavior
```python
import networkx
from networkx.utils.decorators import not_implemented_for
@not_implemented_for("directed")
    def sp_function(G):
        pass
---> 91     return argmap(_not_implemented_for, 0)
TypeError: __init__() missing 1 required keyword-only argument: 'try_finally'
```

### Expected Behavior
```python
import networkx
from networkx.utils.decorators import not_implemented_for
@not_implemented_for("directed")
    def sp_function(G):
        pass
```
no error 

### Steps to Reproduce
```python
import networkx
from networkx.utils.decorators import not_implemented_for
@not_implemented_for("directed")
    def sp_function(G):
        pass
```
### Environment
Python version: 3.8
NetworkX version: 2.6.1

**Comment by acezen** [comment]
upgrade decorator from 4.4.2 to 5.0.5, solved. Seems decorator 4.4.2 not compatible with NetworkX 2.6.1

**Comment by rossbar** [comment]
> Seems decorator 4.4.2 not compatible with NetworkX 2.6.1

As of 2.6, NetworkX no longer depends on `decorator`, and should work in any environment regardless of whether `decorator` is installed (regardless of the decorator version)
