### ISSUE TITLE
Support for Python 3.6

### ISSUE THREAD

**Issue by xkszltl** [networkx/networkx#4964]
We're building PyTorch, which depends on networkx.
On CentOS 7 and Ubuntu 18.04, stock version of python is 3.6 and we're having trouble today due to the newly released networkx 2.6.
Is there any strong reason to switch to 3.7 before the EOL of these 2 distros?
Can we improve the compatibility if not too hard?

**Comment by jarrodmillman** [comment]
Like NumPy, SciPy, Pandas, Matplotlib, and many other Python packages in the scientific Python ecosytem, we are following NEP 29:  https://numpy.org/neps/nep-0029-deprecation_policy.html.

**Comment by xkszltl** [comment]
Is there any hard restriction networkx to support Python3.6?
If not, intentionally break compatibility doesn't sound like a good idea.
For example, numpy 1.19 + networkx 2.5 works just fine on Python3.6.
Would be great if we can keep upgrading to networkx 2.6 even numpy itself cannot go further.

**Comment by xkszltl** [comment]
I believe what numpy trying to propose is a lower bound of support window, not an upper bound.
I would say big lib like numpy can usually get many benefit from newer python and carries quite a lot of burden when supporting old ones.
It's good for them to set an expectation so that downstream won't make wrong assumption of stability on them.
This doesn't mean other lib without the same issue should drop the support as well.

**Comment by xkszltl** [comment]
BTW, just curious, what kind of feature are you looking for from Python 3.7, other than https://github.com/networkx/networkx/commit/5618142c87696c3adfe6490eec65c10098e320c1

**Comment by jarrodmillman** [comment]
The NEP is written in a confusing manner.  However, all the projects I mentioned above have dropped 3.6.  We will not support 3.6 going forward.  So if you need 3.6 support, you will need to use NetworkX 2.5.  ``pip`` should handle this for you, though.  Are you specifically trying to install NetworkX 2.6?

**Comment by jarrodmillman** [comment]
We aren't specifically looking for any features from Python 3.7.  But we are not interested in restricting ourselves to 3.6.  What features of NetworkX 2.6 do you need?  It is possible that we can backport those features and release 2.5.2.  That release may not support Python 3.9, though.  Do you need to run on Python 3.6 through 3.9?  If so, it would be great if you could explain your usecase.

**Comment by rossbar** [comment]
> BTW, just curious, what kind of feature are you looking for from Python 3.7, other than the initial commit of dropping support 

IIRC the big one is that Python 3.7 guarantees that dictionaries preserve insertion order. Since NetworkX's Graph data structures rely heavily on Python dictionaries, this new language feature allowed NX to get rid of custom order-preserving code and deprecate `Ordered` versions of the Graph classes.

**Comment by xkszltl** [comment]
I'm not looking for any specific feature from 2.6 currently.
We can pin to 2.5 for now, but I think it's not a good idea in the long term to stick with an old version.

> pip should handle this for you

Not really.
Our use case is:
- We need to have (almost) offline build.
- We cannot get package from pypi.org due to network restriction.
- We cannot use a local pypi cache due to limited network bandwidth to pypi.
- We mirror the git repo to local and build from source.
- pip version resolver won't work in this case. We need to figure out a git tag to clone.
- Usually we resolve to the latest release based on release tag sorting.

**Comment by xkszltl** [comment]
> It is possible that we can backport those features and release 2.5.2. That release may not support Python 3.9, though. Do you need to run on Python 3.6 through 3.9? If so, it would be great if you could explain your usecase.

I really appreciate the willingness for that kind of support and backport.
However, at this point I'm mostly trying to figure out what's the best way going forward with stock python on these distros, e.g. whether to pin version.

**Comment by rossbar** [comment]
>  We can pin to 2.5 for now, but I think it's not a good idea in the long term to stick with an old version.

I think this is just the natural maintenance burden that results of a mismatch between the goals of LTS distros and the pace of development for software packages.

**Comment by dschult** [comment]
We are making use of the new features of the Python language. So our new releases won't work with the old versions of Python that don't support these new features. It seems reasonable that keeping an environment that works with an older version of Python will need to use an older version of NetworkX. But those users with a newer version of Python will be able to use newer versions of NetworkX. Can you make that work in your environment?  Is there a way you can choose a version of networkx based on the version of python being used?  It sounds like that is what you need here.

**Comment by xkszltl** [comment]
> I think this is just the natural maintenance burden that results of a mismatch between the goals of LTS distros and the pace of development for software packages.

@rossbar Totally agree. But tend to find that burden very noticeable with python ecosystem comparing to other backend languages (C/C++/C#/Java/rust/ruby/shell/...).

> Can you make that work in your environment?

@dschult Yes. But before making decision to pin version, it would be good to receive inputs from authors of networkx. Based on the current opinions I collected, I believe I'll move forward with that. Feel free to close this issue.

> Is there a way you can choose a version of networkx based on the version of python being used?

@dschult No.

**Comment by rossbar** [comment]
I will close this one as resolved - if you'd like to continue the discussion on release cycles for scientific Python libraries more generally, I suggest [the scientific Python discussion forum](https://discuss.scientific-python.org/) or related proposals.
