### ISSUE TITLE
 2.6 installs numpy, pandas and scipy by default

### ISSUE THREAD

**Issue by tetron** [networkx/networkx#4968]
### Current Behavior
Installing networkx 2.6 causes numpy, scipy and pandas to be installed.

These are large packages that have complex binary dependencies.

### Expected Behavior
In networkx 2.5 and earlier, these were optional dependencies that were not installed by default.

### Steps to Reproduce
pip install networkx >= 2.6

### Environment

Python version: 3.7.3
NetworkX version: 2.6.1
pip version: 21.1.3

### Additional context
I woke up to my build system failing because a 3rd degree transitive dependency suddenly expected gfortran :frowning_face: 

I am working around it by pinning to networkx 2.5.

I'm filing this issue because it is not clear if this change in behavior was intended or not.

**Comment by jarrodmillman** [comment]
Yes, this was intended.  It is prominently discussed in the release notes and announcement.  That said, it introduced a circular build dependency issue for scipy: scipy/scipy#14335 and serge-sans-paille/pythran#1837.  We are considering undoing this change: https://github.com/networkx/networkx/pull/4967.  Feel free to give that PR a thumbs up.

**Comment by freddyaboulton** [comment]
@jarrodmillman Thanks for putting up that PR. I gave a thumbs up because it caused problems for EvalML

**Comment by jarrodmillman** [comment]
Out of curiosity, would our current recommendation of using ``pip install --no-deps networkx`` work for you?

**Comment by freddyaboulton** [comment]
Don't think so because there's no way to specify `--no-deps` in the requirements.txt file of our package:

https://stackoverflow.com/questions/31798280/pass-no-deps-in-pip-requirements-txt/37155000
https://github.com/pypa/pip/issues/7339#issuecomment-554139328

**Comment by tetron** [comment]
I see this is being discussed in great detail over on #4967 so feel free to close this issue unless it is helpful for tracking.

**Comment by jarrodmillman** [comment]
I "yanked" 2.6 and 2.6.1 from PyPI:
- https://pypi.org/help/#yanked

See https://github.com/networkx/networkx/pull/4967.
