### ISSUE TITLE
single_source_dijkstra sometimes returns paths that don't match up with distances

### ISSUE THREAD

**Issue by CDBiddulph** [networkx/networkx#4974]
### Current Behavior
On a particular graph I'm working with, there are a few pairs of nodes where the shortest distance is _not_ len(path) - 1. In particular, for two nodes 0 and 1, the path is [0, 1], but the distance is 2.0. This can be seen in the "Additional context" section. Most pairs work as expected.

### Expected Behavior
The distance in this case should be 1.0.

### Steps to Reproduce
Put `bug_demo.py` and `dijkstra.edgelist` into the same directory and run `python bug_demo.py`.
[bug-report.zip](https://github.com/networkx/networkx/files/6820206/bug-report.zip)

### Environment

Python version: 3.9.5
NetworkX version: 2.5.1

### Additional context
I'm pretty sure that the problem is with distances rather than with paths, as I originally noticed the bug when looking at one side of a bipartite graph - I expected all of the distances to be even numbers, but some of them were odd.

**Comment by boothby** [comment]
Hi, you're using a weighted graph, and the weighted shortest-path distance.  The distance from 0 to 1 is reported correctly as the weight of the edge (0, 1).  If you want the unweighted distance, please use `nx.single_source_shortest_path`.
