### ISSUE TITLE
definition of transitivity is misleading

### ISSUE THREAD

**Issue by ma-ji** [networkx/networkx#4975]
Hi, I found this definition is misleading, if not wrong. It should be $closed triads / (close + open triads)$. Not "the fraction of all possible triangles present in G".

https://github.com/networkx/networkx/blob/80704838e60327f3e3a292f4fb4812039be843df/networkx/algorithms/cluster.py#L395

**Comment by rossbar** [comment]
I'm not sure how much would be gained by re-wording the first sentence, as the remainder of the summary in the docstring is pretty explicit about what is meant by "possible triangles" and includes the formula:

https://github.com/networkx/networkx/blob/2eb274e39f712047cebf5666ee9caf2ba2e51ee4/networkx/algorithms/cluster.py#L398-L405

That said, PRs with proposals to reword the docstring are welcome.

**Comment by ma-ji** [comment]
I think a clear definition should be consistent and use as few terms as possible because it is well known that there are term confusions in network metrics. 

I propose using only close/open triads because readers only have to know what is a "triad," which is pretty simple. The current definition introduces "triangles," "possible triangles," and "triads", etc. I tried to replicate transitivity using other NetworkX functions according to the current definition but failed. My guess is that the terms are used differently in different functions, which are made by different people.

Glad to create a PR if you agree to this principle.

**Comment by rossbar** [comment]
I'm not an expert so I can't comment on whether the terms "closed triad" and "open triad" is any more technically correct than "triangles", "possible triangles" and "triads". I still don't think changing the terms makes anything any more or less clear, given the specific definitions/formulae in the remainder of the docstring.

> My guess is that the terms are used differently in different functions, which are made by different people.

Unifying terminology across multiple funtions to make things more consistent would certainly be a worthy goal! If something is called a "triad" in one function but a "possible triangle" in another, that's a clear area for improvement. If you see an opportunity for unifying terminology across multiple functions, I'd encourage you to go for it!

**Comment by rossbar** [comment]
This issue has been inactive for a while, so I will close it. Documentation improvements & wording suggestions are welcome, but at this stage I think a concrete proposal (i.e. a PR) would be the next step in pushing the discussion forward.
