### ISSUE TITLE
Isomorphism for edge matching doesn't seem to work the way I think it should

### ISSUE THREAD

**Issue by danieljbruce** [networkx/networkx#4978]
Running the following script should print `True`, but it throws an error that says `AttributeError: 'int' object has no attribute 'get'`. I'm not too sure if I am using this improperly or if there is an error in the library.

```
import networkx as nx
import networkx.algorithms.isomorphism as iso

G = nx.Graph()
G.add_edge(0, 1, weight=2)
H = nx.Graph()
H.add_edge(1, 2, weight=2)
em = iso.numerical_multiedge_match('weight', 0, rtol=1e-6)
print(nx.is_isomorphic(G, H, edge_match=em))
```

**Comment by dschult** [comment]
You are using `iso.numerical_multiedge_match` which matches multiedges.  But your graphs are not multigraphs (they don't use multiedges).  So you should either switch to `iso.numerical_edge_match` or switch to `nx.MultiGraph`.

**Comment by rossbar** [comment]
Thanks @dschult for correctly identifying the problem and providing the fix.

One potential improvement would be to try to add a mechanism to give more informative error messages when the matching callables fail.

**Comment by rossbar** [comment]
I'm going to close this one as resolved by @dschult 's answer.
