### ISSUE TITLE
Inconsistent documentation nbunch parameter in DiGraph.edges()

### ISSUE THREAD

**Issue by Larrath** [networkx/networkx#4985]
### Current Behavior

The [documentation](https://networkx.org/documentation/stable/reference/classes/generated/networkx.DiGraph.edges.html) of the *edges* function for DiGraphs is misleading due to the description of the *nbunch* parameter, which is contradictory to the rest of the function's documentation:

> **nbunch : single node, container, or all nodes (default= all nodes)**
The view will only report edges incident to these nodes.

Under 'notes', it is stated:

> For directed graphs this returns the out-edges.

It can also be noticed that the function returns an OutEdgeView object.

In terms of the code functionality itself, DiGraph.edges(n) will only return the outgoing edges of the node *n*.

### Expected Behavior
The description of the parameter *nbunch* should be updated to reflect and emphasize the fact that only **outgoing edges** belonging to these nodes will be returned, and not **incident edges**.

I also believe it might be helpful to expand on the Example section and directly show:

```python
G = nx.DiGraph()
nx.add_path(G, [0, 1, 2])
G.edges(0) # <- Returns the edge (0, 1) in a View
G.edges(2) # <- Returns an empty list in a View
```

### Environment

Python version: 3.8
NetworkX version: 2.6.2

**Comment by dschult** [comment]
Looks like instead of `incident to these nodes.` the docstring should read something like:
```The view will only report edges from these nodes.```
or maybe stronger with:
```The view will only report edges from these nodes (outgoing if directed).```
