### ISSUE TITLE
Weird primal/dual graph conversions from networkx 2.6.2

### ISSUE THREAD

**Issue by vishalmhjn** [networkx/networkx#4991]
### Expected Behavior
I am trying to convert the OSM data from geo-dataframe to networkx graph format using the following code. The output from the older version (2.5) of networkx looks alright, but the output from the newer version (2.6.2) is crazy. Since I was working on two machines simultaneously, it was easy for me to identify the issue, otherwise it could be a headache.

### Steps to Reproduce
```
import geopandas
import momepy
import networkx as nx
from contextily import add_basemap
from libpysal import weights

filename = "../data/osm_network.geojson"
file = open(filename)
streets = geopandas.read_file(file)
streets.to_crs(epsg=3857, inplace=True) 
G_dual = momepy.gdf_to_nx(streets, approach="dual")

f, ax = plt.subplots(1, 2, figsize=(30, 15), 
                     sharex=True, 
                     sharey=True)
streets.plot(color="k", ax=ax[0])
for i, facet in enumerate(ax):
    facet.set_title(("Streets", "Graph")[i])
    facet.axis("off")
    add_basemap(facet)
nx.draw(G_dual, {n: [n[0], n[1]] for n in list(G_dual.nodes)}, ax=ax[1], node_size=1)
plt.savefig("../images/dual.png", dpi=400)
```

### Environment
OS: Ubuntu18
Python version: 3.8.11
NetworkX version: 2.5 and 2.6.2

```
In [6]: networkx.__version__
Out[6]: '2.6.2'
In [7]: momepy.__version__
Out[7]: '0.4.4'
In [8]: geopandas.__version__
Out[8]: '0.9.0'
In [9]: contextily.__version__
Out[9]: '1.1.0'
In [10]: libpysal.__version__
Out[10]: '4.5.1'
```

### Additional context

Output with networx 2.5:
![Screenshot from 2021-07-29 11-48-34](https://user-images.githubusercontent.com/42190624/127470924-6206fa5d-e750-41f5-8325-c347c252f107.png)

Output from networkx2.6.2
![Screenshot from 2021-07-29 11-48-12](https://user-images.githubusercontent.com/42190624/127471114-ed279461-d826-4742-8ac7-c67db94b3d6e.png)

**Comment by rossbar** [comment]
The example you've provided isn't reproducible so I can't say for sure, but this looks to me like your Graph might have a lot of self-loops. Self-loops were not drawn by default in v2.5, which was considered a bug (it's never good to silently ignore information).

Can you try adding `G_dual.remove_edges_from(nx.selfloop_edges(G))` before plotting to see if that recovers the original plot?

**Comment by vishalmhjn** [comment]
Thanks for the quick reply. I tried and yes, you are right, removing self-loops returns the previous output.

**Comment by rossbar** [comment]
Great, thanks for confirming!

I think you've also helped uncover a bug: I would've recommended using the `edgelist` parameter in `nx.draw` to suppress the drawing of selfloops, something like:

```python
>>> selfloops = set(nx.selfloop_edges(G_dual))
>>> nx.draw(G_dual, pos, edgelist=[e for e in G.edges() if e not in selfloops])
```

Unfortunately that's not working for me locally, which indicates there may be a bug in how the `edgelist` parameter is handled in the branch responsible for drawing self-loops. I will open an issue specific to that behavior in a bit, so feel free to close this one if you're question has been answered --- and thanks for reporting!
