### ISSUE TITLE
Replacing xml with defusedxml to prevent XML External Entity injection attacks (XXE)

### ISSUE THREAD

**Issue by bt-nia** [networkx/networkx#5001]
https://github.com/networkx/networkx/blob/2eb274e39f712047cebf5666ee9caf2ba2e51ee4/networkx/readwrite/gexf.py#L20

The standard `xml` library is vulnerable to XXE and other denial of service attacks that could impact security of any service making use of this library when parsing XML-based files. 

In general, it should be as easy as replacing the current import with `defusedxml.ElementTree`, however, the `register_namespace` function is not available in the `defusedxml` package. So there is some work-around needed here. 

Other code locations are:
https://github.com/networkx/networkx/blob/2eb274e39f712047cebf5666ee9caf2ba2e51ee4/networkx/readwrite/graphml.py#L456

https://github.com/networkx/networkx/blob/2eb274e39f712047cebf5666ee9caf2ba2e51ee4/networkx/readwrite/graphml.py#L481

https://github.com/networkx/networkx/blob/2eb274e39f712047cebf5666ee9caf2ba2e51ee4/networkx/readwrite/graphml.py#L645

https://github.com/networkx/networkx/blob/2eb274e39f712047cebf5666ee9caf2ba2e51ee4/networkx/readwrite/graphml.py#L832

lxml is also being used, which might need some re-coding unfortunately since the lxml defused replacement is deprecated.
https://github.com/networkx/networkx/blob/2eb274e39f712047cebf5666ee9caf2ba2e51ee4/networkx/readwrite/graphml.py#L159

https://github.com/networkx/networkx/blob/2eb274e39f712047cebf5666ee9caf2ba2e51ee4/networkx/readwrite/graphml.py#L696

**Comment by rossbar** [comment]
> What's the status of this? Security concerns are not small, especially with how widely deployed the NetworkX package is.

I think if there were a contributor who was interested in exploring switching to `defusedxml` it would certainly be considered. Note that the security concerns do not originate in NetworkX itself, but through the use of the xml package in the Python standard library. In principle "fixing" the security vulnerabilities upstream would automatically handle the security issues in NX (and any other library that depends on `xml`), though I'm sure there are reasons why this hasn't been done and a third-party library has been recommended instead.

**Comment by owen-mcmahon** [comment]
Are there any plans to address this/merge in the commits made in the fork above to switch to `defusedxml`? 

We have enterprise restrictions preventing us from downloading all versions of `networkx` at the moment due to the vulnerability, hence why I am asking.

**Comment by dschult** [comment]
From [the Python docs for the `xml` library](https://docs.python.org/3/library/xml.html): So long as you use expat 2.4.1 or later, the `xml` standard library is Safe except for the `xmlrpc` module which we do not use. But the version of expt shipped with Python is 2.2.8 for Python 3.8 AFAICT

What would allow your Enterprise restrictions to allow NetworkX? 
- How are they allowing you to use Python when it ships with the `xml` library?
- Do the Enterprise restriction people understand that so long as you don't use graphml or gexf formats, networkx doesn't use the `xml` library?  
- If they worry about using a package like networkx that **might** use `xml`, then they shouldn't allow you to use Python at all.
- Would a reduced feature version that removed graphml and gexf features (the only ones that use `xml`) work for you?

Honestly, you should be putting pressure first on your Enterprise restrictions, and second on Python itself via `xml` and `expat`. We are so downstream from `expat` that we have no expertise in these matters. The best approach I believe is for your Enterprise to require all programmers to use a sufficiently recent Python version that it ships with `expat 2.4.1` and thus the xml known vulnerabilities are not relevant.

**Comment by rossbar** [comment]
I agree with @dschult 's assessment here - this seems largely like an upstream/dependency management issue. I'm going to close this as resolved by the above suggestion. I
