### ISSUE TITLE
greedy_modularity_communities handling of ties

### ISSUE THREAD

**Issue by elplatt** [networkx/networkx#5005]
Created a separate issue for the below comment. This could be a bug, although I am not certain. Either way, we should make the code clearer.

> I have another question, although not super important.
> 
> Can this statement be False?
> 
> <https://github.com/networkx/networkx/blob/d475ffe7b24633934b5e566974fe7e72a9400cf4/networkx/algorithms/community/modularity_max.py#L126>
> 
> If i, j merge has the best dq, is it possible for the j-row to have as its 1st item a better one? Wouldn't that be the one popped from H at that iteration, instead of i, j? From some examples I run locally, it never goes to else.
> 
> _Originally posted by @ThanasisMattas in https://github.com/networkx/networkx/issues/3112#issuecomment-892005572_

**Comment by rossbar** [comment]
The `greedy_modularity_communities` code has been refactored since this issue was opened - the `dq` is no longer part of the comparison. Therefore, I will close this issue - if the issue (or related) persists, please feel free to open a new issue!
