### ISSUE TITLE
Cannot import networkx.algorithms.lowest_common_ancestors

### ISSUE THREAD

**Issue by kevinmyers** [networkx/networkx#5014]
I cannot import `networkx.algorithms.lowest_common_ancestors`

### Current Behavior
I cannot import `networkx.algorithms.lowest_common_ancestors` and specifically need to run `from networkx.algorithms.lowest_common_ancestors import lowest_common_ancestor`.

### Expected Behavior
I expect to be able to import this module.

### Steps to Reproduce
I simply tried to run the two import commands below in Python:
`from networkx.algorithms.lowest_common_ancestors import lowest_common_ancestor`
`import networkx.algorithms.lowest_common_ancestors`

### Environment
Python version: 3.6.7
NetworkX version: 2.6.2

**Comment by dschult** [comment]
Those imports work for me... but you should be able to do:
```python
import networkx as nx
nx.lowest_common_ancestors(G, u, v)
```

I notice that you are using Python 3.6.7 and NetworkX 2.6.2 doesn't officially support Python 3.6.  But I don't think that should cause this error.

**Comment by kevinmyers** [comment]
Thanks. What version of Python do you recommend using?

**Comment by dschult** [comment]
NetworkX supports Python 3.7-3.9 but should work for most tasks with 3.6-3.10.
I would get 3.9 as that's the latest (3.10 is prerelease still) but again, it seems unlikely that is the trouble.
You might also see whether you can just import networkx.
Perhaps you are running a python from your operating system, but installing networkx on a different installation of python?  That's a common issue.  Check which python you are actually running and also which has networkx installed.

**Comment by kevinmyers** [comment]
Thanks. I can import networkx alone no problem. I can also import other networkx modules:

`from networkx.algorithms.dag import descendants`
`from networkx.algorithms.dag import ancestors`
`from networkx.algorithms.shortest_paths.unweighted import bidirectional_shortest_path`

I also installed networkx via Anaconda and am using the same Anaconda Python.

**Comment by dschult** [comment]
If you can import networkx then it isn't a problem with it trying to find the wrong installation.

Most of networkx is available in a flat namespace from the main module. So:
`networkx.descendants`, `networkx.ancestors`, `networkx.lowest_common_ancestors`.
So you shouldn't need this feature.

But.... I don't understand why it isn't working... unless there is a typo somewhere... It works for me as expected.

**Comment by kevinmyers** [comment]
Here is exactly what I'm typing and the resulting error:

```
from networkx.algorithms.lowest_common_ancestors import lowest_common_ancestor
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'networkx.algorithms.lowest_common_ancestors'
```

**Comment by kevinmyers** [comment]
Ahh, I figured it out. There was something screwy with my PYTHONPATH, but I fixed that and it's working now. Thanks for all your help!
