### ISSUE TITLE
corner-case bug in single_source_dijkstra

### ISSUE THREAD

**Issue by joelmiller** [networkx/networkx#5023]
### Current Behavior
If we call `single_source_disjkstra` with the source equal to target, it returns a path of length 0, even if the source is not in the graph

### Expected Behavior
If the source is not in the graph, it should give an error message.

### Steps to Reproduce

    import networkx as nx
    G = nx.Graph()
    nx.single_source_dijkstra(G, source=1, target=1)

### Environment

Python version: 3.7.6
NetworkX version:  2.4

**Comment by rossbar** [comment]
Note that this issue also affects `single_source_bellman_ford`

**Comment by divyanx** [comment]
Hey @MridulS , I am very new.
The topic seems something I have studied in college.
Could I work on this?

**Comment by MridulS** [comment]
Hi @divyanx, sure thing! Please go ahead.
As a first step you can setup a local development environment for NetworkX, the instructions to setup the environment are present in the [Contributor Guide](https://networkx.org/documentation/latest/developer/contribute.html). You can also go through the [New Contributor FAQ](https://networkx.org/documentation/latest/developer/new_contributor_faq.html) for some general FAQs. Let us know if there are any other questions about this!

**Comment by divyanx** [comment]
Thanks a lot, ill go through this and ask if I get stuck somewhere.

**Comment by divyanx** [comment]
Hey @MridulS, what error message or behavior should I add for the mentioned edge case.

**Comment by rossbar** [comment]
Closed by #5033
