### ISSUE TITLE
Failed to save graph generated using stochastic_block_model

### ISSUE THREAD

**Issue by rubenkerkhofs** [networkx/networkx#5024]
Saving a graph that has been generated with a stochastic_block_model is not possible using write_graphml.

### Current Behavior
When generating a random network using the stochastic block model, the returned networkx object cannot be written to a graphml file using the write_graphml function.

### Expected Behavior
When generating random graphs using the networkx package, it should be possible to export them using write_graphml.

### Steps to Reproduce
The following piece of code reproduces the error message:

```
import networkx as nx

wg = 0.8 # can be any number representing within group probability
bg = 0.2 # can be any number representing between group probability
community_probs = [[wg, bg, bg], 
                   [bg, wg, bg], 
                   [bg, bg, wg]]
community_sizes = [10,10,10]

G = nx.stochastic_block_model(community_sizes, community_probs)
nx.write_graphml(G, 'file_name.graphml')
```

### Environment

Python version: 3.9.6
NetworkX version: 2.6.2

### Additional context
Error message:

<img width="795" alt="Screenshot 2021-08-16 at 10 09 05" src="https://user-images.githubusercontent.com/44324476/129532047-658f7207-448b-4e33-8ad2-8092d498c87e.png">

**Comment by dschult** [comment]
Data attributes that have list values are not part of the GraphML spec. That is, you can't store graphs with list or dict attribute values using the GraphML standard. See #485 #3663 for similar discussions.

I would suggest that you save the graph in a different format.  OR you could clear out the offending data attributes before converting to GraphML.

**Comment by rossbar** [comment]
Thanks @dschult - the only thing that comes to my mind as potentially "resolving" this issue would be to improve the exception message. Otherwise I'd say this can be closed as duplicate.

**Comment by rubenkerkhofs** [comment]
Thank you very much. The solution is indeed to use a different export method. Pickling the graph for example worked perfectly for me. What could be improved is the exception message (like mentioned by @rossbar). I also suggest that  the graph generator algorithm's documentation gets updated to include a warning that it generates graphs that cannot be exported to graphml. It will help future users to identify exactly what is happening. Thanks again for helping me out.
