### ISSUE TITLE
Should `geometric_edges` raise a specific exception if nodes don't have "pos" attribute?

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#5046]
The `networkx.generators.geometric.geometric_edges` function assumes that the input graph contains nodes that have a `"pos"` attribute representing the 2D position of the node. If this is not the case, exceptions are raised (depending on whether or not scipy is installed) that don't really indicate what the problem is:

```python
>>> G = nx.path_graph(3)
```

### with scipy

```python
>>> nx.generators.geometric.geometric_edges(G, radius=1, p=2)
Traceback (most recent call last)
   ...
ckdtree.pyx in scipy.spatial.ckdtree.cKDTree.__init__()

ValueError: data must be 2 dimensions
```
### without scipy
```python
>>> nx.generators.geometric.geometric_edges(G, radius=1, p=2)
Traceback (most recent call last):
   ...
TypeError: 'NoneType' object is not iterable
```

The thing that makes the most sense to me would be to raise an exception with a specific message to indicate to users that the nodes need a "pos" attribute. Another potential solution would be to have a default value for position when the attribute isn't found, but I don't know what a sensible default would be (`(0, 0)`)?

**Comment by dschult** [comment]
I would say it should raise the exception. Putting a bunch of nodes at (0,0) would be potentially hard to notice.
Does raising the exception mean we should go through every node to check if it has a 2-tuple value on a `pos` attribute?
Or is it better to catch the current error and provide a better message for it?

**Comment by rossbar** [comment]
>  Does raising the exception mean we should go through every node to check if it has a 2-tuple value on a pos attribute?

This is what I was thinking just because it's fewer things to modify (adding one check at the beginning versus catching exceptions in multiple branches). The latter may actually be preferable from a performance perspective however since `geometric_edges` is used internally in a couple of the geometric generators where an extra check for node attributes would be unnecessary, and would actually slow things down.
