### ISSUE TITLE
Deprecate `adjacency_matrix` alias of `to_scipy_sparse_matrix`?

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#5050]
The [adjacency_matrix](https://github.com/networkx/networkx/blob/2e61dacc1ffcdcf44edb5fd68dca5f51e09db219/networkx/linalg/graphmatrix.py#L99-L157) function in the `linalg` package is an alias for `to_scipy_sparse_matrix`. Could it be a candidate for deprecation? Or maybe it should be removed from the main namespace and only available in the `linalg` namespace, where it makes more sense that adjacency is represented by a sparse matrix (instead of the nested-dict structure that adjacency often refers to).

**Comment by jarrodmillman** [comment]
I prefer keeping adjacency_matrix.  It is a standard term in graph theory.  And I think we should hide how we implement it.  So I would rather remove to_scipy_sparse_matrix.  But we still need to go over the linalg package to make sure it makes sense.  I would prefer leaving the package (more or less) as it is until we can refactor the whole linalg package.

**Comment by dschult** [comment]
Just to add some more churn :)   the `to_scipy_sparse_matrix` doesn't actually say whether the resulting matrix is an "adjacency matrix" or an "edgelist matrix" or an "incidence matrix".  So the name `adjacency_matrix` is probably better anyway. The `pandas` functions made that clear -- but only years after the scipy functions had been around.

**Comment by dschult** [comment]
Good point!  
We have both many matrices and also many ways to store a matrix. 
Too many combinations... :}

**Comment by rossbar** [comment]
My original question was sufficiently answered, so I will close this!
