### ISSUE TITLE
Issue with attribute names in `greedy_modularity_communities`

### ISSUE THREAD

**Issue by joelmiller** [networkx/networkx#5060]
### Current Behavior
The function is defined as

`def greedy_modularity_communities(G, weight=None, resolution=1):`

but the first step that uses any attributes is

`m = sum([d.get("weight", 1) for u, v, d in G.edges(data=True)])`

If the graph has an attribute `"weight"`, but either wants to use no attribute (`weight=None`) or a different attribute, this will use the value for `"weight"` rather than what the user wants. 

If the graph doesn't have an attribute `"weight"` and the user wants to use a different attribute, then this step will initialize `m` to have all weights equal.

### Expected Behavior

It should use `m = sum([d.get(weight, 1) for u, v, d in G.edges(data=True)])`

### Steps to Reproduce

I haven't worked out an example yet, but I'm confident this is an issue.  [I'm looking at [something that appears to be a bug](https://stackoverflow.com/questions/69006073/attributeerror-nonetype-object-has-no-attribute-get-when-using-greedy-modul?noredirect=1#comment122014639_69006073) on stackoverflow, but I don't yet understand what's going on there].
### Environment

Python version:
NetworkX version:

**Comment by rossbar** [comment]
Good catch, this has already been fixed in #4996
