### ISSUE TITLE
Update documentation for planar embedding

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#5090]
Let's update the documentation to make it clear that the `check_planarity` function is the primary interface for the planar embedding tools.  Also, the class `PlanarEmbedding` is tricky to make sure it maintains the planar data structure. People not familiar with those ideas should definitely start with the `check_planarity` function.

See discussion in #5079

**Comment by abxhr** [comment]
I would love to work on this! 🙋‍♂️

For more context, what all should be added onto the documentation of `PlanarEmbedding` class?

**Comment by dschult** [comment]
I think the main trouble #5079 revealed is that it is not clear where to start using the features we have. It is tempting to go straight to the class. But the better place to start is with the function `check_planarity`.  So I think a pointer in the class documentation would be good, a statement in the function doc_string that it is the primary interface to the routines for planarity, and a paragraph in the module documentation about the various parts and that you want to start with `check_planarity`.  Of course as you read more and learn more, other items might come up. The goal is to make it clear for someone who has done a search for "networkx planarity".

**Comment by 0ddoes** [comment]
Sir, I am an Outreachy applicant. Is this issue still open? Can I try to make any updates to the documentation to make it more clear? If so please do guide me in what you expect , as to how I can improve it?

**Comment by 0ddoes** [comment]
@MridulS Hi, Is this issue still open? And if so can you guide me on how I can improve it?
