### ISSUE TITLE
Improve test suite for random graphs

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#5092]
The tests for the random graph generators in `test_random_graphs.py` could benefit from a refactor/review. Some things that immediately stand out:
 - Improve granularity: some tests have many `assert` statements and are not particularly specific to testing any one thing. Breaking these up into smaller tests should improve readability, specificity, and reduce instances where code is being run but not explicitly tested.
 - There are a lot of `sum(1 for _ in G.edges())` that *I think* can be replaced with `G.number_of_edges()`.
 - The outer test class can be gotten rid of without needing any larger reorganization AFAICT
 - There are a couple obvious opportunities to parametrize tests, which should help with the granularity as well.
 - Review seeding for test reproducibility

**Comment by SimoneGasperini** [comment]
Can I work on this issue? My idea would be to improve the test suite granularity and specificity splitting the big outer class in smaller specific classes for the following "types" of random generators:
- gnp
- gnm
- watts strogatz
- barabasi albert
- powerlaw cluster
- random regular
- random shell
- random lobster
- random kernel

Each one of the above classes would contain its own test_* functions, one for each particular property to be checked.

Question: what do you mean exactly by "seeding review"?

**Comment by rossbar** [comment]
> Can I work on this issue?

By all means!

>  My idea would be to improve the test suite granularity and specificity splitting the big outer class in smaller specific classes for the following "types" of random generators:

I'm not sure such a reorganization would be an improvement. IMO it would be an improvement to get rid of any class-based organization, which adds an extra layer of indirection that doesn't actually add anything in this case.

To give you an example of what I had in mind re: granularity, take a look at the first test in the module:

https://github.com/networkx/networkx/blob/dc3c4861368b4dc60b76e0dfc671cc6317ff20c4/networkx/generators/tests/test_random_graphs.py#L9-L112

In reality, this is many unrelated unit tests all wrapped up into one. To take just one example of how this can be broken up, I did a minor refactor of one section of this first test in #5094 to demonstrate what I would consider an improvement (of course, feedback welcome!)

Regardless, I would recommend starting off submitting smaller PRs that deal with one thing at a time - this will make it easier to provide specific feedback and will make it much more likely that changes get in quickly than a full refactor of the entire file all at once!

**Comment by SimoneGasperini** [comment]
Ok thank your for your help and for the example... Very clear! I go ahead refactoring the file section by section.
