### ISSUE TITLE
Inconsistent results of Dijkstra algorithm

### ISSUE THREAD

**Issue by veager** [networkx/networkx#5112]
The function `nx.shortest_path` and `nx.all_pairs_dijkstra_path` will yields inconsistent results for Dijkstra algorithm.
networkx version: 2.6.3

Test example:
```python
import networkx as nx
print(nx.__version__)
gph = nx.Graph() # undirected graph
gph.add_nodes_from(['A', 'B', 'C', 'D', 'E', 'F'])
gph.add_weighted_edges_from([
    ('A', 'C', 13.), ('A', 'E', 16.), ('A', 'F', 8.), 
    ('B', 'D',  6.), ('B', 'F', 10.), 
    ('C', 'D', 14.), ('C', 'F', 11.),
    ('D', 'E',  5.), ('D', 'F', 17.),
    ('E', 'F',  7.)
])
```

Two ways to realize Dijkstra algorithm
```python
for start in ['A', 'B', 'C', 'D', 'E']:
    for end in ['A', 'B', 'C', 'D', 'E']:
        if start != end:
            print('{0}->{1}'.format(start, end))
            # Way 1 output:
            print(path_all[start][end])

            # Way 2: use nx.shortest_path() function
            path = nx.shortest_path(gph, source=start, target=end, method='dijkstra')
            print(path)
```

The partial outputs with different routes:
```
A->D
['A', 'F', 'E', 'D']
['A', 'C', 'D']
D->A
['D', 'E', 'F', 'A']
['D', 'C', 'A']
E->A
['E', 'F', 'A']
['E', 'A']
```

Seems `nx.shortest_path(method='dijkstra')` has incorrect results

**Comment by dschult** [comment]
The shortest_path function ignores edge weights unless you specify e.g. `weight="weight"`.
The `all_pairs_dijkstra`-like routines use a default edge attribute of "weight".

So, the way you used the functions, `shortest_path` returns the path with fewest hops, while `path_all` holds shortest weighted paths as sums of the edge attribute "weight".

**Comment by veager** [comment]
Got it! Thank you so much! @dschult
