### ISSUE TITLE
Add a figure to every example of layout

### ISSUE THREAD

**Issue by joseberlines** [networkx/networkx#5124]
Problem: trying to decide what layout is better for a DAG graph

### Current Behavior
Going through tall the available layouts: https://networkx.org/documentation/stable/reference/drawing.html

### Expected Behavior
Having a collection of figures that help to decide what is better

**Comment by dschult** [comment]
I would suggest looping over all the layouts, calling each one and sending that into a draw command.  You'll need to use Matplotlib functions to create a new figure.

```python
layouts = [...]
for figno, layout in enumerate(layouts):
    pos = layout(G)
    plt.figure(fig)
    nx.draw(G, pos=pos)
```
Lots more fancy stuff can be added to this of course... :}

**Comment by rossbar** [comment]
I think this would actually be a valuable addition to the [example gallery](https://networkx.org/documentation/latest/auto_examples/index.html).

It might be kind of tricky to select a good example graph that highlights the differences between the different layouts, but IMO this would be a nice improvement to the docs. I'm going to go ahead and reopen this so we can track the suggestion!

**Comment by 0ddoes** [comment]
Hey I would like to contribute into the example gallery if possible. I am Izza and applying for the Outreachy Cohort '22.

**Comment by martwebber** [comment]
Hello @MridulS @joseberlines, I am an Outreachy applicant and I would love to make a contribution to this issue.

**Comment by 5aumy4** [comment]
Hello @MridulS  @joseberlines , I am an Outreachy applicant and I would like to work on this issue.

**Comment by MridulS** [comment]
Hello @5aumy4! There is already an open Pull Request which implements this for Directed Acyclic Graphs https://github.com/networkx/networkx/pull/5432
