### ISSUE TITLE
MAINT: TODO's for 3.10 support

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#5152]
Follow-up for #4807

- [x] unpin the `python_version` on scipy, matplotlib, and pandas once we have wheels for these projects on all three platforms.
- [x] Update Python version for testing matrix in `nx-guides` workflows.

**Comment by MridulS** [comment]
nx-guides is updated https://github.com/networkx/nx-guides/pull/62 and I think we have no more py3.10 specific bits in our CI anymore.

We can close this :)
