### ISSUE TITLE
`networkx.MultiDiGraph.remove_edges_from` has inconsistent documentation (v2.6.2)

### ISSUE THREAD

**Issue by mikidep** [networkx/networkx#5158]
In [this doc page](https://networkx.org/documentation/stable/reference/classes/generated/networkx.MultiDiGraph.remove_edges_from.html) the parameters list reads that if the elements of `ebunch` are

> 2-tuples (u, v) All edges between u and v are removed.

However,  both in the second example below and in my tests, it seems that only one edge between u and v is removed. The functionality described in the parameters list would be useful to have.

**Comment by rossbar** [comment]
I've added the milestone for the documentation component (i.e. point 1) above) which is clearly incorrect and should be fixed before the next release. The other points may require separate discussion --- in fact, it may make sense to break out @dschult 's comment into a separate issue or discussion topic, but we can cross that bridge when we come to it!

**Comment by dschult** [comment]
To address 2) above:
I think I favor the "same namespace" approach hinted at in 3) above: 
   The way to remove all the edges between u and v in a multi(di)graph is:  `G.remove_edges_from([(u, v)])`

The current behavior for this idiom is to remove a single arbitrary edge between u and v. This makes `remove_edges_from` behave as the doc_string says it should. So, this behavior is backward incompatible.  So we'd need to make a Big Fuss in the release notes.  But it is unlikely to affect many users or we would have heard about the documentation error at some point in the last 12 years   :}   If you want to remove an arbitrary multiedge between u and v, you can use `G.remove_edge(u, v)`. So the old behavior is not hard to obtain.

**Comment by rossbar** [comment]
The documentation update was closed by #5699. I've moved the remaining points for discussion to #5825 so we can continue the discussion there.
