### ISSUE TITLE
ImportError: cannot import name 'independent_set' from 'networkx.algorithms.approximation' 

### ISSUE THREAD

**Issue by usbader** [networkx/networkx#5168]
Hello all, 

when I execute my code, the following import error is displayed:

ImportError: cannot import name 'independent_set' from 'networkx.algorithms.approximation' 

networkx==2.6.3

**Comment by rossbar** [comment]
This is because there is no function with the name `independent_set` in the networkx.algorithms.approximation package. Did you mean `networkx.algorithms.approximation.clique.maximum_independent_set`?

**Comment by usbader** [comment]
Yes. That's what I meant.

**Comment by rossbar** [comment]
> Yes. That's what I meant.

In that case, try:

```python
>>> from networkx.algorithms.approximation.clique import maximum_independent_set
```
