### ISSUE TITLE
bug of greedy_modularity_communities

### ISSUE THREAD

**Issue by yingYYDoL** [networkx/networkx#5201]
Clauset-Newman-Moore greedy modularity maximization algorithm should using max heap,and you use min heap

### Current Behavior

 use min heap in dq_dict
### Expected Behavior

shoukd use maxheap
### Steps to Reproduce

import networkx as nx
from networkx.algorithms.community import greedy_modularity_communities
from networkx.algorithms.community.quality import modularity

G = nx.Graph()
G.add_edge('a', 'b', weight = 1)
G.add_edge('b', 'c', weight = 1)
G.add_edge('e', 'd', weight = 10)
G.add_edge('c', 'a', weight = 1)
G.add_edge('b', 'd', weight = 0)
print(greedy_modularity_communities(G))

# return [frozenset({'e', 'b', 'd', 'c', 'a'})]
### Environment

Python version:Python 3.9.7
NetworkX version:2.4

### Additional context

i guess should  use max heap?

**Comment by dschult** [comment]
What would you expect the communities to be for this example?
The example doesn't show that anything is incorrect (as far as I can tell).
Remember, that the way to use a max heap is to use a min heap with negated values.
Are you reading the code to see something is wrong? Or running an example where you know what the answer should be?

**Comment by rossbar** [comment]
The conversation has been stalled here for a couple months, so I will close this due to inactivity. If the issue persists please feel free to reopen this and address [dschult's questions](https://github.com/networkx/networkx/issues/5201#issuecomment-980012747)
