### ISSUE TITLE
nx.drawing.nx_pydot.to_pydot() does not handle correctly nodes with ":"

### ISSUE THREAD

**Issue by grusin** [networkx/networkx#5203]
### Current Behavior
When creating graph with nodes containing colon, for example "3:3" the to_pydot function will create invalid pydot graph, because ":" is a special character in graphviz/dot. ":" symbolizes port number (used in records, to point arrows to given record  cell)

### Expected Behavior
There should be additional parameter to py_dot function to escape the ":" characters, so that caller does not have to do this tedious work when nodes with ports are not desired (like in my usecase). Without that escaping, nodes will be incorrectly created and edges wont connect to the right nodes making graph look quite random.

### Steps to Reproduce
```python
import networkx as nx
import pydot

G = nx.DiGraph()

G.add_node("1@2")
G.add_node("4")
G.add_node("3::3")
G.add_node("a")
  
G.add_edge("1@2", "a")
G.add_edge("a", "4")
G.add_edge("a", "3::3")
G.add_edge("3::3", "3::3")

D = nx.drawing.nx_pydot.to_pydot(G)

for n in D.get_node_list():
  print(n)
```

will print:
```python
"1@2";
4;
3;
a;
```

should print:
```python
"1@2";
4;
"3::3";
a;
```

### FIX:
Attached code that fixes the bug by adding smart quoting function for nodes containing the ":", only if desired to do so. The default behavior is left unchanged, hence it should not produce any breaking changes for existing applications that rly on ":" "feature"

```python
 def to_pydot(N, escape_special_characters: bool=False):
    """Returns a pydot graph from a NetworkX graph N.
    Parameters
    ----------
    N : NetworkX graph
      A graph created with NetworkX
    escape_special_characters : bool
      When true, nodes and edges containing special ":" characters, will be automatically quoted
    Examples
    --------
    >>> K5 = nx.complete_graph(5)
    >>> P = nx.nx_pydot.to_pydot(K5)
    Notes
    -----
    """
    import pydot
    
    def _quote_str(x):
      x = str(x)
      if not escape_special_characters or ":" not in x:
        return x
      
      return f'"{x}"'

    # set Graphviz graph type
    if N.is_directed():
        graph_type = "digraph"
    else:
        graph_type = "graph"
    strict = nx.number_of_selfloops(N) == 0 and not N.is_multigraph()

    name = N.name
    graph_defaults = N.graph.get("graph", {})
    if name == "":
        P = pydot.Dot("", graph_type=graph_type, strict=strict, **graph_defaults)
    else:
        P = pydot.Dot(
            f'"{name}"', graph_type=graph_type, strict=strict, **graph_defaults
        )
    try:
        P.set_node_defaults(**N.graph["node"])
    except KeyError:
        pass
    try:
        P.set_edge_defaults(**N.graph["edge"])
    except KeyError:
        pass

    for n, nodedata in N.nodes(data=True):
        str_nodedata = {k: str(v) for k, v in nodedata.items()}
        p = pydot.Node(_quote_str(n), **str_nodedata)
        P.add_node(p)

    if N.is_multigraph():
        for u, v, key, edgedata in N.edges(data=True, keys=True):
            str_edgedata = {k: _quote_str(v) for k, v in edgedata.items() if k != "key"}
            edge = pydot.Edge(_quote_str(u), _quote_str(v), key=str(key), **str_edgedata)
            P.add_edge(edge)

    else:
        for u, v, edgedata in N.edges(data=True):
            str_edgedata = {k: _quote_str(v) for k, v in edgedata.items()}
            edge = pydot.Edge(_quote_str(u), _quote_str(v), **str_edgedata)
            P.add_edge(edge)
    return P
```

**Comment by rossbar** [comment]
This seems like a reasonable request but it's not really possible to judge the implementation when it's pasted in an issue as it's much more difficult to see what this changes (i.e. it's much easier to review *diffs*) and we can't evaluate whether this breaks existing behavior because the tests aren't run.

@grusin would you be interested/comfortable submitting your suggestion as a pull request? That would make evaluating the changes much more straightforward.
