### ISSUE TITLE
Problem with spiral layout with `equidistant=True`

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#5211]
`nx.spiral_layout` has an `equidistant` kwarg that is False by default. According to the docstring parameter description, this is supposed to enforce that the laid out nodes are all equidistant from one another when True. However, the iterative implementation is such that the node in the first iteration is handled differently than all the rest, resulting in the following behavior:

### Current Behavior

```python
>>> G = nx.path_graph(5)
>>> nx.draw(G, pos=nx.spiral_layout(G, equidistant=True))
```

![fi](https://user-images.githubusercontent.com/1268991/144682663-1655099a-b524-4cfc-a101-68f2ef97865a.png)

### Expected Behavior

The "first" node should (presumably) also be equidistant from it's neighbor

### Environment
Python version: Python 3.9.7
NetworkX version: 2.7rc1.dev0 (766becc1)

### Additional context

`spiral_layout` was added in #3534

**Comment by dschult** [comment]
As part of this issue we should also add a paragraph to the docstring to describe what a spiral layout is and how it is affected by the `equidistant` option.
