### ISSUE TITLE
`spiral_layout` needs more documentation/context

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#5212]
It is difficult to determine how the `spiral_layout` is intended to look. The docstring is relatively sparse and doesn't include a functional example (the example simply calls `nx.spiral_layout` without visualizing or validating the output). Other ways this could be improved might be:
 - Include a gallery example
 - Improve the test suite so that there are some validated checks against expected output
 - Add references to the docstring to the origin of this layout (paper, similar layout in other graph visualization libraries, etc.)

**Comment by Lukong123** [comment]
Hello, @rossbar @MridulS I am an outreachy applicant and I will love to work on this issue.
I have checked out the documentation on `spiral_layout` I will love to work on this issue with your guidance where necessary

**Comment by MridulS** [comment]
@Lukong123 please go ahead and submit a Pull Request when you are ready :)

**Comment by Lukong123** [comment]
Hello sir, I have difficulties drawing the spiral layout.
IWhen I use
```
G = nx.path_graph(15)
daig = nx.spiral_layout(G)
nx.drawing.spiral_layout(daig)
```
 it does not return an error message but I can't see the diagram, and when I use the next line of code it returns an error. Please sir I need your help.
```
G = nx.path_graph(15)
daig = nx.spiral_layout(G)
nx.draw_networkx(daig)

```

**Comment by dschult** [comment]
`spiral_layout` takes as input a Graph and it returns a dictionary keyed by node to that node's (x, y) position value.
Then to draw the Graph with those positions, you need to call `nx.draw_networkx` with both the Graph and also the position dict.  Usually something like:

```python
G = nx.path_graph(15)
pos = nx.spiral_layout(G)
nx.draw(G, pos=pos)
```

**Comment by Lukong123** [comment]
Okay sir thanks

**Comment by MridulS** [comment]
fixed in https://github.com/networkx/networkx/pull/5471
