### ISSUE TITLE
Graph generators in the `small` module need docstrings

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#5213]
There are a number of named graphs defined in `networkx.generators.small` that are not well-documented:

https://github.com/networkx/networkx/blob/766becc132eda01c9d0d458de2d75ab763f83493/networkx/generators/small.py#L183-L575

Each of these functions should have a more extensive docstring with at least a `Parameters`, `Returns`, and `Examples` section, and preferably also a reference to the corresponding paper or wiki page that describes the graph.

**Comment by aramasethu** [comment]
Hi, 

I have started working on this issue. I noticed that the `LCF_graph` function's docstring has all the details that you have specified in the issue. Can use the same format for rest of the modules?

**Comment by dschult** [comment]
That doesn't provide the nice headers that sphinx can make use of.
I would suggest something more like the function [fullrary](https://github.com/networkx/networkx/blob/766becc132eda01c9d0d458de2d75ab763f83493/networkx/generators/classic.py#L67) in `generators/classic.py`

Thanks!

**Comment by aramasethu** [comment]
Hi this is an example of the doc string for bull graph:
```
"""
    Creates a bull graph with 5 nodes and 5 edges.
    "... the bull graph is a planar undirected graph with 5 vertices and 5 edges,
          in the form of a triangle with two disjoint pendant edges" [1]

    Parameters
    ----------
    create_using : NetworkX graph constructor, optional (default=nx.Graph)
       Graph type to create. If graph instance, then cleared before populated.

    Returns
    -------
    G : networkx Graph
        A bull graph with 5 nodes

    References
    ----------
    .. [1] https://en.wikipedia.org/wiki/Bull_graph.

    """
```

Let me know if this looks okay.

**Comment by dschult** [comment]
Our documentation creation tool, sphinx, uses the first part (up to a blank line) as a short description with each link to this function in the docs.  So, it renders much better if the first line is short and sweet, followed by a blank line and  then a paragraph description of what the function is/does.   Also, we usually describe what the function does as `Returns` rather than `creates`.  So maybe the first bit of this should be:
```python
    Returns the Bull Graph

    The Bull Graph has 5 nodes and 5 edges. It is a planar undirected 
    graph in the form of a triangle with two disjoint pendant edges [1]
    The name comes from the triangle and pendant edges representing 
    respectively the body and legs of a bull.
```

**Comment by aramasethu** [comment]
Hi, 

I have added the docstrings to all the graphs (starting from bull graph). I have linked the PR to this issue. Please let me know what your feedback is. 

Thanks for your help
