### ISSUE TITLE
Examples section of `to_numpy_array` could be improved

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#5255]
Currently there is only a single example using an `nx.MultiDiGraph` as input. IMO it would be good to improve a basic example to illustrate the absolute basics of adjacency matrices, then add subsequent examples highlighting the features available via the many keyword arguments.

**Comment by haricash** [comment]
Hello! I am a first timer, and this seems like something I can work on!

If I understand the issue correctly, you would like the documentation to :
1. Talk about what an adjacency matrix is and why it is useful
2. Contain examples that show the functionality of `to_numpy_array` 's many other keyword arguments 

If that is all, I can start working on it right away! Please confirm, and do let me know of any other thing you would like me to add!

**Comment by MridulS** [comment]
@haricash please go ahead!

The examples section can be improved by adding more examples which show the use of other arguments like `dtype`, `weight`, `nonedge`. We don't necessarily need to explain what adjacency matrix is and why it is useful in the examples section of  `to_numpy_array`. Just examples of how to convert a NetworkX graph to numpy array.

Do let us know if you have any other questions about this :)

You can read more about our development processes and some FAQs on the` Developer` page of our website:

[New Contributor FAQ](https://networkx.org/documentation/latest/developer/new_contributor_faq.html)
[Contributor Guide](https://networkx.org/documentation/latest/developer/contribute.html)

**Comment by Lukong123** [comment]
Hello, @MridulS I will love to work on this issue.
I am a newbie here too and I am also willing to learn more, how should the illustration be; should it be something like a jupyter notebook file or how?

**Comment by MridulS** [comment]
Here we are talking about https://networkx.org/documentation/stable/reference/generated/networkx.convert_matrix.to_numpy_array.html, if you go down to the examples section you
will see that the example which is uses a `MultiGraph` doesn't use other available arguments
like `multigraph_weight`, `dtype`, etc. The example for MultiGraph should be improved by
adding the other arguments.

It shouldn't be a jupyter notebook, the example needs to be added to the function documentation 
of `to_numpy_array`.

https://github.com/networkx/networkx/blob/fd52aa52ada0c08dfc25fc749f08589d7b734c00/networkx/convert_matrix.py#L1368-L1390

**Comment by 0ddoes** [comment]
Sir, wouldn't it be cooler if we could include a link that takes you to an external webpage (maybe nx-guides) containing a jupyter notebook explaining what this function does thoroughly , than include a small example in the same documentation? 

In that way probably we can include from Basic multidirected graphs that we define, to real datasets (For eg Political Blogs or Social Networks) on same notebook and show the functionalities on that as well? Like from beginner to advanced kind?

**Comment by rossbar** [comment]
> wouldn't it be cooler if we could include a link that takes you to an external webpage (maybe nx-guides) containing a jupyter notebook

This would be nice too, but is a separate issue. Generally, the `Examples` section in the docstring should highlight the features of a function and demonstrate them for common use-cases. Oftentimes, having quick, clear examples is the quickest way to understand a function!

Having more extensive narrative documentation is a nice idea, but IMO it would make the most sense not to focus on `to_numpy_array` explicitly, but rather to introduce the concept of an adjacency matrix, highlight some of the use-cases where representing graphs this way is particularly useful, then cover the ways that NX has to translate Graph objects into adjacency matrices as e.g. `ndarray` or scipy.sparse arrays.

Just to be clear, the latter is a *much* bigger project and deserves it's own issue/discussion.

**Comment by Oddoes** [comment]
Understood Sir! I will try to do a good example as well . Also if the latter issue ever gets opened sometime I would love to explore it 👍

**Comment by 0ddoes** [comment]
Understood Sir! I will try to work on a good example as well. Also if the latter issue is opened sometime, I will love to explore it!

Sorry for previous comment. That was a different account , not registered with Outreachy.

**Comment by 0ddoes** [comment]
Sir, I tried working on the issue. I am finding a few other issues with the results obtained. I have summarised what I get below:

I tried to make an example from a simple graph and a Multi directed graph to show the difference in usage of arguments. 

**Simple Graph:** 

https://github.com/0ddoes/outreachy/blob/e1ef9bb528a5b26cf7f94de2296ee920aeed801d/2022-round-1/0ddoes/Issue5255.py#L6-L22

This shows how arguments like ```nodelist```, ```nonedge```, ```dtype```, ```weight```  can be used. In this example the ```dtype``` is not structured as well. On adding more edge attributes and values I get the following : 

https://github.com/0ddoes/outreachy/blob/e1ef9bb528a5b26cf7f94de2296ee920aeed801d/2022-round-1/0ddoes/Issue5255.py#L42-L57

Only **Issue** I found was that according to documentation nan values can be assigned but when I tried it gives me the following output. Please let me know if I am doing anything wrong.

https://github.com/0ddoes/outreachy/blob/e1ef9bb528a5b26cf7f94de2296ee920aeed801d/2022-round-1/0ddoes/Issue5255.py#L26-L37


**MultiDiGraph**

In this example I wanted to show the significance of the other arguments : ```multigraph_weight``` and structured array ```dtype```.
https://github.com/0ddoes/outreachy/blob/e1ef9bb528a5b26cf7f94de2296ee920aeed801d/2022-round-1/0ddoes/Issue5255.py#L63-L82

There are 2 edges between 0 and 1 and that reflects in the Adjacency matrix.  Also document can be edited to include that ```multigraph_weight```  will take values (sum, min , max). 

As the dtype is structured Array, according to documentation I gave **None**. But the output is still the previous Adjacency Matrix. It doesn't show the values of **Attribute "Cost"**.  

To tackle this issue, I tried other ways. And changed it to just any Attribute name first (here) "cost".
https://github.com/0ddoes/outreachy/blob/e1ef9bb528a5b26cf7f94de2296ee920aeed801d/2022-round-1/0ddoes/Issue5255.py#L85-L91

Although it took sum of cost attribute for multiple edges between (0,1), it didn't show the value for (2,2) Self edge. Does this not work for a Self edge? 

This output was also seen:

https://github.com/0ddoes/outreachy/blob/e1ef9bb528a5b26cf7f94de2296ee920aeed801d/2022-round-1/0ddoes/Issue5255.py#L85-L91

Even if "weight" is accessed, the previous values of "costs" are given. On displaying A :

https://github.com/0ddoes/outreachy/blob/e1ef9bb528a5b26cf7f94de2296ee920aeed801d/2022-round-1/0ddoes/Issue5255.py#L106-L112

Both values got assigned with the cost Attribute Value, as weights was given as "cost" at the start. But if the weight is given as a tuple ("weight", "cost"), it gives similar to adjacency Matrix. Both values of the tuple get assigned with the number of edges in between. 

https://github.com/0ddoes/outreachy/blob/e1ef9bb528a5b26cf7f94de2296ee920aeed801d/2022-round-1/0ddoes/Issue5255.py#L116-L123

I hope I am using the function right. I checked the code again but I found some of these issues persist. For the final argument ```order```, I was not able to understand from the documentation (how to create example to differentiate two values). Can you please guide me on how to proceed forward?

**Comment by dtekinoglu** [comment]
Hi, @MridulS I am an Outreachy applicant for 2022 Round 1. I added examples for "nonedge" and "nodelist" arguments and created a pull request. Looking forward to hearing your feedback ! :)

**Comment by 0ddoes** [comment]
Hey @rossbar , I would like to contribute more examples. Could you please review my comment above? I appear to still face the same issues. The example given in documentation with structured ```dtype``` doesn't give me the same output as well. Please let me know.

**Comment by dschult** [comment]
@oddoes for simple graph it looks like you used `nan` (which is a `float`) but set the dtype to `int`.  That's why it shows a large integer value instead of nan.

I can't easily follow the other questions. Can you put the code you are asking about inline with your comments? To do that, use \`\`\`python at the beginning and \`\`\` at the end.

````python
```python
G.add_edge(2, 2, weight=3)
G.add_edge(1, 2, weight=4)
```
````

**Comment by 0ddoes** [comment]
Hi, thanks for pointing that out about ```nan```. I understand the mistake I made. I figured if I passed float("nan") , it will override it. But it doesn't seem the case. 

Also I have edited the comment above for the other issues. I hope its alright.

**Comment by MridulS** [comment]
The docs were improved in https://github.com/networkx/networkx/pull/5451 thanks everyone!
