### ISSUE TITLE
Distance_measures.py functions should work for weighted graphs too.

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#5257]
Many of the functions in `distance_measures.py` work for unweighted graphs, but have straightforward definitions for weighted graphs too.  We should go through this module and upgrade each function to work for weighted graphs.  It should be a straightforward fix with a keyword "weight" input which defaults to the current unweighted treatment.  The `shortest_path` functions provide a nice interface for that to use as an example.

**Comment by lucasmccabe** [comment]
To be clear, we mean `distance_measures.py`, right? Or is `distance_measurements.py` somewhere and I'm just not seeing it?

**Comment by dschult** [comment]
Thanks -- Yes -- I mean `distance_measures.py`.  I'll correct it by editing my statement.

**Comment by nishant42491** [comment]
Can i work on this issue

**Comment by Alt-Shivam** [comment]
Hey @dschult 
I would like to work on it.
Thanks.

**Comment by lucasmccabe** [comment]
Hi All, I would also be interested in contributing to this.

It looks like there are handful of functions to address - perhaps we can split the work among ourselves?

**Comment by Alt-Shivam** [comment]
Yeah, @lucasmccabe 
let's do this. :)

**Comment by nishant42491** [comment]
> Hi All, I would also be interested in contributing to this.
> 
> It looks like there are handful of functions to address - perhaps we can split the work among ourselves?

sure lets do it

**Comment by Alt-Shivam** [comment]
Yeah @nishant42491 @lucasmccabe :)

**Comment by BasLaa** [comment]
Hi guys,

Are you still working actively on this? Otherwise I can also take over some work.

**Comment by haricash** [comment]
Hello, if you guys are still working on this and need an extra helping hand, do add me too!

**Comment by MridulS** [comment]
Hello all! It's great to see so much interest to work on the project :)

You can read more about the development processes on our website:

- [New Contributor FAQ](https://networkx.org/documentation/latest/developer/new_contributor_faq.html)
- [Contributor Guide](https://networkx.org/documentation/latest/developer/contribute.html)

For the point about assigning issues we don't usually assign issues to anyone, feel free to open a PR when you are ready.
If you are worried it may conflict with what other people are working on please put in the method you are working on in this issue and open a PR.

Even if you are stuck please do open a PR (you can keep it as a draft) as we can help you review and improve the code in the PR :)

**Comment by BasLaa** [comment]
Alright, so most of the functions actually just use the `eccentricity` function, or the `extrema_bounding` method in the case of `usebounds=True` (BTW this isn't in the documentation or the docstring). So I'm going to start with the `diameter` function just to see how everything works if no one objects.

**Comment by BasLaa** [comment]
I opened a draft PR #5298

**Comment by lucasmccabe** [comment]
Hello, I think I have things figured out in [#5305](https://github.com/networkx/networkx/pull/5305). What do you think?

**Comment by BasLaa** [comment]
I didn't realise you were still working on this issue as I didn't get a response @lucasmccabe , so I added weights for eccentricity and extrema bounding and thus for most distance measures. The weight argument can be a string or a function like in the shortest paths algorithms.

It's PR #5298, could you take a look?
