### ISSUE TITLE
Edge contraction misses multi-edges

### ISSUE THREAD

**Issue by lucasmccabe** [networkx/networkx#5261]
It's possible that we are working with different definitions of edge contraction, but I figured I should bring this up:

[1] defines contraction of an edge e with endpoints u, v in a graph G as follows:

![image](https://user-images.githubusercontent.com/12187602/149555923-1eef1736-8284-4024-9c39-ccccdb3e3bc2.png)

This seems inconsistent with the behavior of `nx.contracted_edge`. If this is deliberate, it may interfere with potential downstream tasks.

### Current Behavior
As far as I can tell, `nx.contracted_edge` does not return a graph with multi-edges when appropriate (e.g. when contracting an edge of a triangle).

### Expected Behavior
In the above example, I would expect edge contraction to result in a MultiGraph with two multi-edges.

### Steps to Reproduce
Consider the example above:

```bash
>>> import networkx as nx
>>> e = [
...         (1, 2),
...         (2, 3),
...         (3, 4),
...         (4, 1),
...         (4, 5),
...         (3, 5)
]
>>> G = nx.Graph(e) # left graph in image above
>>> H = nx.contracted_edge(G, (4, 3))
>>> print(H.edges)
[(1, 2), (1, 4), (2, 4), (4, 5), (4, 4)]
>>> J = nx.contracted_edge(G, (4, 3), self_loops = False)
>>> print(J.edges)
[(1, 2), (1, 4), (2, 4), (4, 5)]
```

### Environment

Python version:  3.10.1
NetworkX version: 2.7rc1.dev0

### Addressing the Issue
If we agree that this is an issue, I am happy to work on it.

### References
[1] West, Douglas B.:
        Introduction to Graph Theory, p.84.
        2018

**Comment by dschult** [comment]
Use a MultiGraph to start with:  `G = nx.MultiGraph(e)`
Or convert to a multigraph as you input it to `contracted_edge`:
`H = nx.contracted_edge(nx.MultiGraph(G), (4, 3))`

**Comment by lucasmccabe** [comment]
Ah, this helps a lot. Thank you!
