### ISSUE TITLE
Deprecate `make_small_graph` and `make_small_undirected_graph` from `small` submodule?

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#5266]
These two functions are defined in the `generators.small` submodule, and are used internally within the module to generate many of the graphs therein. `make_small_graph` is publicly exposed in the namespace, while `make_small_undirected_graph` is not.

Looking at the implementation however, it seems that these functions insert an unnecessary layer of indirection (i.e. a `graph_description` argument that is actually a custom structured list that must be unpacked/parsed)  and complexity (see the node remapping) on top of functionality that is already provided by e.g. `nx.from_edgelist` and `nx.from_dict_of_lists`. AFAICT, `make_small_graph` doesn't add anything that can't be achieved in a more straightforward manner with `from_edgelist` and `from_dict_of_lists` - would there be appetite for it (and `make_small_undirected_graph`) and refactoring the `small` module to use more "canonical" NetworkX graph creation functions?

**Comment by MridulS** [comment]
+1 on deprecation. I'm not sure if we still need `make_small_graph`, `from_dict_of_lists` is definitely more canonical NetworkX IMO.

PS: Most of the `make_small_graph` code hasn't been touched in 17 years!

**Comment by rossbar** [comment]
Awesome, thanks taking a look @MridulS . Any deprecation would depend on #5267 going in, so I'll wait for that. I'll add a milestone to this one though so it doesn't get lost!
