### ISSUE TITLE
Add node independent paths functions (migrated from Trac #538)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#530]
Original ticket https://networkx.lanl.gov/trac/ticket/538
Reported 2011-04-10 by @jtorrents, assigned to @hagberg.

Because of the new flow based connectivity functions (#625) I've changed the name for this module from '''node_independent_paths.py''' to '''connectivity_approx.py'''. I also added a new function '''global_vertex_connectivity_approx''' that uses the same logic than its flow based friend but using the White and Newman fast approximation to find node independent paths. For sparse networks, the approximation is two orders of magnitude faster. I also removed functions for single source node independent paths and all pairs node independent paths because I think that this module will be more useful as a fast approximation to vertex connectivity.

Node independent paths or disjoint vertex paths are paths between two nodes that share no nodes in common other than their starting and ending nodes. The attached implementation finds node independents paths between two nodes by computing their shortest path using BFS, marking the nodes of the path found as 'used' and then searching other shortest paths excluding the nodes marked as used until no more paths exist.

References

White, Douglas R., and Mark Newman. 2001 A Fast Algorithm for Node-Independent Paths. Santa Fe Institute Working Paper 01-07-035

http://eclectic.ss.uci.edu/~drwhite/working.pdf

**Comment by jtorrents** [comment]
This is implemented (and already merged) at #1405 .
