### ISSUE TITLE
incorrect indice in the adjacency matrix

### ISSUE THREAD

**Issue by AnryYang** [networkx/networkx#5312]
### Current Behavior

I input an edgelist file in which nodes are represented by 0,1,2,3,...,2070 and obtain a graph object G. I used networkx.adjacency_matrx(G) to obtain the adjacency matrix but found the entry indices do not accord with the node ids in the edgelist file. 
It seems that in this networkx.adjacency_matrx function, the rows and columns are ordered according to the parameter nodelist, whose default value is list(G). I checked that in Python 2.7 and networkx 2.2, list(G) is sorted according to node ids (e.g, 0,1,2,...,2070), however in Python 3 and networkx 2.5.1, list(G) is random (e.g., 1,3,2,0,...). May I know where this difference comes from? Is it due to Python 3 and Python 2.7 or due to the versions of networkx? Thanks very much.

### Environment

Python version: 3
NetworkX version: 2.5.1

**Comment by dschult** [comment]
In Python 3.6 (I think),  dicts changed to maintain the order in which keys are added to the dict.

Try
```python
d={3: "c", 1: "a", 2: "b"}
print(d)
```
and see whether the keys are in the order you'd expect.

**Comment by AnryYang** [comment]
> In Python 3.6 (I think), dicts changed to maintain the order in which keys are added to the dict.
> 
> Try
> 
> ```python
> d={3: "c", 1: "a", 2: "b"}
> print(d)
> ```
> 
> and see whether the keys are in the order you'd expect.

Thanks for your reply.
I have tried your example code in Python 2.7 and Python 3.6.9, which return "[1,2,3]" and
"dict_keys([3, 1, 2])", respectively. So this means networkx.adjacency_matrx(G) in Python 2.7 will create the adjacency matrix based on the sorted node ids, but in Python 3.6, it creates the adjacency matrix based on the ordering of input nodes.
