### ISSUE TITLE
No module named 'networkx.algorithms.approximation.traveling_salesman' (networkx-2.6.3)

### ISSUE THREAD

**Issue by akazakci** [networkx/networkx#5313]
Hello,
Tring to import and work with traveling_salesman. 

I tried many ways to import:
import networkx.algorithms.approximation.traveling_salesman
from networkx.algorithms.approximation import traveling_salesman
from networkx.algorithms.approximation.traveling_salesman import *
etc

None worked. I tried with version 2.5, updated to version 2.6.3, still getting the same error.

What might be the cause? Is there a turn around?

Thank you all.

**Comment by rossbar** [comment]
How did you install networkx? Any of those import patterns should be fine. IIRC the traveling salesman subpackage was only added in 2.6, so you will need networkx version 2.6 or newer.

**Comment by rossbar** [comment]
It's been a few month since the last comment, so hopefully this was resolved. If not, please feel free to open with updated info on the environment and how you installed NetworkX.
