### ISSUE TITLE
Gephi read/write functions don't handle dynamic data correctly. (migrated from Trac #540)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#532]
Original ticket https://networkx.lanl.gov/trac/ticket/540
Reported 2011-04-14 by @hagberg, assigned to @hagberg.

See 
http://groups.google.com/group/networkx-discuss/browse_thread/thread/6b53d6015821738e

**Comment by hagberg** [comment]
Closed due to inactivity.
