### ISSUE TITLE
size() and degree() returning unexpected result when using a subgraph view

### ISSUE THREAD

**Issue by sengels97** [networkx/networkx#5325]
### Current Behavior

After creating a subgraph view, H.size() wrongly returns 1. However, H.copy().size() correctly returns 2. This seems to be due to the degree of node "4" in H.degree wronlgy being specified as 0 instead of 2. H.copy().degree works as expected. This odd behaivor does not happen with every graph. But it happens when using a graph G as specified in Graph.txt (GraphML format) and creating a subgraph view as seen in Networkx_Bug.pdf.
(See Additional context for a pdf of a Jupyter Notebook and a txt of the used graph in GraphML format)

### Expected Behavior

H.size() should return 2 just like H.copy().size() does.

### Steps to Reproduce

See attached Networkx_Bug.pdf (especially the bottom of page 3, section 4). The used graph in GraphML format is attached in Graph.txt. The files can be found under "Additional contex" uploaded to this bug report.

### Environment

Python version: 3.8.12 via Anaconda
NetworkX version: 2.6.3

### Additional context

[Graph.txt](https://github.com/networkx/networkx/files/8053346/Graph.txt)
[Networkx_Bug.pdf](https://github.com/networkx/networkx/files/8053347/Networkx_Bug.pdf)

**Comment by dschult** [comment]
The problem seems to be in your edge filter.
You only check one direction of your edge. 
It should work if you check `(u,v) in I or (v, u) in I`.
Your edge filter would work with a DiGraph. 

Once you use the `.copy()` feature you copy two edges to the new graph, and it is a Graph so while the edge is added in one direction, it is an undirected edge and suddenly node 4 has degree 2.

**Comment by sengels97** [comment]
Yes, you are right. Thanks for the quick answer. The behavior still seems a bit unexpected to me, since H shows to be a Graph and not a DiGraph. Also both with and without (v,u) in de edge filter H.edges returns the exact same object it seems. But knowing that including (v,u) additionally to (u,v) makes a difference also for undirected graphs, solves the issue. So I get how to obtain the desired result now :)

**Comment by dschult** [comment]
Maybe before leaving this I should ask how you got to the subgraph view code you tried. There is a networkx filter named `nx.show_edges` which would have done what you wanted -- but perhaps is not documented well enough to find.
I would have expect you to use:    `H = nx.subgraph_view(G, filter_edge = nx.show_edges(I))`

What parts of the docs did you look at to figure out the method you used?  We need to put links in there to help people build useful filters.

Thanks!!

**Comment by sengels97** [comment]
Thanks for your comment and the alternative way of writing the subgraph view. I actually noticed one notable difference between `filter_edge = nx.filters.show_edges(I)` and `fitler_edge = lambda u,v: (u,v) in I or (v,u) in I`, namely the behavior when I changes. In the first case, the subgraph view does not change and has to be recreated, whereas in the second case the graph view changes dynamically with I without being recreated. In my case (a greedy-like approximation algorithm for the node-weighted survivable network design problem), I might actually prefer the dynamic behavior of H in case of using `fitler_edge = lambda u,v: (u,v) in I or (v,u) in I`.

Regarding the documentation: First, I actually looked at networkx.Graph.edge_subgraph. However, I explicitly want all nodes and not only nodes incident to selected edges included in my view. For some reason, I then looked at the Graph types overview (https://networkx.org/documentation/stable/reference/classes/index.html) and skimmed over the section on graph views. And from the arguments and short description of subgraph_view, it was quite clear, that this is what I want. Since I didn't read the page on Graph types to the end (since I found the function I needed), I however missed that fact, that there are predefined filters already in networkx.
So, it could have maybe been helpful to have a reference to the predefined filters in the documentation of networkx.classes.graphviews.subgraph_view (https://networkx.org/documentation/stable/reference/classes/generated/networkx.classes.graphviews.subgraph_view.html#)

**Comment by dschult** [comment]
Great!  Thanks that is helpful for us to improve those docs.
I think it would not be hard to rewrite `show_edges` so that it handles I as a dynamic set. We chose not to do it that way to avoid surprise changes in the subgraph when the set is later changed. But I can see the appeal both ways.  That might be a good example actually.   Thanks!
