### ISSUE TITLE
[graphviz_layout] OSError: Error: <stdin>: syntax error in line 

### ISSUE THREAD

**Issue by tkmamidi** [networkx/networkx#5333]
Hello,
Thank you so much for everything you all are doing. Great work!

I'm interested in analyzing [Human Phenotype Ontology](https://hpo.jax.org/app/). I'm trying to draw a graph based on a given node/s to the parent/root node.

### Current Behavior

When using `graphviz_layout`, I got this strange error (FYI - name of node is 'short stature')

```
OSError: Error: <stdin>: syntax error in line 65 near 'stature'
Traceback:
File "/Users/tarunmamidi/opt/anaconda3/envs/hazel/lib/python3.9/site-packages/streamlit/script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
File "/Users/tarunmamidi/Documents/Development/uab-meter/src/streamlit.py", line 39, in <module>
    main()
File "/Users/tarunmamidi/Documents/Development/uab-meter/src/streamlit.py", line 35, in main
    page = page()
File "/Users/tarunmamidi/Documents/Development/uab-meter/src/diagnosis/diagnosis.py", line 124, in hd
    pos=graphviz_layout(final_graph, prog="dot"),
File "/Users/tarunmamidi/opt/anaconda3/envs/hazel/lib/python3.9/site-packages/networkx/drawing/nx_agraph.py", line 239, in graphviz_layout
    return pygraphviz_layout(G, prog=prog, root=root, args=args)
File "/Users/tarunmamidi/opt/anaconda3/envs/hazel/lib/python3.9/site-packages/networkx/drawing/nx_agraph.py", line 287, in pygraphviz_layout
    A.layout(prog=prog, args=args)
File "/Users/tarunmamidi/opt/anaconda3/envs/hazel/lib/python3.9/site-packages/pygraphviz/agraph.py", line 1476, in layout
    data = self._run_prog(prog, " ".join([args, "-T", output_fmt]))
File "/Users/tarunmamidi/opt/anaconda3/envs/hazel/lib/python3.9/site-packages/pygraphviz/agraph.py", line 1397, in _run_prog
    raise OSError(b"".join(errors).decode(self.encoding))
```

Here's the snippet used for this, where `final_graph` is a DiGraph

```
nx.draw_networkx(
                final_graph,
                pos=graphviz_layout(final_graph.reverse(), prog="dot"),
                node_color=color_map,
                with_labels=True,
                arrows=True,
                labels=names,
            )
```

### Expected Behavior

When I use `spring_layout` using the below snippet, it works

```
nx.draw_networkx(
                final_graph,
                pos=nx.spring_layout(final_graph.reverse()),
                node_color=color_map,
                with_labels=True,
                arrows=True,
            )
```

![image](https://user-images.githubusercontent.com/41593805/154408953-ebf99b2e-e9ba-4787-8648-ec2517b0cd8f.png)

### Steps to Reproduce

`from networkx.drawing.nx_agraph import graphviz_layout`
 I'm using `nx.DiGraph`

Nodes = ['HP:0000001', 'HP:0001510', 'HP:0000118', 'HP:0000002', 'HP:0001507', 'HP:0004322']

Edges = [('HP:0001510', 'HP:0001507', {}), ('HP:0000118', 'HP:0000001', {}), ('HP:0000002', 'HP:0001507', {}), ('HP:0001507', 'HP:0000118', {}), ('HP:0004322', 'HP:0000002', {}), ('HP:0004322', 'HP:0001510', {})]

### Environment

Python version: 3.9.7
NetworkX version: 2.6.3

### Additional context

![image](https://user-images.githubusercontent.com/41593805/154409468-c73b7304-1549-43e2-830d-5d51d156187d.png)

I need to draw a dot layout like this. Also, the above error only shows up for only certain nodes.

Any help is greatly appreciated!

Thank you!

**Comment by dschult** [comment]
I can reproduce the error -- with the nodes and edges you provide. And I also added a node "short stature" and that worked fine too.  It looks like `dot` is creating the error. Perhaps you should save the graph to a dot file with:
```python
import pygraphviz
pyG = pygraphviz.ADiGraph()
pyG.add_edges_from(G.edges())
pyG.add_nodes.from(G)
pyG.write("tst.dot")
!dot tst.dot    # or exit python and run dot tst.dot from your shell.
```

**Comment by tkmamidi** [comment]
Is there a way that I can bypass saving files? This is my implementation in a streamlit app

```
plot = nx.draw_networkx(
                final_graph,
                pos=graphviz_layout(final_graph.reverse(), prog="dot"),
                node_color=color_map,
                with_labels=True,
                arrows=True,
                labels=names,
            )
st.set_option("deprecation.showPyplotGlobalUse", False)
st.pyplot(plot)
```

**Comment by rossbar** [comment]
Hmm I can't reproduce this - the following works fine for me:

```python
>>> import networkx as nx
>>> G = nx.DiGraph()
>>> G.add_nodes_from(
...     ["HP:0000001", "HP:0001510", "HP:0000118", "HP:0000002", "HP:0001507", "HP:0004322"]
... )
>>> G.add_edges_from(
...     [
...         ("HP:0001510", "HP:0001507", {}),
...         ("HP:0000118", "HP:0000001", {}),
...         ("HP:0000002", "HP:0001507", {}),
...         ("HP:0001507", "HP:0000118", {}),
...         ("HP:0004322", "HP:0000002", {}),
...         ("HP:0004322", "HP:0001510", {}),
...     ]
... )
>>> nx.drawing.nx_agraph.graphviz_layout(G.reverse(), prog="dot")
{'HP:0000001': (119.25, 306.0),
 'HP:0001510': (55.245, 90.0),
 'HP:0000118': (119.25, 234.0),
 'HP:0000002': (183.25, 90.0),
 'HP:0001507': (119.25, 162.0),
 'HP:0004322': (119.25, 18.0)}
```

I get the same result with both `pygraphviz` versions 1.7 and 1.9. What are the versions of `pygraphviz` and `Graphviz` in your environment?

**Comment by tkmamidi** [comment]
```
  - graphviz=2.50.0
  - pygraphviz=1.8
```

**Comment by tkmamidi** [comment]
I updated the `pygraphviz` version to `1.9` and it still isn't working for me :( 

Is it something to do with plotting it?

**Comment by tkmamidi** [comment]
> 

I have a `networkx` composed DiGraph (merged multiple graphs) and it can't write as a dot file
command - `final_graph.write("tst.dot")`
Error - `AttributeError: 'DiGraph' object has no attribute 'write'`

**Comment by dschult** [comment]
I apologize for my misleading comment earlier. I can *not* reproduce this issue.  Though I haven't tried using the version of Graphviz 2.50.0.    Perhaps you should try using an earlier Graphviz version to see if it makes a difference.

My point with suggesting that you write to a dot file and use command lines is so you can debug whether it is a GraphViz problem or a pygraphviz problem.  I don't suggest you use that for your main workflow. 

Both @rossbar and I have found that your requested workflow works for our versions of pygraphviz and graphviz without errors. So it is starting to look like an issue with this new version of Graphviz.

**Comment by tkmamidi** [comment]
If you don't mind, can you please share your versions? This was my initial environment
```
channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.10.0
  - pandas=1.3.4
  - numpy=1.21.4
  - matplotlib=3.5.0
  - progressbar2=3.53.1
  - pyyaml=6.0
  - graphviz=2.50.0
  - pygraphviz=1.8
  - pip
  - pip:
    - obonet==0.3.0
    - networkx==2.6.3
    - decorator==5.1.0
    - streamlit==1.4.0
```

**Comment by rossbar** [comment]
Here's the output of `pip list` for the env:

<details>
  <summary>my env</summary>
<pre>
  Package                       Version     Editable project location
----------------------------- ----------- -------------------------
alabaster                     0.7.12
argon2-cffi                   21.3.0
argon2-cffi-bindings          21.2.0
asttokens                     2.0.5
attrs                         21.4.0
Babel                         2.9.1
backcall                      0.2.0
beautifulsoup4                4.10.0
black                         22.1.0
bleach                        4.1.0
certifi                       2021.10.8
cffi                          1.15.0
cfgv                          3.3.1
charset-normalizer            2.0.12
click                         8.0.3
codecov                       2.1.12
coverage                      6.3.1
cycler                        0.11.0
debugpy                       1.5.1
decorator                     5.1.1
defusedxml                    0.7.1
distlib                       0.3.4
docutils                      0.17.1
entrypoints                   0.4
executing                     0.8.2
filelock                      3.5.0
fonttools                     4.29.1
identify                      2.4.10
idna                          3.3
imagesize                     1.3.0
iniconfig                     1.1.1
ipykernel                     6.9.1
ipython                       8.0.1
ipython-genutils              0.2.0
ipywidgets                    7.6.5
jedi                          0.18.1
Jinja2                        3.0.3
jsonschema                    4.4.0
jupyter-client                7.1.2
jupyter-core                  4.9.1
jupyterlab-pygments           0.1.2
jupyterlab-widgets            1.0.2
kiwisolver                    1.3.2
lxml                          4.7.1
MarkupSafe                    2.0.1
matplotlib                    3.5.1
matplotlib-inline             0.1.3
mistune                       0.8.4
mypy                          0.931
mypy-extensions               0.4.3
nb2plots                      0.6
nbclient                      0.5.11
nbconvert                     6.4.2
nbformat                      5.1.3
nest-asyncio                  1.5.4
networkx                      2.7rc1.dev0 /home/ross/repos/networkx
nodeenv                       1.6.0
notebook                      6.4.8
numpy                         1.22.2
numpydoc                      1.2
packaging                     21.3
pandas                        1.4.1
pandocfilters                 1.5.0
parso                         0.8.3
pathspec                      0.9.0
pexpect                       4.8.0
pickleshare                   0.7.5
Pillow                        9.0.1
pip                           21.3.1
platformdirs                  2.5.0
pluggy                        1.0.0
pre-commit                    2.17.0
prometheus-client             0.13.1
prompt-toolkit                3.0.28
ptyprocess                    0.7.0
pure-eval                     0.2.2
py                            1.11.0
pycparser                     2.21
pydata-sphinx-theme           0.8.0
pydot                         1.4.2
Pygments                      2.11.2
pygraphviz                    1.9
pyparsing                     3.0.7
pyrsistent                    0.18.1
pytest                        7.0.1
pytest-cov                    3.0.0
pytest-mpl                    0.14.0
python-dateutil               2.8.2
pytz                          2021.3
pyupgrade                     2.31.0
PyYAML                        6.0
pyzmq                         22.3.0
requests                      2.27.1
scipy                         1.8.0
Send2Trash                    1.8.0
setuptools                    60.5.0
six                           1.16.0
snowballstemmer               2.2.0
soupsieve                     2.3.1
Sphinx                        4.4.0
sphinx-gallery                0.10.1
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
sphinxtesters                 0.2.3
stack-data                    0.2.0
terminado                     0.13.1
testpath                      0.5.0
texext                        0.6.6
tokenize-rt                   4.2.1
toml                          0.10.2
tomli                         2.0.1
tornado                       6.1
traitlets                     5.1.1
typing_extensions             4.1.1
urllib3                       1.26.8
virtualenv                    20.13.1
wcwidth                       0.2.5
webencodings                  0.5.1
wheel                         0.37.1
widgetsnbextension            3.5.2
</pre>
</details>

My Python version is 3.10.2 and Graphviz version is 2.50.0

A couple other things come to mind:
 1. `pygraphviz` 1.8 was yanked from pypi and should no longer be available. If you have 1.8 installed you should definitely upgrade (you said you tried with 1.9 as well)
 2. If you're installing pygraphviz with conda, make sure you're installing from the `conda-forge` channel as the packages on the main channel are known to be unreliable. See [the pygraphviz install docs](https://pygraphviz.github.io/documentation/stable/install.html) for details.

**Comment by tkmamidi** [comment]
Thank you so much!
I really appreciate you helping out!

I'm seeing something really strange here and could use your help to debug. This is the script that you can run to reproduce the same error.

```
import networkx as nx
import obonet
import matplotlib.pyplot as plt
plt.rcParams.update({'figure.max_open_warning': 0})
from networkx.drawing.nx_agraph import graphviz_layout

def get_graph(graph, hpos):
            final_graph = nx.MultiGraph()
            for term in hpos:
                sub_graph = nx.subgraph(graph, nx.predecessor(graph, term))
                final_graph = nx.compose(sub_graph, final_graph)
            final_graph = nx.DiGraph(final_graph)
            return final_graph

def plot_graph(final_graph, terms):
    color_map = ["red" if node in terms else "green" for node in final_graph]
    plot = nx.draw_networkx(
                final_graph,
                pos=graphviz_layout(final_graph.reverse(), prog="dot"),
                node_color=color_map,
                with_labels=True,
                arrows=True,
            )
    return plot

def main():
    graph = obonet.read_obo("https://raw.githubusercontent.com/obophenotype/human-phenotype-ontology/master/hp.obo")
    #Change the figure size
    plt.figure(figsize=[60, 20])
    plt.suptitle('HPO terms on ontology', fontsize=35, fontweight='bold')
    terms = ['HP:0000717', 'HP:0002579', 'HP:0001263', 'HP:0000365', 'HP:0001250', 'HP:0004322', 'HP:0004755']

    final_graph = get_graph(graph, terms)
    plot_graph(final_graph, terms)
    plt.savefig("figures.png")
    plt.clf()
    return None

if __name__ == '__main__':
    main()
```

PS - The script works fine if you remove `HP:0004322` from the list `terms`.

Again, thank you so much for your help!

**Comment by tkmamidi** [comment]
I think I figured it out. Looks like the below command is not working as it is supposed to
`final_graph = nx.DiGraph(final_graph)`

I had this workaround and it worked
```
G = nx.DiGraph()
G.add_nodes_from(final_graph.nodes())
G.add_edges_from(final_graph.edges())
del final_graph
```

I don't think this is a version issue though.

I really appreciate your help in this!
