### ISSUE TITLE
networkx.drawing.nx_pydot.read_dot parses dot files incorrectly

### ISSUE THREAD

**Issue by nico5300** [networkx/networkx#5353]
I tried to load the dot file of a control flow graph created by LLVM down below into a networkx graph using this code:
```python
import networkx.drawing.nx_pydot as nxp
import networkx as nx
g = nx.read_dot("/path/to/file/cfg.dot")
print(g.nodes)
```
When looking at the dotfile down below one would assume three nodes being connected by two edges. But in reality one more node gets created with the label "\\\\n". 

### Steps to Reproduce

Load following dotfile with the code above and print the node list:
```dot
digraph "CFG for 'fn_1140' function" {
	label="CFG for 'fn_1140' function";

	Node0x5563aaa6daa0 [shape=record,color="#b70d28ff", style=filled, fillcolor="#b70d2870",label="{entry_fn_1140}"];
	Node0x5563aaa6daa0 -> Node0x5563aaa6f850;
	Node0x5563aaa6dc60 [shape=record,color="#b70d28ff", style=filled, fillcolor="#b70d2870",label="{exit_fn_1140}"];
	Node0x5563aaa6f850 [shape=record,color="#b70d28ff", style=filled, fillcolor="#b70d2870",label="{bb_1140}"];
	Node0x5563aaa6f850 -> Node0x5563aaa6dc60;
}
```

When removing the newline immediately preceeding the closing curly brace, we get the correct graph. Also when swapping the last node definition with the last edge definition.

### Environment

Python version: 3.10
NetworkX version: 2.6.3
Pydot version: 1.4.2

**Comment by rossbar** [comment]
I suspect this is related to pydot/pydot#277. NetworkX has had to xfail the `nx_pydot` tests due to the pydot/pyparsing issues. You can try installing the older version of `pyparsing` in your environment, e.g.

```
pip install pyparsing==2.4.7
pip install pydot networkx
```

Though this certainly isn't a long term solution. Unfortunately I don't think there's anything NX can do unless/until this is fixed upstream.

**Comment by nico5300** [comment]
Ah I see! Thanks for the workaround :)
I'll close the issue then.
