### ISSUE TITLE
Urgent GSoC revisions are needed.

### ISSUE THREAD

**Issue by henrykironde** [networkx/networkx#5358]
Confirmation needed: https://github.com/numfocus/gsoc/issues/396
Google is not happy with our idea lists.
 
 
1. Be sure to include whether the project is a 175 hour (medium sized) or 350 hour (large project). If it can be either, please state that-per idea. 
2. `Your Ideas Page URL should be accessible to all and not require login. --- (Covered)`
3. As we state in the Defining a Project Idea List section of the Mentor guide, please provide the following information for each idea:
a) a project title/description 
b) more detailed description of the project (2-5+ sentences) 
c) expected outcomes 
d) skills required/preferred 
e) possible mentors 
f) expected size of project (175 or 350 hour) 
g) an easy, medium or hard difficulty rating of each project.
 
 
If you want to be selected this year I strongly suggest you make sure your Project Ideas list meets the above requirements ASAP.

**Comment by MridulS** [comment]
We conform with the Google requirements :)
