### ISSUE TITLE
Error in MultiDiGraph.edges(nbunch)

### ISSUE THREAD

**Issue by alejandro-gitt** [networkx/networkx#5363]
The documentation  for 

> networkx.MultiDiGraph.edges 

says: 

> Parameters:
> nbunch: single node, container, or all nodes (default= all nodes)
> "The view will only report edges **incident** to these nodes."

Perhaps **incident** is incorrect, as it is the opposite behavior (as seen in the example in networkx):
```
list(G.edges([0, 2]))
[(0, 1), (2, 3)]
```
Where G.edges([0,2]) returns the edges that comes **out** of the nodes 0 and 2.

**Comment by dschult** [comment]
You are correct, that is a documentastion error. The "Latest" documentation (for version 2.7 due to be released any day now) has the documentation for `nbunch` fixed to be:  "The view will only report edges from these nodes."
Thanks for the report!
