### ISSUE TITLE
Avoid black formatting when using git blame

### ISSUE THREAD

**Issue by jarrodmillman** [networkx/networkx#5382]
We should look into adding a `.git-blame-ignore-revs` file for using with `git blame`:
https://black.readthedocs.io/en/stable/guides/introducing_black_to_your_project.html#avoiding-ruining-git-blame

Looks like GH may also soon support it:
https://github.com/github/feedback/discussions/5033

**Comment by MridulS** [comment]
They have a public beta open. Should I ask them to put us in there?
