### ISSUE TITLE
min_weight_matching gives incorrect results

### ISSUE THREAD

**Issue by water-vapor** [networkx/networkx#5388]
Consider the following graph:
```python
G = nx.Graph()
G.add_edge(1, 4, weight=2)
G.add_edge(2, 3, weight=2)
G.add_edge(1, 2, weight=1)
G.add_edge(3, 4, weight=4)
nx.min_weight_matching(G)
```

### Current Behavior

The program returns `{(2, 1), (4, 3)}`
### Expected Behavior

There are two maximal matchings in the graph, (1,2)(3,4) with weight 1+4=5, and (1,4)(2,3) with weight 2+2=4. The minimum weight maximal matching should be (1,4)(2,3) which has weight 4.
### Steps to Reproduce

Run the code provided
### Environment

Python version: 3.9
NetworkX version: 2.7.1

### Additional context

From the documentation and the code, `min_weight_matching` is simply taking the reciprocal of the weights and uses `max_weight_matching`. This logic seems to be faulty in this example: 1/1+1/4>1/2+1/2.

**Comment by dschult** [comment]
Thanks!   You are correct.  

That is a faulty way of thinking about turning a min problem into a max problem. Maximizing over sums of reciprocal weights does not minimizing correctly.  Other options include negating (if the problem doesn't have trouble with negative weights -- which min_weight_matching does not... but shortest_path does). Or perhaps a more robust approach would be to subtract the weights from a little bigger than the maximum of all weights.

**Comment by dschult** [comment]
Looking into this bug, I'm pretty sure the keyword argument `maxcardinality` should be deprecated and set to True inside the function. What would `min_weight_matching` mean for `maxcardinality=False`?  It would mean the empty matching or maybe the matching that is just the lowest weight edge. 

I propose that we deprecate `maxcardinality`, and inside the function where we call `max_weight_matching` on the newly weighted edges, we set `maxcardinality=True`.  Luckily this code was only merged Summer 2021 so not too many people will be inconvenienced by this deprecation.
