### ISSUE TITLE
Bipartite projection on nodes with duplicates raises ZeroDivisionError

### ISSUE THREAD

**Issue by aaronzo** [networkx/networkx#5403]
When calculating the 'top' nodes for the `weighted_projected_graph` [here](https://github.com/networkx/networkx/blob/6a0b4faf09ec9d3d40ad93e2ec9b431d6bab5dc4/networkx/algorithms/bipartite/projection.py#L192), if the user submits a list with duplicates, the function either gives incorrect results or a `ZeroDivisionError` when `ratio=True`. If the user first checks their set with `is_bipartite_node_set`. this returns `True`:
```python
import networkx as nx
from networkx.algorithms import bipartite

B = nx.complete_bipartite_graph(2,2)
a = [0,1] * 2

bipartite.is_bipartite_node_set(B, a) # returns True

bipartite.weighted_projected_graph(B, a, ratio=True) # raises ZeroDivisionError
```
I can understand that in `weighted_projected_graph` we burden the user with supplying a valid node set to avoid the inefficiency of converting a `list` into a `set`, but I do think anything that passes `is_bipartite_node_set` should definitely give correct and error-free answers when passed to the projection function, else this behaviour is surprising.

Of course in the example above, it's obvious I've made duplicates but in real use-cases the node set could come through a chain of functions and the user is none the wiser.

**Comment by MridulS** [comment]
Thanks for reporting this @aaronzo!
> I do think anything that passes is_bipartite_node_set should definitely give correct and error-free answers when passed to the projection function, else this behaviour is surprising.

I agree, this can be surprising. How about we raise an `Error` for `is_bipartite_node_set` if the user passes in a node list which has duplicates. At least then `is_bipartite_node_set` fails correctly for the input list of nodes. A check like `if len(nodes) > len(S): raise ...`

https://github.com/networkx/networkx/blob/6a0b4faf09ec9d3d40ad93e2ec9b431d6bab5dc4/networkx/algorithms/bipartite/basic.py#L132-L135

On that note there are probably a bunch of places where we silently change the incoming nodes list to a set and get rid of the duplicates. I'm not sure if we should do this everywhere.

**Comment by aaronzo** [comment]
@MridulS I agree with the proposal, and it's probably overkill to check sets within the functions themselves - after all, the function doesn't check the nodeset is a valid partitioning of the graph either. Perhaps alongside your suggestion of checking sets in `is_bipartite_node_set`, we could add a note in the docstring for `weighted_projected_graph`
(and any other functions we think this might a effect); Something like:
```
    nodes : set or iterable
        Distinct nodes to project onto (the "bottom" nodes).
```
over [here](https://github.com/networkx/networkx/blob/6a0b4faf09ec9d3d40ad93e2ec9b431d6bab5dc4/networkx/algorithms/bipartite/projection.py#L134)

and maybe we could add an error like
```
n_top = float(len(B) - len(nodes))
if n_top < 1:
   raise ValueError("The nodeset to project onto has size >= the graph size. Is it a valid partition without duplicates?")
```
which is inexpensive to check
