### ISSUE TITLE
Is `extrema_bounding` intended to be a public function?

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#5415]
I mentioned this in #5402 but I think the point deserves it's own issue:

> Looking at extrema_bounding more carefully, I wonder if it was ever intended to be called directly? It seems like it's mostly used internally for the supported measures mentioned in the docstring and extrema_bounding itself is untested!

There are currently two ways of computing the bounds for the various distance measures. Take the `diameter` metric for example:
 1. Use `extrema_bounding` directly: `nx.extrema_bounding(G, compute="diameter")`
 2. Call `diameter` with the `usebounds` kwarg: `nx.diameter(G, usebounds=True)`

The latter simply calls `extrema_bounding` under-the-hood:

https://github.com/networkx/networkx/blob/6a0b4faf09ec9d3d40ad93e2ec9b431d6bab5dc4/networkx/algorithms/distance_measures.py#L296-L297

To me, the API for option `2.` is preferable to `1.`. This, along with the fact that `extrema_bounding` is neither tested nor has an `Examples` section in the docstring made me question whether it was ever intended to be publicly exposed (as `nx.extrema_bounding`) or only intended for internal use in `distance_measures`.

I was just curious whether there are explicit reasons for this and/or any other opinions. At first glance I would be tempted to make `extrema_bounding` private (deprecate from the main nx namespace) and stick with the `usebounds` approach. Either way, `extrema_bounding` should be tested (and intended usage examples would be great if it stays public) and the `usebounds` kwarg needs to be documented (unless it's decided to remove that instead...)

**Comment by dschult** [comment]
I'm pretty convinced that `extrema_bounding` should be a private function. Looking at the history, I don't think we/I looked very carefully at the naming convention for private/public functions at this time. If it wasn't in `__all__` I thought of it as private. It would be good to get the naming and deprecation changes done before v2.8, but we do also needs tests. Not sure if that is needed before v2.8, but if they are easy and quick, yes.
