### ISSUE TITLE
Future Deprecation: replace utils.pairwise with itertools equivalent

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#5423]
Good news! The `pairwise` function has been included in itertools, so the home-made version (which, according to the comments, originated from an itertools recipe) in `utils.misc` can be replaced with the itertools version.

This change can't be made quite yet however as `itertools.pairwise` [was only added in Python 3.10](https://docs.python.org/3/library/itertools.html#itertools.pairwise), so NX needs to wait until 3.10 is the minimum supported version.

I thought I'd open an issue to track this since I don't think automatic linters like `pyupgrade` will catch this particular case.

**Comment by MridulS** [comment]
> This change can't be made quite yet however as itertools.pairwise [was only added in Python 3.10](https://docs.python.org/3/library/itertools.html#itertools.pairwise), so NX needs to wait until 3.10 is the minimum supported version.

Well that's going to be [atleast April 2024](https://numpy.org/neps/nep-0029-deprecation_policy.html) :)

PS: While typing this I thought ah 4 years away but well 😅

**Comment by MridulS** [comment]
BTW it looks like the stdlib `pairwise` doesn't do the cyclic bit and our implementation does. So I think we still need to keep this around :/

**Comment by MridulS** [comment]
I think we need to keep our util function around as our `pairwise` also implements cyclic version. We would need a utility function in any case.
