### ISSUE TITLE
Deprecate or improve `utils.misc.to_tuple`

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#5426]
`to_tuple` is a simple function that recursively converts nested lists to tuples. It is only used in one place within networkx in the `json_graph` module:

https://github.com/networkx/networkx/blob/2e490a307b97518c98066c058136981dcae95606/networkx/readwrite/json_graph/node_link.py#L167

The usage here makes sense as there's a potential use-case for a node that is stored in json as a nested list (though this case isn't tested). However, it should be noted that this specific usage depends on the fact that `to_tuple` is a no-op for every input *except* Python lists.

Given the fact that it is only used once internally, has a relatively specific use-case, and doesn't seem to have any other obvious connection to common operations in NetworkX, I would propose to do the following:
 - Move the definition over to the `json_graph.node_link` module as a private function, and
 - Deprecate the public function `nx.utils.misc.to_tuple`

If deprecating/removing the function seems too strong, then another option would be to improve the documentation and testing. Documentation should have usage examples to illustrate where it might be useful and also highlight the fact that the function is a no-op for every input except lists.

At face value I'd vote for deprecation because I don't see a strong connection to the rest of the library, but please share your opinion and any other ideas for how to handle this!

**Comment by rossbar** [comment]
Playing devil's advocate against myself... one argument against deprecation is there isn't really a built-in one-liner or simple fix that we can point to instead (at least off the top of my head). I still lean towards deprecation since the behavior is so specific, but definitely another angle to consider!

**Comment by dschult** [comment]
I agree that this makes sense as a private function in the `json_graph` code. And we can deprecate the public version and move the code to the new place.
