### ISSUE TITLE
DOC: scipy conf. citation links spin forever

### ISSUE THREAD

**Issue by ChrisKeefe** [networkx/networkx#5433]
The PDF and BibTeX links [here](https://networkx.org/documentation/latest/#citing) point to conference.scipy.org endpoints that never resolve. This is probably someone else's problem ™️, and I'm hoping you folks know who to check in with for a new URL or an upstream fix.

### Current Behavior
When I click the link, the target page never resolves, resulting in a Connection Timed Out error after a couple of minutes.

### Expected Behavior
I get a PDF or a BibTex file.

### Steps to Reproduce
Visit the citations section linked above, and click one of the affected links.

### Environment
OpenSUSE, Firefox/Chromium

**Comment by MridulS** [comment]
Yeah that's not good. Thanks for the report!

**Comment by aterrel** [comment]
Server has been restored. We should move these though as that server is on an old cluster that we want to migrate away from.

**Comment by MridulS** [comment]
Thanks @aterrel!
