### ISSUE TITLE
Condensation function: mapping and members attributes are hardly accessible.

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#5449]
### Discussed in https://github.com/networkx/networkx/discussions/5446

<div type='discussions-op-text'>

<sup>Originally posted by **Moss4t** March 31, 2022</sup>
In [this](https://networkx.org/documentation/stable/_modules/networkx/algorithms/components/strongly_connected.html#condensation) documentation, I found how to access mapping attribute on graph C: C.graph['mapping']. But still no idea how to access the dictionary for found SCCs and corresponding nodes (still researching). Please make the description more clear on how to use this function.
I'm a beginner in python, but I'm already thankful for the makers of the code. It helps a lot!</div>

Currently we don't have any example how to access the SCCs and mapping from the `condensation` function. We should add an example in the function documentation.

An example is present in the discussion.

**Comment by ManasviGoyal** [comment]
Hi. I am an Outreachy applicant. Can I work on this issue?

**Comment by kpetridis24** [comment]
I was already working on it btw :) But if you want we could cooperate or provide examples both. It's a documentation related issue so i think that if we both provided some examples it would be ok

**Comment by MridulS** [comment]
There is example available at https://github.com/networkx/networkx/discussions/5446#discussioncomment-2477595 but feel free to change it or add more.

@ManasviGoyal please do checkout https://github.com/networkx/outreachy/ too.

**Comment by kpetridis24** [comment]
@MridulS Is there a place that code-examples are meant to be placed except for the ''example' dir? For this specific issue, the goal is to provide examples of how to access the returning graph. Where should the examples be placed exactly?

**Comment by kpetridis24** [comment]
oh ok nice. So it's all placed inside the documentation.

**Comment by kpetridis24** [comment]
@MridulS Added 2 examples and created a PR. Heading to find another issue to solve.

**Comment by aliveevie** [comment]
#5449

**Comment by MridulS** [comment]
fixed in https://github.com/networkx/networkx/pull/5452
