### ISSUE TITLE
Improve Examples Section of ```set_edge_attributes```

### ISSUE THREAD

**Issue by 0ddoes** [networkx/networkx#5463]
While looking at the ```set_edge_attributes``` function, it doesn't include an example using multigraphs. As the ```values``` argument is passed different for non-multigraphs and multigraphs, I figured having a small example will show the difference easily. 

NetworkX version: 2.6.2

**Comment by rossbar** [comment]
I agree that a multigraph example would be a nice improvement. The fact that `values` expects the dict keyed by 3-tuples is definitely worth highlighting.

**Comment by 0ddoes** [comment]
Okay thanks! I will try to include an example and add a PR. Can you guide me on which file in the repo to be edited?

**Comment by rossbar** [comment]
> Can you guide me on which file in the repo to be edited?

Check out [our new contributor FAQ](https://networkx.org/documentation/latest/developer/new_contributor_faq.html#q-i-want-to-work-on-a-specific-function-how-do-i-find-it-in-the-source-code) which will hopefully give you some ideas for how to navigate the code base!
