### ISSUE TITLE
Issues with ```to_numpy_array``` outputs

### ISSUE THREAD

**Issue by 0ddoes** [networkx/networkx#5487]
Sir, I tried working on the issue. I am finding a few other issues with the results obtained. I have summarised what I get below:

I found a few issues with ```to_numpy_array``` while I worked on Issue #5255. Attaching the part of the Comment below: 

**MultiDiGraph**

In this example I wanted to show the significance of the other arguments : ```multigraph_weight``` and structured array ```dtype```.

```python
>>> G = nx.MultiDiGraph()
>>> edges = [(0,1), (0,1), (1,0), (2,2), ("love", "hate"), (1,"love")]
>>> G.add_edges_from(edges)
[0, 1, 0, 0, 0, 0]
>>> nx.to_numpy_array(G, nodelist=[0, 1, 2])
array([[0., 2., 0.],
       [1., 0., 0.],
       [0., 0., 1.]])
>>> 
>>> 
>>> 
>>> attributes = {(0,1,0): {"weight": 20, "cost": 5}, (2,2,4): {"weight": 10, "cost": 3}, (0,1,1): {"cost":5}}
>>> nx.set_edge_attributes(G, attributes)
>>> 
>>> dtype = np.dtype([("weight", float), ("cost", int)])
>>> A = nx.to_numpy_array(G, nodelist=[0, 1, 2], dtype=dtype, weight=None, multigraph_weight = sum)
>>> A["cost"]
array([[0, 2, 0],
       [1, 0, 0],
       [0, 0, 1]])
```

There are 2 edges between 0 and 1 and that reflects in the Adjacency matrix.  Also document can be edited to include that ```multigraph_weight```  will take values (sum, min , max). 

As the dtype is structured Array, according to documentation I gave **None**. But the output is still the previous Adjacency Matrix. It doesn't show the values of **Attribute "Cost"**.  

To tackle this issue, I tried other ways. And changed it to just any Attribute name first (here) "cost".

```python
>>> A = nx.to_numpy_array(G, dtype=dtype, weight="cost", multigraph_weight = sum)
>>> A["cost"]
array([[ 0, 10,  0,  0,  0],
       [ 1,  0,  0,  1,  0],
       [ 0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0]])
```

Although it took sum of cost attribute for multiple edges between (0,1), it didn't show the value for (2,2) Self edge. Does this not work for a Self edge? 

This output was also seen:

```python
>>> A = nx.to_numpy_array(G, dtype=dtype, weight="cost", multigraph_weight = sum)
>>> A["cost"]
array([[ 0, 10,  0,  0,  0],
       [ 1,  0,  0,  1,  0],
       [ 0,  0,  1,  0,  0],
       [ 0,  0,  0,  0,  1],
       [ 0,  0,  0,  0,  0]])
```

Even if "weight" is accessed, the previous values of "costs" are given. On displaying A :

```python
>>> A
array([[( 0.,  0), (10., 10), ( 0.,  0), ( 0.,  0), ( 0.,  0)],
       [( 1.,  1), ( 0.,  0), ( 0.,  0), ( 1.,  1), ( 0.,  0)],
       [( 0.,  0), ( 0.,  0), ( 1.,  1), ( 0.,  0), ( 0.,  0)],
       [( 0.,  0), ( 0.,  0), ( 0.,  0), ( 0.,  0), ( 1.,  1)],
       [( 0.,  0), ( 0.,  0), ( 0.,  0), ( 0.,  0), ( 0.,  0)]],
      dtype=[('weight', '<f8'), ('cost', '<i8')])
```

Both values got assigned with the cost Attribute Value, as weights was given as "cost" at the start. But if the weight is given as a tuple ("weight", "cost"), it gives similar to adjacency Matrix. Both values of the tuple get assigned with the number of edges in between. 

```python
>>> A = nx.to_numpy_array(G, dtype=dtype, weight= ("weight","cost"), multigraph_weight = sum)
>>> A
array([[(0., 0), (2., 2), (0., 0), (0., 0), (0., 0)],
       [(1., 1), (0., 0), (0., 0), (1., 1), (0., 0)],
       [(0., 0), (0., 0), (1., 1), (0., 0), (0., 0)],
       [(0., 0), (0., 0), (0., 0), (0., 0), (1., 1)],
       [(0., 0), (0., 0), (0., 0), (0., 0), (0., 0)]],
      dtype=[('weight', '<f8'), ('cost', '<i8')])
```

I hope I am using the function right. I checked the code again but I found some of these issues persist. 

I noticed that the current example in documentation with the structured ```dtype``` (at the end) is not providing the same output as well. 

Can you please guide me on how to proceed forward?

_Originally posted by @0ddoes in https://github.com/networkx/networkx/issues/5255#issuecomment-1086009899_

**Comment by jarrodmillman** [comment]
What version of networkx are you using?

**Comment by 0ddoes** [comment]
2.6.2 ... Should I install the latest version? Ig its 2.7.1?

**Comment by jarrodmillman** [comment]
You should work off the main branch.  There is some information about how to contribute to NetworkX here:
- https://github.com/networkx/networkx/blob/main/CONTRIBUTING.rst

**Comment by rossbar** [comment]
`to_numpy_array` doesn't support multiple edge attributes for MultiGraphs. If you run your example on the development branch, you should see something like:

```python
>>> A = nx.to_numpy_array(G, dtype=dtype, weight=None, multigraph_weight=sum)
Traceback (most recent call last)
   ...
NetworkXError: Structured arrays are not supported for MultiGraphs
```

**Comment by 0ddoes** [comment]
Okay! Thanks for the clarifications :)
