### ISSUE TITLE
Community Detection Algorithms (migrated from Trac #557)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#549]
Original ticket https://networkx.lanl.gov/trac/ticket/557
Reported 2011-05-20 by @bjedwards, assigned to @hagberg.

This is a ticket to track the progress of community detection algorithms for Google Summer of Code 2011

Links to other info about this ticket.

proposal: http://cs.unm.edu/~bedwards/gsoc2.html

blog: http://gsocnetworkx.blogspot.com/

**Comment by hagberg** [comment]
See #764
