### ISSUE TITLE
Improving Contribution Guidelines

### ISSUE THREAD

**Issue by Lukong123** [networkx/networkx#5492]
Hello everyone, I am a newbie to the networkx repository, when following the contribution guidelines I stepped on `pre-commit install` when I ran this command it returned an error because I never had it installed on my computer since I never knew how important it was I did not immediately research on how to install it, but later on I used `pip install pre-commit` before going ahead with `pre-commit install`. I was suggesting that we add `pip install pre-commit` or `conda install -c conda-forge pre-commit`  before adding the command `pre-commit install`
@MridulS @rossbar @dschult I will love to get your thoughts on this. 
I am using Ubuntu and I don't know if this error was faced by anyone else or not.

**Comment by dschult** [comment]
I think that is a good idea.  It could be simply:  install pre-commit using pip or conda so you don't have to get into too much detail. but I guess detail is OK if it is still readable.

**Comment by Lukong123** [comment]
> I think that is a good idea. It could be simply: install pre-commit using pip or conda so you don't have to get into too much detail. but I guess detail is OK if it is still readable.

Okay sir thanks, I will love to work on it.

**Comment by rossbar** [comment]
From the follow-up discussion in #5493 I think we determined that all of the info re: `pre-commit` was in the contributor guide, though it requires careful attention as there are multiple steps.

Given this, I will close the issue. I think it is indeed worthwhile to take another look at the contributor guide, perhaps after soliciting more feedback about pain points for new contributors. Thanks for bringing this up @Lukong123 !

**Comment by Lukong123** [comment]
> From the follow-up discussion in #5493 I think we determined that all of the info re: `pre-commit` was in the contributor guide, though it requires careful attention as there are multiple steps.
> 
> Given this, I will close the issue. I think it is indeed worthwhile to take another look at the contributor guide, perhaps after soliciting more feedback about pain points for new contributors. Thanks for bringing this up @Lukong123 !

Thank you, sir.
