### ISSUE TITLE
Examples for Centrality Algorithms

### ISSUE THREAD

**Issue by 0ddoes** [networkx/networkx#5535]
Except for the 4 ```EigenVector``` Centrality Measure Algorithms, there aren't any simple basic Examples for the rest of the **Centrality measures**. I would like to work on some. If alright, can I try to include real datasets analysis in the Examples and put the link to the dataset in the documentation?

**Comment by MridulS** [comment]
The correct place to put an example like this would be in the https://github.com/networkx/nx-guides repository. We could have a notebook about various centrality measures explained via a real world dataset.

**Comment by 0ddoes** [comment]
Yes right! Actually I am working on one now. I am trying to include plots as well to make it more interesting. I will put the updates soon :)

**Comment by 0ddoes** [comment]
@MridulS Could you take a look at this [PR](https://github.com/networkx/nx-guides/pull/72). I have tried to make a notebook on the Issue, however my plots are not showing in the Output. Could you please help me in solving it?

**Comment by rossbar** [comment]
Since this is being followed up on in networkx/nx-guides#72, I'll close this here.
