### ISSUE TITLE
Export `is_tournament` to main namespace?

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#5542]
Currently all of the functions defined in the `tournament` module must be accessed through the `tournament` namespace, i.e.

```python
from networkx.algorithms import tournament
```

This makes sense for many of the functions because they require the input graph to be a tournament graph and the `tournament` namespace is an effective way of enforcing this policy without having to add an `is_tournament` validation to every function. There are other cases (e.g. `tournament.is_strongly_connected`) where again the namespace is certainly the correct organization.

However, I think there is an argument for exporting the `is_tournament` function to the main namespace so that users can call `nx.is_tournament(G)` rather than `tournament.is_tournament(G)`. `is_tournament` is a property-checking and is applicable to any graph, and I think there's a usability argument for being able to access it with the other `nx.is_` functions. Thoughts?

I think there may also be an argument for modifying the semantics of `is_tournament`... to be discussed in a separate issue!

**Comment by dschult** [comment]
I think adding `is_tournament` to the main namespace makes sense.  But I would want the code for that function to live with the other tournament code.  And if people are going to discover the function via ipython's tab-completion feature, then we need to make sure they can easily see enough of the doc_string to be able to understand what a tournament graph is. I haven't looked at that. Maybe it is already just fine. :}

**Comment by Qudirah** [comment]
@rossbar I want to work on this but I do not understand the conclusion much. Can you help with it?

**Comment by MridulS** [comment]
You need to add `is_tournament` to the main namespace. That means if someone does `import networkx as nx`, and then they do `nx.is_` and hit a tab for autocomplete, `nx.is_tournament` should show up.

Currently someone needs to first import the `tournament` subpackage and then they will be able to use the `is_tournament` function. To fix this you need to go look at the `__init__.py` files in `networkx/__init__.py` and `tournament/__init__.py`

**Comment by Qudirah** [comment]
> You need to add `is_tournament` to the main namespace. That means if someone does `import networkx as nx`, and then they do `nx.is_` and hit a tab for autocomplete, `nx.is_tournament` should show up.
> 
> Currently someone needs to first import the `tournament` subpackage and then they will be able to use the `is_tournament` function. To fix this you need to go look at the `__init__.py` files in `networkx/__init__.py` and `tournament/__init__.py`

Thank you @MridulS. will get on that rn.
