### ISSUE TITLE
`is_tournament` behavior for undirected and multigraphs

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#5543]
Currently, `is_tournament` is decorated with `not_implemented_for` for the undirected and multigraph cases, so users see the following:

```python
>>> from networkx import tournament
>>> G = nx.Graph()
>>> tournament.is_tournament(G)
Traceback (most recent call last)
   ...
NetworkXNotImplemented: not implemented for undirected type
>>> MG = nx.MultiGraph()
>>> tournament.is_tournament(MG)
Traceback (most recent call last)
   ...
NetworkXNotImplemented: not implemented for multigraph type
```

Based on the docstring and module description, I would've expected `is_tournament` to return `False` for these cases rather than throw a `NotImplemented` exception. I would propose to modify the behavior as such, so the above examples become:

```python
>>> from networkx import tournament
>>> G = nx.Graph()
>>> tournament.is_tournament(G)
False
>>> MG = nx.MultiGraph()
>>> tournament.is_tournament(MG)
False
```

Thoughts on the proposed behavior change?

This would be a breaking change, but I would argue that this is closer to a defect in semantics and thus would just need a release note and *not* require a `FutureWarning`.

**Comment by dschult** [comment]
This is a feature/question for many of the `is_*` functions (both in Networkx and other packages/languages too). It even gets deep into the python language where `1 == "A"` returns False while `1 < "A"` raises an exception.

So I guess the question here is which type of user we want to help out. 1) The person who is scanning through a bunch of graphs to check for tournaments where some are directed and others are undirected. (currently they have to try/except, or check `G.is_directed()`.)  Or 2) the person that (mistakenly) has the graph in a directed/multigraph form, gets the result from `is_tournament` as `False` and can't figure out why the graph isn't a tournament graph when the edges indicate that it really is a tournament graph.

I'm leaning toward leaving it the way it is (based on least surprise). The person scanning many graphs will get the exception and it will be clear to add a pre-check to rule out directed graphs. The person with the wrong type of graph will get the exception and know that it is the base class that is causing trouble -- not the edges satisfying conditions for a tournament.

But I may be missing a use case or type of user we are trying to serve with this function.

**Comment by rossbar** [comment]
> I'm leaning toward leaving it the way it is (based on least surprise). The person scanning many graphs will get the exception and it will be clear to add a pre-check to rule out directed graphs. The person with the wrong type of graph will get the exception and know that it is the base class that is causing trouble -- not the edges satisfying conditions for a tournament.

Thanks @dschult , this makes a lot of sense. I'll admit I had a much more simple perspective (`is_<something>`, True or False?) but I agree that the current situation actually conveys *more* information and is far less likely to lead to silently surprising results.

I'll go ahead and closed this as resolved, though it probably wouldn't hurt to verify that this behavior is consistent between the other `is_` functions (where applicable)
