### ISSUE TITLE
Cannot access `branching_weight()`

### ISSUE THREAD

**Issue by NikitaSharma1** [networkx/networkx#5553]
The documentation of [branching_weight()](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.tree.branchings.branching_weight.html#networkx.algorithms.tree.branchings.branching_weight) specifies `Returns the total weight of a branching`  but I am unable to access the function.

```py
>>> G = nx.DiGraph()
>>> G.add_weighted_edges_from([(0, 1, 2), (1, 2, 4), (2, 3, 3), (3, 4, 2)])
>>> nx.branching_weight(G)
AttributeError: module networkx has no attribute branching_weight
```

**Comment by MridulS** [comment]
`branching_weight` needs to imported from the `tree` namespace, not everything is imported into the root level `networkx` namespace.

``` python
>>> from networkx.algorithms import tree
>>> tree.branching_weight(G)
11
```

This should be better documented.

**Comment by NikitaSharma1** [comment]
Thank you, I can work on this.

**Comment by NikitaSharma1** [comment]
Thank you, I can work on this.
