### ISSUE TITLE
parameter nodelist for triadic_census

### ISSUE THREAD

**Issue by r1ght0us** [networkx/networkx#5557]
This is the code example:
```python
import networkx as nx

G = nx.DiGraph([("b", "a"), ("b","c")])
print(nx.triadic_census(G))
print(nx.triadic_census(G,nodelist=["c"]))
```
This is the result:
```
{'003': 0, '012': 0, '102': 0, '021D': 1, '021U': 0, '021C': 0, '111D': 0, '111U': 0, '030T': 0, '030C': 0, '201': 0, '120D': 0, '120U': 0, '120C': 0, '210': 0, '300': 0}
{'003': 0, '012': 0, '102': 0, '021D': 0, '021U': 0, '021C': 0, '111D': 0, '111U': 0, '030T': 0, '030C': 0, '201': 0, '120D': 0, '120U': 0, '120C': 0, '210': 0, '300': 0}
```
Is it wrong with this parameter nodelist setting?

**Comment by dschult** [comment]
the example is correct. For each type of triad, it shows how many triads are of that type. With only 1 node in the nodelist there are no triads. So there are no triads of any of the types.

**Comment by r1ght0us** [comment]
@dschult 
```python
G = nx.DiGraph([("b", "a"), ("b","c")])
print(nx.triadic_census(G))
print(nx.triadic_census(G,nodelist=["b"]))
```
I got the same result as the parameter nodelist
```text
{'003': 0, '012': 0, '102': 0, '021D': 1, '021U': 0, '021C': 0, '111D': 0, '111U': 0, '030T': 0, '030C': 0, '201': 0, '120D': 0, '120U': 0, '120C': 0, '210': 0, '300': 0}
{'003': 0, '012': 0, '102': 0, '021D': 1, '021U': 0, '021C': 0, '111D': 0, '111U': 0, '030T': 0, '030C': 0, '201': 0, '120D': 0, '120U': 0, '120C': 0, '210': 0, '300': 0}
```
So, sir. how can I get the triads type and quantity of a node?

**Comment by MridulS** [comment]
Just by calling `nx.triadic_census(G))` it will return the triad type and number of occurrences. If you want the type of triad and all the triad graphs please use `nx.triads_by_type(G)`.

**Comment by r1ght0us** [comment]
@MridulS 
Mr., I just want to get the quantity of the triads and the triads group belonging to a single node.
use ```nx.triads_by_type(G)``` . Because it's a bigger graph and takes a long time

**Comment by dschult** [comment]
A single node in the nodelist contains no triads -- there is only one node!!
Perhaps you want to include only the node and its neighbors:
```nx.triad_census(G, nodelist=['b']+list(G['b']))```

**Comment by dschult** [comment]
I see what you mean, but clearly this attempt to implement triad_census for a nodelist does not count the same way you suggest.  The PR that implemented it is #4361. It is possible that there is a bug in that change.  I haven't looked carefully, but I think that the condition `m[u] < m[v]`, which is supposed to eliminate double counting of triads, does not work correctly when only a subset of the actual nodes are looped over. 

So I am thinking this may have a bug.  Can you tell me what you expect the census to be for each node in 'a<-b->c'?
and can you tell me what you expect the census to be for each node of the more complicated 'a->b->c->d'?
If we can work through those two cases I think we should be able to check for bugs and identify the source.

**Comment by r1ght0us** [comment]
@dschult 
For each node in "a<-b->c", i expect to be able to get each node to belong to “021D”,  for each node, the "021D" type quantity value is 1

For each node in "a->b->c->d": 
- node "a" get {"021C": 1}
- node "b" get {"021C": 2}
- node "c" get {"021C": 2}
- node "d" get {"021C": 1}

**Comment by dschult** [comment]
For the `"a->b->c->d"` case we should have 3 triads for each node -- so if we sum the individual node counts, we should get 12 counts.  I only get 4 counts total:  2 for "021D" and 2 for "021C". And there are no triads counted for node "d".

I think we made a serious error when we added the `nodelist` parameter to this code. It would work fine if we didn't have all that code to avoid considering the same triad multiple times. But it is a fundamentally different way of counting. I think it should probably be a different function than `triad_census`.  Perhaps `triad_census_by_node`.

I'm going to mark this as a defect.  Let's see if there is a good algorithm for getting the census by node...

**Comment by r1ght0us** [comment]
@dschult 
Sir, If there is no parameter "nodelist", is this `triad_census` to run normal?
:-)

**Comment by dschult** [comment]
The `triad_census` code without a `nodelist` parameter has been around for a long time and seems to be solidly correct. (though I thought the nodelist part of it was correct, so maybe there is something subtle that we've missed). The `nodelist` feature is relatively new and I can see where the bug is coming from there, and that bug has no impact on the correctness of the calculation without `nodelist`.

So, you are safe to use the function without the `nodelist` parameter.
