### ISSUE TITLE
convert.py needs be re-factored and the design reconsidered (migrated from Trac #565)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#556]
Original ticket https://networkx.lanl.gov/trac/ticket/565
Reported 2011-06-04 by @hagberg, assigned to @hagberg.

convert.py is too big and should be split into modules.
The design of esp. from_dict_of_dicts() could be reconsidered to make it simpler and easier to test.  See ticket #564 for a bug that was hard to find.

**Comment by hagberg** [comment]
Closed due to inactivity.,
