### ISSUE TITLE
induced_subgraph docs show unrelated example

### ISSUE THREAD

**Issue by baheckman** [networkx/networkx#5566]
The example on the documentation for induced_subgraph [here](https://networkx.org/documentation/stable/reference/generated/networkx.classes.function.induced_subgraph.html) shows an example of a generic subgraph function, not the induced_subgraph function. 

### Current Behavior

Currently the doc page in question does not show an example of the function it is documenting in the example. It shows an example of the `subgraph()` method, instead of the `induced_subgraph()` method. Perhaps this is for a reason, but it seems wrong.

### Expected Behavior

I expect the documentation example to show an example using the function being documented (in this case a call to the induced_subgraph function somewhere on this page).

### Environment

Python version: 3.7
NetworkX version: 2.8

**Comment by baheckman** [comment]
If this is something that should be fixed, I'm happy to take this on!

**Comment by rossbar** [comment]
This is a bit tricky... if you look at the implementation of the `subgraph` method (i.e. `G.subgraph`) it looks like it returns the induced subgraph. I agree that the docstring for `induced_subgraph` should probably show the function itself being used though, and perhaps mention that the subgraph method of graphs also returns the induced subgraph.

**Comment by baheckman** [comment]
Agree. I can give this one a shot and put a PR up in the next few days.
