### ISSUE TITLE
Label propagation documentation mistake

### ISSUE THREAD

**Issue by williamjallen** [networkx/networkx#5587]
It appears that the documentation for [this](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.community.label_propagation.label_propagation_communities.html) function has a typo.  Is the highlighted text supposed to be a link?  See attached screenshot.

![image](https://user-images.githubusercontent.com/16820599/165540206-c2e8635b-6f99-44f4-95ae-8088ea8bd773.png)

**Comment by rossbar** [comment]
Closed by #5588
