### ISSUE TITLE
Install Networkx 2.8 in colab

### ISSUE THREAD

**Issue by SalvatoreRa** [networkx/networkx#5591]
I have tried to install networkx in colab. I need the latest version 2.8 or at least 2.7, since I want to use the louvain_communities.

If I use the standard example:
```
import networkx as nx
from networkx.algorithms import community
G = nx.petersen_graph()
community.louvain_communities(G, seed=123)
```
I get:

`AttributeError: module 'networkx.algorithms.community' has no attribute 'louvain_communities'`

Thus I tried:
```

! pip uninstall networkx
!pip install imgaug==0.2.6
!pip install  networkx>=2.7
import networkx as nx
nx.__version__
```
which just allow me to install networkx 2.6.3

Or I tried:

`!pip install git+https://github.com/networkx/networkx.git --verbose`

which it does not work (with other packages) worked.

Do you have some suggestions?

Thanks for help

**Comment by MridulS** [comment]
This is probably because of google colab default python version. They have py3.7 be default and networkx 2.7+ requires python 3.8.
So please first update python in your colab session and then you should be able to update the networkx version available in google colab.
