### ISSUE TITLE
```G.edges(data = True)``` not giving attributes of self loops

### ISSUE THREAD

**Issue by 0ddoes** [networkx/networkx#5592]
While I was trying to get the edge DataView of the following graph for the Contribution #5474 I saw that the attributes assigned to the self Edge in the Multigraph is not displayed when given  ```G.edges(data = True)```. Is it because it outputs only the ```OutMultiEdgeDataView```(meaning only the out edges?) or is this a defect? 
```python 
>>> import networkx as nx
>>> G = nx.MultiDiGraph([(0,1), (0,1), (1,0), (2,2), (3, 4), (1,3)])
>>> nx.set_edge_attributes(G, {(0,1,0): {"weight": 20, "cost": 21}, (2,2,4): {"weight": 10, "cost": 3}, (0,1,1): {"cost":7}})
>>> G.edges(data=True)
OutMultiEdgeDataView([(0, 1, {'weight': 20, 'cost': 21}), (0, 1, {'cost': 7}), (1, 0, {}), (1, 3, {}), (2, 2, {}), (3, 4, {})])

```

**Comment by dschult** [comment]
There is no edge `(2,2,4)` so the set_edge_attributes didn't set those attributes.
