### ISSUE TITLE
Property graph converted using to_networkx() cannot be saved correctly to gexf file

### ISSUE THREAD

**Issue by Jasmine-lxn** [networkx/networkx#5595]
### Current Behavior

**I want to use to_networkx() to convert the data in torch to networkx (retain the attributes of nodes and edges in the graph data), and then save it as a gexf file by using nx.write_gexf() , but it always prompts an error, what should I do? ** 

### Steps to Reproduce

`
import torch
from torch_geometric.datasets import TUDataset
from torch_geometric.data import DataLoader

dataset_dir = "raw_data/TUDataset"
dataset_name = "AIDS"
dataset = TUDataset(root = dataset_dir, name = dataset_name)
data = dataset[0]

import networkx as nx
from torch_geometric.utils.convert import to_networkx
import os

gs=[]
k=3
for i,data in enumerate(dataset):
    if data.num_nodes<=k:
        g=to_networkx(data,node_attrs=['x'],edge_attrs=['edge_attr'] ,to_undirected=True,remove_self_loops=True)
        gs.append(g)      
gs_num=len(gs)

for i in range(0,gs_num):
    if not os.path.exists("data\\{}\\raw\\{}".format(dataset_name,k)):
        os.makedirs("data\\{}\\raw\\{}".format(dataset_name,k))
    nx.write_gexf(gs[i],"data\\{}\\raw\\{}\\{}.gexf".format(dataset_name,k,i))

`

### Environment

Python version: 3.9
NetworkX version: 2.8

### Additional context

![1](https://user-images.githubusercontent.com/56641033/166390129-b92599ba-a036-4804-abe8-57de973c0d20.png)

**Comment by dschult** [comment]
Can you give us the error that you've got?

**Comment by Jasmine-lxn** [comment]
OK, I have uploaded the error information in the format of picture.

**Comment by dschult** [comment]
It looks like you have stored attributes with values that are lists. That won't work with the gexf writer.
Is there a reason you are using GEXF? Perhaps there is a better format for storing your data?
Or, perhaps you could store the data attributes as dicts or numpy arrays?

**Comment by Jasmine-lxn** [comment]
I want to use the file in gexf format to calculate the graph editing distance between two graphs. Now I know. I'll try another format. Thank you!
