### ISSUE TITLE
bug in documentaiton of read_dot 

### ISSUE THREAD

**Issue by horstjens** [networkx/networkx#5604]
The usage example at the bottom of "read_dot" ( https://networkx.org/documentation/stable/reference/generated/networkx.drawing.nx_pydot.read_dot.html ) is misleading. It says:

Use `G = nx.Graph(read_dot(path))` to return a Graph instead of a MultiGraph.

should be instead:

Use `G = nx.Graph(nx.nx_pydot.read_dot(path))` to return a Graph instead of a MultiGraph.

I guess the problem is an outdated docstring but my kwnoledge of the github repos is not sufficient to locate it

### Current Behavior

the example does not work, error message is :
`NameError: name 'read_dot' is not defined`

### Expected Behavior
no error

### Steps to Reproduce

```
import networkx as nx
G = nx.Graph(read_dot("output_graphviz.dot"))

```

### Environment

Python version: 3.10
NetworkX version: 2.8

**Comment by dschult** [comment]
Yes, this string of code would only work if you have done:
`from networkx import nx_pydot.read_dot as read_dot` or `from networkx.nx_pydot import *` or similar.

I like your suggestion of changing the string of code to:
```G = nx.Graph(nx.nx_pydot.read_dot(path))```
This is in the repo at: `networkx/drawing/nx_pydot.py`
Should be an easy fix. Thank You!
