### ISSUE TITLE
Bipartite Closeness centrality algorithm does not report nodes with zero value.

### ISSUE THREAD

**Issue by JulianThx** [networkx/networkx#5620]
### Current Behavior
The function saves closeness values of '0.0' always at closeness[len(nodes)] which is closeness[n]. This results a returned dictionary with less elements than number of nodes in the graph.

### Expected Behavior
The values of '0.0' should instead be saved at closeness[node] within the for-loops iterating over all nodes.

### Steps to Reproduce
/

### Environment
Python version: 3.9.12
NetworkX version: 2.8

### Additional context
In both cases within the source code below
`else:
            closeness[n] = 0.
`
needs to be changed to:
`else:
            closeness[node] = 0.
`
See sourcecode:
https://networkx.org/documentation/stable/_modules/networkx/algorithms/bipartite/centrality.html#closeness_centrality

**Comment by dschult** [comment]
The docstring states that 

    The closeness of a node is the distance to all other nodes in the 
    graph or in the case that the graph is not connected to all other nodes
    in the connected component containing that node.

So, I think we don't intend to report nodes that are not connected to the other nodes. Isn't that the intent of this part of the code?  If I am missing something (and even if not) can you provide a small example where the resulting dict is not what you would expect?  That is the first step toward getting a test to show this difficulty. (and thus the first step toward a fix. :}

**Comment by dschult** [comment]
Ahh... yes, I understand ---  it looks like a typo, that should be `node` instead of `n` in two places.
And you said that in the original post. I was too focused on it being the bipartite and not the regular closeness centrality that I missed that.  

Yes, that code appears to simply avoid dividing by zero. And instead it assigns a value to a nonexisting node.
Thanks!

**Comment by dschult** [comment]
It turns out the tests were actually testing this case:  Incorrectly!!
So, I've fixed the tests and the code in #5800.
Thanks for bringing this to our attention!
