### ISSUE TITLE
nx.navigable_small_world generates a list of edges with 3 dimensions

### ISSUE THREAD

**Issue by www3cam** [networkx/networkx#5621]
### Current Behavior

Maybe there is a reason for this, but I expect navigable_small_worlds `__init__` to generate a list of edges with size and dimension (-1,2).  However with this specification: `G = nx.navigable_small_world_graph(10, p=4, q=2, r=1.5, dim=2, seed=None)` it generates a edge matrix with dimension (-1,2,2).  It looks like it is pairing tuples with other tuples as many tuples repeat in this matrix.  

### Expected Behavior

See above

### Steps to Reproduce

See above

### Environment

Python version: 3.9.7
NetworkX version:  2.7.1

**Comment by dschult** [comment]
Can you explain what you mean by "size and dimension (-1,2)."?
When I generate `G` and then try `G.edges` I get things like:  `((0,0), (0,1))` which seems right because the nodes are 2-tuples, so an edge should be a pair of 2-tuples.
Also `G.size()` reports 2939.

**Comment by CameronFen** [comment]
Oh ok.  I was mistaken.  I assumed each 2-tuple was an edge as well.  Can I rename them to have values from 0 to n number of nodes instead of the 2 tuple?  It's messing up my downstream algorithm.  You are welcome to close.

**Comment by dschult** [comment]
To relabel (that's the technical term we use) the nodes see [the relabel docs](https://networkx.org/documentation/stable/reference/relabel.html)
