### ISSUE TITLE
Lowest common ancestor returns incomplete result

### ISSUE THREAD

**Issue by U-238** [networkx/networkx#5628]
### Current Behavior

In the attached dataset and code, the result returned by `lowest_common_ancestor()` is a common ancestor but certainly not the lowest one. This can be seen in the output below, which shows the path between each node and the returned result.

### Expected Behavior

`lowest_common_ancestor()` should return the LCA. In the attached example, the correct LCA of nodes 1082 and 1096 would be **183**.

### Steps to Reproduce

Download attached dataset [lca_bug.json.txt](https://github.com/networkx/networkx/files/8677017/lca_bug.json.txt)
 and rename to `lca_bug.json`

Put this Python script in the same directory as `lca_bug.json` and run it:

```python
import json
import networkx as nx

# Load data
with open('lca_bug.json', 'r') as f:
    data = json.load(f)
G = nx.node_link_graph(data)
G_rev = nx.reverse(G)

x = 1082
y = 1096

# Find lowest common ancestor
lca = nx.lowest_common_ancestor(G, x, y)
print("Lowest common ancestor:")
print("  %d" % lca)

# Show path to and from this ancestor
print("Go up from X to LCA:")
for node in nx.shortest_path(G_rev, x, lca):
    print("  %d" % node)
print("Then down from LCA to Y:")
for node in nx.shortest_path(G, lca, y):
    print("  %d" % node)
```

The returned result is below, with my own annotations added:

```
Lowest common ancestor:
  199
Go up from X to LCA:
  1082
  1081
  183   <-- the correct LCA
  448
  184
  187
  195
  199
Then down from LCA to Y:
  199
  195
  187
  184
  448
  183   <-- the correct LCA
  1096
```

The result 199 is not the correct LCA. The result should be **183**. The nodes 448, 184, 187 and 195 are additional common ancestors lower than 199 on the same path between 183 and 199. I also can't see any particular reason why it stopped at 199, because there are several common ancestors above 199 as well.

### Environment

Python version: 3.9.12
NetworkX version: 2.8.1.dev0, latest git HEAD, specifically f50fc70b8cb6b4f5217a6d5505ba0e2b82b4761b

**Comment by PraharshitaK-IS** [comment]
Can I solve this?

**Comment by U-238** [comment]
@PraharshitaK-IS Yes, I'd be very happy for anyone to solve this! Please also see #5547 where someone is working on the same problem.

**Comment by U-238** [comment]
Also I should say that in the sample dataset I provided, there are actually two results that would be equally correct: **183** and **319**

**Comment by U-238** [comment]
I've also tried a few different inputs and have more incorrect results that may assist in debugging this issue:

### Inputs are a different number of generations from expected LCA

**Inputs:** 1082, 1096
**Expected result:** 183 or 319
**Actual result:** 199
**Notes:** Expected LCAs 183/319 are 2 generations from 1082 and 1 generation from 1096

### Inputs are an equal number of generations from expected LCA

**Inputs:** 1082, 1097
**Expected result:** 183 or 319
**Actual result:** 199
**Notes:** Expected LCAs 183/319 are 2 generations from 1082 and 2 generations from 1097

### Purported LCA is on a different path to expected LCA

**Inputs:** 1082, 419
**Expected result:** 233
**Actual result:** 991

Path to purported lowest common ancestor 991:

**Up:** 1082 -> 1081 -> 183 -> 207 -> 209 -> 210 -> 158 -> 120 -> 991
**Down:** 991 -> 40 -> 38 -> 34 -> 35 -> 2 -> 419

But common ancestor 233 is much lower:

**Up:** 1082 -> 1081 -> 319 -> 256 -> 233
**Down:** 233 -> 304 -> 333 -> 419

### Purported LCA is on a different path to at least 2 lower CAs

**Inputs:** 1082, 7571
**Expected result:** 1074 or 1068 (these are both lower than the actual result, but I'm unable to say definitively that these are the lowest)
**Actual result:** 1579

Path to purported lowest common ancestor 1579:

**Up:** 1082 -> 1080 -> 341 -> 1059 -> 1062 -> 1063 -> 1065 -> 461 -> 1579
**Down:** 1579 -> 461 -> 4996 -> 7573 -> 7571

Path to a lower common ancestor 1074:

**Up:** 1082 -> 1080 -> 341 -> 1060 -> 1066 -> 1072 -> 1074
**Down:** 1074 -> 7573 -> 7571

Path to another lower common ancestor 1068:

**Up:** 1082 -> 1080 -> 341 -> 1060 -> 1067 -> 1068
**Down:** 1068 -> 4996 -> 7573 -> 7571

I have not yet been able to find _any_ correct output for the inputs I've tried on my dataset!

**Comment by PraharshitaK-IS** [comment]
From my understanding of the code, it looks like it has been implemented for a balanced tree. 
This might be the reason why its not giving you the right output.
Looks like a bug.
Will debug and get back to you.

Thanks for explaining it from your end.

`    Only defined on non-null trees represented with directed edges from
    parents to children. Uses Tarjan's off-line lowest-common-ancestors
    algorithm. Runs in time $O(4 \times (V + E + P))$ time, where 4 is the largest
    value of the inverse Ackermann function likely to ever come up in actual
    use, and $P$ is the number of pairs requested (or $V^2$ if all are needed).

    Tarjan, R. E. (1979), "Applications of path compression on balanced trees",
    Journal of the ACM 26 (4): 690-715, doi:10.1145/322154.322161.
`

**Comment by U-238** [comment]
The notes you quoted are from `tree_all_pairs_lowest_common_ancestor()` which is a specific implementation for trees.

`lowest_common_ancestor()` calls through to a different function `all_pairs_lowest_common_ancestor()` which says it should work on all directed acyclic graphs (DAG), and references a different paper:

>     Only defined on non-null directed acyclic graphs.
> 
>     Uses the $O(n^3)$ ancestor-list algorithm from:
>     M. A. Bender, M. Farach-Colton, G. Pemmasani, S. Skiena, P. Sumazin.
>     "Lowest common ancestors in trees and directed acyclic graphs."
>     Journal of Algorithms, 57(2): 75-94, 2005.

As someone else has pointed out in #5547, the implementation of this function in NetworkX does not match the paper referenced in the notes.

Thank you for taking a look at this!

**Comment by dschult** [comment]
Check out #5736 which could be a function that solves this issue once we rename it as the primary function.

**Comment by U-238** [comment]
@dschult @dtekinoglu I've tried `naive_lowest_common_ancestor` using the same dataset and inputs as above.

It gives the correct results for some of the inputs in my original post: (1082, 1096) and (1082, 1097). This is a great improvement!

However for my other inputs I can still manually find common ancestors who are lower than the output of `naive_lowest_common_ancestor`:

### Example 1

Inputs:

> 1082, 419

Naive LCA output:

> **_236_**, up 4 down 4: 1082 -> 1081 -> 319 -> 276 -> **_236_** -> 253 -> 304 -> 333 -> 419

A lower ancestor I found manually:

> **_233_**, up 4 down 3: 1082 -> 1081 -> 319 -> 256 -> **_233_** -> 304 -> 333 -> 419

### Example 2

Inputs:

> 1082, 7571

Naive LCA output:

> **_1070_**, up 6 down 3: 1082 -> 1080 -> 341 -> 1060 -> 1067 -> 1069 -> **_1070_** -> 4992 -> 7562 -> 7571

A lower ancestor I found manually:

> _**1074**_, up 6 down 2: 1082 -> 1080 -> 341 -> 1060 -> 1066 -> 1072 -> **_1074_** -> 7573 -> 7571

Another lower ancestor I found manually:

> **_1068_**, up 5 down 3: 1082 -> 1080 -> 341 -> 1060 -> 1067 -> **_1068_** -> 4996 -> 7573 -> 7571

**Comment by rossbar** [comment]
Thanks for taking a look @U-238. I think it'd be great if we could boil down these failures to the absolute minimum (i.e. what is the graph with the minimum number of nodes and edges to reproduce this case) and add it as a test case. In it's current state I have a hard time verifying the "manual" ancestor determinations. I understand this may not be simple to do, so anyone who wants to take a stab at it I'd encourage them to do so!

**Comment by dschult** [comment]
Your examples also bring up questions about what it means to be a lowest common ancestor when the graph is a DAG. With a tree, there is a unique LCA for each pair. But with a DAG you can have edges between nodes at the same "level" resulting in multiple choices and how do we compare "5up 3down" to "6up 2down"?

I'll try to construct a simple example to show the trouble:
Multiple LCAs:   `G=nx.DiGraph([(0, 2), (0, 3), (1, 2), (1, 3)])`
`LCA(2, 3)` can be either 0 or 1.    0: 1up 1down   1: 1up 1down
So, we should not expect a unique answer for this LCA problem.

Multiple LCAs with different total numbers of nodes in the paths:
`G=nx.DiGraph([(0,2), (2,4), (0,5), (1,4), (1,3), (3,5)])`
LCA(4, 5) can be either 0 or 1.  0: 2up 1down   1: 1up 2down

Combining the two examples we can get different total lengths:
`G=nx.DiGraph([(0,3), (0,4), (1,3), (1,2), (2,4)])`
LCA(3, 4) can be either 0 or 1,  0: 1up 1down  1: 1up 2down

It's not clear to me exactly how the LCA is defined for a DAG. We return **a** node that is a LCA.

**Comment by dtekinoglu** [comment]
I created the subgraph induced on nodes in your first example: 
![image](https://user-images.githubusercontent.com/79102788/180567061-b78249b5-6156-48e9-9f11-44c034ad92ff.png)

As @U-238 told, total path length of 233 is 7, whereas it is 8 for 236. But I don't think this necessarily means that 233 is a lower ancestor than 236. For example, going from 256 to 233 might not be going "up" but instead they might be in the same level.

I thought of comparing their levels by finding the shortest paths to the root. However, since the graph has 544 nodes with 0 in-degree, I was not able to do that. I agree with @dschult and I will search more about the definition of LCA in DAGs.

**Comment by U-238** [comment]
@dtekinoglu @dschult Thanks for the further analysis. I agree that the issue here is defining what LCA means for a DAG, rather than necessarily a bug in the code.

[This paper](https://mediatum.ub.tum.de/doc/1094624/TUM-I0809.pdf) defines LCA as:

> A lowest common ancestor (LCA) of vertices u and v in a directed acyclic graph (dag) is an ancestor of both u and v that has no descendant which is an ancestor of u and v

The results from `naive_lowest_common_ancestor` meet this definition, even if they are not always the shortest path between the two nodes and an LCA of those two nodes. On this basis I will write a post in #5869 to support replacing the LCA function with the "naive" function.

I still think a shortest-path LCA function could be useful, or even an LCA function that returns all LCAs for a pair of nodes.

**Comment by dschult** [comment]
I agree that
1) LCA may have multiple solutions and so this algorithm finding one of them is a useful function.
2) adding a second function that returns **all** the lowest common ancestors is probably also useful.
There is [a post on Baeldong.com](https://www.baeldung.com/cs/lowest-common-ancestor-acyclic-graph) that describes a fairly simple algorithm to implement this second function for DAGs.

**Comment by dschult** [comment]
I opened an issue requesting a function for all_lowest_common_ancestors. I think that means this one can be closed (with a pointer to it for those interested).

**Comment by Ruchi-here** [comment]
hey @dschult what would be the root node in the given file? because the method I'm using I need to find root node and for that I need to know the structure of graph
