### ISSUE TITLE
DiGraph serialization (get/setstate) triggers an AttributeError for "_adj"

### ISSUE THREAD

**Issue by marscher** [networkx/networkx#5655]
### Current Behavior

Passing a `DiGraph` to deepcopy uses the serialization protocol via get and set_state methods of `InEdgeView`. In the implementation there is an assignment to self._adj like this:
``` python
 self._adjdict = G._pred if hasattr(G, "pred") else G._adj
```
So the passed `Graph` does not have the `_adj` attribute. By inspection I figured, that the state dictionary contains the `_adjdict` property directly.
If I replace the code to set `_adjdict` from the state, everything works as expcted.

### Expected Behavior
Copying a `DiGraph` via deepcopy should work. This used to be the case for networkx<2.8.1

### Steps to Reproduce

```python
G = nx.MultiDiGraph()
edges = G.in_edges()
deepcopy(G)
```

### Environment

Python version: 3.8
NetworkX version: 2.8.1

### Additional context
A github action workflow triggering the error:

https://github.com/BAMWelDX/weldx/runs/6502339152?check_suite_focus=true#step:9:110

``` python
 File ~/micromamba/envs/weldx/lib/python3.8/site-packages/networkx/classes/reportviews.py:1290, in InEdgeView.__setstate__(self, state)
   1288 def __setstate__(self, state):
   1289     self._graph = G = state["_graph"]
-> 1290     self._adjdict = G._pred if hasattr(G, "pred") else G._adj
   1291     self._nodes_nbrs = self._adjdict.items

AttributeError: 'DiGraph' object has no attribute '_adj'
```

**Comment by MridulS** [comment]
Thanks for the report! This is indeed a bug:

A minimal example I was able to come up with (this is a bug for both `DiGraph` and `MultiDiGraph`):
``` python
In [2]: class Something:
    ...:     def __init__(self):
    ...:         self.g = nx.MultiDiGraph()
    ...:         self.e = self.g.in_edges
    ...:

In [3]: s = Something()

In [4]: deepcopy(s)
...
...
AttributeError: 'MultiDiGraph' object has no attribute '_adj'
```

This should be fixed by https://github.com/networkx/networkx/pull/5657

**Comment by dschult** [comment]
Here's another minimal example:
```python
G = nx.MultiDiGraph()
edges = G.in_edges()
deepcopy(G)
```

**Comment by marscher** [comment]
That was a really quick response and fix. Thank you so much! Have a nice weekend
