### ISSUE TITLE
arg margins missing from valid_node_kwds in nx_pylab.py

### ISSUE THREAD

**Issue by harristeague** [networkx/networkx#5658]
margins is a new arg for draw_networkx_nodes(), but does not pass through from draw_networkx() since it is missing from the valid args list in nx_pylab.py:271

### Current Behavior

"invalid argument" exception

### Expected Behavior

it should accept the argument

### Steps to Reproduce

        g = nx.gnm_random_graph(10, 15)
        nx.draw_networkx(g, pos=nx.planar_layout(g), margins=(1,1))

### Environment

Python version: 3.8.12
NetworkX version: 2.8

**Comment by MridulS** [comment]
fixed in https://github.com/networkx/networkx/pull/5660
