### ISSUE TITLE
When writing pydot graph there is an extra "\n" character added

### ISSUE THREAD

**Issue by adam2392** [networkx/networkx#5686]
### Current Behavior
I am trying to save graphs to disc using the DOT language. However, when I save this simple graph, it does not match IO roundtrip.

```
nx_graph = nx.DiGraph()
nx_graph.add_nodes_from([0, 1, 2, 3, 4])
nx_graph.add_edges_from([(0, 4), (3, 4)])
pydot_graph = nx.nx_pydot.to_pydot(nx_graph)

print(pydot_graph)
> strict digraph  {
0;
4;
3;
1;
2;
0 -> 4;
3 -> 4;
}
```

Now when I write to disc...
```
nx.nx_pydot.write_dot(nx_graph, "/Users/adam2392/Downloads/test.dot")
pygraph = pydot.graph_from_dot_file(
    "/Users/adam2392/Downloads/test.dot", encoding="utf8"
)[0]

print(pygraph.to_string())
> digraph G {
0;
4;
3;
1;
2;
0 -> 4;
3 -> 4;
"\n";
}
```
### Expected Behavior
There should not be an extra "\n" character

### Environment
Python version: 3.8
NetworkX version: 2.7.1

**Comment by MridulS** [comment]
Thanks for raising this @adam2392! But this behavior comes from `pydot`

``` python
In [1]: import pydot

In [2]: graph = pydot.Dot("test", graph_type="graph")

In [3]: test_node = pydot.Node("a", label="something")

In [4]: graph.add_node(test_node)

In [5]: graph.to_string()
Out[5]: 'graph test {\na [label=something];\n}\n'
```

One way of handling this could be to drop the line break (`\n`) explicitly while writing the graph to disk in the function `write_dot`.

**Comment by dschult** [comment]
This is not a fix, but a workaround.
If you install graphviz and pygraphviz you can use:
```
nx.nx_agraph.write_dot(nx_graph, "testdot.dot")
```

**Comment by adam2392** [comment]
> One way of handling this could be to drop the line break (`\n`) explicitly while writing the graph to disk in the function `write_dot`.

How would you do this? 

I have something like this, which technically doesn't rely on networkx:

```
# convert to the DOT string
str_dot_graph = graph.to_dot_graph()

# now make a pydot graph
graph = pydot.graph_from_dot_data(str_dot_graph)[0]

graph.write_dot(fname, encoding="utf-8")
```

**Comment by MridulS** [comment]
@adam2392 after thinking a bit more thinking about this I don't think this is a "defect", we shouldn't be mixing `nx.nx_pydot.write_dot` ( a NetworkX function ) with `pydot.graph_from_dot_file` ( a pydot function). I think we should only worry about maintaining round trips inside NetworkX and that works currently.

From example the `to_pydot` and `from_pydot` function do maintain the round trip
``` python
In [1]: import networkx as nx

In [2]: from networkx.drawing.nx_pydot import to_pydot, from_pydot

In [3]: nx_graph = nx.DiGraph()

In [4]: nx_graph.add_nodes_from([0, 1, 2, 3, 4])

In [5]: nx_graph.add_edges_from([(0, 4), (3, 4)])

In [6]: nx.is_isomorphic(nx_graph, from_pydot(to_pydot(nx_graph)))
Out[6]: True

```

`write_dot` and `read_dot` are indeed failing on this round trip but that's because how pydot deals with integers (it doesn't), everything is converted to strings underneath.

``` python
In [7]: nx.nx_pydot.write_dot(nx_graph, 'test.dot')

In [8]: H = nx.nx_pydot.read_dot('test.dot')

In [9]: nx.is_isomorphic(nx_graph, H)
Out[9]: False

In [10]: nx_graph
Out[10]: <networkx.classes.digraph.DiGraph at 0x109073c40>

In [11]: nx_graph.edges() # initial nodes were ints
Out[11]: OutEdgeView([(0, 4), (3, 4)])

In [12]: H.edges() # the nodes after reading from the dot file written to disk are strings
Out[12]: OutMultiEdgeDataView([('0', '4'), ('3', '4')])
``` 

The round trip in pydot isn't maintained:
``` python
In [1]: import pydot

In [2]: graph = pydot.Dot("nx_graph")

In [3]: graph.add_node(pydot.Node(1, foo='bar')) # a integer node is created 

In [4]: graph.write_raw("output_raw.dot")

In [5]: graphs = pydot.graph_from_dot_file('output_raw.dot') 

In [6]: graphs[0].get_node(1) # the file read in via pydot doesn't know about the integer node 1
Out[6]: []

In [7]: graphs[0].get_node('1') # it does know about the string node 1
Out[7]: [<pydot.Node at 0x1096a8e20>]

```

I'll go ahead and close this issue, please feel free to comment here or open a new issue if you think we can add something else here :)
