### ISSUE TITLE
nx.community.louvain_communities(directed_graph) does not return from _one_level().

### ISSUE THREAD

**Issue by Danielsrq** [networkx/networkx#5704]
Calling nx.community.louvain_communities(directed_G) can get stuck in an infinite loop in _one_level(). It seems to be continuously calculating `gain`. The `threshold` parameter does not resolve the problem because _one_level() is called before any comparison to `threshold`.

There is no problem with an undirected version of the graph.

### Current Behavior

louvain_communities(directed_G) does not exit / return.

### Expected Behavior

louvain_communities(directed_G) should exit / return with a perhaps a warning if modularity cannot be further minimised.

### Steps to Reproduce

```
import networkx as nx
# import matplotlib.pyplot as plt

G = nx.DiGraph()
nodes = [1,2,3,4,5,6,7,8,9,10,11]
edges = [(1,2),(1,6),(1,9)]
edges += [(2,3), (2,4), (2,5), (3,4), (4,3), (4,5), (5,4)]
edges += [(6,7), (6,8)]
edges += [(9,10), (9,11), (10,11), (11,10)]
G.add_nodes_from(nodes)
G.add_edges_from(edges)
# G = G.to_undirected() # Undirected version
communities = nx.community.louvain_communities(G) # <--- Does not return 

# nx.draw(G, with_labels = True) # For visualizing graph
# plt.show()
```

### Environment

Python version: 3.8.10
NetworkX version: 2.8.3

**Comment by z3y50n** [comment]
Thank you for your time reporting this. The issue seems similar to #5175 so I am going to close this. Feel free to reopen it if you think it's different!
