### ISSUE TITLE
Change methods to return iterators and retire _iter methods (migrated from Trac #581)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#572]
Original ticket https://networkx.lanl.gov/trac/ticket/581
Reported 2011-06-25 by @dschult, assigned to @hagberg.

Graph class methods such as '''neighbors''', '''degree''', and '''edges''' return lists or dicts when it seems cleaner and more efficient to return iterators.  

Currently these methods have cousin methods like '''edges_iter''' that do return iterators..  We should consider removing the '''_iter''' methods and making the others return iterators by design.  Then if the user needs a list of dict they can use e.g. '''list(G.edges())'''  Making the default behavior an iterator encourages efficiency.

Most methods would generate pairs (node, value) that could be used to construct a dict.  It might also be useful to be able to generate just the values.  Some methods like '''G.nodes()}} would naturally just generate single values.

**Comment by SanketDG** [comment]
This can be closed. Merged in #1716
