### ISSUE TITLE
Import nx in docstrings

### ISSUE THREAD

**Issue by jarrodmillman** [networkx/networkx#5720]
To make the docstring examples self-contained (and less confusing to new users), we should consider removing
https://github.com/networkx/networkx/blob/4e92d77ae1973e892712daac85392efbef9b3591/doc/conf.py#L118
and adding `import networkx as nx` to our docstring examples.

See https://github.com/scipy/scipy/issues/13049.

**Comment by lucasmccabe** [comment]
If one has multiple examples in a single docstring, should each example import networkx?

**Comment by dschult** [comment]
Digging down into the discussion on scipy linked to above, it seems that each doc_string will need to do the import at the top of that doc_string. At least that will satisfy the automated testing system. But it **doesn't** satisfy the idea of cut-and-paste examples and they work. It is very rare that you cut and paste an example from the top of the doc_string code. So most cut/paste examples will need to add the import.  I can still believe it is easier for newcomers to see the import, understand that they didn't copy/paste that part of the code and add it in. But the nly way to make out examples copy/paste friendly would be to have the import statement at the start of every section of the examples -- and to refuse to interrupt the examples with explanatory text -- which would be a shame. Explanatory text is often best in the middle of an example. 

Still, I'm +0 on including the import statements in the examples to help newcomers.  I find myself using copy/paste/remove-the-import when I copy from stackoverflow, or other sites. But it's better for me to have to delete than for a newbie to figure out that they have to add. :}

**Comment by jarrodmillman** [comment]
+0 from me as well. I prefer not having the import, but I understand that newcomers may find it confusing. So while I would prefer not having the imports, I do want to make things easier for newcomers. I am just not sure how confusing it is. I've only seen a handful of people confused over the years and I suspect it is pretty easy to figure out what is happening by entering the error in a search engine.

```
(nx) [jarrod@x15 ~]$ ipython
Python 3.9.9 (main, Nov 19 2021, 00:00:00)
Type 'copyright', 'credits' or 'license' for more information
IPython 8.4.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: sequence = nx.random_powerlaw_tree_sequence(100, tries=5000)
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
Input In [1], in <cell line: 1>()
----> 1 sequence = nx.random_powerlaw_tree_sequence(100, tries=5000)

NameError: name 'nx' is not defined

In [2]:
```

And googling `NameError: name 'nx' is not defined` yields:
https://www.google.com/search?q=NameError%3A+name+'nx'+is+not+defined

which is likely to suggest that newcomers try `import networkx as nx`. @Carreau  I wonder if it would be crazy for IPython to know about numpy, scipy, matplotlibt, scikit-image, networkx, etc imports and when seeing and undefined `np`, `sp`, `nx`, etc. suggests the right thing to do?

**Comment by stefanv** [comment]
Hey, that's a neat idea!  It's like some Linux distributions that tells you "You probably want `apt install foo-package`".  I'd use similar phrasing, since the recommendation might be wrong:

```
Hint: If you are using NetworkX, try `import networkx as nx` first
```

**Comment by jarrodmillman** [comment]
```
Hint: If ..., try `import numpy as np` first
Hint: If ..., try `import scipy as sp` first
Hint: If ..., try `import matplotlib.pyplot as plt` first
Hint: If ..., try `import pandas as pd` first
Hint: If ..., try `import networkx as nx` first
```

**Comment by jarrodmillman** [comment]
See https://github.com/ipython/ipython/issues/13696

**Comment by bsipocz** [comment]
Hints would be really nice, combined with the `doctest_global_setup` would address both the testing and confusion issues. (And the convenience part may not be addressed by adding the imports anyway as even then not all snippets would be fully self-contained (and the main offenders are SO and github issue snippets anyway rather than the official docs)).

**Comment by jarrodmillman** [comment]
We could also have numpydoc auto-insert the imports set in `doctest_global_setup` for the HTML and PDF documentation.

**Comment by Carreau** [comment]
I'll reply more in IPython's issue later, but project like https://github.com/deshaw/pyflyby allow autoimport, and it's also a bit what `ipython --pyplot` did. 

It is problematic to autoimport in the end, as it tend to import typos, or users get confused as they don't understand once they actually need an import.

It goes to further than Just NX, example often reference function from same module.

As for adding a friendly suggestion at the end it is possible, We could try to catch the name error. Python 3.10 already have extended error messages to guess the rights names on attribute error, one of the problem being that CPython implemented it in C, and that with our custom formatter on IPython side we have to re implement the logic. See https://github.com/ipython/ipython/pull/13450, one of the issues is we start to have many project that push for different traceback formatters.

- trio with exception groups, 
- Python 3.10 with catching attributes errors and name errors
- This. 
- Projects like https://pypi.org/project/friendly-traceback/


I think that adding the imports automatically in the docs is a solution, but it won't fix everything as many example can also refer to items in the same module without explicit imports I believe.

I don't believe I'll currently have the time to implement that in IPython, but I'd love to sit-down at SciPy and talk Jupyter & documentation.

**Comment by SultanOrazbayev** [comment]
The automatic import hinting would be cool.

As another alternative, and this is not everyone's preference, docs could specify exact imports to make:

```python
from networkx import Graph
G = Graph()
G.add_edge("A", "B")
```

**Comment by Qudirah** [comment]
@jarrodmillman Can I add your hint suggestion to the doc?

**Comment by MridulS** [comment]
I think we can close this issue on the networkx issue tracker. If this does happen this needs to happen in ipython.

Feel free to re-open this if anyone feels strongly about it :)
