### ISSUE TITLE
Wrong load centrality implementation

### ISSUE THREAD

**Issue by joranp1** [networkx/networkx#5725]
The implementation of load centrality does not seem to match the description of the centrality measure in the referenced paper. Instead load centrality just returns betweenness centrality values. 

### Current Behavior
Load centrality implementation just returns betweenness centrality values

### Expected Behavior
the centrality measure should return load centraltiy measures as described in:
Mark E. J. Newman: Scientific collaboration networks. II. Shortest paths, weighted networks, and centrality. Physical Review E 64, 016132, 2001. http://journals.aps.org/pre/abstract/10.1103/PhysRevE.64.016132

### Steps to Reproduce
When implementing the simple network as mentioned in the above paper different values for load and betweenness should be found

### Environment

Python version: 3.8
NetworkX version: 2.8.3

**Comment by dschult** [comment]
Can you give a simple example (<=5 nodes) that doesn't work and describe what the results should be?
Thanks!

**Comment by joranp1** [comment]
Dear

Based on figure 2 from [1], see image1 below, I would expect in this example on the image below (image2) node number 2 having a different centrality value for betweenness compared to load. This because only contributions of shortest paths between nodes 1 and 7 add to its centrality value.

Thanks in advance.

Kind regards,
Joran Paeye

[1] Ulrik Brandes. On variants of shortest-path betweenness centrality and their
generic computation. Social networks, 30(2):136–145, 2008.

(image1)
***@***.***

(image2)
***@***.***

**Comment by lucasmccabe** [comment]
Hi @joranp1, thanks for looking into this - unfortunately your images aren't showing here.

It's not so uncommon for [load centrality](https://github.com/networkx/networkx/blob/ec267cff8d092534fb0b2616e8f075142d2cd75b/networkx/algorithms/centrality/load.py#L9) and [betweenness centrality](https://github.com/networkx/networkx/blob/ec267cff8d092534fb0b2616e8f075142d2cd75b/networkx/algorithms/centrality/betweenness.py#L15) to be the same, especially for small graphs. I just ran the following experiment with binomial random graphs `G(n, p)` with n from 5 to 99 and p from 1/50 to 1:

![btwn](https://user-images.githubusercontent.com/12187602/173277462-1afb0c8a-b78c-4d7c-8f41-1dddbdee43b9.png)

**Comment by rossbar** [comment]
It's going to be difficult to make progress here without a specific example. @joranp1 , can you pull out the example of the "simple graph" you reference from the paper? The paper is behind a paywall (for me at least) so I can't follow the original link.

**Comment by joranp1** [comment]
Dear

Here a link for a wetransfer with both the images and the paper I mentioned before: https://we.tl/t-nfjxbmduzp

Kind regards,
Joran Paeye

**Comment by joranp1** [comment]
I'm sorry I'm quite new to this platform, please find the two images i mentioned earlier below. As per my reasoning the centrality value of node number 2 in image2 only depends on the shortest path between nodes 1 and 7, since no other shortest paths pass through it. By the methodology of load centrality this  node nr.2  should be assigned a lower centrality value than for betweenness centrality? Or is there a flaw in my reasoning?

(image 1)
![ex_1](https://user-images.githubusercontent.com/73711756/173331488-17ce7aea-f5ec-45b9-bec9-cdda87aa0d1a.png)
(image 2)
![ex_2](https://user-images.githubusercontent.com/73711756/173331491-68a3c99b-1fdd-4c0c-a31a-f3fd8a9aba3b.png)

**Comment by lucasmccabe** [comment]
> As per my reasoning the centrality value of node number 2 in image2 only depends on the shortest path between nodes 1 and 7, since no other shortest paths pass through it.

Several other shortest paths pass through node 2 - for instance, the shortest paths from 1 to 4 and 1 to 5.

**Comment by lucasmccabe** [comment]
Your calculation of betweenness appears correct, though non-normalized.

Unfortunately, your calculation of load is not. Nodes 4 and 5 (via source node 1) contribute 4/3 each to the non-normalized load score for node 2. This can be seen by adding something like ```if source == 1 and v in [4, 5]: print(v, x, between[v], num_paths)``` between lines 119 and 120 [here](https://github.com/networkx/networkx/blob/192f5e15c7a6879d99ecfd107f07b2327582434d/networkx/algorithms/centrality/load.py#L119).

That said, the accumulation routine performed in Algorithm 13 of the [paper](https://www.sciencedirect.com/science/article/abs/pii/S0378873307000731) your figure is from makes it unwieldy to track down load attribution in a spreadsheet like you can for betweenness.

Hope this helps!

**Comment by joranp1** [comment]
thanks!

**Comment by rossbar** [comment]
Thanks @lucasmccabe for the comprehensive answer! IMO that addresses the initial question sufficiently, so I will close this issue. Please feel free to comment/reopen if there are further questions.
