### ISSUE TITLE
Add data keyword to neighbors method (migrated from Trac #582)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#573]
Original ticket https://networkx.lanl.gov/trac/ticket/582
Reported 2011-06-25 by @dschult, assigned to @dschult.

The '''neighbors''' method could return edge data just like the '''edges''' method  does. This would allow simpler code when iterating over the adjacency list of a node.

See #574 for discussion and examples.

'''G.neighbors(n, data=True)''' would return a dict keyed by neighbor node to the edge data dict connecting them.  

'''G.neighbors_iter(n, data=True)''' would return an iterator of pairs (nbr,edgedata).   This is similar to G.edges(n, data=True) but that iterates through (n,nbr,edgedata). This is a synonym for G[u].items()

Suggestions?

**Comment by dschult** [comment]
Revisiting this to see if Views handles this Issue.  With the views interface, we have:

    # Instead of G.neighbors(n, data=True) or even G.neighbors(n, data='foo', default=1)

    # Edge data with neighbors 
    for nbr, edict in G[n].items():      # keydict returned for multigraph -- not desired
    for _, nbr, edict in G.edges(n, data=True)):  # plays nicely with multigraph

    # Node data with neighbors
    (nbr, G.node[nbr] for nbr in G[n])  # doesn't duplicate for multiedges
    (nbr, G.node[nbr] for _, nbr in G.edges(n))    # does duplicate for multiedges

I think these are sufficient so that we don't need to modify G.neighbors()...   So....

Do we get rid of G.neighbors() and tell people to just use G.edges()?

**Comment by dschult** [comment]
Shift conversation to #2467 with a different emphasis...
