### ISSUE TITLE
Some methods doesn't work on child classes of graphs

### ISSUE THREAD

**Issue by genericCandy** [networkx/networkx#5734]
When working on child classes of `nx.Graph` (I assume it is the same for all graph classes) that have other `__init__` parameters, some methods (for example subgraph) fail since they try to access the `__init__` of the child class instead of the `__init__` of the parent class

### Current Behavior
The method tries to access the `__init__` of the child class with the parameters for the parent class (`nx.Graph` in my case), and fails 
In the example below, it returned :
```
TypeError: Child.__init__() missing 1 required positional argument: 'data'
```

### Expected Behavior
The method should access the `__init__` of its first ancestor in {"nx.Graph", "nx.DiGraph", "nx.MultiGraph", ...}

### Steps to Reproduce
Execute this Python script : 
```
import networkx as nx

class Child(nx.Graph):
    def __init__(self, data):
        super().__init__(self)
        self.data = data

G = Child("some data")
G.add_nodes_from(range(5))
G.subgraph([1, 2, 3])
```

### Environment
Python version: 3.10.5
NetworkX version: 2.8

**Comment by MridulS** [comment]
thanks for raising this @genericCandy! But I'm not sure why should the given python script work? Why should the `Child` class should have access to the `subgraph` method from a `[Multi|Di]Graph` class?
How do you define a subgraph for a `Child` object?

If you want to keep a track of a graph object inside the `Child` class maybe something like this could work for you?
``` python
class Child:
    def __init__(self, data):
        self.data = data
        self.graph = nx.Graph()
```

``` python
In [3]: G = Child("some data")

In [4]: G.graph.add_nodes_from(range(5))

In [5]: G.graph.subgraph([1, 2, 3])
Out[5]: <networkx.classes.graph.Graph at 0x10add1120>
```

**Comment by dschult** [comment]
Even if you do subclass the graph class, a subclass should support the existing arguments to the base class. It can add new arguments. But if it removes possible arguments then you will need to overwrite any methods like subgraph that use these arguments.  I like @MridulS suggested approach.  But if you really need the subclass approach, then try
```python
class Child(nx.Graph):
    def __init__(self, data):
        super().__init__(self, data)
        self.data = data
```
Or if you are envisioning a string as the data argument, use a different keyword argument:
```python
class Child(nx.Graph):
    def __init__(self, data, newdata):
        super().__init__(self, data)
        self.data = newdata
```

**Comment by rossbar** [comment]
Thanks @MridulS and @dschult for the nice explanations. IMO the descriptions and examples are sufficient to address the original question, so I will close this one. If the issue persists please feel free to reopen with updated info!
