### ISSUE TITLE
Documentation example on read_edgelist for directed graph has missing parentheses

### ISSUE THREAD

**Issue by toulbar2** [networkx/networkx#5750]
While trying to read a digraph from a list of edges, as suggested in the documentation examples for this function:
G = nx.read_edgelist("network.txt", create_using=nx.DiGraph)
generates an error 
TypeError: clear() missing 1 required positional argument: 'self'

The correction was:
G = nx.read_edgelist("network.txt", create_using=nx.DiGraph())

**Comment by rossbar** [comment]
This shouldn't be a problem - `create_using` accepts either the graph class (as shown in the tutorial) or an instance of the graph class (your proposed change). Can you provide the full traceback along with which version of NetworkX you were using when you encountered the issue?

**Comment by SultanOrazbayev** [comment]
This issue is not reproducible.

**Comment by rossbar** [comment]
Thanks @SultanOrazbayev , let's close this as inactive. If the issue persists, please reopen with a minimal reproducing example.
