### ISSUE TITLE
Trophic Index, Initial Implementation (migrated from Trac #586)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#577]
Original ticket https://networkx.lanl.gov/trac/ticket/586
Reported 2011-06-29 by vaggi.federico, assigned to @hagberg.

I created a very initial implementation for the trophic index, an index used in ecological network analysis to calculate the strength of the indirect effect of a species on another species.  The description of the trophic index can be found here:

Quantifying the importance of species and their interactions in a host-parasitoid community.  F. Jordan, W.C. Liu and F.J.F van Veen  Community Ecology, 2003.

**Comment by hagberg** [comment]
Closed due to inactivity.
