### ISSUE TITLE
`node_link` functions `attrs` kwarg

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#5787]
`node_link_graph` and `node_link_data` have a similar API to the `cytoscape` functions, where there is a `attrs` kwarg which expects a dictionary containing specific keys that is then unpacked internally.

This API is a bit un-Pythonic and was removed in favor of keyword arguments - see the related discussion in #4199. It's worth checking if the `node_link` functions wouldn't benefit from a similar treatment.

**Comment by dschult** [comment]
Yes, IMO these functions should be changed to have 5 keyword arguments instead of a single dict containing the five values.

**Comment by brocla** [comment]
Thinking out loud...

Will need to:

- add key words to signature, while retaining `attrs`
- add a deprecation warning in the,
-- doc string
-- functions. Code will trigger the warning when `attrs is not None`
- Fix  the functions to use the keyword values, instead of `attrs`, when `attrs` is None
-  add tests that  use keywords instead of `attrs`. These tests will work after `attrs` is dropped.

**Comment by brocla** [comment]
There is a strange bit in the examples for `node_link_data`. I'm not sure that I should carry it forward.  Here is a snippet.

```
    >>> data2 = json_graph.node_link_data(H, link="edges", source="from", target="to"})

    To serialize with json

    >>> s2 = json.dumps(
    ...     data2, default={"link": "edges", "source": "from", "target": "to"}
    ... )
```

A dictionary of keywords is passed to `json.dumps` as keyword `default=`. But the documentation for `json.dumps` says that `default=` is a function, not a dictionary!   I tried the code. It runs, but the values in the default dict have no effect. Json ignores them.

Also, there are no examples in the tests of a default argument being passed to `json.dumps`.

Should I drop `default={"link": "edges", "source": "from", "target": "to"}` from the example code?
Or does it have a purpose, that I am not seeing?

Thanks

**Comment by dschult** [comment]
I agree with you that this second example includes a spurious dict that doesn’t actually do anything. I think is should be removed.  In fact, it would be more clear (in my opinion) to change these examples so they show the results instead of just capturing the results in a variable. Also, using the top level `nx namespace would be preferred: `nx.node_link_data` Something like:
```
>>> G = nx.Graph([(“A”, “B”)])
>>> data = nx.node_link_data(G)
>>> data
{'directed': False, 'multigraph': False, 'graph': {}, 'nodes': [{'id': 'A'}, {'id': 'B'}], 'links': [{'source': 'A', 'target': 'B'}]}

>>> H = nx.Graph([(0, 1)])
>>> data2 = nx.node_link_data(H, link=‘edges’, source=‘from', target='to')
>>> data2
{'directed': True, 'multigraph': False, 'graph': {}, 'nodes': [{'id': 0}, {'id': 1}], 'edges': [{'from': 1, 'to': 0}]}

To serialize with json

>>> import json
>>> json.dumps(data)
‘ {'directed': False, 'multigraph': False, 'graph': {}, 'nodes': [{'id': 'A'}, {'id': 'B'}], 'links': [{'source': 'A', 'target': 'B'}]}’

>>> json.dumps(data2)
‘ {'directed': True, 'multigraph': False, 'graph': {}, 'nodes': [{'id': 0}, {'id': 1}], 'edges': [{'from': 1, 'to': 0}]}’

```
Does this look better to you?  Please improve these examples as you think makes them most helpful.

**Comment by brocla** [comment]
Thanks for the feedback @dschult .   Yes, it makes sense to show the results. I can fix that up, and the namespace too.

I'm thinking that `node_link_graph` needs an example with JSON in it too.  And it needs to mention _Serialization_ in the description so someone can find it by that keyword.  I'll try something.

Note: There are question marks ("???") as placeholders in the doc string that need to be replaced with the version number of when the old signature will be removed.

**Comment by brocla** [comment]
Just did an update to the PR. 

Here is a synopsis. Any feedback is welcome.

- The namespace is now nx.
- The examples show the results
- There are more examples with JSON loads and dumps
- The short description for node_link_graph now refers to Serialization
- There is a new note explaining that the keyword values must match between `node_link_data` and `node_link_graph` when converting back and forth between data and graphs.

The version number for dropping the deprecated signature is still needed.
