### ISSUE TITLE
`nx.ancestors()` and `nx.descendants()` does not include the node itself.

### ISSUE THREAD

**Issue by dtekinoglu** [networkx/networkx#5801]
It is not stated in the documentations of `nx.ancestors()` and `nx.descendants()` about whether the node itself is included as ancestor/descendant or not. This information can be added to related documentations.

It is also possible to add a keyword argument to the source codes so that the user can include the node itself to its ancestors/descendants.

**Comment by rossbar** [comment]
I think my preference would be to state explicitly in the docstring that `ancestors` and `descendants` do not include `source` itself. One could even go so far as to provide an example for how a user could easily get the ancestors/descendants with the source node included, i.e. `nx.ancestors(G, n) | n`. IMO this is preferable to expanding the API of `ancestors`/`descendants`, but that's just my opinion!

**Comment by SultanOrazbayev** [comment]
This appears to be resolved by #5802.

**Comment by rossbar** [comment]
Agreed, thanks all!
