### ISSUE TITLE
nx.is_isomorphic does not give consisten results

### ISSUE THREAD

**Issue by LiuCMU** [networkx/networkx#5804]
Hi, could you please take a look at the case about the `nx.is_isomorphic` function? Thank you very much!

### Current Behavior
Two graphs that should be isomorphic are defined as False by `nx.is_ismorphic()` function.

### Expected Behavior
The `nx.is_isomorphic()`function should return True

### Steps to Reproduce
The `G_small.pkl` and `acid_r.pkl` graphs are in the attached `Archive.zip` file. 
As far as I know, these two graphs are isomorphic, which is also supported by the first three isomorphic test. However, the last isomorphic test returned False.
```{Python}
# load the first graph: G_small
G_small = pickle.load(open("G_small.pkl", "rb"))
nx.draw(G_small, with_labels=True, font_weight='bold')

# load the second graph: acid_r
acid_r = pickle.load(open("acid_r.pkl", "rb"))
nx.draw(acid_r, with_labels=True, font_weight="bold")


def node_match(dct1, dct2):
    """Helper function for nx.is_isomorphic
    This function receives the attribute dictionary for two nodes
    Returns True if the attribute are the same
    """
    atomic_num1 = dct1["atomic_num"]
    atomic_num2 = dct2["atomic_num"]
    return (atomic_num1 == atomic_num2)
    

def edge_match(dct1, dct2):
    """Helper function for nx.is_isomorphic
    This function receives the attribute dictionary for two nodes
    Returns True if the attribute are the same
    """
    bond_type1 = dct1["bond_type"]
    bond_type2 = dct2["bond_type"]
    return (bond_type1 == bond_type2)


print(nx.is_isomorphic(G_small, acid_r))  #True
print(nx.is_isomorphic(G_small, acid_r, node_match=node_match))  #True
print(nx.is_isomorphic(G_small, acid_r, edge_match=edge_match))  #True
print(nx.is_isomorphic(G_small, acid_r, node_match, edge_match))  #False
```
[Archive.zip](https://github.com/networkx/networkx/files/8945464/Archive.zip)

### Environment
Python version: 3.9.10 
NetworkX version: 2.8

**Comment by MridulS** [comment]
Thanks for the report @LiuCMU!

My first hunch was this is a bug too! But it's not, these graphs are structurally isomorphic and isomorphic only if you either take the `bond_type` or `atomic_num` but not both!!

After spending way too much time debugging the NetworkX codebase I drew these things out and they are totally different "molecules" if we take both `bond_type` and `atomic_num`. The hexagonal rings inside them can't be exchanged with each other if we take both `bond_type` and `atomic_num` together.


![Scanned Documents](https://user-images.githubusercontent.com/5363860/174770592-843e91ac-61d9-4aa4-936d-88056e9eeb43.png)
