### ISSUE TITLE
karate_club_graph()

### ISSUE THREAD

**Issue by clevo4040** [networkx/networkx#5820]
Zachary's karate club has 17 members in each of the two communities. The original paper, other literature, Barabarsi's Network Science, and other online references suggest that the size of each community is 16 and 18, not 17 and 17. This suggest that at least one of the club member nodes is initialized wrong here:
club1 = {0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 16, 17, 19, 21}
len(club1) is 17.  

### Environment

Python version:
NetworkX version: 2.6.3 and 2.8.4

**Comment by rossbar** [comment]
I went ahead and double-checked this against the original paper. The `club` attribute assigned to the nodes in `karate_club_graph` is consistent with the ground-truth from the paper (i.e. the "club after fission" column of table 1). The only difference is that the nodes are 1-indexed in the paper and 0-indexed in NetworkX.

The 16/18 community sizes appear to correspond to the cuts determined by running `NETFLOW` on the data (i.e. the "side of cut" column in Table 1).

This should hopefully clear things up and I don't think there's any info really missing in the docstring, but concrete suggestions on how things could be improved are always welcome - feel free to reopen in that case.

**Comment by clevo4040** [comment]
Appreciate your quick response! I recognize the 1-indexed node of the original paper and the 0-indexing used here.

As you will see from the following node 8 has been placed into the wrong community. 

Ground Truth 17/17 from Networkx `karate_club_graph`
club1 = {0, 1, 2, 3, 4, 5, 6, 7, 8, 10, 11, 12, 13, 16, 17, 19, 21}

Ground Truth 16/18 from original publication (0-indexed)
club1 = {0, 1, 2, 3, 4, 5, 6, 7,     10, 11, 12, 13, 16, 17, 19, 21}

Ground Truth 17/17 from Networkx `karate_club_graph`
<img width="793" alt="Screen Shot 2022-06-26 at 4 27 04 PM" src="https://user-images.githubusercontent.com/39634251/175834395-8253e4b4-9848-44f1-9004-3644daddb5ac.png">


Ground Truth 17/17 from original publication (0-indexed)
<img width="505" alt="Screen Shot 2022-06-26 at 4 22 26 PM" src="https://user-images.githubusercontent.com/39634251/175834275-7271bdf7-2f44-4d99-a008-8401233ad36f.png">

**Comment by dschult** [comment]
It looks like you are looking at the "Faction" column of the original paper instead of the "Club After Fission" column.
The original paper has 17 members in each of the two clubs after the split.
