### ISSUE TITLE
Bug in closeness_centrality() for bipartite

### ISSUE THREAD

**Issue by teddy21019** [networkx/networkx#5826]
### Current Behavior

Source code file: `networkx/algorithms/bipartite/centrality.py`
Function: closeness_centrallity()

In line 255 and line 265, it assigns 0 to `closeness[n]`
### Expected Behavior

It should be `closeness[node]` instead

Python version: python 3.8.3
NetworkX version: 2.8.4

**Comment by rossbar** [comment]
This was recently changed in #5308 - the line numbers mentioned above don't match those given in the OP. Can you take a look at [the development branch](https://github.com/networkx/networkx/blob/main/networkx/algorithms/centrality/closeness.py) and verify whether you still believe there's an issue? Everything looks correct AFAICT, but I don't know specifically what's being referred to above.

**Comment by teddy21019** [comment]
Thank you for the reply. 
The code I was looking at was the source code presented in the website 
https://networkx.org/documentation/stable/_modules/networkx/algorithms/bipartite/centrality.html#closeness_centrality

But just as you mentioned, the issue seems to be fixed in the development branch. I appreciate your reply and the work of your team, thank you!
