### ISSUE TITLE
Update documentation surrounding `union`, `disjoint_union`, `compose` and `Graph.update`

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#5828]
This is an action item extracted from the discussion in #4208.

It's not always immediately clear to users how the various operators `union`, `disjoint_union`, and `compose` differ and for which use-cases each is appropriate. There is also the `update` method of the graph classes, which simply updates the nodes/edges of a graph in-place with those of another, which is related to the above operations. It would be an improvement to ensure that the docstrings for these functions all include a link to the `update` method.

It may also be worthwhile to update the `operators` module docstring with examples highlighting the use-cases and differences between all of these operations.

**Comment by brocla** [comment]
I'd like to be assigned to this issue. I've read through the discussion in https://github.com/networkx/networkx/issues/4208. I think I can clarify the difference between `union`, `disjoint_union`, `compose` and `Graph.update`

The first time I wanted to combine two graphs, I started at `union`, which was not what I really wanted. I can leave some descriptive bread crumbs in the "See Also" section.

Also, can an update the `operators` module so the descriptions there are consistent with the updates elsewhere.

There were some comments about improving the error message of `union`, which I could do, but perhaps that was meant to be raised in a separate issue.

**Comment by rossbar** [comment]
Sounds good @brocla ! Just as a heads up - NetworkX typically doesn't assign issues. Generally we just ask that you check whether there is already an open PR linked to the issue (you can usually see this in the `Development` panel on the RHS of the page in GitHub). Since there isn't anything open in this case, please feel free to make a PR!

If you're interested in more tid-bits about the typical project workflow, you can check out [this FAQ](https://networkx.org/documentation/latest/developer/new_contributor_faq.html#q-i-ve-found-an-issue-i-m-interested-in-can-i-have-it-assigned-to-me) (feedback welcome of course)!

**Comment by brocla** [comment]
I made PR# 5892.

The docstrings for `union`, `disjoint_union`, and `compose` all point to each other and to `Graph.update()`.  And there is a breadcrumb statement that suggests why an alternative might be useful.

I tried to write the first line description to include a hint about about the way common nodes and edges are treated.

And I tried to begin the descriptions with more generic action words, like "Combine" and work my way up to more specific words like, "disjoint".

Please take a look.  I can make any changes.

**Comment by brocla** [comment]
When there is agreement on these docstring changes, they should also be rolled into `union_all`, `disjoint_all`, `compose_all`
