### ISSUE TITLE
Add ThinGraph example to Multi*Graph doc_strings

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#5854]
Based on discussion in #5813 we should add an example of a subclass of the graph classes to the MultiGraph and MultiDiGraph classes. The `ThinGraph` example from the Graph and DiGraph doc_strings was suggested in that discussion and would be easy to copy over.

**Comment by rossbar** [comment]
Agreed - this is a good idea. Another benefit of moving this is that the ThinGraph would actually be executable, which would serve as additional, practical testing of the factory function mechanism for subclasses.
