### ISSUE TITLE
Update `all_pairs_lca` docstrings

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#5862]
Just a few potential improvements I noticed while reviewing #5736:

 - [ ] The `Returns` section should actually be a `Yields` as this is a generator. This should also simplify the return description
 - [ ] Add a `Raises` section to indicate when exceptions are raised (graph is undirected, graph isn't DAG, graph is empty, etc.)
 - [ ] Update example to show usage both with and without the `pairs` argument.

Note that these changes should be made to the `naive` fn docstring as well.

**Comment by dschult** [comment]
These are all in the module: `networkx/algorithms/lowest_common_ancestors.py`
