### ISSUE TITLE
Cleanup LCA tests

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#5863]
Taking a look at the [LCA test suite](https://github.com/networkx/networkx/blob/main/networkx/algorithms/tests/test_lowest_common_ancestors.py), it looks to me like there are some opportunities to improve the tests.

One obvious one is the test naming scheme: the test methods are enumerated with a comment that explains what the test is for. With the pytest framework, it'd be better if the test method name itself described the test - that way, it'd be easier to get a sense of what's going wrong from the pytest summary when a test fails. For example:

https://github.com/networkx/networkx/blob/8522eea3955f5cf3da43cacc27643d93768aeb03/networkx/algorithms/tests/test_lowest_common_ancestors.py#L131

There are other opportunities to make things easier to read, see e.g. [this comment](https://github.com/networkx/networkx/pull/5736#discussion_r920970920).

As always with tests, the most important thing is that the test behaves exactly as expected.

**Comment by tindi-plus** [comment]
I am working on this.
