### ISSUE TITLE
Mixins incompatible with Graph

### ISSUE THREAD

**Issue by NeilGirdhar** [networkx/networkx#5865]
Using a Mixin with `Graph` is currently perilous:
```python
class Specialized(Graph, Mixin): ...

s = Specialized()  # Mixin.__init__ is not called!!
```

**Comment by dschult** [comment]
What's your use case for this?  I know what you are saying we should do and why. 
But what are you trying to do that makes this helpful for you?

**Comment by NeilGirdhar** [comment]
@dschult My main motivation is that it simplifies the type annotation PR.  However, I believe there are no downsides to repairing this.

**Comment by MridulS** [comment]
Wouldn't it make more sense for compatibility that Mixin is the first base class in the MRO and also call `super().__init__()`? This will make sure the user has more control over the behavior.
 
``` python
In [1]: class Mixin:
    ...:     def __init__(self, *args, **kwargs):
    ...:         print('Mixin is initialized!')
    ...:         super().__init__(*args, **kwargs)
    ...:

In [2]: class Specialized(Mixin, Graph):
    ...:     pass
    ...:

In [3]: Specialized([(1, 2), (2, 3)]).nodes()
Mixin is initialized!
Out[3]: NodeView((1, 2, 3))
```

**Comment by NeilGirdhar** [comment]
> Wouldn't it make more sense for compatibility that Mixin is the first base class in the MRO and also call super().__init__()?

Yes, that's fine until some other base class takes the same approach of declaring that it must come last in every inheritance list.  Then, you can't do anything.

In any case, it's still better to call super just in case someone tries to use a `Mixin` this way since currently there is silent failure to initialize.

**Comment by dschult** [comment]
I'm quite sure we don't want to try to anticipate all the possible mixin init functions that people could possibly want to use. We would need to give up our current ability to tell the user that they spelled `incoming_graph_data` incorrectly. It'd be unlikely they we'd anticipate every case anyway, and it would encourage inheritance in precisely the cases (orthogonal base classes) where using composition instead of inheritance is generally considered better anyway.

I checked other packages in the Scientific Python ecosystem and none of them use `super().__init__` on any classes that inherit from `object`. Many of the packages have multiple inheritance and some even have diamond inheritance. But they only use `super` in objects that subclass something other than object.

**Comment by NeilGirdhar** [comment]
> I'm quite sure we don't want to try to anticipate all the possible mixin init functions

In that case, you should probably block it by asserting that `super().__init__ is object.__init__`.  Otherwise, people get silent failures to initialize.

> I checked other packages in the Scientific Python ecosystem and none of them use super().__init__ on any classes that inherit from object

Yes, it's unfortunately a bug there too.  This does cause problems though.  Matplotlib recently had a problem with PySide classes not calling super.  I've run into the problem before too, but I was able to get the library maintainers to fix their problems.

The reality is that many library don't anticipate inheritance and forget to call super.

> Many of the packages have multiple inheritance and some even have diamond inheritance. But they only use super in objects that subclass something other than object.

The problem is that they're not considering that the user may want to subclass too.  That's when forgetting to call super is a problem.  It's just lack of foresight.  Eventually the linters (or the users) will start complaining and then people will fix their code.

**Comment by rossbar** [comment]
I'm not an OO programming expert, so take this with a grain of salt, but it's my understanding that the mixin multiple inheritance pattern is primarily for extending methods, *not* creating a "subtype" (where concrete instantiation is important). A quick excerpt from [Fluent Python](https://www.oreilly.com/library/view/fluent-python/9781491946237/) (emphasis mine):

> 3. Use Mixins for Code Reuse
> If a class is designed to provide method implementations for reuse by multiple unrelated subclasses, without implying an “is-a” relationship, it should be an explicit mixin class. Conceptually, a mixin does not define a new type; it merely bundles methods for reuse. **A mixin should never be instantiated**, and concrete classes should not inherit only from a mixin. Each mixin should provide a single specific behavior, implementing few and very closely related methods.
> 
> Fluent Python, 1st ed., pp. 359

This makes it seem like it is incumbent on the designer of the mixin/subclasses to not rely on instantiation from the parent class.

**Comment by NeilGirdhar** [comment]
> the mixin multiple inheritance pattern is primarily for extending methods, not creating a "subtype" (where concrete instantiation is important). 

Mixins are used by creating a subtype.

> If a class is designed to provide method implementations for reuse by multiple unrelated subclasses, without implying an “is-a” relationship, it should be an explicit mixin class. Conceptually, a mixin does not define a new type; it merely bundles methods for reuse. A mixin should never be instantiated, 

Exactly.  The mixin itself isn't instantiated, but the subclass is.  For example:

```python
class SerializationMixin:
  "This class provides serialization methods."
  def serialize(self) -> bytes: ...
  @classmethod
  def deserialize(cls, serialized_value: bytes) -> Self: ...
  def _contents(self) -> tuple[Any]:
     "Override this method to provide serialization"
    return ()

class SerializableGraph(Graph, SerializationMixin):
  def _contents(self) -> tuple[Any]:
    return tuple(self.nodes) + super()._contents()  # or whatever you want to serialize.
```

**Comment by dschult** [comment]
Mixins should be changing the methods of the class, not the data.  The example Mixin doesn't have an `__init__` for this reason. And there is no problem in this example with Graph not calling `super().__init__`. In this example, problems would arise if Graph had a method called `_contents`. Then Graph would interfere in your attempts to call `SerializationMixin._contents` using `super()._contents`.  But we're not going to put `super().method()` in every `method` in Graph.

I'm not sure what programming language background you are coming from, but this is not a good way to use Python to provide serialization classes. A cleaner interface in Python for `SerializableGraph` would contain the graph as an attribute -- not subclass the Graph class. 

We are spending way too much time on these debates. The idea that any of us know "the right way" to organize the classes/methods/types is counter-productive and disrupts the community. Ultimately, it is the community that decides which way this package is going to choose to organize its classes/method/types. There is no "right way".

Similarly, we are looking at and thinking about typing, just as we have looked at and thought about other ideas like `super()`. Please try to participate in the discussion in a way that respects the work that has gone into this project and the ideas and opinions of others in this community.

**Comment by NeilGirdhar** [comment]
> We are spending way too much time on these debates. The idea that any of us know "the right way" to organize the classes/methods/types is counter-productive and disrupts the community. Ultimately, it is the community that decides which way this package is going to choose to organize its classes/method/types. There is no "right way".

> Similarly, we are looking at and thinking about typing, just as we have looked at and thought about other ideas like super(). Please try to participate in the discussion in a way that respects the work that has gone into this project and the ideas and opinions of others in this community.

I'm really sorry that you feel like I'm disrespecting your work, ideas, or opinions.  I love networkx.  It's a fantastic graph library.

All that I've done is make some suggestions based on my experience and try to support them with clear reasons.  You're welcome to disagree of course, and I've always respected that.

So I find this comment a bit odd.  All I did was suggest that we add type annotations.  I wrote the pull request and waited literally years for it to be reviewed.  And there's been a tremendous amount of honestly puzzling recalcitrance for what I think many people in the community seem to support.

It really feels like there is a sense that historical code should be protected.  In my career, I learned a long time ago never to get attached to my work or my code, to focus on deliverables, and to be idealistic when possible.  So for example when @danieleades recently edited (https://github.com/networkx/networkx/pull/4014#discussion_r921010410) my pull request to add `contextlib.suppress` (which I didn't know about), I immediately recognized that it was superior to what I had and I approved it.

I just don't feel the same kind of idealism with the way my suggestions are considered.

The reason calling super is important is because allows replaces silent failures to initialize with proper initialization (when the parent class requires no parameters) or an error (otherwise).  Your argument is that we can't support the "otherwise" case, so let's just keep not calling super.  I just find it odd.  There's no downside to calling super, and there are only upsides.

So I accepted your wishes, and suggested that you at least block parent classes.  That way, if you change your mind one day, you won't have to worry about breaking code that does something like explicitly calling the mixin's initializzer.  But you're ignoring these suggestions.

And this isn't the first time we've gone through this kind of discussion.  We had a huge discussion https://github.com/networkx/networkx/issues/3995 about whether `x is True`, which is explicitly proscribed by PEP 8.

For some reason, I feel like you're interpreting any changes to the networkx code as "disrespecting people's contributions" because "there's no 'right way'".

I just don't see it that way.  I try to write the best, clearest code possible, and it's only out of a sense of professionalism that I create issues based on my experience, which I try to motivate them in good faith.  No "disrespect" is intended.  I'm really sorry that you feel that way.

**Comment by NeilGirdhar** [comment]
I'm going to respond to your last comment just because I think I ought to, but do with this as you like.

> Mixins should be changing the methods of the class, not the data.  The example Mixin doesn't have an __init__ for this reason.

Mixins can have their own data, which they store on the object.  For example, the serialization mixin could easily have taken an encoding for example and stored it as a member variable.  In that case, the mixin would have an `__init__`.

> problems would arise if Graph had a method called _contents

Yes, this is always an issue with mixins, and that's why member variables (and `__init__` keyword parameter) names are given fairly unique names to avoid collisions.

> I'm not sure what programming language background you are coming from, but this is not a good way to use Python to provide serialization classes. A cleaner interface in Python for SerializableGraph would contain the graph as an attribute -- not subclass the Graph class.

The principle you're describing is called _composition over inheritance_.  Of course you're right that composition should be preferred.  And your suggestion of _boxing_ the graph in an object with a serialization interface does make sense.  However inheritance is often used to imbue classes with behaviour like serialization, total ordering, caching, etc.  This is necessary when, for example, the mixins interact with one another, or the user doesn't want to have to box and unbox the objects constantly to just perform tasks with them.

Anyway, you could just imagine some mixin that does make sense if you don't like my serialization example.  Ordering for example, was my second choice.

**Comment by dschult** [comment]
Thanks for your comments here @NeilGirdhar. I think I responded when I was tired after a long week. Sorry about that. I apologize. I usually try to not do that.

I don't feel we are protecting code from change. We change lots of things. It is the style of the discussion that I was responding to -- not the particular proposal. It seemed like we were heading into a point/counter-point debate rather than a discussion. My desire is to keep the community enthusiastically showing each other cool ways to get things done, while trying to avoid the negative side effects of those cool ways (which occur with every cool way to get things done). The ultimate goal is to have fun and create useful beauty.

**Comment by charmoniumQ** [comment]
@NeilGirdhar is this needed for the type annotations PR (#4014)?

It seems to me it was needed at one point, when that PR tried to deduplicate code in the constructor but is not needed any longer.

**Comment by NeilGirdhar** [comment]
@dschult Dear Professor Schult, sorry that it's taken me so long to answer your last message. I think one problem with github is that we focus a lot on "issues" and forget to remind each other about all the great things that we appreciate:

You and the networkx team have created a marvelous graph library.  Whenever I need a graph library, I never craft my own.  I always reach for networkx.  It has a great interface, I'm confident in the code, and it has all the graph algorithms I'd ever need.  You should all be very proud of what you've accomplished, and I sincerely wish you all continued success.
