### ISSUE TITLE
Replace existing LCA functions with "naive" implementations?

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#5869]
#5736 recently added "naive" implementations of the LCA functions (thanks @dtekinoglu ! :rocket: ) which avoid some [long-standing bugs](https://github.com/networkx/networkx/issues?q=is%3Aopen+is%3Aissue+label%3ALCA) that have been identified by users with the existing implementation. #5736 added the fixes as new functions with the name `naive_` prepended to the existing function names.

My question is: instead of adding new function names, can we replace the existing LCA implementations with the new naive implementations? At face value, I think we can do so *without any deprecation warnings* because the naive implementations are really bug fixes - AFAICT there is no change to the API.

Is there appetite for this? I think it would be a very nice improvement and would allow us to close a lot of the LCA issues. I'm going to milestone this because we should decide whether to do this prior to the next release (so that we don't have to deprecate the new `naive_` function names).

**Comment by dschult** [comment]
I am +1 for just replacing the existing functions with these naive versions.  I haven't looked closely at the function signatures to see how direct this replacement is. But I think they were created to match, so it shouldn't be a problem. And I'd prefer to get this switched before any release so no deprecations are needed.  It could even be in v2.8.5 depending on the timing.

**Comment by U-238** [comment]
I am also +1 for replacing the existing LCA functions with the new ones from @dtekinoglu. The `naive_` functions provide correct results where the existing functions are incorrect. This is a bug fix, not a new function.

The issues I raised in #5628 relate to the definition of LCA in a DAG where multiple LCAs exist for a pair of nodes, potentially with different path lengths between those nodes and the LCAs, but that that not necessarily make the new functions "wrong".

**Comment by rossbar** [comment]
This was done in #5883 - closing!
