### ISSUE TITLE
generic_bfs_edges has apparently duplicated input arguments

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#5871]
The `generic_bfs_edges()` function has input arguments `neighbors` and `sort_neighbors` and they seems to do the same thing -- or more precisely, their functionality duplicates. 

`neighbors` is "A function that takes a newly visited node of the graph as input and returns an *iterator* (not just a list) of nodes that are neighbors of that node"

while `sort_neighbors` is "A function that takes the list of neighbors of given node as input, and returns an *iterator* over these neighbors but with custom ordering."

In the code, the neighbors of a node are found using:
```python
lambda node: iter(sort_neighbors(neighbors(node)))
```
But that just means that `neighbors` should have been set by the user to this composition of functions.

We need to at least make the doc_string more clear, but it seems that we should eliminate the `sort_neighbors` input and have users just provide `neighbors`. And the doc_strings should correctly reflect whether these function actually need to return iterators or not.

**Comment by still-n0thing** [comment]
- If I get this right ```neighbors``` is a callable object (or function) which decides how the neighbors of visited node should be added to the ```queue``` ? 
- Do we need to remove ```sort_neighbors```(is a callable object or function) and only work with ```neighbors```(is a callable object or function)? since that might cause break some things (I am not really sure about it)

**Comment by still-n0thing** [comment]
@dschult ?

**Comment by dschult** [comment]
You are correct that `neighbors` is a callable function that returns the neighbors of a visited node so they can be added to the queue. And `sort_neighbors` seems to do the same thing -- only it's name emphasizes the function of sorting the results. The idea of this issue is to combine these two input arguments into one and better document what that function does.

I'm not sure exactly how this would/should work. But I'm sure it will require a deprecation where one of the inputs still works but raises a DeprecationWarning if used.

**Comment by still-n0thing** [comment]
https://github.com/networkx/networkx/pull/5925 @dschult
