### ISSUE TITLE
Why does the API `all_simple_paths` miss the nodes in a simple CFG?

### ISSUE THREAD

**Issue by Hanseltu** [networkx/networkx#5872]
Hi all,

I am currently using `Networkx` API  (`all_simple_paths`) to explore all the simple paths in a CFG of a program, but it seems that this API can not explore all the possible paths in a simple CFG. Could you please check what happened here? Did I use `Networkx`  in an wrong way?

Please check the `png` from a `dot` file (attached at the end)

![test-cfg](https://user-images.githubusercontent.com/19731522/179227716-434f5d17-0297-4529-bd0c-3f8db271a2d5.png)

We can see that the nodes `0x4011ca`  and `4011cf` are in the CFG.

### Current Behavior

The paths explored by `all_simple_paths`:

```
path :  ['4011a3', '4011b0', '40120e', '401219', '401223', '401228', '40123f', '401244']
path :  ['4011a3', '4011b0', '40120e', '401219', '40123f', '401244']
```

### Expected Behavior

The paths should include the nodes `4011ca` and `4011cf`.

### Steps to Reproduce

The script I used to print the paths

```
import networkx as nx
import pygraphviz
from networkx.drawing import nx_agraph

G = nx_agraph.from_agraph(pygraphviz.AGraph("./test.dot"))
for path in nx.all_simple_paths(G, source="4011a3", target="401244"):
    print("path : ", path)
```
### Environment

Python version: 3.8.10
NetworkX version: 2.8.4

### Additional context

The `dot` file used : 
[test.dot.zip](https://github.com/networkx/networkx/files/9121018/test.dot.zip)

Thanks and look forward to your response!
Haoxin

**Comment by dschult** [comment]
You can't get from the source to the target by going through those two nodes **and not revisiting node 40120e**.  Revisiting a node means the path is no longer simple (it contains a cycle -- thus crossing itself).  That's why no paths through those two nodes are generated.

**Comment by Hanseltu** [comment]
Hi @dschult, thanks for your quick diagnosis! In that case, are there any solutions to get all the possible paths that include the cycles (we may set a bound to the cycle to avoid infinite iteration) in a graph by using existing APIs in `Networkx`? For the loops in the graph, I may just set the bound of the iterative times of those cycles (e.g., only visit once when encountering a cycle) if I manually traverse the graph.

**Comment by dschult** [comment]
That sounds specialized enough that a general function probably won't work. I suggest that you take the code for one of the path finding routines and morph it to handle the ideas you need.  One function to work from is [single_source_shortest_path](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.shortest_paths.unweighted.single_source_shortest_path.html)  click on the "source" link near the top and scroll down to the helper function below the main function. It is not too long and a straightforward set of loops that traverse the graph. You will need to change it to keep going beyond just finding the shortest path. And still making sure that it doesn't keep going too long.  

Another function you could work from is the [all_simple_paths](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.simple_paths.all_simple_paths.html) itself. Again, click on the "source" link and then scroll down to the helper function below the main function.  That one is a little more complicated logic based on whether there are ties in length so it keeps track of all the possibilities.

**Comment by Hanseltu** [comment]
Hi @dschult, thank you so much again for your speedy and helpful suggestions! Please allow me to explore further on this need. Thanks and have a good day!
