### ISSUE TITLE
Decorator for imports (migrated from Trac #598)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#589]
Original ticket https://networkx.lanl.gov/trac/ticket/598
Reported 2011-07-15 by @bjedwards, assigned to @bjedwards.

Need to fix skip test decorator so it works in python3, also provide decorator to check about importing outside packages and raise NetworkXError if it fails.

Code at:

https://bitbucket.org/bedwards/networkx-bedwards/src/d96d13a0bf58/networkx/utils/decorators.py

**Comment by hagberg** [comment]
Closed due to inactivity.
