### ISSUE TITLE
Critical NetworkX 2.8.X bug with mutable cached_properties

### ISSUE THREAD

**Issue by tdene** [networkx/networkx#5893]
### Current Behavior

The `nodes()` method of a Graph is decorated with `@cached_property`.<br>
This leads to the assumption that a Graph's `nodes()` method should return a static value.<br>
This assumption is incorrect.

Notably, the `@cached_property` decorator completely breaks `Graph.subgraph()`.<br>
Trace:

Graph.subgraph -> graphviews.subgraph_view -> [this line](https://github.com/networkx/networkx/blob/ead0e65bda59862e329f2e6f1da47919c6b07ca9/networkx/classes/graphviews.py#L149) prevents [this line](https://github.com/networkx/networkx/blob/ead0e65bda59862e329f2e6f1da47919c6b07ca9/networkx/classes/graphviews.py#L152) from functioning correctly

Subgraphs are shown as containing the wrong nodes as a result, until `del G.nodes` is manually run.<br>
This breaks things.

### Expected Behavior

`@cached_property` decorators should not break functionality.

### Steps to Reproduce

- Initialize a Graph, `G`
- Populate `G` with node objects that are complex enough that the following inequality assertion will pass: `newG = nx.freeze(G.__class__()); newG._graph = G; newG.graph = G.graph; assert(newG.nodes()!=G.nodes)`.
- Pick a subset of `G.nodes`, call this `subG_nodes`
- `subgraph = G.subgraph(subG_nodes)`
- In NetworkX 2.7, the nodes of `subgraph` will be a subset of the nodes of `G`. In NetworkX 2.8, the nodes of `subgraph` and the nodes of `G` will be a fully disjoint set.

### Environment

Python version: 3.9.10
NetworkX version: 2.8.5 vs 2.7.0

**Comment by dschult** [comment]
Thank you!  This is indeed a bug. We will need to make a similar fix to the ones we made for G.adj/G.succ/G.pred
That is, add a data descriptor for G._node which resets the cache when G._node is set.

**Comment by dschult** [comment]
The workaround until a fix is ready is:
```
subgraph = G.subgraph(subG_nodes)
del subgraph.nodes
```
