### ISSUE TITLE
Incompatibility between `pydot_layout` + `draw_networkx_{nodes, edges, labels}` for graphs with non-string nodes

### ISSUE THREAD

**Issue by ekhahniii** [networkx/networkx#5895]
Previously, `pydot_layout` handled graphs with non-string nodes. At least as of 2.8.4, the returned `dict` of positions is keyed by the string representation of the nodes, rather than the node objects themselves. This introduces an incompatibility with e.g. `draw_networkx_{nodes, edges, labels}`.

Perhaps related to #5710.

### Current Behavior

```python
import networkx as nx
from matplotlib import pyplot as plt


G = nx.DiGraph()
G.add_nodes_from([1, 2])
G.add_edges_from([(1, 2)])
pos = nx.nx_pydot.pydot_layout(G)
f, ax = plt.subplots()
nx.draw_networkx_nodes(G, ax=ax, pos=pos)
nx.draw_networkx_edges(G, ax=ax, pos=pos)
nx.draw_networkx_labels(G, ax=ax, pos=pos)
plt.tight_layout()
plt.show()
```
```
Traceback (most recent call last):
  File "...\lib\site-packages\networkx\drawing\nx_pylab.py", line 425, in draw_networkx_nodes
    xy = np.asarray([pos[v] for v in nodelist])
  File "...\lib\site-packages\networkx\drawing\nx_pylab.py", line 425, in <listcomp>
    xy = np.asarray([pos[v] for v in nodelist])
KeyError: 1

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "...\bugs\networkx_2_8_4_pydot.py", line 30, in <module>
    nx.draw_networkx_nodes(G, ax=ax, pos=pos)
  File "...\lib\site-packages\networkx\drawing\nx_pylab.py", line 427, in draw_networkx_nodes
    raise nx.NetworkXError(f"Node {err} has no position.") from err
networkx.exception.NetworkXError: Node 1 has no position.
```

### Expected Behavior

`draw_networkx_{nodes, edges, labels}` can accept both the graph provided to `pydot_layout` and the `dict` of positions produced by `pydot_layout`.

A workaround is to recreate the graph with the string representation of the nodes; however, the user must then replicate whatever modification was made to the string keys in `pydot_layout` or wantonly assume no modifications were made.

### Steps to Reproduce

See current behavior.

### Environment

Python version: 3.9
NetworkX version: 2.8.4

**Comment by MridulS** [comment]
This is fixed in networkx 2.8.5, could you update the networkx version?

Also we are looking into removing pydot as it isn't actively maintained https://github.com/networkx/networkx/issues/5723, so please do comment there if you have any feelings about this change :)
