### ISSUE TITLE
louvain_partitions iteration difference

### ISSUE THREAD

**Issue by Henniez-SwissWater** [networkx/networkx#5901]
louvain_partitions leads to different clusterings depending on how one iterates over the returned generator

### Current Behavior
If I iterate over the generator returned from louvain_partitions by a for loop I get for each iteration the expected clustering levels. 
However, if I first create a list (or tuple, deque...) and then iterate over the list I get different results. In fact, the levels have certain clusters which are empty if I iterate over the list. 

### Expected Behavior
I would expect that no matter how I iterate over the resulting generator I would get the same results.

### Steps to Reproduce
```
import networkx as nx
import networkx.algorithms.community as nx_comm

G = nx.path_graph(200)

def evaluate(part):
    print(len(part))
    count = 0
    for nodes in part:
        if len(nodes) == 0:
            count += 1
    print(f"\tEmpty Clusters: {count}")

louvian_clustering = list(nx_comm.louvain_partitions(G, resolution=1, seed=20))
for part in louvian_clustering:
    evaluate(part)

print("----")

for part in nx_comm.louvain_partitions(G, resolution=1, seed=20):
    evaluate(part)
```
Output
```
90
    Empty Clusters: 76 
41
    Empty Clusters: 27 
17 
    Empty Clusters: 3
 14
    Empty Clusters: 0
 ----
 90
    Empty Clusters: 0
 41 
    Empty Clusters: 0 
17
    Empty Clusters: 0 
14 
    Empty Clusters: 0
```

### Environment

Python version: 3.10.5
NetworkX version: 2.8.5

**Comment by dschult** [comment]
Thank you very much for reporting this!!

This is a very strange an ugly bug.  It stems from the function yielding a list-of-sets without copying those sets. When the next partition is requested, the sets are updated while computing the next partition. So the originally yielded partition gets changed while computing the next partition. This doesn't show up if you process each partition before iterating to the next partition. Here's a test that fails due to this bug.

```python
def test_partition_iterator():
    G = nx.path_graph(15)
    parts_iter = nx.community.louvain_partitions(G, seed=42)
    first_part = next(parts_iter)
    first_copy = [s.copy() for s in first_part]

    # gh-5901 reports sets changing after next partition is yielded
    assert first_copy[0] == first_part[0]
    second_part = next(parts_iter)
    assert first_copy[0] == first_part[0]
```
