### ISSUE TITLE
s_metric normalized parameter defaults to true resulting in error

### ISSUE THREAD

**Issue by adiehl96** [networkx/networkx#5906]
If I understand correctly, the following three lines always result in an error being raised unless the user changes the default value of the normalized parameter. Does someone know why this was never implemented?
https://github.com/networkx/networkx/blob/0c503e31ba0062dc9a4ed47c380481aa8d6978c8/networkx/algorithms/smetric.py#L6

https://github.com/networkx/networkx/blob/0c503e31ba0062dc9a4ed47c380481aa8d6978c8/networkx/algorithms/smetric.py#L33-L34

**Comment by dschult** [comment]
Actually, it was implemented and then removed. But that was close to 12 years ago before the git system was used so the comments describing why are harder to find. It looks like there used to be a graph generator which returned the graph with maximal s-metric for a given degree sequence. That is no longer provided so I'm guessing it had a problem that was not fixable.  If you know an algorithm to provide the maximal s-metric graph, or to compute the maximal s-metric itself, please let us know. 

Meanwhile, we should probably at least make the default value `False`  :)

**Comment by still-n0thing** [comment]
@dschult should I work on an algorithm to provide the maximal s-metric graph, or to compute the maximal s-metric itself, taking https://arxiv.org/abs/cond-mat/0501169 as an reference?

**Comment by dschult** [comment]
We already had a version of the code that generated the maximal s-metric graph for a given degree distribution according to the method in that paper. Based on [the "blame" report for the smetric.py module](https://github.com/networkx/networkx/blame/main/networkx/algorithms/smetric.py) it was put in place a year after the original code for smetric to be normalized. But then was removed a year after that. The older version was left as a comment, so I'm quite sure that there was a problem with the method to find the maximal s-metric.  So, doing what you propose would not get us to a reasonable normalization for the s-metric. 

I think it would be better to find a newer paper that discusses the s-metric, how it could be normalized, and what it is useful for. Then construct a normalization based on that new paper.

**Comment by dschult** [comment]
Here is a reference paper following up on the 2005 s-metric paper. It was written in 2008. It points out that the algorithm in the 2005 paper for finding a graph with maximal s-metric has not been proven to end. And in practice it appears that sometimes it takes so long you have to give up. If it finishes, then the resulting graph has the maximum value of the s-metric.

That is likely to be the cause of the removal and commenting out of code. The algorithms we have for finding the normalization factor aren't assured of finishing. We could approximate the value of s_max, but approximations aren't very useful for normalizing -- the resulting number could be greater than 1. So we probably shouldn't even provide a normalization option.

We currently do worse than that!  We make `normalized=True` the default -- and it always results in an exception.  Instead we should remove the normalized option (first deprecating it). During the deprecation period, we should check the `normalized` input parameter and if it is False, raise a warning that this option will be deprecated in version 3.1, that the default value is now False, and that users should just remove the `normalized=False` input in their code. We will also need to add a test of the deprecation warning, a filter in conftest.py to ignore the deprecation warning when CI testing and a note in the `doc/developer/deprecations.rst` file to remind us to remove the offending code once v3.1 comes.
