### ISSUE TITLE
all_simple_paths returns repeated paths if there are parallel arcs along the way

### ISSUE THREAD

**Issue by pmlpm1986** [networkx/networkx#5936]
### Current Behavior

The method all_simple_paths returns the same path multiple times if there are parallel arcs along the path. I have tested this with MultiDiGraphs.

This behaviour reflects the fact that there are different paths going through the same nodes, and since the method returns paths as sequences of nodes (unlike all_simple_edge_paths), the same path ends up being returned multiple times.

### Expected Behavior

One would expect this method to return only unique node paths, since not much is gained by repeating the paths.

Users seeking to find the actual paths (i.e., with edge keys) or the number of different paths should simply use all_simple_edge_paths.

### Steps to Reproduce

```
network = nx.MultiDiGraph()

number_nodes = 20

for node_index in range(number_nodes):

    network.add_node(node_index)

list_edges = [
    (0,1),(1,2),(2,3),(3,4),(4,5),(5,6),(6,7),(7,8),(8,9),(9,10),
    (0,11),(11,12),(12,13),(13,5),
    (6,14),(14,15),(15,16),(16,17),(17,18),(18,19),
    (8,8),
    (15,16) 
    ]

for _edge in list_edges:

    network.add_edge(_edge[0],_edge[1])

edge_paths = list(nx.all_simple_edge_paths(network,0, 16))

paths = list(nx.all_simple_paths(network,0, 16))

for path_index in range(len(paths)):
    #print('paths.count(paths[path_index]): '+str(paths.count(paths[path_index])))
    #print('edge_paths.count(edge_paths[path_index]): '+str(edge_paths.count(edge_paths[path_index])))
    assert paths.count(paths[path_index]) == edge_paths.count(edge_paths[path_index])
```

### Environment

Python version: 3.8
NetworkX version: 2.8.4

### Additional context

I have only tested this using MultiDiGraphs

### Suggestion

I don't think this behaviour is a dealbreaker nor completely unexpected. As such, I think explaining this behaviour in the documentation would be enough.

**Comment by rossbar** [comment]
+1 for documenting this. I think the behavior is intentional and arguably makes sense (after all, there are multiple paths via the different multiedges). I agree that the behavior might surprise users given that this yields lists of *nodes*, so the information about which specific edge was traversed is not captured in the output.

FWIW a simpler reproducing example:

```python
>>> G = nx.MultiDiGraph([(0, 1), (0, 1), (1, 2)])
>>> list(nx.all_simple_paths(G, 0, 2))
[[0, 1, 2], [0, 1, 2]]
```
