### ISSUE TITLE
Support Matplotlib 3.6rc1

### ISSUE THREAD

**Issue by jarrodmillman** [networkx/networkx#5938]
Not sure we need to address this before releasing NX 2.8.6, but it would be nice. See #5937.

We could ignore this for now and deal with it before 2.8.7. I've already backported all other 2.8.6 PRs to the v2.8 branch. We need to decide what to do about this, I need to update the 2.8.6 release notes (won't take long), and then make the release. I am busy this afternoon, so I will take care of this tonight or tomorrow morning.

**Comment by rossbar** [comment]
Looks like this was closed by #5937 , thanks @jarrodmillman !
