### ISSUE TITLE
all_pairs_shortest_path ties?

### ISSUE THREAD

**Issue by dzy49** [networkx/networkx#5949]
Hello, I am noticing that when multiple shortest path exist, all_pairs_shortest_path only return one.
I am wondering if there's anything setting that can allow the return of all shortest path(that have equal weight)?

**Comment by dschult** [comment]
It should return all shortest paths. It could be that you are running into round-off trouble or maybe another subtle distinction. Can you give a small example that has at least two shortest_paths but only returns one? Then we can track down the cause.

**Comment by dzy49** [comment]
I used an unweighted graph:
`G = nx.Graph()
G.add_node(1)
G.add_node(2)
G.add_node(3)
G.add_node(4)

G.add_edge(1, 2)
G.add_edge(2, 3)
G.add_edge(3, 4)
G.add_edge(1, 4)
path = dict(nx.all_pairs_shortest_path(G))`
and this is what I got for path
`{1: {1: [1], 2: [1, 2], 4: [1, 4], 3: [1, 2, 3]},
 2: {2: [2], 1: [2, 1], 3: [2, 3], 4: [2, 1, 4]},
 3: {3: [3], 2: [3, 2], 4: [3, 4], 1: [3, 2, 1]},
 4: {4: [4], 3: [4, 3], 1: [4, 1], 2: [4, 3, 2]}}`
which for node 1 to 3, there should be two shortest paths, [1,2,3] and [1,4,3]
is it because I converted the generator object into a dict?

**Comment by dschult** [comment]
Ahh... you are using `all_pairs_shortest_path` which finds a shortest path between all the pairs of nodes in the graph.  So it's not finding all paths. It is finding all **pairs**.  Sorry that I missed that in your original post.

You want:  `list(nx.all_simple_paths(G, 1, 3))`. The `list` is needed, because there may be a huge number of simple paths and so `all_simple_paths` is a generator which yields results one at a time.  If your graph gets big you should probably use:
```pythohn
for path in nx.all_simple_paths(G, 1, 3):
    # handle each oath one at a time
```
so you don't run out of memory making the list.

**Comment by dzy49** [comment]
> 
Sorry for the cofusion, it is kind hard to describe the problem clearly.
I dont think `all_simple_paths` is what I want. I only need the **shortest** path**s**, between all pairs of nodes. 
(which is like a variation of `all_shortest_paths` but for all pairs of nodes in the graph), I think this is achievable with a modification of floyd_warshall?)

**Comment by dschult** [comment]
How about:  `nx.all_shortest_paths` https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.shortest_paths.generic.all_shortest_paths.html

**Comment by dzy49** [comment]
> How about: `nx.all_shortest_paths` https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.shortest_paths.generic.all_shortest_paths.html

it could work, but I am a bit confused why it only works for one node to one node, as opposed to one node to all nodes since it uses dijkstra? So to get all pairs, I would need to run it O(n) times which is probably problematic since I am working on a large dataset.

**Comment by dschult** [comment]
Very good -- that would perhaps be a nice new feature.  If you click on the "Source" link at the top of the documentation link, you can see that most of the work is done by calling djikstra's predecessor_and_distance function. Then there is a helper function to build the paths from the predecessors.  That's the sticking point.  It might be fairly easy to rewrite that helper function for your special needs -- then call the dijkstra function and your special function to construct the multiple paths. We'd love to include such a function and make a `single_source_all_shortest_paths` kind of function. It would then be easy to create in turn an all_pairs version of that. Thoughts?

**Comment by dzy49** [comment]
> Very good -- that would perhaps be a nice new feature. If you click on the "Source" link at the top of the documentation link, you can see that most of the work is done by calling djikstra's predecessor_and_distance function. Then there is a helper function to build the paths from the predecessors. That's the sticking point. It might be fairly easy to rewrite that helper function for your special needs -- then call the dijkstra function and your special function to construct the multiple paths. We'd love to include such a function and make a `single_source_all_shortest_paths` kind of function. It would then be easy to create in turn an all_pairs version of that. Thoughts?

That seems like a good plan and suits my needs well.  I will try to implement that and create a PR. Thanks for the help!
