### ISSUE TITLE
[ENH] Adding typing support

### ISSUE THREAD

**Issue by cvanelteren** [networkx/networkx#5951]
Hi,
There is a general trend to add type hinting support to help guide the programmer and reader for adding new functionality. Type hinting was added in python 3.6, numpy added typing support in 1.20. Would it be an idea to add type support to networkx? It was thinking of adding a `typing` modules with something along the lines of 

- `AbstractGraph`
- `Graph`
- `DiGraph`
- `Edge` (directed or non-directed).

**Comment by MridulS** [comment]
There is a lot of conversation happening already about this at https://github.com/networkx/networkx/issues/3988, https://github.com/networkx/networkx/pull/4014, https://github.com/networkx/networkx/pull/5886. Let's not create a new issue about this :)
