### ISSUE TITLE
Estrada index (migrated from Trac #605)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#596]
Original ticket https://networkx.lanl.gov/trac/ticket/605
Reported 2011-07-22 by trac user franckkalala, assigned to @hagberg.

In chemical graph theory, the Estrada index is a topological index of protein folding. The index was first defined by Ernesto Estrada as a measure of the degree of folding of a protein,[1] which is represented as a path-graph weighted by the dihedral or torsional angles of the protein backbone. This index of degree of folding has found multiple applications in the study of protein functions and protein-ligand interactions.

[1] E. Estrada, Chem. Phys. Lett. 319, 713 (2000).

See also here  http://en.wikipedia.org/wiki/Estrada_index

**Comment by vlado-s** [comment]
Just a quick note - in _Chem. Phys. Lett_. **319** (2000) 713 (where Estrada index is introduced) it is defined as
_I_ = sum over i of exp{_lambda__i}
Here _lambda__i are the eigenvalues of the adjacency matrix of graph _G_.
However sometimes (e.g. in _Bioinf_. **18** (2002) 697 and apparently onward) he uses it normalised by _N_, which is the dimension of the adjacency matrix (number of nodes in _G_). 
The value calculated by NetworkX is the first value (not normalised) - just in case someone was wondering why the large number :) 
Also, obviously, NetworkX does not put the weights on the diagonal - as used (recommended) in chemical application.
