### ISSUE TITLE
Can not compute Laplacian matrix of graph (neither undirected nor directed)

### ISSUE THREAD

**Issue by jan0b** [networkx/networkx#5965]
### Current Behavior
I am trying to compute the laplacian matrix for a simple complete graph. When using  _nx.laplacian_matrix()_ or _nx.directed_laplacian_matrix()_ an error is thrown from the same location, due to a misfit of the matrix and offsets in the initialization of the scipy _dia_matrix_. Find the detailed error below.

### Expected Behavior
The expected behaviour is, that the laplacian is calculated normally. I achieved this by replacing:
`DI = sp.sparse.csr_array(sp.sparse.spdiags(1.0 / A.sum(axis=1), 0, n, n))`
with
`DI = sp.sparse.csr_array(sp.sparse.spdiags(1.0 / A.sum(axis=1).T, 0, n, n))`
in `networkx.linalg.laplacianmatrix._transition_matrix()` and `networkx.linalg.laplacianmatrix.laplacian_matrix()` respectively. But I am not sure, whether this is in line with the mathematical definition for calculating the laplacian matrix. I would apprecaite your help.

### Steps to Reproduce
Here is a short code snippet, to reproduce the error:

```
graph = nx.complete_graph(4)
graph_dir = graph.to_directed()

nx.laplacian_matrix(graph)
nx.directed_laplacian_matrix(graph_dir)
```

ERROR message:
```
File ~/.conda/envs/<<>>/lib/python3.8/site-packages/networkx/utils/decorators.py:845, in argmap.__call__.<locals>.func(_argmap__wrapper, *args, **kwargs)
    844 def func(*args, __wrapper=None, **kwargs):
--> 845     return argmap._lazy_compile(__wrapper)(*args, **kwargs)

File <class 'networkx.utils.decorators.argmap'> compilation 50:4, in argmap_laplacian_matrix_47(G, nodelist, weight)
      2 import collections
      3 import gzip
----> 4 import inspect
      5 import itertools
      6 import re

File ~/.conda/envs/<<>>/lib/python3.8/site-packages/networkx/linalg/laplacianmatrix.py:58, in laplacian_matrix(G, nodelist, weight)
     56 n, m = A.shape
     57 # TODO: rm csr_array wrapper when spdiags can produce arrays
---> 58 D = sp.sparse.csr_array(sp.sparse.spdiags(A.sum(axis=1), 0, m, n, format="csr"))
     59 import warnings
     61 warnings.warn(
     62     "laplacian_matrix will return a scipy.sparse array instead of a matrix in Networkx 3.0.",
     63     FutureWarning,
     64     stacklevel=2,
     65 )

File ~/.conda/envs/<<>>/lib/python3.8/site-packages/scipy/sparse/construct.py:60, in spdiags(data, diags, m, n, format)
     25 def spdiags(data, diags, m, n, format=None):
     26     """
     27     Return a sparse matrix from diagonals.
     28 
   (...)
     58 
     59     """
---> 60     return dia_matrix((data, diags), shape=(m,n)).asformat(format)

File ~/.conda/envs/<<>>/lib/python3.8/site-packages/scipy/sparse/dia.py:152, in dia_matrix.__init__(self, arg1, shape, dtype, copy)
    149     raise ValueError('data array must have rank 2')
    151 if self.data.shape[0] != len(self.offsets):
--> 152     raise ValueError('number of diagonals (%d) '
    153             'does not match the number of offsets (%d)'
    154             % (self.data.shape[0], len(self.offsets)))
    156 if len(np.unique(self.offsets)) != len(self.offsets):
    157     raise ValueError('offset array contains duplicate values')

ValueError: number of diagonals (4) does not match the number of offsets (1)
```

### Environment

Python version: 3.8.13
NetworkX version: 2.8.4 with conda

**Comment by dschult** [comment]
Thanks for this -- it is currently working on my installation. I am using Scipy 1.8.1.  What version of Scipy are you using.

**Comment by jan0b** [comment]
I am using Scipy version 1.7.3.

**Comment by rossbar** [comment]
Networkx > 2.7 requires scipy >= 1.8 due to the use of the sparse array interface as opposed to sparse matrices. Upgrading to scipy>=1.8 should fix the problem.

The fact that you ran into this issue implies there may be a problem with how the dependencies are specified in whichever "channel" you installed from with conda - do you remember how the conda environment was created?

**Comment by rossbar** [comment]
I'm going to close this one as resolved as it's a dependency issue. If the issue persists or you have any additional info about how the environment was created, please feel free to reopen/post.
