### ISSUE TITLE
Failure in vf2pp test suite from `pytest-randomly` workflow

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#5976]
The weekly execution of the test suite in randomized order caught a problem in the vf2pp test suite, specifically `test_candidates.TestCandidateSelection.test_no_covered_neighbors_no_labels`:

https://github.com/rossbar/networkx/runs/8261228458?check_suite_focus=true

I suspect that this is due to the input graphs being stored as class variables (e.g. `self.G1`) which are then modified by subsequent tests leading to unintended crosstalk between the test methods, though I haven't looked at this deeply enough to verify.

The first thing I would try is re-working the tests so that they do not depend on inputs defined as class variables.

**Comment by MridulS** [comment]
This is fixed now right @rossbar ?

https://github.com/networkx/networkx/blob/main/.github/workflows/pytest-randomly.yml seems to show that it's run without any exceptions.

**Comment by rossbar** [comment]
Yes I believe this fix was wrapped into #5972 . Thanks for the reminder!
