### ISSUE TITLE
Tests without assertions

### ISSUE THREAD

**Issue by DiamondJoseph** [networkx/networkx#5981]
### Current Behavior

Multiple tests lack assertions and are therefore incapable of failing.

### Expected Behavior

A test should (conceptually) be able to report a failure if a condition is not true.

### Steps to Reproduce

e.g. test_adjacency.py:11

    def test_graph(self):
        G = nx.path_graph(4)
        H = adjacency_graph(adjacency_data(G))
        nx.is_isomorphic(G, H)

which does not report a failed test with the following alteration:

    def test_graph(self):
        G = nx.path_graph(4)
        H = adjacency_graph(adjacency_data(G))
        nx.is_isomorphic(G, nx.path_graph(1))

### Environment

Python version: 3.10
NetworkX version: 2.8.6

### Additional context

I will submit a patchset linked to this issue with some obvious cases knocked off, but I suspect there will be more the harder I look.

**Comment by Qudirah** [comment]
Hello, I want to try working on this issue but I'm confused as to which test needs assertion. Would I have to run each of them?

**Comment by DiamondJoseph** [comment]
@Qudirah I picked up I think most of them in a pending patchset, but any test that calls is_isomorphic without an assert for one- there may be other methods that (used to?) don't throw an exception but also aren't checked by an assert.
