### ISSUE TITLE
Complement graph class for small footprint dense networks (migrated from Trac #608)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#599]
Original ticket https://networkx.lanl.gov/trac/ticket/608
Reported 2011-07-25 by @dschult, assigned to @hagberg.

It would be nice to include a complement graph data storage class to store dense networks without using a lot of memory.

Let's start with the example from ticket #589 called AntiGraph

**Comment by hagberg** [comment]
Closed due to inactivity.
