### ISSUE TITLE
check that expanders tests are all being run

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#6026]
Based on a comment in #6014 it would be good to check that the tests in `generators/tests/test_expanders.py` are all being run. If they are, the tests should have raised an error upon usage of `.A` (which was fixed in #6014).

At least that's how I understand the discussion ...

**Comment by rossbar** [comment]
Well, the good news is I put an `assert False` in all the tests in that module and got 4 failures, so that's a good sign! I wonder if it's related to the numpy/scipy optional dependencies...

I'd like to take the opportunity to very slightly reorganize the tests!
