### ISSUE TITLE
Improve test coverage for line graph generators

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#6028]
Currently we don't have full coverage for the line graphs generators. Code blocks which are highlighted with red at codcov https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/generators/line.py don't have corresponding tests. The tests should be added in https://github.com/networkx/networkx/blob/main/networkx/generators/tests/test_line.py

### Current Behavior

We don't test all the paths the code can take us.

### Expected Behavior

We should be testing everything so there aren't any surprises.

### Steps to Reproduce

Visit https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/generators/line.py

**Comment by nsengiyumva-wilberforce** [comment]
@MridulS, can I work on this?

**Comment by MridulS** [comment]
Yes please go ahead :)

**Comment by rkc88** [comment]
Hello @nsengiyumva-wilberforce are you still working on this? If not I would like to work on it

**Comment by yixin0829** [comment]
Hi @MridulS, I'm working on this right now and wondering do we need to write tests for testing private functions as well? I saw on CodeCov in `line.py` for example `_triangle()` is not fully covered.
