### ISSUE TITLE
Improve test coverage for algorithms in beamsearch.py

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#6030]
Currently we don't have full coverage for algorithms in beamsearch.py. Code blocks which are highlighted with red at codcov https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/algorithms/traversal/beamsearch.py don't have corresponding tests. The tests should be added in https://github.com/networkx/networkx/blob/main/networkx/algorithms/traversal/tests/test_beamsearch.py

### Current Behavior

We don't test all the paths the code can take us.

### Expected Behavior

We should be testing everything so there aren't any surprises.

### Steps to Reproduce

Visit https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/algorithms/traversal/beamsearch.py

**Comment by ladykkk** [comment]
fix#6045

**Comment by rossbar** [comment]
Fixed by #6087
