### ISSUE TITLE
 Improve test coverage for algorithms in dominating_set.py

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#6032]
Currently we don't have full coverage for algorithms in dominating_set.py. Code blocks which are highlighted with red at codcov https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/algorithms/approximation/dominating_set.py don't have corresponding tests. The tests should be added in https://github.com/networkx/networkx/blob/main/networkx/algorithms/approximation/tests/test_dominating_set.py
### Current Behavior

We don't test all the paths the code can take us.

### Expected Behavior

We should be testing everything so there aren't any surprises.

### Steps to Reproduce

Visit https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/algorithms/approximation/dominating_set.py

**Comment by chimaobi-okite** [comment]
Hi @MridulS , I would like to work on this.

**Comment by MridulS** [comment]
Sure, Please go ahead :)

**Comment by chimaobi-okite** [comment]
Hi @MridulS , I made a pull request on this , could you help review it?

**Comment by SultanOrazbayev** [comment]
Looks like this issue can be closed via #6068.

**Comment by rossbar** [comment]
Indeed, thanks @SultanOrazbayev !
