### ISSUE TITLE
Improve test coverage for algorithms in betweenness_subset.py

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#6033]
Currently we don't have full coverage for algorithms in betweenness_subset.py. Code blocks which are highlighted with red at codcov https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/algorithms/centrality/betweenness_subset.py don't have corresponding tests. The tests should be added in https://github.com/networkx/networkx/blob/main/networkx/algorithms/centrality/tests/test_betweenness_centrality_subset.py

### Current Behavior

We don't test all the paths the code can take us.

### Expected Behavior

We should be testing everything so there aren't any surprises.

### Steps to Reproduce

Visit https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/algorithms/centrality/betweenness_subset.py

**Comment by RoseZhen2022** [comment]
Hi @MridulS , I would like to work on this issue. Thanks!

**Comment by ladykkk** [comment]
Working on it now and opened PR for it.

**Comment by RoseZhen2022** [comment]
Hi @ladykkk , It's ok. I didn't know someone has taken this. If you need any help, I'm glad to be here. Thank you!

**Comment by yixin0829** [comment]
Hi @MridulS, me and my friends would like to add more tests to this issue if possible. Can we still work on this issue since I saw there's already one PR being merged?

**Comment by rossbar** [comment]
Thanks for the ping @yixin0829 - this looks to me like it was largely resolved by #6083 , so I will go ahead and close it. However, if you have concrete ideas for improving tests or coverage please don't hesitate to open a PR!
