### ISSUE TITLE
 Improve test coverage expanders stochastic graph generators

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#6035]
Currently we don't have full coverage for the stochastic graphs generators. Code blocks which are highlighted with red at codcov https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/generators/stochastic.py don't have corresponding tests. The tests should be added in https://github.com/networkx/networkx/blob/main/networkx/generators/tests/test_stochastic.py

### Current Behavior

We don't test all the paths the code can take us.

### Expected Behavior

We should be testing everything so there aren't any surprises.

### Steps to Reproduce

Visit https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/generators/stochastic.py

**Comment by paulitapb** [comment]
Working on this! Already made a pull request!
