### ISSUE TITLE
speed up for simple_cycles using components (migrated from Trac #613)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#604]
Original ticket https://networkx.lanl.gov/trac/ticket/613
Reported 2011-08-05 by @dschult, assigned to @dschult.

On the discussion list, Kevin Greene said (7/22/2011):

I'm currently working on processing large graphs representing object 
relations in a program. 

One aspect I'm interested in is the number of cycles, and how many 
nodes are present in cycles. 

However, the standard nx.simple_cycles() takes a very long time on my 
graphs (multiple days). 

But, if I create the strongly connected components, then iterate over 
all of the components, generating the cycles from them, the algorithm 
is significantly faster. The 46,000 node graph that takes multiple 
days with nx.simple_cycles takes about 5 minutes with my method. 

I think the reason is in the simple_cycles method: 
'''
    ordering=dict(zip(G,range(len(G)))) 
    for s in ordering: 
        # Build the subgraph induced by s and following nodes in the ordering 
        subgraph = G.subgraph(node for node in G 
                              if ordering[node] >= ordering[s]) 
        # Find the strongly connected component in the subgraph 
        # that contains the least node according to the ordering 
        strongcomp = nx.strongly_connected_components(subgraph) 
'''
It seems to me that this is generating the strongly connected 
components far too often, which can be costly in a large graph. 

Also, because of the nature of strongly connected components, no 
simple cycle should exist between two distinct components. So, if 
instead of 

'''nx.simple_cycles(G) '''

I do 
'''
s_components = nx.strongly_connected_components(G) 
cycles = [] 
for s_component in s_components: 
    if len(s_component) == 1: 
        continue 
    else: 
        for cycle in nx.simple_cycles(component): 
            cycles.append(cycle) 
'''
Is there any flaw in this? It is also much faster for the graphs I am 
working on, and seems like it would be faster in general, for any 
graph with at least a few strongly connected components.

**Comment by jfinkels** [comment]
Seems that this can be closed due to #874, #890, etc.
