### ISSUE TITLE
"Error: node, position, expected two doubles" when using AGraph renderer

### ISSUE THREAD

**Issue by reregaga** [networkx/networkx#6049]
### Current Behavior

Get error about `Error: node A, position (0, 0), expected two doubles`:
```
lib\site-packages\pygraphviz\agraph.py:1402: RuntimeWarning: Error: node A, position (0, 0), expected two doubles
Error: node B, position (1, 2), expected two doubles
```
if run code:
```python
import networkx as nx

# Create Graph
Gr = nx.Graph()
Gr.add_node('A', pos=(0, 0))
Gr.add_node('B', pos=(1, 2))

# Create AGraph
Ag = nx.nx_agraph.to_agraph(Gr)

# Output
Ag.write('out.dot')
Ag.layout('neato')
Ag.draw('out.png')
```

### Expected Behavior

Without errors.

#### Without converting `pos` I get this error and image is not correct
Code:
```python
import networkx as nx

# Create Graph
Gr = nx.Graph()
Gr.add_node('A', pos=(0, 0))
Gr.add_node('B', pos=(1, 2))

# Create AGraph
Ag = nx.nx_agraph.to_agraph(Gr)

# Output
Ag.write('out.dot')
Ag.layout('neato')
Ag.draw('out.png')
```
Result `out.dot` file:
```
strict graph "" {
	A	[pos="(0, 0)"];
	B	[pos="(1, 2)"];
}
```
Rendered image:
![out](https://user-images.githubusercontent.com/76629445/195459562-bcac373b-1ba1-4bb4-b7dc-b489161cdde4.png)

#### With manually converting `pos` I don't get error and image is correct
With code:
```python
import networkx as nx

# Create Graph
Gr = nx.Graph()
Gr.add_node('A', pos=(0, 0))
Gr.add_node('B', pos=(1, 2))

# Convert `"(x,y)"` to `(x,y!)`
for node in Gr:
    Gr.nodes[node]['pos'] = "{},{}!".format(
        Gr.nodes[node]['pos'][0], Gr.nodes[node]['pos'][1])

# Create AGraph
Ag = nx.nx_agraph.to_agraph(Gr)

# Output
Ag.write('out.dot')
Ag.layout('neato')
Ag.draw('out.png')
```
Result `out.dot` file:
```
strict graph "" {
	A	[pos="0,0!"];
	B	[pos="1,2!"];
}
```
Result image file:
![out](https://user-images.githubusercontent.com/76629445/195459409-037b104a-a829-4a9f-8c49-a024be5483cd.png)

### Environment

Python version: `3.9.1`
NetworkX version: `2.8.7`

### Additional info
Maybe I'm missing the right way to use `AGraph`, but now I noticed that `AGraph` writes a node position into the file `out.dot` in a format that does not correspond to the [DOT](https://graphviz.org/docs/attr-types/point/) format (`pos="(0,0)"` vs `pos="0,0"`), so I have to manually convert the position format, otherwise I will get an error and incorret `out.dot` and `out.png` files.

Related issue: https://github.com/networkx/networkx/issues/3731

**Comment by rossbar** [comment]
As the warning indicates there's certainly something wrong here, but I think the proposed doesn't really resolve the issue. It *does* result in the warning going away, but note that the node positions are not actually preserved after the `layout` call. In other words, the "correct" node layout about is actually a result of the `neato` layout program, not the positions specified as node attributes. You can verify this with a slightly more complicated example, e.g. using 3 co-linear nodes:

```python
>>> G = nx.Graph()
>>> for n in range(3):
...     G.add_node(n, pos=(n, n))
```

So the fix will suppress the warnings, but still not give the correct result.
