### ISSUE TITLE
Networkx tutorial does not include examples of vendor graph databases where networkx can be used.

### ISSUE THREAD

**Issue by tindi-plus** [networkx/networkx#6078]
The [networkx tutorial](https://networkx.org/documentation/latest/tutorial.html) does not include examples of graph databases that support networkx. For example, graph databases that support gremlin graph traversal language include AWS Neptune, Neo4j, InfinixGraph, etc. Read more [here](https://en.wikipedia.org/wiki/Gremlin_(query_language))

I believe that readers seeing practical databases where networkx can be used will greatly improve their chances of using nextworkx.

**Comment by MridulS** [comment]
Closing this as there a duplicate discussion https://github.com/networkx/networkx/discussions/6079
