### ISSUE TITLE
cutoff argument improperly disallowed when calling `minimum_cut` with `shortest_augmenting_path`

### ISSUE THREAD

**Issue by eecharlie** [networkx/networkx#6081]
It should be possible to call `minimum_cut(G, s, t, flow_func=shortest_augmenting_path, cutoff=3)` however this raises an exception.

From `maxflow.py`, `minium_cut()` definition:
```
    if kwargs.get("cutoff") is not None and flow_func in flow_funcs:
        raise nx.NetworkXError("cutoff should not be specified.")
```
where
```
# Functions that don't support cutoff for minimum cut computations.
flow_funcs = [
    boykov_kolmogorov,
    dinitz,
    edmonds_karp,
    preflow_push,
    shortest_augmenting_path,
]
```
however the docstring and source for `shortestaugmentingpath.py` do allow the `cutoff` argument.

**Comment by paulitapb** [comment]
I think the problem is that cutoff for shortest_augmenting_path is not working properly that's why is disabled even when the function does allow the argument.

**Comment by eecharlie** [comment]
Can you point me to any github issue or failing unit test for `shortest_augmenting_path`?

**Comment by dschult** [comment]
In the details of #1102 it seems that the initial flagging of functions that don't have the cutoff functionality correctly included the `shortest_augmenting_path` (as well as some others) but the `cutoff` functionality was added in a commit a few days later. It looks like an oversight that these functions did not get removed from the list of functions that do not support the cutoff input parameter.  

I believe there may be others in `flow_funcs` that also do now support (and long have supported) the cutoff feature.
Can someone check those functions and make a PR to correct the list of functions that don't support the cutoff feature?

I'm going to transfer this discussion to an Issue so we make sure to fix this.

**Comment by paulitapb** [comment]
I'll do it

**Comment by eecharlie** [comment]
Awesome! I might suggest the list variable be called `flow_funcs_without_cutoff` for readability.

**Comment by dschult** [comment]
I agree that the name of that variable needs to be changed. That suggestion looks good to me.

**Comment by paulitapb** [comment]
this is the PR that correct the list of functions that don't allow cutoff: https://github.com/networkx/networkx/pull/6085

**Comment by eecharlie** [comment]
So, follow up question as I keep pulling the string here...
The [doc page](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.connectivity.connectivity.local_edge_connectivity.html#local-edge-connectivity) for `local_edge_connectivity` interestingly uses `edmonds_karp` as the default max_flow algorithm and states that edmonds_karp and shortest_augmenting_path are the *only* flow algorithms supporting a cutoff criteria. It looks like there is inaccuracy and/or inconsistency here, and given the chained if statements in `local_edge_connectivity`, the property of supporting a cutoff value to inform a wrapped call to a flow function is something that happens in several max flow/min cut-related helper functions and can be reused.

**Comment by paulitapb** [comment]
I checked connectivity.py and `local_edge_connectivity` is using `edmonds_karp` if flow_func is None. Then when `maximum_flow_value` is called _flow_func_ is `edmonds_karp` because that is passed through _**kwargs_ argument. 
I did a simple experiment and I confirmed that. I also checked the doc page and It seems that we should correct that only edmonds_karp and shortest_augmenting_path support _cutoff_. I'll do that later. Also, I will read the doc page for related functions that may have the same inconsistency. Should I open a new issue for this @dschult ?

**Comment by dschult** [comment]
I don't think a new Issue for checking docs for correct statements about `cutoff` is needed. We can do that in this issue. And if the PR doesn't complete that process, that's OK. We can have multiple PRs if needed to fix this Issue. I guess I see fixing the docs and fixing the code as part of the same process.  Both are correcting this mismatch between which functions are providing a cutoff feature and which are listed as providing a cutoff feature.

**Comment by paulitapb** [comment]
I was trying to correct the doc page [local_edge_connectivity](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.connectivity.connectivity.local_edge_connectivity.html#networkx.algorithms.connectivity.connectivity.local_edge_connectivity). But I cant find where should I change it. @MridulS
