### ISSUE TITLE
boykov_kolmogorov and dinitz algorithms allow cutoff but are not tested 

### ISSUE THREAD

**Issue by paulitapb** [networkx/networkx#6086]
I noticed in *test_maxflow.py* that cutoff tests don't include boykov_kolmogorov and dinitz algorithms. I'm already working on this!

**Comment by dschult** [comment]
Great! You can connect this issue to that PR using the "Development" option on the right (under milestone). That makes a link so this Issue is automagically closed when that pull request is merged.

**Comment by paulitapb** [comment]
great!
