### ISSUE TITLE
Improve test coverage for multigraph class

### ISSUE THREAD

**Issue by Qudirah** [networkx/networkx#6088]
I discovered there are still some red spots in this link https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/classes/multigraph.py and will like to work on it. 

The tests will be added in https://github.com/networkx/networkx/blob/main/networkx/classes/tests/test_multigraph.py

Current Behavior
We don't test all the paths the code can take us.

Expected Behavior
We should be testing everything so there aren't any surprises.

Steps to Reproduce
Visit https://app.codecov.io/gh/networkx/networkx/blob/main//networkx/classes/multigraph.py

**Comment by Qudirah** [comment]
I noticed that the red line (line 480) is probably unnecessary. 

G = nx.MultiGraph()
G.add_edge(1,2)

works perfectly fine. 

and unless the statement is stated like:
G.add_edge (u_for_edge=1,v_for_edge=3) which anyone hardly ever does. 

When I used this G.add_edge (u_for_edge=None,v_for_edge=3), it did generate a graph with edge point none. What would you say I do? remove the test line as it seems unnecessary or add a test case for when None is specified.  @MridulS Please look at this.

**Comment by MridulS** [comment]
> When I used this G.add_edge (u_for_edge=None,v_for_edge=3), it did generate a graph with edge point none.

I can not reproduce this. This gives an error (as it should!). Can you give a minimal example how to reproduce this?
It shouldn't be possible to get a graph with a `None` node.
 
You need to add a test when somewhere tries to do something like
``` python
G = nx.MultiGraph()
G.add_edge(None, 'anything_else')
```
it generates an error.

**Comment by Qudirah** [comment]
<img width="454" alt="Multi_graph" src="https://user-images.githubusercontent.com/94577309/196652247-4731500f-7dfa-4fb2-b50e-912dbf23ecf9.PNG">

**Comment by Qudirah** [comment]
@MridulS This is the behavior. There is no error

**Comment by MridulS** [comment]
Well, that's interesting. Can you check your networkx version? What does `nx.__version__` prints out?

**Comment by MridulS** [comment]
This was fixed in https://github.com/networkx/networkx/pull/4892/ so should be in networkx version > 2.6

**Comment by Qudirah** [comment]
> 

I'm so sorry. I totally forgot to upgrade because I changed my laptop. I'll make a pull request now.
