### ISSUE TITLE
Invalid spanning tree returned by random_spanning_tree

### ISSUE THREAD

**Issue by mraa022** [networkx/networkx#6107]
Hello, i was trying to, given a complete 3-partite graph G, find a random spanning tree of G. so i used the networkx.algorithms.tree.mst.random_spanning_tree method, but it returned a tree t which is invalid since it connects 2 vertices in the same part (eg. 10 and 11 are in the same part but they share an edge). Here is my code 
`t = nx.algorithms.tree.mst.random_spanning_tree(G)`. here are the tree and the graph

`G = [[0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], [0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], [0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], [0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0], [1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0], [1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0], [1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0], [1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0], [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0], [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0], [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0], [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0], [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0], [1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0], [1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0]]

t = [[0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0], [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], [0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0], [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]]`

Here is my full code 
<img width="1184" alt="Screen Shot 2022-10-19 at 11 13 08 PM" src="https://user-images.githubusercontent.com/42101911/196847799-a2de4be6-95c5-44e3-8ae5-aff96fbf9da4.png">

Thanks in advance

**Comment by dschult** [comment]
The random spanning tree algorithm doesn't know about or maintain any information about the 3-partite structure of your network. That said, if you give it a graph G that respects the edge restrictions you are looking for, the spanning tree will be formed with only those edges and thus respect the edge restrictions too.

**Comment by rfulekjames** [comment]
I guess you meant `t = nx.algorithms.tree.mst.random_spanning_tree(graph)` rather than `t = nx.algorithms.tree.mst.random_spanning_tree(G)`.

I am not sure how you got your `t` matrix.

The problem might just be that the nodes are permuted in `t.nodes()` of type `NodeView` with respect to `graph.nodes()`. 
One can (re)-construct the tree `t` differently, so that the nodes are ordered in the same way as in `G` like as follows:
```
t = nx.algorithms.tree.mst.random_spanning_tree(graph)

T = [[0]*len(t.nodes()) for _ in range(len(t.nodes()))] 
for u, v in t.edges():
    T[u][v], T[v][u] = 1, 1

t = nx.Graph(np.array(T))
```
Would that solve the problem?

**Comment by mraa022** [comment]
> The random spanning tree algorithm doesn't know about or maintain any information about the 3-partite structure of your network. That said, if you give it a graph G that respects the edge restrictions you are looking for, the spanning tree will be formed with only those edges and thus respect the edge restrictions too.

I thought the algorithm found a spanning tree of G though, and to do that it can only pick edges already in G. some of the edges in my tree aren't even in G. am i misunderstanding the point of the algorithm? Can you please perhaps give an example of how to edit it so the tree it returns only has edges already in G.
Regards

**Comment by mraa022** [comment]
> I guess you meant `t = nx.algorithms.tree.mst.random_spanning_tree(nx.Graph(np.array(G)))` rather than `t = nx.algorithms.tree.mst.random_spanning_tree(G)`.
> 
> I am not sure how you got your `t` matrix.
> 
> The problem might just be that the nodes are permuted in `t.nodes()` of type `NodeView` with respect to `graph.nodes()`. One can (re)-construct the tree `t` differently, so that the nodes are ordered in the same way as in `G` like as follows:
> 
> ```
> t = nx.algorithms.tree.mst.random_spanning_tree(nx.Graph(np.array(G)))
> 
> T = [[0]*len(t.nodes()) for _ in range(len(t.nodes()))] 
> for u, v in t.edges():
>     T[u][v], T[v][u] = 1, 1
> 
> t = nx.Graph(np.array(T))
> ```
> 
> Would that solve the problem?

Unfortunately some vertices that are in the same part are still connected

**Comment by mraa022** [comment]
> 

Thank you for the detailed response. I ran your code and the assertion isn't raised in my machine too. Perhaps sharing the code that generates the invalid spanning trees would be better. So, bellow is the code i used to generate the spanning trees.
```.py
def generate_random_trees(G):
  # returns 2 different random spanning trees of G
  G = nx.Graph(G) # G is a numpy array of the adjacency matrix 
  t1 = nx.algorithms.tree.mst.random_spanning_tree(G)
  t2 = nx.algorithms.tree.mst.random_spanning_tree(G)
  while nx.utils.misc.graphs_equal(t1, t2):
    t2 = nx.algorithms.tree.mst.random_spanning_tree(G)
  return t1,t2
```
When i use this code to generate the spanning tree, one of t1 or t2 violates the partition property.

**Comment by rossbar** [comment]
> When i use this code to generate the spanning tree, one of t1 or t2 violates the partition property.

How often does this happen? Every time? Sometimes? Once? Again I am not able to reproduce, at least using another brute-force initial check for a failing instance:

```python
>>> for _ in range(1000):
...     t1, t2 = generate_random_trees(G)
...     assert is_tripartite(t1) and is_tripartite(t2)
```

There's nothing obvious in the above function to indicate whether/why there'd be a failure.

I suspect there is something going on outside of this function that is causing the behavior you are not expecting. For example, is `G` being modified in some way elsewhere in your code?

Without a full, minimal example that reproduces the behavior, I suspect it will be hard to say anything concrete about whether there may be a problem in `random_spanning_tree`

**Comment by mraa022** [comment]
> > When i use this code to generate the spanning tree, one of t1 or t2 violates the partition property.
> 
> How often does this happen? Every time? Sometimes? Once? Again I am not able to reproduce, at least using another brute-force initial check for a failing instance:
> 
> ```python
> >>> for _ in range(1000):
> ...     t1, t2 = generate_random_trees(G)
> ...     assert is_tripartite(t1) and is_tripartite(t2)
> ```
> 
> There's nothing obvious in the above function to indicate whether/why there'd be a failure.
> 
> I suspect there is something going on outside of this function that is causing the behavior you are not expecting. For example, is `G` being modified in some way elsewhere in your code?
> 
> Without a full, minimal example that reproduces the behavior, I suspect it will be hard to say anything concrete about whether there may be a problem in `random_spanning_tree`

sorry about that, after investigating more i realized the cause of the bug was something else. if you get a random spanning tree t of G, and then create another tree with the same Adjacency matrix as t  you get 2 different trees. the working example i have attached shows this.  Why is that? shouldnt 2 trees with the same adjacency matrix equal one another?
Thank you soo much for the help, sorry i am kind of new to this library.
```.py
adj_matrix = [
[0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
[0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
[0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
[0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0],
[1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0],
[1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0],
[1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0],
[1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0],
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],
[1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 1.0],
[1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 0.0],]
G = nx.from_numpy_array(np.array(adj_matrix))
t1 = nx.algorithms.tree.mst.random_spanning_tree(G)
t1_A = nx.linalg.graphmatrix.adjacency_matrix(t1).A # get adjacency matrix of t1
t2 = nx.Graph(t1_A) # create a tree with the same adjacency matrix as t1 (t2 should equal t1 since they have same adjacency matrix)

# The partitions, from the example in the OP
part1 = [0, 1, 2, 3]
part2 = [13, 4, 5, 6, 7]
part3 = [8, 9, 10, 11, 12, 14]
partitions = (part1, part2, part3)
# A naive, brute-force check for tripartite (there's almost certainly a better way to do this)
def is_tripartite(G):
     return not any(
         [any([u in p and v in p for (u, v) in G.edges(nbunch=p)]) for p in partitions]
     )

print(is_tripartite(t1),is_tripartite(t2)) # outputs True,False
print(nx.utils.misc.graphs_equal(t1, t2)) # outputs False 
```

**Comment by rossbar** [comment]
> Why is that? shouldnt 2 trees with the same adjacency matrix equal one another?

It depends on what you mean by "the same" :). The connections between nodes are the same, but the nodes are being implicitly relabeled with all of the conversion back-and-forth between adjacency and graph representations. A close look at the `adjacency_matrix` docstring reveals the `nodelist` parameter, which is used to determine the *order* of the nodes. When not specified, it uses the order of `G.nodes`, which for `t1` will be random and is very unlikely to be `list(range(15))`.

However, the conversion *from* adjacency matrix makes no such distinction, and automatically maps the indices of the adjacency matrix to the node label (i.e. `t2.nodes` *is* `list(range(15))`. In other words, the exact node labels depends on ordering, and when not specified the default node ordering is not sorted when converting to adjacency representations. This means that `t1` and `t2` should always be *isomorphic* (you can verify this with `nx.is_isomporphic(t1, t2)`), but are *not* guaranteed to have the same node labels. You can of course use the `nodelist` parameter of adjacency_matrix to specify the node order, e.g. `nx.adjacency_matrix(t1, nodelist=sorted(t1.nodes))`.

**Comment by mraa022** [comment]
> 

oooooh, i get it now. thank you sooo much for all the help
