### ISSUE TITLE
Undocumented parameters in `dispersion`

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#6111]
The signature for `nx.dispersion` is:

```python
def dispersion(G, u=None, v=None, normalized=True, alpha=1.0, b=0.0, c=0.0)
```

but the three parameters `alpha`, `b` and `c` are not described in the docstring.

**Comment by Qudirah** [comment]
will do that now!

**Comment by Qudirah** [comment]
@rossbar @MridulS from what I gather, alpha,b, and c are optimal values for obtaining maximum performance. Would that suffice?

**Comment by Qudirah** [comment]
hello @rossbar @MridulS @jarrodmillman I need your help with this

**Comment by rossbar** [comment]
> from what I gather, alpha,b, and c are optimal values for obtaining maximum performance. Would that suffice?

According to the implementation, these three parameters are used in the normalization procedure where the dispersion is normalized by embeddedness. Probably the best way to get a clear description of the normalization procedure is to investigate the paper referenced in the docstring.

**Comment by Qudirah** [comment]
> > from what I gather, alpha,b, and c are optimal values for obtaining maximum performance. Would that suffice?
> 
> According to the implementation, these three parameters are used in the normalization procedure where the dispersion is normalized by embeddedness. Probably the best way to get a clear description of the normalization procedure is to investigate the paper referenced in the docstring.

Alright. I'll look into that.

**Comment by tinaoberoi** [comment]
@rossbar @Qudirah I believe this issue is resolved now, can we go ahead and close this?
