### ISSUE TITLE
Increase test coverage in core.py

### ISSUE THREAD

**Issue by Mjh9122** [networkx/networkx#6115]
Some untested conditionals in https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/algorithms/core.py and I'd like to add them. 

The tests will be added in https://github.com/networkx/networkx/blob/main/networkx/algorithms/tests/test_core.py

Current Behavior: 
Not testing exceptions that are raised

Expected Behavior, test all conditions

Steps to reproduce, Look at coverage link above.

**Comment by rossbar** [comment]
Thanks @Mjh9122 , it turns out that `find_cores` is actually supposed to be removed in the next release! Your discovery via coverage is very helpful, thanks for opening the issue!
