### ISSUE TITLE
Improve test coverage for multidigraph class 

### ISSUE THREAD

**Issue by Qudirah** [networkx/networkx#6118]
I discovered there are still some red spots in this link https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/classes/multidigraph.py
I will like to work on it.

The tests will be added in https://github.com/networkx/networkx/blob/main/networkx/classes/tests/test_multidigraph.py

Current Behavior
We don't test all the paths the code can take us.

Expected Behavior
We should be testing everything so there aren't any surprises.

Steps to Reproduce
Visit https://app.codecov.io/gh/networkx/networkx/blob/main//networkx/classes/multidigraph.py

**Comment by MridulS** [comment]
fixed in https://github.com/networkx/networkx/pull/6131
