### ISSUE TITLE
Improve test coverage for matching.py

### ISSUE THREAD

**Issue by paulitapb** [networkx/networkx#6136]
Currently,  the test coverage is only 95% and I would like to improve it.

**Comment by tinaoberoi** [comment]
Hi @paulitapb 
Are you working on this? If not would love to contribute.

**Comment by paulitapb** [comment]
I think someone else already solved this but didn't link their PR to this issue. I'll go ahead and close this. But feel free to open up some new issues if you want to contribute. There's plenty of code that doesn't have 100% coverage.  You can check that[ here](https://app.codecov.io/gh/networkx/networkx/tree/main/networkx)
