### ISSUE TITLE
Unable to access any functions related to traveling salesman problem upon importation of approximation

### ISSUE THREAD

**Issue by ajgrove456** [networkx/networkx#6137]
### Current Behavior

I am able to import approximation but am not able to use functions such as greedy_tsp() or christofides(). 
![image](https://user-images.githubusercontent.com/116789197/198209758-b43a9790-1af0-4b1b-85d4-62ef37f0aa00.png)

### Expected Behavior

Importation of approximation package and access to greedy_tsp and christofides
![image](https://user-images.githubusercontent.com/116789197/198209917-71ad58a8-0c62-454e-9535-a62e91f12a08.png)

### Steps to Reproduce

![image](https://user-images.githubusercontent.com/116789197/198210272-dd184f8f-88c8-496c-95e1-825fed3844eb.png)

### Environment

Python version: 3.8
NetworkX version: 2.8.7

### Additional context

List of available functions when package itself is imported:
![image](https://user-images.githubusercontent.com/116789197/198210524-8761f979-bad5-4035-8226-8fa6e52cccab.png)
I apologize if the functions were moved to a different package and I am simply missing them, but the examples within the documentation still reference networkx.approximation.

**Comment by paulitapb** [comment]
The function is still in aproximation. I reproduced this with networkX 2.8.7 and Python 3.8 but didn't get that error. Are you using a virtualenv? If helps I also tested networkX 2.6.3 and It works.

**Comment by rossbar** [comment]
I suspect this is an environment management issue. The access pattern in the OP is indeed valid and should work fine with networkx 2.8.7. You can check `nx.__version__` in the notebook to ensure you are actually getting the version of networkx that you expect.

I will close this issue as I don't think there's anything to be done on the networkx side, but if the issue persists feel free to reopen with the latest info.

**Comment by ajgrove456** [comment]
Hi, sorry for the late reply.

After using nx.__version__, it shows as 2.5. Trying to update is causing issues but that's a separate issue. I will update and try the function again. Thanks for your help.
