### ISSUE TITLE
Improve test coverage for voterank algorithm

### ISSUE THREAD

**Issue by Qudirah** [networkx/networkx#6154]
I discovered there are still some red spots in this link 
https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/algorithms/centrality/voterank_alg.py

I will like to work on it.

The tests will be added in
https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/algorithms/centrality/tests/test_voterank.py

Current Behavior
We don't test all the paths the code can take us.

Expected Behavior
We should be testing everything so there aren't any surprises.

Steps to Reproduce
Visit https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/algorithms/centrality/voterank_alg.py

**Comment by rossbar** [comment]
Closed by #6161
