### ISSUE TITLE
Label Propagation Algorithm for community detection (migrated from Trac #627)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#617]
Original ticket https://networkx.lanl.gov/trac/ticket/627
Reported 2011-08-28 by @hagberg, assigned to @hagberg.

From networkx-devel:http://groups.google.com/group/networkx-devel/browse_thread/thread/2751c28efef84461

Tyler Rush via googlegroups.com to networkx-devel
show details Aug 27 (1 day ago) 
Hi,

I wrote an LPA community detection algorithm (based off of 'Community Detection via Semi-Synchronous Label Propagation Algorithms' Cordasco and Gargano, 2011), made use of networkx, and thought I'd donate the resulting code to the networkx project. The code is attached, so do what you will with it.

Sorry that I don't have any time right now to enhance the code: incorporate it into networkx source or use other LPA methods as specified in the aforementioned paper and also the original paper, 'Near linear time algorithm to detect communities in large-scale networks' by Raghavan et al.

**Comment by dschult** [comment]
Fixed in #2821
