### ISSUE TITLE
Improve test coverage for percolation centrality algorithm

### ISSUE THREAD

**Issue by Qudirah** [networkx/networkx#6170]
I discovered there are still some red spots in this link
https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/algorithms/centrality/percolation.py

I will like to work on it.

The tests will be added in
https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/algorithms/centrality/tests/test_percolation_centrality.py

Current Behavior
We don't test all the paths the code can take us.

Expected Behavior
We should be testing everything so there aren't any surprises.

Steps to Reproduce
https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/algorithms/centrality/percolation.py

**Comment by Qudirah** [comment]
@MridulS @rossbar @jarrodmillman I need help with this one. I don't understand how to approach it.

**Comment by rossbar** [comment]
From the coverage report, the untested code is when `weight` is specified (i.e. `weight` is something other than the default `None`).

So the way to test this would be to generate a simple graph with weighted edges, determine what the expected percolation centrality value is for each node both *with* and *without* edge weights, then code up a test that checks the results of the function against the expected values for `weights=None` and `weights="weight"`.
