### ISSUE TITLE
Deprecate `nx.number_of_cliques`?

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#6180]
Just a thought I had while [reviewing 6171](https://github.com/networkx/networkx/pull/6171#pullrequestreview-1169036037).

The `number_of_cliques` helper function creates (by default) a dictionary keyed by node where the values are the number of cliques containing the node. The default behavior essentially boils down to a one-liner:

```python
{n: sum(1 for c in nx.find_cliques(G) if n in c) for n in G}
```

The majority of the implementation of `nx.number_of_cliques` is dedicated to munging the various input arguments. IMO it'd be an improvement to instead recommend that users do this computation the Pythonic way rather than provide networkx-specific API for this task. IMO the potential upside for future users is worth the noise of a deprecation, but this is definitely subjective! Thoughts?

**Comment by dschult** [comment]
Another function like that is `graph_number_of_cliques`.  It is literally `len(cliques)` if the input `cliques` is already computed and it is `sum(1 for c in nx.find_cliques(G))` if the cliques input is `None`. Removing these functions (I am sure there are others in this module) and replacing them with examples in the `find_cliques` doc_string seems like a good idea.

**Comment by rossbar** [comment]
Looking over all the functions in the `clique.py` module, the ones that could be replaced by one-liners on the output of `find_cliques` are:
 - `graph_clique_number`: returns the size of the largest clique in the graph
 - `graph_number_of_cliques`: returns the number of maximal cliques in the graph
 - `number_of_cliques`: The number of maximal cliques for each node
 - `cliques_containing_node`: List of maximal cliques for each node
