### ISSUE TITLE
not able to interpret read_graphml  function . (query regarding read_graphml function)

### ISSUE THREAD

**Issue by anushka192001** [networkx/networkx#6181]
when i fed this graphml file below ino networkx using the tutorial
![image](https://user-images.githubusercontent.com/63954873/200117856-806b1b32-33fe-4742-a6c8-301da3e7edd2.png)

https://networkx.org/documentation/stable/reference/readwrite/generated/networkx.readwrite.graphml.read_graphml.html#networkx.readwrite.graphml.read_graphml

then these many edges and nodes are coming out .

![image](https://user-images.githubusercontent.com/63954873/200117870-65a4f237-3aa9-44b3-b8da-3e795b6e76ad.png)

![image](https://user-images.githubusercontent.com/63954873/200117879-1b7617b6-2408-477e-8fa7-05aecc5f0903.png)

but i am not able to interpret the edges types (what are these no.s 0,1,2) after the 2 edges id,s ?

being a developer of this library i assume if you can help out then it would be a great help for my research project.

link to the graphml file i fed https://drive.google.com/file/d/1ScclXzLMNFs5G3aDiA3R4l6inxWA9O3O/view?usp=share_link

**Comment by dschult** [comment]
The graphml reading function creates a MultiGraph or MultiDiGraph. So, each edge has an "edge key". 
Printing `G.edges` shows each edge as a 3-tuple with the two nodes for that edge, and an edge key to identify which edge it is. You can remove the edge keys if you don't want multiple edges between nodes by using:
```python
newG = nx.Graph(G)               # or nx.DiGraph(G) for directed case
````

**Comment by rossbar** [comment]
@dschult 's explanation sufficiently addresses the initial question, so I will close this as resolved.
