### ISSUE TITLE
README mentions unexisting force.py file

### ISSUE THREAD

**Issue by diogobaltazar** [networkx/networkx#6217]
The [README](https://github.com/networkx/networkx/blob/main/examples/external/force/README.txt) mentions the unexisting ``force.py`` file to generate the necessary data for the example.

**Comment by MridulS** [comment]
Yeah the file was renamed to `javascript_force.py` -> https://github.com/networkx/networkx/blob/main/examples/external/javascript_force.py in https://github.com/networkx/networkx/pull/4422. Feel free to send a PR to fix the typo :)

**Comment by tinaoberoi** [comment]
Hi everyone, is anyone working on this? If not would go ahead and create a PR for the fix.

**Comment by diogobaltazar** [comment]
Sorry I haven't found the time. Just tried running the js file with node but ``d3`` is missing as a dependency to run ``force.js``, and once you add and import, there's a complaint with ``node_modules``:

```sh
<REPO>/networkx/examples/external/force/node_modules/d3/src/index.js:1
export * from "d3-array";
^^^^^^

SyntaxError: Unexpected token export
...
```

[tinaoberoi](https://github.com/tinaoberoi) are you working on it? [MridulS](https://github.com/MridulS) I'll return to it when I have the time if it isn't closed meanwhile.

**Comment by tinaoberoi** [comment]
@diogobaltazar I will start working on it, sorry for the dealy.

**Comment by MridulS** [comment]
@diogobaltazar to get this working you need to run the flask app in `javascript_force.py` not the `js` file itself. d3 is loaded in `force.html` and it is served via the flask app. Just do `python javascript_force.py` in the `external/` folder and it should start a server on 127.0.0.1:8000 with the d3 example.

**Comment by MridulS** [comment]
fixed in https://github.com/networkx/networkx/pull/6312
