### ISSUE TITLE
Potential bug in connected_double_edge_swap

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#6220]
The following test case failed during a `pytest-randomly` workflow:

https://github.com/networkx/networkx/blob/895963729231fe02153afe92ecc946a400247f1d/networkx/algorithms/tests/test_swap.py#L37-L39

I was able to reproduce locally on `main` by running interactively. When running without a `seed`, I occasionally get `1` instead of `0`. This is also reproducible when seeded:

```python
>>> G = nx.path_graph(4)
>>> nx.connected_double_edge_swap(G, seed=140)
1
```

I tested with both 2.8.3 and 2.7 and was able to reproduce with those versions as well, so I don't think this is something recently introduced (though I haven't looked at blame or bisected).

**Comment by dschult** [comment]
Looks like this new test is not a valid test. (Added in #6176)

The path graph with 4 nodes does have a valid edge swap:  (0,1) and (2,3) can be swapped.
So, this should not test that the swapcount is 0. Of course, sometimes it will be zero.

**Comment by rossbar** [comment]
> Looks like this new test is not a valid test. (Added in https://github.com/networkx/networkx/pull/6176)

Thanks @dschult - of course it makes sense to check when the test itself was added - another silly oversight. Fortunately an easy fix!
