### ISSUE TITLE
AttributeError: module 'networkx' has no attribute 'weisfeiler_lehman_subgraph_hashes'

### ISSUE THREAD

**Issue by mmpust** [networkx/networkx#6242]
### Current Behavior
AttributeError: module 'networkx' has no attribute 'weisfeiler_lehman_subgraph_hashes'

### Steps to Reproduce
'''
import networkx as nx
nx.weisfeiler_lehman_subgraph_hashes(graph1nx, iterations=3, digest_size=8)
'''
### Environment
Ubuntu 20.04 (x86/64)
Python version: 3.9.12
NetworkX version: 2.5

**Comment by dschult** [comment]
You are using NetworkX 2.5 and that function was introduced in v2.7.  v2.5 was not built for python 3.9, so you should probably upgrade to a newer version.  Perhaps v2.8.8?
