### ISSUE TITLE
Allow caller to opt out of adding `weight` attributes in `from_numpy_array`

### ISSUE THREAD

**Issue by j6k4m8** [networkx/networkx#6248]
### Current Behavior

Right now, calls to `from_numpy_array` add a `weight` attribute to all edges in the newly created (non-multi)graph. 

### Expected Behavior

It would be nice to allow the user to opt out of this behavior, or to specify an attribute that should receive this weight.

### Steps to Reproduce

```python
import networkx as nx
import numpy as np

mat = np.array([
    [0, 1],
    [1, 0]
])
g = nx.from_numpy_array(mat, create_using=nx.DiGraph)
print(g.edges(data=True))
```

```
[(0, 1, {'weight': 1}), (1, 0, {'weight': 1})]
```

### Environment

* Python version: 3.10
* NetworkX version: All (2.6.3)

### Additional context

This is confusing behavior because the caller does not explicitly request attribute creation. I would propose the following PREFERRED behavior:

#### Preferred

Creating a graph with an array of `dtype` ∈ {int, float} creates an attribute of name `weight_attribute`, which defaults to `w` for backwards compat.

```python
g = nx.from_numpy_array(mat, create_using=nx.DiGraph, weight_attribute="w")
print(g.edges(data=True))
```

```
[(0, 1, {'w': 1}), (1, 0, {'w': 1})]
```

```

Creating a graph with an array of `dtype` = bool treats each value as an existence flag and does not create an attribute:


```python
g = nx.from_numpy_array(mat==1, create_using=nx.DiGraph, weight_attribute="w")
print(g.edges(data=True))
```

```
[(0, 1, {}), (1, 0, {})]
```

#### Also seems fine but changes fn signature:

Perhaps better for backwards compat is to allow the user to opt-out of the current behavior with a new argument `weight_attribute` which defaults to `weight` but can be set to `None` to remove this behavior. (Perhaps a bit more predictable than the above option?)

#### Seems kinda jank but is totally back-compat:

Setting `parallel_edges=True` and `create_using=nx.DiGraph` currently doesn't do anything, and could be repurposed to perform this behavior. Eh. This is kinda gross.

**Comment by rossbar** [comment]
This seems like a reasonable request to me. I can certainly see a use-case for simply using the adjacency matrix to specify edges *without* creating edge attributes (e.g. to save memory). It doesn't look like there's an obvious way to do this, so I think this would be a nice enhancement.

Of all the proposals above I think the one I like best is to add a new keyword argument (though with a more generic name... maybe `edge_attribute`?) to indicate the edge attribute name. By default this would be `edge_attribute="weight"` for backwards compatibility, but users could also pass in `None` which would then treat the adjacency matrix as binary only indicating edge existence and not store attributes.

There are some potentially messy corners (e.g. the interpretation of `0` as non-edge and making sure everything works well with structured dtypes) but overall I think this would be an improvement!

**Comment by dschult** [comment]
I agree with @rossbar that this sounds like a good feature. I'd argue for the keyword to be `weight="weight"` as the default way to refer to edge attributes is `weight` in many other places (like `to_numpy_array`). But I don't feel strongly about it.

And I agree that there might be some messy corner cases.  Distinguishing between 0 and non-edge might be a different PR. But could be done with a keyword argument like `nonedge_sentinal=0` so people could use `nonedge_sentinal=float("nan")` for example.

**Comment by dschult** [comment]
Interesting that all the `to_<datastructure>` functions use `weight="weight"` keywords, while the `from_<data_structure>` functions either don't have it, use `edge_attribute` or use `edge_attr`.  We should probably make this more uniform. The `edge_attr` case is interesting because it uses value `None` for no attributes, just like we are thinking, and `True` to mean load all the available information for each edge.  We could use that option for compound dtypes perhaps. I'm not sure what's involved there.

And just to be clear, the default value for non-edges should be 0. That is standard. We just want to provide a way for people to change that if desired.

**Comment by j6k4m8** [comment]
Got it — would you prefer one PR that refactors the `from_X` fns and adds this functionality, or two (1. refactor; 2. close this issue)?

**Comment by rossbar** [comment]
Let's keep the scope narrow so things are easier to review. I'd be +1 for a PR to address this feature in `from_numpy_array` specifically!
