### ISSUE TITLE
Calculating Line Graph from Incidence Matrix doesn't equal Line Graph from Networkx

### ISSUE THREAD

**Issue by yCobanoglu** [networkx/networkx#6253]
### Description

Derivation from Line Graph from Unsigned Incidence Matrix for undirected Graphs seems to be incorrect
Formula: $L(G) = U^{T} U - 2  I$
[Wikiedia: Incidence Matrix (Formula to get Line Graph from Unsigned Incidence Matrix)](https://en.wikipedia.org/wiki/Incidence_matrix)
[Wikipedia: Line Graph (Section with Formula)](https://en.wikipedia.org/wiki/Line_graph#Other_related_graph_families)

### Current Behavior

$L(G)  =$ Line Graph Adjacency Matrix
$U =$ Unsigned incidence matrix of undirected graph 
$L(G)  \neq U^{T}  U - 2 I$

### Expected Behavior

$L(G)  =$ Line Graph Adjacency Matrix
$U =$ Unsigned incidence matrix of undirected graph 
$L(G) = U^{T} U - 2  I$

### Steps to Reproduce

```python
import networkx as nx
import numpy as np

graph = nx.stochastic_block_model([200, 200], [[0.2 , 0.2], [0.2, 0.2]])
line_graph = nx.to_numpy_array(nx.line_graph(graph))

incidence_matrix = nx.incidence_matrix(graph).toarray()
line_graph_ = incidence_matrix.T @ incidence_matrix - 2 * np.eye(incidence_matrix.shape[1])
assert np.allclose(line_graph, line_graph_)
```
Running Code results in **➔ AssertionError**

### Environment
Python version: 3.10.8
NetworkX version: 2.8.8

**Comment by rossbar** [comment]
I suspect that the difference comes down to edge ordering. Have you checked that the ordering of the edges in the column of the incident matrix is consistent with the ordering of the nodes (which, in L(G), represent the edges of the original G) in the adjacency matrix of L(G)?

**Comment by yCobanoglu** [comment]
Ok you are right. The rows of the incident matrix have to have the same ordering as the rows/columns (because the line graph is symmetric) of the line graph. But the `nx.incidence_matrix(graph)` returns an **csc_array** from which it's not possible to recover the columns associated with the edges. For `nx.line_graph(graph)` one gets a Graph Object which has the property `nodes` which associates each node in the line_graph with an edge in the normal graph.

There is no way to align them because `incidence_matrix(graph)` returns an array and the node information is lost.

**Comment by yCobanoglu** [comment]
One has to pass the line graph nodes as edgeslist to incidence matrix. This fixes the issue so the Assertion Holds and $L(G) = U^{T} U - 2  I$ as expected. Thanks !

```python
import networkx as nx
import numpy as np

GRAPH = nx.stochastic_block_model([200, 200], [[0.2 , 0.2], [0.2, 0.2]])

line_graph = nx.line_graph(GRAPH)
L_G = nx.to_numpy_array(line_graph)

incidence_matrix = nx.incidence_matrix(GRAPH, edgelist=line_graph.nodes)

U = incidence_matrix.toarray()
line_graph_ = U.T @ U - 2 * np.eye(U.shape[1])
assert np.allclose(L_G, line_graph_)
```
