### ISSUE TITLE
OutMultiEdgeView.__call__ order of arguments

### ISSUE THREAD

**Issue by patrick-nicodemus** [networkx/networkx#6264]
### Discussed in https://github.com/networkx/networkx/discussions/6263

<div type='discussions-op-text'>

<sup>Originally posted by **patrick-nicodemus** December  7, 2022</sup>
The __call__ method of `classes.reportviews.OutMultiEdgeView` is defined as:
```
def __call__(self, nbunch=None, data=False, keys=False default=None, ):
```
but the __call__ method of its parent class `classes.reportviews.OutEdgeView` is
```
def __call__(self, nbunch=None, data=False, default=None):
```
I would suggest that `keys` be moved to the last position. Otherwise if a user expects an OutEdgeView and gets an OutMultiEdgeView they will get a wrong answer.</div>

**Comment by SultanOrazbayev** [comment]
Thank you for flagging this @patrick-nicodemus !
