### ISSUE TITLE
Error in documentation of katz_centrality? 

### ISSUE THREAD

**Issue by erikkemperman** [networkx/networkx#6279]
### Current Behavior

The docs for katz centrality state:
https://github.com/networkx/networkx/blob/f20ba5f2f6462af8f1ac9b1772ffa5b4bcca4d58/networkx/algorithms/centrality/katz.py#L131-L132

The value for `beta` here was changed from 1 to 0 a long time ago, in this commit:
https://github.com/networkx/networkx/commit/b33ebd46a32558b1f33bd3caa6030e21502e17bf#diff-fd4d6088095ce7547e9e07adf7326d408cb55f6ef43d47aeba7f53d405b44b8dL259

Which I think may have been an incorrect response to issue https://github.com/networkx/networkx/issues/1247.

### Expected Behavior

I believe that the previous note with `beta=1` was actually correct. For what it's worth, here are the relevant parts of the implementation in current master:

https://github.com/networkx/networkx/blob/6971d845e25aa4b76879831bb85ac2fa23ae0c9e/networkx/algorithms/centrality/katz.py#L153-L166

If we assume that `nstart` is left to the default of `None`, we see that `x` starts out being all zeroes. But then, unless `beta` is non-zero for at least some of the nodes, it is impossible for any element of `x` to ever become non-zero:

https://github.com/networkx/networkx/blob/6971d845e25aa4b76879831bb85ac2fa23ae0c9e/networkx/algorithms/centrality/katz.py#L168-L177

In other words, it looks to me like if `nstart=None` and `beta=0` then Katz centrality will always produce an array of zeroes. And in particular, even if `alpha` is (ever so slightly less than) `1/lambda_max` it will *not* resemble the eigenvector centrality.

### Steps to Reproduce

(EDITED) Figured I should add an example, adapted from the example in the docs:

```python3
import math
G = nx.path_graph(4)
phi = (1 + math.sqrt(5)) / 2.0  # largest eigenvalue of adj matrix

print(f"For reference: eigenvector centrality")
eig_centrality = nx.eigenvector_centrality(G)
for n, c in sorted(eig_centrality.items()):
    print(f"{n} {c:.2f}")
# 0 0.37
# 1 0.60
# 2 0.60
# 3 0.37

print(f"Katz with beta=1.0")
katz_centrality_0 = nx.katz_centrality(G, alpha=(1 / phi - 0.01), beta=1.0)
for n, c in sorted(katz_centrality_0.items()):
    print(f"{n} {c:.2f}")
# 0 0.37
# 1 0.60
# 2 0.60
# 3 0.37

print(f"Katz with beta=0.0")
katz_centrality_1 = nx.katz_centrality(G, (1 / phi - 0.01), beta=0.0)
for n, c in sorted(katz_centrality_1.items()):
    print(f"{n} {c:.2f}")
# 0 0.00
# 1 0.00
# 2 0.00
# 3 0.00
```

### Environment

Python version: 3.11
NetworkX version: 3.0rc

**Comment by BrunoBaldissera** [comment]
I guess you are right! It's nice that you even found the probable origin of this.

Since the  `beta` parameter accounts for the weights in the neighborhood, an assignment of '0' should be expected to output zeroes as you reported.

**Comment by dschult** [comment]
Thanks for this! And for the detailed numerical analysis.
The theory requires  alpha <= 1/lambda_max to avoid singular results. But in the limit alpha -> 1/lambda_max we can look at alpha*A as a multiplication operator that shrinks all vectors except the eigenvector corresponding to lambda_max. And it keeps that vector the same length. Thus repeatedly multiplying by alpha*A should turn any vector into its component in the direction of that eigenvector. Scaling the result to a unit vector reveals the same eigenvector for any starting guess that isn't orthogonal to the eigenvector. For Katz centrality we start with the vector beta. So certainly the current documentation is wrong. If beta=0, it is orthogonal to all eigenvectors. And we won't end up with the stated result of the eigenvector as the Katz centrality. It is also true that beta=1 does give the desired result.  But Beta=2 also works... as does beta=0.2 or any beta>0. (So long as beta as a vector isn't orthogonal to the eigenvector).

So I see two possible fixes -- the suggest correction to the doc_string of \beta=1, or the correction \beta >= 0.  We could also be more precise and say that this result holds in *the limit as* alpha -> 1/lambda_max.  But I'm not sure that is causing any confusion. It is the incorrect value of beta=0 that is causing confusion.

Also, the sentence doesn't say this is the only case where Katz Centrality matches Eigenvector Centrality, so I'm fine with the suggested language here (and in the @BrunoBaldissera PR).  Thanks for the excuse to take a romp down the lane of linear algebra and infinite series. :)  Let's fix the doc_string!
