### ISSUE TITLE
Pearson r calculation for all possible pairs (in in, out out, out in, in out) (migrated from Trac #640)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#628]
Original ticket https://networkx.lanl.gov/trac/ticket/640
Reported 2011-09-27 by Oleguer Sagarra <oleguer.sagarra, assigned to @hagberg.

As done in the reference given at the end of the note, I propose to add to the module: networkx.mixing the following features:

-For directed networks add the option to compute the 'r' coefficient (function networkx.algorithms.mixing.degree_pearsonr) of pairs (In-In, Out-In, Out-Out, In-Out)
- For weighted networks add the option to compute the r weighted degree coefficient
- For directed weighted networks add both.

I add a proposal to apply the changes...

Reference:
Foster, J.G., Foster, D.V., Grassberger, P. & Paczuski, M. Edge direction and the structure of networks. Proceedings of the National Academy of Sciences of the United States of America 107, 10815-20 (2010).

**Comment by hagberg** [comment]
No champion for this.  Closing for now.
