### ISSUE TITLE
Networkx

### ISSUE THREAD

**Issue by Perceivery** [networkx/networkx#6288]
Error : numpy.random.mtrand has no attribute [_rand]

**Comment by MridulS** [comment]
Hi @Perceivery, could you give some more information how you got this error? Please provide minimal example code that can generate this error.

**Comment by Perceivery** [comment]
Hi! Sure. I compile Python code using Pythonista App. I am learning to code and so I came up with an idea to learn graphs. I have copypasted code from the website : 

import networkx as nx
import matplotlib.pyplot as plt

G = nx.DiGraph()
G.add_edges_from(
    [('A', 'B'), ('A', 'C'), ('D', 'B'), ('E', 'C'), ('E', 'F'),
     ('B', 'H'), ('B', 'G'), ('B', 'F'), ('C', 'G')])

nx.draw(G)

plt.show()

And the compiler show me the message mentioned before. 
Please help 🥹

**Comment by dschult** [comment]
Check the version of numpy that you are using.  We support v1.20 or greater.
```python
import numpy as np
print(np.__version__)
```
Install a recent version and update the other libraries to recent versions too. The `_rand` value was most recently changed for numpy in May 2019, so you are apparently using a very old version of numpy -- and thus probably other libraries too.

**Comment by Perceivery** [comment]
import numpy as np
print(np.__version__)

Out : 1.8.0

How to install new version using Stash?

> Check the version of numpy that you are using.  We support v1.20 or greater.
> 
> ```python
> 
> import numpy as np
> 
> print(np.__version__)
> 
> ```
> 
> Install a recent version and update the other libraries to recent versions too. The `_rand` value was most recently changed for numpy in May 2019, so you are apparently using a very old version of numpy -- and thus probably other libraries too.

**Comment by rossbar** [comment]
NumPy 1.8 is incredibly out-of-date, so it's no surprise that you're seeing issues like this. This is very likely to be an issue with your environment and not related to NetworkX; therefore I will close this issue. I suggest checking out general documentation on installing Python libraries, which will be more relevant to the problems you're seeing!
