### ISSUE TITLE
https://networkx.org/documentation/latest/release/release_2.8.8.html title is "NetworkX 2.8.7"

### ISSUE THREAD

**Issue by sandrotosi** [networkx/networkx#6297]
Going to https://networkx.org/documentation/stable/release/release_2.8.8.html, the title od the page is "NetworkX 2.8.7", which is quite confusing, since there's already https://networkx.org/documentation/latest/release/release_2.8.7.html for that release

**Comment by MridulS** [comment]
Thanks for raising this @sandrotosi, it should be fixed soon.
