### ISSUE TITLE
Mypy CI failures in `main` branch

### ISSUE THREAD

**Issue by danieleades** [networkx/networkx#6318]
the mypy CI job is failing in `main`.

**Comment by MridulS** [comment]
The `mypy` job works fine on all PRs (https://github.com/networkx/networkx/actions/workflows/mypy.yml) except https://github.com/networkx/networkx/pull/6315 which touches `test_reportviews` and the mypy test fails for `reportviews.py`

**Comment by danieleades** [comment]
> The `mypy` job works fine on all PRs (https://github.com/networkx/networkx/actions/workflows/mypy.yml) except #6315 which touches `test_reportviews` and the mypy test fails for `reportviews.py`

i can reproduce the failure on `main` locally with

```
mypy -p networkx
```

**Comment by MridulS** [comment]
Which mypy version are you on? It works fine for me locally.

```
(networkx-dev) ➜  networkx git:(main) mypy --version
mypy 0.991 (compiled: yes)
(networkx-dev) ➜  networkx git:(main) mypy -p networkx
networkx/algorithms/planar_drawing.py:226: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
Success: no issues found in 556 source files
```

**Comment by danieleades** [comment]
```
$ mypy --version
mypy 0.991 (compiled: yes)
$ mypy -p networkx
networkx/classes/reportviews.py:1328: error: Incompatible types in assignment (expression has type "Type[OutMultiEdgeDataView]", base class "OutEdgeView" defined the type as "Type[OutEdgeDataView]")  [assignment]
networkx/classes/reportviews.py:1380: error: Incompatible types in assignment (expression has type "Type[MultiEdgeDataView]", base class "OutEdgeView" defined the type as "Type[OutEdgeDataView]")  [assignment]
networkx/classes/reportviews.py:1406: error: Incompatible types in assignment (expression has type "Type[InMultiEdgeDataView]", base class "OutEdgeView" defined the type as "Type[OutEdgeDataView]")  [assignment]
networkx/algorithms/planar_drawing.py:226: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
Found 3 errors in 1 file (checked 556 source files)
```

**Comment by MridulS** [comment]
Indeed. What does git diff/git log tells you? Is this the `main` branch without any changes?

**Comment by danieleades** [comment]
> Indeed. What does git diff/git log tells you? Is this the `main` branch without any changes?

sure is. even tried a fresh clone to check i wasn't losing my mind

**Comment by danieleades** [comment]
> The `mypy` job works fine on all PRs (https://github.com/networkx/networkx/actions/workflows/mypy.yml) except #6315 which touches `test_reportviews` and the mypy test fails for `reportviews.py`

worth noting that mypy lints all files in the package, not just ones that have been touched. It's possible to have mypy set up to only check changed files if set up as a pre-commit hook, but it's discouraged as an anti-pattern, since it prevents mypy from picking up 'non-local' errors. Ie, errors introduced in a different file due to changes in the current file.

The way mypy is currently set up in CI for this repo it will simply run on all packages.

**Comment by rossbar** [comment]
A little extra info: I can't reproduce this in my development environment, but I *can* with a non-editable install. In other words, with `pip install -e .` in the source directory I don't see the errors, but with `pip install .` I do.

**Comment by danieleades** [comment]
> A little extra info: I can't reproduce this in my development environment, but I _can_ with a non-editable install. In other words, with `pip install -e .` in the source directory I don't see the errors, but with `pip install .` I do.

i can reproduce with the following steps-

```sh
rm -rf .venv
virtualenv .venv
. ./.venv/bin/activate
pip install -e ".[developer]"
mypy -p networkx
```

```
networkx/classes/reportviews.py:1328: error: Incompatible types in assignment (expression has type "Type[OutMultiEdgeDataView]", base class "OutEdgeView" defined the type as "Type[OutEdgeDataView]")  [assignment]
networkx/classes/reportviews.py:1380: error: Incompatible types in assignment (expression has type "Type[MultiEdgeDataView]", base class "OutEdgeView" defined the type as "Type[OutEdgeDataView]")  [assignment]
networkx/classes/reportviews.py:1406: error: Incompatible types in assignment (expression has type "Type[InMultiEdgeDataView]", base class "OutEdgeView" defined the type as "Type[OutEdgeDataView]")  [assignment]
networkx/algorithms/planar_drawing.py:226: note: By default the bodies of untyped functions are not checked, consider using --check-untyped-defs  [annotation-unchecked]
Found 3 errors in 1 file (checked 556 source files)
```

**Comment by danieleades** [comment]
possibly related - https://github.com/python/mypy/issues/13392

**Comment by danieleades** [comment]
ah. I think i know what's going on.

My PRs are adding a `pyproject.toml` file. Mypy is picking that up in preference to `.mypy.ini`

will test that theory

**Comment by danieleades** [comment]
scratch that too. moving the config to the `pyproject.toml` file has the same behaviour.

mypy is returning type errors even though the files are explicitly excluded

**Comment by danieleades** [comment]
Ruff supports an alternative configuration file, so I can update to remove the `pyproject.toml` file for the time being. Would that help?

**Comment by danieleades** [comment]
the issue does indeed seem to be related to having both setup.py *and* pyproject.toml in the case of this repo's CI. I wasn't aware this could cause issues, learned something today. But the issue is a subtle one, and doesn't explain why i'm able to reproduce the same errors locally on `main` using an editable install (with no `pyproject.toml` file).
I can get my PRs to build by moving ruff's configuration from `pyproject.toml` to `ruff.toml`.
I think this can be closed for now, as the immediate problem is resolved (/explained), though there's definitely still something fishy going on...
