### ISSUE TITLE
Tracking issue - linting/code quality using Ruff

### ISSUE THREAD

**Issue by danieleades** [networkx/networkx#6325]
This is a tracking issue for the introduction of code quality linting to this repo. Linting can provide the following benefits

- correctness - identify bugs, dead code, inconsistencies, performance issues, antipatterns in code
- consistency - promote a consistent code style to improve readability

I propose an incremental approach where lints are added one at a time, and only where they add clear value.

I propose using [ruff](https://github.com/charliermarsh/ruff). The alternative would be to use flake8. Compared to flake8, ruff
- is faster (by a couple of orders of magnitude)
- can automatically fix code in many cases
- has no dependencies

Ruff is particularly suited for use as a pre-commit hook, due to its speed.

see-

- [x] #6321 
- [x]  #6319 https://pypi.org/project/flake8-simplify/0.19.3/
- [ ]  #6320 
- [x] #6315 
- [x] #6317 
- [x] #6345
- [x] #6350 
- [x] #6351 

---------------------------------------------------------------------------------------------

Current "approved" rust.toml (with atleast one approval)
```
select = [
    "C4",
    "E713",
    "SIM2",  # simplify boolean comparisons
    "SIM110",  # convert loop to 'any'
    "SIM111",  # convert loop to 'all'
    "SIM109",  # use a tuple for multiple comparisons
    "SIM118",  # use 'key in dict'
    "PGH003",  # forbid blanket 'type: ignore' comments
]
```

**Comment by tinaoberoi** [comment]
Hi @danieleades, 
this looks like an interesting issue to solve. I would like to work on this if nobody else is working on it.

**Comment by danieleades** [comment]
> Hi @danieleades, this looks like an interesting issue to solve. I would like to work on this if nobody else is working on it.

Glad to hear it! There are already several open PRs (listed above). What this needs now is a maintainer to review it.

**Comment by MridulS** [comment]
@danieleades Thanks for all the PRs. Individual PRs are indeed a nice way to review all the changes, but merging them one by one would create a lot of merge conflicts all around. How about we start reviewing the individual changes in these one-lint-rule-per-PR but once we are done with the review we close that PR and have all the reviewed changes added once with a ruff.toml file at the end of this exercise. This will also let us add just one commit in the git-blame-ignore file.
We can keep a track of the "approved" lints/ruff.toml structure in this issue.

What do you think? Thanks again for sticking with this :)

**Comment by MridulS** [comment]
Also ruff is having a lot of quick releases, are you keeping a track of things that changing underneath there? We wouldn't want to review for 0.0.215 and then add 0.0.223 (the latest release) in the big PR. Let's keep the changes synced to one ruff version (I'll update the PR to 0.0.223)

**Comment by danieleades** [comment]
Yep, sounds good. Happy to push a new PR with the superset of reviewed lints, and the maximum of ruff version across them.

As an aside- most of these lints are automatically applied, which has the side effect that they're very easy for me to rebase.

Another approach would be to create a new branch, merge these PRs one by one into the branch, and then create a single PR to merge the branch into 'main'. I guess it's equivalent, but preserves the outcome of the PRs (ie accepted or rejected)

Happy to support whatever you prefer.

**Comment by danieleades** [comment]
> > Another approach would be to create a new branch, merge these PRs one by one into the branch, and then create a single PR to merge the branch into 'main'. I guess it's equivalent, but preserves the outcome of the PRs (ie accepted or rejected)
> 
> Yeah that's good too. We can do this on a branch on your fork and then you can just send that PR once it approved?

in order to keep a record of the approval chain within the networkx repo it would have to be a branch in the networkx original, not the fork. If that's too tricky logistically, I'll just create a new branch to squash all my existing diffs.

I don't see any objections on the open diffs so far, modulo the discussion in #6320. Is further approval required, or should I start pulling these together?

**Comment by MridulS** [comment]
> in order to keep a record of the approval chain within the networkx repo it would have to be a branch in the networkx original, not the fork. If that's too tricky logistically, I'll just create a new branch to squash all my existing diffs.

We can use Networkx PRs too.

> I don't see any objections on the open diffs so far, modulo the discussion in https://github.com/networkx/networkx/pull/6320. Is further approval required, or should I start pulling these together?

Please do create a new PR with all the changes with the ruff setup file https://github.com/networkx/networkx/issues/6325#issue-1518545283 (added at the end of the comment), and keep it draft for now. We can move to to review status as soon as we are done with all the ruff linting we want to get in.
