### ISSUE TITLE
nx.DiGraph.to_undirected() not working as expected for bidirectional edges when using as_view = True

### ISSUE THREAD

**Issue by sengels-tum** [networkx/networkx#6336]
Problem: When using `to_undirected()` on a DiGraph the properties are inconsistent, i.e., differ depending on if as_view was set to True or False. More precisely, the reported degree is not as expected when using `as_view = True`. I guess this might also have an effect on other properties that depend on degree.

### Current Behavior

The node degree of the undirected graph returned by `to_undirected()` is different depending on if as_view was set to True or False. If the directed graph had bidirectional edges, the degree is off by approx. a factor of 2 in the graph view. Everything works as expected if as_view is set to false.

### Expected Behavior

`G.to_undirected(as_view = False).degree()` and `G.to_undirected(as_view = True).degree()` should behave the same.

### Steps to Reproduce

```
import networkx as nx
import sys

print(sys.version) # 3.10.8 | packaged by conda-forge | (main, Nov 24 2022, 14:07:00) [MSC v.1916 64 bit (AMD64)]
print(nx.__version__) # 2.8.8

G = nx.DiGraph()
G.add_nodes_from(["v0","v1","v2"])
G.add_edges_from([("v0","v1"),("v1","v0"),("v1","v2")])
print(G.degree()) # Correct [('v0', 2), ('v1', 3), ('v2', 1)]

G_undir_1 = G.to_undirected(as_view = False)
print(G_undir_1.degree()) # Correct [('v0', 1), ('v1', 2), ('v2', 1)]

G_undir_2 = G.to_undirected(as_view = True)
print(G_undir_2.degree()) # Incorrect [('v0', 2), ('v1', 3), ('v2', 1)]
```

### Environment

Python version: 3.10.8
NetworkX version: 2.8.8

### Additional context

n/a

**Comment by Qudirah** [comment]
@MridulS @paulitapb @rossbar @jarrodmillman you guys should look at this issue

**Comment by dschult** [comment]
Thanks @Qudirah  for the nudge on this Issue. and Thanks @sengels-tum for reporting this!!

That's a bug. The `__len__` method in `UnionAtlas` was assuming distinct keys in the two dicts it is taking the union of. When they are not distinct, it gives the wrong answer. **oops!** 
PR coming up.
