### ISSUE TITLE
`subgraph_view` calls filter functions multiple times for each node and edge

### ISSUE THREAD

**Issue by rbaard1** [networkx/networkx#6358]
Consider the following dummy filtering functions to be used with `subgraph_view`:
```python
import networkx as nx
G = nx.path_graph(3)

def filter_node(n):
   print(f'filter_node({n})')
   return True

def filter_edge(n1, n2):
   print(f'filter_edge({n1}, {n2})')
   return True
```

Now, if you call
```python
nx.subgraph_view(G, filter_node=filter_node).nodes
```
I would expected the function `filter_node` to be called 3 times: once for each node. But: it is called 6 times.

And if you call
```python
nx.subgraph_view(G, filter_edge=filter_edge).edges
```
I would expect the function `filter_edge` to be called 2 times: once for each edge, but it is actually called 12 times.

This pattern seems to hold in general for graphs with `n` nodes: `filter_node` is called `2 * n` times and `filter_edge` is called `6 * n` times.

I am not sure if this should be called a bug, and there might be a good reason for this behavior, but it was certainly unexpected for me. If it is possible to prevent redundant calls to filter functions, this might also speed up the filtering. In the case that this behavior is expected, it might be good to mention it in the documentation for `subgraph_view`.

### Current Behavior

Calling `nx.subgraph_view(G, filter_node=filter_node).nodes`:
```python
filter_node(0)
filter_node(1)
filter_node(2)
filter_node(0)
filter_node(1)
filter_node(2)
```

Calling `nx.subgraph_view(G, filter_edge=filter_edge).edges`:
```python
filter_edge(0, 1)
filter_edge(1, 0)
filter_edge(1, 2)
filter_edge(2, 1)
filter_edge(0, 1)
filter_edge(0, 1)
filter_edge(1, 0)
filter_edge(1, 2)
filter_edge(1, 0)
filter_edge(1, 2)
filter_edge(2, 1)
filter_edge(2, 1)
```

### Expected Behavior

Calling `nx.subgraph_view(G, filter_node=filter_node).nodes`:
```python
filter_node(0)
filter_node(1)
filter_node(2)
```

Calling `nx.subgraph_view(G, filter_edge=filter_edge).edges`:
```python
filter_edge(0, 1)
filter_edge(1, 2)
```
or maybe also include the mirrored edges:
```python
filter_edge(0, 1)
filter_edge(1, 0)
filter_edge(1, 2)
filter_edge(2, 1)
```

### Environment

Python version: 3.10.8
NetworkX version: 3.0

**Comment by dschult** [comment]
I think there is some duplication of the filtering due to the process of printing.
If you use `for n in SG.nodes:` you will see only one filter call per node of `G`.
But if you print the `SG.nodes` attribute it must create the string representation
of the object which involves filtering the nodes.
```python
G=nx.path_graph(9)
def sn(n):
    print(f"filtering node {n}")
    return n<4

SG=nx.subgraph_view(G, sn)
for n in SG.nodes:
   print(n)
```

with output
```
filtering node 0
0
filtering node 1
1
filtering node 2
2
filtering node 3
3
filtering node 4
filtering node 5
filtering node 6
filtering node 7
filtering node 8
```

Similarly, constructing a list by hand only filters once per node. 
```python
ml=[]
for n in SG.nodes:
    ml.append(n)
print(ml)  # output: [0, 1, 2, 3]
```

But converting `SG,nodes` to a list seems to iterate through the nodes multiple times.
```python
ml=list(SG.nodes)
```

produces output
```
filtering node 0
filtering node 1
filtering node 2
filtering node 3
filtering node 4
filtering node 5
filtering node 6
filtering node 7
filtering node 8
filtering node 0
filtering node 1
filtering node 2
filtering node 3
filtering node 4
filtering node 5
filtering node 6
filtering node 7
filtering node 8
filtering node 0
filtering node 1
filtering node 2
filtering node 3
filtering node 4
filtering node 5
filtering node 6
filtering node 7
filtering node 8
```
I'm not sure why this would be true.  Perhaps because `len(SG)` also requires filtering. I'll look into that more.

**Comment by dschult** [comment]
It looks like `list(seq)` calls `len(seq)` to figure out how big a list to allocate before iterating over `seq` to get the values. So,  while having the `__len__` function is convenient for users who want the length.  It may cause multiple iterations through the filter when you don't expect a python function to call `len`.  For expensive filters, care would need to be taken.

We could remove the convenience of providing `__len__` and document to users that to get the length they should use something like `sum(1 for n in SubGraph)`. Then `list()` would use it's backup estimate of list length when the object has no length hint.  We could also add a `__length_hint__` function that just returns the length of the graph, or something like that. That would help list guess the size (incorrectly and then adjust as it needs to) without causing the full iteration process to be needed.

Not sure what makes the most sense here...

**Comment by rbaard1** [comment]
Thanks @dschult for looking into this.

Note to self: I didn't understand at first what you meant with '`list(seq)` calls `len(seq)`' because I couldn't find this in the NetworkX code, but it turns out that [Python does this automatically as an optimization when `__len__` is available](https://stackoverflow.com/questions/41474829/why-does-list-ask-about-len). The `__length_hint__` method is documented in [PEP 424](https://peps.python.org/pep-0424/).

I am also not sure what the most sensible solution is. The number of nodes _is_ sized, so implementing `__len__` does make sense, and maybe documenting that is enough.

Perhaps a related observation: if I call `nx.subgraph_view(G, filter_node=filter_node).copy()`, with `G = nx.path_graph(3)`, then I get 20 calls:
```
filter_node(0)
filter_node(0)
filter_node(1)
filter_node(1)
filter_node(2)
filter_node(2)
filter_node(0)
filter_node(0)
filter_node(1)
filter_node(1)
filter_node(1)
filter_node(1)
filter_node(0)
filter_node(0)
filter_node(2)
filter_node(2)
filter_node(2)
filter_node(2)
filter_node(1)
filter_node(1)
```

The first 6 calls are for [copying the nodes](https://github.com/networkx/networkx/blob/main/networkx/classes/graph.py#L1642), and then there are 14 calls when [copying the edges](https://github.com/networkx/networkx/blob/main/networkx/classes/graph.py#L1643). I think it should be possible to bring this number down.

**Comment by dschult** [comment]
I have no doubt that we could reduce the number of times that the filter is called. But there will be a cost. For example, removing `__len__` would be one way. But it will cost if users want to use the `len` function, and it will cost when Python functions like list, dict or tuple use `len` to estiate the size of memory to allocate. I think this may be worth pursuing, but only if we keep a wide angle on our goals. The goal is not to reduce the number of times a node is filtered. It is to reduce the time needed to do common actions with a subgraph.  Hopefully reducing the number of filter function calls will also make other things more efficient too. :}

**Comment by dschult** [comment]
I'm interested to hear what the origin of this Issue was.  What are you trying to do with the `subgraph_view` function?

**Comment by rbaard1** [comment]
I was making a copy of a filtered view, where I filtered nodes and edges by whether they were active at a certain time or not. Roughly 400 nodes and 600 edges, and the filter is not expensive, so performance is not an issue for me. What drew my attention is that I give out `warning`s in certain situations where it is ambiguous whether a node or edge is active at some time. I was unittesting this, and tried to count the number of warnings to test some specific cases. That is when I noted the `filter_edge` and `filter_node` function are called more often than I expected, because I got more warnings than expected.

To be honest, I was mainly interested in trying to understand this behavior and whether I had made some mistake in my code. Now that I now that it is not a bug, and it is not easy to resolve elegantly, feel free to close the issue. There might be some clever solution, but I can imagine there are more pressing issues to be solved at this time.

Thanks for taking your time to look into this though, I have learned something new about Python internals!

**Comment by dschult** [comment]
That's helpful to know.  The views are more straightforward for subgraph_view when there is a set of nodes to filter against. That is, when you use the provided `nx.filters.hide_nodes` or `nx.filters.show_nodes` and their cousins for edges. Those special cases store the nodes to show in a attribute of the filter function and it makes the filtering process more efficient. 

All of this indicates that the subgraph view interface is too complicated and should be simplified or maybe removed. I don't think that will happen any time soon, but if it affects other people that would be good to know about. I'm going to close this issue -- but further comments will be seen and followed up on.

Thanks!
