### ISSUE TITLE
base (ubuntu, pypy-3.8) test fails in PR because of numpy import

### ISSUE THREAD

**Issue by danigil** [networkx/networkx#6377]
We created a PR for some algorithms we implemented and want to add into the library,  
but one of our pytests fails in the "base (ubuntu, pypy-3.8)" automatic test, prompting the following errors:  
  
FAILED networkx/algorithms/bipartite/tests/test_EFM.py::TestMinimumWeightEnvyFreeMatching::test_envy_free_perfect_matching - ModuleNotFoundError: No module named 'numpy'
FAILED networkx/algorithms/bipartite/tests/test_EFM.py::TestMinimumWeightEnvyFreeMatching::test_non_empty_envy_free_matching - ModuleNotFoundError: No module named 'numpy'

### Current Behavior
importing numpy inside our test raises errors

### Expected Behavior
We expect importing numpy to not cause errors since it's one of the packages included in the library's requirements

### Environment
We are both programming in a venv environment, but the problem arises in the automated tests, and not in our systems.

Python version: 3.8
NetworkX version: latest

### Additional context
To demonstrate the problem, and ensure it isn't a side-effect of something other than the import,  
we created another PR which only contains the code that causes the error, indeed, the same problem persists.  
click [here](https://github.com/networkx/networkx/pull/6374) to see this PR we created.  
PR number: 6374

**Comment by danigil** [comment]
Thanks very much for the feedback, and sorry for me being misinformed :>
Do you maybe think we should look for a workaround that doesn't use numpy? will adding these changes hinder our PR somehow?

**Comment by MridulS** [comment]
numpy is fine is to use, adding c/cython is the only issue as we don't yet have a process of incorporating those changes in networkx :)

I'll go ahead and close this issue, feel free to open a new one or ping me on a pull request you are stuck at :)
