### ISSUE TITLE
subgraph_view return corrupt graph when filter function is invalid.

### ISSUE THREAD

**Issue by LukasMoll** [networkx/networkx#6391]
### Current Behavior
```
def filter_func():
        return lambda x: x.real
    graph = nx.DiGraph()
    graph.add_edges_from([(0, 1), (1, 2), (2, 3)])
    filtered_graph = nx.subgraph_view(graph, filter_func)
```
filtered_graph = corrupt graph.
<img width="1120" alt="Screenshot 2023-01-24 at 13 29 56" src="https://user-images.githubusercontent.com/86722560/214292049-6473548e-04a8-45c6-9179-666805e2bf31.png">

### Expected Behavior

It should throw an error.
If def filter_func is corrected:
```
def filter_func(x):
        return lambda x: x.real
```
It'll return a normal graph e.g.:
<img width="749" alt="Screenshot 2023-01-24 at 13 31 20" src="https://user-images.githubusercontent.com/86722560/214292304-be9a79ba-d3e3-4637-9ca1-9cb07d3f6623.png">

### Steps to Reproduce

See code snippet above.

### Environment

IDE: PyCharm (that's where I got the images from)
Python version: 3.10
NetworkX version: 3.0

**Comment by LukasMoll** [comment]
For some reason I can't upload images so here it goes:
Normal graph:
<img width="589" alt="Screenshot 2023-01-24 at 13 33 40" src="https://user-images.githubusercontent.com/86722560/214292725-d5874854-293c-44ed-a576-11acb9abf6f7.png">
Corrupt graph:
<img width="1095" alt="Screenshot 2023-01-24 at 13 34 51" src="https://user-images.githubusercontent.com/86722560/214292970-309fb4aa-f03c-4990-a14a-e5a43c7773bd.png">

**Comment by LukasMoll** [comment]
I can take this issue up. A proposed fix would be to validate the filter func or/and validate the resulting output graph.

**Comment by MridulS** [comment]
Thanks for bringing this up!

> A proposed fix would be to validate the filter func or/and validate the resulting output graph.

How do you plan to validate this? Currently it returns a view and the error would only show up if you actually compute the nodes/edges. If we compute them then we lose out on the flexibility of keeping the value lazily evaluated. 

We do get a corrupted graph as an output but doing anything on that graph should pop up an error with enough information to the user about it, like the above example will give you the following error.

```  python
In [4]: nx.subgraph_view(graph, filter_func).nodes
....
....
TypeError: filter_func() takes 0 positional arguments but 1 was given
```

**Comment by LukasMoll** [comment]
It can still go unnoticed. For example when you use that corrupted graph in nx.bidirectional_dijkstra(corrupted_graph) it'll give a wrong outcome and go unnoticed.

Like you did in your code snippet I'd like to call each attribute (nodes, edges etc.). We'd have a validate_graph(graph: nx.DiGraph) function for this. And with such we'd avoid returning corrupted graphs.

I'm not sure yet how we'll validate the input function.

**Comment by dschult** [comment]
I don't understand your `filter_func`.  It doesn't even return true or false...  it just defines a lambda function and then exits. Am I missing something?  

What is the motivation of this feature request?

**Comment by MridulS** [comment]
> For example when you use that corrupted graph in nx.bidirectional_dijkstra(corrupted_graph) it'll give a wrong outcome and go unnoticed.

Can you give a small code example to show this, as soon as any function which does any computation on the graph calls the subgraph_view graph it will error out and tell the user that the way `filter_func` is defined is wrong.

Like for `betweenness_centrality`:

``` python
In [27]: graph = nx.DiGraph()

In [28]: graph.add_edges_from([(0, 1), (1, 2), (2, 3)])

In [29]: filtered_graph = nx.subgraph_view(graph, filter_func)

In [30]: nx.betweenness_centrality(filtered_graph)
.....
.....
.....
TypeError: filter_func() takes 0 positional arguments but 1 was given
```

Anyway I'm not sure if there is a clean way of preventing users from declaring wrong filter functions. They will get what they feed in :/

**Comment by LukasMoll** [comment]
@MridulS Sorry I was a bit vague there but this is the basic idea behind. We have a graph and orig 0, dest 3 we don't know if those are in the graph. If they are we just return the shortest path, if they are not in the graph than we'll return an empty path with infinite time. If we do this with a wrong `filter_func` we'll always get the `inf, []` response. Bugs like these might be though to detect.
```
    def filter_func():
        lambda x: x.real
    graph = nx.DiGraph()
    graph.add_edges_from([(0, 1), (1, 2), (2, 3)])
    filtered_graph = nx.subgraph_view(graph, filter_func)
    try:
        result = nx.bidirectional_dijkstra(filtered_graph, 0, 3)
    except NodeNotFound:
        result = (float("inf"), [])
```

I think it's still nice to validate that the output is not corrupted to prevent those "hidden bugs" from happening.

**Comment by LukasMoll** [comment]
@dschult Yes you're right I made a typo sorry about that! The result is still the same. An invalid filter_func results in a corrupt graph.

**Comment by MridulS** [comment]
> If we do this with a wrong filter_func we'll always get the inf, [] response. Bugs like these might be though to detect.

Hmm, these bugs would be hard to catch. We give users enough flexibility with these things and the `filter_funcs` are **supposed** to return a boolean. Now if the user isn't testing their `filter_funcs` we can't really expect networkx to test all user input. This would mean a check in every single function that takes in a graph object or any other user defined callable. We even avoid doing type checks (python is still a dynamic language 🙃). These checks are cheap but if we start checking for every little thing this will just add too much cruft to the codebase and it may start having performance issues too.

If you do come up with a not-so-invasive way of fixing it, do let us know :)

**Comment by LukasMoll** [comment]
I was thinking about something like `assert_graph_not_corrupt`? It would be a one liner and raise an error if it's corrupted (or whatever you want to call it).

I was thinking it'll check nodes, edges and adj? Those seem to be the most important. I'm not sure if the issue still presents itself even when those are valid. This should avoid those "hidden bugs".

**Comment by rossbar** [comment]
> Anyway I'm not sure if there is a clean way of preventing users from declaring wrong filter functions. They will get what they feed in :/

Static type checking would likely help here. If we had annotations for `filter_node` and `filter_edge` that specified them as callables that expect nodes or edges as input, respectively, and must return bools then this issue would be caught by e.g. mypy.

**Comment by LukasMoll** [comment]
@rossbar I implemented this in that PR. I tested it with linters. We could do this for more if needed.

**Comment by MridulS** [comment]
> Static type checking would likely help here. If we had annotations for filter_node and filter_edge that specified them as callables that expect nodes or edges as input, respectively, and must return bools then this issue would be caught by e.g. mypy.

True but that still requires the user to know about mypy and actually run it 🙃.

> I was thinking about something like assert_graph_not_corrupt? It would be a one liner and raise an error if it's corrupted 

Similar to the other issue I'm not super excited about adding just another helper function that can be checked by the user in one line (like just `print(filtered_graph)` )

PS: Maybe this is just a disconnect between how different people use networkx. I extensively use jupyter notebook while working with networkx and there is a quick feedback loop. So something like this wouldn't happen as this corrupted graph will be quickly caught.

**Comment by LukasMoll** [comment]
> PS: Maybe this is just a disconnect between how different people use networkx. I extensively use jupyter notebook while working with networkx and there is a quick feedback loop. So something like this wouldn't happen as this corrupted graph will be quickly caught.

Yes, this is looks like it.

**Comment by Qudirah** [comment]
@MridulS I think this needs to be closed. Seems like a deadlock.

**Comment by PurviChaurasia** [comment]
Since this discrepancy is arising due to different usage of NetworkX, perhaps we can add a small pointer regarding this in the documentation? Just for future clarification in case someone passes a similar problem. @MridulS Let me know what you think.

**Comment by rossbar** [comment]
FWIW I'm -1 on adding any explicit input/output validation here. As stated above, the flexibility here is intentional, and it is incumbent on the user to ensure that the callable they are using for filtering matches the prescribed interface. It certainly is reasonable (and good practice) to validate that this is indeed the case, but my sense is that this is best done in *user* code, not upstream in NetworkX.
