### ISSUE TITLE
Louvain Algorithm Incorrectly Imports `modularity`

### ISSUE THREAD

**Issue by jonathangomesselman** [networkx/networkx#6406]
### Current Behavior

In `louvain.py` the utility function `modularity` is incorrectly imported as `from networkx.algorithms.community import modularity`. This breaks the algorithm 

### Expected Behavior

The import has changed to `from networkx.algorithms.community.quality import modularity` as seen in e.g. `modularity_max.py`

Python version:
NetworkX version: 3.0

**Comment by rossbar** [comment]
The import statement:

```python
from networkx.algorithms.community import modularity
```

is valid, so there should be no problem. I can't reproduce the error; the following works fine locally:

```python
>>> import networkx as nx
>>> G = nx.complete_graph(5)
>>> nx.community.louvain_communities(G)
[{0, 1, 2, 3, 4}]
```

Can you provide a minimal example of the import that produces the error, along with the traceback as well as the Python version?

**Comment by jonathangomesselman** [comment]
Hi @rossbar - you are totally correct. This was a mistake on my part. However, my confusion stemmed from a related question that I will post about separately related to running `louvain` over directed graphs. Thanks and sorry again for the mistake!
