### ISSUE TITLE
Duplicate `MultiDiGraph.succ` in the documentation

### ISSUE THREAD

**Issue by ywangmy** [networkx/networkx#6408]
### Current Behavior

See the documentation [https://networkx.org/documentation/stable/reference/classes/multidigraph.html#methods](https://networkx.org/documentation/stable/reference/classes/multidigraph.html#methods)

Duplicate `MultiDiGraph.succ`.

### Expected Behavior

One of them should be `MultiDiGraph.pred` instead.

### Environment

Python version:
NetworkX version:

**Comment by MridulS** [comment]
Indeed this is a bug! Thanks for the catch @ywangmy
https://github.com/networkx/networkx/pull/6409 should fix it.
