### ISSUE TITLE
Pull request unknown lint fail

### ISSUE THREAD

**Issue by TalSomech** [networkx/networkx#6416]
Hi i wanted to open a pull request but except 1 all of my tests pass , however i do not understand the problem or why its failing , im adding a screenshot here of the said test
![Capture](https://user-images.githubusercontent.com/73115681/217521333-3f638721-b9a3-429c-8732-08c62c7303a4.PNG)
any help is welcome

**Comment by rossbar** [comment]
See #6407 

Generally speaking, some here are some best-practices that should help avoid problems like this in the future:
 1. Make sure you are up-to-date with `main` on your development branch
 2. You can search the issue tracker + PRs simultaneously to see if there's anything that looks related to the issue you're seeing.
