### ISSUE TITLE
Issue with matrix market read functionality from NetworkX documentation

### ISSUE THREAD

**Issue by alvaradoo** [networkx/networkx#6419]
### Current Behavior

When following a similar format as presented [here](https://networkx.org/documentation/stable/reference/readwrite/matrix_market.html), my code returns an error message stating:

```
TypeError: 'coo_matrix' object is not subscriptable
```

### Expected Behavior

The code above should create a graph H from the matrix market file. 

### Steps to Reproduce

The way I am reading my file is as follows:
```python
with open(filename, "rb") as fh:
    buf = io.BytesIO(fh.read())
buf.seek(0)
H = nx.from_numpy_array(sp.io.mmread(buf))
print("H =", H)
```

### Environment

Python version: 3.10
NetworkX version: 3.0
SciPy version: 1.10.0

### Additional context

None.

**Comment by MridulS** [comment]
Is the matrix market file in the array format or coordinate one?

Could you try with `nx.from_scipy_sparse_array` instead of `nx.from_numpy_array`?

**Comment by alvaradoo** [comment]
Ah, yes it was in coordinate format. I had started with the numpy instructions but then realized I was in coordinate mode and didn't change the reading method. That worked! Thanks.
