### ISSUE TITLE
rom_prufer_sequence report "ValueError: too many values to unpack"

### ISSUE THREAD

**Issue by newptcai** [networkx/networkx#6420]
### Current Behavior

If you try the following code
```
import networkx as nx
nx.from_prufer_sequence([7, 5, 5, 3, 1])
```
you will get
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/xing/miniconda3/lib/python3.9/site-packages/networkx/algorithms/tree/coding.py", line 396, in from_prufer_sequence
    u, v = orphans
ValueError: too many values to unpack (expected 2)
```

### Expected Behavior

The code should return a tree without any problem. See Applied Combinatorics by Mitchel T. Keller, William T. Trotter, [Chapter 5.6](https://www.rellek.net/book/s_graphs_counting-trees.html)

**Comment by dschult** [comment]
I think the sequence must have `n-2` values with numbers between 0 and n-1.  This has 5 values, so n=7. But the first number in the sequence is 7.  So this is an invalid sequence... Right?
I guess the error message could be more helpful. But first -- let's address the expected behavior question...
Should this return a tree?

**Comment by newptcai** [comment]
I see. But node labels starting from 0 is not the convention in most math books, including [Wikipedia](https://en.wikipedia.org/wiki/Pr%C3%BCfer_sequence).

Anyway, better error would be helpful.

**Comment by MridulS** [comment]
> I see. But node labels starting from 0 is not the convention in most math books, including [Wikipedia](https://en.wikipedia.org/wiki/Pr%C3%BCfer_sequence).

fwiw, the paper cited in the references of the implementation (https://www.scirp.org/journal/paperinformation.aspx?paperid=532) does use 0 to n - 1. Should be print a warning/error about this? Maybe catch the error when looking for orphans.

**Comment by Qudirah** [comment]
@MridulS Should I work on catching the error?
