### ISSUE TITLE
Reference for inverse_line_graph

### ISSUE THREAD

**Issue by barbireau** [networkx/networkx#6428]
There is a spelling mistake in the reference for the documentation of inverse_line_graph (latest version). 

https://networkx.org/documentation/stable/reference/generated/networkx.generators.line.inverse_line_graph.html

The author is "N. D. Roussopoulos" instead of N. Roussopolous (note the location of "ou"). Also, it would be nice to add a link or DOI to the article. The complete bibliographic info is below. 

@article{ROUSSOPOULOS1973108,
title = {A max {m,n} algorithm for determining the graph H from its line graph G},
journal = {Information Processing Letters},
volume = {2},
number = {4},
pages = {108-112},
year = {1973},
issn = {0020-0190},
doi = {https://doi.org/10.1016/0020-0190(73)90029-X},
url = {https://www.sciencedirect.com/science/article/pii/002001907390029X},
author = {Nicholas D. Roussopoulos},
keywords = {graph, maximal subgroup, complete graph, complete bipartite, automorphism}
}

**Comment by Blueclaus13** [comment]
Could you assign to me this issue?

**Comment by barbireau** [comment]
I think I can't do that. Can somebody else do this? Possibly @rossbar?

**Comment by dschult** [comment]
We don't usually use the "assign" function in Github to assign Issues.
Please open a PR with the fix for this issue and we will review it.
Thanks!

**Comment by Blueclaus13** [comment]
great thanks!

**Comment by Blueclaus13** [comment]
I'm sorry @barbireau I have a question with your dio link. It redirects me to a DOI not found when I click on it. I'm doing something wrong or the link is wrong ?

**Comment by barbireau** [comment]
The DOI link should be without the "}" at the end. Github automaticaly makes the doi a clickable link, but adds the "}" by mistake.

**Comment by Blueclaus13** [comment]
> I'm sorry @barbireau I have a question with your dio link. It redirects me to a DOI not found when I click on it. I'm doing something wrong or the link is wrong ?

ooh I got it, it took a square bracket as part of the link
