### ISSUE TITLE
Restructure names of readwrite modules (migrated from Trac #655)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#643]
Original ticket https://networkx.lanl.gov/trac/ticket/655
Reported 2011-11-28 by @hagberg, assigned to @hagberg.

Consider changing names of graph readers and writers to standardize in modules.
Change names from, e.g. 

``` python
read_graphml()
write_graphml()
```

to 

``` python
graphml.read()
graphml.write()
```

Another benefit might be that all of the modules for reading and writing various formats wouldn't need to be automatically imported.  That is, we could import modules when needed and access them like

``` python
>>> from networkx import graphml
>>> G = graphml.read(path)
```

**Comment by hagberg** [comment]
This is really just syntax and can wait for future release.

**Comment by hagberg** [comment]
Closed due to inactivity.
