### ISSUE TITLE
Some tests cancelled automatically even though all tests passed

### ISSUE THREAD

**Issue by bar-schtalman** [networkx/networkx#6456]
Pull request [Pull request](https://github.com/networkx/networkx/pull/6376) 
I recently made some changes to the code and submitted a pull request. The pull request passed all tests.

However, when I made some additional changes and attempted to commit them, I noticed that some of the tests were cancelled automatically. These tests had passed during the previous pull request, and I did not receive any error messages or notifications about why they were cancelled.

I've reviewed my changes and verified that they should not have affected the tests that were cancelled. I suspect that there may be a problem with the testing system or the underlying infrastructure.

Steps to reproduce:

Make changes to the code and attempt to commit them.

Observe that some tests are cancelled automatically, even though they passed during the previous pull request.

Expected behavior:

All tests should pass or fail based on their actual results, and should not be cancelled automatically without a clear reason.

Actual behavior:

Some tests are cancelled automatically, even though they passed during the previous pull request, and there is no clear reason why they were cancelled.

Environment:

Operating system: Mac os
Programming language: Python

**Comment by paulitapb** [comment]
This sometimes happens with the artifacts that run the tests. Maybe there was another push and the artifacts canceled the tests in your PR to run tests on another PR. Don't worry about it. When someone from NetworkX reviews your PR they can rerun the tests.

**Comment by MridulS** [comment]
Yeah, that's just an intermittent github issue. I reran the tests. Should work now :)
