### ISSUE TITLE
upgrade 2.8.6  -> 3.0 breaks shortest_path()

### ISSUE THREAD

**Issue by jkbgbr** [networkx/networkx#6458]
I just re-installed networkx without specifying version so I was upgraded from 2.8.6 to 3.0
Running unaltered code calling nx.shortest_path(*args, **kwargs) under 2.8.6 runs fine and produces correct result but 3.0 fails with an error, missing arguments.

Looking at the source, the 3.0 version got a decorator which doesn't seem to work properly.

The error is reproduced using stripped-down [lollipop example](https://networkx.org/documentation/stable/auto_examples/basic/plot_properties.html#sphx-glr-auto-examples-basic-plot-properties-py)

### Current Behavior

under 3.0:
```
import networkx as nx
G = nx.lollipop_graph(4, 6)
print(nx.shortest_path(G=G, source=list(G.nodes())[1], target=list(G.nodes())[9]))
```
produces

```
Traceback (most recent call last):
  File "C:\Users\XYZ\AppData\Roaming\JetBrains\PyCharm2022.3\scratches\scratch_1.py", line 7, in <module>
    print(nx.shortest_path(G=G, source=list(G.nodes())[1], target=list(G.nodes())[9]))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\modules\venv\networkx_3\Lib\site-packages\networkx\classes\backends.py", line 134, in wrapper
    graph = args[0]
            ~~~~^^^
IndexError: tuple index out of range
```

### Expected Behavior

under 2.8.6:
```
import networkx as nx
G = nx.lollipop_graph(4, 6)
print(nx.shortest_path(G=G, source=list(G.nodes())[1], target=list(G.nodes())[9]))
```
produces
`[1, 3, 4, 5, 6, 7, 8, 9]`

### Environment
Python version: anaconda 3.10, networkx installed via pip
NetworkX version: 2.8.6 and 3.0

**Comment by dschult** [comment]
The error only occurs if you give a keyword name to the input G.  
We need to fix that...  but try it with input `G` instead of `G=G` and it should work just fine.

Perhaps we should make that input a position-only input. But maybe it would be possible to make
the backend code find keyword arguments as well as position arguments. 
(if len(args)<1 look for a keyword `G`? But then we can't apply it to functions that name the graph something else -- if there are any such functions :})

**Comment by jkbgbr** [comment]
> The error only occurs if you give a keyword name to the input G.
> We need to fix that... but try it with input `G` instead of `G=G` and it should work just fine.

I confirm this.

> Perhaps we should make that input a position-only input.

That would reduce compatibility to 3.8+ if I'm not mistaken. IDK if it is a good solution but what about raising an exception if len(args) != 0?

**Comment by MridulS** [comment]
Urghh, yes this is an issue. Thanks for opening the issue! We should have caught this before.

> That would reduce compatibility to 3.8+ if I'm not mistaken. IDK if it is a good solution but what about raising an exception if len(args) != 0?

We already are py3.8+ for new networkx releases.

**Comment by jkbgbr** [comment]
> That would reduce compatibility to 3.8+ if I'm not mistaken. IDK if it is a good solution but what about raising an exception if len(args) != 0?

I meant !=1 of course.
Anyway, thanks for all the effort put into this superb package, it greatly helped me to solve some of the problems I had faced in my apps.

**Comment by dschult** [comment]
We'd have to make any function that uses the `_dispatch` decorator make the first input position-only.
Would it be more flexible to allow the `_dispatch` decorator to include as an argument the name of the possibly keyword input variable? It could default to `G` and not change much code anywhere -- and we'd have to document that anyone decorating a function with first argument called something other than `G` will need to use this argument for the decorator.

Then inside the decorator code we check if `len(args)<1` and if so, we look up the keyword arg.
(of course, maybe we want to allow dispatch to position arguments other than  the first position...  but one step at a time here... :}  Not sure what is best...

**Comment by MridulS** [comment]
> We'd have to make any function that uses the _dispatch decorator make the first input position-only.
Would it be more flexible to allow the _dispatch decorator to include as an argument the name of the possibly keyword input variable? It could default to G and not change much code anywhere -- and we'd have to document that anyone decorating a function with first argument called something other than G will need to use this argument for the decorator.

We anyway have to revisit this specific bit of the decorator as right now the assumption is that there is only 1 argument with a graph object. The current `_dispatch` implementation wouldn't work for functions where you expect 2 graph inputs (like isomorphism). IMO these changes should happen inside the `_dispatch` decorator and we should do better job of standardizing function arguments (like it should either be just `G` or `graph` or something) elsewhere in the codebase.

**Comment by dschult** [comment]
Sounds good.  I think it is pretty universal within NetworkX that the graph goes first and it is named `G`.
I guess that might be the first fix then...  Change `_dispatch` to check if `len(args)` is zero and if so, look at `kwargs` for an entry called `G`.  That seems easier than going through the codebase to add position-only syntax for each function that takes a graph as the first argument.  :)
