### ISSUE TITLE
Red/write weighted edgelist with tuples as nodes

### ISSUE THREAD

**Issue by zzpmarco** [networkx/networkx#6468]
read_weighted_edgelist after write_weighted_edgelist produces an error

### Current Behavior

After having created a graph with tuples as nodes and weighted edges (see attachments), I am writing the edgelist to a text file.
Subsequent reading attempts fail with exception:

File "[...]\Python3.7\lib\site-packages\networkx\readwrite\edgelist.py", line 281, in parse_edgelist
    f"Edge data {d} and data_keys {data} are not the same length"

### Expected Behavior

The graph should be read in, normally.
Hint:
The textual string encoding of tuples (see attachments) does not seem to be correct.

### Steps to Reproduce

Please execute the python fragment in attachment.
txt file produced in the environment below also attached.

### Environment

Python version: 3.7.9
NetworkX version: 2.6.3

[graph_with_tuples_rw.zip](https://github.com/networkx/networkx/files/10897544/graph_with_tuples_rw.zip)

**Comment by MridulS** [comment]
> After having created a graph with tuples as nodes and weighted edges (see attachments), I am writing the edgelist to a text file.

Could you give a minimal example in text? No one should be downloading random .zip files from the internet :D

**Comment by zzpmarco** [comment]
import networkx as nx

import random

if __name__ == '__main__':

    # Generate some tuples
    length = 10
    basic_row = [0] * length
    all_nodes = list()
    all_nodes.append(tuple(basic_row))
    for i in range(length):
        row = basic_row.copy()
        row[i] = 1
        all_nodes.append(tuple(row))

    # Generate graph with tuples as nodes
    graph = nx.Graph()
    for node in all_nodes:
        graph.add_node(node)

    # Generate edges with random weight
    random.seed(3)
    for i in range(length):
        for j in range(i - 1):
            weight = random.random()
            graph.add_edge(all_nodes[i], all_nodes[j], weight=weight)

    print(f"Graph: {graph.number_of_nodes()} nodes - {graph.number_of_edges()} edges ")

    filename_edgelist = 'graph_edgelist.txt'
    nx.write_weighted_edgelist(graph, filename_edgelist)

    graph = nx.read_weighted_edgelist(filename_edgelist)

    print(f"Graph: {graph.number_of_nodes()} nodes - {graph.number_of_edges()} edges ")

**Comment by zzpmarco** [comment]
Sorry, uses these files instead.

BTW, the same behavior reproduces event with python 3.8 and networkx 3.0

[graph_with_tuples_rw.py.txt](https://github.com/networkx/networkx/files/10897665/graph_with_tuples_rw.py.txt)
[graph_edgelist.txt](https://github.com/networkx/networkx/files/10897667/graph_edgelist.txt)

**Comment by dschult** [comment]
The trouble here is that the string representation of the nodes include the delimiter (a space by default).  Note that the string representation of a string with spaces in it will include quotes and thus not cause delimiter troubles even with the default delimiter.

The fix is to assign a delimiter that doesn't occur in the string representation of the nodes.  For example:
```python
nx.write_weighted_edgelist(graph, filename_edgelist, delimiter="|")

graph = nx.read_weighted_edgelist(filename_edgelist, delimiter="|")
```

**Comment by Qudirah** [comment]
@dschult This issue is solved, right?

**Comment by zzpmarco** [comment]
Sorry, I haven't had time to check yet: in the meantime I took a 
different road.
Thank you anyway, yes we cab deem it closed.

- Marco

**Comment by Qudirah** [comment]
@MridulS @dschult please close the issue
