### ISSUE TITLE
Exclude matplotlib from default requirements

### ISSUE THREAD

**Issue by LukeWeidenwalker** [networkx/networkx#6469]
For non-interactive applications that don't ever need to plot anything, it would be useful to exclude the `matplotlib` dependency from the `default` set of dependencies and expose it through something like `pip install networkx[draw]` to opt-in instead. 

Would you be open to consider this as an enhancement? If so, I'd be happy to contribute a PR!

PS: In terms of previous discussions, I've only found [this issue](https://github.com/networkx/networkx/issues/1325), but this is 8 years old and was closed 3 years ago.

**Comment by MridulS** [comment]
We do not have any core dependency. If someone uses pip install networkx they will only get networkx. Users need to opt into install the "default" dependencies.

**Comment by MridulS** [comment]
I see in the linked project "default" is present in pyproject.toml while requiring networkx.

Unless the package requires the scipy/numpy/pandas parts of networkx, it should work just fine on plain networkx without any extras. If it does depend on numpy/scipy, the package can independently install that package. NetworkX should work just fine with the latest scipy/numpy/pandas installed independently of networkx.

**Comment by LukeWeidenwalker** [comment]
Ohhh - apologies, then I misunderstood how the `default` extra already works! Thanks a lot for the clarification! :)
