### ISSUE TITLE
Add examples for graph algorithms 

### ISSUE THREAD

**Issue by PurviChaurasia** [networkx/networkx#6482]
Currently `examples/algorithm` covers a limited scope of examples of various graph algorithms. It would be better to further incorporate the wide variety of graph algorithms at our disposal.

**Comment by PurviChaurasia** [comment]
@MridulS I'll be working on this issue. I'll let you know in a while which algorithms I shall be implementing.

**Comment by PurviChaurasia** [comment]
@MridulS @paulitapb Kindly review this PR

**Comment by rossbar** [comment]
Adding examples to the gallery is always welcome. Since this issue doesn't relate to anything specific I'll go ahead and close it so we can keep discussions focused in the corresponding PRs.

**Comment by PurviChaurasia** [comment]
Sure, thanks!
