### ISSUE TITLE
`nx_pydot.read_dot` method inserting undefined node

### ISSUE THREAD

**Issue by rkrishnasanka** [networkx/networkx#6485]
When I run the `nx_pydot.read_dot()` command, it adds a node named `'\\n'` into the graph.

### Current Behavior

Currently when I run the following snippet:

```python
ref_graph = networkx.drawing.nx_pydot.read_dot(Path("test.dot")
print(list(ref_graph.nodes))
```
We get the following results:
```
['\\n', 'in1', 'in1_METER_(%)_60', 'in2', 'base_droplets_MIX_(+)_in2_61', 'base_droplets', 'injected_droplets', 'injected_droplets_PROCESS_(~)_62', 'incubated_droplets', 'discarded_droplets_SIEVE_(-)_incubated_droplets_63', 'sorted_droplets', 'out1', 'discarded_droplets', 'out2', 'val_1']
```
### Expected Behavior

```
['in1', 'in1_METER_(%)_60', 'in2', 'base_droplets_MIX_(+)_in2_61', 'base_droplets', 'injected_droplets', 'injected_droplets_PROCESS_(~)_62', 'incubated_droplets', 'discarded_droplets_SIEVE_(-)_incubated_droplets_63', 'sorted_droplets', 'out1', 'discarded_droplets', 'out2', 'val_1']
```

### Environment

Python version:
NetworkX version: 2.8.8

### Additional context

test.dot
```dot
strict digraph "" {
	in1 -> "in1_METER_(%)_60";
	in2 -> "base_droplets_MIX_(+)_in2_61";
	base_droplets -> "base_droplets_MIX_(+)_in2_61";
	injected_droplets -> "injected_droplets_PROCESS_(~)_62";
	incubated_droplets -> "discarded_droplets_SIEVE_(-)_incubated_droplets_63";
	sorted_droplets -> out1;
	discarded_droplets -> out2;
	"in1_METER_(%)_60" -> base_droplets;
	val_1 -> "in1_METER_(%)_60";
	"base_droplets_MIX_(+)_in2_61" -> injected_droplets;
	"injected_droplets_PROCESS_(~)_62" -> incubated_droplets;
	"discarded_droplets_SIEVE_(-)_incubated_droplets_63" -> sorted_droplets;
	"discarded_droplets_SIEVE_(-)_incubated_droplets_63" -> discarded_droplets;
}
```

**Comment by navyagarwal** [comment]
Based on the discussion over [here](https://github.com/networkx/networkx/issues/5723), I gather that the pydot package has issues and is not actively maintained. Consider using nx.nx_agraph.read_dot instead.

**Comment by rkrishnasanka** [comment]
@navyagarwal  yeah it seems like there was a warning tucked in somewhere in the stdout that I missed when debugging. I ended up using `nx_agraph` instead and I was able to continue.

**Comment by MridulS** [comment]
I have seen this issue before and this does come from pydot if I remember correctly (not able to quickly find a link right now), and as @navyagarwal pointed it's recommended to use pygraphviz instead for now.

Thanks for reporting it! I'll close the issue for now.
