### ISSUE TITLE
Join operation in trees---not handling label_attribute

### ISSUE THREAD

**Issue by sirichandana-v** [networkx/networkx#6488]
[https://github.com/networkx/networkx/blob/main/networkx/algorithms/tree/operations.py](https://github.com/networkx/networkx/blob/main/networkx/algorithms/tree/operations.py)
1. The resulting graph of join operation in trees isn't including the old labels of inputs.
2.  Not handling the cases where label_attribute is passed as an argument.

### Current Behavior
![Screenshot from 2023-03-11 17-03-33](https://user-images.githubusercontent.com/88175932/224483929-b1ebff93-2e5e-46a6-9c6e-11de1dc53ca1.png)

### Expected Behavior

![image](https://user-images.githubusercontent.com/88175932/224484244-9e9653fe-2aa8-4f02-9bee-39942a2ab08f.png)

### Steps to Reproduce
As shown above

### Environment

Python version: 3.10.6
NetworkX version: 3.0

### Additional context
[https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.tree.operations.join.html](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.tree.operations.join.html)

**Comment by sirichandana-v** [comment]
Can I take up this issue. I figured out that 
1. we are unnecessarily removing old node labels in the code. Deleting this part can retain old labels.
2. using "label_attribute" instead of the "_old" can solve the second issue

**Comment by rossbar** [comment]
There's definitely something strange going on with `label_attribute`. The docstring does indeed make it seem like the labels of the original graphs are stored as attributes in joined graph, but that's clearly not the case. This feels like a bug to me, but I don't know enough about the join operation to say whether this was intentional. The first step should be to determine what the behavior actually should be before we go about trying to change it!

**Comment by rossbar** [comment]
FWIW here's a minimal example of the current behavior:

```python
>>> G = nx.path_graph(3)
>>> H = nx.path_graph(3)
>>> joined = nx.join([(G, 1), (H, 1)])  # Joining at the "middle" node of the path
>>> joined.nodes(data=True)
NodeDataView({1: {}, 2: {}, 3: {}, 4: {}, 5: {}, 6: {}, 0: {}})
```

I would've expected the node attributes from the last line to have one attribute with key `"_old"` and the value set to what the node value was in the original graph.
