### ISSUE TITLE
Deployment workflow for development docs is broken

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#6492]
The deploy action passes after merges in this repo, but we get an error from `gh-pages` in the `networkx/documentation` repo stating that the gh-pages build fails due to not being able to find `reference.pdf`. Here's the full error text:

```
The page build failed for the `gh-pages` branch with the following error:

Site contained a symlink that should be dereferenced: /networkx-1.0.1/networkx_reference.pdf. For more information, see https://docs.github.com/github/working-with-github-pages/troubleshooting-jekyll-build-errors-for-github-pages-sites#config-file-error.

For information on troubleshooting Jekyll see:

  https://docs.github.com/articles/troubleshooting-jekyll-builds
```

This is definitely related to #5572 . I wasn't immediately able to chase down the right fix so I figured I'd open an issue for visibility.

**Comment by BenFaruna** [comment]
I am an outreachy intern and I am interested in taking on this issue. Can it be assigned to me please

**Comment by MridulS** [comment]
@BenFaruna there is no need to get any issue assigned :)
If you are interested in it you can start working on the issue (you can just write a comment that you are working on it), this issue will involve looking at the documentation pipeline and our sphinx builds, so it could be a bit complicated to start with, but please do look into it!

**Comment by BenFaruna** [comment]
@MridulS thank you
I will do my best

**Comment by jarrodmillman** [comment]
@rossbar I am not sure this is related to not making the PDFs. That should impact networkx-1.0.1 and it looks like everything worked fine for that PR: https://github.com/networkx/documentation/runs/11676885185

**Comment by jarrodmillman** [comment]
I think this is the issue: https://github.blog/changelog/2023-02-21-github-pages-deprecating-symlinks-in-non-actions-builds/

The problem started for us right after Feb. 28th.

**Comment by jarrodmillman** [comment]
Yes, that looks like it is it:
![screenshot](https://user-images.githubusercontent.com/123428/225223417-0c899a84-f4f2-48d0-a47f-d3068a4b5e63.png)

We are deploying from a branch and on February 28th GH pages stopped supporting symlinks in non-action builds.

**Comment by dschult** [comment]
I'm not sure if this is related, but I'm getting a circle-ci workflow error message:
[https://github.com/networkx/networkx/actions/runs/4450093865](https://github.com/networkx/networkx/actions/runs/4450093865)

The error is basically:
```
##[debug]Fetching JSON: https://circleci.com/api/v2/project/gh/networkx/networkx/9388/artifacts
##[debug]Successfully read CircleCI API token
##[debug]Artifacts JSON:
##[debug]{"message":"Bad request."}
Error: Cannot read properties of undefined (reading 'length')
```

**Comment by MridulS** [comment]
Just putting this here, the circle-ci issue was unrelated and was resolved.
