### ISSUE TITLE
k_truss function does not raise NetowrkX exception in case of self loops in graphs

### ISSUE THREAD

**Issue by PurviChaurasia** [networkx/networkx#6508]
This issue is in reference to the discussion #6500.

In the `k_truss` function in `networkx/algorithms/core.py` it is mentioned that the function doesn't work for graphs containing self loops. However, having tried a few cases on my own behalf, I realised that it is actually giving output for graphs with self loops.

### Current Behavior

`k_truss` function doesn't raise an error for a graph containing self loops. 

![image](https://user-images.githubusercontent.com/97350598/225336620-08036fb4-6dbd-4fbd-aacb-4ac129982bc6.png)

### Expected Behavior

The documentation mentions that `k_truss` raises `NetworkX` error for graphs containing self loops.
<img width="447" alt="image" src="https://user-images.githubusercontent.com/97350598/225338267-eba0c2b2-67ce-4f43-b3ae-7ad3f8c1e2f5.png">

### Steps to Reproduce

Fix the documentation and mention in notes, reason as to why `k_truss` can handle graphs with self loops.

**Comment by PurviChaurasia** [comment]
#6501 covers this issue almost completely. Will make minor changes after it gets merged.

**Comment by PurviChaurasia** [comment]
@dschult Could you please clarify as to _why_ `k_truss` function doesn't work for graphs with self loops? Because I am unable to understand that part fully.

**Comment by dschult** [comment]
Hmmm...   Selfloops are such a crazy corner case...   
The `k_truss` function does "work" when selfloops are present. I mean it returns an induced subgraph with one definition of the right property.  But it might not match what people expect. The code ensures that every edge in the induced subgraph has k-2 nodes that are connected to the two nodes on the end of the edge. That normally implies that the edge participates in k-2 triangles within this induced subgraph. And the standard definition of a k_truss is that it counts the triangles an edge participates in.

But with selfloops, the two nodes at the end of the selfloop edge are the same!  So every neighbor of the node with a selfloop is a neighbor of both ends of the selfloop edge.  Does this count as a triangle? u - v - u and back to u along the selfloop edge is a strange triangle.  But it does fulfill the property that the edge has a shared neighbor between the two ends of the edge(!!).  It reminds me of the question: if one angle of a triangle has angle measure 0-degrees then is it a triangle? One edge has length 0 and the other two are really the same edge. There's no good answer.

I guess that means we could say that the returned subgraph is a k_truss as long as you are willing to count triangles generously.  But I prefer the approach that we should **not** be counting these self-loop paths as triangles.  What do you think?

If we go with the standard definition/intuition of what a triangle is, then the documentation could be changed.
I would prefer to say that the results are potentially confusing if the graph G has selfloops. So, update the current language about not implemented for directed graphs or multigraphs (take out the parallel edges in favor of the term multigraphs). Then add a sentence saying that if G has selfloop edges, the results may give surprising results. 

But I think a maybe better solution would involve raising an exception when self-loops are present. You can check if selfloops are present using `if G.number_of_selfloops() > 0:`  or if you prefer: `if any(n in nbrs for n, nbrs in G.adj.items()):`  Then raise a `nx.NotImplementedError` with a message saying the function doesn't work with selfloops.

So -- we need to choose between backward compatibility by updating the docs to explain that selfloops will give an answer that might be confusing. Or change the code (making it not backward compatible) to raise an exception when G contains selfloops.

**Comment by rossbar** [comment]
> Or change the code (making it not backward compatible) to raise an exception when G contains selfloops.

My sense is that raising in this case is an improvement if it cuts down on "silently unexpected" results. The fact that it's straightforward to either filter or remove self-loop edges means we're not *removing* any features, just making the requirements a little more strict!

**Comment by PurviChaurasia** [comment]
I agree @rossbar @dschult I will add the condition to the function itself to handle this rather tricky case. I think it's better to make the function itself more restrictive than to leave space for unexpected results. @dschult Thanks a lot for that amazing explanation! Made the reason crystal clear :)
