### ISSUE TITLE
Add knot algorithm (migrated from Trac #663)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#651]
Original ticket https://networkx.lanl.gov/trac/ticket/663
Reported 2011-12-07 by rachel.bobbins, assigned to @hagberg.

A knot in a directed graph is a collection of vertices and edges with the property that every vertex in the knot has outgoing edges, and all outgoing edges from vertices in the knot terminate at other vertices in the knot. 

There should be an algorithm that detects whether a knot exists in a directed graph.

**Comment by kshitij10496** [comment]
@hagberg 
I would like to work on this.
Do you find this document relevant. [[Link]](http://www.cs.utexas.edu/users/misra/scannedPdf.dir/KnotDetection.pdf)

**Comment by OrkoHunter** [comment]
@kshitij10496 You can start from here https://networkx.lanl.gov/trac/attachment/ticket/663/knot.py

**Comment by jfinkels** [comment]
The original comment is a little unclear. The paper linked by @kshitij10496 states

> A vertex *u* in a directed graph is in a *knot* if for every vertex *v* reachable from *u*, *u* is reachable from *v*.

Another way to express this seems to be that a strongly connected component is a knot if it has no outgoing edges on its boundary. So I propose the following algorithm. Please correct me if this seems wrong.

```python
def knots(G):
    for S in nx.strongly_connected_components(G):
        try:
            next(nx.boundary(G, S))
        except StopIteration:
            yield S
```

**Comment by hagberg** [comment]
Closed due to inactivity.
