### ISSUE TITLE
Add a quickstart guide/option to use github codespaces to our developer docs?

### ISSUE THREAD

**Issue by MridulS** [networkx/networkx#6531]
Currently our developer docs only cover using local installs/developer env setup. Should we also look into supporting github codespaces? It can help interested new contributors, especially for quick doc changes or during sprints.

**Comment by MridulS** [comment]
This first requires a conversation with the developer community itself. Please don't start working on this just yet :)

**Comment by Richiio** [comment]
Hi @MridulS, I would love to know the feedback from the dev team

**Comment by jarrodmillman** [comment]
i would prefer becoming less dependent on GitHub rather than adopting more of their technologies. They are likely to pull the rug out from under us once they get whatever they want from us.
