### ISSUE TITLE
Random expander

### ISSUE THREAD

**Issue by fcrozatier** [networkx/networkx#6541]
### Discussed in https://github.com/networkx/networkx/discussions/6494

<div type='discussions-op-text'>

<sup>Originally posted by **fcrozatier** March 12, 2023</sup>
There is no utility function to generate a random [expander](https://en.wikipedia.org/wiki/Expander_graph) graph. I could fill a PR if there is interest.

Suggestion: It has been [proved](https://arxiv.org/pdf/cs/0405020.pdf) that a random k-regular graph made of k/2 distinct permutations (k even) on {1,...,n} has probabilty $1 − O(n^{-τ})$ of being an expander, where $\tau$ is computable. 
We could add a utility `maybe_expander(n,k)` that returns such a graph and the probability of it being an expander. For engineers this utility would be enough. 

For mathematicians we could add an `is_regular_expander` utility and a slower `random_expander(n,k)` that loops over `maybe_expander` while not `is_regular_expander`. The `is_regular_expander` utility would be based on [Cheeger inequalities](https://en.wikipedia.org/wiki/Expander_graph#Cheeger_inequalities) for k-regular graphs (and the `is_regular` utility)</div>

I could work on this, let me know.

**Comment by rossbar** [comment]
FWIW there exists the [expanders module](https://github.com/networkx/networkx/blob/main/networkx/generators/expanders.py). Perhaps this (and existing functionality) is relevant to the discussion?

**Comment by ayajnik** [comment]
Is this still active or can I take this up? @rossbar

**Comment by rossbar** [comment]
At this stage I'd say there isn't really a concrete plan for path forward, though if you have one that fits within the wider context of the expanders module then please feel free to add to the discussion!

**Comment by fcrozatier** [comment]
@rossbar I would say that the [expander generators](https://networkx.org/documentation/stable/reference/generators.html#module-networkx.generators.expanders) do not address the need since they are based on explicit constructions of expanders and give graphs only of sizes $n^2$ or $p$ prime. The idea here is to propose a utility to return random regular expanders (with good probability) of any size and degree (even).

**Comment by dschult** [comment]
This seems like a good addition to NetworkX. And the expanders module is a good place. The proposed names look reasonable except I would like "regular" to be included in `maybe_regular_expander` and `random_regular_expander`.
