### ISSUE TITLE
`.number_of_edges()` method returns only zero when calling it inside a child class of `nx.Graph`

### ISSUE THREAD

**Issue by com3dian** [networkx/networkx#6546]
### Current Behavior

Hi maintainers, I'm using `networkx` and wish to define a child class of `nx.Graph()` and use it on my own algorithms. I wrote the `self.__init__` method for the child class like this:
```{python}
	def __init__(self, incoming_graph_data = None, **attr):
		super().__init__(incoming_graph_data, **attr)
		self.num_edges = self.number_of_edges()
```
and I expect the `self.num_edges` should be the actual number of edges in this graph. However it turns out to be 0 all the time.

### Expected Behavior

`self.num_edges` should be the number of edges in the graph, instead of 0.

### Steps to Reproduce

```
import networkx as nx

class child_graph(nx.Graph):
    def __init__(self, incoming_graph_data = None, **attr):
        super().__init__(incoming_graph_data, **attr)
        self.num_edges = self.number_of_edges()
		
if __name__ == '__main__':
    G = child_graph()
    G.add_edges_from([(0, 1), (1, 2)])
    print('number of edges: ', G.num_edges)
    print('number of edges: ', G.number_of_edges())
    print('edges: ', G.edges())
```
**output**:
```
number of edges:  0
number of edges:  2
edges:  [(0, 1), (1, 2)]
```

### Environment

Python version: `Python 3.11.2`
NetworkX version: `'3.0'`

### Additional context

None.

**Comment by rossbar** [comment]
You are setting the `num_edges` attribute only once at construction time, so it is reflecting the number of edges at the time the graph was constructed. In your `__main__`, the number of edges at instantiation is 0, but then you add edges afterwards which is reflected in the `number_of_edges` *method*, but not your custom static attribute. If you want the `num_edges` attribute to track the current state, consider using a `property` instead (or simply rely on the built-in `number_of_edges` method, which already does this).

Either way, this is not a NetworkX bug, but a feature of the Python object model so I will close this.

**Comment by com3dian** [comment]
Oh my bad for didn't seeing this, thank you 👍 !
