### ISSUE TITLE
Layout of website page for ISMAGS needs fixing

### ISSUE THREAD

**Issue by navyagarwal** [networkx/networkx#6547]
The website documentation page for [ISMAGS algorithm](https://networkx.org/documentation/stable/reference/algorithms/isomorphism.ismags.html) is not rendering properly. The layout of components is messed up.

<img width="959" alt="image" src="https://user-images.githubusercontent.com/82928853/227500999-8a7f51a5-f04e-41b1-9c0c-b17e9be9b3dc.png">

<img width="960" alt="image" src="https://user-images.githubusercontent.com/82928853/227501167-c14302bd-9b80-4139-9a6a-95d1bd4e8b0b.png">

**Comment by rossbar** [comment]
This looks like a bad interaction between sphinx extensions and the pydata-sphinx-theme. My guess is that one or more of `numpydoc` or `sphinx-autodoc` is mis-identifying some sections from the module docstring which is screwing up the heading levels/object tags for the rest of the docstring.

This should likely be fixed upstream, though we'll need to figure out which sphinx extension is behaving badly. In the mean time we can probably use a simple workaround to fix the docs.
