### ISSUE TITLE
Add Lowest Common Ancestor Example 

### ISSUE THREAD

**Issue by vanshika230** [networkx/networkx#6550]
The current examples/algorithm only has a small selection of examples for different graph algorithms. It would be preferable to incorporate more of the many different graph algorithms we have available.
I have created a python script to create a binary tree with 8 nodes and perform various operations related to finding the lowest common ancestor (LCA) of nodes in the tree and visualizes it. It briefly uses all the functions mentioned here https://networkx.org/documentation/latest/reference/algorithms/lowest_common_ancestors.html. 
Output is as follows :- 
![1](https://user-images.githubusercontent.com/74042272/227709635-46d5dbc8-9017-4500-874e-a3195b2e47e9.png)
![2](https://user-images.githubusercontent.com/74042272/227709834-886d09c5-ff13-44c2-9e1c-e1ba7eb1ef93.png)
![3](https://user-images.githubusercontent.com/74042272/227709653-316a980d-7614-4d75-a43b-d0a662073df1.png)

**Comment by navyagarwal** [comment]
@vanshika230 Hey, I created a [PR](https://github.com/networkx/networkx/pull/6542) for LCA example too a couple of days back. Just wanted to let you know! If it's something different that you're working on, I apologize :)

**Comment by rossbar** [comment]
See also: #6542

**Comment by rossbar** [comment]
Closing as completed by #6542
