### ISSUE TITLE
triangles, clustering coefficent for directed graphs (migrated from Trac #669)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#657]
Original ticket https://networkx.lanl.gov/trac/ticket/669
Reported 2012-01-02 by unknown, assigned to @hagberg.

based on Newmann book Networks: An Introduction (2010) one can count triangles see chapter 7.9 : "It is however possible to generalize transitivity to take account of directed links. If we have a directed relation between vertices such as “u likes v” then we can say that a triple of vertices is closed or transitive if u likes v, v likes w, and also u likes w. (Note that there are many distinct ways for such a triple to be transitive, depending on the directions of the edges. The example given here is only one of six different possibilities.) One can calculate a clustering coefficient or fraction of transitive triples in the obvious fashion for the directed case, counting all directed paths of length two that are closed and dividing by the total number of directed paths of length two."

**Comment by dschult** [comment]
Fixed in #2943
