### ISSUE TITLE
laplacian_centrality not working for graphs with single nodes

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#6571]
### Discussed in https://github.com/networkx/networkx/discussions/6565

<div type='discussions-op-text'>

<sup>Originally posted by **PurviChaurasia** March 28, 2023</sup>
If I add a single node the graph, the `laplacian_centrality` function returns an error state which I'm unable to understand. Can someone help me out with this?
Code - 
```
G = nx.Graph()
G.add_node(0)
nx.laplacian_centrality(G)
```

```
---------------------------------------------------------------------------
error                                     Traceback (most recent call last)
Cell In[15], line 3
      1 G = nx.Graph()
      2 G.add_node(0)
----> 3 nx.laplacian_centrality(G)

File [d:\outreachy\networkx\networkx\networkx\algorithms\centrality\laplacian.py:129](file:///D:/outreachy/networkx/networkx/networkx/algorithms/centrality/laplacian.py:129), in laplacian_centrality(G, normalized, nodelist, weight, walk_type, alpha)
    126 new_diag = lap_matrix.diagonal() - abs(lap_matrix[:, i])
    127 np.fill_diagonal(A_2, new_diag[all_but_i])
--> 129 new_energy = np.power(sp.linalg.eigh(A_2, eigvals_only=True), 2).sum()
    130 lapl_cent = full_energy - new_energy
    131 if normalized:

File [d:\Outreachy\NetworkX\networkx-dev\lib\site-packages\scipy\linalg\_decomp.py:561](file:///D:/Outreachy/NetworkX/networkx-dev/lib/site-packages/scipy/linalg/_decomp.py:561), in eigh(a, b, lower, eigvals_only, overwrite_a, overwrite_b, turbo, eigvals, type, check_finite, subset_by_index, subset_by_value, driver)
    558         lwork_args = {'lwork': lw}
    560     drv_args.update({'lower': lower, 'compute_v': 0 if _job == "N" else 1})
--> 561     w, v, *other_args, info = drv(a=a1, **drv_args, **lwork_args)
    563 else:  # Generalized problem
    564     # 'gvd' doesn't have lwork query
    565     if driver == "gvd":

error: (il>=1&&il<=n) failed for 6th keyword il: dsyevr:il=1
```

Since this will create a laplacian matrix with a single node = 0, shouldn't the centrality be 0?
p.s. I might be going completely wrong somewhere :)</div>

**Comment by PurviChaurasia** [comment]
Thanks for creating the issue! @rossbar

**Comment by PurviChaurasia** [comment]
I'll be looking into it and will let you know what I find. Will add a PR shortly :)

**Comment by PurviChaurasia** [comment]
Hi, yes you're absolutely right @Qudirah However, in normal cases laplacian centrality _should_ be defined for matrices with singular nodes. We'll have to come up with a way for that. That's what was covered in the discussion with @dschult and @rossbar.

**Comment by PurviChaurasia** [comment]
I'm still working on it, extremely sorry for the delay :)

**Comment by Qudirah** [comment]
> Hi, yes you're absolutely right @Qudirah However, in normal cases laplacian centrality _should_ be defined for matrices with singular nodes. We'll have to come up with a way for that. That's what was covered in the discussion with @dschult and @rossbar.

oh! Thanks for the explanation.
