### ISSUE TITLE
Improve test coverage for connected.py

### ISSUE THREAD

**Issue by Qudirah** [networkx/networkx#6572]
There are a few red lines I want to work on in https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/algorithms/approximation/connectivity.py.

My issue is I can't import the modified bidirectional_shortest_path function in the connectivity.py file. The one in the shortest_path/unweighted.py does not have the exclude argument. To write the test cases, I need to access the function somehow. What am I missing? @MridulS @dschult @rossbar Also I don't know if that is why the doc examples of the function are missing in the doc, but I will like to work on that too.

**Comment by MasterC4t** [comment]
+1

**Comment by rossbar** [comment]
The functions that are prefixed with an underscore (`_`) are "private" by convention; i.e. they are not intended for direct use by users. Thus they are intentionally left out of the API documentation.

Internal functions like this are often intended only for use in the module in which they're defined, so they are typically only accessible by that module. For example, if you wanted to access `_bidirectional_pred_succ` you'd do something like `from networkx.algorithms.approximation.connectivity import _bidirectional_pred_succ`.
