### ISSUE TITLE
Improve test coverage for clique.py

### ISSUE THREAD

**Issue by Qudirah** [networkx/networkx#6574]
There is a line left uncovered in https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/algorithms/approximation/clique.py and I am looking into it. There is a bit of an issue though when I try G = None. An attribute error is raised not a value error. 

Steps to Reproduce

from networkx.algorithms.approximation.clique import maximum_independent_set,max_clique
G=nx.Graph()
G.add_nodes_from([(2,3),(5,6),(3,6)])
max_clique(G=None)

output:

AttributeError                            Traceback (most recent call last)
Cell In[84], line 1
----> 1 max_clique(G)

File <class 'networkx.utils.decorators.argmap'> compilation 32:3, in argmap_max_clique_28(G)
      1 import bz2
      2 import collections
----> 3 import gzip
      4 import inspect
      5 import itertools

File ~\anaconda3\lib\site-packages\networkx\utils\decorators.py:83, in not_implemented_for.<locals>._not_implemented_for(g)
     82 def _not_implemented_for(g):
---> 83     if (mval is None or mval == g.is_multigraph()) and (
     84         dval is None or dval == g.is_directed()
     85     ):
     86         raise nx.NetworkXNotImplemented(errmsg)
     88     return g

AttributeError: 'NoneType' object has no attribute 'is_multigraph'

**Comment by Qudirah** [comment]
@MridulS @rossbar @dschult

**Comment by rossbar** [comment]
In this case I think we can safely delete the check in L109-110. I don't think it's possible to hit that due to the `not_implemented_for` decorator. Even if it were hit-able, it's a pretty trivial input validation that I think can be safely removed.
