### ISSUE TITLE
The greedy_coloring function strategy_connected_sequential is not behaving well

### ISSUE THREAD

**Issue by Qudirah** [networkx/networkx#6606]
I was trying to work on improving the test coverage of the greedy_coloring algorithm but something weird is happening. This code is running just fine without raising the NetworXError eve though the traversal argument isn't "bfs" or "dfs". What did I do wrong? Is this a bug?

`G = nx.Graph()`
`G.add_edges_from([(0, 1), (0, 2), (0, 3)])`
`coloring = {0: 0, 1: 1, 2: 2, 3: 3}`
`strategy_connected_sequential(G,traversal="lol",colors=coloring)`

**Comment by Qudirah** [comment]
It returns a graph object when I run it. 
`<generator object strategy_connected_sequential at 0x000001C116238C80>`

**Comment by Qudirah** [comment]
`G = nx.Graph()`
`G.add_nodes_from([1, 2, 3])`
`G.add_edge(1, 2)`
`colors = {1: 'red', 2: 'red',3:'red'}`
`strategy_saturation_largest_first(G, colors)`

same thing with this even though there should be this error
`raise nx.NetworkXError("Neighboring nodes must have different colors")`

Am I doing something wrong?

**Comment by rossbar** [comment]
The`strategy_*` objects are actually *generators* - in other words when you "call" `strategy_connected_sequential` it will return a generator object that will yield values when iterated over. To actually hit the code path, you have to request a value from the generator - one simple way of doing so is `next(my_generator)`.

**Comment by Qudirah** [comment]
> The`strategy_*` objects are actually _generators_ - in other words when you "call" `strategy_connected_sequential` it will return a generator object that will yield values when iterated over. To actually hit the code path, you have to request a value from the generator - one simple way of doing so is `next(my_generator)`.

Thank you. will fix that now.

**Comment by rossbar** [comment]
Hopefully the original question was sufficiently answered - if not please feel free to follow up.
