### ISSUE TITLE
Improve test coverage for summarization.py

### ISSUE THREAD

**Issue by Qudirah** [networkx/networkx#6609]
There are a few red lines in https://app.codecov.io/gh/networkx/networkx/blob/main/networkx/algorithms/summarization.py and I want to get rid of those lines. :)

will attach a PR soon.

**Comment by rossbar** [comment]
Hi @Qudirah - there's no need to open an individual issue for each instance where coverage is not 100%. Doing so decreases the "signal-to-noise" level on the issue tracker, not to mentions sending an email to the 281 people who watch the repository every time a new issue is opened! Code coverage is generally an open-ended potential improvement, so there's not a lot to be gained by highlighting the individual instances.

Please feel free to keep working on improving coverage! I'm going to go ahead and clean up some of the issues though.

**Comment by Qudirah** [comment]
> Hi @Qudirah - there's no need to open an individual issue for each instance where coverage is not 100%. Doing so decreases the "signal-to-noise" level on the issue tracker, not to mentions sending an email to the 281 people who watch the repository every time a new issue is opened! Code coverage is generally an open-ended potential improvement, so there's not a lot to be gained by highlighting the individual instances.
> 
> Please feel free to keep working on improving coverage! I'm going to go ahead and clean up some of the issues though.

oh. That is understood. if i keep working on them, on what issue do I attach the PR though?

**Comment by rossbar** [comment]
> oh. That is understood. if i keep working on them, on what issue do I attach the PR though?

There is no requirement that every PR have a corresponding issue. A clear, concise summary in the PR description is enough!
