### ISSUE TITLE
Cannot import name '_dispatch' from 'networkx.classes'

### ISSUE THREAD

**Issue by Grufoony** [networkx/networkx#6624]
import scipy as sp
        import numpy as np
        import sys
        import seaborn as sns
        import matplotlib.pyplot as plt
        import networkx as nx

### Current Behavior

        ---------------------------------------------------------------------------
        ImportError                               Traceback (most recent call last)
        Cell In[24], line 6
              4 import seaborn as sns
              5 import matplotlib.pyplot as plt
        ----> 6 import networkx as nx
        
        File [~/.local/lib/python3.10/site-packages/networkx/__init__.py:24](https://vscode-remote+wsl-002bubuntu-002d22-002e04.vscode-resource.vscode-cdn.net/home/grufoony/physics_unibo/src/Complex_Networks/~/.local/lib/python3.10/site-packages/networkx/__init__.py:24)
             22 from networkx.classes import filters
             23 from networkx.classes import *
        ---> 24 from networkx.classes import _dispatch
             26 from networkx import convert
             27 from networkx.convert import *
        
        ImportError: cannot import name '_dispatch' from 'networkx.classes' (/usr/lib/python3/dist-packages/networkx/classes/__init__.py)

### Expected Behavior

Correct import

### Environment

WIN 10 - WSL2 - Ubuntu 22.04.1

Python version: 3.10.6 (Jupyter Notebook kernel)
NetworkX version: 3.1

You can also see [here](https://github.com/Grufoony/Physics_Unibo/blob/main/src/Complex_Networks/ER_networks.ipynb)

**Comment by MridulS** [comment]
Hmm, I just tested with a clean python 3.10.6 + networkx 3.1 environment. But I can't reproduce this.

Did this behavior emerge after the update to NetworkX 3.1?

**Comment by Grufoony** [comment]
It's been a lot since I used networkx.
However, the error seems to appear only on jupyter notebook and not on python standalone

**Comment by rossbar** [comment]
I suspect this is an environment issue - can you run `nx.__version__` inside the notebook to verify you are indeed getting the NetworkX version you expect?

**Comment by Grufoony** [comment]
Ok sorry for the late response.
I tried to uninstall networkx and it worked by i found that i had the also the version 2.4 installed (which i could not remove with pip).
I removed the 2.4 version manually and installed the 3.1 again.
Now it works, thanks for the help!
