### ISSUE TITLE
Handling corner cases in laplacian_centrality

### ISSUE THREAD

**Issue by navyagarwal** [networkx/networkx#6626]
This was first touched upon in #6565 and #6571. But, I think the previous discussion is part of a broader issue in `laplacian_centrality` that needs to be handled.

TLDR; Exceptions should be raised for the two cases - 1. when there are no edges on the graph and 2. when there is a single node in the graph.

The following formula gives the computation for Laplacian Centrality.

$$\begin{align}\begin{aligned}C_L(u_i,G) = \frac{(\Delta E)_i}{E_L (G)} = \frac{E_L (G)-E_L (G_i)}{E_L (G)}\end{aligned}\end{align}$$

$$\begin{align}E_L (G) = \sum_{i=0}^n \lambda_i^2\end{align}$$

From this particular part - 

$$\begin{align}\begin{aligned}C_L(u_i,G) = \frac{E_L (G)-E_L (G_i)}{E_L (G)}\end{aligned}\end{align}$$

It is evident that when the Laplacian energy of G (E<sub>L</sub>(G)) = 0, Laplacian centrality is not defined because of zero division error. 

E<sub>L</sub>(G) = 0 when the eigenvalues of Laplacian matrix of G are all zero i.e. Laplacian matrix is a null matrix. Laplacian matrix of G is a null matrix when there are no edges in G. Currently the `laplacian_centrality` method does not handle this case very well. 

```python
G = nx.Graph()
G.add_nodes_from([3, 4])
nx.laplacian_centrality(G)
```
The following Numpy warning is raised.
```
RuntimeWarning: invalid value encountered in double_scalars
  lapl_cent = lapl_cent / full_energy
```
Output:
```python
{3: nan, 4: nan}
```

I think Laplacian matrix can be null only when there are no edges in the graph (self-loops not counted as edges).

```python
H = nx.Graph()
H.add_nodes_from([1, 2, 3])
H.add_edges_from([(1, 1)])
print(nx.laplacian_matrix(H).toarray())
```
Output:
```python
[[0 0 0]
 [0 0 0]
 [0 0 0]]
```

Thus, NetworkX should raise an exception when a graph with zero edges (ignoring self loops) is passed to the `laplacian_centrality` method.

Also, for the case when there is a single node in the graph, the above condition obviously holds true since there are no edges. But there is another side to it - to compute the `laplacian_centrality` of a node, we also calculate **E<sub>L</sub>(G<sub>i</sub>)** i.e. Laplacian energy of graph G when the node is dropped. When the one and only node of G is dropped, G is now an empty graph and the Laplacian matrix isn't defined on an empty graph.

```python
K = nx.Graph()
print(nx.laplacian_matrix(K).toarray())
```
```
NetworkXError: Graph has no nodes or edge
```

While `laplacian_centrality` already handles the case when there are no nodes in a graph to begin with, a separate exception should be raised for the case when there is a singular node in the graph.

@dschult @rossbar Can you give your inputs on this?

**Comment by aaronzo** [comment]
Agree that your proposals are better than current behaviour, with the note that

> Thus, NetworkX should raise an exception when a graph with zero edges (ignoring self loops) is passed to the laplacian_centrality method.

should only happen if `normalized=True` is requested.

I also wonder if there isn't something clever to be done with identities in cases that are currently undefined. For example, is should be true that

$$ C_L(u, G) = C_L(u, G \cup \{ v \} ) $$

for all $u \in G$ where $v$ is a new, isolated node, because we're adding zero rows/cols to a matrix just adds a 0 eigenvalue and keeps others the same. Thus, it might make sense to add a second, isolated node to a single node graph to obtain a sensible value for the first node - which would be $0$ everytime in the unnormalized case.
