### ISSUE TITLE
have trouble adding multiple edges between two nodes

### ISSUE THREAD

**Issue by cisan86** [networkx/networkx#6685]
when i use the code below I can only get two nodes with one edge , but the output of `print(list(G.edges))` is `[('a', 'b', 0), ('a', 'b', 1), ('a', 'b', 2)]`
```
import networkx as nx
import matplotlib.pyplot as plt

G = nx.MultiGraph()
V = {'a', 'b'}
G.add_nodes_from(V)
G.add_edge('a', 'b')
G.add_edge('a', 'b')
G.add_edge('a', 'b')
print(list(G.edges))
nx.draw(G, with_labels=True, node_size=100)
plt.show()
```
the graph is like 
![image](https://user-images.githubusercontent.com/53175649/236759486-60dc380d-e773-458d-957e-35ee994770d3.png)

It is very kind of you to help me

**Comment by MridulS** [comment]
Hello @cisan86! You are creating a multigraph (multiple edges between two nodes) and currently we don't natively support drawing those edges between two nodes.

**Comment by dschult** [comment]
See also #5882

**Comment by cisan86** [comment]
> Hello @cisan86! You are creating a multigraph (multiple edges between two nodes) and currently we don't natively support drawing those edges between two nodes.
I use this code , and it can do it, 
```python
import networkx as nx
import matplotlib.pyplot as plt

# Create an empty graph
G = nx.MultiGraph()

G.add_edge(1, 2)
G.add_edge(1, 2)
G.add_edge(1, 2)
G.add_edge(1, 2)


pos = nx.spring_layout(G)
nx.draw_networkx_nodes(G, pos, node_size=0.1)


ax = plt.gca()
for e in G.edges:
    # matplotlib.pyplot.annotate有Simple arrow和Fancy arrow
    ax.annotate("",
                xy=pos[e[0]], xycoords='data',
                xytext=pos[e[1]], textcoords='data',
                arrowprops=dict(arrowstyle="-",
                                shrinkA=0.1, shrinkB=0.1,
                                patchA=None, patchB=None,
                                connectionstyle="arc3,rad=rrr".replace('rrr', str(0.1 * e[2])),
                                linewidth=0.05
                                ),
                )



# Display the graph
plt.axis('off')
plt.savefig("all_txns2.svg")
plt.show()
```
and i get this image, but When I set the nodesize very small, the nodes I get are hollow circles with a dot in the middle, I want to remove the outer ring.  It seems to be the porblems of the function `nx.draw_networkx_nodes`
![image](https://user-images.githubusercontent.com/53175649/237010337-1aed4575-ae2d-4f93-b64f-20ecc75ebdbd.png)

**Comment by cisan86** [comment]
> The nodes might be oitlines with linewidth 1. Try setting linewidth to something small in draw_networkx_nodes? (untested)
> 
> ```python
> nx.draw_networkx_nodes(G,  pos, node_size=0.1, linewidths=0.1)
> ```

**this works for me , thanks !**
