### ISSUE TITLE
Inconsistent order of .edges()

### ISSUE THREAD

**Issue by amaissen** [networkx/networkx#6699]
### Current Behavior

The order of the edges returned by `.edges()` is not ordered

### Expected Behavior

As networkx graphs are build around python dict, I would expect that the output of `.edges()` is ordered.

### Steps to Reproduce

```
  edges1 = list(sorted([(0, 1), (0, 3), (1, 0), (1, 2), (2, 1), (2, 3), (3, 2), (3, 0)]))
  g1 = nx.DiGraph(edges1)
  print(edges1 == list(g1.edges)) # gives False
  
  edges2 = list(sorted([(0, 1), (0, 2), (1, 0), (1, 2), (2, 0), (2, 1), (2, 3), (3, 2)]))
  g2 = nx.DiGraph(edges2)
  print(edges2 == list(g2.edges)) # gives True
```

### Environment

Python version:  3.9.16 
NetworkX version: 3.1

**Comment by MridulS** [comment]
The dictionary underneath is a node to node mapping, the edges are not added as a key in the dictionary. There is no guarantee that `.edges` would be sorted. 

The only guarantee is that the same insertion order will give you the same result.

**Comment by amaissen** [comment]
@MridulS Thank you for the clarification. I thought that `.edges` have the same order as the insertion order, but actually the guarantee is only that `.edges` is deterministic.

**Comment by amaissen** [comment]
@MridulS Are there any stronger guarantees on `.nodes()`?

**Comment by dschult** [comment]
Yes, .nodes() are in the order in which nodes are added to the graph.
Actually the edges also have an order to them based on the node pairs. 
The first node of the edge is reported in the order that nodes were added.
And the second node of each edge is in the order in which that edge was
added among all edges starting at that node.

It is a dict-of-dicts.  dicts are ordered in python by order the key is entered.
The edge (u, v) is added with u as the key to the outer dict and v as the
key to the inner dict pointed to by u. Then when edges are reported we iterate
through the keys `u` of the outer dict and for each one, we iterate through
the keys `v` of the associated inner dict and put them together to yield `(u, v)`. 
That's the order that is the same every time. It is not the order in which the edges
were added, but it is determined by the order in which nodes and edges are added.
