### ISSUE TITLE
Grid_2d_graph and grid_graph problem

### ISSUE THREAD

**Issue by muuusso** [networkx/networkx#6707]
As I understood it, [grid_2d_graph](https://networkx.org/documentation/stable/reference/generated/networkx.generators.lattice.grid_2d_graph.html#networkx.generators.lattice.grid_2d_graph) and [grid_graph](https://networkx.org/documentation/stable/reference/generated/networkx.generators.lattice.grid_graph.html) should generate 2d lattices with coordination number equal to 4. I noticed that, sometimes and randomly, they produce a different graph. 
<img width="856" alt="Screenshot 2023-05-24 at 12 59 40" src="https://github.com/networkx/networkx/assets/22865991/aacd20bd-639a-4aef-b814-38c536e2a863">

As you can see in the figure, I obtain the wrong graph in the first figure, while I obtain the right one in the second figure. As you can see I had to rerun the cell 30 times before running into the pathological case, but it is still a problem since it happens randomly. The same behaviour happens for both *grid_2d_graph* and *grid_graph*.

I'm running python 3.10.10 and the latest version of networkx (3.1)

**Comment by boothby** [comment]
For what it's worth, you can get a nice drawing with the following:

```python
G = nx.grid_2d_graph(2, 3)
pos = dict(zip(G, G))
nx.draw(G, pos=pos)
```

The graph is not changing between the two pictures; only their drawing shows unnecessary edge crossings.  This behavior is expected.

**Comment by muuusso** [comment]
Yeah, I know. I realized it a few minutes after I opened the issue. I was not able to delete it. Thanks anyway
