### ISSUE TITLE
bug in from_pydot with subgraphs (migrated from Trac #685)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#672]
Original ticket https://networkx.lanl.gov/trac/ticket/685
Reported 2012-02-08 by @jseabold, assigned to @hagberg.

The nodes in subgraphs in pydot were not properly traversed. Attached you can find a fix for this. To replicate the problem, you can do run the code found here:

http://www.pastie.org/3338627

As you can see there graph.node does not have the custom attribute information for all the nodes.

You can find a git patch attached that corrects this.

**Comment by Michael-E-Rose** [comment]
Just found this 5 year old ticket.  The link to the code that replicated the bug is dead.  Can someone still replicate the bug?

**Comment by hagberg** [comment]
Closed due to inactivity.
