### ISSUE TITLE
remove_edges_from() affects all copies of a graph, not just the one specified

### ISSUE THREAD

**Issue by schoenfa** [networkx/networkx#6747]
### Current Behavior

I have built a graph and want to remove edges based on their edge weights. I want to do this repeatedly, for different edge weight thresholds. Therefore, I have copied the original graph (G) by assigning a copy to a new object (G2) to avoid constructing G over and over. When I run remove_edges_from() on G2, the edges are removed as expected. However, I was surprised to see that the same edges are also removed from G.

### Expected Behavior

My expectation was that G remains unchanged and edges are only removed from G2. Below example creates a graph with 4 nodes and 3 edges. After running `G2.remove_edges_from(ebunch)` I would expect G to still have 4 nodes and 3 edges but both, G and G2 have 4 nodes and 1 edge afterwards.

### Steps to Reproduce

Using an extended example from the documentation of remove_edges_from()

`G = nx.path_graph(4)`
`ebunch = [(1, 2), (2, 3)]`
`G2 = G`
`G2.remove_edges_from(ebunch)`

### Environment

Python version: 3.11.2
NetworkX version: 3.1

### Additional context

If the described behaviour is intended, how can I create a copy of G and remove edges only from that copy?

**Comment by rossbar** [comment]
In Python, the statement `G2 = G` does not copy the underlying object, but instead binds a new name (`G2` in this case) to the same underlying object that the variable name `G` is bound to.

If you want a copy, you have to indicate so explicitly: `G2 = G.copy()`.

Closing as this is a Python language feature and not related to networkx; hope this helps!

**Comment by schoenfa** [comment]
I was not aware of that. Apologies and thanks for teaching me this. Works as expected now.
