### ISSUE TITLE
directed clustering coefficient (migrated from Trac #688)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#675]
Original ticket https://networkx.lanl.gov/trac/ticket/688
Reported 2012-02-14 by vhatzopoulos, assigned to @hagberg.

The directed clustering coefficient was introduced in 
'Clustering in complex directed networks'
 Phy.Rev.E 76, 026107 (2007)

This coefficient can be implemented both for weighted and unweighted versions.

The coefficient can be further subdivided into four components 'cycle','middle','in','out', when taking into account the direction of edges and the isomorphisms of all possible triangles.

A function signature could take the form directed_clustering(G,nodes=None,weight=None,type)
with type:string('cycle','middle','in','out')

I am willing to provide a draft or assist with any more information.
Thanks for your time, Vasilis

**Comment by codewithsk** [comment]
Is there an existing pull request for this functionality?

**Comment by dschult** [comment]
Add in #2943
