### ISSUE TITLE
`louvain_communities` runs infinite loop

### ISSUE THREAD

**Issue by woQal** [networkx/networkx#6751]
### Current Behavior

The louvain algorithm runs into unending cycle with a specific graph. I test some other graphs (and it ends in few moments) but on this graph (and on a few other graphs) it just runs into infinity.

### Expected Behavior

The algorithm does not cycle and ends in some time (either raises exception or just some code fixes).

### Steps to Reproduce
The file is provided here:
[sth.txt](https://github.com/networkx/networkx/files/11782239/sth.txt)
```
import networkx as nx
graph = nx.read_edgelist(path="sth.txt")
nx.algorithms.community.louvain_communities(graph, weight="weight")
```

### Environment

Python version: 3.9.5
NetworkX version: 3.1

**Comment by woQal** [comment]
The problem is in float weights. The louvain algorithm should maybe round the G.degree(weight="weight").

**Comment by dschult** [comment]
Thanks for your update.  I'm sorry you ran into this issue.
Floating point values involve round-off error.  But it is pervasive.

To be able to avoid such problems, we suggest avoiding floating point values when round-off may cause problems.
One way to do that is to multiply the number by 1e6 and convert to an integer. This is effectively rounding the value, but it also converts it to a form (integers) that doesn't involve round-off error.

**Comment by woQal** [comment]
Added some rounding to the algorithm:
```
_one_level(...)
...
        degrees = dict(map(lambda x: (x[0], round(x[1], 3)), G.degree(weight="weight")))
...
                Stot[best_com] = round(Stot[best_com] - degree, 3)
...
                Stot[best_com] = round(Stot[best_com] + degree, 3)
```

All are necessary, because the floating error just appears after a few plus and minus. (the code is edited for undirected graphs, for directed, it is similar, just round `Stot` changes).

**Comment by rossbar** [comment]
Rounding may also give unexpected results for others who don't have floating point precision comparison issues... Generally this is something that has to be handled in user code. i.e. You can convert attributes to integers with the precision level that you care about.

**Comment by woQal** [comment]
> 

Thank you. I was just really surprised I cannot use the algorithm for floating points (it worked for some).

**Comment by woQal** [comment]
Fin

**Comment by rossbar** [comment]
Yeah, this is a general "issue" with floating point representations - comparisons are always tricky!
