### ISSUE TITLE
Functions with assumed edge or node attributes

### ISSUE THREAD

**Issue by eriknw** [networkx/networkx#6753]
### Current Behavior

As part of #6688, I believe I found a few functions that assume specific attributes for edges or nodes, which means they don't provide a way to specify a different attribute to use.

These functions assume an edge attribute `"weight"` with a default value of 1:
- [x] `second_order_centrality`
- [x] `quotient_graph`
- [x] `panther_similarity`
- [x] `generate_random_paths`
- [x] `number_of_walks`

And this functions assumes a node attribute `"pos"`:
- [x] `geometric_edges`

### Expected Behavior

I expect these functions to follow the networkx convention of allowing users to specify which attribute to use (such as having `weight="weight"` argument).

### Steps to Reproduce

Use the above functions with and w/o the assumed attributes.

### Environment

NetworkX version: main branch (as of 2023-06-20)

### Additional context

There could be more functions with assumed attributes that I didn't find.
Also, I didn't include "flow" algorithms, which often assume `"capacity"`, `"flow"`, or `"id"` attributes in the auxiliary or residual graphs.

We can check-mark functions above as their API are updated to include attribute name.

**Comment by MridulS** [comment]
Hmm, for `number_of_walks` I don't think it make senses to add `weight` to it. The matrix power of a weighted adjacency matrix will just give the product of the weights on the path. Not sure if that means anything (it's definitively not number of walks).

**Comment by dschult** [comment]
We should make sure that "number_of_walks" creates the adjacency_matrix with `weight=None`. Otherwise if the graph has a weight attribute it will be used to compute the number of walks and we don't want that. I'll make a PR for that.

**Comment by eriknw** [comment]
> Hmm, for number_of_walks I don't think it make senses to add weight to it. The matrix power of a weighted adjacency matrix will just give the product of the weights on the path. Not sure if that means anything (it's definitively not number of walks).

Using a weight here would mean something like "number of multiedges". I believe this convention has been used elsewhere. Still, it's fine to use no weight too and wait to see if anybody wants to use weights.

> We should make sure that "number_of_walks" creates the adjacency_matrix with weight=None. Otherwise if the graph has a weight attribute it will be used to compute the number of walks and we don't want that. I'll make a PR for that.

Agreed. This _was not_ done in #6814. It still needs done, so I unchecked this in the task list in the this issue.

**Comment by MridulS** [comment]
> Agreed. This was not done in https://github.com/networkx/networkx/pull/6814. It still needs done, so I unchecked this in the task list in the this issue.

That got in https://github.com/networkx/networkx/pull/6815 :)
