### ISSUE TITLE
github-actions `test / base (ubuntu, 3.12-dev) (pull_request)` fails due to missing numpy dependency

### ISSUE THREAD

**Issue by paulbrodersen** [networkx/networkx#6756]
### Current Behavior

I recently opened [this PR](https://github.com/networkx/networkx/pull/6755). However, one of the github actions fails with the following error trace:

```shell
Run pytest --durations=10 --pyargs networkx
ImportError while loading conftest '/home/runner/work/networkx/networkx/networkx/conftest.py'.
networkx/__init__.py:35: in <module>
    from networkx import generators
networkx/generators/__init__.py:32: in <module>
    from networkx.generators.fractal import *
networkx/generators/fractal.py:4: in <module>
    import numpy as np
E   ModuleNotFoundError: No module named 'numpy'
Error: Process completed with exit code 4.
```

### Expected Behavior

Numpy is imported successfully. 

### Steps to Reproduce

Presumably, submit a PR containing a numpy import. 

### Environment

N/A

**Comment by MridulS** [comment]
Closing this as this is not a CI issue, numpy isn't installed for every run https://github.com/networkx/networkx/pull/6755#issuecomment-1604543925
