### ISSUE TITLE
Building the documentation requires additional dependencies beyond what is specified in doc/README.md

### ISSUE THREAD

**Issue by paulbrodersen** [networkx/networkx#6764]
The documentation for the building the documentation only instructs to install the additional dependencies in `requirements/doc.txt`. However, other than the requirements listed in `default.txt` and `doc.txt`, building the documentation additionally requires the dependencies listed in `example.txt` and `extra.txt`. 

### Current Behavior

Running `make html` inside the /doc folder results in several errors due to missing imports.

### Expected Behavior

No imports should be missing. 

### Steps to Reproduce

1. Install networkx.
2. Install additional requirements listed in `requirements/doc.txt` as outlined in doc/README.md.
3. `cd doc/`
4. `make html`

### Environment

Python version: 3.10
NetworkX version: 3.2rc0.dev0

**Comment by paulbrodersen** [comment]
I would just expand the installation instructions to also include the additional dependencies:

After installing NetworkX and its dependencies, install the Python packages needed to build the documentation by entering::

```shell
pip install -r requirements/doc.txt
pip install -r requirements/extra.txt
pip install -r requirements/example.txt
```

**Comment by rossbar** [comment]
FWIW I think the reason NX doesn't necessarily recommend that is because some of the dependencies in `extra`/`example` are not always easy to install, esp. w/ the latest stable version of Python (this is why they're broken out into separate requirements files).

I would perhaps instead mention `make html-noplot` to skip building the gallery in the case where the other dependencies are not available.

**Comment by paulbrodersen** [comment]
How about the following then:

After installing NetworkX and its dependencies, install the Python packages needed to build the documentation by entering::

```shell
pip install -r requirements/doc.txt
```

Building the example gallery additionally requires the dependencies listed in `requirements/extra.txt` and `requirements/example.txt`:

```shell
pip install -r requirements/extra.txt
pip install -r requirements/example.txt
```

To build the HTML documentation, enter `doc/` and execute:

```shell
make html
```

If the dependencies in `extra.txt` and `example.txt` are **not** installed, build the HTML documentation without generating figures by using:

```shell
make html-noplot
```

**Comment by rossbar** [comment]
Seems reasonable to me, the [current contributor guide](https://networkx.org/documentation/latest/developer/contribute.html#documentation) seems to capture most of this modulo the bit about the extra dependencies - PRs welcome!
