### ISSUE TITLE
Unify documentation README with contributor guide

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#6770]
It was pointed out in #6766 that we have a README in the `doc/` folder that describes how to build the documentation. I think the go-to reference for this information is the contributor guide, and these two documents are not necessarily in sync. However, contributors have also indicated that having a README in the doc folder is nice. Therefore I would propose the following:

1. Reformat `doc/README.md` to .rst, then
2. `.. include` `doc/README` in the `Documentation` section of `CONTRIBUTING.rst`

This should check all boxes: it preserves the README in the `doc/` folder, de-duplicates the source of info (preventing divergence of the README from the contributor guide), and guarantees that the info from the README shows up in the html version of the contributor guide.

**Comment by dschult** [comment]
This sounds like the right organization of this info.  Thanks @rossbar
