### ISSUE TITLE
Canonical labelling (migrated from Trac #691)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#678]
Original ticket https://networkx.lanl.gov/trac/ticket/691
Reported 2012-02-21 by florian.goebels, assigned to @hagberg.

I would like to have a method that returns the canonical labelling for a given graph.

**Comment by jfinkels** [comment]
I have a (slow) implementation of the color refinement algorithm, which I believe is the same thing or at least related, at https://github.com/jfinkels/fraciso/blob/master/fraciso/partitions.py (see function `coarsest_equitable_partition`).

**Comment by ehannesson** [comment]
If I understand correctly, the canonical labeling of a graph is the same as the coarsest equitable partition, as @jfinkels suggested. If this is still a desired enhancement, I have an implementation of the color refinement algorithm which produces the coarsest equitable partition in m log(n) time (based on http://match.pmf.kg.ac.rs/electronic_versions/Match40/match40_265-272.pdf).

**Comment by dschult** [comment]
A PR for this would be welcomed!  Thanks!

**Comment by ehannesson** [comment]
Okay, great. I have a couple questions/requests for guidance.

1. I am entirely unfamiliar with the networkx organization, so I'm not really sure where I should put the code or how to integrate it into the networkx ecosystem properly.

2. Currently my implementation returns a dictionary mapping partition numbers to a list of its members (more precisely, integer labels of the members, not the vertex/node objects themselves). Does this seem like a reasonable thing to return, or should we change it?

Thanks for the help!

**Comment by dschult** [comment]
How about a new module in ```networkx/algorithms/isomorphism```. Then tests go in the tests subfolder there with something like:  ```tests/test_canonical```.  To connect the docstrings to the documentation make an entry in ```doc/reference/algorithms/isomorphism.rst```. And to make the package find the new functions put an entry into ```networkx/algorithms/isomorphism/__init__.py```

Return values seem to either be dicts keyed by nodes to partition numbers or dicts keyed by partition labels to some collection of nodes. It is fairly easy to convert from one to the other. If you return only lists of integer labels of the members then you'll have to deal with a mapping of integers to nodes. Does the algorithm depend on the labels being integers? Maybe you can make it work with arbitrary nodes. Perhaps the best way is proceed is to put together a PR with what you've got and we'll see how easy it would be to convert the results to other formats.

**Comment by ehannesson** [comment]
Thanks for the feedback.

I will go ahead and proceed as suggested, though it may take a little while (I have some relatively significant research demands at the moment).
