### ISSUE TITLE
Minimum cycle basis returns impossible cycles

### ISSUE THREAD

**Issue by mbr085** [networkx/networkx#6783]
### Current Behavior
The minimum cycle basis of the generalized Petersen graph G=P_7,2 appearing in example 11 of 
Liebchen, Christian, and Romeo Rizzi. "Classes of cycle bases." Discrete Applied Mathematics 155.3 (2007): 337-355.
generated by nx.minimum_cycle_basis
contains cycles containing edges that are not edges of the graph.

### Expected Behavior

According to the cited paper, the following is a minimum cycle basis for the graph G:

[7, 9, 1, 0, 6,]
[7, 12, 4, 5, 6,]
[10, 8, 0, 1, 2]
[13, 8, 0, 6, 5]
[11, 9, 1, 2, 3]
[12, 10, 2, 3, 4]
[13, 11, 3, 4, 5]
[7, 9, 1, 2, 10, 12]

This is an expected result. (The basis is not unique.)

### Steps to Reproduce

```python
>>> import scipy.sparse as sp
>>> import networkx as nx
>>> row = [0, 0, 0, 1, 1, 2, 2, 3, 3, 4, 4, 5, 5, 6,
...        7, 7, 8, 8, 9, 10, 11]
>>> col = [1, 6, 8, 9, 2, 3, 10, 4, 11, 5, 12, 6, 13, 7,
...        9, 12, 10, 13, 11, 12, 13]
>>> data = [3.] * 14 + [2.] * 7
>>> G = sp.coo_array((data, (row, col)), shape=(14, 14))
>>> G = G + G.T
>>> GG = nx.Graph(G)
>>> nx.minimum_cycle_basis(GG)
[[0, 5, 6, 8, 13], [0, 1, 6, 7, 9], [4, 5, 6, 7, 12], [0, 1, 2, 8, 10], [0, 6, 7, 8, 10, 12], [1, 2, 3, 9, 11], [2, 3, 4, 10, 12], [3, 4, 5, 11, 13]]
```

Here, for example (0, 5) is not an edge of the graph G.

### Environment

Python version: 3.10.12
NetworkX version: 3.1

**Comment by navyagarwal** [comment]
This is because the nodes in the node list of a cycle are not necessarily returned in the order by which they appear in the cycle.

**Comment by mbr085** [comment]
Thank you for the prompt reply. I overlooked this in the documentation. Is there a preferred way of finding the order in which the nodes appear in the cycles?

**Comment by rossbar** [comment]
> Is there a preferred way of finding the order in which the nodes appear in the cycles?

I can't say that this way is "preferred", nor can I guarantee that it will even always work, but the naive thing to do would be an exhaustive search of potential edges from the cycle basis in `G`:

```python
>>> import itertools
>>> cycle_bases = nx.minimum_cycle_basis(GG)
>>> cb = cycle_bases[0]
>>> cb
[0, 5, 6, 8, 13]
>>> potential_edges = {
...     (u, v) for u, v in itertools.product(cb, cb)
...     if u != v  # ignoring self edges in this example
... }
>>> cycle = potential_edges & set(GG.edges())
>>> cycle
{(0, 6), (0, 8), (5, 6), (5, 13), (8, 13)}
```

**Comment by dschult** [comment]
Using the `GG.subgraph` method should cut down the work in finding edges.
The `nx.cycle_basis(GG)` function returns lists of nodes that are the path of the cycle.  It is worth looking into...  

The current return values of `nx.minimum_cycle_basis` are not very useful. I'm not sure why it returns the cycles with unordered nodes.   We will look into it more.

Here are some partial fixes:
`nx.find_cycle` might work with something like this:
```python
cb = nx.minimum_cycle_basis(GG)
cbasis = [bl for b in cb if len(bl:=nx.find_cycle(GG.subgraph(b)))==len(b)]
```
which can be written more clearly:
```python
cb = nx.minimum_cycle_basis(GG)
cbasis=[]
for b in cb:
    cycle = nx.find_cycle(GG.subgraph(b))
    if len(cycle) == len(b):
        cbasis.append(cycle)
```

Does `nx.cycle_basis(GG)` work for you? Or do you need a minimum?
Maybe the following works? (max of a collection of lists uses `len` to get the longest one.)
```python
[max(nx.cycle_basis(GG.subgraph(b))) for b in nx.minimum_cycle_basis(GG)]
```

**Comment by mbr085** [comment]
@dschult I am confused about the find_cycle function. Does it only find one cycle in the graph? Not necessarily all cycles?
@rossbar I think what you achieve is what GG.subgraph(b) in the code of dschult does. Correct? 
I think this code will find the correct order of all of the minimum cycles.
```python
min_cycles = []
for b in basis:
    s = nx.simple_cycles(GG.subgraph(b))
    s = [np.append(x, x[0]) for x in s if len(x) == len(b)]
    c = np.array([np.sum(G[x[:-1], x[1:]]) for x in s])
    idx = np.argmin(c)
    min_cycles.append(list(s[idx][:-1]))
```
