### ISSUE TITLE
Louvain algorithm throws ZeroDivisionError with graphs that have no edges.

### ISSUE THREAD

**Issue by juanis2112** [networkx/networkx#6790]
### Current Behavior

I'm running the Louvain algorithm with a graph that has no edges and it raises a ZeroDivisionError.

```
Traceback (most recent call last):

  File /opt/anaconda3/envs/networkx/lib/python3.11/site-packages/spyder_kernels/py3compat.py:356 in compat_exec
    exec(code, globals, locals)

  File ~/Local/Dev-Repos/networkx/networkx/algorithms/community/test1.py:22
    print(nx.community.louvain.louvain_communities(G))

  File ~/Local/Dev-Repos/networkx/networkx/utils/decorators.py:766 in func
    return argmap._lazy_compile(__wrapper)(*args, **kwargs)

  File <class 'networkx.utils.decorators.argmap'> compilation 8:4 in argmap_louvain_communities_5
    import inspect

  File ~/Local/Dev-Repos/networkx/networkx/algorithms/community/louvain.py:111 in louvain_communities
    q = deque(d, maxlen=1)

  File ~/Local/Dev-Repos/networkx/networkx/algorithms/community/louvain.py:167 in louvain_partitions
    mod = modularity(G, partition, resolution=resolution, weight=weight)

  File ~/Local/Dev-Repos/networkx/networkx/algorithms/community/quality.py:239 in modularity
    norm = 1 / deg_sum**2

ZeroDivisionError: division by zero
```

### Expected Behavior

Modularity should be undefined for a graph with no edges so the output of the Louvain algorithm probably should be 'NetworkPointlessConcept'.

### Steps to Reproduce

G = nx.Graph()
G.add_nodes_from(range(10))
nx.community.louvain.louvain_communities(G)

### Steps to Solve

Inside the louvain_partitions function (in louvain.py), before the line `mod = modularity(G, partition, resolution=resolution, weight=weight)` there should be a check for the degree of the graph and if the degree is zero, the function should probably just break and return  'NetworkPointlessConcept'.

### Environment

Python version: 3.11
NetworkX version:

**Comment by juanis2112** [comment]
I'll open a PR to solve it.

**Comment by MridulS** [comment]
fixed in https://github.com/networkx/networkx/pull/6791
