### ISSUE TITLE
Problem in nx.adjacency_matrix() related to the format csr change.

### ISSUE THREAD

**Issue by federedef** [networkx/networkx#6792]
Hi,

As I said in a previous issue, thanks again for this fantastic tool. 

I am working on with some adjacency matrix operations. To be precise, I am getting the adjacency matrix of a graph and trying to perform the dot product of itself. There was no problem doing so in the Networkx 2.8.8 version, where I get back an ```<class 'scipy.sparse._csr.csr_matrix'>```. However, upgrading to Networkx 3.1 version, the results differ not just in getting a different sparse class ```<class 'scipy.sparse._arrays.csr_array'>``` (which I expected as documentation said) but also in the dot product result.

### Current Behavior (Networkx 3.1)

**the data type for adjacency matrix is:** <class 'scipy.sparse._arrays.csr_array'>
**the values are:**
  (0, 1)	0.200888972729445
  (0, 2)	0.165412490721792
  (0, 3)	0.607962501002476
  (0, 4)	0.822335097473115
  (0, 6)	0.959318335400894
  (0, 12)	0.826441606041044
  (1, 0)	0.200888972729445
  (1, 2)	0.0653157168999314
  (1, 3)	0.202538545010611
  (1, 4)	0.134010264184326
  (1, 6)	0.797074364963919
  (1, 9)	0.111913250060752
  (1, 10)	0.106002133805305
  (1, 12)	0.0142805050127208
  (2, 0)	0.165412490721792
  (2, 1)	0.0653157168999314
  (2, 3)	0.711981028551236
  (2, 4)	0.156805430073291
  (2, 6)	0.148135325638577
  (2, 12)	0.286343949381262
  (3, 0)	0.607962501002476
  (3, 1)	0.202538545010611
  (3, 2)	0.711981028551236
  (3, 4)	0.104123025201261
  (3, 6)	0.626988608390093
  :	:
  (4, 5)	0.919871900696307
  (4, 6)	0.666519925696775
  (4, 8)	0.632746612653136
  (4, 12)	0.444996226811782
  (4, 13)	0.722622992703691
  (5, 4)	0.919871900696307
  (6, 0)	0.959318335400894
  (6, 1)	0.797074364963919
  (6, 2)	0.148135325638577
  (6, 3)	0.626988608390093
  (6, 4)	0.666519925696775
  (6, 7)	0.878620180534199
  (6, 12)	0.893194946693256
  (7, 6)	0.878620180534199
  (8, 3)	0.868103366345167
  (8, 4)	0.632746612653136
  (9, 1)	0.111913250060752
  (10, 1)	0.106002133805305
  (11, 3)	0.00763212377205491
  (12, 0)	0.826441606041044
  (12, 1)	0.0142805050127208
  (12, 2)	0.286343949381262
  (12, 4)	0.444996226811782
  (12, 6)	0.893194946693256
  (13, 4)	0.722622992703691
**the data type for adjacency matrix:** **float64**
**the values for dotproduct**
  (0, 1)	0.0403563793642917
  (0, 2)	0.027361292086786927
  (0, 3)	0.3696184026251856
  (0, 4)	0.6762350125361175
  (0, 6)	0.920291668636342
  (0, 12)	0.6830057281957002
  (1, 0)	0.0403563793642917
  (1, 2)	0.004266142874151985
  (1, 3)	0.041021862215015296
  (1, 4)	0.017958750906752845
  (1, 6)	0.6353275432826349
  (1, 9)	0.012524575539160409
  (1, 10)	0.011236452371277785
  (1, 12)	0.0002039328234183439
  (2, 0)	0.027361292086786927
  (2, 1)	0.004266142874151985
  (2, 3)	0.506916985016876
  (2, 4)	0.024587942900469756
  (2, 6)	0.02194407470204725
  (2, 12)	0.08199285734725874
  (3, 0)	0.3696184026251856
  (3, 1)	0.041021862215015296
  (3, 2)	0.506916985016876
  (3, 4)	0.010841604377062435
  (3, 6)	0.39311471505094536
  :	:
  (4, 5)	0.8461643136906365
  (4, 6)	0.44424881135083444
  (4, 8)	0.4003682758240178
  (4, 12)	0.19802164187672294
  (4, 13)	0.5221839895840387
  (5, 4)	0.8461643136906365
  (6, 0)	0.920291668636342
  (6, 1)	0.6353275432826349
  (6, 2)	0.02194407470204725
  (6, 3)	0.39311471505094536
  (6, 4)	0.44424881135083444
  (6, 7)	0.7719734216419484
  (6, 12)	0.7977972127983686
  (7, 6)	0.7719734216419484
  (8, 3)	0.7536034546598113
  (8, 4)	0.4003682758240178
  (9, 1)	0.012524575539160409
  (10, 1)	0.011236452371277785
  (11, 3)	5.8249313271965664e-05
  (12, 0)	0.6830057281957002
  (12, 1)	0.0002039328234183439
  (12, 2)	0.08199285734725874
  (12, 4)	0.19802164187672294
  (12, 6)	0.7977972127983686
  (13, 4)	0.5221839895840387
**the values for dotproduct in array non sparsed format**
[[0.00000000e+00 4.03563794e-02 2.73612921e-02 3.69618403e-01
  6.76235013e-01 0.00000000e+00 9.20291669e-01 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  6.83005728e-01 0.00000000e+00]
 [4.03563794e-02 0.00000000e+00 4.26614287e-03 4.10218622e-02
  1.79587509e-02 0.00000000e+00 6.35327543e-01 0.00000000e+00
  0.00000000e+00 1.25245755e-02 1.12364524e-02 0.00000000e+00
  2.03932823e-04 0.00000000e+00]
 [2.73612921e-02 4.26614287e-03 0.00000000e+00 5.06916985e-01
  2.45879429e-02 0.00000000e+00 2.19440747e-02 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  8.19928573e-02 0.00000000e+00]
 [3.69618403e-01 4.10218622e-02 5.06916985e-01 0.00000000e+00
  1.08416044e-02 0.00000000e+00 3.93114715e-01 0.00000000e+00
  7.53603455e-01 0.00000000e+00 0.00000000e+00 5.82493133e-05
  0.00000000e+00 0.00000000e+00]
 [6.76235013e-01 1.79587509e-02 2.45879429e-02 1.08416044e-02
  0.00000000e+00 8.46164314e-01 4.44248811e-01 0.00000000e+00
  4.00368276e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
  1.98021642e-01 5.22183990e-01]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  8.46164314e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [9.20291669e-01 6.35327543e-01 2.19440747e-02 3.93114715e-01
  4.44248811e-01 0.00000000e+00 0.00000000e+00 7.71973422e-01
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  7.97797213e-01 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 7.71973422e-01 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 7.53603455e-01
  4.00368276e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.25245755e-02 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 1.12364524e-02 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 5.82493133e-05
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [6.83005728e-01 2.03932823e-04 8.19928573e-02 0.00000000e+00
  1.98021642e-01 0.00000000e+00 7.97797213e-01 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  5.22183990e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  0.00000000e+00 0.00000000e+00]]

### Expected Behavior (Networkx 2.8.8)

**the data type for adjacency matrix is:** <class 'scipy.sparse._csr.csr_matrix'>
**the values are:**
  (0, 1)	0.200888972729445
  (0, 2)	0.165412490721792
  (0, 3)	0.607962501002476
  (0, 4)	0.822335097473115
  (0, 6)	0.959318335400894
  (0, 12)	0.826441606041044
  (1, 0)	0.200888972729445
  (1, 2)	0.0653157168999314
  (1, 3)	0.202538545010611
  (1, 4)	0.134010264184326
  (1, 6)	0.797074364963919
  (1, 9)	0.111913250060752
  (1, 10)	0.106002133805305
  (1, 12)	0.0142805050127208
  (2, 0)	0.165412490721792
  (2, 1)	0.0653157168999314
  (2, 3)	0.711981028551236
  (2, 4)	0.156805430073291
  (2, 6)	0.148135325638577
  (2, 12)	0.286343949381262
  (3, 0)	0.607962501002476
  (3, 1)	0.202538545010611
  (3, 2)	0.711981028551236
  (3, 4)	0.104123025201261
  (3, 6)	0.626988608390093
  :	:
  (4, 5)	0.919871900696307
  (4, 6)	0.666519925696775
  (4, 8)	0.632746612653136
  (4, 12)	0.444996226811782
  (4, 13)	0.722622992703691
  (5, 4)	0.919871900696307
  (6, 0)	0.959318335400894
  (6, 1)	0.797074364963919
  (6, 2)	0.148135325638577
  (6, 3)	0.626988608390093
  (6, 4)	0.666519925696775
  (6, 7)	0.878620180534199
  (6, 12)	0.893194946693256
  (7, 6)	0.878620180534199
  (8, 3)	0.868103366345167
  (8, 4)	0.632746612653136
  (9, 1)	0.111913250060752
  (10, 1)	0.106002133805305
  (11, 3)	0.00763212377205491
  (12, 0)	0.826441606041044
  (12, 1)	0.0142805050127208
  (12, 2)	0.286343949381262
  (12, 4)	0.444996226811782
  (12, 6)	0.893194946693256
  (13, 4)	0.722622992703691
**the data type for adjacency matrix:** **float64**
**the values for dotproduct**
  (0, 7)	0.8428764490397007
  (0, 13)	0.5942382491413037
  (0, 5)	0.7564429491218772
  (0, 11)	0.0046400450564189535
  (0, 8)	1.0481040411237763
  (0, 1)	1.0205912759358677
  (0, 12)	1.2730279668530322
  (0, 10)	0.021294659767276895
  (0, 9)	0.02248213783951797
  (0, 6)	1.8520886403197903
  (0, 4)	1.1233298378671095
  (0, 3)	0.8455640017188029
  (0, 2)	0.9536810700915272
  (0, 0)	2.716868483444424
  (1, 7)	0.7003256224437806
  (1, 13)	0.0968388981578899
  (1, 5)	0.12327227642805018
  (1, 11)	0.0015457992441328975
  (1, 8)	0.2606189334617477
  (1, 0)	1.0205912759358677
  (1, 12)	0.9563026224328366
  (1, 6)	0.43145718663338445
  (1, 4)	0.7341495554343307
  (1, 3)	0.6823466145704229
  (1, 2)	0.3206106908618974
  :	:
  (11, 2)	0.005433927333257994
  (11, 1)	0.0015457992441328975
  (11, 0)	0.0046400450564189535
  (12, 7)	0.7847791053158629
  (12, 13)	0.3215645051605804
  (12, 8)	0.2815698551585817
  (12, 5)	0.40933952496003884
  (12, 10)	0.0015137640031657592
  (12, 9)	0.0015981777284824455
  (12, 0)	1.2730279668530322
  (12, 12)	1.7610213730414688
  (12, 6)	1.1432197164938778
  (12, 4)	1.3217581885433773
  (12, 3)	1.3155667280354604
  (12, 2)	0.33972805492731617
  (12, 1)	0.9563026224328366
  (13, 13)	0.5221839895840387
  (13, 12)	0.3215645051605804
  (13, 8)	0.45723725085853234
  (13, 6)	0.48164262340364533
  (13, 5)	0.6647205857851978
  (13, 3)	0.07524169208029706
  (13, 2)	0.1133112091517509
  (13, 1)	0.0968388981578899
  (13, 0)	0.5942382491413037
**the values for dotproduct in array non sparsed format**
[[2.71686848e+00 1.02059128e+00 9.53681070e-01 8.45564002e-01
  1.12332984e+00 7.56442949e-01 1.85208864e+00 8.42876449e-01
  1.04810404e+00 2.24821378e-02 2.12946598e-02 4.64004506e-03
  1.27302797e+00 5.94238249e-01]
 [1.02059128e+00 7.62895639e-01 3.20610691e-01 6.82346615e-01
  7.34149555e-01 1.23272276e-01 4.31457187e-01 7.00325622e-01
  2.60618933e-01 0.00000000e+00 0.00000000e+00 1.54579924e-03
  9.56302622e-01 9.68388982e-02]
 [9.53681070e-01 3.20610691e-01 6.67069295e-01 2.22999759e-01
  4.45068215e-01 1.44240909e-01 1.01742363e+00 1.30154687e-01
  7.17291232e-01 7.30969416e-03 6.92360536e-03 5.43392733e-03
  3.39728055e-01 1.13311209e-01]
 [8.45564002e-01 6.82346615e-01 2.22999759e-01 2.07517527e+00
  1.60592350e+00 9.57798451e-02 9.19537469e-01 5.50884844e-01
  6.58834915e-02 2.26667468e-02 2.14695179e-02 0.00000000e+00
  1.31556673e+00 7.52416921e-02]
 [1.12332984e+00 7.34149555e-01 4.45068215e-01 1.60592350e+00
  3.14061034e+00 0.00000000e+00 1.38167804e+00 5.85617857e-01
  9.03895487e-02 1.49975242e-02 1.42053740e-02 7.94679816e-04
  1.32175819e+00 0.00000000e+00]
 [7.56442949e-01 1.23272276e-01 1.44240909e-01 9.57798451e-02
  0.00000000e+00 8.46164314e-01 6.13112951e-01 0.00000000e+00
  5.82045829e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
  4.09339525e-01 6.64720586e-01]
 [1.85208864e+00 4.31457187e-01 1.01742363e+00 9.19537469e-01
  1.38167804e+00 6.13112951e-01 3.98469745e+00 0.00000000e+00
  9.66029147e-01 8.92031827e-02 8.44915835e-02 4.78525466e-03
  1.14321972e+00 4.81642623e-01]
 [8.42876449e-01 7.00325622e-01 1.30154687e-01 5.50884844e-01
  5.85617857e-01 0.00000000e+00 0.00000000e+00 7.71973422e-01
  0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00
  7.84779105e-01 0.00000000e+00]
 [1.04810404e+00 2.60618933e-01 7.17291232e-01 6.58834915e-02
  9.03895487e-02 5.82045829e-01 9.66029147e-01 0.00000000e+00
  1.15397173e+00 0.00000000e+00 0.00000000e+00 6.62547234e-03
  2.81569855e-01 4.57237251e-01]
 [2.24821378e-02 0.00000000e+00 7.30969416e-03 2.26667468e-02
  1.49975242e-02 0.00000000e+00 8.92031827e-02 0.00000000e+00
  0.00000000e+00 1.25245755e-02 1.18630433e-02 0.00000000e+00
  1.59817773e-03 0.00000000e+00]
 [2.12946598e-02 0.00000000e+00 6.92360536e-03 2.14695179e-02
  1.42053740e-02 0.00000000e+00 8.44915835e-02 0.00000000e+00
  0.00000000e+00 1.18630433e-02 1.12364524e-02 0.00000000e+00
  1.51376400e-03 0.00000000e+00]
 [4.64004506e-03 1.54579924e-03 5.43392733e-03 0.00000000e+00
  7.94679816e-04 0.00000000e+00 4.78525466e-03 0.00000000e+00
  6.62547234e-03 0.00000000e+00 0.00000000e+00 5.82493133e-05
  0.00000000e+00 0.00000000e+00]
 [1.27302797e+00 9.56302622e-01 3.39728055e-01 1.31556673e+00
  1.32175819e+00 4.09339525e-01 1.14321972e+00 7.84779105e-01
  2.81569855e-01 1.59817773e-03 1.51376400e-03 0.00000000e+00
  1.76102137e+00 3.21564505e-01]
 [5.94238249e-01 9.68388982e-02 1.13311209e-01 7.52416921e-02
  0.00000000e+00 6.64720586e-01 4.81642623e-01 0.00000000e+00
  4.57237251e-01 0.00000000e+00 0.00000000e+00 0.00000000e+00
  3.21564505e-01 5.22183990e-01]]

### Steps to Reproduce

This are the edges from the graph: [(4, 8, {'weight': 0.632746612653136}), (4, 6, {'weight': 0.666519925696775}), (4, 2, {'weight': 0.156805430073291}), (4, 1, {'weight': 0.134010264184326}), (4, 3, {'weight': 0.104123025201261}), (4, 5, {'weight': 0.919871900696307}), (4, 13, {'weight': 0.722622992703691}), (4, 12, {'weight': 0.444996226811782}), (4, 0, {'weight': 0.822335097473115}), (9, 1, {'weight': 0.111913250060752}), (8, 3, {'weight': 0.868103366345167}), (6, 7, {'weight': 0.878620180534199}), (6, 2, {'weight': 0.148135325638577}), (6, 1, {'weight': 0.797074364963919}), (6, 3, {'weight': 0.626988608390093}), (6, 12, {'weight': 0.893194946693256}), (6, 0, {'weight': 0.959318335400894}), (11, 3, {'weight': 0.00763212377205491}), (10, 1, {'weight': 0.106002133805305}), (2, 1, {'weight': 0.0653157168999314}), (2, 3, {'weight': 0.711981028551236}), (2, 12, {'weight': 0.286343949381262}), (2, 0, {'weight': 0.165412490721792}), (1, 3, {'weight': 0.202538545010611}), (1, 12, {'weight': 0.0142805050127208}), (1, 0, {'weight': 0.200888972729445}), (3, 0, {'weight': 0.607962501002476}), (12, 0, {'weight': 0.826441606041044})]

and I am executing the next code:

```
node_list=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
adj = nx.adjacency_matrix(net, weight='weight', nodelist=node_list)
dotproduct = np.dot(adj, adj) 
```

### Environment

Python version: 3.10
NetworkX version: 3.1

**Comment by rossbar** [comment]
I think this is a bug in scipy. It looks like `np.dot` semantics are not consistent between sparse arrays and sparse matrices. In both cases, `np.dot` *should* result in matrix multiplication (since both inputs are 2D arrays), but it looks like `np.dot` is element-wise multiplication on the sparse arrays:

```python
>>> import scipy as sp
>>> G = nx.Graph()
>>> G.add_edges_from(<cp edgelist from OP>)
>>> node_list = list(range(14))
>>> A = nx.adjacency_matrix(G, weight="weight", nodelist=node_list)
>>> A
<14x14 sparse array of type '<class 'numpy.float64'>'
        with 56 stored elements in Compressed Sparse Row format>
>>> M = sp.sparse.csr_matrix(A)
>>> M
<14x14 sparse matrix of type '<class 'numpy.float64'>'
        with 56 stored elements in Compressed Sparse Row format>
# Dot on sparse matrices == matrix multiplication
>>> np.dot(M, M)
<14x14 sparse matrix of type '<class 'numpy.float64'>'
        with 150 stored elements in Compressed Sparse Row format>
>>> np.allclose(np.dot(M, M).toarray(), (M @ M).toarray())
# Dot on sparse arrays != matrix multiplication
>>> np.dot(A, A)
<14x14 sparse array of type '<class 'numpy.float64'>'
        with 56 stored elements in Compressed Sparse Row format>
>>> np.allclose(np.dot(A, A).toarray(), (A @ A).toarray())
False
>>> np.allclose(np.dot(A, A).toarray(), (A ** 2).toarray())
True
```

FWIW the matrix multiplication operator (`@`) should be used instead of `np.dot` as it is unambiguous and will solve your issue here. I will open an issue upstream.

**Comment by federedef** [comment]
Ok, thank so much for the answer and the issue on scipy. I am taking it into account and will be using ```@``` instead of ```np.dot```.

**Comment by dschult** [comment]
I'll close this as it is an upstream issue in scipy. Thanks for reporting!
