### ISSUE TITLE
confusing results generated by dfs_predecessors()

### ISSUE THREAD

**Issue by HyperionTau** [networkx/networkx#6795]
The dfs_predecessors(G, source, depth) and the dfs_successors(G, source, depth) generate the same results. 
They both return the successors of the source node.

**Comment by rossbar** [comment]
If the graph `G` is undirected, then this is expected. You can think of undirected edges as bi-directional, in which case there is no distinction between predecessors and successors:

```python
>>> G = nx.path_graph(4)
>>> nx.dfs_successors(G, source=1, depth_limit=1)
{1: [0, 2]}
>>> nx.dfs_predecessors(G, source=1, depth_limit=1)
{0: 1, 2: 1}
```

**Comment by HyperionTau** [comment]
Please try the following code

import networkx as nx

G = nx.DiGraph()
G.add_edges_from([(1, 2), (1, 3) , (3, 4) , (3, 5) , (0, 1), (9, 0)])
nx.draw(G, label = True)

a = nx.dfs_predecessors(G, source=1)
b = nx.dfs_successors(G, source=1)


print(b)
{1: [2, 3], 3: [4, 5]}

print(a)
{2: 1, 3: 1, 4: 3, 5: 3}

**Comment by rossbar** [comment]
Thanks for the example, I see what you mean now: I assume you are expecting `nx.dfs_predecessors(G, source=1)` to give the predecessors of node `1`, so something like `{1: [0, 9]}`. The current result does seem incorrect to me.

**Comment by dschult** [comment]
But the docs state that the source is the starting node for the DFS, not the node for which you want the predecessors.  So, while I think the returned value is correct, I can see that there is a misunderstanding in the wording of the doc_string.

We could change the name of the optional keyword argument from `source` to `starting_node_of_DFS`. But I think that may be more than what is called for.  How about the description becomes:
```
    source : node, optional
       Specify starting node for depth-first search.
        Note that you will get predecessors for all nodes in the
        component containing `source`. This input only specifies
        where the DFS starts.
```
Thoughts? Is there a better way to convey this?
