### ISSUE TITLE
Modifying the edges of a PlannarEmbedding graph invalidates its structure.

### ISSUE THREAD

**Issue by mdealencar** [networkx/networkx#6796]
If an edge is removed and another one added to a `PlanarEmbedding`, it becomes invalid even if the modifications result in a planar embedding (see notebook below).

### Current Behavior

An error is produced upon calling `PlanarEmbedding.check_structure()`.

### Expected Behavior

No error (provided the graph is still a planar embedding).

### Steps to Reproduce

```python
import networkx as nx

edges = ((0, 1), (1, 2), (2, 3), (3, 0), (0, 2))
pos = ((0, 0), (1, 0), (1, 1), (0, 1))

Gmwe = nx.Graph(((0, 1),
                 (1, 2),
                 (2, 3),
                 (3, 0),
                 (0, 2)))

cert, Pmwe = nx.check_planarity(Gmwe)
cert
```
Output:
    True

```python
type(Pmwe)
```
Output:
    networkx.algorithms.planarity.PlanarEmbedding

```python
nx.draw(Pmwe, with_labels=True, pos=pos)
```
![output_5_0](https://github.com/networkx/networkx/assets/856825/ea8589c7-6d20-46f3-bb12-2d8641f28bdf)
```python
list(Pmwe.neighbors_cw_order(0))
```
Output:
    [1, 3, 2]
```python
list(Pmwe.neighbors_cw_order(2))
```
Output:
    [1, 0, 3]

Now we remove the edge `(0, 2)` and add `(3, 1)`, inserting each half-edge in the proper position.
```python
Pmwe.remove_edges_from(((0, 2), (2, 0)))
Pmwe.add_half_edge_ccw(1, 3, 2)
Pmwe.add_half_edge_cw(3, 1, 2)
```

```python
nx.draw(Pmwe, with_labels=True, pos=pos)
```
![output_10_0](https://github.com/networkx/networkx/assets/856825/20adc934-4c37-46bf-a433-c786bf8b3cca)

Why is the modified PlanarEmbedding not structurally sound anymore?

```python
Pmwe.check_structure()
```
Output:

    ---------------------------------------------------------------------------

    KeyError                                  Traceback (most recent call last)

    File ~\programs\miniconda\envs\interarray\lib\site-packages\networkx\algorithms\planarity.py:938, in PlanarEmbedding.check_structure(self)
        937 try:
    --> 938     sorted_nbrs = set(self.neighbors_cw_order(v))
        939 except KeyError as err:
    

    File ~\programs\miniconda\envs\interarray\lib\site-packages\networkx\algorithms\planarity.py:915, in PlanarEmbedding.neighbors_cw_order(self, v)
        914 yield current_node
    --> 915 current_node = self[v][current_node]["cw"]
    

    File ~\programs\miniconda\envs\interarray\lib\site-packages\networkx\classes\coreviews.py:53, in AtlasView.__getitem__(self, key)
         52 def __getitem__(self, key):
    ---> 53     return self._atlas[key]
    

    KeyError: 2

    
    The above exception was the direct cause of the following exception:
    

    NetworkXException                         Traceback (most recent call last)

    Cell In[12], line 1
    ----> 1 Pmwe.check_structure()
    

    File ~\programs\miniconda\envs\interarray\lib\site-packages\networkx\algorithms\planarity.py:941, in PlanarEmbedding.check_structure(self)
        939 except KeyError as err:
        940     msg = f"Bad embedding. Missing orientation for a neighbor of {v}"
    --> 941     raise nx.NetworkXException(msg) from err
        943 unsorted_nbrs = set(self[v])
        944 if sorted_nbrs != unsorted_nbrs:
    

    NetworkXException: Bad embedding. Missing orientation for a neighbor of 0

The `check_planarity()` function has no problems with it:

```python
cert, Nmwe = nx.check_planarity(Pmwe)
cert
```
Output:
    True

```python
nx.draw(Nmwe, with_labels=True, pos=pos)
```
![output_15_0](https://github.com/networkx/networkx/assets/856825/a7bfc515-0bd7-4c47-a158-543af6203f63)
 
```python
nx.difference(Pmwe, Nmwe).edges
```
Output:
    OutEdgeView([])

### Environment

Python version: 3.10.12
NetworkX version: 3.1

**Comment by mdealencar** [comment]
After experimenting a bit, I figured that `PlanarEmbedding.remove_edges()` is not changing the keys `'cw'` and `'ccw'` of the edges surrounding the removed edge (i.e. they keep referencing the removed edge). I think this is a bug.

**Comment by dschult** [comment]
Yes -- it sounds like that is a bug. 
Thanks for tracking down the `remove_edge` location for the bug. Are you able to open a PR to fix it? If not we will get to it, but we'd love a PR -- or even a description/patch of what changes are needed. 
Thanks!!
