### ISSUE TITLE
NetworkX User Survey 2023 closed but still displayed on website

### ISSUE THREAD

**Issue by kraktus** [networkx/networkx#6817]
Hello, thank you for this lib with great features and docs. It seems the "NetworkX User Survey 2023" is still displayed on the doc website despite being closed.

### Current Behavior

<img width="494" alt="image" src="https://github.com/networkx/networkx/assets/56031107/b0c4efc5-3a87-48e4-80b2-6cc43bd09200">

### Expected Behavior

Either reopening the survey, or removing the banner from the website.

### Steps to Reproduce

https://networkx.org/documentation/stable/index.html
<img width="1152" alt="image" src="https://github.com/networkx/networkx/assets/56031107/bcfc40d3-f9a7-432e-9f0e-4ef77e57c704">

**Comment by MridulS** [comment]
Thanks @kraktus for raising this. It should be removed soon.

But it would still be part of the 3.1 release docs as we would need to rebuild them and publish it.
