### ISSUE TITLE
dfs_labeled_edges output doesn't make sense/is inconsistent with definitions

### ISSUE THREAD

**Issue by 20kavishs** [networkx/networkx#6821]
The dfs_labeled_edges function returns some results that may be inconsistent. If not, then I think the documentation at https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.traversal.depth_first_search.dfs_labeled_edges.html should at least be updated

### Current Behavior
The best example is simply the one in the documentation: https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.traversal.depth_first_search.dfs_labeled_edges.html

```
from pprint import pprint
G = nx.DiGraph([(0, 1), (1, 2), (2, 1)])
pprint(list(nx.dfs_labeled_edges(G, source=0)))
```
The above code outputs:
```
[(0, 0, 'forward'),
 (0, 1, 'forward'),
 (1, 2, 'forward'),
 (2, 1, 'nontree'),
 (1, 2, 'reverse'),
 (0, 1, 'reverse'),
 (0, 0, 'reverse')]
```

The definitions from the documentation are: 

A ‘forward’ edge is one in which u has been visited but v has not. A ‘nontree’ edge is one in which both u and v have been visited but the edge is not in the DFS tree. A ‘reverse’ edge is one in which both u and v have been visited and the edge is in the DFS tree. 

But then how is (0,1) both a reverse and forward edge? As it is, why is (0,0) a forward edge? 

### Expected Behavior
Just needs to ensure correct classification of edges

### Steps to Reproduce
See above. 

### Environment
Python version: 3.11
NetworkX version: 3.1

**Comment by dschult** [comment]
The tree edges each get reported twice. Once when the edge is traversed in the forward direction (when v is first discovered). A second time when the node `v`  has been fully explored and the process moves back to exploring u -- this is reported as a reverse traversal on that same edge.

So, the (0, 1, 'forward') means that node v is being prepared for exploration -- it should be reported on a dfs_preorder at this time. Then the (0, 1, 'reverse') means that node v has been explored completely and we are returning to node u -- node v should be reported on a dfs_postorder at this time.

**Comment by 20kavishs** [comment]
Ah I see, got it thanks!
