### ISSUE TITLE
question about Graph Isomorphism with function "nx.vf2pp_is_isomorphic"

### ISSUE THREAD

**Issue by ElahehA** [networkx/networkx#6833]
I want to check two below graphs G1 and G2 are isomorphic? 
My expected result for "nx.vf2pp_is_isomorphic(G1, G2 ,node_label=None)"  is  "False" while the code result is "true".

import networkx as nx
G1 = nx.Graph()
G1.add_edges_from([(1, 1), (1, 1), (1, 1), (2, 2)])
G2 = nx.Graph()
G2.add_edges_from([(1, 1), (1, 1), (2, 2), (2, 2)])
nx.vf2pp_is_isomorphic(G1, G2 ,node_label=None)

Environment:
Python version: 3.11.4
NetworkX version: 3.1

**Comment by MridulS** [comment]
`G1` and `G2` are isomorphic graphs as you are adding the same edges multiple times. Both `G1` and `G2` only has 2 edges.
``` python
In [7]: G1.edges()
Out[7]: EdgeView([(1, 1), (2, 2)])

In [8]: G2.edges()
Out[8]: EdgeView([(1, 1), (2, 2)])
```
Adding the same edge again just overwrites the previous edge, it doesn't add a new edge for a `Graph` object.

If you want to have multiple edges between 2 nodes in a graph you can use `MultiGraph`, and in that case `vf2pp_is_isomorphic` would give you `False` for this example.

``` python
In [9]: G1 = nx.MultiGraph()

In [10]:  G1.add_edges_from([(1, 1), (1, 1), (1, 1), (2, 2)])
Out[10]: [0, 1, 2, 0]

In [11]: G2 = nx.MultiGraph()

In [12]:  G2.add_edges_from([(1, 1), (1, 1), (2, 2), (2, 2)])
Out[12]: [0, 1, 0, 1]

In [13]: nx.vf2pp_is_isomorphic(G1, G2 ,node_label=None)
Out[13]: False
```
