### ISSUE TITLE
closeness_centrality AttributeError: module 'networkx' has no attribute 'single_source_shortest_path_length'

### ISSUE THREAD

**Issue by aroyphillips** [networkx/networkx#6844]
### Current Behavior
The closeness centrality is failing to run yielding AttributeError: module 'networkx' has no attribute 'single_source_shortest_path_length'

### Expected Behavior
I believe the code should just be refactored at that failing point so it runs.

### Steps to Reproduce

```
# test nx.closeness_centrality
dummy_graph = nx.Graph()
dummy_graph.add_nodes_from([1,2,3,4,5])
dummy_graph.add_edges_from([(1,2), (1,3), (1,4), (1,5), (2,3), (2,4), (2,5)])
nx.closeness_centrality(dummy_graph)
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[65], line 5
      3 dummy_graph.add_nodes_from([1,2,3,4,5])
      4 dummy_graph.add_edges_from([(1,2), (1,3), (1,4), (1,5), (2,3), (2,4), (2,5)])
----> 5 nx.closeness_centrality(dummy_graph)

File [~/.conda/envs/myEnv/lib/python3.10/site-packages/networkx/algorithms/centrality/closeness.py:114](https://vscode-remote+ssh-002dremote-002byoda-002eece-002erice-002eedu.vscode-resource.vscode-cdn.net/home/ap60/github/my_project/notebooks/~/.conda/envs/myEnv/lib/python3.10/site-packages/networkx/algorithms/centrality/closeness.py:114), in closeness_centrality(G, u, distance, wf_improved)
    110     path_length = functools.partial(
    111         nx.single_source_dijkstra_path_length, weight=distance
    112     )
    113 else:
--> 114     path_length = nx.single_source_shortest_path_length
    116 if u is None:
    117     nodes = G.nodes

AttributeError: module 'networkx' has no attribute 'single_source_shortest_path_length'

```
### Environment

I am using a conda environment with Networkx 3.1 installed

Python version: 3.10
NetworkX version: 3.1

**Comment by dschult** [comment]
Something seems to be wrong with your setup. There should definitely be an attribute
`nx.single_source_shortest_path_length`. That has been part of NX from the beginning and it doesn't change in v3.1.

Can you (say, in a new cell) import networkx and then type `nx.<tab>` to activate the tab completion. This should show you the attributes of the library. Maybe there is a conda way of checking the installation too, but I don't know it.

**Comment by aroyphillips** [comment]
Thanks for the quick response. Something went wrong with my conda environment. Remaking it solved my issue.
