### ISSUE TITLE
Update documentation for community algorithms

### ISSUE THREAD

**Issue by navyagarwal** [networkx/networkx#6849]
Some of the community algorithms like `kernighan_lin_bisection`, and `naive_greedy_modularity_communities` are only implemented for certain types of graphs (undirected, not multigraph). The documentation should be updated to reflect the same. 

What would be the appropriate place to add that, in the _parameters_ section or the _raises_ section?

**Comment by MridulS** [comment]
You can add that in the parameters section, something like https://github.com/networkx/networkx/blob/c08ae3af1656a449c803565924669299bd308272/networkx/algorithms/non_randomness.py#L30-L31

**Comment by achluma** [comment]
Good First issues

**Comment by akshayamadhuri** [comment]
Does this issue still need PR

**Comment by rossbar** [comment]
This was closed by #6992
