### ISSUE TITLE
"nx.trophic_levels" returning strange INF value caused by insufficient checking for singular matrix 

### ISSUE THREAD

**Issue by joyemang33** [networkx/networkx#6899]
Hello here and sorry for bothering you again. I noticed that `nx.trophic_levels` will sometimes return INF values for an unsupported graph instead of the following message.
```
networkx.exception.NetworkXError: 
Trophic levels are only defined for graphs where every node has a path from a basal node (basal nodes are nodes with no incoming edges).
```
By investigating the source code, I found that the root cause may be the insufficient checking for whether the matrix can be inverse (reference [link](https://stackoverflow.com/questions/13249108/efficient-pythonic-check-for-singular-matrix)).

To solve the issue, the lines 57 to 66 of [trophic.py](https://github.com/networkx/networkx/blob/main/networkx/algorithms/centrality/trophic.py) could be changed by the following code:
```Python
    if np.linalg.cond(i - p) < np.finfo((i - p).dtype).eps:
        n = np.linalg.inv(i - p)
    else:
        # LinAlgError is raised when there is a non-basal node
        msg = (
            "Trophic levels are only defined for graphs where every "
            + "node has a path from a basal node (basal nodes are nodes "
            + "with no incoming edges)."
        )
        raise nx.NetworkXError(msg) 
```
After I use this effective way to check it, this problem is solved well. It would be highly appreciated if you could further confirm and investigate the issue. I will also create a PR for fixing it if you approve.

Best regards,
Joye

### Step to Reproduce
Running the following Python code:
```Python
import networkx as nx

edges = [(0, 5), (0, 3), (0, 33), (3, 2), (3, 24), (3, 32), (33, 1), (33, 10), (2, 3), (2, 16), (1, 33), (10, 16), (16, 4), (16, 9), (18, 11), (11, 5), (11, 21), (4, 2), (4, 33), (9, 16), (9, 26), (9, 17), (26, 19), (17, 10), (19, 10), (19, 9), (19, 7), (19, 0)]
G = nx.DiGraph(edges)
res = nx.trophic_levels(G)
print(res[0])
```
#### Actual Result:
an extremely large positive value

#### Expected Result:
```
networkx.exception.NetworkXError
```

### Environment
Python 3.10
NetworkX 3.1

**Comment by joyemang33** [comment]
To fully avoid this issue, we can also use BFS to determine whether the graph is supported first. This will not cost much time since its time complexity is linear, compared with the time-consuming matrix operations.

**Comment by Aditya-Shandilya1182** [comment]
I made a PR addressing this issue. Can someone please review it?
Link: https://github.com/networkx/networkx/pull/7453
Thank You!
