### ISSUE TITLE
Desired semantics for nx.join_trees

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#6910]
This is a follow-up to #6503 and related to #6908 (I meant to add to the #6503 discussion, but I was too slow - apologies!)

#6503 modified the behavior of `nx.join` to match behavior as specified in the documentation for `label_attribute=None`: 

> If provided, the old node labels will be stored in the new tree under this node attribute. If not provided, the node attribute '_old' will store the original label of the node in the rooted trees given in the input.

However; I wonder if the default behavior for `label_attribute=None` shouldn't be that new node attributes *aren't* created. In other words, rather than adding `"_old"` attributes to every node in the joined tree by default, would it make more sense to only create these attributes when `label_attribute` is explicitly provided? This would have the advantage of not creating a bunch of extra node attributes by default.

Also, because of the bug which was fixed in #6503, this wouldn't even be a behavior change - so no need for a deprecation/future warning.

**Comment by dschult** [comment]
This suggestion for the default behavior of `label_attribute` would make `nx.join` match the behavior of `nx.convert_node_labels_to_integers` which is very similar in it's relabeling goal and interface.

Looking at that function brings up the idea that maybe this should also have a `first_label` optional keyword argument for people who want the nodes to be integers starting at some offset from zero.

I could add both of these changes to #6908 depending on this discussion.

**Comment by rossbar** [comment]
Good point - I'll go ahead and close this as the original discussion is fairly well-resolved. A new kwarg for the initial offset can be addressed separately if someone is interested!
