### ISSUE TITLE
`nx.negative_edge_cycle` gets crashes for MultiDiGraph in two corner cases

### ISSUE THREAD

**Issue by joyemang33** [networkx/networkx#6921]
Hello! I found that `nx.negative_edge_cycle` will get crashes in the following two cases on MultiDiGraph that contain self-loops. 
The interesting thing is that `nx.negative_edge_cycle` will not get crashes for the same test cases but in other graph types (e.g., DiGraph), and different ways to construct the same graph will lead to different error messages :P.

Please kindly run the following Python codes:

```Python
import networkx as nx
G = nx.MultiDiGraph()
G.add_edge(0, 0)
print(nx.negative_edge_cycle(G))

G = nx.MultiDiGraph()
G.add_edge(0, 0, weight = 0)
print(nx.negative_edge_cycle(G))
```
```
ValueError: min() arg is an empty sequence
AttributeError: 'int' object has no attribute 'get'
```

These behaviors look strange and may need further investigation. Any help in this case will be highly appreciated!

Best regards,
Joye

**Comment by MridulS** [comment]
Thanks for opening this up @joyemang33! This is making NetworkX more robust :)
