### ISSUE TITLE
Some examples in tournament.py don't use tournament graphs

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#6924]
Most `tournament` functions assume the input graph is a tournament. And the docs say the user must check whether it is a tournament. But some of the example don't use tournament graphs.  The docs say that the function's output is undefined when the graph is not a tournament graph. So, while the examples do produce the output they claim to produce, it is a meaningless result.

For example: `tournament.is_strongly_connected(G)` returns False even though the graph in the example is strongly connected.
```python
>>> G = nx.DiGraph([(0, 1), (0, 2), (0, 3), (1, 2), (1, 3), (2, 3), (3, 0)])
>>> nx.tournament.is_strongly_connected(G)
True
>>> G.remove_edge(1, 3)
>>> nx.tournament.is_strongly_connected(G)  # this graph is strongly connected.
False
```
The function `is_strongly_connected` returns `False` even though the graph G is strongly connected.  This is because both examples used are not tournament graphs (exactly one directed edge between each pair of nodes).

I think every example in this module should add a line checking if the graph is a tournament before running the function. There may be others that are not valid example uses of the function. And those examples will reinforce the good practice of checking each time a graph is changed.

**Comment by davidbonin92** [comment]
Hello! I have been working on this issue. I changed the example for `is_strongly_connected` and checked the others in my PR.
