### ISSUE TITLE
`fruchterman_reingold_layout` returns an error if `dim=1`

### ISSUE THREAD

**Issue by rat-h** [networkx/networkx#6932]
I want to project a weighted graph on a line such that the nodes connected with heavier edges located close to each other.  I thought to solve this problem with the `fruchterman_reingold_layout` function, but it returns an error if `dim=1`

### Current Behavior

```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
File ~/.local/apps/jupytor/lib/python3.10/site-packages/networkx/drawing/layout.py:476, in spring_layout(G, k, pos, fixed, iterations, threshold, weight, scale, center, dim, seed)
    475 if len(G) < 500:  # sparse solver for large graphs
--> 476     raise ValueError
    477 A = nx.to_scipy_sparse_array(G, weight=weight, dtype="f")

ValueError: 

During handling of the above exception, another exception occurred:

IndexError                                Traceback (most recent call last)
Cell In[28], line 4
      1 # pos = {}
      2 # for n1 in range(x.shape[0]):
      3 #     pos[f'{n1}'] = rand()
----> 4 pos = nx.fruchterman_reingold_layout(G, dim=1)

File <class 'networkx.utils.decorators.argmap'> compilation 4:4, in argmap_spring_layout_1(G, k, pos, fixed, iterations, threshold, weight, scale, center, dim, seed)
      2 import collections
      3 import gzip
----> 4 import inspect
      5 import itertools
      6 import re

File ~/.local/apps/jupytor/lib/python3.10/site-packages/networkx/drawing/layout.py:491, in spring_layout(G, k, pos, fixed, iterations, threshold, weight, scale, center, dim, seed)
    489         nnodes, _ = A.shape
    490         k = dom_size / np.sqrt(nnodes)
--> 491     pos = _fruchterman_reingold(
    492         A, k, pos_arr, fixed, iterations, threshold, dim, seed
    493     )
    494 if fixed is None and scale is not None:
    495     pos = rescale_layout(pos, scale=scale) + center

File <class 'networkx.utils.decorators.argmap'> compilation 8:4, in argmap__fruchterman_reingold_5(A, k, pos, fixed, iterations, threshold, dim, seed)
      2 import collections
      3 import gzip
----> 4 import inspect
      5 import itertools
      6 import re

File ~/.local/apps/jupytor/lib/python3.10/site-packages/networkx/drawing/layout.py:531, in _fruchterman_reingold(A, k, pos, fixed, iterations, threshold, dim, seed)
    526     k = np.sqrt(1.0 / nnodes)
    527 # the initial "temperature"  is about .1 of domain area (=1x1)
    528 # this is the largest step allowed in the dynamics.
    529 # We need to calculate this in case our fixed positions force our domain
    530 # to be much bigger than 1x1
--> 531 t = max(max(pos.T[0]) - min(pos.T[0]), max(pos.T[1]) - min(pos.T[1])) * 0.1
    532 # simple cooling scheme.
    533 # linearly step down by dt on each iteration so last iteration is size dt.
    534 dt = t / (iterations + 1)

IndexError: index 1 is out of bounds for axis 0 with size 1

```

### Expected Behavior

return dictionary with 32 node position

### Steps to Reproduce

```python
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import networkx as nx
>>> from  numpy.random import rand
>>> G = nx.Graph()
>>> L = [
...     (f'{n1}',f'{n2}',rand()) 
...     for n1 in range(32)
...     for n2 in range(n1, 32)
... ]
>>> G.add_weighted_edges_from(L)
>>> pos = nx.fruchterman_reingold_layout(G, dim=1)
Traceback (most recent call last):
  File "/home/rth/.local/apps/jupytor/lib/python3.10/site-packages/networkx/drawing/layout.py", line 476, in spring_layout
    raise ValueError
ValueError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/rth/.local/apps/jupytor/lib/python3.10/site-packages/networkx/utils/decorators.py", line 766, in func
    return argmap._lazy_compile(__wrapper)(*args, **kwargs)
  File "<class 'networkx.utils.decorators.argmap'> compilation 4", line 4, in argmap_spring_layout_1
  File "/home/rth/.local/apps/jupytor/lib/python3.10/site-packages/networkx/drawing/layout.py", line 491, in spring_layout
    pos = _fruchterman_reingold(
  File "/home/rth/.local/apps/jupytor/lib/python3.10/site-packages/networkx/utils/decorators.py", line 766, in func
    return argmap._lazy_compile(__wrapper)(*args, **kwargs)
  File "<class 'networkx.utils.decorators.argmap'> compilation 8", line 4, in argmap__fruchterman_reingold_5
  File "/home/rth/.local/apps/jupytor/lib/python3.10/site-packages/networkx/drawing/layout.py", line 531, in _fruchterman_reingold
    t = max(max(pos.T[0]) - min(pos.T[0]), max(pos.T[1]) - min(pos.T[1])) * 0.1
IndexError: index 1 is out of bounds for axis 0 with size 1
>>> nx.__version__
'3.0'

```

### Environment
Python version: 3.10.12
NetworkX version: 3.0

**Comment by rossbar** [comment]
Thanks for reporting - this strikes me as a documentation issue, as indeed the FR/spring layout are only intended for 2D and 3D layouts.

**Comment by rat-h** [comment]
@rossbar - thank you for a note. Let's say, if the documentation will says that `dim` should be 2 or 3D, I have no problem with that.

Still, the open question for me: is there an algorithm to order (1D) all nodes of a graph with weighted edges so that nodes connected by heavier edges will be close to each other and with lighter edges far? I hoped the spring algorithm could help me with the problem, but it cannot.

**Comment by rossbar** [comment]
> Still, the open question for me: is there an algorithm to order (1D) all nodes of a graph with weighted edges so that nodes connected by heavier edges will be close to each other and with lighter edges far? I hoped the spring algorithm could help me with the problem, but it cannot.

Nothing jumps out to me as an obvious solution for a complete graph as there are connections between every node - it's not obvious to me how to embed all this information in one dimension.

One thing you could *try*[^1] is your original idea of projection: compute the layout in a higher dimension (e.g. 2D) and project it down to 1D. For example, compute the best-fit line for the collection of 2D points, then project the points from 2D down onto that line. I have no idea if this gets you any closer to what you're really hoping for so YMMV!

[^1]: strictly for visualization purposes, this is not at all a rigorous approach to the real optimization problem!

**Comment by dschult** [comment]
Nice idea of computing in 2D and then projecting onto a best fit line! :} 

Another approach could be to pick one node as the "root" (position 0) and set the position of the others to their weighted shortest path distance to that root node. You could use [single_source_djikstra_path_length](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.shortest_paths.weighted.single_source_dijkstra_path_length.html) to get the lengths even though it is a complete graph the weighted nature might show something. I have no idea if this works or is even close to what you want. :)

**Comment by peijenburg** [comment]
Another, very recent method to project nodes on a line is using this Linear Clustering Algorithm (read Section 3): https://doi.org/10.1109/TNSE.2023.3271360
It is intended for finding clusters in the graph, but it also provides a projection of the graph to a one-dimensional line.

**Comment by rat-h** [comment]
@rossbar, thank you for the suggestion, but I don't think it can work. Even with a very good ellipsoid in 2D, points on the opposite sides from the main axis are still pretty well separated in terms of low binding, but the projection mixes them.

@dschult sounds more reasonable than the projection, but I'm surprised there is no ready-to-use solution.

@peijenburg Thank you. It seems like exactly what I need. Do you know any implementation in Python? Can the algorithm be quickly programmed using Networkx? 

all __Thank you so much for your help!__

**Comment by peijenburg** [comment]
@rat-h I didn't see any code attached to that paper, so perhaps you can contact the authors directly?

**Comment by rat-h** [comment]
Thank you so much, @peijenburg
