### ISSUE TITLE
change default for new function `join_trees` 

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#6947]
As mentioned in #6910 we could make the default behavior for the `label_attribute` be that the old node labels are not stored on the joined trees.

> In other words, rather than adding "_old" attributes to every node in the joined tree by default, would it make more sense to only create these attributes when label_attribute is explicitly provided? This would have the advantage of not creating a bunch of extra node attributes by default.

So, let's remove the part of the code where the "_old" attribute is added by default. That will also require a check below where we store the old labels. If `label_attribute is None` then we just return the graph without storing the old labels.

Let's also add a keyword argument `first_label` matching that argument of `convert_node_labels_to_integers`. Instead of the root node being `0`, it would be `first_label` which is determined near line 106 when we `chain([0]...` and the `accumulate` function will also need a new `initial` argument.

We should add tests of both no label attribute and first_label other than 0.

**Comment by yadomkar** [comment]
@dschult Raised a PR to add these enhancements. Please review and let me know if there are any adjustments or changes needed. Appreciate your feedback!
