### ISSUE TITLE
Add Functionality to Display DiGraph in ASCII Format

### ISSUE THREAD

**Issue by ashish16052** [networkx/networkx#6951]
### Proposal:
Currently, NetworkX does not provide a built-in function to display graphs in ASCII art format. This proposal suggests adding a new functionality to NetworkX that allows users to visualize graphs as ASCII art, providing a textual representation of the graph's structure.

### Proposed Solution:
- Create a new function, e.g., display_ascii, that takes a graph as input and generates an ASCII art representation of the graph's nodes and edges.
- Ensure that the function can handle both directed and undirected graphs.
- Include relevant documentation updates, including the docstring, to explain how to use the new functionality.

```
└── A
    ├── B
    │   └── D
    └── C
        ├── E
        ├── F
        └── G
```

### Additional Information:
This feature would enhance NetworkX's usability and make it more accessible for users who prefer textual representations of graphs for various purposes, including teaching, debugging, and documentation.

**Comment by dschult** [comment]
Is this available in `nx.readwrite.text.py` with functions `nx.write_network_text(G)` and `nx.generate_network_text(G)`?

I think supporting the "rich" ascii features has been started in #5821 and an invitation to build on that to get it merged with NetworkX. :)

**Comment by ashish16052** [comment]
Yes `nx.generate_network_text(G)` is exactly what i was looking for
