### ISSUE TITLE
"documentation version" drop-down button doesn't work on the stable version 

### ISSUE THREAD

**Issue by Schefflera-Arboricola** [networkx/networkx#6986]
### Current Behavior
The "version" drop-down button doesn't interact when clicked, on the stable version. But, it's working on the unstable development version.

### Expected Behavior

Able to switch from stable version to unstable development version.

### Steps to Reproduce

https://networkx.org/documentation/stable/index.html 

### Environment

Browsers tried: Brave and Safari

Python version: --
NetworkX version: 3.1

**Comment by MridulS** [comment]
The button should work on the latest version https://networkx.org/documentation/latest/index.html to move between the latest and stable release.

As soon as 3.2 is released it will work on the stable release too.
