### ISSUE TITLE
d_separated and minimal_d_separator functions incorrectly handle non-disjoint sets and adjacent nodes

### ISSUE THREAD

**Issue by Alex-Markham** [networkx/networkx#6994]
See discussion post #6889

### Current Behavior

d-separation statements are returned even when the sets aren't disjoint, and adjacent nodes can be found to be d-separated

### Expected Behavior
an error should be raised when the sets given to `d_separated()` aren't disjoint and `minimal_d_separator()` should return something that clearly indicates no such separator exists (as opposed to an empty object, which should indicate that the nodes are d-separated given the empty set)

### Steps to Reproduce

See discussion post #6889

### Environment

Python version: 3.11.5
NetworkX version: 3.2rc0.dev0

### Additional context
See discussion post #6889

**Comment by dschult** [comment]
Can you look at #6438 and see if that helps with these issues? I'm pretty sure it addresses the second problem, but I think it might also at least partially address the first. It would be helpful to have someone with more intuition about this take a look at it. :}

**Comment by Alex-Markham** [comment]
Glad to! Little busy at the moment, but should be able to get to it this week

**Comment by Alex-Markham** [comment]
getting fixed in #7019
