### ISSUE TITLE
parallelization of all_pairs_bellman_ford_path

### ISSUE THREAD

**Issue by Schefflera-Arboricola** [networkx/networkx#7003]
```.py
@nx._dispatch
def all_pairs_bellman_ford_path(G, weight="weight"):
    path = single_source_bellman_ford_path
    # TODO This can be trivially parallelized.
    for n in G:
        yield (n, path(G, n, weight=weight))

```
[all_pairs_bellman_ford_path](https://github.com/networkx/networkx/blob/a40863040eb31f60cf39a1c7e4255e059007c461/networkx/algorithms/shortest_paths/weighted.py#L1930)

## Suggested solution
```.py
from multiprocessing import Pool, cpu_count
import networkx as nx
import time

# helper function
def calculate_shortest_paths(args):
    G, source, weight = args
    path = nx.single_source_bellman_ford_path(G, source, weight=weight)
    return (source, path)

@nx._dispatch
def all_pairs_bellman_ford_path(G, weight="weight", num_processes=None):
    if num_processes is None:
        num_processes = cpu_count()  # Using all CPU cores, by default

    pool = Pool(num_processes)
    args_list = [(G, n, weight) for n in G]

    # Using pool.map to get a list of tuples (source, path)
    results_list = pool.map(calculate_shortest_paths, args_list)
    pool.close()
    pool.join()

    # Combining the tuples into a single result dictionary
    all_results = {}
    for source, paths in results_list:
        all_results[source] = paths

    return all_results
```

Is there a parallel implementation of some other function that I could use as a reference or is the above one good? Please give your feedback. Can I create a PR for this?

Thank you :)

**Comment by peijenburg** [comment]
Please have a look at https://github.com/networkx/nx-parallel
if you contribute there :)

**Comment by Schefflera-Arboricola** [comment]
@peijenburg I am not sure if the above algorithm is supposed to be in [networkx/nx-parallel](https://github.com/networkx/nx-parallel), because it's not an independent function it uses `nx.single_source_bellman_ford_path` function, so if we might also have to implement a parallelized version of `single_source_bellman_ford_path` function, and I don't know much about it.

@MridulS sir, could you please guide on how should I proceed?

Thank you :)

**Comment by dschult** [comment]
The functions in `nx-parallel` do not need to be independent of networkx. This use case is an example of how we could use part of networkx to make a parallel function similar to another networkx function. At the moment, networkx does not provide parallel computations. So your suggestion:
1) looks like one reasonable way to parallelize the functionality you want.
2) doesn't use the `joblib` interface to parallel code that nx-parallel does. 
3) could form a skeleton of how to implement this in nx-parallel

**Comment by MridulS** [comment]
The discussion has moved to https://github.com/networkx/nx-parallel/pull/14.
