### ISSUE TITLE
single_source_dijkstra algorithms with multiple target nodes (migrated from Trac #717)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#703]
Original ticket https://networkx.lanl.gov/trac/ticket/717
Reported 2012-04-16 by t.r.etherington, assigned to @hagberg.

I need to apply Dijkstra's algorithm to calculate the shortest paths from a single source node to a subset of other nodes on what will be a large graph.

Given the subset of nodes I'm interested in are generally going to be quite "close" to the source node, I don't want to have to apply Dijkstra's algorithm across the whole graph as the shortest paths to my subset of nodes will probably be found well before the entire graph has been processed.

Presently I can use single_source_dijkstra and specify a target node to stop the algorithm once a single node from my subset has been reached, but doing this for each node in my subset of target nodes is also going to be computationally wasteful, as on each occasion Dijkstra's algorithm will have to start again from scratch, and will have to repeat the same initial searches multiple times.

I'm wondering if it would be possible to extend the "target" parameter of single_source_dijkstra to accept not just a single node, but also a list of nodes?

It would also be very useful to have such an option with single_source_dijkstra_path and single_source_dijkstra_path_length as I will have occasions when I only need the paths or the path lengths.

**Comment by tristan-f-r** [comment]
Was there ever an implemented design for this?

**Comment by dschult** [comment]
No -- finding **all targets** in a list can/should be done manually by the user.
At worst you can find them al one taregt at a time. Or you could use single_source_djikstra to find all nodes from one node and then eliminate the targets found doing that, wash and repeat until list of targets is small enough and then do them one at a time.  You can see why its a tricky interface -- lots of different ways to do it depending on the particular situation.

**Comment by tristan-f-r** [comment]
I see the motivation behind why this design is tricky (it seems like the most general candidate is to pass in a lambda for filtering target nodes, which is [how petgraph does it with `astar`](https://docs.rs/petgraph/latest/petgraph/algo/astar/fn.astar.html)), though a "multi target" dijkstra function really helps when doing a dijkstra call on a large graph but only on a few select, close-together nodes.

**Comment by amcandio** [comment]
Another way to do a multi-target is to add a sentinel node and multiple
cost-0 edges connecting from each of your targets to the sentinel node.
Then you call Dijkstra with one target and drop the last hop.


Ale

**Comment by amcandio** [comment]
But yeah, the current interface could be extended to follow petgraph's
pattern. Target could be either None, str, Callable, if Callable, it will
return true once method returns True for that node.

**Comment by rossbar** [comment]
> Another way to do a multi-target is to add a sentinel node and multiple
> cost-0 edges connecting from each of your targets to the sentinel node.
> Then you call Dijkstra with one target and drop the last hop.

Thanks @amcandio , this is really slick! I'd advocate for documenting it!

**Comment by amcandio** [comment]
@tristan-f-r I added documentation on the sentinel approach, see https://networkx.org/documentation/latest/reference/algorithms/shortest_paths.html#notes-on-multi-target-shortest-path-queries
