### ISSUE TITLE
Miscalculation of a node's degree when it is connected to itself (affects `modularity` and `louvain_communities`)

### ISSUE THREAD

**Issue by ArturoSbr** [networkx/networkx#7035]
I came across this issue upon implementing the Louvain algorithm in PySpark. In essence, I think the [modularity function](https://github.com/networkx/networkx/blob/main/networkx/algorithms/community/quality.py) does not work properly when a node is connected to itself (i.e., a self-loop exists).

**I think this traces back to how a node's degree is calculated.**

To see this, suppose we have the following undirected graph:

```python
# Import nx
import networkx as nx

# Network where node 1 is connected to itself
G = nx.Graph(incoming_graph_data=[
    (1, 1), (1, 2), (1, 3),
    (1, 4), (2, 4), (3, 5)
])

# Declare an awesome partition
P = [{1, 2, 4}, {3, 5}]

# Calculate modularity of said partition
modularity =nx.algorithms.community.quality.modularity(G, P, weight='weight', resolution=1)
```
 This yields 0.2083333333333333. However, upon deriving the modularity by hand according to the formula cited in `networkx/algorithms/community/quality.py` (Reference [1]_), I believe the modularity should equal 0.24305555555 (see attached screenshot).

Notice how my solution matches yours when we count the self loop twice (i.e., node 1 has degree 5 and $A_{11}$ is summed twice).

I am unsure about the degree being equal to 4 (it very well could be 5). However, why is $A_{11}$ being counted twice? Mathematically, the sum over $i$ and $j$ would not allow this.

![screenshot](https://github.com/networkx/networkx/assets/47676848/b56d9dc6-d25d-48c7-9389-b3616e92d44b)

**Comment by ArturoSbr** [comment]
Hello all!

I went back and did some research on some entry-level literature.

In the words of Newman, a self-edge counts double "_because every self-edge from i to i has two ends, both of which are connected to vertex i_".

This means that $A_{11} = 2$, which in turn implies that $k_i = 5$ and $\sum_{ij} A_{ij} \delta(C_i, C_j) = 10$. Hence, your definitions are correct!

I cannot close the issue, but now we know you guys are right!

Thank you for your time!

**Comment by rossbar** [comment]
Thanks for sharing your detailed work and findings @ArturoSbr ! IIUC this issue is resolved, so I will close it - please feel free to reopen if I misinterpreted!
