### ISSUE TITLE
Add Python features that started with v3.10 now that v3.9 support is dropped

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#7036]
I looked at the changes in Python 3.10 to see what we could now use and noticed:
- [ ] the `match` statement which is a super-powerful switch/case system.
- [x] the `|` operator acts with classes now (as this PR implements). The result is like a tuple combining classes in e.g. `isinstance(obj, class1 | class2)`
  * Note: automatically handled by `ruff` `UP` rules in #7028
- [x] `itertools.pairwise` is now available (probably making our utility `pairwise` obsolete, but I haven't checked the details yet.

This issue should be considered done when someone has looked at these issues, not when all possible changes are considered. Otherwise this would stay around forever. Feel free to add other features of interest that I missed.

See #7028 [Edited to add this link]

**Comment by rossbar** [comment]
Linking to #5423 which discusses the `pairwise` bullet explicitly.

**Comment by rossbar** [comment]
Also, the [match statement](https://peps.python.org/pep-0636/) is a really exciting feature!

**Comment by jarrodmillman** [comment]
See #7028.

**Comment by eriknw** [comment]
`zip(x, y, strict=True)` is pretty handy ([see here](https://docs.python.org/3.10/library/functions.html#zip)).

**Comment by rossbar** [comment]
The "automatic" features have already been handled by `pyupgrade` - the other more involved changes (e.g. using the match statement) should be handled on a case-by-case basis, so I'll go ahead and close this tracking issue!
