### ISSUE TITLE
conda python 3.8 pulls networkx 3.2

### ISSUE THREAD

**Issue by jeremyleung521** [networkx/networkx#7039]
`conda install networkx` using python 3.8 will pull networkx=3.2 despite dropped support. This does not occur when running `pip install networkx`. Both the default solver and libmamba solvers produce the same result. 

I suspect the `noarch/networkx-3.2-pyhd8ed1ab_0.conda` [file](https://anaconda.org/conda-forge/networkx/files) might have to be removed from `conda-forge` using procedures from https://conda-forge.org/docs/maintainer/updating_pkgs.html#removing-broken-packages.

### Current Behavior

`conda install networkx` will solve for networkx 3.2 despite dropped support. This will lead to #7033 when running `import networkx`.

```
# See environment section below for the full thing
The following NEW packages will be INSTALLED:

  networkx           conda-forge/noarch::networkx-3.2-pyhd8ed1ab_0 


Proceed ([y]/n)? 
```

```
# Error after installing networkx 3.2 on python 3.8 via conda
(test-env) user$ python
Python 3.8.18 | packaged by conda-forge | (default, Oct 10 2023, 15:46:56) 
[Clang 16.0.6 ] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import networkx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/user/miniconda3/envs/test-env/lib/python3.8/site-packages/networkx/__init__.py", line 35, in <module>
    from networkx import generators
  File "/Users/user/miniconda3/envs/test-env/lib/python3.8/site-packages/networkx/generators/__init__.py", line 5, in <module>
    from networkx.generators.atlas import *
  File "/Users/user/miniconda3/envs/test-env/lib/python3.8/site-packages/networkx/generators/atlas.py", line 54, in <module>
    ATLAS_FILE = importlib.resources.files("networkx.generators") / "atlas.dat.gz"
AttributeError: module 'importlib.resources' has no attribute 'files'

```

### Expected Behavior

`conda install networkx` should pull 3.1 on python 3.8.

### Steps to Reproduce

```
conda create -y -n test-env python=3.8
conda activate test-env
conda install networkx
```

### Environment

Python version: Python 3.8.18
NetworkX version: 3.2
Tested manually on `arm64-osx` but it's occurring on `ubuntu-latest` as well.

```
(test-env) user$ conda list
# packages in environment at /Users/user/miniconda3/envs/test-env:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.8                h3422bc3_4    conda-forge
ca-certificates           2023.7.22            hf0a4a13_0    conda-forge
libffi                    3.4.2                h3422bc3_5    conda-forge
libsqlite                 3.43.2               h091b4b1_0    conda-forge
libzlib                   1.2.13               h53f4e23_5    conda-forge
ncurses                   6.4                  h7ea286d_0    conda-forge
openssl                   3.1.3                h53f4e23_0    conda-forge
pip                       23.3.1             pyhd8ed1ab_0    conda-forge
python                    3.8.18          h2469fbe_0_cpython    conda-forge
readline                  8.2                  h92ec313_1    conda-forge
setuptools                68.2.2             pyhd8ed1ab_0    conda-forge
tk                        8.6.13               hb31c410_0    conda-forge
wheel                     0.41.2             pyhd8ed1ab_0    conda-forge
xz                        5.2.6                h57fd34a_0    conda-forge

(test-env) user$ conda install networkx
Channels:
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/user/miniconda3/envs/test-env

  added / updated specs:
    - networkx


The following NEW packages will be INSTALLED:

  networkx           conda-forge/noarch::networkx-3.2-pyhd8ed1ab_0 


Proceed ([y]/n)? n


CondaSystemExit: Exiting.
```

### Additional context

Thanks!

**Comment by jarrodmillman** [comment]
Conda doesn't follow the upstream releases closely. We ran into a similar problem with scikit-image. I pinned this so other can see it more easily. If they aren't updating the minimum Python versions, I suspect they aren't updating our other minimum dependencies either. I wonder how they were able to get the tests to pass with Python 3.8? Or do they not tests their releases?

**Comment by MridulS** [comment]
I fixed the min python versions https://github.com/conda-forge/networkx-feedstock/pull/52, but I still need to patch the repo-feedstocks so this doesn't show up. I'll send in a PR later today. We need to turn off auto-merges on networkx conda-forge feedstocks.

**Comment by MridulS** [comment]
I have created a repo-data-patch https://github.com/conda-forge/conda-forge-repodata-patches-feedstock/pull/578 which should fix this issue. Thanks for the detailed report @jeremyleung521!
