### ISSUE TITLE
weisfeiler_lehman_graph_hash different for isomorphic graphs

### ISSUE THREAD

**Issue by luvrgz** [networkx/networkx#7102]
Hello,
I notice that the hash provided by the method weisfeiler_lehman_graph_hash can be different for two graphs with same attributes when attributes are 0.0 or -0.0.

### Current Behavior

When I put nodes or edges attributes, the Weisfeiler Lehman hash is different even when the method is_isomorphic is True.

### Expected Behavior

The two hashs given by the weisfeiler_lehman_graph_hash method should be the same.

### Steps to Reproduce

Here is a small example to reproduce:

```
import networkx
from networkx.algorithms import isomorphism
nodes_s1 = [('0'), ('1'), ('2')]
edges_s1 = [('0', '1', {'x': -0.0}),
                ('0', '2', {'x': 1.0}),
                ('1', '2', {'x': 1.0})]

nodes_s2 = [('2'), ('3'), ('4')]
edges_s2 = [('2', '3', {'x': 0.0}),
                ('2', '4', {'x': 1.0}),
                ('3', '4', {'x': 1.0})]

 g1 = nx.Graph()
 g1.add_nodes_from(nodes_s1)
 g1.add_edges_from(edges_s1)

 g2 = nx.Graph()
 g2.add_nodes_from(nodes_s2)
 g2.add_edges_from(edges_s2)

 key = lambda x, y: x["x"] == y["x"]
 print(isomorphism.is_isomorphic(g1, g2, edge_match=key))  # True

 print(nx.weisfeiler_lehman_graph_hash(g1, edge_attr="x"))  # 5d623f95408d5605f51ee221c8b02478
 print(nx.weisfeiler_lehman_graph_hash(g2, edge_attr="x"))  # b7ebdb05048840dac74934c87e3845d9
```

### Environment

Python version:  3.10.9
NetworkX version:  2.8.4

**Comment by rossbar** [comment]
`-0.0` and `0.0` are numerically equivalent but may not hash the same. If you change the `-0.0` attribute in edges_s1 to 0.0 then the hashes are equivalent.

**Comment by dschult** [comment]
Floating point numbers are tricky that way.  
Changing the weights to integers also works (as does multiplying the floating point by 10000 and converting to int -- which is often good enough).

**Comment by luvrgz** [comment]
Ok thank you very much! 
I finnaly preprocess my data to change all -0.0 to 0.0 and indeed it works well now. I was just confuse about the resulting hashs whereas the provided labels where (almost) equal. I understand that the issue come from floating-point hash function, but it can be very confusing that isomorphic graphs have different hashs.
I close the issue but i just wanted to notice networkx users of this behaviour (I personnaly spent one day debugging it).
