### ISSUE TITLE
Unhandled Exceptions in `panther_similarity`, `simrank_similarity`, `preferential_attachment` and `jaccard_coefficient`

### ISSUE THREAD

**Issue by iany0** [networkx/networkx#7108]
Hello, \
I've encountered a few corner cases while using Link Prediction and Similarity Measures Algorithms that lead to exceptions that aren't currently handled.
### 1. Panther Similarity ValueError with Isolated Nodes
- **Current Behavior**: 
  - Executing `nx.panther_similarity` on a graph with isolated nodes results in `ValueError: probabilities contain NaN`. This issue might be arising due to the presence of an isolated node.
- **Steps to Reproduce**:
```python
G = nx.Graph()
G.add_node(1)
G.add_edges_from([(2, 3), (3, 4), (4, 5), (5, 6)])
nx.panther_similarity(G, source = 2)
```

### 2. SimRank Similarity ValueError Instead of NodeNotFound
- **Current Behavior**: 
  - Calling `nx.simrank_similarity` on a graph where node 7 does not exist results in `ValueError: 7 is not in list`.
- **Expected Behavior**: 
  - The function should raise a `NodeNotFound` exception for better clarity when a non-existent node is specified.
- **Steps to Reproduce**:
```python
G = nx.Graph()
G.add_edges_from([(1, 1),(1, 2), (1, 3), (4, 5), (5, 6)])
nx.simrank_similarity(G, source=7)
```

### 3. Preferential Attachment TypeError and Incorrect Exception
- **Current Behavior**: 
  - Using `nx.preferential_attachment` raises `TypeError: 'int' object is not iterable` and `NetworkXError: nbunch is not a node or a sequence of nodes`.
- **Expected Behavior**: 
  - The function should raise a `NetworkXError: v is not in the graph` for non-existent nodes in the pairs provided.
- **Steps to Reproduce**:
```python
G = nx.Graph()
G.add_edges_from([(1, 1),(1, 2), (1, 3), (4, 5), (5, 6)])
preds = nx.preferential_attachment(G, [(1, 2),(3, 7)])
for u, v, p in preds:
    print(f"Preferential Attachment between nodes {u} and {v}: {p}")
```

### 4. Jaccard Coefficient KeyError for Non-existent Node
- **Current Behavior**: 
  - Executing `nx.jaccard_coefficient` where node `7` does not exist in `G` results in `KeyError: 7`.
- **Expected Behavior**: 
  - The function should raise a `NetworkXError: v is not in the graph` for non-existent nodes in the pairs provided.
- **Steps to Reproduce**:
```python
G = nx.Graph()
G.add_edges_from([(1, 1),(1, 2), (1, 3), (4, 5), (5, 6)])
preds = nx.jaccard_coefficient(G, [(1, 2),(3, 7)])
for u, v, p in preds:
    print(f"Jaccard similarity between nodes {u} and {v}: {p}")
```

### Environment

Python version: 3.9.10 \
NetworkX version: 3.2.1

**Comment by Schefflera-Arboricola** [comment]
@iany0 Thanks! I've made a PR for this :)
