### ISSUE TITLE
`nx.configuration_model` + `nx.Graph` = degree distribution not preserved

### ISSUE THREAD

**Issue by miticollo** [networkx/networkx#7119]
### Current Behavior

```python
nx.configuration_model(degree_sequence, create_using=nx.Graph(), seed=12346)
```
The above statement must be produce an undirected graph with the degree sequence specified in `degree_sequence`.

![282475859-a134fe4e-c01e-480e-9d2d-8d9e3e17cc72](https://github.com/networkx/networkx/assets/30465144/e18cb1d0-d06a-4d76-b1e3-739dfff20114)

```text
G1.#edges = 4
G1.#avg_degree = 1.6
G.#edges = 5
G.#degree_sequence = [3, 2, 1, 2, 2]
G.#avg_degree = 2.0
```

### Expected Behavior

It doesn't it.

### Steps to Reproduce

```python
G = nx.Graph()
G.add_edge(0,1)
G.add_edge(0,2)
G.add_edge(0,3)
G.add_edge(1,4)
G.add_edge(3,4)
degree_sequence = [d for _,d in G.degree()]
G1: nx.Graph = nx.configuration_model(degree_sequence, create_using=nx.Graph(), seed=12346)
print("G1.#edges =", G1.number_of_edges())
print("G1.#avg_degree =", np.mean([d for _,d in G1.degree()]))
print("G.#edges =", G.number_of_edges())
print("G.#degree_sequence =", degree_sequence)
print("G.#avg_degree =", np.mean(degree_sequence))

fig, axes = plt.subplots(nrows=1, ncols=2)
ax = axes.flatten()
nx.draw(G1, ax=ax[0], with_labels=True)
ax[0].set_axis_off()
ax[0].title.set_text('G1')
nx.draw(G, ax=ax[1], with_labels=True)
ax[1].set_axis_off()
ax[1].title.set_text('G')
plt.show()
```

### Environment

OS: Manjaro
Python version: 3.11.5
NetworkX version: 3.2.1

### Additional context

Two days ago I opened [a question](https://github.com/networkx/networkx/discussions/7112) and it seems that this is a bug.

**Comment by rossbar** [comment]
Let's keep the discussion in #7112 since creating the issue loses the context, i.e. the existing responses. Issues/Discussions is not really an important distinction in this case (contributors who watch the respository will be notified of activity on either).
