### ISSUE TITLE
neighbors function returns iterator, not list

### ISSUE THREAD

**Issue by vxld100** [networkx/networkx#7124]
### Current Behavior

As of right now networkx.neighbors(graph, node) returns a `dict_keyiterator` object, and not a `list` as stated on the [official documentation](https://networkx.org/documentation/stable/reference/generated/networkx.classes.function.neighbors.html).

### Environment

Python version: 3.11.5
NetworkX version: 3.2.1

### Example

```
import networkx as nx

line = "Hitchhiker's Guide to the Galaxy, The (2005)/Fry, Stephen (I)/Stanley, Jack (III)/Plaskitt, Nigel/Gatiss, Mark/Gomez, John (II)/Donn, Ray/Blackner, Danny/Jennings, Garth/Walker, Patrick (III)/Longhurst, Mark/Bodrozic, Milo/Jones, Simon (I)/Blake, Jerome (I)/Wilson, Mak/Bailey, Bill (IV)/Solle, Sean/Woodington, Albie/Uttley, Ben/Grindle, Steve/Griffiths, Richard (I)/Hewitt, Art/McNeice, Ian/Stuart, Ashley/Nathaniel, Paul/Lennon, Thomas (III)/Ball, Mason/Def, Mos/Wright, Edgar/Shearsmith, Reece/Freeman, Martin (II)/Schwartzman, Jason/Rockwell, Sam/Dawson, Martin/Davis, Warwick (I)/Nouri, Mohsen/Thrift, James/Kay, Ian (II)/Riley, Jessie/Horseman, Rob/Rickman, Alan/Hibbs, Simon/Ellis, Dan (III)/Freeman, Aron/Nighy, Bill/Wollen, William/Lewis, Mike (VIII)/Malkovich, John/Stevens, Tucker/Perrin, Tim/Pemberton, Steve/Johnston, Rich/Stevenson, Mark (II)/Parham, Ollie/Wilding, Spencer/Lynn, Jim/McInness, Nikki/Elliot, Su/Fay, Cecily/Adams, Polly Jane/Chancellor, Anna/Burroughs, Hayley/Kubaisi, Zoe/Deschanel, Zooey/Belson, Jane/Bennett, Sarah/Mirren, Helen/Bruce, Lynn Robertson/Gossling Valerio, Susie/Jackson, Dominique/Macdonald, Kelly (I)"

graph = nx.Graph()

movie_info = line.split('/')
title = movie_info[0] 
performers = movie_info[1:]

for p in performers:
    graph.add_edge(title, p)

def get_list_of_performers(g, title):
    performers = nx.neighbors(g, title)
    print(type(performers))

def main():
    get_list_of_performers(graph, "Hitchhiker's Guide to the Galaxy, The (2005)")

if __name__ == "__main__":
    main()
```

output:
`<class 'dict_keyiterator'>`

expected output:
`<class 'list'>`

### Edit

I would like to bring attention to the inadequacy of source code explanations in the documentation, particularly evident in functions like [neighbors(G, n)](https://networkx.org/documentation/stable/_modules/networkx/classes/function.html#neighbors). The provided source code lacks ANY insight into the implementation details of the function, making it challenging for users to grasp the underlying mechanics. This essentially defeats the purpose of having documentation in the first place.

**Comment by Schefflera-Arboricola** [comment]
there is a PR open to fix this (https://github.com/networkx/networkx/pull/5565)

**Comment by vxld100** [comment]
I'm confused. This PR is open since almost 2 years.

**Comment by MridulS** [comment]
Yes, sometimes PR's fall through the cracks :)

https://networkx.org/documentation/stable/reference/classes/generated/networkx.Graph.neighbors.html#networkx.Graph.neighbors has a better documentation of the `neighbors` function.

The `networkx.neighbors` function just uses `Graph.neighbors(n)`, anyway thanks for pointing this out! We will try to merge the updated docs asap :)
