### ISSUE TITLE
Document walk_type in directed_laplacian and friends

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#7147]
The current documentation of the "walk_type" argument to the many directed laplacian matrix approaches is opaque. And the logic is hidden within the actual code because it occurs in a helper function presumably so the logic is the same for all these functions. The logic should be fairly straightforward to explain. For the directed graph case it is given in `linalg.laplacianmatrix._transition_matrix` as
```python
    if walk_type is None:
        if nx.is_strongly_connected(G):
            if nx.is_aperiodic(G):
                walk_type = "random"
            else:
                walk_type = "lazy"
        else:
            walk_type = "pagerank"
```
We should put a word description of this into the `walk_type` parameter description..

**Comment by mahamtariq58** [comment]
I want to work on this issue. Kindly assign me this issue.

**Comment by dschult** [comment]
You may submit a PR or a comment here if you have further questions. 
We are small enough that we don't assign PRs. :)
Thanks!!
