### ISSUE TITLE
Invalid link in girth docs - missing close parenthesis )

### ISSUE THREAD

**Issue by johnflavin** [networkx/networkx#7150]
### Current Behavior

The HTML documentation for the [girth](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.cycles.girth.html) function contains an invalid link. The URI is valid in the [source code docstring](https://github.com/networkx/networkx/blob/9cc8b422a512e7e7819238d597fd6815ec9c1c8e/networkx/algorithms/cycles.py#L1205) from which the HTML is generated.

In the docstring, the URI ends with a close parenthesis `)` character:
```
    References
    ----------
    .. [1] https://en.wikipedia.org/wiki/Girth_(graph_theory)
```
In the generated HTML for the docs, the close parenthesis `)` character is outside the link, making the link invalid.
```
<p><a class="reference external" href="https://en.wikipedia.org/wiki/Girth_(graph_theory">https://en.wikipedia.org/wiki/Girth_(graph_theory</a>)</p>
```

### Additional context

I'm sure this is an issue upstream when the docs are being generated. I was initially going to report this to sphinx instead of here. However, I decided to report it here instead for two reasons:
1. I don't know if the issue is with sphinx itself or the autodoc extension. I would look in the build logs for the networkx docs build job, but I don't know how to find that. I figured someone more familiar with maintaining networkx would know how and where to find those logs to dig for more information.
2. If there is some upstream update that fixes this issue, networkx would need to bump a dependency version to include that fix. So it still makes sense to open an issue here.

**Comment by dschult** [comment]
Thanks for this!  It makes me wonder about our other Wikipedia links — which often end with a close paren.
;)

**Comment by MridulS** [comment]
This is indeed probably an upstream issue, a quick fix here is to use a properly ASCII encoded url like 
https://github.com/networkx/networkx/blob/9cc8b422a512e7e7819238d597fd6815ec9c1c8e/networkx/algorithms/connectivity/edge_kcomponents.py#L84
or make sphinx links like `` `Wikipedia: Matching <https://en.wikipedia.org/wiki/Matching_(graph_theory)>`_ ``
