### ISSUE TITLE
AttributeError: module networkx has no attribute from_scipy_sparse_array

### ISSUE THREAD

**Issue by qureshinomaan** [networkx/networkx#7158]
Hi, 
I have been facing this issue which I am unable to solve : AttributeError: module networkx has no attribute from_scipy_sparse_array

Has anyone faced a similar issue? 

### Environment

Python version:
NetworkX version:

**Comment by MridulS** [comment]
Make sure to update your networkx version :)

**Comment by rossbar** [comment]
Thanks @MridulS ! I'll close as resolved since this is very likely the correct answer. If the issue persists, please reopen and provide the requested information about the networkx and python version!
