### ISSUE TITLE
NetworkX has a logical problem on subgraph isomorphism

### ISSUE THREAD

**Issue by mdindoost** [networkx/networkx#7170]
### Current Behavior
finding isos less than expected! for my graphs it finds 7
NetworkX version: 3.1
NetworkX subgraph_isomorphism found ISOs: 7
Subgraph isomorphisms found:
{3: 0, 4: 1, 1: 2, 5: 3}
{3: 0, 4: 1, 1: 2, 8: 3}
{4: 0, 5: 1, 2: 2, 9: 3}
{7: 0, 4: 1, 8: 2, 1: 3}
{8: 0, 5: 1, 9: 2, 2: 3}
{8: 0, 7: 1, 4: 2, 6: 3}
{9: 0, 8: 1, 5: 2, 7: 3}

### Expected Behavior
it should find 15 isos!
VF2 subgraph_isomorphism run and this is the found ISOs: 15
[1 3 4 7]
[1 3 4 0]
[2 4 5 8]
[2 4 5 1]
[3 4 1 5]
[3 4 1 8]
[4 8 7 5]
[4 1 3 0]
[4 5 2 9]
[5 2 4 1]
[7 4 8 5]
[7 4 8 1]
[8 7 4 6]
[8 5 9 2]
[9 8 5 7]

### Steps to Reproduce
 import networkx as nx
    
    # Creating directed graphs
    G = nx.DiGraph()
    H = nx.DiGraph()

    # Clearing graphs (optional in this context)
    G.clear()
    H.clear()

    # Adding nodes and edges to directed graphs
    G.add_nodes_from(range(0, 10))
    G.add_edges_from([(3, 0), (1, 3), (4, 1), (2, 4), (5, 2), (3, 4), (4, 5), 
                      (3, 7), (7, 6), (4, 8), (5, 9),(1, 0),(2,1),(8, 7), (7,4), (8, 5), (9,8)])

    H.add_nodes_from(range(0, 4))
    H.add_edges_from([(0, 1), (1, 2), (2, 0), (1, 3)])
    #H.add_edges_from([(3, 1), (1, 2), (2, 3), (1, 0)])

    node_label = 'NodeLabel'
    edge_label = 'EdgeLabel'
    nx.set_node_attributes(G, node_label, 'label1')
    nx.set_edge_attributes(G, edge_label, 'Y1')

    nx.set_node_attributes(H, node_label, 'label1')
    nx.set_edge_attributes(H, edge_label, 'Y1')
    

    # Find subgraph isomorphisms of H in G
    GM = nx.algorithms.isomorphism.DiGraphMatcher(G, H)
    subgraph_isomorphisms = list(GM.subgraph_isomorphisms_iter())

    print("NetworkX subgraph_isomorphism found ISOs:", len(subgraph_isomorphisms))
    print("Subgraph isomorphisms found:")
    for iso in subgraph_isomorphisms:
        print(iso)

Run the code
### Environment

Python version: 3.8.3
NetworkX version:3.1

### Additional context
During my implementation of the VF2 code based on the author's paper. I found something odd in your code. please take a look at these graphs. your current implementation gives 7 found which is 8 less than what I expected. I even checked with authors' implementation and ullmann algorithm both gave me 15 isos. I took a look at your code and it seems you already found the first mistake on the 2004 paper describing candidate generation. I think your mistake comes from the second misunderstanding point which is in describing the RNEW feasibility condition and the way you describe and implement it. 

![photo_2023-12-16_14-36-02](https://github.com/networkx/networkx/assets/120276281/2b3e0b8f-fb14-47ab-8bdb-1b0fa204400c)

**Comment by dschult** [comment]
It looks like you are expecting "subgraph monomorphisms" instead of what we call "subgraph isomorphisms" which could also be called "induced subgraph isomorphisms".  The monomorphisms let you find a subset of the nodes and edges of the original graph.  The subgraph isomorphism requires that the subsets of edges include all edges from the original graph connecting the nodes in the subgraph -- that is, the result must be an induced subgraph of the original graph.

Change your line as follows and it should work:
```python
subgraph_isomorphisms = list(GM.subgraph_monomorphisms_iter())
```

**Comment by mdindoost** [comment]
Thanks.

**Comment by rossbar** [comment]
Thanks for the answer @dschult . I'm inclined to close this as completed since the question was addressed. Perhaps a summary of terminology could be added to the `isomorphism` package docs, including `:term:`'s to link to the glossary.
