### ISSUE TITLE
Should `is_distance_regular` and `intersection_array` have @not_implemented_for?

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#7172]
Something I noticed while reviewing #5849 :

The docstrings for [`is_distance_regular`](https://github.com/networkx/networkx/blob/d68caf64b057f3c5f0adf4f09ce3843e4f2395c4/networkx/algorithms/distance_regular.py#L21) and [`intersection_array`](https://github.com/networkx/networkx/blob/d68caf64b057f3c5f0adf4f09ce3843e4f2395c4/networkx/algorithms/distance_regular.py#L114) state that they are only defined for undirected graphs; however, the implementations do not check the type of the graph. The functions and definitions should be reviewed to determine whether these should get the `not_implemented_for` decorator.

**Comment by dschult** [comment]
It looks like those two functions use `@not_implemented_for("directed", "multigraph")` which is almost certainly a bug that should be written:
```python
@not_implemented_for("directed")
@not_implemented_for("multigraph")
```
See #6904 for others that should be checked too.
