### ISSUE TITLE
"to_scipy_sparse_array" invents non-existing edges

### ISSUE THREAD

**Issue by GregorySchwing** [networkx/networkx#7173]
### Current Behavior

Generating a networkx graph from an edgelist and then converting it to a CSR shouldn't invent new edges.

In example, edge (0,1) is added to CSR.

### Expected Behavior

CSR should accurately represent the network graph.

### Steps to Reproduce

[Link_to_collab](https://colab.research.google.com/drive/1opbidhuOqSZ-iycnXEGuwLpTYh2-z04_?usp=sharing)

**Edge list**
[(0, 2), (0, 11), (1, 2), (1, 10), (2, 3), (3, 4), (3, 6), (4, 5), (5, 6), (6, 7), (4, 8), (7, 9), (8, 9), (10, 11)]
14
**Edge list in networkX graph object**
[(0, 2), (0, 11), (2, 1), (2, 3), (11, 10), (1, 10), (3, 4), (3, 6), (4, 5), (4, 8), (6, 5), (6, 7), (7, 9), (8, 9)]
14
**CSR Matrix Representation:**
  **(0, 1)	1**
  (0, 2)	1
  (1, 0)	1
  (1, 3)	1
  (1, 5)	1
  (2, 0)	1
  (2, 4)	1
  (3, 1)	1
  (3, 4)	1
  (4, 2)	1
  (4, 3)	1
  (5, 1)	1
  (5, 6)	1
  (5, 7)	1
  (6, 5)	1
  (6, 8)	1
  (6, 10)	1
  (7, 5)	1
  (7, 8)	1
  (7, 9)	1
  (8, 6)	1
  (8, 7)	1
  (9, 7)	1
  (9, 11)	1
  (10, 6)	1
  (10, 11)	1
  (11, 9)	1
  (11, 10)	1
[ 1  2  0  3  5  0  4  1  4  2  3  1  6  7  5  8 10  5  8  9  6  7  7 11
  6 11  9 10]
[ 0  2  5  7  9 11 14 17 20 22 24 26 28]

### Environment

Python version: 3.10.12
NetworkX version: 3.2.1

**Comment by dschult** [comment]
There is a difference between the integers you see in the matrix and the integers you see as the nodes of the graph. In the sparse array, the indices are the row number of the node, while in the networkx graph the integers are the objects that represent the nodes. The order of the rows is determined by the order those nodes were added to the graph.

To simplify things, you should provide a `nodelist` argument to `nx.to_scipy_sparse_array` function.  To match what you seem to expect make it `nodelist=range(12)` or something like that (untested).  Then the row numbers will match the python objects you are using for nodes.
:)

**Comment by GregorySchwing** [comment]
Thanks
