### ISSUE TITLE
Add function to produce edges in all simple paths (migrated from Trac #732)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#718]
Original ticket https://networkx.lanl.gov/trac/ticket/732
Reported 2012-06-12 by @hagberg, assigned to trac user sergionery.

The all_simple_paths() function produces nodes.  Add a function that produces the edges with optional data.

This ticket continues #713.

**Comment by amirc** [comment]
Hi,
Any chance that someone still has the file simple_paths9.py ?
I'm looking for it because I'm trying to do something similar to this  [question](https://groups.google.com/forum/#!topic/networkx-discuss/DYck64hoxGI).

Thanks,
Amir.

**Comment by jfinkels** [comment]
To get the paths as edges, you can do something like

```python
>>> import networkx as nx
>>> G = nx.complete_graph(4)
>>> for p in map(nx.utils.pairwise, nx.all_simple_paths(G, 0, 3)):
...     print(list(p))
... 
[(0, 1), (1, 2), (2, 3)]
[(0, 1), (1, 3)]
[(0, 2), (2, 1), (1, 3)]
[(0, 2), (2, 3)]
[(0, 3)]
```
If you are not using the development version of NetworkX, you can implement pairwise yourself by doing something like `pairwise = lambda l: zip(l, l[1:])`.
