### ISSUE TITLE
not well-formed (invalid token): line 9242, column 48

### ISSUE THREAD

**Issue by myrainbowandsky** [networkx/networkx#7187]
Ubuntu 22.04
python 3.10.13
nx: 3.2.1

i saved 5 graphs  as xx.gexf or graphml , there were no problem.

When i read them with nx.read_gexf or nx.graphml, three of them  raised : `not well-formed (invalid token): line 9242, column 48`, the other two are OK . weird

**Comment by dschult** [comment]
Maybe look at line 9242 column 48 and see if there is a strange character or a different structure than expected. The different graph formats are quite different so it's not such a surprise that some files have the invalid token and the others don't.  Without more information,we can't really help. You are in the debugging stage. Look where the errors say there is a problem and see what part of the graph is causing trouble. Then make a very simple graph with just that part. You might figure it out from that. If not, post the small example here and we can recreate it to see if something is wrong with the files or the code. :}

**Comment by myrainbowandsky** [comment]
Thank you. Yes, strange characters appear. I replaced them with others. it is OK.
