### ISSUE TITLE
Drawing fails as ```TypeError: '_AxesStack' object is not callable```

### ISSUE THREAD

**Issue by CNelias** [networkx/networkx#7206]
When I try to plot any type of graph created with networkx, I always get the ```TypeError: '_AxesStack' object is not callable``` error.
There was a similar issue opened in 2022, but none of the proposed solutions managed to fix the issue on my machine.

### Steps to Reproduce

Take the example from the documentation:
```
import matplotlib.pyplot as plt

G = nx.dodecahedral_graph()

nx.draw(G)  # networkx draw()

plt.draw()  # pyplot draw()
```
it returns
```
Traceback (most recent call last):

  Cell In[10], line 5
    nx.draw(G)  # networkx draw()

  File ~\anaconda3\lib\site-packages\networkx\drawing\nx_pylab.py:113 in draw
    if cf._axstack() is None:

TypeError: '_AxesStack' object is not callable
```

Matplotlib version: 3.7.1
Python version: 3.10.9
NetworkX version: 3.1

**Comment by rossbar** [comment]
I suspect you are not actually using NetworkX v3.1 - this was [fixed in NX v2.8.6](https://github.com/networkx/networkx/pull/5937) and will work as expected with all matplotlib >=3.6. I suggest double-checking your environment to ensure you are actually getting the library versions you expect!
