### ISSUE TITLE
No attributes 'from_numpy_matrix' and 'to_numpy_matrix'

### ISSUE THREAD

**Issue by HripsimeS** [networkx/networkx#7239]
Hello,

I am trying to run the following script and I received the errors below.
https://github.com/Yaxin-Cui/Graph-Neural-Network/blob/main/code/graphstellar_updated.py

**AttributeError: module 'networkx' has no attribute 'from_numpy_matrix'**
**AttributeError: module 'networkx' has no attribute 'to_numpy_matrix'**

Can you please help me to figure our what I should modify in the code to run it without that errors. Thanks in advance!

**Comment by Schefflera-Arboricola** [comment]
Hi @HripsimeS, `to_numpy_matrix` and `from_numpy_matrix` were depreciated and removed in this PR( https://github.com/networkx/networkx/pull/5746). And in this PR(https://github.com/networkx/networkx/pull/4093) all the internal usages of `to_numpy_matrix` and `from_numpy_matrix` in networkx were replaced with `to_numpy_array` and `from_numpy_array` respectively. So, doing this renaming in your script might resolve this issue. Thanks!

**Comment by rossbar** [comment]
Thanks @Schefflera-Arboricola ! I will close this as resolved as this is indeed the correct solution.
