### ISSUE TITLE
Contributing.md details with setup not included

### ISSUE THREAD

**Issue by DreadTheNaught** [networkx/networkx#7246]
### Current Version

One setup step from CONTRIBUTING.md doesn't include step/link to download relevant dependencies: 
- pip install -r requirements/default.txt -r requirements/test.txt -r requirements/developer.txt : You have to install Rust and Cargo beforehand which should be mentioned

### Expected Behavior

Contributing should have included a message telling users to have rust installed and relevant links

Python version: 3.11.1
NetworkX version: 3.3rc0.dev0

**Comment by rossbar** [comment]
NetworkX is a pure Python package and does not require rust to be installed. If you have gotten warnings related to a rust requirement from following the contributing guide, please provide additional info about your system OS.

**Comment by DreadTheNaught** [comment]
No problem, my OS is windows 11 22H2.

**Comment by MridulS** [comment]
Could you also give an exact traceback of the error? This error is probably coming from one of the many dependencies in the `requirements/default.txt`, `requirements/test.txt`, `requirements/developer.txt` that are being installed with that command.

**Comment by rossbar** [comment]
Any follow-up here @DreadTheNaught ? I'm certain this isn't an NX issue so I'm inclined to close, but if you've managed to track down specifically what happened during environment setup it may be worth documenting.

**Comment by rossbar** [comment]
I'll go ahead and close this as "not an nx issue", but if you figure out precisely what happened in your environment @DreadTheNaught please feel free to post here in case any other users run into this issue!
