### ISSUE TITLE
problem with cycle_basis

### ISSUE THREAD

**Issue by ValeriaIM** [networkx/networkx#7272]
### Current Behavior

Hello, I'm having problems using the function cycle_basis(G).
It finds some of the basic cycles incorrectly - cycles of greater length are found (see picture).

![bug](https://github.com/networkx/networkx/assets/50073123/cc80801d-51fa-4460-a379-f0d58c266e9b)

### Expected Behavior

I expected that there would be cycles:
11 - 12 - 22
22 - 12 - 21
22 - 21 - 16
20 - 1 - 18
15 - 2 - 20
5 - 4 - 15

But instead, cycles were found accordingly:
[11, 12, 13, 19, 17, 14, 23, 9, 10]
[22, 12, 13, 19, 17, 14, 23, 9]
[22, 21, 14, 23, 9]
[20, 1, 0, 13, 19]
[15, 2, 1, 0, 13, 19]
[5, 4, 3, 2, 1, 0, 13, 19, 17]

That is, it finds the first two vertices correctly, and then covers a larger cycle than necessary

### Steps to Reproduce

I checked that all the edges are being passed correctly, so (as my opinion) the problem is in the function. The example from the image includes the following edges:

19 - 21
3 - 15
5 - 6
8 - 9
15 - 20
18 - 19
11 - 22
5 - 17
4 - 5
13 - 0
1 - 18
6 - 17
17 - 19
1 - 20
17 - 21
2 - 3
16 - 21
21 - 22
14 - 21
2 - 20
11 - 12
6 - 7
6 - 23
19 - 20
10 - 11
12 - 21
9 - 16
15 - 19
14 - 16
5 - 15
10 - 22
2 - 15
12
4 - 15
14 - 17
12 - 13
9 - 10
0 - 18
18 - 20
16 - 22
9 - 22
8 - 23
13 - 19
6 - 14
0 - 1
13 - 21
9 - 23
16 - 23
12 - 22
14 - 23
3 - 4
7 - 23
7 - 8

When creating it I used the following functions:
self.G = nx.Graph()
self.G.add_edges_from(self.E)
cycles = nx.cycle_basis(self.G)

### Environment

Python version: 3.11.5
NetworkX version: 3.2.1

**Comment by ValeriaIM** [comment]
In my case, most cycles are less than 5, so if there was a cycle with a length >= 5, I used the cycle search function from the point nx.cycle_basis(self.G, cycle[0]). The number of incorrect cycles has decreased, but is still not equal to 0

**Comment by rossbar** [comment]
Let me just preface by saying I'm certainly no expert, so apologies if I've misdiagnosed the issue!

I suspect the confusion may arise from the exact definition of a cycle basis. From the docstring (emphasis mine):

> A basis for cycles of a network is a minimal collection of
> cycles such that any **cycle** in the network can be written
> as a sum of cycles in the basis.  Here summation of cycles
> is defined as "exclusive or" of the edges.

Note that a cycle basis is not the minimal collection of cycles that will cover every *edge* in the graph, but the minimal collection of cycles necessary to represent all other *cycles* in the graph.

In this specific case, this means e.g. the cycle `[11, 12, 13, 19, 17, 14, 23, 9, 10]` cannot be constructed from a combination of any other cycles in the cycle basis. Verifying that this is true would be the next step in determining whether there is a bug.

---

It may also help to look at a simpler example, e.g. `wheel_graph`:

```python
>>> G = nx.wheel_graph(10)
>>> pos = nx.spring_layout(G, iterations=200, seed=0xdeadc0de)
>>> nx.draw(G, pos=pos, with_labels=True)
```
![wheel](https://github.com/networkx/networkx/assets/1268991/bfdb896e-5fe0-45c5-b0ab-f151c6a9d667)

And it's cycle_basis:

```python
>>> cb = nx.cycle_basis(G)
>>> cb
[[0, 1, 9],
 [0, 2, 1],
 [0, 3, 2],
 [0, 4, 3],
 [0, 5, 4],
 [0, 6, 5],
 [0, 7, 6],
 [8, 7, 6, 5, 4, 3, 2, 1, 9],
 [0, 8, 9]]
```

This may seem surprising: there is a "long" cycle in this basis too. If you think about it though, this is perfectly valid as there are multiple ways to represent the cycle basis. One way (perhaps the more obvious) is to take the collection of 3-cycles composed of a pair of adjacent nodes on the "rim" and the central "axle" node. In this case, the "rim" cycle is computed by summing each of the 3-cycles. However, the above basis is equally valid: the "rim" cycle is included explicitly, and the cycle `[0, 7, 8]` (the "missing" 3-cycle) can be constructed from summing the rim cycle and `[0, 7, 6]` and `[0, 8, 9]`, bearing in mind "summing" in this means taking the symmetric difference of edge sets. Both cycle bases are "minimal" in that they contain the same number of cycles.

In any case - I suspect this is what is happening in your original example too. However, if there is a cycle basis that has fewer cycles than the one returned above (i.e. the original cycle basis is not minimal) or it can be shown that not *every* cycle can be constructed from summing those in the original basis (i.e. it's not actually a cycle basis) then there is indeed a real bug!

**Comment by ValeriaIM** [comment]
You are absolutely right, sorry - it's my fault that I forgot the definition of basic cycles.  Thank you, I double-checked - the quantity is the same and I can get the missing cycles from others

**Comment by boothby** [comment]
Note that we do have an implementation to find minimum-weight cycle bases.

https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.cycles.minimum_cycle_basis.html

**Comment by ValeriaIM** [comment]
Thank you so much, you are amazing!

вт, 6 февр. 2024 г., 02:47 Kelly Boothby ***@***.***>:
