### ISSUE TITLE
python3.10 -m pip install -e . 3.2.1 results in "ROR: Could not find a version that satisfies the requirement 3.2.1 (from versions: none) ERROR: No matching distribution found for 3.2.1"

### ISSUE THREAD

**Issue by JPeetz** [networkx/networkx#7275]
Hello,

would anyone have any idea for this, please.

Cant't install networkx 3.2.1

### Expected Behavior

no issue installing 3.2.1

### Steps to Reproduce

python3.10 -m pip install -e . 3.2.1
Defaulting to user installation because normal site-packages is not writeable
Obtaining file:///home/jpeetz/networkx
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Installing backend dependencies ... done
  Preparing editable metadata (pyproject.toml) ... done
ERROR: Could not find a version that satisfies the requirement 3.2.1 (from versions: none)
ERROR: No matching distribution found for 3.2.1

### Environment

Ubuntu 22.04

Python version: 3.10
NetworkX version:

**Comment by MridulS** [comment]
I'm not even sure if `python3.10 -m pip install -e . 3.2.1` should work?

Maybe you could try git check out the 3.2.1 tag and then install?
```
$ git checkout networkx-3.2.1
$ python3.10 -m pip install -e .
```

**Comment by rossbar** [comment]
Indeed the original incantation doesn't make sense - you can either install from a package index like PyPI *or* from source, but not both.

If you want to install version 3.2.1 from a package repository, you'd do something like `pip install networkx==3.2.1`. If you want to install version 3.2.1 from source, then indeed @MridulS 's suggestion is the correct one.

**Comment by JPeetz** [comment]
> Indeed the original incantation doesn't make sense - you can either install from a package index like PyPI _or_ from source, but not both.
> 
> If you want to install version 3.2.1 from a package repository, you'd do something like `pip install networkx==3.2.1`. If you want to install version 3.2.1 from source, then indeed @MridulS 's suggestion is the correct one.

That did the trick for me, thank you both very much indeed, appreciated.
