### ISSUE TITLE
Measures for weighted networks (migrated from Trac #744)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#730]
Original ticket https://networkx.lanl.gov/trac/ticket/744
Reported 2012-07-12 by unknown, assigned to @hagberg.

Upon detailed inspection I found out that networkx does not support any measures for weighted networks. A possibility could be to implement the algorithms in TNet of Tore Opsahl. 

I have implemented a weighted version of density on group and individual level. I will try to contribute accordingly.

**Comment by MridulS** [comment]
@hagberg 
We can start by implementing these measures: http://en.wikipedia.org/wiki/Weighted_network#Measures_for_weighted_networks
What do you think?

**Comment by pabloem** [comment]
This seems like something I'd like to tackle in a SoC project. I guess this would mean reimplementing some of these measures to work on networks with link weights different than zero, correct? (e.g. degree of a node, closeness, betweenness,...), and maybe implementing new ones that are specific for weighted networks (e.g. random network-generating algorithms..). Does this make sense?
If you're ok with it, I can start looking into the methods for network measures, and prepare a proposal on making them weight-aware.
Any advice or comments here will be welcome!

**Comment by hagberg** [comment]
Closed due to inactivity.
