### ISSUE TITLE
contextily.add_basemap failing in some geospatial gallery examples

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#7301]
Followup issue to #7299 - the `contextily.add_basemap` had been intermittently failing in some of the geospatial gallery examples, e.g. `plot_lines.py` and `plot_delaunay.py`. These have been temporarily renamed to stop them from running during the doc build to avoid CI blockers (#7299). I haven't looked into it in detail, but my initial guess would be it has to do with a network timeout or some other issue accessing resources over the web. A full traceback can be found at the [end of this log](https://github.com/networkx/networkx/actions/runs/7916641025/job/21610909161#step:7:3889).

@ljwolf I know this isn't specifically a geopandas issue, but is this something you've encountered before?

#7299 should be reverted once a fix is found!

**Comment by ljwolf** [comment]
I haven't seen this error before, but it looks like something easy to replicate/fix. I'll take a look. Also, tagging @martinfleis in case he can get to it sooner than me!

**Comment by martinfleis** [comment]
That is the same issue that showed up in our CI today https://github.com/geopandas/contextily/actions/runs/7909639251/job/21591004622 It seems to be cause by some network issue and, in our case, simply re-triggering CI fixed it. 

Have you encountered the issue in any other case than that single time linked above?

**Comment by martinfleis** [comment]
I've seen this one first time today, so I'm not entirely sure what's causing it. The easiest solution may be changing the source of the baseline that is used. If it is caused by the server that is serving the tiles, different one might be a solution. 

Are you aware of any difference between CircleCI and GHA that could cause this?

**Comment by rossbar** [comment]
> Are you aware of any difference between CircleCI and GHA that could cause this?

No, not concretely though different runtime limits might have an effect. In further testing I was able to also intermittently reproduce it locally so CI configuration is not the root cause.

**Comment by martinfleis** [comment]
I'll have a look if we can build some additional robustness to contextily. We do have retries on request but if the request returns invalid data like in this case, we do not try to fetch the tile again. I suppose we should.

**Comment by rossbar** [comment]
Maintainer note: both #7299 and #7324 need to be reverted to re-enable all docstring examples that are affected by this issue!

**Comment by martinfleis** [comment]
I am having a really hard time trying to reproduce the issue. I've seen it once in `contextliy` CI and found it a couple of times in your CI but am unable to reproduce it locally. I will implement more robust retries, ensuring that another attempt is made not only if request fails but also if image read fails (this case) but have no idea how to test if it solves the issue...

**Comment by rossbar** [comment]
Thanks @martinfleis - for now I think we'll just try/except the `add_basemap` calls and close this issue. Would you prefer we open one in contextily too? Re: the failure - I still suspect this is something specifically to do with CI: these examples get run on every PR & push, and any downloaded assets for the examples are not cached, so if `add_basemap` is downloading info I suspect our CI requests are being throttled/403'd.

**Comment by martinfleis** [comment]
That would show up as error 403 in the Traceback. I have a PR in contextily that would automatically retry tile download if this error happens but have no clue if it actually solves the issue.
