### ISSUE TITLE
Reciprocity for networks and nodes (migrated from Trac #745)

### ISSUE THREAD

**Issue by networkx-trac** [networkx/networkx#731]
Original ticket https://networkx.lanl.gov/trac/ticket/745
Reported 2012-07-12 by @plotti, assigned to @hagberg.

I noticed that there is no reciprocity measure both for the overall network and for each node. Since this measure is quite handy it should be implemented.

**Comment by jfinkels** [comment]
Here is [Wikipedia's definition of reciprocity][1].

[1]: http://en.wikipedia.org/wiki/Reciprocity_%28network_science%29

**Comment by hagberg** [comment]
Need to add to reference documentation.

**Comment by dschult** [comment]
#1895 added the docs
