### ISSUE TITLE
Pydot export fails for nodes with colons in their data.

### ISSUE THREAD

**Issue by aurorabam** [networkx/networkx#7331]
### Current Behavior

>>> import networkx as nx
>>> nx.nx_pydot.write_dot(graph, "/tmp/asdf")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/opt/homebrew/lib/python3.11/site-packages/networkx/utils/decorators.py", line 770, in func
    return argmap._lazy_compile(__wrapper)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<class 'networkx.utils.decorators.argmap'> compilation 5", line 5, in argmap_write_dot_1
    import itertools
             ^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/networkx/drawing/nx_pydot.py", line 51, in write_dot
    P = to_pydot(G)
        ^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/networkx/drawing/nx_pydot.py", line 265, in to_pydot
    raise ValueError(
ValueError: Node names and attributes should not contain ":" unless they are quoted with "".                For example the string 'attribute:data1' should be written as '"attribute:data1"'.                Please refer https://github.com/pydot/pydot/issues/258
>>> 

### Expected Behavior

A beautiful DOT graph of my networkx graph is exported to /tmp/asdf.

### Steps to Reproduce

```
import networkx as nx
import yaml
import frozendict

dct = yaml.safe_load('''
name: John
age: 30
automobiles:
- brand: Honda
  type: Odyssey
  year: 2018
- brand: Toyota
  type: Sienna
  year: 2015
''')

graph = nx.DiGraph()
graph.add_node(frozendict.deepfreeze(dct))
nx.nx_pydot.write_dot(graph, "/tmp/asdf")
```

### Environment

I'm running this on my apple macbook.

Python version: Python 3.11.7
NetworkX version: 3.2.1

### Additional context

Thank you so much for this incredible tool, which I have found to be extremely valuable for operating on my data.

I have come to get to the point of wanting to draw the diagrams into graphviz or any other, and hit this snag.

I realize that I'm probably not using the library quite as intended; when I found out that node data needed to be hashable I used frozendict to freeze the data rather than just creating a 'proper' python3 object, which by default is hashable. Consequently I have some code now written where I'm using dictionary semantics rather than object semantics, and it will be quite the refactor to fix this problem.

If you do consider the error message, about having a colon in data but no quotes around it, to be a bug in networkx (I can imagine other reasons possibly that we might want to have a colon in node data, unrelated to my being mr. hasty 2024 in his workarounds) then I figured I would let you know about it ahead of refactoring my code in case it makes doing that obsolete.

Thank you so much and again, this is a quite brilliant library, fast, efficient, and a great interface. Thank you.

**Comment by dschult** [comment]
The error message seems to say that you can use colons as long as you put them inside double quotes.
I interpret that as meaning you need your string to have this line:
```
- "brand:Honda"
```

This is a workaround for a problem in pydot.  If you can use the pygraphviz library instead it would not have that restriction. NetworkX has a similar interface to both those routes to graphviz. :)

**Comment by rossbar** [comment]
Indeed this is an upstream issue with pydot: pydot/pydot#258. IMO the exception message is clear and includes the workaround - I'm not sure what else NetworkX can do to handle this other than hard-code a workaround, but that becomes tricky to maintain and a likely point where more bugs would be introduced. I will close this as dupcliate of #4663
