### ISSUE TITLE
Missing documentation for output of ```optimal_edit_paths``` function

### ISSUE THREAD

**Issue by paolotron** [networkx/networkx#7353]
### Current Behavior

The current description in the documentation for the ```optimal_edit_paths``` function is:

```
    edit_paths: list of tuples (node_edit_path, edge_edit_path)
         node_edit_path : list of tuples (u, v) edge_edit_path : list of tuples ((u1, v1), (u2, v2))
    cost : numeric
         Optimal edit path cost (graph edit distance).
```
while it states the type of output, there is no explanation on how to interpret the result.
On stackoverflow there is a [question](https://stackoverflow.com/questions/73696000/how-to-interpret-the-output-of-networkx-optimal-edit-paths) where users don't know how to interpret the output of such function.

**Comment by dschult** [comment]
I agree that this doc_string should be improved. 
The best description of graph edit paths I have found is buried in the doc_string of a function defined within a function -- and thus not available outside of the source code.  Perhaps it can kick-start a better description for the main doc_string.

<this is from the `get_edit_paths` function defined in `optimize_edit_paths`>
```
      Returns:
            sequence of (vertex_path, edge_path, cost)
                vertex_path: complete vertex edit path
                    list of tuples (u, v) of vertex mappings u<->v,
                    u=None or v=None for deletion/insertion
                edge_path: complete edge edit path
                    list of tuples (g, h) of edge mappings g<->h,
                    g=None or h=None for deletion/insertion
                cost: total cost of edit path
            NOTE: path costs are non-increasing
 ```
