### ISSUE TITLE
DiGraph.clear() is not clearing the graph content

### ISSUE THREAD

**Issue by Hasena386** [networkx/networkx#7368]
Hi,

DiGraph.clear() is not clearing content of graph as expected. It should return an empty graph as per specification but this function is just returning the whole graph content.

For now I am initialising using nx.DiGraph().  

I get this error on Google Collab notebook. I encountered this error in my recent project where I am converting a XML tree into Networkx graph using python and extracting/re-constructing subtrees from the graph.

Thanks and Cheers,
Kala

**Comment by mohamedrezk122** [comment]
Can you provide a minimal reproducible example, to see where the issue is ?
