### ISSUE TITLE
Graph name attribute for `complete_bipartite_graph` verbose for non-integer intputs

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#7396]
The `complete_bipartite_graph` creation function adds a `.graph["name"]` attribute like so:

https://github.com/networkx/networkx/blob/cca1a715217a102b970800c43a066dd759ece92d/networkx/algorithms/bipartite/generators.py#L65

This works fine when `n1` and `n2` are integers, but can get ugly when they aren't. For example:

```python
# Generator expressions designed to be intentionally verbose
>>> n = (i for i in range(4))
>>> m = (i for i in range(4, 7))
>>> G = nx.complete_bipartite_graph(n, m)
>>> print(G)
Graph named 'complete_bipartite_graph(<generator object <genexpr> at 0x7e94bc447370>, <generator object <genexpr> at 0x7e94bc5352f0>)' with 7 nodes and 12 edges
```

**Comment by mohamedrezk122** [comment]
The expected behavior should be printing the length of the generator, right ?

**Comment by Schefflera-Arboricola** [comment]
> The expected behavior should be printing the length of the generator, right ?

Usually it's `Graph with 7 nodes and 12 edges`

**Comment by mohamedrezk122** [comment]
> Usually it's `Graph with 7 nodes and 12 edges`

This is a bipartite graph, so i guess n1 and n2 refers to the two  node sets.
I think it should be 
`complete_bipartite_graph(4,3) with 7 nodes and 12 edges`
