### ISSUE TITLE
keys added as edge attributes when using nx.from_pandas_edgelist

### ISSUE THREAD

**Issue by RiccardoBasilone** [networkx/networkx#7444]
Hi there,
regarding the nx.from_pandas_edgelist function, when creating multigraphs:

### Current Behavior

Following the example in the documentation, but calling "edge_attr = True" instead of "edge_attr=["weight", "color"]", the edge keys get added to the graph not only as keys, but also as edge attributes.
i.e G.edges(data=True) outputs:
`MultiEdgeDataView([(0, 2, {'my_edge_key': 'A', 'weight': 3, 'color': 'red'}), (0, 2, {'my_edge_key': 'D', 'weight': 6, 'color': 'blue'}), (2, 1, {'my_edge_key': 'B', 'weight': 4, 'color': 'blue'}), (2, 3, {'my_edge_key': 'C', 'weight': 5, 'color': 'blue'})])`
I do not think this is intended behavior, as edge keys are not edge attributes. 
In other words If we start with a multigraph and save it to a pandas edgelist using `nx.to_pandas_edgelist()`, the graph we load from that same edgelist in this way has an extra attribute (my_edge_key).

### Expected Behavior
keys should only be added as keys, as is what happens when you manually specify which columns are edge_attr.

### Steps to Reproduce

`edges = pd.DataFrame(
    {
        "source": [0, 1, 2, 0],
        "target": [2, 2, 3, 2],
        "my_edge_key": ["A", "B", "C", "D"],
        "weight": [3, 4, 5, 6],
        "color": ["red", "blue", "blue", "blue"],
    }
)`

`
G = nx.from_pandas_edgelist(
    edges,
    edge_key="my_edge_key",
    edge_attr=["weight", "color"],
    create_using=nx.MultiGraph(),
)
`

### Environment

NetworkX version: 3.2.1

**Comment by rossbar** [comment]
I agree that this is undesirable behavior, thanks for the report!
