### ISSUE TITLE
Add config option to disable the cache warning message, update warning to include instructions on how to disable

### ISSUE THREAD

**Issue by rlratzel** [networkx/networkx#7456]
As discussed by @dschult , @eriknw , and @rlratzel at PyCon US 2024, the current behavior of warning users when they enable caching to inform them that changing graph attributes after the converted graph is cached will result in a stale cached value seems adequate for now and possibly longer-term.  However, to improve the UX, the following updates were proposed:

* Add a config option to allow users to disable the warning.
  * This will let users easily disable only this particular warning, without the need to add code (if they use the config env var or other front-end option such as .yaml, .ini, etc.)
  * This defaults to `False`, so users still have to knowingly disable this warning and therefore are more likely to understand the limitations of caching.

* Update the warning message to include instructions on using the above config option to disable the warning.

**Comment by eriknw** [comment]
Here is a command to disable this warning:
```python
warnings.filterwarnings("ignore", "Using cached graph", UserWarning, "networkx.utils.backends")
```

**Comment by eriknw** [comment]
Completed in #7497. Closing.
