### ISSUE TITLE
designated points shortest path problem？How to implement

### ISSUE THREAD

**Issue by everyday-gao** [networkx/networkx#7457]
### Environment

Python version:
NetworkX version:

**Comment by dschult** [comment]
There isn't enough information to know what the question is here.  Please edit the original post to explain your issue. (you can delete the default headings if they aren't appropriate)

**Comment by Openegg15** [comment]
Hello, I can't get your result :( could you make a short explanatory video?
▶️ https://l.eggfi.io/

**Comment by cyschneck** [comment]
This is a spam/virus link. Do not click on it. I reported the user/comment

**Comment by cyschneck** [comment]
> Hello, I can't get your result :( could you make a short explanatory video?
> 
> ▶️ https://l.eggfi.io/

You can close this issue, this user is just fishing for spam/virus

**Comment by everyday-gao** [comment]
Find the shortest route from the starting point to the endpoint, which should include multiple required nodes and edges

**Comment by dschult** [comment]
This issue is closed and we need more info. Can you open a new issue and give a small example with description?
