### ISSUE TITLE
edgelist reader removes deliminators if deliminator is white-space and file has empty fields [BUG]

### ISSUE THREAD

**Issue by carissableker** [networkx/networkx#7462]
This `line.strip` without an argument, means a white-space delimited file (e.g. tab, which is quite common) with  empty edge attribute(s) in the last column(s) results in a crash with error `Edge data [...] and data_keys [...] are not the same length`. 
   
https://github.com/networkx/networkx/blob/729bec23b10e89b5f6d37175e30484f2278107c4/networkx/algorithms/bipartite/edgelist.py#L222

An example file that would crash:

```
A	B	interaction	2
B	C	interaction	4
C	A	interaction	
```
The last line ends in `\t\n`, and both are striped instead of just the `\n`. This is inconsistent, as the same data in a different order of columns works fine, e.g.:
```
A	B	2	interaction
B	C	4	interaction
C	A		interaction
```

# Fix

    s = line.rstrip("\n").split(delimiter)

is the safe fix, and is cross OS compatible in Python (https://peps.python.org/pep-0278/)

**Comment by dschult** [comment]
Thanks for this!
It looks like the same code idiom is used in `networkx/readwrite/edgelist.py` line 250.
So the fix should be applied there too.
