### ISSUE TITLE
`shortest_path_length()` specifies return value of `int` but was `float`

### ISSUE THREAD

**Issue by davidhuser** [networkx/networkx#7467]
### Current Behavior

if `shortest_path_length` is used with weights containing `float`, a `float` is returned, contrary to the function docs.

```python
import networkx as nx

G = nx.DiGraph()

G.add_node(0)
G.add_node(1)
G.add_node(2)

G.add_edge(0, 1, weight=3.33333)
G.add_edge(1, 2, weight=4.75555)

length = nx.shortest_path_length(G, source=0, target=2, weight='weight', method='dijkstra')
print(length)
print(type(length))
```

```
8.08888
<class 'float'>
```

### Expected Behavior

According to the documentation I would expect an integer or a `ValueError`, as it specifies that an `int` is returned -- see [docs](https://networkx.org/documentation/stable/_modules/networkx/algorithms/shortest_paths/generic.html#shortest_path_length) and [code](https://github.com/networkx/networkx/blob/729bec23b10e89b5f6d37175e30484f2278107c4/networkx/algorithms/shortest_paths/generic.py#L225-L229)

however, the underlying function used here, `dijkstra_path_length`, [specifies](https://github.com/networkx/networkx/blob/729bec23b10e89b5f6d37175e30484f2278107c4/networkx/algorithms/shortest_paths/weighted.py#L205-L208) that a "number" is returned.

Perhaps this is a documentation bug? Are float in edge weights supported (with the caveat of floating point issues)?

### Steps to Reproduce

see above

### Environment

Python version: Python 3.12.3
NetworkX version: 3.3

**Comment by dschult** [comment]
Thanks for this!  The docs are indeed incorrect here. It should return a number of iterator, not specifically an `int` or iterator.  It goes all the way back to #744 before which it is correctly called a number.  

NetworkX supports `float` edge weights with the usual caveats of floating point issues.
Thanks!

**Comment by KoushikNekkanti** [comment]
Hi @dschult,

I'm new to this project and would love to contribute to this issue. I'm interested in working on this issue. Is it still available? ,Could you provide some guidance on how to get started?

Thanks!

**Comment by dschult** [comment]
We dont assign issues to individual developers -- you can start looking at an issue. When you have a solution open a PR. Or open a PR with a partial solution and we'll give feedback. (actually we'll give feedback either way. :)

This one might be a good one to start with. To start, you should read through the developer section of the docs, especially the contributor guide.
