### ISSUE TITLE
`is_d_seperator` doesn't allow empty set in z

### ISSUE THREAD

**Issue by KevinTheRainmaker** [networkx/networkx#7476]
### Current Behavior

<img width="600" alt="image" src="https://github.com/networkx/networkx/assets/76294398/e00b65d8-0e1e-47a6-a98b-7925941160e0">

Official documentation says that the z parameter in is_d_separator allows an empty set.
However, I encountered issue that it doesn't allow the empty set in z.

`model.nodes` -> `NodeView(('D', 'A', 'G', 'C', 'B', 'E', 'F'))`
`print(nx.is_d_separator(model,x={'D'},y={'G'},z={}))` -> `NodeNotFound: One of x, y, or z is not a node or a set of nodes in G`

### Expected Behavior

`print(nx.is_d_separator(model,x={'D'},y={'G'},z={}))` -> `False`

### Steps to Reproduce

```
import networkx as nx

model = nx.DiGraph([
    ('D','A'),
    ('A','G'),    
    ('C','A'),
    ('C','B'),
    ('B','E'),
    ('F','E'),
])

print(nx.is_d_separator(model,x={'D'},y={'G'},z={}))
```
### Environment

Python version: 3.10.0
NetworkX version: 3.3

**Comment by KoushikNekkanti** [comment]
Hello Maintainer,

I hope you're doing well! I came across this issue and I'm really interested in contributing to it. Would it be alright if I work on this issue by making the necessary code changes and submitting a pull request?

Looking forward to your response!

Thanks!

**Comment by dschult** [comment]
Unfortunately, `{}` is a dict.... not a set.  To get an empty set you need to use `set()`.

**Comment by KevinTheRainmaker** [comment]
@dschult Thx for your comment. However, `print(not(nx.is_d_separator(model,x={'A'},y={'B'},z=())))` or `print(not(nx.is_d_separator(model,x=('A'),y=('B'),z=())))` are also doesn't work.

**Comment by KevinTheRainmaker** [comment]
Oh, literally `set()` is working.. Thx

**Comment by TernaryM01** [comment]
Just had the exact same issue. Used code from a book. Using {} actually works until NetworkX version 3.2.1. I suggest the documentation be clearer on what it means by "empty set", or at least give an example below with z being the empty set. Many Python users have no idea that {} is not a proper empty set and that there is such a thing as set() for constructing the empty set.

**Comment by dschult** [comment]
Yes -- an example in the doc_string that uses `set()` should help a lot. Thanks!
