### ISSUE TITLE
docs: several links in Citing section seem to have expired 

### ISSUE THREAD

**Issue by epogrebnyak** [networkx/networkx#7479]
The specific links in https://networkx.org/documentation/stable/#citing to PDF and *Exploring network structure, dynamics, and function using NetworkX*  seem to have expired - for example https://conference.scipy.org/proceedings/SciPy2008/paper_2/ is not lobger valid.

Would be nice to fix the link, if it still exists. I looked up http://conference.scipy.org.s3-website-us-east-1.amazonaws.com/proceedings/scipy2008/ - but there is no NetworkX paper there.

**Comment by Peiffap** [comment]
@epogrebnyak the links you need are:

- For the conference proceedings: http://conference.scipy.org.s3-website-us-east-1.amazonaws.com/proceedings/scipy2008/index.html
- For the NetworkX paper: http://conference.scipy.org.s3-website-us-east-1.amazonaws.com/proceedings/scipy2008/paper_2/
- For the PDF: http://conference.scipy.org.s3-website-us-east-1.amazonaws.com/proceedings/scipy2008/paper_2/full_text.pdf
- For the BibTex entry: http://conference.scipy.org.s3-website-us-east-1.amazonaws.com/proceedings/scipy2008/paper_2/reference.bib

Let me know if you want to add these yourself or if you want me to do it.

**Comment by rossbar** [comment]
@Peiffap a PR here would be welcome!
