### ISSUE TITLE
Fix the docs of `strong_product`

### ISSUE THREAD

**Issue by Schefflera-Arboricola** [networkx/networkx#7510]
### Issue

The definition of the [strong_product](https://networkx.org/documentation/stable/reference/algorithms/generated/networkx.algorithms.operators.product.strong_product.html) operator in the docs is a bit inaccurate. (Discussed in https://github.com/networkx/networkx/discussions/7509)

### Fix

Fix the docs and check if the results of `strong_product` align with the [correct definition](https://en.wikipedia.org/wiki/Strong_product_of_graphs).

Thank you :)

**Comment by sanchitram1** [comment]
@Schefflera-Arboricola are you able to review #7511? should be clearer
