### ISSUE TITLE
Clarification of `networkx.karate_club_graph()` Dataset

### ISSUE THREAD

**Issue by Schefflera-Arboricola** [networkx/networkx#7519]
> From what I can tell, the "club" entries in the karate club data uses "Club After Fission" (Column 4) of Table 1, which is repeated as "Club After Split From Data" (column 5) in Table 3 of the original paper, which does indeed have "Mr. Hi's" at the 9th row (accommodating for the change of index from 1-based to 0-based), so I don't think there's a bug here. In fact, in comments on #5820, both @dschult and @rossbar confirm this. 

_Originally posted by @ivanov in https://github.com/networkx/networkx/discussions/7515_

### Ref.:
- [`karate_club_graph` docs](https://networkx.org/documentation/stable/reference/generated/networkx.generators.social.karate_club_graph.html)
- Discussion https://github.com/networkx/networkx/discussions/7515 
- issue #5820

**Comment by mbbolger** [comment]
Hi @Schefflera-Arboricola, I'd be happy to take this if it's still open.

From reading the discussions and the original paper, it seems that something like the below needs to be added to `karate_club_graph()` in `networkx/generators/social.py`:

```
The dataset is derived from the 'Club After Split From Data' column of Table 3 in the source paper (see below). 
The Table 3 column was in turn derived from the 'Club After Fission' column of Table 1 in the same paper. 
Note that the nodes are 0-indexed in NetworkX, but 1-indexed in the paper (the 'Individual Number in Matrix C' column of Table 3 starts at 1).
This means, for example, that G.nodes[9]["club"] returns 'Officer', which corresponds to row 10 of Table 3 in the paper.
```

I'll make the change if you feel this covers it.

**Comment by Schefflera-Arboricola** [comment]
@mbbolger please feel free to create a PR :)

**Comment by mbbolger** [comment]
PR made @Schefflera-Arboricola

https://github.com/networkx/networkx/pull/7626

Let me know if it needs further work from my side
