### ISSUE TITLE
wrong citation for dominance algorithms

### ISSUE THREAD

**Issue by marksantcroos** [networkx/networkx#7522]
### Current Behavior

In https://github.com/networkx/networkx/blob/main/networkx/algorithms/dominance.py the current citation is non-existing:
```
.. [1] K. D. Cooper, T. J. Harvey, and K. Kennedy.
           A simple, fast dominance algorithm.
           Software Practice & Experience, 4:110, 2001.
```

### Expected Behavior

The correct citation is:
```
K.D. Cooper, T.J. Harvey, and K. Kennedy, “A Simple, Fast Dominance Algorithm,” Rice University, Department of Computer Science Technical Report 06-33870, 2006.  [pdf version](http://www.cs.rice.edu/~keith/Publications/TR06-33870-Dom.pdf)
```
Taken from the first authors personal website at http://keith.rice.edu/publications-2/technical-reports/

**Comment by dschult** [comment]
Thanks for this!
We have trouble with personal websites becoming non-existant too.  What do you think of:

Cooper, Keith D., Harvey, Timothy J. and Kennedy, Ken. "A simple, fast dominance algorithm." (2006).
https://hdl.handle.net/1911/96345

**Comment by marksantcroos** [comment]
Even better!

**Comment by marksantcroos** [comment]
Thanks!
