### ISSUE TITLE
Graph becomes invalid after node removal

### ISSUE THREAD

**Issue by Old-Shatterhand** [networkx/networkx#7523]
### Current Behavior

When removing a node from a networkx graph using G.remove_node(...), the graph becomes somehow invalid as the internal node-indices become unstable.

### Expected Behavior

After removing a node, the graph should still work fine as before.

### Steps to Reproduce

```
import networkx as nx

G = nx.path_graph(5)
nx.set_node_attributes(G, {i: i for i in range(5)}, 'idx')
G.remove_node(2)
idx3 = [i for i, node in enumerate(G.nodes) if G.nodes[node]["idx"] == 4][0]
print(G.nodes[idx3]["idx"])
```
### Environment

Conda environment with

Python version: 3.11
NetworkX version: 3.3

### Additional context

It would be really nice, if networkx would reassign the internal node labels after removing the nodes. Or if there would be a function to call manually after removing plenty of nodes. If that does not run into issues because the graph becomes invalid after the first removal.

**Comment by dschult** [comment]
In what sense is the graph invalid? You don't show any error or what the value of `idx3` is.  What are you expecting and what do you get?  I get the response `3`...  Which is what I expect.

**Comment by Old-Shatterhand** [comment]
Yes, you're right, I got confused over indices and node names.
