### ISSUE TITLE
VF2PP subgraph monomorphism

### ISSUE THREAD

**Issue by mdindoost** [networkx/networkx#7564]
### Discussed in https://github.com/networkx/networkx/discussions/7563

<div type='discussions-op-text'>

<sup>Originally posted by **mdindoost** July 16, 2024</sup>
Is there a function based on the VF2++ algorithm for finding subgraph monomorphism?</div>

**Comment by dschult** [comment]
I'm going to close this in favor of the discussion pointed to above.
