### ISSUE TITLE
compute a random_regular_graph(N,K) but the adjacency matrix is totally wrong

### ISSUE THREAD

**Issue by BitBute01** [networkx/networkx#7580]
I will show my code to reproduce the issue. Thank you for your attention.

# 设置随机种子以获得可重复的结果
np.random.seed(42)  # 或者使用任何你喜欢的种子值

N = 10
K = 3

# 生成 k-正则图
graph = nx.random_regular_graph(K, N)

# 绘制图形
plt.figure(figsize=(6,3))
pos = nx.spring_layout(graph)
nx.draw(graph, pos, node_size=200, node_color='skyblue', with_labels=True, width=0.5)
plt.axis('off')

# 显示图形
plt.show()

# 计算并打印邻接矩阵以验证
adj_matrix = nx.adjacency_matrix(graph).todense()
print("邻接矩阵:")
print(adj_matrix)
![image](https://github.com/user-attachments/assets/146018eb-1d24-48df-9f40-060c3dd0a453)
![image](https://github.com/user-attachments/assets/32166354-4529-4f7f-84d7-33cf8d9e7b1a)

**Comment by Schefflera-Arboricola** [comment]
I think this is very similar to https://github.com/networkx/networkx/issues/7173. It was about `to_scipy_sparse_array` and `adjacency_matrix` also just calls `to_scipy_sparse_array` internally.

Explanation - https://github.com/networkx/networkx/issues/7173#issuecomment-1862152218

From the [docs](https://networkx.org/documentation/stable/reference/generated/networkx.linalg.graphmatrix.adjacency_matrix.html#networkx.linalg.graphmatrix.adjacency_matrix):
```
If you want a pure Python adjacency matrix representation try 
networkx.convert.to_dict_of_dicts which will return a dictionary-of-dictionaries 
format that can be addressed as a sparse matrix.
```

We should probably consider clarifying this a little better in our docs :}

Thank you @BitBute01 for raising this :)

**Comment by BitBute01** [comment]
@Schefflera-Arboricola Thank you， sir， as you said, I recover the classic adjacency relationship by calling nx.convert.to_dict_of_dicts(G), but can we obtain the algebraic adjacency matrix in a simple way by networkx ?   Thanks for your comments again!

**Comment by dschult** [comment]
Please look at [the previous question's answer](https://github.com/networkx/networkx/issues/7173#issuecomment-1862152218) as linked by @Schefflera-Arboricola .  You **are** getting the classical algebraic adjacency matrix. But you aren't specifying the node order for the matrix. See that answer.

**Comment by rossbar** [comment]
I will close this as hopefully *improved* by the examples added in #7627 - any other ideas for how the documentation can be improved are of course welcome!
