### ISSUE TITLE
`nx.drawing.nx_pydot.graphviz_layout` crashes on a node with `"\n"` in the name (on new pydot versions)

### ISSUE THREAD

**Issue by lkk7** [networkx/networkx#7581]
### Current Behavior

If a graph contains a node with a name containing `"\n"`, then calling `nx.drawing.nx_pydot.graphviz_layout()` on it crashes.

```
Traceback (most recent call last):
  File ".../script.py", line 29, in <module>
    pos = nx.drawing.nx_pydot.graphviz_layout(G, prog="dot")
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.12/site-packages/networkx/drawing/nx_pydot.py", line 322, in graphviz_layout
    return pydot_layout(G=G, prog=prog, root=root)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File ".../.venv/lib/python3.12/site-packages/networkx/drawing/nx_pydot.py", line 406, in pydot_layout
    node = node[0]
           ~~~~^^^
IndexError: list index out of range
```

### Expected Behavior
`nx.drawing.nx_pydot.graphviz_layout()` call on a graph with nodes that have `"\n"` in their names returns without any error.

### Steps to Reproduce
(see linked issue below for full crashing code)

### Environment
NetworkX version: latest
Pydot version `3.0.1`

### Additional context

The original issue was raised in pydot https://github.com/pydot/pydot/issues/396
An example script that crashes is in its description.
The true reason is on `pydot`'s side: there was a fix so that nodes are escaped and quoted only on their final output. 
In short, if you created a node with name `A\ntest`, earlier `node.get_name()` returned `"A\\ntest"` (quoted and escaped), and now it returns `A\ntest` (raw input) because that's what's expected. You want the original name.

Now, somehow the function `nx.drawing.nx_pydot.graphviz_layout` was dependent on the wrong behavior, so the fix broke it:  https://github.com/networkx/networkx/blob/main/networkx/drawing/nx_pydot.py#L335-L421

I wanted to fix that immediately. But I got stuck on the code – it's very complex.
To quote the comment from the issue:

> From what I can see, the `nx.drawing.nx_pydot.graphviz_layout` call:
> 1. Creates a Pydot graph (1) from a NetworkX graph (2)
> 2. Converts (1) to `.dot` (3)
> 3. Parses the (3) back to a new Pydot graph (4)
> 4. Iterates over (2)'s nodes, creates new Pydot nodes (5) from them and then uses (5)'s names to retrieve a node from the (4) graph. The error happens at that point, so what happens after is irrelevant.

It's pretty convoluted. I'll admit I still don't understand what is going on  here :smile: 
I was wondering if we could somehow simplify whatever `nx.drawing.nx_pydot.graphviz_layout` is doing, while at the same time fixing the problem.

Full additional context in: https://github.com/pydot/pydot/issues/396

**Comment by lkk7** [comment]
Update: I've prepared a fix: https://github.com/networkx/networkx/pull/7588

**Comment by rossbar** [comment]
>  I was wondering if we could somehow simplify whatever nx.drawing.nx_pydot.graphviz_layout is doing, while at the same time fixing the problem.

IMO this would be a very worthwhile endeavor, especially since y'all are doing so much work on pydot these days (awesome!). I haven't personally looked at `nx_pydot` all that much, but if there are opportunities to simplify and/or better integrate with pydot that'd be a big improvement.
