### ISSUE TITLE
Shortest path with weight=weight_function not uniquely identifying MultiEdges

### ISSUE THREAD

**Issue by ff781** [networkx/networkx#7582]
```py
import networkx as nx

# Create a multidigraph
G = nx.MultiDiGraph()

# Add edges with different weights
G.add_edge(0, 1, weight=5, key=0)
G.add_edge(0, 1, weight=2, key=1)

def f(u, v, d):
    print(u,v,d)
    return 1

# Find the shortest path
shortest_path = nx.shortest_path(G, source=0, target=1, weight=f)
#shortest_path = nx.shortest_path(G, source=0, target=1, weight='weight')
path_length = nx.shortest_path_length(G, source=0, target=1, weight='weight')

print(f"Shortest path: {shortest_path}")
print(f"Path length: {path_length}")
print(f"Edge data: {G.get_edge_data(0, 1)}")
```

Shortest path (djikstra by default), works fine with multigraphs and a single scalar weight value, but when using a function for the weight, only passes u,v,dict key->data, which makes it impossible in the weight_function to distinguish which multiedge is currently selected.

```py
0 1 {0: {'weight': 5}, 1: {'weight': 2}}
0 1 {0: {'weight': 5}, 1: {'weight': 2}}
Shortest path: [0, 1]
Path length: 2
Edge data: {0: {'weight': 5}, 1: {'weight': 2}}
```

i.e. this is the current output of the above code, while both multiedges are correctly traversed, they both get the same key->data dict, and thus it is not trivial to return the correct weight value.

A more reasonable behaviour would be to use the weight_function(u,v,k,d) or weight_function(u,v,{k:d}).

**Comment by dschult** [comment]
The output you describe is precisely what networkx is intended to provide.

When djikstra is finding the shortest_path, you will always want it to be choosing the multiedge with the smallest distance between those two nodes. Write your function to search through the multiedge key_dict to find the shortest edge and return the distance for that edge. 
```py
def f(u, v, kd):
    print(u,v,kd)
    return min(dd['weight'] for dd in kd.values())
```

If you are going to be doing this many times with the same multigraph, you should probably create a graph with each edge having the weight that is the minimal weight between those two edges.
```py
smallerG = nx.Graph((u, v, {'weight': min(dd['weight'] for dd in G[u][v].values())}) for u, v in G.edges()) 
```

**Comment by ff781** [comment]
Hm, maybe I didn't communicate that clearly with the code, since it just commented out the line using weight="weight", and the path_length=... line is not relevant here.

weight can also be a weight_func, which exactly takes (u,v,{k:d}), notice that it will not take key as an argument.

```
weight : None, string or function, optional (default = None)
        If None, every edge has weight/distance/cost 1.
        If a string, use this edge attribute as the edge weight.
        Any edge attribute not present defaults to 1.
        If this is a function, the weight of an edge is the value
        returned by the function. The function must accept exactly
        three positional arguments: the two endpoints of an edge and
        the dictionary of edge attributes for that edge.
        The function must return a number.
```

In multigraphs, this makes it impossible to distinguish the multiedges from each other, and return a multiedge-specific weight from the weight function.

**Comment by dschult** [comment]
It actually doesn't make it impossible to distinguish the multi-edges from each other. But you do have to use info from the original graph. You know `(u, v, {k:d})` for each edge in the path, and that's enough to find the shortest edge between those nodes. It is true that the format of the shortest path does not include the edge key as part of the return value. But you have all the information you need to find which edge key was chosen on every edge of the shortest path.  The one-liner code to form the path with edge keys is very similar to the one-liner code to construct a smaller graph over which to find the shortest paths (from comment above). 

Something like:
```python
edge_key_path = [(u, v, min(G[u][v].items(), key=lambda k, dd: dd.get('weight', 1))) for u, v in shortest_path)
```

But I would still recommend that you use `shortest_path` on the reduced graph that has only the shortest edges between each node-pair present.

```python
smallerG = nx.Graph((u, v, {'weight': min(dd['weight'] for dd in G[u][v].values())}) for u, v in G.edges()) 
```

**Comment by ff781** [comment]
Ok, yes, I kind of get the point now that the function isn't there to enable dynamic edge weights (dynamic in the sense they dynamically depend on the path taken till the current node) but just as a convenient function to map edges with more rich information to edge weights, I assume, so in that sense the edge reduction would probably make most sense. Thanks for your help.
