### ISSUE TITLE
Doc: visually hidden edge on gallery example Max Ind Set

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#7633]
An email bug report from edwin.van.der.klaauw@woodwing.com:

> I’m enjoying your documentation of NetworkX a lot.
>
> I just noticed something confusing on [this](https://urldefense.com/v3/__https:/networkx.org/documentation/stable/auto_examples/algorithms/plot_maximum_independent_set.html__;!!Bt8fGhp8LhKGRg!DfsARZwCPV2af182hhRJ-v7kPQYG3D84WVmxpm79hxm8lPQuMoFO4Mn6ielbnVqWln6VE5CYwM4r6zaT4SRsNMecL1LKpw$) page. That page gives an example plot of a graph that does not show the (6,1) edge.
>
> The reason is that the edge is visually exactly overlapped by edges (1,7) and (7,6) combined. As a result, looking at the plot alone, I can’t see that vertexes 1 and 6 are adjacent. The output is written as “Maximum independent set of G: {8, 1, 10, 3}”, which is correct. But then I started wondering why vertex 6 is not listed in that set. So, I started digging a bit.
>
> It turned out that the seed parameter value 39299899 causes it to plot in the confusing way. By picking a different value, the graph got plotted differently and the (6,1) edge became visible.
> 
> The graph currently plotted on the page for seed 39299899 shows 13 edges only (one is hidden). By picking seed 333222113 it shows 14 edges, now including the (6,1) edge.

I think we should choose a simple seed value like 42, but maybe I haven't looked at what that would produce.

**Comment by WoojinJung-04** [comment]
Hi everyone! I took care of this by changing the seed to 251134665. I did try from 1~100 but they were all unsuccessful, so I started changing the order of the vertices and it also worked with 134. But I lost progress in failing to save, and I just put random numbers in and 251134665 was what I found. It show 14 independent(not overlapping) vertices that without overlapping points.

[https://github.com/networkx/networkx/pull/7634/commits](url)

This is the first ever commit I've ever made to an open source project!
