### ISSUE TITLE
read_pajek issues with *edges and *arcs headers

### ISSUE THREAD

**Issue by fblamanna** [networkx/networkx#7640]
Since the Pajek format does treat in the same way the header _*arcs_ or _*edges_ to define the number of links in the network, the behaviour on `nx.read_pajek()` should be more clear about the real behaviour like the source code explains:

```
if l.lower().startswith("*edge"):
                # switch from multidigraph to multigraph
                G = nx.MultiGraph(G)
            if l.lower().startswith("*arcs"):
                # switch to directed with multiple arcs for each existing edge
                G = G.to_directed()
```
I would expect an optional parameter such as `create_using` as other import functions and let the file I am reading with either _*edge_ or _*arc_ header to avoid confusion.

**Comment by dschult** [comment]
I thought edges are undirected and arcs are directed. 
Do you understand that differently?

**Comment by rossbar** [comment]
Any followup here @fblamanna ? We'll need a concrete understanding of the Pajek semantics in order to determine whether anything needs to be changed.

**Comment by rossbar** [comment]
I'm going to go ahead and close this one for now - if there are any updates that clarify the Pajek data spec please share here and reopen!
