### ISSUE TITLE
Docs for Stable 3.4 Tutorial first result is a RunTimeWarning

### ISSUE THREAD

**Issue by dschult** [networkx/networkx#7671]
The [3.4 doc Tutorial](https://networkx.org/documentation/stable/tutorial.html) has a RunTimeWarning on its very first cell.
The RunTimeError occurs on importing networkx and it looks like a circular import error. The Warning states: 
```
/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/networkx/utils/backends.py:541: 
RuntimeWarning: Error encountered when loading info for backend parallel: 
cannot import name '_registered_algorithms' from partially initialized module 'networkx.utils.backends' 
(most likely due to a circular import) 
(/opt/hostedtoolcache/Python/3.11.10/x64/lib/python3.11/site-packages/networkx/utils/backends.py)
  backend_info = _get_backends("networkx.backend_info", load_and_call=True)
```

Looking back at the commit log (along with artifacts for the CI doc build) shows that this first started occurring with [PR 7585](https://github.com/networkx/networkx/pull/7585).  So we must have missed a circular import during review (we would have had to look at the tutorial of the docs artifact).

Can we find a circular import in [PR 7585](https://github.com/networkx/networkx/pull/7585)?

Thanks @rlratzel for noticing this!

**Comment by Schefflera-Arboricola** [comment]
Yes, I was looking into it.. it's something to do with `default_config`. I think we need to either change how we initiate it in nx-parallel's `get_info` (because of some recent change in networkx) or we need to change something in this networkx repository's code.

**Comment by dschult** [comment]
It looks like `backends_info` entries are set by "load_and_call"ing the entry_point. So if the backend's backend_info function imports networkx (which is not an unreasonable thing to do), it triggers an import of networkx which starts a circular import. This happens with nx-parallel.

We need to "load_and_call" the backend_info functions **after** the import of utils is finished to avoid circular import trouble.  

But that pushes back the config setting of BackendPriorities configs because those configs use the `backend_info` dict to check for valid values.  That is, we need to set up the config values after the backend_info values are set.

I've been able to get this working by putting code at the end of the `__init__.py` file.  This is where @eriknw originally had the config settings. But if we allow backends to import nx during the `backend_info` function call, we need to load `backend_info` values here too.

But it might be cleaner to separate the function definitions in backend.py and config.py from the actual setting of the values in `backend_info` and `config`.  Perhaps put all the tools into one module and all the setting of values into another. The order would be something like:
- import backend tooling to get the `_dispatchable` decorator available (for other backends importing networkx), 
- import configs tooling
- import the module that sets all the values
But perhaps there is a better way.
