### ISSUE TITLE
draw_networkx_edge_labels - node_size is not an accepted key word. 

### ISSUE THREAD

**Issue by bdougherty13** [networkx/networkx#7680]
### Current Behavior

The draw_networkx_edge_labels in the 3.4.1 version receives the error message "TypeError: draw_networkx_edge_labels() got an unexpected keyword argument 'node_size'" when using the node_size parameter as described in the documentation.

https://networkx.org/documentation/stable/reference/generated/networkx.drawing.nx_pylab.draw_networkx_edge_labels.html

### Expected Behavior

The documentation indicates this should be an accepted parameter. 

### Steps to Reproduce

import networkx as nx
import matplotlib.pyplot as plt

#####Create a directed graph
G = nx.DiGraph()

#####Add nodes
G.add_nodes_from(['A', 'B', 'C', 'D'])

#####Add edges
G.add_edges_from([('A', 'B'), ('B', 'C'), ('C', 'D'), ('D', 'A')])

#####Set node sizes
node_size = 400

#####Set edge labels
edge_labels = {('A', 'B'): '10%', ('B', 'C'): '20%', ('C', 'D'): '30%', ('D', 'A'): '40%'}

#####Draw the graph
pos = nx.spring_layout(G)
nx.draw_networkx_nodes(G, pos, node_size=node_size)
nx.draw_networkx_edges(G, pos)
nx.draw_networkx_labels(G, pos)
nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels, node_size=node_size)

plt.axis('off')
plt.show()

### Environment

Python version: 3.10
NetworkX version: 3.4.1

### Additional context
I work in DataBricks. 

Output from reproducible example:
![image](https://github.com/user-attachments/assets/04949b39-893a-452c-9dd9-0a65e158abee)

**Comment by MridulS** [comment]
Hmm, I am not able to reproduce the issue.

I don't have access to databricks and I'm not sure if that could trip up this behavior.

```python
import sys
import networkx as nx
import matplotlib.pyplot as plt

#####Create a directed graph
G = nx.DiGraph()

#####Add nodes
G.add_nodes_from(['A', 'B', 'C', 'D'])

#####Add edges
G.add_edges_from([('A', 'B'), ('B', 'C'), ('C', 'D'), ('D', 'A')])

#####Set node sizes
node_size = 400

#####Set edge labels
edge_labels = {('A', 'B'): '10%', ('B', 'C'): '20%', ('C', 'D'): '30%', ('D', 'A'): '40%'}

#####Draw the graph
pos = nx.spring_layout(G)
nx.draw_networkx_nodes(G, pos, node_size=node_size)
nx.draw_networkx_edges(G, pos)
nx.draw_networkx_labels(G, pos)
nx.draw_networkx_edge_labels(G, pos, edge_labels=edge_labels, node_size=node_size)

plt.axis('off')
plt.show()
print(f'NetworkX: {nx.__version__}')
print(f'Python: {sys.version_info.major}.{sys.version_info.minor}')
```

gives me

![Screenshot 2024-10-16 at 7 02 50 PM](https://github.com/user-attachments/assets/e7c7e0c7-c2a2-42b8-b1d0-c9eebf4e6d8c)

**Comment by bdougherty13** [comment]
I would not be surprised if its due to DataBricks. I have found the platform does not play nicely with other graphing packages as well. Thanks for your help and time.
