### ISSUE TITLE
Deployed documentation failing to load javascript, hangs on views.scientific-python.org

### ISSUE THREAD

**Issue by rossbar** [networkx/networkx#7719]
There is something about the anolytics setup in the documentation that causes the deployed documentation to bork when I visit the site.

Essentially, when I go to `networkx.org/documentation/latest` (or `stable`), I get a `Connecting to views.scientific-python.org...` in the lower left corner of the browser, and an endless loading wheel in the browser favicon. While this is happening, none of the javascript elements on the page work at all (e.g. the searchbar is unresponsive). Similarly, if I load this in a private window where I don't have the pages cached, the theme fails to render properly - though refreshing will cause the theme to load. Ultimately the javascript elements remain unresponsive until the attempted to connection with `views.scientific-python.org` times out (~30 seconds) at which point the banners load and the search bar becomes active.

I'm on Firefox 132 with the uBlock origin extension, though I've seen this behavior on other computers with Firefox without any extensions.

Any ideas @jarrodmillman @stefanv ? I'm happy to provide more detailed debug info!

**Comment by stefanv** [comment]
Hi Ross :wave: 

The call is supposed to look something like this:

```
    <script data-domain="networkx.org" defer="defer" src="https://views.scientific-python.org/js/script.js"></script>
```

From https://www.w3schools.com/tags/att_script_defer.asp:

> If defer is present (and not async): The script is downloaded in parallel to parsing the page, and executed after the page has finished parsing

So, the analytics script *should* not interfere with the rest of the page. I cannot reproduce on my side, but that doesn't say much: we have different DNS, firewall, etc.

In the Javascript itself, it does:

```
var request = new XMLHttpRequest();
request.open("POST", apiUrl, true);
```

which, with the `true` flag, should be an async request.

So, I really cannot see why this should block anything :/

**Comment by rossbar** [comment]
Yeah I have no idea - I mentioned it at the NX community meeting and I don't think anyone else was able to reproduce it either, so it could just be me :upside_down_face: .

**Comment by rossbar** [comment]
Okay - I've at least confirmed it's not just me! I did a quick poll of lab mates and they all had the same issues at `networkx.org/documentation/latest` on both chrome and safari.

**Comment by stefanv** [comment]
Are you able to dig in a little bit to see what freezes it up? I can send you some un-smallified Javascript, if that helps.

**Comment by rossbar** [comment]
> Are you able to dig in a little bit to see what freezes it up? I can send you some un-smallified Javascript, if that helps.

I was trying around a bit more and have noticed that on at least one computer it's working fine. Also - I can access `views.scientific-python.org/networkx.org` now, which I wasn't able to before. I suspect that's the root cause of why networkx.org/documentation/latest is hanging for me (setting aside the fact that the request to views.scientific-python.org is not supposed to be blocking).

**Comment by MridulS** [comment]
Can you also share the logs from the browser console? I assume this hasn't anything to do with your lab network right?

**Comment by rossbar** [comment]
So after trying a few other things, I realized that `views.scientific-python.org` is just entirely unreachable from the campus network - I can't even get a response via `ping`. Therefore, I think my original "javascript is blocking" hypothesis is incorrect - the timeout is happening on the initial GET request to `views.scientific-python.org`.

IMO this is likely a local network conf issue - the only other thing I can think is if there's something strange/misconfigured in the records for `views.scientific-python.org`, but my money would be on a problem with the local network.

Either way, it's certainly not a networkx issue, so I'll close this!
