### ISSUE TITLE
Potential new algorithm to use for finding maximum cliques

### ISSUE THREAD

**Issue by adulau** [networkx/networkx#773]
Hi All,

Do you think that is new algorithm could be useful to add for improving the speed of finding the max cliques?

http://arxiv.org/abs/1209.5818

"The maximum clique problem is a well known NP-Hard problem with applications in data mining, network analysis, informatics, and many other areas. Although there exist several algorithms with acceptable runtimes for certain classes of graphs, none of them are feasible for massive graphs. We present a new exact algorithm which employs novel pruning techniques to very quickly solve for the maximum clique on large sparse graphs. Extensive experiments on several types of synthetic and real-world graphs show that our new algorithm is up to several orders of magnitude faster than existing algorithms for most instances. We also present a heuristic variant that runs orders of magnitude faster than the exact algorithm, while providing optimal or near-optimal solutions. The new algorithms, unlike existing algorithms, are also well suited for parallelization. "

Cheers

**Comment by jfinkels** [comment]
The paper is published now here: https://dx.doi.org/10.1007/978-3-319-03536-9_13 and more recently here: https://dx.doi.org/10.1080/15427951.2014.986778

**Comment by dschult** [comment]
Implemented in #2830
