### ISSUE TITLE
NetworkX handles data inconsistently for pandas>=2

### ISSUE THREAD

**Issue by gboeing** [networkx/networkx#7763]
There seems to be some inconsistency with how NetworkX handles data with pandas>=2.

The main issue here, as described below:
> why would NetworkX inconsistently make the edge `u` a Python int but make the edge `v` a `np.int64`?

### Current vs Expected Behavior

For example, if we run this snippet with Networkx v3.4 and (*old*) pandas v1.5.3:

```python
import networkx as nx
import pandas as pd

# nodes come saved as a path in a pandas series
nodes = pd.Series([333, 555])

# add the nodes and the edge
G = nx.MultiDiGraph()
G.add_nodes_from(nodes)
G.add_edge(nodes[0], nodes[1])

print(G.nodes)  # [333, 555]
print(G.edges)  # [(333, 555, 0)]
```
...the resulting graph nodes are of type int, and the edge is a tuple of ints, as expected. All good.

However, if we run that snippet again, but this time with Networkx v3.4.2 and (*current*) pandas v2.2.3:

```python
import networkx as nx
import pandas as pd

# nodes come saved as a path in a pandas series
nodes = pd.Series([333, 555])

# add the nodes and the edge
G = nx.MultiDiGraph()
G.add_nodes_from(nodes)
G.add_edge(nodes[0], nodes[1])

print(G.nodes)  # [333, 555]
print(G.edges)  # [(333, np.int64(555), 0)]
```
...the resulting graph nodes are still of type int, and the edge's `u` is an int, but the edge's `v` is type `np.int64`. Recent versions of pandas use these numpy types, but why would NetworkX inconsistently make the edge `u` a Python int but make the edge `v` a `np.int64`?

### Environment

Platform: ubuntu 24.10
Python version: 3.11
NetworkX version: 3.4 and 3.4.2 (it appears I cannot install NetworkX>3.4 with pandas>=2)

### Additional context

@LBasara brought this issue to my attention because it's affecting the OSMnx package downstream (crossref https://github.com/gboeing/osmnx/issues/1241). They also provided this screenshot: 

![image](https://github.com/user-attachments/assets/6c65af01-dac0-4f32-978c-f7ab934a4993)

**Comment by rossbar** [comment]
AFAICT this arises from an inconsistency in the return types from pandas whether one is accessing objects with `__getitem__` or iterating over items:

```python
>>> nodes = pd.Series([333, 555])
>>> type(nodes[0])  # accessing the scalar with __getitem__
numpy.int64
>>> type(next(iter(nodes)))  # iterating over series
int
>>> # Or, equivalently:
>>> for n in nodes: print(type(n))
<class 'int'>
<class 'int'>
```

FWIW the pandas behavior is inconsistent with numpy (again, AFAICT):

```python
>>> a = nodes.to_numpy()
>>> a.dtype
dtype('int64')
>>> for i in a: print(type(i))
<class 'numpy.int64'>
<class 'numpy.int64'>
```
As for whether this is intended/desired behavior I can't say. NetworkX is faithfully capturing the types returned by the various operations - the differences in return types appear to come from pandas itself!

**Comment by gboeing** [comment]
@rossbar interesting!

In this example, we access two scalar values the same way, via `__getitem__` (i.e., `G.add_edge(nodes[0], nodes[1])`), yet one ends up in the graph edge as `int` and the other ends up in the graph edge as `np.int64`. What could explain this inconsistency in NetworkX's result when accessing the values the same way as each other?

```python
import networkx as nx
import pandas as pd

# nodes come saved as a path in a pandas series
nodes = pd.Series([333, 555])

# add the nodes and the edge
G = nx.MultiDiGraph()
G.add_nodes_from(nodes)
G.add_edge(nodes[0], nodes[1])

print(G.nodes)  # [333, 555]
print(G.edges)  # [(333, np.int64(555), 0)]
```

**Comment by rossbar** [comment]
> yet one ends up in the graph edge as int and the other ends up in the graph edge as np.int64. What could explain this inconsistency in NetworkX's result when accessing the values the same way as each other?

Because the original nodes are added via `add_nodes_from`, which *iterates* over the nodes to add them to the underlying data structure(s). The code for this is here:

https://github.com/networkx/networkx/blob/32c898dfd76fb384297747a4a053f35c40005618/networkx/classes/graph.py#L634-L649

but it essentially boils down to:

```python
for node in nodes:  # When `node` not already in the graph
    G._adj[node] = {}
```

which is where the difference between how pandas treats iterating/accessing scalars gets injected.

If you were to take the `add_nodes_from` out of the original example, you would get the expected result, i.e. both nodes would be scalars since the node addition *and* edge creation were handled by `add_edge`:

```python
>>> G = nx.Graph()
>>> nodes = pd.Series([333, 555])
>>> G.add_edge(nodes[0], nodes[1])
>>> G.nodes  # Now both scalars, since originally added via `__getitem__`
NodeView((np.int64(333), np.int64(555)))
>>> G.edges
EdgeView([(np.int64(333), np.int64(555))])
```

**Comment by rossbar** [comment]
My initial assessment is that there's nothing to be done about this on NetworkX's side - adding special casing for iterating over pandas objects seems fragile to me. I'd raise it upstream and see what pandas says - if it's an intended feature then it's something that may need to be handled downstream.

**Comment by dschult** [comment]
You should also keep in mind that it has always been this way. Numpy scalars are equal to Python ints if they represent the same value. The reason we see it now is only because NumPy 2.x displays numbers together with their class. So what used to show up as `333` now shows up as `np.int64(333)`.  But they are equal just as they always have been.

**Comment by gboeing** [comment]
@dschult thanks for that insight.

> adding special casing for iterating over pandas objects seems fragile to me. I'd raise it upstream and see what pandas says

@rossbar I agree, and will do. This issue can be closed.

In case anyone else finds this in the future and is interested, I discovered that you can use [numpy.set_printoptions](https://numpy.org/doc/stable/reference/generated/numpy.set_printoptions.html) to prevent this visual inconsistency in the results:

```python
import networkx as nx
import numpy as np
import pandas as pd

# nodes come saved as a path in a pandas series
nodes = pd.Series([333, 555])

# add the nodes and the edge
G = nx.MultiDiGraph()
G.add_nodes_from(nodes)
G.add_edge(nodes[0], nodes[1])

print(G.nodes)  # [333, 555]
print(G.edges)  # [(333, np.int64(555), 0)]

np.set_printoptions(legacy="1.25")
print(G.edges)  # [(333, 555, 0)]
```

**Comment by gboeing** [comment]
Upstream issue at https://github.com/pandas-dev/pandas/issues/60560
