### ISSUE TITLE
The weight function cannot use any property of the minimal path up to a certain node

### ISSUE THREAD

**Issue by rianwouters** [networkx/networkx#7772]
With reference to https://adventofcode.com/2024/day/16, this is a graph in which weights are depending on the previous node, i.e. the weight of edge (u,v) is determined by how you arrive in (u,v).
AFAIKS this can currently not be implemented with the shortest path algorithms, as no information is exposed on the intermediate shortest path to node u.
I believe the pred parameter can be used for this, but it is currently not exposed by the public methods.

### Current Behavior

The weight function cannot be path-dependend

### Expected Behavior

Information should be available to the weight function (or the pred dictionary should be accessible) so that the weight function can depend on it.

### Steps to Reproduce

N.A.

### Environment

N.A.

Python version:
NetworkX version:

**Comment by dschult** [comment]
Hmmmm...  
If the edge weight can change during the search, then will the standard algorithms for shortest path like Dijkstra work? It seems like they rely on the static nature of edge weights.

Perhaps it would be better to reformulate the graph by splitting nodes based on the state data needed to make the paths static.  For the adventofcode-day16 example, each position may have 4 nodes in the graph depending on the direction you are facing. Turning moves you to a different node. But the edge weights are now constant and standard shortest path methods can be used.

**Comment by rianwouters** [comment]
@dschult You are fully right. Please reject this request.
