### ISSUE TITLE
Floating-point error results in error in Preflow-Push Algorithm

### ISSUE THREAD

**Issue by silaas** [networkx/networkx#7775]
## Preflow-Push Algorithm Issue in `relabel()` Function

This issue pertains to the Preflow-Push algorithm, specifically in the `relabel()` function within `preflow_push_impl()` in the `preflowpush.py` file.

---

### Current Behavior

I ran a network simulation utilizing your library, which extensively uses the `max_flow` algorithm based on the Preflow-Push algorithm. Occasionally, though rarely, the `min()` operation in the `relabel()` function encounters an empty set. Specifically, the following expression:

```python
R_nodes[v]["height"] for v, attr in R_succ[u].items() if attr["flow"] < attr["capacity"]
```

returns an empty set. However, according to the Preflow-Push algorithm, this situation should not be possible. If there is excess on a node, it implies that the excess originated from another node via an edge. Hence, there should be an edge in the residual graph that fulfills the condition, ensuring the above set is not empty.

When attempting to reproduce this issue, it proved elusive as it appears to occur randomly. However, during debugging, I observed the following:

- When the issue occurs, the excess is very small, typically in the range of `[1e-10, 1e-11]`.
- All edges leaving the problematic node have `capacity = flow = 0`.

This suggests that the excess is effectively zero but affected by floating-point errors. Consequently, the algorithm fails to recognize this and triggers the error.

To address this, I implemented a rounding mechanism for the comparison at Line 151:

```python
if round(R_nodes[u]["excess"], 8) == 0:
    # The node has become inactive.
    levels[height].inactive.add(u)
    break
```

This modification resolved the issue in my use case.

---

### Expected Behavior

The `relabel()` function should not operate on an empty set under any circumstances, as per the theoretical guarantees of the Preflow-Push algorithm. Proper handling of floating-point errors should ensure this.

---

### Steps to Reproduce

Unfortunately, this issue is difficult to reproduce as it occurs sporadically. A minimal example or controlled simulation has not yet been identified.

---

### Environment

- **Python version**: 3.11.10  
- **NetworkX version**: 3.4.2

---

### Additional Context

I am using a `DiGraph` where each edge is assigned a capacity. Floating-point inaccuracies in flow calculations appear to be the root cause of this issue.

---

**Comment by dschult** [comment]
Thank you for reporting this issue. Floating point inaccuracies are tricky for sure. We run into those problems in many algorithm areas, like shortest_path, min_flow, etc. Anywhere that we want to optimize or find a cutoff. Rounding can work, but is not consistently applicable because rounding can mess up the values if the resolution needed is finer than the rounding.

When possible, and especially in algorithms that avoid division, it is best to use integer values for attributes that are being optimized. If your data is floating point you can effectively round to integers while keeping the desired accuracy by multiplying by a large value and converting to integer. 
```python
old_cap = nx.get_node_attributes(G, "capacity")
new_cap = {node: int(1e8 * val) for node, val in nx.get_node_attributes(G, "capacity").items()}
nx.set_node_attributes(G, new_cap, "new_capacity")
```

**Comment by silaas** [comment]
Ah, I see. Thanks for the explanation!
