### ISSUE TITLE
Error writting stochastic_block_model as a gml file : networkx.exception.NetworkXError: {0} is not a string

### ISSUE THREAD

**Issue by MohamedLEGH** [networkx/networkx#7780]
Hello, I was working with stochastic block model and I tried to write my model into a gml file but it raised an exception. It seems that the attributes of the graph created when building a SBM are not compatible with GML.

### Current Behavior
```bash
Error when writing the GML : 
  File "/usr/lib/python3.13/site-packages/networkx/utils/decorators.py", line 788, in func
    return argmap._lazy_compile(__wrapper)(*args, **kwargs)
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^
  File "<class 'networkx.utils.decorators.argmap'> compilation 10", line 5, in argmap_write_gml_6
    import itertools
             ^^^^^^^
  File "/usr/lib/python3.13/site-packages/networkx/readwrite/gml.py", line 878, in write_gml
    for line in generate_gml(G, stringizer):
                ~~~~~~~~~~~~^^^^^^^^^^^^^^^
  File "/usr/lib/python3.13/site-packages/networkx/readwrite/gml.py", line 786, in generate_gml
    yield from stringize(attr, value, ignored_keys, "  ")
  File "/usr/lib/python3.13/site-packages/networkx/readwrite/gml.py", line 763, in stringize
    yield from stringize(key, val, (), indent, True)
  File "/usr/lib/python3.13/site-packages/networkx/readwrite/gml.py", line 773, in stringize
    raise NetworkXError(f"{value!r} is not a string")
networkx.exception.NetworkXError: {0} is not a string
```
### Expected Behavior
Create a gml file of the graph

### Steps to Reproduce
Here is the code that I used to have the bug:
```python
import networkx as nx

sizes = [1, 10]
probs = [[0, 1.0], [1.0, 0]]
G = nx.stochastic_block_model(sizes, probs)

nx.write_gml(G, "test.gml")
```

### Environment

Python version:  3.13.1
NetworkX version: 3.4.2

### Additional context
I suppose I should convert the attributes into string but I don't know if I need to do it manually or if there is an option to do it when building the graph

**Comment by MohamedLEGH** [comment]
Ok, I added `nx.readwrite.gml.literal_stringizer`
```python
import networkx as nx

sizes = [1, 10]
probs = [[0, 1.0], [1.0, 0]]
G = nx.stochastic_block_model(sizes, probs)

nx.write_gml(G, "test.gml", nx.readwrite.gml.literal_stringizer)
```
It seems to work.
I don't know if it's a good solution. Does someone have experience with this ?

**Comment by dschult** [comment]
That's the right approach.  The stochastic_block_model function provides a graph attribute named `partition` which has a list of sets as it's value. Sets are not automatically taken care of by the default stringizer, so you need to supply a more complicated function -- and in this case, `literal_stringizer` works fine.

Looks like you solved your own question, so I will close this, but you can leave more comments an/or start a new issue if desired.
