### ISSUE TITLE
depth first search, with a cutting condition

### ISSUE THREAD

**Issue by mfrasca** [networkx/networkx#781]
I have written a function based on the `dfs_labeled_edges` function in the `networkx.algorithms.traversal.depth_first_search` module, I think it could be useful to others.

imagine the problem of visiting a network from a given node as long as a specific property is satisfied. for example all nodes that have a "z" coordinate lower than the starting point. or such that the node can be reached along a path where the "z" coordinate is everywhere increasing.

I could not find such a function in the library and I have written it. it's not as beautifully optimized as the original `dfs_labeled_edges` function I modified.

**Comment by dschult** [comment]
Moving this to milestone networkx-future because the PR for this ( #782 )  has that milestone.

**Comment by hagberg** [comment]
See #782.
