### ISSUE TITLE
Algorithms for cographs

### ISSUE THREAD

**Issue by jnyrup** [networkx/networkx#851]
I've written to algorithms for cographs:
   * modular decomposition for a cograph into its corresponding cotree
   * verification of cographs

The code can be seen here:
https://github.com/jnyrup/thisandthat/blob/master/cographs.py

I've tried to make it ready for inclusion in networkX, so please comment on missings, wrongs or other suggestions.

**Comment by jfinkels** [comment]
Please create a pull request so that we can discuss the suggested changes directly on the pull request.

**Comment by jnyrup** [comment]
https://github.com/networkx/networkx/pull/1548
