### ISSUE TITLE
Consistent way to retrieve edges/pairs between Graph and MultiGraph classes

### ISSUE THREAD

**Issue by jamiefolson** [networkx/networkx#852]
Current edge retrieval functions that return a single edge for a Graph or DiGraph return a dict of edges for MultiGraph or MultiDiGraph (e.g. `get_edge_data`, `__getitem__`).  It would be convenient to have some methods that _always_ return a list/dict/iterator of edges, even for Graph/DiGraph, to make Graph and MultiGraph instances more interchangeable.

**Comment by hagberg** [comment]
Closed due to inactivity.
