### ISSUE TITLE
Directed (and weighted) clustering coefficient PR

### ISSUE THREAD

**Issue by FedericoV** [networkx/networkx#859]
Dear all,

I worked on an implementation of the directed and weighted clustering coefficient using this reference:

http://web1.sssup.it/pubblicazioni/ugov_files/303163_PRE_2007.pdf

I wrote test code to confirm that in the weighted undirected, and unweighted undirected case this gives the exact same values as the current clustering coefficient formulas.

There is one point left to be discussed though - currently, clustering coefficient, is defined in two ways (fraction of total edges vs total possible edges, and fraction of total triangles vs total triangles), which, for the undirected case give the same answer.

For the directed case, however, the two definitions differ because of the presence of mutual edges.  The reference I listed explains why right after equation 8.  What normalization should I use?  Cytoscape normalizes by the fraction of possible edges for the directed case, but I don't know if that's an intentional choice.

**Comment by dschult** [comment]
Implemented in  #2943
