### ISSUE TITLE
.gexf graph read/write converts edge start and end dates attributes  to attvalues element

### ISSUE THREAD

**Issue by brycethomas** [networkx/networkx#927]
This pertains to dynamic graphs read/written in the `.gexf` format.  Consider the following:  

``` bash
$ cat dynamic_network.gexf
<?xml version="1.0" encoding="UTF-8"?>
<gexf xmlns="http://www.gexf.net/1.2draft" version="1.2">
    <graph mode="dynamic" timeformat="date">
        <nodes>
            <node id="0" />
            <node id="1" />
        </nodes>
        <edges>
            <edge id="0" source="0" target="1" start="2009-03-01" end="2009-03-10"/>
        </edges>
    </graph>
</gexf>
$ python
>>> import networkx as nx
>>> g = nx.read_gexf('dynamic_network.gexf')
>>> nx.write_gexf(g, 'dynamic_network_out.gexf')
>>> quit()
$ cat dynamic_network_out.gexf
<?xml version="1.0" encoding="utf-8"?><gexf version="1.1" xmlns="http://www.gexf.net/1.1draft" xmlns:viz="http://www.gexf.net/1.1draft/viz" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.w3.org/2001/XMLSchema-instance">
  <graph defaultedgetype="undirected" mode="static">
    <attributes class="edge" mode="dynamic">
      <attribute id="0" title="start" type="string" />
      <attribute id="1" title="end" type="string" />
    </attributes>
    <nodes>
      <node id="1" label="None" />
      <node id="0" label="None" />
    </nodes>
    <edges>
      <edge id="0" source="1" target="0">
        <attvalues>
          <attvalue for="0" value="2009-03-01" />
          <attvalue for="1" value="2009-03-10" />
        </attvalues>
      </edge>
    </edges>
  </graph>
</gexf>
```

At some stage between the graph being deserialized from file with `read_gexf()` and serialized back to file with `write_gexf()`, networkx converts the `start` and `end` attributes of the `edge` element to an `attvalues` element applied to the same edge.

**Comment by mbastian** [comment]
Hi, I confirm that these two examples (before and after) aren't the same and Gephi won't recognize the latter as a dynamic graph. There's two things that can be dynamic in GEXF, the graph structure and the attributes. A dynamic graph structure means that elements (nodes or edges) have a certain time span and would appear/disappear when you manipulate the timeline filter in Gephi. In GEXF, one needs to set `<graph mode="dynamic">` and set `start` and/or `end` attribute directly on the `<node>` or `<edge>`. Dynamic attributes aim to represent a element attribute that varies over time, a stock price for example. To do that in GEXF, one needs to set `<attributes mode="dynamic">`. Each column represented by `<attribute>` within a dynamic `<attributes>` will then by dynamic and `<attvalue>` will accept `start` and `end` attributes. Note that it's possible to have a graph set at `static` and yet have attributes set at `dynamic`. The opposite is true as well: it's possible to have a dynamic graph but with static attributes (i.e. the attribute value will remain the same regardless the timeline filter). Hope this clarifies.
