### ISSUE TITLE
Multigraph Monomorphisms

### ISSUE THREAD

**Issue by mikk-c** [networkx/networkx#948]
I think the multigraph isomorphism matching routine is not working as expected. Consider the following code:

``` python
import networkx as nx
from networkx.algorithms import isomorphism

MG = nx.MultiGraph()
MG.add_edge(0, 1, label = 0)
MG.add_edge(0, 1, label = 1)
MG.add_edge(1, 2, label = 1)
MG.add_edge(1, 2, label = 2)
MG.add_edge(1, 2, label = 4)
MG.add_edge(1, 3, label = 0)
MG.add_edge(2, 3, label = 0)
MG.add_edge(2, 3, label = 3)
MG.add_edge(3, 4, label = 2)
MG.add_edge(3, 4, label = 3)
MG.add_edge(3, 4, label = 4)
MG.add_edge(3, 5, label = 1)

edge_labels = 6
motifs_tocheck = []

for i in range(edge_labels):
   motif = nx.MultiGraph()
   motif.add_edge(0, 1, label = i)
   motifs_tocheck.append(motif)

for i in motifs_tocheck:
   GM = isomorphism.GraphMatcher(MG, i, edge_match = isomorphism.numerical_multiedge_match("label", -1))
   print GM.subgraph_is_isomorphic()
   for isos in GM.subgraph_isomorphisms_iter():
      print isos
```

The generated MultiGraph is represented here:

![toy](https://f.cloud.github.com/assets/3075791/1076310/3962d5f0-14e0-11e3-8dce-7a24e25a92bd.png)

The current output is:

```
True
{1: 0, 3: 1}
{1: 1, 3: 0}
True
{3: 0, 5: 1}
{3: 1, 5: 0}
False
False
False
False
```

What I'd expect as output is:

```
True
{0: 0, 1: 1}
{0: 1, 1: 0}
{1: 0, 3: 1}
{1: 1, 3: 0}
{2: 0, 3: 1}
{2: 1, 3: 0}
True
{0: 0, 1: 1}
{0: 1, 1: 0}
{1: 0, 2: 1}
{1: 1, 2: 0}
{3: 0, 5: 1}
{3: 1, 5: 0}
True
{1: 0, 2: 1}
{1: 1, 2: 0}
{3: 0, 4: 1}
{3: 1, 4: 0}
True
{2: 0, 3: 1}
{2: 1, 3: 0}
{3: 0, 4: 1}
{3: 1, 4: 0}
True
{1: 0, 2: 1}
{1: 1, 2: 0}
{3: 0, 4: 1}
{3: 1, 4: 0}
False
```

In motifs_tocheck there is one single-edge motif per element. The GraphMatcher catches only an isomorphism with labels "0" and "1" because they are the only ones for which there is no parallel edge (between nodes 1-3 and 3-5 respectively). However, I'd expect that all motifs find a match except the last, because label 5 is not present in the graph. "1-2" and "3-4" should be correct matches for a motif composed by a single edge labeled with "2".

**Comment by hagberg** [comment]
Closed due to inactivity.
