### ISSUE TITLE
Louvain Modularity Community Detection

### ISSUE THREAD

**Issue by SuperAce99** [networkx/networkx#951]
## Overview

NetworkX only provides the [K-Clique algorithm](http://networkx.lanl.gov/reference/algorithms.community.html?highlight=community#networkx.algorithms.community) for community detection, despite past efforts to add more options such as [Louvain Modularity](https://en.wikipedia.org/wiki/Community_structure#Modularity_maximization). These efforts should be completed and integrated into the main branch.
## Current Status

Code for louvain community detection has been submitted and partially tested in #239. This code appears to be maintained by @taynaud on [bitbucket ](https://bitbucket.org/taynaud/python-louvain/src/bb73de3cd42c?at=default)

@bjedwards [proposed](https://www.google-melange.com/gsoc/proposal/review/google/gsoc2011/bedwards/1001) to add several community detection methods during Summer of Code 2011. The directed laplaian portion of this was eventually merged via #741, but it appears that this was the only portion of the proposal that was completed.
## Proposal

Merge @taynaud's [python-louvain](https://bitbucket.org/taynaud/python-louvain/src/bb73de3cd42ccb8c2234672b9e472702cd4159d9/community.py?at=default) implementation into Network X.

**Comment by harrismirza** [comment]
Is there any update on this? Seems to be held up but I can't quite work out why.

**Comment by dschult** [comment]
Looks like it is waiting for code to be submitted as a Pull Request.
